### ISSUE TITLE
Add ruins category to the built-in editor OSM

### ISSUE THREAD

**Issue by kikuok** [organicmaps/organicmaps#1005]
Hello, it is very convenient for me to add objects to the openstreet map through your app, but there is no category of ruins (historical ruins) in the built-in search. Can you copy this category from openstreetmaps and add it to the app? I really need this feature and I'm ready to send you donate 5 dollars to add this category in search to add object on openstreetmap. 
 I really hope for you, as it is very important for me. Write the address where I am I can send. Thank you.

**Comment by kikuok** [comment]
Are you going to add this someday? I thought adding a category is easy ... It will also help other users when adding objects

**Comment by biodranik** [comment]
It would be easier if you help, for example, by finding a good open-source SVG icon for it, and by planning on which zoom level this POI should be displayed.

**Comment by kikuok** [comment]
I do not quite understand you, as I am asking you to add this category to the search box to add to the openstreetmap. That is, I create an object on the map in the "ruins" category and it is sent to the server, as it is now the rest of the categories do it. The standard icon itself appears on the map and the zoom too. (Now it is 50 meters. I wish there was at least 100, but I repeat that my request is to add a category to the text list after adding objects to the map.)

**Comment by kikuok** [comment]
For example, the osmand application has source code, but I do not understand why you need a picture if I ask you to add a text category. The picture will update itself and appear if the object appears on the openstreetmaps
![Screenshot_06 08 21-17 24 37_Organic Maps](https://user-images.githubusercontent.com/81811653/128530981-b30dcde6-83ad-4ab5-a499-b746369baecb.png)

**Comment by biodranik** [comment]
Sorry, I assumed they are not present already on the map. Many ruins in OSM have a building associated with them. Is it your case? Or you plan to add only point-like objects, without drawing any building?

**Comment by kikuok** [comment]
Yes, I plan to add point objects exactly like on the map. (foundations are written there). These are the historical foundations of old Finnish farmsteads and the remains of military fortifications, etc. In openstreetmap such the category is called "historical ruins" or simply ruins. This is what I am asking to add to the search which allows me to add objects from your application. Then the objects will have their own picture and it will be displayed together with others sightseeing, which is very good.

**Comment by biodranik** [comment]
There are not just "ruins", it's more complex in OSM, and adding only a generic type may mislead people: https://wiki.openstreetmap.org/wiki/Tag:historic%3Druins
Enabling just the ruins is simple, but there are also "building=ruins", how to explain to other people that some ruined building should not be mapped as historic=ruins?

What type of ruins do you usually add, and why there are so many of them in your area?

**Comment by biodranik** [comment]
There is a workaround though if you have SD-card and can use adb tool. You may try to enable ruins editing in data/editor.config file in this repo, and push this file into the directory with maps. Without SD-card you need root access.

**Comment by kikuok** [comment]
Thank you. So you can add 2 values, if the system allows it: historical ruins and ordinary ruins... Most of all I add historical ruins, as I live in St. Petersburg and in our the surroundings were 2 big wars and there are many Finnish defensive structures, historical fortifications as well as the ruins of Finnish settlements I think people should have a choice of what to apply: just ruins or historical ruins.

I have root rights and xposed, but I do not understand which files and where I need to move. There is no directory "editor.config" in the root folder of the application 
![Screenshot_28 08 21-10 41 33_Solid Explorer](https://user-images.githubusercontent.com/81811653/131210877-29d9c1c4-2cfb-4487-9a2c-47dc9bfc8513.png)

**Comment by biodranik** [comment]
Download this file: https://github.com/organicmaps/organicmaps/blob/master/data/editor.config
Edit it (remove can_add="no" for historic ruins). And place into the `files` directory where maps are located. Then restart the app and check if editor allows you to add ruins.

**Comment by kikuok** [comment]
I kind of did everything right, but nothing came of it. I didn’t see the download button on the link so I clicked on "View raw" and copied the lines from there. I created a file, changed it, placed it in the maps directory, rebooted the application and the phone, but nothing changed ...
![Screenshot_28 08 21-11 44 26_Solid Explorer](https://user-images.githubusercontent.com/81811653/131212606-5005642a-051f-4ac9-be38-6846821a90bb.png)

**Comment by biodranik** [comment]
Is the file at  `…/app.organicmaps/files/editor.config` location?

**Comment by kikuok** [comment]
Yes, I moved it there. Although you said about the folder with maps, and I have it in a separate folder 210703. The file was there and there. And all this is on the memory card.
![20210828_131707](https://user-images.githubusercontent.com/81811653/131214708-b3496ffd-64b1-47d0-9b50-0cbf3d3a3c24.png)

**Comment by biodranik** [comment]
Please restart the app and send us logs if it doesn't work.

**Comment by kikuok** [comment]
Ok. This is logs https://www.mediafire.com/file/97dh5480v83htg0/logcat.log/file
But if you checked and you have added this category, maybe you can send me your editor config file so that I can insert it into the directory ...

**Comment by Misalf-git** [comment]
Works for me on Android when copied to internal storage
`/data/data/app.organicmaps/files/editor.config`
and permissions set to `600`

PS: Nice to know this feature. I've added "Kiosk" in my case.

**Comment by kikuok** [comment]
And for some reason it doesn't work for me. I also issued permits, it's a pity. Please skip your file, maybe it is something different ...

**Comment by biodranik** [comment]
Did you also try in /data/data folder? It should work, I don't see anything suspicious in the log.
Is XML properly formatted and passes validation?

**Comment by kikuok** [comment]
Yes, I moved it to this root folder and set the rights to 600. I don't know what is xml is and how to format it. I just copied this huge text(since there was no button to download the file), created a file and deleted everything you need with a text editor. Perhaps something was wrong. Here is my editor config file. https://www.mediafire.com/file/0vgug898zuxiu9z/editor.config/file

**Comment by Misalf-git** [comment]
The XML is not properly formated.

There is one leading space at the beginning of the file (not sure if that already prevents parsing).

Also, at the very end:
```
    <preferred_types>
      <type id="amenity-restaurant" />
      <type id="amenity-cafe" />
      <type id="amenity-fast_food" />
      <type id="shop-convenience" />
      <type id="highway-bus_stop" />
    </preferred_types>
  </editor>
</mapsme>
r>
</mapsme>
or>
</mapsme>
r>
</mapsme>

```
It should be:
```
    <preferred_types>
      <type id="amenity-restaurant" />
      <type id="amenity-cafe" />
      <type id="amenity-fast_food" />
      <type id="shop-convenience" />
      <type id="highway-bus_stop" />
    </preferred_types>
  </editor>
</mapsme>

```

**Comment by kikuok** [comment]
Can you please send your formatted working editor config file? I have exactly the same as it should be, but in order to send the file, I have to move it to internal memory, but for some reason the lines are added by themselves! And  I don't understand anything in xml and I don't know how to format it and why, without my knowledge, lines and records are added there.

**Comment by Misalf-git** [comment]
Here you go @kikuok 
https://www.dropbox.com/s/3tpkyd1sct6kvd7/editor.config.kikuok.zip?dl=0

**Comment by kikuok** [comment]
@Misalf-git thanks for the help, but nothing has changed. I don't know where the problem is. I tried changing the explorer and used the root explorer, rebooted the phone and app, and even tried it on a different device.

**Comment by Misalf-git** [comment]
@kikuok, do you have OMaps set up to use internal or external storage for maps data?

I believe to remember that modifications to edits.xml (this file is unrelated to this issue) on external storage were not recognized by OMaps without rebooting, until I set it to use internal storage were a simple app restart was enough for the app to pick up the changes.

If that's not it, maybe these screenshots may help you double check how things should look like:
![Screenshot_20210901-141858_Total_Commander.png](https://user-images.githubusercontent.com/72605561/131673128-f187646d-c461-4bd6-a713-cddf7fed7c5d.png)
![Screenshot_20210901-141952_Total_Commander.png](https://user-images.githubusercontent.com/72605561/131673149-f332f08c-e07b-4148-857c-7366fdf9ea9b.png)

**Comment by kikuok** [comment]
@Misalf-git omg omg thank you very much, bro!!!!! Finally it worked out. Indeed, the maps were stored on a memory card. I moved them to internal memory, and then all the categories just disappeared! Then I realized that I was somewhere close. Turns out besides rights 600. Nobody told me (and I forgot) that I need to change the owner of the file! By default, the owner was "root", i changed this to app number just like other files. I rebooted the app and the ruins appeared! So I edited the file again and now I can add the beach to the map as well.

       However, the problem is that I understood everything, but 90% of users do not have root rights and do not understand what to change and don't read this issue, and therefore I often see what is displayed on the map "attraction" although it is in ruins. And so on. And because of this, inaccurate values ​​appear.

 So I can close this issue or leave it open, and in the future there will be more categories for all users for adding to the map? Or maybe I can help by removing the line with negative values ​​for all categories everywhere, so that then I can present it to the developer and so that it will be for everyone?

**Comment by biodranik** [comment]
Let's discuss first, how exactly and what can be improved or changed. It's a risky area: too many types may be unclear for most of our audience (common folks, not geeks), and people may add the wrong types. Too many restrictions will make it harder for those who know what they are doing.

**Comment by kikuok** [comment]
I think people understand the usual categories that should be added. For example, the category cave. There are not so many of these categories, and I do not understand what could be indicated here incorrectly. Of course, you should not add a category of roads and so on, since for this you need to use a professional the editor on the site. (Our Application is not designed for this.) And individual categories such as ruins, kiosk, cave, cape and so on can be added. I think there is nowhere to be confused. By the way, on the map, all the ruins are designated as attractions; I think that there is nothing wrong with that.

**Comment by biodranik** [comment]
This is about the problem with bad edits from unexperienced people. 

Can you show caves as attractions in osm? It looks like a bug.

**Comment by biodranik** [comment]
Then I don't understand your comment above about attractions.

Regarding peaks and caves, they are very rare and are already added on the map. That is one of the reasons why we don't enable them in OM editor.

**Comment by kikuok** [comment]
It's okay, there was no question about it. But still, from time to time I see on the map that someone designated the mountain as a landmark, but this is wrong, but there is no addition in our application categories of mountains. The same thing happens with other categories. If it is difficult, then you do not need to change anything, since this is not a critical problem, but only a useful addition. Thank you for the attention.

**Comment by kikuok** [comment]
Hello. Now it doesn't work anymore? I updated the app and maps and the "ruins" category is disappeared. I downloaded the editor.config file again, set the rights 600 and changed the owner om in the root folder, but this category did not appear. I tried with another category ("beach") and nothing changed either. It is also strange that I then deleted this file altogether, but the standard categories in adding objects remained! 
Maybe you changed some algorithm?

**Comment by biodranik** [comment]
No, we did not change anything. Please check your local setup and make sure that you fully restarted the app.

**Comment by pastk** [comment]
> Hello. Now it doesn't work anymore? I updated the app and maps and the "ruins" category is disappeared. I downloaded the editor.config file again, set the rights 600 and changed the owner om in the root folder, but this category did not appear. I tried with another category ("beach") and nothing changed either. It is also strange that I then deleted this file altogether, but the standard categories in adding objects remained! Maybe you changed some algorithm?

It was fixed in https://github.com/organicmaps/organicmaps/pull/2303/commits/8d38ac19bb5c4bb1d9ddd4c3600950d9883e16f9

**Comment by pastk** [comment]
Ruins had been addable for quite some time
