### ISSUE TITLE
Display social network contact links for POIs

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1016]
For example, contact:facebook or contact:instagram tags are ignored now. The full list is available here:
https://wiki.openstreetmap.org/wiki/Key:contact

**Comment by ccptr** [comment]
Note that it's also fairly popular to tag some of them without the `contact:` prefix (eg. `facebook=*`, not so much with `instagram=*`).

See taginfo for usage comparison:
[contact:facebook](https://taginfo.openstreetmap.org/keys/contact:facebook)
[facebook](https://taginfo.openstreetmap.org/keys/facebook) 
[contact:instagram](https://taginfo.openstreetmap.org/keys/contact:instagram)
[instagram](https://taginfo.openstreetmap.org/keys/instagram)

**Comment by reinhart1010** [comment]
As an OSM contributor I also often put some Instagram links under the `website` tag, since they are also more discoverable on other map clients (Maps.me, OsmAnd, Magic Earth) instead of `contact:`.

**Comment by biodranik** [comment]
There were already several PRs by @strump to solve this issue for Android. This issue can be closed after we integrate UI for iOS.

There is a dedicated instagram field, let's not pollute it with instagram links.
