### ISSUE TITLE
Search: shop shown in map view, but not in the list

### ISSUE THREAD

**Issue by richlv** [organicmaps/organicmaps#1017]
The search results in the list view do not include the closest supermarket - but it it highlighted in the map view (the selected one).
![IMG_9829](https://user-images.githubusercontent.com/112888/128417879-163fadfd-32ea-4d48-af09-ad8e200c1a10.PNG)
![IMG_9830](https://user-images.githubusercontent.com/112888/128417893-f8f73462-a6c9-4638-80e8-c924c39c0680.PNG)

**Comment by richlv** [comment]
The list view in general seems to exclude "Rimi Mini" when searching for "rimi".

**Comment by biodranik** [comment]
Please check, it should be fixed now.

**Comment by richlv** [comment]
Thank you for looking into this, still seems to act weird in 2022.08.23-3.

a) Really not expecting "Riga" to be in the results at all;
b) A bus stop 30km away above all the shops seems weird;
c) The supermarket that's 500m away not visible in the list.
![IMG_5521](https://user-images.githubusercontent.com/112888/190633289-3b7c459e-bc5b-4f6f-b4c2-965909d58fbd.PNG)
![IMG_5520](https://user-images.githubusercontent.com/112888/190633341-30f43669-a321-4c47-8ed5-0f3b9747e30f.PNG)

**Comment by richlv** [comment]
Same with 2022.09.15-2 .
