### ISSUE TITLE
Clicking on address links does nothing

### ISSUE THREAD

**Issue by nwhitehorn** [organicmaps/organicmaps#1020]
On my phone (Android 11 AOSP), when I tap an address (e.g. in contacts), it opens Organic Maps, but does not go to that address. No error messages, no zooming somewhere else, no nothing -- the behavior is identical to just opening the app. I'm not sure how to debug this further, but would be happy to do so if you have suggestions.

**Comment by biodranik** [comment]
This issue is similar to #930 and may be related to #320

**Comment by nwhitehorn** [comment]
Yep, this is a duplicate of #320 . Apologies I didn't find it!
