### ISSUE TITLE
[android]  Hidden "North on Top" (compass) button 

### ISSUE THREAD

**Issue by Yourez** [organicmaps/organicmaps#1022]
While observing a bookmark chosen via the bookmarks list, the button "Nord on top" is hidden by the top panel

**Comment by biodranik** [comment]
One solution is to redesign UI to avoid hiding the compass button at the top right.

Another is to shift button(s) down so the compass button becomes visible while the top panel with a selected bookmark name is visible.

**Comment by Yourez** [comment]
Second one will work. Of course until we have two- and more stringed text.

First one is more elegant.

**Comment by arnaudvergnet** [comment]
@biodranik I think we can close this issue since https://github.com/organicmaps/organicmaps/pull/2081 removed the bookmark toolbar.
