### ISSUE TITLE
Seach function doesn't find a road. The road is in two parts residential and secondary

### ISSUE THREAD

**Issue by wemissyou** [organicmaps/organicmaps#1028]
Hello.  i think there is a weird bug in organic maps, i am not sure if it's a bug in search function or in general, i am from Cyprus and there is a road called Christaki Kranou, which when it starts is a residential road and after becomes secondary road.
The search function of organic maps only finds the residential road and its highlighted only that part of the road. The secondary is not found at all.

Here is the location
https://www.openstreetmap.org/search?query=christaki%20kranou#map=19/34.70676/33.08698

Thank you for the awesome project <3

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.01.09-6-Google
