### ISSUE TITLE
Make it possible to easily distinguish between public and private parking 

### ISSUE THREAD

**Issue by Outlet2048** [organicmaps/organicmaps#1031]
This could he achieved by coloring or desaturating the parking icon based on the access tag

**Comment by wemissyou** [comment]
Also if needs permission to enter, or if you have to pay for it and the price based on data.

**Comment by westnordost** [comment]
Displaying private parkings as normal parkings leads to some confusion, see

https://www.openstreetmap.org/note/2803062#map=19/53.58171/9.95070&layers=N

A user thought it is an error that there is a "parking lot" here, but the situation is mapped correctly. It is a private parking entrance.

**Easy Suggestion**: Just do not show private parkings as parkings at all, as they are irrelevant for most users.

**Comment by biodranik** [comment]
I think the best way would be to drop "access=private" parking from maps data. They don't have any value for our users, and are not attractive to map using the built-in editor.

**Comment by AlertSubject** [comment]
Maybe private parking places that have a name tag associated with them should not be deleted from the map data
Those should be searchable since it's not just a generic parking lot

And while we're at parking, I think it would be great to show more POI information when the user clicks on a parking lot icon
Free / Paid
Cost

**Comment by georg-d** [comment]
Having private parkings not present at all means I cannot see it when I e.g. go there for a business meeting and I got a permission to use the private parking. Also, it means big parkings cannot be used as landmark any more. I'd rather like to see them as parking but with different display, e.g. in a different color (grey?) or in the same color but chequered/plaid red pattern as overlay.

**Comment by dvdmrtnz** [comment]
Done in https://github.com/organicmaps/organicmaps/pull/3896
