### ISSUE TITLE
Doesn't work with replicant 6 on Samsung S3, because of lack of 3D

### ISSUE THREAD

**Issue by millerebonds** [organicmaps/organicmaps#1036]
Hello,

I installed your program and have an error message (it asks openGL), and then it closes.

Replicant doesn't have functional GPS or 3D.

I still use OsmAnd (and don't like it because of it's bloated and slow when I use it).

I look often for alternatives, and was happy to see your new project.

**Comment by biodranik** [comment]
Unfortunately, our rendering engine requires OpenGL, and can't work without it.
