### ISSUE TITLE
New OSM edits spontaneously disappeared

### ISSUE THREAD

**Issue by csidirop** [organicmaps/organicmaps#1049]
Im on vacation and I've added a bunch of new points to OSM via omap. Everything worked as espected: points were on omap and shortly after on osm.

Two days ago I got the newest update (Version 2021.08.05-15-g31e5587-Google) and updated the map data (210729). All edits survived the mapdata update.

Today Ive added a few points and used omap as usually. But suddenly all edits were gone (locally). 

Thats not that big deal, but strange behavour.
The edits.xml file has just the ones I had edited after the disappearing.

**Comment by biodranik** [comment]
As far as I remember, edits that are already present in the downloaded maps (e.g. were successfully uploaded into the OSM before we generated a new map data), are deleted from the local store. So it is not a bug.

**Comment by csidirop** [comment]
Ok, but the generated map is older than my edits. Thats why I even realized it. If the edits where present in the new map there would'nt be an issue.

**Comment by biodranik** [comment]
Then it's definitely a bug. Did you do your edits before or after July 29?

**Comment by csidirop** [comment]
Definetly after the 29th. OSM history says it was after the 5th.

I'm still adding new points and informations via omap to osm. Im copying the edit.xml file every few hours, maybe that can help.

**Comment by biodranik** [comment]
Were disappeared edits successfully uploaded into OSM or not?

**Comment by csidirop** [comment]
Yes they where. At least I haven't noticed any that are missing. But I cant say it for sure. 

The few points from excatly that day where all missing, but was more my fault, because I didn't enauble the mobile data for that day. So they didn't got synced.

**Comment by biodranik** [comment]
So some disappeared points were uploaded, some disappeared points were not uploaded and lost. Correct?

**Comment by csidirop** [comment]
Maybe I was unclear. It seams that all edits were correctly pushed to OSM till that day. 
I believe that every edit I did that day didn't synced, but more because of not setting the allways use mobile data option (I had no wifi). No connection, no sync.

**Comment by biodranik** [comment]
Without connection/sync, bookmarks should anyway survive and not disappear. Please let us know if you can reproduce the issue; it looks bizarre. Did you change the maps storage location in settings btw?

**Comment by csidirop** [comment]
Edits not bookmarks, but yes very strange.
Im still adding new points to the map and hadn't this issue again. I'll do morr test when getting home again. Maybe some encoding issues with greek symbols or some other unsupported symbols which maybe got copied from translation apps.

Anyway I'll updade you.

**Comment by csidirop** [comment]
And all maps are saved on an external SD Card.

**Comment by csidirop** [comment]
It happend again. I did a backup of the edit.xml, notes.xml and icudt69.dat files. The edit file looks corrupted, I'll need to take a deeper look with a pc on my hand.
Anyway I have two assumptions which I'm going to test as soon as I can.

**Comment by biodranik** [comment]
Wow, interesting. Where are these files stored? In internal memory or on SD-card? If the latter, then the card may be corrupted.

**Comment by csidirop** [comment]
Sorry for my late response. Im back home but I didn't found time to sort things out. 
These files are stored under /storage/0000-0000/Android/data/app.organicmaps/files/edits.xml next to the downloaded mapdata where 0000-0000 is my external SD card (See screenshot).
![ScreenshotFolder](https://user-images.githubusercontent.com/43964592/130454249-e4a2d34d-f716-4285-8170-9b1842fe9ee6.png)

I checked card with checkdisk but it showed nothing. To be honest, I don't believe that anyway. It would be very unlikely if the file was written twice on a memory cell that then fails, while the rest of the card works without restriction.

I'll attach the corrupted edit file (edits_errorbackup.xml) and a two days older backup (edits-5.xml). Edit: I can not attach xml-files and for some reason while uploading the zip "Something went really wrong, and we can’t process that file.". Therefore as an alternative: 
![ScreenshotEdits](https://user-images.githubusercontent.com/43964592/130456882-f8e2f6db-1368-455c-b345-19474ffeec68.png)

If someone wants to look at the files I can send them to him.

**Comment by Misalf-git** [comment]
Might it be related to the code page used?
When I copied my edits.xml from Axet's Maps.Me fork to Organic Maps, my edits didn't show up on the map. After I made some edits manually within OM and then inspected the edits.xml that was newly created by OM, I noticed that "german umlauts" (ä, ö, ü) were not properly displayed in my text editor (i.e. "ü" becomes "Ã¼").

**Comment by biodranik** [comment]
@csidirop please send files to android@organicmaps.app

Regarding encoding, interesting. Which device language/locale you have?

**Comment by Misalf-git** [comment]
Me? My locale is set to German, i.e. "Deutsch (Deutschland)".

**Comment by csidirop** [comment]
@Misalf-git I had the same thought, but most of the edits with non ascii greek letters pushed correctly and remained in omap for a while. 

@biodranik I'm using a S7 with [LineageOS 17.1](https://forum.xda-developers.com/t/stable-lineageos-17-1-for-galaxy-s7-build-26.3980101/page-91#post-85454309) (Android 10 Custom Rom) with a [128GB Samsung Endurance Micro SD Card](https://www.amazon.de/gp/product/B07CYFR48N) and using like Misalt-git German as locale.

**Comment by biodranik** [comment]
Thanks! To avoid overwrite, you need to kill the app. If it doesn't work, then the file may be in invalid format (need to check logs).

**Comment by csidirop** [comment]
I think this problem has not appeared since last fall. I have a new phone since February but I think this issue can be closed. Thanks anyway for your help!

**Comment by biodranik** [comment]
So it could be related to SD-card write issues, interesting. Thanks!
