### ISSUE TITLE
[iOS] All text in menu shows as label names [Version 2021.08.04]

### ISSUE THREAD

**Issue by Thomvh** [organicmaps/organicmaps#1054]
After installing Organic Maps on my company iPhone 12 I was pleasantly surprised to see label names and not the actual label text. 

App Version: 2021.08.04
iOS Version: 14.7.1

The problem seems to lay in the fact that my iPhone is set the English (UK) and not English. Therefore it did not have a language file. After switching the app to English and not English (UK) it works perfectly fine.

![IMG_0019](https://user-images.githubusercontent.com/1483055/128825541-fca73d9b-b1c2-4b77-a3cf-3fd743933fa6.PNG)
![IMG_0020](https://user-images.githubusercontent.com/1483055/128825551-9c3aac40-b091-49c7-937d-8f29b3eb2bc2.PNG)

**Comment by biodranik** [comment]
Thanks! The fix is already in AppStore's review and should be available soon.
