### ISSUE TITLE
Long routes may differ significantly when starting point is sifted slightly

### ISSUE THREAD

**Issue by WiseLord** [organicmaps/organicmaps#1071]
The issue was found as a result of a discussion on 4pda [thread](https://4pda.to/forum/index.php?s=&showtopic=1027194&view=findpost&p=108621648)

Let's take two points A to B, at the west of Moscow:

![1](https://user-images.githubusercontent.com/718324/129110527-aeb04999-cd6b-4a7f-8e6f-21571b0ec394.jpg)

The route between them (east A to west B) is a simple line.
But when we try to make a route to the Desnogorsk (quite far from this location), the results differs too much if different starting point is selected.

### A to C:
Full route:

![5](https://user-images.githubusercontent.com/718324/129111015-c71c6c00-5e5a-43b1-ab63-725d0fdfc998.jpg)

Beginning of route:

![3](https://user-images.githubusercontent.com/718324/129111002-93745de3-ce48-4290-9034-e04b421fd269.jpg)

### B to C:

Full route:

![4](https://user-images.githubusercontent.com/718324/129112245-dc50f25b-159e-4439-bc35-a69925fbf4e5.jpg)

Beginning of route:

![2](https://user-images.githubusercontent.com/718324/129112255-b86d1c02-3a76-4404-a682-8063ac8fadff.jpg)

Despite short distance from A to B (1.3 km), the route A-C is done in a strange way - 411 km / 5h26min.
At the same time route from B-C is much better - 350km / 4h47min

So, the problem is that route A to C is much worse then sum of A-B and B-C

The similar behavior is observed when routing in contrary direction (C-A or C-B).

Maps version: 210729
App version: 2021.08.05-15-g31e5587-Google
OS: Android 10 on Redmi 4x

**Comment by WiseLord** [comment]
Addition: such a behaviour is observerd with default options.

Route from A to C becomes "fixed" when the the checkbox "Avoid paid" is selected.

But this is strange: why the application prefers long (in time and in distance) and paid road?

This looks like disabled "Avoid paid" option works like "Prefer paid" that is not correct.

**Comment by biodranik** [comment]
@rtsisyk @vng can you please double check that we do not accidentally invert the "avoid paid roads" option meaning in the code (together with other options)?

**Comment by vng** [comment]
This is weird bug with Cross-MWM routing in first (bad) case, and honest (but time-consuming) routing in second (good) case. The difference here is that starting point in first case is in Moscow MWM, in the second case is In Moscow_West MWM (neighbouring with Smolensk). Will investigate this issue, but Cross-MWM routing still uses some heuristics that can cause such bugs.
