### ISSUE TITLE
[android] Add OrganicMaps to LocationPrivacy recommendations

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#1081]
https://guardianproject.info/apps/info.guardianproject.locationprivacy/

LocationPrivacy by Guardian (preinstalled on CalyxOS) is aware about OrganicMaps, but doesn't recommend it by default:

![Screenshot_20210812-105339](https://user-images.githubusercontent.com/1799054/129159677-e47ed618-06c0-41ba-8897-ed4e791f2483.png)
![Screenshot_20210812-015613](https://user-images.githubusercontent.com/1799054/129159630-c21cbdf8-9db3-486a-94b5-d715cdab3fa7.png)
![Screenshot_20210812-015638](https://user-images.githubusercontent.com/1799054/129159660-aa3fd931-2fb1-43db-9ce4-0a17a6bd606f.png)

We should fix support for Google Maps and OSM.org link and contact Guardian to add our app to recommendations.

Blocked by https://github.com/organicmaps/organicmaps/issues/475

**Comment by meenbeese** [comment]
Can this issue be closed @rtsisyk ? LocationPrivacy is pretty much dead with no updates on Google Play for 7+ years and it is already removed from F-Droid. Seems redundant to add support for a project with an uncertain future.
