### ISSUE TITLE
Routing choses the longer highway in Lebanon

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1097]
OSRM shows correct route: https://map.project-osrm.org/?z=15&center=34.017967%2C35.633340&loc=34.068907%2C35.643715&loc=34.022200%2C35.631881&hl=en&alt=0&srv=0

While OM avoids the faster highway:

![Screenshot_20210813-160047](https://user-images.githubusercontent.com/170263/129420560-00e97aa2-76a4-4402-b7fe-cb4e440660dc.jpeg)

**Comment by vng** [comment]
Well, M51 motorway has manually set maxspeed = 100
A2 which was chosen by the app has only highway=trunk type without maxspeed.

We have maxspeed = 90 in city and 103 out of city defaults for trunk.

Can we ask the author of this issue about ground truth for speed limits and if trunk is an appropriate type here for A2?
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrunk

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.01.09-6-Google
