### ISSUE TITLE
Make a single tap and a long tap on the map discoverable by users

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#1105]
Looks like some users don't know that objects on the map can be selected by tapping on them. And that any empty space on the map can be selected by long-tapping on it.

Let's brainstorm the best way to inform users about these core features.

**Comment by rtsisyk** [comment]
I didn't open this ticket. How does it work? GitHub creates tickets on my behalf? 
Anyway, what should be fixed here? I didn't get the problem.

**Comment by biodranik** [comment]
Brainstorm how to make a long tap discoverable :)

**Comment by besendorf** [comment]
Some apps have a first-use scenario where you force the user to do a few actions and explain what they do like in a video game tutorial. This could be an idea to introduce long tapping.

**Comment by biodranik** [comment]
Maybe recording a simple video and showing a link to it may help :)

**Comment by zyphlar** [comment]
Now that there's apparently no route button, only search and bookmark, it becomes even more important to either create a button for common tasks or give users a first-use guide. Even a highlighted screenshot slideshow can be better than nothing.
