### ISSUE TITLE
[android] Broken place page

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#1106]
![Screenshot_20210815-140020_Organic Maps](https://user-images.githubusercontent.com/1799054/129476266-ea80563f-c496-49a7-9476-cb4a9287638d.jpg)

55.73908, 37.305322

**Comment by biodranik** [comment]
Is it Android 11?

**Comment by rtsisyk** [comment]
Android 11, Samsung S10. I also don't like empty space here.
