### ISSUE TITLE
I encountered a problem using my own generated MWM file via Maps_generator

### ISSUE THREAD

**Issue by gitdhs** [organicmaps/organicmaps#1115]
Can't add map France_Ile-de-France_Paris ( UnsupportedFileFormat ). Probably it's already added or has newer data version.

**Comment by biodranik** [comment]
Please provide more details: is it a computer or phone? Are there any other maps installed? Where did you place the map file?

**Comment by gitdhs** [comment]
> 请提供更多详细信息：是电脑还是手机？是否安装了其他地图？你把地图文件放在哪里？

The cell phone I used, I got it fromhttps://download.geofabrik.de/I downloaded the osm.pbf file and the osm.pbf.md5 file, and generated the corresponding .mwm file using maps_generator, but when I put the file in the phone's storage directory /storage/emulated/0/MapsWithMe/190314 directory, The code shows that the file can be read but cannot be parsed.
![image](https://user-images.githubusercontent.com/31686645/129870345-05507432-3e73-4f4e-bbe7-8cfebbcf1eec.png)

**Comment by gitdhs** [comment]
> 请提供更多详细信息：是电脑还是手机？是否安装了其他地图？你把地图文件放在哪里？

https://download.geofabrik.de/

**Comment by biodranik** [comment]
Organic Maps stores maps data in other folders. Why did you use MapsWithMe folder?

**Comment by gitdhs** [comment]
> Organic Maps 将地图数据存储在其他文件夹中。为什么要使用 MapsWithMe 文件夹？

When I use Maps.Me to download the .mwm file, they put the .mwm file in this folder, so I put my custom files in this folder as well. In fact, I created an app when I was using android studio, and I put the file in the app's directory here, /storage/emulated/0/Android/data/com.example.mapswithme/200920.
It can be resolved using a direct download instead of my custom .mwm file, which is the difference between reading the two files.
![image](https://user-images.githubusercontent.com/31686645/129873577-d729f709-03d6-4ceb-82c6-c4dabcadd5a0.png)
And I can retrieve the results(direct download .mwm file)
![image](https://user-images.githubusercontent.com/31686645/129873824-ec545970-70f1-4817-8a59-deb51c7ffb46.png)

**Comment by gitdhs** [comment]
> Organic Maps stores maps data in other folders. Why did you use MapsWithMe folder?
I'm sorry to ask you questions in this code base, but I'm using https://github.com/mapsme/omim/tree/master/tools/python/maps_generator Generated mwm file, I replaced the downloaded process, so that the local downloaded .osm.pbf and .osm.pbf.md5 were used, and the command python3.9 -m maps_generator --skip="Coastline" --without_countries="World*" was used to generate a .mwm file. But I can't use it. Please give me some advice. Do I need to look at the .poly process?
Thanks!

**Comment by gitdhs** [comment]
I found the problem. The version of the customized mwm file is v11, but the latest version that can be parsed in platform/mwm_version.h is v10. How can I solve this problem?Thanks

**Comment by gitdhs** [comment]
Another question,when i add osm node-id that exceeds the int type and is long int, I cannot generate an MWM file,Can the long int type be supported by modifying the maps_generator script?
Thanks!!!

**Comment by biodranik** [comment]
Looks like you are trying to generate files for another application. Our generator's files work with Organic Maps.

**Comment by gitdhs** [comment]
> Looks like you are trying to generate files for another application. Our generator's files work with Organic Maps.

Yes, I am so sorry but I encountered a problem when generating MWM files. I also use maps_ generator.Can the long int type be supported by modifying the maps_generator script?When i add osm node-id that exceeds the int type and is long int, I cannot generate an MWM file.Because my files are big.
