### ISSUE TITLE
Vegetarian diet mapping handled incorrectly

### ISSUE THREAD

**Issue by FinixFighter** [organicmaps/organicmaps#1118]
When adding a restaurant, users can add the vegetarian cuisine (in the cuisine section). When doing so, OMaps should create a restaurant with the tag "diet:vegetarian=yes" and not with the tag "cuisine=vegetarian", as stated here: https://wiki.openstreetmap.org/wiki/Key:diet:vegetarian (see "Avoidable tags").

I noticed this behaviour because someone commented a changeset I made https://www.openstreetmap.org/changeset/109336939 and pointed out this error. In fact, in the history of the POI https://www.openstreetmap.org/node/8816486981/history you can see the incorrect update in Version n.5.

**Comment by jolesh** [comment]
Or better make a new section "diets" where you can choose the diet type fx vegan and the level (value) "no", "yes" and "only". Then it would be more clear and better with for correct tagging.

**Comment by biodranik** [comment]
The proper implementation should take into account existing cuisines implementation + add diets support. And make it not confusing for users in UI.

**Comment by khao-soi** [comment]
I just stumbled across this issue after checking one of my edits. It creates a lot of mapping mistakes and should get a higher priority.

**Comment by biodranik** [comment]
@vng vegetarian places are popular, is it easy to fix this one?

**Comment by vng** [comment]
- Quick fix is to patch this functions with vegetarian/vegan exception.
string XMLFeature::GetCuisine() const { return GetTagValue(kCuisine); }
void XMLFeature::SetCuisine(string const & cuisine) { SetTagValue(kCuisine, cuisine); }
- Or add full diet support ..

**Comment by khao-soi** [comment]
Oh, it's been a while since my last cpp coding. I gave it a shot anyways:

```
void XMLFeature::SetCuisine(string const & cuisine) {
  if(cuisine.find("vegan")) {
    SetTagValue("diet:vegan", "yes");
  }
  else if(cuisine.find("vegetarian")) {
    SetTagValue("diet:vegetarian", "yes");
  }
  else {
    SetTagValue(kCuisine, cuisine);
  }
}
```

this should work but the vegan/vegetarian will remain in the cuisine string. Is there already a function to remove a certain tag, that I could use?

**Comment by biodranik** [comment]
That's a low-level hack ) Ideally, the code should be changed on the upper level. With this hack, after the next data update, user won't see vegan/vegetarian again.

@vng there is a replacement in data/replaced_tags.txt

**Comment by vng** [comment]
This hack should work. After the data update, user will see vegan/vegetarian because of data/replaced_tags.txt :)

**Comment by TheAdventurer64** [comment]
Any progress?

**Comment by silke** [comment]
Hi, I also noticed that I am creating mapping mistakes when editing with Organic Maps and thus returned to editing with openvegemap which renders maps in quite an unreliable way. It would be great if someone could tell how much work it is to implement the diet tag properly. Whom could I ask about this?

**Comment by vng** [comment]
Hm, I thought that it already fixed ..
The fix: https://github.com/organicmaps/organicmaps/pull/4498

**Comment by biodranik** [comment]
@silke let's double-check, what kinds of mapping mistakes are created by OM?
