### ISSUE TITLE
[android][routing][usa] under some conditions, routes leave and reenter highway incorrectly

### ISSUE THREAD

**Issue by smithed** [organicmaps/organicmaps#1129]
I don't know if there is a more appropriate place to put this feedback (I couldn't find the "report a bug" option mentioned on the contribution guidelines page), but I happened across a condition where organic maps instructs me to leave the interstate, take back roads for 30 minutes, then join back on the interstate.

To demonstrate, first navigate from Albany, NY to Boston, MA. The correct route is to take I-90 the entire way, and organic maps shows the correct route. Then, change the starting point to springfield, MA (another city just off I-90). In this case, it routes you off the highway in "meadowbrook green" and returns you to I-90 at "little alum road" in...literally the middle of nowhere.

Issue existed prior to current version, but persists in current (2021.08.05-15-g31e5587abd-FDroid). 

may be related to #788

**Comment by vng** [comment]
Fixed, please, check on the latest app and data version if possible.

**Comment by smithed** [comment]
Looks good, thank you :)
