### ISSUE TITLE
Hunting stand is sometimes shown as picknick table icon

### ISSUE THREAD

**Issue by chaptergy** [organicmaps/organicmaps#1132]
It seems in some cases, though not all, a hunting stand is displayed with a picknick table icon.

Here is a specific example of one:

[om://04DbKv6thW/Hunting_Stand](om://04DbKv6thW/Hunting_Stand) or https://omaps.app/04DbKv6thW/Hunting_Stand

My app version is 2021.08.05-15-g31e5587abd-FDroid.

![Screenshot-2021-08-19-16-56-28](https://user-images.githubusercontent.com/26956711/130091597-7520728e-64dd-4cd0-8da3-781140f97f6a.jpeg)

**Comment by RicoElectrico** [comment]
This is because of `shelter=yes`. Related to #655

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.01.09-6-Google
