### ISSUE TITLE
Opening Hours Alignment

### ISSUE THREAD

**Issue by ilLekaL** [organicmaps/organicmaps#1136]
Pretty self-explanatory: they should be aligned evenly.
![Screenshot_20210820-115154](https://user-images.githubusercontent.com/67637622/130208393-b74d0d9d-44fb-4a6a-8295-49f835457738.png)

**Comment by csidirop** [comment]
_Hold my beer_
![Screenshot](https://user-images.githubusercontent.com/43964592/130460769-73537627-0ec2-44d3-a573-6df3813d4eee.jpg)

**Comment by biodranik** [comment]
I think the best way to fix it would be some universal formatting in C++ code, returning a string with \n's

**Comment by Kazing** [comment]
Alignement problem corrected by this PR : #1599 

Issue can be closed

**Comment by biodranik** [comment]
Thanks for helping us!
