### ISSUE TITLE
Find different German translation for routing options

### ISSUE THREAD

**Issue by ann0see** [organicmaps/organicmaps#1142]
Thank you for developing this great app! While using it, i was a bit confused about the German translation of routing options 
e.g. here: https://github.com/organicmaps/organicmaps/blob/99384652a8483a127e01193b50078250b7def566/data/strings/strings.txt#L18655

"Einstellung des Umwegs" sounds strange. Maybe something like
"Straßen meiden", "Routeneinstellungen" or similar might describe this option better. I‘m open for suggestions or completely different ideas.

**Comment by biodranik** [comment]
This particular string should tell the user that _some_ of "avoid xxx" settings are already _enabled_. So if the route is wrong or incorrect, the user can change "avoid" settings and maybe get a better route by pressing this button and opening preferences.

So just writing "Routeoptionen" would be misleading. English translation "Routing options enabled" is not perfect also, but is better than just "Routing options".

Any ideas how to improve it?

**Comment by Misalf-git** [comment]
German: "Umweg" = English: "Detour"
I see how this isn't accurate.

Maybe EN: "Routing options enabled" --> DE: "Routenvermeidung aktiv" (which is closer to "Route avoiding active")

**Comment by ann0see** [comment]
@Misalf-git exactly. Routenvermeidung would be an option (but still sounds a bit bulky).

This isn’t the only occurrence though. See

![D78C3B64-E04A-45AA-B618-3F87FB95371F](https://user-images.githubusercontent.com/20726856/130314980-dbfe6719-519b-476d-812b-d0248935e049.jpeg)

**Comment by maciboy** [comment]
How about 
„Routenbeschränkung aktiv“?

**Comment by maciboy** [comment]
Ok, ist seems as if this string is used at least 3 times:
- in settings list (1)
- in settings screen for route options (2)
- on map screen, after a Route is planned (3), HOWEVER there is an additional „aktiv“ appended at the string @biodranik 

So, in my opinion, the string in case 1 and 2, should be „Routenbeschränkung(en?)“ (…en would be plural)
and in case 3, an additional „aktiv“ should be appended, as it is now, so it says „Routenbeschränkung(en?) aktiv“, which points the user to change settings if he wants 

1:
![IMG_0023](https://user-images.githubusercontent.com/19333006/130324674-08ff5665-bf5e-45eb-aece-7e87428353ac.jpeg)

2:
![IMG_0024](https://user-images.githubusercontent.com/19333006/130324714-ac9e0f03-a99b-47c8-accb-5cb3dd520f84.jpeg)

3:
![IMG_0022](https://user-images.githubusercontent.com/19333006/130324746-e35f2754-db7b-4b74-9c4e-2e4c983f40a3.jpeg)

**Comment by Misalf-git** [comment]
Yes, "Routenbeschränkung" makes sense.

**Comment by ann0see** [comment]
Agree. That’s a good solution.

**Comment by biodranik** [comment]
Is everyone ok if I update texts to "Routenbeschränkungen" and "Routenbeschränkungen aktiv"?

**Comment by ann0see** [comment]
Ok by me

**Comment by maciboy** [comment]
I think plural is more consistent with the wording in other languages 🤓🤔

**Comment by Misalf-git** [comment]
If I count to everyone, then I'm OK too.
