### ISSUE TITLE
Download entire countries

### ISSUE THREAD

**Issue by aha999** [organicmaps/organicmaps#1144]
In my Case, Slovenia can be downloaded as 'East' and 'West', but i've never seen that before in a navigation app, and Slovenia is a smaller country, so there's no point in dividing maps.

It would be handier if there were entire countries that you clould click on, and then select parts, or "download all" on the top.

**Comment by rtsisyk** [comment]
https://user-images.githubusercontent.com/1799054/130322600-ad985a3f-764c-4a44-9ce9-581ce06613ee.mp4

Just click on the country. Maps are divided to keep files small.
