### ISSUE TITLE
Search does not find some features in the current viewport

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1147]
This is clearly a bug, and it reproduces with some search queries.

![IMG_9140](https://user-images.githubusercontent.com/170263/130333532-bc108f39-81f0-4835-8239-612ba2cd45fb.png)

![Screenshot_20210821-203122_Organic Maps](https://user-images.githubusercontent.com/170263/130333541-a820da0a-2f8b-4253-bf1e-4062440e108f.jpeg)

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.01.09-6-Google
