### ISSUE TITLE
The app does not propose Ferries in my area even if it's not set to avoid Ferries

### ISSUE THREAD

**Issue by nusstard** [organicmaps/organicmaps#1150]
Every day, I need to cross a river ( La Loire ) with a free ferry offered by the city of Nantes. I did not avoid ferries in the options but the navigation, no matter if I select cycling or walking, avoid the ferry and propose me a very long detour. Try it yourselves: go from Orvault to Le Pellerin (France, near Nantes) by walking or cycling. The app should propose the Ferry and not make a large detour.
![Screenshot_20210822-093632_Organic Maps](https://user-images.githubusercontent.com/74362368/130346622-dac83cf7-e48d-4670-9791-23f7552ee277.jpg)
![Screenshot_20210822-093643_Organic Maps](https://user-images.githubusercontent.com/74362368/130346620-1ba622a7-809c-4a35-b674-4363b94369a7.jpg)
![Screenshot_20210822-093657_Organic Maps](https://user-images.githubusercontent.com/74362368/130346618-e61d414b-fe22-4303-a4aa-51866cd37e19.jpg)

**Comment by biodranik** [comment]
Does OpenStreetMap data have all correct tags/value there? Do other routing apps or services like OSRM work?

**Comment by nusstard** [comment]
![Screenshot_20210822-112007_Magic Earth](https://user-images.githubusercontent.com/74362368/130349719-6fb4dc76-b16c-424a-9bce-52479a37d554.jpg)
![Screenshot_20210822-112000_Magic Earth](https://user-images.githubusercontent.com/74362368/130349723-6dafbe6a-7d90-4e50-ba2f-3eb4178a2211.jpg)
On MagicEarth which uses OSM and Waze/Gmaps, the routing propose this.
By car, the route is only faster when there is traffic on the other (happens a lot).
The ferry goes every 5 minutes from one side to the another.
The data indicate that the point is considered as a ferry.

Thanks for your answer.

**Comment by nusstard** [comment]
You can also see that other navigation app does not propose the longer route but propose the three possible way to pass with ferries to the three available ferry passway offered by the city.

**Comment by biodranik** [comment]
Hm, so the route via ferry may be considered "not the best one" by our algorithm. Then this issue is more about "propose alternate routes".

**Comment by nusstard** [comment]
It should be the first route since it's 10 km less than the other. By cycling, it's not even worth comparaison.
Note that, it take less than 5 minutes to cross by ferry. And even considering that, look what Organic Mpa do:
![Screenshot_20210822-142808_Organic Maps](https://user-images.githubusercontent.com/74362368/130355187-304ff9f6-6d4a-4123-9336-de91fb397a5c.jpg)
![Screenshot_20210822-142801_Organic Maps](https://user-images.githubusercontent.com/74362368/130355188-631c3363-e8d1-46ae-ac24-a039a3834792.jpg)

**Comment by biodranik** [comment]
Great, thanks for the details! We'll take a look.

**Comment by vng** [comment]
Thanks for the example. We have several serious problems here:

- auto mode doesn't route on ferry if it has opening hours (still not sure ?!)
- bicycle and pedestrian mode doesn't route on motor_vehicle allowed ferry even with foot/bicycle=yes.
- if ferry terminal is connected with continuing roads by **area** highway=pedestrian only (Istanbul), pedestrian/bicycle routing is failed

**Comment by vng** [comment]
UPD. So, the graph is ok, should tune ferries default timing.

The long route:
CalculateSubrouteJointsMode() Result route weight: (0, 0, 0, 5062.04, 0)
DoCalculateRoute() Route length: 29088.4 meters. ETA: 6252.85 seconds.

The short route with intermediate point in "Ferry Basse-Indre"
CalculateSubrouteJointsMode() Result route weight: (0, 0, 0, 3417.81, 0)
CalculateSubrouteJointsMode() Result route weight: (0, 0, 0, 2166.45, 0)
DoCalculateRoute() Route length: 18328.6 meters. ETA: 5585.35 seconds.

Algorithm's weight is bigger in the short route, but the final ETA is smaller.

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.01.09-6-Google version
