### ISSUE TITLE
A bit subotimal claims on donate page - "new" "unique"

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#1152]
> Organic Maps promotes the new ideology, which is unique on the market

1) it is not really new one

2) as far as I know Osmand is also without listed issues (though adding "100% free, without paid features" to the list would make it true and is worth adding anyway)

https://organicmaps.app/donate/

**Comment by biodranik** [comment]
Thanks, a great suggestion, which is completely true!

**Comment by biodranik** [comment]
Should be fixed now.

**Comment by matkoniecz** [comment]
I would argue that "new" is not so new (see say GNU / FSF / Stallman )

> OSMand has inapp-purchases though.

Yes, though AFAIK it is not qualifying for listed "bad" parts (except paying itself). And there is also F-Droid version of Osmand, with all this features enabled.
