### ISSUE TITLE
Map is not centered

### ISSUE THREAD

**Issue by lentyay** [organicmaps/organicmaps#1153]
When i send location link from my app to Organic Maps app, map is not centered and marker appears somewhere outsite viewport. I tryed both coldstart and hot start and 2 types of deeplinks:
`om://map?v=1&ll=lat,lng`
and
`om://geo:lat,lng`

**Comment by RedAuburn** [comment]
@lentyay can you stil reproduce this issue?

**Comment by lentyay** [comment]
Actually, i moved to other maps API years ago, so i can't reproduce.

**Comment by lentyay** [comment]
I'm not using deeplinks anymore in my app.

**Comment by Jean-BaptisteC** [comment]
Not reproduced on the latest version (2024.01.09-6-Google)
