### ISSUE TITLE
Too simple to remove a bookmark

### ISSUE THREAD

**Issue by aha999** [organicmaps/organicmaps#1173]
I mistakenly removed a bookmark by selecting "bookmark" and with no queations it was removed.

I propose that when a bookmark is made, you change its edit menu word "Bookmark" to "Remove Bookmark" and if you select it, a confirmation window should pop up, asking you if you are sure.

**Comment by biodranik** [comment]
That's a bug, on iOS, the same button is named "Save" and changes to "Delete". So the easier fix would be to make it obvious for users.

Probably also it makes sense to ask for a confirmation if a bookmark has some complex description. But it may make the removal more complex for some users.

**Comment by keunes** [comment]
> Probably also it makes sense to ask for a confirmation if a bookmark has some complex description

Sounds like a good idea. I wouldn't want to confirm removal all the time. When on holiday I add and remove pins ('favourites') all the time, e.g. to store a restaurant spotted for later that day.

**Comment by pastk** [comment]
A couple more ideas to brainstorm:
(all approaches share an idea that the deletion should be a quick one-tap process like it is now)

1. When a bookmark is deleted another tap on the star button will bring it back (not just re-create, but revert deletion, so no info is lost). If a user de-selects the current point then the bookmark is lost indeed.
2. Like previous, but add a visible 3-5 seconds "undo timer" in place of the star button (e.g. see how undo works in telegram when deleting chats).
3. Put all deleted bookmarks into a "trash bin" accessible from the bookmarks screen from where they could be restored.
