### ISSUE TITLE
Voice Navigation stops music playback

### ISSUE THREAD

**Issue by besendorf** [organicmaps/organicmaps#1174]
On 2021.08.14-4 on Android (GrapheneOS without GApps) voice navigation stops music plaback. This shouldn't be the case as listening to music while driving is a pretty common use-case.
This might be related to #573 but I didn't look into the Android Sound playback APIs so Im not sure.

**Comment by biodranik** [comment]
No, it could be related to #901
@Endem10n can you please help?

**Comment by syborgxx** [comment]
My music players (Pandora and Foldplay) were paused by Organic Maps.

**Comment by biodranik** [comment]
LineageOs (Android 11), music played via Bluetooth pauses on voice directions.

**Comment by biodranik** [comment]
Also confirmed to happen on Samsung Galaxy A40, Android 11.

**Comment by edzob** [comment]
also linked to https://github.com/organicmaps/organicmaps/issues/1433 ?

**Comment by edzob** [comment]
@biodranik I did some testing. Audio instructions of OM worked during listning to Audible. It only stops when the screen is turned-off. Then screen is off the sound of audible (or Spotify/Castbox) do continue, that caused the mixup I think.. Not yet searched for an issue on voice navigation when screen is off.
