### ISSUE TITLE
Please display key cutters/locksmiths

### ISSUE THREAD

**Issue by andrewshadura** [organicmaps/organicmaps#1194]
See https://wiki.openstreetmap.org/wiki/Tag:craft=key_cutter for the details

**Comment by dvdmrtnz** [comment]
Material icons has a couple of "key" icons that are okay:

https://fonts.google.com/icons?selected=Material+Symbols+Outlined:key:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=key&icon.platform=web
![](https://github.com/organicmaps/organicmaps/assets/47610359/d98c5ccf-36d6-48be-a879-0cc62867e659)

https://fonts.google.com/icons?selected=Material+Symbols+Outlined:vpn_key:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=key&icon.platform=web
![](https://github.com/organicmaps/organicmaps/assets/47610359/23619011-16dd-4f6f-a12f-88a01e990492)

**Comment by dvdmrtnz** [comment]
Proposal:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/f2807691-f787-46b3-bf0d-2d651a28e4df" width="36"/>
