### ISSUE TITLE
Address is not generated for a building in multipolygon relation

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1198]
In the OM there is no address for this building, but it's present in OSM data: 
 https://www.openstreetmap.org/relation/10358170

**Comment by vng** [comment]
This relation is deleted. Can't find another one here to reproduce a problem.

**Comment by Jean-BaptisteC** [comment]
Gift :)
https://www.openstreetmap.org/relation/812638
I have created request on overpass https://overpass-turbo.eu/s/1pa7

**Comment by vng** [comment]
Got it, thanks! The house number is visible, so there is something wrong with PP.

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.01.09-6-Google version
