### ISSUE TITLE
[render] Invalid road ref placement

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#1202]
M2 should be on the orange road.

![image](https://user-images.githubusercontent.com/175612/131219029-0bfda7bb-d687-446c-a0bf-bf96f18752ca.jpeg)

**Comment by Jean-BaptisteC** [comment]
Could you please share link to OSM ?

**Comment by RicoElectrico** [comment]
https://www.openstreetmap.org/#map=16/53.8924/28.0300

**Comment by vng** [comment]
Added note, lets the locals do the job :)
