### ISSUE TITLE
Route from Munich to Byala (Bulgaria, on the Black Sea) fails

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1206]
Remove all maps downloaded in-between. Select Munich as from, Byala as to, and build a route. Accept and download regions. Build the route again. It should work, but the "Route planning failed" message is displayed.

**Comment by vng** [comment]
Also check Zurich -> Kiev.

**Comment by vng** [comment]
UPD: После #1626 маршрут строится
![image](https://user-images.githubusercontent.com/175612/143733532-561bb8d8-fc18-4e7e-ba65-f69670ccb815.png)
![image](https://user-images.githubusercontent.com/175612/143733540-a16a3629-2ad5-49e4-b06f-6322d0bd21cd.png)

**Comment by vng** [comment]
UPD: Zurich -> Kiev:
![image](https://user-images.githubusercontent.com/175612/143734839-76837706-b092-4e1f-bde7-a02f4c591c5f.png)
![image](https://user-images.githubusercontent.com/175612/143734841-956621bf-3ad8-446b-a65c-e22db38d9d1c.png)
