### ISSUE TITLE
amenity=school is shown as a point instead of an area

### ISSUE THREAD

**Issue by ghost** [organicmaps/organicmaps#1221]
[Bug Report]
Organic Maps displays/renders amenity=schools as a point/node instead of rendering it as an area.
![OSM](https://user-images.githubusercontent.com/82209775/131560444-b6eb01fd-47bf-43c0-8a3f-52e8aa665aba.png)
How it is correctly rendered on OpenStreetMap

![organicMaps](https://user-images.githubusercontent.com/82209775/131560679-b676ecec-4d69-4bc3-a392-b5a54411c906.png)
How it is incorrectly rendered as a point in OrganicMaps

**Comment by biodranik** [comment]
Can you please provide a link to the OSM school on the screenshot?

**Comment by starwatcher11** [comment]
> 
> 
> Can you please provide a link to the OSM school on the screenshot?

I'm sorry but I'd prefer not to, for privacy reasons.
All I can say that might be helpful is that when in ID Editor, I create "School Grounds" (amenity=school) as an AREA (NOT a point), in OSM it appears correctly, but on Organic Maps it will appear as a point.
This issue doesn't happen only with one instance of a "School Grounds" but all of them that can be found on the map in my country.

**Comment by pastk** [comment]
Looks like same story with `amenity=kindergarten` https://www.openstreetmap.org/way/66668858

**Comment by pastk** [comment]
Related to #2324

**Comment by dvdmrtnz** [comment]
As far as I know, this happens on all `amenity=school`. Example:

https://omaps.app/4n_T5I8zcU/Instituto_de_Educación_Secundaria_Julio_Caro_Baroja

![](https://user-images.githubusercontent.com/47610359/161068410-38ca27ef-018a-414a-b5a0-f453f024fdf0.png)


https://www.openstreetmap.org/way/51155332#map=17/42.81859/-1.66050

![](https://user-images.githubusercontent.com/47610359/161068427-46750bed-5757-4dbb-85b5-72df36c630c9.png)

**Comment by vng** [comment]
Area style should be enough.
