### ISSUE TITLE
leisure=nature_reserve background makes contours & highway~path|track hard to see

### ISSUE THREAD

**Issue by 1papaya** [organicmaps/organicmaps#1222]
![photo_2021-08-31_23-00-04](https://user-images.githubusercontent.com/25945912/131576682-d316a2a2-fa24-4a2a-a534-8ca0a0897b25.jpg) ![photo_2021-08-31_23-00-11](https://user-images.githubusercontent.com/25945912/131576687-b2e24d48-c8fe-48be-a90a-b8c792ea3e01.jpg)

As reported by a few users on Telegram, with the green diagonal lines used as fill for `leisure=nature_reserve` /  `boundary=natural_park` it becomes quite hard to see contour lines and tracks/paths at certain zoom levels.

Here is the style definition in the mapcss
https://github.com/organicmaps/organicmaps/blob/f02f23d265fc34c5b86f3bd134c3ef4b7a5699ef/data/styles/clear/include/Basemap.mapcss#L301-L303

In my opinion the ideal would be to display a border around the polygon but from what I can tell that's not supported because I see no other polygon outlines in OMaps, only fill's. So my suggestion would be to lower the fill opacity or somehow make the lines more spaced out or thinner. Wish I could help more, but I'm lost on what `fill-position: background` means I can't find any info about it in the code or online. Thanks again for OMaps!

**Comment by pastk** [comment]
> 
> Here is the style definition in the mapcss
> 
> https://github.com/organicmaps/organicmaps/blob/f02f23d265fc34c5b86f3bd134c3ef4b7a5699ef/data/styles/clear/include/Basemap.mapcss#L301-L303
> 
> In my opinion the ideal would be to display a border around the polygon but from what I can tell that's not supported because I see no other polygon outlines in OMaps, only fill's. So my suggestion would be to lower the fill opacity or somehow make the lines more spaced out or thinner. Wish I could help more, but I'm lost on what `fill-position: background` means I can't find any info about it in the code or online. Thanks again for OMaps!

Hatching fill is harcoded for these types at the moment.
Polygon borders are supported by the rendering engine (e.g. `casing-width: 1;casing-color: @building_border;`) but looks like its hardcoded only buildings use it.
So the only quick option for now is to reduce fill's opacity, see #1979
