### ISSUE TITLE
[android] Visible delay before opening Settings screen

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1230]
Something takes too much time on the main thread before showing settings dialog. Need to profile, fix, and make it more smooth.

**Comment by Jean-BaptisteC** [comment]
I have doing some tests, i didn't have see delay when i open settings screen

**Comment by biodranik** [comment]
Do you see any warnings or strange lines in logs?

**Comment by Jean-BaptisteC** [comment]
Not warnings in logs

**Comment by biodranik** [comment]
It could be related to slow SD-cards. Can someone test it on a cold start, on an older device with SD-card?

**Comment by zogmn** [comment]
Tested with 5 year old Android phone, running Android 10 and SD card, with OM 2024.09.19. No noticable delay when opening Settings screen.

**Comment by RedAuburn** [comment]
thanks for testing @zogmn, closing as unreproducible for now
