### ISSUE TITLE
[drape] Rare street names and oneway arrows drawing.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#1241]
Some complicated variants:
https://omaps.app/8y5hklsTK8/Hasan_Amir_Sokağı
https://omaps.app/8y5hklsDNK/Rüştiye_Sokağı

Tons of space to draw street name, but the line is empty and you should scroll far away to see it ..

The same with oneway arrows, like here:
 https://omaps.app/8y5hkhcEue/Nene_Hatun_Sokağı

**Comment by vng** [comment]
One more good example is here: https://www.openstreetmap.org/way/181133407#map=19/40.98341/29.02231

I wasn't able to see street name at all on iPhoneX.

**Comment by pastk** [comment]
Those street names are displayed fine on my device. Thanks to recent priorities refactoring,

The last example is the trickiest, probably the app chooses a spot at the street corner to display its name and then fails. However its possible to see the name at z20 in one place :)
