### ISSUE TITLE
HK subway

### ISSUE THREAD

**Issue by cffung** [organicmaps/organicmaps#1242]
How to report or suggest the subway update ?

**Comment by biodranik** [comment]
What is the mistake? Is it already fixed in OSM?

**Comment by cffung** [comment]
OSM updated but Organicmap not

**Comment by biodranik** [comment]
In which city? How can we test and check that the issue is fixed?

**Comment by cffung** [comment]
Hong Kong, please refer to the official website
http://www.mtr.com.hk/en/customer/services/system_map.html

**Comment by dikkechill** [comment]
Hi cffung, 
There are a number of issues with the current Hong Kong OpenStreetMap data, hence the subway map doesn't show in OrganicMaps at the moment.
You can find a list of the issues here: https://cdn.organicmaps.app/subway/china.html under Hong Kong.
