### ISSUE TITLE
Complex opening times impossible to edit

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#1247]
The garden *[Jardin du sacré coeur](https://www.openstreetmap.org/way/60091397)* in Toulouse, France, has some complex opening times to account for the season.

Organic maps is unable to correctly display this information and the editing screen is empty.

I don't know OSM well enough to tell if the date format is valid, but the app should at least let the user edit the time to correct it if the entry is invalid.

Here is the format:

```
Nov-Jan 07:45-18:00; Feb 07:45-18:30; Mar 1-15 07:45-19:00; Mar 16-31 07:45-19:30;Apr 07:45-20:00;May 07:45-20:30;Jun-Aug 07:45-21:00;Sep 1-15 07:45-20:30; Sep 16-30 07:45-19:30;Oct 1-15 07:45-19:00;Oct 16-31 07:45-18:30
```

And here is a video:

https://user-images.githubusercontent.com/80701113/132094410-45c2db1b-2414-4d21-89ce-a619b264340f.mp4

# System
- **OS:** `Android 9`
- **Organic Maps version:** `2021.08.14-4-F-Droid`
- **Data Version:** `210729`

**Comment by biodranik** [comment]
Thanks! There should be some bug in our code. Opening Hours IsValid says that it's ok though…

**Comment by arnaudvergnet** [comment]
What's weirder is that I get a blank window, but there seems to be some TextEdit components in the screen as the keyboard opens when I click

**Comment by kudlav** [comment]
Hi,
I am facing to the same issue with the expert mode.
Event when I try to edit simple opening hours `Mo-Su 11:00-24:00` or POI without opening hours.

1) Open POI with or without opening hours
2) Edit, Edit opening hours
3) Make the input box blank
4) Type "c"
5) The ui glitch appears
6) You can continue typing and when you type "closed", it turns back into normal UI and the value can be saved.

So it works but cannot see what typing.

[logs.zip](https://github.com/organicmaps/organicmaps/files/7135843/logs.zip)
![Screenshot_20210909-123825_Organic Maps](https://user-images.githubusercontent.com/11516259/132672054-20e75f5e-f505-4e10-ae88-e2a48189c438.png)
![Screenshot_20210907-121318_Organic Maps](https://user-images.githubusercontent.com/11516259/132672086-1c57b2cf-6bc2-47cd-a636-a0ca0283ec1e.png)

**Comment by anibyl** [comment]
Same issue when trying to **add** this tag to a place. It says 24/7 by default, any edit breaks the view. Validation should be performed while confirming, I think.

**Comment by mnalis** [comment]
> Same issue when trying to **add** this tag to a place. It says 24/7 by default, any edit breaks the view. Validation should be performed while confirming, I think.

I agree. Or just make a red outline around input field if it is invalid (instead of hiding complete input field).

**Comment by endim8** [comment]
another test case (with only months): [Greenwich park](https://www.openstreetmap.org/way/4483968)

`opening_hours = Oct-Feb 06:00-18:00; Mar-Apr,Sep 06:00-20:00; May-Aug 06:00-21:00`

![signal-2022-11-15-104416_002](https://user-images.githubusercontent.com/26939824/201900505-a067e3d1-bf48-4511-a656-584dc9a02911.png)

**Comment by dikkechill** [comment]
Another example with date ranges and comments. It's not nicely displayed in the app.
Editing seems possible though.
```
opening_hours = Nov 01-Mar 31 Mo-Fr,Su 09:00-19:00 "Online tickets only"; Nov 01-Mar 31 Sa 09:00-21:00 "Online tickets only"; Apr 01-Oct 31 Mo-Su 09:00-22:00 "Online tickets only"
```
![IMG_20230702_182210](https://github.com/organicmaps/organicmaps/assets/45293195/ef72a21c-00c2-4e7d-a7b7-9996d7a6467c)

OrganicMaps version 2023.06.04-13-FDroid (Android)

**Comment by Jean-BaptisteC** [comment]
@RedAuburn can you retry, I'm not able to reproduced on latest version

**Comment by RedAuburn** [comment]
> @RedAuburn can you retry, I'm not able to reproduce on the latest version

which bit? the times are still not parsed into a table, but editing is possible (it opens in the text-only advanced editor)
