### ISSUE TITLE
Farmlands color is similar to parking spaces

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1250]
Farmlands make it harder to see parking places on the map. So it would be great to choose a different color for either farmlands or for parkings.

Introduced by #1125 

![Screenshot_20210904-115217_Organic Maps](https://user-images.githubusercontent.com/170263/132103931-a6bcb631-5a6a-4ff5-af62-103a31d3fb90.jpg)
![Screenshot_20210904-115222_Organic Maps](https://user-images.githubusercontent.com/170263/132103933-a5626533-a5b8-4be0-b2e5-8f47214d4f29.jpg)

**Comment by biodranik** [comment]
@pastk didn't we fix it already?

**Comment by pastk** [comment]
After #2134 the colors are more distinct indeed.

"After" is on the right side, parking fills are smaller squares at the edges:
![footway](https://user-images.githubusercontent.com/18434508/154532930-76f9f905-a7e2-4736-b819-f5253ac74ab9.svg)


Though they are similar enough to be confused still.
![Screenshot_1651260068](https://user-images.githubusercontent.com/18434508/166056994-8b155813-8720-464b-91e9-dcc8972d714f.png)

**Comment by RedAuburn** [comment]
i think it's different enough to close now
