### ISSUE TITLE
Do not draw leisure=beach icon for natural=beach

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1253]
[The natural=beach tag](https://wiki.openstreetmap.org/wiki/Tag:natural=beach) is used to mark a loose geological landform along the coast or along another body of water consisting of sand, gravel, shingle, pebbles, cobblestones or sometimes shell fragments etc.

For seaside resorts use leisure=beach_resort for the boundary of the resort, which may include accommodation and other facilities and which may include one or more actual beaches. For areas of sand that are not beaches, use natural=sand or surface=sand (or a more specific tag describing the area).

![telegram-cloud-photo-size-2-5294280399528244314-y](https://user-images.githubusercontent.com/170263/132118327-424b41cd-624f-4b96-905e-0b7edb43580f.jpg)

**Comment by Phantom63rus** [comment]
![Screenshot_2021-09-15-01-49-50-046_app organicmaps](https://user-images.githubusercontent.com/25801542/133405306-eed2af69-ed48-49de-8a99-a7d5dc57f189.jpg)
This is wrong.

**Comment by vng** [comment]
I removed "umbrella" icon from beach and seems like it's not consistent now. We draw forest, park, garden icons, but not beach now ..

**Comment by biodranik** [comment]
We may need an icon for a beach if it has additional meta info (opening_hours, contacts, etc.)
