### ISSUE TITLE
addr:interpolation is not supported in search and renderer

### ISSUE THREAD

**Issue by brandoncote** [organicmaps/organicmaps#1256]
There are 2M+ ways with interpolation addresses in OSM

https://wiki.openstreetmap.org/wiki/Addresses#Using_interpolation

https://taginfo.openstreetmap.org/keys/addr:interpolation

**Comment by endim8** [comment]
I was about to create an issue for this, then found that there's one already 😅 Here's my description anyway:

>If a POI has the tags 
>
>`addr:housenumber=1-5` + `addr:interpolation=all | odd | even` + `addr:street=Cedar Avenue` 
>
>Searching for `1 Cedar Avenue` will return the correct POI, but `2 Cedar Avenue` will only return the street.
>
>Something to keep in mind for implementation is the importance of `addr:interpolation`. The usage of this tag explicitly states >that the house number is a range, as opposed to being a singular house number with a dash.

**Comment by Growebis** [comment]
still no support? a bit of a deal breaker especially here in canada where they seem to be used a lot in OSM

**Comment by biodranik** [comment]
@vng can we patch it in the generator and automatically calculate/bind house addresses in our currently supported way?

**Comment by biodranik** [comment]
#606
