### ISSUE TITLE
Symbols and synonyms mess with search

### ISSUE THREAD

**Issue by zyphlar** [organicmaps/organicmaps#1262]
If you accidentally search for a place without apostrophes that may easily be confused as a place with apostrophes, like "Michael's" or "Barne's & Noble," or switch out the ampersand as is "Barnes and Noble," none of the desired results appear. Some fuzzy search in these cases would help greatly.

**Comment by biodranik** [comment]
Can you please clarify your case with some examples from OM? As far as I remember, all apostrophes are stripped. @vng ?

**Comment by vng** [comment]
Well, we strip apostrophes, but the problem is more complicated here.
Removing ' "Michael's" is indexed as 2 tokens: "Michael" and "s". Our search can/should process possible errors, so "Michael**s**" token also should match this POI (treating "s" as error), but I'm not sure here.

For the best experience (after refactoring, I hope), "Michael's" should be indexed as "Michael" and "Michael**s**" tokens

**Comment by zyphlar** [comment]
Yeah that would help. Without revealing my location, these are national US chains so you may expect to find many US results for the "Michaels" craft shop when searching for "Michael's" but because of what vng said, you don't. Maybe all you find is "Michael's pizza" etc.

**Comment by biodranik** [comment]
@vng the easiest approach: do not strip apostrophe if it's in the middle of the word.

**Comment by zyphlar** [comment]
I do generally like ignoring apostrophes because likewise there's the opposite case of "Macy's" which many people will type as "Macys" -- treating symbols as interchangeable or optional is probably best

**Comment by vng** [comment]
@zyphlar Could you please clarify your search context, e.g. where is you current viewport, and what result did you expect to get?

I did some experiments and seems like apostrophe works well. Probably, there are other kind of bugs like bad results ranking:
So, I have "New York" downloaded and current viewport is above it:

![photo_2021-09-08 14 21 10](https://user-images.githubusercontent.com/175612/132501103-8d3d391c-e976-4332-b679-1c21492dd6a7.jpeg)
![photo_2021-09-08 14 21 14](https://user-images.githubusercontent.com/175612/132501108-ad89561e-c8c1-4928-bbca-addd93f5f614.jpeg)
![photo_2021-09-08 14 21 17](https://user-images.githubusercontent.com/175612/132501111-b01c2104-d7de-478f-91c6-97eea81dee69.jpeg)

Also "Barne's & Noble" is mapped like "Barnes & Noble" in OSM.

**Comment by vng** [comment]
Here is "Michael's" shops (don't know are they craft or not)
![image](https://user-images.githubusercontent.com/175612/132502419-92058640-b654-48a6-96c6-e7d17abeec4a.png)

**Comment by zyphlar** [comment]
I was trying to not divulge my location but fine. Most of your spelling or punctuation is wrong or backwards.


Demonstrating frustrating failure mode, incorrect apostrophe in Phoenix Arizona USA, with viewport centered on default downtown 1mi radius:
![](https://i.imgur.com/MA6EgdE.jpg)


Success mode, correct lack of apostrophe:
![](https://i.imgur.com/h4ZIPiT.jpg)


Annoying mode, distant airports and streets get vastly higher priority than nearby shops:
![](https://i.imgur.com/a2yiA5n.jpg)


Failure mode, incorrect apostrophe:

![](https://i.imgur.com/rYcXm5Z.jpg)


Failure mode, incorrect ampersand/"and":

![](https://i.imgur.com/F5n1upv.jpg)


Success mode, correct lack of apostrophe and presence of ampersand:

![](https://i.imgur.com/1vaRK4T.jpg)


Obviously remembering which locations have which punctuation is the optimal solution, but Organic Maps already does a pretty good job of ignoring missing apostrophes in shops that DO have one which is very helpful; the opposite case, ignoring present apostrophes or other incorrect synonyms in shops that DON'T have one would be very nice. There seems to be no rhyme or reason to which shops do and don't have them (what, did two men named Michael make a crafting store, but only one Macy made a clothing store?) so handling both mistakes is a great feature.

**Comment by zyphlar** [comment]
Encountered this today with Lowe's though it eventually found the right thing around result 5 when I persisted
