### ISSUE TITLE
Although turn restrictions are mapped, OM still prefers to make you make a u turn :)

### ISSUE THREAD

**Issue by wemissyou** [organicmaps/organicmaps#1267]
hello, i recently mapped a lot of u turn restrictions in Cyprus as i don't remember a place that you can make a u-turn in general :)
For that location for sure i mapped before the data update.

![photo_2021-09-07_18-36-43](https://user-images.githubusercontent.com/25705292/132372798-b9f3efd1-54a2-4c65-83b8-a970e585d7ab.jpg)

here is the location: https://www.openstreetmap.org/#map=19/34.68758/33.04501

thanks<3

**Comment by wemissyou** [comment]
Btw i manually tested many of the restrictions i mapped, and i dont remember any other issue just happened to drive to this road today in noticed

**Comment by biodranik** [comment]
They are created 5 days ago, but we took the map snapshot in August 25.

**Comment by wemissyou** [comment]
How can you check when they where created? :) so i dont make the same mistake again)

**Comment by biodranik** [comment]
Open Settings -> About :)

**Comment by alexey-zakharenkov** [comment]
> How can you check when they where created? :) so i dont make the same mistake again)

In JOSM, having the object selected go to "View -> History" menu.
Also, open the object page https://www.openstreetmap.org/relation/13158722 and find "View history" link.

**Comment by vng** [comment]
https://github.com/organicmaps/organicmaps/issues/1565

**Comment by alexey-zakharenkov** [comment]
The problem doesn't appear in data version 220103.
