### ISSUE TITLE
treat xxx=use_sidepath as xxx=no

### ISSUE THREAD

**Issue by vincentvd1** [organicmaps/organicmaps#1272]
There are countries (especially in the Netherlands) that have compulsatory bicycle paths, seperated from the main road where the cars drive. The bicycle path is often mapped seperately as `highway=cycleway`. In that case, the main driveway is tagged with `bicycle=use_sidepath`. The same applies to for example `foot`, `moped` etc. with seperately tagged roads like `highway=footway`.

Currently, the router of Organic maps does not recognize `use_sidepath`, resulting in incorrect routing suggestions (it routes you over major roads where you should not supposed to be). Organic maps should therefore treat `xxx=use_sidepath` as `xxx=no` and search for the nearest path (according to whether the user is using a bike or is by foot).

**Comment by biodranik** [comment]
@vng this one should be easy to fix
