### ISSUE TITLE
Organics Maps connects to map.google.com and ge0.me on update (Android)

### ISSUE THREAD

**Issue by BayLee4** [organicmaps/organicmaps#1276]
After an update, Organics Maps make requests to `map.google.com` and `ge0.me`. I do not know exactly what are those requests, as I just noticed them when monitoring DNS queries. Are they really needed ? If so, couldn't they be replaced by free alternative ?

**Comment by biodranik** [comment]
It's required to support opening ge0.me and google's maps URLs in offline. It's caused by link verification, see more details here: https://developer.android.com/training/app-links/verify-site-associations

> When android:autoVerify="true" is present on any one of your intent filters, installing your app on devices with Android 6.0 and higher causes the system to attempt to verify all hosts associated with the URLs in any of your app's intent filters. 

I'm not sure if these links together with our omaps.app will work if we disable autoVerify.
@rtsisyk can you please test on a fresh app install, after removing android:autoVerify="true" for omaps.app, or setting android:autoVerify="false" for those two domains (this won't change anything I suppose).

**Comment by BayLee4** [comment]
Sure I'm cloning the repo now and will test asap. Could you share an omaps.app link for testing purpose ?

**Comment by biodranik** [comment]
@BayLee4 install ndk r21e, not the latest one, and it should work.

https://omaps.app/test

**Comment by BayLee4** [comment]
Thanks, it did work with ndk r21e.

I built the fdroidRelease flavor with both `android:autoVerify="true"` removed for `omaps.app` links and `android:autoVerify="false"` added for `ge0.me` and `map.google.com` and I got no trouble opening links in [https://omaps.app/test](https://omaps.app/test). I did get the exact same behaviour that when using the official .apk downloaded from f-droid.

**Comment by biodranik** [comment]
Did you reinstall the app before each try? (I would also reboot the device after uninstall).
Did you see requests to those domains?

**Comment by BayLee4** [comment]
> Did you reinstall the app before each try? (I would also reboot the device after uninstall).

Yes, I did a complete reinstall between each try. (Force stop/Clean cache/Clean data/Uninstall -> Reinstall)

> Did you see requests to those domains?

Not at all.

**Comment by biodranik** [comment]
From documentation, looks like verification influences the default opening app. Was there any confirmation on the screen when opening omaps.app links?

**Comment by BayLee4** [comment]
No, to my surprise (and for both versions), there wasn't any confirmation popup when opening `omaps.app` links, even with "Ask every time" set in the "Open supported links" Android setting.

**Comment by BayLee4** [comment]
I'm using a Chromium based browser, are `omaps.app` links supposed to open directly the Organic Maps application ? Because in both case, it first load in the browser the map, and then when clicking on "Open with Organic Maps" on the top menu, it effectively opens it without any confirmation.

**Comment by BayLee4** [comment]
Anyway, if it's only used to skip one dialog (which apparently doesn't always work, if working at all), could you please consider adding `android:autoVerify="false"` to `ge0.me` and `maps.google.com` to f-droid builds ?

**Comment by biodranik** [comment]
omaps.app links should open in offline. If they are not open, then it's very bad.
Now it works like that: you install the app. Android verifies domain ownership. And if confirmed, then you can open these links in offline.

**Comment by BayLee4** [comment]
But it doesn't prevent opening links in offline mode, it just add a dialog the first time a link is opened right ?

**Comment by biodranik** [comment]
That is what should be tested. If UX breaks for omaps.app after removing validation, then the benefit of removal is ambiguous.

**Comment by BayLee4** [comment]
Yes, you could conveniently test it with the ge0.me link above on an unmodified Organic Maps build, it should work as expected even offline. (I tested it before commenting)
