### ISSUE TITLE
Different museum icons

### ISSUE THREAD

**Issue by DzmitryiK** [organicmaps/organicmaps#1280]
Museums starting to show on scale 1 km with old style icon. But when I zoom in to 200 m - icon changes to new one. Maybe app should use one icon?
Version: 2021.09.01-6-Google

![Screenshot_20210910-122457~2](https://user-images.githubusercontent.com/63190498/132861399-b1260312-7792-4cdf-a4da-14f3cacb7013.png)
![Screenshot_20210910-122519~2](https://user-images.githubusercontent.com/63190498/132861419-bac68e41-43b1-45cd-a115-1c7bc8456c0c.png)

**Comment by kudlav** [comment]
Similar with `leisure=pitch` + `sport=basketball`. The icon is changed from running person into basketball when zooming in.
\--
![Screenshot_20210917-163137_Organic Maps](https://user-images.githubusercontent.com/11516259/133940927-4b9678db-9087-4266-b307-8c241eaa6e5b.png)
++
![Screenshot_20210917-163148_Organic Maps](https://user-images.githubusercontent.com/11516259/133940925-177f41c7-6ced-4a55-ba38-806638f4632a.png)

**Comment by endim8** [comment]
Just checked and can confirm that both of these are still happening 👍

**Comment by pastk** [comment]
`museum-s.svg` and `museum-m.svg` in `data/styles/clear/style-clear/symbols/` (and in style-night) use different images. Edit those files to use just one shape.
