### ISSUE TITLE
Make marinas searchable as an object type

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#1288]
Marinas are already shown as marinas so data seems to be included already.

But...

Expected:

I can search for "drinking water" or "marina" and get list of objects of such type.

Actual:

Expected:

I can search for "drinking water" and get list of objects of such type. Searching for "marina" returns only objects with "marina" text in name,

**Comment by biodranik** [comment]
Which OSM tags are you speaking about?

**Comment by matkoniecz** [comment]
`leisure=marina` https://taginfo.openstreetmap.org/tags/leisure=marina

**Comment by biodranik** [comment]
What is your use case? Is it to park a yacht?

**Comment by matkoniecz** [comment]
> What is your use case? Is it to park a yacht?

Yes, I was looking for a possible marinas withing our range. I would be for initial planning, final planning would be done with navigational maps. But we had several people interested in looking for a good target for a day and just one set of navigational maps.

Also, it could be useful if you are a tourist and want to see a marina as an attraction.

**Comment by pastk** [comment]
There are also boat moorings [`mooring=yes/*`](https://wiki.openstreetmap.org/wiki/Key:mooring), but most of them (35k) are way-type compared to 7k node-type, so we can't just add them as POIs.
