### ISSUE TITLE
Routing doesn't want to work with this path

### ISSUE THREAD

**Issue by dbf256** [organicmaps/organicmaps#1289]
Routing doesn't want to follow the path.
It looks like a simple highway=path: https://www.openstreetmap.org/way/48179173#map=16/43.2734/42.5180

![image](https://user-images.githubusercontent.com/2550295/132990996-7aad2fb6-0ce5-4a1c-87a9-ad26098d0824.png)

**Comment by vng** [comment]
Because of this https://www.openstreetmap.org/node/7781402360 and I can't say for sure is it right or wrong ..

**Comment by dbf256** [comment]
Thanks for the details! I think that it is fine to not to rote through the ford (if I start before and end after it), but if I'm already after the ford and there is a long path later it should be able to route using remaining part of the path.

**Comment by vng** [comment]
Double checked. Yes, there is a bug, obviously. Thanks!

**Comment by vng** [comment]
So, the problem here is that OM doesn't process foot=yes (bicycle/motor_vehicle, I believe also) for node barriers. Should process them the same way as access=*

See https://www.openstreetmap.org/node/7781402361 as example.

**Comment by BelKed** [comment]
The [ford](https://www.openstreetmap.org/node/7781402360) data in OSM has been updated so it will now navigate smoothly along the expected route:

![IMG_8036](https://github.com/organicmaps/organicmaps/assets/66956532/d5690cf1-4a5e-4c25-8054-9813e50f2897)
