### ISSUE TITLE
[Editor] What to do with statistics?

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#129]
See user_stats.cpp, Ln 17
Should create our own service for statistics or remove it at all.

**Comment by dbf256** [comment]
fyi stats server is open-source, but need to be installed and running somewhere: https://github.com/Zverik/mmwatch

**Comment by rtsisyk** [comment]
What is the purpose of stats server? How does it affect user-visible behavior?

**Comment by dbf256** [comment]
> 
> What is the purpose of stats server? How does it affect user-visible behavior?

There is a screen Settings -> OpenStreetMap profile that displays how many objects you have changed with embedded openstreetmap editoe.

**Comment by rtsisyk** [comment]
```
WARNING   24.4239 editor/user_stats.cpp:105 Update() Server returned 404 for url https://editor-api.maps.me/user?format=xml&name=rtsisyk
```

@vng @biodranik: can we disable that?

**Comment by biodranik** [comment]
Выпилить, как это просочилось интересно.

**Comment by vng** [comment]
Я создал issue в надежде что мы запустим сервачок с циферками. Приятно было видеть наматывающий счетчик :)
Ок, выпилю сейчас.

**Comment by biodranik** [comment]
А погоди, не выпиливай, если это про количество правок.
Пускай стучится только при открытии профиля.

**Comment by vng** [comment]
Это именно про количество правок. Про стучится не совсем понял .. Тот ендпоинт скорее всего уже мертв. Стучится он туда и так только при открытии окошка или по кнопке "Обновить".

**Comment by rtsisyk** [comment]
Если стучаться некуда, то давайте пока временно выключим.

**Comment by vng** [comment]
А не, жив.
```
% curl "https://editor-api.maps.me/user?format=xml&name=vng_me" 
<?xml version="1.0" encoding="UTF-8"?>
<mmwatch>
  <name value="vng_me" />
  <rank value="962" />
  <edits value="358" />
  <joined value="2019-05-28" />
</mmwatch>
```

Рома, видимо это у тебя что-то не так ..

**Comment by dbf256** [comment]
Я добавляю объекты через omaps, но число правок на соответствующем экране у меня не меняется. Возможно сервер достает правки по фильтру mapsme.

**Comment by biodranik** [comment]
Пока закомментируем.

А потом можно убрать рейтинг и кверить osm api напрямую, чтобы брать оттуда число правок и другую полезную инфу.

**Comment by rtsisyk** [comment]
Закомментировали или нет?

**Comment by vng** [comment]
Да, надо комментить, пока у нас самих не будет такого сервиса.

**Comment by biodranik** [comment]
Я уже работаю над этим.

**Comment by Zverik** [comment]
На всякий случай, напрямую из апи эти числа не получить, нужно вести базу данных. Но если не нужны конкретные правки, а только количество, то требования к серверу можно заметно снизить.
