### ISSUE TITLE
city_wall and other barriers tagged as areas

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#1290]
Add barrier=city_wall and historic=citywalls as barrier=fence. Now they are not drawing and seems like there are no any barries on the map.

See https://www.openstreetmap.org/relation/12352553

**Comment by matkoniecz** [comment]
Note that https://www.openstreetmap.org/relation/12352553 is mapped as an area what makes it even more problematic to support.

https://www.openstreetmap.org/#map=18/51.11414/18.21498 may be simpler to handle https://www.openstreetmap.org/way/168957689

**Comment by vng** [comment]
@matkoniecz You are right. city_wall already presents in classificator and style. The problem here is because of area relation. So the solution here is to apply "linear" styles for area objects or generate area + linear feature for area objects.

**Comment by biodranik** [comment]
Wait, why is [that](https://www.openstreetmap.org/relation/12352553) relation an area? It is not closed, so it is an invalid multipolygon.

**Comment by matkoniecz** [comment]
`type=multipolygon` indicates that it is an area, though it can be an invalid one if not closed. Maybe it is a purely data issue?

I am not familiar with OM preprocessing, but hopefully it is not treating invalid multipolygons as lines.

**Comment by alexey-zakharenkov** [comment]
> Wait, why is [that](https://www.openstreetmap.org/relation/12352553) relation an area? It is not closed, so it is an invalid multipolygon.

In fact, it's a valid multipolygon. It consists of two closed non-overlapping simple outer rings.
