### ISSUE TITLE
fix rendering of highway areas

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#1293]
Currently, it seems that areas tagged with highway=footway render as if it was a way, with a dashed path around the edge. 

highway=footway and an area tag are used together 133,327 times (14.64% of all highway=footway also includes an area tag)

This mock-up shows that fixing this would greatly reduce screen clutter:
![Screenshot_20210912-182212_Organic_Maps(4)(1)](https://user-images.githubusercontent.com/26939824/133002448-5818e730-b871-4120-8447-8e392ad0e097.png)

**Comment by biodranik** [comment]
@vng this one should be easy to fix.

**Comment by vng** [comment]
Well, I suspect (not 100% sure) that separate linear feature is created around area objects .. If we ban it, the pedestrian routing will be broken. We need to make some complex solution here and it's not so easy if I'm right.

**Comment by biodranik** [comment]
Routing should work over area features, that's the right solution.

**Comment by endim8** [comment]
Discovered some more information that should make this easier;
 https://wiki.openstreetmap.org/wiki/Key:area:highway#Differentiation_area:highway_vs._area=yes_on_a_highway

only areas with area=yes are meant to be routable, there is a different tag called area:highway which isn't meant to be routable and is only used for rendering. adding a style definition for area:highway shouldn't break anything ^-^

**Comment by endim8** [comment]
area:highway renders fine, this issue was based on incorrect tagging.

**Comment by map-per** [comment]
I think this is still an issue for `highway=pedestrian`, especially as it is inconsistent for simple areas and multipolygons.

Is it possible to just hide the outline in the style and still use it for routing?
Is it possible to filter for `highway=pedestrian` without `area=yes` in mapcss-mapping.csv?

#### Example
[multipolygon](https://www.openstreetmap.org/relation/1951581) on the left and [simple area](https://www.openstreetmap.org/way/500116641) on the right
![Screenshot (102)](https://github.com/organicmaps/organicmaps/assets/79519062/1aa4c785-cd4a-4732-b6e7-99a1be03b4d5)
