### ISSUE TITLE
Non-business hours hidden 

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#1297]
When looking at a business opening hours, the non-business hours are hidden which can be misleading.

Example:
| Real time | Shown time | 
|-|-|
| ![Screenshot_20210914-101344_Organic_Maps](https://user-images.githubusercontent.com/80701113/133221444-9a436fa9-216d-415d-a753-eb9ba3e5f5b1.png) | ![Screenshot_20210914-101339_Organic_Maps](https://user-images.githubusercontent.com/80701113/133221450-177ac244-6d85-419a-8bd7-8dbaea1bf2b4.png) |

## Possible solution

Show the hours including the non-business hours like this:
12:00 to 14:00, 19:30 to 22:00

## System

- OS: Android 9
- Organic Maps version: 2021.09.01-6-F-Droid
- Data Version: 210825

**Comment by FinixFighter** [comment]
Maybe issue #502 could be related to this, since there it is stated that "No Open/Close status" is available on Android.

**Comment by arnaudvergnet** [comment]
Seems like a duplicate of #970

**Comment by arnaudvergnet** [comment]
Seems to be fixed when clicking on a feature in the map view, but not in the editor, should I close this issue?

| Map view | Editor | 
|-|-|
| ![Screenshot_20211223-142310_Organic_Maps](https://user-images.githubusercontent.com/80701113/147246748-2923e1b2-aea3-4baa-8276-304aa1f43128.png) | ![Screenshot_20211223-142335_Organic_Maps](https://user-images.githubusercontent.com/80701113/147246766-28056bf3-3e86-46f7-9c55-285f10793319.png) |

**Comment by biodranik** [comment]
@strump can you please take a look on it?

**Comment by strump** [comment]
@biodranik , in my PR I made changes only to Place page. Let me do changes to Editor page too. I'll post a PR soon  😉

**Comment by Kazing** [comment]
Non-business hours are displayed also in editor view, with Organic Maps version: 2022.01.15-3-F-Droid

see PR #1751

**Comment by arnaudvergnet** [comment]
Closing this issue as this has been fixed for some time now.
