### ISSUE TITLE
Display Mailbox Collection Times

### ISSUE THREAD

**Issue by kojid0** [organicmaps/organicmaps#1304]
OSM has information about collection times of mailboxes. Given that there is a dedicated category in Organic Maps, it would be nice to have this kind of information displayed as well.

**Comment by RedAuburn** [comment]
closing in favour of https://github.com/organicmaps/organicmaps/issues/1304 as more detailed

**Comment by patepelo** [comment]
> closing in favour of #1304 as more detailed

@RedAuburn you linked to it's same issue.

**Comment by RedAuburn** [comment]
oops 😅 closing in favour of https://github.com/organicmaps/organicmaps/issues/2431
