### ISSUE TITLE
[Icon request] More "Maps" icon

### ISSUE THREAD

**Issue by julianfairfax** [organicmaps/organicmaps#1305]
The current app icon isn't easily identifiable as being "Maps" and doesn't really fit in with other Android app icons. An app icon in the style of the OpenStreetMap icon but respecting Android's app guidelines would make it more obvious that this is a maps app and that it's a maps app for OpenStreetMap. I could ignore it, but I'm very particular about small details.

**Comment by julianfairfax** [comment]
OpenStreetMap and GNOME Maps icons for inspiration:
![image](https://user-images.githubusercontent.com/43753131/130283618-91b3761d-66e4-4624-b7fb-835578891af5.png)
![image](https://user-images.githubusercontent.com/43753131/130283563-5d68bded-86f7-42df-bbaf-7bc563186ab3.png)

**Comment by FinixFighter** [comment]
The community voted for this logo some time ago.. Anyway I find it quite professional. Just think of Google Maps, the setting is quite similar, so most of the people should understand that this is a "maps app". But it's just my opinion. :)

**Comment by julianfairfax** [comment]
Well it might just be me, but I'm very particular about design, probably too much for my own good, and I personally don't feel right about this one. Feel free to close this issue if I'm the only one who can comes up with that view.

**Comment by biodranik** [comment]
The original icon chosen by us was this one:

![icon_512x512@2x](https://user-images.githubusercontent.com/170263/133497966-621c18f8-52b0-48c9-a1a7-312860b5d59b.png)

**Comment by julianfairfax** [comment]
I think its the color that does it for me. A lighter one more along the lines of OpenStreetMap's or GNOME Maps' would look better in my opinion. Apart from that I'd say its a good icon, but could maybe do with a light shadow in between the background and foreground elements.

**Comment by julianfairfax** [comment]
Closing since there are probably no plans to change it.
