### ISSUE TITLE
Prioritise Train station POI over bus stop

### ISSUE THREAD

**Issue by keunes** [organicmaps/organicmaps#1332]
I've noticed this before (I think also in maps.me) and just saw this again: bus stops next to train stations get prioritised  over the train stations themselves. Only when zooming in quite far, the train station POI becomes visible.

Example:
![Screenshot_20210923-140037.png](https://user-images.githubusercontent.com/11229646/134503130-ccca07e5-cd26-4224-9dbd-8f9effe95e28.png)

The train station should take priority (especially when zoomed out), because it covers a wider area and is more relevant to travellers).
https://omaps.app/o4JIUpz132/Station_Venlo

Slightly related; in OSM, is there a distinction between local/regional and (inter)national bus stations?

**Comment by biodranik** [comment]
@vng is it easy to change priority?

**Comment by dbf256** [comment]
And station name is not displayed on a very close zoom
![Screenshot_2021-10-02-11-05-26-158_app organicmaps](https://user-images.githubusercontent.com/2550295/135708775-d40e954b-004f-41a1-9bfa-f61fa1b81801.png)
