### ISSUE TITLE
Give rough route & time estimate even with missing maps

### ISSUE THREAD

**Issue by keunes** [organicmaps/organicmaps#1335]
Hello

I was in a bus on the highway, though in an area for which I hadn't downloaded a map. The highway was included in the world map, though. I tried to use routing to get an estimate duration, but that didn't seem to work.

I was asked if I wanted to download maps, and tapped on 'Later'. Since I was on a known route and my destination was in an area of which I had downloaded a map, I expected to get a route proposed indicating a time estimate.

![Screenshot_20210923-140748.png](https://user-images.githubusercontent.com/11229646/134504851-2fe386e4-9c85-4c60-9c00-e6616aeb58a9.png)

Of course, when not on a road included in the world map, a grey line could be drawn to indicate the unknown bit until the road on the world map. I assume road details (like maximum speed) aren't included. Therefore this route would be kind of a 'minimum'. Maybe a warning should be shown on the screen when the guesstimate route is shown. I wouldn't expect it to be possible to initiate actual navigation mode.

**Comment by biodranik** [comment]
Unfortunately, that's not possible. World map does not have all roads, traffic lights, barriers and gates, border controls, etc. it is also greatly simplified. Any such "rough" estimate will mislead people in most of the cases.
