### ISSUE TITLE
[!] No `Podfile' found in the project directory.

### ISSUE THREAD

**Issue by yesmanchyk** [organicmaps/organicmaps#1352]
I'm following https://github.com/organicmaps/organicmaps/blob/master/docs/INSTALL.md#ios-app and getting `No Podfile found in the project directory` when running `(cd iphone/Maps && pod install)`

masOS BigSur 11.6 on MacBook Air M1
```
% pod --version
1.11.2
```
Checked out commit 5cf88f0c83cac08e8c7e80f721bf42786a8287c8

**Comment by yesmanchyk** [comment]
Podfile was removed in the commit 89799be3353ebf07d78a75b8d809e7a59252d9c0.

**Comment by biodranik** [comment]
Please update README and make this world a bit better ;-)

**Comment by yesmanchyk** [comment]
@biodranik done, please review https://github.com/organicmaps/organicmaps/pull/1370
