### ISSUE TITLE
[Editor]: keyboard hides Notes field

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#1357]
**OS:** LineageOS 17.1 (Android 10.0).
**OM:** 2021.09.14-4-Google.
**Keyboard:** [jbak2](http://jbak2.ucoz.net/) 2.36.03.

In editor, `Notes` field is being overlayed by keyboard, even when typing. Here's the video:
https://user-images.githubusercontent.com/22843816/135196628-e5db21e3-63db-4679-ab4f-04d9f84c7e41.mp4

**Comment by pratyaksh1610** [comment]
@biodranik I think this can be closed as this issue is resolved by #3323 .
PTAL.
Thanks.

**Comment by biodranik** [comment]
@pratyaksh1610 thanks, next time you can mention the issue in your PR as `Closes #number` or `Fixes #number`, and the issue will be closed automatically after the merge.
