### ISSUE TITLE
Intent Processing not working (open with Dialogue from other Apps)

### ISSUE THREAD

**Issue by 13hannes11** [organicmaps/organicmaps#1361]
## What?
When clicking a location Link in another app the location can be opened with Google Maps or Organic Maps. When opening with Organic Maps nothing happens.

## Expected behaviour
The search of Organic Maps opens with the given Address as a search String.

## To reproduce:
1. Download Etar calendar app. (It is the default calendar app for LineageOS).
2. Create a new appointment and add an address in the appointment location and save.
3. Click on the appointment and then click on the location link.
4. If multiple Map apps are installed click on open with Organic Maps

As screenshots:
![image](https://user-images.githubusercontent.com/9381167/135289158-3b90ffca-e163-42f0-a5be-b59c37ffcc5b.png) ![image](https://user-images.githubusercontent.com/9381167/135289212-8dae38c3-97ac-4838-b3ac-9364dace6509.png) ![image](https://user-images.githubusercontent.com/9381167/135289236-a27b1781-c656-43bf-bc32-de74d7722a13.png)

## Further information

According to my understanding and the android documentation _intents_ are used to open apps. The developer guide gives some hints: https://developers.google.com/maps/documentation/urls/android-intents

Here is some more basic documentation about intents: https://developer.android.com/training/basics/intents/sending

**In the code there seems to be a factor that does stuff with IntentProcessors this could be a starting point**: https://github.com/organicmaps/organicmaps/blob/0659467a622160b0059a95e6925b13c16430044f/android/src/com/mapswithme/maps/intent/Factory.java

**Comment by biodranik** [comment]
Is it similar to #320 ?

**Comment by 13hannes11** [comment]
> Is it similar to #320 ?

It seems to be. However, the Google documentation describes more than just coordinates for Geo URLs.

Wikipedia says the following:

> Some vendors, such as Android OS, have adopted extensions to the "geo" URI scheme:
>
>    * z: Zoom level for Web Mercator projection scaling. The value is an integer from 1 to 21.
>   * q: Perform a search for the keyword given around the point. If the location is given as "0,0", search around the current position. A parenthetical can be used to indicate the label to show on the map.
>
>Android adopts an unconventional approach to parsing the points: it does not show a map pin at the point given normally, and a map pin will show up only when given as the query. In other words, to show a pin at the Wikimedia Foundation office, one should not use `geo:37.78918,-122.40335` but `geo:0,0?q=37.78918,-122.40335`
