### ISSUE TITLE
GPS Signal lost when screen is off

### ISSUE THREAD

**Issue by TheBiostarfly** [organicmaps/organicmaps#1372]
When I navigate on my bicycle I wanna put my phone in my pocket and use the voice navigation. As soon as I turn the display off, Organicmaps looses GPS connection and the navigation isn't continued. Not until I return to the app it will look for the GPS signal and continue the navigation. 
When I use Osmand it works just as expected. I'm on GrapheneOS. I'm not sure if this plays in to it. 
Oh and something else. I guess it would also be helpful if organicmaps would warn you that it lost the GPS signal through voice command.

**Comment by Misalf-git** [comment]
I believe you have to allow OMaps to "run in background" via Android's settings (apps - battery).

**Comment by TheBiostarfly** [comment]
Thank you for your responds. I tried your suggestion but it didn't work. I think I'm just going to use osm when biking as omap doesn't work for me in this scenario

**Comment by biodranik** [comment]
It's not about losing GPS signal. It's about the app working in the background. See #573 for more details.
We'll implement it, of course.

**Comment by rtsisyk** [comment]
I am closing this ticket in favor of #573. See also discussion in #1853.
