### ISSUE TITLE
[search] POI ranking is strange.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#1376]
My position is [here](https://www.openstreetmap.org/node/5878439983#map=19/40.41050/-3.69784). Current map viewport also here.
1. I do search for "Carrefour" and first results are _3, 4, 5 km away_. If I scroll to the very bottom! of the list, I can find my result _49m, 340m away_. I suspect that it's because of POIs composite names "Carrefour Express" or "Carrefour Market", but it definitely **NOT good** behaviour.
2. Ok, I add "Carrefour e" to the search and I see completely irrelevant results: regions or neighbourhoods with matched "e" letter and **NO** Carrefours in top-20!
3. Ok, let's try "Carr". I see "El Carrizal" village on first place _(45km)_. "Museo Cerralbo" on 5th place (match with error! here) and **NO** Carrefours in the results, **BUT** "Carrefour" token presents in suggests list. Definitely, "Carrefour Express" _(45m)_ should present in results list.

**Comment by biodranik** [comment]
Here is one more example:
![telegram-cloud-photo-size-2-5465272251696919890-y](https://user-images.githubusercontent.com/170263/139559395-c53ef6ce-2d61-42e5-832a-14e0bead2a9b.jpg)

**Comment by biodranik** [comment]
Рудея (речка) в Беларуси в топе показывает Рудня.

**Comment by vng** [comment]
The same issue here https://github.com/organicmaps/organicmaps/issues/1017
"Carrefour Express" and "Rimi mini" are ranked low when searching for "Carrefour" or "Rimi". Usually far away (5 km) results on top because the have NAME_SCORE_FULL_MATCH agains closer NAME_SCORE_PREFIX.
