### ISSUE TITLE
Hedge rendering practically invisible

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#1385]
Hedges are basically impossible to see, Carto renders it much more nicely: https://www.openstreetmap.org/#map=19/51.76043/-0.20681

![Screenshot_20211008-044709_Organic_Maps-01.jpeg](https://user-images.githubusercontent.com/26939824/136495201-7cbb1906-ea9a-4cb7-996b-3833acb95cee.jpeg)

**Comment by AlertSubject** [comment]
![Screenshot_2022-06-29-12-57-08-75_75d0290a7c00525acd83c0ab8700d64c.jpg](https://user-images.githubusercontent.com/72819077/176421227-81eb34de-885e-4f71-afa8-a998fd72bcf7.jpg)

New hedge rendering
Can this be closed now?

**Comment by endim8** [comment]
![Screenshot_20220629-230659_Organic Maps](https://user-images.githubusercontent.com/26939824/176554104-81892c54-2539-4bc5-bf76-afddd0080663.jpeg)
yup 👍
