### ISSUE TITLE
[classificator] Question: multiple initialization?

### ISSUE THREAD

**Issue by rsippl** [organicmaps/organicmaps#1387]
I'm trying to understand the code related to classificator initialization (BTW it should be called "classifier" but that's not my point ;)).

The classificator and types txt files are loaded here:

https://github.com/organicmaps/organicmaps/blob/1620f5908311b09c3f50bffd3d0a6e534defd3c9/indexer/classificator_loader.cpp#L53-L65

Can you please explain why they are loaded for every style, i.e. at least four times? If I understand correctly, these files do not depend on styles, they are generated from a single file (mapcss-mapping.csv), so shouldn't it be enough to load them once? On the other hand, if I move the ReadCommon(... line out of the loop, the app crashes with a failed assert when I change to night mode, so something about my assumption must be wrong.

**Comment by biodranik** [comment]
I think txt files are loaded every time because they are needed to initialize each style ruleset. The obvious optimization could be to load txt files once and use their content from the memory, for a bit faster app startup.
@vng  ?

**Comment by rsippl** [comment]
Agreed, thanks for the details. I assume you'll create a new issue for that refactoring, so closing for now.
