### ISSUE TITLE
POI type in German displayed but not found by search unless full word is searched

### ISSUE THREAD

**Issue by georg-d** [organicmaps/organicmaps#1400]
I'm in the mood to have ice cream. Hence I trigger search with search term "Eis" and I want to find 

1. all kinds of locations offering ice cream, so - as DE is my system language - "Eisstand", "Eisdiele", "Eiscafé", "Eisverkauf" etc. Because I cannot know which of the synonyms and regional dialects OM uses and I am too lazy to manually search the map until I find one POI of the desired type & can look what term is used by OM, I search for "Eis" and I hope OM will suggest categories starting with these characters (like wehen entering "bäcker" getting "bäckerei") but I get no suggestion. I also hope OM will select all POI type names with that prefix or word stem, but it does not.
2. all POIs carrying "Eis" in ther name, or at least starting with that prefix like when I e.g. search "Krokod" I will get results like "Cafe Krokodil" or "Krokodilstein". But for "Eis", such a prefixing/autocomplete does not work.

The POI is only found when search term is exactly "Eisstand".

Odd enough, when I do search the English term "ice", it's found despite nowhere "ice" is displayed.

![displayed type and name but not found by search](https://user-images.githubusercontent.com/45993293/136697520-6ef6240a-c73c-4676-a4da-92732ed1bee5.png)

OM v2021.09.14-4-Google

It differs from https://github.com/organicmaps/organicmaps/issues/1147 in the sense there, only one of 2 similar objects is found while here, it's about translations.

It differs from https://github.com/organicmaps/organicmaps/issues/1017 in the sense there, it's about searching one word of the name while here, it's about POI type.

**Comment by biodranik** [comment]
Search hints are not showed automatically now. Take a look at data/categories.txt to get a better understanding. This should be fixed and improved.

Search ranking is a complex topic. If you show only "Eis" starting names, then you miss "Eis" type for example. Some other results are mixed in, search tries to guess what are you typing (and it can be improved, obviously).
