### ISSUE TITLE
Train platform ref/name rendering

### ISSUE THREAD

**Issue by starsep** [organicmaps/organicmaps#1405]
It would be useful to render either ref or name of a train platform.

Example train platform: https://www.openstreetmap.org/way/69334312
It has both `ref=5` and `name=Peron 5` (Platform 5 in Polish) tags.

Screenshot of Organic Maps (data from 2021-08-25)
![image](https://user-images.githubusercontent.com/2798728/136714082-914f115b-748e-4aba-9b48-611c3fdfee77.png)
Screenshot of OSM Carto
![image](https://user-images.githubusercontent.com/2798728/136714260-8dd4a00f-9e02-4e93-af26-04c6fb5a90ca.png)

**Comment by vng** [comment]
Will be like that:
<img width="1072" alt="Screenshot 2021-12-22 at 12 45 19" src="https://user-images.githubusercontent.com/175612/147072312-12e95bfa-115d-4f10-9a3b-5e244bb81f55.png">
