### ISSUE TITLE
Relocate bookmarks button to search tab

### ISSUE THREAD

**Issue by Donkey-Doug** [organicmaps/organicmaps#1409]
Bookmark button is currently in the bottom bar:

![Screenshot_20211011-015757_Organic_Maps](https://user-images.githubusercontent.com/50382414/136717155-72b2703f-09f0-4a3d-bc1b-c1d8e76babad.png)

I suggest relocating it to a tab in the search view:
![Screenshot_20211011-015742_Organic_Maps](https://user-images.githubusercontent.com/50382414/136717156-57844a9d-a8fe-469d-a528-4c7521a013d6.png)

**Comment by biodranik** [comment]
But you can't see History or Categories then.

**Comment by dpriskorn** [comment]
I don't understand what you mean. Could you make an image?
How would this improve the experience?

**Comment by patepelo** [comment]
May I close this suggestion as "Not planned"? At least for the moment. It would be a polemic change for many users and is not clear.

**Comment by biodranik** [comment]
Bookmarks button is a strategic one. There is no benefit of breaking the existing UX by moving/hiding it from the map.
