### ISSUE TITLE
[styles] Clarify icons drawing for multiple types.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#1414]
Like leisure=stadium + sport=basketball, seems like we draw generic stadium icon here:https://www.openstreetmap.org/relation/8209013

**Comment by pastk** [comment]
When selected the feature is shown as "Basketball" so the `sport=basketball` is considered primary by the app.

Possible reasons basketball icon is not used:
- it's defined for nodes only, whereas stadium is defined for areas also
- its defined for z18- whereas stadium is z13-
- stadium has a higher z-index

**Comment by pastk** [comment]
But there are other issues beside the icon. It's a stadium after all, so it should be displayed in PP at least as a
```
Basketball
Stadium
```
Or even better
```
Stadium
Basketball * Voleyball * etc.
```

**Comment by pastk** [comment]
@biodranik what do you think about types priorities here?

**Comment by biodranik** [comment]
Types should be sorted by priority. Stadium then sports types.

**Comment by pastk** [comment]
ATM `leisure-stadium` has a much higher priority than individual `sport=*`, hence a generic stadium icon is shown
(also stadium's icon is z13- while sport-* are z17-)

**Comment by dvdmrtnz** [comment]
Closing this. Now https://github.com/organicmaps/organicmaps/pull/8481 shows all POI types on the place page.

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/41cb10cb-4cab-4ede-af34-8bd93204c5e3" width="320"/>
