### ISSUE TITLE
[POI Types]: laboratory doesn't work as  it should

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#1428]
**App:** 2021.10.09-2-Google
**Language:** RU
**OS**: LineageOS 17.1 (Android 10.0)

According to _2021.10.09-2_ release notes,
> Added healthcare=laboratory type

However:
1. [The following lab](https://www.openstreetmap.org/node/5876438788) is being showed as `type.healthcare.laboratory` instead of `Лаборатория` or something;
2. There's no such category in POI adding activity

**Comment by pastk** [comment]
Its fixed, please close the issue.
