### ISSUE TITLE
Implement "Helicopter routing and navigation" for areas without OSM routes

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1452]
Some people prefer to have a "straight line" routing on the map, for different reasons: missing maps data, sports orienteering, habits, etc. Properly implementing "Helicopter" aka "straight line" routing can also make it easier to measure the distance between any number of points on the map.

Related to #1167.

![image](https://user-images.githubusercontent.com/170263/138411957-fd46e88c-053d-495a-846c-e9bb4cf950e0.png)

**Comment by hoizan** [comment]
I like the proposed direct routing  feature.  It provides better visual experience for being able to see one's  location on map with  a directional line drawn to the destination.  I believe it won't break the compass view.  Both views  should complement each allowing users to toggle between them.

**Comment by pastk** [comment]
I think "straight line" routing as seen on the first screenshot can replace the current "compass view" completely - it provides the same info to the user but in more clean way without obstructing the map view as much. It could be started the same way - by tapping on a small direction arrow in PP preview.

**Comment by tvld** [comment]
#2661 my two cents ;)

**Comment by sunsero** [comment]
I'd love this feature as routing option.

As a quick temporary solution to have something like this I would suggest to keep the straight line between start and destination after calculating the route until actually starting to navigate.

Implementing as the crow flies as actual routing mode would even allow for more complex forms like area rectangles when additional stops are added to routing.

**Comment by biodranik** [comment]
Closing as already implemented.
