### ISSUE TITLE
Finish Belarusian translations for search categories

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1455]
At the moment, the search doesn't work properly for Belarusian. This file should be updated with be: translations:

https://github.com/organicmaps/organicmaps/blob/master/data/categories.txt

![telegram-cloud-photo-size-2-5447269883390834589-y](https://user-images.githubusercontent.com/170263/138549950-c5bd8d36-1d4b-40ba-a179-a328ef1b5835.jpg)

**Comment by pastk** [comment]
Fixed in https://github.com/organicmaps/organicmaps/pull/1830/commits/0fbdc70cb4d8bfcadb39600b7b6c0c1bb884aabc?

**Comment by biodranik** [comment]
No, it still needs to be translated.
