### ISSUE TITLE
Searching for "toilet" or "bathroom" doesn't include amenity=toilets in the results

### ISSUE THREAD

**Issue by squeak9** [organicmaps/organicmaps#1462]
This seems like an oversight, currently it only shows results for `toilets=yes` ([wiki](https://wiki.openstreetmap.org/wiki/Key:toilets)) and not `amenity=toilets` ([wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets)) which is the tag for public toilets and not just if a feature has a toilet or not.

Please include `amenity=toilets` into the results.

While you're at it consider displaying information from the tags that further describes the public restroom like `changing_table=*`, `wheelchair=*`, `access=customers` and `fee=*` cause these are tags that [streetcomplete users constantly contribute to the map](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#Released_quest_types).

**Comment by matkoniecz** [comment]
> Building=toilets should be added as well

definitely no, as it includes also disused toilet buildings, private toilets (say separate toilet building on stadium inaccessible to general public) etc.

**Comment by pastk** [comment]
> We do search for amenity=toilets. Better to check it like "Show on map". Current ranking in search is bad _(on my opinion)_ and first results in list will be POIs with names and toilet=yes. Public toilets will be at the end of the list despite of the distance. This is bad and we already have a bunch of issues with search ranking ...

Do we really support [toilets=yes](https://wiki.openstreetmap.org/wiki/Key:toilets)? It doesn't show up as an extension of other types in `types_strings.txt` like its done with some some other attributes e.g. `amenity.parking.private` or `natural.beach.gravel`

**Comment by pastk** [comment]
Just to link here related issues: #1301 and #979

**Comment by pastk** [comment]
To be done as part of #1376
