### ISSUE TITLE
Not optimal routing (time) and choice of road type (Android)

### ISSUE THREAD

**Issue by ooprizrakoo** [organicmaps/organicmaps#1470]
Not optimal routing and choice of road type in case no any restriction:
Москва-->Десногорск
![image](https://user-images.githubusercontent.com/661813/138953727-cf680711-31d1-4e26-a8e7-915fc887b13b.png)
Time: 5:44 - медленный маршрут по платным и по плохим дорогам.

When avoidance of toll roads is ON - as a result GOOD routing:
Когда включено избегание платных дорог, строит ХОРОШИЙ маршрут:
![image](https://user-images.githubusercontent.com/661813/138953527-33972cbd-65b4-4d1c-8c73-92c552fc3da8.png)
Time: 5:10 - быстрый маршрут, и по бесплатным хорошим дорогам.

**Comment by ooprizrakoo** [comment]
1) (настройки объезда **отключены**)
Если построить маршрут из _Москва, Факультетский переулок_ до города Десногорск - то он будет занимать 5 ч. 41 минуту (маршрут идет через плохие разбитые, хоть и асфальтовые дороги)

2) (настройки объезда **включены** - избегание платных дорог)
Если построить маршрут из Москва, _Факультетский переулок_ до города Десногорск - то он будет занимать 5 ч. 8 минут (то есть на пол часа быстрее, если ехать не по платнику)

Это, имхо, неправильно.

**Comment by vng** [comment]
Issues закрываются при мерже PR. Конечно, надо дождаться следующего обновления аппы.
<img width="792" alt="Screenshot 2022-02-07 at 12 31 35" src="https://user-images.githubusercontent.com/175612/152762213-ec5a673a-8937-40e8-b8ad-a2a09a3f3cbf.png">
