### ISSUE TITLE
"Name of the place" is not populated in the place editor

### ISSUE THREAD

**Issue by omentic** [organicmaps/organicmaps#1478]
Frequently when editing a place, its existing name doesn't appear in the place editor.

https://user-images.githubusercontent.com/35242550/139355359-912f9b86-8c2d-4538-a216-0489cf267f25.mp4

**Comment by biodranik** [comment]
Interesting, video doesn't work in mobile Safari.

**Comment by j-james** [comment]
That might be because it's a webm I sneakily renamed to an mp4 so GitHub would take it.

Here's a direct link: https://0x0.st/-nuX.webm

**Comment by biodranik** [comment]
Interesting, the feature has a default "name" tag: https://www.openstreetmap.org/node/8421856512

**Comment by reinhart1010** [comment]
See also https://github.com/organicmaps/organicmaps/issues/762#issuecomment-966791448

**Comment by bxl-forever** [comment]
The "name" tag in OSM is not shown in that editor window by default.  On the contrary, name:* tags—with translations in other languages—are.
Here is the workaround: click on "add a language" and select "Native for each country" at the bottom of the list.  Then you can see the real name and you can edit it and upload changes.

It would be highly desirable to change this behaviour and show the real name by default.

**Comment by map-per** [comment]
Looks like this bug only appears in bilingual countries like e.g. Belgium

**Comment by map-per** [comment]
Fixed the issue with #6257
