### ISSUE TITLE
Show more results on the map when searching

### ISSUE THREAD

**Issue by j-james** [organicmaps/organicmaps#1479]
Like all map apps, Organic Maps hides some place icons as you zoom out. But this can make it difficult to find places sometimes.

Because you're likely going to be looking for fewer icons over a larger area when searching, Organic Maps should display more or all of them to make search easier.

![zoomed-out](https://user-images.githubusercontent.com/35242550/139364165-ea2a31b2-5abe-47ca-8c66-9af1420a0cd3.png) ![zoomed-in](https://user-images.githubusercontent.com/35242550/139364162-4e35a0d3-640a-418f-8b38-1fefa3e58d0a.png)

(Notice that another three restaurants appear after zooming in two blocks.) Google Maps also suffers from this problem. It's more apparent when you're searching for something more specific (like a book store).

![zoomed-out](https://user-images.githubusercontent.com/35242550/139364179-aa8b6591-bfd4-4257-a4ea-dfa0b75ad8be.png) ![zoomed-in](https://user-images.githubusercontent.com/35242550/139364175-fd766c1e-fff1-4e90-b8a3-c82df2eff414.png)

**Comment by biodranik** [comment]
This issue was already referenced somewhere, no?

**Comment by j-james** [comment]
Found it: #1003
