### ISSUE TITLE
[Android] Editor ignores name in russian if it's the same as default name

### ISSUE THREAD

**Issue by strump** [organicmaps/organicmaps#1481]
Android 9
OrganicMaps: 2021.10.15-15-google
Android default locale: Russian

**Steps to reproduce:**

1. Select a POI which has `'name'` and `'name:ru'` tags same value. E.g. https://osm.org/node/8235467349

    | Key | Value |
    | ---------- | ---------- |
    | name | Паштет |
    | name:en | Pashtet |
    | name:ru | Паштет |

    `'name'` tag is treated as ukrainian lang.

2. Open editor
3. Don't change anything and press save button (upper right corner)
4. Open editor again

**Actual result:** Russian name becomes empty.
**Expected result:** Russian name should be present.

This happenes only when `name` and `name:ru` tags have the same value on the map of Ukraine.

![pashtet](https://user-images.githubusercontent.com/720808/139391147-001fb036-328e-4e6a-b862-bfe63dcfc346.png)

**Comment by map-per** [comment]
Fixed the issue in #6257
