### ISSUE TITLE
[Bookmarks] Rename "List Settings" to "Rename"

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#1485]
### Discussed in https://github.com/organicmaps/organicmaps/discussions/1483

<div type='discussions-op-text'>

<sup>Originally posted by **Shohreh** October 31, 2021</sup>
Hello,

In the Bookmarks section, I suggest renaming the "List Settings" to… "Rename".

Cheers,

![Screenshot_2021-10-16-19-59-18-722_app organicmaps](https://user-images.githubusercontent.com/1541861/139560967-48e1c7c8-f3ab-4d04-9867-7a43ca25ec22.jpg)
</div>

**Comment by biodranik** [comment]
There was an option to share the list. If we add it as a menu item then the current text can be renamed.
