### ISSUE TITLE
IPFS support

### ISSUE THREAD

**Issue by thegriglat** [organicmaps/organicmaps#1486]
Is somebody tried to store maps on IPFS filesystem? Look at http://ipfs.io
It allows peoples easily help with maps distribution

**Comment by biodranik** [comment]
Files are too large to pollute IPFS, and are constantly updated. What is the reason to use IPFS for maps?

**Comment by jpds** [comment]
This sometimes comes up on Reddit, see: https://www.reddit.com/r/openstreetmap/comments/qg7sgg/improving_the_world_bit_by_expensive_bit/

**Comment by RedAuburn** [comment]
closing as there isn't really any point

**Comment by pataquets** [comment]
Maybe IPFS is not the best solution technically, but I see the merit of using some kind of distributed/P2P distribution mechanism and I share @thegriglat's motivation background.
Setting up a maps/ISO/whatever mirror server when you want to contribute back to some project is quite an involved task, as opposed to deploying a simple IPFS/torrent node on your VPS (or even your home PC) which joins the swarm *permissionless* to shoulder the load on maintainer's infra.

I actually do/did it for some projects I care (Linux ISOs, [OpenStreetMap dumps](https://wiki.openstreetmap.org/wiki/Planet.osm#BitTorrent_RSS.2FAtom_feed), [Library Genesis](https://en.wikipedia.org/wiki/Library_Genesis), and [many](https://www.reddit.com/r/DataHoarder/comments/abld5g/800_gib_torrents_with_1500k_public_domain/?rdt=38268) [more](https://opendata.stackexchange.com/questions/4080/what-are-some-opendata-torrents-to-seed)) and I'd definitely would join a swarm carrying OrganicMaps' maps.

Disclaimer: I've already voiced for swarm distribution in the past. See https://github.com/organicmaps/organicmaps/issues/835#issuecomment-1718405153.

**Comment by biodranik** [comment]
Distributing maps via torrents swarm sounds good, but for frequent updates (e.g. daily) and stably fast first user experience (new users won't wait but uninstall the app if download is slow) it may not scale well. 

One of the ideas was to use devices connected to a charger and wifi to work as a torrent node. That may also not work well due to mostly firewalled ports worldwide.
