### ISSUE TITLE
Airport gates labeling

### ISSUE THREAD

**Issue by zaizone** [organicmaps/organicmaps#1487]
Thanks to Organic Maps offline data, it easy to find your way around when traveling abroad. Unfortunately airports gates are not well rendered as it is labeled with its name tag. According to OSM wiki "aeroway=gate" is mostly associated with "ref=XXX" and not "name=XXX". [https://taginfo.openstreetmap.org/tags/?key=aeroway&value=gate#combinations](https://taginfo.openstreetmap.org/tags/?key=aeroway&value=gate#combinations)

**Comment by biodranik** [comment]
Thanks! @vng it should be easy to fix in generator: always use ref, and only switch to name when there is no ref.

**Comment by vng** [comment]
https://github.com/organicmaps/organicmaps/pull/1626
