### ISSUE TITLE
Add option to disable location services startup popup

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [organicmaps/organicmaps#1517]
Everytime the app boots and if the location services are disabled a popup appears informing the user to enable the service. After a while this can get a bit annyoing, so I propose let's add a checkbox at least after the 2nd time this appears to be able to disable it and/or add a settings entry making it possible to disable it.

**Comment by biodranik** [comment]
Duplicate of #1128

**Comment by IHateTheProgrammingClass** [comment]
@biodranik Should I close?

**Comment by biodranik** [comment]
Probably yes, it would be easier to track only one.
