### ISSUE TITLE
Bogus truncation of route distance

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1528]
When there is not enough screen space to display route's estimated time & distance (due to font size settings for example) then time & distance get truncated, sometimes producing bogus / misleading results:

Case 1.
![OM-route-distance-00-bug](https://user-images.githubusercontent.com/18434508/140812428-4f20d60e-0a5d-4533-85c8-8660a8a49e02.png)

The actual distance here is 1000m (possible to check by rotating screen).

Case 2.
![OM-route-distance-9km-bug](https://user-images.githubusercontent.com/18434508/140812442-996ae1c7-2183-4fb5-a2c9-48c7234ad65c.png)

Here the output looks legit at the first glance, but the actual distance is **4.9km**! Its not obvious it was truncated and it makes it much worse as it provides wrong information to the user.

Probably cases like that are rare though as they require a certain combination of screen resolution, font size and display size settings (and dpi possibly?).

How to reproduce:
Increase a "display size" setting to be i.e. "large" and / or increase "font size" to e.g. 125%.
Depending on your device it might take a different combination of settings to reproduce or maybe it won't be reproducible at all.
A sure way to reproduce is to use android emulator with a "Nexus S" (480x800 resolution) virtual device and Android 11 image and a "font size" setting "large".

for case 1:
1. put a bookmark at 36.825394, 28.603961
2. download a map if you have to
3. another bookmark at 36.826417, 28.597898
4. build a walking route between the two
5. you should get a route of 1000m length with a first "10" truncated

for case 2:
1. put a bookmark at 36.825394, 28.603961
2. download a map if you have to
3. another bookmark at 36.80212, 28.598841
4. build a walking route between the two
5. you should get a route of 4.9km length with "4." truncated

Expected behavior:
First of all - truncate from the end, not from the beginning! E.g. "4.9km" should become "4.9..." not "...9km". In this case its much easier for the user to understand that the truncation took place.
Ideally find another way to position time, distance and elevation info so there is enough space for everything.
If its not possible then I think that the most important info is distance, next is estimated time and the last one is elevation (so it should be sacrificed first). Ideally it would be possible to tap on the truncated info and a full time - distance - elevation info will be displayed in a pop-up.

Tested on "2021.11.04-2-FDroid-debug".

**Comment by biodranik** [comment]
The best solution here could be to move the Start button down, and use the space above it for the path information. E.g. to use a whole horizontal line above the graph and the Start button.

**Comment by pastk** [comment]
#1700 doesn't solve the issue completely, but at least prevents confusing outputs.

E.g. before:
![OM-route-distance-9km-bug](https://user-images.githubusercontent.com/18434508/146438880-73be0aad-9eaf-479f-ba12-3d1d45dc7d71.png)

After:
![OM-route-distance-9km-bug-fixed](https://user-images.githubusercontent.com/18434508/146438907-6e1359df-a8e2-46f5-9677-1ddc9ddf07e0.png)

**Comment by biodranik** [comment]
Another option is to automatically reduce font size to fit the width. Is there such an option in Android resources?

**Comment by pastk** [comment]
Yep it looks there is a font auto-size option and also an option to auto-scroll the text that doesn't fit - I'll experiment more with it.

**Comment by Jean-BaptisteC** [comment]
Fixed by #5889
