### ISSUE TITLE
When viewing search resoults on map, the bottom buttons are still clickable  

### ISSUE THREAD

**Issue by ShimonHoranek** [organicmaps/organicmaps#1532]
When viewing search resoults on map, the search, bookmarks and 'burger menu' buttons are still clickable.

How to recreate: 
- search for anything
- click on "view on map"
- a bottom bar appears with a "list" button
- click on the white space where the search, bookmarks etc. buttons ussualy are

**Comment by biodranik** [comment]
It reproduces indeed, thanks for reporting it! @rtsisyk it should be easy to catch clicks by the "list" panel, right?
