### ISSUE TITLE
Dark mode glitch with bare rock

### ISSUE THREAD

**Issue by jpds** [organicmaps/organicmaps#1533]
I obversed this strange glitch whilst looking around south-western Iceland with night mode enabled.

Seems to be related to this relation: https://www.openstreetmap.org/relation/11793558

https://user-images.githubusercontent.com/29158971/141000438-9646134a-fffe-408f-9977-bffc63fdb1ae.mp4

**Comment by biodranik** [comment]
@vng did we touch bare-rock recently?
