### ISSUE TITLE
You should commit package-lock.json

### ISSUE THREAD

**Issue by tiziodcaio** [organicmaps/organicmaps#1537]
Remove it from gitignore and commit it... npm suggests it

**Comment by biodranik** [comment]
How does this warning looks like?

**Comment by tiziodcaio** [comment]
https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json

**Comment by biodranik** [comment]
Not the file, the warning :)

**Comment by tiziodcaio** [comment]
> Not the file, the warning :)

So, I'm sorry but as you can see I don't understand what you mean...

**Comment by tiziodcaio** [comment]
Do I missed something?

**Comment by matkoniecz** [comment]
by

> Not the file, the warning :)

they likely meant message that you mentioned

>npm suggests it

**Comment by tiziodcaio** [comment]
So it was a joke? Sorry but I'm not so clever with english...
I'm sorry

**Comment by matkoniecz** [comment]
Not, it was not a joke. They are asking about what exact message you described as "npm suggests it"

What npm displayed which you interpreted as recommendation to commit to file?

Or is it about something mentioned in documentation?

**Comment by biodranik** [comment]
There were no intention to lock the package versions with package-lock.json, because it is not critical at all for now. Even better if the latest versions of all dependencies will be used. That's why I asked if you see any warning when you use it.

Sometimes we don't blindly follow generic recommendations.

**Comment by tiziodcaio** [comment]
Ok I just wanted to warn about it...
