### ISSUE TITLE
FeatureRequest: Use Wit.ai or the ilk to provide speech recognition to the app

### ISSUE THREAD

**Issue by StewAlexander-com** [organicmaps/organicmaps#1539]
Feature Request:

Use wit.ai (https://wit.ai/docs/quickstart) or something like this to add some level of speech recognition to the app...

Just a thought, any opinions?

**Comment by biodranik** [comment]
Aren't these services online-only? For a privacy-focused app we need offline privacy-focused engines.

Another question: do we need them at all?

**Comment by StewAlexander-com** [comment]
Navigation by voice seems to be where we are headed 

But, yeah, its just an idea

**Comment by biodranik** [comment]
Most of the devices already have some built-in keyboards with voice input. It could be way easier to reuse them. These voice inputs are usually already set up by users and trained to their voices.

**Comment by StewAlexander-com** [comment]
How easy / safe is it to interact with the tiny keyboard microphone while operating a vehicle?

Unfortunately sending one's voice to the cloud requires a robust internet connection, also there are real & present security / privacy concerns with this also …

A separate project to create a self-contained non-cloud open source voice API might be useful … it might have to wait if the tech isn't good enough yet, but this might be a decent idea

Then programs just call out to the voice api 

Just a thought I have …

Alexa & Siri are always listening, think this can be improved somehow too

**Comment by StewAlexander-com** [comment]
Regardless it's ok to close this as listening to vocal input is likely outside the scope of this project
