### ISSUE TITLE
[iOS] "Rate this app" dialog redirects to MAPS.ME app on Appstore

### ISSUE THREAD

**Issue by dzintb** [organicmaps/organicmaps#154]
App randomly begs for 5 star rating. I pressed "Rate" (I dont remeber exact text) and was redirected to submit rating on Appstore for MAPS.ME app.

App version - 10.5.1 (installed via Testflight)

**Comment by rtsisyk** [comment]
Thanks for your report! We will update the url after publishing to AppStore.

**Comment by andrewshadura** [comment]
"Rate app" dialog needs a button, "Don’t ever ask me again".
