### ISSUE TITLE
Render parcel pickup lockers

### ISSUE THREAD

**Issue by AlertSubject** [organicmaps/organicmaps#1555]
https://wiki.openstreetmap.org/wiki/Tag:vending=parcel%20pickup;parcel%20mail%20in?uselang=en
Amenity=vending_machine +  vending=parcel_pickup;parcel_mail_in
is used to describe lockers that can be used to receive and send parcels. These things are pretty useful and I find myself searching for them from time to time
Sadly OM doesnt display them as of right now
So my suggestion would be to render them :)

**Comment by 10992-osm** [comment]
Note the current [proposal for an `amenity=parcel_lockers` tag](https://wiki.osm.org/wiki/Proposed_features/amenity%3Dparcel_lockers).
