### ISSUE TITLE
wrong display of some opening_hours

### ISSUE THREAD

**Issue by zorglubu** [organicmaps/organicmaps#1561]
Hello,
I have sometimes a wrong display of opening_hours, ex. this node : https://www.openstreetmap.org/node/1812754636
OMaps displays `Tu-Sa 09:30-:19:00` instead of `Tu-Sa 09:30-13:00,15:00-19:00` 
If I am not wrong, the problem seems to appear when there are several days like `Tu-Sa`, and not with a single day like `Tu` : multiple days and multiple time periods.
The opening hours on this node are from March 2021.

version used 2021.11.04-2-FDroid
data 211022

Thanks for your beautiful app :-)

**Comment by Kazing** [comment]
duplicate of #970 ?

**Comment by biodranik** [comment]
On iOS the time is displayed correctly. So the problem is somewhere in Android Java code.

**Comment by biodranik** [comment]
Yes, it is a duplicate.

**Comment by zorglubu** [comment]
I agree, it's a duplicate of https://github.com/organicmaps/organicmaps/issues/970
sorry.

**Comment by biodranik** [comment]
NP, more examples to test the fix )

**Comment by Kazing** [comment]
Opening hours display is now correct for this node : https://www.openstreetmap.org/node/1812754636
Issue can be closed 

Version : 2021.12.01-4-FDroid
Map Data : 211122

**Comment by zorglubu** [comment]
That's OK. Thanks a lot.
