### ISSUE TITLE
Do not ignore turn restriction for cyclists

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#1563]
based on https://github.com/organicmaps/organicmaps/blob/99c5b878a048b467d1c66cf5a5ff0ce04975c73b/3party/osrm/osrm-backend/features/bicycle/restrictions.feature

> Ignore turn restrictions on bicycle, since you always become a temporary pedestrian.

it appears to be intentional

This is problematic for multiple reasons.

1) navigating and following route is very likely to require sudden changes - like going to sidewalk despite being on left side of roads with two lanes (another two lanes on left going in opposite direction, another lane on right). Because navigation app instructed you to turn left where it is illegal.  What is confusing, dangerous and irritating.

2) switching to being pedestrians is adding extra time, very often going another way without dismounting would be significantly faster

3) switching to being pedestrian in many places is illegal or impossible

Previously reported as https://github.com/mapsme/omim/issues/6743

There should be at least some penalty for that. Maybe even apply them fully on `foot=no` `foot=use_sidepath` `sidewalk=separate` roads.

**Comment by vng** [comment]
@matkoniecz Well, we don't use 3party/osrm/osrm-backend any more. Could you please show us the real example with incorrect bicycle routing in OM. We will investigate it.

**Comment by matkoniecz** [comment]
Try following https://www.openstreetmap.org/relation/6564091 - OM instructs to use road

**Comment by Jean-BaptisteC** [comment]
@matkoniecz can you retry with the latest version?

**Comment by matkoniecz** [comment]
this specific breakage is gone, thanks
