### ISSUE TITLE
UTM coordinates support

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1572]
Osmand and trekarta has it, so the code can be reused for the search and displaying in Place Page.

https://en.m.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system

**Comment by strump** [comment]
I think this code could be ported to OM either from C code [UTM.h](https://github.com/bakercp/ofxGeo/blob/master/libs/UTM/include/UTM/UTM.h) or from Osmand [UTMPoint.java](https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/com/jwetherell/openmap/common/UTMPoint.java), or from [UTMCoord.java](https://github.com/nasa/World-Wind-Java/blob/master/WorldWind/src/gov/nasa/worldwind/geom/coords/UTMCoord.java) used by Trekarta.

**Comment by biodranik** [comment]
C version should be used, to also allow parsing search queries.
