### ISSUE TITLE
Change the behavior when pressing enter during search 

### ISSUE THREAD

**Issue by AlertSubject** [organicmaps/organicmaps#1573]
When im searching for something and have finished typing I tend to press enter to make the keyboard go away
This works in all apps. Just not in this one

Organic maps instead switches from list of search results to the map that displays results

A user that comes from any other app expects to type the search request, click enter and then be shown the search results
And this case the user gets a blank map
Obviously you can just press the list button and get back to the search you just made but this doesn't feel very elegant
Maybe even confusing to new users

Please consider making it more similar to how other apps handle it

**Comment by biodranik** [comment]
iOS hides keyboard

**Comment by AlertSubject** [comment]
> iOS hides keyboard

Android does not

Assuming that this is not intentional then?
