### ISSUE TITLE
Cycling directions ignore foot tunnels

### ISSUE THREAD

**Issue by jpds** [organicmaps/organicmaps#1603]
If you ask the app for cycling directions from Millwall Park to Greenwich Park in London, it'll ignore this foot tunnel which is marked bicycle=dismount: https://www.openstreetmap.org/way/514076578 .

And instead send one on this much longer detour:

![Screenshot_20211122-181703_1](https://user-images.githubusercontent.com/29158971/142915243-1260e185-74f5-4852-aa2a-ca395d969e87.png)

**Comment by biodranik** [comment]
Thanks! I remember this tunnel, you're right, the algorithm should prefer it. Later we'll implement alternate routes, it would be even better.
@vng do we process bicycle=dismount properly?

**Comment by pastk** [comment]
- related to https://github.com/organicmaps/organicmaps/issues/8028
