### ISSUE TITLE
[android][UX] Make POI info like name, address, etc. copyable

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1616]
At the moment some of POI data is copyable, e.g. social network links, e-mail, web site url, etc.
But not the name, description or address.

It'll be great to offer to copy into clipboard upon a long click.

(I don't know the situation with iOS version)

**Comment by pastk** [comment]
I'm working on a PR atm.

**Comment by biodranik** [comment]
iOS also should support that.

**Comment by pastk** [comment]
As a related improvement I suggest to copy name, phone, etc. upon just one long press.

At the moment the user needs to long press first, then a confirmation popup with a copy button will appear, second click on that button will copy the text to clipboard finally. That extra confirmation step seems redundant as copy to clipboard is not some irreversible action. E.g. in Osmand the stuff is copied by one long press - very convenient.

There is one exception of lat/lon field - upon long press a popup with 4 coordinate formats appear and the user can choose one to copy. One option is to leave it as is. 

However its also redundant because the user can select necessary coords format to display by clicking on lat/lon field. After that a long press will copy the format in display to the clipboard - I think that'll be more consistent UX overall.

**Comment by Jean-BaptisteC** [comment]
Now all in place page is copyable except cuisine

**Comment by Jean-BaptisteC** [comment]
@pastk can be closed ?

**Comment by biodranik** [comment]
It's done on iOS, thanks to @kirylkaveryn
