### ISSUE TITLE
[UI] Display total elevation gain and loss in the route preview

### ISSUE THREAD

**Issue by Gumix** [organicmaps/organicmaps#1618]
It would be useful to have an elevation gain and elevation loss in the route preview, in addition to the elevation difference which is currently displayed. Maybe switch between them by clicking on the number, e.g.:
<img src="https://user-images.githubusercontent.com/5719536/143658332-b041e989-f2ed-41a2-9a3b-9a01b1500574.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/5719536/143658344-f5f4121b-43ce-4988-940f-57f2c54c796d.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/5719536/143658339-bfb5099d-0196-4fdb-8469-2090a1432e99.png" width=50% height=50%>

**Comment by pastk** [comment]
I would add it should be a _total_ elevation gain/loss to be really useful.

**Comment by Gumix** [comment]
Implemented in #3062

**Comment by biodranik** [comment]
That implementation should be improved, there are some issues: https://github.com/organicmaps/organicmaps/issues/3477
