### ISSUE TITLE
[search] Searching for "water" miss many water source types - important for hiking use

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1621]
"water" search result only in `type.natural.water.*` like "water", "lake", "reservoir".
But it doesn't result (neither in the list, nor on the map) in "drinking water", "water tap", "spring", "water well", "drinking fountain" types.

Likewise, searching for e.g. "drinking water" will not show "water tap", "spring" etc.

For hiking use its really important to be able to search for all available water sources around.
Maybe we need to maintain a list of synonims for some popular/important search terms?

(it'll be great to distinguish between potable/non-potable water as well by maybe using different icons - but that's a further improvement, first thing a search needs to be fixed)

**Comment by biodranik** [comment]
The list of synonyms is defined in data/categories.txt

**Comment by pastk** [comment]
I propose following changes. Its mainly targeted to outdoors use, but will be an improvement for urban use as well.

Add "Water" to the "categories" list in search screen (in the bottom of the list, in between Entertainment and Hospital maybe).

That "Water" search shall result in all water sources with a likely drinkable water:
```
amenity=drinking_water
amenity=water_point
man_made=water_tap
man_made=water_well
natural=spring
```
Bigger bodies of water like rivers, lakes, ponds etc. should not be included as they are quite big and obvious terrain features on the map anyway (it'll be possible to search for them using their own terms like "lake" still).

A search for "drinking/potable water" shall result in `amenity=drinking_water` only.
As I understand we don't have a [drinking_water=*](https://wiki.openstreetmap.org/wiki/Key:drinking_water) attribute available in OM map files? If we do, then we can add other types with a `drinking_water=yes` to this search.

I don't think that the "water" search should result in confirmed drinkable (`amenity=drinking_water`) sources only, because 
- a lot of other sources are actually drinkable (but not marked) or conditionally drinkable (e.g. after a boil)
- technical water is important in outdoors also (doing dishes, washing, rinsing stuff...)
- there is no obvious way to search for "all water" if the "water" term is reserved for drinkable only

I'll prep the changes in `categories.txt`.

Feedback?
@biodranik

**Comment by biodranik** [comment]
Approved.

**Comment by matkoniecz** [comment]
That was very useful and improved OM and thanks for it, but I have a followup:  

> Stop showing water wells without drinking water like other water sources #4953
