### ISSUE TITLE
Routing bug

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#1633]
OMaps is suggesting a not optimal route. Using last version of iOS and OSM data. From what I saw on OSM, the data on that area (streets, turn restrictions etc.) hasn't changed in the last months.

[Expected behavior:](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=-3.72656%2C-38.51044%3B-3.72607%2C-38.51502#map=18/-3.72631/-38.51272)
![image](https://user-images.githubusercontent.com/86851490/143770779-cf85350c-c96b-40f7-a221-a4cf76de2767.png)

OMaps suggestion:
![image](https://user-images.githubusercontent.com/86851490/143770919-813a870a-45d2-48a0-92cd-75979c1d82e4.png)

**Comment by vng** [comment]
The app now prefers 60 km/h streets, but with 2! more maneuvers, instead of direct 40 km/h road.
Make additional penalty for maneuver is in our plans for routing.

**Comment by matheusgomesms** [comment]
> Make additional penalty for maneuver is in our plans for routing.

It makes, sense, that is great! In this case, specifically, there is a ["give way" sign](https://www.openstreetmap.org/node/7617975023), and a [traffic light](https://www.openstreetmap.org/node/477358138), so not sure if these nodes affect routing as well.

**Comment by vng** [comment]
They don't actually, and it's in our plans to implement.

**Comment by RedAuburn** [comment]
correct route is now generated
![image](https://github.com/organicmaps/organicmaps/assets/26939824/3c986634-12ea-4f2f-a9a7-e96e59a33bda)
