### ISSUE TITLE
[qt] The desktop app crashes when launched in russian locale

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1638]
```
organicmaps$ LC_ALL=ru_RU.utf8 ../omim-build-debug/OMaps -data_path ./data

TID(3) ASSERT FAILED
drape/texture_manager.cpp:104
CHECK(strings::to_double(token, d)) 
OMaps: /home/pastk/dev/organicmaps/drape/texture_manager.cpp:104: dp::{anonymous}::ParsePatternsList(const string&, ToDo)::<lambda(const string&)>::<lambda(const string&)> [with ToDo = dp::TextureManager::Init(ref_ptr<dp::GraphicsContext>, const dp::TextureManager::Params&)::<lambda(const buffer_vector<double, 8>&)>; std::__cxx11::string = std::__cxx11::basic_string<char>]: Assertion `false' failed.
```

It works fine with `en` locale though.
Looks like parsing of doubles can't handle the comma "," decimal separator used in `ru` locale.

**Comment by pastk** [comment]
@biodranik

**Comment by biodranik** [comment]
Please make sure that you don't have LC_ALL set already in your shell, it overrides everything. Use `LANG=ru_RU.utf8 ../omim-build-debug/OMaps` to override the locale.

**Comment by pastk** [comment]
It starts now, thanks!

Though there is absolutely no change in the app, e.g. the app itself is not translated and e.g. POI names are still shown both in en (first) and ru (second).

Moreover there is no change in the search behavior, e.g. the reason I wanted to start it in ru locale was to test #1621 - when "пит" is entered into the search box it should show a "питьевая вода" search suggestion - but it doesn't (works for en "drink"->"drinking water"). Also when entered manually "питьевая вода" doesn't search for drinking water types.

So I guess the desktop app doesn't support any localization ATM.

**Comment by biodranik** [comment]
On Mac, the map language changes when LANG variable is changed (after unset LC_ALL). It should work also on Linux. Do you have

**Comment by pastk** [comment]
> On Mac, the map language changes when LANG variable is changed (after unset LC_ALL). It should work also on Linux.
> 
> What is displayed in logs? Does it show ru?

I nailed it finally!
The issue was I had a `LANGUAGE=en_US` env var set. Apparently it has a precedence over `LANG`.

Now when I start `LANGUAGE=ru_RU ../omim-build-release/OMaps -data_path ./data` the map is shown in Russian (and it appears in the logs too). The search works as expected now, except selecting a search suggestion doesn't do anything (its not copied in the search input field).

**Comment by biodranik** [comment]
> except selecting a search suggestion doesn't do anything (its not copied in the search input field).

Did it work before overriding? Should be easy to fix IMO.

**Comment by biodranik** [comment]
It would be great to document locale vars for developers.

**Comment by pastk** [comment]
> > except selecting a search suggestion doesn't do anything (its not copied in the search input field).
> 
> Did it work before overriding? Should be easy to fix IMO.

Nope, it did not work in en locale either.

**Comment by pastk** [comment]
Now that's really weird - the app shows the russian map always even if I start it with `LANGUAGE=en_US` (and in the log there is `LOG TID(1) INFO     0.131926 search/processor.cpp:232 SetPreferredLocale() New preferred locale: en`)
When I click "edit place" it shows both ru and en names as containing russian, though before it was russian and english accordingly.
Is it possible the app had overwritten the map data when it was in ru locale? Or maybe it stores the locale is some config?

**Comment by biodranik** [comment]
No, locale is not stored. Please double check all env vars, and try to use LANG

And let's close this issue after updating documentation.

**Comment by biodranik** [comment]
Clicking search results works on Mac, they are properly inserted into the search field.

**Comment by pastk** [comment]
> No, locale is not stored. Please double check all env vars, and try to use LANG

LANG works only if I unset manually LANGUAGE first, so LANGUAGE seems to have a higher priority. Hence I suggest to add LANGUAGE to the docs.

> And let's close this issue after updating documentation.

**Comment by pastk** [comment]
The issue could be closed now.
