### ISSUE TITLE
No "Save maps to" option in options

### ISSUE THREAD

**Issue by oldwizard1010** [organicmaps/organicmaps#1647]
there is no "Save maps to" option in options, also "Bookmarks path" is missing
Нет настроек пути сохранений\загрузок, но они точно были в других ипостасях этого приложения
(wanted to move downloaded maps on sd card from "Maps" to this one) )

**Comment by biodranik** [comment]
1. Due to Android 11 scoped storage changes, all data is now stored internally and can't be accessed.
2. We don't promise compatibility with other apps. Why do you need to reuse/move old maps data? Download a fresh one.

**Comment by oldwizard1010** [comment]
I use fork (https://f-droid.org/packages/com.github.axet.maps) from the original Maps.me and have my maps on sd card (Android 5), wanted to just move already downloaded to OrganicMaps folder.

2 - i mean, i have no "move to" settings at all, even to other folder on internalStorage

well, actually i found, that it appears for a moment, and then instantly dissapears, was able to screenshot this
 
was
[https://sun9-81.userapi.com/impg/FkLyGmIpPG0n4xLorc9apXbhYczM58KANRdFvA/9EVL0_6x0Ts.jpg?size=1080x1854&quality=96&sign=5739d95db932fe5da1d423ac56c90a15&c_uniq_tag=qW0DzM6jAeOaddoHIuDky9m01EIL_pQlIqa3Q5QegSQ&type=album](url)

disappeared
[https://sun9-68.userapi.com/impg/bQHvbjAtdao0xfJtFLGRvHpLlzyoSG0POWynEQ/rAbg9oY9VWw.jpg?size=1080x1869&quality=96&sign=8f62bba44f09e37eb4942d37ad12ba62&c_uniq_tag=dBDdMJGqyE32szeXX14GAnlS8_79Q4C-pJmFN5YhYL4&type=album](url)

**Comment by biodranik** [comment]
Sorry, we do not promise compatibility and support for maps from other apps. It should not work, because the maps format is constantly changed and updated by us. Please re-download maps in Organic Maps, or download them manually from here if you can't do it for some reason from the app (why?): https://mirror.organicmaps.app/mirror

You can also import bookmarks into Organic Maps from other apps.

**Comment by biodranik** [comment]
Regarding SD-card, after installing OM, you can choose SD-card storage in settings. If it is not available for any reason, please send us logs as I described above.
