### ISSUE TITLE
Inappropriate "toilet" search results formatting; toilets=yes not shown in POIs Place Page

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1648]
![image](https://user-images.githubusercontent.com/18434508/144229842-340875a1-2cf8-4351-9686-af66dcb6a648.png)
That [restaurant POI](https://www.openstreetmap.org/node/5751482221) has `toilets=yes` and `cuisine=turkish` tags.
Though "Toilet * Turkish" subtitle doesn't look appropriate. "Restaurant * Toilet" would be much better.

Second thing is that the POI itself doesn't have any info about toilets shown. It'll be great to have an icon shown similiar to e.g. `wheelchair=yes` icon we have already.
![image](https://user-images.githubusercontent.com/18434508/144229883-62c23012-cfd5-499f-a522-0a68d2057faa.png)

**Comment by dvdmrtnz** [comment]
https://www.openstreetmap.org/node/5751482221#map=19/36.56757/30.55651
