### ISSUE TITLE
Android status bar hard to read in navigation

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#1654]
When navigating during the day, the status bar becomes hard to read if the road name is shown as can be seen in the screenshot bellow. Night mode is okay as the road name is displayed on a dark background.

I don't know if it matters but my phone has the system dark mode enabled.

| Day | Night |
|-|-|
| ![Screenshot_20211204-153042_Organic_Maps](https://user-images.githubusercontent.com/80701113/144719388-0ec41ce5-cd3a-4e69-9072-5743b52292e5.png) | ![Screenshot_20211204-182941_Organic_Maps](https://user-images.githubusercontent.com/80701113/144719391-5f947134-0b0d-410b-adda-9028184d6c62.png)

- OS: Android 9
- Organic Maps version: 2021.11.04-2-F-Droid
- Data Version: 211022

**Comment by biodranik** [comment]
Are you talking about Square Bouligrin at the top? What is wrong with it? How do you propose to fix it?

**Comment by arnaudvergnet** [comment]
Just above the square name, where we usually read the date and notification icons. In day mode it is written in white over a light background. When not in navigation or when there is no street name written at the top, having a light status bar is OK because there is the map behind and not a white background.

A possible fix would be to change the statusbar color when a street name is displayed, or make the status bar opaque.
