### ISSUE TITLE
Layers button clickable behind navigation instructions

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#1655]
In navigation mode, the layers button is still accessible behind the turn by turn instructions. It would be better to remove the button in navigation mode, or move it bellow the instructions next to other buttons.

https://user-images.githubusercontent.com/80701113/144720049-f6fe4290-7515-43cb-a1b2-50848fc4ed9e.mov

- OS: Android 9
- Organic Maps version: 2021.11.04-2-F-Droid
- Data Version: 211022

**Comment by biodranik** [comment]
Let's start with removing/hiding the layers button. When we implement several different map styles, we'll return it back, but maybe hidden in the bottom nav settings bar.
