### ISSUE TITLE
Prominent display of vandalism

### ISSUE THREAD

**Issue by 10992-osm** [organicmaps/organicmaps#1658]
With the most recent map update, users of maps of GB are greeted by the label Republic of Pandora over Ailsa Craig.

See https://www.openstreetmap.org/changeset/114341892, https://omaps.app/ctfiTcGWj5/Republic_of_Pandora, picture:

![Screenshot of Organic Maps showing the "Republic of Pandora"](https://user-images.githubusercontent.com/83511672/144727913-58b772b0-605a-49da-9798-dade97076b98.png)

I'm not sure whether anything ought to be done by you, given the vandalism has been corrected, but it stands out somewhat.

**Comment by vng** [comment]
Well, turned out that data snapshot got this vandal change. Probably, we can make some mechanics to filter such cases in client app code.
