### ISSUE TITLE
House number overlaps parking icon (rendering issue)

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1665]
https://www.openstreetmap.org/#map=19/60.26318/24.84968

| Example 1 | Example 2 |
|-|-|
| ![image](https://user-images.githubusercontent.com/170263/144890255-de66a74b-5adf-49cd-869b-8d05af425510.png) | ![image](https://user-images.githubusercontent.com/170263/144890275-f5add76d-012e-41ff-9eb8-e7a54a37e6d7.png) |

**Comment by dvdmrtnz** [comment]
Looks fine in latest version ⁦2023.09.19-15⁩

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/2fc3d6fc-31a0-40b7-bdba-19d7299a697a" width="310"/>
