### ISSUE TITLE
Cuisine type search works only with english words

### ISSUE THREAD

**Issue by csidirop** [organicmaps/organicmaps#1679]
Here is an issue I have for long time. 
The seach for editing or adding the cuisine type (not sure if thats the correct term...) or what type of meals a restaurant is serving finds only hits for the english terms of the different cuisines:

![Screenshot_20211209-144455_Organic_Maps-cmp](https://user-images.githubusercontent.com/43964592/145412950-95bb9cc8-2ac6-47bf-8dcf-d0368516664f.png)
![Screenshot_20211209-145213_Organic_Maps-cmp](https://user-images.githubusercontent.com/43964592/145412972-33c06684-f043-4eaa-b6ec-bb45321a3d2a.png)
![Screenshot_20211209-145215_Organic_Maps-cmp](https://user-images.githubusercontent.com/43964592/145412979-b39ead11-cb62-47e1-a0ee-1e2eab73a828.png)
![Screenshot_20211209-145226_Organic_Maps-cmp](https://user-images.githubusercontent.com/43964592/145412983-8922fe9f-a2cd-4695-ad59-3bd1ea30c2cb.png)

while e.g. the search for objecttypes works like expected (and even better, finding similar results):
![Screenshot_20211209-145141_Organic_Maps-cmp](https://user-images.githubusercontent.com/43964592/145413007-58f5c9b0-1a08-45f7-b402-f24faaa87dca.png)
![Screenshot_20211209-145150_Organic_Maps-cmp](https://user-images.githubusercontent.com/43964592/145413009-f9217279-7f8d-406d-a311-f18ba8123f5b.png)

**Comment by csidirop** [comment]
Hi again, this issue is still present. Any idea where the problem is? Is it the search? Does the search only checks the English translation?
Maybe I could look into into it if you give me a hint.

**Comment by pastk** [comment]
Looks like it was fixed just recently in #2921!
