### ISSUE TITLE
No maps download

### ISSUE THREAD

**Issue by JGRvanN** [organicmaps/organicmaps#1693]
it is not possible to download any map, i just get the message that the download has "Failed"

**Comment by biodranik** [comment]
Do you use any firewall or network filter? Did you try to download over WiFi or Cellular connection? Please provide more details: your device, OS, app version.

**Comment by JGRvanN** [comment]
Hi Alexander, thanks for the quick response! After reinstalling the app the
issue has sorted itself out for now.
I have no idea what caused it. I have no firewall or any filter...

Any way, I was able to download all the maps I need after the reinstal!

Regards,
Van

**Comment by biodranik** [comment]
Interesting, did you choose SD-card in the app's settings when it didn't work?
