### ISSUE TITLE
Diacritics rendering issues - Bangla

### ISSUE THREAD

**Issue by Oymate** [organicmaps/organicmaps#1723]
This place is being rendered weird:
22.334382, 91.829363

**Comment by biodranik** [comment]
What is weird there? I don't see any issues. Can you please provide a screenshot?

**Comment by Oymate** [comment]
It should say চট্টগ্রাম
![Imagepipe_3](https://user-images.githubusercontent.com/50857856/147377947-5a46d555-022b-4bb4-93d5-a37ac5b7d706.jpg)
![Imagepipe_4](https://user-images.githubusercontent.com/50857856/147377950-424abbd0-8590-44ee-a808-8966aa8529d6.jpg)

**Comment by Oymate** [comment]
Below is correct

**Comment by biodranik** [comment]
Thanks for the details! It looks like a bug with rendering diacritics, similar to #460 and #516

**Comment by Oymate** [comment]
It seems like most OSM doesn't have harfbuzz support which is the main problem

**Comment by esdnm** [comment]
Rendering of Bengali fonts is still problematic ![Screenshot_20240530-011828~2.png](https://github.com/organicmaps/organicmaps/assets/90970080/beddf889-fab9-49c6-adb6-d8b2629c7070)

**Comment by biodranik** [comment]
This should be fixed when #4281 is finished.

**Comment by biodranik** [comment]
Rendering with Harfbuzz fix looks good:

<img width="217" alt="выява" src="https://github.com/organicmaps/organicmaps/assets/170263/94d37cda-d628-4a2c-bd58-15567d0fea2a">

**Comment by biodranik** [comment]
Before | After Harfbuzz integration
-------|-------
<img width="1089" alt="image" src="https://github.com/organicmaps/organicmaps/assets/170263/6681665e-5607-494f-98fb-90f4a1907c06">|<img width="1089" alt="image" src="https://github.com/organicmaps/organicmaps/assets/170263/51cb79ec-41c4-406e-b7eb-0c00b9e4f89c">
