### ISSUE TITLE
[android] Remove x86_64 and x86 from F-Droid and Beta APKs

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#1741]
Intel-based mobiles phones don't exist in the world. Zero. Chromebooks are not rare, especially in universes, but they don't use F-Droid and/or Beta APKs. Please remove x86 and x86_64 from F-Droid and Beta.

CC: @biodranik

**Comment by pastk** [comment]
There are some Intel Atom based Android smartphones and tablets, e.g. from Lenovo and Asus.
https://www.kimovil.com/en/list-smartphones-by-processor/intel-atom-z3560
https://phonedb.net/index.php?m=device&id=10427&c=asus_zenpad_10_z300cnl_global_td-lte_32gbhttps://phonedb.net/index.php?m=device&id=9401&c=asus_zenfone_zoom_zx551ml_td-lte_64gb

Though they're rare indeed and it seems like Intel has withdrawn from that market.

**Comment by pastk** [comment]
It looks like F-Droid allows separate apks for different arches though, e.g. here is separate arm64-v8a and armeabi-v7a for "Fennec F-Droid" app.

![f-droid_arches](https://user-images.githubusercontent.com/18434508/147506171-b0614cb7-6907-4ac8-b5c2-60a05ca91fb1.jpg)

It will be nice to have separate apks if it will provide significant size savings.

**Comment by rtsisyk** [comment]
> There are some Intel Atom based Android smartphones and tablets, e.g. from Lenovo and Asus. https://www.kimovil.com/en/list-smartphones-by-processor/intel-atom-z3560 https://phonedb.net/index.php?m=device&id=10427&c=asus_zenpad_10_z300cnl_global_td-lte_32gbhttps://phonedb.net/index.php?m=device&id=9401&c=asus_zenfone_zoom_zx551ml_td-lte_64gb
> 
> Though they're rare indeed and it seems like Intel has withdrawn from that market.

No more Intel phones. Zero. The only one thing that requires x86 is Android Emulator on x86.

**Comment by biodranik** [comment]
We have at least 80 Chromebook users in GP. There are no other statistics about Intel arch devices in GP, but I personally received support feedback from several users with some old Intel devices.

Nobody complains so far, so let's postpone this issue. Maybe we can drop Intel for fdroid when AA with min API 23 will be ready. Dropping it in betas is not a good idea, because of Chromebooks.

**Comment by rtsisyk** [comment]
Replaced by #6198
