### ISSUE TITLE
Background dim for bottom menu appearing too late

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#1744]
When opening the bottom menu, the background dim effect appear too late. It appears when the menu is fully open instead of when the menu starts to open. This makes the background flash when swiping down the menu then up again. It also allows users to click on the menu, then quickly click on a feature on the map to open both the feature information page and the menu.

Both bugs can be found in the following recording:

https://user-images.githubusercontent.com/80701113/147409006-d70127fd-bab2-457b-977a-1812ea8e988e.mp4

- OS: Android 9
- Organic Maps version: 2021.12.01-4-F-Droid
- Data Version: 211122

**Comment by starsep** [comment]
> It also allows users to click on the menu, then quickly click on a feature on the map to open both the feature information page and the menu.

I think it is caused by the fact that `onTouchEvent` in `FadeView` is not called while `FadeView` is being animated by `animate`.
Changing to a different animation API in `FadeView` makes it react to touch events.
```java
  public void fadeIn()
  {
    UiUtils.show(this);
    ValueAnimator animation = ValueAnimator.ofFloat(0.0f, FADE_ALPHA_VALUE);
    animation.setDuration(getResources().getInteger(DURATION_RES_ID));
    animation.addUpdateListener(valueAnimator -> setAlpha((Float)valueAnimator.getAnimatedValue()));
    animation.addListener(mFadeInListener);
    animation.start();
  }

  public void fadeOut()
  {
    ValueAnimator animation = ValueAnimator.ofFloat(getAlpha(), 0.0f);
    animation.setDuration(getResources().getInteger(DURATION_RES_ID));
    animation.addUpdateListener(valueAnimator -> setAlpha((Float)valueAnimator.getAnimatedValue()));
    animation.addListener(mFadeOutListener);
    animation.start();
  }
```

For testing purposes is useful to increase `anim_default` value.
Unfortunately after this change it's still buggy but I think it's some start.

**Comment by arnaudvergnet** [comment]
Fixed by https://github.com/organicmaps/organicmaps/pull/2248
