### ISSUE TITLE
Bottom menu consistency on Android

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#1745]
Each bottom menu behaves slightly differently. These are all minor issues but could help in improving the app's consistency on Android.

- Feature information menu has a grey arrow indicating it can be swiped, options menu does not, layers menu has an arrow facing down on the right, and navigation menu has an other arrow with a different style.
- Map layers menu does not have the same style as others, the title's font is thinner and the separator is a single line, instead of using elevation for a card like effect.
- Map layers and options menu both dim the screen, but not by the same amount.
- Navigation menu cannot be swiped up or down, while others can.

| Map layers menu | Options menu | Feature menu | Navigation menu |
|-|-|-|-|
| ![Screenshot_20211226-141817_Organic_Maps](https://user-images.githubusercontent.com/80701113/147409304-63c92b45-04f0-450d-b616-204fd7745e8a.png) | ![Screenshot_20211226-141829_Organic_Maps](https://user-images.githubusercontent.com/80701113/147409307-b152b1f9-667b-466c-abe0-05df51cd6d94.png) | ![Screenshot_20211226-141823_Organic_Maps](https://user-images.githubusercontent.com/80701113/147409305-5d03f0d4-dae1-486b-b27e-257619ea1420.png) | ![Screenshot_1643105542](https://user-images.githubusercontent.com/80701113/150957340-3b10dd11-eed6-45d6-a713-355d066d0ff2.png) |

- Map layers and option menu do not use the same opening animation. As they both behave the same, they should animate the same. As you can see in the following recording, layers menu appears above the navigation bar and move faster.

https://user-images.githubusercontent.com/80701113/147409291-96a6b971-c45c-4b42-bc74-a5acf71dd585.mp4

**EDIT:** added navigation menu

- OS: Android 9
- Organic Maps version: 2021.12.01-4-F-Droid
- Data Version: 211122

**Comment by biodranik** [comment]
Thanks! Can you please summarise all necessary changes that you expect from developers?

**Comment by arnaudvergnet** [comment]
I would say add the grey arrow indicator on all the different menus. Make the layers menu use the same menu component as the one used for the options to ensure consistency (but only keep the layers part of the content).

If done right, making those changes should simplify the code as well.

**Comment by arnaudvergnet** [comment]
Updated the issue to add the navigation menu.

**Comment by biodranik** [comment]
You are correct. It would be great to simplify all this code, keeping in mind that:
1. The main bottom bar can be removed in the favor of floating buttons.
2. The Place Page is too heavy and complex now and should be greatly simplified, to allow an easy adding/editing of many additional OSM data fields.

**Comment by biodranik** [comment]
Let's discuss the layers/styles menu together @vng @rtsisyk @pastk 

1. We need layers for the future when we add cycling, hiking, city walking, driving map styles/layers.
2. There is absolutely no reason to have it in two places: in the bottom right menu and on the top left button.
3. From a UX point of view, users need two touches to select a different layer in both current implementations.
4. Bottom right option is more convenient to use by one hand. So we can safely remove the top left layers button.
5. When we replace the bottom buttons bar with floating buttons, there still be a menu button where users can switch layers.

What do you think?

**Comment by pastk** [comment]
The menu button is better for one-handed use, but could become overloaded with options (when we have more layers in addition to current two overlays).

A separate button is cleaner and more cohesive from UX-perspective as it contains layers only at the expense of using extra screen space. We can move it to some other place to make more accessible for one-handed use.

**Comment by biodranik** [comment]
Menu button can expand into anything, showing any amount of additional, not frequently used buttons. The basic idea is to have only the most frequent buttons on top of the map.

**Comment by arnaudvergnet** [comment]
Found yet another bottom sheet implementation. This one is used in a lot of places: `BookmarkCategoriesFragment`, `BookmarkListFragment`, `DownloaderAdapter.ItemViewHolder`, `ProfileFragment` and `PlacePageButtons`. They all use the class `BottomSheetHelper` to create the menu.

The good thing is all menus look the same and creating a bottom sheet is quite easy. The less good thing is this implemntation relies on the library [`com.cocosw:bottomsheet:1.5.0@aar`](https://github.com/soarcn/BottomSheet) which is not maintained anymore. Here are some notes from its author:

> Google introduced official bottomsheets implementation in Support library 23.2.0,thus this library is no longer activly being developed. I will continuely fix defects been found and accept good PR but No more new feature will be developed. Thanks for your support!

**Comment by arnaudvergnet** [comment]
> @arnaudvergnet thanks for discovering it! Can you please help with migrating the code to the officially supported Google library?

Sure I will see what I can do. So you want to migrate from [`com.cocosw:bottomsheet:1.5.0@aar`](https://github.com/soarcn/BottomSheet) to `BottomSheetBehavior` or do you have another idea in mind?

**Comment by biodranik** [comment]
Yes, if BottomSheetDialogFragment already does properly what was done before by a third-party wrapper.

**Comment by arnaudvergnet** [comment]
From what I could find, Android's default BottomSheet does not work exactly like the [`com.cocosw:bottomsheet:1.5.0@aar`](https://github.com/soarcn/BottomSheet) dependency. BottomSheet expects a regular layout file, while `com.cocosw:bottomsheet:1.5.0@aar` expects a menu. But I found the library [BottomSheetMenu](https://github.com/Kennyc1012/BottomSheetMenu) which wraps a BottomSheet to add this feature. 

So here are our choices:

1. Keep the [current dependency](https://github.com/soarcn/BottomSheet) (unmaintained)
2. Use the new [BottomSheetMenu](https://github.com/Kennyc1012/BottomSheetMenu) library (maintained).
3. Implement this feature from scratch and create our own BottomSheetMenu component.
4. Stop using menus and think of another way to create bottom sheet menus.

For solution 1 and 2, we will need to use another component for the place page, layers and main menu as they display complex layouts and not simple menus. Solution 3 and 4 will allow use to write a generic component to be used everywhere in the app to ensure consistency, but will require more development and maintenance work. Maybe more experienced Android developers will find a better solution.

What do you think would be the best idea?

**Comment by biodranik** [comment]
Thanks for the details! Why do we need the 3party menu support for BottomSheet? What are the main reasons? Trying to understand the point (4).


I would stick with using Google's default library + our own, simple implementation, to focus on these goals:
1. Avoid 3party dependencies (they may break or become unsupported, they often add unnecessary overhead).
2. Keep our code as simple as possible (fewer lines of code = fewer bugs + more battery capacity).

**Comment by arnaudvergnet** [comment]
I also want to avoid using 3parties, but I could not find an easy way to use menus in a bottom sheet. Google's default bottom sheet is very simple and only accepts regular layouts. But the current implementation in OM uses menus to describe the content of the bottom sheet. This menu is then converted to a regular layout by the 3party library.

So if we want to remove external libraries, we either need to convert menus to layouts ourselves, or find another way to describe the content of bottom sheets (point 4).

**Comment by arnaudvergnet** [comment]
Menus in xml simply define text and icons, not the layout. So it is simpler to use this and have the 3party convert it to a layout rather than create the layout manually. This also ensures consistency and makes sure every menus displayed in a bottom sheet looks the same. If we were to create layouts manually, we would need to ensure every item in menus have the same font size, margins, etc.

Doing this programmatically would also ensure consistency, but we will have to think of a way of doing this in the most efficient way possible.

**Comment by biodranik** [comment]
How many menus are there now? Two? One with layers, another with layers + vertical menu items? It should be easy to implement, no? Create two layouts, one for layers, another for the menu.

**Comment by arnaudvergnet** [comment]
The only bottom sheets using the menu method are the ones mentioned in https://github.com/organicmaps/organicmaps/issues/1745#issuecomment-1038755374 because they behave like a context menu.

The ones in https://github.com/organicmaps/organicmaps/issues/1745#issuecomment-1034260077 all use a custom layouts and have consistency issues.

It would be nice to find a way to create all those bottom sheets in a similar way, with or without menu items and with or without custom layouts.

**Comment by biodranik** [comment]
All these examples are completely different cases, with different UI and UX. Why do you want to make them the same?

**Comment by arnaudvergnet** [comment]
Except for the place page and the navigation menu, those are all modal bottom sheet so they should behave the same. In some cases you only have menu items, layers menu only has a custom layout and in the case of the main menu you have both. So if we want to keep the current UX, it would be nice to have a way to create all those modal bottom sheets the same way.

I agree that the place page and the navigation menu should be treated differently.

Maybe I misunderstood something so feel free to correct me. I am currently making some experiments to try different methods.

**Comment by biodranik** [comment]
Google's standard implementation allows creating all bottom sheets in the same way, right? Their content is different in each case:
- Layers (this layout can be shared and reused)
- Main menu
- Place Page
- Navigation menu

Please correct me if I'm wrong, but I really don't see the value from some "common menu" wrapper on top of the standard bottom sheet.

**Comment by arnaudvergnet** [comment]
> Please correct me if I'm wrong, but I really don't see the value from some "common menu" wrapper on top of the standard bottom sheet.

I made a draft PR where I explain in more details how I plan to fix this issue https://github.com/organicmaps/organicmaps/pull/2248. I hope this answers your question.

**Comment by arnaudvergnet** [comment]
There is one thing left before closing the issue: adding the sheet handle to the modals, just like in the place page and the navigation menu.

**Comment by biodranik** [comment]
@arnaudvergnet What do you think about this error in logs?
```
07-10 20:41:52.063 W/BottomSheetBehavior(20223): Cannot set state: 5
```
