### ISSUE TITLE
Search funeral_directors no results

### ISSUE THREAD

**Issue by wemissyou** [organicmaps/organicmaps#1748]
So yeah I don't want to be spooky but yes as the title although funeral_directors are mapped searching the world funeral doesn't show any results!

**Comment by pastk** [comment]
`shop-funeral_directors` is missing in `data/categories.txt`.

**Comment by wemissyou** [comment]
Also graveyard and cementery should both give the same results when searching just for convenience

**Comment by pastk** [comment]
> Also graveyard and cementery should both give the same results when searching just for convenience

That should work as they're listed as search synonyms for English:
```
amenity-grave_yard|landuse-cemetery
en:Graveyard|cemetery
```
Do you mean it doesn't work in some language other than English?
