### ISSUE TITLE
[iOS] Remove "Discovery" button

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#175]
<img width="900" alt="Screenshot 2021-02-20 at 23 35 56" src="https://user-images.githubusercontent.com/1799054/108607920-7cdc3780-73d4-11eb-8888-09ecc35fa68e.png">
<img width="900" alt="Screenshot 2021-02-20 at 23 36 04" src="https://user-images.githubusercontent.com/1799054/108607921-7e0d6480-73d4-11eb-9ef2-af2d99deb7cc.png">

**Comment by biodranik** [comment]
Надо не просто убрать, а заменить на кнопку "загрузить карты"

**Comment by rtsisyk** [comment]
Не надо посередине приложения ставить кнопку загрузить карты.
