### ISSUE TITLE
Display drag lifts on the map

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#1758]
I noticed the map shows ways tagged as `aerialway` such as `gondola` or `chair_lift`, but ignores [drag lifts](https://wiki.openstreetmap.org/wiki/Tag:aerialway%3Ddrag_lift). These are usually tagged as `aerialway=drag_lift`, `aerialway=t-bar`, `aerialway=j-bar`, `aerialway=platter` or `aerialway=rope_tow`.

There is also a less common type used for children: the [magic carpet](https://wiki.openstreetmap.org/wiki/Tag:aerialway%3Dmagic_carpet), tagged as `aerialway=magic_carpet`.

It would be really useful to add those as they are very common near where I live.

You can find some here: https://www.openstreetmap.org/#map=18/42.69961/1.81339

| OM | Vespucci |
| - | - |
| ![Screenshot_20211230-205559_Organic_Maps](https://user-images.githubusercontent.com/80701113/147784199-f8159c03-193e-481f-a9f9-4897944810ab.png) | ![Screenshot_20211230-205546_Vespucci](https://user-images.githubusercontent.com/80701113/147784182-ff009302-03fc-43b1-b287-a714f93758ec.png) | 

- OS: Android 9
- Organic Maps version: 2021.12.01-4-F-Droid
- Data Version: 211122

**Comment by pastk** [comment]
They're being displayed
though some of them are mapped as footways (and hence displayed as such) with `conveying=yes` which OM doesn't support atm (e.g. https://www.openstreetmap.org/way/265421807)
![image](https://github.com/organicmaps/organicmaps/assets/18434508/a4f6d7ab-047d-40c5-b3c7-fe60013661c7)
