### ISSUE TITLE
Show ski piste name

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#1759]
It would be really helpful to see ski piste names in OM. Right now, we have the piste ways with colors depending on the difficulty which is nice, but having the names displayed would be even better. 

According to the [wiki](https://wiki.openstreetmap.org/wiki/Piste_Maps), pistes are ways with the tags `piste:type` and `piste:difficulty` (and more but these are the basics). If pistes are also used as tracks during other seasons, they are tagged `highway=track` as well. In that case, OM shows the piste name and draws the way dashed. But if a way only has the piste tags, the name will not be shown and the way will be drawn solid. Names are tagged as `name`, but if it is also a track, it may have the `piste:name` tag to differentiate the piste name from the track name.

In the following screenshot, _Boulevard de la griole bas_ is a piste and a track, while the blue line is only a piste.

![Screenshot_20211230-212012_Organic_Maps](https://user-images.githubusercontent.com/80701113/147786014-5bd2597f-05e1-464f-b7a4-800fe87fc24d.png)

Here is the link to the piste/track: https://www.openstreetmap.org/way/207012274#map=15/42.6941/1.8020

Here is the location of the piste only (it is not displayed in OSM default renderer, but can be seen in OM and Vespucci): https://www.openstreetmap.org/#map=18/42.69855/1.81307

This would really help users find their way up in the mountains while skiing.

- OS: Android 9
- Organic Maps version: 2021.12.01-4-F-Droid
- Data Version: 211122

**Comment by VladimirMorozov** [comment]
Displaying **ref** number along a name is also important, that's what you often see on signs and pocket paper maps.

**Comment by VladimirMorozov** [comment]
@vng @pastk 
Are ref numbers included? Should I open a separate issue? It's important to have them since you often don't even know how to pronounce the name and your fellow skiers may use only numbers as they are usually printed directly on the map, while the names are in legend. You won't be able to communicate without ref numbers.

**Comment by biodranik** [comment]
@VladimirMorozov please create a separate issue with some rendering examples from other popular apps that draw both name and ref.

1. First, refs should be stored in features.
2. Second, the renderer should be updated to extract them and draw near the piste name.
