### ISSUE TITLE
[iOS] A crash on attempt to modify the route

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#176]
1. Create a route
2. Click "Manage route"
3. Swap the starting point and destination and/or click done

<img width="900" alt="Screenshot 2021-02-20 at 23 38 27" src="https://user-images.githubusercontent.com/1799054/108608003-eeb48100-73d4-11eb-9de6-8bad1a2b8b7e.png">
<img width="1552" alt="Screenshot 2021-02-20 at 23 39 19" src="https://user-images.githubusercontent.com/1799054/108608005-efe5ae00-73d4-11eb-96dc-893255b01aa0.png">

```
    guard let contents = layer.contents else {
      return snapshotView(afterScreenUpdates: true)!
    }
```

**Comment by vng** [comment]
Can't reproduce on latest master.
- Still relevant?
- Device or simulator?

**Comment by rtsisyk** [comment]
This was a simulator bug.
