### ISSUE TITLE
Display aerial way name

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#1760]
Aerial ways are searchable and we can long press to select them, but we cannot find them by looking for their name on the map.

It would be really helpful if the names could be added the same way road names are displayed. 

Here is an example lift: https://www.openstreetmap.org/way/749366976#map=14/43.5572/1.4466

- OS: Android 9
- Organic Maps version: 2021.12.01-4-F-Droid
- Data Version: 211122

**Comment by biodranik** [comment]
Do they all have a name like in your example?

**Comment by arnaudvergnet** [comment]
All the ones I've checked have a name, but it might be missing in some cases (like roads sometimes do not have a name).

You can find more examples in this area : https://www.openstreetmap.org/#map=16/42.6986/1.8126

**Comment by pastk** [comment]
It was fixed already, names should be displayed at higher zoom levels (e.g. cable_car from z15-).
