### ISSUE TITLE
Name directions instead of just showing arrows while routing

### ISSUE THREAD

**Issue by Inrumpo** [organicmaps/organicmaps#1761]
While routing (in car mode) I get a vague indication of what kind of turn to take after a certain distance:
![organic maps enhancement](https://user-images.githubusercontent.com/11300164/147797251-9f7d67ce-02f6-448a-925a-20f096bc768e.jpg)

I'm used to directions named after the location they lead to (e.g. a city). A simple arrow might not always be enough, especially in situations with different routes parallel to each other. Example:
![multiple routes](https://user-images.githubusercontent.com/11300164/147797472-d732550e-147f-4ca3-8207-a177e2fb2f02.png)

Getting more information about my direction (e.g. name) would be very helpful here. 

Does the available data allow for such a feature?

**Comment by biodranik** [comment]
Some data is available in OSM, but not everywhere. A better heuristic can be done. See also #1104 and #849
