### ISSUE TITLE
[strings] Translations for some languages are ignored

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1762]
Following translations are present in strings.txt, but are missing in android/iphone/js generated files:
```
bg      : 529 / 636 (83%)
sw      : 220 / 636 (35%)
he      : 151 / 636 (24%)
af      : 5 / 636 (1%)
fr-CA   : 5 / 636 (1%)
hi      : 5 / 636 (1%)
```

That's because in `generate_localizations.sh` twine is being run without `--create-folders` option.
(and its better to keep it this way for now until we add language codes validation - to prevent typos from getting in)

We need to add ignored translations into android, iphone, js localization files.

There are some special cases for Android:

There is `android/res/values-in/`, `in` is a deprecated code for Indonesian used in older java versions, a correct current code is `id` and current java supports it, see https://developer.android.com/reference/java/util/Locale.html#toLanguageTag()
To be sure it works in older android/java versions lets symlink `values-in` to `values-id`.

`zh-Hans, zh-Hant` are missing in android localizations, but `zh, zh-rTW, zh-rHK, zh-rMO` are present.
It looks like `zh-Hans, zh-Hant` are supported by Android natively starting from 8.0 Oreo (ref https://medium.com/googleplaydev/demystifying-chinese-languages-in-the-app-world-b2a4e7dd1276), so my suggestion is to add `zh-Hans, zh-Hant` and symlink `zh, zh-rTW, zh-rHK, zh-rMO` to them accordingly.

I see there were updates to `in` and `zh, zh-rTW` in android localizations, but current `generate_localizations.sh` doesn't produce them so I assume they were adjusted manually or maybe there is some other script that does renaming I don't know about?

**Comment by biodranik** [comment]
Did you check twine patches?

**Comment by pastk** [comment]
Ahh, found it, thanks!
Do you prefer to keep `in` and `zh-*` support via a patch? I think that symlinking solution is simpler (and we have symlinks for `zh-HK` and `zh-MO` already anyway) and less patches to maintain.

**Comment by biodranik** [comment]
It would be great to drop the patch if symlinks will work properly.

**Comment by pastk** [comment]
The idea with symlinks didn't work unfortunately - android build errors on `res/values-zh-rHant` dir names. `zh-Hant` is supported in Android via BCP-47 tags which are not supported by Twine.
(https://github.com/scelis/twine/issues/307#issuecomment-1003964271)

**Comment by biodranik** [comment]
Then let's leave the patch as it is until the better times.

**Comment by pastk** [comment]
Done.
