### ISSUE TITLE
Increase highway=unclassified visibility

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1766]
The `highway=unclassified` between small villages is not visible at zoom level 11. However village streets (`highway=residential`) are visible already.
![hw_unclassified_z11](https://user-images.githubusercontent.com/18434508/147855806-20d2d091-115c-4fc1-9b5b-789d153227e8.png)

The inter-village `highway=unclassified` is rendered at higher zoom level 12 only.
![hw_unclassified_z12](https://user-images.githubusercontent.com/18434508/147855809-8b83fbce-45ff-42f4-a601-22539f9b0a7f.png)

Obviously inter-connecting (transit) roads are more important than local streets and should be displayed first.

According to https://wiki.openstreetmap.org/wiki/Key:highway and https://wiki.openstreetmap.org/wiki/Highway:International_equivalence `highway=unclassified` sits below `highway=tertiary` and higher than `highway=residential` by importance.

However in OM its vice versa at the moment:
(from `data/styles/vehicle/include/Roads.mapcss`)
```
6.RESIDENTAL & TERTIARY 11-22 ZOOM
  6.1 Residential & Tertiary 11-22 ZOOM
7.ROAD, STREETS, UNCLASSIFIED & SERVICE 12-22 ZOOM
  7.1 Road, Street, Unclassified 12-22 ZOOM
  7.4 Service 15-22 ZOOM
```

I suggest to promote `unclassified` to z11-  and demote `residential` to z12- (and maybe demote `highway=living_street` ("streets" above) to z13-). 
(and update rendering style e.g. line width accordingly)

**Comment by biodranik** [comment]
@vng what do you think?
What if we move unclassified to the same level as residential?
It would be great to see real screenshots to compare.
