### ISSUE TITLE
[strings] highway=* types classification

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1767]
E.g. at the moment all of the roads are just "Streets" (incl. motorways and forest tracks).

I propose following more specific translations:

Motor roads:
```
highway.motorway
	en = Motorway
	ru = Автомагистраль
highway.trunk
	en = National Highway
	ru = Трасса
highway.primary
	en = Primary Road
	ru = Шоссе
highway.secondary
	en = Secondary Road
	ru = Автодорога
highway.tertiary
	en = Tertiary Road
	ru = Дорога
highway.unclassified
	en = Minor Road
	ru = Небольшая дорога
highway.residential
	en = Street
	ru = Улица
highway.living_street
	en = Living Street
	ru = Жилая зона
highway.road
	en = Road
	ru = Дорога
highway.service
	en = Service Road
	ru = Проезд
highway.service.driveway
	en = Driveway
	ru = Подъезд
highway.service.parking_aisle
	en = Parking Aisle
	ru = Парковочный проезд
highway.track
	en = Track
	ru = Грунтовка
```

Non-motor:
```
highway.bridleway
    en = Bridle Path
    ru = Конная дорожка
highway.cycleway
    en = Cycle Path
    ru = Велодорожка
highway.steps
    en = Stairs
    ru = Лестница
highway.footway
    en = Foot Path
    ru = Пешеходная дорожка
highway.pedestrian
    en = Pedestrian Street
    ru = Пешеходная улица
highway.footway.area
highway.pedestrian.area
    en = Pedestrian Zone
    ru = Пешеходная зона
highway.path
    en = Path
    ru = Тропа
```

I referred extensively to OSM wiki to try to come up with the most generic options suitable for most regions.
E.g. https://wiki.openstreetmap.org/wiki/Highways, https://wiki.openstreetmap.org/wiki/Highway:International_equivalence, https://wiki.openstreetmap.org/wiki/Key:highway

**Comment by biodranik** [comment]
Тут есть коллизии в русском: проезд может быть частью адреса, а подъезд — входом в здание.

**Comment by pastk** [comment]
Да, без контекста может возникнуть путаница.
Но контекста вроде как нет только на экране добавления места, но там всё равно только точки добавлять можно, никаких дорог.
При выборе объекта на карте или в поиске тип объекта явно от адреса отделяется.
Или где-то ещё может быть путаница?

(Можно, конечно, использовать "проездная дорога" и "подъездная дорога", но длинновато, имхо.)

**Comment by pastk** [comment]
BTW it'll be great to be more specific with `*.bridge` and `*.tunnel` too.
I suggest mimicking PP subtitle style, e.g.
```
Secondary Road • Bridge
Secondary Road • Tunnel
Велодорожка • Мост
Улица • Тоннель
```

We might use this approach for some other tags also, e.g.
```
Parking • Private
Parking • Fee
Beach • Sand
```
etc.

I hope it'll work well in PP, search and add place as well. What do you think?

**Comment by biodranik** [comment]
Looks interesting, but it's more like a hack. It would be better to have additional properties for features instead of sub-types for each possible combination. @vng is it feasible? What do you think?
