### ISSUE TITLE
Replace ge0:// with om://

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#177]
Click "Share" button on iOS:

<img width="856" alt="Screenshot 2021-02-20 at 23 43 01" src="https://user-images.githubusercontent.com/1799054/108608060-6387bb00-73d5-11eb-8324-2e825742126c.png">

**Comment by rtsisyk** [comment]
@biodranik any ideas what to do here?

**Comment by vng** [comment]
ge0.me is not ours. We can remove this functionality or register some other "short name" sharing service.

**Comment by rtsisyk** [comment]
Name Server: NS1.MAIL.RU
Name Server: NS2.MAIL.RU

**Comment by vng** [comment]
Про что это?
