### ISSUE TITLE
When adding POIs remember recently used one(s) to make repeatred actions quicker

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#1770]
I use Organic Maps editor almost solely for adding bicycle parking.

It is a bit irritating to search it every single time in POI lister and discourages its use.

It would be nice to remember 2 or 3 last used unique POI types (also across app restarts).

**Comment by danvyr** [comment]
https://github.com/organicmaps/organicmaps/issues/1140
