### ISSUE TITLE
Navigation bug on moterway junctions

### ISSUE THREAD

**Issue by vincentvd1** [organicmaps/organicmaps#1773]
I found a bug in routing. See the image below. When driving on the moterway from left to right it takes the wrong turn on the junction. As a result, it drives north, takes the first exit to turn around and then drives south. There is nothing wrong with the OSM data because graphhopper results in the correct route. Also, when I start and end the navigation just before and after the junction, organic maps takes the correct turn.

[Location of the junction](https://www.openstreetmap.org/search?whereami=1&query=51.7007%2C4.3922#map=16/51.7007/4.3922)

I haven't encountered any other extreme mistakes like this but something clearly goes wrong here.

![](https://i.imgur.com/aas9bBB.png)
![](https://i.imgur.com/wDv5F8l.png)

**Comment by biodranik** [comment]
Thanks! That's a bug, @vng will check it out.

**Comment by vng** [comment]
Checked, works fine on 211122 data and World.
@vincentvd1 Do you have FDroid version installed? Do you have latest 211122 data?

**Comment by vincentvd1** [comment]
> Checked, works fine on 211122 data and World. @vincentvd1 Do you have FDroid version installed? Do you have latest 211122 data?

I indeed use the latest F-Droid version (2021.12.01-4-FDoid). I have the 211122 data. Just checked again and the bug still occurs for me. I just used this start and end point, can you reproduce it with this?: https://graphhopper.com/maps/?point=51.847656%2C4.089189&point=51.651632%2C4.725924&locale=nl-nl&elevation=true&profile=car&use_miles=false&layer=Omniscale

**Comment by biodranik** [comment]
Did you load the "World map" on the initial start screen before updating the app to the latest version? If yes, and if you have root access on the device, can you please delete World*.mwm files from the app's folder and restart the app/re-download world maps?

**Comment by vincentvd1** [comment]
> Did you load the "World map" on the initial start screen before updating the app to the latest version? If yes, and if you have root access on the device, can you please delete World*.mwm files from the app's folder and restart the app/re-download world maps?

Not that I am aware of, I just updated the app and started using it. I don't have root access so I can't test that for you.

**Comment by biodranik** [comment]
If we're right assuming that it's an outdated World map, then you can export/backup your bookmarks, uninstall the app, and reinstall it again. Newer world maps will be downloaded at the start.

Or you can wait until one of the next app updates, we're already working on the World map update issue.

**Comment by vincentvd1** [comment]
> Or you can wait until one of the next app updates, we're already working on the World map update issue.

Okay, then I will wait. I will keep an eye for the next update(s) and test whether the issue is resolved

**Comment by vng** [comment]
@vincentvd1 With the new (April) app update you are able to update World map via the Downloader view. Please, check.

**Comment by vincentvd1** [comment]
> @vincentvd1 With the new (April) app update you are able to update World map via the Downloader view. Please, check.

I updated the app, all data and the world files but that spike in the navigation is still there.
