### ISSUE TITLE
'Route to' 'Route from' lower toolbar doesnt always appear

### ISSUE THREAD

**Issue by AKDub** [organicmaps/organicmaps#1777]
The lower toolbar will often not appear when I click on a POI.

I can't seem to replicate it consistently, from what I tell tell its random. Don't think its a visual bug as the buttons that should be there dont work at all and are not just hidden from view.

Not sure what else I can really add but I will upload some screenshots if I figure out how to.

<img src="https://user-images.githubusercontent.com/43154960/148070211-3ca84a9a-0b3b-4c2c-a03d-df5a58d808e4.png" width=50% height=50%> <img src="https://user-images.githubusercontent.com/43154960/148070239-dc6fffcb-5307-4cfd-9bd9-866170ceb081.png" width=50% height=50%>

**Comment by pastk** [comment]
Android 11? It's a long standing known bug :( #1021

**Comment by biodranik** [comment]
The workaround is to rotate the screen into the landscape. We're working on the fix now.
