### ISSUE TITLE
Search should not show non-relevant results after matching coordinates

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1780]
![image](https://user-images.githubusercontent.com/170263/148126176-e703efee-841d-4ad8-b9c0-4d3af321df06.png)

**Comment by gfreitag** [comment]
Hi, I'm new to open source, but I'm interested in helping out with this issue. Where should I start? I have experience in Java.

**Comment by biodranik** [comment]
This one requires C++ knowledge. It should be easy to fix if you can read C++ search core code.

**Comment by gfreitag** [comment]
> This one requires C++ knowledge. It should be easy to fix if you can read C++ search core code.

Ok. I know some C++ as well. I will make an attempt. (:

**Comment by aeshaganatra** [comment]
hey @biodranik 
I was trying to understand search code, and I find that we might be using organicmaps/search/result.cpp. 

Result::Result(m2::PointD const & pt, string const & latlon, string const & address)
  : m_resultType(Type::LatLon), m_center(pt), m_str(latlon), m_address(address)
{
}

But I couldn't find, where we are using this! 

I think there should be some list that will store the Result object, and if we find Type::LatLon  at 0th index we can drop all others.

**Comment by biodranik** [comment]
All documentation we have is already in the repository. Please check the docs folder. I think the search should be canceled if the first result provided a 100% lat lon match.

**Comment by aeshaganatra** [comment]
@biodranik can you please guide me to doc. 
I am unable to find it. link will be very helpful.

**Comment by pastk** [comment]
@aeshaganatra all the docs we have are in the `docs/` folder. Unfortunately we don't have docs for subsystems internals, search included. So it usually takes a lot of code reading to understand how things work..
Did you see/check `search/latlon_match.hpp`?
