### ISSUE TITLE
[iOS] Disable/hide "Backup bookmarks" in preferences

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#179]
<img width="626" alt="Screenshot 2021-02-20 at 23 54 04" src="https://user-images.githubusercontent.com/1799054/108608271-fd9c3300-73d6-11eb-8f65-c9447e588d18.png">

**Comment by vng** [comment]
@rtsisyk @biodranik 
Should we implement some bookmarks backup?

**Comment by rtsisyk** [comment]
Yes, we should, but later. Let's hide this menu for now.
