### ISSUE TITLE
[ios] Top bar is broken (regression)

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#1806]
![photo_2022-01-08 14 02 07](https://user-images.githubusercontent.com/1799054/148641709-d72304d1-61a2-4870-9b14-7bb1a54f80dd.jpeg)
![photo_2022-01-08 14 02 11](https://user-images.githubusercontent.com/1799054/148641710-0b851e93-88c5-4106-80c1-4603968a5111.jpeg)
![photo_2022-01-08 14 02 04](https://user-images.githubusercontent.com/1799054/148641708-5196e838-e345-418f-b2e9-5fe75e0a19be.jpeg)

**Comment by vng** [comment]
https://github.com/organicmaps/organicmaps/pull/1820
