### ISSUE TITLE
[android] Settings->Help crash

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1823]
There are both latest stable 2021.12.01-4-FDroid and latest master 2022.01.09-11-FDroid-debug on a custom Android 9 device.
"?" help button works just fine.
However when I (in debug app) go to Settings -> Help it opens the help screen from 2021.12.01-4-FDroid stable! If I press back and press Help again it crashes showing the android crash dialog (Close app, Copy crash log, etc.)

Before the Android 12 commits (e.g. if built off https://github.com/pastk/organicmaps/tree/pastk-loc-share) when I press Help it shows  app selection pop-up with both OM and OM Debug options.
![Screenshot_20220110-010704](https://user-images.githubusercontent.com/18434508/148701287-3c7d7884-6b57-4b1b-a82b-cbd174637a6d.jpg)

**Comment by biodranik** [comment]
@rtsisyk регрессия, давай может выпилим Help из Settings тогда, чтобы в одном месте точка входа осталась?

**Comment by pastk** [comment]
Как-то не очень, в сеттингах самое классическое место для хелпа. Там же вроде можно в интенте excluded components задать или что-то такое, не помогает?

**Comment by vng** [comment]
А что за такая техника? Почему у нас одна прилага вызывает активити другой установленной прилаги? Тут надо разобраться,  а не просто убрать кнопку. Может это нормально для ведра, но противоречит здравому смыслу в моем понимании :)

**Comment by biodranik** [comment]
Это не нормально для ведра, мы свои же активити должны вызывать без всяких подтверждений )

**Comment by vng** [comment]
Цимус не только в подтверждении, а в том что debug app вызывает активити release app. Это мы так накодили или это custm Android так разрешает или как вообще?

**Comment by biodranik** [comment]
Это в настройках intent должно регулироваться. @rtsisyk знает.

**Comment by pastk** [comment]
Fixed in  https://github.com/organicmaps/organicmaps/pull/1832
