### ISSUE TITLE
Wrong icon used for amenity=waste_disposal

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1839]
`amenity=waste_disposal` is used for general rubbish going to landfills ("A medium or large disposal bin, typically for bagged up household or industrial waste.")
However at the moment its displayed using recycling icon which is wrong and confuses people (who expect to find e.g. separate collection of recyclable stuff there).
Current icon:

![bin_recycling](https://user-images.githubusercontent.com/18434508/149151715-c4a0f92a-74c2-49f4-978b-9d7673bdaa56.png)

Please change it to the trash bin icon used for `amenity=waste_basket`:

![bin_trash](https://user-images.githubusercontent.com/18434508/149151434-1d2c0524-9859-4bf1-8748-da4168ea2185.png)

**Comment by vng** [comment]
Well, seems like current OM approach for recycling is obsolete and needs to be reviewed.

See https://taginfo.openstreetmap.org/tags/amenity=recycling#combinations

- recycling_container is obsolete
- not sure that recycling classificator subtypes are correctly parsed
- should make _big_ icon like waste basket

**Comment by vng** [comment]
Probably, can find some interesting things here: https://github.com/mapsme/omim/pull/13450

**Comment by pastk** [comment]
E.g. `recycling:aluminium_cans=yes` and `recycling:pet_drink_bottles=yes` are not recognized by OM at the moment.
