### ISSUE TITLE
How frequently are OM maps rendered to reflect OSM edits? What is the update process?

### ISSUE THREAD

**Issue by sn0ot** [organicmaps/organicmaps#1846]
The rendering of the main (mapnik) map (as seen at [openstreetmap.org](https://www.openstreetmap.org/#map=3/32.69/-98.79)) should typically update within a few (tens of) minutes, however occasionally it can take longer. A great resource about it is found [here](https://help.openstreetmap.org/questions/178/how-often-does-the-main-mapnik-map-get-updated).

> if you edit OpenStreetMap data, your changes get applied to the main database and are immediately visible from the API. The rendering of the map however uses a secondary database that needs to be kept updated from the main database.

I'm still getting familiar with this project, but what is the update process for the maps in OrganicMaps?

24 hours went by after my edits on OSM before I removed and downloaded maps again through the OM application and my edits are still not reflected. My edits are reflected in other applications, like StreetComplete. However in the reverse direction, if I make edits from the OM application, they are visible on OSM much sooner.

What is the normal process to update maps? Perhaps my first contribution to the project can be to work on this if the current approach is sub-optimal.

**Comment by dbf256** [comment]
OrganicMaps doesn't use tiles from openstreetmap.org (or any other website), you can download new map files with each new application release (~ 1 per month now).

**Comment by sn0ot** [comment]
just as you replied I found the release history which confirmed the ~1 prt monyh new map files that you said, thank you.

Theoretically, what would it take to have these map files updated sooner so that if a user deletes the old map file and downloads the new one, they can see the reflected changes. Is that a distributed compute / resource problem or a code base thing?

**Comment by dbf256** [comment]
Based on dev's feedback it takes ~3-4 days to build maps for the whole planet also map files need to be compatible with application. There is a plan to have more frequent updates (without application releases).

**Comment by sn0ot** [comment]
[Found another mention of this on the discussion board](https://github.com/organicmaps/organicmaps/discussions/714#discussion-3426822). Also learned there was a Discussion board - sorry to pollute the issue tracker.

I am closing this issue but if possible, can someone migrate this to the discussion board as I do not have privileges, or delete it all together.

Otherwise I can edit this issue to track progress of speeding up deployment of updated map data.

**Comment by biodranik** [comment]
Please monitor the related #404 PR. There are many subtasks to do before a properly working frequent maps update feature.
