### ISSUE TITLE
Fix roads/paths selection by long tap

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1847]
Selection works fine if there is no "background":

![road_sel_road](https://user-images.githubusercontent.com/18434508/149323772-aa7963cf-2789-4547-8385-637f62e091bd.png)

However if there is e.g. `natural=wood` or `landuse=allotments/farmland/etc` area in the background then the area type wrongly takes precedence:

![road_sel_forest](https://user-images.githubusercontent.com/18434508/149323778-53ccae62-3b25-4ab6-bce0-e1f57a8be033.png)

Way-like features should have a priority over area-like ones.

When all (most) of the displayed features are selectable it'll help close the "Where is the map legend?" case.

**Comment by biodranik** [comment]
Here all types should be displayed, Minor Road * Forest.

**Comment by pastk** [comment]
> Here all types should be displayed, Minor Road * Forest.

There are two things here.
We don't do it in other situations, e.g. we don't display "Power Tower * Farmland" or "Water Tap * Forest" or "Cafe * Retail Land".
It won't be as easy to do as those types belong to different features and the current PP filling code operates on a single selected feature only (`map/place_page_info.cpp:Info::SetFromFeatureType`).

**Comment by biodranik** [comment]
Ok. Then we need to do what users expect from the selection.

**Comment by pastk** [comment]
Displaying additional types makes perfect sense when they're hidden/undiscoverable by the user otherwise, e.g. in POIs with many types.
But in this situation the "background" type is visible (and selectable also) in the viewport, so its present there in the UX context already.
