### ISSUE TITLE
Add support for provides_feature relations

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#1866]
**What It Is:**
https://wiki.openstreetmap.org/wiki/Relations/Proposed/Provides_feature
a relation with `type=provides_feature` links things like entrance nodes and car parks with specific shops and sites. 

**Why OM Should Implement This:**
It would improve routing in well mapped areas dramatically, as you can route to the entrance or car park of the POI instead of to the general building area.

**Example:**
<img width="1056" alt="Screenshot 2022-01-15 at 22 51 54" src="https://user-images.githubusercontent.com/26939824/149640173-e0802ca7-534f-4a96-a77e-6dc84051ae69.png">

At the moment, `type=provides_feature` has around 1,600 uses, mainly in Sweden, however an implementation from OM would definitely boost uses, leading to better micro-routing on OSM :)

**Comment by pastk** [comment]
In the meantime maybe it'll make sense to route by default to the nearest entrance and not to the building center?

**Comment by vng** [comment]
Good point for the "last mile navigation". Can't promise that we will make it fast, but will keep in mind. Some time ago [the proposal](https://wiki.openstreetmap.org/wiki/Relations/Proposed/Associated_Entrance) also was about this problem, but seems like it died.

**Comment by AntonM030481** [comment]
Why to limit ourselves by such relations? See #2705 
There are 3.000.000+ of [entrance=](https://wiki.openstreetmap.org/wiki/Key:entrance) items.
It's positioned on the border of area object.
I hope it's possible to identify the relation between such objects and their entrances.

**Comment by endim8** [comment]
actually, yeah! Just route through the entrance=main node if the POI is in a building 👍 gonna close this in favour of #2705
