### ISSUE TITLE
[iOS] A crash on attempt to add a new object

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#187]
1. Click "Add a new object"
2. Choose any category
3. Try to type something in any input field

<img width="1552" alt="Screenshot 2021-02-21 at 00 18 48" src="https://user-images.githubusercontent.com/1799054/108608806-87013480-73da-11eb-896c-084cf9c242f6.png">

**Comment by vng** [comment]
@rtsisyk Can't reproduce on latest master.
- Did you test it on a device or simulator?

**Comment by rtsisyk** [comment]
This was a simulator bug.
