### ISSUE TITLE
Display a description field for POIs 

### ISSUE THREAD

**Issue by AlertSubject** [organicmaps/organicmaps#1888]
OSM has a description tag that can be used to display information about a POI

Some objects are linked to wikidata, which too can be used to populate a description field

**Comment by biodranik** [comment]
The issue was already created: #1233
See also #1879, #1052

**Comment by AlertSubject** [comment]
The first linked issue isn't about the same topic from what I can't tell. Looks like it's about the option to add an description to objects when creating them, not about displaying said description

The second linked issue was created in reaction to the third linked issue. In which you said that it would make sense to create a new issue for it, which is why I created this one
(https://github.com/organicmaps/organicmaps/discussions/1052#discussioncomment-1989271)

In which thread should we keep this conversation?

**Comment by biodranik** [comment]
We can't add/edit invisible descriptions, right? So the first step is to display them. I'm ok with any issues if they're properly linked together, so when we fix it, they can be all closed at once. Or if someone will create a detailed meta issue, so we can close everything else.

**Comment by pastk** [comment]
Let's track it in #1953
