### ISSUE TITLE
Add dump stations (used by caravaners, motorhomers, boaters...)

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1889]
`amenity=sanitary_dump_station` / `waterway=sanitary_dump_station` are absent in OM at the moment.
However these facilities are very important to campervan/motorhome/boat users!
Somehow taginfo doesn't show tags used in combination with them...
However many dump stations are tagged in good detail, e.g. https://www.openstreetmap.org/node/4448464154
Its important to include a dump station name at least.
And its important to differentiate between public/free and private/paid ones.
E.g. we can divide in two types at least: if there is a `fee=yes` or `access != yes` then its a private type, otherwise a public type.

`sanitary_dump_station=yes/no/customers` (https://wiki.openstreetmap.org/wiki/Key:sanitary_dump_station) could be converted into OM types as well.

_Originally posted by @pastk in https://github.com/organicmaps/organicmaps/pull/1868#issuecomment-1015399903_

**Comment by pastk** [comment]
> Somehow taginfo doesn't show tags used in combination with them...

It seems they fall below some usage frequency cut-off value in taginfo https://github.com/taginfo/taginfo/issues/349

**Comment by pastk** [comment]
>And its important to differentiate between public/free and private/paid ones. E.g. we can divide in two types at least: if there is a `fee=yes` or `access != yes` then its a private type, otherwise a public type.
> 

E.g. for `amenity=sanitary_dump_station` more than a third of objects have fee/access keys, so it'll be reasonable to do such division:
```
$ osmfilter dump_stations_amenity.o5m --out-count
       5667	amenity
       2264	fee
       1917	access
       1395	water_point
...
```

Of course, ideally we would have access and fee information separately as e.g. public doesn't mean no fee and private doesn't mean its paid.

Thanks to @biodranik for help with the stats!

**Comment by biodranik** [comment]
If the meta-information is necessary only in the Place Page, then it's easier to store it in the feature's metadata.

**Comment by pastk** [comment]
Ideally it should be searchable, e.g. ability to search for a "public dump station". However as there are not too many of them then someone could just search for "dump station" and then check out PPs of a few nearest results.

**Comment by vng** [comment]
I have plans to refactor fee/access like separate tag-types.
https://github.com/organicmaps/organicmaps/issues/1312
So let's make new types standalone at this moment.
