### ISSUE TITLE
Use single tap to select arbitrary point on the map instead of long tap

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1894]
At the moment only POIs are selectable via single tap.
Long tap is used to select other (no POI) points on the map.

Why not select everything via a single tap?
There will be several advantages:
- solves "undiscoverable long tap" issue #1105
- single tap is quicker - more snappy UI - one of the strongest points of OM
- more coherent UX - for users it might be not obvious why e.g. a building and a road are selected differently
- long tap will be vacant for some other use (e.g. an optional power user feature like quick bookmarking or navigating, etc.)

Concerns/challenges:
- single tap on an "empty" area is used to toggle UI controls at the moment (we can trigger it some other way, e.g. a dedicated floating button, a long tap / double tap on existing layers button, "back" button press - let's brainstorm) - and at the moment it doesn't work well anyway when viewing an area with a lot of POIs, so its hard to find an "empty" spot to tap on
- random / accidental taps - some other single-tap-select-everything apps like 2gis and Gaia gps doesn't seem to have this issue; also if it was an issue then users would complain about accidental taps in OM anyway when the map is filled with POIs - also we can address this concern by adding a setting to switch behavior back
- need to get used to a core behavior change

**Comment by biodranik** [comment]
This change is a critical one and can cause a lot of negative feedback. It should be carefully tested first.

**Comment by pastk** [comment]
One way to make the change smoother is to add a setting first and keep the old behavior by default. After getting enough feedback and if its positive we might switch to a single tap by default.
