### ISSUE TITLE
Downloading to SD card freezes the app

### ISSUE THREAD

**Issue by kudlav** [organicmaps/organicmaps#1896]
Hi, I've installed version from F-Droid and the following problem with downloading maps raised.
Broken both in `2022.01.12-5-FDroid` and `2022.01.15-3-FDroid`.

- When I start downloading of region, the UI is really laggy. UI updates (including animations) only each 5-10 seconds. The only thing that works smoothly even during downloading is the map. A am unable to interact with it, but the compass and screen-centerign is smooth even with the animations.
- Downloading fails when the screen goes off. I have to keep the screen on. Was fine with the Google Play version. I have backgroud activity turned on for Organic Maps.
- After 3 fails I am unable to continue due to _Not enough space on device_. But I have 10 GB free on internal storage and 17 GB free on SD card.

**Comment by biodranik** [comment]
Did you choose SD-card as maps storage? If yes, this issue is caused by bad/slow/fragile/counterfeit/broken/old SD-card. Then try to change the storage to an internal one and check again.

**Comment by kudlav** [comment]
Hi, I switched to internal storage and UI is no longer laggy.

**Comment by biodranik** [comment]
I would recommend you to replace your SD. Or at least to reformat it. UI lags and random crashes are very common issues with Organic Maps amongst users who store maps on SD.
