### ISSUE TITLE
Some bus stops are displayed with a "Platform" text

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1900]
![platform-bust_stop](https://user-images.githubusercontent.com/18434508/150118300-370b2b0c-a818-4598-9b49-c3c800ac71d8.png)

This [bus stop](https://www.openstreetmap.org/node/1515591158) is tagged as
```
highway=bus_stop
public_transport=platform
bus=yes
```

`public_transport=platform` type takes precedence hence its translation string is displayed. However its a more generic tag used for places where passengers board public transport (be it a bus, or a tram, etc.).

`highway=bus_stop` is a more specific tag (as well as `railway=platform`, etc.), so it should be a "main" type for such POIs.

Somewhat related to #1166

**Comment by pastk** [comment]
Currently having all three tags
(btw OSM online editor adds all three if user wants to create a bus stop)
```
highway=bus_stop
public_transport=platform
bus=yes
```
doesn't make sense for OM as `public_transport=platform` is not used for anything AFAIK.
So we might consider to merge it into a more specific co-existing tag (e.g. into `highway=bus_stop`, `railway=platform`, `railway=tram_stop`, etc.) or maybe drop it altogether even.

**Comment by biodranik** [comment]
How many public_transport=platform without any other specific tags?

**Comment by vng** [comment]
OSM public transport has simple PTv1 scheme and complicated PTv2 scheme. public_transport is from PTv2. Sometimes they are mixed. In general, we can't replace public_transport with bus/tram _stop, i discussed it in some issue few months ago ..
