### ISSUE TITLE
Map data and search improvements for caravanners, motorhomers, etc.

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#1921]
In addition to dump stations #1889 let's add [`shop=caravan`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcaravan).

Also we can add a "RV/caravan" search category for specific facilities RVers often need:
- dump stations
- `amenity=water_point` (and water taps?)
- `shop=caravan`
- `tourism=caravan_site`
anything else?

All those things are not too common (except water taps) so the search should be useful / not overwhelmed.

@biodranik

**Comment by biodranik** [comment]
An RV/Caravan search category is a great idea. Then we don't need to teach users specific tokens.
The same idea would be great for recycling.
