### ISSUE TITLE
"Subway map is not available" for Vienna

### ISSUE THREAD

**Issue by j13m126** [organicmaps/organicmaps#1923]
I get this error message when I try to enable the subway map layer. 
Devices I checked:
- pixel 6 running Android 12 (Google PlayStore)
- fairphone 2 running Android 10 (Google PlayStore)
I also tried deleting the map or the app.

**Comment by biodranik** [comment]
There are some errors in how OSMers map the subway in Vienna. Can you please check this: https://cdn.organicmaps.app/subway/austria.html and fix OSM to make it green? Or let us know how our validator should be fixed to properly handle Vienna's OSM mapping rules?

@alexey-zakharenkov Any insights on how this error can be fixed?

**Comment by j13m126** [comment]
I just checked, the subway layer was available with the previous app data (211122)

**Comment by j13m126** [comment]
I fixed a few warnings months ago, so I recognise most of the warnings/errors. 
These though I don't. And these relations (Vienna S-Bahn Warnings) got recently changed too.. 
Hole in route rails near node n9338012276 (relation 3773484, "S50 Neulengbach – Wien Westbf")
Hole in route rails near node n5480897127 (relation 3774038, "S60 Wr. Neustadt – Bruck an der Leitha")
Hole in route rails near node n7022527683 (relation 3774039, "S60 Bruck an der Leitha – Wr. Neustadt")
Hole in route rails near node n1772970248 (relation 5736565, "S80 Wien Aspern Nord – Wien Hütteldorf")

**Comment by biodranik** [comment]
> I just checked, the subway layer was available with the previous app data (211122)

That's because we used a 1-year old subways data. In the latest release we finally updated it, but Vienna, unfortunately, was broken.

**Comment by j13m126** [comment]
I think this issue can be closed. The subway map issues were fixed and is available again with the latest update. And I managed to fix all errors of Vienna's s-bahn map.
