### ISSUE TITLE
The buttons for route is not visible in certain case.

### ISSUE THREAD

**Issue by marunguy** [organicmaps/organicmaps#1927]
The buttons for route is not visible in certain case on certain device.

* organic maps version : 2022.01.15-3 - the older versions( 2022.01.12-6, 2021.12.01-4, 2021.11.04-2, 2021.10.15-15, ...) also have same problem.
* device model : Galaxy S5 LTE(SM-G900K) https://wiki.lineageos.org/devices/kltekor/
  * It works fine on other devices - Pixel 4a, Nexus 5x, Mi A2 Lite
* os version : lineageos 18.1 20220120 (android 11) - the older versions also have same problem.

* invisible case
![image](https://user-images.githubusercontent.com/6366548/150669145-6e6cc8f9-ca6e-407b-8e9e-77c28fa464da.png)![image](https://user-images.githubusercontent.com/6366548/150669168-ccd7be80-a569-45b3-8ebd-b2ce430e2966.png)![image](https://user-images.githubusercontent.com/6366548/150669205-e97e6185-9501-4b48-a6b5-cdc82de779da.png)![image](https://user-images.githubusercontent.com/6366548/150669217-34e5f0e4-da06-48fd-9994-01f0b3d5f3b0.png)![image](https://user-images.githubusercontent.com/6366548/150669234-6ea53b6b-5c19-41f7-88e7-13b7dc340cad.png)

* visible case
![image](https://user-images.githubusercontent.com/6366548/150669145-6e6cc8f9-ca6e-407b-8e9e-77c28fa464da.png)![image](https://user-images.githubusercontent.com/6366548/150669331-ec1f1c25-cc6d-48c7-8d2b-97f5062b796d.png)![image](https://user-images.githubusercontent.com/6366548/150669285-a1796ee9-0602-4d36-bc6a-07fc47b8992c.png)

**Comment by biodranik** [comment]
See also:
- #1021 
- #1106
- #1777 
- #722

The current workaround is to rotate the screen into the landscape and then back. Or to restart the app.

**Comment by marunguy** [comment]
This issue is not fixed.
This issue is reproduced in the latest version(2022.03.23.4).
This issue shoud be reopened.

**Comment by biodranik** [comment]
Wow, that's really interesting. Thanks for the feedback, we'll check it.

**Comment by marunguy** [comment]
@biodranik The buttons for route is visible and works well on Galaxy S5 LTE(SM-G900K).

**Comment by biodranik** [comment]
@marunguy thanks! Just to confirm: did you follow the exact sequence of steps as it was described in the screenshots above?

**Comment by marunguy** [comment]
> @marunguy thanks! Just to confirm: did you follow the exact sequence of steps as it was described in the screenshots above?

@biodranik Exactly the above visible and invisible cases were tested.
And the buttons for route are visible in the latest organicmaps version.

**Comment by biodranik** [comment]
@marunguy can we close the issue then? :)

**Comment by marunguy** [comment]
@biodranik Yes, you can close this issue.
