### ISSUE TITLE
Mobile internet setting string outdated

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#1934]
In settings, the entry for **Mobile Internet** still shows it is needed for place images, prices and reviews. If I am not mistaken, internet is only used for downloading maps in OM and the uses described are from MWM.

![Screenshot_20220124-223939_Organic_Maps](https://user-images.githubusercontent.com/80701113/150869375-c6c5a478-76d8-4003-94e8-c2b6b74e078a.png)

**Comment by j5k** [comment]
Maybe we can keep/only hide this option for future use. For example if we want to load wikidata/wikipedia/wikicommons data.

**Comment by pastk** [comment]
Yeap I haven't been asked for internet usage for a very long time already (I have "Always Ask" in the settings), so my guess this setting is not used anymore. @biodranik, shall we remove it completely?

**Comment by biodranik** [comment]
We want to add a maps update check. It obviously requires some connection. Then automated maps updates are in the roadmap. And bookmarks sync. So need to rethink the whole approach.

Also, maybe we find some open source to query for reviews/photos for places.
And maybe displaying Wiki articles.

**Comment by biodranik** [comment]
Let's change it to:

Mobile internet is required for displaying detailed information about places, your bookmarks, and map update notifications.

**Comment by biodranik** [comment]
Even better is:

Mobile internet is required for map update notifications and for displaying detailed information about places and bookmarks.

It unambiguously translated to other languages :)

**Comment by pastk** [comment]
Fixed in https://github.com/organicmaps/organicmaps/pull/2019/commits/76d51aa5adb63bb0cc750d91132119898d403af4
