### ISSUE TITLE
Show house numbers only on zoom 18 and 19

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#1935]
When looking at the map in a city, house numbers (addresses) really clutter the view. Some start appearing on a low zoom level (16), and the rest by further zooming in.

Showing just a few house numbers is completely useless: unless the exact house number you are looking for appears, it is just cluttering your view with unnecessary information. Then when the majority of house numbers appear, the zoom level is still too low (17) because you are usually seeing a whole neighborhood.

What would be more useful would be to show house numbers only when really zoomed in on a street (zoom level 18 and 19 only), because you only need to see house numbers when you found the associated street.

Same thinking can be applied to navigation mode.

| Zoom 16 (useless scattered house numbers) | Zoom 17 (too many house numbers) | Zoom 18 (Good for long streets and making house numbers discoverable by users) | Zoom 19 (good, shows remaining house numbers) |
|-|-|-|-|
| ![Screenshot_1643104675](https://user-images.githubusercontent.com/80701113/150954915-ca24e07d-d12b-4d43-9696-542e8f98a305.png) | ![Screenshot_1643104691](https://user-images.githubusercontent.com/80701113/150954924-01d8219e-15af-4fb8-a43e-602775669536.png) | ![Screenshot_1643104714](https://user-images.githubusercontent.com/80701113/150954930-7fb49719-ae98-477d-861d-26dfe241575f.png) | ![Screenshot_1643104723](https://user-images.githubusercontent.com/80701113/150954938-51af89f2-f2b0-4555-8dc1-11baa4c820c8.png) |

**Comment by arnaudvergnet** [comment]
Might help in solving #1656

**Comment by pastk** [comment]
It depends on average buildings sizes in displayed area. E.g. with large multi-apartment buildings in ex-USSR countries house numbers are looking good and are useful at zoom level 16:
![Screenshot_1643136993](https://user-images.githubusercontent.com/18434508/151041068-2b0ef3d3-4711-41b9-8aa2-e1967d8a615a.png)

I don't see a way we can fix it for all cases unless we have a dynamic display based on density of features in a viewport.

**Comment by arnaudvergnet** [comment]
> I don't see a way we can fix it for all cases unless we have a dynamic display based on density of features in a viewport.

A display based on density would probably be the best, but maybe not the easiest to implement. **After more testing, I found showing house numbers only on levels 18 and 19 would not be enough to reduce clutter.**

As a temporary fix, a setting could be added to show/hide house numbers globally. I personally nearly never used the house numbers from the map and always relied on the search. Sometimes when there are a lot of POIs, even showing the numbers on a low zoom level is cluttering the view.

As an example, here are some screenshots of the center of Toulouse in France. Even on zoom level 19 house numbers are distracting, and you often end up clicking on a house number instead of a POI. While navigating, house numbers are completely useless because you often enter the number you want to go to as the destination.
| House numbers with lots of POIs |House numbers during navigation |
|-|-|
| ![Screenshot_1643198466](https://user-images.githubusercontent.com/80701113/151159568-0c16c19f-e062-49fd-8ec0-4e6722767897.png) | ![Screenshot_1643198798](https://user-images.githubusercontent.com/80701113/151160216-a8ed2b55-dde4-43d9-b6d4-82bfaf326f64.png) |

**Comment by biodranik** [comment]
Please don't forget that by drawing house numbers we motivate people to add missing numbers via OM's editor. This is also an important feature.

**Comment by arnaudvergnet** [comment]
But addresses as shown in the map here are made from nodes tagged with `addr:housenumber` (see the [osm wiki](https://wiki.openstreetmap.org/wiki/Key:addr)) and users cannot add those with OM's editor. This is how addresses are mapped in a lot of places in France, don't know about the rest of the world.
| Node tags | Nodes in Vespucci |
|-|-|
| ![Screenshot_20220126-134712_Vespucci](https://user-images.githubusercontent.com/80701113/151165568-84038915-203b-4d28-ba6d-eea02e6b1409.png) | ![Screenshot_20220126-134741_Vespucci](https://user-images.githubusercontent.com/80701113/151165602-84fee509-96c8-4ec7-bf91-7b3e2baf7f06.png) |

But in any case, when users are using the navigation they do not have the time to add missing addresses so they do not need to see those.

**Comment by biodranik** [comment]
You can edit any building's address (street, house number, postal code) and height directly from OM.

I agree that house numbers during active navigation should be hidden in favor of street names and other important POIs. That issue should be already somewhere on Github.

**Comment by biodranik** [comment]
While driving, it is useful to see nearby/neighborhood numbers, it helps to find a house faster.
Displaying house numbers helps to edit and add missing ones (and helps to select a building).
Also so far only a few users out of millions (including mapsme) complained about them.

A smarter approach would be a dynamic style to avoid cluttering if there are many nearby POIs and do not display a few numbers if others are not displayed.

**Comment by endim8** [comment]
Perhaps rendering of house numbers can be disabled on lower zoom levels for everything except `building=apartments` (and similar)

In my area, basically all houses are either `building=house` or `semidetatched_house` & the house numbers result in a lot of visual clutter.
![jbbijfnv](https://user-images.githubusercontent.com/26939824/180659846-6a3e27ab-0dcc-424a-add2-c3960f28c7b1.png)
coords for 1: 51.48005/0.01384 
coords for 2: 51.49808/-0.02445

**Comment by arnaudvergnet** [comment]
This will not work for every country. [As I said for France](https://github.com/organicmaps/organicmaps/issues/1935#issuecomment-1022172673) house numbers are separate features from the building:
> But addresses as shown in the map here are made from nodes tagged with addr:housenumber (see the [osm wiki](https://wiki.openstreetmap.org/wiki/Key:addr)) and users cannot add those with OM's editor. This is how addresses are mapped in a lot of places in France, don't know about the rest of the world.

Thus those nodes will not have the tags `building=house`.

**Comment by endim8** [comment]
> This will not work for every country. [As I said for France](https://github.com/organicmaps/organicmaps/issues/1935#issuecomment-1022172673) house numbers are separate features from the building:
> 
> > But addresses as shown in the map here are made from nodes tagged with addr:housenumber (see the [osm wiki](https://wiki.openstreetmap.org/wiki/Key:addr)) and users cannot add those with OM's editor. This is how addresses are mapped in a lot of places in France, don't know about the rest of the world.
> 
> Thus those nodes will not have the tags `building=house`.

Ah fair point, biodranik suggested using `FeatureID Framework::FindBuildingAtPoint(m2::PointD const & mercator) const` ([link](https://github.com/organicmaps/organicmaps/pull/3015#issuecomment-1193196310)) for a similar issue, maybe getting the building type from that would solve it?

**Comment by arnaudvergnet** [comment]
That would not solve the issue as those addresses could be out of the building if it is far from the road:
![Screenshot_20220724-212325_Organic_Maps](https://user-images.githubusercontent.com/80701113/180662674-e3593bb1-e324-44c2-948d-3fcea9371afe.png)
.

**Comment by endim8** [comment]
> That would not solve the issue as those addresses could be out of the building if it is far from the road: ![Screenshot_20220724-212325_Organic_Maps](https://user-images.githubusercontent.com/80701113/180662674-e3593bb1-e324-44c2-948d-3fcea9371afe.png) .

ohh, that's strange. In that case yeah only calculating density would fix it. Are you sure that's a standard/accepted mapping practice though?

**Comment by arnaudvergnet** [comment]
Here are the mapping practices from the French OSM wiki: https://wiki.openstreetmap.org/wiki/FR:Adresses#Comment_cartographier_les_adresses

It does not mention out of building addresses but I have observed this quite often. From what I could find, some cities import addresses from official parcel documents called the "Cadastre". In those documents house numbers are written on the edge of the parcel, which may not be the building itself. When enabling the Cadastre layer on the Vespucci app, you can see the house number nodes are at the same place as in the Cadastre: 


![Screenshot_20220724-231330_Vespucci](https://user-images.githubusercontent.com/80701113/180666083-e9400c69-c630-4b2d-9c0a-e9e19a6c2087.png)


But then again, I could not find a rule about this, and it really depends on the local mapping practices.

**Comment by biodranik** [comment]
You're doing really strange things there in France. But you have great food that compensates for everything :)
Regarding the issue, I would ask a question to the French OSM community. I assume that marking buildings with numbers is a better idea than using numbers outside. And it's a question of time when volunteers fix it. Maybe we can make it easier to fix directly from OM :)

@arnaudvergnet which part of France are you from?

**Comment by arnaudvergnet** [comment]
I observed this in several cities such as Toulouse, Paris, Lyon, Bordeaux. There may be others but these are some of the bigger cities so it impacts a lot of people.

**Comment by richlv** [comment]
> Regarding the issue, I would ask a question to the French OSM community. I assume that marking buildings with numbers is a better idea than using numbers outside. And it's a question of time when volunteers fix it.

We recently had similar discussions in Latvia, as our corresponding state agency published addresses as open data.
Where there is a corresponding building in OSM data, address info is assigned to that - but many, many addressed will get a node only.

Overall, personally I'm much more happy to see more addresses than less. It helps both with navigation and mapping.

**Comment by endim8** [comment]
What about calculating in the generator & storing the area of the polygon? That wouldn't have any performance impact for the app runtime. The addresses as nodes complicate it, but it could be a good solution for a lot of cases.

**Comment by pastk** [comment]
> What about calculating in the generator & storing the area of the polygon? That wouldn't have any performance impact for the app runtime. 

We have area's bounding box in the runtime already. ATM very small houses (and other areas) get hidden from a certain zoom level (incl. a house number caption) if they're deemed to small for it.

Here you suggest to hide captions only if the house is smaller than certain threshold?
Its possible via "dynamic tags" mechanism in styles, see how its done for e.g. `[landuse=reservoir][bbox_area>=4000000]`.
It will add some overhead to the runtime (I didn't assess it in detail though, maybe its negligible).
