### ISSUE TITLE
[ios] iPad UI freezes when using external Bluetooth or attached physical keyboard

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#1940]
Reproduced on iOS >= 15.

**Comment by biodranik** [comment]
@vng please test it with the most recent iOS 15 update. If it reproduces, please write down the steps to reproduce it.

**Comment by valynor** [comment]
Same here. 2020 Ipad Pro 12,9", iOS 15.3.1
UI freezes when you go into settings. Sometime you can do a click before it freezes. it's also unresponsive to touch or Apple Pencil when that happens.

**Comment by biodranik** [comment]
It doesn't reproduce with the debugger attached.

**Comment by biodranik** [comment]
@valynor did you upgrade to iOS 16? If yes, do you still have the same issue?

**Comment by Pr0Ger** [comment]
@biodranik I have an iPad Pro with 16.1.1 and it is still reproducible if magic keyboard is attached.

However rotating the screen will unfreeze UI until next time
