### ISSUE TITLE
Android Back button should close the opened Place Page instead of exiting navigation mode

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1946]
There is a related annoying thing - if a user selects a POI or a point on the map while in navigation mode then a bottom sheet expands and gets populated with the info - as usual. Now if a user presses the android back button then an expected behavior is to de-select the selected point (this is how it works in non-navigation mode). But contrary to this the android back button exits navigation mode completely.
It would be great if this behavior could be fixed altogether.

_Originally posted by @pastk in https://github.com/organicmaps/organicmaps/issues/836#issuecomment-1022317669_

**Comment by pastk** [comment]
The fix works like a charm, many thanks @arnaudvergnet!
