### ISSUE TITLE
Make zoom transitions smoother

### ISSUE THREAD

**Issue by NovaliX-Dev** [organicmaps/organicmaps#1952]
#Current behaviour

When we zoom in/out, a approximately 5km, the maps suddenly appear/disappear.

![image](https://user-images.githubusercontent.com/79244938/151307121-8de72341-5700-4190-9998-76f8aa0d6886.png)

![image](https://user-images.githubusercontent.com/79244938/151307155-c29f9aab-0b10-4959-8cd2-d604e807174c.png)

#My proposition

In my opinion, it will be better if you can maie this transition smoother.

There is two ways i found to do this :
- Make the opacity disappear smoothly
- Add low res maps so the transitions are smoother

**Comment by NovaliX-Dev** [comment]
What do tou think about it ?

**Comment by biodranik** [comment]
This issue is related to how we store maps data, and is not easy to fix. The better option would be to support dynamic feature priorities and draw them earlier than now, without cluttering the screen. But it requires a complex refactoring of our current approach.

**Comment by NovaliX-Dev** [comment]
I understand.
Thanks for the reply
