### ISSUE TITLE
smoothness=intermediate results in paved_good

### ISSUE THREAD

**Issue by rsippl** [organicmaps/organicmaps#1957]
This code

https://github.com/organicmaps/organicmaps/blob/ce8e10f3a4ab105f4e496ca476433182f4712f79/generator/osm2type.cpp#L455-L480

needs to be reviewed. When a path is tagged with a smoothness of `intermediate` and no surface is specified, then the code above applies the `paved_good` tag. Explain that to a guy riding a road bike. A more pessimistic estimation like `unpaved_good` would make much more sense. `paved_bad` may also be acceptable in some cases, but `paved_good` is surely wrong in most cases.

**Comment by biodranik** [comment]
@vng I think this one can be easily fixed.
