### ISSUE TITLE
Allow user to choose whether to keep screen on or not

### ISSUE THREAD

**Issue by smartyw** [organicmaps/organicmaps#196]
When the map is displayed, the screen is not allowed to sleep (there's a function called Utils.keepScreenOn which is invoked). I would like to request that the Android application be changed so that the user can choose whether or not the screen is allowed to sleep via a user setting. Here's the use case behind this request:

I sometimes do long distance, multi-day bike rides with camping equipment (so called "bike-packing"). On these trips, my phone is an essential tool for navigation, information and communication. Sometimes I cannot charge my phone battery for days and so conserving battery power is critical. Therefore, I use map navigation sparingly and I memorise the route and make notes about it on paper. I then only look at the map on my phone occasionally, just to check I am still on the planned route and sometimes to help find a way back on to the route if I've strayed. I do this without stopping and keep cycling.... double-tapping the screen to wake the screen up so that the map shows. If I'm using Google Maps, that's all I need to do. I keep cycling and (say) 60 seconds later, the screen sleeps. But with the official maps.me application, the screen stays on all the time and I have to manually show the home screen, which then allows the display to sleep. If I'm wearing gloves, this is difficult or impossible and I have to stop cycling and take a glove off to operate my phone.

So, to restate, I would be grateful if the Android application was changed so that I can indicate that I want the display to be allowed to sleep, according to the OS settings.

Thank you

**Comment by biodranik** [comment]
An option can be added in Settings to allow this scenario.

**Comment by smartyw** [comment]
That would be tremendous, thank you!

**Comment by maciboy** [comment]
Such a setting would be great for iOS, too!

**Comment by rtsisyk** [comment]
Fixed

**Comment by smartyw** [comment]
Successful road test!

https://the-bikepacker.blogspot.com/2021/07/bikepacking-fox-wood-in-south-downs.html
