### ISSUE TITLE
The metropolitan subway map is displayed incorrectly in South Korea.

### ISSUE THREAD

**Issue by marunguy** [organicmaps/organicmaps#1977]
The metropolitan subway map is displayed incorrectly in South Korea.
* organic maps version : android 2022.01.15-3 - the older versions( 2022.01.12-6, 2021.12.01-4, 2021.11.04-2, 2021.10.15-15, ...) also have same problem.
* organic maps
![image](https://user-images.githubusercontent.com/6366548/151749238-51920db5-55d0-400b-87ba-87aecf65c252.png)![image](https://user-images.githubusercontent.com/6366548/151749466-207278b5-3b01-4f84-8e61-2ff20b7e77fa.png)
* openstreetmap - https://www.openstreetmap.org/#map=11/37.4713/127.0029&layers=T
![image](https://user-images.githubusercontent.com/6366548/151749682-226c7bce-171d-4a86-b763-4a1229cb08ea.png)
* openstreetmap - https://www.openstreetmap.org/#map=11/37.4713/127.0029&layers=O
![image](https://user-images.githubusercontent.com/6366548/151749719-c40389d9-164a-4cf8-a892-988d99556245.png)

**Comment by biodranik** [comment]
Thanks! There are many validation errors for Seoul https://cdn.organicmaps.app/subway/south-korea.html

You or other OSM contributors can help by fixing it.

**Comment by biodranik** [comment]
Did you check the March release? Was it already fixed?

**Comment by marunguy** [comment]
> Did you check the March release? Was it already fixed?

It is not fixed.

**Comment by marunguy** [comment]
It is fixed in 2022.04.27-2-android.
The metropolitan subway map is displayed almost correctly in South Korea.
Some parts are wrong, but I am very satisfied.
Thanks to the developers.

**Comment by Jean-BaptisteC** [comment]
@marunguy can we close issue ?

**Comment by marunguy** [comment]
@Jean-BaptisteC Yes, you can close this issue.
