### ISSUE TITLE
No results for bubble tea

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#1981]
If you look up things such as bubble tea or boba, you get no relevant results.

**Comment by biodranik** [comment]
Do you see these objects on the map? Are they present in OpenStreetMap.org?

**Comment by TheAdventurer64** [comment]
I believe they are visible. However, they simply do not show up on the search. A solution would be to add support for `cuisine=bubble_tea`.

**Comment by pastk** [comment]
We don't import this tag into OM yet.
This is what needs to be done to make it work:
1. add it into `data/mapcss-mapping.csv`
2. add translation into `data/types_strings.txt`
3. add search aliases into `data/categories_cuisines.txt`
4. wait for the next maps update

**Comment by biodranik** [comment]
I think we can document it in the wiki.

**Comment by TheAdventurer64** [comment]
> I think we can document it in the wiki.

This tag is [already documented](https://wiki.openstreetmap.org/wiki/Tag:cuisine%3Dbubble_tea).

**Comment by biodranik** [comment]
I meant to document in our wiki how to add and edit cuisines.

**Comment by TheAdventurer64** [comment]
Fixed in #2107
