### ISSUE TITLE
Use id-tagging-schema presets for editor

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#1984]
Using presets from the iD tagging schema would mean not having to maintain a separate schema, and it is also often updated with the latest tagging practices.

https://github.com/openstreetmap/id-tagging-schema

**Comment by biodranik** [comment]
That's an interesting idea, but it's not easy to implement. We need to properly map our types to OSM ones, and OM doesn't support any custom tags yet.

**Comment by TheAdventurer64** [comment]
See also #1249.

**Comment by RedAuburn** [comment]
closing as not worth it due to types mapping
