### ISSUE TITLE
Display an indicator for unknown opening hours in search overview 

### ISSUE THREAD

**Issue by Outlet2048** [organicmaps/organicmaps#1996]
Picture this:
It's 7:30 and hungry
I open organic maps and type the name of a restaurant chain of my choice
The app presents me with a list of places. A majority are signed as closed for obvious reasons while some entries don't show the closed marker. Therefore, I'd usually assume that this store is open right now. But upon further inspection it shows that no one has mapped the opening hours

Sadly you can't differentiate between unknown opening hours and a store being open from within the search results
Maybe a little "hours unknown" or something similar would be useful

**Comment by AlertSubject** [comment]
(im still hungry) :(

**Comment by R3gi** [comment]
Other apps (Mapy.cz, OsmAnd) display for how long the place will stay open (when open, e.g. "Open until 23:00") or when it will open (when closed, e.g. "Opens tomorrow at 11:00").

Label "Open" would also solve the problem.

**Comment by biodranik** [comment]
Another important improvement is to enlarge the label "open" in search results, in some languages it doesn't fit.

**Comment by Kazing** [comment]
Can be closed since #2403  added indicator for open & close in search result.
No open/close indicator means there is no opening_hours data.

**Comment by AlertSubject** [comment]
> Can be closed since #2403  added indicator for open & close in search result.
> No open/close indicator means there is no opening_hours data.

I think there should be an indicator for unknown opening hours to make it clear for the user to not rely on those stores
Of course it can be deducted from the fact that there is neither open nor close signed. But thah would require the user to have a functional brain

**Comment by RedAuburn** [comment]
i think we can close this, i do believe most users have functional brains 😅

**Comment by RedAuburn** [comment]
> And I don't think the answer is calling users "stupid" 🙃

I'm really sorry, that wasn't directed at you (or at anyone, but I see now it could easily be interpreted that way). I'll be more careful in future.

Still, I do think the presence of an indicator should be linked to the presence of the metadata, and vice versa. If the metadata doesn't exist, the absence of the indicator makes sense.
It would also lead to further issues, like how to represent unparsed or comment-only opening hours. Overall, it doesn't seem worth it :)
