### ISSUE TITLE
Searching for 'Asda' gives completely wrong results

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#1997]
Searching for 'Asda' takes until the 23rd search result to find the correct POI, after places thousands of miles away. 

The Asda I was trying to find: https://www.openstreetmap.org/way/285156063
Roughly where I started the search from: https://www.openstreetmap.org/node/1178103861

![asdasearchissue](https://user-images.githubusercontent.com/26939824/152107433-1b24e4a4-371d-4c9e-ab45-2f9dd9984b88.png)

**Comment by endim8** [comment]
oops, this wasn't meant to be published yet, gimme a second to actually fill it in 😅

**Comment by biodranik** [comment]
Do you have the latest app version?

**Comment by endim8** [comment]
oo, just realised i'm using 2022.01.11-1-Google-beta, and i didn't get the update notification because it was a firebase version, I'll retest with the latest version and report back 👍

**Comment by endim8** [comment]
tried on 2022.01.15-3-FDroid, unfortunately still the exact same results 🙁
