### ISSUE TITLE
Add @OrganicMapsTR

### ISSUE THREAD

**Issue by MetehanOzyurek** [organicmaps/organicmaps#2003]
Can you add official Turkish Telegram group’s link to Organic Maps’ Turkish version (help section on Android and “about Organic Maps” section on iOS)? So, Turkish users will ask their questions in Turkish group directly.

link: https://t.me/OrganicMapsTR

![image](https://user-images.githubusercontent.com/80093621/152206606-2fbd46ad-70fb-4870-9ebf-bea089d8e635.jpeg)

**Comment by MetehanOzyurek** [comment]
Also can you add Turkish Instagram page?

instagram.com/organicmapstr

**Comment by MetehanOzyurek** [comment]
Also website can redirect to translated page but it hasn’t published yet.

**Comment by MetehanOzyurek** [comment]
Any update on this? :')

Can we add separate options for Russian and Turkish Telegram groups (and also Instagram page as well)

**Comment by biodranik** [comment]
That's a good idea. It can be done easily via translations, maybe even you can do it:
1. Find hard-coded links in the code and replace them with strings.txt tags
2. Add string txt telegram tag with different values for en, ru, tr (actually, be: and kz: translations can also lead to ru).

**Comment by MetehanOzyurek** [comment]
> That's a good idea. It can be done easily via translations, maybe even you can do it:
> 1. Find hard-coded links in the code and replace them with strings.txt tags
> 2. Add string txt telegram tag with different values for en, ru, tr (actually, be: and kz: translations can also lead to ru).

Yes, I think I can do but I don't know how to find hard-coded links on repo.

**Comment by biodranik** [comment]
Search for them )

**Comment by MetehanOzyurek** [comment]
https://github.com/organicmaps/organicmaps/pull/3202/
