### ISSUE TITLE
[Android] Fix data sharing between Beta and Release versions

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#201]
```
  <?xml version="1.0" encoding="utf-8"?>
  <manifest xmlns:android="http://schemas.android.com/apk/res/android"
 -    xmlns:tools="http://schemas.android.com/tools"
 -    tools:remove="sharedUserId, sharedUserLabel">
 ```

A request from @biodranik

**Comment by biodranik** [comment]
Это не про шаринг между бетой и продом, а про шаринг между омапс и другими аппами, например гайдами, которые смогут достукиваться до данных или настроек, если нужно.

**Comment by rtsisyk** [comment]
sharedUserId and sharedUserLabel are deprecated. This issue is won't fix.
https://developer.android.com/guide/topics/manifest/manifest-element#uid
