### ISSUE TITLE
A missing word

### ISSUE THREAD

**Issue by MetehanOzyurek** [organicmaps/organicmaps#2011]
In Turkish version, there is a missing word in search when you didn't download a map. According to data/strings, "olmayacak" is missing.
![image](https://user-images.githubusercontent.com/80093621/152416514-2db8ca94-2e90-44c7-9050-60efc836700f.jpeg)

**Comment by pastk** [comment]
Maybe a text field has a small text length limit..
How do you get this screen? I can't find in Android version :)

**Comment by MetehanOzyurek** [comment]
> Maybe a text field has a small text length limit..
> How do you get this screen? I can't find in Android version :)

Delete all your maps and try to search. If there is search history, clear it.

**Comment by biodranik** [comment]
Thanks! That should be easy to fix. Someone needs to expand the TextView and ideally make the text automatically shrinkable to always fit it.

**Comment by MetehanOzyurek** [comment]
Also its showing all text when typing to search bar. But it's still same in beta :(

**Comment by biodranik** [comment]
The beta does not include your most recent changes. Please wait until another beta )

**Comment by shankarpriyank** [comment]
I would like to work in this !

**Comment by MetehanOzyurek** [comment]
This issue has been fixed. Now search is showing categories and search history when you haven't downloaded maps.
