### ISSUE TITLE
Add haberdashery and sewing shops to categories

### ISSUE THREAD

**Issue by FinixFighter** [organicmaps/organicmaps#2017]
Hi! It would be useful to have the categories "haberdashery" (https://wiki.openstreetmap.org/wiki/Tag:shop%3Dhaberdashery) and sewing shop (https://wiki.openstreetmap.org/wiki/Tag:shop%3Dsewing). They're pretty much the same thing, but both tags are active, so I think they could be merged, and then always use shop-sewing in UI and the editor (as discussed here https://github.com/organicmaps/organicmaps/pull/2015).
As a suggestion for a logo, I'd say "scissors" or "scissors-2" from https://remixicon.com/ could be good.

**Comment by pastk** [comment]
Here is a guide how to do it properly: https://github.com/organicmaps/organicmaps/issues/1917#issuecomment-1030623850

It might seem very complex at first glance but we'll help you as you go!

**Comment by FinixFighter** [comment]
> Here is a guide how to do it properly: [#1917 (comment)](https://github.com/organicmaps/organicmaps/issues/1917#issuecomment-1030623850)
> 
> It might seem very complex at first glance but we'll help you as you go!

Thank you! I did the first step (add data to data/mapcss-mapping.csv). Second step is not necessary. Now I should upload an icon but I can't, because when I click "Upload files" it says " Uploads are disabled.
File uploads require push access to this repository. ".  The file I wanted to upload is scissors-cut-line from https://remixicon.com/
How can I do that?

**Comment by biodranik** [comment]
You should fork this repo and create a branch in it with your changes.

**Comment by pastk** [comment]
> > Here is a guide how to do it properly: [#1917 (comment)](https://github.com/organicmaps/organicmaps/issues/1917#issuecomment-1030623850)
> > It might seem very complex at first glance but we'll help you as you go!
> 
> Thank you! I did the first step (add data to data/mapcss-mapping.csv #2180). Second step is not necessary. Now I should upload an icon but I can't, because when I click "Upload files" it says " Uploads are disabled. File uploads require push access to this repository. ". The file I wanted to upload is scissors-cut-line from https://remixicon.com/ How can I do that?

I guess you tried to upload the file directly to the main `github.com/organicmaps/organicmaps` repository. In github you do all the changes in your fork of the main repo first and then create a pull request to propose to include the changes into the main repo. So you need to upload the new file into your fork into a branch which you used for #2180 already (to keep all changes together): https://github.com/FinixFighter/organicmaps/tree/patch-3

Did you consider cloning the repository to your computer? (there are instructions in https://github.com/pastk/organicmaps/blob/master/docs/INSTALL.md#getting-sources) Its much more convenient to do complex changes this way (but you need to know basics of working with git at least).

**Comment by pastk** [comment]
> The file I wanted to upload is scissors-cut-line from https://remixicon.com/ How can I do that?

A scissors icon is used in OM for hairdressers already (see `data/styles/clear/style-clear/symbols/hairdresser-m.svg`) so we need something different e.g. a needle with a thread.

> I did the first step (add data to data/mapcss-mapping.csv https://github.com/organicmaps/organicmaps/pull/2180). Second step is not necessary.

As the `shop=haberdashery` and `shop=sewing` are identical it makes sense to merge the `haberdashery` tag into a sewing shop (so in OM all haberdasheries will appear as sewing shops) - it needs to be done in `data/replaced_tags.txt`.

**Comment by FinixFighter** [comment]
> A scissors icon is used in OM for hairdressers already (see `data/styles/clear/style-clear/symbols/hairdresser-m.svg`) so we need something different e.g. a needle with a thread.

What about this one: https://fontawesome.com/icons/reel?s=solid?

**Comment by FinixFighter** [comment]
> A scissors icon is used in OM for hairdressers already (see `data/styles/clear/style-clear/symbols/hairdresser-m.svg`) so we need something different e.g. a needle with a thread.

What about this one? https://www.flaticon.com/free-icon/thread_1248527 (attribution to this website is already in data/copyright.html file)

**Comment by pastk** [comment]
> 
> What about this one? https://www.flaticon.com/free-icon/thread_1248527 (attribution to this website is already in data/copyright.html file) Alternatives: -https://www.freepik.com/free-icon/needle_14550960.htm#query=needle&position=35&from_view=search -https://www.freepik.com/free-icon/sewing_15571883.htm#query=needle&position=42&from_view=search -https://www.freepik.com/free-icon/sewing_15571937.htm#query=needle&position=46&from_view=search What do you think?

Some of them are really good!
My order of personal preference is
https://www.flaticon.com/free-icon/needle-with-thread-to-sew-clothes_27046
and https://www.flaticon.com/free-icon/needle_113317
https://www.freepik.com/free-icon/needle_14550960.htm
https://www.freepik.com/free-icon/sewing_15571937.htm

**Comment by FinixFighter** [comment]
>My order of personal preference is https://www.flaticon.com/free-icon/needle-with-thread-to-sew-clothes_27046

Great! Can I upload it as it is, or do I have to resize/modify it in some way?

**Comment by pastk** [comment]
Yes it needs to be modified to look like other similar icons, e.g. we use the same icon color for all shops and there should be a circle around, for example see department_store, computer, book-shop, etc. in `data/styles/clear/style-clear/symbols`. Note that a separate "dark/night" version should be added to `data/styles/clear/style-night/symbols` as well.

**Comment by FinixFighter** [comment]
> Yes it needs to be modified to look like other similar icons, e.g. we use the same icon color for all shops and there should be a circle around, for example see department_store, computer, book-shop, etc. in `data/styles/clear/style-clear/symbols`. Note that a separate "dark/night" version should be added to `data/styles/clear/style-night/symbols` as well.

I see. I'm sorry I think I'm not able to do so, I've never done it XD I was following the guide and I managed to edit the code, but don't know how to edit svg correctly.

**Comment by pastk** [comment]
SVG is actually a text file in xml format, you can try to replace the "inner shape" code (the `<path>` tag) of the old icon with the code from a new one.
But don't worry if you can't do it - you've helped already by finding a good suitable icon! Thanks!

**Comment by FinixFighter** [comment]
> SVG is actually a text file in xml format, you can try to replace the "inner shape" code (the `<path>` tag) of the old icon with the code from a new one. But don't worry if you can't do it - you've helped already by finding a good suitable icon! Thanks!

Ok, I'm sorry I can't help on this point. Thanks for your guidance anyway! ^^

**Comment by TheAdventurer64** [comment]
Any progress on this?

**Comment by charlie2clarke** [comment]
I've made some changes to try and complete this issue (https://github.com/organicmaps/organicmaps/compare/master...charlie2clarke:organicmaps:master). I followed all the documentation, and the tests passed. However, I believe I haven't added my entries to 'Icon.mapcss' correctly, as I am not seeing my newly made icons on the map.  Does anyone know what I am doing wrong here?

**Comment by endim8** [comment]
> I am not seeing my newly made icons on the map. Does anyone know what I am doing wrong here?

You need to re-generate the map file for it to include the new type (see [maps_generator/README.md](https://github.com/organicmaps/organicmaps/blob/master/tools/python/maps_generator/README.md))

also, it's good practice to separate the styles and strings generation into a separate commit (eg. [3132/commits](https://github.com/organicmaps/organicmaps/pull/3132/commits))

looks good to me otherwise :)

**Comment by pastk** [comment]
> I've made some changes to try and complete this issue ([master...charlie2clarke:organicmaps:master](https://github.com/organicmaps/organicmaps/compare/master...charlie2clarke:organicmaps:master)). I followed all the documentation, and the tests passed. However, I believe I haven't added my entries to 'Icon.mapcss' correctly, as I am not seeing my newly made icons on the map. Does anyone know what I am doing wrong here?

Thanks for working on it!
Haberdasheries don't show up because maps should be re-generated first to include them (but you don't have to do it to contribute).
And actually, as mentioned above, 
>As the shop=haberdashery and shop=sewing are identical it makes sense to merge the haberdashery tag into a sewing shop (so in OM all haberdasheries will appear as sewing shops) - it needs to be done in data/replaced_tags.txt.

I can see there are some other issues in your changes (e.g. please separate your manual changes and automatic changes by scripts into different commits) - please feel free to submit a PR so that we can review and provide feedback to you!

**Comment by pastk** [comment]
Done in #4839
