### ISSUE TITLE
[routing] Navigation prioritized exiting and re-entering motorway

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#2020]
When creating a route on the motorway surrounding Toulouse, navigation is asking users to take exit 17 to re-enter directly the same motorway. This is an error as the user should not have to exit.

Example route (could only reproduce on this side of the road and on this exit):
- start: `43.587808, 1.495385`
- end: `43.600145, 1.490489`
![Screenshot_20220204-190712_Organic_Maps](https://user-images.githubusercontent.com/80701113/152580464-3b772000-21e9-44ee-91d3-b40fe8387ace.png)

- OS: Android 9
- Organic Maps version: 2022.01.15-3-F-Droid
- Data Version: 220103

**Comment by vng** [comment]
Will be fixed in the next app/data update.

**Comment by vng** [comment]
Also, check:
"From Clayton, NC to FarmVille, NC, the program had me exiting the roadway 4 times just to re-enter the roadway."
