### ISSUE TITLE
Wikipedia link is added to a building if it's part of relation with wikipedia tag

### ISSUE THREAD

**Issue by strump** [organicmaps/organicmaps#2052]
If there's relation with tag `type = associatedStreet` and non-empty `wikipedia` tag than all buildings in such relation get Wikipedia link in OrganicMaps. The problem is when you edit such building (e.g. add number of levels) it's saved to OSM database with `wikipedia` tag inherited from relation.

<img src="https://user-images.githubusercontent.com/720808/153010346-311ef5c0-3e95-486d-8f58-6f841fd3cb7d.png" width="300px"/>

Most of buildings in Ukraine are members of `associatedStreet` relations. And in Kyiv most of street relations have `wikipedia` tag. Here's example of changeset when wikipedia tag was added by OM: https://osmcha.org/changesets/106682968/

**Comment by biodranik** [comment]
So what is the proper fix?
1. Is it correct to display Wiki page link as it is displayed now?
2. Should the fix check on upload if there is a parent relation for the way with associated Wiki entry exists, and if yes, then drop Wiki link?

**Comment by strump** [comment]
Expected behaviour: Wikipedia link should not be uploaded to OSM for such buildings.

But if Wikipedia link is not inherited from a parent relation but is assigned to a building itself, then it should not be removed on edit.
