### ISSUE TITLE
Regularly Illogical Routing When on A Highway -- App Will Route Off and Immediately Back On

### ISSUE THREAD

**Issue by Scrapporoid** [organicmaps/organicmaps#2057]
Hi,

This has been a regularly-occurring frustration from when I used Maps.me and continues now I've moved to Organic Maps.  The problem occurs when you're on a straight section of a main limited-access highway that has multiple crossing roads with entrances/exits, but your route will be going straight past those exits.  Instead of staying on the highway and continuing past the exit, the app will tell you to exit, take you through an intersection, and then back on to the highway.  I've attached just one example of multiple dozens of places this occurs.  I have looked at how the roadways are modeled in these Open Street Maps areas and don't see any issues with the data.

In this example, the intersection in question is at GA-400 and Holcomb Bridge Road in Roswell, Georgia, USA (34.02178, -84.32429).  The screen shot is "track up" heading south and the OSM screenshots are oriented north up.

The app is 2022.01.15-3-Google, Data Version 2200103 on a Pixel 4a running Android 11.

Thanks in advance,
Shawn
![maps_Screenshot_20220206-113010](https://user-images.githubusercontent.com/97354126/153041826-b7a9fa07-7367-4a2c-b75f-4f49801b2472.png)
![maps_OSM_400-Holcomb_2](https://user-images.githubusercontent.com/97354126/153041881-d9710826-a875-438e-91a3-001e3943dc82.png)
![maps_OSM_400-Holcomb](https://user-images.githubusercontent.com/97354126/153041896-e78ae827-fb44-4fd6-a4b4-f717ed0c497c.png)

**Comment by biodranik** [comment]
I think it should be fixed with the next app/maps data update. @vng?

**Comment by Scrapporoid** [comment]
That's great to hear, biodranik!

**Comment by vng** [comment]
Yes, it should. Will check with the new data update.

**Comment by Scrapporoid** [comment]
I wanted to follow up and say that this problem appears to be fixed.  In the last month, I have driven two highways where this occurred frequently and it hasn't occurred even once.
