### ISSUE TITLE
Add "Google Play Services" to strings

### ISSUE THREAD

**Issue by MetehanOzyurek** [organicmaps/organicmaps#2062]
It's hardcoded here: res/xml/prefs_main.xml
It shoud be changed to reference a localization from strings.txt

![IMG_20220209_144602_004.jpg](https://user-images.githubusercontent.com/80093621/153194231-ea5bc74a-c1f3-4e78-9e5e-e65f433d64a2.jpg)
![IMG_20220209_144608_548.jpg](https://user-images.githubusercontent.com/80093621/153194004-6c0584dd-3b22-478f-8ee1-a5f3d6d5323d.jpg)

**Comment by pastk** [comment]
To fix:
- replace a verbatim Google Services string in `android/res/xml/prefs_main.xml` with a string id/key
- add this new string id/key and its translations into strings.txt

**Comment by MetehanOzyurek** [comment]
> To fix:
> - replace a verbatim Google Services string in `android/res/xml/prefs_main.xml` with a string id/key
> - add this new string id/key and its translations into strings.txt

@pastk I'm not sure that I can do.
