### ISSUE TITLE
Add gambling, stripclub etc.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#210]
- stripclub
- gambling
- adult_gaming_centre
- bookmaker
etc

**Comment by dvdmrtnz** [comment]
Icon proposal for `amenity=stripclub` and `amenity=brothel`:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/eeb08368-fa04-4fe9-a79c-f68ba6826186" width="35px"/>

**Comment by Misalf-git** [comment]
IMO, The bigger X in the middle makes it too stylized.
I'd rather keep it boring (all same size) as the tripple-X already describes something by not describing it, thereby evading attention.

**Comment by dvdmrtnz** [comment]
Same size alternative:
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/dce14c92-cd4d-4ff1-8924-ecc052b0e350" width="35px"/>

 --

Taller:
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/b32bab0c-a7bf-49a1-9cf0-c831e274343f" width="35px"/>

**Comment by Misalf-git** [comment]
> Same size alternative:
> <img src="https://github.com/organicmaps/organicmaps/assets/47610359/dce14c92-cd4d-4ff1-8924-ecc052b0e350" width="35px"/>

I think this is good.

**Comment by dvdmrtnz** [comment]
`amenity=gambling`, `leisure=adult_gaming_centre`, `shop=bookmaker` and `shop=lottery` could use a cloverleaf icon

https://fontawesome.com/icons/clover?f=classic&s=solid

**Comment by dvdmrtnz** [comment]
> `amenity=gambling`, `leisure=adult_gaming_centre`, `shop=bookmaker` and `shop=lottery` could use a cloverleaf icon
> 
> https://fontawesome.com/icons/clover?f=classic&s=solid
> 
> <img alt="" width="35px" src="https://user-images.githubusercontent.com/47610359/261820344-e20d6b18-29b5-42a6-9a7b-aa7106f8eeb2.svg">

Or maybe better a clubs symbol ♣

**Comment by RedAuburn** [comment]
i think some cards or dice would be good for gambling (top right):
<img width="400px" src="https://st2.depositphotos.com/1069290/8386/v/950/depositphotos_83862252-stock-illustration-gambling-icons-set-vector.jpg"/>

**Comment by Misalf-git** [comment]
> Or maybe better a clubs symbol ♣

That's probably better describing symbol for gambling than a cloverleaf, since a cloverleaf is associated with **_good_** luck, while gambling is more about loosing.

**Comment by dvdmrtnz** [comment]
> i think some cards or dice would be good for gambling (top right):
> <img alt="" width="400px" src="https://camo.githubusercontent.com/f555be8b7355adc85065baa1f4221550ef3e0672a5aafc45cffc23e1a96ad8db/68747470733a2f2f7374322e6465706f73697470686f746f732e636f6d2f313036393239302f383338362f762f3935302f6465706f73697470686f746f735f38333836323235322d73746f636b2d696c6c757374726174696f6e2d67616d626c696e672d69636f6e732d7365742d766563746f722e6a7067">

We already have dice for `amenity=casino`. 

<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/casino-m.svg" width="35px"/>



Cards could be good for gambling.

**Comment by dvdmrtnz** [comment]
Also leisure=amusement_arcade needs to be added. Icon could be same as OSM Carto:

<img src="https://wiki.openstreetmap.org/w/images/4/44/Amusement_arcade-14.svg" width="35px"/>

https://wiki.openstreetmap.org/wiki/Tag:leisure%3Damusement_arcade

**Comment by Misalf-git** [comment]
If there are no concerns about copyright regarding Space Invaders, I'd suggest something more recognizable (like RetroArch is using):
![Invader_resized.png](https://github.com/organicmaps/organicmaps/assets/72605561/d22a5434-d028-4fc9-8f8a-aeef7021a753)

**Comment by dvdmrtnz** [comment]
> If there are no concerns about copyright regarding Space Invaders, I'd suggest something more recognizable (like RetroArch is using): ![Invader_resized.png](https://user-images.githubusercontent.com/72605561/261848842-d22a5434-d028-4fc9-8f8a-aeef7021a753.png)

It would be nice, however I would guess that they are copyrighted.

**Comment by dvdmrtnz** [comment]
Proposal:

amenity=gambling: <img src="https://github.com/organicmaps/organicmaps/assets/47610359/f0d74a01-4eff-4962-bec0-43c2644524df" width="35px"/>

leisure=adult_gaming_centre: <img src="https://github.com/organicmaps/organicmaps/assets/47610359/b1c47324-370c-4e3b-b622-b449e92f0668" width="35px"/>

leisure=amusement_arcade: <img src="https://github.com/organicmaps/organicmaps/assets/47610359/c08ed9ad-cc18-4b42-99e7-4673580889a1" width="35px"/>

shop=bookkeeper and shop=lottery: <img src="https://github.com/organicmaps/organicmaps/assets/47610359/501b0437-fc9f-42f0-ae97-fc6f841050e5" width="35px"/>

**Comment by Misalf-git** [comment]
> amenity=gambling: <img src="https://github.com/organicmaps/organicmaps/assets/47610359/f0d74a01-4eff-4962-bec0-43c2644524df" width="35px"/>

The heart somehow drives me away from the impression of gambling.
Would you try with ♠︎ (spade) or ♦︎ (diamond)?

**Comment by dvdmrtnz** [comment]
> > amenity=gambling: <img alt="" width="35px" src="https://user-images.githubusercontent.com/47610359/261854464-f0d74a01-4eff-4962-bec0-43c2644524df.svg">
> 
> The heart somehow drives me away from the impression of gambling. Would you try with ♠︎ (spade) or ♦︎ (diamond)?

You're right. With spade:

<img alt="" width="35px" src="https://github.com/organicmaps/organicmaps/assets/47610359/ac5aa47d-1573-4b1c-bbb7-14e15b548c8c">

**Comment by dvdmrtnz** [comment]
I am working on a PR to add these icons. While preparing the PR, I noticed that there is already a [shop=bookmaker](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbookmaker) icon: 
<img width="35px" src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/bookmaker-m.svg">

I am not sure what this icon is supposed to represent. I was going to change the icon to: 
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/501b0437-fc9f-42f0-ae97-fc6f841050e5" width="35px"/>

Should we keep the current icon or change it?

**Comment by vng** [comment]
I like these icons: https://github.com/organicmaps/organicmaps/issues/210#issuecomment-1685284923
