### ISSUE TITLE
[android] Improve input text hints for EditText fields

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#2117]
This is the warning in the current code when you select a bookmark and press "Edit bookmark":
```
I TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
```

According to [this](https://stackoverflow.com/questions/35775919/edittext-added-is-not-a-textinputedittext-please-switch-to-using-that-class-ins) post, EditText wrapped inside TextInputLayout should be wrapped inside [com.google.android.material.textfield.TextInputLayout](https://stackoverflow.com/questions/38423809/android-support-design-widget-textinputlayout-could-not-be-instantiated)

All EditText fields should be replaced in resources and in the code for better behavior.

**Comment by Gfenrir** [comment]
Hello, 
if this is still available, can I work on it ?

**Comment by biodranik** [comment]
It would be great!

**Comment by Gfenrir** [comment]
Thank you, i'll do the pull request soon then.

**Comment by Gfenrir** [comment]
By the way, can you assign me the task (in case you forgot to do it).

**Comment by shankarpriyank** [comment]
Hey @Gfenrir are you still working on this ?

**Comment by Gfenrir** [comment]
yes, but i had trouble setuping everything i needed.

**Comment by Gfenrir** [comment]
Update on the issue, 
I can't seem to be able to finish the issue, my computer doesn't have enough memory to make the app work. 
Sorry but if anyone want to work on the issue it's now free.
