### ISSUE TITLE
Improve highway=footway visibility

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#2123]
(originally posted in https://github.com/organicmaps/organicmaps/issues/1427#issuecomment-1005172739)

At the moment footways are rendered by a white dashed line, which looks great in urban setting imho, but there are cases when its hardly visible against pale backgrounds (https://www.openstreetmap.org/way/119140699#map=16/51.0872/-1.4516):
![Screenshot_1644924862](https://user-images.githubusercontent.com/18434508/154054465-81cd280d-0183-45bf-aa4c-ffe86925e28b.png)
The footway in the center at the edge of farmland and meadow is very hard to see.
Note that in the bottom another footway in the middle of farmland is more visible, but not good still.

Let's brainstorm how to make it better without breaking visibility of other things :)
![Screenshot_1644925485](https://user-images.githubusercontent.com/18434508/154055792-4df0d4e8-971f-479c-a3ea-e176a5606d04.png)

Some ideas:

- make pale backgrounds darker - could break visibility of other features, also it'll be good to keep the "light" theme light :)
- add some kind of a shadow/halo to the dashed line or fill in gaps between dashes with a darker color - afaik not supported by our renderer at the moment, but could be implemented
- play with dashes and gaps size - its unlikely to have a significant effect as it won't change the contrast
- switch footways color from white to dark e.g. dark red/burgundy
it might be a big change for users who is accustomed to white sidewalks in urban areas
however it will make footways rendering closer to `highway=path` which is dashed brown and for most users a distinction between footway and path is confusing anyway; also it'll be closer to OSM.org rendering which is red dotted line

**Comment by pastk** [comment]
And an example with a good-looking white footway
![Screenshot_1644926335](https://user-images.githubusercontent.com/18434508/154058000-f5439f7a-1050-4334-8fc4-763c8a92aac0.png)

**Comment by pastk** [comment]
BTW we have a similar issue with smaller roads, e.g.
(51.48894,0.01497)
![Screenshot_1644926816](https://user-images.githubusercontent.com/18434508/154059169-0dcee3c8-335d-4c66-98f8-184c4332b5d1.png)

**Comment by pastk** [comment]
A minor change option:

current style is to the left
to the right the footway is brighter (max white) and the farmland is a bit darker

![darker-farmland](https://user-images.githubusercontent.com/18434508/154090522-8819d769-ef19-4b8f-8e6c-a5f6328f6bb3.png)

**Comment by pastk** [comment]
An option with reddish color similiar to the `highway=path` (path and track rendering added for comparison).

![footway-path](https://user-images.githubusercontent.com/18434508/154131155-48a6a537-5967-4262-bba6-53f0305c1558.svg)

**Comment by biodranik** [comment]
Looks better, maybe not so red ) Would be great to see it in cities.

**Comment by pastk** [comment]
Looks too bold in the cities. Much more visibility than lesser roads even.

![Screenshot_1645023537](https://user-images.githubusercontent.com/18434508/154292853-00c910d4-1132-4e87-9310-16a14aad926e.png)

Could probably improve it playing with width and opacity at lower zooms, but its going to be more prominent than before anyway (as it was the point basically)...

BTW, in OSM `footway` and `path` are rendered exactly the same. Maybe we should do it too.
ATM they look a little different (footways are reddish):

![Screenshot_1645023652](https://user-images.githubusercontent.com/18434508/154292869-3d6abd93-5384-45c1-8aa3-130e1dcb8b4e.png)

**Comment by biodranik** [comment]
Let's make a branch with it and test. Don't make them equal, but make the red one a bit more brownish.

**Comment by pastk** [comment]
Its so brownish already that I wouldn't tell a path apart from a footway unless both of them are in a viewport :) That's why I thought maybe its easier to use same color but different dash lenghts maybe  if we want them to look differently.

But the biggest issue is that the roads should be more visible than footways around. We can do it by adding a thin casing around (just like OSM and OSMand do) at the expense of slower rendering.

**Comment by pastk** [comment]
I'm leaning towards a more complex solution which we can implement in a few steps:
1. make farmlands and parkings darker - it's an easy and small change and will help both with footways and lesser roads visibility (though won't solve the issue completely)
2. experiment more with dark footways and looks harmonization with paths (and tracks, bridleways..)
3. experiment with adding casing to the roads when needed - extra benefit is it'll allow to distinguish between paved/unpaved by altering solid/dashed casing like other renderers do
