### ISSUE TITLE
"Subway" transit vs "Subway" restaurant

### ISSUE THREAD

**Issue by zyphlar** [organicmaps/organicmaps#2133]
When I search for Subway, I want to find a nearby national sandwich restaurant chain, but the results I get are for underground transit networks 500 miles away. Searching for Subway Restaurant fixes the problem, but it seems like since the name of the place is only Subway, that I shouldn't have to specify when there are no other nearby results.

**Comment by biodranik** [comment]
You are correct, there is a bug in our search ranking. Of course, local results with a fully matching name should be displayed at the top instead of remote subway stations.

**Comment by biodranik** [comment]
Also see #678

**Comment by zyphlar** [comment]
Ah sorry I thought I searched for an existing issue, I guess not well enough
