### ISSUE TITLE
CarPlay does not show all bookmarks

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#2145]
There is a limit (why?) of 24 bookmarks for a list. So it is not possible to choose those above 24.

**Comment by fabwu** [comment]
This is a limit imposed by Apple and cannot be changed (see [here](https://developer.apple.com/documentation/carplay/cplisttemplate/maximumitemcount)). 

There's also a [reddit post](https://www.reddit.com/r/apple/comments/alrhpq/carplay_limits_max_number_of_visible_list_items/) about it:

> It’s purposely designed that way so you concentrate on the road, not the titles of podcasts. Apple has very specific CarPlay rules and app developers have to be specifically approved to write them.

**Comment by biodranik** [comment]
Can we provide a workaround, or at least warn a user about it?

**Comment by fabwu** [comment]
> Can we provide a workaround, or at least warn a user about it?

We could replace the last cell with a info for the user:
<img width="565" alt="image" src="https://github.com/user-attachments/assets/0c2dcd45-9fad-4e98-bb57-45809d31d009">

**Comment by biodranik** [comment]
Good idea! Can this cell be tappable and do the switch to the phone?

**Comment by fabwu** [comment]
> Good idea! Can this cell be tappable and do the switch to the phone?

That might be possible but it might distract the user from driving. I would just leave the message cell and if the user want to select more bookmarks he can pickup the phone and switch screens.
