### ISSUE TITLE
Pitch and sport icon conflict

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#2164]
_Originally posted by @kudlav in https://github.com/organicmaps/organicmaps/issues/1280#issuecomment-922526542:_

Similar with `leisure=pitch` + `sport=basketball`. The icon is changed from running person into basketball when zooming in.
\--
![Screenshot_20210917-163137_Organic Maps](https://user-images.githubusercontent.com/11516259/133940927-4b9678db-9087-4266-b307-8c241eaa6e5b.png)
++
![Screenshot_20210917-163148_Organic Maps](https://user-images.githubusercontent.com/11516259/133940925-177f41c7-6ced-4a55-ba38-806638f4632a.png)

**Comment by pastk** [comment]
This case differs from the museum one.
In this case `leisure=pitch` icon rules are to display it from z17 zoom level, while basketball icon from z18 level and it has a higher priority.
Hence at z17 we see a pitch icon and at z18-19 - a basketball one.

BTW when you select an icon what text is displayed in the bottom sheet?

**Comment by kudlav** [comment]
Hi, it's this pitch: https://www.openstreetmap.org/way/380467073

Bottom sheet always says Basketball.

**Comment by pastk** [comment]
Its a case similar to #1414 actually.

First thing we need to decide what should be primary here - a pitch or a basketball?
I think that pitch is more important than a sport that is practiced there (similarly in #1414 a stadium is more important).

**Comment by biodranik** [comment]
Both `pitch * basketball` should be displayed.

**Comment by pastk** [comment]
> Both `pitch * basketball` should be displayed.

Text-wise yes, but what about an icon?

Here a more specific basketball icon seems more appropriate though in #1414 a stadium icon is preferable I think (as its a prominent physical structure).

**Comment by pastk** [comment]
BTW another issue with screenshots above is that pitches fill is indistinguishable from surrounding grass - could make colors a bit different.

**Comment by pastk** [comment]
So this issue could be solved by making a basketball icon display starting from z17 same as pitches icon. Icons for other sports that could be practiced at `leisure=pitch` should be moved to z17 too. Hence a generic pitch icon will be used only in cases of sports for which we don't have a specific icon.

The "Pitch * Basketball" text change needs coding and could be done in a different issue e.g. #1414

**Comment by pastk** [comment]
> BTW another issue with screenshots above is that pitches fill is indistinguishable from surrounding grass - could make colors a bit different.

Actually a pitch has a different color, but `landuse=grass` around has a higher z-index hence overrides pitches fill. Amending z-indexes should fix it. Related to #2166

**Comment by endim8** [comment]
fixed by https://github.com/organicmaps/organicmaps/pull/2925
