### ISSUE TITLE
Redirect to localized OSM wiki pages

### ISSUE THREAD

**Issue by MetehanOzyurek** [organicmaps/organicmaps#2167]
When you tap to "learn more about OpenStreetMap" button, it is redirecting you to English wiki page even when your device/OM language is different. Please redirect defaut language wiki page.
For example,
Turkish version of About OSM:
 https://wiki.openstreetmap.org/wiki/Tr:About

**Comment by MetehanOzyurek** [comment]
@biodranik is it possible to make this as localized Telegram/Instagram links?

**Comment by biodranik** [comment]
Yes, I see two hardcoded links in iOS:
```
iphone/Maps/Classes/CustomViews/Login/MWMAuthorizationLoginViewController.mm
104:  [self openUrl:@"https://wiki.openstreetmap.org/wiki/Main_Page"];

iphone/Maps/UI/Editor/MWMEditorNotesFooter.m
25:  [self.controller openUrl:@"https://wiki.openstreetmap.org/wiki/Main_Page"];
```

And one in Android (they're different!):
```
android/src/com/mapswithme/util/Constants.java
40:    public static final String OSM_ABOUT = "https://wiki.openstreetmap.org/wiki/About_OpenStreetMap";
```

**Comment by endim8** [comment]
Is it possible/advisable to store links in the translation strings? That would be an easy solution as it falls back to English

**Comment by biodranik** [comment]
Yes, that is a good idea which is already used for other cases.
