### ISSUE TITLE
Area fill priorities

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#2170]
There are cases when sorting areas by z-index is not enough, e.g. generally a parking lot should be drawn over the forest, but a strip of trees tagged as a forest should be drawn over the parking lot area.

Looks like the best solution is to always draw enclosed features over the enclosing ones, some examples:
parkings, forests, lawns, parks, etc. over hospital / university grounds
https://www.openstreetmap.org/way/191553797
https://www.openstreetmap.org/way/95514530
![1](https://user-images.githubusercontent.com/18434508/155022799-3e834cca-cae7-4725-83f8-d8df233c8d5b.png)

There are patches of forest and a playground that should be drawn over the park here:
https://www.openstreetmap.org/way/29457433
![2](https://user-images.githubusercontent.com/18434508/155022964-5edeedf2-0e0a-4ba7-913b-4e053a4b6473.png)

A `leisure=pitch`, fitness stations and a parking should be drawn over `landuse=grass` here:
https://www.openstreetmap.org/way/380467073
![3](https://user-images.githubusercontent.com/18434508/155023791-887b7316-c52f-4736-bf8b-6f8ff7dbc39a.png)

A more complex case is when areas are not enclosed inside each other, but intersect:
https://www.openstreetmap.org/relation/2994307
![intersect](https://user-images.githubusercontent.com/18434508/155023966-b2785acd-0389-47e6-9be9-3a030c949928.png)
Possible solutions for such cases:
- mix the fills somehow (OSM has a good example)
- the area which is smaller gets a higher priority (hospital grounds in this case), but information about forest patches inside will be lost
- draw a border around a hospital (a forest should be drawn over hospital grounds, but hospital's border drawn over the forest? hmm)

Hopefully its a fringe case, would be great to estimate the frequency somehow.

**Comment by biodranik** [comment]
@vng can we code exceptions for styles and draw smaller areas on top of bigger areas?

**Comment by pastk** [comment]
> 
> A `leisure=pitch`, fitness stations and a parking should be drawn over `landuse=grass` here: https://www.openstreetmap.org/way/380467073 ![3](https://user-images.githubusercontent.com/18434508/155023791-887b7316-c52f-4736-bf8b-6f8ff7dbc39a.png)


![2023-02-26-211816_1366x768_scrot](https://user-images.githubusercontent.com/18434508/221437908-f4a85f33-b1b3-40a7-a4e9-ec27ad8379ba.png)

Its better now, though we don't have an area style for `leisure-fitness_station` hence its not rendered :)
BTW, fitness stations are not rendered in this case on OSM too! :)
