### ISSUE TITLE
[android] Search floating toolbar need two clicks on query to go back to the list

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#2171]
When showing search results on the map after clicking on the "Show on map" button, you need to click twice on the search query in the floating toolbar to go back to the list (the search activity). In previous releases you only had to click once.

This is an important issue as when you click the keyboard shows up and you can edit the query, but the search will not be updated.

https://user-images.githubusercontent.com/80701113/155028828-d73aef8b-5c28-4616-aa4e-374f0bd0fbf6.mp4

- OS: Android 9
- Organic Maps version: 2022.02.16-29-FDroid
- OpenStreetMap data: Feb 4, 2022

**Comment by biodranik** [comment]
Could it be caused by #2006 ?

**Comment by arnaudvergnet** [comment]
Maybe I will try to investigate but I only noticed it while working on #2081 and rebasing on master.

**Comment by biodranik** [comment]
It looks like an old bug. I tried to edit the search query but the results on the screen were not updated. Let's fix it and make a one-click open back the search dialog.

Maybe in the future we'll refactor it and make a better search UX when the map is visible.
