### ISSUE TITLE
[android] Cannot show keyboard when app is on the lockscreen

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#2172]
When the app is on the lockscreen, the keyboard cannot be shown so all search bars and text fields are unusable.

If it is not possible to make the keyboard show on the lockscreen due to limitation in Android, it may be a good idea to prevent users from accessing screens making use of the keyboard.

For example, place editing could be disabled when on the lockscreen, and the search bar could be removed.

- OS: Android 9
- Organic Maps version: 2022.02.16-29-FDroid
- OpenStreetMap data: Feb 4, 2022

**Comment by biodranik** [comment]
Are you speaking about the #1928 ? That's a serious limitation.

**Comment by arnaudvergnet** [comment]
Yes exactly

**Comment by biodranik** [comment]
@arnaudvergnet I have tested it on Sony's Android 10, all keyboards are visible and working properly. Is there some specific setting in your case that disables keyboards on the lock screen? Do you have a stock Android or some custom firmware?

**Comment by arnaudvergnet** [comment]
I use a custom ROM based on LineageOS but I don't see any setting to change this. Maybe this was added in Android 10?

**Comment by biodranik** [comment]
Tested on Samsung's Android 8: works properly. Google's Android 9: works properly. Lineage OS Android 11: works properly.

I can't reproduce the issue.

Please check your firmware or its settings.

**Comment by arnaudvergnet** [comment]
This may be an issue with my ROM then. I'll try to see with its devs thanks.

**Comment by arnaudvergnet** [comment]
If anyone else if having the issue, I updated my phone from Android 9 to 10 (same custom ROM) and I can now use the keyboard on the lock screen within OM. So if you have this problem, try updating your Android version if possible.
