### ISSUE TITLE
Building polygon render bug

### ISSUE THREAD

**Issue by gtrus21** [organicmaps/organicmaps#2176]
Здание отображается "разорванным"
56.116145, 47.257282
![Screenshot_2022-02-22-12-48-21-463_app organicmaps](https://user-images.githubusercontent.com/69676792/155107764-4e559249-d8b2-4edc-a4f5-2d2e6ad4d6fe.jpg)

**Comment by endim8** [comment]
https://www.openstreetmap.org/relation/7876262

Seems to be something to do with using multiple ways in a relation to define an area

**Comment by Jean-BaptisteC** [comment]
Fixed on 2023.09.22-27-Google
