### ISSUE TITLE
Make Voice Guidance Sound More Natural

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#2178]
Would it be possible to make the navigation voice guidance sound more natural?

**Comment by biodranik** [comment]
There are only two options:
1. You update/change your TTS engine or the voice in it.
2. We find somewhere a copyright-free recorded voices for all our announced directions (see data/strings/sound.txt) and integrate their support.

**Comment by TheAdventurer64** [comment]
One solution would be to [get voice guidance from Mapbox](https://blog.mapbox.com/custom-voice-instructions-for-navigation-5052a6ffc032). However, that would require the use of the Mapbox Navigation SDK.

**Comment by TheAdventurer64** [comment]
Coming back to this, is there a way to change TTS on iOS?

**Comment by biodranik** [comment]
I think the only API is the official one (and it also works offline).

**Comment by TheAdventurer64** [comment]
> I think the only API is the official one (and it also works offline).

What do you mean by API? I meant is there a way to change the voice of the TTS?

**Comment by biodranik** [comment]
There are 1) device's settings and 2) OM settings. Did you try to change them?

**Comment by TheAdventurer64** [comment]
> There are 1) device's settings and 2) OM settings. Did you try to change them?

Yes. I changed system settings, but that didn't change anything. By trying to change OM settings, the voice was changed to Australian English.

**Comment by TheAdventurer64** [comment]
Anything we can do about this?
