### ISSUE TITLE
Render survey points & shelter icon

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#2181]
It'd be nice to render `man_made=survey_point` as an icon

**Comment by biodranik** [comment]
Are there any good and open SVG icons (or examples) for it?

**Comment by endim8** [comment]
According to [this](https://en.m.wikipedia.org/wiki/Triangulation_station), they are usually represented as a small triangle, which seems the best option to me.

OSMAnd renders it as a tripod, but i'm nlt such a fan of it: ![Screenshot_20220223-143819_OsmAnd~-01.jpeg](https://user-images.githubusercontent.com/26939824/155341224-f7551975-6efe-48f2-9d92-c81349165308.jpeg)

**Comment by biodranik** [comment]
What is the main value of these objects for different people using Organic Maps?

**Comment by endim8** [comment]
How do these look? I prefer the one without the fill:
<img width="734" alt="Screenshot 2022-02-27 at 00 47 45" src="https://user-images.githubusercontent.com/26939824/155863723-69b1c9b1-3f3b-4260-b1cc-8d80dc99260d.png">
[Left SVG](https://github.com/endim8/organicmaps/blob/8acdcca63b259e613aaf02cba939ab7c85c84e29/data/styles/clear/style-clear/symbols/survey_point-m.svg) | [Right SVG](https://github.com/endim8/organicmaps/blob/8acdcca63b259e613aaf02cba939ab7c85c84e29/data/styles/clear/style-clear/symbols/survey_point-m-alt.svg)

**Comment by biodranik** [comment]
Maybe something like this will be more clear? The triangle is associated with a peak.
![image](https://user-images.githubusercontent.com/170263/155879084-deddb885-4e67-45df-ba74-80eca14cc635.png)

**Comment by endim8** [comment]
@biodranik  how is this?
<img width="250" alt="Screenshot 2022-02-27 at 19 23 20" src="https://user-images.githubusercontent.com/26939824/155896653-aabceaeb-4f68-402c-bc60-ba4daa3cde54.png">
[link to svg](https://github.com/endim8/organicmaps/blob/add-survey_point/data/styles/clear/style-clear/symbols/survey_point-m-2.svg)

**Comment by biodranik** [comment]
Is it possible to remove a circle? We want to use circles only for businesses.

**Comment by endim8** [comment]
> Is it possible to remove a circle? We want to use circles only for businesses. But it is also important to make it visible in the night theme.

Can do 👍

Like a picnic table or like a bench?
<img width="43" alt="Screenshot 2022-03-01 at 00 03 08" src="https://user-images.githubusercontent.com/26939824/156079527-89efa297-6a85-4700-926b-16ef4b04bb14.png"> <img width="43" alt="Screenshot 2022-03-01 at 00 03 24" src="https://user-images.githubusercontent.com/26939824/156079549-752b8ea0-411b-4ca3-937e-baa6f0b78e6d.png">

**Comment by biodranik** [comment]
Like a bench. Please also remove the circle for the picnic table, and make sure that the bench, survey point, picnic table are properly displayed in the night theme (they need to have some light color or a different outline).

**Comment by endim8** [comment]
> Like a bench. Please also remove the circle for the picnic table, and make sure that the bench, survey point, picnic table are properly displayed in the night theme (they need to have some light color or a different outline).

I've done all this now (https://github.com/endim8/organicmaps/commit/c9195f7f563157a8dee7bfe63fbab3ff81a55759), but I've noticed that other icons also have the transparent circle, for example telephone and post boxes:
<img width="230" alt="Screenshot 2022-03-01 at 10 58 43" src="https://user-images.githubusercontent.com/26939824/156157436-ec377fb8-0072-47c5-8fbf-64b1c4b96874.png">

Should this be removed from all icons that don't have the centre circle? If so, I'll go through all the icons and check them

**Comment by endim8** [comment]
Alright, will do 👍 I'll move the picnic table change over too :)
