### ISSUE TITLE
icons: Community center disappears when zoomed in

### ISSUE THREAD

**Issue by jpds** [organicmaps/organicmaps#2186]
As of this month's release: the community center icon disappears as one zooms in closer to the map.

**Comment by biodranik** [comment]
Can you please provide coordinates or a link to OSM feature where we can test and reproduce it?

**Comment by jpds** [comment]
Sure, for instance this object in London: https://www.openstreetmap.org/way/834674020 - will appear as a star from afar, and that disappears as one gets closer and only the name is displayed.

**Comment by pastk** [comment]
An icon for `amenity=community_centre` is defined for z14-16 only for some reason. Its been like this for a long time - the last release changed nothing.

The fix is to make the icon z14-.
