### ISSUE TITLE
Add lat, lon coordinates in the web map when sharing location

### ISSUE THREAD

**Issue by CarlosBrys** [organicmaps/organicmaps#2190]
When someone shares a location and the link is opened in the web map, no useful information is provided.

It is very important to have this data to be able to copy it and use it in other applications.

The screen on the web site does not provide any information about the location being shared.

![image](https://user-images.githubusercontent.com/6495550/155841301-79ab6ec0-a30a-4ed9-aa2b-29df92144ce3.png)

**Comment by CarlosBrys** [comment]
The only thing I ask is that they show the coordinates of the point that was shared on the website.
If you follow the link to OpenStreetMap, it doesn't show the coordinates of the point either.
Do you want to see an example in another app?
![image](https://user-images.githubusercontent.com/6495550/155971200-7e27270d-ee9d-4ce8-ab39-b0d83c5571ff.png)

**Comment by biodranik** [comment]
The main reason is to copy coordinates, right? We'll do it.

**Comment by CarlosBrys** [comment]
I am deeply grateful.
In my province, the police and firefighters use Organics Maps to locate themselves and it is necessary to take the coordinates when they share a location to process them in other apps.

**Comment by biodranik** [comment]
Do you need any specific link to open coordinates faster in other apps? Like `geo:lat,lon`?

**Comment by CarlosBrys** [comment]
I think with geo: lat, lon is enough.
It would be of great help if clicking on the link in the mobile web app suggests seeing the point in Organic, or some installed map app.
Thank You

**Comment by biodranik** [comment]
This PR should close the issue: https://github.com/organicmaps/url-processor/pull/2

**Comment by biodranik** [comment]
Now coordinates are displayed.
