### ISSUE TITLE
Sync footways visibility with service roads

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#2208]
At the moment footways (e.g. sidewalks) are rendered starting from z14 and service roads (e.g. driveways inside a block of buildings) from z15.
However these roads are a much more significant features used both by motorists and pedestrians, so the service roads should be rendered at the same zoom levels as footways at least.

I think demoting footways from z14 to z15 is a better idea than promoting service roads from z15 to z14, because both footways and service roads are used in urban areas mostly and displaying footways at z14 generally doesn't make much sense anyway.

The row above: 
screenshots to the left - note that sidewalks are visible while driveways are not
to the right - some footways seem "hanging in the air", as the roads they connect are not rendered

The row below:
after making both footways and service roads visible from z15
z14 has a more clean look
the downside is that on the screenshots to the right paths and tracks are now "hanging", because they were mixed with footways and roads in this case
![demote-footways](https://user-images.githubusercontent.com/18434508/156371537-8d5de495-85ef-49d3-b80f-788970e05acb.png)

Related to #2207

**Comment by biodranik** [comment]
That looks better now. Let's implement it, but also create another issue to draw line and area styles dynamically: if they are too small, and are not connecting something already visible, then don't display them, even if the style allows it.

**Comment by pastk** [comment]
> That looks better now. Let's implement it, but also create another issue to draw line and area styles dynamically: if they are too small, and are not connecting something already visible, then don't display them, even if the style allows it.

Created #2210
