### ISSUE TITLE
Glitch selecting station whilst navigating

### ISSUE THREAD

**Issue by jpds** [organicmaps/organicmaps#2214]
Found this UI glitch whilst checking which station came before the one I was navigating to:

https://user-images.githubusercontent.com/29158971/156594909-ccc8c82d-9b78-4919-9c8f-6db46d2893fc.mp4

**Comment by Vanshitgupta9717** [comment]
I want to work on this issue. Please assign this to me and since I am new to this repo so please guide me through it.

**Comment by arnaudvergnet** [comment]
I looked through the code and found where to start working. There is a [TODO in `framework.cpp`](https://github.com/organicmaps/organicmaps/blob/master/map/framework.cpp#L2179) where the information for the place page should be created.
