### ISSUE TITLE
Many tracks are almost impossibly to see in dark mode

### ISSUE THREAD

**Issue by Syberiyxx** [organicmaps/organicmaps#2227]
![Screenshot_20220307-073759_Organic Maps.jpg](https://user-images.githubusercontent.com/2048087/157055098-50cb5d5f-2528-4fa8-8f45-ada10773d615.jpg)
![Screenshot_20220307-073816_Organic Maps.jpg](https://user-images.githubusercontent.com/2048087/157055111-b3d64e28-f979-469b-8711-2c8a92bcfff2.jpg)

**Comment by biodranik** [comment]
Agree, it makes sense to make roads more visible.

**Comment by pastk** [comment]
I would say that icons are too bright too. 

![night](https://user-images.githubusercontent.com/18434508/157632973-e58afc96-1519-4067-826f-9e9463a80b04.png)

**Comment by sybenx** [comment]
I still have this issue. It's especially difficult on mobile apps when any glare or fingerprints are visible on the screen. Things not easy to deal with while driving. ![image](https://user-images.githubusercontent.com/2048087/170086959-1dbd3cba-60a1-4616-bde8-c7701d941f3d.png)

**Comment by pastk** [comment]
> I still have this issue. It's especially difficult on mobile apps when any glare or fingerprints are visible on the screen. Things not easy to deal with while driving. 

The current "night mode" was initially developed as a low-contrast one, it needs a big overhaul to make it high contrast dark mode #688
