### ISSUE TITLE
Bunker POI

### ISSUE THREAD

**Issue by gtrus21** [organicmaps/organicmaps#2234]
Прошу добавить поддержку отображения бункеров (military=bunker)

**Comment by biodranik** [comment]
Какие именно бункеры вы хотите отображать и с какой целью? Большинство перечисленных бункеров в OSM явно имеют военное предназначение: https://wiki.openstreetmap.org/wiki/Tag:military%3Dbunker

**Comment by gtrus21** [comment]
Хотелось бы бомбоубежища, но в списке в вики нет конкретно их. Наиболее подходящий - personnel_shelter. Так же в чатах упоминался civil_shelter, но его в вики нет

**Comment by biodranik** [comment]
Не хотелось бы добавлять недокументированные вещи. Необходимо, чтобы сообщество сформулировало правила. Во всём мире сейчас [63 civil_shelter](https://taginfo.openstreetmap.org/keys/bunker_type#values), вряд ли его добавление поможет.

А добавление на карту явно военных целей не выглядит хорошей идеей.

**Comment by gtrus21** [comment]
Достаточно только с этими двумя типами. Но вводить надо сейчас, потом может быть и поздно. Если ввод этого тега поможет спасти хоть одну жизнь, то почему нет?

**Comment by biodranik** [comment]
Чтобы спасти жизни с помощью ОМ, надо добавить убежища в OpenStreetMap, сгенерировать данные, дождаться ревью у Google и Apple, дождаться, пока пользователи обновятся, и догадаются посмотреть на карту. Тут слишком длинная цепочка. Вы оценили, в каких странах сейчас находятся эти 63 убежища из OSM?

В большинстве стран жители либо знают о ближайших убежищах, либо спрашивают у тех, кто знает. Маловероятно, что люди будут искать их в OM.

Это не мешает начать работу над фичей, просто надо понимать value. На этом фоне, например, важность более частых обновлений данных гораздо выше.
