### ISSUE TITLE
[maybe bug?] Organic Maps will randomly say "Keep Left" or "Keep Right" when going straight through an intersection

### ISSUE THREAD

**Issue by CorruptComputer** [organicmaps/organicmaps#2238]
I'm not quite sure what causes it to happen, but sometimes Organic Maps will say either "Keep Left" or "Keep Right" when you are going straight through an intersection. 

I was able to get an exact intersection this happens at here: https://www.openstreetmap.org/node/2805280899
If you are driving on "Holcomb Bridge Road" heading south and going straight through that intersection, the app will say "Keep Right" when it just shouldn't say anything at all.

If this is some sort of mapping error instead of an issue with the app please let me know! I would be happy to fix these in OSM when I encounter them if thats the case.

Tested using Android app version 2022.02.19-1-Google

**Comment by biodranik** [comment]
I think it's our algorithm's bug. Sometimes it announces "keep left/right" in places where clearly there is only one main road going (almost) straight forward. Can you please share starting and ending points coordinates for this exact place to reproduce the issue? It would be also great to see the same route/directions in the OSM as a reference.

**Comment by CorruptComputer** [comment]
Sure no problem at all, try routing from (34.001784, -84.288465) to (33.99675, -84.282898) and you should be able to see the issue.

OSM doesn't seem to give any specific direction to keep right or left at that intersection: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=34.00182%2C-84.28843%3B33.99747%2C-84.28328#map=17/33.99961/-84.28587

**Comment by Jean-BaptisteC** [comment]
@CorruptComputer can you retry in latest version?

**Comment by CorruptComputer** [comment]
Looks like this issue has been resolved, I tried the same location I shared in the original post above and it didn't seem to be happening anymore. Thanks!
