### ISSUE TITLE
[android] Import bookmarks button doesn't allow to select a single file

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#2240]
The current implementation allows selecting only folders, not files. Some users have issues with that. They do not understand that the folder should be selected.

**Comment by shankarpriyank** [comment]
How are we planning to resolve this?

**Comment by biodranik** [comment]
Well, by allowing to select file(s) in addition to directories, and by properly importing only those files that were selected.

**Comment by Jean-BaptisteC** [comment]
Duplicate of #5413
