### ISSUE TITLE
Keyboard can not be removed in CarPlay when doing a search

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#2241]
When performing a search, if the search does not produce the correct results on the first line, there is no way to make the keyboard disappear in order to see the rest of the results if found. A prime example is below when searching for Fire Tower Road in Selma the system responds with Fire Tower Road in Bailey and no way to page down to see more results.

![image](https://user-images.githubusercontent.com/170263/157749779-a6194aac-ba6c-4207-a6f0-eea6f3d0c91e.png)

**Comment by theholy7** [comment]
This also happens on Apple Maps. I thought I was going crazy, because I can't dismiss the keyboard.
