### ISSUE TITLE
Runway.  Взлётно-посадочная полоса

### ISSUE THREAD

**Issue by FUZZY-42** [organicmaps/organicmaps#2246]
I would like to suggest to display numbers (ref=*) of runways (aeroway=runway) as they are displayed in OsmAnd app (ref=*). But it is desirable that (ref=*) be displayed as street names. 
__________________________________________________________________

Хотелось предложить отображения номеров (ref=*) взлётно-посадочных полос (aeroway=runway), так как в приложение OsmAnd (ref=*) отображается. Но желательно чтоб (ref=*) отображались как названия улиц.

**Comment by biodranik** [comment]
Приложите примеры рендеринга? И какую именно проблему решит отображение названий полос?

**Comment by RedAuburn** [comment]
duplicate of https://github.com/organicmaps/organicmaps/issues/2078
