### ISSUE TITLE
Bicycle routing doesn't consider steps

### ISSUE THREAD

**Issue by FinixFighter** [organicmaps/organicmaps#2253]
Today I planned a route by bike, and the app routed me on steps. I think that when an highway=steps doesn't have any additional specific tag (for examples bicycle=yes) then the app shouldn't route bike through steps.
This is the suggested route:
![275309741_685130342934669_8312164971556078383_n](https://user-images.githubusercontent.com/19877271/158164248-c7c4e47f-6367-40a9-b214-67f768f0fa40.jpg)
here are the steps I'm talking about: https://www.openstreetmap.org/way/322456728
and here is an example of handling this correctly (by OSRM): https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=42.46310%2C14.21342%3B42.46343%2C14.21250

**Comment by biodranik** [comment]
@vng should we increase steps penalty? Looks like the OSRM route is faster.

**Comment by Jean-BaptisteC** [comment]
OSRM suggest to use steps :)

**Comment by FinixFighter** [comment]
> OSRM suggest to use steps :)

But I really don't imagine my mum or girlfriend taking these steps with their city bikes when they have an alternate route available in 100m or less (first image refers to the OrganicMaps screenshot I published in my first post).
![scala1](https://github.com/organicmaps/organicmaps/assets/19877271/6d934516-1a08-475e-b8c4-490d6341e5ed)
![scala2](https://github.com/organicmaps/organicmaps/assets/19877271/edfa53f9-7614-4d9d-91dc-bca3dbd26fd7)

**Comment by pastk** [comment]
Currently OM avoids those stairs:
![image](https://github.com/user-attachments/assets/d4f1d755-51b1-4fe4-8b78-3ef0b9668e71)
This is 800m detour route instead of 100m direct via stairs.

**Comment by pastk** [comment]
With https://github.com/organicmaps/organicmaps/pull/9692:

a shorter route without weird turns
![2253_2024-11-19_21-23](https://github.com/user-attachments/assets/9dee7734-0d78-490c-9aea-2c31302e8d15)
