### ISSUE TITLE
School areas are not visible

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#2279]
Only school icon is visible, not a whole area as before.

**Comment by biodranik** [comment]
Coordinates to test?

**Comment by AntonM030481** [comment]
Check out
Unknown Place
35.155317, 33.351621
https://omaps.app/0yxfvv53GB/Unknown_Place
om://0yxfvv53GB/Unknown_Place

**Comment by pastk** [comment]
Duplicate of #1221

**Comment by pastk** [comment]
Fixed in #2341
