### ISSUE TITLE
Overlapping Buttons

### ISSUE THREAD

**Issue by GreenBeard** [organicmaps/organicmaps#2280]
On very odd resolutions the zoom out button overlaps the center on current location button. For example, the Unihertz Titan Pocket. According to the android settings app it is 716x720 in resolution.

![Screenshot_20220324-034624](https://user-images.githubusercontent.com/2000704/159878179-5d59b30d-c098-4211-879f-dd2ed78794f8.png)

**Comment by arnaudvergnet** [comment]
Fixed by https://github.com/organicmaps/organicmaps/pull/2905. If you still encounter issues with overlapping buttons in next month's release, please open a new issue.
