### ISSUE TITLE
Navigation prioritizes getting on and off freeway

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#2285]
When navigating from 21.277841, -157.779314 to 21.296098, -157.823823, Organic Maps seems to route you on and off the freeway, when the route should just stay on the freeway.

**Comment by biodranik** [comment]
Is it for the car route?

**Comment by vng** [comment]
Confirm. Should be fixed with the new "default" speeds model within each MWM.

This route has _in and out_ city roads (this is another thing to investigate, because of correct Honolulu boundaries), and primary out city default speed (Wailalae ave) > 50 mph (Lunalilo freeway).
