### ISSUE TITLE
Main menu color is different from other screens (for example, Settings)

### ISSUE THREAD

**Issue by dbf256** [organicmaps/organicmaps#2297]
For Android new build. It looks inconsistent.
![diff_2](https://user-images.githubusercontent.com/2550295/160287748-0b3b0234-0a5d-4d1c-9693-1224569deaef.jpg)
![diff_1](https://user-images.githubusercontent.com/2550295/160287749-a3038673-54f6-45c4-8775-dad22e941865.jpg)

**Comment by endim8** [comment]
I'm not such a big fan of the new colour either, but it's only because that's the default colour, hopefully it'll be fixed in the future :)

**Comment by arnaudvergnet** [comment]
Thanks for noticing! On my test device the bottom navigation bar was black (while yours is white) so I did not notice the subtle color change. But you are right this should and will be changed. I will work on this as soon as I finished migrating the old codebase to the new official Android components.

**Comment by biodranik** [comment]
@arnaudvergnet is it hard to make the menu background white in the light theme?

**Comment by arnaudvergnet** [comment]
It should just be a matter of find the right theme key here:

https://github.com/organicmaps/organicmaps/blob/master/android/res/values/styles.xml#L396-L402

I did not find the time to fix this yet. If anyone wants to try it should not be very hard.
