### ISSUE TITLE
Font issue?

### ISSUE THREAD

**Issue by vachan-maker** [organicmaps/organicmaps#2313]
I think there is something wrong with the font. Some letters are smaller and some other letters are bigger. 

Screenshot:
![image](https://user-images.githubusercontent.com/65799568/160600504-7ca7db14-e071-410f-aaf5-f89028a3f37a.png)

Here the letter e is big

![image](https://user-images.githubusercontent.com/65799568/160600587-ba4e8732-47e8-4a3c-94c3-01b9aa62a6fd.png)

**Comment by biodranik** [comment]
Android? iOS? Can you please share your device's log (with fonts) if it's Android?

**Comment by vachan-maker** [comment]
I use Oppo A5 2020 running Android 10.
I use the default font and i don't know how to get the font log. Checked settings and it just says Default Font.
Using the latest version of organic maps which I downloaded from GitHub.
Thanks

29 Mar 2022, 6:16 pm by ***@***.***:

**Comment by biodranik** [comment]
Please temporarily enable logs recording in OM settings, restart the app and send us logs via "?" / Report a bug dialog

**Comment by vachan-maker** [comment]
Thanks for the instructions
I sent it via email


30 Mar 2022, 3:50 am by ***@***.***:

**Comment by vng** [comment]
We have got your logs, thanks. I have the same picture on desktop with RobotoMedium font family:
<img width="212" alt="Screenshot 2022-03-30 at 08 57 20" src="https://user-images.githubusercontent.com/175612/160762072-a08ee9d3-c62c-4886-8ba0-714f0ef7174a.png">
<img width="141" alt="Screenshot 2022-03-30 at 09 01 28" src="https://user-images.githubusercontent.com/175612/160762077-b65d8c5e-8201-4999-acb3-6d83788a90c2.png">

**Comment by biodranik** [comment]
It could be our FreeType renderer issue.

**Comment by vng** [comment]
Maybe. I removed roboto font file from bundle and here is how DejaVu Sans:Book font family looks like:
<img width="207" alt="Screenshot 2022-03-30 at 10 48 01" src="https://user-images.githubusercontent.com/175612/160779708-a58e8dc1-de71-4510-a4c9-3825cbf95585.png">
<img width="123" alt="Screenshot 2022-03-30 at 10 48 06" src="https://user-images.githubusercontent.com/175612/160779712-c4cae80b-c53e-4c48-b86d-65a30b4f3236.png">

**Comment by biodranik** [comment]
Could our repo's roboto file be corrupted? Try to replace it with a newer one.

**Comment by vng** [comment]
Update https://github.com/organicmaps/organicmaps/commit/ee5a9269d2714a20dd224c7a3d012eb7e8bfd886
2.137 is the latest version I found. Here is the same https://fonts.google.com/specimen/Roboto

**Comment by pastk** [comment]
I have reproduced it on 5.0 emulator too
![font_letter_sizing](https://user-images.githubusercontent.com/18434508/160816560-dc2777cf-7d1d-4d49-81ad-7ca50f452fc5.png)

**Comment by vng** [comment]
I will debug glyph's heights later.

**Comment by vachan-maker** [comment]
Thanks for fixing the issue
