### ISSUE TITLE
This button has a different color in dark mode

### ISSUE THREAD

**Issue by vachan-maker** [organicmaps/organicmaps#2340]
In light mode, the button is fine.
But in dark mode, the button looks dim and washed out.

![image](https://user-images.githubusercontent.com/65799568/161433230-b6daf478-4644-4908-8bf6-1df4968f75bd.png)

Using Organic Maps on Android 10

**Comment by endim8** [comment]
can reproduce 👍

**Comment by biodranik** [comment]
@arnaudvergnet

**Comment by arnaudvergnet** [comment]
@biodranik can you please assign this to me so that I don't forget to fix it?
