### ISSUE TITLE
1-way roads are not visualised properly in some situations

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#2351]
IMHO 1-way roads should be visualised much more intense. Compare OM vs GM at
https://www.openstreetmap.org/query?lat=35.15716&lon=33.35381#map=18/35.15716/33.35381
![image](https://user-images.githubusercontent.com/85622715/161941521-397d3775-9049-4455-9128-78f3c9b7a64b.png)
![image](https://user-images.githubusercontent.com/85622715/161941666-63f2cfa4-e183-4b5f-be66-c78aca3157ad.png)

**Comment by AntonM030481** [comment]
Most of the time you need to zoom so much to see arrows. And sometimes these arrows are not properly located:
![image](https://user-images.githubusercontent.com/85622715/161942930-b76a9e25-ef23-4632-91f7-10cc4462ca30.png)

**Comment by biodranik** [comment]
@pastk can you please check if it's easy to 1) display arrows more often and 2) increase their drawing priority (if necessary)?

**Comment by pastk** [comment]
Probably related to #1241

**Comment by arnaudvergnet** [comment]
+1 on this. When trying to avoid a road block (so you stop following the navigation) it is very difficult to find one way roads.
