### ISSUE TITLE
Add Navigation Mode

### ISSUE THREAD

**Issue by MisterY** [organicmaps/organicmaps#2359]
Related to #1577 but more specifically #2358.

There should be a separate mode for when in the actual Navigation mode, where the app serves as a HUD. This focuses on the next couple of steps (turn navigation), real-time information such as the speed limits, pedestrian crossings, traffic ligths, speed cameras, etc.

Not sure if the Navigation mode should be specific to the View (i.e. pedestrian, driving, public transport).

**Comment by pastk** [comment]
We have a navigation mode already, is this a different idea somehow?

**Comment by MisterY** [comment]
> OM has a navigation mode already, is this a different idea somehow?

No, I'm sorry if I missed it. You are right, of course. It turns out I'm not using the app for navigation since it does not display the speed limit, which I find extremely important in the city.

Thanks!
