### ISSUE TITLE
Add option to search for specific amenities and keep it permanently displayed on the map

### ISSUE THREAD

**Issue by roboes** [organicmaps/organicmaps#2362]
I would like to request the following feature: option to search for all OSM amenities (https://wiki.openstreetmap.org/wiki/Key:amenity) and keep it permanently displayed on the map.

For example, for drinking water: ```Tag:amenity=drinking_water``` (https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddrinking_water). Currently it is possible to find these tags by opening ```Search > Categories > Water``` (which displays "Drinking Water", "Spring" and "Water Well").

First, it would be a great add-on to be able to search for specific amenities (by typing ```amenity=``` in the search function).

Second, for the Drinking Water example, it would be better to give the option to select specifically "Drinking Water" (i.e. inside ```Search > Categories > Water```, we would see "All" (which would correspond to the current display setup when "Water" is pressed), "Drinking Water", "Spring", "Water Well", etc.).

Last, it would be great to have the option to always show some specific amenities. In the example above, Drinking Water would always be displayed on the map no matter if I search for something else or plan a route.

**Comment by biodranik** [comment]
You can now type any amenity (from supported by OM, see [this file](https://github.com/organicmaps/organicmaps/blob/master/data/categories.txt)) in the search directly, and see it on the map. Why do you need it in a more complex way?

**Comment by roboes** [comment]
Thanks for sharing the [categories file](https://github.com/organicmaps/organicmaps/blob/master/data/categories.txt).

I have found the following code snippet:

```
# A generic "Water" search shall result in all water sources with a likely drinkable water:
#   amenity=drinking_water
#   amenity=water_point
#   man_made=water_tap
#   man_made=water_well
#   natural=spring
#
# Bigger bodies of water like rivers, lakes, ponds etc. should not be included in "Water" search
# as they are quite big and obvious terrain features on the map anyway.
#
# A search for "Drinking/Potable water" shall result in amenity=drinking_water only.
```

For me is now clear what is displayed when "Water" is pressed inside "Categories". The way to search and find Drinking Water by typing "Drinking/Potable water" is better than the one suggested by me. Thus, my first suggestion in the OP can be disregarded.

**Comment by biodranik** [comment]
Regarding the second, our main goal is to teach users that they can type anything in the search and find it. Extending categories does not solve this problem and takes a lot of our development time. As you already understood, all "categories" UI leads to a simple pasting of the search keyword into the search field. Users can and should do it directly. And we should focus on how to teach users that it is possible.

Regarding the last, can you please elaborate? What problem are you trying to solve?

**Comment by roboes** [comment]
The idea is to give the option to overlay chosen amenities on the map.

Here is an example from OsmAnd for Drinking Water: no matter what I search, Drinking Water POI is always shown:

<img src="https://user-images.githubusercontent.com/44812635/162328469-8276cf5f-41e2-4f05-893e-3f373c8e2c31.jpg" height="400"> <img src="https://user-images.githubusercontent.com/44812635/162328466-1be9046e-529c-4b8c-b01d-439efe0ace38.jpg" height="400">

**Comment by biodranik** [comment]
So it is not related to the search, but to the map rendering.
What is the use-case, when you manually go and select something to be always visible, instead of searching it and seeing search results on the map? Why do you think it is important for other users?

If we blindly start copying OSMand features, Organic Maps can become as complex as OSMand, and it is not our goal.

**Comment by roboes** [comment]
Some use cases to always overlay user defined POI:
- While travelling: keep Sights displayed on the map while walking around, on a turn-by-turn navigation or following a .kml route.
- While walking on a park or cycling: keep Water displayed on a map for Drinking Water POI (currently need to stop navigation to search for this POI).

**Comment by biodranik** [comment]
1. The first case is already implemented in a more convenient way: a user can search for anything while in walking/cycling/car navigation mode. And search results will be highlighted on the map while navigating. Did you discover this option?

2. The second case is also solved: you don't need to stop navigation to search for water. Press a search icon in the nav mode and search for the water. And see it displayed on the map.

**Comment by roboes** [comment]
This is great, I was unaware of this feature! Given that this existing feature works similarly with my request, I will close this issue. Thanks!
