### ISSUE TITLE
Ability to create new address POI from editor

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#2371]
It'd be good to have an editor type called 'address', for when a building has multiple addresses eg. https://www.openstreetmap.org/#map=19/51.47540/0.02215 , or for surveying when buildings haven't been added to the map.

**Comment by endim8** [comment]
Turns out it was pretty simple
 https://github.com/endim8/organicmaps/tree/add-address-editor

![Screenshot_20220410-024823_Organic Maps (Debug).jpg](https://user-images.githubusercontent.com/26939824/162598771-6c719b07-2c43-4900-8d47-e4eafc6cde1c.jpg)![Screenshot_20220410-024856_Organic Maps (Debug).jpg](https://user-images.githubusercontent.com/26939824/162598774-543313d6-9e45-4737-aff1-f4d8b9c4bdba.jpg)

I can open a PR if it's wanted :)

(Translations will need to be filled in though)

**Comment by endim8** [comment]
It would also be nice to be able to add `addr:housename`, I tried enabling it, but I think the map needs to be regenerated or something.

**Comment by endim8** [comment]
Also of note, it renames all address nodes to 'Address', previously they were called 'Building' (actual buildings aren't changed)

![Screenshot_20220410-034503_Organic Maps (Debug).jpg](https://user-images.githubusercontent.com/26939824/162599011-1569cc73-455c-419e-a22b-94895aa44809.jpg)

**Comment by biodranik** [comment]
Can you please clarify why it would be good to enable this feature? What problem are you trying to solve? And why do you think that this feature is needed for all users?

**Comment by endim8** [comment]
> Can you please clarify why it would be good to enable this feature? What problem are you trying to solve? And why do you think that this feature is needed for all users?

Being able to add address nodes is admittedly more useful for OSM contributors than the average user, but it'd be a very convenient way to add new addresses to the map, and could prompt people to contribute to OSM more directly.

I think renaming 'building' to 'address' should be merged for sure though, as it more accurately describes the selected element. There could be an address node that isn't a building, for example.

**Comment by biodranik** [comment]
What is the main case of adding addresses without a building/POI? Isn't it discouraged by the OSM community?

If there is a building without an address, then the user can edit it and add it (already implemented in OM).
If there is a POI, then its address can be edited (even without a building, already implemented in OM).

Isn't it better to draw a house or add a POI with an address instead of adding just an address on the empty map?

**Comment by pastk** [comment]
I guess the case is for buildings with multiple addressess (separate address nodes are placed inside of a building or on its outline). But I think its too niche case to enable a type in the editor which is likely to be misused (nodes put elsewhere..)

Also there are other possibilities to map multi address buildings (and there is no consensus): https://wiki.openstreetmap.org/wiki/Addresses#Buildings_with_multiple_house_numbers

**Comment by endim8** [comment]
Ah strange, I thought I'd replied to this.

Address nodes are used almost exclusively in some places, eg. the Netherlands, Denmark & Norway, but the case of a building with multiple addresses is also a good one 👍

(see https://wiki.openstreetmap.org/wiki/Addresses#Country_specific_rules_and_sources for address tagging practices)
