### ISSUE TITLE
Voice instructions guide links to Maps.Me

### ISSUE THREAD

**Issue by Mortein** [organicmaps/organicmaps#2383]
The "For more information, please check this guide." button on the Android Voice instructions settings page links to https://mapsme.zendesk.com/hc/en-us/articles/208628985-How-can-I-check-TTS-settings-on-my-Android-device-

A bit confusing for users who don't know about the history.

**Comment by biodranik** [comment]
@pastk @rtsisyk can we simply insert a clickable link to open a proper TTS settings dialog from OM settings screen? The code should be very simple:

```Java
    Intent intent = new Intent();
    intent.setAction("com.android.settings.TTS_SETTINGS");
    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
    startActivity(intent);
```

**Comment by trafotin** [comment]
The ZenDesk link is now dead, so maybe the documentation should be expanded with the old information? https://mapsme.zendesk.com/hc/en-us/articles/208628985-How-can-I-check-TTS-settings-on-my-Android-device-
