### ISSUE TITLE
Add an option to build a route along the imported KML track

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#2384]
Many people (especially cyclists) want to follow their custom routes imported from some other sources. It would be great to build a route using the imported track as a reference if the final point lies on the track. When the track recording will be implemented, this feature become even more useful.

Of course, if there is no map data under the track, the route should detour.

**Comment by anibyl** [comment]
My partner drives, she uses OsmAnd with imported KML routes. Would be cool if Organic Maps could do the same.

**Comment by biodranik** [comment]
What is the UI? How to activate it?

How OSMand handles edge cases?
1. If you are currently not on the route?
2. If there is no OSM data under the track? Eg no road?

**Comment by anibyl** [comment]
Click on a KML file, choose to open it in OsmAnd, OsmAnd opens in navigation mode with info about the route (distance/elevation/distance to start point) and the “Start” button, similar to when you choose “Route From” and “Route To” points in Organic Maps.

1. OsmAnd continued navigation from the place where we entered the route (maybe 50m from the starting point). Maybe it suggests a way to go to a starting point
2. I don't know, it didn't happen to us.

**Comment by biodranik** [comment]
1. Does the opened track stays saved/imported in OSMand after that?
2. What does OSMand display if the imported file contains several tracks, or track and some separate nodes?

We need to think about all corner cases before implementing it.

**Comment by biodranik** [comment]
See also #2434

**Comment by cyber-toad** [comment]
Looks like a duplicate for https://github.com/organicmaps/organicmaps/issues/1360

**Comment by RedAuburn** [comment]
closing as duplicate (https://github.com/organicmaps/organicmaps/issues/1360)
