### ISSUE TITLE
Area with landuse=forest + leisure=nature_reserve are rendered using a single nature reserve style only

### ISSUE THREAD

**Issue by FinixFighter** [organicmaps/organicmaps#2388]
As discussed on Telegram group, OrganicMaps should render a nature reserve in case the tag landuse=* is present. 
For example, this nature reserve is rendered with parallel grey lines
![photo_2022-04-11_15-27-36](https://user-images.githubusercontent.com/19877271/162962077-e9269631-677a-476c-8636-418021f2a56b.jpg)

but the tag landuse=forest is present on OpenStreetMap (see below):
![OSM](https://user-images.githubusercontent.com/19877271/162962226-cbcbbf6b-5183-4a4f-a91c-2884d200714d.png)

In this case it would be more correct if OrganicMaps rendered it as forest, instead of grey parallel lines, since the landuse is specified.
(OSM location of my example: https://www.openstreetmap.org/#map=18/42.49380/14.18431)

**Comment by pastk** [comment]
Probably it has something to do with `landuse=forest` being tagged on [a relation](https://www.openstreetmap.org/relation/453356). Maybe our generator code pulls only `leisure=nature_reserve` tag from the relation.

E.g. [this nature reserve](https://www.openstreetmap.org/relation/4759683) is rendered properly as a green forest with nature reserve hash pattern on top of it. Maybe because the "forest" tags are specified separately of "nature_reserve" ones..

**Comment by vng** [comment]
Well, if we have 2 area styles for one feature, the only one is selected (by bigger priority?).
If we have 2 separate features, they are rendered independently.

**Comment by pastk** [comment]
> Well, if we have 2 area styles for one feature, the only one is selected (by bigger priority?). If we have 2 separate features, they are rendered independently.

Any idea how to fix it?

Either split the feature in the generator into two features (feels wrong)
or somehow make an exception to the "one feature - one style" rendering logic (might need a lot of refactoring)
?

**Comment by pastk** [comment]
However in [this](https://www.openstreetmap.org/way/107292866) example a line feature containing both `highway=path` and `piste:type=nordic` is rendered using both styles (path over piste):
![Screenshot_1643638602](https://user-images.githubusercontent.com/18434508/151809518-f1190297-a25c-4e31-8974-7cf5b9b48058.png)

**Comment by vng** [comment]
Well, good solution is to allow combining area filling rule + area **hatching** rule.
Hatching now is hardcoded, hatching rules should be well-implemented. See https://github.com/organicmaps/organicmaps/issues/1415
