### ISSUE TITLE
Usability improvements in opening hours

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#2396]
Here are some ideas for improving the usability of the opening hours info:

* Show currently “Open”/“Closed” status in the info sheet of a POI.

![](https://user-images.githubusercontent.com/47610359/163385388-89893e43-344d-4d94-b794-b7eb962230ed.jpg)
![](https://user-images.githubusercontent.com/47610359/163385442-fe592ebf-351d-4364-9b27-cbbd6fed5fa0.jpg)

* Show “Opening in X hours” in the info sheet of a POI when the place is currently closed. This can be specially useful for nightclubs that open after midnight. Right now you have to stop and think: Is it opening tonight or not?

![](https://user-images.githubusercontent.com/47610359/163385547-5429f601-8fa9-4bdf-9a22-46dca772626f.jpg)

* Show “Open” in the search result list. Currently we only show if the POI is “Closed”.

![](https://user-images.githubusercontent.com/47610359/163385600-095d0405-206f-4fb0-a3ba-38d5ded39c29.jpg)

**Comment by Kazing** [comment]
For displaying "Open/Closed" status in the page place, it's related to #1852

For displaying "Open" status (or unknown) in search overview there is #1996

**Comment by AntonM030481** [comment]
It will be better to show periods when POI is open,
rather then current implementation when breaks are shown. Especially important for 2+ breaks.
![image](https://user-images.githubusercontent.com/85622715/175814171-6fa98ddd-c51b-4a12-b360-7b2a6b905dca.jpeg)

**Comment by BelKed** [comment]
This issue has been resolved in https://github.com/organicmaps/organicmaps/pull/3045.
Is there anything preventing it from being closed?

**Comment by AntonM030481** [comment]
I still believe that 2+ non-business hours are very bad readable in current format:
![image](https://github.com/organicmaps/organicmaps/assets/85622715/d04091e2-7c2d-4cb2-987f-5748f4f45e46)

If will be great to click for switching to "open accent mode" instead of "closed accent mode".

**Comment by BelKed** [comment]
@AntonM030481, I would suggest you to open a new issue, since this is about showing open/closed status :)
