### ISSUE TITLE
[Navigation] TurnSlightLeft or TurnLeft directions for rightmost turn

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#2417]
It was mentioned in #2262 
Here we have TurnSlightLeft direction.
Why? Because way is 10.2 degrees left from current direction vector.
Current angle limit for GoStraight is standard 10 degrees from left side in this situation.
Such situation (way goes though rightmost turn) is handled specifically now, so angle limit can be easily customised.
We can extend this limit to e.g. 20 degrees for such situation, so we will have GoStraight in pictured case.
<img width="811" alt="image" src="https://user-images.githubusercontent.com/85622715/163335771-b92607f3-a81f-48fb-bdde-1c53fcb1aa93.png">
The question is what to do in rare cases when both possible turns go significantly left from current direction vector.
E.g. selected (rightmost) turn is 30 degrees left and another turn is 40 degrees left.
For sure it's incorrect to give directions TurnLeft or TurnSlighLeft if we need rightmost turn.
Should we continue give GoStraight direction after proposed 20 degrees limit? The reason is that our selected rightmost turn is the most straight turn in such situation.

**Comment by AntonM030481** [comment]
@vng @biodranik 
I can easily fix it in proposed way (anyway it will be better then current behaviour).

**Comment by biodranik** [comment]
Let's do it go straight. It would be better than now. And then we'll debug and find some rare cases and think about a better solution.

**Comment by AntonM030481** [comment]
During modification some bugs were found.
Currently in the process of fixing and refactoring.

**Comment by biodranik** [comment]
For a proper UX, we need to distinguish between displayed arrows and announced directions. So visually it should be left + slight left, but the announcement should say "keep right". What do you think?

**Comment by AntonM030481** [comment]
- If route direction is rightmost and visually goes (slight) left, it will be converted to SoStraight.
- Next it will be converted to SlightRight if another possible turn is slight left too.

So, for rightmost route:

A. left+slight_left will be announced as go_straight.
B. slight_left+slight_left will be announced as slight_right.

It should be considered also, that when the roads are curved, it's very arguable if it is visually slight_left or go_straight, go_straight or slight_right.

**Comment by AntonM030481** [comment]
Currently rule for correction of go_straight to slight_turns is applied rather often.
But the rule of Leftmost/Rightmost angle when direction is changed to opposite is applied 2 times in our tests.

1. Germany_ShuttleTrain_TurnTest
<img width="741" alt="Germany_ShuttleTrain_TurnTest" src="https://user-images.githubusercontent.com/85622715/167144513-154d9959-8dcc-47b5-a4b1-24d01a8fbd80.png">

2. Russia_Moscow_LeningradskiyPrptToTTK_TurnTest:
<img width="1131" alt="Russia_Moscow_LeningradskiyPrptToTTK_TurnTest" src="https://user-images.githubusercontent.com/85622715/167144546-45707852-b2ec-44a3-8a7a-c85fb3eec19f.png" width='300' height = 'auto'>

In the test from the top https://github.com/organicmaps/organicmaps/issues/2417#issue-1206792896 such turn is discarded.
