### ISSUE TITLE
Share OSM node/way/relation link instead of 'OSM Go' links

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#2421]
Being able to share the OSM object ID link would be nice, eg. https://www.openstreetmap.org/node/8420901036

I'd prefer this to the current option of 'OSM go' links eg.  https://osm.org/go/0EEFbHJP-?m=

**Comment by biodranik** [comment]
We do not store OSM IDs. It can be queried dynamically though, but think about the edge cases (it was deleted?)

**Comment by endim8** [comment]
> but think about the edge cases (it was deleted?)

hmm this is a good point.

Deleted objects aren't actually 'deleted', just marked as deleted and not returned in database queries (unless querying for them eg. https://www.openstreetmap.org/node/8420901035), so it'd still work, and then the user can check the map to see what's there now. It's not ideal, but i still feel it'd be worth it.

**Comment by biodranik** [comment]
As we don't store ids, the only possible way is to query the api and return the closest object in rhat coordinates. It could be anything else if the original object was deleted from OSM (but was still present in OM maps).

**Comment by endim8** [comment]
> As we don't store ids, the only possible way is to query the api and return the closest object in rhat coordinates. It could be anything else if the original object was deleted from OSM (but was still present in OM maps).

Ah right i see what you mean now, fair enough 👍

i'll close this for now.
