### ISSUE TITLE
Turn names on the route are not visible in Desktop version anymore.

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#2422]
Arrows for turns are still visible but no text anymore.
<img width="489" alt="image" src="https://user-images.githubusercontent.com/85622715/164009231-09153e1e-184b-4d80-b754-683f4c10396e.png">

**Comment by biodranik** [comment]
We did not change that, definitely :)

**Comment by AntonM030481** [comment]
Me too!

**Comment by AntonM030481** [comment]
Information about turn is filled correctly.

**Comment by AntonM030481** [comment]
@biodranik the problem is solved.
In "Routing setting" menu "Show turns" was unchecked.
For some reason changes for "Choose router" are changed anyway,
but not "Show turns". The latter is changed only if "Save for next sessions" is checked.

Steps to reproduce:
1. Open "Routing setting"
2. Uncheck "Save for next sessions"
3. Change "Show turns"
4. Press OK
5. Open "Routing setting" again
6. Take a note that "Show turns" was not changed

**Comment by biodranik** [comment]
Am I right that the "Show Turns" setting is completely ignored (like it's off), if "Save for next sessions" is not checked?

@vng can you please fix it?

**Comment by AntonM030481** [comment]
Just to clarify:
You can't change setting for "Show turns" if "Save for next sessions" is not checked.
