### ISSUE TITLE
Provide pre-built binaries

### ISSUE THREAD

**Issue by nighto** [organicmaps/organicmaps#244]
As a suggestion, you could every now and then have some binaries (.apk for Android, .ipa for iOS etc.) so users would be able to test on their devices easily without compiling.

Specifically for iOS devices an .ipa can be easily installed on devices by non-dev users with [AltStore](https://altstore.io), and furthermore be added to an AltStore repo so it can be kept up-to-date independently of Apple's walled garden.

**Comment by rtsisyk** [comment]
https://github.com/organicmaps/organicmaps/issues/383

**Comment by unbeatable-101** [comment]
What does #383 have to do with this?
