### ISSUE TITLE
[android] Make "Save maps to" menu item always visible

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#2441]
At the moment the "Save maps to" menu item is visible for users that have an SD card only (and if there is enough space).

This leads to a number of inconveniences and confusing behavior:
- users without SD card can't check total size used by maps and amount of free space available
- if there is too little free space on the SD card then menu item is not visible (e.g. after downloading another map) - very confusing

Settings inside should be made more user-friendly:
- round sizes to Mb (at the moment its e.g. 10.2 MB, such precision doesn't make sense with OM map sizes)
- add understandable labels like "Internal storage" and "SD card", display actual filesystem paths in a smaller less contrast font below the labels

**Comment by biodranik** [comment]
Already done.
