### ISSUE TITLE
Allow to select external storage for maps mapped in /storage/emulated/

### ISSUE THREAD

**Issue by hamer13** [organicmaps/organicmaps#2451]
Android allows to use external SD-card as a «memory expansion». It means that the internal flash used only for installed applications and their internal data (in /data/data/ folder) and external SD-card used as an user storage and mapped into /storage/emulated/.
In this case omaps does not allow to use this /storage/emulated/ as a location for stored maps.

Typical mounts with SD-card as an **external storage**:
```
/dev/block/sda66 on /data type ext4
/data/media on /storage/emulated type sdcardfs

/dev/block/vold/public:179,1 on /mnt/media_rw/E90A-4A26 type texfat
/mnt/media_rw/E90A-4A26 on /storage/E90A-4A26 type sdcardfs
```
As we see the internal flash is mounted into /storage/emulated  and external SD-card into /storage/E90A-4A26. In this case we have a 3 locations for our files:
```
/data/data/app…
/storage/emulated
/storage/E90A-4A26
```

But in case of «**memory expansion**» android mounts this SD-card as an internal storage:
```
/dev/block/dm-0 on /data type ext4

/dev/block/dm-1 on /mnt/expand/95f428b7-4235-4226-9827-2b8474443531 type ext4
/mnt/expand/95f428b7-4235-4226-9827-2b8474443531/media on /storage/emulated type sdcardfs
```
The internal flash used only for /data/ and external SD-card is mounted into /storage/emulated. In this case we have only 2 locations for our files:
```
/data/data/app…
/storage/emulated
```

In 1st case the /data/ and /storage/emulated/ are really located on one physical device.
In 2nd case the are two different physical devices.

**Comment by pastk** [comment]
So a basic use case is a user with a device limited on internal storage, the user uses an SD card to expand available memory to it, and use the SD card to store maps too.

However atm OM shows only internal in storage options hence there is no way to store maps on SD.
I understand its possible to install OM into "extended storage" initially and it should store maps (and other files) onto SD. But this way is not obvious and tricky for the most users.

Hence a solution is to show emulated storage device in "Save maps to" menu.
However if a user uses SD card as an ordinary removable storage, then Android returns an emulated option nevertheless and two options with the same free / total size will confuse the user. An idea is to hide the emulated option if its size / free space is equal to internal storage (there might be a caveat that free space checks will return slightly different values if there is an ongoing writing process).

**Comment by hamer13** [comment]
I think the good way to show all available storages. User can want to use the /storage/emulated/ even if it is the internal flash for backup purposes (ex. Titanium Backup) — to backup only application (in /data/app/) with configuration (in /data/data/) but without maps (in /storage/emulated/0/Android/Data/).

**Comment by vlotarev** [comment]
I would support this issue.  The user without root access even does not see /data/data folder ... I personally want to move maps to user controlled /storage/emulated/0/Android/Data. Just for the sake of consistency :-)

**Comment by pastk** [comment]
Actually "emulated" storage is a primary storage in most (if not all) androids nowadays. This is what users are able to browse and this is what is accessible from PC via USB connection.
Its backed by internal device memory (sometimes with an exception of adopted SD cards)
([ref-1](https://source.android.com/devices/storage/config-example) and [ref-2](https://android.stackexchange.com/a/205494)).

So its quite strange OM was avoiding it for maps storage.
(but this is where OM puts its log files at the moment).

I think it should be changed to prefer "emulated" as the primary/default storage.
If its the same as "internal" device then "internal" should not be shown to the user at all, as it doesn't have any benefits but is confusing to the user as `/data/data/...` is not visible in file managers even.
With "emulated" (Android usually names it "Internal shared storage") users on Androids before 11 will be able to access map files. On Android 11+ it won't be accessible (but `/Android/data/` visible via FMs still? - need to check), so less difference with "internal".

CC @biodranik

**Comment by biodranik** [comment]
You're right, I already thought about your proposed solution and approve it (but please avoid breaking existing users). @rtsisyk what were the reasons for using /data/data instead of the emulated storage?
