### ISSUE TITLE
Routing issues caused by bollard

### ISSUE THREAD

**Issue by HalloMike** [organicmaps/organicmaps#2463]
Hi,

it seems there is a routing issue caused by barrier=bollard.

Example:
Route from
A-Address: Am Webereck 9, 86157 Augsburg, Germany
 to
B-Address: Gollwitzerstraße 12a, 86157 Augsburg, Germany 

Between A and B there is a barrier=bollard which allowing passage of pedestrians and bicycles:
https://www.openstreetmap.org/node/21597415

Attached an screenshot of an walking route where you can see that the route is much longer as the direct route via the bollard.
I think the bollard is blocking the direct route.

![IMG_0228](https://user-images.githubusercontent.com/104468664/165403903-cb77d1db-e58c-43f6-92fd-0cd9eaeb49ee.PNG)

I'm using an iPhone and the App is updated on the latest version.

Please let me know if you need more details

Thanks and regards
Mike

**Comment by vng** [comment]
Thanks for the report! Bollards with foot=yes should not prevent pedestrian routing.
I suspect that this restriction relation https://www.openstreetmap.org/relation/4554932 breaks pedestrian route what is weird :) Because the route B -> A is ok. Will investigate it.

**Comment by HalloMike** [comment]
> I suspect that this restriction relation https://www.openstreetmap.org/relation/4554932 breaks pedestrian route what is weird :) Because the route B -> A is ok. Will investigate it.

Many thanks! I haven't realised the restriction relation, big sorry.
