### ISSUE TITLE
Address link from calendar entry does not open that location

### ISSUE THREAD

**Issue by dreng** [organicmaps/organicmaps#2468]
As mentioned in #2311 Organic Maps does not jump to the address tapped from a calendar entry. Instead it jumps to my current location everytime. I tried a few addresses and none of them showed up. If you copy the addresses and search for them manually in Organic Maps, every address is found correctly. It seems that the address is simply ignored.

See logcat attached. One can see that an Intent has been opened with the submitted address. This log file was created with an active instance of Organic Maps. However it doesn't matter whether the instance already exists or is newly created.

[logs.zip](https://github.com/organicmaps/organicmaps/files/8573208/logs.zip)

**Comment by endim8** [comment]
The important bit:
`Incoming intent uri: Intent { act=android.intent.action.VIEW dat=geo:0,0?q=Mörkenstraße+47 flg=0x3000000 cmp=app.organicmaps/com.mapswithme.maps.SplashActivity (has extras) }`

According to https://en.wikipedia.org/wiki/Geo_URI_scheme#Unofficial_extensions, this uri should return the nearest search result for 'Mörkenstraße 47' I think a better option however would be to open and automatically search the query, as the first search result may be incorrect/misleading.

**Comment by biodranik** [comment]
Thanks! That should be easy to implement because we already have an API to open the search.

**Comment by ritikBhandari** [comment]
Hi,
Can I work on this issue?

**Comment by biodranik** [comment]
Of course!

**Comment by gzqx** [comment]
Any news on this feature?
