### ISSUE TITLE
Search is not consistent

### ISSUE THREAD

**Issue by AlertSubject** [organicmaps/organicmaps#2470]
There is a POI called "Heide-Park Resort" with the alt_name "Heidepark Soltau". It is located in Soltau, Germany.
https://www.openstreetmap.org/way/28865933#map=16/53.0250/9.8822
My viewpoint / location was located a bit north of Hamburg, Germany.
https://www.openstreetmap.org/#map=13/53.6951/9.9212 (this area)
I have the following areas downloaded:
- Hamburg
- Schleswig Holstein (2/2)
- Mecklenburg-Vorpommern
- Lower Saxony (Lüneburg)

My device: OnePlus 9 Pro
Android 12

When I search for "Heide-Park" I get the following results:
- A park in Hamburg called "Heine-Park" (Fair enough)
- A villa nearby
- A building called "Ulf C. Hermanns - von der Heide & Partner" 
- A park called "Astrid-Lindgren-Park"
But the POI I searched for is nowhere to be found

A search for "Heide Park" results in the exact same results

A search for "Heidepark" results in the following:
- A park called "Heidepark" (fair enough)
- Heide Park Resort (**Heidepark** Soltau) (The POI I wanted, but the app only found it because of the alt_name that is highlighted in the list)
- A building related to the park
- A bus stop called "Höckel, Heideparadies" (??)
- etc.

All Screenshots can be found at the end of this post

Adding the city name to the search terms has been inconsistent as well.
Adding "Soltau" didnt help, even thoug Soltau is in the address-tags of the POI
Adding "Friedrichseck" did help, even though its just a small city right next to the park.

Zooming out until half of Germany (inlcuding the park) is in the view did help. In this case all search terms lead to the wanted result within the first 3 results
(But I dont think its reasonable to expect a user to zoom out all the way, whenever searching for something that is 70 km away)

Screenshots:
![signal-2022-04-27-182228_001](https://user-images.githubusercontent.com/72819077/165567061-3f69c721-37cd-4475-9c9d-c292448b850a.jpeg)
![signal-2022-04-27-182228_002](https://user-images.githubusercontent.com/72819077/165567063-c857979c-f056-4363-b22a-119346633121.jpeg)
![signal-2022-04-27-182228_003](https://user-images.githubusercontent.com/72819077/165567065-da4983f6-3edc-447b-a3a9-4a8750d18028.jpeg)

**Comment by KazimirPodolski** [comment]
Suffering from this too. My particular case:
1. I added this POI from the app https://www.openstreetmap.org/node/9701406317
2. When I search for "bank of georgia" new POI is not in the list and not on the map, and it seems a lot of actually exsiting POIs with this name are missing too
3. Suddently when I search for "bank of georg" it IS in the list

**Comment by hellojaccc** [comment]
Also how is search item organized? I see franchises that are really far away from me instead of closest one

**Comment by biodranik** [comment]
The search is complex... and it needs improvements, obviously. Please describe to us how to reproduce your results, it would be easier for us to fix.

**Comment by duemoselund** [comment]
I don't know how much help another description of a similar issue helps, but I'm also experiencing some rather random results when I search.
I live in Denmark, Aarhus and if I search for fx. 'Netto' which is a rather common supermarket discount chain across all of Denmark. 
As you can see in the picture below the top result result is a random bus stop 43 km away whxuh fair enough does have Netto in the name, but still seems like an odd top result. 
Next is a building named Netto, which likely is the supermarket chain, though it's 9.5km away.
Third is some town in Germany that only partly has the same letters and is 597km away. I haven't even downloaded any parts of Germany! I know you can search for results outside of downloaded areas, though if it's not downloaded it's likely less of personal priority. 
Then finally as the fourth result I get the supermarket chain right around the corner. 

![Screenshot_20220626_135922_app organicmaps](https://user-images.githubusercontent.com/11139391/175813154-8ed207d0-ab48-439f-b8dd-1da3d4fa1a7e.jpg)

**Comment by vng** [comment]
![Screenshot_20220628-195959_Organic Maps](https://user-images.githubusercontent.com/175612/176434951-d4f17804-07c3-42b9-9bda-06bab0262327.jpg)

**Comment by biodranik** [comment]
1. Москва буденного 51 к1
2. Show all suggested results on the map
3. OK.

1. Москва буденного 51 к 1 
2. Show all suggested results on the map.
3. None of results is displayed.
