### ISSUE TITLE
maps_generator readme needs updating

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#2488]
https://github.com/organicmaps/organicmaps/blob/master/tools/python/maps_generator/README.md

is outdated, with lots of references to omim, and broken/incorrect instructions

**Comment by biodranik** [comment]
Please improve it :)

**Comment by endim8** [comment]
> Please improve it :)

will do :) this issue was more of a reminder for me to do it

**Comment by Jean-BaptisteC** [comment]
@endim8 can be closed ?
