### ISSUE TITLE
"Shortcut" routing doesn't respect fences

### ISSUE THREAD

**Issue by dbf256** [organicmaps/organicmaps#2492]
Not a big issue but routing suggests to go through the fences 

![image](https://user-images.githubusercontent.com/2550295/166156438-8b9a84c5-8007-43d0-b987-2ff1cd8eb79b.png)

**Comment by biodranik** [comment]
Where is it in OSM data? It's a bug.

**Comment by dbf256** [comment]
Location: https://www.openstreetmap.org/relation/7103024

**Comment by vng** [comment]
OSM is ok, strange that the app stopped near "6 c2", but should make a detour around and arrive at the footway near the position.

**Comment by vng** [comment]
Same error here https://www.openstreetmap.org/#map=16/62.8527/27.7612

Putting start/end point (pedestrian) everywhere on island doesn't take into account highway=track. The app always snaps on ferry point.

**Comment by AntonM030481** [comment]
Maybe this is related #2546.

**Comment by AntonM030481** [comment]
@vng still not perfect (but maybe too short distance between fence and final point):
from: 35.1358897, 33.3574245
to: 35.1355549, 33.3579138

**Comment by vng** [comment]
Last build with May 5 test data:
<img width="636" alt="Screenshot 2022-05-17 at 12 03 18" src="https://user-images.githubusercontent.com/175612/168773866-4e23701b-af1f-456b-b5a2-25307a43a4a4.png">

**Comment by AntonM030481** [comment]
last build with 15 April data:
![image](https://user-images.githubusercontent.com/85622715/168774662-a7a369f7-fc3e-40ca-a007-bcc7d430ae5c.png)
