### ISSUE TITLE
[Routing] Longer distance route calculates deviating inefficient route

### ISSUE THREAD

**Issue by octocat-mona** [organicmaps/organicmaps#2494]
Compared to OSRM OrganicMaps calculates a different, more inefficient route depending on the starting point used.

For example from 'Woerden' (NL) to 'Apenheul' (Apeldoorn, NL) [using OSM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=52.0870%2C4.8767%3B52.2153%2C5.9187#map=10/52.1428/5.3970):

![image](https://user-images.githubusercontent.com/538170/166302611-212205ee-6369-44ed-a330-f60cceda0f0f.png)

Calculates about the same route in OrganicMaps:

![image](https://user-images.githubusercontent.com/538170/166307625-6306f0de-9bc5-4324-b135-a2d8edc0a8eb.png)

But when I choose another starting point further away from 'Utrecht' (which both routes passes through), OrganicMaps calculates a deviating route.
'Gouda' (NL) to 'Apenheul' (Apeldoorn, NL) [using OSM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=52.0181%2C4.7111%3B52.2153%2C5.9187#map=10/52.1259/5.3009):

![image](https://user-images.githubusercontent.com/538170/166305024-600a089e-06c3-40b3-8287-bafbfbe4fe51.png)

Compared to route in OrganicMaps:

![image](https://user-images.githubusercontent.com/538170/166307692-72bee88c-81b6-46ff-bb1b-7e4ea886ba44.png)

This is an additional ~15km!
Is there a reason why OrganicMaps calculates the second route like this?

**OrganicMaps Android version:**
2022.04.27-2-Google

**Enabled routing options:**
- Toll roads
- Ferries

**Downloaded maps:**
NL (24/24 maps)

**OSM data:**
15 april 2022

**Comment by biodranik** [comment]
It's a bug in our cross-region routing algorithm. Thanks!
