### ISSUE TITLE
Generic icon of leisure=pitch is displayed for leisure=playground instead of existing specific one

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#2510]
Specific icon can be seen in search mode, but not in normal one.
It's for all playgrounds. Particular case: 35.17352, 33.36106
![image](https://user-images.githubusercontent.com/85622715/166479832-9de9f064-f994-4758-9a6a-eec02d72fe2c.jpeg)
![image](https://user-images.githubusercontent.com/85622715/166479866-dcadda0c-49e6-40af-8bee-7e1de9b54ea1.jpeg)

**Comment by vng** [comment]
Well, yes, current system is a bit complicated. Main POI icons are in svg, but bookmark, search, traffic, .. icons are in png.
Check ./data/styles/clear[vehicle]/style-clear[style-night]/hdpi[xhdpi ...]/*.png

**Comment by biodranik** [comment]
@vng it should also be refactored, maybe even now, as you're rewriting the Drape. We need to have all icons in SVG sources, then it will be very easy to "edit" them in memory and create all necessary bitmaps as necessary.

**Comment by vng** [comment]
The "problem" is not about code. Finally, all this stuff is generated into one png texture. How will repaint this icons from png to svg?

**Comment by biodranik** [comment]
We will replace the existing icons with SVG ones.

**Comment by pastk** [comment]
A detailed vision of a better icons workflow:
#2026

**Comment by pastk** [comment]
> I can't find the svg file to search-result-playground.png in the repo. Any idea where I can get it?

ATM playgrounds use `pitch-m.svg` for regular icons and `search-result-playground.png` for search results (there are versions for various resolutions in `hdpi/`/`xxhdpi/` etc. folders).

**Comment by pastk** [comment]
> > I can't find the svg file to search-result-playground.png in the repo. Any idea where I can get it?
> 
> ATM playgrounds use `pitch-m.svg` for regular icons and `search-result-playground.png` for search results (there are versions for various resolutions in `hdpi/`/`xxhdpi/` etc. folders).

It needs to be changed in `map/bookmark_helpers.cpp`

**Comment by TheAdventurer64** [comment]
Looks like this was fixed in #3084
