### ISSUE TITLE
Some leisure=pitch are just "Sports Ground" with no respect to sport tag

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#2511]
As a side effect one can't search for leisure=pitch with some specific sports.

At the same time icons for some of leisure=pitch are specific. E.g. for sport=tennis.

**Comment by AntonM030481** [comment]
Clarification.

For athletics, equestrian, golf everything is OK.
But for tennis and soccer is not OK.
Most likely because of conflict of tags:
leisure=pitch
and
sport-...
The priority is set according to key name order.

**Comment by AntonM030481** [comment]
![image](https://user-images.githubusercontent.com/85622715/177197290-f8535675-2753-4a29-aeac-fc8880ed5848.jpeg)
![image](https://user-images.githubusercontent.com/85622715/177197307-189d3fc3-476a-4506-bff9-1630716f2b28.jpeg)

**Comment by pastk** [comment]
I think this issue is similar to #1392 and a root problem is that  there are two different priority systems used for rendering and choosing a text. A proper solution is to use z-index from styles to choose the text too.

**Comment by AntonM030481** [comment]
It should be independent from zoom level. E.g. for search.
My suggestion is to use the same approach as restaurant's cousins.

**Comment by pastk** [comment]
> It should be independent from zoom level. E.g. for search. My suggestion is to use the same approach as restaurant's cousins.

Z-index is independent of zoom level.

How do cuisines work? You mean add a custom listing of all sports types into a subtitle field?

**Comment by vng** [comment]
IMHO, more specific type like sport=xxx is _always_ better than leisure=pitch.
UselessTypesChecker -> SortUselessToEnd can/should fix it.

**Comment by AntonM030481** [comment]
> How do cuisines work? You mean add a custom listing of all sports types into a subtitle field?

Displayed text for restaurant:
Title: <Name>
Subtitle: Restaurant * Cuisine1 * Cuisine2.

It is searchable by "Restaurant", "Cuisine1", "Cuisine2".

IMHO, perfect solution is to do the same for sport grounds:

Displayed for restaurant:
Title: "Sport Grounds" or <Name> if any.
Subtitle: Sport Grounds * Sport1 * Sport2.

It is searchable by "Sport Grounds", "Sport1", "Sport2".

The same approach for stadiums, sport centers, sport shops, sport clubs, etc.

Icons for Sport Grounds should match Sport1.

**Comment by pastk** [comment]
Sounds good!
And looks like several cuisines for one place are parsed from a semicolon-delimited list - its should be applied to sports too, e.g. parse `sport=gymnastics;badminton` into two OM types.

**Comment by AntonM030481** [comment]
> IMHO, more specific type like sport=xxx is _always_ better than leisure=pitch.
> UselessTypesChecker -> SortUselessToEnd can/should fix it.

I think that https://github.com/organicmaps/organicmaps/issues/2511#issuecomment-1174768530 will be better.
But it will take much longer time to implement. For this reason let's fix it easily now and make perfect after next refactoring.

**Comment by AntonM030481** [comment]
Search still does not work after fix (page info is OK).

**Comment by vng** [comment]
Confirm that search doesn't work, but this fix can't fix it, only PP. Will investigate search.

**Comment by endim8** [comment]
fixed by https://github.com/organicmaps/organicmaps/pull/2925
