### ISSUE TITLE
Building addresses with a slash are not processed properly

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#2516]
Search also doesn't work.

![image](https://user-images.githubusercontent.com/170263/166861719-460a14e5-50fe-4d9f-9b3e-344e2e372f83.png)

**Comment by dvdmrtnz** [comment]
Actually, housenumbers with slashes seem to work fine:

https://omaps.app/84HGPoUIRY/Kostol_Panny_Márie%2C_Pomocnice_kresťanov
om://84HGPoUIRY/Kostol_Panny_Márie%2C_Pomocnice_kresťanov

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/3a86e4e8-469b-4c34-8042-f83f386a00cd" width="320"/> <img src="https://github.com/organicmaps/organicmaps/assets/47610359/f0415aea-26e5-4c75-bd1c-c44a66f75df1" width="320"/>

**Comment by dvdmrtnz** [comment]
In that case seems to be because it is tagged with addr:subdistrict

https://www.openstreetmap.org/way/653151488#map=19/52.33506/25.18679

* See https://github.com/organicmaps/organicmaps/issues/3624
