### ISSUE TITLE
Bike navigation rankes streets too high

### ISSUE THREAD

**Issue by simonschaufi** [organicmaps/organicmaps#2522]
I use this app for bike navigation quite a lot but I often switch to walking navigation as the bike navigation is often not the most convenient way and ignores even official bike ways and instead sends me to big roads.

![Screenshot_20220505-113707_Organic Maps](https://user-images.githubusercontent.com/941794/166898857-c42df2e3-427f-4f84-8361-54d0e876c984.jpg)
Which should be the same like:
![Screenshot_20220505-113730_Organic Maps](https://user-images.githubusercontent.com/941794/166898894-002a4d42-6c87-4d37-9ab5-77d6e3b8990e.jpg)

This is the route in Maps.me:

![Screenshot_20220506-000437_MAPSME](https://user-images.githubusercontent.com/941794/167033056-3c40b2a8-16ca-44eb-93c3-d6391d9cc30f.jpg)

This is the route in Komoot:

![photo_2022-05-28_23-28-57](https://user-images.githubusercontent.com/941794/170843409-542af006-f44d-40ef-a275-0440813b88a5.jpg)

Also not optimal as it also uses only big streets instead of field ways.

**Comment by simonschaufi** [comment]
These are the routes:

- https://www.google.de/maps/dir/Pestalozzischule/Epplesee,+76287+Rheinstetten/@48.9609508,8.3451356,14.19z/data=!4m14!4m13!1m5!1m1!1s0x479705bb6b7624b9:0x9f67e9a8101a35d0!2m2!1d8.3862906!2d48.9513674!1m5!1m1!1s0x4797040b218ff77d:0x92ded19145cf769e!2m2!1d8.3235399!2d48.9655289!3e1
- https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=48.9734%2C8.4036%3B48.9647%2C8.3239#map=14/48.9685/8.3616
- https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=48.9734%2C8.4036%3B48.9647%2C8.3239#map=14/48.9608/8.3604

Does this help? The routes in the app are totally different from the ones from OSM.

**Comment by endim8** [comment]
Definite +1 for this, an option to only route (when possible) with dedicated bike lanes would be nice too

**Comment by vng** [comment]
@endim8 If the app skips dedicated/designated bike roads - it's an obvious bug. Please, attach the examples here, will investigate.

**Comment by vng** [comment]
@simonschaufi The desired route has [highway=track](https://www.openstreetmap.org/way/158406819)
Not sure, but is next set of tags ok for bicycle routing?
```
highway=track
motor_vehicle=forestry
name=Pirschweg
smoothness=intermediate
surface=fine_gravel
tracktype=grade2
```

The app assumes 8kmh speed for this road, at the same time has obviously bigger speed via "big roads".

Possible solution here is to introduce more bicycle profiles like fastest, nicest/quite.

**Comment by simonschaufi** [comment]
Many tracks which are used for walking can also be easily used by bikes except some really rough ways through fields but as a biker I rarely find ways which are only useful for walking. Exceptions are usually in the fields or ways in the forest but these ways I have in the screenshot could even be used by a car even though often not allowed. So the whole algorithm is not optimized for bikers.

**Comment by biodranik** [comment]
@simonschaufi it would be helpful if you can make a list of OSM tags that actually allow cycling, so we can tune our algorithms.

**Comment by simonschaufi** [comment]
@biodranik can you tell me how to do that as I'm just a user of the app and don't know much about internals of OSM?

**Comment by biodranik** [comment]
We're not bikers :) So if you help us to find answers to your _good_ questions, it may save us a lot of time and help us to focus on development.

**Comment by simonschaufi** [comment]
I'm a developer myself and could maybe also understand the algorithm if you point me to the right file where this happens. The main question is: is the tagging in OSM bad or is your algorithm not optimal? Which tag does the road need in order to be chosen as a possible way? Where is the "switch" between pedestrians and bikers?

**Comment by biodranik** [comment]
At first, it's important to check the OSM data quality. If everything is tagged properly, and it is obvious for you that there is a mistake in the algorithm, then it's a bug.
You can check routing_common/bicycle_model.cpp

**Comment by simonschaufi** [comment]
Here are some already:

- concrete:plates
- Gravel
- Compacted
- Asphalt
- Paved

PS: I found a special tag in OSM called "Bicycle Route DE:BW:KA". This can be used and should be rated high.

![Bildschirmfoto vom 2022-05-29 00-05-00](https://user-images.githubusercontent.com/941794/170844357-dd91066d-674a-4e9d-8218-2c7d18e9694f.png)

**Comment by simonschaufi** [comment]
ping. Any progess here?

**Comment by vng** [comment]
Simply increasing highway=track priority for bicycle is not a good fix, IMHO.
Upcoming release makes this route, that uses _designated_ bicycle paths and seems like its OK:
<img width="1229" alt="Screenshot 2022-07-24 at 11 44 22" src="https://user-images.githubusercontent.com/175612/180639541-6c35bb04-5a2f-4411-9a63-e0ff2c8d5bf3.png">

We are working on _alternative routes_ algorithm that will allow you to select best route for the user.

**Comment by vng** [comment]
I see a problem on this route:
<img width="998" alt="Screenshot 2022-07-24 at 11 47 08" src="https://user-images.githubusercontent.com/175612/180639617-cdf3ff27-9349-43da-8451-914d7eb4ae00.png">

The app left designated bicycle highway=path and uses secondary/residential instead. Will investigate it.

**Comment by vng** [comment]
One more example: (53.2876678, 8.11889789) -> (53.2122689, 8.20143976)

**Comment by pastk** [comment]
> One more claim of ignoring track roads for bicycles: https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=49.6461%2C8.6475%3B49.6624%2C8.6920#map=14/49.6540/8.6696
> 
> Let's try to increase track's weight, especially with tracktype=grade1/grade2. And it should be defined as unpaved_good (now have unpaved_bad).

Did you adjust it? Is it fixed now?

**Comment by simonschaufi** [comment]
It is indeed better with the release of 2024.10.08. I'm closing it now and will report further issues in a new issue. Thank you very much!
