### ISSUE TITLE
Support mouse scroll to zoom in iPad/Mac Organic Maps from the App Store

### ISSUE THREAD

**Issue by kropochev** [organicmaps/organicmaps#2524]
Please add mouse scroll for zoom map on desktop app.

**Comment by vng** [comment]
Hm, what is your desktop OS? MacOS works fine here (at list scroll gesture on touchpad).

**Comment by kropochev** [comment]
MacOS, scroll wheel on mouse not work

**Comment by biodranik** [comment]
@kropochev you are using Organic Maps from the Apple Store, right?

**Comment by kropochev** [comment]
yes, from AppStore. I also checked on the iPad, the mouse wheel does not enlarge the map.

**Comment by dalb8** [comment]
Doesn't work for me on Android.

**Comment by dvdmrtnz** [comment]
Apple Maps supports using the scroll wheel on macOS. Organic Maps for iPad running on macOS should support it too

**Comment by eisams** [comment]
> Somehow even with a trackpad it's not possible to zoom in/out on the map by scrolling (only possible to zoom in by double tap).

Yup, pinch to zoom doesn't work either
