### ISSUE TITLE
Symbols in phone numbers

### ISSUE THREAD

**Issue by tastrax** [organicmaps/organicmaps#2528]
HI Folks,

There are many Map Roulette challenges for correcting phone numbers in OSM, the accepted format is to add the + symbol, then country and area codes. 

https://maproulette.org/browse/challenges?query=Phone%20or%20fax%20number%20is%20not%20in%20international%20format%20%28ITU-T%20E.164

It appears organic maps does not allow the + character in the phone number fields therefore folks cant add the correct formats. 

https://www.openstreetmap.org/changeset/120404348

Would it be possible to enhance the phone number fields to allow this (maybe with a prompt for the correct format?)

**Comment by biodranik** [comment]
It is possible to type + symbol in Android and iOS versions. Can you please clarify and maybe send your screenshots?

**Comment by tastrax** [comment]
I will get back to the original user for clarification

**Comment by tastrax** [comment]
Sorted - user error!
