### ISSUE TITLE
Use US Censor (Tiger) address database for missing OpenStreetMap US addresses

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#2532]
In the ideal world, all houses will be in OSM and will have their addresses. But in reality, it's often needed to navigate to some address that is not (yet) in OSM.

https://nominatim.org/release-docs/3.5.2/data-sources/US-Tiger/

------------------------

<table>
  <tr>
    <td>
      <a href="https://nlnet.nl/"><img src="https://raw.githubusercontent.com/organicmaps/organicmaps/87f50b9fdb874ffc9b905d2738774d9b16d3c5a5/docs/sponsors/nlnet.svg" alt="The NLnet Foundation" width="200px"></a>
    </td>
    <td>
      This project has been funded through NGI0 Entrust Fund. <a href="https://nlnet.nl/entrust/">NGI0 Entrust Fund</a> is established by the <a href="https://nlnet.nl/">NLnet Foundation</a> with financial support from the European Commission's <a href="https://www.ngi.eu/">Next Generation Internet programme</a>, under the aegis of DG Communications Networks, Content and Technology under grant agreement No 101069594.
    </td>
  </tr>
</table>

**Comment by rtsisyk** [comment]
wget https://nominatim.org/data/tiger-nominatim-preprocessed-latest.csv.tar.gz:

```
06037.csv  13149.csv  17165.csv  20067.csv  22031.csv  27077.csv  29163.csv  34035.csv  37125.csv  40071.csv  46035.csv  48073.csv  51029.csv  54051.csv
```


```
15999;15901;all;Ness;Wilson;KS;66710;LINESTRING(-95.724080 37.601210,-95.724078 37.601259)
18300;18398;all;Queen Rd;Wilson;KS;66710;LINESTRING(-95.669668 37.636600,-95.669612 37.641864,-95.669586 37.642743)
800;898;even;Iowa St;Wilson;KS;66757;LINESTRING(-95.683754 37.419614,-95.684712 37.419620)
801;899;odd;Iowa St;Wilson;KS;66757;LINESTRING(-95.683756 37.419450,-95.684714 37.419456)
900;998;even;Indiana St;Wilson;KS;66757;LINESTRING(-95.685020 37.418620,-95.685989 37.418614)
901;999;odd;Indiana St;Wilson;KS;66757;LINESTRING(-95.685018 37.418456,-95.685987 37.418450)
100;148;even;10th St;Wilson;KS;66757;LINESTRING(-95.686053 37.417617,-95.686050 37.417898)
```

**Comment by rtsisyk** [comment]
A good test case from the documentation for testing the search in the U.S.:

`123 Main St, Seattle, WA 98101`

**Comment by ooosssay** [comment]
Possibly the [National Address Database](https://www.transportation.gov/gis/national-address-database)?
