### ISSUE TITLE
Login Methode Github

### ISSUE THREAD

**Issue by Tig3rch3n** [organicmaps/organicmaps#2533]
I use as 'Login through Github' for My OSM Account. But I think there is no Possibility atm to use my Account with Organic Maps right?

**Comment by biodranik** [comment]
There should be a way to edit an OSM password and use it in OM. Did you see your account settings? @Zverik can you please help?

**Comment by Tig3rch3n** [comment]
@biodranik
Oh I didn't know I can set a PW even if i use Git as Login.
Works Perfect for me thx

Issue Solved for me :)

**Comment by Tig3rch3n** [comment]
@biodranik
Oh I didn't know I can set a PW even if i use Git as Login.
Works Perfect for me thx

Issue Solved for me :)
