### ISSUE TITLE
[Navigation] Unnecessary directions going to the link if all alternatives are sharp

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#2536]
Here direction is provided because of going to the link from non-link at the presence of alternative which goes back and for sure will not confuse user.
34.818354, 33.361381
![image](https://user-images.githubusercontent.com/85622715/167451904-53c193f5-96bc-4e2b-ad73-59de58e668b7.jpeg)

**Comment by vng** [comment]
Latest data snapshot (220506) has next turn problems:

1. (Debug)
Running bicycle_route_test.cpp::SpainTenerifeAdejeVilaflor
Avoid next roads: RoutingOptions: {}
routing section for Spain_Canary Islands loaded in 0.317133 seconds
Routing in mode: Joints
Route build time: 1351 ms
TID(1) ASSERT FAILED
routing/turns_generator.cpp:1189
CHECK(turnCandidates.front().m_segment == firstOutgoingSeg) 
routing_integration_tests: /home/planet/omapsapp-private/routing/turns_generator.cpp:1189: void routing::turns::GetTurnDirection(const routing::turns::IRoutingResult&, size_t, const routing::NumMwmIds&, const routing::RoutingSettings&, routing::turns::TurnItem&): Assertion `false' failed.
Aborted (core dumped)

2. (Release) or if remove assert above.
bicycle_turn_test.cpp::RussiaMoscowSevTushinoParkBicycleWayTurnTest
pedestrian_route_test.cpp::BelarusMinskRenaissanceHotelUndergroundCross
turn_test.cpp::Russia_Moscow_BolshoyKislovskiyPerBolshayaNikitinskayaUl_TurnTest
turn_test.cpp::Netherlands_Barneveld_TurnTest

3. (Warnings) "nodes.candidates are not expected to have same m_angle."

**Comment by AntonM030481** [comment]
@vng Maybe move it to the separate issue?

**Comment by vng** [comment]
As you wish.

**Comment by AntonM030481** [comment]
@vng how to get data snapshot (220506)?
