### ISSUE TITLE
Turn problem for latest data snapshot (220506)

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#2538]
Latest data snapshot (220506) has next turn problems:

1. (Debug)
Running bicycle_route_test.cpp::SpainTenerifeAdejeVilaflor
Avoid next roads: RoutingOptions: {}
routing section for Spain_Canary Islands loaded in 0.317133 seconds
Routing in mode: Joints
Route build time: 1351 ms
TID(1) ASSERT FAILED
routing/turns_generator.cpp:1189
CHECK(turnCandidates.front().m_segment == firstOutgoingSeg)
routing_integration_tests: /home/planet/omapsapp-private/routing/turns_generator.cpp:1189: void routing::turns::GetTurnDirection(const routing::turns::IRoutingResult&, size_t, const routing::NumMwmIds&, const routing::RoutingSettings&, routing::turns::TurnItem&): Assertion `false' failed.
Aborted (core dumped)

2. (Release) or if remove assert above.
bicycle_turn_test.cpp::RussiaMoscowSevTushinoParkBicycleWayTurnTest
pedestrian_route_test.cpp::BelarusMinskRenaissanceHotelUndergroundCross
turn_test.cpp::Russia_Moscow_BolshoyKislovskiyPerBolshayaNikitinskayaUl_TurnTest
turn_test.cpp::Netherlands_Barneveld_TurnTest

3. (Warnings) "nodes.candidates are not expected to have same m_angle."

**Comment by AntonM030481** [comment]
@vng how to get data snapshot (220506)?

**Comment by vng** [comment]
- First, please check assert with current 220415 data.
- If not reproduced, download files manually from https://cdn.organicmaps.app/maps/220506 and put them into your current 220415 folder

**Comment by AntonM030481** [comment]
@vng  403 Forbidden, nginx

**Comment by AntonM030481** [comment]
Using new Belarus_Minsk Region.mwm:
```
Running pedestrian_route_test.cpp::BelarusMinskRenaissanceHotelUndergroundCross
Loaded countries list for version: 220415
Settings path: ./data/settings.ini
Avoid next roads: RoutingOptions: {}
TID(1) ASSERT FAILED
indexer/features_vector.cpp:16
CHECK(m_metaDeserializer) 
Assertion failed: (false), function FeaturesVector, file features_vector.cpp, line 16.
```

**Comment by vng** [comment]
Yes, try to reproduce and fix assert on 220415 data for Spain (28.11984, -16.72592) -> (28.15865, -16.63704)

**Comment by AntonM030481** [comment]
For 220415 it is fine.

**Comment by vng** [comment]
Ok, please, take this branch https://github.com/organicmaps/organicmaps/pull/2539 and check 220506

**Comment by AntonM030481** [comment]
I was able to reproduce issue in SpainTenerifeAdejeVilaflor.
In fact this is start of the route.
If shift start point just a bit - no problem (no turnCandidates).
But for this particular point - somehow turnCandidates appears - and check is failed.
![image](https://user-images.githubusercontent.com/85622715/167647112-d46fe8e2-b8c4-4187-937c-0da0c6839c40.png)

**Comment by AntonM030481** [comment]
BelarusMinskRenaissanceHotelUndergroundCross
Here I can see following picture. 1 TurnRight looks good here.
Looks like the test is irrelevant. Maybe route is different now from before.
My suggestion is to add distance check in all tests before any turns checks.
![image](https://user-images.githubusercontent.com/85622715/167661508-988f67a5-91b6-40d3-a0af-f3b29136a0b1.png)

**Comment by vng** [comment]
Ok, thanks!
