### ISSUE TITLE
Elizabeth line navigation enablement

### ISSUE THREAD

**Issue by jpds** [organicmaps/organicmaps#2543]
This should be opening in a couple of weeks time: https://www.bbc.com/news/uk-england-london-61095510

The relations in OSM which are pertinent seem to be:

- https://www.openstreetmap.org/relation/2956938
- https://www.openstreetmap.org/relation/9789693 # related members (should become operational on the 24th)
- https://www.openstreetmap.org/relation/9789694 # related members (some are already operational, but all operational on 24th too)

It however doesn't seem like the rest of the London rail network is enabled for navigating either.

**Comment by biodranik** [comment]
@alexey-zakharenkov can you please add it?

**Comment by jpds** [comment]
As of `2022.11.24-3`, the app now displays the Elizabeth line routes - will test out the navigation search results in the coming days.

**Comment by Jean-BaptisteC** [comment]
@jpds problem is fixed ?

**Comment by jpds** [comment]
This is fixed, but there is some weirdness in the routing, for example: if you look at Paddington Station in London - you'll see that it has two buildings, the larger concourse for the railways and the Underground lines, and the smaller building just south-west for the Elizabeth line.

- If someone asks Organic Maps to route from Stratford to the larger building, they're told to get on the Underground lines and make a change:

![signal-2023-07-07-095151_002](https://github.com/organicmaps/organicmaps/assets/29158971/c57365f4-0c73-4acc-93b8-ca8a06fe0bb8)

- If they select Stratford and then the smaller building, they're told to take the faster Elizabeth line all the way:

![signal-2023-07-07-095208_002](https://github.com/organicmaps/organicmaps/assets/29158971/924a8610-225c-4d67-905b-9659fa09a51c)

- It gets weirder if a stop a few stations from Stratford is selected:

![signal-2023-07-07-095224_002](https://github.com/organicmaps/organicmaps/assets/29158971/628ecd46-4750-41cd-8ad1-b899a85d6324)

Where they're told to get on the correct, fast train which would take them to their destination, but then it changes at a stop that happens to have a connection - and then continue (however the correct route is shown if the smaller station building is selected).

**Comment by biodranik** [comment]
@alexey-zakharenkov is it related to subway relations in OSM?

**Comment by alexey-zakharenkov** [comment]
@jpds I'm sure the roughness of the transit model affects. The app doesn't know what train service is faster, it operates with averaged values. There is a way to specify duration (inverse to speed) of a train route in OSM, but the XR route is lacking it; anyway the app doesn't take it into account for now.

What counts is the distance along the rails, and the distance of the destination point from a station center. Routing algorithm tries to lead you to the station that is closer to the final point, with the shortest path along rails, making amendments for transfers.

**Comment by RedAuburn** [comment]
the remaining issues are covered by [other transport routing issues](https://github.com/organicmaps/organicmaps/issues/5331), as the lizzy line is rendered and usable for routing i'd say this is resolved now :)
