### ISSUE TITLE
[Routing] Unpredictable jumps to real route and from it for pedestrians

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#2546]
Real route - blue part of route, utilising real roads.
start: 47.2196728, 38.8627865
finish: 47.2191428, 38.8633633
![image](https://user-images.githubusercontent.com/85622715/168113605-b81b78b7-4331-4560-9c34-e8e07bd03efc.png)
compare with 
finish: 47.219102, 38.863243
![image](https://user-images.githubusercontent.com/85622715/168114410-972139bd-50d4-4578-b717-bb58634dcaf6.png)

**Comment by AntonM030481** [comment]
Another strange effect is that fist segment of real path sometimes is very small and unexpectedly oriented.
start: 47.2196199, 38.8624116
finish: 47.2198782, 38.8634859
![image](https://user-images.githubusercontent.com/85622715/168126112-3dfdf7a1-1c5b-4f66-893e-6f18ff442ae1.png)

**Comment by biodranik** [comment]
It looks ok in the first example, the algorithm chooses the shortest distance to the nearest road.

**Comment by AntonM030481** [comment]
Do you think that both are OK here? https://github.com/organicmaps/organicmaps/issues/2546#issue-1234173715
For me second one only for sure.

**Comment by biodranik** [comment]
Why do you think it's not ok? Not the shortest distance?
