### ISSUE TITLE
Water under tunnels rendered as normal water

### ISSUE THREAD

**Issue by hippalectryon-0** [organicmaps/organicmaps#2564]
[Version 2022-04-27-2-Google]

Waterways with `tunnel=yes` are rendered as normal waterways. This is not the expected behavior (see https://help.openstreetmap.org/questions/1181/should-i-map-underground-water-tunnels).

I expect the same happens with `covered=yes` waterways.

Example: Bing Maps
![image](https://user-images.githubusercontent.com/6502864/168485206-2944c612-a3d0-4cad-9cb0-12d8a8c2df22.png)
 vs OrganicMaps: 
![image](https://user-images.githubusercontent.com/6502864/168485240-beab2f80-d7a5-469c-833e-4f6cf42197c9.png)

**Comment by vng** [comment]
Holy moly, thanks for the issue!

Possible solution here is to skip tunnel=yes area objects and don't think too much ..

More complicated solution is to take into account layer=* in draw priority for area objects (surprisingly, layer is nor working for areas now) and process area pedestrian ways/relations correctly even if area=yes is not set. Same [here](https://github.com/organicmaps/organicmaps/issues/2393)

**Comment by biodranik** [comment]
The best way is to draw semitransparent tunnel=yes, and then properly draw other objects on top of it using layer.

**Comment by pastk** [comment]
Which PR/commit did fix it? Is it https://github.com/organicmaps/organicmaps/pull/2583/commits/223f611a14397690ba2aa0f215025fbef059fcc1 ?

**Comment by vng** [comment]
Proper fix here was to correct assign the highway-pedestrian-area type.

And of course highway-pedestrian-area priority was (and should be) bigger than any water with layer < 0
