### ISSUE TITLE
[android] Log files are stored separately of all other files

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#2567]
By default logs are written to the "emulated" (internal shared storage), while e.g. maps are stored either in "internal" or on SD card. Other files (settings, bookmarks, etc.) reside in "internal" always.

(see `StorageUtils.getLogsFolder()` which uses getExternalFilesDir() returning "emulated" in most androids).

I think logs should go together either with maps ("writable dir") or maybe into "internal" always (as they contain sensitive info, but there will be no way for the user to read them?)

**Comment by biodranik** [comment]
That's an artifact of the introducing /data/data. Everything should be in one place, emulated storage.

**Comment by pastk** [comment]
> That's an artifact of the introducing /data/data. Everything should be in one place, emulated storage.

What if a user chose to put maps onto a SD card?
Keep logs on emulated anyway?

**Comment by biodranik** [comment]
1. Logs should be accessible
2. Logs should be with maps
Are both possible?

**Comment by pastk** [comment]
> 1. Logs should be accessible
> 
>     2. Logs should be with maps
>        Are both possible?

There is a (rare) case when maps storage could be not writable (read-only or full). In this case we can use some other writable location for logs. The downside is that there will be log files in a few places, which could be confusing to the user.

**Comment by pastk** [comment]
The only way I see to make logs always accessible is to add an export button similar to export bookmarks (because of android 10+ restrictions). Obviously it won't work for cases when the app is not starting and we want to see the logs to debug.

Or hopefully there is a way to put them into a standard shared documents location (along with pdfs etc.) - need to check it.
One more idea - ask user to pick a location when he/she enables logging.

**Comment by biodranik** [comment]
That's complex, let's leave it as is.

**Comment by pastk** [comment]
One user has a peculiar case of logging not working.
Android 5.1.1 (API 22)
EMUI 3.1
HUAWEI CHM-U01 (4C)

He has an SD as adopted storage.
`getExternalFilesDir()` returns a `/storage/sdcard1/...`, but its not writable (requires `WRITE_EXTERNAL_STORAGE` for some reason)!
also its not the first element of `getExternalFilesDirs()` (which is emulated storage)

So the app fails to log.
Debug logs:
```
06-03 09:03:29.850 17700 17700 W LoggerFactory: getExternalFilesDir: /storage/sdcard1/Android/data/app.organicmaps.beta/files
06-03 09:03:29.860 17700 17700 I LoggerFactory: isFileLoggingEnabled: true; logs folder: /storage/sdcard1/Android/data/app.organicmaps.beta/files/logs
06-03 09:03:29.860 17700 17700 I LoggerFactory: Creating a file logger for MISC
06-03 09:03:29.860 17700 17700 W FileLoggerStrategy: File logger created: /storage/sdcard1/Android/data/app.organicmaps.beta/files/logs/misc.log
06-03 09:03:29.860 17700 17700 I LoggerFactory: Creating a file logger for STORAGE
06-03 09:03:29.860 17700 17700 W FileLoggerStrategy: File logger created: /storage/sdcard1/Android/data/app.organicmaps.beta/files/logs/storage.log
06-03 09:03:29.860 17700 17729 E FileLoggerStrategy: Failed to write the string: I/LoggerFactory: isFileLoggingEnabled: true
06-03 09:03:29.860 17700 17729 E FileLoggerStrategy: java.io.FileNotFoundException: /storage/sdcard1/Android/data/app.organicmaps.beta/files/logs/misc.log: open failed: EACCES (Permission denied)
06-03 09:03:29.860 17700 17729 E FileLoggerStrategy: 	at libcore.io.IoBridge.open(IoBridge.java:482)
...
06-03 09:03:29.860 17700 17729 E FileLoggerStrategy: 	at com.mapswithme.util.log.FileLoggerStrategy$WriteTask.run(FileLoggerStrategy.java:150)
...
06-03 09:03:29.860 17700 17729 E FileLoggerStrategy: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
06-03 09:03:29.860 17700 17729 E FileLoggerStrategy: 	at libcore.io.Posix.open(Native Method)
06-03 09:03:29.860 17700 17729 E FileLoggerStrategy: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
...

```
