### ISSUE TITLE
[Navigation] Arguable number of exit from small roundabouts

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#2570]
Currently there is an exception in counting of exits from roundabouts.
Service road (including parking aisle) are not counted.
Maybe this is OK for big roundabout, but for small ones it's is confusing.
E.g. here 1st exit is advised. But in fact 2nd needed (in parking road will be taken in account):
From: 35.1310318, 33.3722178
To: 35.1309897, 33.3708949
![image](https://user-images.githubusercontent.com/85622715/168603869-6508051f-f26c-443f-a276-50ff787ba214.png)

**Comment by AntonM030481** [comment]
Here ignoring service roads looks reasonable:

Russia_HugeRoundabout_TurnTest
![image](https://user-images.githubusercontent.com/85622715/168620113-06c6f5d0-f175-4def-a9d8-f1dd53f29b73.png)

Russia_Moscow_TrikotagniAndPohodniRoundabout_TurnTest
![image](https://user-images.githubusercontent.com/85622715/168622773-52cd12ba-e093-46cc-b4cf-e1d54015e24a.png)

**Comment by vng** [comment]
Possible solution:
If roundabout has "major type" like motorway, ..., secondary - ignore services.
If roundabout has "same with service type" like residential, living_street, service - don't ignore.

@AntonM030481 WDYT?

**Comment by biodranik** [comment]
Drivers expect ALL exits to be counted.

**Comment by AntonM030481** [comment]
@biodranik have a look at these old cases. I didn't change them. Are you sure that you want to count all services roads here?
 https://github.com/organicmaps/organicmaps/issues/2570#issuecomment-1127782984
These cases were designed 7 years ago, and they were committed by bykoianko and you :)
TrikotagniAndPohodniRoundabout - https://github.com/AntonM030481/organicmaps/commit/3397cbcfb8f87100d23c7a6d897016ad16b5cdcf
HugeRoundabout - 
https://github.com/AntonM030481/organicmaps/commit/db0f5fcfdfed42429d29fb9cb001e5cfce1274c4

**Comment by AntonM030481** [comment]
@vng agree.
for Secondary and bigger roads - ignore service roads.
for Tertiary and smaller roads - consider service roads.

BTW, maybe for cyclists service roads should be considered always.
They for sure will count every one (but I don't know about this General Fueller example above).

**Comment by biodranik** [comment]
> These cases were designed 7 years ago, and they were committed by bykoianko and you :)

At that time I didn't have enough driver experience with OM and other apps :)

Ok, and improvement could be to count roads of one "class" lower, but do not count roads of two or more classes lower.
