### ISSUE TITLE
Broken link in TRANSLATIONS.md

### ISSUE THREAD

**Issue by 10992-osm** [organicmaps/organicmaps#2588]
The link in the **Technical details** section of TRANSLATIONS.md for the Twine syntax reference is broken:

> Most of the translation files (strings, types_strings...) are in Twine file format ([syntax reference](https://github.com/organicmaps/organicmaps/blob/master/tools/twine/README.md))…

**Comment by biodranik** [comment]
You can edit this file/link directly from the browser.

**Comment by pastk** [comment]
Fixed in #2598
