### ISSUE TITLE
qt5 path issue

### ISSUE THREAD

**Issue by johnwillicks** [organicmaps/organicmaps#2596]
I have been trying to set up this project for a few days now. However, I get the following error;

>  Using ccache, export CCACHE_DISABLE=1 to disable it.
> -- Using ld.gold
> CMake Error at CMakeLists.txt:223 (find_package):
>   Could not find a package configuration file provided by "Qt5" with any of
>   the following names:
> 
>     Qt5Config.cmake
>     qt5-config.cmake
> 
>   Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
>   to a directory containing one of the above files.  If "Qt5" provides a
>   separate development package or SDK, be sure it has been installed.
> 
> 
> -- Configuring incomplete, errors occurred!`

Where do I set the CMAKE_PREFIX_PATH? Where are the environment variables set?

I have already installed qt5 on my Ubuntu machine.

**Comment by biodranik** [comment]
How/where did you install qt5? Isn't it at `/usr/lib/x86_64-linux-gnu/qt5`? What does `which qmake` command say?
Generally, it's enough to have qmake in your PATH, then cmake is able to detect everything else automatically.
