### ISSUE TITLE
Devanagari font in 2022 May release is still old

### ISSUE THREAD

**Issue by sanketgarade** [organicmaps/organicmaps#2597]
I saw that the latest update for iOS now has Marathi (with Devanagari font) enabled on the maps. Thanks for this! 😃 

I checked it on my iPad and the Marathi names appear on the map now (with Marathi set as the topmost "preferred language").
But the new font that I had added in #2247  (`data/08_NotoSerifDevanagari-Regular.ttf`) is not getting applied. The font that is visible in this version is still the same as that in the previous versions.

https://fonts.google.com/noto/specimen/Noto+Sans+Devanagari

Say for the word पिंपरी चिंचवड ,

Here is how it looks :

![image](https://user-images.githubusercontent.com/74632379/169634019-319e0a41-7e4d-4f70-89f9-ef9f5db3dc4e.jpeg)

How it should look :
![image](https://user-images.githubusercontent.com/74632379/169633857-74caba3b-e9b7-4160-850b-c0f0c35f53cd.png)

**Comment by biodranik** [comment]
Could it be related to #1723 and #516

**Comment by sanketgarade** [comment]
I am not sure, but probably yes. If multiple people have reported the same issue (for different scripts), then maybe it is not related to one specific font, but more of a rendering issue.

**Comment by sanketgarade** [comment]
Ok I want to understand this in detail so that I can study and find out if its doable for me or not.

Please correct me if I am using the wrong terms or have a wrong understanding.
What I gathered from the above referenced issues and a brief study is -

1. OM app (across all platforms) uses the FreeType library for font rendering (displaying) on the map. This library does not render certain (complex) script fonts properly. Basically it renders whatever is passed to it in a linear/sequential way.
2. Hence you need something else which can arrange the glyphs properly and then pass it to the FreeType for rendering. From [Complex text layout wiki](https://en.wikipedia.org/wiki/Complex_text_layout#Implementations)

> Most text-rendering software that is capable of CTL will include information about specific scripts, and so will be able to render them correctly without [font files](https://en.wikipedia.org/wiki/Computer_font) needing to supply instructions on how to lay out characters. Such software is usually provided in a [library](https://en.wikipedia.org/wiki/Library_(computing));

And one such library is Harfbuzz, which is a shaping engine.

From https://www.reddit.com/r/archlinux/comments/8d7a1b/whats_the_difference_between_freetype_and/ ,
> harfbuzz tells programs what glyphs to put where, freetype rasterizes glyphs
> "shaping" means turning a string into a set of glyphs and their locations

3. It means that the Devanagari text (unicode) needs to be passed to harfbuzz which can shape the glyphs correctly and that output is then passed to FreeType to display/raster it on the screen.

4. Since harbuzz [already supports](https://harfbuzz.github.io/what-does-harfbuzz-do.html) Devanagari and other Indian & Arabic scripts, all that needs to be done is to integrate harfbuzz in OM in the manner mentioned in step 3. (I assume that the shaping is already done in harfbuzz and hence we don't need to do it.)

Is this correct?

**Comment by sanketgarade** [comment]
> I assume that the shaping is already done in harfbuzz and hence we don't need to do it.

ok, turns out that this is true 😄 . tested with `hb-view`.

![image](https://user-images.githubusercontent.com/74632379/169649177-c6c089fa-dc50-4f24-9a9f-890f2a2fb222.png)

**Comment by biodranik** [comment]
You're right. The goal now is to:
1. Accurately integrate Harfbuzz as 3party lib on all our platforms.
2. Fix the code in our Drape rendering engine to properly shift glyphs using Harfbuzz.

**Comment by sanketgarade** [comment]
ok. So is anyone already working on both the above items?

**Comment by biodranik** [comment]
No )

**Comment by sanketgarade** [comment]
Ok. I will try then.

If you can 
1. give me some pointers about the OM code relevant to this issue and 
2. break down these problem statements into smaller ones

then it will be helpful. 

> 1. Accurately integrate Harfbuzz as 3party lib on all our platforms.
> 2. Fix the code in our Drape rendering engine to properly shift glyphs using Harfbuzz.

**Comment by biodranik** [comment]
1. Check how other 3party libs are integrated. Add harfbuzz in the same way, build it and test.
2. grep for freetype in our code to find its usage.
3. Read harfbuzz examples with freetype and integrate them to our code.
4. Test it on all platforms.

**Comment by sanketgarade** [comment]
Noting for reference :

OSMAnd fixes this same issue by integrating harfbuzz in their iOS app v4.2 release. Delta between V4.2 and previous release version can be referred and studied for this development.
