### ISSUE TITLE
[Bug] Better support Kurdish alphabet by using a better shaping tool (Harfbuzz)

### ISSUE THREAD

**Issue by M86xKC** [organicmaps/organicmaps#2612]
<details>
<summary>Screenshot</summary>

![Screenshot of the OrganicMaps with broken kurdish font rendering](https://user-images.githubusercontent.com/31791780/169962343-b2556dca-0141-4530-aedc-0f1189f117d4.png)

</details>

Some characters from the Kurdish alphabet are missing when viewed on the map. I don't know if it is a problem with the font or the rendering, but I've seen this font with support for Kurdish all over android.

Maybe it is a stripped down version of the font for (performance reasons?) or an older version?  

btw the text in the middle should become "سلێمانی", "دارەبەن"، "کانی بەردینە" ...etc

From the looks of it the two most prominent missing characters are (which make the text almost unreadable specially for people with low vision):
U+06D5 ARABIC LETTER AE (UTF-8: 0xDB 0x95): " ە " 
U+06CE ARABIC LETTER YEH WITH SMALL V (UTF-8: 0xDB 0x8E): " ێ "

App version 2022.04.27-2-FDroid
Android Version: 11

**Comment by biodranik** [comment]
Can you please share the app's log? Or at least the part where fonts are initialized and loaded?
Also, can you please check if these letters are present in ttf files here: https://github.com/organicmaps/organicmaps/tree/master/data ?

**Comment by biodranik** [comment]
Is OSM data also correct?

**Comment by M86xKC** [comment]
I'm not certain on that one.
But it looks correct in OsmAnd~ and www.openstreetmap.org
It might be worth take a look into the OSM data though they might be doing something with the data. Because only these two characters I found are affected by this. 

<details>
<summary>Screenshot</summary>

![Map of the city of سلێمانی openstreetmap.org](https://user-images.githubusercontent.com/31791780/170061311-b7e25568-3587-4c11-9327-459da0c32b02.png)

![Map of the city of سلێمانی OsmAnd](https://user-images.githubusercontent.com/31791780/170060897-249f9c03-57ee-46a0-8c31-6191bddd81cb.png)

</details>

**Comment by M86xKC** [comment]
Here are two related issues you might find useful. Apparently updating Skia and Harfbuzz should fix the issue.

1. https://github.com/osmandapp/OsmAnd/issues/13097
2. https://github.com/osmandapp/OsmAnd/issues/6782

**Comment by M86xKC** [comment]
I would guess so.

**Comment by biodranik** [comment]
@M86xKC Organic Maps doesn't support Harfbuzz yet. It should be integrated, see #4281

**Comment by M86xKC** [comment]
Thanks! it is fixed now :rocket:
