### ISSUE TITLE
In Navigation Modus, the infos at the bottom of the screen are cut

### ISSUE THREAD

**Issue by schorschfunke** [organicmaps/organicmaps#2616]
![Screenshot_20220524-175306248](https://user-images.githubusercontent.com/4370739/170083732-1f87c2ab-7963-4dca-91c6-bccbf0259bf8.jpg)
![Screenshot_20220524-175258440](https://user-images.githubusercontent.com/4370739/170083743-52b6598a-9af0-4478-bdd9-11c250a82d25.jpg)
The bottom area of the screen in navigation mode is cut. See the attached screenshots. 
My device is OP6t with crdoid custom rom A11.
App version is 2022.05.24-2-Web

**Comment by SaranshBaniyal** [comment]
Can you please assign this issue to me. I am an Android dev beginner, would very much love to contribute.

**Comment by schorschfunke** [comment]
In the latest versions the bug is fixed for me,  so i will close the bug😁
