### ISSUE TITLE
Show vehicle inspection places

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#2621]
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dvehicle_inspection

Icon can be generic (just a car)

**Comment by biodranik** [comment]
There should be a better icon. A car can mean many different things...

**Comment by AntonM030481** [comment]
Sure it will be better.
My suggestion was for 1st iteration.

Not sure who can create image for this. We need to match existing car icon style.

**Comment by dvdmrtnz** [comment]
Based on the style of the OSM Carto icon <img src="https://github.com/organicmaps/organicmaps/assets/47610359/986875b7-079a-4dcf-8f51-6945a5e1527c" width="36"/> (https://wiki.openstreetmap.org/wiki/File:Vehicle_inspection-14.svg), I made this icon:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/0ae199e0-74db-4ffb-81a2-fb89dddd9e73" width="36"/>

**Comment by biodranik** [comment]
Is it recognizable in a small resolution? There are some ideas with a magnifying glass when you google for `car inspection icon`.

**Comment by dvdmrtnz** [comment]
> Is it recognizable in a small resolution? There are some ideas with a magnifying glass when you google for `car inspection icon`.

I tried to make it pixel perfect after learning from https://github.com/organicmaps/organicmaps/issues/4017 how the exact icon images are generated. I think it looks good at the smallest 18x18 resolution:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/b6f54f0a-0ab0-4715-80b7-f01b828bdf41" width="126"/>
