### ISSUE TITLE
[styles] Do not draw place=region features.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#2626]
According to the [doc](https://wiki.openstreetmap.org/wiki/Tag:place=region)
```
This is a tag from the earliest days of OpenStreetMap, is used in various ways, was never clearly defined and is rarely used by data consumers.

As of 2022, the [Standard tile layer](https://wiki.openstreetmap.org/wiki/Standard_tile_layer) does not render such natural regions, but [OpenTopoMap](https://wiki.openstreetmap.org/wiki/OpenTopoMap) does.
```

But keep them in search.

**Comment by vng** [comment]
Some noisy screens:
![Screenshot_20220525_152218_app organicmaps](https://user-images.githubusercontent.com/175612/170482850-cdbdb681-d39c-46f3-aae0-151ef0ed51d3.jpg)
![Screenshot_20220525_152448_app organicmaps](https://user-images.githubusercontent.com/175612/170482863-6e087016-189f-42c9-bee5-cb79f40eb7f9.jpg)

**Comment by basings** [comment]
It's really sad to see this go.

When you explore the map and see the name of the region you might remember it. It's just interesting how regions are called. The examples are really unfortunate and I checked in other regions and it really can be messy but completely removing it on a map that doesn't dependend on images is sad tbo. 

Can't you simply lower its priority such that it is only shown on higher zoom levels or another solution?

**Comment by biodranik** [comment]
> [place](https://wiki.openstreetmap.org/wiki/Key:place)=region is used both as a broad tag for geographic or historical areas with no clear boundary and for distinct administration areas (with specific boundaries) in some countries.
> This is a tag from the earliest days of OpenStreetMap, is used in various ways, was never clearly defined and is rarely used by data consumers.

https://wiki.openstreetmap.org/wiki/Tag:place%3Dregion

**Comment by basings** [comment]
> Used both as a broad tag for geographic or historical areas with no clear boundary and for distinct administration areas (with specific boundaries) in some countries.
All | 2 3980.00%
-- | --
Node | 1 4740.00%
Way | 1550.00%
Relation | 7690.01%

https://taginfo.openstreetmap.org/tags/?key=place&value=region#overview
