### ISSUE TITLE
[Bookmarks]: freezes when opening or scrolling through some lists

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#2629]
**Device**: Xiaomi Redmi Note 9 Pro
**OS**: LineageOS 19 (Android 12)
**OM**: 2022.04.27-2-FDroid

Some bookmark lists are causing freezes when opening or scrolling through them.

On the [video](https://user-images.githubusercontent.com/22843816/170540051-d32ac2c3-e25c-4bb4-a147-5efe805255d0.mp4) you can see that _Мурманская область_ list works pretty fine (although not smooth) but _Петрозаводск_ causes freezes, although it has less bookmarks than _Мурманская область_. The same problem is with _Республика Карелия_ list which is attached too in [this archive](https://github.com/organicmaps/organicmaps/files/8780884/KMZ.zip).

[Logs](https://github.com/organicmaps/organicmaps/files/8780891/logs.zip) are attached too

**Comment by biodranik** [comment]
Looks like some slow/unnecessary operations are called during the scroll. It should be debugged and fixed.

**Comment by Jean-BaptisteC** [comment]
@PetbkA can you retry on the latest version?

**Comment by Jean-BaptisteC** [comment]
Thanks for feedback. I close this issue.
But it's can be reopen is problem appears on other devices.
