### ISSUE TITLE
change the path of saved maps

### ISSUE THREAD

**Issue by GH0STsama** [organicmaps/organicmaps#2633]
**[suggestion]**
why does the app not let you change the path of the saved maps?  that is, save them in another path that is not:
`/data/data/app.organicmaps/files`

e.g. allow saving them to paths like:
`/storage/emulated/0/organicmaps/files`

this would allow access to them without being root

**Comment by vng** [comment]
If you take the latest app (May) and install it from scratch, it should save maps into "emulated" domain. Could you please check it?

**Comment by GH0STsama** [comment]
> If you take the latest app (May) and install it from scratch, it should save maps into "emulated" domain. Could you please check it?

I have the latest update (May), and it only lets me select the default path data/data/app.organicmaps/files`

**Comment by GH0STsama** [comment]
> > If you take the latest app (May) and install it from scratch, it should save maps into "emulated" domain. Could you please check it?
> 
> I have the latest update (May), and it only lets me select the default path `data/data/app.organicmaps/files`

![Screenshot_20220528-072609](https://user-images.githubusercontent.com/87672676/170823758-0908a803-eb14-4cb4-9a32-a0ddce1f00ae.jpg)
![Screenshot_20220528-072534](https://user-images.githubusercontent.com/87672676/170823760-4dbb7f3e-7324-4206-9a98-bb5986ab9cde.jpg)

**Comment by biodranik** [comment]
Can you please enable Logs in OM settings, restart the app, press ? and then Report a bug, and send us email with logs?

**Comment by GH0STsama** [comment]
> Can you please enable Logs in OM settings, restart the app, press ? and then Report a bug, and send us email with logs?

of course, right now I send you the email with the log!

the text contains the link to this issue

**Comment by biodranik** [comment]
@GH0STsama Logs show that you have the April version of the app, not the latest one (May).

**Comment by GH0STsama** [comment]
> @GH0STsama Logs show that you have the April version of the app, not the latest one (May).

oh, I'll try downloading the release from GitHub, according to the play store I had the latest... I don't know what I use it for..

**Comment by GH0STsama** [comment]
> @GH0STsama Logs show that you have the April version of the app, not the latest one (May).

that was it, thank you!  😁 keep it up, I love your app, and the support is perfect!
