### ISSUE TITLE
[android] Impossible to delete bookmarks list if it's name is too long

### ISSUE THREAD

**Issue by janusbenissa** [organicmaps/organicmaps#2635]
It is impossible to delete bookmarks with a very long tittle.
If you click on the three dots next to the bookmark you only see the tittle, no option to delete the bookmark.

**Comment by biodranik** [comment]
Sorry, can you please clarify?
To delete a bookmark, you tap it on the map, and press a star button.

Are you talking about deleting the list of bookmarks? Then the last remaining list can't be deleted at the moment.

**Comment by janusbenissa** [comment]
Sorry, I mean with bookmarks, a KMZ file with multi tracks in it.
I imported them but the tittle was all the names of the tracks after each other.

**Comment by biodranik** [comment]
Is it the only bookmarks list? Can you create a new one, and then delete the old one?

**Comment by janusbenissa** [comment]
I can create a new one but can't delete the old one.

**Comment by biodranik** [comment]
Is it Android or iOS? Is it possible to use your kml/kmz file to reproduce the issue?

**Comment by janusbenissa** [comment]
Android, latest version of OM
[20220528135707-12250-map.kmz.txt](https://github.com/organicmaps/organicmaps/files/8791864/20220528135707-12250-map.kmz.txt)

Rename file to kmz

**Comment by biodranik** [comment]
Thanks! Reproduced. The title text takes up all available space and the menu is not visible. It makes sense to limit the title to some 3 lines max and truncate the text.
