### ISSUE TITLE
F-droid releases lag behind other app stores

### ISSUE THREAD

**Issue by Salim9304** [organicmaps/organicmaps#2639]
1. I'm an open source fan and don't use GP, but the releases for the F-droid store are delayed, the latest version is 2022.04.27-2-FDroid.  Since in other stores this version of the application is 2022.05.20.

2. The OSM maps themselves are outdated on April 15, although the documentation says that the maps will be updated (1-4 times a month), there are no map updates for a month and a half.  

Please put things in order with releases, maps and possibly updating the documentation (update).

**Comment by biodranik** [comment]
Sorry, our small team doesn't have enough time and resources to handle everything in a perfect way. It's our hobby project :)

There were some fdroid build issues, and now the build is ready, but is waiting for their manual signature.
