### ISSUE TITLE
Add support for opening_hours:check_date

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#2642]
Support for opening_hours:check_date would inform you if the opening hours haven't been updated for a long time. 
this would be useful as you can gauge if they will still be correct.

mock-up:
![Screenshot_20220529-145704_Organic Maps](https://user-images.githubusercontent.com/26939824/170873443-2ee70493-d1ec-4b09-907b-4c0522443762.jpg)

**Comment by biodranik** [comment]
It is rare and not reliable anyway. A better (but still not reliable) way is to check the last edited date of the feature.

**Comment by endim8** [comment]
> It is rare and not reliable anyway. A better (but still not reliable) way is to check the last edited date of the feature.

I was thinking about that, ideally comparing all previous versions until the opening_hours value is different, but including history in the pbf will make it like 10x the size. Maybe it can be retrieved using the overpass API?

**Comment by biodranik** [comment]
The problem you're trying to solve is not comparable with efforts :) There is no guarantee that the Opening Hours are still valid even if they were edited yesterday. It depends only on the business itself.
