### ISSUE TITLE
Display of forest roads and trails at a scale of 1 km

### ISSUE THREAD

**Issue by Salim9304** [organicmaps/organicmaps#2644]
At the moment, forest roads and trails are displayed on a scale of up to 500m, for tourists this is too small coverage on the gadget screen.  It is difficult to plan routes in the forest and countryside.  
But at the same time, city roads are displayed on a scale > 1km.  On the example of osmand, there forest roads are displayed on a scale of 2 km.  very comfortably. 

 And osm maps, in my opinion, are primarily touristic, and only then urban.

**Comment by biodranik** [comment]
Many of our users use OM in cities and towns. It's hard to make a universal style, so we decided to split styles: #1577

**Comment by Salim9304** [comment]
Good.  But you should understand that forest roads are not only for hikers, they are ridden by bicycles, motorcycles and cars.

**Comment by biodranik** [comment]
We would enable all roads, but the actual problem is that cities become very polluted and look ugly.

**Comment by Salim9304** [comment]
Here, I opened a random forest area, osmand displays forest roads connecting villages, natural objects, it is obvious how to get to lakes, etc.  It's not obvious in OM.
![2022-05-31-09-26-08-059](https://user-images.githubusercontent.com/61138725/171107252-03cd6a10-c6e7-44d0-94ed-2c9229e33ac9.jpg)

**Comment by biodranik** [comment]
Again, I completely agree with you. The problem is with cities, not with outdoor areas.
