### ISSUE TITLE
[Routes]: can't plan car route between Moscow and Murmansk

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#2646]
**Device:** Xiaomi Redmi Note 9 Pro.
**OS:** LineageOS 19 (Android 12).
**OM:** 2022.05.24-2-FDroid.

Today I've tried to plan car route between two "capitals":
1. From _Moscow_ (55.750447, 37.617495)
2. To _Murmansk_ (68.970664, 33.074967)
but got an error that I have to change starting point or destination.

Theoretically it's OK 'cause _Moscow_ point is in Kremlin which isn't accessible via car (at least as OM shows it).

_Murmansk_ point isn't too far from road but still is on the square with pedestrian roads only.

I've changed starting and ending points to:
1. _Метро «Библиотека имени Ленина»_ (55.752884, 37.611567, near the road);
2. Some point at _Vorovskogo Street_ in  Murmansk (68.969947, 33.074904, right on the road)
but still got no avail. This route definitely should've been able to be planned.

Logs are [attached](https://github.com/organicmaps/organicmaps/files/8801676/logs.zip)

**Comment by vng** [comment]
Confirm strange situation.
Череповец -> Мурманск, ок
Устюжна -> Мурманск, not ok
Everything downloaded, except Leningrad Oblast North, but it's not needed here. Petersburg is out of date.
