### ISSUE TITLE
[Map]: scrolling isn't always "inertial" when sliding quickly

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#2652]
**Device**: Xiaomi Redmi Note 9 Pro
**OS**: LineageOS 19 (Android 12)
**OM**: 2022.04.27-2-FDroid

When sliding quickly through map, scrolling isn't always "inertial", i.e. it looks like I'm doing "slow" scrolling.

Don't know how to describe it better so I've attached a video from [Yandex.Maps](https://user-images.githubusercontent.com/22843816/171311255-526cf399-8cd0-4e34-9d5e-a31b5fa7482d.mp4) and [OM](https://user-images.githubusercontent.com/22843816/171311330-8486c4cd-0acc-4cdd-972d-c9202eac331c.mp4) for comparison. You can see that Yandex always scrolls "inertially", unlike OM.

There's some dependence on the detailization of the region being scrolled through, although it happens even when scrolling through "plain" areas

**Comment by biodranik** [comment]
It also rarely happens on iOS.

**Comment by n8x0b7T** [comment]
I have the same issue on Android.

**Comment by endim8** [comment]
Weirdly I can only reproduce it with release builds, fdroidDebug works fine

**Comment by n8x0b7T** [comment]
If it helps, I'm installing the app through F-Droid.

**Comment by GIthubbomax** [comment]
The same here,  but in other map apps working well #

**Comment by SnIPeRSnIPeR** [comment]
Same thing on OnePlus Ace (10R), Android 12.1

**Comment by n8x0b7T** [comment]
@endim8 Any word on if this is something that can be fixed?

**Comment by utack** [comment]
What is even weirder:  
Never works on my S21, but when I switch the display down to 60Hz display refresh rate it starts working in many places

**Comment by vng** [comment]
Ok, I can reproduce _no animation_ on my iPhone.
Immediately after zoom-in/zoom-out first scroll gesture doesn't invoke animation. 2nd, 3rd, ... are ok.

Suspect that there are any uninitialized vars. Will take a look soon.

**Comment by Atemu** [comment]
This problem still reptoduces for me.

It's not just fling after zoom being an issue though; fling is generally a bit too "sticky" I feel.

**Comment by vng** [comment]
Please, test if possible on your Android devices: https://github.com/organicmaps/organicmaps/pull/6237
Any feedback is welcome.
