### ISSUE TITLE
dissapearing poi info

### ISSUE THREAD

**Issue by j13m126** [organicmaps/organicmaps#2664]
I stumbled upon this little bug at this [memorial](https://www.openstreetmap.org/way/187078721) on Android 12 (App version 2022.05.31-8-Google-beta and 2022.05.20-4-Google)

![screenshot1](https://user-images.githubusercontent.com/7961926/171814534-7eb3f063-6526-4769-9028-1881aa5f039a.gif)

**Comment by biodranik** [comment]
There is also a monument there: https://www.openstreetmap.org/node/3372150572

**Comment by Jean-BaptisteC** [comment]
Fixed in 2023.09.22-27-Google version
