### ISSUE TITLE
Possible issue with building Ubuntu 20.04

### ISSUE THREAD

**Issue by jdhoek** [organicmaps/organicmaps#2667]
I'm following `docs/INSTALL.md` on Ubuntu 20.04, but the build gets stuck.

The first problem I ran into (which may be related to the latter) was that the documentation gives the following instructions for installing build dependencies:

```
sudo apt-get update && sudo apt-get install -y \
    build-essential \
    cmake \
    clang \
    ninja-build \
    python3 \
    qtbase5-dev \
    libc++-dev \
    libfreetype-dev \
    libglu1-mesa-dev \
    libicu-dev \
    libqt5svg5-dev \
    libsqlite3-dev \
    zlib1g-dev
```

(Ubuntu 20.04 is explicitly mentioned.)

This however installs Cmake version `3.16.*`, but the build requires `3.18.0` at the least. I've installed version `3.23.2` manually from the Cmake website. So this may be a bug in the documentation.

After that, the build (`tools/unix/build_omim.sh -r desktop`) starts, but I get stuck somewhere in the part where Unity is built. I've attached the output. Any idea what I'm doing wrong? Is Ubuntu 20.04 still supported as build environment?
[build-output.txt](https://github.com/organicmaps/organicmaps/files/8834868/build-output.txt)

**Comment by biodranik** [comment]
You're right, the documentation should be updated.
There are some errors in the build log, which compiler version are you using?

**Comment by programmin1** [comment]
Ubuntu 22.04 is the new LTS release and [it has 3.22 in the repository](https://packages.ubuntu.com/jammy/cmake).

How did you upgrade Cmake and why didn't you do an upgrade which would upgrade Cmake from [Focal's  old 3.16](https://packages.ubuntu.com/focal/cmake)?

**Comment by jdhoek** [comment]
> There are some errors in the build log, which compiler version are you using?

The defaults from Ubuntu 20.04. Only Cmake is different. From which binaries shall I look up the versions?

**Comment by biodranik** [comment]
g++ --version

**Comment by jdhoek** [comment]
```
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

**Comment by vng** [comment]
I don't have g++ 9.4 to test, but try to apply this patch:
```
diff --git a/generator/intermediate_data.cpp b/generator/intermediate_data.cpp
index 8a5f0f403c..b9ab83b4ef 100644
--- a/generator/intermediate_data.cpp
+++ b/generator/intermediate_data.cpp
@@ -64,6 +64,8 @@ void AddToIndex(Index & index, Key relationId, Container const & values)
 class PointStorageWriterBase : public PointStorageWriterInterface
 {
 public:
+  virtual ~PointStorageWriterBase() noexcept(false) override = default;
+
   // PointStorageWriterInterface overrides:
   uint64_t GetNumProcessedPoints() const override { return m_numProcessedPoints; }
```

**Comment by jdhoek** [comment]
@vng Patch applies cleanly. I get a different output, but this error at the patched line:

```
In file included from /home/freaknl/Dev/osm/omim-build-release/generator/CMakeFiles/generator.dir/Unity/unity_0_cxx.cxx:99:
/home/freaknl/Dev/osm/organicmaps/generator/intermediate_data.cpp:67:11: error: non-deleted function ‘virtual generator::cache::{anonymous}::PointStorageWriterBase::~PointStorageWriterBase()’ overriding deleted function
   67 |   virtual ~PointStorageWriterBase() noexcept(false) override = default;
```
[build-output-patched.txt](https://github.com/organicmaps/organicmaps/files/8839523/build-output-patched.txt)

**Comment by vng** [comment]
Have no idea here, the compiler assumes that ~PointStorageWriterInterface() and ~PointStorageWriterBase() are deleted, but they are explicitly marked as default.

Need to experiment to find correct workaround for gcc. Try to replace "= default" with empty body {} in both cases.

**Comment by jdhoek** [comment]
Right! That fixes the build on my end:

```diff
diff --git a/generator/intermediate_data.cpp b/generator/intermediate_data.cpp
index 8a5f0f403c..bd56398c38 100644
--- a/generator/intermediate_data.cpp
+++ b/generator/intermediate_data.cpp
@@ -64,6 +64,8 @@ void AddToIndex(Index & index, Key relationId, Container const & values)
 class PointStorageWriterBase : public PointStorageWriterInterface
 {
 public:
+  virtual ~PointStorageWriterBase() noexcept(false) override {};
+
   // PointStorageWriterInterface overrides:
   uint64_t GetNumProcessedPoints() const override { return m_numProcessedPoints; }
 
diff --git a/generator/intermediate_data.hpp b/generator/intermediate_data.hpp
index 14241634ee..e130e62c71 100644
--- a/generator/intermediate_data.hpp
+++ b/generator/intermediate_data.hpp
@@ -58,7 +58,7 @@ static_assert(std::is_trivially_copyable<LatLonPos>::value, "");
 class PointStorageWriterInterface
 {
 public:
-  virtual ~PointStorageWriterInterface() noexcept(false) = default;
+  virtual ~PointStorageWriterInterface() noexcept(false) {};
   virtual void AddPoint(uint64_t id, double lat, double lon) = 0;
   virtual uint64_t GetNumProcessedPoints() const = 0;
 };
```

I have no idea if this breaks anything in newer environments though, but for Ubuntu 20.04 at least this leads to a working binary.

**Comment by vng** [comment]
Great!

**Comment by jdhoek** [comment]
Do you want this as a PR, of shall I leave that to you? I have no idea if this patch causes collateral damage.

**Comment by vng** [comment]
Could you try to leave only this change (remove ~PointStorageWriterBase)?
```
+  virtual ~PointStorageWriterInterface() noexcept(false) {}
```
If its ok on your system, feel free to add fix commit with this change. It will not break anything.
