### ISSUE TITLE
Sports centers have no building

### ISSUE THREAD

**Issue by Fxsch** [organicmaps/organicmaps#2671]
While the icons of sports centers are there, the building itself isn't. Here are pictures of how it looks in Organic Maps and on the OpenStreetMap website:
![Screenshot_20220605-091703_Organic_Maps](https://user-images.githubusercontent.com/77849217/172040058-82ca55ec-2863-4d32-96ca-5152f79adf2a.png)
![Screenshot_20220605-091726_Iceraven](https://user-images.githubusercontent.com/77849217/172040061-bbf57166-b54c-491b-86a2-f495a090f1e6.png)

**Comment by biodranik** [comment]
@pastk isn’t it a drawing priority issue?

**Comment by Kazing** [comment]
I think the problem comes from Openstreetmap data and not from Organicmaps.

This buildidng shall have a `building=yes` tag but does not : https://www.openstreetmap.org/way/238178323

**Comment by Fxsch** [comment]
That seems to be the issue, other sports centers that have that tag are getting rendered properly. I'll change it on OpenStreetMap then.
