### ISSUE TITLE
Invisible chars broke search by coordinates

### ISSUE THREAD

**Issue by leonidv** [organicmaps/organicmaps#2682]
Android 9 (Xiaomi mi 9t)
OrganicMaps 2022.05.31-Google

If a copied text contains invisible chars and newlines, a search by coordinates is not work
Example of the pasted text (without quotes):
"48.351795, 40.295364

“
After deleting chars it's working correctly.

https://youtube.com/shorts/K4BaUjPxPDI

**Comment by biodranik** [comment]
@vng do we properly trim the search input?
