### ISSUE TITLE
Water icons hard to see

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#2683]
Issue created for https://github.com/organicmaps/organicmaps/pull/2203#issuecomment-1147356877

potential issues:
- waterfalls
- fountains
- drinking water points

**Comment by endim8** [comment]
i'm out at the moment, but i'll look at this when i get back 👍

**Comment by endim8** [comment]
Making the waterfall 150% bigger improves visibility a lot, do you think the colour change is still needed @biodranik ?
<img width="644" alt="bigger" src="https://user-images.githubusercontent.com/26939824/172259185-22c4218f-d3e5-4192-8537-261ee89e108a.png">

**Comment by endim8** [comment]
darker & 150% scale:
<img width="322" alt="Screenshot 2022-06-06 at 23 31 06" src="https://user-images.githubusercontent.com/26939824/172259961-78dafde9-f41e-4830-b480-6ff890549d75.png">

**Comment by endim8** [comment]
i think fountain would also benefit from scaling:
![Screenshot 2022-06-06 at 23 49 53](https://user-images.githubusercontent.com/26939824/172262339-3084d4f0-c0cc-42f3-9e6a-342cd6481263.png)

**Comment by biodranik** [comment]
Yeah, they look good. Please also check waterfalls with
1. Night theme
2. On the forest and grey (empty) background
And change the color if needed.

**Comment by pastk** [comment]
Could you please test in an area with any waterfalls also, e.g. https://github.com/organicmaps/organicmaps/issues/755#issue-930895548

**Comment by endim8** [comment]
> Could you please test in an area with many waterfalls also, e.g. [#755 (comment)](https://github.com/organicmaps/organicmaps/issues/755#issue-930895548)

They are less obnoxious now, but a full fix is only really possible with layers for hiking etc (#1577)
![Screenshot_20220614-015834_Organic Maps (Debug)](https://user-images.githubusercontent.com/26939824/173471520-e5a8e808-f8df-437e-a6be-791a70d09aaa.jpg)
