### ISSUE TITLE
address search not working in town Mannheim since most houses only use addr:place and no street name

### ISSUE THREAD

**Issue by foss-** [organicmaps/organicmaps#2689]
In city center of Mannheim there are only a few street names but most squares go by a letter combined with a number e.g. the building in F1 7 does not use a street name, but `addr:place F1`.

**Currently**

A search for `F1 7` in OM shows many results but not the address users may be searching for.

**Expected**

Allow search to also take `addr:place` into consideration. While some builds do have a street, for most street is blank and addr:place is used instead making it hard to find anything currently.

This is the link to the city center: https://osm.org/go/0DwUI1Ef?relation=62691

**Comment by strump** [comment]
If I understand correctly, addresses in Mannheim looks like: 5, L12, Mannheim, where 5 is building number, L12 is square name. L12 is not a street name, so it would be hard to implement such address system.
See details: https://forum.openstreetmap.org/viewtopic.php?id=61194
https://forum.openstreetmap.org/viewtopic.php?id=62139

**Comment by vng** [comment]
addr:place is a commonly used tag in German addresses. Some more examples that should work:
```HOPFENBURG 12 D-72525 MÜNSINGEN``` https://www.openstreetmap.org/way/142581712#map=19/48.40362/9.50835

**Comment by biodranik** [comment]
As it was mentioned in #6643, Mannheim search works; HOPFENBURG does not work, because of place without actual tag place=*

Is it a tagging issue? Can this one be closed? @vng

**Comment by vng** [comment]
"HOPFENBURG"-like addresses are still questionable.

**Comment by biodranik** [comment]
@vng let's create a separate/dedicated issue for it?
