### ISSUE TITLE
Translation "Kamera vorne"

### ISSUE THREAD

**Issue by bitboy85** [organicmaps/organicmaps#2694]
https://github.com/organicmaps/organicmaps/blob/1bc8313a11e022c272c66cd0ce26ac4be722d790/data/strings/sound.txt#L2313

This should be "Kamera voraus"

**Comment by AlertSubject** [comment]
Even better if it also says "in x meters"

Example: "Blitzer in 300 Metern"

**Comment by biodranik** [comment]
Please fix it )
