### ISSUE TITLE
Road gets missed in Routing

### ISSUE THREAD

**Issue by thomasjimmy** [organicmaps/organicmaps#2696]
![Suggested Route](https://user-images.githubusercontent.com/8177444/172683018-0110fb35-22b5-4352-b8bc-8e0864f25d68.jpg)
![Map](https://user-images.githubusercontent.com/8177444/172683039-34a6136f-e544-4d6e-a130-810a1eb145ff.jpg)

A usable road gets missed while routing. The road getting missed is already tagged in OSM. (https://www.openstreetmap.org/way/389548229)   

Steps to recreate
1. Starting Point - https://www.openstreetmap.org/#map=18/9.7836682/76.5777457
2. Destination Point - https://www.openstreetmap.org/#map=18/9.9840800/76.2741457
3. Road getting missed - https://www.openstreetmap.org/way/389548229

Version Of Organic Maps -> 2022.5.31-10
Routing Options -> Nothing selected

**Comment by vng** [comment]
Can't say anything about ground truth, but the app prefers primary detour with maxspeed = 70kmh instead of residential section (usually ~15 kmh) ..

**Comment by biodranik** [comment]
@thomasjimmy why do you think that navigation should make a shortcut? It's not an OM issue, but an OSM mapping issue.

**Comment by thomasjimmy** [comment]
ok, understood the logic. But here, in this case
1.The non highway road is not a residential road. Is there any way to mark this in OSM?
2. The highway doesnt get a speed of 70 km because of the curved nature. It will be also slow. So here, practically preferred route is the non highway road.

**Comment by Popolon** [comment]
The maxspeed tag (Speed Limit item in interface) can be set road by road or even by section of road in OpenStreetMap, is 70km/h really accepted in this city (in France that's 50 or 30) ? There is no maxspeed at all on this road, adding it would probably help the routing tool.

**Comment by Misalf-git** [comment]
> is 70km/h really accepted in this city (in France that's 50 or 30) ? There is no maxspeed at all on this road, adding it would probably help the routing tool.

Probably, maybe, however (in case anyone runs ahead and blindly tags it with maxspeed=70), mapping for the tools is not the right direction. 
I hope you meant to say "is 70km/h really **_allowed_**", because the question must not be "what is acceptable" but "what is the real maxspeed to be seen on signs along the road".

I've luckily been caught first time I made such a stupid mistake and learned immediately that my assumptions often don't reflect reality.
Just a friendly warning.

**Comment by RedAuburn** [comment]
working now:
![image](https://github.com/user-attachments/assets/6b861390-047c-421f-88a5-423763a7676c)
