### ISSUE TITLE
add link to openbenches for benches with openbenches:id

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#2698]
the tag isn't used much yet, but it'd be cool to have.
https://wiki.openstreetmap.org/wiki/Key:openbenches:id

i'm working on linking as many benches in London as possible, so the tag will increase in usage a lot.

example bench:
https://www.openstreetmap.org/node/9768393702
https://openbenches.org/bench/23409/

**Comment by strump** [comment]
I found 209 nodes with `openbenches:id` tag in OSM: https://taginfo.openstreetmap.org/keys/openbenches:id

It's not very popular case.

**Comment by endim8** [comment]
> I found 209 nodes with `openbenches:id` tag in OSM: https://taginfo.openstreetmap.org/keys/openbenches:id
> 
> It's not very popular case.

At the moment, yes.

**Comment by AlertSubject** [comment]
What's the use case for the average user?
I'd imagine this to be somewhat confusing
