### ISSUE TITLE
Display toilet fee

### ISSUE THREAD

**Issue by hippalectryon-0** [organicmaps/organicmaps#2707]
When searching for "Toilet", the nodes on the map don't have any indication whether there's a fee. This is obviously not great for the users, as we most often search for free toilets.

Suggestion: if osm knows the toilet has a fee, display a line below/after "Toilets" indicating it.

**Comment by PetbkA** [comment]
I would also suggest to enable filtering toilets while searching. It's nice to see "paid" sign, but it's better to see _only_ free toilets in search results.

I remember that some filtering functionality was available in Maps.ME era for hotels. Now I don't see it but I hope that the open source part of the code has it
