### ISSUE TITLE
[android] Separation of logs into several files

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#2713]
Log files in Android are separated into several "scopes": `MAIN, LOCATION, TRAFFIC, GPS_TRACKING, TRACK_RECORDER, ROUTING, NETWORK, STORAGE, DOWNLOADER, CORE, THIRD_PARTY`

The idea is to keep all related log messages together without the "noise" from unrelated ones and hence make debugging easier.
In my experience it works quite well with STORAGE (for storage options scanning) and, maybe, LOCATION.
However, e.g. DOWNLOADER log is pretty useless - it doesn't contain names of files being downloaded even!
And most other scopes suffer from the fact that often Android code is just a thin frontend to a native core code, which logs everything to CORE. So often related log messages are split between the CORE and SOMETHING_ELSE, and its a pain to switch between the files to understand what message follows what - in those cases a regular single log will be much more helpful.

Here are some [raw] ideas how to improve it:
1. Log everything into a single file. We can have a scope attribute written with every log message still to facilitate log filtering.
2. Log into a single file in addition to separate files. The downside is extra logging overhead, but perhaps its ok for a debugging feature that is supposed to be enabled on request only.
3. Log everything into android syslog (logcat) always in addition to separate files. Pros: less overhead compared to file writing and a single most complete log (incl. system messages). Cons: capturing logcat doesn't work on all devices.
4. Add scopes support into core native code (and iOS code too?), so that separation is more logical and useful.

Personally I'd prefer option 1. as the easiest and the most simple one. Also if we go with it we can switch to a static logging API (instead of Logger object creation) just like android's, e.g. `Logger.i(TAG, msg)`  where TAG could contain both scope and class name.

**Comment by biodranik** [comment]
Let's make it simple:
1. Log everything into one file.
2. Remove scopes
3. Grep by tag name should be enough.

**Comment by pastk** [comment]
Done in #2700
