### ISSUE TITLE
[Search]: include bookmarks in search results

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#2719]
Sometimes I need to plan a route to or find a place marked only as bookmark (i.e. "Best parking area" when planning a trip). But bookmarks aren't shown in search results so I have to either find them by scrolling/zooming the map or by choosing from bookmarks lists.

It would be nice to see bookmarks in search results. Things to note:
1. As there's no object icons in results yet, bookmarks should be identified with type "Bookmark". When #2066 will be ready, bookmark icon should be shown as it is in bookmarks list;
2.  Bookmarks should be placed on the top of results. Although I'm not sure about this 'cause I saw that some users have hundreds of bookmarks in every of the tens of bookmarks lists (hard to imagine why 🙂)

**Comment by biodranik** [comment]
Aren't there already some similar existing issues?

**Comment by PetbkA** [comment]
> Aren't there already some similar existing issues?

Didn't find one, except #2066 which is about adding icons to results, not bookmarks

**Comment by biodranik** [comment]
#808 ?

**Comment by PetbkA** [comment]
> #808 ?

Indeed, sorry 🙂
