### ISSUE TITLE
[Editor]: add word wrapping

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#2721]
Some lengthy website addresses etc [aren't word-wrapped](https://user-images.githubusercontent.com/22843816/173226628-063151a3-13da-48ed-a2ed-c2841443c484.png), and it isn't very convenient to edit them.

It would be nice if editor fields would have word wrapping

**Comment by iuvenis** [comment]
Decided to give this a try for my first pull request. Let me know if I missed anything in the contribution guidelines.
