### ISSUE TITLE
[UI][POI card]: show phones / sites / social networks / coordinates as icons instead of icons+texts

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#2729]
Right now POI card is pretty lengthy 'cause phone numbers, website, social networks and coordinates are being showed as _icon + text_, each on the separate line. I doubt that it's necessary 'cause user will rather tap them to call/open the address/send e-mail than read it.

**I suggest to rework it to something similar to [Yandex.Maps](https://yandex.ru/maps):**
1. Show them as icons arranged in one line;
2. Tapping on the phone/site/e-mail icon will open the phone/browser/e-mail client app;
3. If several phones are available - tapping on the phone icon will open the list of numbers from which user can choose which one to call;
4. Tapping on the coordinates icon will show "copy" list of coordinates of different types (as it's now for long tap on the coordinates).

**Questions to be raised:**
1. Copying implementation. I see the following logic:
    1. Long tapping the icon will always copy the data if the only "instance" of it is available;
    2. If e.g. several phones will be available, copying them will be possible by:
        1. Long tapping on the icon → tapping on the certain phone from the list (as it's now for coordinates);
        2. Tapping on the icon → long tapping on the certain phone (tap will trigger calls app);
2. Whether coordinates should be turned to icon. IMHO there's no benefit from always showing it, but someone would think it is and it's better to keep the old UI for then;
3. How to align the icons. IMHO it's better to align to the right (or to the left if OM supports left-handed UI), although the most "cute" way is to always align to the left as the opening hours icon will always be on the left.

**Eventually it should turn to something like this:**
![Rework POI Info](https://user-images.githubusercontent.com/22843816/173366719-869586e4-fffb-4893-bcc0-2c7c354dce0e.png)

**Comment by strump** [comment]
Maybe we should add grey icon on the left. E.g.
![58427A53-E4C6-48D9-A9E5-D73E6748EBAC](https://user-images.githubusercontent.com/720808/173431388-6203489c-e669-4cd5-a1af-e6ff8d07ad1d.jpeg)

Don’t forget that on long tap on Instagram username you will see menu with two options: ‘techmuseum_ptz’ and ‘https://instagram.com/techmuseum_ptz’.

**Comment by biodranik** [comment]
For some people, icons are not too intuitive, especially unknown ones. And it's easier to press a cell than a button.
