### ISSUE TITLE
Icons line

### ISSUE THREAD

**Issue by gtrus21** [organicmaps/organicmaps#2735]
Прошу заменить кучу строк с контактными данными единой полоской иконок. Пользователю не интересны конкретные адреса, он просто будет нажимать на нужную кнопку для перехода на сайт. При необходимости долгое удержание позволит посмотреть или скопировать данные
![IMG_20220614_095224](https://user-images.githubusercontent.com/69676792/173513404-d2fc662f-5cd1-4773-a4f1-b39190bb1e3b.jpg)
![IMG_20220614_095547_1](https://user-images.githubusercontent.com/69676792/173513415-f81efe72-0af9-4611-9dc2-cd61eb676005.jpg)

**Comment by vng** [comment]
Same as https://github.com/organicmaps/organicmaps/issues/2729 ?

**Comment by gtrus21** [comment]
Yes
