### ISSUE TITLE
building maps either freezes system or fails

### ISSUE THREAD

**Issue by patrickgra** [organicmaps/organicmaps#2736]
Hi, I want to build the maps by myself, but I'm either getting an error or my system freezes completely. I tried it on a Linux machine, in a VM and with wsl.
For example while building the Germany_Berlin map `CHECK(currentPolygon.IsValid())` fails with:

TID(1) ASSERT FAILED
generator/borders.cpp:157
CHECK(currentPolygon.IsValid()) Invalid region in /mnt/e/Arbeit/OrganicMaps/build-maps/2022_06_14__11_14_45/intermediate_data/borders/Germany_Berlin.poly
 0# 0x000055843C82F020 in /mnt/e/Arbeit/OrganicMaps/omim-build-release/generator_tool
 1# 0x00007F1B66D53090 in /lib/x86_64-linux-gnu/libc.so.6
 2# gsignal in /lib/x86_64-linux-gnu/libc.so.6
 3# abort in /lib/x86_64-linux-gnu/libc.so.6
 4# 0x000055843C7A61DD in /mnt/e/Arbeit/OrganicMaps/omim-build-release/generator_tool
 5# 0x000055843C987240 in /mnt/e/Arbeit/OrganicMaps/omim-build-release/generator_tool
 6# 0x000055843C98AD35 in /mnt/e/Arbeit/OrganicMaps/omim-build-release/generator_tool
 7# 0x000055843C9F5075 in /mnt/e/Arbeit/OrganicMaps/omim-build-release/generator_tool
 8# 0x000055843C9F7F9A in /mnt/e/Arbeit/OrganicMaps/omim-build-release/generator_tool
 9# 0x000055843C890D2A in /mnt/e/Arbeit/OrganicMaps/omim-build-release/generator_tool
10# 0x000055843C898ED9 in /mnt/e/Arbeit/OrganicMaps/omim-build-release/generator_tool
11# 0x000055843C8201C6 in /mnt/e/Arbeit/OrganicMaps/omim-build-release/generator_tool
12# 0x000055843C7FB809 in /mnt/e/Arbeit/OrganicMaps/omim-build-release/generator_tool
13# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
14# 0x000055843C81F25E in /mnt/e/Arbeit/OrganicMaps/omim-build-release/generator_tool
Aborted

[generation.log](https://github.com/organicmaps/organicmaps/files/8899009/generation.log)

The osm file should be file. Do you have any tips? What setup are u guys using for building?

**Comment by vng** [comment]
- How did you run the toolchain? Try to add skip coastlines like this:
```
python3.6 -m maps_generator --countries="Germany_Berlin" --skip="Coastline"
```
- Is your borders folder empty? "/mnt/e/Arbeit/OrganicMaps/build-maps/2022_06_14__11_14_45/intermediate_data/borders"
- Please, let me see your map_generator.ini file

**Comment by patrickgra** [comment]
> * How did you run the toolchain? Try to add skip coastlines like this:
> 
> ```
> python3.6 -m maps_generator --countries="Germany_Berlin" --skip="Coastline"
> ```
I've seen this tip somewhere and have been running it exactly like that.

> * Is your borders folder empty? "/mnt/e/Arbeit/OrganicMaps/build-maps/2022_06_14__11_14_45/intermediate_data/borders"

The folder isnt empty but the files are.

> * Please, let me see your map_generator.ini file

```
[Main]
# If the flag DEBUG is set a special small planet file will be downloaded.
DEBUG: 0
# The path where the planet will be downloaded and the maps are generated.
MAIN_OUT_PATH: /mnt/e/Arbeit/OrganicMaps/build-maps
# The path where caches for nodes, ways, relations are stored.
# CACHE_PATH:


[Developer]
# The path where the generator_tool will be searched.
BUILD_PATH: /mnt/e/Arbeit/OrganicMaps/omim-build-release
# The path to the project directory omim.
OMIM_PATH: /mnt/e/Arbeit/OrganicMaps/organicmaps


[Generator tool]
# The path to the omim/data.
USER_RESOURCE_PATH: ${Developer:OMIM_PATH}/data
# Do not change it. This is determined automatically.
# NODE_STORAGE: map


[Osm tools]
# The path to the osmctools sources.
OSM_TOOLS_SRC_PATH: ${Developer:OMIM_PATH}/tools/osmctools
# The path where osmctools will be searched or will be built.
OSM_TOOLS_PATH:/mnt/e/Arbeit/OrganicMaps/organicmaps/osmctools


[Stages]
# Run osmupdate tool for planet.
NEED_PLANET_UPDATE: 0
# Auto detection.
THREADS_COUNT_FEATURES_STAGE: 0
# If you want to calculate diffs, you need to specify, where old maps are
DATA_ARCHIVE_DIR: ${Generator tool:USER_RESOURCE_PATH}
# You may specify, how many versions in the archive to use for diff calculation
DIFF_VERSION_DEPTH: 2


[Logging]
# The path where maps_generator log will be saved.
# LOG_FILE_PATH: generation.log


[External]
# Note: If you want to set a directory name you have to add "/" to the end of url.

# The url to the planet file.
PLANET_URL: file:///mnt/e/Arbeit/OrganicMaps/osm-pbfs/germany-latest.osm.pbf
# The url to the file with md5 sum of the planet.
PLANET_MD5_URL: file:///mnt/e/Arbeit/OrganicMaps/osm-pbfs/germany-latest.osm.pbf.md5
# The base url to WorldCoasts.geom and WorldCoasts.rawgeom (without file name).
# Files latest_coasts.geom and latest_coasts.rawgeom must be at this URL.
# For example, if PLANET_COASTS_URL = https://somesite.com/download/
# The https://somesite.com/download/latest_coasts.geom url will be used to download latest_coasts.geom and
# the https://somesite.com/download/latest_coasts.rawgeom url will be used to download latest_coasts.rawgeom.
PLANET_COASTS_URL: file:///mnt/e/Arbeit/OrganicMaps/coasts
# Set to 'true' to build special routing section in World.mwm for alerting about absent regions without which the
# route can't be built.
NEED_BUILD_WORLD_ROADS: true
# The url to the subway file.
SUBWAY_URL: http://osm-subway.maps.me/mapsme/latest.json

# The url of the location with the transit files extracted from GTFS.
# TRANSIT_URL:

# Urls for production maps generation.
# UGC_URL:
# HOTELS_URL:
# PROMO_CATALOG_CITIES:
# POPULARITY_URL:
# FOOD_URL:
# FOOD_TRANSLATIONS_URL:
# SRTM_PATH:
# ISOLINES_PATH:
# UK_POSTCODES_URL:
# US_POSTCODES_URL:


[Common]
# Auto detection.
THREADS_COUNT: 0


[Stats]
# Path to rules for calculating statistics by type
STATS_TYPES_CONFIG: ${Developer:OMIM_PATH}/tools/python/maps_generator/var/etc/stats_types_config.txt


```

**Comment by vng** [comment]
- Hm, but logs say that you have enabled "Coastline"
- Does Germany_Berlin.poly file present in "/mnt/e/Arbeit/OrganicMaps/build-maps/2022_06_14__11_14_45/intermediate_data/borders"?

**Comment by patrickgra** [comment]
The thing is I've run it with multiple constellations of settings and cities and I've deleted most of the build files. I've started another run with the instruction you proposed and I'd update you with the specific .log and files after it crashes. 
But in the other 2 runs I've tested last, the .poly files are present but are 0KB big however none of my editors can open them.

**Comment by vng** [comment]
In xxx/intermediate_data/borders/ folder should present symlinks (not real files) to the original *.poly files from USER_RESOURCE_PATH (in your case /mnt/e/Arbeit/OrganicMaps/organicmaps/data/borders/)

**Comment by patrickgra** [comment]
Seems like the symlinks aren't working properly then. I've checked the properties of the file and the directory with cmd and it seems like Germany_Berlin.poly is a junction with destination "[...]".

**Comment by vng** [comment]
Do you run on Linux environment or any other?

If you familiar a bit with python, check that function setup_borders from ./tools/python/maps_generator/generator/env.py works properly (add logs?) while running generator script.

**Comment by patrickgra** [comment]
Right now I'm on windows and using wsl. That path is the from the linux subsystem accessing the harddrive mounted in windows.
Thats the .log from the last run mentioned above.
[generation.log](https://github.com/organicmaps/organicmaps/files/8927365/generation.log)

> If you familiar a bit with python, check that function setup_borders from ./tools/python/maps_generator/generator/env.py works properly (add logs?) while running generator script.
>
I can boot into a proper Linux and check it there. It wasn't working there as well.

**Comment by patrickgra** [comment]
It seems to be a problem with symlinks between Windows and wsl. From what I found theyre only working on the system they were created with. I'll boot into Linux and start a run.

**Comment by patrickgra** [comment]
Well as it seems that was the problem and I guess I wont be able to run it with wsl.


I switched to my Linux machine and I've run:
`python3 -m maps_generator --countries="Germany_Berlin" --skip="Coastline"`

with the ini:
```
[Main]
# If the flag DEBUG is set a special small planet file will be downloaded.
DEBUG: 0
# The path where the planet will be downloaded and the maps are generated.
MAIN_OUT_PATH: ~/arbeit/created-maps
# The path where caches for nodes, ways, relations are stored.
# CACHE_PATH:


[Developer]
# The path where the generator_tool will be searched.
BUILD_PATH: ~/arbeit/omim-build-release
# The path to the project directory omim.
OMIM_PATH: ~/arbeit/organicmaps


[Generator tool]
# The path to the omim/data.
USER_RESOURCE_PATH: ${Developer:OMIM_PATH}/data
# Do not change it. This is determined automatically.
# NODE_STORAGE: map


[Osm tools]
# The path to the osmctools sources.
OSM_TOOLS_SRC_PATH: ${Developer:OMIM_PATH}/tools/osmctools
# The path where osmctools will be searched or will be built.
OSM_TOOLS_PATH: ~/arbeit/organicmaps/osmctools


[Stages]
# Run osmupdate tool for planet.
NEED_PLANET_UPDATE: 0
# Auto detection.
THREADS_COUNT_FEATURES_STAGE: 0
# If you want to calculate diffs, you need to specify, where old maps are
DATA_ARCHIVE_DIR: ${Generator tool:USER_RESOURCE_PATH}
# You may specify, how many versions in the archive to use for diff calculation
DIFF_VERSION_DEPTH: 2


[Logging]
# The path where maps_generator log will be saved.
# LOG_FILE_PATH: ~/arbeit/generation.log


[External]
# Note: If you want to set a directory name you have to add "/" to the end of url.

# The url to the planet file.
PLANET_URL: file:///home/patrick/arbeit/map-pbfs/germany-latest.osm.pbf
# The url to the file with md5 sum of the planet.
PLANET_MD5_URL: file:///home/patrick/arbeit/map-pbfs/germany-latest.osm.pbf.md5
# The base url to WorldCoasts.geom and WorldCoasts.rawgeom (without file name).
# Files latest_coasts.geom and latest_coasts.rawgeom must be at this URL.
# For example, if PLANET_COASTS_URL = https://somesite.com/download/
# The https://somesite.com/download/latest_coasts.geom url will be used to download latest_coasts.geom and
# the https://somesite.com/download/latest_coasts.rawgeom url will be used to download latest_coasts.rawgeom.
# PLANET_COASTS_URL:
# Set to 'true' to build special routing section in World.mwm for alerting about absent regions without which the
# route can't be built.
NEED_BUILD_WORLD_ROADS: true
# The url to the subway file.
SUBWAY_URL: http://osm-subway.maps.me/mapsme/latest.json

# The url of the location with the transit files extracted from GTFS.
# TRANSIT_URL:

# Urls for production maps generation.
# UGC_URL:
# HOTELS_URL:
# PROMO_CATALOG_CITIES:
# POPULARITY_URL:
# FOOD_URL:
# FOOD_TRANSLATIONS_URL:
# SRTM_PATH:
# ISOLINES_PATH:
# UK_POSTCODES_URL:
# US_POSTCODES_URL:


[Common]
# Auto detection.
THREADS_COUNT: 0


[Stats]
# Path to rules for calculating statistics by type
STATS_TYPES_CONFIG: ${Developer:OMIM_PATH}/tools/python/maps_generator/var/etc/stats_types_config.txt
```

on my Linux machine and the task got killed with:
```
LOG TID(1) INFO   1.1116e-05 generator/intermediate_data.cpp:190 MapFilePointStorageReader() Nodes reading is started
LOG TID(1) INFO      157.092 generator/intermediate_data.cpp:207 MapFilePointStorageReader() Nodes reading is finished
LOG TID(1) INFO      157.639 Offsets reading is started for file /home/patrick/arbeit/created-maps/2022_06_17__14_37_53/intermediate_data/ways.dat.offs
Killed
```
The symlink here is at least working.
The log:
[generation.log](https://github.com/organicmaps/organicmaps/files/8928486/generation.log)

**Comment by vng** [comment]
Please, attach /home/patrick/arbeit/created-maps/2022_06_17__14_37_53/logs/Features.log file here.

**Comment by patrickgra** [comment]
[Features.log](https://github.com/organicmaps/organicmaps/files/8929382/Features.log)

**Comment by vng** [comment]
How much RAM do you have on your computer?

**Comment by patrickgra** [comment]
16gb

**Comment by vng** [comment]
Can't say for sure is it ok or not. Log is not very informative but I suspect that process killed because of memory.
Could you please download Berlin only pbf from download geofabrik.de and run generator tool on it?

**Comment by patrickgra** [comment]
That worked. So the takeaway seems to be building maps works only on Linux (or pure Windows if somebody figures out the dependicies) and with a decent amount of RAM for bigger base maps. I think that this could be worth adding to the readme.
Thank you for your help and patience.
