### ISSUE TITLE
[android] Replace com.timehop.stickyheadersrecyclerview and disable jetifier

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#2737]
The [`com.timehop.stickyheadersrecyclerview`](https://github.com/timehop/sticky-headers-recyclerview) library is not maintained (last updated in 2016) and is based on the support library still (which is deprecated in favor of androidx).
Its being used in OM's `DownloaderAdapter` class.

Looks like its the last library that prevents us to disable the [jetifier](https://developer.android.com/jetpack/androidx/migrate).

Maybe modern RecyclerVIew has this functionality built-in already or could be implemented with a little of our own code?
If its too hard then find an actively maintained replacement lib based on androidx.

**Comment by strump** [comment]
Other option - copy [sticky-headers-recyclerview](https://github.com/timehop/sticky-headers-recyclerview) code to OM repo and maintain ourselves.

**Comment by biodranik** [comment]
There are several possible implementations:
https://stackoverflow.com/questions/32949971/how-can-i-make-sticky-headers-in-recyclerview-without-external-lib
https://medium.com/swlh/android-recyclerview-stickyheader-without-external-library-25845ec3e20f

Another library https://github.com/shuhart/StickyHeader

Avoiding external library dependency while using the most lightweight implementation is the best way to go IMO.

CC @arnaudvergnet

**Comment by arnaudvergnet** [comment]
A custom sticky header implementation seems the best option. But are those sticky headers really necessary? I did not notice them prior to looking at the code. I would completely remove them.

**Comment by pastk** [comment]
I thought they're used in bookmarks lists (e.g. sorted by type or date), but no (or is it broken?).

So I don't know where are they used if used at all :)

**Comment by strump** [comment]
https://user-images.githubusercontent.com/720808/174290355-5091ca0d-6e8e-4168-939f-6f93d16614e6.mp4

AFAIK, sticky headers are used in available maps list.
1. Open "Download Maps"
2. Click "+" button
3. You see list with sticky headers.

**Comment by arnaudvergnet** [comment]
But using sticky headers here is not that useful. I mean you can clearly see you are looking at countries starting with M because they all start with M, no need to be reminded by the sticky header.

**Comment by pastk** [comment]
Yeap I think no point to keep sticky headers implementation around just for this.
They could be more useful for bookmarks sorting though for people who have lots of bookmarks.

**Comment by biodranik** [comment]
They could be useful if clicking on them would scroll to the beginning of a long list, for example. At the moment they can simply be removed.

**Comment by pastk** [comment]
Yep for now its best just to remove them.
We can add an implementation later if we'll really need them.

**Comment by Jean-BaptisteC** [comment]
Fixed by https://github.com/organicmaps/organicmaps/pull/4701
