### ISSUE TITLE
Map layers button active in navigation mode

### ISSUE THREAD

**Issue by siiky** [organicmaps/organicmaps#2742]
While in navigation mode, the map layers button of the top left is still active, even though it's covered by the "next direction" squarish thingy.

This is on Android, Organic Maps 2022.05.31-10-FDroid, happens at least with car and pedestrian navigation.

**Comment by arnaudvergnet** [comment]
Duplicate of https://github.com/organicmaps/organicmaps/issues/1655

**Comment by siiky** [comment]
Ah indeed. I didn't even try looking for a similar issue because they told me to open it on Telegram. Won't happen next time.

**Comment by arnaudvergnet** [comment]
No problem, at least we know more people noticed the issue.

**Comment by biodranik** [comment]
@siiky we don't always remember all issues )
