### ISSUE TITLE
Create and add missing icons for the tag "Craft="

### ISSUE THREAD

**Issue by ooprizrakoo** [organicmaps/organicmaps#2748]
OM-app contains information about the most common variants of tag "craft= "
(информация отсюда: https://github.com/organicmaps/organicmaps/blob/master/data/classificator.txt#L207 )

    craft  +
        beekeeper  -
        blacksmith  -
        brewery  -
        carpenter  -
        confectionery  -
        electrician  -
        electronics_repair  -
        gardener  -
        handicraft  -
        hvac  -
        metal_construction  -
        painter  -
        photographer  -
        plumber  -
        sawmill  -
        shoemaker  -
        tailor  -
        winery  -
        {}

Now these icons are not displayed in the current version. Only duplicated house numbers are displayed - without icons "craft=...", or just the same  "hand palm" icon, looks like a stop sign, for the all types of Craft= POI.
![image](https://user-images.githubusercontent.com/661813/173852014-310c9676-4c11-4a53-a8af-256d5f21288d.png)

It is suggested to find suitable icons for these 18 types of tag, and add them to the application.

Resources:
for example, as an option:
https://materialdesignicons.com/icon/storefront-outline
 
Current icons: 
https://github.com/organicmaps/organicmaps/tree/master/data/styles/clear/style-clear/symbols
Dark-style:
https://github.com/organicmaps/organicmaps/tree/master/data/styles/clear/style-night/symbols

**Comment by dvdmrtnz** [comment]
Here are the top 20 most used tags of [craft=*](https://taginfo.openstreetmap.org/keys/craft) from taginfo. Also two additional ones that are currently used in Organic Maps.

| Top | Tag | Usage | [Icon](https://github.com/organicmaps/organicmaps/blob/master/data/styles/clear/include/Icons.mapcss) | [Strings](https://github.com/organicmaps/organicmaps/blob/master/data/strings/types_strings.txt) | [Categories](https://github.com/organicmaps/organicmaps/blob/master/data/categories.txt) |
|-|-|-|-|-|-|
| 1 | [craft=grinding_mill](https://taginfo.openstreetmap.org/tags/craft=grinding_mill) | 38 604 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | No | No
| 2 | [craft=carpenter](https://taginfo.openstreetmap.org/tags/craft=carpenter) | 15 948 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 3 | [craft=metal_construction](https://taginfo.openstreetmap.org/tags/craft=metal_construction) | 11 430 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 4 | [craft=winery](https://taginfo.openstreetmap.org/tags/craft=winery) | 11 068 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 5 | [craft=photographer](https://taginfo.openstreetmap.org/tags/craft=photographer) | 9 607 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 6 | [craft=electrician](https://taginfo.openstreetmap.org/tags/craft=electrician) | 9 333 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 7 | [craft=shoemaker](https://taginfo.openstreetmap.org/tags/craft=shoemaker) | 9 170 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 8 | [craft=tailor](https://taginfo.openstreetmap.org/tags/craft=tailor) | 8 905 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 9 | [craft=brewery](https://taginfo.openstreetmap.org/tags/craft=brewery) | 8 763 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 10 | [craft=electronics_repair](https://taginfo.openstreetmap.org/tags/craft=electronics_repair) | 8 760 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 11 | [craft=sawmill](https://taginfo.openstreetmap.org/tags/craft=sawmill) | 7 618 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 12 | [craft=plumber](https://taginfo.openstreetmap.org/tags/craft=plumber) | 7 615 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/plumber-m.svg) | Yes | Yes
| 13 | [craft=hvac](https://taginfo.openstreetmap.org/tags/craft=hvac) | 6 492 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 14 | [craft=caterer](https://taginfo.openstreetmap.org/tags/craft=caterer) | 6 436 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | No | No
| 15 | [craft=window_construction](https://taginfo.openstreetmap.org/tags/craft=window_construction) | 5 672 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | No | No
| 16 | [craft=confectionery](https://taginfo.openstreetmap.org/tags/craft=confectionery) | 5 152 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 17 | [craft=gardener](https://taginfo.openstreetmap.org/tags/craft=gardener) | 4 729 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 18 | [craft=handicraft](https://taginfo.openstreetmap.org/tags/craft=handicraft) | 4 596 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 19 | [craft=beekeeper](https://taginfo.openstreetmap.org/tags/craft=beekeeper) | 4 424 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 20 | [craft=stonemason](https://taginfo.openstreetmap.org/tags/craft=stonemason) | 4 213 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | No | No
| 23 | [craft=painter](https://taginfo.openstreetmap.org/tags/craft=painter) | 4 115 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes
| 28 | [craft=blacksmith](https://taginfo.openstreetmap.org/tags/craft=blacksmith) | 2 805 | ![](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hand-m.svg) | Yes | Yes

**Comment by dvdmrtnz** [comment]
I think we could reuse some of the existing icons for some of the craft types. For example:

| Tag | Icon |
|-|-|
| [craft=photografer](https://taginfo.openstreetmap.org/tags/craft=photographer) | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/photo-shop-m.svg" width="30" /> |
| [craft=shoemaker](https://taginfo.openstreetmap.org/tags/craft=shoemaker) | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/shoes-m.svg" width="30" /> |
| [craft=confectionery](https://taginfo.openstreetmap.org/tags/craft=confectionery) | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/sweets-m.svg" width="30" /> |
| [craft=gardener](https://taginfo.openstreetmap.org/tags/craft=gardener) | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/florist-m.svg" width="30" /> |

**Comment by yaslack** [comment]
hi created this one for metal_constructuon what do you think ?

![metal-construction](https://user-images.githubusercontent.com/73611344/204680017-ddcb01c1-9681-4d6a-a867-b0a8326ac5ef.svg)

**Comment by biodranik** [comment]
Try to reduce it to 18x18 pixels, draw it on the map together with other icons in Light and Dark styles, and you'll understand yourself.

**Comment by DounekoKai** [comment]
Hello I am new contributor, I propose these images for the "craft=winery" what do you think?
clear 24x24 pixel:
![test1-clear](https://user-images.githubusercontent.com/116730993/204818151-c56c4558-ca81-4ed5-948a-3895b96bfd25.svg)![test2-clear](https://user-images.githubusercontent.com/116730993/204818174-6ab88d5a-5f59-41b3-ac7f-fdbef7d6f03e.svg)![test3-clear](https://user-images.githubusercontent.com/116730993/204818205-6809863e-b99e-4be1-ad67-4ada3f04effe.svg)

dark 24x24 pixel:
![test1-dark](https://user-images.githubusercontent.com/116730993/204818239-76a0ee1a-c6c6-4345-83f0-1bfe4caa992d.svg)![test2-dark](https://user-images.githubusercontent.com/116730993/204818265-789b6c24-cf8a-4856-b09f-1da07b101dd4.svg)![test3-dark](https://user-images.githubusercontent.com/116730993/204818348-4a5c3bb6-232c-4c87-8376-46764ef3a51a.svg)

**Comment by biodranik** [comment]
Can you please use colors that are used in Organic Maps Dark and Light modes? Did you see the app and its current icons? Also, check it with an 18x18 pixels size.

**Comment by yaslack** [comment]
hi, i finally correctly made the metal cponstuction one unfortunately i don't seem to make them appear when i build (even after editing the map), here they are : 
![metal_construction_night](https://user-images.githubusercontent.com/73611344/214180853-255c723b-3552-4014-90d3-f63ca63ee6b9.svg)
![metal_construction](https://user-images.githubusercontent.com/73611344/214180855-e1d14d7c-0158-4477-8db4-24079e53f636.svg)

**Comment by yaslack** [comment]
hi, i finally correctly made the metal cponstuction one unfortunately i don't seem to make them appear when i build (even after editing the map), here they are : 

![metal_construction_night](https://user-images.githubusercontent.com/73611344/214183607-9bf5185a-4b31-4044-88eb-f0301a47eea0.svg)
![metal_construction](https://user-images.githubusercontent.com/73611344/214183636-bf1228fb-a6f1-47da-9648-d720f5eaf783.svg)

**Comment by DounekoKai** [comment]
hello Biodranik, I modified the colors of the icons so that it complies with the colors Organic Maps Dark and Light modes

Light icon
![Grape](https://user-images.githubusercontent.com/116730993/223718903-6d4897ad-752e-4d73-a59c-7bd8a87ec3dc.svg)
Dark icon:
![Grape-Night](https://user-images.githubusercontent.com/116730993/223718933-742ce41d-0677-4fdc-9f8e-078af01c7994.svg)

**Comment by biodranik** [comment]
Thanks! Your first version with a leaf was better ;-)

**Comment by dvdmrtnz** [comment]
I propose this simplified icon for `craft=winery` following the style of @DounekoKai's icon:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/550d4c79-87ab-49b6-b7d5-07a892ec5c7b" width="35"/>

**Comment by dvdmrtnz** [comment]
Proposal for [`craft=caterer`](https://wiki.openstreetmap.org/wiki/Tag:craft%3Dcaterer):

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/b6666ed9-48d7-4fe6-bfc4-6ef60efae57f" width="36"/>

**Comment by pastk** [comment]
> Proposal for [`craft=caterer`](https://wiki.openstreetmap.org/wiki/Tag:craft%3Dcaterer):
> <img alt="" width="36" src="https://user-images.githubusercontent.com/47610359/267782460-b6666ed9-48d7-4fe6-bfc4-6ef60efae57f.svg">

I get the idea, but it resembles a hat also  :)

**Comment by dvdmrtnz** [comment]
Proposal for [`craft=handicraft`](https://wiki.openstreetmap.org/wiki/Tag:craft%3Dhandicraft):

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/8322d20e-97d4-467f-9aa4-8687df20b285" width="36"/>

**Comment by dvdmrtnz** [comment]
> > Proposal for [`craft=caterer`](https://wiki.openstreetmap.org/wiki/Tag:craft%3Dcaterer):
> > <img alt="" width="36" src="https://user-images.githubusercontent.com/47610359/267782460-b6666ed9-48d7-4fe6-bfc4-6ef60efae57f.svg">
> 
> I get the idea, but it resembles a hat also :)

I see 😂

Maybe it's better like this:


<img src="https://github.com/organicmaps/organicmaps/assets/47610359/c77bf756-b510-4d2f-b87b-cfb628d73ecf" width="36"/>

**Comment by dvdmrtnz** [comment]
Proposal for [`craft=grinding_mill`](https://wiki.openstreetmap.org/wiki/Tag:craft%3Dgrinding_mill):

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/ed3bdae6-dea7-4db3-92a5-bb651a0cb381" width="36"/>

**Comment by pastk** [comment]
> Proposal for [`craft=grinding_mill`](https://wiki.openstreetmap.org/wiki/Tag:craft%3Dgrinding_mill):
> <img alt="" width="36" src="https://user-images.githubusercontent.com/47610359/268189150-ed3bdae6-dea7-4db3-92a5-bb651a0cb381.svg">

My first impression was - a thrash bin with a cog wheel :)
It doesn't resemble a house... Maybe a more sharp roof traditional for windmills?

**Comment by dvdmrtnz** [comment]
> > Proposal for [`craft=grinding_mill`](https://wiki.openstreetmap.org/wiki/Tag:craft%3Dgrinding_mill):
> > <img alt="" width="36" src="https://user-images.githubusercontent.com/47610359/268189150-ed3bdae6-dea7-4db3-92a5-bb651a0cb381.svg">
> 
> My first impression was - a thrash bin with a cog wheel :) It doesn't resemble a house... Maybe a more sharp roof traditional for windmills?

How about like this:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/d2d7121b-96fa-465d-8e30-d8a009f58170" width="36"/>

**Comment by dvdmrtnz** [comment]
All main `craft=*` icons have been added. I will close this issue now. If any other specific `craft` icon is required, a separate issue can be opened.
