### ISSUE TITLE
better icon for information=guidepost

### ISSUE THREAD

**Issue by j13m126** [organicmaps/organicmaps#2752]
Right now there is a single icon 🛈 for [tourism=information](https://wiki.openstreetmap.org/wiki/Key:information) (#1919)
I'd like to find better icon for information=guidepost and also information=map/board

Here are some examples I found for information=guidepost
1. [openstreetmap](https://wiki.openstreetmap.org/wiki/File:Guidepost-14.svg)
![Bildschirmfoto vom 2022-06-16 00-41-47](https://user-images.githubusercontent.com/7961926/173955806-70cbc424-90d9-4f57-99e4-be933cf4d0d6.png)![Bildschirmfoto vom 2022-06-16 00-42-09](https://user-images.githubusercontent.com/7961926/173955812-0cc051a0-77de-4648-8aeb-d3beb85b80e9.png)
2. [boxicons](https://boxicons.com/?query=directions)
![Bildschirmfoto vom 2022-06-16 00-33-26](https://user-images.githubusercontent.com/7961926/173955914-68faa9dc-13c8-4462-a11a-ea623b37bb84.png)![Bildschirmfoto vom 2022-06-16 00-33-42](https://user-images.githubusercontent.com/7961926/173955918-30b30482-2278-4566-9966-8c3acacae61e.png)
3. [boxicons](https://boxicons.com/?query=directions)
![Bildschirmfoto vom 2022-06-16 00-36-39](https://user-images.githubusercontent.com/7961926/173955989-d9af9cd2-464d-49a1-8f78-283930c2f945.png)![Bildschirmfoto vom 2022-06-16 00-36-54](https://user-images.githubusercontent.com/7961926/173955991-27667186-1aaa-439c-ba76-1b72a4843e1d.png)
4. [material](https://fonts.google.com/icons?icon.set=Material+Icons&icon.query=signpost)
![Bildschirmfoto vom 2022-06-16 00-39-36](https://user-images.githubusercontent.com/7961926/173956168-f6e3b8a5-20fc-4ca0-9c52-20abeac240b9.png)![Bildschirmfoto vom 2022-06-16 00-39-19](https://user-images.githubusercontent.com/7961926/173956163-41b178e9-5323-4a22-b06f-c317bb234783.png)
I personally like 1. and 4. What do you think?

**Comment by biodranik** [comment]
1 is ok )
