### ISSUE TITLE
cycleway=no + highway=* should be bike-routable

### ISSUE THREAD

**Issue by skfd** [organicmaps/organicmaps#276]
`cycleway:both=no` just means there is no dedicated cycleway, so riders use common road. 

This tag is excessive, but valid and it is a product of one of StreetComplete's quests.

Thank you!

**Comment by FinixFighter** [comment]
I think this should be reported to OSRM and/or GraphHopper. I don't know which of these two OMaps uses.

**Comment by biodranik** [comment]
No, it's in our code. @skfd can you please provide some map/osm examples where we can test that?
Maybe you can check the code and suggest a fix? `routing_common/bicycle_model.cpp` may be a good starting point.

**Comment by skfd** [comment]
Ok, it might not be caused by these tags. Here are two routes [one working](https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=50.42399%2C30.60409%3B50.42349%2C30.60334) and [one failing for bike](https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=50.42399%2C30.60409%3B50.42338%2C30.60336) (it still builds works for car and foot).

I don't see anything obvi wrong with data here...

**Comment by Jean-BaptisteC** [comment]
Works on 2023.08.18-8-Google
