### ISSUE TITLE
contact:facebook does not show on iOS

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#2762]
So apparently on Android, `contact:facebook` is used to render Facebook tags, as shown here: ![image](https://user-images.githubusercontent.com/50059322/174197195-8efc6c26-a992-4ad8-bb66-73babb962ffd.jpeg)

However, when looking at the exact same place on iOS, the Facebook section is not shown:![image](https://user-images.githubusercontent.com/50059322/174197475-8824566d-0f22-4eaa-b19d-52dd161f9c46.png)

**Comment by biodranik** [comment]
Several social networks were added to Android in #1196, iOS version should be synced too.
