### ISSUE TITLE
Return interface localization

### ISSUE THREAD

**Issue by ioctl-user** [organicmaps/organicmaps#278]
Omaps loose interface localization, that was in Maps.me.

Could you return it back?

**Comment by biodranik** [comment]
@ioctl-user What exactly is missing?

**Comment by ioctl-user** [comment]
Everything, there is no translation at all. See MAPS.ME and OMaps screenshots as example:
![maps_me](https://user-images.githubusercontent.com/23457638/113443499-c881f800-93fa-11eb-8acc-a315c1c63110.png)
![OMaps](https://user-images.githubusercontent.com/23457638/113443520-d172c980-93fa-11eb-9da8-85c17f435732.png)

**Comment by biodranik** [comment]
Thanks for reporting that. What is your system language(s)? In what order?

**Comment by ioctl-user** [comment]
Russian the first and the only :)

Other programs and system UI work as expected.

**Comment by biodranik** [comment]
Did you build the app yourself, or launched it from the TestFlight?

**Comment by ioctl-user** [comment]
I have installed it from Google Market with Aurora app.

**Comment by rtsisyk** [comment]
I will check on a device.

**Comment by rtsisyk** [comment]
![Screenshot_20210403-165107_OMapsdebug.jpg](https://user-images.githubusercontent.com/1799054/113480454-f3bd2380-949c-11eb-85cd-92dc8f30a707.jpg)

**Comment by rtsisyk** [comment]
OK, We will try to reproduce this problem.

**Comment by ioctl-user** [comment]
Я так понимаю, разработчики русскоговорящие? :)

При необходимости могу собрать дополнительные логи или скомпилировать и запустить версию со включённой отладкой.

p.s. Телефон без Гуглосервисов, но установлен MicroG.

**Comment by biodranik** [comment]
Может ли быть такое, что из гугла aurora скачала оптимизированную гуглом версию, где гугл оставил только английскую локаль? В aurora есть выбор языков?

**Comment by rtsisyk** [comment]
Скорее всего как-то так и было. Там нет вообще никаких гарантий, что они после скачивания не заменяют в приложении ресурсы на какие-нибудь свои и не вставляют какие-нибудь трояны.

**Comment by rtsisyk** [comment]
Давайте мы вам APK выложим на гитхаб, попробуете без этого Аврора-стора.

**Comment by ioctl-user** [comment]
Это как-то сранно. У меня куча приложений поставленных непосредственно из гугло-магазина. Например, ранее был старый maps.me, переводчик Google, телеграмм и т.п. Есть ряд приложений из других источников, там тоже всё в порядке.

Язык в настройках Авроры стоит русский, её интерфейс тоже русскоязычный.

Хм.. Что-то странное. Сейчас поставил последний maps.me, он тоже англоязычный. Похоже, проблема пришла из него.

Но телефон настроен нормально. См. снимки с разделённым экраном.

Переводчик и OMaps:
![Screenshot_20210405-100624_Переводчик](https://user-images.githubusercontent.com/23457638/113547960-6e9a5180-95f7-11eb-9bad-bce9ab31ceda.png)

Аврора и OMaps.
![Screenshot_20210405-101033_OMaps](https://user-images.githubusercontent.com/23457638/113547974-73f79c00-95f7-11eb-9d95-5444e072ac83.png)

**Comment by ioctl-user** [comment]
Fixed in version 2021.05.08-7 .
