### ISSUE TITLE
Allow amenity=parking node creation in editor

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#2781]
Right now only bicycle parkings and motorcycle parking are available

nodes for parking lots are fine, and better than nothing

**Comment by biodranik** [comment]
Creating many points for each lot could be worse than marking the whole area once.

**Comment by matkoniecz** [comment]
> Creating many points for each lot could be worse than marking the whole area once.

Yes, but in such case single one should be created for entire one. Do you think that OM users are likely to make this mistake? (or maybe they were making and it got removed)?

**Comment by biodranik** [comment]
We never enabled it, and don't know the consequences ) We may try to enable point parking in the editor and see how it goes. At the moment, most of our users are more or less educated.

**Comment by RicoElectrico** [comment]
My anecdata based on fixing MAPS.ME edits in their peak - users added a lot of obviously invalid `amenity=motorcycle_parking` to make up for the non-existent car parking preset.
