### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#2784]
Comparison between Google Maps and Organic Maps:![image](https://user-images.githubusercontent.com/50059322/174529289-9bd9ba94-2c96-4dde-840b-33796e7ba896.png)![image](https://user-images.githubusercontent.com/50059322/174529290-1d513754-0eb2-488f-82c3-e8f4e5306071.jpeg)

In this situation, the route was from Pearl City to Hawaii Kai. Organic Maps should not route you onto the exit, as it adds an additional three minutes to the route.

**Comment by vng** [comment]
Hm, this [way](https://www.openstreetmap.org/way/37450546) has motor_vehicle=no tag.
Is it a mistake or something unusual with this motorway section?

**Comment by TheAdventurer64** [comment]
> Hm, this [way](https://www.openstreetmap.org/way/37450546) has motor_vehicle=no tag.
> Is it a mistake or something unusual with this motorway section?

Fixed. Thanks for noticing this!
