### ISSUE TITLE
Automatically shortened facebook links won't allow you to save changes. 

### ISSUE THREAD

**Issue by R1123345** [organicmaps/organicmaps#2787]
When adding the facebook link of a poi and saving the change, it will shorten the link to the reference after the / (so https:/www.facebook is removed). This is fine, but if you want to re-edit the poit, it won't allow you to save your changes until you r-add the first part of the url or delete the field. 
Can anyone confirm this issue on their device?

**Comment by biodranik** [comment]
@strump can you please check it?

**Comment by R1123345** [comment]
I shared a place below where the issue still occurs. The url is different than most, maybe that is the issue. 

Dózsa György út, 108. Click this link om://04FvDIBbae/Páter_Bonifác_Vendéglő 

https://omaps.app/04FvDIBbae/Páter_Bonifác_Vendéglő

**Comment by strump** [comment]
Ok, I see Facebook page `Páter-Bonifác-Restaurant-Budapest-111001693867133` is treated as invalid by OrganicMaps.
Here’s the POI in OSM: https://osm.org/node/5961248015
I’ll fix it and update our unit-tests.

**Comment by R1123345** [comment]
Excellent. I wasn't sure if it was my app/version/device or the link.

**Comment by strump** [comment]
Hi, @R1123345 .
New OrganicMaps version released this week. Please update from Google Play, F-Droid, or Apple Store and verify is issue is fixed.

**Comment by R1123345** [comment]
The issue still persists with more lengthy facebook links.

**Comment by strump** [comment]
@R1123345  which POI you can't edit? Could you please share a link or coordinates?

**Comment by R1123345** [comment]
The following facebook link isn't working:
/pages/Daikichi-Japans-Restaurant/118163444928138
