### ISSUE TITLE
Flatpak - error while updating in fedora

### ISSUE THREAD

**Issue by digitalplaywright** [organicmaps/organicmaps#2789]
While update the Flatpak I get the error "Unable to update Organic Maps. Error Pulling from repo: GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable)". Is this an issue you are aware of?

**Comment by biodranik** [comment]
CC @Ferenc- @fgaz

**Comment by fgaz** [comment]
Works for me. iirc that's a generic flatpak issue, it happened to me on another package some time ago. I think re-adding the flathub remote fixes it

**Comment by digitalplaywright** [comment]
I updated the flatpak directly from flatpak.org and it installed with no issues. Thanks!

**Comment by digitalplaywright** [comment]
The

**Comment by fgaz** [comment]
I think this can be closed
