### ISSUE TITLE
[localisation] Marathi not visible under language options in iOS settings

### ISSUE THREAD

**Issue by sanketgarade** [organicmaps/organicmaps#2800]
Thanks for adding the Marathi localisation in the latest update, `Version: 2022.06.18-1`. 

But Marathi language is not visible under the language selection settings in iOS. Same on iPadOS. 

Screenshots from iOS below -

![image](https://user-images.githubusercontent.com/74632379/174953572-326215f4-ca02-490b-863c-ff7a422fc754.jpeg)

![image](https://user-images.githubusercontent.com/74632379/174953594-b6690584-fe52-49f1-972e-46b50020f41b.jpeg)

**Comment by sanketgarade** [comment]
It seems similar/related issue present in android as well. (I got it checked from someone else since I don't have an android device myself.)

Even though the phone language is set to Marathi and all apps display Marathi, still Organic Maps continues to display English language in its UI.

**Comment by biodranik** [comment]
Thanks for reminding us, it's easy to fix for the next release.

**Comment by sanketgarade** [comment]
Thanks for quick fix 😃
