### ISSUE TITLE
[routing][pedestrian] Bad detour.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#2803]
(41.8996055, 12.4983314) -> (41.9000141, 12.4987951)
<img width="947" alt="Screenshot 2022-06-22 at 14 41 33" src="https://user-images.githubusercontent.com/175612/175020740-c48991bd-94ce-45a3-8014-780f5fdfdbcd.png">

**Comment by vng** [comment]
Same issue on this steps: https://www.openstreetmap.org/#map=18/43.15146/77.06158

Should review diff-altitude penalty.

**Comment by Jean-BaptisteC** [comment]
@vng is it fixed ?
First case doing not bad detour in 2023.06.04-13-Google

**Comment by vng** [comment]
Fixed, see Italy_Rome_Altitude_Footway test.
