### ISSUE TITLE
"Oficina de correos" category search doesn’t work

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#2826]
When tapping on “Oficina de correos” (Post) the search shows no results, when the app is in Spanish. However when editing the search it works again. Other categories work fine. Changing the app language to English, it works fine.

https://user-images.githubusercontent.com/47610359/175782757-a8b51d49-7a99-418a-9bf2-569e7c381ba1.MOV

iPhone 8
iOS 15.4.1
Organic Maps 2022.06.16-16

**Comment by biodranik** [comment]
@pastk can you please fix it?

**Comment by pastk** [comment]
It works fine in the 2022.05.31 release, but is broken in the current master (for me even editing the search term doesn't work). `types_strings` and `categories` search term do match and haven't been changed.
I tried a few other categories and languages and could reproduce it with "Oficina de correos" only.
Could be related to #2712 @vng ?

**Comment by pastk** [comment]
BTW when it doesn't work it stops searching (no spinner) almost immediately.

But sometimes it does work actually. Looks like the most sure way to make it work is to zoom in.
