### ISSUE TITLE
Organic maps underestimates the climb when laying the route

### ISSUE THREAD

**Issue by snooppr** [organicmaps/organicmaps#2831]
Organic maps underestimates the climb significantly when plotting a route in pedestrian and bicycle mode.  Example, comparison of the same route: organic maps vs osmand. 

 In fact, I checked on many different routes, organic maps always underestimate the climb.

![osmand vs organic](https://user-images.githubusercontent.com/61022210/175820343-e1bce044-2f2a-42e5-8f77-92094461eaef.jpg)

**Comment by biodranik** [comment]
You compare different values. OM shows _a difference_ between the lowest and highest elevation point. OSMand shows the sum of all ascents and descents. There probably was an issue to show the same in OM, but if not, this issue can be converted into "Implement it".

**Comment by snooppr** [comment]
Ah, this figure means the difference.  Wouldn't have thought.  By the way, for tourists and sportsmen it is climbing in the interests (and done, as I believe, is a figure for them).

**Comment by snooppr** [comment]
Thanks fixed in version 22-08-23-5.
