### ISSUE TITLE
June update on GP

### ISSUE THREAD

**Issue by Ethereal-Fox** [organicmaps/organicmaps#2834]
I see that you have released a new update **2022.06.18-2-android**. But the latest version on Google Play is **2022.05.31-10-Google**.
Why don't you distribute the June update on Google Play? I can't install the version from github over the version from google play; they have different signatures and I don't want to delete the previous version.

**Comment by biodranik** [comment]
Because Google is delaying the review for a week now. Please be patient.

**Comment by pastk** [comment]
It had been released.
