### ISSUE TITLE
POI info isn't being updated after editing

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#2835]
**OS:** LineageOS 17.1 (Android 10)
**OM:** version 2022.05.31-10-FDroid

1. Choose POI;
2. Add e.g. website;
3. Save changes.

After returning to map view you won't see added info on POI card until you reselect it.

Here's the [video](https://user-images.githubusercontent.com/22843816/175854378-788dc32a-58a2-4755-8c9b-49a32276799a.mp4)

**Comment by map-per** [comment]
Fixed this issue in #9388
