### ISSUE TITLE
Removing cuisine from restaurant data does not work

### ISSUE THREAD

**Issue by Explorer256** [organicmaps/organicmaps#2842]
When I try to remove a kitchen from the data, I uncheck the list, save the changes, but the kitchen remains in the restaurant data

**Comment by Explorer256** [comment]
> Уточните, пожалуйста, это iOS или Android.

Android

**Comment by arnaudvergnet** [comment]
Duplicate of https://github.com/organicmaps/organicmaps/issues/1283
