### ISSUE TITLE
Add more railway=rail types and improve rendering

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#2844]
Add more subtypes of [`railway=rail`](https://wiki.openstreetmap.org/wiki/Tag:railway=rail) and render them differently.

E.g. render less important `branch`es and especially `siding` and `yard` rails at upper zooms in thinner / more faint lines.
It will allow to render big railway stations/hubs better at upper zooms because they're overloaded with too many minor rail lines at the moment.

I think we don't need all the possible subtypes, following selection will be enough:
1. [`usage=main`](https://wiki.openstreetmap.org/wiki/Key:usage) & `usage=tourism` => `railway.rail.main` (the most important lines)
2. `usage=branch` => `railway.rail` (lines of secondary importance, incl. the ones w/o the `usage=*` tag)
3. [`service=siding/yard/spur`](https://wiki.openstreetmap.org/wiki/Key:service) => `railway.rail.service` (to be rendered at upper zooms)
4. `service=crossover` => `railway.rail.crossover` (for zoom 18- perhaps)

**Comment by pastk** [comment]
Now I think its better to add more railway types, it'll help to have better translation for the types too, so that railways' purpose is more clear to the users (esp. important to distinguish non-passanger lines like usage=industrial).

Here is what I have in mind including possible translations:

- `railway-rail-highspeed`
		`[highspeed=yes]` 120k usages out of 2500k total `[railway=rail]`
		"High-speed rail" "Высокоскоростная железная дорога"
- `railway-rail-main`
		`[usage=main]` 1000k
		"Railway" "Железная дорога"
- `railway-rail-tourism`
		`[usage=tourism]` 18k
		"Touristic railway" "Туристическая железная дорога"
- `railway-rail-branch`
		`[usage=branch]` 260k and ordinary railways w/o `[usage=]` and `[service=]` tags
		"Railway branch" "Периферийная железная дорога"
- `railway-rail-utility` // tertiary/nonpublic/restricted/special/utility
		`[usage=industrial]` 160k and `[usage=military/test/scientific]`
		"Utility railway" "Служебная железная дорога"
- `railway-rail-spur`
		`[service=spur][!usage]` 400k
		"Railway spur" "Ответвление ЖД пути"
- `railway-rail-service`
		`[service=siding]` 330k and `[=yard]` 570k and `[=crossover]` 90k
		"Service rail track" "Вспомогательный ЖД путь"

The currently used single `railway-rail` type is better to mark obsolete and leave as is so that translations and styling/visibility is left intact for old mwms.

**Comment by vng** [comment]
Ok, but replace railway-rail with railway-rail-main ?

**Comment by pastk** [comment]
> Ok, but replace railway-rail with railway-rail-main ? UPD: But the OSM still has (I'm sure) a lot of ways with railway=rail tag only. So, I think we should treat this type as main.

I think its better to put it into `railway-rail-branch` (together with `usage=branch`).
We might raise visibility of `railway-rail-main` to z10 and add them to the world map also. And if there are no tags beside `railway=rail` then its usually a minor line that was not tagged comprehensivly..

**Comment by vng** [comment]
Ok, not _put_, but _keep_ in railway=rail. Otherwise, you should duplicate styles.

**Comment by pastk** [comment]
Overall the looks of the railways should stay similar to what we have now - a simple grey line in lower zooms and
a dashed line w/ casing in higher ones (we can play with the "dash white" color to distinguish lines).

Here is a visual scheme I have in mind:

`railway-rail-main` from z10
Just more contrast/thick than it is now and visible earlier.

`railway-rail-highspeed` from z10
Longer dashes, maybe more thick.

(Later we can think about inclusion of main and highspeed (and touristic?) in the World map.)
 
`railway-rail-tourism` from ~z10-11
Slightly different color? A golden tint? Other ideas?

`railway-rail-branch` from z11
Same style as main, but visible a zoom later.

Following non-passenger lines should be visually distinct.
Probably thinner and with a blue-ish tint similar to the color of industrial areas.
`railway-rail-utility` from ~z13-14
`railway-rail-spur` from ~z15-16
`railway-rail-service` from ~z17-18

CC @biodranik

**Comment by biodranik** [comment]
Differentiating railways will be more important when we implement PT style and PT online routing. Now most people do not care about types or subtypes. Only knowing the fact that there is a rail is useful.

**Comment by pastk** [comment]
Closed by #5510
