### ISSUE TITLE
Search in Russian doesn't work in sub-search (like kitchen type) when POI is added

### ISSUE THREAD

**Issue by dbf256** [organicmaps/organicmaps#285]
If you search 'амери' than 'американская кухня' is not displayed. But it is displayed for 'ameri' (probably, as a substring for 'american').

![index_1](https://user-images.githubusercontent.com/2550295/113474504-ff96ee80-9478-11eb-9b37-59f2f3a0807b.jpg)
![index_2](https://user-images.githubusercontent.com/2550295/113474505-002f8500-9479-11eb-9b28-a22dc1f08a76.jpg)
![index_3](https://user-images.githubusercontent.com/2550295/113474506-00c81b80-9479-11eb-92a3-8cbef327d14a.jpg)

**Comment by dbf256** [comment]
For POI-type search it works fine

![index_4](https://user-images.githubusercontent.com/2550295/113474605-8c41ac80-9479-11eb-989a-ff3d87e84890.jpg)

**Comment by rtsisyk** [comment]
I can confirm that it doesn't work in this way. Neither the original MAPS.ME nor this application support automatic transliteration and/or translation. This is a good feature request. Thanks!

**Comment by dbf256** [comment]
Thanks, I think it could be not about auto-translate, but about search in displayed list: if there are items in russian than it should be possible to search using russian text. But looks like by some reason code expects latin letters. I had some email conversation with mapsme, they mentioned that it could be an issue with detection of input language because of keyboard that I use, but were not able to fix it. Hope it helps.
