### ISSUE TITLE
Screen flickering on Android 7

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#2857]
From a user report:

I have discovered a nasty bug when using it on a Samsung S7 Active running Android 7.0. When the bug occurs, it causes the screen to flicker very quickly back and forth to a black screen. After having it occur a few times apparently at random while doing different things, and not being able to repeat it, I finally discovered a way to trigger it repeatably:

- In settings ensure "Show on the lock screen" is enabled (as it seems to be by default).
- Return to main map screen and tap power button to lock phone and switch off display
- Tap power button again to switch screen on again
- Select either one of the Layers button at top left, or the Menu button at bottom right
- The screen will now flicker rapidly between black screen and lock screen requiring pressing the home button a good number of times to recover control over the phone.

Note that the bug occurs in this manner only with the show on lock screen option enabled, though I'm not sure if it is absolutely required to be on the lock screen display to trigger it, since I'm not sure I was using that mode the first few times it occurred when not repeatable. The very first time I encountered it was when I was in the bookmarks menu just after having moved my bookmarks over by sharing them from Maps.me (I can't recall exactly which step I was at when the bug appeared, but might have been when I was renaming the bookmarks set). Another time it happened while doing something with route navigation checkpoints (again I can't recall exactly what I'm afraid, but couldn't manage to repeat it).

At least in the repeatable steps mentioned above, the bug only occurs for the two option buttons mentioned (Layers or Menu button – selecting any of the others does not cause any issue). I note that they both bring up the same map layers selection view.

I have also tested this on a different unit of the same S7 Active phone model running Android 8.0, and the bug does not seem to occur here.

**Comment by arnaudvergnet** [comment]
I was able to reproduce the issue on a Wiko with Android 7. Indeed this is a nasty bug. As this device does not have a physical home button, I was forced to hard reboot the phone.

**Comment by arnaudvergnet** [comment]
I noticed the following lines in the log appearing when I open any bottom sheet dialog:

```
2022-06-28 20:01:46.795 8009-8009/app.organicmaps.debug V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@41d5147
2022-06-28 20:01:46.796 8009-8009/app.organicmaps.debug V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@3296d74
2022-06-28 20:01:46.820 8009-8009/app.organicmaps.debug V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@bd1ba4
2022-06-28 20:01:46.820 8009-8009/app.organicmaps.debug V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@3c8ed0d
2022-06-28 20:01:46.927 8009-8009/app.organicmaps.debug V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@9935258
2022-06-28 20:01:46.927 8009-8009/app.organicmaps.debug V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@ee10fb1
```

It does not show in the emulator, do you known anything about this?

**Comment by arnaudvergnet** [comment]
I tried the following and nothing fixed the issue:
- Disabling the background dim
- Using an empty layout
- Returning `null` in `onCreateView` from `MenuBottomSheetFragment`
- All the above at the same time

I have no clue on what could be causing this.

I noticed the phone where I can reproduce the bug is using GL3 for rendering, while the emulator without problem is using Vulkan.

**Comment by biodranik** [comment]
> It does not show in the emulator running another android version, do you known anything about this?

It should not be related. It means that some process consumes a lot of CPU (does our bug cause it?)

You can type `?gl` or `?vulkan` in the search field to force switch (app restart is needed).

**Comment by Explorer256** [comment]
On my Android 5.1 phone, this bug also happened while using it on the lock screen.  It arose when I wanted to edit my label.  
In this case, new labels are created without problems.

**Comment by biodranik** [comment]
Also opening layers menu can be related.

**Comment by biodranik** [comment]
> Another way I've found to repeatably reproduce this bug is from the "Edit Bookmark" menu when used on the lock screen. I.e. by trying to open that menu after unlocking the phone, or by having it open already prior to unlocking the phone.

**Comment by programmin1** [comment]
I think I'm seeing this same bug! just after upgrading maps and installing map updates today!

**Comment by biodranik** [comment]
It would be great if some Android 7 owners can experiment with a proper fix for this bug (maybe some additional runtime flags for the Android window/app)?

**Comment by programmin1** [comment]
That might be hard as that old phone doesn't connect to computer very well and when it does happen it ruins the phone (until the battery wears down and it restarts??) - is there any other workaround?

Since other apps have given warnings that ancient-Android-version is not supported I really should just get things set up on Librem phone... is Organicmaps working better on Librem phone btw?

**Comment by biodranik** [comment]
Any newer device should work faster and better with OM and other apps )

**Comment by programmin1** [comment]
You would think so, but I just updated everything on Librem 5 phone including Organicmaps and it still does not even open and load at all. That is really frustrating for every person on a Linux phone. https://github.com/organicmaps/organicmaps/issues/2623

**Comment by biodranik** [comment]
@AlexValue what is your device model?

**Comment by AlexValue** [comment]
> @AlexValue what is your device model?

Meizu m3s
