### ISSUE TITLE
[Linux Desktop] Dragging the map drags the entire window instead

### ISSUE THREAD

**Issue by PureTryOut** [organicmaps/organicmaps#2858]
Normally I expect to be able to drag the map around by holding the left-mouse button and dragging it around, but when I do this it drags the entire window instead making me unable to move the map.

This is using 2022.06.18-2-android (why does it have that `-android` suffix...?) and running on Alpine Linux using Qt 5.15.5 with KDE patches. Running on KDE Plasma 5.25.1, Wayland session.

**Comment by jaimeMF** [comment]
I think I had the same issue and I fixed it with https://github.com/organicmaps/organicmaps/pull/3943

**Comment by biodranik** [comment]
@PureTryOut can you please try the latest version and close this issue, if it is already fixed?

**Comment by biodranik** [comment]
What errors do you see? Did you clone the repo with all submodules and run ./configure.sh ?

**Comment by PureTryOut** [comment]
I did both yes.

```
$ ./configure.sh 
Initializing repository with default values in Open-Source mode.
./bootstrap.sh: line 195: ./tools/build/src/engine/build.sh: not found
Building B2 engine..
./bootstrap.sh: line 229: ./tools/build/src/engine/build.sh: not found

Failed to build B2 build engine
```

**Comment by biodranik** [comment]
Looks like you did not initialize submodules properly. What does `git submodule update --init --recursive` say?

**Comment by PureTryOut** [comment]
That does the job, I forgot that Boost had submodules itself as well so needed to add `--recursive`... :facepalm: 

However it now fails to compile with the same problem as the system provided boost did:

```
/home/bart/Documents/Git/organicmaps/3party/boost/boost/geometry/geometries/point_xy.hpp: In member function 'void boost::geometry::model::d2::point_xy<CoordinateType, CoordinateSystem>::x(const CoordinateType&)':
/home/bart/Documents/Git/organicmaps/3party/boost/boost/geometry/geometries/point_xy.hpp:69:27: error: type/value mismatch at argument 1 in template parameter list for 'template<class _Key, class _Compare, class _Alloc> class std::set'
   69 |     { this->template set<0>(v); }
      |                           ^
/home/bart/Documents/Git/organicmaps/3party/boost/boost/geometry/geometries/point_xy.hpp:69:27: note:   expected a type, got '0'
/home/bart/Documents/Git/organicmaps/3party/boost/boost/geometry/geometries/point_xy.hpp:69:27: error: template argument 2 is invalid
/home/bart/Documents/Git/organicmaps/3party/boost/boost/geometry/geometries/point_xy.hpp:69:27: error: template argument 3 is invalid
/home/bart/Documents/Git/organicmaps/3party/boost/boost/geometry/geometries/point_xy.hpp: In member function 'void boost::geometry::model::d2::point_xy<CoordinateType, CoordinateSystem>::y(const CoordinateType&)':
/home/bart/Documents/Git/organicmaps/3party/boost/boost/geometry/geometries/point_xy.hpp:73:27: error: type/value mismatch at argument 1 in template parameter list for 'template<class _Key, class _Compare, class _Alloc> class std::set'
   73 |     { this->template set<1>(v); }
      |                           ^
/home/bart/Documents/Git/organicmaps/3party/boost/boost/geometry/geometries/point_xy.hpp:73:27: note:   expected a type, got '1'
```

**Comment by biodranik** [comment]
We fixed this issue a long time ago. Are you building the master branch? If yes, then can you please provide a full log?

**Comment by PureTryOut** [comment]
I had to reclone organicmaps as I cleared it out recently, so yes this is the latest master branch.

The full log is giant, I've uploaded it as a file to this comment.
[organicmaps_build.log](https://github.com/organicmaps/organicmaps/files/10399622/organicmaps_build.log)

**Comment by PureTryOut** [comment]
I run `cmake --target desktop` which seems to build just the desktop app (it at least builds a whole lot less than not specifying the target). It did before at least.

GCC is 12.2.1. Good to know it's an actual issue, I'll happily await a fix :smile:

**Comment by biodranik** [comment]
#4264 should help. Can you please test the latest master?

**Comment by PureTryOut** [comment]
Yup, build works and this issue is not present any more. Thanks!
