### ISSUE TITLE
[drape] 3D building rendering artifacts

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#2862]
https://osm.org/go/2YpWxiQ~-?m=

![2022-06-29 06 41 12](https://user-images.githubusercontent.com/175612/176346506-b69f0146-d626-4fca-b3c2-7d3959906155.jpg)

**Comment by mpawelski** [comment]
I've found similar issue at 52.39966, 16.962772
![image](https://user-images.githubusercontent.com/2056282/189505775-6e8bc7f1-de2f-464e-96df-d832f8d8a518.png)
