### ISSUE TITLE
Beaches overlap streams on the map

### ISSUE THREAD

**Issue by ivanbarsukov** [organicmaps/organicmaps#2864]
If you zoom in on the screenshot, you can see where the stream starts in the forest, but it disappears on the beach

60.270851, 28.93112

![photo_2022-06-29_10-00-56](https://user-images.githubusercontent.com/14816075/176374680-07d11c29-dfaf-4dd6-bf75-23db4f56b652.jpg)
![photo_2022-06-29_10-00-56 (2)](https://user-images.githubusercontent.com/14816075/176374686-04962b60-76ef-4b91-8857-2d1ccec81d8a.jpg)

**Comment by biodranik** [comment]
A priority issue
