### ISSUE TITLE
[Android] Navigation refuses to route over ferry crossing a border

### ISSUE THREAD

**Issue by PureTryOut** [organicmaps/organicmaps#2871]
I'm trying to calculate a route between Hamburg and Copenhagen, but OM refuses to route over the ferry and quickest route between those places, even with ferry enabled in the route options.

![Screenshot_20220629-180111_Organic_Maps](https://user-images.githubusercontent.com/1565836/176482999-b0207400-9047-4f63-86ad-fb342494e4c8.png)

As you can see in the screenshot I even added an inbetween stop next to the ferry to try and force it to route over it, but no matter what I do it refuses and takes a route over the mainland instead.

OpenStreetMap does know about the ferry however, and I can see it in OM.

**Comment by biodranik** [comment]
Did you check OSM history? Wasn't the ferry broken when we generated maps (see at ? dialog)?

**Comment by PureTryOut** [comment]
I did not. I did try to check just now, but I find the history mode of https://openstreetmap.org hard to use and can not really find anything. I just see in edit mode that the ferry line is there, but your question does make sense. What is the ETA for new maps?

**Comment by vng** [comment]
What "Routing options" are enabled in your case? If ferry is check, the app _avoids_ ferries.

**Comment by PureTryOut** [comment]
Ah, wow, that explains it. Not sure how I missed that. :facepalm: 

OM seems to still prefer the mainland but now if I add a stop just after the ferry, it reroutes and takes that shorter route with the ferry. It only makes the trip go down from 4 hours and 10 minutes to 4 hours, but shortens it with about 100km which is enough to make me go that route instead.

Sorry for bothering you guys with this one, seems I just didn't understand the UX :see_no_evil:

**Comment by biodranik** [comment]
@PureTryOut you're not the first one. We need a separate issue with a proposal on a better UX for these options. Maybe simple renaming?
