### ISSUE TITLE
amenity.events_venue displayed unformatted

### ISSUE THREAD

**Issue by jpds** [organicmaps/organicmaps#2872]
If one clicks on a events venue POI (for example: https://www.openstreetmap.org/way/344501804 ) - one will see `type.amenity.events_venue` instead of a more 'human' string as the object description.

**Comment by pastk** [comment]
A base EN translation was not added when the type was initially added in #1313.
Same for `amenity=loading_dock`.

Please add translations into `types_strings.txt` and also into `categories.txt` if it needs to be searchable.

**Comment by csidirop** [comment]
I think this issue should be fixed in the next release and can be closed now that @biodranik merged my PR

**Comment by pastk** [comment]
Thanks for the work!
