### ISSUE TITLE
TTS more information links to maps.me documentation

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#2875]
Reported by MXX in the OSM discord:

In the TTS settings, there is a link called "For more information, please check this guide."

It links to maps.me documentation at the link https://mapsme.zendesk.com/hc/en-us/articles/208628985-How-can-I-check-TTS-settings-on-my-Android-device-

Ideally this should be hosted on organicmaps.app, with OrganicMaps branding.

**Comment by biodranik** [comment]
It is a duplicate, there was already a similar issue as I remember.

**Comment by arnaudvergnet** [comment]
Yes this was reported here https://github.com/organicmaps/organicmaps/issues/2383

**Comment by endim8** [comment]
Ah good, I'll close this one
