### ISSUE TITLE
Intermediate stop numbers are shown as letters in subway routing

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#2879]
Intermediate stops are numbered on the map (`1` and `2`).
But in the bottom they're shown as `A` and `B`, which is confusing.

![Screenshot_1656598012](https://user-images.githubusercontent.com/18434508/176699806-a21bfc2a-f94c-4eee-8a54-863e9c3b3216.png)

**Comment by hoizan** [comment]
Issue causing Android OM to crash as reported in case #1456

**Comment by biodranik** [comment]
The crash is confirmed. @arnaudvergnet can you please take a look at these related issues? On iOS proper numbered icons are used, while on Android old icons with letters A B C (only three!) are still used instead of numbered icons.

**Comment by arnaudvergnet** [comment]
I'll try to take a look when I get the time
