### ISSUE TITLE
[iOS]: I can’t authorize to my OSM account. 

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#288]
A feedback from TestFlight: I can’t authorize to my OSM account. 
IPhone XS.
10.6.4 (0) latest

https://appstoreconnect.apple.com/apps/1546633890/testflight/screenshots/AGl-xrGpn9RjoQyxP5kzIUU?preReleaseVersionId=cbde4833-3283-4e96-981f-c13e46829839

**Comment by biodranik** [comment]
@rtsisyk похоже, версия в тестфлайте собрана с неправильным private.h, локально у меня авторизуется, а из тестфлайта - нет. В следующий раз нужно убедиться, что configure.sh был действительно запущен с правильным урлом к репо с ключами.

**Comment by rtsisyk** [comment]
Точно! Предыдущий релиз был бажный по этой причине. Последний должен быть нормальный.

**Comment by maciboy** [comment]
Off topic: where can I find the TestFlight link? I registered on the provided shortlist, but never got any information and now the link is dead :(

**Comment by rtsisyk** [comment]
https://testflight.apple.com/join/62l4Qh2K

**Comment by maciboy** [comment]
Thanks for the Link @rtsisyk :)
With the latest TestFlight version I have the same issue and can‘t login with OSM account :(

**Comment by rtsisyk** [comment]
```
2021-04-10 18:37:11.832634+0300 OMaps Debug[11653:5963474] Task <CD7DD2D9-C54D-4E42-83D2-92513309784A>.<14> finished with error [-1004] Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={_kCFStreamErrorCodeKey=61, NSUnderlyingError=0x600002b02760 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <CD7DD2D9-C54D-4E42-83D2-92513309784A>.<14>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <CD7DD2D9-C54D-4E42-83D2-92513309784A>.<14>"
), NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=http://localhost/?oauth_token=<REDACTED>, NSErrorFailingURLKey=http://localhost/?oauth_token=<REDACTED>&oauth_verifier=2BSdollvzcZwWxIjAQdO, _kCFStreamErrorDomainKey=1}
LOG TID(10) DEBUG     121.811 platform/http_client_apple.mm:169 RunHttpRequest Error:  -1004 : Could not connect to the server. while connecting to https://www.openstreetmap.org/oauth/authorize
LOG TID(10) WARNING   121.811 Login/MWMAuthorizationOSMLoginViewController.mm:139 -[MWMAuthorizationOSMLoginViewController login]_block_invoke Error login NetworkError /Users/roman/code/omapsapp/omapsapp/editor/osm_auth.cpp:205, "SendAuthRequest Network error while connecting to https://www.openstreetmap.org/oauth/authorize"
```

**Comment by rtsisyk** [comment]
@maciboy could you please try to login again? This problem was caused by misconfiguration of our OAuth token. It should work now. No update of application is required.

**Comment by maciboy** [comment]
Works!
Wow this was amazingly fast!
Thanks so much, I really love how you keep Maps.me alive!

**Comment by rtsisyk** [comment]
Cool! Thank you for your report. Sorry for inconvenience. Stay tuned!
