### ISSUE TITLE
Cannot donate, donation was sent back

### ISSUE THREAD

**Issue by vn971** [organicmaps/organicmaps#2890]
Hi, I'm trying to donate money to OrganicMaps.
On 2022-05-17 I've donated using "SEPA/direct bank transfer - negligible fees" method. The money was sent to the BE39 9672 0031 0319 IBAN address, with the description "Thanks for Organic Maps. The app is fast and convenient.".
However, approximately 30 days later, on 2022-06-17, I've got the money back.

Any ideas? Does this way of donating to OrganicMaps really work? Anything to double-check there?

Thanks

**Comment by vn971** [comment]
UPD: maybe the description should've been "Donation" rathan than "Thanks for ....." ?

**Comment by biodranik** [comment]
No, the reason was a due diligence check by the bank. We got a notification from the bank asking us to provide details about you to approve the transfer. Obviously, we did not know how to get your details (and did not want to share them anyway), so the bank canceled the transfer.

**Comment by biodranik** [comment]
@vn971 can you please contact me directly on Telegram (@biodranik) about this issue?

**Comment by biodranik** [comment]
@vn971 we recently updated our donation methods, please check https://organicmaps.app/donate/

**Comment by matkoniecz** [comment]
It seems closeable then?
