### ISSUE TITLE
[android] [f-droid build] Option to disable gathering data from "Network location provider"

### ISSUE THREAD

**Issue by CortexReaver** [organicmaps/organicmaps#2893]
I am using organic maps only outside with GPS and happy with it. But after I've optimized my Android and disable maybe some system apps so they do not drain battery that much, an annoying message start appearing on my screen, telling about "Network location provider". It is really frustrating and there is no way to turn it off. So it might be a good idea to either disable such messages completely, or disable use of "Network location provider". Is it possible?

**Comment by biodranik** [comment]
Can you please show us the screenshot, and describe how to reproduce it?

**Comment by CortexReaver** [comment]
I've checked other apps which using GPS, same message on screen.. So it's not your app's fault. Anyway, I'm on Android 11. By "system apps" I mean all google service. I have restricted their battery usage and disabled "Background data", including Google Play services and Google maps (also Google Drive, Android Auto, Google Assistant, YouTube, Youtube music, Android Accessibility Suite, Calendar, Carrier services, Digital Wellbeing, Duo, Gmail, GoogleTV). But have not touched "hidden" android services in any way. Also disabled "Mobile data always active" in Developer options. Switched it back but message still there. Maybe there is an app that can just hide those?

![Screenshot_20220702-112848](https://user-images.githubusercontent.com/34350690/176995575-45981a61-46cd-409e-a7ad-cd49943b33f9.png)

**Comment by CortexReaver** [comment]
Yeah, it was Google Play services, my apologies for bothering you. And I think this is cannot be fixed because NLP services tied too much to the OS and cannot be rewritten from zero just for this. Stock android so irritating to use, I need to switch to something like Lineage ASAP :(

**Comment by meenbeese** [comment]
Issue can be closed? I think that it is resolved @Jean-BaptisteC

**Comment by patepelo** [comment]
No more feedback. I'm closing this issue as resolved, like stated in the comments.
