### ISSUE TITLE
[android] Map view locks up when zooming-in/out on certain places

### ISSUE THREAD

**Issue by unmanbearpig** [organicmaps/organicmaps#2900]
If I zoom in or zoom out on certain location the map just stops responding, but other controls still work. If then switch to another view like Search or Bookmarks and come back to the map it becomes black.

Here is one of the places I see this bug at:
om://0y9dMP21Fo/Aram_Khachaturian_Concert_Hall 
https://omaps.app/0y9dMP21Fo/Aram_Khachaturian_Concert_Hall

I get this issue after the last update 2022.06.18-2-FDroid (Play Store version too).
The previous version 2022.05.24-2-FDroid works fine.

Let me know if I can provide any other helpful information or can help debugging it.

**Comment by vng** [comment]
This is already fixed and updated version is available in Play Store (from 30.06). F-Droid should be available soon ..
Please, check it out.
