### ISSUE TITLE
Accented letters with TTS

### ISSUE THREAD

**Issue by julianfairfax** [organicmaps/organicmaps#2919]
The TTS engine I use, RHVoice, has issues with accented letters: https://github.com/RHVoice/RHVoice/issues/552.

Would it be possible for Organic Maps to pass on roadnames with accented letters replaced with unaccented letters, so these kinds of issues don't happen?

Otherwise, at least with RHVoice, the accented letters are simply ignored and the name is not properly said at all.

Thank you for your work on this app!

**Comment by biodranik** [comment]
What about other TTS engines? I think that this issue should be properly fixed on RHVoice side.

**Comment by biodranik** [comment]
You can check our TTS issues: https://github.com/organicmaps/organicmaps/labels/TTS

**Comment by julianfairfax** [comment]
I tried with Flite and eSpeak NG. The former had the same issue but the latter worked. I will close this, but hopefully it'll be useful to prevent someone else from opening the same issue again.

**Comment by biodranik** [comment]
Let's keep it open for searchability. It also may motivate other TTS to properly implement it. Did you also create an issue for Flite?

**Comment by RedAuburn** [comment]
closed issues are still searchable, and helps reduce issue clutter :)
