### ISSUE TITLE
Build does not work

### ISSUE THREAD

**Issue by Tobey16** [organicmaps/organicmaps#293]
I have tried to make a build, but it failed. I tried as described in install.md (https://github.com/omapsapp/omapsapp/blob/master/docs/INSTALL.md).
Im running on Ubuntu 18.04 and configured the repository as opensource build.

Building only the generator_tool did not work. Find attached the log.

I put also errors in the file that i could find (except those in the last 100 lines iof the log). [errors i found.txt](https://github.com/omapsapp/omapsapp/files/6254084/errors.i.found.txt)

[log omaps.txt](https://github.com/omapsapp/omapsapp/files/6254072/log.omaps.txt)

**Comment by Tobey16** [comment]
`-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads - not found
-----------------------------------------------------------------------------
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
Doing nothing, because we know nothing about developer frameworks dir
-- Looking for dlfcn.h
-----------------------------------------------------------------------------

-- Looking for arc4random_buf - not found
-- Looking for off_t - not found
-- Looking for size_t - not found
-----------------------------------------------------------------------------
You have called ADD_LIBRARY for library shaders without any source files. This typically indicates a problem with your CMakeLists.txt file
-----------------------------------------------------------------------------
/root/omapsapp/3party/libtess2/Source/geom.c: In function ‘tesedgeIsLocallyDelaunay’:
/root/omapsapp/3party/libtess2/Source/geom.c:291:80: error: ‘M_PI’ undeclared (first use in this function); did you mean ‘__P’?
      calcAngle(e->Sym->Lnext->Org, e->Sym->Lnext->Lnext->Org, e->Sym->Org)) < (M_PI + 0.01);
                                                                                ^~~~
                                                                                __P
-----------------------------------------------------------------------------
3party/libtess2/CMakeFiles/tess2.dir/build.make:110: recipe for target '3party/libtess2/CMakeFiles/tess2.dir/Source/geom.c.o' failed
CMakeFiles/Makefile2:1692: recipe for target '3party/libtess2/CMakeFiles/tess2.dir/all' failed
-----------------------------------------------------------------------------`

**Comment by Tobey16** [comment]
I think i fucked up :dagger:

**Comment by biodranik** [comment]
Please apply this fix, we'll merge it soon: https://github.com/omapsapp/omapsapp/pull/273/commits/1937c7c2143b38af0681d2dfe40d8222209072be
