### ISSUE TITLE
The soccer field is called a sports ground

### ISSUE THREAD

**Issue by Explorer256** [organicmaps/organicmaps#2930]
The field for soccer is not signed with its name. Instead, a more general name is used

**Comment by strump** [comment]
@Explorer256  то есть, нужно чтобы вместо "Спортплощадка" было "Футбольная площадка"?

**Comment by Explorer256** [comment]
> @Explorer256 то есть, нужно чтобы вместо "Спортплощадка" было "Футбольная площадка"?

Да, было бы идеально, если влезет. Можно ещё "Баскетбол" в "Баскетбольная площадка"

**Comment by Explorer256** [comment]
> > @Explorer256 то есть, нужно чтобы вместо "Спортплощадка" было "Футбольная площадка"?
> 
> Да, было бы идеально, если влезет. Можно ещё "Баскетбол" в "Баскетбольная площадка"

Ну и "Спортплощадка" можно переименовать в "Спортивная площадка"

**Comment by pastk** [comment]
Duplicate of #2511
