### ISSUE TITLE
[android] A race condition when opening geo:// url

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#2934]
There is a kind of race condition bug.

steps to reproduce:

- send a geo: intent to Organic Maps

Note that first the map moves to the geo intent's position like expected.

But after a few seconds the maps jumps to the gps position

this happens in case the gps position is not instantly available after sending the geo: intent to Organic Maps. (Happens often for me.)

https://t.me/organicmaps/16401

**Comment by Norbert80** [comment]
Hi There,

below i have added a screen recording. Please note that I also see this bug sometimes without that request to continue to search position appearing.

https://user-images.githubusercontent.com/6921696/178098758-f1da43af-14fd-47b0-a8d4-4dc7d410525d.mp4

**Comment by rtsisyk** [comment]
Should be fixed by #6546.
