### ISSUE TITLE
Fix handling of opening_hours=closed/off

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#2936]
![Screenshot_20220708-133702_Organic Maps](https://user-images.githubusercontent.com/26939824/177996605-ea145c78-14d3-4e59-954f-110420cf6bc7.png)

the recently added search info displays it correctly, but it is interpreted internally as open 24/7

`opening_hours=closed` usage = 3,559
`opening_hours=off` usage = 1,030

These tags are more commonly used with `opening_hours:covid19`, but it'd be good to handle them for normal hours.

**Comment by strump** [comment]
Hm, so node https://osm.org/way/288973788 has tag `opening_hours=closed`. But OrganicMaps shows in POI details `24/7`. This should be fixed

**Comment by endim8** [comment]
duplicate of https://github.com/organicmaps/organicmaps/issues/1274
