### ISSUE TITLE
[android] Extend color of menu bar to navigation bar when using "Swipe gestures" mode

### ISSUE THREAD

**Issue by foersterp** [organicmaps/organicmaps#2943]
In my opinion, Organic Maps already has a pretty modern interface and especially a nice map design. Nevertheless, here some more ideas on how to improve the UI.

---

At the moment the navigation bar is always black:

![01](https://user-images.githubusercontent.com/83224514/178114368-8c19e438-c9a4-4a63-a9b5-4fe0c51f9bc7.jpg)

I think it would look better if the color of the menu bar at the bottom (white/black depending on the theme) could also be used to tint the navigation bar. This should only be done when using the "Swipe gestures" mode (not when using the traditional buttons). Furthermore, the transparency should match the transparency of the menu bar.

Then, it would look how it currently looks on iOS:

![](https://user-images.githubusercontent.com/92886370/176152288-3d5bdd79-8602-4f86-83d1-ec915f8d83fe.jpg)

![](https://user-images.githubusercontent.com/92886370/176152301-f49475dd-326a-4f08-92d5-2aed7483d040.jpg)

(not my images since I don't own an iOS device / source: #2853)

---

Also, while the start screen is shown, the green color could be extended to the navigation bar (green instead of black).

Current situation:

![02](https://user-images.githubusercontent.com/83224514/178114409-6a5bcdb5-9b2b-4178-9fc6-08692cb8c5eb.jpg)

**Comment by biodranik** [comment]
Good, can you implement it?

**Comment by foersterp** [comment]
I'm not into Android development but I would want to learn something new. However, I can't evaluate how hard it is to implement this.

Do you (or anybody else) have an idea on how I could get started (e.g. documentation)?

**Comment by foersterp** [comment]
I'll take a look. Thank you!

**Comment by arnaudvergnet** [comment]
Please note https://github.com/organicmaps/organicmaps/pull/2905 will remove the bottom menu so the navigation bar will only need to match the app background on the splash screen.
