### ISSUE TITLE
[Android] crash when using transport navigation

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#2944]
Since the last update I cannot use the transport navigation mode (for routing with the subway).

When creating a route using this mode, the app computes the path using foot navigation then crashes (I can see the generated path before the crash).

I cannot give more information right now, I will try to replicate the issue on a Dev build when I have my computer.

App version: 2022.06.29-3-FDroid

**Comment by biodranik** [comment]
This is a known issue that was already fixed on master and in the next upcoming fdroid release (which failed to build for some reason).

**Comment by arnaudvergnet** [comment]
I must have missed the issue sorry about that. Nice to hear it's already been been fixed!
