### ISSUE TITLE
Add "powered by OpenStreetMap project" onto a splash screen

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#2950]
When the app starts there is a splash screen with the logo and "Organic Maps" title.

Just below it we can add a subtitle like "powered by OpenStreetMap project", to make users aware that maps data comes from OSM (map data issues are a major source of negative feedback as newbie users assume mapping is done by the OM team). Also it'll help popularize OSM and give an extra attribution to this great project!

**Comment by biodranik** [comment]
@MihirShirgaonkar please read docs folder carefully, we have a lot of useful information there.

**Comment by endim8** [comment]
I made the title text bold as well, is it good or should we keep it the same as before?
![Screenshot_20220724-205550_Organic Maps (Debug)](https://user-images.githubusercontent.com/26939824/180663751-b002b2f9-aee9-4f47-8764-b91b6a79fb41.png)

**Comment by biodranik** [comment]
Looks good.

**Comment by Rythm18** [comment]
hey @pastk i am a beginner to open source. I want to contribute to this project, so can you please guide how can i start with?
i know basics of C, C++ and python and javascript and html.

**Comment by biodranik** [comment]
@Rythm18 please check README and documentation in the docs folder.
