### ISSUE TITLE
Share only coordinates when sharing the location for usage in other maps apps

### ISSUE THREAD

**Issue by MatsG23** [organicmaps/organicmaps#2957]
When sharing the current location from Organic Maps, it generates a text that can be sent to other apps. However, I dislike the text that is made up. It includes an direct app link, an online link and a download link for the app.
tbh, I will not use the feature like that. That predefined sharing messages annoy me in every app. It is mostly a call-to-download for the receivers if the text is not heavily modified manually.
I propose that you only generate the basic coordinates of the current location as a text. **This allows the sender to directly paste the coordinates in any maps app.** I know that the coordinates are shown on the online link to OSM but I would personally always copy the coordinates from there instead of sending the app link, the web link or the download link to the app.

**Comment by strump** [comment]
If you long click on coordinates line there’s option to copy coordinates. Is it what you are looking for?
<img src= "https://user-images.githubusercontent.com/720808/178826438-113ee8a5-18c1-47ca-94e2-694e857db456.png" width="300px"/>

**Comment by biodranik** [comment]
#1821 is in progress.
