### ISSUE TITLE
Generating maps end with "ModuleNotFoundError: No module named 'descriptions'" in df0291c

### ISSUE THREAD

**Issue by Tobey16** [organicmaps/organicmaps#296]
I made a complete build, but when trying to generate a map it does not work.
I tried like it is descriped in: 
https://github.com/omapsapp/omapsapp/blob/split-repo/docs/INSTALL.md 
and
https://github.com/omapsapp/omapsapp/blob/split-repo/tools/python/maps_generator/README.md
(I changed in the ini the path "OMIM_PATH: ~/omim" to "OMIM_PATH: ~/omapsapp", and added the pdf files)
[map_generator.ini.txt](https://github.com/omapsapp/omapsapp/files/6264596/map_generator.ini.txt)

The output is as follows:
root:~/omapsapp/tools/python/maps_generator# python3.6 -m maps_generator --countries="World, WorldCoasts, Liecht*"
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code    exec(code, run_globals)
  File "/root/omapsapp/tools/python/maps_generator/maps_generator.py", line 12, in <module>
    from descriptions.descriptions_downloader import (check_and_get_checker,
ModuleNotFoundError: No module named 'descriptions'

**Comment by biodranik** [comment]
Looks like you need python2

**Comment by Tobey16** [comment]
No, it has the same error with python3 and 2.7.

**Comment by Tobey16** [comment]
I found my problem:
While the instructions in the first part of the above mentioned README.md told to change a directory, the instructions at the bottom did not! So you have to run it in "/root/omapsapp/tools/python/". And because python can run the directory "maps_generator" and the file "maps_generator.py" it was not obvious that this was wrong.

BTW: can you tell me what the stage(?) "subway" is?
