### ISSUE TITLE
Bookmarks list: remove extra padding for list name row

### ISSUE THREAD

**Issue by mirko77** [organicmaps/organicmaps#2964]
Hi there,

there is a lot of left and right padding in the bookmark list on the name rows, not allowing too many characters for list names before they get shortened with the ellipsis

The left one could be reduced to the same amount used on the "Create new list" and "Import Bookmarks" rows

The right one could be reduced as well.

Samsung A33, Android 12

![bookmarks-list](https://user-images.githubusercontent.com/1233305/178998102-a53c6221-b09b-4a49-b8e3-99b8ed9aa5da.jpg)

**Comment by biodranik** [comment]
The padding on the left and right can also be reduced )
