### ISSUE TITLE
Undesired background activity

### ISSUE THREAD

**Issue by ioctl-user** [organicmaps/organicmaps#297]
This problem seems to be a legacy of maps.me , because I seen it with that app.

OMaps has undesired background activity when screen off, even if app was not run. Please see Battery Historian screenshot with my marks:

![1](https://user-images.githubusercontent.com/23457638/113826626-109e7300-978b-11eb-96e3-9aef642a207d.png)

**Comment by rtsisyk** [comment]
This job service schedules the map downloading.

**Comment by ioctl-user** [comment]
Настройка Auto-download при этом выключена.

В любом случае, проверка раз в час это как-то слишком часто.
