### ISSUE TITLE
Навигатор - стрелка

### ISSUE THREAD

**Issue by ZinlineTourist** [organicmaps/organicmaps#2975]
Есть возможность указательную стрелку при навигации маршрута поднять чуть высшее, в данный момент она располагается в самом внизу экрана. Очень неудобно, когда маршрут проложен и поворот примерно на 90 градусов (не говоря если у тебя сейчас разворот), получается экран пустой, навигацию не видно, а куда ехать не понятно. Хотелось бы видеть немного пройдённого пути.
![Курсор](https://user-images.githubusercontent.com/109215445/179309651-b0865119-833d-44b6-b123-63782f5b9b2c.jpg)

**Comment by patepelo** [comment]
> There is a possibility to raise the arrow when navigating the route a little higher, at the moment it is located at the very bottom of the screen. It is very inconvenient when the route is laid out and turn about 90 degrees (not to mention if you now have a turn), you get a blank screen, navigation is not visible, and where to go is not clear. I would like to see a little bit of the route traveled.
> 
> Translated with www.DeepL.com/Translator (free version)
> 

I believe this is planned for a next beta release or already implemented.
Related to #3441

**Comment by Jean-BaptisteC** [comment]
Duplicate of #2987
