### ISSUE TITLE
Add new function to start navigation from lists of bookmarks

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#2980]
Each bookmarks is steps of route, the first bookmarks is the start of route and the latest bookmarks of list is the end of route.

**Comment by biodranik** [comment]
Why not to import the whole track then?

What is the source of your bookmarks? Do you create them in OM?

**Comment by arnaudvergnet** [comment]
I would prefer this alternative: https://github.com/organicmaps/organicmaps/issues/1785

**Comment by Jean-BaptisteC** [comment]
Ok for me, i close the issue
