### ISSUE TITLE
[iOS] [API] Opening a URL with one point crashes the app

### ISSUE THREAD

**Issue by BelKed** [organicmaps/organicmaps#3012]
Opening a URL with only one point results in crashing the whole app
- [MWE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) ❯ `om://map?ll=12.34567,12.34567`

However, when the URL contains two or more points, everything works fine...
- [MWE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) ❯ `om://map?ll=12.34567,12.34567&ll=12.7654321,12.7654321`

---

This issue appeared after the last update to version `2022.07.01-5` (iOS 15.5). Everything worked as intended in the previous version(s).

---

By the way, thanks for creating such a useful map app :)

**Comment by biodranik** [comment]
Thanks. Actually, it fails on a cold start in both cases and works on a warm start in both cases.

**Comment by SirTypesALot** [comment]
@biodranik What would be a cold start in this case? Starting from no GPS fix or from starting up OM without being in the background. All of my attempts of using the API links to point to a place in OM now fails.

**Comment by BelKed** [comment]
Cold start means there starting Organic Maps from URL without being in the background.

**Comment by biodranik** [comment]
@SirTypesALot it means that OM is always killed when you put it into the background.

We need to fix this ASAP.

**Comment by BelKed** [comment]
Huge thanks for fixing this!

**Comment by biodranik** [comment]
Yes, it was an annoying one ) Please let us know if you find any other API issues.

**Comment by BelKed** [comment]
I can confirm that it works now as intended :)
Good work!
