### ISSUE TITLE
Refresh rate / framerate in map view is always 60Hz

### ISSUE THREAD

**Issue by talyz** [organicmaps/organicmaps#3021]
In the map view, the refresh rate is always lowered to 60Hz from my device's native refresh of 120Hz. When I open a menu, it jumps back to 120. This is with Android 12 on a OnePlus 9 Pro.

**Comment by endim8** [comment]
After reading a [similar issue in the flutter repo](https://github.com/flutter/flutter/issues/35162), it seems that we need to set [preferredDisplayModeID](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#preferredDisplayModeId) . This should ideally go to the lower framerate when paused & when in battery saving mode (both system and the one in the settings)

unfortunately, this might not even fix for OnePlus devices, as it seems OnePlus will ignore these calls unless the app is whitelisted:
https://www.reddit.com/r/Android/comments/twtsua/oneplus_devices_are_restricting_high_refresh_rate/

**Comment by biodranik** [comment]
@talyz what is the actual problem? Isn't 60Hz better for the battery?

**Comment by talyz** [comment]
60Hz feels extremely sluggish and unresponsive in contrast to 120Hz. Battery saving measures are already handled outside the app, where enabling `Power saving mode` lowers the refresh rate to 60Hz.

**Comment by biodranik** [comment]
You didn't compare OM at 120 Hz with OM at 60 Hz, right? Not sure if changing it will help to improve performance.

The frame rate is hard-coded at android/src/com/mapswithme/maps/VideoTimer.java, so it should be easy to test. But not easy to properly manage and change dynamically.

**Comment by talyz** [comment]
Before I got the update to Android 12, I used to run maps.me with AutoHz to force the framerate to 120Hz, which worked fine. The animations were perhaps a bit too fast, but it was a lot better than running at 60Hz.

**Comment by thany** [comment]
I feel a request for an option coming up to switch between native >60fps and fixed 60fps.
Otherwise an issue where OM would be at >60fps in battery saver mode.

Personally, I don't need >60fps at all. It's all bollocks to me. Anything that's 30fps or higher, is perfectly workable. More than 60fps is just showing off. To each their own of course, because some people can indeed "see" high fps rates. Nevertheless, to save battery, I personally would like to keep it at 60fps, even when battery saver is turned off.

**Comment by d4f5409d** [comment]
I think we shouldn't create a toogle for this. We only need to haveb60 FPS when Battery Saver is turned on. Otherwise we don't.

**Comment by talyz** [comment]
Indeed, there's no need for an in-app toggle. The framerate / screen refresh rate can be set globally through the Android settings, even when the battery saver is off. Apps should just respect this global setting, not impose limitations in order to save battery against the user's wishes.

**Comment by RedAuburn** [comment]
FPS is unlocked now :)
