### ISSUE TITLE
Re-open #2199

### ISSUE THREAD

**Issue by JaZ-99** [organicmaps/organicmaps#3022]
The issue is not fixed. Now it tells you to ford the river instead of finding the nearest bridge. Tested with 2022.07.01-5-Google version
![Screenshot_20220725-161600_Organic Maps](https://user-images.githubusercontent.com/100690450/180801040-a82665ff-5d29-4293-8a0c-acdfecfd3d92.jpg)
GPS: 51.076320, 16.982557

**Comment by biodranik** [comment]
@vng rivers should be always avoided )

**Comment by BelKed** [comment]
I think the problem is already fixed. Navigation on the specified location works as intended for me :)
@JaZ-99, could you verify that this is working for you as well?

![IMG_8035](https://github.com/organicmaps/organicmaps/assets/66956532/bfde9b7d-eef6-4d1b-b681-daa0cac5f357)
