### ISSUE TITLE
Show bridge area in Organic Maps

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3023]
On this position https://www.openstreetmap.org/#map=19/49.11965/6.17060, bridge is separated between different road on Organic Maps

<img src="https://user-images.githubusercontent.com/87148630/180801938-3edb05b3-5a4f-4b8d-90da-c8bc94de4f28.png" width="300">

Is it possible to represente [this](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge) ?

Android 12 - Pixel 6 / 2022.07.01-5-Google

**Comment by strump** [comment]
You want to see bridge structure as on pic?
<img src="https://user-images.githubusercontent.com/720808/180830138-0387e9c4-cc04-4a2e-81f8-3bb53023c460.png" width="400px"/>

**Comment by Jean-BaptisteC** [comment]
Yes, it's perfect

**Comment by csidirop** [comment]
I would endorse that. I think the way OM is rendering bridges isnt accurate. If available OM should use [bridge shape](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge).

This looks like multiple bridges:
![Screenshot_20220730-090957_Organic_Maps.png](https://user-images.githubusercontent.com/43964592/181879437-3985d66c-ef75-4c30-be1f-0c544262c1e6.png) but it has it bridge structure/shape in osm:
![Screenshot_20220730-091503_Firefox.png](https://user-images.githubusercontent.com/43964592/181879486-8fdd80e5-3ba1-420c-8de2-287bff6ba407.png)

But in comparison google is rendering it the same way:
![Screenshot_20220730-091625_Maps.png](https://user-images.githubusercontent.com/43964592/181879545-f1607c11-60bd-452b-8aed-7705ff36c211.png)

**Comment by biodranik** [comment]
We probably don't support bridge shape yet. Right @vng ?

**Comment by vng** [comment]
we don't

**Comment by bveldkamp** [comment]
Somewhat related, here's a bridge that's used exclusively by buses: https://www.openstreetmap.org/node/1116759198 When zooming out slightly (in OM), neither the bridge nor the buslanes are visible, so there's no indication at all that there is a bridge. It would be nice if bridge shapes could be added.

**Comment by TheAdventurer64** [comment]
> You want to see bridge structure as on pic?
> 
> <img src="https://user-images.githubusercontent.com/720808/180830138-0387e9c4-cc04-4a2e-81f8-3bb53023c460.png" width="400px"/>
> 
> 

How could this (or is it already) implemented?

**Comment by biodranik** [comment]
It requires to add support for that OSM tag type (if it's mapped, of course).

**Comment by AlertSubject** [comment]
Two bridges out of the entire area seem to be rendered properly
![Screenshot_2022-09-04-13-41-48-94_75d0290a7c00525acd83c0ab8700d64c.jpg](https://user-images.githubusercontent.com/72819077/188311536-f0ee4059-6761-478d-9953-b6278edddf71.jpg)

https://www.openstreetmap.org/#map=18/53.55708/9.99760
