### ISSUE TITLE
Strange search ranking 

### ISSUE THREAD

**Issue by dbf256** [organicmaps/organicmaps#3026]
I search for a shop REWE that is close to me and instead of ranking exact match higher it shows different cities that are far away.

Order of screenshots shows search outpit.

![Screenshot_2022-07-25-20-44-27-211804070_app organicmaps](https://user-images.githubusercontent.com/2550295/180852029-9a0490f3-1554-4a77-8a68-65e85253af4d.png)
![Screenshot_2022-07-25-20-44-37-976_app organicmaps](https://user-images.githubusercontent.com/2550295/180852039-d441de34-341a-4477-8c68-a6ca3f6d1b41.png)
![Screenshot_2022-07-25-20-44-47-116_app organicmaps](https://user-images.githubusercontent.com/2550295/180852051-ac6acbcb-0eff-4f13-b651-350cb725ca44.png)

**Comment by PetbkA** [comment]
Another example:
**OS:** LineageOS 17.1 (Android 10)
**OS Language:** EN or RU
**OM:** 2022.07.01-6-FDroid

**Steps:**
1. Scroll to [Church of Saints Simon and Helen](https://www.openstreetmap.org/way/100418249) ("Костёл святого Симеона и святой Елены" in Russian);
2. Search for "Simon" or "Симеон" - the church is at the bottom of the result set - even some hamlets in Grodno are ahead of it. Changing OS locale doesn't help
