### ISSUE TITLE
[turns] Bad exit roundabout number if enter is connected with first exit

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#3027]
For this roundabouts always show actual exit - 1:
https://www.openstreetmap.org/#map=17/45.20871/33.32763
https://www.openstreetmap.org/#map=19/45.20616/33.38493

**Comment by vng** [comment]
Кольца нарисованы так, что конечная точка сегмента входа == начальной точке первого выхода. Программно, мы даже не заехали в кольцо, потому первый поворот и скипается в exitNum. В таком случае и маневр там Turn{Slight}Right без захода на кольцо.

Сложно сказать как (и стоит ли) это разруливать тут ..

**Comment by biodranik** [comment]
Предлагаю посмотреть, что показывает Google и Apple, и сделать так же.

**Comment by AntonM030481** [comment]
1. GraphHopper и OSRM сходятся в том, что этот съезд нужно учитывать при подсчете, когда требуется съезд не с первого кольца. Надо сделать также.
А насчет того, нужно ли для первого съезда говорить что это съезд с кольца или просто поворот - мнения расходятся.
С учетом нашего - "Enter the roundabout", "Exit from the roundabout" - логичнее говорить "Turn right" (особенно если заезд на круг идет по вы), хотя иконку с кругом и первым съездом - возможно, стоило бы показать.
В тоже время, мы ведь говорим "Enter the roundabout", "Exit from the roundabout" даже когда расстояние совсем мало, и логично говорить и показывать одно и тоже, когда расстояние равно нулю, или, например, одному метру.
