### ISSUE TITLE
[iOS] [opening_hour] Non-Business Hours button does not work after midnight

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#3036]
iOS
Last AppStore version (2022.07.01-5)

When editing any opening hours POI, when you have, for example, the following situation:

Open from 14:00-04:00, with 17:00-20:00 off.

At OMaps, when you first add the 14:00-04:00 open/close times, the non-business hour button is then blocked/grayed-out.

If you add manually at Advanced Mode, you can later edit those non-business hours. However, if you edit the opening hours again, the non-business hours disappears too.

**Comment by habi** [comment]
https://user-images.githubusercontent.com/1651235/195829912-ea1773f0-c591-4229-9870-1e03f242d9dc.MOV
