### ISSUE TITLE
[ios]: Update the application URL

### ISSUE THREAD

**Issue by maciboy** [organicmaps/organicmaps#304]
Hi,
I just got the „rate this app“ dialog in the Omaps TestFlight app. After pressing the 5 stars (I really appreciate your work!), I was send to the AppStore and there the original Maps.me app was shown to give the rating.
Just writing this, so you can consider when finally publishing the app in the AppStore :)

**Comment by rtsisyk** [comment]
A good catch. Thank you! We will update the link :)
