### ISSUE TITLE
Wikipedia info looks weird

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3042]
When looking at Wikipedia info on iOS, the way the text is formatted looks strange. Maybe revamping or linking to a POI's Wikipedia page would be better: ![image](https://user-images.githubusercontent.com/50059322/181467154-06a4694f-3288-4970-9b18-60b22d6bd774.png)

**Comment by dvdmrtnz** [comment]
Can confirm. This happens when the app is set to dark mode.

Organic Maps 2022.07.25-6
iPhone 8
iOS 15.4.1

<img src="https://user-images.githubusercontent.com/47610359/181763169-042b602d-b5e2-4e53-99ce-2683cdd9030a.png" width="375"/>

**Comment by endim8** [comment]
Also an issue on android (in dark mode):
![Screenshot_20220731-181524_Organic Maps](https://user-images.githubusercontent.com/26939824/182037910-de526b56-252d-4eac-87c0-553c2e3ce2cc.png)
