### ISSUE TITLE
[generator] Road inherits Wikipedia link from district relation not from street

### ISSUE THREAD

**Issue by strump** [organicmaps/organicmaps#3043]
**Steps to reproduce:**
1. Download Kiev map
2. Navigate to Andriivskyi Descent (Андреевский спуск) https://osm.org/way/8140718
3. Long click on Andriivskyi Descent road

**Expected result:**
PlacePage view shows Wikipedia article for "Andriivskyi Descent"

**Actual result:**
PlacePage view shows Wikipedia article for "Shevchenkivskyi district"
<img src="https://user-images.githubusercontent.com/720808/181489689-a86a9714-78af-413e-9d7e-9e21e3ef41a1.png" width="300px" />

The problem is that road https://osm.org/way/8140718 is part of three relations:
* Street relation [Андреевский спуск (356758)](https://www.openstreetmap.org/relation/356758)
* District relation [Шевченковский район (1755014)](https://www.openstreetmap.org/relation/1755014)
* District relation [Подольский район (1754975)](https://www.openstreetmap.org/relation/1754975)

And Wikipedia link is inherited from the second relation. For example another section of Andriivskyi Descent https://osm.org/way/130279860 shows correct Wikipedia article:
<img src="https://user-images.githubusercontent.com/720808/181490421-9d7861c7-da01-4d4a-b6e3-8d063dc94683.png" width="300px" />

**Comment by vng** [comment]
Fixed in latest data update.
