### ISSUE TITLE
Add splash screen for iOS

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3049]
Currently, there is no splash screen for iOS. Could this be added?

**Comment by biodranik** [comment]
Apple guidelines are different from Android https://developer.apple.com/design/human-interface-guidelines/patterns/launching/

**Comment by Markus40** [comment]
I would prefer the app without the splash screen on Android. A splash screen offers the user no real added value. The delay is not terrible but definitely noticeable. If there was a way to turn it off, I would do it immediately.

It seems that the map does not load in the background, but it is difficult to judge on my relatively fast phone. Would it be possible to load the map in the background and then exit the splash screen?

**Comment by arnaudvergnet** [comment]
The splash screen is shown when the app loads into the phone's memory. Removing it would simply show a blank screen and would not speed up the app.

**Comment by Markus40** [comment]
If that's the case, I don't have a problem with it. I tried an older phone and the duration seemed pretty similar, so I thought it was an artificial delay.

**Comment by TheAdventurer64** [comment]
> Apple guidelines are different from Android https://developer.apple.com/design/human-interface-guidelines/patterns/launching/

I find these guidelines interesting, considering how probably every Google app in existence along with a few other apps (including iOS' GoMap OSM editor) have a splash screen.

**Comment by euf** [comment]
Apple Human Interface Guidelines discourage using splash screens, and they do it for a good reason. It is better to implement a launch screen, which shows a part of user interface available without loading anything else (e.g. a tab bar with no content above it). Here is a good explanation of iOS best practices for launch screens:

https://medium.com/evermos-tech/apples-different-perspective-about-splash-screen-2dfd38f22590

In this fashion, a good launch screen for iOS would look something like that: 

![7AE17B60-B0A3-4DA3-84D9-3EE1C736534F](https://user-images.githubusercontent.com/11754264/182310615-73a6539d-be03-489d-9cd9-20c1b60411fc.jpeg)

**Comment by arnaudvergnet** [comment]
If it can ne animated maybe show a loading indicator on the map as well.

**Comment by biodranik** [comment]
No indicators, please.
