### ISSUE TITLE
[Linux Desktop] Application crashes if name of source code directory differs from default value

### ISSUE THREAD

**Issue by trueTatar** [organicmaps/organicmaps#3058]
The bug occurs in the following circumstances:
- source directory has name, different from 'organicmaps' ('source' in my case);
- application is launched outside of the source code folder.

Log is attached
![log](https://user-images.githubusercontent.com/52957710/181914176-49a77434-b6f7-4675-894b-fa434f1fb54c.png)
Application was built from [[98c5c1b1]](https://github.com/organicmaps/organicmaps/commit/98c5c1b1c05ae3e963a5e0637c246589ed23b736)
OS: Ubuntu 22.04

**Comment by biodranik** [comment]
How would you expect it to guess where is `data` folder located? You can create a symlink to the `data` folder near the binary, or pass data folder as a parameter. Or use default directory name )
