### ISSUE TITLE
Add a generic shop, and a vacant shop to editor

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#3074]
A generic `shop=yes` type in the editor would be very useful, as either the shop type doesn't exist in the editor, or there isn't time to find the correct shop type (eg. mapping from a bus window). perhaps the type could be called 'Unknown Shop'
see https://wiki.osm.org/wiki/Tag:shop=yes for `shop=yes`

`disused:shop=yes` would also be useful

**Comment by 501Ghost** [comment]
shop:fixme=* does currently not exist: https://taginfo.openstreetmap.org/keys/shop:fixme
fixme:shop=* exists 7 times: https://taginfo.openstreetmap.org/keys/fixme:shop

I find it unlikely that anyone would go looking for these rare keys to try and fix them, so I suggest a regular fixme=* instead, or otherwise no fixme at all as shop=yes gives enough indication to mappers that the tagging can be improved.

**Comment by endim8** [comment]
fair point, removed the bit suggesting the fixme 👍

**Comment by biodranik** [comment]
Adding a generic type is not good, especially if this piece of knowledge already exists. Maybe some advanced mode with manual tagging helps?

**Comment by endim8** [comment]
A generic type isn't the best, but it's much better than the POI not being mapped because the user can't find the right type (either due to time constraints, or the type isn't in the list). 

An advanced mode with manual tag entry would also be very nice, but manually typing out tags would take too long in some situations :)

**Comment by 501Ghost** [comment]
"vacant" isn't a type of shop, and a former shop might easily become another type of place (pharmacy, real estate agent, some amenity etc.), so I advise against adding shop=vacant to the list.

**Comment by TheAdventurer64** [comment]
> "vacant" isn't a type of shop, and a former shop might easily become another type of place (pharmacy, real estate agent, some amenity etc.), so I advise against adding shop=vacant to the list.

In that case, is there another way to tag vacant shops?

**Comment by 501Ghost** [comment]
I usually tag [disused:shop=*](https://taginfo.openstreetmap.org/keys/disused%3Ashop) (~39K uses) or [was:shop=*](https://taginfo.openstreetmap.org/keys/was%3Ashop) (~3.6K uses). See also [OSM Wiki: Lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix).

**Comment by TheAdventurer64** [comment]
> I usually tag [disused:shop=*](https://taginfo.openstreetmap.org/keys/disused%3Ashop) (~39K uses) or [was:shop=*](https://taginfo.openstreetmap.org/keys/was%3Ashop) (~3.6K uses). See also [OSM Wiki: Lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix).

What if there are multiple disused shops, then what?

**Comment by 501Ghost** [comment]
Disused shops are not always [verifiable](https://wiki.openstreetmap.org/wiki/Verifiability), so they may not even be worth adding, but if they are and there are multiple in one building, you can map them as nodes in the building. 
The same goes for multiple addresses or active shops in the same building.

**Comment by TheAdventurer64** [comment]
Considering how places marked "don't exist" have editing disabled on Organic Maps, I'm not sure if this is a good idea.
