### ISSUE TITLE
[android]: Editing list name doesn't work - the name is already taken

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#308]
![Screenshot_20210410-224501_OMapsdebug](https://user-images.githubusercontent.com/1799054/114282755-900f9900-9a4e-11eb-9e19-925a36ffecc5.jpg)

**Comment by Endem10n** [comment]
On iOS current behavior is to allow any renaming of the list without any validation, but at the same time during list creation on iOS list name uniqueness validation presents.

![IMG_9332](https://user-images.githubusercontent.com/86627724/124332984-3a511580-db93-11eb-80cf-6c2ac6e5d916.jpeg)
![IMG_9333](https://user-images.githubusercontent.com/86627724/124332992-40df8d00-db93-11eb-966f-82d668ebe616.jpeg)

After killing process and starting app again we can see that renamed lists with the same names were implicitly renamed by the application to become unique:
![IMG_9334](https://user-images.githubusercontent.com/86627724/124332948-1c83b080-db93-11eb-9550-8327c008a378.jpeg)

In case of Android we have list name duplication check both for list creation and list editing user action.
On screenshot above user tries to rename the list to the same name that was before, in this case it looks looks like UX bug. For other cases we should leave validation during name editing, correct?

The other question is: "Should list renaming validation behavior for iOS and Android be the same for consistency?".

@rtsisyk @vng @biodranik

**Comment by biodranik** [comment]
The good question is "What is the best scenario for users?"

**Comment by rtsisyk** [comment]
This problem has been fixed. Thanks @Endem10n!
