### ISSUE TITLE
Show multiple route options

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [organicmaps/organicmaps#3081]
Hi its nice to see that Organic Maps calculate the best route for u but as im on the road more often i noticed that it is not always the best route to follow.

![routes options](https://user-images.githubusercontent.com/73130443/182475671-d84a8af3-4ec8-4cb4-a746-794e77db9e0a.PNG)

Google Maps shows u multiple routes u can choose from before starting to navigate to the destination. I would like to see something similar if possible.

**Comment by biodranik** [comment]
Please search for existing issues with "alternate routes" keywords. Also, note that google knows about the traffic.

**Comment by biodranik** [comment]
See https://github.com/organicmaps/organicmaps/issues/1183, #2153 and #2237

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
apologies for creating a duplicate
