### ISSUE TITLE
Horizontal grey lines in location info cards

### ISSUE THREAD

**Issue by gnojus** [organicmaps/organicmaps#3082]
Hi, I just switched from recent version maps.me, so I don't really know how the interface is supposed to look exactly. However, this seems a bit off:
![IMG_0359](https://user-images.githubusercontent.com/46261165/182485197-50ffe11b-0eff-45f6-9a98-47f426ec4be3.png)
(the grey line below **Vilnius**). It's a bit unstable, but seems to be triggered with system dark mode and organicmaps night mode set to auto.

- iPhone14,4 (15.5)
- Organic Maps 2022.07.26-3

**Comment by dvdmrtnz** [comment]
Fixed in https://github.com/organicmaps/organicmaps/pull/6200
