### ISSUE TITLE
Double road number badge and wrong H-type road badge in Belarus

### ISSUE THREAD

**Issue by DzmitryiK** [organicmaps/organicmaps#3083]
If the road has `ref=*` tag and tied relation also has `ref=*` tag with the same value - road number badge is doubled. Maybe some `ref=*` value duplicate check is needed.

<img src="https://user-images.githubusercontent.com/63190498/182560650-a80a3099-e75e-4261-a065-5c0f2d84d5ad.png" width="400">

[Road](https://www.openstreetmap.org/way/599795177#map=17/53.70956/27.22458)
[Relation](https://www.openstreetmap.org/relation/2569928)

Also I have a question - why in Belarus H-type roads (local highways, like on the screenshot below) are show with black-white colors while according to the rules (and to what's on the ground) - there are red-white road signs.
[Belarus road rules ](https://pdd.by/pdd/ru/sign-5.29.1/)

<img src="https://user-images.githubusercontent.com/63190498/182566116-69c50aaf-a061-4fbc-b30f-2d9a9bd3fcf0.png" width="400">

There is also a bug in showing such roads - on the example above road H9075 is show as P-type road, while it must be shown as H-type. Maybe also because of relation.
[H9075](https://www.openstreetmap.org/way/28324145)
[H9075 relation](https://www.openstreetmap.org/relation/2313911)
[H9031](https://www.openstreetmap.org/way/683771674)

Version: 2022.07.27-3-Google

**Comment by vng** [comment]
Looks like way ref and relation ref are not equal: way has cyrillic "P1" and relation has latin "P1".
Probably, better to normalize osm data ..

**Comment by DzmitryiK** [comment]
Thank you, didn't see that.
What about H-roads?

**Comment by vng** [comment]
Все H-дороги в Беларуси, которые принадлежат отношению с типом network=by:regional, будут рисоваться красным. Остальные H-дороги рисуются по умолчанию _некричащим_ белым.

В вашем примере соседние дороги тоже уже кто-то добавил в by:regional https://www.openstreetmap.org/relation/14417898

Все эти правила можно найти тут https://github.com/organicmaps/organicmaps/blob/master/indexer/road_shields_parser.cpp

**Comment by DzmitryiK** [comment]
А почему выбрано такое правило? Получается, Н-дороги приравниваются к Р и М. А это не совсем корректно, т.к. Р и тем более М - это всегда дороги с хорошим покрытием, а Н может быть вообще голая земля или лесная тропа. 

Может by:regional тоже рисовать некричащим белым?

**Comment by vng** [comment]
Тут не скажу определенно, это правило задали давно еще в MM ..

**Comment by DzmitryiK** [comment]
Ну не знаю, на скрине выше две одинаковые дороги, с одинаковым покрытием и полосностью, но одна в отношении, а другая нет (не была на момент скрина). При этом обе Н, а 9031 даже поважнее будет, чем 9075.

Может @biodranik подскажет, почему так?

**Comment by biodranik** [comment]
Почему ранее кто-то выбрал подсвечивать красным network=by:regional? Лучше спрашивать у беларуского комьюнити OSM, а не у нас. Найдёте подробную документацию по значению этого тега — поделитесь, пожалуйста.

**Comment by DzmitryiK** [comment]
Документация по Беларуси в принципе не очень хорошая. Всё что есть:
[Общая страница по дорожной сети со ссылками на отношения маршрутов и сетей](https://wiki.openstreetmap.org/wiki/WikiProject_Belarus/Road_network#.D0.90.D0.B2.D1.82.D0.BE.D0.BC.D0.BE.D0.B1.D0.B8.D0.BB.D1.8C.D0.BD.D1.8B.D0.B5_.D0.B4.D0.BE.D1.80.D0.BE.D0.B3.D0.B8_.D0.BC.D0.B5.D1.81.D1.82.D0.BD.D0.BE.D0.B3.D0.BE_.D0.B7.D0.BD.D0.B0.D1.87.D0.B5.D0.BD.D0.B8.D1.8F)

На форуме и в вики обсуждений не нашел.

Возможно, такая подсветка была связана с тем, что ранее значения network по Беларуси имели другие значения. Где-то [в 2013-м](https://www.openstreetmap.org/changeset/15853690) М-сеть стала `by` (была `by:national`), Р-сеть стала `by:national` (была `by`), а Н-сеть [стала ](https://osmlab.github.io/osm-deep-history/#/relation/1246286)`by:regional` (была `by`). Может это как-то повлияло на выбор подсветки)

Ну и еще, [вот тут](https://wiki.openstreetmap.org/wiki/WikiProject_Belarus/Road_network/%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D0%B0%D0%BD%D1%81%D0%BA%D0%B8%D0%B5_%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D0%B4%D0%BE%D1%80%D0%BE%D0%B3%D0%B8) есть примечание:

> Применение индекса M или P в совокупности с индексом Н означает дорогу к объекту от республиканской автомобильной дороги

Может для этих случаев делалась красная подсветка?

**Comment by DzmitryiK** [comment]
Немного о том, как Н-дороги обозначаются на других картах, в сравнении с М:

Google
<img src="https://user-images.githubusercontent.com/63190498/188713540-6ebc8939-8649-4b8e-99e2-dd08479b1b99.png" width="400">

Яндекс
<img src="https://user-images.githubusercontent.com/63190498/188713707-b3d35fd8-0759-4b4b-b690-4c2dae9cadd7.png" width="400">


OsmAnd
<img src="https://user-images.githubusercontent.com/63190498/188713755-9bbdb402-f094-4bbf-b03c-c0c6ef7ff3ee.png" width="400">

Apple
<img src="https://user-images.githubusercontent.com/63190498/188714844-2fce2621-7b33-4d6b-8be2-68b63c482730.png" width="400">

И как такие дороги обозначают на местности:
<img src="https://blisch.by/wp-content/uploads/2017/08/20-IMG_20170802_120826.jpg" width="600">
<img src="https://blisch.by/wp-content/uploads/2017/09/05-IMG_20170806_103014.jpg" width="600">


В отношении `by:regional` включены дороги только типа Н.

**Comment by biodranik** [comment]
Надо исправлять. Сможете разобраться?

**Comment by DzmitryiK** [comment]
Если это мне, то да, смогу, но это может быть долго)

**Comment by biodranik** [comment]
Мы не спешим )
