### ISSUE TITLE
[Route Preview]: show topology info for car routes

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#3088]
Topology info is being shown only for pedestrian and bicycle routes, although sometimes it woild be useful in car route (e.g. when planning to drive through mountains).

Suggest to show topology info for car route preview too

**Comment by biodranik** [comment]
Isn't it a duplicate?

**Comment by arnaudvergnet** [comment]
Yep this is a duplicate of https://github.com/organicmaps/organicmaps/issues/1493

**Comment by PetbkA** [comment]
Ooops, sorry :)
