### ISSUE TITLE
Editor breaks some Facebook links

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#3089]
When the Facebook URL is in the format `facebook.com/pages/PLACENAME`, the editor removes the host part so the text shown in the text field is `pages/PLACENAME`. As there is a `/` the input is considered invalid.

| Full URL | URL in editor |
|-|-|
| ![Screenshot_20220804-134316_Organic_Maps](https://user-images.githubusercontent.com/80701113/182839708-f9a8d5fa-f3c1-4a9a-9aa4-b1fdcda72b4f.png) | ![Screenshot_20220804-134328_Organic_Maps](https://user-images.githubusercontent.com/80701113/182839775-a0e329f3-0d0b-4d2a-babd-3830808f3872.png) |

Tested on Android with version 2022.07.27-3-FDroid, but my guess is that it will also happen on iOS as it seems to be handled by the CPP.

**Comment by strump** [comment]
Thanks for example of invalid OM behavior. 
Issue #2787 reports similar error.
I’m gonna fix it in near future.

**Comment by galenasphaug** [comment]
I have noticed the same issue occuring with links directing to FB groups as well.

**Comment by biodranik** [comment]
@galenasphaug  Can you please provide a link to the bad changeset, or paste the wrong contents here?

**Comment by galenasphaug** [comment]
@biodranik https://www.openstreetmap.org/changeset/132701714
I can't upload screenshots here for some reason, but it looks similar to the images above.

**Comment by biodranik** [comment]
@galenasphaug the original issue was about editor complaining to the invalid value in the input. Is it your case? OM's editor should accept both:
1. Full URL to the FB page/group
2. Only the path part (without scheme://host/) to the FB page/group.

CC @strump

**Comment by galenasphaug** [comment]
@biodranik Yes, sorry for the confusion.

Steps to reproduce:

- Select node without a FB link
- Add a FB link to a node (full url)
- Publish chages

Expeted result:
contact:facebook tag is set to Full URL

Actual result:
contact:facebook tag is set to truncated path part of url on OpenStreetMap

In addition, when coming back to edit the URL within OrganicMaps, it will show the truncated URL. After tapping the checkmark to upload changes (keeping the truncated URL as-is), the keyboard will open and the cursor will move to the offending URL, without showing an error message.

Version 2023.02.13-11-Google
![Screenshot_20230218-004018](https://user-images.githubusercontent.com/5401408/219899729-f3d4a5a6-a730-4488-b8a0-0410af05d3d8.png)
![Screenshot_20230218-004012](https://user-images.githubusercontent.com/5401408/219899735-ecb0be03-0ce1-4770-b2e6-9c07487c01dd.png)
