### ISSUE TITLE
Process PH on/off in opening hours

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#310]
Example: https://www.openstreetmap.org/way/395340854

**Comment by vng** [comment]
Hm, but it works on iOS:
![image](https://user-images.githubusercontent.com/175612/117427158-6b172480-af2d-11eb-8eba-7fa1aedeb439.png)

**Comment by tobim91** [comment]
But it only seems to work on iOS did try it few days ago on Android and id didn't show anything with opening hours.
