### ISSUE TITLE
[suggestion] Only search specific string, and within the area

### ISSUE THREAD

**Issue by Shohreh** [organicmaps/organicmaps#3103]
Hello,

I notice the Search feature hasn't improved since forking Maps.me: It still searches all items that contain the letters (or even a bit less, eg. searching "Aldi" also returns "Albi") and even items way outside the map as currently zoomed in.

At least as an option, I suggest limiting the search to…
1. the specific string the user typed (if I typed "Aldi", I don't care about "Ideal Audition")
2. within the map as shown (not 500 miles away)

Cheers,

![image](https://user-images.githubusercontent.com/1541861/183246115-acf8645e-cecf-49e8-9e4d-d7f54d482833.png)

**Comment by biodranik** [comment]
The work is in progress. Did you already check similar existing issues and pull requests?

**Comment by vng** [comment]
Should be better with the next app update.
Common tip: it's usefull to add space to the end, when searching for the full POIs name, like "Aldi "

**Comment by biodranik** [comment]
@vng shouldn't space _filter out_ prefix-matches? If there is a _full match_ without a trailing space, then they should be, obviously, at the top. Most users expect exactly that, without typing additional spaces (how do they know it?).

**Comment by vng** [comment]
- space does filter prefix matches as I mentioned above
- full match factor is better than prefix match of course, but the final rank is a complex function including dozens of factors
