### ISSUE TITLE
Not visible dense POI

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#3112]
When POI are close to each other, they are not visible.

E.g. here: [35.20682, 33.34134](https://www.openstreetmap.org/#map=18/35.20682/33.34134)
Compare OM:
![image](https://user-images.githubusercontent.com/85622715/183292476-6d248624-0540-4d9a-83cc-aa4d88924c23.jpeg)
To competitor:
![image](https://user-images.githubusercontent.com/85622715/183292492-373efa80-5d60-4e55-8311-e5dd18824d27.jpeg)

This is from OSM:
Not so dense as competitor better than OM.
They don't allow overlapping, since icons don't have circle, so it will be ugly.
They use dots if icon does not fit.
![image](https://user-images.githubusercontent.com/85622715/184857401-449c2698-9628-4616-9023-ce418f9ac16e.png)

**Comment by AntonM030481** [comment]
In some cases only overlapping can help (it should be considered as an option).
But in other cases it's possible to draw 2 POI, but for some reason only 1 is visible.

**Comment by biodranik** [comment]
Can someone try overlapping in OM in the same area? Where is it in OSM?

**Comment by AntonM030481** [comment]
Initial post updated.

**Comment by Jean-BaptisteC** [comment]
Improved with new level zoom
