### ISSUE TITLE
allow to set custom bookmarks path

### ISSUE THREAD

**Issue by axet** [organicmaps/organicmaps#3125]
That would be usefull to sync booksmarks using third party software like syncthing.

* https://gitlab.com/axet/omim/-/commit/4ec85b831a5286a5b385833b16b1a28d7785c20d

**Comment by biodranik** [comment]
It won't work on Android 11+ without additional permissions that we don't want/plan to use because of privacy concerns.

**Comment by axet** [comment]
Wrong! All you have to do is implement new android api calls for reading / writing files. `GetFilesByExt` etc...

**Comment by biodranik** [comment]
@axet What exactly is wrong? Do you know any workaround for [Android 11 scoped storage restrictions](https://developer.android.com/about/versions/11/privacy/storage)? We are not aware of any. If you propose to replace all our native file reading code with some Java equivalent, then it won't work. The app become VERY slow.

**Comment by biodranik** [comment]
We are reading megabytes of mwm files in C++. Please don't push if you didn't read our code.
