### ISSUE TITLE
set minimum sdk to sdk16

### ISSUE THREAD

**Issue by axet** [organicmaps/organicmaps#3126]
Hello!

Why not support more devices by lowereing sdk to 16?

* https://gitlab.com/axet/omim/-/commit/5817f32cd8085a6b4e36d6daef7260209b214c14
* https://gitlab.com/axet/omim/-/commit/012e2c974142387a716a06e80b7092fcf008042e
* https://gitlab.com/axet/omim/-/commit/faccf9074e3d0959332d303c096b11b357f02cf8
* https://gitlab.com/axet/omim/-/commit/55da2186a46e859186300d86b5e8c421b93987c2

**Comment by biodranik** [comment]
How much "more"? 0.1% out of all possible users?

There are some technical reasons for API 21. We definitely won't lower it.

**Comment by axet** [comment]
You are speaking with technical. I just point you out technicals reasons for API21: it is only 2 lines of c++ code.

**Comment by biodranik** [comment]
There are several places in our code that require API 21 or greater. We do not want to complicate the support by lowering the API level. The intent would be to _increase_ it, not to _lower_.

**Comment by biodranik** [comment]
FYI: one of the most important reasons for API 21 is proper OpenGL/Vulkan support and better performance/usability for the app. Older devices are too slow for OM.

**Comment by axet** [comment]
Trash taking: "proper openGL support", "technical reasons", "0.1%", no details, no facts. I hope not all orgranicsmaps team like that.

**Comment by biodranik** [comment]
Trash commenting. There are plenty of sources about Android API versions in the wild:
https://gs.statcounter.com/android-version-market-share
https://www.appbrain.com/stats/top-android-sdk-versions
https://www.androidpolice.com/googles-latest-android-version-distribution-numbers-show-11-in-dead-heat-with-10/

Out of these, only a small fraction would ever install or use OM.

You can always fork a project and downgrade it if you want. The source code is open. It may even work for you in some cases.
