### ISSUE TITLE
Place page in iOS inefficiently uses space compared to Android

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#3127]
Android:
![image](https://user-images.githubusercontent.com/85622715/183403212-929456ec-7173-467b-995f-191b509c7aed.jpeg)

iOS (delimiter lines are wider, coordinates are duplicated): 
![image](https://user-images.githubusercontent.com/85622715/183402194-686442a6-ec04-448c-bbda-dff30047caac.png)

**Comment by Jean-BaptisteC** [comment]
Fixed by #6200
