### ISSUE TITLE
Routing error (pedestrian) 

### ISSUE THREAD

**Issue by brunetton** [organicmaps/organicmaps#3133]
## Steps

- do a pedestrian routing from`48.821901, -3.533239` to `48.823211, -3.53412`

## Excepted result 

![Screenshot_20220809_033054_1](https://user-images.githubusercontent.com/86322/183543244-07f008bc-6554-4789-a503-fbaad80d069f.jpg)

## Actual result 

![Screenshot_20220809_033305_app organicmaps](https://user-images.githubusercontent.com/86322/183543534-a26b8f52-39ff-4d1c-a88f-2c1f5b591f25.jpg)

I suppose this is due to the combination of tags on [this way](https://www.openstreetmap.org/way/3033047) 

## Details

Version 2022.07.27-3-FDroid

**Comment by zyphlar** [comment]
Looks like `highway=path` is routable but not `highway=track`?

**Comment by vng** [comment]
Did you have the latest map of this area (check downloader)?
I have this picture, but on current development version:
<img width="709" alt="Screenshot 2022-08-11 at 07 20 47" src="https://user-images.githubusercontent.com/175612/184064296-7c12420f-6034-48de-a34c-ac72d260f706.png">

**Comment by brunetton** [comment]
> Did you have the latest map of this area (check downloader)? I have this picture, but on current development version: <img alt="Screenshot 2022-08-11 at 07 20 47" width="709" src="https://user-images.githubusercontent.com/175612/184064296-7c12420f-6034-48de-a34c-ac72d260f706.png">

Interesting ! Yes I have the last map data (just checked now).
So if the current dev versions fixes this, maybe I can just close this issue and wait for the next version to be released.

Thanks !

**Comment by vng** [comment]
BTW, check you routing settings. Looks like "Avoid unpaved roads" is ON.

**Comment by brunetton** [comment]
> BTW, check you routing settings. Looks like "Avoid unpaved roads" is ON.

OMG you're right ! Why the hell this option is taken into account for **pedestrian** routing ??? I would never have suspected this !

Do I need to open another bug for this ? I mean something like "Avoid unpaved roads shouldn't influence pedestrian routing" ?

Thanks !

**Comment by vng** [comment]
Well, this option worked for cars only some time ago, but we enabled it for all because of several requests in support. Open and existing issue here is that we don't show alert button that avoid options are enabled.

https://github.com/organicmaps/organicmaps/issues/2978

I understand that for pedestrians only "Avoid motorways" is the options that makes sense. Probably, we should reconsider this logic.
