### ISSUE TITLE
Adding new point types

### ISSUE THREAD

**Issue by AlexValue** [organicmaps/organicmaps#3139]
I propose to implement the ability to add (and display on the map) the following points:

- [x] 1) Point of issue of the online store
shop=outpost

- [x] 2) Barbershop
shop=hairdresser
male=yes

- [x] 3) Vending machines
amenity=vending_machine

- [ ] 4) Advertising flag
advertising=flag

- [x] 5) Transformer substation
power=substance

- [ ] 6) Political party
office=political_party

- [ ] 7) Rescuer post
emergency=lifeguard

- [x] 8) Battery drop box
amenity=recycling
recycling:batteries

**Comment by Explorer256** [comment]
Also please also add display of polygons with flowerbeds
landuse=flowerbed

Now they don't show up at all.

**Comment by Kazing** [comment]
There is already issues which contain suggestion for adding things to the map:
* for POI see issue #1917 
* for other stuff please see issue #2873 

Some remarks:
2. shop=hairdresser
currently displayed but without distinction male/female/unisex
3. amenity=vending_machine
Vending machine are displayed on the map; and some vending tag are also specified (see : https://github.com/organicmaps/organicmaps/blob/7a05ecb0596aadc267a6c7bad1e525584e1e9c6a/data/mapcss-mapping.csv#L10887)
4. advertising=flag
man_made=flagpole are already displayed, what is the use case for having specific display when its an advertising flag ?
6. office=political_party
currently displayed as a generic office
8. amenity=recycling & recycling:batteries
It is already displayed on the map

**Comment by Explorer256** [comment]
+ surveillance camera
man_made=surveillance

And her direction by tag
camera:direction=*
https://wiki.openstreetmap.org/wiki/Key:camera%3Adirection

**Comment by matkoniecz** [comment]
Maybe it would be better to close this one and open more specific issues for remaining tasks?

**Comment by matkoniecz** [comment]
>  office=political_party

shown as "office". Do we need super-dedicated support here?

> advertising=flag

why we would need to show it at all? Also

>  man_made=flagpole are already displayed, what is the use case for having specific display when its an advertising flag ?

remains not answered

> emergency=lifeguard

After looking at https://wiki.openstreetmap.org/wiki/Tag:emergency=lifeguard I have no clear idea how to label it 

> It is not to be used map non-permanent locations (e.g. where lifeguards may be found on a beach, but be in a different spot each day). For those situations, see [lifeguard](https://wiki.openstreetmap.org/wiki/Key:lifeguard)=yes.

also, covered by #2656 (which also should be split)

**Comment by matkoniecz** [comment]
overall I would recommend just closing this issue  partially it is done, partially should not be done, partially covered by other issue

**Comment by RedAuburn** [comment]
yeah fair enough, thanks for reviewing them :)

I was considering converting `advertising=flag` to `man_made=flagpole` (360 without man_made), but ultimately we should encourage flags to be tagged with `man_made=flagpole`+`flag:type=advertising` instead :+1:
