### ISSUE TITLE
Street Address seemingly ignored on route

### ISSUE THREAD

**Issue by geofromkc** [organicmaps/organicmaps#3141]
Trying to map an address on a somewhat rural road, although there is a school directly across the road.  OM locates either the beginning of the road itself, or the village that the road is named after.   Google Maps correctly locates the specific street location. 

![OrganicMaps-4100SardisRd](https://user-images.githubusercontent.com/8407803/183719297-e7c78b31-4f73-4945-aae5-c33c7ed41962.jpg)
![OrganicMaps-4100SardisRd-Options](https://user-images.githubusercontent.com/8407803/183719305-b8d1b7f0-989b-408e-9f76-f7b262f6e881.jpg)
![OrganicMaps-4100SardisRd-Short](https://user-images.githubusercontent.com/8407803/183719308-db48674f-14ef-4338-8a9e-b4e1bd931645.jpg)
![GoogleMaps-4100SardisRd](https://user-images.githubusercontent.com/8407803/183719312-be405b71-ffd8-4b1d-afa4-a2b866e0dbee.jpg)

**Comment by geofromkc** [comment]
There are multiple public buildings at this address.   So what does work is to search for the name of the library, or the fire hall, or whatever else is there.   Then OM correctly finds that place and sets the appropriate destination.

**Comment by biodranik** [comment]
Is osm.org data correct there?

**Comment by geofromkc** [comment]
I'm not sure how to verify the data, but visually on the map the destination marked is correct.

**Comment by vng** [comment]
Unfortunately, exact addresses (house numbers) are not mapped in this area https://www.openstreetmap.org/#map=19/40.45790/-79.66468, so the app shows only street.

We are going to use https://openaddresses.io/ someday ..

**Comment by geofromkc** [comment]
That was my conclusion.  I tested another address a few miles away, on a different road, and it worked as expected.  Overall, I like the app.   Nice to have a non-Google alternative.    And thanks for looking into this issue.   I worked for IBM for a long time and did software development and support for a part of that time.   Software is challenging.

**Comment by biodranik** [comment]
@geofromkc you can edit the OpenStreetMap.org and add missing addresses )
