### ISSUE TITLE
[iOS] Show/hide buttons animation.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#3145]
Animation behaves in a different way for the left (layers) and right (position, scales) buttons.
- Layers button moves left when hide and appears from left when show.
- Position and scale buttons _jump left_ and move right when hide and have opacity animation when show.

Imho, behaviour should be the same.

**Comment by AntonM030481** [comment]
Я голову сломал, пока разбирался)
Вроде все просто, анимация в MWMSideButtonsView, но почему оно в горизонтальной ориентации работает,
а в вертикальной нет - непонятно. В горизонтальной оно вообще всегда работает, какие бы параметры не задавай в layoutXPosition.

**Comment by biodranik** [comment]
Надо упрощать код. Может вообще без анимации попробовать?

**Comment by vng** [comment]
Анимации кнопок должны быть, иначе эти пропадания выглядят как баг.

**Comment by AntonM030481** [comment]
Практически во всех современных интерфейсах есть анимации, поэтому логично и нам иметь их.

**Comment by AntonM030481** [comment]
Layers button также имеет анимацию по альфе, я проверил, временно расположив ее дальше от края.
А дергание зума и позиции надо исправить.
