### ISSUE TITLE
When planning a route *not* from current location, one can't use saved "Bookmarks" as destination

### ISSUE THREAD

**Issue by maze88** [organicmaps/organicmaps#3154]
Title say it all; Feature request/suggestion.

### Expected behavior
When planning a route between two remote locations, one should be able to set them not only by searching but also from Bookmarks list.

### Steps to recreate

1. Make sure you save _Location B_ in your **Bookmarks**.
2. Search for _Location A_ and select it on the map.
3. Press "Route From".
4. This is the step I'd expect the above [Expected behavior] to be possible, but one is only able to _search_ for their desired destination (_Location A_).

**Comment by biodranik** [comment]
Is it about adding "Route from/Route to" buttons to bookmarks in bookmark lists?

Now you can select any bookmark and then press "Route from" button.

**Comment by maze88** [comment]
No, it's specifically for the case I described in original post. Specifically when selecting a destination (after selecting an origin).

**Comment by AntonM030481** [comment]
It's possible but not very user friendly (these buttons are present during planning and navigation modes):
![image](https://user-images.githubusercontent.com/85622715/184339571-f4d96125-784f-45fe-8353-4248c66c4abf.png)

**Comment by maze88** [comment]
I have a different icon there - just a big star (bookmarks), but it doesn't allow the desired functionality I described in original post.

Fyi I have version `2022.07.27-3-FDroid`.

**Comment by strump** [comment]
How you can build route from LocationA to any bookmark in OrganicMaps:
1. Select LocationA point
2. Press “Route from” button
3. Press button with star icon on the left side of screen. List of bookmarks will open
4. Select bookmark
5. Press “Route to” button.

Actual result: route from LocationA to bookmark is built.

@maze88 Is this feature you are looking for?

**Comment by maze88** [comment]
> How you can build route from LocationA to any bookmark in OrganicMaps:
> 
> 1. Select LocationA point
> 2. Press “Route from” button
> 3. Press button with star icon on the left side of screen. List of bookmarks will open
> 4. Select bookmark
> 5. Press “Route to” button.
> 
> Actual result: route from LocationA to bookmark is built.
> 
> @maze88 Is this feature you are looking for?

Alright!
That works - thank you!

This issue could be closed, unless someone wants to improve the UX . .
