### ISSUE TITLE
Better support for shop=vacant

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3156]
Currently, `shop=vacant` is currently featured as a generic shop. This is a problem, as a consumer could assume that a vacant shop is an actual shop that's open. When they go to the place, it may be vacant.

To solve this issue, I propose a non editable preset. Similar to the Basketball preset, you can't add basketball features from the map through the editor, but consumers can view the features as such.

**Comment by JLZIMMERMANN** [comment]
shop=vacant is interest for OSM contributors and municipality wishing to knows how many shops remain vacant.
Maybe an expert mode such like for JOSM could be activated for OSM hunters ;-)
Then if there a new shop instead : the preset could be updated.

Personnaly I keep the old tags using the key was:*=*
example [here](https://www.openstreetbrowser.org/#shop/n1272434537/details&map=19/44.13693/4.80903&categories=shop)
![image](https://user-images.githubusercontent.com/4929752/184603434-20503cfa-ed23-43df-a5f4-b200a06f38ce.png)

**Comment by TheAdventurer64** [comment]
> shop=vacant is interest for OSM contributors and municipality wishing to knows how many shops remain vacant.
> 
> Maybe an expert mode such like for JOSM could be activated for OSM hunters ;-)
> 
> Then if there a new shop instead : the preset could be updated.
> 
> 
> 
> Personnaly I keep the old tags using the key was:*=*
> 
> example [here](https://www.openstreetbrowser.org/#shop/n1272434537/details&map=19/44.13693/4.80903&categories=shop)
> 
> ![image](https://user-images.githubusercontent.com/4929752/184603434-20503cfa-ed23-43df-a5f4-b200a06f38ce.png)
> 
> 

The way I see it, if the object visible to ALL users, regardless of whether they contribute to OSM or not, `shop=vacant` should not be marked as a generic shop, as that would imply that the shop is open.

**Comment by JLZIMMERMANN** [comment]
This is why I suggested an **expert mode**.

**Comment by TheAdventurer64** [comment]
Related to #860 and #1068
