### ISSUE TITLE
[android] Place page shortcut buttons inconsitent

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#3157]
When a place has a phone number available, the place page's bottom bar containing actions changes: the `Route From` button gets replaced by a `Call` button. In this case, the share button to the right gets replaced by a `More` button showing a bottom sheet with the replaced buttons.
The same kind of behavior also happens when in planning mode but with a new `Add Stop` button. **So we have 4 different shortcuts positions possible.**

This makes it harder to plan trips: If I want to try routes from different starting points, I must check if the place has a phone number to understand where the different buttons will be.

IMO those action buttons should never change no matter the place page's content so users can rely on muscle memory (they could still change if we are planning/browsing the map).

#### Suggestions
- Remove the `Call` button as users can still click the number in the place page's content.
- In regular map view, always show the buttons in this order (left to right):
  - Share
  - Save
  - Route from
  - Route to
- In planning mode, always show the buttons in this order (left to right):
  - More (with Save and Share in the bottom sheet) 
  - Add stop
  - Route from
  - Route to

This way the most often used buttons will be easier to access. This order could then be mirrored when implementing a left-handed mode.

Here is an example of 2 POIs, one with a phone number and one without in regular and planning modes.

| With phone number | Without phone number |
|-|-|
| ![Screenshot_20220811-093925_Organic_Maps](https://user-images.githubusercontent.com/80701113/184086330-89b7be1f-a6c0-485f-aa24-13df6d3c2ed7.png) | ![Screenshot_20220811-094538_Organic_Maps](https://user-images.githubusercontent.com/80701113/184087214-b82d5640-6638-49c0-8c09-fa0e5ec3864c.png) |
| ![Screenshot_20220811-094943_Organic_Maps](https://user-images.githubusercontent.com/80701113/184087875-7bbdbcab-91e0-4eed-a43f-66124dd1f789.png) | ![Screenshot_20220811-094938_Organic_Maps](https://user-images.githubusercontent.com/80701113/184087871-cbf61a36-3b96-4877-84b6-0eeab244278b.png) |

**Comment by biodranik** [comment]
1. Agree with the call button, it should be consistent.
2. Changing the order of buttons is a no-go at the moment, many people have already used to it.

**Comment by arnaudvergnet** [comment]
If not changing the order, at least we should make it so it does not change with the presence of a phone number.

**Comment by arnaudvergnet** [comment]
Fixed by https://github.com/organicmaps/organicmaps/pull/4174
