### ISSUE TITLE
Change designations for swamp and wet forest

### ISSUE THREAD

**Issue by AlexValue** [organicmaps/organicmaps#3165]
(an offer from a telegram group)
There are 2 problems:

1) The swamp symbol is now displayed in the same color as water, but lighter. It looks like a shoal, not a swamp.
2) The designation of the swamp and the swampy forest are indistinguishable

Users are suggesting adding a texture with horizontal stripes to represent wetlands. For a swampy forest, these can be blue stripes on a light green background, and for a swamp, blue stripes on a light blue background.

**Comment by vng** [comment]
https://github.com/organicmaps/organicmaps/issues/1415

**Comment by pastk** [comment]
Closing as duplicate.
