### ISSUE TITLE
Hotel stars are not displayed in search results on Android

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#317]
5 stars are always displayed, regardless of the actual number of stars.

**Comment by endim8** [comment]
this seems to be fixed
<img width="238" alt="Screenshot 2022-02-11 at 20 57 26" src="https://user-images.githubusercontent.com/26939824/153669719-f00db607-875b-4694-aba9-890f8e9570ba.png">

however, they aren't displayed in the search results on android
