### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by khadeshyam** [organicmaps/organicmaps#3173]
You use Google speech services API so how can you say user's privacy is protected and there's no tracking

**Comment by biodranik** [comment]
User selects which TTS services he/she wants to use. It is his/her decision, not ours. You can install any other TTS engine and use it instead of Google services. Or you can disable the TTS engine completely in Organic Maps Settings.

Does it answer your question?

**Comment by khadeshyam** [comment]
Can't you create your own TTS service?

**Comment by endim8** [comment]
You can install a FOSS TTS engine like [RHVoice](https://f-droid.org/en/packages/com.github.olga_yakovleva.rhvoice.android/).
If Google Speech Services is being used, that means it's installed and set as your default TTS engine. OrganicMaps has no control over what TTS services you choose to install & use on your device.

**Comment by Jean-BaptisteC** [comment]
This message is show by Android, because you try to install APK manually, we can't do anything for this message.

**Comment by meenbeese** [comment]
This issue can be closed now. I believe that all of the concerns of original author are resolved.
