### ISSUE TITLE
Android track recording in background

### ISSUE THREAD

**Issue by ioctl-user** [organicmaps/organicmaps#318]
It's a feature request, not a bug.

For now path recording works only in foreground and only when OMaps in the route navigation mode.
It could be useful to have independent recording working in background.

According to my experiments, there is only one GPS locally working recording tool in the F-Droid, that works fine in Android 11: https://f-droid.org/packages/net.fabiszewski.ulogger/
So, this app can be used as a reference.

**Comment by rtsisyk** [comment]
I have the same problem.

**Comment by rtsisyk** [comment]
Replaced by #512
