### ISSUE TITLE
Better visibility for next turn street/road text

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#3182]
Comparison Waze VS OM.
Waze is much more visible.
- Font 1.4 times larger. Let's copycat.
- Text color is better. Can we use e.g. color of turn sign background?
- Left instead of center text position. Left is better IMHO.
![image](https://user-images.githubusercontent.com/85622715/175496259-e7f71d06-5a96-485b-9131-e7f30200c34c.png)
![image](https://user-images.githubusercontent.com/85622715/175292616-737fd97f-da81-4445-97d0-6a7f11a9d47c.png)

Horizontal mode and CarPlay/AndroidAuto should be considered.

**Comment by biodranik** [comment]
1. Only if it will shrink dynamically to fit a longer street name.
2. We can try, so far it looks more or less ok.
3. Not sure that left is better, need to mock.

**Comment by AntonM030481** [comment]
Now label max lines are 2 for portrait and 1 for landscape (was unlimited).
Font increased from 18 to 24 (like many other fonts on this screen). Scaled till 0.5.

Horizontal. Unscaled.
![image](https://user-images.githubusercontent.com/85622715/185391431-7aa331f6-4717-4645-8d9f-24aae5f423de.png)

Horizontal. Scaled font:
![image](https://user-images.githubusercontent.com/85622715/185390518-25e22ce9-1251-45ed-97ed-2bc18cdda866.png)

Vertical. Scaled and Unscaled.
![image](https://user-images.githubusercontent.com/85622715/185391986-a3bdecc5-5484-422b-88fd-1ea94f01a8b7.png)

**Comment by biodranik** [comment]
Landscape UI definitely needs improvements, similar to CarPlay.

**Comment by AntonM030481** [comment]
It's not so easy now. The question is if we want to make font changes now.
IMHO, yes. Current street names visibility is very low.
