### ISSUE TITLE
[search] Specific village not found

### ISSUE THREAD

**Issue by dreng** [organicmaps/organicmaps#3187]
I just did some search tests because I had the feeling that some things are not found sometimes. This time I searched for the German village "Wald-Michelbach" which hasn't been found in Organic Maps. There's is no problem with that search string at osm.org.

I you have a look at Nominatim https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=537060&class=boundary you will notice a boundary entry and also a village entry. Both are not found in Organic Maps. Instead, there are completely non-sense search results like "Mistelbachweg / Bienenbüttel".

Version is Organic Maps 2022.07.27-3-Google (latest stable)

**Comment by Jean-BaptisteC** [comment]
Can you retry on the latest version?

**Comment by dreng** [comment]
I have just tried it again with version 2024.01.09-6-Google. The village is now found. However, it only appears in 15th position and other, less suitable matches are positioned above it.

I would expect an exact match to be in the first position.

**Comment by biodranik** [comment]
@vng the exact match should be at the top.

**Comment by vng** [comment]
Now:
- The first 2 results are "Wald" strasse in "Michelbach" village on North from Frankfurt. Looks ok here.
- Then 8 results of "Wald-Michelbach XXX" bus stops. Looks ok here. Actually ok here and top these stops are in "Wald-Michelbach"
- Then "Wald-Michelbach" village.

Well, the ranking will be better after adding popularity based on wiki pages (this village has wiki).

Another bad thing here is that "Wald-Michelbach village" shows mostly irrelevant results at first glance.

**Comment by vng** [comment]
UPD: On my dev version now with "popularity" (viewport in Frankfurt):
<img width="1204" alt="Screenshot 2024-01-29 at 13 44 53" src="https://github.com/organicmaps/organicmaps/assets/175612/fb004184-59a5-4d67-a9cb-78d665c4e3d0">
