### ISSUE TITLE
[styles] Add less generic icon for shop=convenience_store

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3195]
Related to #2510, I found a icon for `shop=convenience_store` that's less generic than the current icon, which is currently used for `shop=supermarket` as well.

![image](https://user-images.githubusercontent.com/50059322/185266121-4167b4bb-fcd5-4273-ba52-6641ab592df7.png)![image](https://user-images.githubusercontent.com/50059322/185266137-3b00c4fd-3f49-444b-a92a-81fd2d35dcc2.png)

**Comment by biodranik** [comment]
That's not a clear icon ) What is it?

**Comment by RedAuburn** [comment]
how about this?
https://commons.wikimedia.org/wiki/File:Shop_(50373)_-_The_Noun_Project.svg
![image](https://github.com/organicmaps/organicmaps/assets/26939824/c91a170f-a1bb-4c26-999b-dca2532ea58f)

**Comment by dvdmrtnz** [comment]
I noticed there is already a [convenience-m.svg](https://github.com/organicmaps/organicmaps/blob/master/data/styles/clear/style-clear/symbols/convenience-m.svg) icon on the repo that we are not using. I tweaked it to match a bit the style that @RedAuburn proposed:
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/32ac921a-63e0-4330-ae30-eaebc02a1350" width="32"/>

I think that we could leave the cart icon for `shop=supermarket` and change all the others that are currently using the cart icon to this new icon (`shop=convenience`, `shop=deli`, `shop=farm`, `shop=grocery`,`shop=health_food`)

WDYT?

**Comment by vng** [comment]
Some basket icon?

https://www.google.com/search?q=basket+icon&sca_esv=572370827&tbm=isch&sxsrf=AM9HkKleltBRn6MGrAD8o0NOCy3EsETYhg:1696982225195&source=lnms&sa=X&ved=2ahUKEwiJ8uO11-yBAxWDiJUCHS-7DCsQ_AUoAXoECAIQAw&biw=1496&bih=783&dpr=2

**Comment by patepelo** [comment]
Basket and Trolley are good proposals to differentiate

**Comment by dvdmrtnz** [comment]
Basket:
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/b3634032-b86d-426f-8380-d2239b713818" width="32"/>

**Comment by biodranik** [comment]
Maybe not so bold?

**Comment by dvdmrtnz** [comment]
Like this?:
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/31a2e324-d3e6-42f8-98f3-5bbee1f8d9d1" width="32"/>

**Comment by biodranik** [comment]
Has it become smaller? At 18px it's harder to decipher.

**Comment by dvdmrtnz** [comment]
> Has it become smaller? At 18px it's harder to decipher.

I made some lines thinner, that’s why it looks smaller. What did you mean by "not so bold then?

**Comment by biodranik** [comment]
It usually looks better if the icon fills up the circle, so it's more recognizable in smaller sizes. When you made it thinner, it visually become smaller. Would it be possible to keep the same size but keep it thinner?

**Comment by dvdmrtnz** [comment]
Okay let's see. Made it bigger and white lines thinner:
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/b8e13eee-b904-433f-be1b-385a3cc978cc" width="36"/>


In mdpi (18x18):
![](https://github.com/organicmaps/organicmaps/assets/47610359/adf740f5-1ec3-4450-9bc3-c1b3346cd720)
![](https://github.com/organicmaps/organicmaps/assets/47610359/b2177976-e2a0-475f-80b3-75aefe94e0cb)
