### ISSUE TITLE
[styles] less generic bar icon

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3196]
Related to #2510 and #3195, found a bar icon that's less generic when searching, compared to the normal icon currently used for breweries as well:![image](https://user-images.githubusercontent.com/50059322/185266485-91719c1d-469a-4d33-a30a-d243e2418781.png)![image](https://user-images.githubusercontent.com/50059322/185266488-3f8080b2-f268-4fa8-954c-7abe716bfc39.png)

**Comment by endim8** [comment]
I wish we had the SVGs for these raster icons :|

I'll see if I can remake this 👍

**Comment by endim8** [comment]
fixed by https://github.com/organicmaps/organicmaps/pull/4042
