### ISSUE TITLE
No icon for the Internet Cafe

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3203]
![image](https://user-images.githubusercontent.com/170263/185407403-92937770-4139-4c04-989b-a17ef28a4723.png)

**Comment by dvdmrtnz** [comment]
We could add a symbol similar to the one in OSM Carto. [See wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dinternet_cafe). 

This is how it could look: 

![](https://user-images.githubusercontent.com/47610359/185762366-25886c4d-1173-4822-8a29-99585662f542.png)

What do you think?
