### ISSUE TITLE
ModuleNotFoundError: No module named 'maps_generator.generator'; 'maps_generator' is not a package

### ISSUE THREAD

**Issue by glencoe2004** [organicmaps/organicmaps#3205]
Trying to generate a map, but keep getting this error:

```
$ python maps_generator.py --countries="Canada_Ontario_London" --skip="Coastline" 
Traceback (most recent call last):
  File "/home/kali/Documents/organicmaps-master/tools/python/maps_generator/maps_generator.py", line 6, in <module>
    from maps_generator.generator import stages_declaration as sd
  File "/home/kali/Documents/organicmaps-master/tools/python/maps_generator/maps_generator.py", line 6, in <module>
    from maps_generator.generator import stages_declaration as sd
ModuleNotFoundError: No module named 'maps_generator.generator'; 'maps_generator' is not a package
```

May be a dependency issue? Not sure, as pip tells me all dependencies are already satisifed.

**Comment by endim8** [comment]
You need to CD to the parent folder of `maps_generator` (`organicmaps/python/tools/`) before running the generator command :)

**Comment by glencoe2004** [comment]
Thanks, the command runs now!

Now getting an `assert USER_RESOURCE_PATH is not None` error, but progress!

**Comment by endim8** [comment]
For `assert USER_RESOURCE_PATH is not None` check your `tools/python/maps_generator/var/etc/map_generator.ini`
has correct paths for `BUILD_PATH` & `OMIM PATH`

eg. here's mine:
```
BUILD_PATH: /Users/endi/Documents/Git/omim-build-release
OMIM_PATH: /Users/endi/Documents/Git/organicmaps
```

I really need to finish updating the map generator docs 😅
