### ISSUE TITLE
Add icon for ATM in POIs

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#3209]
Similar to https://github.com/organicmaps/organicmaps/issues/1301, I think it would be useful to add an ATM icon in the Place Page of POIs that have the [atm=yes](https://wiki.openstreetmap.org/wiki/Tag:atm%3Dyes) tag, next to the wheelchair icon that we currently display.

We could use the ATM emoji icon: 🏧 (https://emojipedia.org/atm-sign/)

**Comment by patepelo** [comment]
Good idea, similar to #5883

This would be maybe also good to consider with vegan friendly places:

![image](https://github.com/organicmaps/organicmaps/assets/23003127/6f7c01df-e710-4954-ad05-cf895f7ab04a)
