### ISSUE TITLE
[POI]: add shop=medical_supply

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#3217]
There are many [medical supply](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dmedical_supply) shops (orthopedic, for instance), but there's no such type in OM. I suggest to add it

**Comment by biodranik** [comment]
Are there already other meta issues with proposals to add some types?

**Comment by PetbkA** [comment]
@biodranik , indeed. Sorry, will add it to #1917
