### ISSUE TITLE
Commons link prefix is duplicated, breaking the link

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#3220]
Clicking on the commons of this object: https://www.openstreetmap.org/node/565594680

Results in this broken link: https://commons.m.wikimedia.org/wiki/Https://commons.wikimedia.org/wiki/File:Anchor_Iron,_Greenwich.jpg

**Comment by vng** [comment]
Is it current production version form store? Seems like everything is fine on current master with fresh data.

**Comment by biodranik** [comment]
@endim8 do you click from Android or Desktop?

**Comment by endim8** [comment]
this is now fixed 👍
