### ISSUE TITLE
Select bookmark list when saving poi

### ISSUE THREAD

**Issue by bveldkamp** [organicmaps/organicmaps#3232]
I have one general bookmark list, ie 'my bookmarks', and I also imported several kml's, which appear as additional lists. 

Now, if I try to save a location to my bookmarks, it will always store it in a different list (the last one I added?). There doesn't seem to be a way to change this behaviour, or even to move a bookmark to a different list.

I'm not sure if this is a bug, an oversight, or the intended behavior. Maybe someone can shed some light on this.

**Comment by biodranik** [comment]
You can edit/change the list of the selected/added bookmark. Then new bookmarks will be added to that "last used" list.

**Comment by bveldkamp** [comment]
Hmm, I changed the name of the My Bookmarks list, but new bookmarks are still added to another 'last used list.

**Comment by GreenAloe** [comment]
it works for me like this:
1. add new bookmark
2. swipe up => edit bookmark
3. change list
4. next bookmark will be added to the last list

**Comment by bveldkamp** [comment]
Thanks @GreenAloe (and @biodranik , now that I understand how to do it, I see that you were probably referring to the same functionality, it was just me failing to see how it works).

**Comment by biodranik** [comment]
Can this issue be closed?
