### ISSUE TITLE
Use mimic 3 for TTS when available 

### ISSUE THREAD

**Issue by Outlet2048** [organicmaps/organicmaps#3235]
Has anyone ever considered bundling these voices with organic maps?

https://mycroft.ai/mimic-3/

Quite a few languages are already supported and it sounds much better than default TTS
A huge bonus for magic earth is having actual human voices you can download. OM still uses the default TTS engine as far as I'm concerned. 
Perhaps it would be neat to let the user download these voices (optional download) and use that instead
I'd happily sacrifice a few MB of free storage if my ears will get some rest from androids default TTS engine

The company behind mimic 3 is also privacy focused and very open source friendly
Might make it easier to work with

**Comment by Ferenc-** [comment]
Depends on what you mean by bundling.
Mimic3 appears to [have AGPL 3 License](https://github.com/MycroftAI/mimic3/blob/master/LICENSE).
I might be wrong, but as far as I know, that doesn't allow for example packaging it together with [OrganicMaps's Apache 2.0 LICENSE](https://github.com/organicmaps/organicmaps/blob/master/LICENSE), without relicensing the end result to AGPL3 as well.
But the interfaces provided by Mimic3 could still be legally used, as long as they are distributed in a separate package.

**Comment by AlertSubject** [comment]
By bundling I meant adding voices using mimic 3 and letting the user download them

If I'm not mistaken then it would be possible to generate all the necessary audio files and let the user download those files. Instead of generating audio on the go locally

**Comment by arnaudvergnet** [comment]
Mimic  3 only runs on Linux so it would not be possible to generate voices on the go on Android/iOS.

A solution would be to generate the files on each new release and host the results on OM's website.

**Comment by AlertSubject** [comment]
> A solution would be to generate the files on each new release and host the results on OM's website.

Yes, that's what I meant with downloading them
Could be done similar to how map updates are downloaded and probably wouldn't take up much storage

To me this would make me enable voice guidance during navigation whereas currently I wouldn't ever do that due to default TTS

**Comment by biodranik** [comment]
Can you please link this issue with other similar issues?

**Comment by TheAdventurer64** [comment]
#1875 and #2178 are related (adding 2148 this TTS sounds more natural imho)

**Comment by AlertSubject** [comment]
https://github.com/organicmaps/organicmaps/issues/2178#issuecomment-1048166964

Looks like option two seems to be available :)

**Comment by AlertSubject** [comment]
> Can you please link this issue with other similar issues?

TTS related issues that can / might be fixed by implementing this approach:
https://github.com/organicmaps/organicmaps/issues/2200
https://github.com/organicmaps/organicmaps/issues/2178

**Comment by RedAuburn** [comment]
closing as out of scope, the correct resolution here would be for someone to develop a MIMIC 3 implementation for android, which uses the standard TTS API.
