### ISSUE TITLE
PT routing unavailable

### ISSUE THREAD

**Issue by rawder** [organicmaps/organicmaps#324]
Perhaps, no route data and "Start" button invisible.
![photo_2021-04-22_13-38-36](https://user-images.githubusercontent.com/33424706/115701396-6a4c9300-a370-11eb-8145-607f3e2288dd.jpg)

**Comment by vng** [comment]
![image](https://user-images.githubusercontent.com/175612/115985102-e8987780-a5b2-11eb-8fbd-34af6a11cebc.png)

В режиме ОТ нет кнопки Начать ..

**Comment by Endem10n** [comment]
Checked on different versions of maps.me, starting from 8.6.2(released on December 2018).

In case of building route using PT option "Start" button was never visible. So in case of original feature looks like it was product decision not to show this button, but not a bug, according to current code base it also looks so. 
Maybe, someone knows or has idea, why it was implemented in a such way initially?

Screenshots of routing result from maps.me 9.1.7

![Screenshot_1625145441](https://user-images.githubusercontent.com/86627724/124132576-4351c200-da81-11eb-997e-b1ec38757355.png)

![Screenshot_1625147420](https://user-images.githubusercontent.com/86627724/124135400-10f59400-da84-11eb-8fba-7305c2ff8f0c.png)

**Comment by pastk** [comment]
- #5331
