### ISSUE TITLE
Question: what is the exact meaning of the elevation number?

### ISSUE THREAD

**Issue by RobertoRoos** [organicmaps/organicmaps#3244]
See for example the screenshot from the main website: 
<img src="https://organicmaps.app/images/screenshots/hiking.jpg" alt="screenshot" width="300"/>

How the elevation number 705m made up?

I can think of several meanings:

- Absolute sum of all climbs and descents
- Sum of all climbs only
- Relative difference between starting point and end

Maybe it would be good the explain the number somewhere?

**Comment by RobertoRoos** [comment]
I thought I might figure this out by analyzing one section of path. Here are screenshots of three routes:

<img src="https://user-images.githubusercontent.com/12717020/186357955-66d9d3f5-3cc4-43c4-9657-074325301feb.png" alt="screenshots" width=750/>

These routes are i) up the hill and back, ii) down hill and iii) up hill.

They all show the same elevation number, so none of the three meanings I described above can be correct.

Maybe the meaning is instead:

- Absolute sum of climbs or absolute sum of all descents (whichever is higher)

**Comment by dvdmrtnz** [comment]
The behavior of that feature is changing in the next release. See https://github.com/organicmaps/organicmaps/pull/3062 for more details

**Comment by RobertoRoos** [comment]
Ah, I see. So from the code the current meaning is the difference between the highest and lowest point during the route. So 'double climbs' won't affect the number. The new behavior sounds better.

Looking forward to the new release!
