### ISSUE TITLE
Render cycleways at highway=path + bicycle=designated

### ISSUE THREAD

**Issue by jekhor** [organicmaps/organicmaps#3246]
I have found that Vilnius mappers map sidewalks with cycleway+footway parts by combination of tags highway=path + bicycle=designated + foot=designated. This ways are rendered in OM as paths and give no information about presenting of cycling facilities.
The default OSM render and OSMand render such paths as cycleways. This approach do not have information about pedestrian facilities but looks as a reasonable compromise.

So, a proposal is to render them in OM by similar way.

For example, see https://www.openstreetmap.org/way/176663512#map=19/54.69725/25.27212

![image](https://user-images.githubusercontent.com/117467/186398528-355fe3df-b73b-478c-822c-c8ae2bda5169.png)
![screenshot](https://user-images.githubusercontent.com/117467/186398880-6ece526e-7bd2-4635-ace2-fcb234ac2a9a.jpg)

**Comment by kaneap** [comment]
Also see my related issue #1796

**Comment by pastk** [comment]
It was fixed in https://github.com/organicmaps/organicmaps/pull/7878
