### ISSUE TITLE
[search] Category results with names are better than without.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#3247]
Names don't make any sense in ranking for many categorial search like "bench".

Check here: https://www.openstreetmap.org/#map=19/38.70454/0.03705

**Comment by biodranik** [comment]
Думаю это можно надёжнее всего решить специальной подсказкой с иконкой (или текстом типа "search benches only"), по клику на которые будут искаться только ТИПЫ, без матчинга по именам.
