### ISSUE TITLE
[search] ranking issues

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#3249]
In this screenshot, the POI "Asda - Supermarket - 0.8 mi" should be the top search result

potential issues:

- the ranking prioritises results with more words, even over an exact match
- café & bakery types seem to have a higher priority than supermarket (i don't know if this is actually how it works)

searching from here: [geo:51.47890,0.01062](geo:51.47890,0.01062)
![Screenshot_20220824-203353_Organic Maps](https://user-images.githubusercontent.com/26939824/186507596-e94effbd-be7f-4c68-9fa7-181e99e95ec3.png)

**Comment by biodranik** [comment]
Is it the recent master?

**Comment by endim8** [comment]
> Is it the recent master?

yep

**Comment by biodranik** [comment]
Does it change if you add a space after the word?

**Comment by endim8** [comment]
> Does it change if you add a space after the word?

The results are the same
![Screenshot_20220825-230504_Organic Maps](https://user-images.githubusercontent.com/26939824/186777343-653857b9-e6f8-4aa2-bb5a-9fae461f73b2.png)

they also remain the same when capitalising, with and without the space

**Comment by vng** [comment]
Well, yes, "Eat" category has better rank than "Shop" category in search.
Probably, this ranking _factors_ shouldn't be so distinct (like 0.8 mi vs almost 10 mi).
