### ISSUE TITLE
[editor] searching for the type "kitchen store" doesn't work, but it appears when searching for "furniture store"

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#3250]
![Screenshot_20220824-205336_Organic Maps](https://user-images.githubusercontent.com/26939824/186511092-cb126968-ba5b-47de-a3ee-f47c54ccf21f.png)

**Comment by biodranik** [comment]
Is it a recent master?

**Comment by endim8** [comment]
> Is it a recent master?

yup, most recent
