### ISSUE TITLE
Unable to install app from releases

### ISSUE THREAD

**Issue by DeiAsPie** [organicmaps/organicmaps#3253]
Unable to install app from releases section of the project's Github on CalyxOS (Android 11).

**Comment by endim8** [comment]
That's very vague, is there an error message? It works fine for me

**Comment by DeiAsPie** [comment]
All I see is `App not installed`. And that is the case even though the app has been removed/UN-installed from the system (so I assume it's not a signature conflict)

**Comment by biodranik** [comment]
@DeiAsPie can you please send us (or check yourself) `adb logcat` logs after installing the apk via USB using `adb install`? There should be an error reason.

**Comment by DeiAsPie** [comment]
@biodranik Thanks you suggestion worked. For some reason it was retaining the signature even after the app was uninstalled. The issue got fixed when uninstalled the app via adb(`adb uninstall app.organicmaps`)

Thanks again! I couldn't figure this out for a while
