### ISSUE TITLE
Category search can't find by full name

### ISSUE THREAD

**Issue by strump** [organicmaps/organicmaps#3260]
**Steps to reproduce:**

* OrgancMaps for iPad v.2022.08.23-3, or OM for Android v.2022.07.27-3
* Set Ukrainian locale
* Open Organic maps and create new POI
* In categories search enter "Витвір"

**Expected result:** Category "Витвір мистецства" (which means Artwork) is found
**Actual result:** No categories found
<img src="https://user-images.githubusercontent.com/720808/186888306-d3252de9-4583-44e2-b1a0-0631c60a6889.png" width="300"/>

But if I search by "Твір мистецтва" or "Скульптура" then category is found:
<img src="https://user-images.githubusercontent.com/720808/186888488-f469b064-1097-4952-9c1f-1f3dee1ed42a.png" width="300px"/>
<img src="https://user-images.githubusercontent.com/720808/186888494-0d30b0ff-3eb5-4fbe-94b2-b779c891df94.png" width="300px"/>

Looks like `NewFeatureCategories::Search(std::string const & query)` method only looks for string from `categories.txt` but ignores `type_strings.txt`.

**Comment by endim8** [comment]
https://github.com/organicmaps/organicmaps/issues/3250 i just had a similar issue, i submitted a temporary fix, but using `type_strings.txt` would be much better 👍

**Comment by biodranik** [comment]
@vng what if we merge types strings into loaded categories?

**Comment by vng** [comment]
- Having _all_ types as search categories is not a good idea
- Search categories should _inherit_ type strings as we discussed for many times
- I suspect that this issue not only about category-type strings. Strange behaviour according to screenshots, should investigate.

**Comment by pastk** [comment]
Same as #8290, but the latter is better described / illustrated.
So closing this one in favor of
- #8290
