### ISSUE TITLE
Check elevation data.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#3265]
Build route [from](https://www.openstreetmap.org/node/1929932097) [to](https://www.openstreetmap.org/node/948646637)
Elevations should be from approx 660 to 724 according to the OSM data. But we have from 564 to 575

**Comment by jpds** [comment]
I've also observed that from `51.50990, 0.00065` to `51.50811, -0.00409`, Organic Maps reports that there's a 100m drop somewhere.

![signal-2022-08-31-133819_002](https://user-images.githubusercontent.com/29158971/187680229-0f2eca2c-960d-4e9d-a9ac-55a4b129de1e.jpeg)

But that entire road is basically flat, so I don't know where this comes from.

**Comment by vng** [comment]
Will be fixed with the next data update.
