### ISSUE TITLE
Exclude private swimming pools from search

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3269]
When looking for swimming pools, many users will probably search for "swimming pools". The problem is that private residential pools will show up in the result, along with other swimming pools open to the public.

**Comment by biodranik** [comment]
Recently icons for private gardens were fixed by creating a separate type, could it also work for pools? #3179

**Comment by dvdmrtnz** [comment]
As far as I know, this is fixed. Swimming pools tagged with `access=private` don't show up on search anymore.

**Comment by patepelo** [comment]
This change has been very positive for improving appealing. Would you consider going one step further and not to include plain leisure=swimming_pool that has no other besides access=private? Maybe only include access=* [not private]

The general situation with OSM database currently is that the majority of swimming pools are private but aren't tagged correctly yet and the this happens:

![image](https://github.com/organicmaps/organicmaps/assets/23003127/146566a8-f7b2-43f0-b148-4df29823a19e)
