### ISSUE TITLE
Generic shop category with custom icon

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3270]
Despite `shop=musical_instrument` displaying a unique icon, it still has a generic "Shop" category shown.

![image](https://user-images.githubusercontent.com/50059322/187022267-002db460-5329-4273-b3d3-d3edb2a5f2ea.png)

**Comment by TheAdventurer64** [comment]
Looks related to #2511

**Comment by dvdmrtnz** [comment]
Closing this as right now the correct name shows fine:

![](https://github.com/organicmaps/organicmaps/assets/47610359/cfeadbf8-2be1-4685-b2dc-593654ea9e2d)
