### ISSUE TITLE
24 vs 12 hour time

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3272]
Preferred time system should be consistent.

![image](https://user-images.githubusercontent.com/50059322/187022931-83a2fc5b-d4f5-471a-8c1f-e6bc8b1139a7.jpeg)
![image](https://user-images.githubusercontent.com/50059322/187022959-a34ebaec-bd03-43d0-8b89-4b725b4c5ffd.jpeg)

**Comment by biodranik** [comment]
Code in PlacePagePreviewViewController should be rewritten to use locale-dependent hour formatting.
