### ISSUE TITLE
[ios] Make Headers Bold

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3280]
Similar to Android, would it be possible to bold the top header of the UI on iOS?

Comparison: 

**Android**
![image](https://user-images.githubusercontent.com/80093621/152206606-2fbd46ad-70fb-4870-9ebf-bea089d8e635.jpeg)
(Taken from #2003)

**iOS:**
![image](https://user-images.githubusercontent.com/50059322/187051027-a2b35320-8a93-4073-a2b4-a839bda5c944.jpeg)

**Comment by AE542** [comment]
Hi there. It should be possible to change the UI Navigation bar's font attribute to be bold. I had a look at the AboutController and it seems it can be done in there. I was experimenting a bit with it but have yet to run it on a device. Would it be possible to have a go at this one?

Thanks for your time.

**Comment by TheAdventurer64** [comment]
> Hi there. It should be possible to change the UI Navigation bar's font attribute to be bold. I had a look at the AboutController and it seems it can be done in there. I was experimenting a bit with it but have yet to run it on a device. Would it be possible to have a go at this one?
> 
> 
> 
> Thanks for your time.

I think you should just go for it. 😄

**Comment by AE542** [comment]
Ok I'd like to have a go. I'm just having problems running the app, (specifically 'glm/gtc/type_ptr.hpp' file not found, when I cloned it) . Do you have a readme on how to initially start up the app?

**Comment by TheAdventurer64** [comment]
> Ok I'd like to have a go. I'm just having problems running the app, (specifically 'glm/gtc/type_ptr.hpp' file not found, when I cloned it) . Do you have a readme on how to initially start up the app? 

See [INSTALL.MD](https://github.com/docs/INSTALL.md).

**Comment by pratyaksh1610** [comment]
@biodranik  @TheAdventurer64 
Is it required to change the text to `bold`, as after app inspection I found that all the headers are in default state i.e `not bold`  , like `settings` , `bookmarks` and others, I think headers must have similar properties like size and font.
PTAL.
Thanks.

**Comment by TheAdventurer64** [comment]
> @biodranik  @TheAdventurer64 
> 
> Is it required to change the text to `bold`, as after app inspection I found that all the headers are in default state i.e `not bold`  , like `settings` , `bookmarks` and others, I think headers must have similar properties .
> 
> PTAL.
> 
> Thanks.

That was my intention. I'd like all Headers to be bold.

**Comment by angelina-p09** [comment]
Hello! below are some screenshots that show how the headers look bold and in 20 size font. The first three images are of an iPad and the middle three are on an iPhone 5s and the last two are from an iPhone 13. Please let me know if there are any changes that you would like me to make to the header. I look forward to any feedback. 

<img src=https://user-images.githubusercontent.com/124469658/222036712-976f3e11-ebc1-4975-8280-0daf94be4802.png width=40% height=40%>

<img src= https://user-images.githubusercontent.com/124469658/222036714-876253e2-be77-4fa8-b9c6-451ddf9ad71f.png width=40% height=40%>

<img src=https://user-images.githubusercontent.com/124469658/222036715-7ff615df-37f7-4454-a1aa-1d562e8ed7e9.png width=40% height=40%>

<img src=https://user-images.githubusercontent.com/124469658/222036719-50c59919-46c0-407e-808e-2ab6b855d2f2.png width=40% height=40%>
<img src=https://user-images.githubusercontent.com/124469658/222036720-557fa43f-ab94-4d6c-a91f-e90bf5003f7e.png width=40% height=40%>
<img src=https://user-images.githubusercontent.com/124469658/222036722-22677eee-c8e2-438e-96c3-33c0725598fc.png width=40% height=40%>

<img src=https://user-images.githubusercontent.com/124469658/222038679-559c1353-5c22-42e9-a27e-376bdc78f628.png width=40% height=40%>
<img src=https://user-images.githubusercontent.com/124469658/222038680-bd4d265e-18a5-4707-bdad-289f27791b84.png width=40% height=40%>
