### ISSUE TITLE
[iOS] "Report a bug" doesn't jump to default mail app

### ISSUE THREAD

**Issue by sanketgarade** [organicmaps/organicmaps#3281]
The "report a bug" link jumps to outlook app on iPhone and gmail app on iPad, even though the default mail app on both devices is the Mail app.

OM Version: ⁦2022.08.23-3⁩

**Comment by habi** [comment]
On my iPhone (iOS 15.6.1) it simply opens up a new email in Mail.app.
But I also don't have Outlook nor Gmail installed.
