### ISSUE TITLE
Add generic amenity icon

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3289]
Considering how many amenities don't have icons on the map, we should have a generic icon dedicated to amenities without specific icons.

**Comment by biodranik** [comment]
Leaving them without an icon is a better idea to avoid map pollution.

**Comment by TheAdventurer64** [comment]
> Leaving them without an icon is a better idea to avoid map pollution.

IMHO, having generic icons is better, as other navigation apps (Google and Apple Maps) have them. From my POV, I would probably think the app is broken if I didn't see any icons for certain places.

**Comment by biodranik** [comment]
It motivates people to contribute )

Please don't forget that we've manually chosen the most popular/useful types for the map. Drawing "everything" without filtering may degrade maps usability significantly.

**Comment by RedAuburn** [comment]
the amenity key covers a huge amount of things, including a lot of things that would definitely create clutter eg. grit bins, tables, chairs. so agreed that it's better to add specific types.
