### ISSUE TITLE
Strange road rendering

### ISSUE THREAD

**Issue by starsep** [organicmaps/organicmaps#3295]
Strange road rendering at 40.640484, 22.940303
I haven't checked current tagging, perhaps there is something wrong with OSM data.
![Screenshot_2022-08-30-14-18-21-83_75d0290a7c00525acd83c0ab8700d64c](https://user-images.githubusercontent.com/2798728/187423593-2e562f68-c83a-4fbc-bc42-00e4d4aef3d0.jpg)

**Comment by habi** [comment]
Around https://www.openstreetmap.org/relation/8004337

**Comment by habi** [comment]
The roundabout has a very large amount of nodes, they maybe trip up the OM renderer.

BTW: There was a note about the park there, which I just fixed now; https://www.openstreetmap.org/note/3338206, but I didn't touch the roundabout :)
