### ISSUE TITLE
Train station is rendered twice

### ISSUE THREAD

**Issue by habi** [organicmaps/organicmaps#3297]
This [OSM Note](https://www.openstreetmap.org/note/3333877) mentions that the train station in Morges, Switzerland is shown twice in OrganicMaps.

Indeed there are two 'train station' thingies there, once [Node 3081154409](https://www.openstreetmap.org/node/3081154409) as `railway=station` (which would regard as correct one, with [`uic
_ref`](https://wiki.openstreetmap.org/wiki/Key:uic%20ref) and Wikidata and once [Way 86759698](https://www.openstreetmap.org/way/86759698/), which is the station building mapped as `building= train_station`.

I think it would be best to only render only *one* public transport icon in this case, not two, as shown in the screenshot below.

![IMG_0742](https://user-images.githubusercontent.com/1651235/187446509-60fa5aff-d91c-48a5-bf2c-9d12fb71b79c.PNG)

**Comment by biodranik** [comment]
@vng Is it because we match the building to the train station type?

**Comment by vng** [comment]
building=train_station is drawing like railway=...

**Comment by biodranik** [comment]
building=* types are NOT amenities, they definitely should not have an amenity-like icon. Maybe only the corresponding translation when a building is selected.
