### ISSUE TITLE
[Routing] Foot routing is *very* weird

### ISSUE THREAD

**Issue by habi** [organicmaps/organicmaps#3298]
On vacation I wanted to check how far we are from an intermediate destination on our hike to tell our kids how long it's still going to take :)

I selected 'Foot' routing from [somewhere in the vicinity of here](https://www.openstreetmap.org/way/835077025#map=19/46.42256/11.61751) to [this memorial](https://www.openstreetmap.org/node/5825475253). In my opinion, it's evident that OrganicMaps should figure out to route me along [the Hirzelweg](https://www.openstreetmap.org/way/835077025) and tell me 'it's going to take about 25 minutes'.
I was quite baffled that OM chose to route me perpendicularly up the mountain to it's [peak](https://www.openstreetmap.org/node/6853104331) and around the backside for a *much* longer journey.

A screenshot of the 'wrong' route is shown below.

![IMG_0482](https://user-images.githubusercontent.com/1651235/187449462-d96772e2-42e5-4a75-b9ab-7e512af1a77a.PNG)

**Comment by habi** [comment]
Maybe related to https://github.com/organicmaps/organicmaps/issues/3285, as I've also seen that.

Sometimes 'foot' routing fails. e.g. from approximately [here](https://www.openstreetmap.org/node/9401926458) to [here](https://www.openstreetmap.org/node/2709438596), which is not needed for *routing* per se, but telling kids how long it will approximately take :)

![IMG_0742](https://user-images.githubusercontent.com/1651235/187450406-44449f7c-2be2-4a1a-86e5-e570d1ede026.PNG)

**Comment by biodranik** [comment]
Thanks! Let's fix it so kids will be properly informed next time :) 
Routing can fail if OSM paths are not connected with each other. Did you test it on the latest app/data version?

**Comment by habi** [comment]
I just tried again with OM version 2022.08.23-3 and "OpenStreetMap data: 16 August 2022".

![image](https://user-images.githubusercontent.com/1651235/188299977-c4f47661-d784-42a4-a98f-7fb475a89902.png)

OM refuses to route over https://www.openstreetmap.org/way/835077025/ no matter how much I try to coerce it ;)

**Comment by habi** [comment]
Routing on OSM works as expected:  https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=46.42616%2C11.61399%3B46.41383%2C11.62302#map=14/46.4200/11.6185

**Comment by biodranik** [comment]
@vng can surface=gravel influence foot nav? Foot nav should ignore some surface types, or treat them as equal.

**Comment by vng** [comment]
I have good pedestrian road here. @habi BTW, do you have any "Avoid roads" options enabled? We have a bug when "Avoid gravel" also influence on pedestrian routing. On the other hand, why not to avoid if its set ;)

**Comment by habi** [comment]
Indeed; avoid unpaved roads, because I've used OM with a rented car before...

![image](https://user-images.githubusercontent.com/1651235/188321148-d1c9e59c-3b6e-4942-8704-e1c413af78c0.jpeg)

**Comment by habi** [comment]
When I turn the 'avoid unpaved roads' setting off, foot routing works as expected.

![image](https://user-images.githubusercontent.com/1651235/188321507-0384c222-aabb-4af6-87ab-60e3fd228cb6.png)
