### ISSUE TITLE
Android: publish the app on F-Droid

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#33]
This OSS project should meet F-Droid guidelines.

**Comment by relan** [comment]
F-Droid maintainer here.

Kudos for starting this fork!

F-Droid main repo [includes only free software](https://f-droid.org/docs/Inclusion_Policy/). OMaps in its current shape is _not free_ because of those Gradle plugins:

* com.google.gms.google-services
* com.google.firebase.crashlytics
* com.google.firebase.appdistribution

and those libraries:

* all com.google.android.gms:*
* all com.google.firebase:*
* [com.flurry.android:analytics](https://mvnrepository.com/artifact/com.flurry.android/analytics/12.1.0)
* [com.mopub:mopub-sdk-native-static](https://mvnrepository.com/artifact/com.mopub/mopub-sdk-native-static/5.10.0)
* [com.appsflyer:af-android-sdk](https://mvnrepository.com/artifact/com.appsflyer/af-android-sdk/4.9.0)

I personally would love to see all this removed and can help with F-Droid inclusion then.

**Comment by nicolasmaia** [comment]
Is it possible to make a gradle flavor without these dependencies?

**Comment by relan** [comment]
Just checked the snapshot tagged as 2021-05-08. The good news is that I managed to build it without proprietary dependencies in the F-Droid environment! There are still a few issues left.

A major issue: missing `private.h`. OMaps just crashes because of missing server URLs. You should either fill all the constants to make OMaps work out-of-the-box or allow users to configure them on start. F-Droid does not sign up for keeping any "secrets" like API keys.

And a few minor notes:

* Versioning. The versionName and versionCode are include a Git hash and current date (see `getVersion()` in `build.gradle`). This won't work in F-Droid, versionName and versionCode must be constant across multiple `gradle` runs.
* Proprietary dependencies conditions. `googleFirebaseServicesEnabled` and `googleMobileServicesEnabled` make no sense for us as we still remove references to non-free Gradle plugins and libraries to avoid their downloading and accidental use. If those conditions were added only for F-Droid, you can safely drop them to simplify build.gradle.

**Comment by rtsisyk** [comment]
Hey @relan, thank you for your work making F-Droid package real. I [took a look at F-Droid scripts](https://gitlab.com/rtsisyk/fdroiddata/-/tree/organicmaps), but I didn't have time to finish this work.

> Proprietary dependencies conditions. googleFirebaseServicesEnabled and googleMobileServicesEnabled make no sense for us as we still remove references to non-free Gradle plugins and libraries to avoid their downloading and accidental use. If those conditions were added only for F-Droid, you can safely drop them to simplify build.gradle.

You are right, `googleFirebaseServicesEnabled` and `googleMobileServicesEnabled` flags were added **especially** for F-Droid. Please note that these flags not only remove Google/Firebases libraries, but also override some Java sources. For example,  `googleMobileServicesEnabled` enables enhanced implementation of LocationProvider which relies both on GPS and Google data.  F-Droid users will wait for location 5-10 minutes instead of 5-10 sec, but I hope that it is an informed choice.

>Versioning. The versionName and versionCode include a Git hash and the current date (see getVersion() in build.gradle). This won't work in F-Droid, versionName and versionCode must be constant across multiple gradle runs.

Please feel free to send PRs to this repo instead of patching our build.gradle from the build scripts. You can add an optional parameter to disable automatic version generation and use this flag from F-Droid scripts.

**Comment by rtsisyk** [comment]
@relan, it would be nice if you could combine [@linsui](https://gitlab.com/linsui/fdroiddata/-/commits/omap), [my](https://gitlab.com/rtsisyk/fdroiddata/-/tree/organicmaps) and your changes into a new MR to [fdroiddata](https://gitlab.com/fdroid/fdroiddata). We are busy with fixing the codebase itself.

**Comment by gerion0** [comment]
> You are right, `googleFirebaseServicesEnabled` and `googleMobileServicesEnabled` flags were added **especially** for F-Droid. Please note that these flags not only remove Google/Firebases libraries, but also override some Java sources. For example, `googleMobileServicesEnabled` enables enhanced implementation of LocationProvider which relies both on GPS and Google data. F-Droid users will wait for location 5-10 minutes instead of 5-10 sec, but I hope that it is an informed choice.

Thank you for your work, just to clarify: With [UnifiedNlp](https://github.com/microg/UnifiedNlp), MicroG provides a google free reimplementation to use GPS + cell/wifi data from e.g. Mozilla (well supported by F-Droid). Afaik, this can even be used on non rooted phones. Will Organicmaps use that within the F-Droid build, too? I have also installed the APK of Organicmaps from Github on a Google services free Android with UnifiedNLP and showing the current location works very well.

**Comment by Victor239** [comment]
> GitHub APK *HAS* Google Services included. But F-Droid wants us to remove these services for some unknown reason. We are added to such option to meet requirements.

He was referring to microG allowing the use of **generic** location services via UnifiedNLP, instead of dependent on Google's specific one. This would be much faster and more accurate at obtaining location than relying on simply GPS.

**Comment by relan** [comment]
> F-Droid users will wait for location 5-10 minutes instead of 5-10 sec, but I hope that it is an informed choice.

Sure.

> You can add an optional parameter to disable automatic version generation and use this flag from F-Droid scripts.

Once you release a stable version, it'll have a fixed version name and version code, won't it?

> it would be nice if you could combine @linsui, my and your changes into a new MR to fdroiddata. We are busy with fixing the codebase itself.

Sure, don't spend your time making a recipe for F-Droid, we'll do that.

> But F-Droid wants us to remove these services for some unknown reason.

We keep only free software in our main repository, i.e. all parts of an app must be free. The com.google.android.gms:* libraries are proprietary, so they have to be excluded.

Could you comment about the missing `private.h`?

**Comment by rtsisyk** [comment]
> Once you release a stable version, it'll have a fixed version name and version code, won't it?

We are happy with the automatic version generation. It gets the version number from the last git commit, i.e. version generation is deterministic. Do you have better ideas?

> Could you comment about the missing private.h?

`private.h` is created by `./configure.sh` or you can just copy `private_default.h` to `private.h`. The only missing part is the server address. The traffic is expensive and we did't want other forks to parasite on our infrastructure. The current plan is to create a new URL especially for F-Droid. This URL will be included to the main repository and enabled by default.

**Comment by relan** [comment]
> We are happy with the automatic version generation. It gets the version number from the last git commit, i.e. version generation is deterministic. Do you have better ideas?

Fixed version name/code better fit our workflow, but it makes little sense to introduce them specifically for F-Droid. We can force any version name/code in our recipe.

> The current plan is to create a new URL especially for F-Droid. This URL will be included to the main repository and enabled by default.

OK, will wait until this happens because builds without this URL are useless. Thanks!

**Comment by rtsisyk** [comment]
https://github.com/organicmaps/organicmaps/pull/398

**Comment by rtsisyk** [comment]
@relan do you need any help with F-Droid integration? Please contact us via TG, Email or here if you have some problems.

**Comment by relan** [comment]
> do you need any help with F-Droid integration?

Everything's OK now, thanks a lot for your help! Here is a recipe: https://gitlab.com/relan/fdroiddata/-/blob/omaps/metadata/app.omaps.yml

Waiting for a stable release.

**Comment by rtsisyk** [comment]
Wre are updating applicationId to app.organicmaps. This change is already in master. A new version will be tagged after merging pending PR. Google ask us to remove mandatory location permission.

**Comment by rtsisyk** [comment]
Hey @relan, you could start integrating 2021-05-21 into the main F-Droid repository. We will publish this release as soon as it reaches Google Play. Probably tomorrow. This release already have a new applicationId.

**Comment by relan** [comment]
> you could start integrating 2021-05-21 into the main F-Droid repository

Done: https://gitlab.com/fdroid/fdroiddata/-/commit/2360a00d7ab0740ff28cc91196f7726d36878480. Will be available in a few days.

**Comment by rtsisyk** [comment]
We're finally there! Thanks a lot!

**Comment by relan** [comment]
Available on F-Droid now: https://f-droid.org/packages/app.organicmaps/

Note that new versions have to be added manually: automatic detection works only when version code and version name are defined as literals.

**Comment by bristow** [comment]
Thanks for this !!

We need a big button on website nom ;)

![image](https://user-images.githubusercontent.com/1156507/119684217-9ca45100-be44-11eb-8664-4d65402578dd.png)

**Comment by rtsisyk** [comment]
> Note that new versions have to be added manually: automatic detection works only when version code and version name are defined as literals.

@relan how to update the app? What should be done to get automatic updates? Could you please show me a script which parses build.gradle to get version?

**Comment by relan** [comment]
> how to update the app?

Through merge requests to https://gitlab.com/fdroid/fdroiddata.

> What should be done to get automatic updates?

Define version name and version code as literals in build.gradle or AndroidManifest.xml:

    versionName "1.2.3"
    versionCode 123

That's because build.gradle is a program that can do any kind of nasty things, we cannot run it without isolation. But spawning 3161 VMs every day to check for updates is not feasible. So, we rely on static parsing only.

> Could you please show me a script which parses build.gradle to get version?

The entry point is here: https://gitlab.com/fdroid/fdroidserver/-/blob/master/fdroidserver/checkupdates.py

**Comment by biodranik** [comment]
Manual updates should be fine for now. Hardcoding versions into the manifest is not convenient for other stores.

**Comment by rtsisyk** [comment]
> Through merge requests to https://gitlab.com/fdroid/fdroiddata.

OK, created https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9126

> Define version name and version code as literals in build.gradle or AndroidManifest.xml:
>
> versionName "1.2.3"
>versionCode 123

I think we can define a static version name and code as literals in build.gradle, but override this version later dynamically. I don't see any problems bumping version on every release (=tag), but we also want dynamic versions for every commit.

**Comment by rtsisyk** [comment]
This ticket is done, I'm closing it for the planning purposes, but we can continue discussion here.

**Comment by rugk** [comment]
The update problem just came up in https://github.com/organicmaps/organicmaps/issues/818#issuecomment-875952176. And I have to say, especially given your update schedule (quite fast), manual updates are really not a future-proof way IMHO.

For more information, see https://f-droid.org/en/docs/FAQ_-_App_Developers/#do-i-need-to-tell-you-when-i-update

AFAIK you can [choose another update mode](https://f-droid.org/en/docs/Build_Metadata_Reference/#UpdateCheckMode) based on git tags, e.g. instead, if that better suits.

or shall I open a new issue for that?

**Comment by rugk** [comment]
Finally opened a new issue about automating this: https://github.com/organicmaps/organicmaps/issues/825
