### ISSUE TITLE
FlatIcons

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3311]
Considering how OrganicMaps sources icons from FlatIcons (eg. toilet and cinema icons) we should probably cite them properly. Per [their attribution guidelines](https://support.flaticon.com/s/article/Attribution-How-when-and-where-FI?language=en_US), we should put credits for them in the app stores' descriptions.

**Comment by biodranik** [comment]
Wow, that's a complexity that is better to avoid (including translations!). It would be way easier to use icons from other sources instead.

CC @rtsisyk @vng

**Comment by rtsisyk** [comment]
We should not have any icons from Flaticon. At least we didn't take any graphics from them intentionally. Primitive icons can look very similar.

According to my records, toilet was taken from Material Design Icons and Cinema from Font Awesome.  If you 100% sure that icons are from Flaticons - please let us know and we will replace them.

ICON NAME | ICON SET | ICON ORG NAME
-- | -- | --
ic_category_toilet | Material Design Icons | ic_wc_24px
ic_category_toilet_night | Material Design Icons | ic_wc_24px
cinema-m.svg | Font Awesome Free | Local Movies

**Comment by TheAdventurer64** [comment]
> We should not have any icons from Flaticon. At least we didn't take any graphics from them intentionally. Primitive icons can look very similar.
> 
> 
> 
> According to my records, toilet was taken from Material Design Icons and Cinema from Font Awesome.  If you 100% sure that icons are from Flaticons - please let us know and we will replace them.
> 
> 
> 
> ICON NAME | ICON SET | ICON ORG NAME
> 
> -- | -- | --
> 
> ic_category_toilet | Material Design Icons | ic_wc_24px
> 
> ic_category_toilet_night | Material Design Icons | ic_wc_24px
> 
> cinema-m.svg | Font Awesome Free | Local Movies
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

I checked, and I couldn't find anything on Material Design Icons for toilet icons used in OM after doing a quick search. Regarding Cinema, the category list and search icon both use the old logo from MAPS.ME.

**Comment by rtsisyk** [comment]
> One more thing: https://github.com/organicmaps/organicmaps/pull/3302 uses icons from FlatIcons.

#3302 was reworked to remove Flaticons before getting merged, please see https://github.com/organicmaps/organicmaps/pull/3302#issuecomment-1236120352.  I am adding a new mandatory legal/license review for all new graphics to prevent copyrighted graphics from getting in (see #6438). 

Let's work on replacing icons we can't identify the source. "Entertainment" category icon should be replaced? @TheAdventurer64 do you see any other issues?
