### ISSUE TITLE
Ottawa is rendered twice

### ISSUE THREAD

**Issue by keunes** [organicmaps/organicmaps#3313]
When not having downloaded the map of the region, at a specific zoom level, the city of Ottawa is shown twice on the map:
![Screenshot_20220901-092914.png](https://user-images.githubusercontent.com/11229646/187929236-56f3fb2e-6fe2-4776-ace3-609cf28147b9.png)

2022.08.23-5-FDroid

Maybe duplicate of #3297?

**Comment by biodranik** [comment]
What is there in the OSM?

**Comment by Jean-BaptisteC** [comment]
Maybe Organic Maps show name of the city and name of county ?
County of Ottawa https://www.openstreetmap.org/relation/4136816#map=10/45.2507/-75.8015
City of Ottawa https://www.openstreetmap.org/node/18886011

**Comment by keunes** [comment]
The one on the right: https://omaps.app/csESG0wrhj/Ottawa

On the left: https://omaps.app/csESGCuciX/Ottawa

Maybe these codes are of any use?

**Comment by biodranik** [comment]
@keunes what is displayed in the Place Page Info if you select these objects?

**Comment by keunes** [comment]
@biodranik For both I see the same thing (except, I suppose, the coordinates):
![Screenshot_20220902-104029.png](https://user-images.githubusercontent.com/11229646/188173920-1de5c03e-ce70-4fac-92f2-f7ac2e8a64c1.png)

**Comment by biodranik** [comment]
@vng could it be a point feature from the relation? https://www.openstreetmap.org/relation/4136816#map=10/45.2502/-75.8009

**Comment by vng** [comment]
https://github.com/organicmaps/organicmaps/issues/2310#issuecomment-1087278293
https://github.com/organicmaps/organicmaps/issues/2035

**Comment by keunes** [comment]
Thanks @vng. Should I close this one, given that it's (probably) covered in (one of) the other ticket(s)?

**Comment by vng** [comment]
No, please, keep it open! I suspect that this issues has similar roots, but not 100% sure.

**Comment by neilguertin** [comment]
Maybe one is at the node and one is at the geographic center or bounding box center of the city boundary? And the difference in Ottawa and Reykjavik is large enough to show at world map zooms?

There are some differences in the two places of each city. Here is Reykjavik before and after downloading.
![reykjavik1-world](https://user-images.githubusercontent.com/8312387/200893520-4797063d-9bd4-4f30-a3e3-783b9fd39fee.png) ![reykjavik2-world](https://user-images.github.usercontent.com/8312387/200893533-709b3edd-badb-4e1f-91f7-1a615bcd08ff.png)
![reykjavik1-local](https://user-images.githubusercontent.com/8312387/200893541-f0ef75df-f98e-4839-8fe2-2df7fb4da307.png) ![reykjavik2-local](https://user-images.githubusercontent.com/8312387/200893550-652f4a37-2925-4de6-af8c-6d9f08b7911c.png)

Note the difference in name. The one at the city center is Reykjavík (with accent on the i). The other one is Reykjavíkurborg. I'm not sure where it's pulling the names from, but some possibilities are
name=Reykjavíkurborg
name:en=Reykjavik
alt_name=Reykjavík
wikipedia=is:Reykjavík
wikidata=Q1764

Here is another clue from Linux desktop: 
![image](https://user-images.githubusercontent.com/8312387/200895116-e74ddfa9-bdf2-45b3-93d3-cbfdbf648a88.png)
![image](https://user-images.githubusercontent.com/8312387/200895190-00ffcf57-26d3-4833-8034-2d83f21ad4a6.png)
The second city has Raw Types = place-city-capital-6. I see this in Ottawa too, and not on any of the non-duplicated capitals.

I also found that Tehran is duplicated too. It shows the same issues, different name when clicking on it on mobile, and different Raw Types (place-city-capital-7 this time) when clicking on it on desktop.

**Comment by Mr-Mime** [comment]
Some more info which might be helpful:

Same for Berlin. Here it is a (IMHO) faulty polygon of the Berlin border in the OSM data.
In the OSM editor you can see the single polygon on the right.

| OMAPS | The region in OSM Editor |
| --- | --- |
| ![signal-2022-11-10-111210](https://user-images.githubusercontent.com/37423773/201063803-4e95504e-2e01-483c-97ef-a811141c8b4d.png) | ![2022-11-10-103242_escrotum](https://user-images.githubusercontent.com/37423773/201062758-fce23cfd-9b13-49c6-b781-d9ee22e506b5.png)


The issue with Ottawa seems to have been fixed in OSM Data, as I do not see a duplicate in Omaps (2022.11.02-2-FDroid).
Seems like [this changeset](https://www.openstreetmap.org/relation/4136816#map=10/45.2478/-75.8029) removed faulty border polygons there.
<img src="https://user-images.githubusercontent.com/37423773/201064577-10cc2202-b7b3-4f0a-ba7d-54aa9efa8d04.png" width=200px />

**Comment by neilguertin** [comment]
How did https://github.com/organicmaps/organicmaps/pull/4093 resolve this? Was it an OSM data issue?

**Comment by biodranik** [comment]
It's a result of our experimental changes to the generator.

**Comment by map-per** [comment]
It could also be that Ottawa was fixed in this changeset removing `place=city` from the relation (https://www.openstreetmap.org/changeset/126288137).
