### ISSUE TITLE
Cuisine Alias search issue

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3317]
Searching for "gelato" should give results for ice cream shops, as gelato is an alias for `amenity=ice_cream`. However, searching for "Ice Cream" vs. "Gelato" gives very different results.

Searching for ice cream:
![image](https://user-images.githubusercontent.com/50059322/188047409-f41010d5-c43b-4c76-8911-bffe1b89896c.png)

Searching for gelato:
![image](https://user-images.githubusercontent.com/50059322/188048113-8d95a1f5-0bd6-44f6-b8c7-d7469f112c50.png)

**Comment by biodranik** [comment]
@vng could it be some bug that gelato matches only those features where is more than one type?
