### ISSUE TITLE
Searching for partial word gives better results than full word:

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3318]
Searching for part of gelato gives better results than the word gelato itself: 

Searching for part of gelato:![image](https://user-images.githubusercontent.com/50059322/188048391-f7090d72-60cc-4430-8f54-cc11a8e0bde2.png)

Searching for the full word gelato:![image](https://user-images.githubusercontent.com/50059322/188048712-6e14de6f-6863-498b-8e3c-d073d0fba8e9.png)

From what I can tell, searching for gelato is supposed to give results for `amenity=ice_cream` (its an alias), and when it does, it omits results with "gelato" in the title.

**Comment by biodranik** [comment]
Is it the latest iOS version?

**Comment by TheAdventurer64** [comment]
> Is it the latest iOS version of OM?

Yes.
