### ISSUE TITLE
"Rate the app" opens up the donate page 

### ISSUE THREAD

**Issue by pratyaksh1610** [organicmaps/organicmaps#3319]
I think  it should point to a rating page or similar to that.

<p float="left">
  <img src="https://user-images.githubusercontent.com/76740999/188058697-6b0e6b75-0f34-4f0c-87b0-f45aacde9a31.jpeg" width="300" />
</p>

**Comment by biodranik** [comment]
Are you using the FDroid build? FDroid doesn't have any rating pages.

**Comment by pratyaksh1610** [comment]
In  `master` branch , under the help section `Rate the app.`

**Comment by endim8** [comment]
in this case, it would be better to remove the "rate the app" element for fdroid & web builds

**Comment by biodranik** [comment]
No, it would be the best to replace "rate the app" with "Donate".

**Comment by TheAdventurer64** [comment]
> No, it would be the best to replace "rate the app" with "Donate".

I thought about that, but isn't there already a Donate button?

**Comment by pratyaksh1610** [comment]
> > No, it would be the best to replace "rate the app" with "Donate".
> 
> I thought about that, but isn't there already a Donate button?

I think there is no `Donate` button, so we can rename `rate the app`.

**Comment by pratyaksh1610** [comment]
I think then the icon needs to be changed too.

**Comment by pratyaksh1610** [comment]
@biodranik Can we remove `rate the app` as there is already a donate button.

**Comment by biodranik** [comment]
@rtsisyk let's hard-code Donate instead of Rate for FDroid.
