### ISSUE TITLE
Wikipedia article is hidden when you set bookmark

### ISSUE THREAD

**Issue by csidirop** [organicmaps/organicmaps#3321]
I don't know if this is known or maybe intended, but setting a bookmark hides the Wikipedia article. Plus, I can't find a way to show it again. 

Tested on multiple points.
The screen recording is too big for github at this moment, I can add it later if needed.

Version: 2022.08.23-5-Google

**Comment by biodranik** [comment]
Please check github for duplicate issues.

**Comment by arnaudvergnet** [comment]
Duplicate of https://github.com/organicmaps/organicmaps/issues/2825

**Comment by csidirop** [comment]
Oh, I must have missed it somehow
