### ISSUE TITLE
Download maps with PC/curl

### ISSUE THREAD

**Issue by cscode2000** [organicmaps/organicmaps#3341]
How to run OM on a device with no internet connection?
I'm desperately looking for the mwm-files (at least for Germany). 

OSM/OBF-files can be downloaded without problems, so OSMAnd runs completely offline, as OM should do, too. On the BBBike-Service there's no option for "mwm".

IMO it should be no problem to provide links to the files for the newest app-version, because the current apk can be downloaded, when the map-format has changed. Thank you.

**Comment by endim8** [comment]
there's a mirror here: http://omaps.webfreak.org/maps/ but it would definitely be better if there was a proper frontend for it. this also ties into #1801 as there is currently no way to import an MWM file without root

**Comment by rtsisyk** [comment]
@cscode2000 could you please tell us more about your use case? Why do you want to download it manually?

**Comment by cscode2000** [comment]
@endim8 Thanks a lot, this was very helpful! Couldn't find these links myself. Now I can run OM and it seems to work fine and very fast. It seems to be less powerful than OSMAnd, but I missed contour lines there during hiking or biking and found no way to use them, although I downloaded/activated the plugin and SRTM-files... In this case OM is much easier.
Thanks once again!

**Comment by HeldHannes** [comment]
If you load the map-files from a computer, how do you get OM to import/recognize the files in the end?
