### ISSUE TITLE
[android] Add an icon when current location is unknown and is not actively searched

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#3361]
See https://github.com/organicmaps/organicmaps/pull/2905#issuecomment-1214151890:
> is it hard to add a different icon state when the current location is unknown and is not actively searched? So users can understand it and press the location button to refresh it? Maybe a crossed location arrow would be understandable.

**Comment by rtsisyk** [comment]
> See [#2905 (comment)](https://github.com/organicmaps/organicmaps/pull/2905#issuecomment-1214151890):
> 
> > is it hard to add a different icon state when the current location is unknown and is not actively searched? So users can understand it and press the location button to refresh it? Maybe a crossed location arrow would be understandable.

We have crossed out the location icon already.
