### ISSUE TITLE
Why surface=compacted is considered as paved road?

### ISSUE THREAD

**Issue by DzmitryiK** [organicmaps/organicmaps#3363]
Highways with `surface=compacted` are considered as paved, when routing option to avoid unpaved roads is enabled. As for me, they more like `surface=gravel`, which is unpaved.

Example:
[highway](https://www.openstreetmap.org/way/232685585)

<img src="https://user-images.githubusercontent.com/63190498/188718742-c8ba5035-f3c3-4547-ad8b-0e84acc12687.png" width="400">

Version: 2022.08.23-5-Google
Map data: 16 Aug 2022

**Comment by biodranik** [comment]
This surface type is definitely better than gravel, and is close to a paved one. If it saves a lot of time for a driver in some cases, then better not to change it.

**Comment by DzmitryiK** [comment]
I thought the avoid "Unpaved roads" option avoids ALL unpaved roads, not ALMOST ALL )
It may be close to paved, but it is still unpaved ([OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:surface)). It turns out there is a slight mismatch between the name of the option and how it works.

I have another example.
The route is [Pastavy](https://www.openstreetmap.org/node/242978929) - [Braslaw](https://www.openstreetmap.org/node/119357582).

<img src="https://user-images.githubusercontent.com/63190498/192610247-78edb6bf-9578-4b14-b87c-c625eec23b0d.png" width="400">

Why does OM route through compacted roads when there is a good alternative - [national highway P27](https://www.openstreetmap.org/relation/2796635) (which is primary, has asphalt pavement, maxspeed and lanes mapped)?

H2107 is [compacted ](https://www.openstreetmap.org/way/97618416)
<img src="https://user-images.githubusercontent.com/63190498/192611083-9ada8030-7296-451a-81e1-6d255e916cc5.png" width="400">

H2119 is [compacted](https://www.openstreetmap.org/way/97532057)
<img src="https://user-images.githubusercontent.com/63190498/192611523-3fb753e1-7d36-49cc-a3d9-dd9f8d1fa641.png" width="400">


Route through this roads would definitely take more time than through P27.

[OSMR ](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=55.1129%2C26.8400%3B55.6393%2C27.0318) and [GraphHopper](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=55.1129%2C26.8400%3B55.6393%2C27.0318) are using P27.


Version: 2022.08.23-5-Google
Map data: 16 Aug 2022

**Comment by endim8** [comment]
It'd be cool if instead of road surface, we stored a value, eg.

0 = asphalt
1 = cobble
2 = gravel
3 = compacted
4 = mud

then have a slider from 1-4 (etc) to allow the user to select the minimum surface condition they want to route across

**Comment by vng** [comment]
This case is fixed with the new data update. We have a separate issue about surfaces [here](https://github.com/organicmaps/organicmaps/issues/2704)
