### ISSUE TITLE
Can't send a note to OSM editors on Unknown place

### ISSUE THREAD

**Issue by DzmitryiK** [organicmaps/organicmaps#3364]
There is a way to send a note via Edit place button.  
But when I tap on a place with not tags ("empty" place) - there is only "Add a place to the map" button. 

![image](https://user-images.githubusercontent.com/63190498/188720208-63960f77-9da9-4677-aba6-c138773e61be.png)

I can add an object and write a note in addition screen, but what if there is no appropriate object on the list? Or I just want to note that there is a polygon object, like swamp? 

Edit place button could help there.

**Comment by janusbenissa** [comment]
"but what if there is no appropriate object on the list?"
You can use the edit function from OSM.

**Comment by endim8** [comment]
also see #266
