### ISSUE TITLE
[android] Regression in the bottom bar in 2022.08.11

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#3389]
Two problems:

1. Buttons are overlapped by the system control
2. Buttons are not on the right place horizontally

![image](https://user-images.githubusercontent.com/1799054/189522006-d3ae44d8-604c-4a8f-a5e2-ee22c2e9efaf.png)

**Comment by arnaudvergnet** [comment]
> Buttons are overlapped by the system control

What version of Android are you using? It works as expected on my test devices.

> Buttons are not on the right place horizontally

https://github.com/organicmaps/organicmaps/pull/3353 changed the position of buttons to make it easier to use with one hand.

**Comment by arnaudvergnet** [comment]
I tried latest master on Pixel emulators running Android 5, 11 and 12 and could not reproduce your issue.

**Comment by rtsisyk** [comment]
> What version of Android are you using? It works as expected on my test devices.

Android 12. I made that screenshot on the first run from `master` after upgrading from the previous version. Surprisingly, but on the second run, buttons were not overlapped. I am trying to reproduce this issue one more time.

**Comment by rtsisyk** [comment]
@arnaudvergnet , this bug reproduces only on the first start without downloaded maps. Subsequent runs are OK. Try to uninstall the app and/or clear data (on a debug app). I can see the same behavior both on Android 12 (Samsung 10) and Android 13 (Pixel 4a).

**Comment by arnaudvergnet** [comment]
Strange I can't seem to reproduce it by following your steps.

**Comment by rtsisyk** [comment]
The problem exists, but I don't know how to reproduce it. This screenshot is from Huawei P30 with enabled navigation bar. 

![photo_2022-09-18 09 57 08](https://user-images.githubusercontent.com/1799054/190889753-2c880b35-e4e1-4194-8fe0-85c961409013.jpeg)

**Comment by rtsisyk** [comment]
@arnaudvergnet , I was able to reproduce the problem above on one of my devices.

1. Enable navigation bar if not enabled:
   * Settings -> System -> Gestures -> 3-button navigation (stock Android, most devices).
2. Kill the app
3. Try to open any [omaps://](https://omaps.app/g4CNuz0APo/Paris) link from any source

https://user-images.githubusercontent.com/1799054/190891061-91879bf1-9495-4d73-b7dd-5b18d4495001.mp4

**Comment by arnaudvergnet** [comment]
Thanks a lot I managed to reproduce it! I will see what I can do about this.

**Comment by rtsisyk** [comment]
This issue also predictable reproduces without navigation bar. The first clean version (without data) always has overlapping gesture bar on the first launch. I think that this is the same issue as with navigation bar.

**Comment by arnaudvergnet** [comment]
The code to position the UI elements only checks "system window insets", meaning everything which is not from the app. The navigation bar creates one of those insets no matter its nature: gesture bar, 3-button bar or even 2-button bar. Depending on the navigation bar type, the size and position of the inset will change.

Here the issue seems to be the call to get the system window insets is done at the wrong time, when the navigation bar is not available. I don't understand how it is possible but I will look into it.
