### ISSUE TITLE
[search] 'hairdresser' provides correct results, but 'hairdressers' doesn't

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#3401]
(this is using a build with the latest search fixes, which has massively improved searching)

It seems that an `S` suffix produces incorrect results.

![egfdgdg](https://user-images.githubusercontent.com/26939824/189949478-bbf58da4-3440-4d7a-83e6-d1dddd99a508.png)
location of search: `51.47760, 0.01212`

the same happens for greengrocer/greengrocers & optician/opticians (likely others too)

**Comment by biodranik** [comment]
For many languages with plural endings (парикмахерСКИЕ, stelleN, cajeroS automáticoS) a simple if can help:
if some category name matched token's prefix, then count it as a full/exact category match.

**Comment by vng** [comment]
Here is a bit different case. We _do_ match hairdresser**s**, but ranking is not good.

**Comment by biodranik** [comment]
The fix is to match/rank exactly in the same way (if there are no name matches, of course). 

After implementing the proposed if, only few exceptions can be manually added to categories for the ideal ranking.

**Comment by endim8** [comment]
this is still an issue after https://github.com/organicmaps/organicmaps/pull/5323

**Comment by vng** [comment]
@endim8 This is a separate mystic issue and I will investigate it now. The ranking is unstable (and becomes good) after several requests "hairdresser" and "hairdressers".
