### ISSUE TITLE
[android] Layers button shown behind status bar

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#3411]
A minor issue with "Layers" button:

![Screenshot_20220915-124749_Organic Maps (Beta)](https://user-images.githubusercontent.com/1799054/190386701-add4d7e5-23ae-42d9-b8c7-894e56dc4575.jpg)

**Comment by vng** [comment]
Just to link this issues together: https://github.com/organicmaps/organicmaps/issues/3389

**Comment by vng** [comment]
@rtsisyk Please, always write your device model, Android version, another device specific info if any (like custom firmware).

**Comment by arnaudvergnet** [comment]
@rtsisyk your status bar is way too large compared to stock Android. Do you have any custom UI made by your vendor on top of the stock Android? This may also explain https://github.com/organicmaps/organicmaps/issues/3389

**Comment by rtsisyk** [comment]
This is Samsung UI. Samsung S10 Android 1 device.

**Comment by biodranik** [comment]
@arnaudvergnet shouldn't there be some android api/constant to get the status bar height and make the code more flexible?

**Comment by arnaudvergnet** [comment]
There's no constant but you can dynamically retrieve this value from Java. This is what I did for the navigation bar. I can make a PR to do this when I get the time. It wasn't done like this before this is why I did not bother. Maybe the margin was bigger before so on this case it would not be behind the status bar.

**Comment by Kazing** [comment]
Same problem here, appeared with the last version : 2022.09.15-5-FDroid

The device is a Pixel 4a, Android 13

![Screenshot_20220918-181740](https://user-images.githubusercontent.com/41507326/190917491-8914be4c-22c2-4afe-a5c5-dca359f4b1d3.png)
