### ISSUE TITLE
For long descriptions compass and plus buttons are clashed

### ISSUE THREAD

**Issue by dbf256** [organicmaps/organicmaps#3413]
![Screenshot_2022-09-15-18-35-21-420_app organicmaps](https://user-images.githubusercontent.com/2550295/190459623-7522dd4d-2b5a-47e1-9f6d-8c21c4a297a6.png)

**Comment by vng** [comment]
Is it latest beta?

**Comment by dbf256** [comment]
It is 2022.08.23-5-Google

**Comment by vng** [comment]
Please, try our todays beta (links in Telegram).

**Comment by arnaudvergnet** [comment]
Yes it should be fixed in latest beta, if it is not please post new screenshots

**Comment by biodranik** [comment]
@dbf256 can we close it?

**Comment by dbf256** [comment]
I don't use beta and September version is not available in GooglePlay so can't say anything on it

**Comment by arnaudvergnet** [comment]
@dbf256 Any news? The update should be available on google play

**Comment by dbf256** [comment]
Yes it looks good in current version. Thanks!
