### ISSUE TITLE
[android]: Remove bundled World.mwm from GitHub & AppDistribution version

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#342]
I propose to remove bundled World.mwm from GitHub & AppDistribution versions. APK users care about the free space a lot, but can wait a couple of minutes until the world map is downloaded. For Google Play version we need to switch to Play Delvier API, but this is a separate topic.

```
diff --git a/android/build.gradle b/android/build.gradle
index 74d92052e8..8871481f4f 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -369,7 +369,6 @@ android {
       dimension "default"
       versionName = android.defaultConfig.versionName + '-Web'
       buildConfigField 'String', 'SUPPORT_MAIL', '"apk@omaps.app"'
-      android.sourceSets.web.assets.srcDirs = ['flavors/mwm-ttf-assets']
     }

     fdroid {
```

![image](https://user-images.githubusercontent.com/1799054/116005450-9d608200-a60f-11eb-8fd3-6f083a3a88d2.png)

**Comment by biodranik** [comment]
I'm ok to remove worlds when we start dynamically download the most recent data version.
