### ISSUE TITLE
Consistently name bookmark groups (sets, categories)

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#343]
Now different names are used

**Comment by pastk** [comment]
Its called
- "lists" in bookmarks page, e.g. "create new list", "list settings"
- "set" in "create new list"/"select list" pop-ups and in bookmark edit page

So what name do we choose? :)

**Comment by biodranik** [comment]
@pastk please use lists everywhere, it's compatible with Google Maps.
