### ISSUE TITLE
Integrate three words coordinates

### ISSUE THREAD

**Issue by lab-at-nohl** [organicmaps/organicmaps#3437]
Recently some people used this for traveling. Quite handy to share a poi. Of course, it needs a network connection - I guess.

**Comment by endim8** [comment]
see https://github.com/organicmaps/organicmaps/discussions/2132

**Comment by lab-at-nohl** [comment]
I understand your position on proprietary services. However, people use it. But I have chosen Organicmaps for being open ;-)

**Comment by biodranik** [comment]
If w3w contributes an open-source implementation to OM which will work in offline, then we can support it, of course )
