### ISSUE TITLE
[iOS] 3D buildings intermittently do not render

### ISSUE THREAD

**Issue by eisams** [organicmaps/organicmaps#3443]
The new September iOS app update does not render buildings as 3D in Oslo

It worked in the last August app

FYI: Updated map tiles, restarted the app, and turned on/off 3D buildings

**Comment by eisams** [comment]
I am not sure what happened, but it is working now... Closing

**Comment by eisams** [comment]
But now it's not working again, so it is intermittently broken?

**Comment by biodranik** [comment]
@eisams maybe you enabled the "power saving" option. It disables 3D rendering.

**Comment by eisams** [comment]
That does indeed seem to be the case. Thanks!
