### ISSUE TITLE
[Android] The semi-transparent status bar overlay doesn't match the height of the actual status bar

### ISSUE THREAD

**Issue by najodleglejszy** [organicmaps/organicmaps#3444]
The device I use, Fairphone 4, has got a screen with a notch and the status bar height is increased in order to accomodate for that and to line up the bottom edge of the status bar with the lowest part of the notch. It looks like Organic Maps' UI isn't properly adjusting to it, which results in the status bar overlay being drawn straight across the status bar icons. so far it's the only app I've used on this phone that's been showing that behaviour.

![Screenshot_20220918-120812](https://user-images.githubusercontent.com/8598559/190897155-ab9a20b1-933b-4097-b969-7e36f2ba84c6.png)

here's a photo in order to show how it looks like with the notch:

![20220918_121032](https://user-images.githubusercontent.com/8598559/190897179-d9bc6ab5-6a75-468e-8c4e-a6c3eec3233a.jpg)

I'm running CalyxOS based on Android 12, but I've noticed the same behaviour on other ROMs based on Android 11, too.

**Comment by arnaudvergnet** [comment]
Was this always the case or did this happen since last update?

**Comment by arnaudvergnet** [comment]
Seems to be working as expected on the Samsung S10 on Android 12 https://github.com/organicmaps/organicmaps/issues/3411 (which raises another issue ;) )

**Comment by najodleglejszy** [comment]
> Was this always the case or did this happen since last update?

it's been happening for a few months at least, it's just that I've only now got around to reporting it ^^'

**Comment by arnaudvergnet** [comment]
Thanks at least we know its been around for some time and not introduced in last update.
