### ISSUE TITLE
Describe clearly that "Power Saving" option turns off 3D buildings rendering

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3446]
Many users are confused because they don't see how it is connected.

A better text description can help. Even better is to explicitly disable the 3D rendering option when this Power Saving setting is enabled.

As mentioned in the comment below, the "automatic" setting can be still unclear to users (it turns off 3D rendering if the battery level is very low). It has to be also solved somehow.

**Comment by eisams** [comment]
Question: Does this indeed save power on modern devices? My hunch would be that it's not

I'd expect power saving to be related to GPS polling and similar

The default setting of automatic would still cause confusion since it would turn off and on buildings randomly, as users may not browse through all the settings and descriptions

**Comment by biodranik** [comment]
@eisams you can test it and share your results :)

**Comment by eisams** [comment]
Ok, not sure what I'm doing, but I at least made a "Game Performance" instruments analysis on an iPad Air 3 from 2019 with an A12 processor

I recorded while holding my finger down and dragging in circles to move the map

With 3D buildings:
<img width="601" alt="Screen Shot 2022-09-18 at 15 50 43" src="https://user-images.githubusercontent.com/62468530/190909264-c0596d73-e4e8-445e-a5e9-5a643d0e7aac.png">

<img width="585" alt="Screen Shot 2022-09-18 at 15 53 33" src="https://user-images.githubusercontent.com/62468530/190910393-12a49211-9286-4682-9ede-f7e4aeea3153.png">


Without 3D buildings:
<img width="602" alt="Screen Shot 2022-09-18 at 15 51 36" src="https://user-images.githubusercontent.com/62468530/190909573-978ff643-bd5f-4e03-b12d-f4db7dc370e0.png">

<img width="583" alt="Screen Shot 2022-09-18 at 15 53 56" src="https://user-images.githubusercontent.com/62468530/190910490-46681e03-8aaf-43eb-a8e3-f7b6680274bb.png">

Don't exactly know what I'm looking at, but there doesn't seem to be any big differences in GPU usage, and there will be some variability in these two tests as they're not identical

I'd say it would be better to only let the "3D buildings" setting control this

**Comment by biodranik** [comment]
Dragging for several seconds is not a proper testing scenario. The best one would be to walk/drive thru the same city with a lot of buildings using the same route and the same initial battery change. Or simulate it somehow.

As I know the code, I tell you that there is a difference in rendering at least 3x more polygons (even more triangles) for simple square buildings, and way more polygons for more complex buildings.

**Comment by biodranik** [comment]
It affects 3D and perspective in navigation mode. In the future, it may affect some other components too, so removing it is not an option. The idea is that when you're in mountains, you enable power saving. When you're committing to the city, you use all features.

**Comment by euf** [comment]
Thanks for clarification! Let me share some more simplification ideas: 
1. Move “3d buildings” options under combined switch “Power saving and 3D” 
2. Rewrite power saving description, making it more transparent about conditions (battery level) and effects (disabling 3d and perspective view features)
3. Make “Auto option” more feature rich, e.g. depending not only on battery level, but also on iOS system power saving switch
