### ISSUE TITLE
Advanced search / Filtering

### ISSUE THREAD

**Issue by c-mahn** [organicmaps/organicmaps#3465]
When searching for something like a parking spot for eating lunch, I would like to filter it to have a bench and a trashcan nearby. This way I wouldn't get shown all the small parking places, that don't provide anything.

The same applies to something like a place to stay the night. I would like to have a parking spot, where there are no / few buildings around.

The advanced search would likely only search for the specific types like "bin" or "bench" or would have a toggle for fuzzy search.

**Comment by Jean-BaptisteC** [comment]
Do you know somes routing app which have this feature ?

**Comment by c-mahn** [comment]
I have not seen it in a mobile form, but I have written a partial example from above (parking not within 5km of an aerodrome) in Overpass Turbo. It's a tool for creating more complex requests:
[https://overpass-turbo.eu/s/1oEO](https://overpass-turbo.eu/s/1oEO)

**Comment by Jean-BaptisteC** [comment]
To search spot to lunch, you can search [rest_area](https://wiki.openstreetmap.org/wiki/FR:Tag:highway%3Drest_area) in OM.
Do you search parking during your route or before ?
If you search before, you can use blue button at the bottom to access to the map and show all results in on map and zoom to check if you near buildings, bench trashcan.

**Comment by c-mahn** [comment]
> To search spot to lunch, you can search [rest_area](https://wiki.openstreetmap.org/wiki/FR:Tag:highway%3Drest_area) in OM. Do you search parking during your route or before ? If you search before, you can use blue button at the bottom to access to the map and show all results on map and zoom to check if near you have buildings, bench, trashcan.

I have used these before, but the problem with looking at everything manually on the map is, that it is very tedious. I would very much prefer to filter the results somehow. Having the option to filter something to be near train stations, rivers and parks would be quite nice (and away from airports, highways and main roads).

**Comment by c-mahn** [comment]
I know the results would be a little slower, but checking for nearby amenities with Pytagoras "if(sqrt((x1-x2)²+(y1-y2)²) >= 5000)" isn't that hugely impactful on performance.

**Comment by c-mahn** [comment]
One option would be to make it accessible through a GUI (as seen in the image [above](https://github.com/organicmaps/organicmaps/issues/3465#issuecomment-1275197255) )

Otherwise it could be done via some form of system similar to [google advanced search](https://support.google.com/websearch/answer/2466433?visit_id=638058745801973902-2063067059&p=adv_operators&hl=en&rd=1), where the search could be filtered with additional syntax. In syntax this could look something like:

Example 1:
`parking \!nearby(5km,amenity=aerodrome) \nearby(200m,amenity=waste_basket)`

Example 2:
`parking \nearby((aerodrome, !5km), (waste_basket, 200m))`

I personally think, that for users the graphical way with a GUI would be easier to understand. Similarly it is quite difficult to remember the tags, so a GUI (as posted before) could provide helpful suggestions for tags, that would be difficult to implement for advanced queries.

**Comment by biodranik** [comment]
1. No complex gui on mobiles.
2. No complex symbols on mobiles. How many times did you try to switch the keyboard to type \, ! and ()?

**Comment by Jean-BaptisteC** [comment]
Too complex for users on mobile
Keep in mind, we want to develop an application usable by everything.
Use overpass is more adapted to filter OSM data

**Comment by biodranik** [comment]
Any ideas on the "natural" and easy-to-use search syntax that can be guessed by most users are welcome.
