### ISSUE TITLE
Bookmark list load performance

### ISSUE THREAD

**Issue by jla217** [organicmaps/organicmaps#3466]
[test.zip](https://github.com/organicmaps/organicmaps/files/9616225/test.zip)

When opening the attached bookmark set from the list, it takes several seconds to load. The problem escalates with more bookmarks in the set (more than 10 seconds in some cases, and once the app crashed altogether).

The issue does not appear if the corresponding offline map is not downloaded. It does not seem to be related to phone or OS/OM version, as I have faced it for a while now (including on MapsMe), but for the sake of completeness:
- Fairphone 3+, Android 11
- OM 2022.08.23-5-Google, data 16 Aug 2022

My conjecture is it has to do with shoreline (I faced similar issues on other great lakes map).

**Comment by biodranik** [comment]
Do you use SD-card? Do you store maps on SD-card? Can you test it with maps on the internal memory?

Slow/faulty SD-cards are usually the number one reason for such issues.

**Comment by jla217** [comment]
The phone doesn't have an SD card, both the app and the map are on internal memory.

**Comment by Jean-BaptisteC** [comment]
@arnaudvergnet you have a Faiphone right ?
Can you check ?

**Comment by Jean-BaptisteC** [comment]
@jla217 can you check on latest version?

**Comment by jla217** [comment]
@Jean-BaptisteC with the latest version, all bookmark lists I had experienced the issue with now load in a reasonable amount of time.

**Comment by Jean-BaptisteC** [comment]
Thanks for feedback, I close this issue.
