### ISSUE TITLE
It shows country, not city

### ISSUE THREAD

**Issue by toas-koas** [organicmaps/organicmaps#3473]
When I search for a street in a city, it shows the address with the country name and not from the city

**Comment by Jean-BaptisteC** [comment]
Could you give somes examples with screenshots ?

**Comment by toas-koas** [comment]
It show this adress in Augsburg. But its in Bobingen. 
Bobingen is in the country Augsburg

![Screenshot_20220923-212137_Organic Maps](https://user-images.githubusercontent.com/74021807/192042241-e8615700-8183-439e-bd20-15fa8b8e08f5.png)
![Screenshot_20220923-212203_Organic Maps](https://user-images.githubusercontent.com/74021807/192042244-b4311063-58bb-4d65-8422-44db2554d7a6.png)

**Comment by Jean-BaptisteC** [comment]
Check this https://www.openstreetmap.org/relation/62407#map=11/48.3585/10.8614 and this https://www.openstreetmap.org/relation/935167

Admin level is different between Bobingen and Augsburg.

**Comment by toas-koas** [comment]
Yes admin level  its different. Bobingen shows in the app the admin level from Augsburg. It should show bobingen.

**Comment by endim8** [comment]
also see https://github.com/organicmaps/organicmaps/issues/616

**Comment by biodranik** [comment]
See #2490

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.01.09-6-Google version
