### ISSUE TITLE
Bookmark lists sorting by recently modified does not work properly

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3475]
The idea is to show users sorted lists so they can navigate them easier. Another idea in #1066 is about sorting by name and other criteria.

Cold restart sorts bookmark lists by recently modified (RM) criteria.

Editing bookmarks in iOS and Android doesn't always behave correctly. Possible editing actions:
1. Add a new list.
2. Add a bookmark to the last used list.
3. Remove a bookmark from the list (this action probably should NOT modify the RM field, WDYT?)
4. Moving a bookmark from one list to another (should the source's RM field be modified? Probably no (as in the case above), but if yes, then that modification should be _before_ modification of the destination list.)
5. Importing a list should update its RM field.
6. Renaming a list or adding a description to a list? (Later - changing its permissions?)
7. Renaming a bookmark, changing its color, or adding a description to it?
8. Changing the visibility of a list?

There are some open questions. CC @vng

**Comment by Volodymyr-13** [comment]
I have some issues too, just load new kml file shows it in the list on top, close open app - now it's somewhere randomly in the all list of my bookmarks.

**Comment by mirko77** [comment]
+1 to @Volodymyr-13, I am experiencing the same.

There should be a way to sort bookmark lists (newest, oldest, A-Z, Z-A) and filter by search string, I have ~100 lists and currently finding the one I need is a pain. Moreover, pinning lists to the top would be nice.

**Comment by Volodymyr-13** [comment]
@mirko77 oh yea, pinning should be superb function here! @biodranik I hope this is on the short list :) 
Moreover, now I understand that search in Favourites is a must have feature. Should I create another request for this.. don't know.

**Comment by biodranik** [comment]
What if the move recently used lists to the top? Will it help? Searching, of course, should work, from the main search bar.

**Comment by Volodymyr-13** [comment]
I believe that recently used(should be some option to enable/disable) is a great feature, also ability to pin any list is a great feature too.

But, ability to search through all my ~50lists(imported kml files of routes with names like "forest", "city" and so on..) will help even more than pin or recently used!

**Comment by biodranik** [comment]
@mirko77 should it filter only lists? Or also find/display matched bookmarks inside lists? How it will look to be usable?

**Comment by Volodymyr-13** [comment]
I can add that it initially it should search through the names. 

![1](https://user-images.githubusercontent.com/3391456/196947492-17ced4ce-c6d0-4f17-b1a1-a5003e04a6b0.png)

**Comment by mirko77** [comment]
@biodranik @Volodymyr-13 filtering only the list names will do, I guess.

**Comment by biodranik** [comment]
Also sorting should always group visible lists at the top, and invisible lists at the bottom.

**Comment by vbertola** [comment]
I haven't noticed that, sorry. But while you're at it, could you actually add a display of the "last modified" date to the bookmark lists screen? If you add a simple date and time (beautified to "X minutes ago", if you want / have code ready), near to the number of places in the bookmark list that you already show, it should not clutter the UI significantly - but it would help people with many lists by knowing, for example, whether that list was updated before or after their last trip to that location or the last manual backup.
And of course, it would be great if you could add a simple button somewhere that allows you to change the sorting order by cycling among last modified first and A-Z (if you want you could also add last modified last and Z-A, but those two would already cover most needs).

**Comment by biodranik** [comment]
Looks like changing list visibility modifies it and changes the sort order. That should not influence the sorting.

**Comment by kaoneko** [comment]
Hello @biodranik,

You asked me the following on Reddit:

> The last modified sorting should work without restarting the app. Can you please update the existing issue with your details (device OS) and steps to reproduce it easily?

I just confirmed this is not the case with the currently latest version 2023.03.05-5-FDroid, both on a Pixel 4a running LineageOS 18.1 and a Mi 11 Lite 5G running LineageOS 19.1. Volodymyr-13 mentions the same behavior above in [this comment](https://github.com/organicmaps/organicmaps/issues/3475#issuecomment-1272091663) in regard to newly imported kml files: “close open app - now it's somewhere randomly”.

Steps to reproduce:
- have multiple bookmark lists and note their order
- edit any bookmark list other than the top one in any way, e.g. toggle its visibility, add/edit/remove a bookmark (it doesn't matter if you do this from the map or the list)
- notice its position in the bookmark lists overview stays the same
- remove Organic Maps from Android's recent apps screen
- open Organic Maps, the splash screen should show briefly, then notice the last edited bookmark list is now on top in the bookmark lists overview (although unchecked lists will always be listed above checked lists)

Very confusing behavior, the user doesn't connect the moving of the lists to the top to editing them when the moving only happens after they haven't used the app for a while, especially with there also not being any visual indication as to the sort order of the bookmark lists overview. It had me frustrated for a good while, not understanding what was going on!

So I understand this isn't the intended behavior and the delay in sorting doesn't happen for everyone?

**Comment by biodranik** [comment]
Toggling visibility modifies the file underneath. Do you think that this kind of "modification" should be ignored for "sorting by recently modified/last used" criteria? Or we should have separate "usage" and "modification" sorting?

**Comment by mirko77** [comment]
@biodranik, well, it still does not sort by last modified. 

If I toggle the bookmark visibility, that bookmark is not pushed to the top of the bookmark list. At least not on `2023.03.05-5-Google`
However, I agreed on the consistent approach, so ANY changes should count towards recently modified/last used, when that sorting is used. So yes, in this case, toggling visibility should move that bookmark to the top of the list.

Adding the A-Z, Z-A sorting options would be a nice later addition. 

Good point by @vbertola, showing the "last modified" timestamp on each bookmark helps. 
"Modified X minutes|hours|days ago"

@Volodymyr-13 was working on name filtering, not sure about the current state of that feature?

**Comment by kaoneko** [comment]
I just noticed in the opening post of this issue you (@biodranik) wrote:
> Cold restart sorts bookmark lists by recently modified (RM) criteria.

Whereas on Reddit you wrote:
>The last modified sorting should work without restarting the app.

So this should have been changed since Sep 24, 2022? Maybe a regression then?

**Comment by biodranik** [comment]
It wasn't working for a longer time. We already tried to fix it, but unsuccessfully.

**Comment by biodranik** [comment]
@vng User confirms that we made the behavior worse after the fix:

In my opinion, the sorting of the bookmarks has the following problems:

1. If I choose one (or more) lists with a hook, the list(s) are always at the end of all lists (after restarting the app). The handling would be much much easier if the chosen list(s) would be on top of the bookmark list, especially when you have lots of bookmark lists. (Attachments 1 and 2)

2. When I choose all lists with a hook the sorting is different in comparison to choosing no lists! (Attachments 3 and 4)

3. Sorting of bookmark lists by different characteristics like "Alphabet", "Date", "the list is chosen or not" etc. would be very useful.

1|2|3|4
-|-|-|-
![image](https://user-images.githubusercontent.com/170263/232631535-c4871b8d-ff0b-4f97-aa30-35888de925af.png)|![image](https://user-images.githubusercontent.com/170263/232631549-1fca8ecf-bdf7-4dd0-b917-49b182ffa798.png)|![image](https://user-images.githubusercontent.com/170263/232631564-14b8cc19-427f-4c8a-b858-c1f1c8cf5a35.png)|![image](https://user-images.githubusercontent.com/170263/232631617-8876436c-5af5-4dab-abb3-aa5521e9adfe.png)
