### ISSUE TITLE
CarPlay: support panning guestures (swipes to move the map)

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3482]
Speaking about CarPlay: panning guestures (swipes to move the map) aren’t implemented for some reason.

Being able to navigate to arbitrary point (I know there no generic touches, map view center is ok if panning guestures are implemented will do the job, I think) is also a really good option. This approach is used in my car’s native navigation app.

My car has touchscreen which supports panning guestures and maps.me supports them (or  mapy.cz , not sure).

_Originally posted by @imixerpro in https://github.com/organicmaps/organicmaps/discussions/3431_

**Comment by euf** [comment]
Maybe this post (in Russian) would be useful, look for «Перемещение карты жестами»:
https://habr.com/ru/company/2gis/blog/452638/#:~:text=Перемещение%20карты%20жестами

Also it would be great to support pinch gestures for zoom

**Comment by fabwu** [comment]
@biodranik You can close this issue see #6832

**Comment by RedAuburn** [comment]
> @biodranik You can close this issue see #6832 

Nice, thank you!
