### ISSUE TITLE
Change translation for 'Subway' to 'Metro'

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#3485]
Subway implies that it's underground, Metro is short for Metropolitan Railway which can be both under and overground
(feels a bit pointless to open a whole PR just for this, so if someone's updating translations pls add this as well)

**Comment by biodranik** [comment]
Which languages and what is the context? What should be translated and where?

**Comment by endim8** [comment]
In [organicmaps/data/strings/strings.txt](https://github.com/organicmaps/organicmaps/blob/master/data/strings/strings.txt)

```diff
  [button_layer_subway]
    tags = android,ios
-    en = Subway
+    en = Metro
```

**Comment by biodranik** [comment]
It is more complex: https://multimedia-english.com/grammar/underground-subway-metro-tube-59

I propose:
en_US = Subway/Light Rail
en_UK = The Tube/Light Rail
en = Metro/Light Rail

**Comment by endim8** [comment]
`ERROR: Invalid languages: en_UK,en_US`
how would i add the new language variants?

**Comment by biodranik** [comment]
With dashes?
