### ISSUE TITLE
ISSUE: Uploading edits on OpenStreetMap n/w

### ISSUE THREAD

**Issue by G-i-o** [organicmaps/organicmaps#3498]
Hi. I made an edit on the map which shows nicely on the map itself and on the linked webmap. However, when I try to upload the edits on OpenStreetMap I'm presented with the log in box but after inputing my account access details and clicking on the login button, the box closes without confirmation (or denial) for the upload.

I then checked on OpenStreeMap itself but found no uploaded change on the map.

OS Used: Lineage v19.1 (= Android 12).

To reproduce:
1. Open the app and click on the map, scroll up the bottom menu and click on "**Add a place to the map**"
2. Input all the details and click on tick to confirm and save.
3. You'll be presented with the OpenStreeMap login page. Fill in the login details and click on the button to login.
4. Seemingly the page closes and you are presented with the map or the app crashes entirely and reopens at the same point on the map. Either way it's not clear as there's no confirmation message or error message of any kind.
5. Check if the uploaded changes reached OpenStreetMap. You'll find it's not there.

Thank YOU!
P.S. Great app!

**Comment by biodranik** [comment]
1. What is your OM version? Is it from FDroid or Google Play/AppGallery?
2. What is displayed when you open a profile page in OM settings? Are you logged in there?
3. What is displayed when you type `?edits` in the search box?

@arnaudvergnet is there any confirmation or failure displayed on successful/unsuccessful OSM login in that scenario? Let's show a toast for the successful login :)

**Comment by arnaudvergnet** [comment]
There is a dialog shown when the auth fails. If it is successful, you are redirected to the profile page if you clicked on your profile initially, and it does nothing otherwise.

I'll have to check why it crashes but yeah showing a toast could be a good idea if you logged in to upload edits.

**Comment by G-i-o** [comment]
Thank you for your prompt responses @alexander
@arnaud

To answer your questions:

- OM Version: 2022.09.15-5-FDroid with OSM data
dated 2022.09.12
- I can log in via SETTING > OSM PROFILE and which
case there's no issue.
- When I type ?edits in the SEARCH box my edits do
come up. (BTW.....cool, did not know this query
was possible. Thank YOU!).

So, to recap, the issue is when I am NOT logged
into OSM and I make an edit directly in the map
and I try to submit, the OSM login screen comes
up. If there's a problem with my login (es. I not
online at that moment), the auth fails and the
login page/screen closes without reporting
anything.

That indeed is what confused me as I thought that
my edit was submitted even if I was not online
(aka queued for when a connection was established)
or, if that was not the case, I was supposed to
receive an error message saying to retry later.

Hope it helps! 🙏 🙏️


On Thu, 2022-09-29 at 15:25 -0700, Alexander
Borsuk wrote:

**Comment by biodranik** [comment]
@arnaudvergnet as we do not store passwords, then the "login" dialog should not be displayed in offline mode at all. A better UX idea may be to show some "needs upload" icon (do you have any ideas?) or a number of local unsent edits to the right of "OpenStreetMap profile" line in Settings.

We definitely don't want to interrupt user with a popup "Login to OSM" dialog when he uses the map. Do you have other cool and simple ideas on how to motivate people who edited something in offline or online to log in/register in OSM?

**Comment by arnaudvergnet** [comment]
Showing the number of uploads next to the profile button when offline is a good idea. Then when connected I would love to be able to access the list of my edits from the profile screen instead of the hidden search trigger.

To incite people logging in, we could show a toast when the app starts and there are unuploaded changes. Users should be able to disable this toast if they really don't want to upload.

**Comment by biodranik** [comment]
I don't like many "enable/disable" options, almost the same as I don't like the annoying toasts :)
Let's focus on better and more convenient solutions. Showing (not too annoying) not uploaded edits marker in Settings (and in Profile) is a good idea. If you can implement a list of local edits there, that would be great. I've added it via a secret query in 2016 for debug purposes, there were no resources to write a better UI for local edits.

Please keep in mind that:
- Uploaded edits disappear if the user downloads map data with these edits integrated into OSM.
- There are some upload bugs now, and it would be very convenient for users and us to debug/fix them if we see these errors easier in the profile section, together with as much detailed info as possible, probably also with a button to zoom on that edited feature.
