### ISSUE TITLE
[android] No progress in Downloader search activity.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#350]
- Enter downloader activity
- Search for any region ("Brest")
- Tap to download

Progress status not updated

**Comment by biodranik** [comment]
Это же ты не выпилил на своей ветке?

**Comment by vng** [comment]
Мои ветки наоборот понемногу чинят ..

Это не работает очень задолго до наших изменений. Все это вскрывается, пока я пытаюсь просто читать код ..
