### ISSUE TITLE
App crashes on device orientation change

### ISSUE THREAD

**Issue by ShivamHP** [organicmaps/organicmaps#3506]
If orientation of mobile is changed frequently, the app crashes.

https://user-images.githubusercontent.com/45695285/193299375-3363880e-fc5d-4cbd-b502-1822d4ff9634.mp4

**Comment by biodranik** [comment]
Can you please share `adb logcat` log of the crash? Or try to enable logs in OM settings, then crash it, restart, and share log with us via "?" -> Report a bug?

**Comment by biodranik** [comment]
Can you please confirm that it is reproduced in the September release? What is your Android version and device model? I can't reproduce it on my devices.

**Comment by Jean-BaptisteC** [comment]
Not reproduced on the latest version 2023.11.17-18-Google
I close the issue
