### ISSUE TITLE
Fix subway icons

### ISSUE THREAD

**Issue by starsep** [organicmaps/organicmaps#3509]
I would like to fix subway icons for cities where it doesn't work at the moment. It looks that some of them were fixed in #1113
| Current render of subway station/entrances in Warsaw |Expected state (rendered by removing `[city=warszawa]` from Subways.mapcss) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2798728/193370188-0b5f1089-3cee-4a95-ab6e-c1f4c7e64e2f.png) | ![image](https://user-images.githubusercontent.com/2798728/193369734-030d59b5-8ed2-4225-b354-e19e3452c57c.png) |

I tried making changes based on #1113 and generating map data but no luck.
Once I know what needs to be done for a single city I can fix all cities with subway and test them.

**Comment by biodranik** [comment]
Likely you should not remove the style. Did you check other cities where custom subway icons work?

**Comment by starsep** [comment]
Just to clarify: I know that removing `[city=warszawa]` is a bad solution as it causes *every* subway station/entrance to render this icon, not only Warsaw. It was just to check that styling inside those rules still works (it does) and to be able to screenshot effect I want to achieve.
I checked other cities Minsk and Moscow. Custom subway icons work there. I tried to add "warszawa" to every file where I could find "minsk". Unfortunately it's not obvious to me which files should be edited manually and which are generated. Also it's possible I am not re-generating properly after changes. At the moment I am not running "Subway layer generation" as I believe this styling is only in base map style.

**Comment by AlertSubject** [comment]
Where are custom subway icons sourced? Maybe I could help with finding some for German cities

**Comment by starsep** [comment]
Current icons can be found in https://github.com/organicmaps/organicmaps/tree/master/data/styles/clear/style-clear/symbols and https://github.com/organicmaps/organicmaps/tree/master/data/styles/clear/style-night/symbols
Firstly I'd like to fix cities where icons are added to repo already but not rendered at the moment.
I don't know what is the source of those icons. Wikimedia Commons is likely a good source if licences of files are fine.

**Comment by biodranik** [comment]
There should be some documentation in the repo, you can also search other pull requests with style changes, there were some docs/steps listed.

**Comment by biodranik** [comment]
Regarding icons sources, please check data/copyright.html
