### ISSUE TITLE
Render natural=shrubbery

### ISSUE THREAD

**Issue by vincentvd1** [organicmaps/organicmaps#3517]
`natural=shrubbery` is gaining quite some traction in [usage](https://taginfo.openstreetmap.org/tags/natural=shrubbery), especially in (Western) Europe. It is used as the urban replacement of `natural=scrub` which has been used a lot in the absence of a good tag to map manicured bushes. The [proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/shrubbery) to fix this was rejected a year ago but nonetheless quite some mappers agreed with `natural=shrubbery`.

These shrubbery can be used to orient on a map and would therefore be a good addition to the map in my opinion. It can be rendered the same as `natural=scrub` in organic maps.

**Comment by biodranik** [comment]
If I understand you correctly, then we can simply alias all natural=shrubbery to natural=scrub and count it as a synonym, right? Then it can be done by adding a line into data/replaced_tags.txt

**Comment by vincentvd1** [comment]
Yes, in OSM it is ofcourse not the same but for rendering on Organic maps it is fine to me if it renders the same as `natural=scrub` (which on its turn renders the same as `natural=grass`).
