### ISSUE TITLE
Routing doesn't seem to handle exception for bikes on only_right_turn restriction

### ISSUE THREAD

**Issue by ArcoMul** [organicmaps/organicmaps#3521]
[This relation](https://www.openstreetmap.org/relation/7701750#map=18/50.95187/6.96654) has a only_right_turn restriction, but it has an exception for bikes.

<img src="https://user-images.githubusercontent.com/1388162/193470686-5ec66add-ecb4-428e-887e-e53763fcfe1a.png" width=400 />

When navigating the road the following happens:

<img src="https://user-images.githubusercontent.com/1388162/193470601-511d6a58-bbd6-4005-9939-6591b649f976.png" width=300 />

Could it be that Organic Maps doesn't handle the `only_right_turn` exception for bicycles?

**Comment by biodranik** [comment]
Yes, looks like it is ignored. @vng can you please check it?

**Comment by Jean-BaptisteC** [comment]
Fixed in the latest version 2023.11.17-18-Google
