### ISSUE TITLE
Subway layer is slow/laggy

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#3526]
When enabling the subway layer, the map looses a lot of FPS. It does not matter if we are in a city with metro or in the middle of nowhere, the performance is heavily impacted by this layer. This is not the case with the elevation layer.

Tried on Android 10.

**Comment by biodranik** [comment]
Performance is also impacted on iOS, although not as dramatically.

Could it be caused by some semitransparent view drawn on the top of the map? Or is everything drawn exclusively via Drape's OpenGL/Vulkan?

**Comment by arnaudvergnet** [comment]
I think the semitransparent view is drawn via Drape because it is above the regular map but below the subway lines.

**Comment by arnaudvergnet** [comment]
Using a debug build on the device, I can see the app uses Vulkan and has around 50-60 fps while dragging the map. As soon as the subway layer is active the fps drop to 30. It does not matter if there are lines available nearby or not, and it happens on all zoom levels (even when looking at the world map).

**Comment by arnaudvergnet** [comment]
Found the source of the issue: https://github.com/organicmaps/organicmaps/blob/master/drape_frontend/frontend_renderer.cpp#L873

Commenting out this line removes all performance issues without any visible change. Is antialiasing needed for the subway layer @vng?

**Comment by vng** [comment]
Good job! Actually, I don't know if it is needed or not, but you can put and commit your comments there.
Please, tell us more about your device model with this log:
```
drape/support_manager.cpp:35 Init():
```

And FPS numbers if possible.

**Comment by arnaudvergnet** [comment]
Here is the output, first using Vulkan then OpenGL (both modes have the performance issue on this device):
```
drape/support_manager.cpp:35 Init(): Renderer = Adreno (TM) 506 | Api = Vulkan | Version = API:1.1.128/Driver:512.502.0
drape/support_manager.cpp:79 Init(): Max line width = 1 | Max texture size = 16384
```

```
drape/support_manager.cpp:35 Init(): Renderer = Adreno (TM) 506 | Api = OpenGLES3 | Version = OpenGL ES 3.2 V@0502.0 (GIT@3b5766d, Ia5561a03a2, 1626798686) (Date:07/20/21)
drape/support_manager.cpp:79 Init(): Max line width = 8 | Max texture size = 16384
```

**Comment by biodranik** [comment]
Antialiasing was enabled because without it tooths/peaks were visible on metro lines. We need to test it on different devices.

**Comment by arnaudvergnet** [comment]
I only have access to one device, so I can only test on emulators. But between some jagged lines and horrible performance, I'd prefer to see jagged lines.

**Comment by arnaudvergnet** [comment]
Tried on several emulators (phone and tablet), and found a difference on an Android 5 Nexus S (480*800 pixels at 320x534dp).

| With AA | Without AA |
|-|-|
| ![Screenshot_1681460397](https://user-images.githubusercontent.com/80701113/232003875-80dbbabd-aa28-43c3-b1f0-10484a98c736.png) | ![Screenshot_1681460204](https://user-images.githubusercontent.com/80701113/232003881-f48baae8-b7d3-4778-ac71-6ca3a08733e7.png) |

The difference is not that big but you can see the FPS going from 40 to 20. We can see artifacts even with AA enabled.
