### ISSUE TITLE
Coastal lines cut off 

### ISSUE THREAD

**Issue by AlertSubject** [organicmaps/organicmaps#3529]
When zooming out too far the coastal line is flattened
Comparison of different zoom levels
![Screenshot_2022-10-03-18-13-27-18_75d0290a7c00525acd83c0ab8700d64c.jpg](https://user-images.githubusercontent.com/72819077/193627159-d9eeca1e-676b-457f-b8eb-cc93c08f072b.jpg)
![Screenshot_2022-10-03-18-13-29-57_75d0290a7c00525acd83c0ab8700d64c.jpg](https://user-images.githubusercontent.com/72819077/193627193-89938dbd-91b5-489e-b730-1b6eb9392c7a.jpg)

**Comment by endim8** [comment]
![signal-2022-10-03-172802_002](https://user-images.githubusercontent.com/26939824/193629932-5f59cddb-1dfd-4ed9-8daa-cb8f1d6e7db2.png)
on an even higher zoom level, it becomes sort of gridified

**Comment by biodranik** [comment]
@vng I'm ok if coastlines will take 10M instead of 5M, but the map will be more beautiful. Can we test it?

**Comment by vng** [comment]
Should be better starting from 221029
