### ISSUE TITLE
Routing error - motorway_link is prioritised over motorway

### ISSUE THREAD

**Issue by tguen** [organicmaps/organicmaps#353]
This route directs me to take an exit ramp, then immediately take the entry ramp (twice) instead of simply staying on the motorway.

![Screenshot_20210416-124012](https://user-images.githubusercontent.com/57420975/116499054-c183c380-a89a-11eb-8d06-0eec5fbd85c2.png)

https://www.openstreetmap.org/#map=15/45.5634/-122.6787

**Comment by biodranik** [comment]
It looks like OSM bug. Did you already check road relations there? Any recent edits? You may also report it by putting a map note there for local OSMers.

Looks like OSRM also doesn't want to build correct route there.

**Comment by tguen** [comment]
[OSRM provides the correct route on openstreetmap.org](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=45.5525%2C-122.6786%3B45.5737%2C-122.6786#map=17/45.55310/-122.67601)

It has nothing to do with recent edits, I had the same problem with maps.me months ago.

**Comment by tguen** [comment]
Same error, different place

![Screenshot_20210429-040717](https://user-images.githubusercontent.com/57420975/116541815-750ca800-a8db-11eb-9cec-ade4875fa272.png)

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=45.4379%2C-122.5681%3B45.4247%2C-122.5693#map=16/45.4314/-122.5671

**Comment by biodranik** [comment]
Thanks! @vng will take a look.

**Comment by biodranik** [comment]
@bykoianko any ideas where to start from?

**Comment by vng** [comment]
Should be fixed with the next data update.

**Comment by rtsisyk** [comment]
OK, I'm closing this ticket then.
