### ISSUE TITLE
[android] remove download manager

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3536]
To target API 33, we need to add POST_NOTIFICATIONS permission in Android Manifest because OM create notifications with information from download manager when user download maps.

This issue was created to remove download manager because "many users had a lot of download issues with it."

More information here #3525

**Comment by biodranik** [comment]
Wait, we have already removed download manager :)

**Comment by Jean-BaptisteC** [comment]
Ok, maybe we have just need to remove classes about notifications :)

**Comment by biodranik** [comment]
Are there any classes left unused? Can you please remove them?

**Comment by Jean-BaptisteC** [comment]
I think problem is fixed, i have try with debug  apk and POST_NOTIFICATIONS doesn't appears in OM android settings.
