### ISSUE TITLE
[android] Add ability to change language

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3537]
With Android 13, we can add ability to change app language in Android settings only for OM (Only for devices on Android 13).

More information [here](https://developer.android.com/guide/topics/resources/app-languages)

Requirements:
- Use Appcompat 1.6.0 (stable release is not yet available, latest version is Version 1.6.0-rc01)
- Declare android:localeConfig with path of xml (with list of languages) in Android Manifest.
- Create new xml in resources with list of languages.

**Comment by Jean-BaptisteC** [comment]
If you want, i can add this feature, can you add assign me on this issue.

**Comment by biodranik** [comment]
We usually don't assign someone. Just implement it and create a PR. There are not so many contributors yet to compete for our 1000+ issues :)

**Comment by Jean-BaptisteC** [comment]
I have try in my fork, i have crash about theme.

I think you need to update theme to implement per-app language and bump appcompat to 1.6.0 (I don't have enough knowledge to fix this).

APK are available [here](https://github.com/Jean-BaptisteC/organicmaps/actions/runs/3229100462)

```
10-11 20:20:55.451 17897 17897 E AndroidRuntime: FATAL EXCEPTION: main
10-11 20:20:55.451 17897 17897 E AndroidRuntime: Process: app.organicmaps.debug, PID: 17897
10-11 20:20:55.451 17897 17897 E AndroidRuntime: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:926)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:889)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:772)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.app.Dialog.dispatchOnCreate(Dialog.java:436)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.app.Dialog.show(Dialog.java:325)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.mapswithme.maps.location.LocationHelper.onLocationDisabled(LocationHelper.java:343)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.mapswithme.maps.location.LocationHelper.onLocationResolutionRequired(LocationHelper.java:296)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.mapswithme.maps.location.GoogleFusedLocationProvider.lambda$start$1$com-mapswithme-maps-location-GoogleFusedLocationProvider(GoogleFusedLocationProvider.java:98)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.mapswithme.maps.location.GoogleFusedLocationProvider$$ExternalSyntheticLambda1.onFailure(Unknown Source:2)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.google.android.gms.tasks.zzk.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7898)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by biodranik** [comment]
Wow, can you reproduce the crash without your changes? Looks like you enabled location in the app while it was disabled in the system. @rtsisyk it looks like a new Google dialog we recently added. And it looks like its theme should be derived from the AppCompat theme.

**Comment by rtsisyk** [comment]
> I have try in my fork, i have crash about theme.
> 
> I think you need to update theme to implement per-app language and bump appcompat to 1.6.0 (I don't have enough knowledge to fix this).
> 
> APK are available [here](https://github.com/Jean-BaptisteC/organicmaps/actions/runs/3229100462)
> 
> ```
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime: FATAL EXCEPTION: main
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime: Process: app.organicmaps.debug, PID: 17897
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:926)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:889)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:772)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.app.Dialog.dispatchOnCreate(Dialog.java:436)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.app.Dialog.show(Dialog.java:325)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.mapswithme.maps.location.LocationHelper.onLocationDisabled(LocationHelper.java:343)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.mapswithme.maps.location.LocationHelper.onLocationResolutionRequired(LocationHelper.java:296)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.mapswithme.maps.location.GoogleFusedLocationProvider.lambda$start$1$com-mapswithme-maps-location-GoogleFusedLocationProvider(GoogleFusedLocationProvider.java:98)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.mapswithme.maps.location.GoogleFusedLocationProvider$$ExternalSyntheticLambda1.onFailure(Unknown Source:2)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.google.android.gms.tasks.zzk.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7898)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 10-11 20:20:55.451 17897 17897 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
> ```

Are you trying `master` branch or have some customization on top of it? Master shouldn't crash on Android 13 in this place.

**Comment by rtsisyk** [comment]
OK, I am working on a fix.
