### ISSUE TITLE
[android] Fix NonConstantResourceId before upgrading to Android Gradle Plugin version 8.0

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#3552]
74 warnings like these:

> Avoid the usage of resource IDs where constant expressions are required.
>
>A future version of the Android Gradle Plugin will generate R classes with non-constant IDs in order to improve the performance of incremental compilation.
>To suppress this error, use the issue id "NonConstantResourceId" as explained in the [Suppressing Warnings and Errors](https://github.com/organicmaps/organicmaps/issues/new#SuppressInfo) section.

../../src/com/mapswithme/maps/editor/AdvancedTimetableFragment.java:96: Resource IDs will be non-final by default in Android Gradle Plugin version 8.0, avoid using them in switch case statements

```
  93   {
  94     switch (v.getId())
  95     {
  96     case R.id.examples:                                                                             
  97       showExample(!mIsExampleShown);
  98     }
  99   }
```

**Comment by biodranik** [comment]
That sucks. Am I correctly understanding that they force us to edit production code for faster developer builds? That's ridiculous.
