### ISSUE TITLE
public transport from GTFS

### ISSUE THREAD

**Issue by islam2hamy** [organicmaps/organicmaps#3555]
Hi ,

i can now build a map with out any problem ,
but i couldn't convert GTF to add it to the map

cd organicmaps/transit/world_feed/gtfs_converter

./gtfs_converter --path_mapping=mapping.txt --path_mapping_edges=mapping_edges.txt --path_gtfs_feeds=organicmaps/tools/python/transit/gtfs/dir_for_storing_feeds --path_json=/home/islam/organicmaps/islam/GTFS_json --path_resources=organicmaps/data

bash: ./gtfs_converter: No such file or directory

please help

thank you

**Comment by endim8** [comment]
you need to be in the parent directory (world_feed) so just run `../` and then the converter again.
AFAIK gtfs support doesn't work though, see https://github.com/organicmaps/organicmaps/issues/837

**Comment by islam2hamy** [comment]
cd organicmaps/transit/world_feed

./gtfs_converter --path_mapping=mapping.txt --path_mapping_edges=mapping_edges.txt --path_gtfs_feeds=../organicmaps/tools/python/transit/gtfs/dir_for_storing_feeds --path_json=../organicmaps/islam/GTFS_json --path_resources=../organicmaps/data

bash: ./gtfs_converter: Is a directory

**Comment by dikkechill** [comment]
In the organicmaps project directory you first need to build it with:
```
./tools/unix/build_omim.sh -r gtfs_converter
```
When successful, you can find it in:
```
../omim-build-release/gtfs_converter
```
docs/EXPERIMENTAL_PUBLIC_TRANSPORT_SUPPORT.md should be updated to include this

**Comment by biodranik** [comment]
Closing this issue in favor of #5331
