### ISSUE TITLE
Blurred buttons on Android 5 with a low resolution screen

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3556]
Looks like vector icons are not scaled properly. It appeared somewhere after recent refactorings.

SM-A300F Resolution 540 x 960 pixels, 16:9 ratio (~245 ppi density)

![image](https://user-images.githubusercontent.com/170263/194545831-fc3d7922-818a-4540-a9d0-c49dd24b0b0c.png)

**Comment by rtsisyk** [comment]
@arnaudvergnet do you have any spare cycles to take a quick look at this issue? I checked Android 5 emulator and our buttons look no more blurry than anything else such tiny emulator screen. AFAIK, API 21 fully supports vectors and we shouldn't have any issue. Maybe I am missing something.

**Comment by arnaudvergnet** [comment]
I don't have much time to look into this but I'll keep you updated if I find anything.

**Comment by biodranik** [comment]
A more clear example of the blurriness on the same device is here: #3708

**Comment by biodranik** [comment]
This can be the answer: https://stackoverflow.com/questions/34936590/why-isnt-my-vector-drawable-scaling-as-expected

Also, are these vector icons reused in different places with a different scale? Then Google recommends to create a copy of them for each resolution.
