### ISSUE TITLE
Add option to change Tracks colors

### ISSUE THREAD

**Issue by Volodymyr-13** [organicmaps/organicmaps#3559]
I have imported a lot of **.kml** files as routes, if I enable more than 1 route, they all just red color, I can't understand where is what.

1 and 2 it's a different routes, but some paths are close in the way, I just want to change their colors.. so I can't separate them.

![IMG_6636](https://user-images.githubusercontent.com/3391456/194656790-0aff20d3-dc49-441a-b3b6-dbdd4ed42be3.PNG)![IMG_6637](https://user-images.githubusercontent.com/3391456/194656836-14379133-f712-420d-bcb8-e68d538172c6.PNG)

**Comment by biodranik** [comment]
Until we add a color change option, you can manually edit the default color in KML files and then import them.

**Comment by Friptick** [comment]
Seconded. Bookmark lists - i.e., types - are not especially useful if all bookmarks look the same on the map, as currently.

This project's intro mentions "travelers" and "tourists" right at top. As it happens, this is exactly the category that has been a little neglected by Osmand (in favor of outdoor sportspeople and drivers).

For traveling and tourism, decent bookmarking is _super_ important.

Thanks for your work.

**Comment by biodranik** [comment]
You already can change an individual bookmark color. The issue is about changing tracks colors.

**Comment by Friptick** [comment]
Yes, wrong issue. Sorry about that. Just recreated it in the correct one, #1805

**Comment by Friptick** [comment]
Maybe merge this with #3672 and copy over OP's screenshot.

**Comment by Volodymyr-13** [comment]
@biodranik @Friptick 
I have over 50 tracks created in gpx.studio, and managing and assigning different colors to all of them is proving to be impossible.
What I really want is the ability to select 2-3 tracks, enable them in the view, and then easily change their colors to red, blue, and black. This is crucial for me because I use these tracks to compare and choose my rides based on road conditions, and having distinct colors for each track is essential.
It would be incredibly helpful if you could add an option to change or override the color for any tracks, making the process much more efficient and user-friendly.

**Comment by biodranik** [comment]
We all want this implemented. Any volunteers to help?

**Comment by Aurareus** [comment]
This is implemented now.
