### ISSUE TITLE
[android] Back button in the Search dialog does not hide cursor

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3564]
The back button hides the keyboard, but the cursor is still blinking. Reproduces on Android 8 and 9.

**Comment by Gnorv** [comment]
Can confirm this is also true for my Android 12 device.

**Comment by Jean-BaptisteC** [comment]
https://stackoverflow.com/questions/5582702/disable-edittext-blinking-cursor

**Comment by biodranik** [comment]
@Jean-BaptisteC can the focus be removed from the EditText when the back button that hides the virtual keyboard is pressed?

**Comment by biodranik** [comment]
While it looks inconsistent to me (what's the reason to keep blinking cursor if there's no way to type text there?), and on iOS there's no such behavior, it looks like all Android apps behave similarly. So changing the system/default behavior may not be what users expect. Instead of writing code, we can avoid it and leave things as is.

Maybe we'll come back again to this issue in the future to make a _perfect_ app, who knows.
