### ISSUE TITLE
Scale ruller in navigation mode

### ISSUE THREAD

**Issue by Yourez** [organicmaps/organicmaps#3565]
Please show the scale ruller in navigation mode like it done in observe mode. It will help to estimate distances by view.

**Comment by biodranik** [comment]
The trickiest part is: where to draw it? It is more critical in landscape mode, where side buttons can be very close to top and bottom panels.

**Comment by Yourez** [comment]
In my case, in landscape mode, bottom bar occupies bottom left half of the screen, so ruller can be placed at the bottom right half.

**Comment by maze88** [comment]
I suggest allowing a few options for placement such as 'bottom right', 'right', 'top', 'none'.
I'd definitely beneif from such a feature! (:

**Comment by Jean-BaptisteC** [comment]
Implement here #5381
