### ISSUE TITLE
Missing voice instructions for Catalan language in Android platform

### ISSUE THREAD

**Issue by jmontane** [organicmaps/organicmaps#3568]
Catalan language support was added recently. Voice instructions work fine at iOS, but I'm unable to get voice instructions in Catalan language at Android platform.

Google Android TTS device engine doesn't support Catalan language. So, I read [this guide](https://mapsme.zendesk.com/hc/en-us/articles/208628985-How-can-I-check-TTS-settings-on-my-Android-device-).

I installed a [third party TTS engine](https://play.google.com/store/apps/details?id=es.codefactory.vocalizertts&hl=en&gl=US), but Organic Maps ignore it. I'm unable to activate voice instructions. So, Organic Maps doesn't provide Catalan voice instructions.

Espeak-ng is an open source TTS engine with poor quality Catalan support. Installing espeak-ng activates Organic Maps voice instructions menu, but Catalan isn't available at language list.  So, Organic Maps doesn't provide Catalan voice instructions.

Is there any way to Organic Maps manage third party Android TTS engines? Or, otherwise, Could Organic Maps use Google on-line TTS to languages not supported by Android TTS?

**Comment by biodranik** [comment]
Did you try to restart the app and reboot the device? Some users reported that it helped them.

Also, there were reports that installing RHVoice in addition to eSpeak somehow activates eSpeak.

If it won't help, please enable logs in OM settings, restart the app, and send us logs via "?" -> Report a bug, we'll take a look at TTS.

**Comment by jmontane** [comment]
Restarting app and rebooting device don't help. Neither installing RHVoice, which lacks Catalan voice support.

I think I found the cause. Catalan language is missing in [strings-tts.xml file](https://github.com/organicmaps/organicmaps/blob/master/android/res/values/strings-tts.xml#L19). I guess adding language code `ca`

>
    <item>en</item>
    <item>ru</item>
    <item>ca</item>
    <item>cs</item>
    <item>da</item>
    ...

and language name `Catalan`...
> 
    <item>English</item>
    <item>Русский</item>
    <item>Català</item>
    <item>Čeština</item>
    ...

 will do the trick. I can make a PR with these changes, but I'm unable to test them (I'm not a programmer).

**Comment by Misalf-git** [comment]
FWIW, for eSpeak to function, I have to explicitely set the TTS language to anything but "System language".
Choosing it automatically doesn't seem to work.

Android 12, Lineage based + microG

**Comment by biodranik** [comment]
> I can make a PR with these changes, but I'm unable to test them (I'm not a programmer).

Please do. Then you can download a zipped apk from this PR and test it on your device.

**Comment by jmontane** [comment]
I've tested it. It works like a charm. All tested TTS engines with Catalan language support, Google TTS, espeak NG, and CTV Vocalizer, provide voice indications in Catalan language at Organic Maps
