### ISSUE TITLE
POI types visible on map but not searchable

### ISSUE THREAD

**Issue by Kazing** [organicmaps/organicmaps#3582]
Recently I wanted to search for record store in a city, but search returned only shops with "record" in their names.

After looking in https://github.com/organicmaps/organicmaps/blob/master/data/categories.txt
I see there is no search aliases for `shop=music` and for plenty of other features that are shown on map (such as `shop=cheese` `shop=musical_instrument` `shop=paint` `shop=medical_supply` `shop=fabric` `shop=antiques` `shop=tea` `shop=interior_decoration` `shop=art` `shop=storage_rental`)

IMO the shop types that are visible on map shall be searchable.

**Comment by biodranik** [comment]
Can you sync categories.txt with data/strings/type_strings.txt to fix the search? We plan to fix it so the copy-paste will be not necessary.
