### ISSUE TITLE
[android] Enforce HTTPS

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#3610]
Missing SSL in 2022 this is not a thing we will be able to explain to anybody.

> Permitting cleartext traffic could allow eavesdroppers to intercept data sent by your app, which impacts the privacy of your users. Consider only allowing encrypted traffic by setting the cleartextTrafficPermitted tag to "false".
More info: https://developer.android.com/preview/features/security-config.html
Note: This issue has an associated quickfix operation in Android Studio and IntelliJ IDEA.
To suppress this error, use the issue id "InsecureBaseConfiguration" as explained in the [Suppressing Warnings and Errors](https://github.com/organicmaps/organicmaps/issues/new#SuppressInfo) section.

```
   <?xml version="1.0" encoding="utf-8"?>
   <network-security-config>
     <base-config cleartextTrafficPermitted="true">                                                    
     </base-config>
     <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">organicmaps.app</domain>
```

**Comment by biodranik** [comment]
We are not missing SSL. It is used everywhere in our code. Clear text HTTP is enabled to properly load images from users' bookmark HTML descriptions in edited or imported KML files.
