### ISSUE TITLE
[android] Find a better way of getting system status bar height

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#3611]
The current approach is hacky:

https://github.com/organicmaps/organicmaps/blob/04422bef3fa3396d31a497a3ac6ee2dec5bc6497/android/src/com/mapswithme/util/UiUtils.java#L366-L375

See https://stackoverflow.com/questions/3407256/height-of-status-bar-in-android

**Comment by arnaudvergnet** [comment]
See https://github.com/organicmaps/organicmaps/pull/3495
