### ISSUE TITLE
Searching for addresses with one of the Norwegian words for street, "gate", fails

### ISSUE THREAD

**Issue by guleri** [organicmaps/organicmaps#3616]
When I search for addresses that contain the word "gate", for example "Vogts gate 64", nothing happens other than the spinning waiting symbol. If I leave out the word "gate", and search for "Vogts 64", it works fine, but that’s not intuitive at all, and I only figured out that had to do it this way by a coincidence. It's the same for all similar names, and since it's a very common way to write street names in Norway, I would say it's major issue for users in Norway.

Version tested 2022.09.22-3-Fdroid.

**Searching for the full street name and number:**
![signal-2022-10-13-095337_002](https://user-images.githubusercontent.com/2116676/195538016-a7b9e4a3-4baa-45aa-abd4-83d981fa0b26.jpeg)

**Leaving out "gate":**
![signal-2022-10-13-095356_002](https://user-images.githubusercontent.com/2116676/195540439-19b305b5-b6a6-4ac7-aae6-2bd2f7d01174.jpeg)

**Comment by biodranik** [comment]
1. What is your device model? How old is it?
2. Do you shore maps on an SD card and how old and how slow is the card? If yes, did you try to move maps to internal memory and see how fast you see search results?
3. Did you try to wait for several minutes? It could be slow for a number of reasons.

**Comment by guleri** [comment]
1. Asus Zenfone 8, about 2 years old.
2. No SD card.
3. Yes. And it's only with this particular type of street name, i.e. "xxxx gate #", so I'm quite sure slowness is not the case.

Similar street names, with other Norwegian words for street, like "Christian Sindings vei 4" or "Iduns vei 4" works fine.

**Comment by eisams** [comment]
@vng "gata" would still be a valid street synonym

The synonyms "veg" and "vegen" should definitely also be added, and possibly "allé"

"svingen" is not really a street synonym, but a street name suffix. There would be plenty more of those though.

"plass" actually means a location as in a specific city square
