### ISSUE TITLE
[bug] steps should be rendered above platform

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#3620]
<img width="165" alt="Screenshot 2022-10-13 at 22 22 23" src="https://user-images.githubusercontent.com/26939824/195713477-de90f9cb-8fc6-4b93-b0ee-996135920969.png"> 
<img width="165" alt="Screenshot 2022-10-13 at 22 24 21" src="https://user-images.githubusercontent.com/26939824/195713630-fa14e529-edf1-470c-8d99-a9605a8e4ac0.png">

https://www.openstreetmap.org/#map=19/51.48268/0.00332

**Comment by vng** [comment]
Actually, it is rendered above. But because pedestrian style has white dashed line only (without casing for bridge like other highways), looks like it is _mixed_ with railway.

**Comment by vng** [comment]
<img width="372" alt="Screenshot 2022-10-14 at 12 55 41" src="https://user-images.githubusercontent.com/175612/195819132-cf0bb1ae-14a4-4176-a6c2-ab683916261c.png">

**Comment by endim8** [comment]
ooops, this was meant to be submitted to https://github.com/gravitystorm/openstreetmap-carto 😅
