### ISSUE TITLE
Building a route from Jal, NM to Corpus Christi, TX takes a lot of time

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3625]
It takes several minutes on iPhone 6 Plus. Also, the progress is not updated for a very long time. While foot and cycling routes are building 2-4 times faster, with a proper progress update.

https://omaps.app/EjbbJ3o2YH/Jal

https://omaps.app/EjW5v8DgaN/Corpus_Christi

**Comment by vng** [comment]
Also (54.05054, 35.22995) -> (44.72269, 37.76173)

**Comment by Jean-BaptisteC** [comment]
First example:
- Car = 30 seconds
- Walk = 47 seconds
- Cycling=43 seconds

I can't test second example, OM return error message -> Unable to create route
@vng can you check ?

**Comment by vng** [comment]
Make sure that you have Western Russia regions downloaded.

**Comment by Jean-BaptisteC** [comment]
Yes, you right, i have forgot to download map around Louhansk

Car=30 seconds
Foot=32 seconds
Cycling=34 seconds

@biodranik can be closed ?
