### ISSUE TITLE
[android]  getSystemWindowInsetXXX() in WindowInsets has been deprecated

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#3631]
int 	[getSystemWindowInsetLeft](https://developer.android.com/reference/android/view/WindowInsets#getSystemWindowInsetLeft())()

This method was deprecated in API level 30. Use [getInsets(int)](https://developer.android.com/reference/android/view/WindowInsets#getInsets(int)) with [Type#systemBars()](https://developer.android.com/reference/android/view/WindowInsets.Type#systemBars()) instead.

CC: @arnaudvergnet

**Comment by arnaudvergnet** [comment]
Fixed by https://github.com/organicmaps/organicmaps/pull/4591
