### ISSUE TITLE
Italian translations for types_strings

### ISSUE THREAD

**Issue by 501Ghost** [organicmaps/organicmaps#3635]
My girlfriend has been so kind to help us with Italian translations for the tags, and to teach me some Italian words while we were working on this. I still have no idea how pull requests work, but please review this. I also updated a handful other (mainly Dutch) translations that we came across.

[types_strings.txt](https://github.com/organicmaps/organicmaps/files/9789944/types_strings.txt)

I downloaded the document on 2022-10-10, so if other translations have been added in the meantime there may be conflicts that need to be reviewed.

Cheers

**Comment by hiddewie** [comment]
@501Ghost I made a PR of the changes in the linked file. Please review it if you think the changes are correct and as you meant them.

**Comment by 501Ghost** [comment]
I checked https://github.com/organicmaps/organicmaps/pull/3644/files/ffd527bea82057d93626f7204d1873b89f33797d and all changes seem to be as I meant them. Thank you for making the PR.
