### ISSUE TITLE
Make place page peek height properly adapt to Wikipedia/bookmark description

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#3637]
At least on android, the place page peek height is set to a fixed value when a Wikipedia article is available. It is often less then the size of the preview. It would be better to show the full preview.

| expected | current |
|-|-|
| ![Screenshot_20221015-001539_Organic_Maps](https://user-images.githubusercontent.com/80701113/195951808-6f1ffd48-626f-41f6-8afc-0b9ef165bcde.png) | ![Screenshot_20221015-001530_Organic_Maps](https://user-images.githubusercontent.com/80701113/195951810-1047f847-0cf4-4ea0-9841-5e7af6e698b7.png) |

The same issue happens with bookmark description. If it is small enough, the place page should show only the description in the same way the Wikipedia article is shown.

| expected | current |
|-|-|
| ![Screenshot_20221015-001759_Organic_Maps](https://user-images.githubusercontent.com/80701113/195952157-0db6ac30-42b0-4063-ac1d-faa65415c5e4.png) | ![Screenshot_20221015-001748_Organic_Maps](https://user-images.githubusercontent.com/80701113/195952163-59619014-3d95-4473-88cb-0b9b66848335.png) |

In case there is both a Wikipedia preview and a bookmark description, I think only the description should be shown with the Wikipedia below. But https://github.com/organicmaps/organicmaps/issues/2825 should be fixed before as the Wikipedia preview is lost when a POI is bookmarked.

**Comment by biodranik** [comment]
It could make sense to reduce the preview height for the bookmark's description and wiki data to avoid unexpected map jumps.

**Comment by arnaudvergnet** [comment]
When reworking the place page, we decided it is better to have a predictable peek height so making it adapt to the wikipedia description size would be confusing for the users.
