### ISSUE TITLE
Show and copy address in PP.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#3638]
Here is what we see now in iOS (with ability to copy address):
![photo_2022-10-15 10 27 19](https://user-images.githubusercontent.com/175612/195974820-a0824c8c-1dd5-4329-9038-db293760575a.jpeg)

Here is Android (no address cell):
<img width="357" alt="Screenshot 2022-10-15 at 10 24 27" src="https://user-images.githubusercontent.com/175612/195974839-ee151702-457e-4593-b90d-9b07a0749c93.png">

If we click on address only building (not POI), there is no separate address field in PP and there is no way to copy it on both platforms.

**Comment by vng** [comment]
BTW, is it ok that we show "Add business" button in PP for already existing POI?

**Comment by vng** [comment]
@arnaudvergnet 
User claims that _copied_to_clipboard_ message disappeared (Copied to clipboard: %1$@) on latest Android release, when copying address. I have no idea how to copy address now in Android ..

**Comment by arnaudvergnet** [comment]
Seems to be working without problem on latest android. Also works for the POI name.

https://user-images.githubusercontent.com/80701113/195977001-42cbe7cb-6d76-4e2d-9a8d-a1808db70b43.mp4

**Comment by vng** [comment]
Hm:
- Is it long tap or what? I'm trying to make long tap (double tap) on emulator (Pixel 5 API 32), no luck ..
- What about single building address (not POI)?

**Comment by endim8** [comment]
It's a long press

It'd be good if a proper address was shown for houses etc, as that's basically all information that is needed about them.
Like this:
![signal-2022-10-15-145701_002](https://user-images.githubusercontent.com/26939824/195991043-a3bd8f7b-beba-4361-a9c7-c4da0d0f547c.png)

**Comment by GreenAloe** [comment]
Android 10, on a long tap address is copied, but there is no any toast message.

**Comment by biodranik** [comment]
It should be visible to the user if it's copied, of course! Or a more expected way with a popup "Copy" should be used.
