### ISSUE TITLE
When searching for cafe a cosmetics shop appears in the search results

### ISSUE THREAD

**Issue by ArcoMul** [organicmaps/organicmaps#3655]
I'm seeing no reason it should show up.

Can't find a link between cosmetics shop and cafe in [categories.txt](https://github.com/organicmaps/organicmaps/blob/master/data/categories.txt) or [types_string.txt](https://github.com/organicmaps/organicmaps/blob/master/data/strings/types_strings.txt)

Node: https://www.openstreetmap.org/node/1351928392

<img width=400 src="https://user-images.githubusercontent.com/1388162/196038132-6bc60e64-12f1-4fe9-b139-ceedffc1f594.png" />

<img width=400 src="https://user-images.githubusercontent.com/1388162/196038123-74dff9e1-17ec-461a-af9b-de8cfbbb3d58.png" />

**Comment by vng** [comment]
Can't reproduce on latest master with English language ..
You have Germany system language. What input language was used? English or German?

**Comment by vng** [comment]
Same with cafe -> care -> child care -> kindergarten ;)

**Comment by ArcoMul** [comment]
Great! My apologies for not getting back to you

**Comment by vng** [comment]
No problem. I made this comments for me, not to forget _synopsis_ when I'll gonna fix this bug.

**Comment by vng** [comment]
One more example: shoe -> shop. Search for "shoe store".

**Comment by zyphlar** [comment]
I would even be okay with fuzzy search results displaying on the map... if those results are reflected in the list and lower priority than exact matches like #4190 -- I hear that "search in viewport" is a preferred fix but when similar named streets exist they appear as small blue dots which is confusing behavior especially when the list of results still includes "Taco Bell"s for the entire state. It's as if the viewport ("view in map") mode is more fuzzy than the search itself.

**Comment by biodranik** [comment]
@vng should it be closed?
