### ISSUE TITLE
Runtime error on mac M1

### ISSUE THREAD

**Issue by 4x10m** [organicmaps/organicmaps#3658]
Plop, 
So i tried to compile organics maps myself.
Firstly, im not apple developper program enrolled so i was blocked by the carplay entitlement that i just removed to make compilation happen.
Secondly, i had to delete associated domains.
Finally, i got a runtime error
![Capture d’écran 2022-10-16 à 23 30 36](https://user-images.githubusercontent.com/6149277/196059363-3372589d-01b1-4126-b6bd-f867ed8bc54f.png)
I can't understand why you are, here, trying to retrieve program3d before checking isPerspective because when i remove program3d stuff, i do not get the error.
![Capture d’écran 2022-10-16 à 23 32 53](https://user-images.githubusercontent.com/6149277/196059452-9df1d5cc-8815-47d3-8ef7-976c56d7aad2.png)
I modified PrepareBucket to
```
void FrontendRenderer::PrepareBucket(dp::RenderState const & state, drape_ptr<dp::RenderBucket> & bucket)
{
  CHECK(m_context != nullptr, ());
  auto program = m_gpuProgramManager->GetProgram(state.GetProgram<gpu::Program>());
  program->Bind();
  bucket->GetBuffer()->Build(m_context, program);
}
```
Do i need to make a pull request which try to retrieve program3d AFTER having checked that we are in perspective mode ?

Regards

**Comment by vng** [comment]
Well, FrontendRenderer::PrepareBucket can be written in more pretty way, definitely. I'll do it by myself.

But it doesn't explain your crash. Don't know what did you delete and is your build target valid, but "vsTextBollboard" should present. It is defined in kMetalProgramsInfo.

**Comment by 4x10m** [comment]
Thank you for fast answer.

I deleted "OMaps-Debug.entitlements" file.
Also in the OMaps xcode target i clicked the bin button in the "associated domains" part of "signing and capabilities" tab.
And finally i checked "automatically manage signing".
That's all

"But it doesn't explain your crash. "

You are right and its difficult for me to give revelants informations about that bug since i do not understand anything about shaders, metal, vulkan... and the fact im loosed into this MASSIVE omim code base (i do not even know how to go perspective mode and i don't understand why google don't know "vsTextBollboard" LUL (but don't loose time to explain those things to me, im just lacking time to learn).
Is it revelant to specifiy that is do not get errors on iphone simulator.

Maybe we should wait to see if other peoples got this error. BTW, my mac is really pretty stock, i just factory reseted it less than one week ago and only installed xcode on it.
Do you have a mac ? M1 ?

**Comment by biodranik** [comment]
Do you have any other warnings or errors? Could it be that you don't have working python installation? Could it be that shaders didn't compile properly on your machine?

Does command line build work for you?

**Comment by 4x10m** [comment]
Heum....

![Capture d’écran 2022-10-18 à 11 03 47](https://user-images.githubusercontent.com/6149277/196387406-576e2bda-dad4-4270-a0bb-11db42f978fb.png)

I tried to re-compile this morning to prepare my answer and.... No more error... I'm crying... I did absolutely nothing... I'm so sorry.

> * so, if you select iPhone Simulator and everything works fine, then My Mac (Designed for ...) target is not suitable

I don't understand the cause and effect relationship. Are you saying that this error is normal if i do not get any error on iPhone Simulator ? If yes, i don't understand why.

> Do you have any other warnings or errors?

I don't see any other thing or may be i don't know where to watch.

> Could it be that you don't have working python installation? 

May i forgot to say that i runned "confiure.sh" before opening the project ? 🤐

> Could it be that shaders didn't compile properly on your machine?

That seems to be a good path to me. How can i know it ?

> Does command line build work for you?

Like "xcodebuild....", please let me be lazy on that point 🙄


So anyway, my goal was to run the project and it's currently running... So we may closed this issue ?
I would still be grateful to learn how i can know shaders has been compiled.

Thank you for help.
