### ISSUE TITLE
[Android] Make dark theme consistent in Auto mode

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#366]
Device: Xiaomi Redmi Note 9 Pro
OS: LineageOS 17.1 (Android 10.0)
App ver.: 2021.04.24-16-g3793046ba4-Web-beta

When Night Mode is set to ``Auto`` and it's evening/night time of the day, the app enables the dark theme only when route is active. When route is canceled, the app goes back to the light theme. This is especially "nice" when you're cancelling route at night. Here's the video of it - you can see that the theme changes to light when I'm pressing Back button:

https://user-images.githubusercontent.com/22843816/116931282-7b977880-ac69-11eb-981d-ecd0100c8d46.mp4

Dark theme should be used through all app when Auto Night Mode is on

**Comment by rtsisyk** [comment]
I drafted a proposal: https://github.com/organicmaps/organicmaps/issues/749
Please review and comment.

**Comment by rtsisyk** [comment]
Superseded by #749.
