### ISSUE TITLE
Survey point hide building (ruins)

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3664]
On OM this survey point https://www.openstreetmap.org/node/670178910 hide this building https://www.openstreetmap.org/way/103142065 (POI ruins is hide). Need to use search to access informations about building.

**Comment by biodranik** [comment]
How it looks like on the map/screen?

**Comment by Jean-BaptisteC** [comment]
Without POI ruins:
<img src="https://user-images.githubusercontent.com/87148630/196252328-355c7cd9-56dc-4a27-b5e4-230696a936e1.png" height="600"/>

With POI ruins (survey_point is hide):
<img src="https://user-images.githubusercontent.com/87148630/196252456-6cfd63ef-198e-4146-a9fd-0a48de6adc62.png" height="600"/>
POI ruins disappear if i increase zoom level

**Comment by biodranik** [comment]
@vng is it a z-order style issue?
