### ISSUE TITLE
[ios]: rearrange toolbar buttons

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#367]
Device: Xiaomi Redmi Note 9 Pro
OS: LineageOS 17.1 (Android 10.0)
App ver.: 2021.04.24-16-g3793046ba4-Web-beta

In older Maps.ME versions ``Search`` button was closer to the right corner of the screen. Don't know why, but Mail.Ru then moved it to the left corner.

May be I'm not aware of last tendencies in UI design, bit I think that:
1. The more frequently the button is used, the closer it should be to the right corner of the screen so you hadn't stretch your fingers to reach it. Of course there's a left-handed case but it's definitely not the major one;
2. It's very doubtful that Search button is the most rarely used so it have to be on the left of even Routes button.

Is it possible to rearrange buttons and move ``Search`` closer to the right corner?

Personally I think that the best layout is something like this: ``Routes→Favorites→Search→Menu``

**Comment by maciboy** [comment]
As a left handed person, I dislike this ;)

**Comment by PetbkA** [comment]
> As a left handed person, I dislike this ;)

Current layout isn't the best for you either 'cause Search button is strictly in the corner so you have to "bend" your finger to reach it with one hand.

The second and third position is the most appropriate for frequently used buttons, that's why I offered to put Search and Favorites there.

Of course, the most flexible way would be to allow user to rearrange the buttons as he wants (e.g. by long-tapping and dragging them), but it would be very time consuming feature, as I can guess

**Comment by maciboy** [comment]
It was a joke, more or less ;)
But muscle memory might be a bit tricky at the beginning…
When looking at the latest commits, search and routing button have been switched lately, as you wish

**Comment by maciboy** [comment]
See https://github.com/organicmaps/organicmaps/commit/f0d3e7f5a5bf3450829107c301c35bc310e5bbee

**Comment by rtsisyk** [comment]
@biodranik could you please unify the toolbar layout both on Android and iOS?

**Comment by biodranik** [comment]
Let's start with routes -> search -> secret button -> bookmarks -> menu and see how it goes.

**Comment by PetbkA** [comment]
> secret button

What is "secret button"? :)

**Comment by rtsisyk** [comment]
Done
