### ISSUE TITLE
Seperate directory for bookmarks (for sync for backup)

### ISSUE THREAD

**Issue by brunetton** [organicmaps/organicmaps#3670]
I'm using Organic Maps everyday! And thanks a lot for that.

I'm adding many many previous bookmarks everyday, but some months ago my phone fall in water and I lost everything 😢
Now I would like to sync those bookmarks to a drive. I know that I can export manually to a KMZ file but I'm looking for an automatic way to do that.

After writing those words I found this thread: https://github.com/organicmaps/organicmaps/discussions/517
This appears to be difficult to realize if I'm right.

**Comment by biodranik** [comment]
Please search for relevant issues to link them together. Also, please search for Android 11 scoped storage restrictions.

**Comment by brunetton** [comment]
> Please search for relevant issues to link them together. Also, please search for Android 11 scoped storage restrictions.

Yes I searched for similar issues but didn't found one (maybe I missed something). Then, after creating the issue I found the thread https://github.com/organicmaps/organicmaps/discussions/517.

**Comment by brunetton** [comment]
My very bad, here is another similar issue: https://github.com/organicmaps/organicmaps/issues/3296
