### ISSUE TITLE
Wrong objects are highlighted when search results are displayed on map

### ISSUE THREAD

**Issue by dbf256** [organicmaps/organicmaps#3677]
I try to search for "rewe" and search result page is fine. But when I try to display results on map some un-related objects are highlighted with blue dots.

![Screenshot_2022-10-19-18-45-22-706_app organicmaps](https://user-images.githubusercontent.com/2550295/196777702-a081fe50-c016-43c5-839a-4c45cb9f908e.png)
![Screenshot_2022-10-19-18-45-41-486_app organicmaps](https://user-images.githubusercontent.com/2550295/196777707-304250c8-ebe3-493c-92d8-527f05aea941.png)
![Screenshot_2022-10-19-18-45-36-549_app organicmaps](https://user-images.githubusercontent.com/2550295/196777709-9de01e67-3314-4a79-bdaf-ce15757b5f01.png)

**Comment by telluroid** [comment]
When searching for "Warte" in Frankfurt, Germany I get "Bockenheimer Warte" but not "Friedberger Warte" despite being closer to the latter. When going to the map all kinds of trash cans and recycling containers are highlighted as well as some streets and anything that closely matches the word.

**Comment by vng** [comment]
Confirm. The app mixes "warte -> waste". Same as https://github.com/organicmaps/organicmaps/issues/3655

**Comment by biodranik** [comment]
@vng that should be fixed systemically to avoid garbage, as we discussed before.
