### ISSUE TITLE
Blue point disappear or are not present when you show map from search

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3680]
<img src="https://user-images.githubusercontent.com/87148630/196784081-00836855-5687-4739-b8d6-328539b5adc3.png" height="600"/>

Link to place on OSM -> https://www.openstreetmap.org/node/7746716203

I have searched fire_hydrant in search and after used button to search results on map, blue POI are not show on all fire_hydrant.
Examples:
- fire_hydrant in front of number house 11
- fire_hydrant in front of number house 30 (but i think, zoom level is not enough)

**Comment by Kazing** [comment]
Similar to issue #1003 ?
