### ISSUE TITLE
Fix OSM changes text layout on Android

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3683]
It doesn't fit with a large font. Layout should work properly with any font size, also in landscape. 

![image](https://user-images.githubusercontent.com/170263/196864628-34e81c2b-3dd3-4010-ad83-984bd805acbf.jpeg)

**Comment by arnaudvergnet** [comment]
As this text is already big, a quick fix would be to simply disable font scaling for it

**Comment by biodranik** [comment]
Appropriate layout scaling is also an option.

**Comment by Jean-BaptisteC** [comment]
Fixed by #2909
