### ISSUE TITLE
Floating toolbar instead of individual buttons

### ISSUE THREAD

**Issue by Donkey-Doug** [organicmaps/organicmaps#3700]
The individual floating buttons look a little bit cluttered:

![Screenshot_20221022-140018_Organic Maps](https://user-images.githubusercontent.com/50382414/197337888-57f23bd0-43a3-4517-ba0e-ec8da3de91a2.png)

Perhaps make a flaoting toolbar with all the button:

![Screenshot_20221022-135916_Stealth](https://user-images.githubusercontent.com/50382414/197337910-2ec1562b-4ede-47b3-9960-11c596cf7def.png)

**Comment by biodranik** [comment]
The idea was to _remove_ toolbars, to show more of the map :)

Next steps are to customize and improve buttons.

**Comment by Altonss** [comment]
> Next steps are to customize and improve buttons.

Maybe they could be made a little bit more visible, maybe more contrast?

**Comment by biodranik** [comment]
Maybe, you can help us by experimenting with it, and sharing screenshots that you like the most.

**Comment by Altonss** [comment]
> Maybe, you can help us by experimenting with it, and sharing screenshots that you like the most.

Yes I could help you with experimenting :) But I don't really know how it works on a technical level to tweak the visual aspect of the buttons... I would need to try and dig in the code, and try to understand how it works :)

**Comment by Donkey-Doug** [comment]
> The idea was to _remove_ toolbars, to show more of the map :)
> 
> Next steps are to customize and improve buttons.

Hide on ~scroll~ pan?

**Comment by Jean-BaptisteC** [comment]
We have recently done the same thing in IOS and we do not have a bad feedback about these changes.
I close this issue for now, she can be reopened if a better proposition is suggested without taking more space on screen.
