### ISSUE TITLE
Weird result with search about fire_hydrant in French 

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3712]
During my test for #3709.

I have some problems to search fire_hydrant:

- I search fire_hydrant -> fire_hydrant near is showed (most near is 100m)
- I search Bouche incendie -> fire_hydrant near is showed (most near is 100m)
- I search Bouche d'incendie (real orthography in BottomSheet when i click on fire_hydrant POI) -> fire_hydrant show is not near (4,4km)

Search is too long in version [WebDebug ](https://github.com/organicmaps/organicmaps/actions/runs/3306246860)is it normal ?

CC @vng

**Comment by biodranik** [comment]
All Debug versions are _very_ slow, they do a lot of safety checks underneath. So it is normal.

Just to confirm, did you test the mentioned branch `vng-fix`? Not the `master` one?

**Comment by vng** [comment]
Do you have French device system language? Or French input keyboard layout during this test?

**Comment by Jean-BaptisteC** [comment]
Yes, i have test with vng-fix branch.
I have same issue with 2022.09.23-3-Google.
I used French language in system and in input keyboard
