### ISSUE TITLE
[android] Screen blinks after returning back from the full-screen mode

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3727]
On Android 8 and 9, after returning back from full-screen mode the screen blinks. To reproduce, tap once to hide UI controls, and then tap a second time to return them back. 

_Originally posted by @biodranik in https://github.com/organicmaps/organicmaps/issues/3654#issuecomment-1288219597_

**Comment by arnaudvergnet** [comment]
> Same blink on S9+ with Android 10 and default Vulkan.

https://github.com/organicmaps/organicmaps/pull/3654#issuecomment-1290142094

**Comment by arnaudvergnet** [comment]
I managed to reproduce the issue on an Pixel 5 API 28 emulator, but it is not happening every time.

**Comment by biodranik** [comment]
Something _invalidates or redraws_ the screen. It should be easy to debug, no?
