### ISSUE TITLE
Top elements are cut off in Android Navigation mode

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3732]
That's a regression, likely related to #3654

Reproduces on Android 13 Pixel 6, and Android 9 Moto g6, not always, but 90% of the time.
It's happening for car, bike, and pedestrian navigation. No specific steps, on the road, with location following enabled (blue arrow button).

Entering & exiting the spit-screen or switching apps doesn't solve the issue. The top is still cut off.

![2022-10-26 11 10 12](https://user-images.githubusercontent.com/170263/197985360-86de3a36-015a-42ec-b20a-ecd25310ec25.jpg)
![2022-10-26 11 10 06](https://user-images.githubusercontent.com/170263/197985367-d82daa8d-3895-4a8a-9c3c-e3c3ef11877d.jpg)

**Comment by biodranik** [comment]
@arnaudvergnet this is the only issue left that blocks our Android update.

**Comment by rtsisyk** [comment]
<img width="428" alt="Screen Shot 2022-10-29 at 16 16 10" src="https://user-images.githubusercontent.com/1799054/198842459-b3fb71c6-baee-48da-b8ed-ef2d2ad1cded.png">
<img width="330" alt="Screen Shot 2022-10-29 at 16 16 24" src="https://user-images.githubusercontent.com/1799054/198842461-626258e4-7f07-4a78-af32-5b486d0a0480.png">
