### ISSUE TITLE
Busways aren't visible

### ISSUE THREAD

**Issue by A67-A67** [organicmaps/organicmaps#3739]
The tag [highway=busway](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbusway) was approved in early 2021, but these roads show up as empty areas in Organic Maps. 

Details around the busway are visible, like fences, bus stops and grass, but the busway itself is missing.

**Comment by biodranik** [comment]
How do you think they should be rendered, compared to other road types in OM?

**Comment by A67-A67** [comment]
I'd say the same width as highway=unclassified or maybe highway=service, if you think that'll look better.

As color I'd pick an unsaturated blue or purple. OSMAnd uses blue, for OSM Carto purple is under consideration. Blue would be comparable to the bus stops, so it's a color that can be seen as a public transport color.

**Comment by biodranik** [comment]
The blue color is definitely a no-go for our current generic style scheme. It will look like an imported track or ski resort track. We need something more neutral.

**Comment by A67-A67** [comment]
Then I think an unsaturated purple ("grey-purple") may be a good choice.

**Comment by matheusgomesms** [comment]
An idea for Carto [currently in discussion](https://github.com/gravitystorm/openstreetmap-carto/pull/4714) is to use the same width and color as service roads, although I would use something like light-purple too.

**Comment by nighto** [comment]
As the author of the previous PR, my proposal for rendering it with the same width and color as service roads, is purely because before the introduction of `highway=busway`, the accepted tagging scheme for busways was `highway=service` + `access=no` + `bus=yes`.

**Comment by vng** [comment]
Example for test: https://www.openstreetmap.org/way/256111937
