### ISSUE TITLE
[ios] Add Wikipedia and Wikimedia Commons link to iOS Place Page

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#3755]
Currently the Android app shows the Wikipedia and Wikimedia Commons links in the Place Page of POIs that have these tags. In iOS currently they are not shown, and they should be added.

Also the Wikimedia Commons icon should be changed to a blue color icon, matching the rest of the Place Page Icons.

| Android | iOS |
|-|-|
| ![](https://user-images.githubusercontent.com/47610359/198870347-dead1948-341a-4a6d-94a4-8dff3395d7ce.png) | ![](https://user-images.githubusercontent.com/47610359/198870366-522dd73f-a343-41bc-8826-d9cb60561cfd.png) |

**Comment by nemissm** [comment]
Нello, @dvdmrtnz! Is this issue in progress? I did some small research and can try to implement it. But if you have already started, I will look at another one.
