### ISSUE TITLE
[ios] Show local language name in iOS Place Page

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#3756]
Currently the Android app shows the name of places in the user language and then in the local language of the place in a smaller font. However, the iOS app only shows the name in the user language. It's missing the local language. This should be added.

Some examples:

| Android | iOS |
|-|-|
| ![](https://user-images.githubusercontent.com/47610359/198870823-1e08d3c0-962f-4839-9962-1ae98b2096b4.png) | ![](https://user-images.githubusercontent.com/47610359/198870928-dbaaa1e0-bd2e-40e9-8d36-2c680054b08b.png) |
| ![](https://user-images.githubusercontent.com/47610359/198870828-bc241955-b222-4621-a90a-b840e8410bea.png) | ![](https://user-images.githubusercontent.com/47610359/198870950-fa1d8d49-8a00-4305-8495-ce7f7e408d50.png) |
| ![](https://user-images.githubusercontent.com/47610359/198870829-4d3f824c-b98f-4a88-8130-40d02505aefb.png) | ![](https://user-images.githubusercontent.com/47610359/198870942-9ee1aced-0805-4924-ac9d-11b4d42f52f9.png) |

**Comment by nemissm** [comment]
Hello! @dvdmrtnz, is this issue in progress? I did some research and can try to implement it. But if you have already started, I will look at another one.

**Comment by dvdmrtnz** [comment]
@nemissm I'm not currently working on this issue. You can go ahead and try to implement it. Thanks!
