### ISSUE TITLE
Use recycling categories in French doesn't work

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3761]
How reproduce:

- Start OM
- Click on search
- Go on categories tab
- Select Recyclage (Recycling in English)
- 0 Results

If i search Recyclage, i have results but it's not sort by distance.
I have try recycling categories in English, it's work fine

Other problem, when i search Recycl in French, OM show me search suggestions but suggestions is in English.

List of search suggestions not translated
- Recycling
- Recycling centre
- Recycling container
- Recycling of batteries
- Recycling of bewerage cartons

Pixel 6 - Android 13
v2022.09.22-3-Google

CC @vng

**Comment by vng** [comment]
Could you please check the validity of French _recycling_ translations in:
strings.txt
categories.txt
types_strings.txt

**Comment by vng** [comment]
If _Recyclage_ is ok (like in strings.txt) then we should also make _Recyclage_ as first keyword in categories.txt

**Comment by Jean-BaptisteC** [comment]
Yes, _Recyclage_ and _Traitement des déchets_ are similar.

**Comment by Jean-BaptisteC** [comment]
I have try to fix problem with this change https://github.com/organicmaps/organicmaps/commit/040d961426e61aad922b779f47b7820bd4e8ce44 -> categories recycling works fine.
But list of search suggestions are not translated and translations in fr are available in types_strings.txt.

**Comment by vng** [comment]
Put a digit (number of letters) to show a search suggestion, like this:
fr:4Recyclage ...
