### ISSUE TITLE
Improve search for amenity=recycling in French

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3762]
In french for Recycling Center, in name of POI, we can write:
- `Déchetterie`
- `Déchèterie`

Source: https://www.larousse.fr/dictionnaires/francais/D%C3%A9chetterie/22144

Some examples:
- https://www.openstreetmap.org/way/201177777
- https://www.openstreetmap.org/way/250265991

Can you add ability to search Déchetterie and Déchèterie and have same results ?

**Comment by biodranik** [comment]
Yes, please edit data/categories.txt

**Comment by Jean-BaptisteC** [comment]
I have try with this change https://github.com/organicmaps/organicmaps/commit/040d961426e61aad922b779f47b7820bd4e8ce44.
But, when i search _Déchetterie_, i don't have POI with name contains _Déchèterie_

**Comment by biodranik** [comment]
@vng data files should be regenerated for each categories.txt modification for search to work, right?

**Comment by vng** [comment]
For each types changes only, not translations.

**Comment by vng** [comment]
@Jean-BaptisteC Adding 2 words as synonyms for amenity-recycling-centre actually works, but ranking will be a bit tricky.
As this tokens (Déchetterie and Déchèterie) are present in names, results with name that exactly match input token will be on top, other recyclings will be at the bottom.

You can check search _in viewport_ that this 2 words successfully match all recycling centers.

**Comment by Jean-BaptisteC** [comment]
The most of recycling centre in France used _Déchetterie_ but if POI used _Déchèterie_ elements is not show in list results.

I know French language is complicated :)
