### ISSUE TITLE
Landuse=garages shouldn't be the same color as buildings

### ISSUE THREAD

**Issue by lunarna-gh** [organicmaps/organicmaps#3766]
Organic Maps
![Screenshot_2022-10-30-15-19-28-577_lockscreen.jpg](https://user-images.githubusercontent.com/113068485/198884024-88ed7b15-91de-42ae-bc19-041b98813a30.jpg)

Carto
![IMG_20221030_152603.jpg](https://user-images.githubusercontent.com/113068485/198884037-1e1392c2-7e10-4963-9cef-90f05bd0fa37.jpg)

The light brown color looks much nicer. It should at least be a slightly lighter gray than buildings.

**Comment by biodranik** [comment]
Can we somehow relate garages to parking colors?

**Comment by lunarna-gh** [comment]
Unassigning myself for now since I can't really get generate_drules.sh to work, looks like python2 is a pain to get working on Fedora 37, keep getting 
```
Traceback (most recent call last):
  File "/home/luna/Code/organicmaps/tools/unix/../../tools/kothic/src/libkomwm.py", line 26, in <module>
    from drules_struct_pb2 import *
  File "/home/luna/Code/organicmaps/tools/kothic/src/drules_struct_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google'
```

**Comment by endim8** [comment]
> I can't really get generate_drules.sh to work, looks like python2 is a pain to get working on Fedora 37

Kothic was updated to use Python3, do the instructions still say Python2 somewhere?

**Comment by lunarna-gh** [comment]
Hm, then python3 doesn't work I guess. I was just looking through old issues that had the same bug, not the fault of the instructions.

**Comment by endim8** [comment]
Ah alright 👍 maybe try reinitialising the submodules with `git submodule update --init --recursive` then re-running `./configure.sh`? i _think_ that's fixed it for me before

**Comment by biodranik** [comment]
It looks like a protobuf python lib issue. How did you install it?

**Comment by lunarna-gh** [comment]
Ah, looks like `protobuf` in the Fedora repos isn't `python3-protobuf` but a different tool, this confused me because all of the other tools without the python3 prefix are correctly linked. Thanks both of you.

**Comment by lunarna-gh** [comment]
What do you think?
![image](https://user-images.githubusercontent.com/113068485/198907821-9b5fd918-ac0f-47ff-90a4-06d95a728fae.png)

**Comment by biodranik** [comment]
On second thought, parking color can mislead someone to park there... Let's try other options and compare them side to side on detailed and non-detailed zoom levels.

**Comment by lunarna-gh** [comment]
I've tried a couple options and ended up on a grayish, less saturated yellow. It can be associated with the parking color without causing confusion and fits OM's color scheme nicely. It may blend in with the background color though.
![Screenshot from 2022-11-03 02-24-14](https://user-images.githubusercontent.com/113068485/199633680-5a6d9c15-3183-45d0-a295-7f46a4ac32fa.png)
![Screenshot from 2022-11-03 02-25-57](https://user-images.githubusercontent.com/113068485/199633697-60d80184-1a86-425d-9a7f-4fa52a1cb4a2.png)
![Screenshot from 2022-11-03 02-22-45](https://user-images.githubusercontent.com/113068485/199633704-8e5328cb-1d36-4e5a-9ea0-8383c440a233.png)

Unfortunately I couldn't test dark mode as I can't find the option to turn it on in the desktop app. Is it possible? Do I have to build the mobile app?

**Comment by biodranik** [comment]
```
bool Framework::ParseDrapeDebugCommand(string const & query)
{
  MapStyle desiredStyle = MapStyleCount;
  if (query == "?dark" || query == "mapstyle:dark")
    desiredStyle = MapStyleDark;
  else if (query == "?light" || query == "mapstyle:light")
    desiredStyle = MapStyleClear;
  else if (query == "?vdark" || query == "mapstyle:vehicle_dark")
    desiredStyle = MapStyleVehicleDark;
  else if (query == "?vlight" || query == "mapstyle:vehicle_light")
    desiredStyle = MapStyleVehicleClear;

  if (desiredStyle != MapStyleCount)
  {
#if defined(OMIM_OS_ANDROID)
    MarkMapStyle(desiredStyle);
#else
    SetMapStyle(desiredStyle);
#endif
    return true;
  }

  if (query == "?aa" || query == "effect:antialiasing")
  {
    m_drapeEngine->SetPosteffectEnabled(df::PostprocessRenderer::Antialiasing,
                                        true /* enabled */);
    return true;
  }
  if (query == "?no-aa" || query == "effect:no-antialiasing")
  {
    m_drapeEngine->SetPosteffectEnabled(df::PostprocessRenderer::Antialiasing,
                                        false /* enabled */);
    return true;
  }
  if (query == "?scheme")
  {
    m_transitManager.EnableTransitSchemeMode(true /* enable */);
    return true;
  }
  if (query == "?no-scheme")
  {
    m_transitManager.EnableTransitSchemeMode(false /* enable */);
    return true;
  }
  if (query == "?isolines")
  {
    m_isolinesManager.SetEnabled(true /* enable */);
    return true;
  }
  if (query == "?no-isolines")
  {
    m_isolinesManager.SetEnabled(false /* enable */);
    return true;
  }
  if (query == "?debug-info")
  {
    m_drapeEngine->ShowDebugInfo(true /* shown */);
    return true;
  }
  if (query == "?debug-info-always")
  {
    m_drapeEngine->ShowDebugInfo(true /* shown */);
    settings::Set(kShowDebugInfo, true);
    return true;
  }
  if (query == "?no-debug-info")
  {
    m_drapeEngine->ShowDebugInfo(false /* shown */);
    settings::Set(kShowDebugInfo, false);
    return true;
  }
  if (query == "?debug-rect")
  {
    m_drapeEngine->EnableDebugRectRendering(true /* shown */);
    return true;
  }
  if (query == "?no-debug-rect")
  {
    m_drapeEngine->EnableDebugRectRendering(false /* shown */);
    return true;
  }
#if defined(OMIM_METAL_AVAILABLE)
  if (query == "?metal")
  {
    SavePreferredGraphicsAPI(dp::ApiVersion::Metal);
    return true;
  }
#endif
#if defined(OMIM_OS_ANDROID)
  if (query == "?vulkan")
  {
    SavePreferredGraphicsAPI(dp::ApiVersion::Vulkan);
    return true;
  }
#endif
  if (query == "?gl")
  {
    SavePreferredGraphicsAPI(dp::ApiVersion::OpenGLES3);
    return true;
  }
  return false;
}
```

**Comment by mpawelski** [comment]
> Unfortunately I couldn't test dark mode as I can't find the option to turn it on in the desktop app. Is it possible? Do I have to build the mobile app?

Just enter `?dark` as search query and `?light` to switch it back. `?vlight` and `?vdark` is also usefull to check.

FYI, if you didn't get why biodranik posted the above code snippet ;)

**Comment by lunarna-gh** [comment]
Thank youu but I got it, I just didn't have enough time in the past couple of weeks to fully test this. I came up with these so far to keep in theme with the light mode one, feedback is appreciated

**Dark**
![image](https://user-images.githubusercontent.com/113068485/202881417-9f9884b7-3906-44b8-b35e-863f027869e0.png)
![image](https://user-images.githubusercontent.com/113068485/202881419-13f4efdc-f3f5-45af-9e07-e8e86ab3612e.png)
![image](https://user-images.githubusercontent.com/113068485/202881427-737c52e2-6353-4d03-9b71-2fb2674efeb8.png)

**Vehicle Light**
![image](https://user-images.githubusercontent.com/113068485/202881447-ab693202-9d41-4a91-879f-99bc1522a4b2.png)
![image](https://user-images.githubusercontent.com/113068485/202881460-8d8937b1-cfe0-4ad1-af38-5f8c5041fe38.png)
![image](https://user-images.githubusercontent.com/113068485/202881461-f16cb0fe-1e3a-44ff-a7b7-20afc1d3d459.png)
^looks similar to parking colors when zoomed out. not sure if this is an issue since there is a clear parking icon shown, but could be tweaked

**Vehicle Dark**
![image](https://user-images.githubusercontent.com/113068485/202881495-06414e34-f822-43c3-a4a1-4df83ecdeee0.png)
![image](https://user-images.githubusercontent.com/113068485/202881503-2b5ad5fa-5f16-431b-bef6-ff9b58097172.png)
![image](https://user-images.githubusercontent.com/113068485/202881506-d9ec6dd3-5aa0-4895-8f92-80687bc5e130.png)
^looks similar to buildings when zoomed out. i've made it dark because it stood out too much, but could be tweaked

**Comment by biodranik** [comment]
I'm not sure that it is now better than before. For example, garages are not visible on the dark theme.

Would it be better if we leave the same color as buildings but apply some kind of a "car" texture for garages (later, when we implement texture support)?

**Comment by lunarna-gh** [comment]
![Screenshot_2022-11-20-14-39-16-094_app.organicmaps.jpg](https://user-images.githubusercontent.com/113068485/202905305-788c8148-49b8-400f-9cea-c78bbf947c5d.jpg)
I don't think it looks worse than it currently does in dark mode, garages are not visible at all. I can try changing the colors

**Comment by biodranik** [comment]
What are the coordinates of this place? Can you please share OM link?

**Comment by biodranik** [comment]
Let's try some different gray colors. Can the difference between buildings and landuse be similar to the color difference in OSM style? For the dark one, it's harder though. Likely, it shouldn't be too different from the background.

You did not change colors of garage buildings, right?
