### ISSUE TITLE
[android] Crash on selecting Feature Category after reloading activity

### ISSUE THREAD

**Issue by AndrewShkrob** [organicmaps/organicmaps#3768]
Tried to reproduce #3757 but possibly found another bug.

Branch: master.
Device: Xiaomi Redmi Note 8 Pro (Android 11).

Steps to reproduce:
* Select point on the map
* Add a place to the map
* Select location and click "Done"
* Select category
* Tap on the selected category (FeatureCategoryFragment will be opened again)
* Lock the phone and wait until the app will be unloaded from the ram (5-7 minutes)
* Unlock the phone (splash screen will appear and FeatureCategoryFragment will be loaded)
* Select any category
* Crash

Error in Logcat:
```
indexer/mwm_set.cpp:92 GetMwmIdByCountryFileImpl(): CHECK(!name.empty()) 
organicmaps/indexer/mwm_set.cpp:92: MwmSet::MwmId MwmSet::GetMwmIdByCountryFileImpl(const platform::CountryFile &) const: assertion "false" failed
```

**Comment by Jean-BaptisteC** [comment]
@AndrewShkrob can you retry with latest version?

**Comment by AndrewShkrob** [comment]
Not reproduced
