### ISSUE TITLE
Climbing rock icon is not consistent across zoom levels

### ISSUE THREAD

**Issue by dbf256** [organicmaps/organicmaps#3770]
See Glatze point, it's icon changes to mountain at some zoom.

![Screenshot_2022-10-30-19-48-12-040_app organicmaps](https://user-images.githubusercontent.com/2550295/198896393-2614e4b7-ee28-4a32-acb9-5457ace7006c.png)
![Screenshot_2022-10-30-19-48-20-589_app organicmaps](https://user-images.githubusercontent.com/2550295/198896395-24ea9a2f-6a9b-42c4-8ceb-d7a974c754c3.png)

**Comment by biodranik** [comment]
@vng it looks like a style error

**Comment by vng** [comment]
https://www.openstreetmap.org/node/3351945183
This point is natural=peak and sport=climbing at the same time.
Peak draws from z12, climbing from z17

**Comment by endim8** [comment]
closing as not an issue
