### ISSUE TITLE
Bookmark list directories, sorting or search

### ISSUE THREAD

**Issue by ioctl-user** [organicmaps/organicmaps#3772]
In current Android version bookmarks doesn't sorted in alphabet order that make a problem while looking for needed bookmark list among a several tens of the same lists.

Could you add one more name hierarchy level for bookmarks (bookmarks directory), or may be alphabetical sort mode for lists, or bookmark list search?

**Comment by biodranik** [comment]
Did you see #1066 ?

**Comment by ioctl-user** [comment]
This suggestion is definitely duplication.
