### ISSUE TITLE
Offer several possible roads when travelling with public transportation

### ISSUE THREAD

**Issue by Kalytis** [organicmaps/organicmaps#3808]
Sometimes it would be good not to have one possible itinerary with public transportations, and have several options, when available.

**Comment by biodranik** [comment]
There are already several similar issues about alternate/alternative routes support for other means of transport.

**Comment by biodranik** [comment]
@Jean-BaptisteC if you're closing as a duplicate, then it's better to provide a reference to the issue that is duplicated.

**Comment by Jean-BaptisteC** [comment]
#4938
