### ISSUE TITLE
Render highway links under lower level non-link highways

### ISSUE THREAD

**Issue by VladimirMorozov** [organicmaps/organicmaps#3818]
Here's how it looks like now
![photo_2022-11-04_23-16-09](https://user-images.githubusercontent.com/2279813/200076842-0e6fb1c0-ae28-4168-bd29-790384edd608.jpg)
![photo_2022-11-04_23-13-15](https://user-images.githubusercontent.com/2279813/200076854-d093518d-32dc-4463-8d85-3cfd5054475d.jpg)
Orange links' ends on top of white highways look strange.

Here is how I propose it should look like. 
![photo1](https://user-images.githubusercontent.com/2279813/200076982-5c69602b-1cdf-419e-98bd-629677399ae0.jpg)
![photo_2](https://user-images.githubusercontent.com/2279813/200076987-a385a44b-43f7-4fa7-9136-81ae51705c3d.jpg)

**Comment by biodranik** [comment]
Won't it break some highways? You can edit the priority yourself in mapcss files in the data folder, regenerate styles, and see how it looks in different places.

**Comment by VladimirMorozov** [comment]
I don't quite understand how it can break anything. The default carto style on OSM follows this rule too.
![изображение](https://user-images.githubusercontent.com/2279813/200127053-8998e87b-1588-45a5-a2f5-844fb3c663af.png)

**Comment by biodranik** [comment]
It is always safer to test it first in many cities. We have complex z-ordering rules in our styles that can break something.

**Comment by Jean-BaptisteC** [comment]
Fixed by #7117
