### ISSUE TITLE
Map data updates are still not independent of application updates.

### ISSUE THREAD

**Issue by cayenne17** [organicmaps/organicmaps#3819]
Hello,
In a previous problem, @biodranik had specified that the next map data updates would be independent of the application updates.
Currently, this is not the case at all, you have to wait for the application updates to benefit from the map data updates.

https://github.com/organicmaps/organicmaps/issues/87#issuecomment-1120183057

**Comment by biodranik** [comment]
Please do not open new issues, there are already #835 and #851

**Comment by cayenne17** [comment]
> Please do not open new issues, there are already #835 and #851

OK, I didn't find the problems because I'm looking with the Map Data label
