### ISSUE TITLE
Type of POI defaults to building

### ISSUE THREAD

**Issue by Mr-Mime** [organicmaps/organicmaps#3831]
Some POI's seem to be rendered / labeled wrong or misleading.
Nearby are some physiotherapist and psychotherapists which have no icon and thus are rendered only with the house number.
However this is a different issue (at least I think so), which I will create a separate issue, and a PR with new icons.

When opening the place page of one of the POI's it is labeled as "building".
While the opening hours, phone number etc. are displayed I do not see that it is a physiotherapist anywhere.

| Omaps | POI info |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/37423773/200186839-b11670dc-48b5-4b2f-b5ab-ae14c40e4fc6.png) | ![image](https://user-images.githubusercontent.com/37423773/200186874-382c6e2b-18d1-4d84-b105-7e52aa652fec.png) |

I propose that the healthcare value is shown, e.g. physiotherapist in the case above.
I have seen the described issue on android an iOS.

If you consider this as a `good first issue` I am happy to try my best to contribute :+1:

**Comment by biodranik** [comment]
It looks like you need:
1. Add a new type to classificator
2. Add type translations and modify categories.txt
3. Decide about the icon (reuse Doctor?)

**Comment by Mr-Mime** [comment]
Okay, thanks for the steps I need to look at.
I will look into it and hope to create a PR in the next few days.
