### ISSUE TITLE
Reykjavik appears twice in world map

### ISSUE THREAD

**Issue by neilguertin** [organicmaps/organicmaps#3834]
This is the world map only, I don't have Iceland downloaded and never have.

I looked around a bit and didn't find any other capitals with this issue.

This appears on Android and on Linux desktop.

![image](https://user-images.githubusercontent.com/8312387/200233038-1d1ed3a3-3c8d-4ce9-b3d3-c2577f0a4a12.png)

**Comment by tech189** [comment]
Similar to #3313

**Comment by neilguertin** [comment]
Closing as duplicate

**Comment by vng** [comment]
This case is more complicated as it seems, so reopen as separate issue.
