### ISSUE TITLE
Handle `building:part=no`

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#3836]
`building:part=no` shouldn't be interpreted as a building part as it currently is.
this tag is not something that should be tagged in the first place, but while it exists, we should handle it.

(this also applies to `building=no`, but I think that's handled)

**Comment by biodranik** [comment]
@vng is it hard to use our data/replaced_tags.txt to simply remove this tag?

**Comment by vng** [comment]
@endim8 It shouldn't. What made you think that building:part=no is present in the app?

**Comment by endim8** [comment]
Copying from the telegram chat:

> Umberto:
> Is there any reason why the inner courtyard is not displayed?
> ![index](https://user-images.githubusercontent.com/26939824/200381239-78157d2d-d604-4ab4-8c7c-c864b95288ab.png)

Looking at https://www.openstreetmap.org/way/166726426, it had the tag `building:part=no` so I assumed it was that.

Looking again now, it seems actually to be due to a `building=yes` tag on the main relation: https://www.openstreetmap.org/relation/10794761

**Comment by endim8** [comment]
I don't think this is something that can be handled by OM, and I've fixed the OSM data here: https://www.openstreetmap.org/changeset/128609084

so I'll close this 👍
