### ISSUE TITLE
(Foreign) category search seems to be broken: Unable to find categories & hits

### ISSUE THREAD

**Issue by bentolor** [organicmaps/organicmaps#3850]
Hi there,

thanks for your great work. I was reading the changelog for Nov 3 update of OSM, but stumbled over significant issues. In my memory this had worked in earlier versions.

I'm on Android, OM 2022.11.02-2-FDroid, Germany and German locale

# Cannot find category by word
_"Vending machine"_  translates to _"Verkaufsautomat"_ . Unfortunately, even if i literally type in this category name, i only find hits with this in their name but not the category. Honestly I'd already expect that after only typing "_verkauf_ " I'd already received a autocompletion suggestion for the category. 
![signal-2022-11-09-205806_002](https://user-images.githubusercontent.com/588260/200929204-94c6b2f2-b446-477d-8bc8-8da12630447b.png)

# Selecting category in search dialog does not work at all
If i click the search class icon, switch to the category tab and then select the category ", Einrichtungen für Wohnmobile" (infrastructure for RSV) i never receive any result regardless of zooming level or current visible map viewport.

I think this search has worked (somewhat) in earlier versions.

![signal-2022-11-09-205806_003](https://user-images.githubusercontent.com/588260/200929309-0fe6ba92-5ec9-4a24-a9da-e6d20c93ac4d.png)

Not sure: Is this an issue in the search logic or just the localization?

Thanks for working on the search functionally! This has been always one of the weak spots of OM. Really appreciate the efforts here!

**Comment by bentolor** [comment]
Hmmm… Looking at [`categories.txt`](https://github.com/bentolor/organicmaps/blob/master/data/categories.txt) I neither find a plain `vending machine` entry nor any entry containing `Einrichtungen für Wohnmobile`.

Maybe I misinterpret the GUI labels above for the category word search. But still the category search by selecting the entry should work, right?

**Comment by Jean-BaptisteC** [comment]
Search vending_machine

**Comment by bentolor** [comment]
@Jean-BaptisteC Similar to the single German word, searching for `vending_machine` does not seem to work for me as well ( en and de language setting )

I think i mixed up two different issues:

1. You cannot search on the category vending machine issus itself at all. I assumed that, because i used the regular search to identify category names and then tried to search for that.
2. Searching for category via the category list works in  (rv facilities) but not in German.

**Comment by biodranik** [comment]
1. There is no generic "vending machine" category in OM. You need to search specific types, like Zeitungsautomat. They are all listed in https://github.com/organicmaps/organicmaps/blob/master/data/categories.txt (search for vending_machine).

Why do you think looking for _any_ type of vending machine can be useful for users? It is easy to do by creating a common group for different types, like it is done for food.

2. DE translation is missing from categories.txt. I'll add it.

**Comment by bentolor** [comment]
Hi @biodranik: Sorry for my late reply. And thank you @j13m126 already making already most of my point.

@biodranik,you ask, why would I like to search for _"Verkaufsautomat"_. There are two aspects in this question.

## Why I as user, want to find vending machine of unknown types
During the (ongoing) pandemic I've become quite fond of vending machines. I enjoy to access new from small, local sellers. During travel I am always interested in learning on vending machines along my route.

Lately I saw someone on Twitter posting a picture on a "flower vending machine" ("Blumenautomat") in my city. I'd never came up with a search for that. So my use case is that I'd like to be able to discover that. 

### Is is easily feasible to make this usable in OM/OSM?
On your comment I tried to create search in [overpass search](https://overpass-turbo.eu/). I realized that this results in tons of `vending = parking_tickets`, `excrement_bags` or `cigarettes` results: All I'm obviously not interested. Filtering those out gave me the results I'm was actually interested in. Try it for yourself in your location. ;-)

```
[out:json][timeout:25];
(
  node["amenity"="vending_machine"]["vending"!~"cigarettes"]["vending"!~"tickets"]["vending"!~"excrement"]
  ({{bbox}});
);
out body;
>;
out skel qt;
```

So I understand that my use case might not fit OMs approach as my interests does not easily map a OSM simple tag or tag value.

Nota bene: Using _that_ search I was eventually able to spot the flower selling machine.



## Why OM suggests me to search for _"Verkaufsautomat"_
There is another reason why I'd expect to be able to search for "Verkaufsautomat". In the search results lists below the name line a description on the hit is given, like _Verkaufsautomat_, _Metzgerei_, … 

I understand that this is the category/classification of the search hit. **As a user, I really expect that I'd be able to search for any content listed in a search result itself**. 

I'm a little confused and honestly really don't understand there those values originate from. My former understanding was that these equal to categories also listed in `categories.txt`, hence also being searchable themselves.

**Comment by biodranik** [comment]
You can implement your desired behavior in OM if you want, it is easy :)

1. There is types_strings.txt file that contains translations of how object types are visible to users (in search results and when you select an object on the map).
2. There is categories.txt where you can list all search synonyms and use search groups like Verkaufsautomat that can find different types of objects.

There are comments in both files that explain it in more details. At the moment, you need to duplicate exactly the same name from types_strings.txt in the categories.txt for the search to work. We hope to refactor and improve it, please follow #2780 for that.
