### ISSUE TITLE
Blue halo is not draw after reopen OM

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3859]
How reproduce:

- Start OM
- Select POI -> blue halo is draw around POI and bottomsheet is show
- Leave OM
- Reopen OM -> POI is always selected, bottomsheet is show but blue halo is not draw

Pixel 6 - Android 13
v2022.11.02-2-Google

**Comment by biodranik** [comment]
Why did you close it?

**Comment by Jean-BaptisteC** [comment]
Because it's duplicate of #2024
