### ISSUE TITLE
Reduce visibility of street-side parking

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#3863]
Some people love to micromap. However, this can make the map too bloated sometimes. See this example of a neighborhood with all street-side parkings mapped (`amenity=parking` + `parking=street_side`). I think all the "P" symbols are a bit too much. I think we should maybe start drawing street-side parking at zoom 18 and maybe use the smaller "P" icon.

https://www.openstreetmap.org/way/1108977807#map=18/42.79162/-1.70039

https://wiki.openstreetmap.org/wiki/Tag:parking=street_side

| Z16 | Z17 |
|-|-|
| ![](https://user-images.githubusercontent.com/47610359/201440752-e7f048e3-8c29-45a8-910e-f9e8490b791b.png) | ![](https://user-images.githubusercontent.com/47610359/201440766-c15f2eb0-458c-4a69-bfe4-a0cba9d3ac6b.png) |

| Z18 | Z19 |
|-|-|
| ![](https://user-images.githubusercontent.com/47610359/201440904-1d52a92a-6280-4fb7-96ce-eac51a48734c.png) | ![](https://user-images.githubusercontent.com/47610359/201440914-799c84c2-6cd8-493c-a61c-9569eefc5415.png) |

**Comment by biodranik** [comment]
The current map style is generic and is used in different cases. IMO it is often very useful to quickly see if there is some parking. Hiding parking icons _everywhere_ because someone micromapped some places is also not a good idea.
Hiding parking icons can be useful on non-driver styles when we implement them.

**Comment by dvdmrtnz** [comment]
OSM Carto shows street-side parking with a small "P" icon from zoom 18.

Compare the big "P" of the regular parking with the smaller "P"s of the street-side parking.

![map](https://user-images.githubusercontent.com/47610359/201441958-5cfa33da-31c8-47b3-ac5e-5fda2cf99687.png)

**Comment by biodranik** [comment]
It sounds better than our current rendering. Are there special tags for that so we can distinguish the street-side parking?

Also, how parking on the street roadway is different (in terms of OSM) from parking not on the roadway and from parking on a separate parking place?

**Comment by dvdmrtnz** [comment]
Yes, we can distinguish street-side parking from the regular parkings.

Regular parkings are simply tagged with `amenity=parking` and some may have `parking=surface` or `parking=underground`.

Street-side parkings are tagged with `amenity=parking` and `parking=street_side`.

https://wiki.openstreetmap.org/wiki/Tag:parking=street_side

I suggest that we modify the rendering of `amenity=parking` + `parking=street_side` and don't modify the rendering of the rest of `amenity=parking`.

**Comment by biodranik** [comment]
That should be easy to do by introducing a separate type for it.

**Comment by mpawelski** [comment]
I agree that currently many `amenity=parking` + `parking=street_side` doesn't look good and makes the map a bit bloated. I also planned to create an issue for it.

But my ideas was to try removing this rounded square background from parking icon (and related POI icons too, like `amenity=parking_entrance` and `amenity=bicycle_parking`) and see if the that improves the map. I mean, have icons similar to OSM Carto, like just a "P" letter in blue color. It could make the parking icons less distracting, yet preserve the map details (like when we removed background from garden icons  in #3386, which IMO was an improvement).

Or is there a hard preference to have this blue rounded square background for parking-related icons?

And about OSM Carto. When they [made](https://github.com/gravitystorm/openstreetmap-carto/pull/4301) `amenity=parking` + `parking=street_side`  smaller, it was definitely an improvement, but:
- The reason it was such a bit improvement was that the OSM Carto had a _pretty big_ icon for parking, I think in OM parking icons are smaller.
- The `amenity=parking` + `parking=street_side` icon is smaller but icons for POIs like `amenity=parking_entrance` and `amenity=bicycle_parking` are the size of original parking icon, which IMO looks bad when they appear next to `amenity=parking` + `parking=street_side`. For example:
![image](https://user-images.githubusercontent.com/2056282/201912313-fdf08225-b64e-4d62-aec6-bd5eaa61ab24.png)

So I propose to try removing background from parking-related icons, make this icons blue, see how it looks. And maybe consider making normal (not `parking=street_side` ) parking icon a bit bigger if we decide that the visibility of this icon without background is not good enough.

**Comment by biodranik** [comment]
Removing background is a good idea. Then we can have a consistent blue square background only for public transport.
