### ISSUE TITLE
[desktop][linux] Geoclue support

### ISSUE THREAD

**Issue by fgaz** [organicmaps/organicmaps#3870]
From https://github.com/flathub/app.organicmaps.desktop/issues/19

Geoclue is a location framework commonly used on linux desktop

**Comment by stroobandt** [comment]
This problem may occur when a Qt `desktopID` different from the (flatpak) application name `app.organicmaps.desktop` was defined for communicating with `geoclue` over the D-bus. See also: https://doc.qt.io/qt-6/position-plugin-geoclue2.html

Any regular GNU/Linux flatpak user is left clueless —pun intended— of what that `desktopId` might be. A consistently defined ID is required for granting Organic Maps permission to use the `geoclue` service in `/etc/geoclue/geoclue.conf`

```
# Application configuration options
#
# NOTE: Having an entry here for an application with allowed=true means that
#       geoclue will not ask agent to authorize the application. This is to
#       ensure that applications with built-in authorization mechanism (e.g web
#       browsers) do not have to be bound to agents.
#
#       If your application is denied access to location information and your
#       operating system doesn't provide any mechanism to change that, it is
#       likely a bug in your operation system (or geoclue). The solution is to
#       report the issue with all details, rather than adding your application
#       to this list.
#
# Format:
#
# # Desktop ID of application without .desktop part

[app.organicmaps.desktop]
allowed=true
system=false
users=
```
To add to the confusion, the Linux desktop flatpak application in `/var/lib/flatpak/app/app.organicmaps.desktop/current/active/files/share/applications`
is called `app.organicmaps.desktop.desktop`, where the first `.desktop` refers to the desktop variant of the application and the second `.desktop` is the file name extension. Hence, what needs to go in `/etc/geoclue/geoclue.conf` has the appearance of not complying with the documentation comments, when in fact is does.

**Comment by stroobandt** [comment]
Much also depends on whether the particular GNU/Linux desktop environment (DE) in use is implementing a `geoclue`-agent. If it is not, Organic Maps should first launch the `geoclue` demo agent, prior to launching the main program. This is most probably something that must be added to the Linux desktop flatpak by default.

The `geoclue` project is astonishingly poorly documented. I just happen to learn this from this casual [`geoclue` issue comment](https://gitlab.freedesktop.org/geoclue/geoclue/-/issues/143#note_785369).

**Comment by fgaz** [comment]
Looks like this was done in #5823
