### ISSUE TITLE
Wrong poi type shown at train station

### ISSUE THREAD

**Issue by j13m126** [organicmaps/organicmaps#3873]
It should say 'train station' or 'building', but not 'full wheelchair access'. Tagging looks ok to me. See [here](https://osm.org/go/0JpzvEMo-?m=)
![Screenshot_20221113-162201.png](https://user-images.githubusercontent.com/7961926/201529565-362d4e7e-7889-4dee-ba0b-b7b2ffa91043.png)

2022.11.02-2-FDroid on Android 13

**Comment by Jean-BaptisteC** [comment]
@biodranik maybe we can create issue to collect all issues about wrong POI or wrong description (because the problem is same, OM use wrong key:value to determine which POI or description is showing)
