### ISSUE TITLE
Category searching for Parking shows private parking places

### ISSUE THREAD

**Issue by ddpasa** [organicmaps/organicmaps#3875]
I ran into this when driving today.  I needed to find a parking spot and tried searching using the parking category on the map.  This category also shows private parking places, which is confusing.  I recommend removing private parking places from the category search. (these are tagges with the access=private tag)

**Comment by biodranik** [comment]
Another option is to explicitly mark them as private. Sometimes you need a private one.

**Comment by ddpasa** [comment]
> Another option is to explicitly mark them as private. Sometimes you need a private one.

That works too.  The important thing is that it's clearly marked.  It's very frustrating to go to a parking lot only to find it restricted for provate use :)

**Comment by biodranik** [comment]
@vng there are at least two additional parking types we should care of: 1) private parking and 2) paid parking

Would it be better to create separate types for them? Or wait until the refactoring with tags will be done?

**Comment by dvdmrtnz** [comment]
Search results currently already show if parking is private or paid

<img src="https://user-images.githubusercontent.com/47610359/202922232-69b7f20c-076e-4975-9e51-6d724a8c86aa.png" width="375" />

Organic Maps 2022.11.01-25 
OSM data: 29 October 2022
iOS 16.1

**Comment by biodranik** [comment]
Wow, I forgot about it )

It could be useful to update icons. 

Also, if I select underground paid parking, only underground parking is visible on the screen (and in the search results).

**Comment by ddpasa** [comment]
> Search results currently already show if parking is private or paid
> 
> <img alt="" width="375" src="https://user-images.githubusercontent.com/47610359/202922232-69b7f20c-076e-4975-9e51-6d724a8c86aa.png">
> 
> Organic Maps 2022.11.01-25 OSM data: 29 October 2022 iOS 16.1

Not if you are in map mode :)

**Comment by Jean-BaptisteC** [comment]
@ddpasa please retry on the latest version, we have improved search and icons parking. Now private parking is less visible on map.

**Comment by ddpasa** [comment]
> @ddpasa please retry on the latest version, we have improved search and icons parking. Now private parking is less visible on map.

beautiful!  you guys are amazing.

which version number should I use?

**Comment by Jean-BaptisteC** [comment]
The latest available on App Store
