### ISSUE TITLE
[desktop][linux] "Import KML/KMZ" only finds lowercase .kml/.kmz files on Linux

### ISSUE THREAD

**Issue by stroobandt** [organicmaps/organicmaps#3878]
On GNU/Linux systems, when importing KML/KMZ bookmark files, only files with lowercase `.kml`/`.kmz` filename extensions are found.

In practice, these filename extension quite often are delivered in uppercase lettering. This is confusing and it took me some time to figure out what was wrong.

**Comment by biodranik** [comment]
How exactly are you importing files on Linux?

**Comment by biodranik** [comment]
@stroobandt It is still not clear to me how _exactly_ are you importing kml files. Are you renaming them and then copy manually into some specific folder? Or are you clicking on them and opening the app directly via some file manager?

**Comment by stroobandt** [comment]
@biodranik In the Organic Maps Linux desktop flatpak application, I click on the red star icon. This opens the "Bookmarks and tracks" window. There, I click on the "Import KML/KMZ" button, which opens a file selection dialog window. Pretty straightforward.

Mind you that "Import KML/KMZ" is also uppercase, whereas the Xubuntu file selection dialog only lets one select files with a lowercase '.kml/.kmz' file extension.
