### ISSUE TITLE
Add mini-map during navigation

### ISSUE THREAD

**Issue by gtrus21** [organicmaps/organicmaps#3879]
Прошу добавить отображение мини-карты во время навигации, как это реализовано в 2гис. На ней отображать маршрут в более высоком зуме. При нажатии переключаться между ней и обычной картой
![IMG_20221114_083908](https://user-images.githubusercontent.com/69676792/201584249-7f3e0384-09de-4891-b5d2-db77a41f37e9.jpg)

**Comment by Jean-BaptisteC** [comment]
I'm not sure we want add this feature, because on navigation we show only most important information. And show minimap can increase consumption app.

**Comment by biodranik** [comment]
Adding a button to view the whole remaining route is a good idea. Minimap? Likely not as good.
