### ISSUE TITLE
KML makes OM very slow

### ISSUE THREAD

**Issue by not-available-username** [organicmaps/organicmaps#3880]
If I add [this KML](https://hiking.waymarkedtrails.org/#route?id=1021025&type=relation&map=7.0/42.3432/12.1468) (quite big) the app is slow in every function and in map rendering. I'm not sure if this is a bug or a limitatiod due to the size/complexity of the KML.

I'm using the latest version of OM with an iPhone 12 with latest iOS, usually OM is very fast and smooth.

**Comment by not-available-username** [comment]
> One track from sentiera-italia? Looks like the drape renderer can be benchmarked and optimized.

Yes, from Sentiero Italia, an hiking route that goes through the whole peninsula. It’s an uncommon length but someone could need long tracks maybe.

**Comment by not-available-username** [comment]
> This track contains 456000 nodes (points) that are all rendered now. You can filter it out using some tools by removing close points and reducing their amount, or we can try to patch our rendering and dynamically filter some unnecessary points for better speed.

I think it should be done by the app, not by the user. But maybe is not needed since KML like this one are not common, I just wanted to report this issue to make the developers aware of that. 

I think fixing random straight lines is more important (like https://t.me/organicmaps/20752) it happened also with this KML.

**Comment by biodranik** [comment]
How to reproduce straight lines? Between which points you saw them? Do they reproduce every time? It would be better to create a separate issue for it.

**Comment by biodranik** [comment]
@not-available-username the fix was just merged. Please let us know if the next release fixes this issue for you.

**Comment by not-available-username** [comment]
> @not-available-username the fix was just merged. Please let us know if the next release fixes this issue for you.

It’s fixed in ⁦2022.11.24-1⁩ or in the next one?

**Comment by biodranik** [comment]
The fix was merged 4 hours ago. In the next one.

**Comment by not-available-username** [comment]
> The fix was merged 4 hours ago. In the next one.

Thank, I will check in the next release

**Comment by matkoniecz** [comment]
@not-available-username Ping?

**Comment by not-available-username** [comment]
> @not-available-username Ping?

It works as expected, without any lag and the track is properly rendered, thanks!
