### ISSUE TITLE
Invalid cycling route

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3881]
OM shows a longer route.
The correct route is this one: https://www.openstreetmap.org/way/384883003#map=19/54.26785/18.67673&layers=D

Is it because of the surface=paving_stones? https://www.openstreetmap.org/way/384883003#map=19/54.26785/18.67673&layers=D

**Comment by vng** [comment]
(54.2632738, 18.6771661) -> (54.2698882, 18.6765837)
highway=residential has significantly less speed than designated cycleway
