### ISSUE TITLE
[android] Investigate how to split API21-22 into a separate bundle

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#3886]
Needed for #3806

**Comment by AndrewShkrob** [comment]
I see another approach. But I'm not sure if there is at least one company/product that uses it as it has significant cons.

Use Dynamic Feature Delivery for Google Play. Everything is good - one bundle, old API support, AA for API 23+ devices, AAOS support
For App Galery and Fdroid:
1. increase the minimum API level for AA support
2. create another application for old API 21-22, call it "Organic Maps Legacy"

**Comment by biodranik** [comment]
There are Huawei, Samsung, Amazon, and other marketplaces too )

**Comment by rtsisyk** [comment]
> Use Dynamic Feature Delivery for Google Play. Everything is good - single bundle

We already use AAB bundles.

Google told me that two separate bundle for different APIs are not supported. It looks like that we will have to drop API21-22.

**Comment by AndrewShkrob** [comment]
>It looks like that we will have to drop API21-22.

No. We don't have to. At least for google play. Check this: https://developer.android.com/training/cars/apps/automotive-os
AAOS code is in a separate module. I think the same can be done for AA. We'll have three modules:
* Base app
* AA for API 23+
* AAOS

And it should be possible to configure it in the way to download AA module if a user has an API 23+ device. Check the `Conditional delivery` section here: https://developer.android.com/guide/playcore/feature-delivery

**Comment by biodranik** [comment]
Considering AAOS approach, is it feasible to easily support:
1. API 21-22 APK (or API 21-31+ APK)
2. AA APK (API 23+)
3. AAOS APK (API 29+)
so we can build all these APKs and distribute all of them either in separate apps in stores, or publish them on Github/our website, and distribute only (2) in stores?

What are the pros and cons of this approach?

**Comment by AndrewShkrob** [comment]
Regarding AAOS:
I'm not sure if there is a sense in publishing this version for other stores. AAOS seems to be a "closed" platform. I guess there is no possibility to install 3rd party apks.
So, it should be distributed only for Google Play.
And it can be distributed for Google Play only after refactoring of `android` folder to enable modules support

Regarding AA and other stores:
* We also can separate AA into a module like for AAOS for Google Play.
* We will have to distribute 2 separate apps for other stores. The disadvantages are:
  * New page in stores for a legacy version without rating and reviews
  * We'll have to notify users with old API devices that they must download a new app if they wish to get updates

The easiest way is to drop old API support. We won't have any problems until the AAOS support which requires refactoring as described above.

**Comment by rtsisyk** [comment]
Conclusion here is to bump API level to 23 as soon as Android Auto is ready.
