### ISSUE TITLE
Render `entrance=service` or `entrance=*` + `access=no/private` differently

### ISSUE THREAD

**Issue by deevroman** [organicmaps/organicmaps#3890]
Now they are displayed the same way and make it difficult to find the main entrances to the building

**Comment by endim8** [comment]
this is a good point. 
`entrance=main` is used for main entrances,
`entrance=yes` is used for unknown & for secondary entrances,
`entrance=service`  should be lowest priority, as it's only for employees etc

access would be solved by showing access in the place page
