### ISSUE TITLE
OM is showing a blue circle instead of an arrow

### ISSUE THREAD

**Issue by d4f5409d** [organicmaps/organicmaps#3894]
OS: OxygenOS
Android 13
OM version: 2022.11.02-2-FDroid
![Screenshot_2022-11-15-21-46-05-39_75d0290a7c00525acd83c0ab8700d64c.jpg](https://user-images.githubusercontent.com/76624594/202022379-e74b3f2e-a3d9-48b9-a227-a90586c9c559.jpg)

**Comment by biodranik** [comment]
It means that there is an issue with your device's compass or gyroscope sensors. Does your device have them? Does direction work in other apps?
