### ISSUE TITLE
Weird track (KML)

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3895]
How reproduce:
- Download this track https://hiking.waymarkedtrails.org/#route?id=3159559&type=relation&map=10.0/47.758/7.0831 (format KML)
- Or this track https://hiking.waymarkedtrails.org/#route?id=2029679&type=relation
- Import on OM -> track is weird on end route
- Use near here https://www.openstreetmap.org/relation/5524891
<img src="https://user-images.githubusercontent.com/87148630/202022562-10a64919-ee8a-4580-a295-229349f5442d.png" height="300"/>

Pixel 6 - Android 13
Version 2022.11.02-2-Google

**Comment by biodranik** [comment]
Thanks! Reproduced it everywhere.
[gr-5f.kml.zip](https://github.com/organicmaps/organicmaps/files/10016505/gr-5f.kml.zip)

**Comment by daimajiin** [comment]
[06.12.2019.kml.zip](https://github.com/organicmaps/organicmaps/files/10095317/06.12.2019.kml.zip)
another file to reproduce

**Comment by Jean-BaptisteC** [comment]
Maybe problem appears if elements in relations have don't correct order ?

**Comment by Jean-BaptisteC** [comment]
Tips: after this correction to see a correct track, we need to remove track and re-import in OM to see the right track

**Comment by vng** [comment]
Of course, because the previously imported track is buggy.
