### ISSUE TITLE
Missing in the search for "cell towers" icons are not displayed on the map

### ISSUE THREAD

**Issue by snooppr** [organicmaps/organicmaps#3898]
tag: man_made:: tower, type:communication

**Comment by biodranik** [comment]
Can you please clarify what is it about?

1. Why do you think that cell towers should be searchable? Do users really need that?
2. Why any icons are needed for cell towers? They will greatly pollute the map.

**Comment by snooppr** [comment]
1.Yes, cell towers need users (this is obvious, ), for example, when a user is without a network, he can search for the nearest tower by distance.
2.There is no information about cell towers/icons on the map at all.  Does an icon, for example, a playground, not pollute the map, but a tower pollutes?!
3. I remember that in mapsme it was very poor with icons, and in OM they began to massively add a picnic table, a picnic area, etc.  Have you polluted the map?

**Comment by snooppr** [comment]
![скрин](https://user-images.githubusercontent.com/61022210/202121828-2737ec73-e35b-4f26-ba66-58863ca2cbc7.png)

**Comment by snooppr** [comment]
@biodranik What do you think?

**Comment by biodranik** [comment]
Cell towers ([man_made=mast](https://overpass-turbo.eu/s/1nWF)) are drawn now from zoom level 16 as a dot. They are not indexed for the search yet. It is not an obvious use case.

**Comment by snooppr** [comment]
> Cell towers ([man_made=mast](https://overpass-turbo.eu/s/1nWF)) are drawn now from zoom level 16 as a dot. They are not indexed for the search yet. It is not an obvious use case.

https://github.com/organicmaps/organicmaps/pull/4520

Если добавляете вышки, обратите внимание и на тэг "antenna" это тоже вышки сот.связи, вот пример со смежной проблемой в OsmAnd
https://github.com/osmandapp/OsmAnd/issues/16442

**Comment by biodranik** [comment]
@vng can we try to replace [man_made=antenna](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dantenna) with tower:type=communication ?
