### ISSUE TITLE
toilet=yes sometimes overrides amenity's actual icon

### ISSUE THREAD

**Issue by jpds** [organicmaps/organicmaps#3915]
I've noticed that with some amenities, if that amenity has `toilet=yes` - the toilet icon is used instead of the actual icon for the amenity.

For example: https://www.openstreetmap.org/way/344501804 is shown in OM as:

![signal-2022-11-18-151712_002](https://user-images.githubusercontent.com/29158971/202738880-424f47bc-23d3-431e-b055-58888f09f07e.jpeg)

**Comment by biodranik** [comment]
@vng was it fixed by #3910 ?

**Comment by Jean-BaptisteC** [comment]
Similar of https://github.com/organicmaps/organicmaps/issues/3744

**Comment by vng** [comment]
events_venue doesn't have an icon

**Comment by dvdmrtnz** [comment]
https://github.com/organicmaps/organicmaps/issues/563

**Comment by map-per** [comment]
The same thing happens with this disused Burger King (https://www.openstreetmap.org/node/266579979). Because of the `toilets=yes` it's displayed like a toilet although it doesn't exist any more.

(2023.03.05-5-Google, Map data 2023.02.27)
