### ISSUE TITLE
cycle barriers with bicycle=yes

### ISSUE THREAD

**Issue by 501Ghost** [organicmaps/organicmaps#3920]
I created a cycling route from the [Langhoven](https://www.openstreetmap.org/way/6919626) street to the [Krulweg](https://www.openstreetmap.org/way/6920271) in Bennekom, the Netherlands. I noticed that I was routed the long way over the [Commandeursweg](https://www.openstreetmap.org/way/6920825) instead of cycleway [Hogeweg](https://www.openstreetmap.org/way/413996601). This is most likely because of [this cycle barrier](https://www.openstreetmap.org/node/4494637799) and maybe also [this bollard](https://www.openstreetmap.org/node/44795427). Both have a `bicycle=yes` tag, so I think the penalty for routing past them may be too much.

Relevant image: https://cdn.discordapp.com/attachments/428214296695144458/1043089814238543892/Screenshot_20221118-100321.jpg

**Comment by vng** [comment]
Adding some intermediate point within Hogeweg gives needed route.
Hogeweg is a regular residential road, but Commandeursweg is manually tagged as bicycle=yes, so the app chooses to make additional 100m detour. I think we should _increase_ default priority for residential roads a bit ..

Also see https://github.com/organicmaps/organicmaps/issues/3881

**Comment by vng** [comment]
Also, we don't draw barrier=cycle_barrier

**Comment by 501Ghost** [comment]
> Adding some intermediate point within Hogeweg gives needed route.

That's true, but I was wondering why the shorter route wasn't preferred.

> we don't draw barrier=cycle_barrier

Is that by choice or has it just not been done yet?

> Commandeursweg is manually tagged as bicycle=yes, so the app chooses to make additional 100m detour

I hadn't looked at this this way, but you are more familiar with this of course. It's true that there is asphalt and a `cycleway=lane` at the Commandeursweg, but it's still a tertiary road and a longer way from A to B. 

> I think we should increase default priority for residential roads a bit

Perhaps, or one could argue that the Commandeursweg with no cycle barrier at all + asphalt surface + `cycleway=lane` should be the preferred route in this case. That's a design choice that I shall leave up to you.

**Comment by vng** [comment]
Now we treat barrie=cycle_barrier as Access:No for bicycles, which is wrong in general. According to the wiki, it is also used to calm down bicycle traffic, but not forbid it. In general, we can't distinguish which barrier forbids and which calms the traffic (if there are no other tags). So my proposal is to ignore cycle_barrier on cycleways.

The example: https://overpass-turbo.eu/s/1Cxo A lot of barriers with different purpose.
Expected route: https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.38224%2C-2.38862%3B51.35866%2C-2.31299#map=14/51.3535/-2.3210

**Comment by biodranik** [comment]
@vng `bicycle=no` should be forbidden for bicycles, right?

**Comment by vng** [comment]
> @vng `bicycle=no` should be forbidden for bicycles, right?

Right
