### ISSUE TITLE
Draw barrier=cycle_barrier

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3922]
Also, we don't draw barrier=cycle_barrier

_Originally posted by @vng in https://github.com/organicmaps/organicmaps/issues/3920#issuecomment-1320929185_

**Comment by dvdmrtnz** [comment]
Icon could be two horizontal lines similar to the OSM Carto style.

![](https://wiki.openstreetmap.org/w/images/0/09/Cycle_barrier-14.svg)

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcycle_barrier
