### ISSUE TITLE
Highlight secondary roads

### ISSUE THREAD

**Issue by FinixFighter** [organicmaps/organicmaps#3923]
Highlighting secondary roads on Organics Maps could be useful, for instance they could be colored with a very light yellow, similarly to OSM. Secondary roads are the most common roads in a city, and they're useful for more understanding the "architecture" of the city and for quickly locate out position (not only on the screen, but in out mind too). Briefly, it would make the map easier to understand. I attach two photos of Palermo (Italy), one from Organic Maps and one from OSM, as an example.
![photo_2022-11-19_18-09-33](https://user-images.githubusercontent.com/19877271/202865785-c632a610-714d-47a9-ac6c-810b4671982e.jpg)
![Screenshot from 2022-11-19 18-06-41](https://user-images.githubusercontent.com/19877271/202865787-0973a678-48e5-4915-a166-31cd283933d1.png)

**Comment by Jean-BaptisteC** [comment]
Fixed by #7117
