### ISSUE TITLE
Routing attempts to circumvent no right turn by performing three left turns on divided intersections

### ISSUE THREAD

**Issue by potomatosm** [organicmaps/organicmaps#3925]
In the image below, taking a right turn is forbidden. The routing instead performs three left turns within the intersection, allowing it to drive straight through, circumventing the right turn forbidden instruction. Needless to say, routing softwares should not be encouraging this type of stunt that would generally not be considered safe.

![](https://user-images.githubusercontent.com/118641128/202877081-e02dcf83-a319-4396-bdf2-7ada0ae6ea48.png)

The intersection in question (On 2022/11/10) - JOSM, Bing Aerial Imagery

![](https://user-images.githubusercontent.com/118641128/202877408-fc75965b-48e6-4105-bff0-190bb17da22a.png)

This was detected at the intersection at 43.5463, -79.6832. When I was new to OSM editing, I accidentally removed a dedicated right turn lane without removing the no_right_turn on the main road. (This has since been fixed, so if OrganicMaps' map database updates past the current October 29 database it will no longer occur *at this particular intersection*. However, this is still a genuine issue that may prop up elsewhere when right turns are forbidden on divided intersections.)

Hardware data: Pixel 6, Android 13 running CalyxOS 4.3.0
Software data: Organic Maps from F-Droid, v2022.11.02-2-FDROID

1. What is the issue?

On a divided intersection with a no_right_turn applied, the routing software will direct the driver to commit three left turns in the middle of the intersection to circumvent the no_right_turn

2. What should occur?

The routing software should not be doing this, and should find an alternate route.

**Comment by biodranik** [comment]
Isn't this wrong OM routing instruction a consequence of missing turn restrictions in OSM data? What if in reality these left turns are allowed? How can we guess it without tagging?

**Comment by potomatosm** [comment]
> Isn't this wrong OM routing instruction a consequence of missing turn restrictions in OSM data?

Maybe. This only occurs if right turns are disallowed but left turns are allowed, which I wouldn't wager to be very common. Unfortunately, due to how specific it is and my inexperience with OSM, I'm not sure how I could go about querying OSM if an intersection like this does indeed exist. Theoretically speaking though, there's nothing preventing a hypothetical intersection in real life where this does occur, and it would be correct turn restrictions as far as I know. Please correct me if I am wrong.

If a bug report based off a hypothetical intersection, without a concrete example, is not allowed, feel free to close this issue and I apologize for the inconvenience.

> What if in reality these left turns are allowed?

Are you asking what if the current router's directions are allowed? I am not aware of a place where performing this in a intersection would not be considered reckless driving.

> How can we guess it without tagging?

Is this a "we cannot prevent the router from doing this without further tagging" or "this was tagged wrong, the lack of tagging caused the router to do this"? If the latter, how would one tag to prevent the router from doing this?

**Comment by biodranik** [comment]
The main question: should it be fixed in OM at all? If it is OSM data error issue, then we likely should not fix our algorithm to "workaround" wrong or missing data, because it can lead to false positives and false negatives.

**Comment by potomatosm** [comment]
I have done some more digging revolving intersection turns. There is another instance of it occurring at 43.7323138, -79.2681022.

However, observing other intersections, it seems the easiest way to fix this is to create an implied=yes u-turn restriction on the intersection to prevent the router from doing this.

This will prevent the router from allowing a u-turn at the intersection, but I guess that's better than the router doing this.

Apologies for the inconvenience. I will close this issue.
