### ISSUE TITLE
Cycling route avoids cycleway:right=lane and cycleway=opposite_track

### ISSUE THREAD

**Issue by starsep** [organicmaps/organicmaps#3928]
Cycling route avoids cycleway:right=lane
Example route https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=52.22974%2C20.98327%3B52.23686%2C21.01753
(52.22974, 20.98327) -> (52.23686, 21.01753)
OSRM/GraphHopper also find slower route with 2 additional traffic lights.

I see no logic for cycleway=lane in https://github.com/organicmaps/organicmaps/blob/master/routing_common/bicycle_model.cpp

**Comment by vng** [comment]
Did you try to build route on latest data?
https://github.com/organicmaps/organicmaps/blob/master/generator/osm2type.cpp#L753

<img width="1166" alt="Screenshot 2022-11-20 at 19 34 17" src="https://user-images.githubusercontent.com/175612/202914000-36a548e3-16b6-44da-a054-6aee6322401a.png">

**Comment by starsep** [comment]
Yes, sorry for not posting the screenshot. This one is slower one. It crosses from south side to north and back. I expected to stick to the south side all the time and use cycleway lane instead of dedicated cycleway

**Comment by vng** [comment]
Dedicated highway=cycleway has better priority than cycleway=* (or bicycle=yes).
We will add crossing/traffic_lights penalty someday.

BTW, Graphhoper with your link makes the same route.

**Comment by Altonss** [comment]
> Cycling route avoids cycleway:right=lane

I noticed cycling route also avoids `cycleway:left = opposite_track`

**Comment by vng** [comment]
@Altonss Do you have any example? cycleway:left=* should always work (except "no").

**Comment by Altonss** [comment]
> @Altonss Do you have any example? cycleway:left=* should always work (except no, use_sidepath, separate).

There is this example: https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=48.76634%2C6.12736%3B48.76511%2C6.12480 which works on osm.org bike routing with OSMR, GraphHopper and Valhalla, but doesn't work in OM

**Comment by pastk** [comment]
> Dedicated highway=cycleway has better priority than cycleway=* (or bicycle=yes). We will add crossing/traffic_lights penalty someday.
> 
> BTW, Graphhoper with your link makes the same route.

Interestingly, OM prefers the south side now, while OSM routers switch to north cycleway still.

![image](https://github.com/user-attachments/assets/e86da3dd-77f1-4635-a2a3-f8d909c7d296)

**Comment by pastk** [comment]
> I noticed cycling route also avoids `cycleway:left = opposite_track`
> 
> Edit: on osm.org only OSMR bike routing gets it right and following the wiki https://wiki.openstreetmap.org/wiki/Key:cycleway#Cycle_tracks this doesn't seem to be a recommended tagging scheme (but it would be great if OM could handle it better nonetheless).

> There is this example: https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=48.76634%2C6.12736%3B48.76511%2C6.12480 which works on osm.org bike routing with OSMR, GraphHopper and Valhalla, but doesn't work in OM

Doesn't work in OM as OM thinks its one-way only street.

![image](https://github.com/user-attachments/assets/bbc71c4a-a8c0-46d1-bd2b-e1d8e19b3209)

But given this tag is deprecated and only ~700 usages left (https://wiki.openstreetmap.org/wiki/Tag:cycleway%3Dopposite_track) it doesn't make sense to support it.

Could you please update the mapping with recommended schema and then we'll see if it works?

**Comment by pastk** [comment]
Closing it as its a tagging issue.
