### ISSUE TITLE
[Android][2021.05.08]: first start fails 'cause of the absence of geolocation services

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#393]
**OS**: Android 10.0 (LineageOS 17.1).

Very minor bug. Just installed the new version ``2021.05.08`` (along with already installed ``2021.04.24``): app didn't requested access to location → Showed the error that geolocation services are disabled but required to run the app → And just closed. Unfortunately I haven't made a screenshot of the error.

Rerunning the app was OK - location permission was requested and app started normally.

Clearing app's storage and even reinstalling it haven't reproduced the situation

**Comment by rtsisyk** [comment]
>Unfortunately I haven't made a screenshot of the error.

Do you mean this screen?

![Screenshot_20210509-103854_Organic Maps (2)](https://user-images.githubusercontent.com/1799054/117564116-10a7d080-b0b3-11eb-8f55-619099837b1a.jpg)

Currently the app check access to location services on the start. The app display the error message above doesn't continue until location permission is granted. 

I guess that you just accidentally pressed "Deny" on the first start, didn't you?

**Comment by PetbkA** [comment]
> Do you mean this screen?

Yep.

> I guess that you just accidentally pressed "Deny" on the first start, didn't you?

I doubt that, but of course there's some chance of it :)

Anyway, theoretically app should work without location access - you can just browse map and editing objects without GPS to save battery, for example

**Comment by rtsisyk** [comment]
I agree with you that it should. Additional changes are required to make it
happen.

**Comment by rtsisyk** [comment]
This problem has been fixed already.
