### ISSUE TITLE
Unable to open openstreetmap.org link on osm login fragment

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3950]
How reproduce:

- Start OM --> settings --> Profile OSM (Need app without OSM connection)
- Click on [openstreetmap.org](openstreetmap.org)
- OM restart

To reproduce openstreetmap.org has been enabled on Android app settings (open by default)

I think OM try to open link because he has detected like openable link but he has not GPS coordinates to load position on map
Maybe be more restrictive on openable link, to allow users to open openstreemap.org on browser without start OM

https://github.com/organicmaps/organicmaps/blob/78f09b392d5a12c9033934d8044ee88d52bd5854/android/AndroidManifest.xml#L554

Android 13 - Pixel 6
v2022.11.02-2-Google

**Comment by biodranik** [comment]
You're right, OM should intercept only links with coordinates, like `https://www.openstreetmap.org/#map=15/45.8610/18.4110`, and should not intercept general links, including wiki.

But it also should not crash.

@rtsisyk can you please fix it?

**Comment by biodranik** [comment]
Let's leave it as is for Android 5-11, but fix the crash.

**Comment by Jean-BaptisteC** [comment]
I have doing some test, we don't have crash, i guess OM restart activity to open link
Here is log when i click on OSM link in login fragment

```
01-08 18:48:41.527  1461  1523 I ActivityManager: Start proc 31387:com.android.chrome:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:9/u0ai9 for  {com.android.chrome/org.chromium.content.app.SandboxedProcessService0:9}
01-08 18:48:41.527 31387 31387 E libc    : SetHeapTaggingLevel: re-enabling tagging after it was disabled is not supported
01-08 18:48:41.533 31387 31387 E ocessService0:9: Not starting debugger since process cannot load the jdwp agent.
01-08 18:48:41.592  1461  1889 I ActivityManager: Killing 31387:com.android.chrome:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:9/u0a176i-8991 (adj 0): isolated not needed
01-08 18:48:41.711 30156 30156 E cr_CompositorSurfaceMgr: surfaceDestroyed format : 4
```

**Comment by Jean-BaptisteC** [comment]
I have find a solution to open link in browser, if we replace openstreetmap.org by osm.org, link is open in browser.
Just replace constants links with openstreetmap.org by osm.org
