### ISSUE TITLE
OSM attribution only shown for a very short time

### ISSUE THREAD

**Issue by 13hannes11** [organicmaps/organicmaps#396]
HI noticed that the attribution to OSM is only shown for a very short time. I think it would be good to show it for longer or better even permanently.

**Comment by matkoniecz** [comment]
Why showing attribution is consuming extra battery?

BTW, I really appreciate much better approach to attribution that maps.me!

**Comment by biodranik** [comment]
Because the graphics engine needs to constantly merge/blend the attribution text with the map background. For each frame. Many times per second.
