### ISSUE TITLE
Bug: if you press on the hamburger icon when using organic maps on the lock screen it flickers constantly (see video below).

### ISSUE THREAD

**Issue by Growebis** [organicmaps/organicmaps#3967]
Steps to Reproduce:

1. Open Organic Maps.

1.5 Make sure to have "Show on the lock screen" enabled in settings

2. Close your phone's screen

3. Open your phone screen and try clicking on the hamburger icon (or three line icon, whatever you wanna call it)

4. Watch it flicker.

How to get it out of flickering: just simply restart.

Phone: Sony Xperia L1
OS: Android 7
2022.11.02-2-FDroid

https://user-images.githubusercontent.com/113867283/204059868-7c023e6a-416d-46a7-a164-47fa20c526a8.mp4

**Comment by biodranik** [comment]
It looks like Android 7 bug, see similar #2857

**Comment by biodranik** [comment]
@arnaudvergnet @rtsisyk does it make sense to disable "show on lock screen" option for Android 7 devices?

**Comment by Growebis** [comment]
should i mark it as closed since its a duplicate?

**Comment by biodranik** [comment]
This issue has a video, we can keep both.

**Comment by arnaudvergnet** [comment]
On some phones you need to restart the phone when triggering the bug, so if we don't find a way to fix this, I'd say locking the feature for Android 7 and older makes sense. We can keep the issues and when someone finds a way to fix it, we can enable it back.

**Comment by jech** [comment]
I can confirm that the issue occurs on an Android 6 device.

> does it make sense to disable "show on lock screen" option for Android 7 devices?

I think that's necessary.  I encountered the issue immediately upon using *Organic Maps* the first time in real conditions, and it forced me to go back to OSMAnd.

**Comment by biodranik** [comment]
@jech what is your device model? It could be some specific graphics chip...

**Comment by jech** [comment]
> @jech what is your device model?

Wiko Sunny.

> It could be some specific graphics chip...

It's a Mali-400 MP, what could possibly be more boring than that?  Also, the symptoms are consistent with the ones in Growebis' video, the display quickly alternates between the lock screen and the map until I reboot.

**Comment by biodranik** [comment]
Mali-T720MP2
Mali-400MP2
Adreno 530

Ok, it would be safer to make this "Use on lock screen" setting off by default on Android 7 and lower. Can anyone help and also test it?

**Comment by Growebis** [comment]
> Ok, it would be safer to make this "Use on lock screen" setting off by default on Android 7 and lower. Can anyone help and also test it?

i can try testing it on two devices i got running android 7.
