### ISSUE TITLE
Update color for emergency=phone icon

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3969]
Actually color for POI emergency=phone is grey, but other emergency equipments is in red. -->Replace grey by red

**Comment by biodranik** [comment]
Screenshots would be helpful.

**Comment by Jean-BaptisteC** [comment]
<img src="https://user-images.githubusercontent.com/87148630/204091142-98c7324d-875d-473e-ac52-bb7bbb5c9596.png" height="600"/>

https://www.openstreetmap.org/#map=18/49.19676/6.16257
