### ISSUE TITLE
OM wants to avoid ferries, even when avoiding ferries option is unticked

### ISSUE THREAD

**Issue by d4f5409d** [organicmaps/organicmaps#3971]
Current state:
OM wants to avoid ferries on the road, even when no driving options are set, and with the ferry, you could get to your destination faster.

Expectation: 
OM should calcute the ferries in, when needed. Only not, if avoiding ferries is ticked on.

(The avoiding ferries option is unticked in driving options. Only avoid highways are ticked in)
![Screenshot_2022-11-26-12-31-58-88_10a7d9276315e62e56e7300dfec6be06.jpg](https://user-images.githubusercontent.com/76624594/204086675-ac9ae241-759b-456d-8deb-9161168129da.jpg)

I had to add a intermediate destinatio to force OM to navigate trough the ferry, which is faster.
![IMG_20221126_123503.jpg](https://user-images.githubusercontent.com/76624594/204086695-4a95ca03-63e2-44ee-9852-f051cf71a1bb.jpg)

**Comment by biodranik** [comment]
What are the tags in OSM there?

**Comment by d4f5409d** [comment]
https://www.openstreetmap.org/node/834686623

```addr:city=Szántód
amenity=ferry_terminal
ele=100
ferry=yes
name=Szántódrév
operator=Balatoni Hajózási Zrt.
operator:addr=8600 Siófok, Krúdy sétány 2.
public_transport=stop_position
ref:vatin=HU11238326
ref:vatin:hu=11238326-2-14
wheelchair=yes
```

**Comment by vng** [comment]
We have _precalculated_ 40 mins ferry landing penalty in the app. Together with 15 min ferry's duration it gives a bit worse time then 70 km detour. Well, I can't say for sure what we can make better here.

BTW what is the ferry's **period** (timetable) here?

**Comment by d4f5409d** [comment]
You'll see what I'm talking about. https://bahart.hu/en/szantod-tihany-ferry-transportation

**Comment by d4f5409d** [comment]
Hit me up if you fixed it, because the error still occurs.

**Comment by biodranik** [comment]
@vng reducing ferry onboarding to 30 min may help.
