### ISSUE TITLE
Allow to choose between fastest and shortest route calculation

### ISSUE THREAD

**Issue by d4f5409d** [organicmaps/organicmaps#3974]
Current state:

Organic Maps currently only allows to calcute routes based on which is the shortest. However, this may be problematic, when we see an example of bypass roads (that are bypassing the city to make traffic flow faster, and more fluent) In the cities the speed limits are also slow and you often can get to your destination with bypass roads faster.

Expectation:
In the driving options we could have a toggle between fastest and shortest route calculation modes.

This is a reference issue to another #3975

**Comment by biodranik** [comment]
As we discussed, this issue will be solved by implementing alternate (alternative) routes for all routing modes. And there will be no need to complicate the app with additional settings.
https://github.com/organicmaps/organicmaps/issues/1183

**Comment by niuo345533** [comment]
I have same problem ,  should allow multiple routes for a location
