### ISSUE TITLE
Display alternative routes

### ISSUE THREAD

**Issue by d4f5409d** [organicmaps/organicmaps#3975]
Current state:
Organic Maps currently only displays one route per calculation. We can't choose between, which is better for us

Expection:
OM should offer alternative routes based on the main route, and users could select which route they go on to, like here:
![Screenshot_2022-11-26-18-21-18-94_b71d18658519e274790a1f109e40d1e1.jpg](https://user-images.githubusercontent.com/76624594/204101174-a2a7298e-b81f-4ddc-b1ae-7d457cd2191d.jpg)
![Screenshot_2022-11-26-18-21-30-29_b71d18658519e274790a1f109e40d1e1.jpg](https://user-images.githubusercontent.com/76624594/204101193-fcac6a94-488a-4b38-adeb-f97e8494d8d6.jpg)
![Screenshot_2022-11-26-18-21-39-16_b71d18658519e274790a1f109e40d1e1.jpg](https://user-images.githubusercontent.com/76624594/204101196-7ef48946-0566-4929-9445-eec2e5a693e5.jpg)

[This feature has been discussed by ne and Alexander Borsuk, this is why I made this GitHub issue.]

**Comment by Jean-BaptisteC** [comment]
https://github.com/organicmaps/organicmaps/pull/3447
