### ISSUE TITLE
Busway is displaying type.highway.busway

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#3996]
Since #3739 (busways are shown on map), there is no title for each busway (displaying type.highway.busway per image).

If pointed out where I can edit this, I can glad fix this.

![IMG_6745B221FFC6-1](https://user-images.githubusercontent.com/86851490/204608159-0e2d632f-a4ae-441b-98ec-eb50e9ce1544.jpeg)

**Comment by matheusgomesms** [comment]
Shall this be added at data/strings/types_strings.txt, with all translations?

**Comment by Jean-BaptisteC** [comment]
Yes, you can find more informations here -> [TRANSLATIONS.md](https://github.com/organicmaps/organicmaps/blob/master/docs/TRANSLATIONS.md)
