### ISSUE TITLE
Long back pulse exits from app

### ISSUE THREAD

**Issue by racuna** [organicmaps/organicmaps#4004]
Hi, I don't think this is an urgent issue. 

My phone has the power/lock button damaged. Luckily, MIUI have the option to lock the screen with a long "back pulse". 

The problem is, when I do this and Organic Maps is opened (i.e. giving me a route to a destiny), when I unlock again the phone to watch my route, the app is not there anymore, and I have to open it again.

Probably is a MIUI issue, but I don't have the same issue with other apps. Didn't happened with Osmand~ but I switched to Organic because it is more simple to use.

Regards, and congrats for this app. I'm loving it.

**Comment by biodranik** [comment]
Do you have "Show on Lock screen" option enabled in OM settings?

**Comment by racuna** [comment]
Yes. Everything is mostly by default (I just installed it this weekend)

**Comment by biodranik** [comment]
Can the issue be closed? :)

**Comment by racuna** [comment]
yes, thanks.
