### ISSUE TITLE
Dark mode icons color

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#4014]
I think the dark mode icons are too white, they look too bright. I think the Maps.me icons in dark mode look better. Did Organic Maps change the color after the fork of Maps.me? Or did they change it?

| Organic Maps | Maps.me |
|-|-|
| ![](https://user-images.githubusercontent.com/47610359/205447057-ef5bb5c1-543f-4c58-ab6d-1eddf39d2eb1.jpeg) | ![](https://user-images.githubusercontent.com/47610359/205447062-27521e7e-da31-4589-b702-408756a177ba.jpeg) |

**Comment by biodranik** [comment]
Good point, but it may be worth fixing it later when we implement dynamic SVG icons with dynamic backgrounds and colors.

**Comment by dvdmrtnz** [comment]
Here is how the icons on other apps look in dark mode:

| Google Maps | Apple Maps |
|-|-|
| ![](https://user-images.githubusercontent.com/47610359/205491651-e2f97b21-8602-453e-be4e-32989de33c0b.png) | ![](https://user-images.githubusercontent.com/47610359/205491654-f922dcff-d105-412a-b9cb-3c29922d705e.png) |

**Comment by biodranik** [comment]
There are two main use cases for Dark mode:
1. To use during daylight (some users love it, but it is not a blocker). Icons here should be bright, like in Apple and Google maps.
2. To use at night in a dark car. Any bright text or icon there will create a lot of pain in the driver's eyes. So icons should NOT be bright.

There is already _vehicle_ style, maybe we can do it differently for the _general_ dark style, and for the _vehicle_ dark style.

**Comment by dvdmrtnz** [comment]
I think we can actually use a dark mode style that suits both use cases. Here I made a quick change to some icons to test it out and I think it looks better than the current style. What I did:
* Change white background circle to black and add 60% transparency

* Add 0.6 transparency to the background

**Comment by biodranik** [comment]
It looks better. What about icons without circles?

**Comment by dvdmrtnz** [comment]
White icons without circles don't look too bad. Maybe opacity could be lowered a bit. Currenty they are set to 60% opacity.

| 60% opacity | 50% opacity |
|-|-|
| ![](https://user-images.githubusercontent.com/47610359/205705514-8d67902d-d8da-494d-9744-74f790a7de47.png) | ![](https://user-images.githubusercontent.com/47610359/205705539-65237f08-dccb-411c-b3a0-58f3a76cc46a.png) |

**Comment by endim8** [comment]
> I think we can actually use a dark mode style that suits both use cases. Here I made a quick change to some icons to test it out and I think it looks better than the current style. What I did:

this looks _much_ better, definitely in favour of this!

**Comment by biodranik** [comment]
Let's create a PR and test it on devices.

**Comment by dvdmrtnz** [comment]
> Let's create a PR and test it on devices.

I will make a PR
