### ISSUE TITLE
Missing bus lanes on some cities

### ISSUE THREAD

**Issue by RaphLeSel** [organicmaps/organicmaps#4031]
I was looking to the issue PT routing unavailable #324 to see if it was fixed or not and I tested it. When I made my test, the transit distance/time was the same as the pedestrian distance despite there is a bus lane on this path.

![omaps_marche](https://user-images.githubusercontent.com/77000210/205656938-8e65d724-05eb-4220-b21a-508baf28c0a9.jpg)
![omaps_transit](https://user-images.githubusercontent.com/77000210/205656926-1d93cc10-7137-4bff-885a-2b529f79e34d.jpg)

**Comment by endim8** [comment]
Currently there is no public transport routing, so bus routes aren't used for routing. It's a good point however that pedestrian routing shouldn't route over `highway=busway` unless it's specifically tagged as public foot access

**Comment by pastk** [comment]
Public Transport expansion to trams, buses etc is tracked here:
- #5331

> Currently there is no public transport routing, so bus routes aren't used for routing. It's a good point however that pedestrian routing shouldn't route over `highway=busway` unless it's specifically tagged as public foot access. Many bus lanes near me have no footpath.

Would be good to create a separate issue for that if you think its actual still.
