### ISSUE TITLE
Differences between mobile app and desktop app on Rennes subway lanes

### ISSUE THREAD

**Issue by RaphLeSel** [organicmaps/organicmaps#4032]
When I used the gps on Rennes, I saw that there is only one subway lane on mobile app for this city while there is two lanes on the desktop app.

![subway_rennes_desktop](https://user-images.githubusercontent.com/77000210/205658443-21ee7e2f-9f12-46c5-bec9-a8b2ad3011e8.png)
![subway_rennes_mobile](https://user-images.githubusercontent.com/77000210/205658455-63bd5467-a648-43f2-a3b4-d6d548f5ab89.jpg)

**Comment by endim8** [comment]
It seems you dont have the latest maps on mobile. Try updating the maps, click the hamburger in the bottom right & press "download maps". If the issue is still present please say :)

**Comment by endim8** [comment]
please reopen if it remains broken after updating maps 👍
