### ISSUE TITLE
make popup informing user of new maps

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#4033]
Currently, the only indication that there are new maps to download is the little red dot on the hamburger menu.

It'd be better to do a popup (similar to 'stop detecting location') on the first launch after update, with 'download all', 'manage maps' & 'close' buttons

**Comment by biodranik** [comment]
No, that is a bad idea. The UI should not be intrusive, and a small dot (or a number on Android) perfectly works. Think about it from this perspective: more often, delta updates with an option to download all updates automatically.

**Comment by endim8** [comment]
That's true, although I feel like it should be more prominent somehow, a lot of reported issues are due to outdated maps

**Comment by biodranik** [comment]
Not much actually, from our experience. Maybe the color of the indicator should be more bright )
