### ISSUE TITLE
Custom subway icons doesn't display is some cities

### ISSUE THREAD

**Issue by Kazing** [organicmaps/organicmaps#4039]
In PR #3514 custom icons where added for several cities (https://github.com/organicmaps/organicmaps/pull/3514#issuecomment-1301144690)

I found at least 9 cities added with this PR (custom icons are present and city are listed in data/mapcss-mapping.csv), but doesn't display custom icon : 

- Lille, France
OSM node: https://www.openstreetmap.org/node/389432270
<details>
<summary>Screenshot</summary>

![Screenshot_20221206-103646](https://user-images.githubusercontent.com/41507326/205892780-7aee1d60-1d11-4f06-b908-36cf630b91b0.png)
</details>

- Adana, Turkey
OSM node: https://www.openstreetmap.org/node/5303110883
<details>
<summary>Screenshot</summary>

![Screenshot_20221206-114839](https://user-images.githubusercontent.com/41507326/205895671-0e078562-a95f-4355-89fc-1e1ee5a03470.png)
</details>

- Baku, Azerbaidjan
OSM node: https://www.openstreetmap.org/node/670216818

- Brescia, Italy
OSM node: https://www.openstreetmap.org/node/2183569935

- Bengalore, India
OSM node: https://www.openstreetmap.org/node/6432710301

- Bursa, Turkey
OSM node: https://www.openstreetmap.org/node/5315446884

- Izmir, Turkey
OSM node: https://www.openstreetmap.org/node/5388472390

- Malaga, Spain
OSM node: https://www.openstreetmap.org/node/4409530066

- Medellin, Colombia
OSM node: https://www.openstreetmap.org/way/932492025

I didn't check all 100+ cities, so there might be other.

OS: Android 13
Organic Maps version: 2022.11.24-3-FDroid
Data Version: 19 nov. 2022

**Comment by Kazing** [comment]
I attached 2 screenshots; default subway icon is displayed :
https://raw.githubusercontent.com/organicmaps/organicmaps/e9056f11fbc2cf3c41850701302bba305cbde95a/data/styles/clear/style-clear/symbols/subway-m.svg

**Comment by biodranik** [comment]
Where did you attach screenshots?

**Comment by endim8** [comment]
I can reproduce.I tried to find a fix but it's something more complicated, the drawing rules and classificator is correct (AFAIK). 
My only guess is that there's some issue with the function that checks if a station is with a region bounds.

**Comment by biodranik** [comment]
What are the underlying types of these metro stations in the desktop OM?

**Comment by endim8** [comment]
just `railway-station-subway`, not a city variant

**Comment by biodranik** [comment]
Then borders should be checked. @vng

**Comment by ember-rose** [comment]
Boston's MBTA is also missing its logo icon. The icon itself is already in the repo as [subway-massachusets-m.svg](https://github.com/organicmaps/organicmaps/blob/3a1700ab1f654812c85d1210db521fb5b066c4a6/data/styles/clear/style-clear/symbols/subway-massachusetts-m.svg) but it's not linked in [Subways.mapcss](https://github.com/organicmaps/organicmaps/blob/3a1700ab1f654812c85d1210db521fb5b066c4a6/data/styles/clear/include/Subways.mapcss). It might be worth checking if there are other metro systems in a similar state.

**Comment by endim8** [comment]
Happy to report that this is definitely fixed with the latest map data :)

**Comment by Altonss** [comment]
> * Lille, France
>       OSM node: https://www.openstreetmap.org/node/389432270

Somehow not all stations are fixed in Lille, this one for example is still missing the subway icon: https://www.openstreetmap.org/node/412283375

**Comment by vng** [comment]
Yes, https://github.com/organicmaps/organicmaps/pull/4136

**Comment by Altonss** [comment]
> Yes, #4136

Thanks! I'm sorry, missed this PR :)
