### ISSUE TITLE
Railways should be thicker

### ISSUE THREAD

**Issue by thany** [organicmaps/organicmaps#4049]
Railways are rendering as a super thin line, barely noticable when just panning around and trying to get your bearings. The fact that important station names are not visible, doesn't help either.

All the while, main roads are super in-your-face thick orange lines. In a country where the public infrastructure is almost exclusively built around cars, this makes sense (for example, in North America), but where railways are considered a primary mode of transport, it's important to see them. People are likely to use them as a way to find their way around on a map. Japan is a prime example of this. Numerous people use trains there, and you navigate around on a map by railway lines. Heck, hotels oftenly boast about how close they are to the train station 😀

This undoubtedly varies from country to country, making it slightly more difficult to fix properly for everyone. But hairline-thin railways with no station names (not even central/hub/terminal stations!) is not very useful. Take a look at Google Maps for inspiration 😉

**Comment by biodranik** [comment]
@vng can we do country-based drawing rules?

**Comment by biodranik** [comment]
A separate PT map style/layer would solve this issue too. Dynamic styles depending on the country allow us to do even more cool features.

**Comment by thany** [comment]
> a public transport focussed map rendering

That kind of sounds like switching between the two. I hope that's not the case. Railway lines sure can be made more visible alongside the current style of roads. Again, Google Maps is proof of this.

Then again, rendering the map focused on publi transit is probably more involved than just beefing up the style of railway lines. In probably similar ways, you could also make a style that focuses on bicycle and pedestrian use. Dutch people will surely like that 😀

**Comment by pastk** [comment]
Related to #2844

**Comment by pastk** [comment]
@thany railways visibility is improved by #5510, please check how it looks in the upcoming release..

**Comment by pastk** [comment]
Closing as completed - feel free to re-open if you think something else should be done.

There is an open idea to add main railway lines display into the World overview map #4945
