### ISSUE TITLE
Add direction notification

### ISSUE THREAD

**Issue by starvingarden** [organicmaps/organicmaps#4057]
There should be an option to enable a notification with directions like google maps and osmand.

**Comment by biodranik** [comment]
What kind of notifications are you talking about? Those that appear when the app is in the background? Please check #1104 and some other relevant issues.

**Comment by ksan314** [comment]
A notification that shows information about the next turn while navigating, regardless if the app is in the foreground or background. The notification should show a few things such as the distance to the next turn, the street name, and the direction (left, slight right, keep left, etc.)

**Comment by biodranik** [comment]
What is the point to show the notification if the app is in the foreground, and displays the next turn anyway?

**Comment by ksan314** [comment]
Im just describing how the direction notifications work in both google maps and osmand. I would think that always showing the notification while navigating would be easier to implement, and would just be consistent for the user. Or maybe this could be configurable...

**Comment by lapaz17** [comment]
Is there a mini version like google maps?
![image](https://user-images.githubusercontent.com/39624400/236844219-6721f9fa-efc7-4aae-8f8c-0700ecbe5c05.png)

**Comment by RedAuburn** [comment]
this has been implemented :)
