### ISSUE TITLE
Allow to selectively clear search history

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4063]
It will be very convenient, especially after implementing the "more often items are at the top" logic.

**Comment by pm4rcin** [comment]
Do you mean cleaning one entry from history when long-press and click?

**Comment by biodranik** [comment]
There are several native ways to delete list entries on Android and iOS. Long tap, swipe to the left or right, cross button, etc.

**Comment by Jean-BaptisteC** [comment]
Duplicate of #7185

**Comment by slackuj** [comment]
> There are several native ways to delete list entries on Android and iOS. Long tap, swipe to the left or right, cross button, etc.

I don't find this working on Android.And why is this issue marked closed? Has it been resolved?

**Comment by Jean-BaptisteC** [comment]
This issue has been closed because it's a duplicate of another issue
