### ISSUE TITLE
[android] Crash in split screen mode

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4072]
Android 7.0
Samsung SM-T813

There is `12-07 22:00:02.421 (Thread-23) E/OMcore: drape/texture_manager.cpp:377 Init(): CHECK(!m_isInitialized) ` crash in logs.

User's feedback:

Following various tests, I found that in split screen mode:
- if I try to change the screen surface of applications in operation, for example switching from 1/2 + 1/2 to 1/3 + 2/3 or 2/3 +1/3, OM crashes.
- if I open the Speedometer app and reduce its window to 1/3 and then open OM which will occupy 2/3 of the screen, OM works without crashing.
- if I open OM and then reduce its screen window to 1/3, OM crashes.

Conclusion: OM does not accept that its screen window will be changed to size when it is in operation.

This problem happened quite recently because until about mid November 2022, it did not happen.

**Comment by Jean-BaptisteC** [comment]
I reproduce in my Pixel 6 - Android 13 - version 2022.11.24-3-Google
I don't reproduce in version 2022.12.11-2-Google-beta

**Comment by biodranik** [comment]
The same user's feedback on the recent build with a possible fix:

I tried OM beta: the problem is the same as OM; in OMb split screen display stops if you try to change your screen window by going for example from 1/2 + 1/2 to 1/3 + 2/3.
To avoid shutdown, first open Speedometer in split screen in landscape mode, then reduce its window to 1/3 and then open OMb. By doing this way OMb does not stop. So I have on my landscape screen to the left Speedometer which occupies 1/3 of the screen surface and on the right OMb which occupies the remaining 2/3. If I try with the cursor between the Speedometer and OM windows to change the size of their windows or reverse the windows on the screen, OMb stops.


@Jean-BaptisteC can you please test this apk? https://cdn.organicmaps.app/apk/OrganicMaps-22121714-google-beta.apk

**Comment by Jean-BaptisteC** [comment]
I don't reproduce on this beta, for information, on Android 12 and Android 13, we need to have two applications opened to used split screen.
You can't used split screen with one applications. But i know older phones where open one app in splitscreen is possible and the other part of screen, show apps list can be openable in split screen. I have Honor 8 and this phone can be open one app in split screen, do you want i test ?

**Comment by biodranik** [comment]
Yes, please!

**Comment by Jean-BaptisteC** [comment]
I don't reproduce crash in version 2022.11.24-3-Web and version 2022.12.17-14-Google-beta on Honor 8 - Android 8

**Comment by Jean-BaptisteC** [comment]
Did you have some reports from user about crash on latest release ?

**Comment by biodranik** [comment]
Thanks for the reminder, user confirmed that it was resolved!
