### ISSUE TITLE
Routing not offering best route

### ISSUE THREAD

**Issue by DavidKarlas** [organicmaps/organicmaps#4110]
From: 46.038579, 14.469414
To: 45.22718, 13.596334

Takes 2h and 42min(201km).

But if I add stop at 45.530089, 13.734501 it takes 1h and 45min(159km).

**Comment by biodranik** [comment]
Do you have any "avoid" route options enabled?

**Comment by DavidKarlas** [comment]
Afaik, no:
![image](https://user-images.githubusercontent.com/774791/208512718-b7e9e866-3427-4353-9482-6ca4488e3ea8.png)

**Comment by Jean-BaptisteC** [comment]
[OSRM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=46.0385%2C14.4691%3B45.2272%2C13.5964) and [GraphHopper](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=46.0385%2C14.4691%3B45.2272%2C13.5964) suggest routing with 157km and duration < 2h.

**Comment by vng** [comment]
New app update with 221216 data gives route that seems like equal to the OSRM (157km):
<img width="456" alt="Screenshot 2022-12-19 at 23 24 24" src="https://user-images.githubusercontent.com/175612/208538576-ce6de9b7-62ea-46ca-b117-16ad80ab04e0.png">

**Comment by endim8** [comment]
did you update all the maps? i'll see if i can reproduce

**Comment by endim8** [comment]
i think i've found the issue:
the "download maps for better routing" popup only suggests to download West Slovenia & West Croatia, but East Slovenia is needed for the optimal route:
![signal-2022-12-20-020200_002](https://user-images.githubusercontent.com/26939824/208563854-de43ba9f-b6b0-4590-81ee-dab30f5e2f28.png)

@DavidKarlas do you have the East Slovenia map downloaded?

**Comment by DavidKarlas** [comment]
I have both installed:
![image](https://user-images.githubusercontent.com/774791/208565621-b92d9f51-3864-49e1-bab9-44ae3da6f29a.png)

I also deleted app, re-installed, re-downloaded all Slovenian(2) and Croatian regions(2).

**Comment by biodranik** [comment]
@DavidKarlas so you updated the app and maps data, and your route is still different from [this one](https://github.com/organicmaps/organicmaps/issues/4110#issuecomment-1358491960), right? Can you please show the similar screenshot?

**Comment by DavidKarlas** [comment]
I already posted 4 comments above screenshot of how my route looks like.

Now I wonder if locale could affect this.

**Comment by biodranik** [comment]
Sorry, I somehow missed that screenshot. The route is also correct with the latest app version and data on my device.

So if you zoom to areas on the correct route, all of them are downloaded, right?

**Comment by vng** [comment]
I found the reason.
- To reproduce a bug, should download all Slovenia and all Croatia.
- Funny, but app thinks that long (bad) route is better because it doesn't add crossing countries border penalty. And it adds this penalty (+2 hours) to the short (good) route.

Will investigate.

**Comment by DavidKarlas** [comment]
Glad to hear you were able to reproduce! Another fun fact... Quickly fix it or you won't be able to reproduce in 10 days when Croatia enters Schengen and border cease to exist 😃

**Comment by DavidKarlas** [comment]
I have a question... What needs to happen for this penalty to not be applied on 1.1.2023 when Croatia enters Schengen? 

1) You need to change some config to say no penalty on Slovenia-Croatia border?
2) I need to remove some tags/nodes marking border pass in OSM?
3) There is no way to remove penatly... What about Benelux? They also have this penalty?

**Comment by vng** [comment]
We don't depend on OSM data here. Croatia will be added to this file https://github.com/organicmaps/organicmaps/blob/master/routing/mwm_hierarchy_handler.cpp
