### ISSUE TITLE
No custom subway icon when station is an area

### ISSUE THREAD

**Issue by Kazing** [organicmaps/organicmaps#4120]
Hello, thanks for the fix of issue  #4039 👍 

When testing the change with new version 2022.12.18-12-FDroid 
I saw stations that doesn't display the custom icon, while other stations in same city do.

Seems that when `railway=station + station=subway` is tagged on an area (here it's on the building of an above ground station), custom icon doesn't display (4 area station in the cities, the 4 doesn't display the custom icon).
![Screenshot_20221220-133814](https://user-images.githubusercontent.com/41507326/208671244-9b530e86-ff7f-4f26-9237-db0ba45098bd.png)

* Station with custom icon: https://www.openstreetmap.org/node/389432270
* Station with standard icon: https://www.openstreetmap.org/way/65203864

**Comment by endim8** [comment]
https://github.com/organicmaps/organicmaps/blob/68c528f26606333a50c2f119e41c58a78af4f696/generator/osm2type.cpp#L589-L594

can confirm that only nodes are processed when assigning metro-CITY types

**Comment by biodranik** [comment]
That should be easy to fix, right?
