### ISSUE TITLE
planet.o.a TLSv1.3 enablement

### ISSUE THREAD

**Issue by jpds** [organicmaps/organicmaps#4123]
TLSv1.3 should be enabled on planet.organicmaps.app as this reduces the round-trip time for the handshake:

- https://www.cdn77.com/blog/improving-webperf-security-tls-1-3
- https://blog.cloudflare.com/rfc-8446-aka-tls-1-3/

This should just be a case of setting in the `nginx` configuration:

```
ssl_protocols TLSv1.2 TLSv1.3;
```

This can then be checked with:

```
$ curl -I -v --tlsv1.3 --tls-max 1.3 https://planet.organicmaps.app
```

Android supports this for all apps as of version 10: https://developer.android.com/about/versions/10/behavior-changes-all#tls-1.3 and iOS since 12.2: https://support.apple.com/en-gb/guide/security/sec100a75d12/web

**Comment by biodranik** [comment]
@rtsisyk can you please take a look and fix it for all our servers? I did a quick check, and our nginx has `ssl_protocols TLSv1.2 TLSv1.3;` in `/etc/letsencrypt/options-ssl-nginx.conf` enabled. But it doesn't work for some reason.

This is a high-priority issue, @jpds thanks for letting us know!

**Comment by biodranik** [comment]
Found and fixed the issue. Thank you again, now all our servers will serve maps to our users a bit faster!
