### ISSUE TITLE
Night mode text color is too similar to 2d buildings

### ISSUE THREAD

**Issue by tguen** [organicmaps/organicmaps#4126]
With night mode enabled & 3d buildings disabled, text on top of buildings is too low-contrast.
![omaps-dark-text_1](https://user-images.githubusercontent.com/57420975/208812736-cb0148c0-8d50-41c5-a25d-a59a92074406.png)

**Comment by biodranik** [comment]
To confirm:
1. Is it the same for all buildings?
2. Is contrast ok with 3D buildings enabled?
3. Was it changed recently or is it an old issue?

**Comment by tguen** [comment]
1. Yes, all buildings, but only at higher zoom levels since buildings get brighter as I zoom in.
2. Yes, buildings are darker in 3d & look fine.
3. Not a recent change. I first noticed several months ago.

**Comment by Rorschach1010** [comment]
Same here. I don't like using 3D style but I can confirm that the contrast is better on 3D.

**Comment by dvdmrtnz** [comment]
* This was fixed in https://github.com/organicmaps/organicmaps/pull/7413
