### ISSUE TITLE
planet.o.a BBR mode

### ISSUE THREAD

**Issue by jpds** [organicmaps/organicmaps#4127]
Small infra suggestion: planet.organicmaps.app should use BBR as its TCP congestion algorithm:

- https://cloud.google.com/blog/products/networking/tcp-bbr-congestion-control-comes-to-gcp-your-internet-just-got-faster
- https://www.bleepingcomputer.com/news/technology/googles-bbr-algorithm-for-speeding-up-internet-traffic-gains-wider-adoption/
- https://blog.wirelessmoves.com/2022/06/fiber-in-paris-part-4-packet-loss-and-bbr-to-the-rescue.html

By default, `cubic` is used which is a conservative algorithm sensitive to packet loss whereas BBR favours maximizing bandwidth. This can be checked on the server doing:

```
$ ss --tcp -i
```

BBR can be set in `/etc/sysctl.d/01-bbr.conf` with:

```
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
```

And then set with:

```
$ sudo sysctl -p /etc/sysctl.d/01-bbr.conf
```

The `ss` command above will then show new connections as having BBR in use (with stats).

**Comment by biodranik** [comment]
Thanks for the links, it is definitely worth enabling on our side in our use-case.

**Comment by biodranik** [comment]
BBR should work now, let's see if we have any issues with it.
