### ISSUE TITLE
Selection circle color in navigation have wrong color in dark mode

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4132]
In this PR https://github.com/organicmaps/organicmaps/pull/4037, we have update circle color in dark mode but we have forgotten to update circle color in navigation mode (Color is blue in dark mode like in light mode)

Pixel 6 - Android 13
v2022.12.18-12-Google

CC @dvdmrtnz

**Comment by biodranik** [comment]
Could it be a "feature"? E.g. if icons are more visible when driving then it's better.

**Comment by Jean-BaptisteC** [comment]
I don't talk about icons POI but i talk about selection circle color.
On map:
<img src="https://user-images.githubusercontent.com/87148630/209130814-1bbfd0b0-0cdf-41cd-8ba5-2b6c26c5cc79.png" height=600 />

In routing:
<img src="https://user-images.githubusercontent.com/87148630/209131103-562f42d6-c1c2-48ee-855e-81c5686b6e35.png" height=600 />

**Comment by Jean-BaptisteC** [comment]
We have forgotten to update this line https://github.com/organicmaps/organicmaps/blob/3cde21e34d7c344d6ad36e690d6ae6992daaec85/data/styles/vehicle/style-night/style.mapcss#L26
