### ISSUE TITLE
Measure distance

### ISSUE THREAD

**Issue by HiddenLeveI** [organicmaps/organicmaps#4139]
This is a feature request:

You guys should add a feature where you can measure distances between places like what google earth has. It would be helpful for knowing how many miles I'm running.

**Comment by biodranik** [comment]
What exactly do you mean? Is it something similar to #1452 ?

**Comment by mxdanger** [comment]
Organic Maps already has route distance. If you mean straight-line measuring, then this would be a duplicate of #1452 as mentioned above.

**Comment by HiddenLeveI** [comment]
Yes, I meant like #1452

**Comment by mxdanger** [comment]
Alright so this should be closed as a duplicate of #1452
