### ISSUE TITLE
Touch bookmarks icon or title POI on map doesn't open same place page

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4141]
How reproduce:
- Open OM
- Select POI --> add to bookmarks
- Touch bookmarks icon on POI --> POI is attached to bookmarks and star is yellow on place page
- Touch title of POI --> POI is not attached to bookmarks and star is grey on place page (we can re-add POI on bookmarks)

User has touched bookmarks icon
<img src="https://user-images.githubusercontent.com/87148630/209299262-7d476415-914b-4b5f-b5f8-254990391792.png" height=500 />

User has touched title of POI
<img src="https://user-images.githubusercontent.com/87148630/209299614-be2d232d-b976-4510-badf-dfb3866dbc10.png" height=500 />

Pixel 6 - Android 13
v2022.12.18-12-Google

**Comment by biodranik** [comment]
Title of poi = on the map? Or in the Place Page?

**Comment by Jean-BaptisteC** [comment]
Title of poi on the map

**Comment by biodranik** [comment]
Title is likely not related here. The selection code has a bug. If user tapped close to a bookmark/bookmarked feature, the same bookmarked feature/bookmark should be selected.
