### ISSUE TITLE
Location button is displayed incorrectly on older Android devices

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4142]
OnePlus2, Android 6.0.1

|img|video|
|---|-----|
|![image](https://user-images.githubusercontent.com/170263/209322750-83fc34ad-86ba-4e7e-b86e-9b5a14d074cd.png)|https://user-images.githubusercontent.com/170263/209323775-c7c8e418-bb97-4920-96a2-d37d0ff50876.mp4|

Similar behavior was observed in the Android 5 emulator.

**Comment by Jean-BaptisteC** [comment]
Fixed by https://github.com/organicmaps/organicmaps/pull/6067
