### ISSUE TITLE
POI feature type is not marked correctly on Organic Maps.

### ISSUE THREAD

**Issue by Growebis** [organicmaps/organicmaps#4144]
For some unknown reason to me, This POI isn't marked as a bowling alley, it doesn't even register it's name, but rather as a "building" with the address as the name. See image below,
OpenStreetMap
![Screenshot 2022-12-23 142949](https://user-images.githubusercontent.com/113867283/209398331-03d8f045-b43e-42f0-8537-486b639a80b8.png)
Organic Maps
![Screenshot_20221223-141420](https://user-images.githubusercontent.com/113867283/209398389-c60d9874-d46d-4dfc-ba8b-4cf9933e2834.png)

POI is [45.4321793, -73.6173618](https://www.openstreetmap.org/#map=18/45.4321793/-73.6173618)

**Comment by biodranik** [comment]
There is no leisure=bowing_alley type support yet in OM. We also need a good icon for it.

**Comment by Growebis** [comment]
Should this be now marked closed since there is a pull request merge for it?

**Comment by biodranik** [comment]
Issues should be closed only when PRs are merged into the master branch.
