### ISSUE TITLE
Found a case where routing make passing by toll both, even when asking to avoid paid roads.

### ISSUE THREAD

**Issue by Popolon** [organicmaps/organicmaps#4151]
On Organic Maps from December 2022 (2022.12.18-12-FDroid), updated maps for this area,
I select a route from [Fécamp](https://www.openstreetmap.org/relation/109976) to [Paris](https://www.openstreetmap.org/relation/71525), the option to "avoid toll roads" is enabled.

Route wrongly passes through this Yvetot city toll both:
https://www.openstreetmap.org/way/428611061

**Comment by biodranik** [comment]
@vng "avoid toll roads" doesn't work here for some reason.

**Comment by vng** [comment]
We process toll=yes on ways now. Of course, can skip routes via standalone barrier=toll_booth nodes, but hard to define where it ends. So better to map ways properly.

https://wiki.openstreetmap.org/wiki/Key:toll

**Comment by Popolon** [comment]
tooll=yes has been added to this specific section on OSM.

**Comment by Popolon** [comment]
Sorry I forgot to close this issue.
