### ISSUE TITLE
The ground cannot be rendered with my own generated MWM file via maps generator when zoom in map.

### ISSUE THREAD

**Issue by kf99916** [organicmaps/organicmaps#4152]
Hi all,

As title and the map generator command is:
`python3 -m maps_generator --countries="World, WorldCoasts, China_Guangdong"`

Here is the logs generated by map generator: [https://drive.google.com/drive/folders/1QPm1EfO40gxmnXu29I4PGKWfVutFJ9aJ?usp=share_link](https://drive.google.com/drive/folders/1QPm1EfO40gxmnXu29I4PGKWfVutFJ9aJ?usp=share_link)

### Before zoom in:
![IMG_A5F61BA05460-1](https://user-images.githubusercontent.com/6695195/209526530-0f45d3e8-0906-457d-bff8-3388ab398681.jpeg)

### After zoom in:
![IMG_BDECC6E21D0F-1](https://user-images.githubusercontent.com/6695195/209526265-1e9cfcfd-13e9-4612-99f3-e987d0b9fcd7.jpeg)

I didn't encounter the problem with my own generated MWM file in other regions. Are any steps wrong for my generated MWM file? 

Thanks so much.

**Comment by biodranik** [comment]
Did you process the whole planet dump? It is required to properly generate correct WorldCoasts.mwm and World.mwm files.

**Comment by biodranik** [comment]
Also, the log clearly says that some coastlines weren't closed. It should be fixed in OSM first, and then you need to regenerate maps again.

**Comment by kf99916** [comment]
Hi @biodranik ,

No, I was not process the whole planet. The process takes a lot of time and disk spaces and I just want to generate some regions instead of whole planet. Thus, I followed [the tutorial](https://github.com/organicmaps/organicmaps/blob/master/tools/python/maps_generator/README.md#non-standard-planet-with-coastlines) to configure `map_generator.ini`.

```
PLANET_URL: https://download.geofabrik.de/asia/china-latest.osm.pbf
PLANET_MD5_URL: https://download.geofabrik.de/asia/china-latest.osm.pbf.md5
```

Based on your reply, if I just want to generate `China_Guangdong.mwm`, then the steps are:

1. Process the whole planet by configuring `map_generator.ini`

```
PLANET_URL: https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
PLANET_MD5_URL: https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf.md5
```

2. Run the command
```
python3 -m maps_generator --countries="World, WorldCoasts, China_Guangdong"
```

Is it right? I got stuck into the problem for a while. It is grateful if you can guide me to generate the `China_Guangdong.mwm`.

**Comment by biodranik** [comment]
Should be right. Looks like our manual is a bit misleading, the whole planet should be used as a source if you want to generate correct coastlines.
Later you can reuse generated intermediate coastlines data in a country-only generation. Please let us know if you succeed, and update the tutorial accordingly.

**Comment by kf99916** [comment]
The process for whole planet is very time-consuming and space-consuming. Is it possible to generate coastlines related to target region?

**Comment by biodranik** [comment]
Not at the moment, unfortunately. The code should be written for that case. We don't need it, so nobody implemented it.

**Comment by kf99916** [comment]
Is it possible to share the generated intermediate coastlines data to this community? The coastlines should be not changed often. Thanks for your big help.

**Comment by kf99916** [comment]
Hi @biodranik ,
I tried to use the whole planet to generate intermediate coastlines data: `WorldCoasts.geom` & `WorldCoasts.rawgeom`, but still not work. Here is my process:

1. Generate intermediate coastlines data: `WorldCoasts.geom` & `WorldCoasts.rawgeom` with the whole planet.
2. Set `PLANET_COASTS_URL` to the above intermediate coastlines data and update code in the `StageCoastline()` to use the data.
3. Set `PLANET_URL` & `PLANET_MD5_URL` to China.
4. Generate `China_Guangdong` map with 
`python3 -m maps_generator --countries="World, WorldCoasts, China_Guangdong"`
5. Update the `China_Guangdong` part at  the `countries.txt` in `data` folder. Keep others in `data` folder. (Should I use my generated `World.mwm` and `WorldCoasts.mwm`?)
6. Put  `China_Guangdong` map into app folder.
7. Run app.

**Comment by biodranik** [comment]
What is your issue? Did you generate and use world* files? Did you use a planet dump with fixed coastlines (no holes in them)? There were warnings about holes, I mentioned it above.

**Comment by kf99916** [comment]
Hi @biodranik,
Thanks for the update. Could you clarify on the following points on which you mentioned?
1. By “using world* files” what did it mean? I used the plant dump from [https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf](https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf) to generate intermediate coastline data: `WorldCoasts.geom` & `WorldCoasts.rawgeom`; and then used them to generate country files. However, I did not use my generated `World.mwm` and `WorldCoasts.mwm` for App test.
2. I’m nor sure if the planet dump from [https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf](https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf) has fixed coastlines. Any instructions on how I can check it? (and if it turns out to have broken coastlines, how might I fix it?)
3. The latest version of the manual on map generation states that "To build an entire country with coastlines, you need to download the latest_coasts.geom and latest_coasts.rawgeom files and specify their path in the config." Any instruction on where I can download the latest_coasts.geom and latest_coasts.rawgeom files? [Link to manual](https://github.com/organicmaps/organicmaps/blob/master/tools/python/maps_generator/README.md#japan-with-coastlines)

Your help will be much appreciated! Thanks!

**Comment by kf99916** [comment]
Hi @biodranik,

We fixed this issue and thank you for your help.

**Comment by biodranik** [comment]
@kf99916 I've checked and didn't find a reference to the Organic Maps copyright message in Hiking Book. According to our Apache 2.0 license, you should display it in your app. There is also a list of other software used in OM source code that requires copyright messages, we show it now in About -> Copyrights (at the bottom).

Can you please add a visible and clickable message like this in your Welcome/login screen at the bottom?

> Offline maps source code is based on [Organic Maps](https://organicmaps.app)

**Comment by kf99916** [comment]
@biodranik the copyright messages for Organic Maps and OSM are shown now in our Settings -> About & Contact Support -> Copyright.

![IMG_DD158BDACBD1-1](https://user-images.githubusercontent.com/6695195/220579611-7fd85f58-9e7e-4b75-b388-0dd17cd7a785.jpeg)

Is it ok with you?

**Comment by biodranik** [comment]
I don't see settings in the app. Should users login to see it? Would it be possible to see the copyright without logging in?

**Comment by kf99916** [comment]
Now, you need to log in to see it. Yes, it is definitely possible to do this. We will make it visible even without logging in and let you know in this thread once the change is released. Thank you all and this awesome project.

**Comment by kf99916** [comment]
Hi @biodranik the copyright messages for Organic Maps and OSM are visible now without logging in with Hikingbook v13.3. Skip the login view and you can see the Settings at the top-right corner in Me tab.

**Comment by biodranik** [comment]
Awesome, thank you!
