### ISSUE TITLE
Allow zooming even further on the map

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4156]
At the moment it is not easy to see all icons or add a new place precisely when there are many icons on the map. Allowing zooming further may help in some cases.

A better option for showing hidden icons is their grouping (discussed in #1109)

**Comment by Misalf-git** [comment]
I was about requesting increased max zoom level for better cross hair prcision as well.

Smart grouping of icons sounds good for checking several POIs without the need to zoom in and out repeatedly.

**Comment by patepelo** [comment]
Adding more zoom would improve the overall experience even if the grouped POIs solution is added on top of this later. 

This is a benchmarking comparison.

GM: 
![image](https://github.com/organicmaps/organicmaps/assets/23003127/44de1926-c024-462b-a0ea-86c36e16854b)

OsmAnd:
![image](https://github.com/organicmaps/organicmaps/assets/23003127/bf873b1e-29f5-4ba3-81db-5d3b1da1d198)

Current OM:
![image](https://github.com/organicmaps/organicmaps/assets/23003127/f9a73732-f087-4bb5-b4f8-642a736801e4)

It would be a good first step to declutter nearby POIS at first, with other improvements to the UX. Then if, still needed, a second solution as mentioned it #1109 would be a good addition that's not contradictory to amplofying zoom.

Is it techically difficult? or more resource demanding to the device to add more zoom levels?

**Comment by RedAuburn** [comment]
with the new PR :)

<img width="400px" src="https://github.com/organicmaps/organicmaps/assets/26939824/b5550345-73d7-4b3b-8e04-8df819fb98a1"/>

**Comment by pastk** [comment]
Interesting, the line is supposed to be 16m, but the 5m ruler is not 3 times shorter, but much more shorter..

**Comment by RedAuburn** [comment]
hmmm.. It works in metric (goes to >10ft), maybe there aren't enough steps in imperial?
it doesn't scale at all once it reaches the smallest 5m bar, even when zooming further

**Comment by RedAuburn** [comment]
fixed it @pastk! set this to 1: 

https://github.com/organicmaps/organicmaps/blob/a0481130fdf11154dac04ac09a664dbe8ae25db5/drape_frontend/gui/ruler_helper.cpp#L23
