### ISSUE TITLE
Network-based location not used on LineageOS with MicroG

### ISSUE THREAD

**Issue by philipmgrant** [organicmaps/organicmaps#4158]
My setup:
	Organic Maps (2022.12.18-12-FDroid.22121812)
	Moto G5S+ (sanders)
	LineageOS 17.1 (based on Android 10)
	MicroG 0.2.24.214816
	
The problem is that Organic Maps never finds a location when GPS can't get a lock - even when network location providers are active (via MicroG).

Organic Maps does have location permissions, and can successfully get locations from GPS.

I know MicroG's network location can be unreliable, but that doesn't seem to be the problem here: I can see from the MyLocation app that the Apple and Mozilla backends are reporting up-to-date locations, and from logcat that LocationFuser does find a fused location.

I can't see a smoking gun in the logcat, but to be honest I have limited knowledge of what to look for - if anyone can point me to what to look for in the logs, then I can provide it here.

**Comment by biodranik** [comment]
Can you please enable logs in OM settings, reproduce the location search failure, and then share logs with us via "?" -> Report a bug?

**Comment by endim8** [comment]
i _think_ i get this issue as well on Lineageos 19.1 w/ UnifiedNLP, i'll try get logs too

**Comment by philipmgrant** [comment]
> Can you please enable logs in OM settings, reproduce the location search failure, and then share logs with us via "?" -> Report a bug?

Thank you, I've just sent them over!

**Comment by philipmgrant** [comment]
This turns out not to be a problem on the Github release version of OM, which works fine with MicroG network location.  Thanks @biodranik for the assistance!

**Comment by biodranik** [comment]
Let me summarize: FDroid build of OM doesn't have the Google Location services library integrated, and it doesn't detect networking location providers on a de-googled device.

Any other build has this Google library, which works properly with Microg.

It could be a Microg issue.

**Comment by rtsisyk** [comment]
We investigated this issue based on reports from other users. It looks like that certain LineageOS ROMs have broken `fused` location provider that pretends to be enabled, but in the reality does absolutely nothing. The system just misreports that `fused` provider is available, but it doesn't return any location updates. This behavior is affected by privacy-related checkboxes offered during initial onboarding screens. My latest PR will always try all three providers (`fused`, `gps` and `network`) even if `fused` is reported to be available.
