### ISSUE TITLE
Zooming crashes the app

### ISSUE THREAD

**Issue by jf99** [organicmaps/organicmaps#4175]
The app crashes as soon as I start zooming. Panning works, but zooming kills the app. I use the F-Droid build on /e/OS 1.6-20221129238947. Here is the [log file](https://github.com/organicmaps/organicmaps/files/10327863/organicmaps-bugreport-RhDJPSdQQAKabh4-UylUDw.zip) from the "Report a bug" function for more details. Let me know if I can provide more helpful information.

**Comment by biodranik** [comment]
It looks like a corrupted SD-card issue. Can you please delete all maps, select internal storage, redownload maps and test them again? Or format/replace your SD-card and re-download maps?

**Comment by jf99** [comment]
Indeed, re-downloading the maps solves the problem. Thanks!
