### ISSUE TITLE
Store downloaded maps in external storage

### ISSUE THREAD

**Issue by brainchild0** [organicmaps/organicmaps#4176]
Currently, it seems downloaded maps are not kept in external storage. The  choice has undesirable implications for backup and other system operations.

Suggested is use of external storage.

**Comment by biodranik** [comment]
What is your Android version? External storage requires additional (non-privacy friendly) permissions, and it doesn't work from Android 11 and above.

**Comment by biodranik** [comment]
Another important question: why do you need to backup downloaded maps? We plan to update them weekly. What is the point, if you can always re-download maps?

**Comment by brainchild0** [comment]
I am running Android 12. I believe a framework is available for accessing an external storage directory designated for the application. 

Downloaded maps should not be backed up, which is why placement in external storage is preferred.

**Comment by biodranik** [comment]
1. There is a complex Java middleware to access files on external storage from Android 11 and above, but it will make fast Organic Maps slow as hell. We don't want to use it.
2. What is your backup software? We have marked now downloaded maps to be excluded from Google's backups. Does your software respect these "exclude" settings?

**Comment by brainchild0** [comment]
I make backups variously using NeoBackup and TWRP. The former appears not to respect the setting, and the latter captures an image of entire partitions.   Images of   internal data partitions should not grow  in size due to storage of large downloaded assets, because it is external storage that is intended for such data. The data partition should store applications and basic settings.

**Comment by biodranik** [comment]
Do you have any options available in OM Settings/Storage selection?

Did you contact NeoBackup why are they ignoring the app's backup ignore settings? Maybe they already have similar issues, or it is already a known issue.

In any case, we do not plan to implement any Java wrappers to access the storage. As I mentioned above, the read speed will decrease significantly (5x-10x or even more) in addition to the time necessary for us to implement this code.

Please let us know if you see any other options.

**Comment by brainchild0** [comment]
I have not brought the issue to the attention of the developer of Neo Backup.

Regarding external storage, since the current opinion is firm, all I can offer is two questions:

1. Would a configuration setting be considered  for allowing a user to choose external storage, if desired?

2. Taking the premise that access speeds are severely degraded for external storage, might the practical implications for application use be considerably more mild, considering that the application is an interactive one that needs to access  map components only as  required for immediate rendering demands?

**Comment by biodranik** [comment]
You likely don't understand the consequences of implementing _indirect_ file access via Java wrappers, as Google proposes. Organic Maps _extensively_ reads all information from maps. It won't be usable, even if we decide, for some reason, to spend weeks or months coding and testing that middleware layer. _It does not worth it_.

**Comment by biodranik** [comment]
What I do not understand, is why you can't select external storage now from Organic Maps settings. What is displayed there in your case?

**Comment by brainchild0** [comment]
Perhaps I misunderstood your earlier question. I do find the option for using external storage.

However, your earlier comments have implied that such a feature is not available nor will be available in the foreseeable future.

Perhaps you might resolve the  disparity, of your explanation of not having plans to implement the feature, versus the option currently appearing in the menu.

**Comment by biodranik** [comment]
Does it mean that this issue is invalid for your case and should be closed?

I was speaking about these restrictions: https://developer.android.com/about/versions/11/privacy/storage

**Comment by brainchild0** [comment]
> Does it mean that this issue is invalid for your case and should be closed?

You tell me.

Is external storage supported, or not?

**Comment by biodranik** [comment]
OM can store maps on a private directory on the SD card. That directory can not be accessed by other software on Android 11 and above if the device is not rooted without using new Android 11+ API that slows down the access. 

Does it work in your case?

**Comment by brainchild0** [comment]
There is no reason why the directory must be accessible by other applications.  Answering the question, the  available option satisfies the needed case.

To my mind, external storage would be preferred for most users as the storage location for downloaded maps. I suggest the default be changed.   I cannot think of any reason for a user preferring internal storage, and it would not bother me in the least if it were not   supported.

**Comment by biodranik** [comment]
External storage should be already selected as the default one after the installation. Please create a detailed issue if it is not selected automatically including your device's hardware configuration and Android version.

P.S. To test it, you need to uninstall OM. Uninstall will delete all bookmarks! Please back up them first by exporting each bookmark list.

**Comment by brainchild0** [comment]
Perhaps the non-default setting would have been inherited from some default settings given by an earlier version of the application.

**Comment by rudolfmu** [comment]
I have a Samsung with Android 13. I can change the location where to store maps in the app settings. Maps are then moved there and used.

**Comment by rtsisyk** [comment]
The app chooses external storage by default (if available). You can also choose between available options in the app settings. This ticket is not actionable. Please feel free to re-open if you still have this issue.
