### ISSUE TITLE
Many wrong search results (streets) in Salem

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4190]
"Taco Bell" shows many streets starting with Bellevue on the map.

Similar complaints were for the "Pet shop" query.

**Comment by vng** [comment]
Use "search on map" mode.

**Comment by vng** [comment]
Something similar: https://github.com/organicmaps/organicmaps/issues/3655

**Comment by vng** [comment]
de: "sprit" (fuel category) makes fuzzy prefix match and got a lot of "spital" results (at least in Zurich).
