### ISSUE TITLE
Missing Voice Language

### ISSUE THREAD

**Issue by FTno** [organicmaps/organicmaps#4199]
In Settings - Voice Instructions - Voice Language, Norwegian (Norsk) is missing on the list of languages.

Maybe related: https://github.com/organicmaps/organicmaps/issues/3568#issuecomment-1274825401

Version 2022.12.18-12-FDroid

**Comment by endim8** [comment]
It looks like we don't have TTS translations for Norwegian yet, would you be able to add them? 

https://github.com/organicmaps/organicmaps/blob/master/data/strings/sound.txt
