### ISSUE TITLE
Render prisons

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#4204]
Should also increase icon rendering to z16

OM Currently:
<img width="736" alt="Screenshot 2023-01-06 at 13 58 23" src="https://user-images.githubusercontent.com/26939824/211026889-3f1c4fc0-8e58-4beb-adf2-b68b34f79650.png">

OSM Carto:
<img width="736" alt="Screenshot 2023-01-06 at 14 01 44" src="https://user-images.githubusercontent.com/26939824/211027442-d7cce4f9-86ef-470e-9614-6401eee763f5.png">

(https://www.openstreetmap.org/way/37711456)

**Comment by endim8** [comment]
needs rendering of the [amenity=prison](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dprison) tag with the hatching of a military area, but grey.

icon and strings already exist, but should render at a lower zoom
