### ISSUE TITLE
[generator] Check main type for drinking_water

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#421]
Seems like wheel chair access is "better" than drinking_water now.
![photo_2021-05-17 01 12 09](https://user-images.githubusercontent.com/175612/118414399-fff7eb80-b6ac-11eb-88d2-9be7e08de213.jpeg)

**Comment by biodranik** [comment]
Also, it would be great to draw a wheelchair icon (emoji) instead of the current text.

**Comment by rtsisyk** [comment]
Fixed by #434
