### ISSUE TITLE
Better translations for tracks and bookmarks

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4218]
![image](https://user-images.githubusercontent.com/170263/211115618-98207b14-4e1f-4d1e-a6a1-4f344403fccf.png)

Sample 1: in Dutch 3 plaats
Better: 1 track + 2 bookmarks
In Dutch:  1 track + 2 plaatsen

Sample 2: in Dutch 11 plaats
Better: 1 track + 10 bookmarks
In Dutch: 1 track + 10 plaatsen

Sample 3: in Dutch 2 routes
Better: 2 tracks
In Dutch: 2 tracks

——

1 bookmark and 2 bookmarks
Translation In Dutch:
1 plaats and 2 plaatsen

It should be done not only for Dutch, but also for other languages.

**Comment by Priyanshu-Mallick** [comment]
Hey, I want to work on this issue and I think I can solve it. Please assign me this issue.

**Comment by prithvi206** [comment]
@biodranik  Can I get a list of languages which this has to be translated

**Comment by biodranik** [comment]
1. Find where this string is used in the code.
2. Make sure that you'll change only this dialog and a few relevant places (e.g. 3d touch menu on iOS).
3. Edit data/strings/strings.txt, adding a new translation only if the old one is reused in some other place that is not related to tracks, but only related to bookmarks.
4. See more info in docs/TRANSLATIONS.md

**Comment by prithvi206** [comment]
thank you then I will work on it.

**Comment by Rakshith-sakhamuri** [comment]
Hey @biodranik,I tested it in my iphone and I translated every thing pretty well
![image](https://user-images.githubusercontent.com/106099851/222931003-186c1e4e-0667-488a-948e-2f23fbf5963a.png)
 
![image](https://user-images.githubusercontent.com/106099851/222931016-37b16669-ab5b-4502-abcc-7433abda66b3.png)

**Comment by Rakshith-sakhamuri** [comment]
hey @biodranik ,I tested the app in my iphone and everything is working well 
<img width="391" alt="image" src="https://user-images.githubusercontent.com/106099851/222931073-052ee57e-dc8d-43db-8c11-35005fcfb9ac.png">

**Comment by Rakshith-sakhamuri** [comment]
I think bookmarks and route translation are there in strings.xml and strings.txt but are not there in localizable strings .
Can i add the translations to those files or is there anything we have to do with the java and swift codes too?

**Comment by Rakshith-sakhamuri** [comment]
hey @biodranik I think bookmarks and route translation are there in strings.xml and strings.txt but are not there in localizable strings .
Can i add the translations to those files or is there anything we have to do with the java and swift codes too?
