### ISSUE TITLE
Wrong search results ranking

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4219]
Test in this area: https://www.openstreetmap.org/?#map=16/53.6458/9.8937

![image](https://user-images.githubusercontent.com/170263/211117461-f5ddc5a7-8316-4abb-8ea2-b7367c9bd4cc.png)

**Comment by Jean-BaptisteC** [comment]
In the latest version (2023.11.17-18-Google) nightclub is at the top of the list.
