### ISSUE TITLE
Location detection doesn't work on Fdroid

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4223]
It is not clear yet if it works with Google Play services or not.

Google Pixel 2 XL, Android 12

After (non-cold) OM restarting (in location disabled state) and tapping the location button, nothing happens. Logs show that location service was stopped:

```
01-02 16:51:55.756 (main) D/LocationHelper: onTransit(): Location updates are stopped by the user manually, so skip provider start until the user starts it manually.
01-02 16:51:56.580 (main) D/LocationHelper: start():
01-02 16:51:56.593 (main) D/LocationHelper: calcLocationUpdatesInterval(): mode = 1 interval = 3000
01-02 16:51:56.594 (main) I/LocationHelper: start(): provider = AndroidNativeProvider mInFirstRun = false oldInterval = 0 interval = 3000
01-02 16:51:56.594 (main) D/AndroidNativeProvider: start():
01-02 16:51:56.597 (main) D/AndroidNativeProvider: start(): Request Android native provider 'fused' to get locations at this interval = 3000 ms
01-02 16:51:56.604 (main) D/MwmActivity: onMyPositionModeChanged(): location newMode = 0
01-02 16:52:56.618 (main) D/LocationHelper: onLocationPendingTimeout():  permissions = true settings = true
01-02 16:53:04.491 (main) W/LocationHelper: lambda$onLocationPendingTimeout$4(): Disabled by user
01-02 16:53:04.493 (main) D/LocationHelper: stop():
01-02 16:53:04.493 (main) D/AndroidNativeProvider: stop():
01-02 16:53:04.513 (main) D/MwmActivity: onMyPositionModeChanged(): location newMode = 1
01-02 16:53:12.459 (main) D/AppBackgroundTracker: onActivityPaused(): onActivityPaused activity = app.organicmaps.MwmActivity@7276c7d

```

https://user-images.githubusercontent.com/170263/211139196-cfd8e1df-8ce7-4c4d-90fe-a1a1d660d558.mp4

[logs.zip](https://github.com/organicmaps/organicmaps/files/10365685/logs.zip)

**Comment by biodranik** [comment]
@rtsisyk can we somehow log/detect which fused location provider is installed/configured? Any additional info about it in the log would be very useful.

**Comment by Altonss** [comment]
I'm experiencing similar issues with OM (only tried with the latest F-droid version). Sometimes when entering OM no location is detected.

**Comment by jakoblm** [comment]
I am experiencing a similar issue with the F-Droid release: https://github.com/organicmaps/organicmaps/issues/4540.

**Comment by rtsisyk** [comment]
We have solved this problem in May 2023 release. Now F-Droid versions uses all available location providers to avoid issues with broken `fused` that does nothing. Please see #4158.

**Comment by rtsisyk** [comment]
Please feel to re-open if problem still exists.

**Comment by biodranik** [comment]
@Altonss can you please provide more details, and maybe record and send us logs?

**Comment by privatemaker** [comment]
With my testing and opening of #5669 I also encounter this as I am on version `2023.07.10`

Given critical-ness of this issue, I can test on a few devices with non-standard ROMS. I will test the following cases specifically:

- [ ] Install Google Play (via AuroraStore) without Play Services
- [ ] Install Google Play (via AuroraStore) with Play Services

**Comment by pm4rcin** [comment]
I think the difference is that in OSMAnd and Magic Earth the location indicator (this green thing on newer Android in status bar) appears right after launching the app so apps are listening to satellites while on OM it **looks** like (not sure how the code is written) it's waiting for system to get GPS fix and only when there's a fix, indicator is shown. Not sure if it's intended or not?

**Comment by biodranik** [comment]
The problem is that the `fused` provider, reported by the system, doesn't work (when it should work!). OM requests it instead of directly requesting `gps` provider, because `fused` provider also gives the location using the network (if it is setup/enabled) until GPS gets a fix.

Many custom Android OSes break the `fused` and `network` location providers for some reason, which also breaks OM.

A proper fix is to manually always enable `gps` provider, even if the `fused` one is available, and manually filter out duplicate/network locations/disable `fused` or `network` providers when `gps` got a fix.

CC @rtsisyk

**Comment by rtsisyk** [comment]
> The problem is that the `fused` provider, reported by the system, doesn't work (when it should work!). OM requests it instead of directly requesting `gps` provider, because `fused` provider also gives the location using the network (if it is setup/enabled) until GPS gets a fix.
> 
> Many custom Android OSes break the `fused` and `network` location providers for some reason, which also breaks OM.
> 
> A proper fix is to manually always enable `gps` provider, even if the `fused` one is available, and manually filter out duplicate/network locations/disable `fused` or `network` providers when `gps` got a fix.
> 
> CC @rtsisyk

Previously, the app preferred `fused` provider and didn't enable other if fused existed. We changed this behavior a couple of months ago primarily because of completely broken `fused` provider on LineageOS. As of today, the version from F-Droid subscribes to ALL available providers, including `fused`, `network` and `gps`. If the location is provided by ANY available provider, the app will have it. However, if NONE of the providers return data - there is nothing we can do in this scenario. The suggested solution mentioned earlier, "manually always enable gps provider, even if the fused one is available" is already in place, as the GPS is always enabled.

The issue in this ticket most probably arises from the fact that Organic Maps disconnects from the location services when the app is not in the foreground on the screen. If the app is the sole user of the location services, the system shuts down the GPS and on the next switch to Organic Maps the search for GPS signal starts from the beginning. Try to enable navigation, and it will keep GPS search in the background even when you switch to other apps.

**Comment by biodranik** [comment]
@rtsisyk how can your hypothesis explain that location is properly detected in other apps?

**Comment by rtsisyk** [comment]
> @rtsisyk how can your hypothesis explain that location is properly detected in other apps?

Some other apps just keep location going in the background and don't disconnect from the location services when the user switches to other apps. Organic Maps also keeps location in the background, but ONLY when navigation is started. 

What happens typically: 

1. The user launches Organic Maps.
3. Organic Maps subscribes to GPS updates.
4. The Android system tries to do the cold start of GPS if there were no other GPS-enabled apps before.
5. In certain cases, GPS takes too long to warm up and location doesn't arrive even after 10-20 seconds or even a minute.
6. The user gets tired and switches to other apps to do something productive.
7. Organic Maps disconnects from location services in the background.
8. The Android system deactivates GPS if there are no other apps using it (this is the most important part of the story).
9. The next launch of Organic Maps starts this process from the square one. 

The presence of other apps with the background location just doesn't allow the system to disable GPS HW. No magic involved whatsoever. There is still a chance, albeit small, that there could be a bug in which Organic Maps does not subscribe to GPS at all. Please enable logs by going to Settings -> Enable logging in the menu and try to catch such moment to help me to reproduce such scenario.

**Comment by biodranik** [comment]
@rtsisyk you're missing an important point: the system "location is searched/active" indicator _is not visible_ when OM is "looking" for location, while other apps show it correctly.

**Comment by rtsisyk** [comment]
I can't reproduce this issue, sorry. Starting from a22e306212b07098c8e0eb808b58070af2bbd77a (Apr 2023) Organic Maps without Google Services subscribes to ALL available providers: `fused`, `network`, `gps` - whatever is available in the system. The missing location indicator can be the same sort of story as "fused provider which is active but returns nothing" (#4158) or `network` provider that is active but doesn't exist at the same time (https://github.com/organicmaps/organicmaps/issues/5999#issuecomment-1784235816). Or just and old issue that doesn't exist anymore.
 
Please try to reproduce this issue on the latest version and provide detailed steps with debug logs.

**Comment by rtsisyk** [comment]
BTW, on my CalyxOS (Android 13 based) I don't see the location indicator anymore no matter of the app I run. Does it still exist in Android 13+?

**Comment by pm4rcin** [comment]
> BTW, on my CalyxOS (Android 13 based) I don't see the location indicator anymore no matter of the app I run. Does it still exist in Android 13+?

It's probably bug, you should ask Calyx people because I don't recall any changes in that regard.
