### ISSUE TITLE
Document with list of commands available in search

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4229]
I think, it could be interesting to list in documentation in the repo, the list of commands available in search with description foreach commands.

Examples:

- ?gl
- ?vulkan

**Comment by endim8** [comment]
you can see all commands here: https://github.com/organicmaps/organicmaps/blob/1bbda8a756cdfcdb1ab4d54d42dd0487673a439c/map/framework.cpp#L2572-L2729

**Comment by not-available-username** [comment]
They don’t work for iOS right?

**Comment by endim8** [comment]
> They don’t work for iOS right?

They all do, except `?vulkan` (android only) and iOS instead gets `?metal` ([metal](https://en.wikipedia.org/wiki/Metal_(API)))

**Comment by Jean-BaptisteC** [comment]
I'm not sure if create new document, is necessary, somes informations is already available here
https://github.com/organicmaps/organicmaps/blob/master/docs/INSTALL.md#debug-commands
