### ISSUE TITLE
Landing page from sharing link is bland and shows no location

### ISSUE THREAD

**Issue by habi** [organicmaps/organicmaps#423]
When sharing the app the recipient is linked to https://omaps.app/im_get.
This page is very bland and shows a location in the middle of the North Atlantic Ocean.
I think it would be good if the page links to the current geolocation of the user.

**Comment by rtsisyk** [comment]
A good catch.

**Comment by rtsisyk** [comment]
@biodranik could you please fix the link? Also, `https://omaps.app/im_get` looks ugly. Could we change it to `https://omaps.app/download`?

**Comment by rtsisyk** [comment]
up

**Comment by biodranik** [comment]
@habi can you please retest? Does it work now?

**Comment by habi** [comment]
- [x] https://omaps.app/im_get now links to the Apps Store page, as well as https://omaps.app/ 
- [x] "Share My Location" prepares a nice link to share to someone which then ends up at https://omaps.app/c4BmwJJdKK (slightly edited to conceal my exact location :).
- [ ] I think it would be double-awesome if the sharing link is a [plus.code](https://maps.google.com/pluscodes/), as you already seem to be able to parse those: https://github.com/organicmaps/organicmaps/search?q=%22plus+code%22&type=code

Thanks for implementing this!
