### ISSUE TITLE
Hot sync with OSM

### ISSUE THREAD

**Issue by AvidSeeker** [organicmaps/organicmaps#4231]
New updates on OSM don't seem to reflect quickly in OM. (Try changing a name or a detail in OSM, then check OM)

Is it possible to re-download new updates of OSM?

**Comment by jpds** [comment]
The map data file updates are tied to the application updates, you can see this in the changelog: https://github.com/organicmaps/organicmaps/releases

Whole related thread over at #835.

**Comment by endim8** [comment]
Currently maps are regenerated roughly monthly, the aim is to eventually provide weekly updates (See https://github.com/organicmaps/organicmaps/issues/835)

closing as duplicate
