### ISSUE TITLE
Freeze on throttled connections during intial load, on Android

### ISSUE THREAD

**Issue by Caellian** [organicmaps/organicmaps#4234]
As my ISP is throtling my internet connection, the application (on Android) seems unresponsive/frozen on initial load.

It's stuck somewhere between ConnectionManager init and opening the download World map screen.

I experienced this several times which is why I decided to report the issue. I will look into this a bit more and include additional info, I'm just opening it for now so I remember later as I don't use the app very often.

**Comment by biodranik** [comment]
1. What is your device model?
2. What is your Android version?
3. What is your OM build? Is it FDroid?
4. There should be no networking requests on the first app start.
5. The only case for networking requests now on the non-first app launch is the case when you started downloading/updating some maps but did not finish downloading. Then OM will continue downloading on the next launch. Is it your case?

**Comment by Jean-BaptisteC** [comment]
@Caellian up

**Comment by Caellian** [comment]
I can't replicate this currently. I was literally passing through a tunnel at the time, and I'd have to do so again. My current phone isn't rooted so it'd be really tricky to "emulate" similar conditions.

I did try it 2/3 times later while I had bad connection but it didn't occur.

I'll reopen if I notice the same issue.
