### ISSUE TITLE
Defer evaluation of "eval()" in mapcss styles compilation

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#4258]
Its possible to override mapcss style rules defined earlier - either in the same file or in another via `@import()`.

There are some issues with it that makes it confusing and error-prone.

Evals like `{casing-width: eval(prop("width")+1);}` commonly used for bridge and tunnel casings seem to be evaluated immediately when encountered. Hence if the `width` will be overriden later (e.g. in another style to make the road line more thick), then width of road bridges and tunnels won't update.
E.g. that's why tram and monorail bridges are not rendered - tram/monorail line rules are defined after railway bridges "evals", hence those bridges don't get correct params.
This means also that the evals sections atm shoud be cloned for styles based on the main style, e.g. #4247.

A possible solution - defer evalutions to the end of style compilation (after all *.mapcss files were parsed and overrides resolved).

**Comment by biodranik** [comment]
Should it be done in https://github.com/organicmaps/kothic ?
