### ISSUE TITLE
[search] Tourism and Entertainment categories for POIs.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#4279]
The issue is mostly to discuss. I have doubts about:

amenity-cinema|entertainment|children
tourism-zoo|tourism|children
leisure-water_park|tourism|children
tourism-theme_park|tourism|children

Why cinema is children. Why zoo is not entertainment. Etc ...

And other entries with tourism, entertainment, children tags in data/categories.txt

**Comment by vng** [comment]
CC @endim8 @j13m126 @dvdmrtnz @Jean-BaptisteC

**Comment by biodranik** [comment]
amenity-cinema|entertainment
tourism-zoo|tourism|children
leisure-water_park|tourism|children
tourism-theme_park|tourism|children

**Comment by pastk** [comment]
Probably `entertainment` should (only?) inclue things that are regularly done by locals e.g. bars, clubs.
While leaving traveling-related entertainment to `tourism`.

However, alternatively we can define `tourism` as sight-seeing related things only? And actually its translated as "Sights" ATM! The things you mentioned are much more "entertainment" than "sights" IMO.
