### ISSUE TITLE
Integrate Harfbuzz to properly shape/render symbols and diacritics in many languages

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4281]
This meta issue wraps all related non-Latin script rendering issues on the map, that can be fixed by integrating Harfbuzz into our Drape rendering engine.

> HarfBuzz implements separate shapers for Indic, Arabic, Thai and Lao, Khmer, Myanmar, Tibetan, Hangul, Hebrew, the Universal Shaping Engine (USE), and a default shaper for scripts with no script-specific shaping model [[source](https://harfbuzz.github.io/terminology.html)].

A [detailed list of languages](https://harfbuzz.github.io/what-does-harfbuzz-do.html) supported by Harfbuzz.

There is an interesting [Maplibre discussion](https://github.com/maplibre/maplibre-native/discussions/778#discussioncomment-4902968) about the related complexities.

Should fix:
- [ ] #460
- [ ] #516
- [x] #1723
- [ ] #2597 
- [ ] #2612
- [ ] #7875

Also may be related:
- [ ] #3812
- [ ] #732

--------------------------------------

<table>
  <tr>
    <td>
      <a href="https://nlnet.nl/"><img src="https://raw.githubusercontent.com/organicmaps/organicmaps/87f50b9fdb874ffc9b905d2738774d9b16d3c5a5/docs/sponsors/nlnet.svg" alt="The NLnet Foundation" width="200px"></a>
    </td>
    <td>
      This project has been funded through NGI0 Entrust Fund. <a href="https://nlnet.nl/entrust/">NGI0 Entrust Fund</a> is established by the <a href="https://nlnet.nl/">NLnet Foundation</a> with financial support from the European Commission's <a href="https://www.ngi.eu/">Next Generation Internet programme</a>, under the aegis of DG Communications Networks, Content and Technology under grant agreement No 101069594.
    </td>
  </tr>
</table>

**Comment by strump** [comment]
Vng disabled Harfbuzz last year in commit [#fecab9f4](https://github.com/organicmaps/organicmaps/commit/93ad046f23c423a10b1c445831a0600ffecab9f4). Should we start from reverting it?

**Comment by biodranik** [comment]
That is only a small piece of the puzzle. HB should be added as a submodule first.

**Comment by biodranik** [comment]
Here are the results of the research on the current Drape rendering engine text rendering.

To simplify, the current architecture does the following:

1. Initializes fonts including white and black lists.
2. Extracts character regions for each font.
3. Gives weights for each font: character ranges explicitly listed in data/unicode_blocks.txt has the highest priority, and fonts with more chars in each char range have higher priority than those with fewer chars.
4. Each line of text is processed via ICU's log2vis first, and split if necessary into 2 lines.
5. For each char its character range is calculated, a font with a higher weight is selected, and Freetype's glyph metrics and the glyph itself are cached in the texture atlas.
6. Rendering thread uses metrics (x and y offset and advance) and cached glyphs to render a line of text.

The issue here is that the current implementation simply adds offsets and advances for each glyph while ignoring complex shapes and glyph combinations. Integrating Harfbuzz should fix that.

Here is a screenshot with a test prototype:

![telegram-cloud-photo-size-2-5407063397452862594-y](https://github.com/organicmaps/organicmaps/assets/170263/47e0699e-f830-4d51-acfe-da8bb5b58559)


Related methods are mentioned in the diagram below.

![image](https://github.com/organicmaps/organicmaps/assets/170263/c21857a9-6b0c-43ab-a380-6184fb7e9362)

**Comment by biodranik** [comment]
Great article about caveats with font rendering in Warp terminal https://www.warp.dev/blog/adventures-text-rendering-kerning-glyph-atlases

**Comment by biodranik** [comment]
The implementation in our case consists of several different parts:

1. The "single line of text" shaping function that accepts a UTF8 string with the language code of the text in this string and generates necessary glyphs and their relative offsets.
2. Extracting/passing the language code to the shaping function.
3. Refactoring of the current drape glyphs (and their offsets) caching implementation. It currently assumes that each Unicode symbol has a glyph (it's not true), and uses Unicode char code as a key for the cache.
4. Refactoring of how text is layout because it is tightly related to glyphs caching.
5. A possible improvement (need to investigate): use Freetype's SDF generation instead of sdf_image library for better performance/quality. Note: now the bitmap is rendered several times, but as it's paralleled to several threads, it takes more or less acceptable time. From experiments, rendering glyphs with freetype only on a single thread takes several times as much time, as with overhead but on several threads.

**Comment by biodranik** [comment]
With a merge of #8254 the only part of the issue is to refactor the existing rendering approach and integrate the new one that is using Harfbuzz shaping.

The main difference: the existing approach caches each glyph image together with its metrics (xyoffset, xyadvance) separately on the texture atlas. Text is rendered by a per-character basis by retrieving cached data.

The proper shaping approach can not cache metrics for each glyph separately, because the same glyph used in different contexts may have different metrics. For each line of text, its metrics (and necessary glyphs) should be calculated separately each time (and cached for reuse if necessary).

The idea is to still use the texture atlas with rendered glyphs (they don't change), and calculate/cache metrics where layout is calculated.
