### ISSUE TITLE
Long omaps and ge0 URIs crash when app is closed in iOS (Version 2022.12.18-9)

### ISSUE THREAD

**Issue by reinhart1010** [organicmaps/organicmaps#4285]
Sample link: https://omaps.app/oeyKGxYKMS/Maspion%20Square%2C%20Jalan%20Ahmad%20Yani%20No.%2073%2C%20Surabaya%2C%20East%20Java%2060238%2C%20Indonesia, generated from https://maps.reinhart1010.id/-7.31524/112.736258/?zoom=14&name=Maspion%20Square&address=Jalan%20Ahmad%20Yani%20No.%2073%2C%20Surabaya%2C%20East%20Java%2060238%2C%20Indonesia

Hi, I'm the creator of https://maps.reinhart1010.id and would like to report an issue when the Organic Maps app crashes when opening these deeplinks. To reproduce:

1. Close Organic Maps from Multitasking / App Drawer
2. Open a deeplink

This issue is reproducible on 2022.12.18-9 on iOS 16.2 on iPhone 14 Pro Max.

**Comment by biodranik** [comment]
Hi and thanks, we'll take a look. Am I right that if OM is already launched, then it works?

Btw, you can also try another format for links (that is supported on mobile devices) listed here: https://omaps.app/api

**Comment by reinhart1010** [comment]
> Am I right that if OM is already launched, then it works?

Yes.
