### ISSUE TITLE
Bus stops / Автобусные остановки

### ISSUE THREAD

**Issue by diruxke** [organicmaps/organicmaps#4287]
Пожалуйста, добавтье возможность   смотреть маршруты общественного транспорта при открытии автобусной остановки, как это реализовано в OsmAnd. Organic Maps замечательные карты, но этой функции очень не хватает.

------------------------

Please add the ability to see public transport routes when you open a bus stop, as it is implemented in OsmAnd. Organic Maps are great maps, but this feature is sorely lacking.

**Comment by Jean-BaptisteC** [comment]
Duplicate of #2175
