### ISSUE TITLE
Google Firebase tracker in build 20210508

### ISSUE THREAD

**Issue by j5k** [organicmaps/organicmaps#429]
I saw in my TrackerControl app that Organic Maps connects to Google Firebase. Fortunately the connection was blocked by TrackerControl. It seems that there is some code left over from tracker removing.

Thanks for fixing.

I'm looking forward to see the app in the F-Droid store :slightly_smiling_face:

**Comment by rtsisyk** [comment]
Hi, I can confirm that 20210508 APK from GitHub still had Crashlytics. Google version didn't. We will remove Firebase from GitHub APK in the next release.
