### ISSUE TITLE
Incorrect Order of Search Results

### ISSUE THREAD

**Issue by biicwlim** [organicmaps/organicmaps#4291]
Frequently, the order of search results in OM is unexpected.

One recent example: searching in the area of Greenville, SC (https://www.openstreetmap.org/?#map=12/34.8485/-82.3940) for the Greenville Memorial Hospital.

Searching "Greenville Hospital" shows the "Greenville Memorial Hospital Heliport" as the 24th result.
Many of the higher results seem illogical, such as "Greenville and Western" (railway), "Greenville and Western Yard" (industrial land), and "Southern Culture Hospitality Group" (company office). And numerous hospitals and animal hospitals appear that do not contain Greenville in the name, and a few which do not contain Greenville in the name and are not even located in Greenville itself, such as "mcPhail Animal Hospital" (in Mauldin).

Searching "Greenville Memorial" does much better, pulling the hospital site, "Prisma Health Greenville Memorial Hospital" as the 13th result. Some of the higher ones are related and contain the name such as the heliport and childcare center. But it still includes numerous parks, monuments, etc., which simply have "memorial" in the name and are located in the city of Greenville (e.g. "Memorial Patio" garden) over the "Greenville Memorial" Hospital.

I haven't been able to figure out a potential simple change to improve the algorithm, but someone who understands the search algorithm might be able to benefit from this example.

**Comment by Jean-BaptisteC** [comment]
Search is much better in 2024.01.09-6-Google version.

**Comment by vng** [comment]
@Jean-BaptisteC Thanks! Will add tests for this case and it works ok for now:
<img width="830" alt="Screenshot 2024-01-28 at 16 45 09" src="https://github.com/organicmaps/organicmaps/assets/175612/951499d1-6e3e-4e93-8447-c684098c703d">


Airports have big ranks ..
