### ISSUE TITLE
[FR][UI][Bookmarks]: add lists sorting options

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#430]
**OS**: Android 10.0 (LineageOS 17.1)
**App version:** version 2021.05.08-7-g19ac5fb5-Google

Changing sorting is possible only inside of the list of bookmarks. It would be nice to have sorting options for the lists themselves.

Button for changing sorting can be in upper right corner of the root of `Bookmarks` menu, and sorting should be applied to the menu and to the "list of lists" in bookmark editor

**Comment by biodranik** [comment]
Which sorting modes do you need and what is your use case?

**Comment by PetbkA** [comment]
The ones that's for bookmarks (excluding Distance) is enough:
1. Default (as I guess, sorts by date added);
2. Name.

With sorting by name it's easier to update the lists that you've created a long time ago - you will find the list by alphabet faster
