### ISSUE TITLE
Incomplete contour lines

### ISSUE THREAD

**Issue by FabianInostroza** [organicmaps/organicmaps#4300]
Hi,

I use the app a lot for MTB and hiking, in my country (Chile) there are a lot of zones without contour lines. From the Ñuble region and below the are no contour lines.
Could you please add them?

When I used maps.me I was able to generate my own maps but I hated it because the process was very slow and required the use of the whole openstreetmap data for the generation of coastlines (i'm not sure). I don't know if this has improved, maybe I should try.

**Comment by vng** [comment]
- We don't have contour line for some regions because the size will be significantly greater .. Will check it out for Chile.
- Yes, you need whole planet to generate coastlines, BUT you always can use some predefined coastlines (we don't share them, but there is no problem to do it).
- Try to follow mans for generation process, we can assist you if any ..

**Comment by biodranik** [comment]
A complete 3D terrain model will solve missing elevations issue: #4163

**Comment by boroli** [comment]
Does this mean the interval of the contour lines depends on the region, and is hard coded through the map which was downloaded?

In the area I'm currently in, I've an interval of 500m, which means those contour lines are (almost) useless for any outdoor activity.  I just try to understand, if there's an option in the app itself to increase this?!?

**Comment by biodranik** [comment]
It's hardcoded. It can be increased only when maps are generated. Maps will take way more space after that…
What's your region?

Elevation refactoring is in our plans. But it's not an easy task.

**Comment by boroli** [comment]
> It's hardcoded. It can be increased only when maps are generated. Maps will take way more space after that… What's your region?

Southern Parts of Argentina, Patagonia

**Comment by pastk** [comment]
It had been fixed for Chile and Patagonia in latest releases.
