### ISSUE TITLE
Arrow is not shown when you start OM

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4301]
<img src="https://user-images.githubusercontent.com/87148630/213285919-d4416622-cea4-4224-ab0a-ae0b9d7cb981.jpg" height="500" />

When i start OM, i need to wait some minutes before arrow is show
This tablet don't have a big performance (show map take a bit longer if i compare with my Pixel 6), can be caused by low performance ?

Samsung Galaxy Tab S6 Lite - Android 12
v2022.12.18-12-Google

**Comment by vng** [comment]
No about performance. The app is waiting for a compass fix here (or heading in GPS when moving). Looks like your tablet doesn't have compass right?

**Comment by biodranik** [comment]
According to https://www.gsmarena.com/samsung_galaxy_tab_s6_lite-10158.php, your tablet does not have a compass sensor. An arrow can be drawn only if the device's rotation/direction is known. To get it, you need a compass sensor.

While moving, the arrow direction is taken from the movement direction from GPS coordinates.

**Comment by Jean-BaptisteC** [comment]
Thanks for diagnostic :)
