### ISSUE TITLE
parking_entrance icon is different following different zoom level

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4302]
<img src="https://user-images.githubusercontent.com/87148630/213287641-d56155ab-7ed4-4837-9f86-45d43511f4cd.png" height="500" />
<img src="https://user-images.githubusercontent.com/87148630/213287495-5a572900-f0a8-418a-95af-49389ad16d28.png" height="500" />

Sometimes i have parking_entrance icon and sometimes i have entrance icon, in most case i have entrance icon

https://www.openstreetmap.org/#map=19/49.12163/6.17408

Pixel 6 - Android 13
v2022.12.18-12-Google
CC @endim8

**Comment by endim8** [comment]
surprisingly, there are 2671 `amenity=parking_entrance`+`entrance=*` so yeah this would be good to fix

**Comment by vng** [comment]
"parking_entrance" priority should be greater than "entrance" priority in all zoom levels.

**Comment by Jean-BaptisteC** [comment]
Fixed
