### ISSUE TITLE
Update strings about max level in editor

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4309]
Recently we have increase max level about building https://github.com/organicmaps/organicmaps/pull/4215 but we have forgotten to update strings in editor

Update here for android https://github.com/organicmaps/organicmaps/blob/81c1d08024b950220c718ffab639251ea6dda00d/android/src/app/organicmaps/editor/EditorFragment.java#L425
Check on IOS

CC @biodranik

**Comment by octopols** [comment]
Hey, I would like to work on this issue. Can you please assign it to me?
