### ISSUE TITLE
Can’t lookup a POI

### ISSUE THREAD

**Issue by matic13** [organicmaps/organicmaps#4320]
Hello,

for some reason I can’t look up this restaurant by name in OM. When I type the name into the search box it’s as if it didn’t exist.

https://omaps.app/84EY7qG3NA/Pop%27s_placeom://84EY7qG3NA/Pop%27s_place

https://www.openstreetmap.org/node/4284221389

Also, when you zoom in (in OM), sometimes this POI’s icon is visible and sometimes it's hidden.

Please can you check?

Thanks

**Comment by vng** [comment]
Hm, what did you enter in search? Where is your current viewport and locale? Is Ljubljana city downloaded?
Please, provide more details or screenshot, I can't reproduce the problem.

POI icons may be hidden to avoid mess on map rendering. There is one more restaurant nearby that can _displace_ icon.

**Comment by matic13** [comment]
> Hm, what did you enter in search? Where is your current viewport and locale? Is Ljubljana city downloaded? Please, provide more details or screenshot, I can't reproduce the problem.
> 
> POI icons may be hidden to avoid mess on map rendering. There is one more restaurant nearby that can _displace_ icon.

1. Yes, the city is downloaded.
2. I simply type the name of the restaurant and it won’t find it. See attached screenshot.

Thanks!
![Uploading 92C4398B-7F46-4334-9180-EA2D141D92C3.jpeg…]()

**Comment by vng** [comment]
Looks like some locale problem. Got it. There are also "Pop's pizza" nearby and search results are definitely inconsistent.
They should be together with "pop's" search.

**Comment by matic13** [comment]
> Looks like some locale problem. Got it. There are also "Pop's pizza" nearby and search results are definitely inconsistent.
> They should be together with "pop's" or "pops" search.

Yes, exactly. Both should show uo when you start typing “pop”, but for some reason only “Pop’s pizza” shows up.

**Comment by matic13** [comment]
> Looks like some locale problem. Got it. There are also "Pop's pizza" nearby and search results are definitely inconsistent.
> They should be together with "pop's" or "pops" search.

I noticed that Pop’s place only shows up on the list if you type “pop”:
![Uploading 53FF55E1-5FB0-4B88-8F09-4BD463D6AA3E.jpeg…]()

**Comment by Jean-BaptisteC** [comment]
@matic13 can you retry with latest version?
