### ISSUE TITLE
Consider removal of "Add business" button in favor of "Add a place"

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4321]
> when I press on a building there is the string [placepage_add_business_button] en = Add business
when I long press anywhere else there is the string [placepage_add_place_button] en = Add a place to the map

> both seem to open the editor in the same way, I don't see why we need two different strings, and moreover, a building does not necessarily contains a business (school, amenity, association, etc...)

_Originally posted by @Kazing in https://github.com/organicmaps/organicmaps/pull/4292#discussion_r1082668126_

**Comment by jaivsh** [comment]
Hi, I'm doing this one!

**Comment by endim8** [comment]
> Hi, I'm doing this one!
You can use `./tools/unix/translate_categories.sh "Add a place"` to generate translations :)

**Comment by privatemaker** [comment]
This is a good idea, definitely do this!!
