### ISSUE TITLE
Search results displayed on map ≠ search results displayed on list 

### ISSUE THREAD

**Issue by Outlet2048** [organicmaps/organicmaps#4325]
When I search for a burger chain called burgerme I was able to find all the stores (thanks to my amazing osm editing)
When I then also wanted to find them on the map to see which one was most convenient to reach by train, I noticed that the map view reminds me more of the old search results many many updates ago

See comparison Screenshots

![Screenshot_2023-01-23-18-17-22-98_75d0290a7c00525acd83c0ab8700d64c.jpg](https://user-images.githubusercontent.com/72819077/214106088-1947d65a-0534-46af-bbb3-1b2ab3b2f306.jpg)
List /\
Irrelevant items in map view \/
![Screenshot_2023-01-23-18-17-27-87_75d0290a7c00525acd83c0ab8700d64c.jpg](https://user-images.githubusercontent.com/72819077/214106137-bb65e0d2-4233-4c67-891a-693066732380.jpg)
![Screenshot_2023-01-23-18-17-30-78_75d0290a7c00525acd83c0ab8700d64c.jpg](https://user-images.githubusercontent.com/72819077/214106163-f423689e-4f56-4242-998d-a857115c46c7.jpg)

**Comment by endim8** [comment]
I think this is because display on map shows all matched POI regardless of how well it matches. These results could be at index 100 in the search results but is still displayed because it's geographically closer

**Comment by AlertSubject** [comment]
> I think this is because display on map shows all matched POI regardless of how well it matches. These results could be at index 100 in the search results but is still displayed because it's geographically closer

Hm, but that makes it more or less useless
The search results in the list were exactly what I was searching for
And then clicking the map completely no longer shows me those same POIs. And therefore I cannot determine distance to me / public transport, etc etc

**Comment by endim8** [comment]
> Hm, but that makes it more or less useless The search results in the list were exactly what I was searching for And then clicking the map completely no longer shows me those same POIs. 

Yeah definitely, was just trying to explain why it was happening :)

**Comment by vng** [comment]
Like https://github.com/organicmaps/organicmaps/issues/4190
