### ISSUE TITLE
Gradle error while building the code

### ISSUE THREAD

**Issue by varad64** [organicmaps/organicmaps#4332]
```
Build file 'E:\OrganicMaps\organicmaps\android\build.gradle' line: 112

A problem occurred evaluating root project 'android'.
Process 'command 'C:\Program Files\Git\bin\bash.exe'' finished with non-zero exit value 1
```

Getting the above error when building the project on Windows 10.
I have run the configure.sh file before building the project and can confirm that bash has been added to the PATH variable.

I have been trying to figure out why this is the case, but no breakthrough so far.
Any help appreciated.

Thanks in advance!

**Comment by biodranik** [comment]
It is hard to guess what is broken in your environment without any additional data.

You may try to run bash manually with params from build.gradle, e.g. `bash ../tools/unix/version.sh android_code`

**Comment by Jean-BaptisteC** [comment]
@varad64 problem is solved ?
