### ISSUE TITLE
Can't locate myself via GPS (even with Android method)

### ISSUE THREAD

**Issue by d4f5409d** [organicmaps/organicmaps#4339]
Organic Maps can't find my location. Stable and Beta versions both affected (OSMAnd don't, this is an Organic Maps issue)

OnePlus 8, Android 13, GPlay Services disabled.

Stable: 2022.12.18-12-FDroid
Beta: 2023.01.25-18-Google-beta

**Comment by d4f5409d** [comment]
Hell lot weird. I swear to god, when I reported this issue I still encountered it. Somehow it is now working. It wasn't working for one whole day and at the end of the day, now works! LOL
 real weird.

**Comment by Altonss** [comment]
This might maybe be related to : https://github.com/organicmaps/organicmaps/issues/4223

**Comment by biodranik** [comment]
Any temporary strong EMF/RF source nearby?

**Comment by d4f5409d** [comment]
> Any temporary strong EMF/RF source nearby?

But everywhere?

**Comment by d4f5409d** [comment]
> Do Google Play Services work?
> 

I think my issue description makes this clear
(no)

But I can't reproduce the issue anymore myself.
