### ISSUE TITLE
Map cut off at Fiji and some land is not visible

### ISSUE THREAD

**Issue by simonschaufi** [organicmaps/organicmaps#4347]
It's not possible to move the map beyond Fiji and there is definitely some land not visible and it's also not visible on the far left side of the map.

![Screenshot_20230128-112451_Organic Maps](https://user-images.githubusercontent.com/941794/215218938-ca1487b2-508f-40aa-93f4-fcee8acf4090.jpg)

See Koro Se... the rest is missing. 

If you zoom in a bit more, you can clearly see that the map is cut off.

![Screenshot_20230128-113659_Organic Maps](https://user-images.githubusercontent.com/941794/215219564-a3683443-11fe-4db0-837d-7807f8b48c3b.jpg)

**Comment by biodranik** [comment]
See #1373
