### ISSUE TITLE
Kitchen type "regional" is duplicated

### ISSUE THREAD

**Issue by simonschaufi** [organicmaps/organicmaps#4348]
There are 2 entries for the kitchen type "regional" in the German version.

**Comment by Jean-BaptisteC** [comment]
We have two strings "regional" because we have local cuisine and regional cuisine
Do you think we can improve this with better translations ?

**Comment by simonschaufi** [comment]
I would translate it with "Regional" and "Lokal" but I have no idea what lokal actually means concerning food.

**Comment by Jean-BaptisteC** [comment]
https://wiki.openstreetmap.org/wiki/FR:Key:cuisine

**Comment by biodranik** [comment]
Is their meaning the same? Can we simplify it and stick to one of the two?

**Comment by biodranik** [comment]
cuisine | local | Food originating from the area the restaurant is located in. Use a more specific value if possible. | 3 990 |   | 3 990
-- | -- | -- | -- | -- | --




cuisine | regional | Food originating from the region the restaurant is located in. Use a more specific value if possible. | 80 874 |   | 80 874
-- | -- | -- | -- | -- | --

**Comment by simonschaufi** [comment]
![IMG_20230128_230419_779](https://user-images.githubusercontent.com/941794/215260389-ea6abcd1-0081-40cf-abc1-1e38a240922d.jpg)

This is what maps.me has. I suggest to translate it the same way for consistency.
