### ISSUE TITLE
[Android] Bad Bookmark's color picker fragment.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#4353]
Android 13 (API 33), SM-S908E.
Locale: iw_IL.

![Screenshot_20230128_074516_Organic Maps](https://user-images.githubusercontent.com/175612/215266734-09919717-2a14-4192-960d-c0a65831416d.jpg)

**Comment by jaivsh** [comment]
Hello, I would like to go after this one please?

**Comment by vng** [comment]
@jaivsh Do you want to fix this issue? Feel free and push the PR with a fix.

**Comment by biodranik** [comment]
@Jean-BaptisteC is it easily fixable by using material dialogs?

**Comment by Jean-BaptisteC** [comment]
Problem is caused by alignment of text because in this language (like in arabish), text start at the right

**Comment by rtsisyk** [comment]
Does anyone work on a fix?

**Comment by Jean-BaptisteC** [comment]
No
