### ISSUE TITLE
my location icon change, if moving while try connecting to the gps

### ISSUE THREAD

**Issue by Monirzadeh** [organicmaps/organicmaps#4376]
**Describe problem:**
If you are not connect to GPS, my location icon is similar this
![af1cd515-1c40-43b7-8416-b19027712e4c png](https://user-images.githubusercontent.com/25131576/215578705-b6d67525-8e84-4ed4-bf8e-3121ee3b07f4.png)(mode1)
If you try to connect GPS(not connected yet) icon is like this
![f5c3d52e-05e5-480b-9081-a0eb98b55724 png](https://user-images.githubusercontent.com/25131576/215578942-318a2e62-e9ad-498f-b24e-bd3914e5fc5d.png) (mode2)

Now if you try to connect GPS (mode2) than move in map, zoom in or zoom out icon of my location immediately change to mode1.

**What expected:**
Icon be in mode2 until it connected or canceled with user.
It should not be affected with user interaction with map.

**Additional note:**
I am not sure that organic map stop trying to connect GPS in background, or it is just a bug in UI.
Update: It happens on android and Linux as I tested (other platform not test)

**Comment by biodranik** [comment]
@Monirzadeh is your GPS enabled on the device? Does it actually find satellites after some interval?

CC @rtsisyk

**Comment by biodranik** [comment]
So the detection actually works. It is the icon that should not change on drag. @rtsisyk can you please fix it? I also saw a similar scenario when GPS was not detected immediately (cold start for example).

**Comment by jakoblm** [comment]
I can confirm this behavior. The location search is apparently interrupted as soon as I move the map with my fingers or zoom. See also other issue: https://github.com/organicmaps/organicmaps/issues/4540. This is very annoying.

**Comment by rtsisyk** [comment]
This is drape's MyPositionController behavior rather than an Android bug. The location search continues despite showing the different icon.

**Comment by biodranik** [comment]
The icon should not change when the map is dragged, it should be fixed to avoid users' confusion and unnecessary support requests.
