### ISSUE TITLE
Additional bookmarks suggestions

### ISSUE THREAD

**Issue by ioctl-user** [organicmaps/organicmaps#4381]
Please consider implementing the following features:

- **Sorting by tags** -- add tags to bookmarks. Can be used select bookmarks for one country, for example.
- **Implement bookmarks directories.** Can be used to organize bookmarks, for example, by creating directory for each continent or country.

**Comment by biodranik** [comment]
Aren't there already similar issues?

**Comment by ioctl-user** [comment]
There are issues like that, but not exactly. You was asking me creating new one.

**Comment by biodranik** [comment]
Thanks, let's cross-reference all that is related to have a full picture.

**Comment by ioctl-user** [comment]
The second one: https://github.com/organicmaps/organicmaps/issues/1066

**Comment by Friptick** [comment]
@biodranik You're right, this is overlapping and vague, so many open issues makes finding stuff hard. Just a suggestion, but perhaps you should close a few like this one.

**Comment by biodranik** [comment]
It would be great if our community help us to better organize issues, and have a full picture on what's going on. We want to create the best maps, with the best UX, so any help is appreciated.

**Comment by Friptick** [comment]
Well if I were a moderator I would begin by deleting this whole thread :) Can't imagine how you stay organized with 1.4k open issues.

Slightly off-topic: I would also recommend that this project be clearer about what distinguishes it from the obvious alternative. The pitch is very similar to Osmand's, but Osmand is a much, much, more featureful app than Organic Maps. I know anecdotally that Maps.me is (or was) quite well-known among normies but you can't trade off the Maps.me association forever. In my past experience, when users discovered that Osmand was Maps.me with ten times more features, they often moved.

My selfish motivation is for Organic Maps to fix bookmarking, which is a rare weakness of Osmand (but even with that, OM is still behind, so I can't move yet). More generally, I would suggest you take the angle of "backpacker" to Osmand's "sportsperson" but that's just my 2 cents.

None of this is a criticism! Your work is really obviously appreciated by many already and hopefully it will reach even more.

**Comment by ioctl-user** [comment]
Wait, please. In this issue are original bookmark feature requests.

**Comment by Friptick** [comment]
My suggestion then is that you split the "Additional suggestions" of this issue into two separate issues, and for each one summarize  the suggestion **in the title**. The developers are never going to get to anything with 1400 "issues" like this when they have to click to see what it is and then discover that there are 2 issues hidden inside.

**Comment by ioctl-user** [comment]
Splitted to 2 new requests.
