### ISSUE TITLE
Show major rivers on all zoom levels

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#4389]
![signal-2023-02-02-104828](https://user-images.githubusercontent.com/26939824/216304828-3a10f62c-0798-4b7e-a1f6-c0e986ecf397.png)

**Comment by aronkvh** [comment]
the title could be:
Always show major rivers on all zoom levels

I noticed most rivers get broken up /hidden if you zoom out.

**Comment by biodranik** [comment]
That's not an easy task. Somehow rivers should be marked as "major ones", and their smaller/narrower parts should not be excluded by the simplification algorithm (otherwise they can look like a dashed line).

**Comment by pastk** [comment]
Closing in favor of #5717.
