### ISSUE TITLE
Desktop application

### ISSUE THREAD

**Issue by elandorr** [organicmaps/organicmaps#4394]
First of all, thank you for your efforts!

Your mission makes me smile:

- offline! RARE
- no data collection
- relatively lightweight from the looks of it

But I don't use a smartphone. It'd be great if you considered a desktop program. I understand porting it is absolutely not trivial, so I don't expect anything.

Is there a decent offline mapping program for Linux?

Ideally I'd be looking to mark points of interest, with notes, draw routes and such. Like on... the absolutely unacceptable Google products. I tried QGIS, but it cannot handle large datasets. Your mobile program apparently handles that fine, with varying levels of detail. QGIS dies even on a small region, as it tries to load everything to RAM at once. Even if you had a terabyte of RAM, it doesn't seem to handle metadata like you do.

Thanks for fighting the offline fight! 3/4/5/whatever G must die. It's great to see a program with some common sense.

This is even a social cause: 'Classic' physical maps are unaffordable for regular people nowadays. Not to mention the physical space a collection of maps takes up. A laptop? Everyone is forced under threat of death to have one. So an offline map with possibly even battery-efficient lightweight vector maps would be a fantastic addition. One can plan out a route oldschool and then write the important drawn stuff on paper with a physical pen. A real tool, no gimmicks.

A 'smartphone' is unfortunately no option, if one is very serious about the cause. The only device that comes across as even remotely 'acceptable' is the librem usa, and that thing costs 3000 bucks, which makes it only for the 1%.

I see you list a 'flathub' package, but judging from the screenshots that's also for mobile. I can't seem to find a regular desktop build, please excuse, if there should be one.

Cheers

**Comment by biodranik** [comment]
Organic Maps works on Linux and Mac OS X (Windows can be added too), we develop and test our code there. The app is not targeted at the end users, but it is possible to do (there was already a discussion/issue about it.

The desktop version is available on Flathub.

**Comment by elandorr** [comment]
I didn't know the flathub package ran on ordinary desktop, the screenshots look mobile, so I thought it may be for some ubuntu touch phone. flatpack won't ever touch my system, so I didn't try. But it seems to be indeed just for testing and not an actual desktop program given the same UI. 

Here's a vote for exploring desktop more, if that ever becomes an option for you. There is literally no one else with the same mission of being offline/no data collection. 

Anyone finding this thread via search:

QGIS is far too unwieldy and for everyone not completely insane, not an option. It requires a supercomputer for a small region. You can manually start filtering before it crashes, but that requires such absurd amounts of time and effort, especially on a chaotic dataset like OSM (many naked fields with just a name, something 'organic' will also suffer from), you'll practically have hand-drawn a map at this point.

Seems most pragmatic to carefully use google spyware on Tor to find what you need to find, and draw your own bare map by hand on physical paper. In real life, you only need some orientation help and landmarks, anyway.

If you have very simple needs, KDE's Marble can download tiles. It's neither fast nor handles tracks/exports/other GIS essentials, but it's a way to browse OSM offline, and the only maintained one that you can actually run in 5mins. Can't pre-download an entire region though, as it fetches tiles one by one, which is limited.

**Comment by biodranik** [comment]
The screenshots on Flathub are from Android version. With your help and the help of other users and contributors we can improve the desktop UI and make it usable/helpful not only for our developers ;-)

**Comment by rizajur** [comment]
@biodranik sadly is the flatpak version kinda broken at least for me i run instantly into a system freeze when running it:

`LOG TID(1) INFO     4.04e-06 qt/main.cpp:122 main(): Organic Maps 2023.03.02-1-fd7b293f-dirty-Linux started, detected CPU cores: 12
Gtk-Message: 16:14:55.388: Failed to load module "xapp-gtk3-module"
Gtk-Message: 16:14:55.406: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:14:55.407: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
LOG TID(1) INFO    0.0612279 platform/string_storage_base.cpp:26 StringStorageBase(): Settings path: /home/user/.var/app/app.organicmaps.desktop/config/OMaps/settings.ini
LOG TID(1) INFO    0.0767218 storage/storage.cpp:624 LoadCountriesFile(): Loaded countries list for version: 230227
LOG TID(1) WARNING  0.148016 indexer/categories_holder.cpp:109 ProcessCategory(): Invalid type when parsing the line: area:leisure-track
LOG TID(1) INFO     0.164779 search/processor.cpp:215 SetPreferredLocale(): New preferred locale: en
LOG TID(2) WARNING  0.167222 search/geocoder.cpp:736 CacheWorldLocalities(): Can't find World map file.
LOG TID(2) WARNING  0.167245 search/cities_boundaries_table.cpp:49 Load(): Can't find World map file.
LOG TID(2) WARNING   0.16725 search/processor.cpp:341 LoadCitiesBoundaries(): Can't load cities boundaries
LOG TID(1) INFO      0.18248 storage/storage.cpp:959 RegisterLocalFile(): Found file: World in directory:  with size: 44007849
LOG TID(1) INFO     0.182493 storage/storage.cpp:959 RegisterLocalFile(): Found file: WorldCoasts in directory:  with size: 8751743
LOG TID(1) INFO      0.18258 map/framework.cpp:147 RegisterMap(): Loaded World map, of version 230227
LOG TID(1) INFO     0.182603 map/framework.cpp:147 RegisterMap(): Loaded WorldCoasts map, of version 230227
LOG TID(1) INFO     0.183903 map/framework.cpp:378 Framework(): System languages: en_US.UTF-8
LOG TID(1) WARNING   0.18395 power_management/power_manager.cpp:71 Load(): Cannot read power manager config file. Exception: /home/user/.var/app/app.organicmaps.desktop/config/OMaps/power_manager_config; Read; No such file or directory
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
LOG TID(1) INFO     0.252779 drape_frontend/visual_params.cpp:56 Init(): Visual scale = 1 ; Tile size = 1024
LOG TID(3) INFO     0.252913 drape_frontend/backend_renderer.cpp:679 Do(): Start routine.
LOG TID(3) INFO      0.25293 drape_frontend/backend_renderer.cpp:647 OnContextCreate(): On context create.
LOG TID(4) INFO     0.253188 drape_frontend/frontend_renderer.cpp:2407 Do(): Start routine.
LOG TID(4) INFO     0.253205 drape_frontend/frontend_renderer.cpp:2324 OnContextCreate(): On context create.
LOG TID(3) INFO     0.255108 drape/support_manager.cpp:35 Init(): Renderer = AMD Radeon RX 5700 XT (navi10, LLVM 15.0.7, DRM 3.49, 6.1.0-5-amd64) | Api = OpenGLES3 | Version = 4.6 (Core Profile) Mesa 22.3.5 (git-6570a15662)
LOG TID(3) INFO     0.255152 drape/support_manager.cpp:79 Init(): Max line width = 2048 | Max texture size = 16384
LOG TID(3) INFO     0.255384 platform/platform.cpp:214 GetFontNames(): Available font files: [9: 00_NotoNaskhArabic-Regular.ttf 00_NotoSansThai-Regular.ttf 01_dejavusans.ttf 02_droidsans-fallback.ttf 03_jomolhari-id-a3d.ttf 04_padauk.ttf 05_khmeros.ttf 06_code2000.ttf 07_roboto_medium.ttf ]
LOG TID(2) INFO     0.260852 search/processor.cpp:339 LoadCitiesBoundaries(): Loaded cities boundaries
LOG TID(4) INFO     0.261123 shaders/program_manager.cpp:68 InitForOpenGL(): VTF enabled
LOG TID(3) WARNING  0.273001 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_tram-s
LOG TID(3) WARNING  0.273015 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_tram-m
LOG TID(3) WARNING  0.273019 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_bus-s
LOG TID(3) WARNING  0.273022 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_bus-m
LOG TID(3) WARNING  0.273024 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_ferry-s
LOG TID(3) WARNING  0.273027 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_ferry-m
LOG TID(3) WARNING   0.27303 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_cable_tram-s
LOG TID(3) WARNING  0.273033 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_cable_tram-m
LOG TID(3) WARNING  0.273036 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_aerial_lift-s
LOG TID(3) WARNING  0.273039 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_aerial_lift-m
LOG TID(3) WARNING  0.273042 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_funicular-s
LOG TID(3) WARNING  0.273044 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_funicular-m
LOG TID(3) WARNING  0.273047 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_trolleybus-s
LOG TID(3) WARNING  0.273049 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_trolleybus-m
LOG TID(3) WARNING  0.273052 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_air_service-s
LOG TID(3) WARNING  0.273055 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_air_service-m
LOG TID(3) WARNING  0.273058 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_water_service-s
LOG TID(3) WARNING  0.273061 drape/texture_manager.cpp:517 GetSymbolRegion(): Detected using of unknown symbol  transit_water_service-m
amdgpu: amdgpu_cs_query_fence_status failed.
amdgpu: The CS has been rejected (-125), but the context isn't robust.
amdgpu: The process will be terminated.
malloc(): unaligned fastbin chunk detected`

**Comment by adventure-tense** [comment]
I am using the Linux, MacOS, and iOS versions. The UI on the Apple platform is very nice. I hope the Linux version gets that same UI upgrade.

**Comment by biodranik** [comment]
@rizajur can you please check the latest version?

@elandorr as OM already works on Linux, and there are already plans on improving its UI, can this issue be closed?

**Comment by kNsja5w** [comment]
The iOS version works perfectly on macOS, no issues or errors whatsoever. Is there any chance of having a proper desktop version as .dmg available soon? There's no real competitor for Apple Maps on macOS, especially not Open Source.
Cheers!

**Comment by RedAuburn** [comment]
closing this as there isn't really anything actionable that isn't already in other issues
