### ISSUE TITLE
Icons before field move when error input message is shown

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4395]
How reproduce:
- Start OM
- Select POI and open editor
- Update social fields with wrong url--> red error message is shown and icon about social network has moved

I think it's better, if icons before fields is fixed

**Comment by Jean-BaptisteC** [comment]
CC @arnaudvergnet

**Comment by satvik2131** [comment]
Hi can you please help me with the second point like I don't understand what exactly needs to be done , I have searched for a point where I want to go and where is the editor , are you talking edit place ?
