### ISSUE TITLE
Rendering of an outline for pedestrian / bike bridges

### ISSUE THREAD

**Issue by gvellut** [organicmaps/organicmaps#4400]
**Is your feature request related to a problem? Please describe.**

I would like to see the rendering of an outline for pedestrian / bike bridges, in a similar way to car bridges (and to what the standard OSM rendering is doing). It concerns paths with tags:

| bridge     | yes  |
| highway  | path |

Currently there is no indication there is a bridge: It would be useful for smaller bridges, where it is unclear if there is indeed a bridge or if it is a ford (there is a tiny dot rendered for fords but the data is not very consistent and it is often missing).

**Describe the solution you would like**

An outline similar to the rendering of car bridges is drawn.

**Describe alternatives you have considered**

For example:

OM
![Screenshot_20230205_124047_Organic Maps](https://user-images.githubusercontent.com/3685/216816858-949c8305-6043-4bd9-ad83-1309fbe5fef8.jpg)

OSM
<img src="https://user-images.githubusercontent.com/3685/216817014-5dda5fa8-f46e-4c2a-8f6c-75f1004a2b75.png"  width="350">

(from https://www.openstreetmap.org/#map=18/45.97650/6.30859)

**Additional context**

There are somewhat related issues with #3023 and #3322 but they are more about rendering a bridge area (for large bridges).

**Comment by pastk** [comment]
Some bridge styles for some reason are half-defined and hence not working. There are TODO comments for that in `data/styles/clear/include/Roads.mapcss`.
