### ISSUE TITLE
POI filter by floors/levels

### ISSUE THREAD

**Issue by Zavgor1990** [organicmaps/organicmaps#4409]
Good afternoon.
If possible, I would like to see the implementation of the POI filter by floors/levels. This would be convenient, for example, when viewing points in shopping complexes, where there may be 2-3 points in the same coordinate, but each on its own floor.
![Screenshot_2023-02-06-17-03-21-016_ru dublgis dgismobile](https://user-images.githubusercontent.com/124589977/216991728-1b8723e3-785e-4e69-8d0e-0d8f887b6783.jpg)
![Screenshot_2023-02-06-17-03-25-138_ru dublgis dgismobile](https://user-images.githubusercontent.com/124589977/216991764-0ae8b6a6-44a2-4f77-a170-8b19650189e5.jpg)

**Comment by dvdmrtnz** [comment]
Related to https://github.com/organicmaps/organicmaps/issues/1308
