### ISSUE TITLE
No F-Droid release

### ISSUE THREAD

**Issue by TheBiostarfly** [organicmaps/organicmaps#4419]
**Describe the issue**
I did not receive the newest update through F-Droid. The latest version is still the December update. Is there an  problem with the updates? 
Thany you for your help!

**Comment by biodranik** [comment]
There is a problem with FDroid build system. There is no problem with Organic Maps. They are solving build issues now.

We also plan a new release soon.

**Comment by TheBiostarfly** [comment]
Thank you for clarifying! Gonna just close this then.
