### ISSUE TITLE
Voice navigation not working

### ISSUE THREAD

**Issue by letkan** [organicmaps/organicmaps#444]
V 2021-05-08 (Beta)
I'm on LineageOS (patched for TTS) with MicroG and can't turn Voice instructions On (disabled) although I have Google TTS and RHVoice installed. I've tested with Here Maps beta which requires TTS and it works as expected.
Also with Google Play Services enabled the app can't find my location, if I disable it, it finds it immediately.

**Comment by biodranik** [comment]
Can you please record and share separate `adb logcat` logs while trying to use TTS  and while trying to use location services?

**Comment by letkan** [comment]
> Can you please record and share separate `adb logcat` logs while trying to use TTS and while trying to use location services?

Will do

**Comment by letkan** [comment]
[GooglePlayServ.txt.zip](https://github.com/organicmaps/organicmaps/files/6527929/GooglePlayServ.txt.zip)
[TTS.txt.zip](https://github.com/organicmaps/organicmaps/files/6527931/TTS.txt.zip)

**Comment by letkan** [comment]
On an AOSP based rom (same MicroG + TTS) voice navigation works.
But... speech rate (English) is ridiculously fast and adjustments in Android Settings have no effect. Also the volume is lower then, say, some music I'm playing in the background, it should be the same.

**Comment by SamHawkens** [comment]
I am using lineageos 18.1 with espeak-ng installed from f-droid. TTS works fine with other apps, but in organic maps voice navigation cannot be enabled. The switch is grayed out ("not available").

**Comment by biodranik** [comment]
@SamHawkens can you please also kill the app and then record/share your adb logcat while launching Organic Maps and going into that settings screen?

**Comment by SamHawkens** [comment]
@biodranik here is the log. It shows a line
`TtsPlayer: Failed to initialize TextToSpeach`
Hope you can make something out of it. Thanks a lot for checking.
[organicmaps_espeak-ng.log](https://github.com/organicmaps/organicmaps/files/6569515/organicmaps_espeak-ng.log)

**Comment by biodranik** [comment]
Does LineageOS correlate somehow with the recent Android 11? If yes, then I suspect why it doesn't work.

**Comment by SamHawkens** [comment]
Yes it does. lineageos 18 is based on android 11.

**Comment by biodranik** [comment]
Then the fix should be easy.

> Apps targeting Android 11 that use text-to-speech should declare TextToSpeech.Engine.INTENT_ACTION_TTS_SERVICE in the queries elements of their manifest:

https://developer.android.com/reference/android/speech/tts/TextToSpeech

**Comment by letkan** [comment]
Waiting for the next release, then.

**Comment by biodranik** [comment]
CC @rtsisyk

**Comment by SamHawkens** [comment]
thanks a lot, that solved my problem. Now working with espeak-ng on lineageos 18 (android 11)
