### ISSUE TITLE
Don't navigate through locked gates

### ISSUE THREAD

**Issue by aronkvh** [organicmaps/organicmaps#4442]
OM offers a navigation route through gates that are marked `locked=yes`.
https://www.openstreetmap.org/node/10084369862
![IMG_20230211_130046](https://user-images.githubusercontent.com/57704946/218258738-731e454f-f513-4b73-83ae-5b041abbbd89.jpg)

**Comment by aronkvh** [comment]
In another instance it navigated through 
```
barrier=gate
access=customers
```

**Comment by aronkvh** [comment]
The best ux for me would mean showing the access tag value for gates and showing a marker similar to unpaved roads where you can select if you have access to a gate. but I understand knowing that when navigating is a rare situation

**Comment by Misalf-git** [comment]
Same problem for me. While I would think a `highway=track` that has any kind of vehicle barrier shouldn't be used for car routing in the first place (maybe depends on local law or I'm just wrong), it's even used if it's **blocked** by something like
```
barrier=swing_gate
bicycle=yes
foot=yes
locked=yes

```

IMO, `locked=yes` should be treated as impassable unless explicitely ignored by the user.

**Comment by vng** [comment]
barrier=swing_gate adds a big penalty for car routing. Could you please give an example of a bad route?
The only possible thing for now - if there are no other alternatives except passing through a barrier.

**Comment by vng** [comment]
This issue is related to pedestrians only. Yes, historically assumed that pedestrians can pass through gates, but bicycle and car routing have penalties. Moreover, we got some claims to allow bicycles to pass through _regular_ gates without penalties also.

Now we don't distinguish _locked_ or _usual_ gates.

https://github.com/organicmaps/organicmaps/issues/713

**Comment by Misalf-git** [comment]
OK, so the algorithm already avoids gates, if at all possible, and your point holds true no matter what examples I would give (I'd need to find one not in my backyard).
Then the actual issue might be letting the user know there is a (locked) gate.

**Comment by vng** [comment]
Implemented in https://github.com/organicmaps/organicmaps/commit/db97c5d207b3e28a93ac252e83cfe567fed1af7b
