### ISSUE TITLE
landuse=orchad overlaps natural=wood

### ISSUE THREAD

**Issue by ivanbarsukov** [organicmaps/organicmaps#4447]
landuse=orchad overlaps natural=wood

Example: https://www.openstreetmap.org/way/83224001

![Screenshot_20221201-144607](https://user-images.githubusercontent.com/14816075/218270688-07302804-e059-424a-a681-fb510519c788.png)

![Screenshot_20230211_230016](https://user-images.githubusercontent.com/14816075/218270812-2a3f1399-25a8-430e-a786-1ff9200e2b63.png)

**Comment by pastk** [comment]
Orchard fills have higher priority than forests'. It makes sense as orchards are usually smaller than forests. So this is as intended.

In this case there is a smaller patch of forest over a larger orchard - it could be improved changing to area-sized based fill priorities, see #2170.

**Comment by pastk** [comment]
Should've been improved by #4581

**Comment by ivanbarsukov** [comment]
> Should've been improved by #4581

I confirm, fixed

**Comment by pastk** [comment]
> I confirm, fixed

Could you provide a screenshot please?
I'm curious because it looks like a more rare case of partial intersection of areas, might be similar to a difficult case of a hospital and a forest in #4581

**Comment by ivanbarsukov** [comment]
> > I confirm, fixed
> 
> Could you provide a screenshot please? I'm curious because it looks like a more rare case of partial intersection of areas, might be similar to a difficult case of a hospital and a forest in #4581

Sure 

![image](https://user-images.githubusercontent.com/14816075/224525181-e988f5df-7060-4e10-9dae-475219be9e07.png)
