### ISSUE TITLE
translate_categories.sh output is incompatible with strings.txt

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#4451]
I run `./tools/unix/translate_categories.sh` to translate a string:
```
./tools/unix/translate_categories.sh "• No ads, no tracking, no data collection"
```

It outputs the full screen of text:

```
[REDACTED]
    fr:• Pas de publicité, pas de pistage
    he:םינותנ ףוסיא אלל ,בקעמ אלל ,תועדומ אלל •
    hu:• Nincs nyomkövetés, nincsenek hirdetések
    id:• Tanpa ikla, tanpa pelacakan
[REDACTED]
```

I have to replace `:` with ` = ` and paste for strings.txt every time:

```
[REDACTED]
    fr = • Pas de publicité, pas de pistage
    he = םינותנ ףוסיא אלל ,בקעמ אלל ,תועדומ אלל •
    hu = • Nincs nyomkövetés, nincsenek hirdetések
    id = • Tanpa ikla, tanpa pelacakan
[REDACTED]
```

Is `translate_categories.sh` a recommended way of generating translations for strings.txt? If yes, why does it generate `lang:string` instead of `lang = string`? I added a proper script before, but it has been removed by c452ffb7857f4cfc457527bfee1eea46264755c8 by @pastk .

**Comment by biodranik** [comment]
This script has a parameter for this case. Please check its help output.
