### ISSUE TITLE
Improve box dialog when opening_hours is incorrect in advanced mode

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4455]
Scenario:
- Start OM
- Select POI on map
- Open editor -> open opening_hours IHM
- Select advanced mode
- Fill field with wrong syntax -> pop-up `fix error` appears

**Describe the solution you would like**
- Improve pop-up
- Title: Incorrect syntax
- Text in pop-up: Your opening_hours doesn't respect syntax, please check examples of values or copy paste your opening_hours on [YoHours](https://projets.pavie.info/yohours/)

https://github.com/organicmaps/organicmaps/blob/4a66bda647900bde3b02a9c08262632e1cf4fb50/android/src/app/organicmaps/editor/TimetableContainerFragment.java#L155

**Comment by n1snt** [comment]
I would love to work on this issue.
Can you please assign me this issue?

**Comment by Jean-BaptisteC** [comment]
@biodranik are you ok, to improve box dialog ?
@n1snt Feel free open PR if you want, don't ask

**Comment by biodranik** [comment]
An appropriate fix for this issue should _disable_ pressing the check mark if the typed text is not valid like it's done on iOS. Then the error message dialog would be not necessary, and it can be removed, together with the unused string https://github.com/organicmaps/organicmaps/blob/master/data/strings/strings.txt#L10026

Here is the documentation how to work with strings in Organic Maps: https://github.com/organicmaps/organicmaps/blob/master/docs/TRANSLATIONS.md
