### ISSUE TITLE
historic = fountain

### ISSUE THREAD

**Issue by toygarlk** [organicmaps/organicmaps#4457]
historic = fountain is not on Organic Maps. Please fix this.

![Ekran Görüntüsü (40)](https://user-images.githubusercontent.com/95170414/218314155-d08b966e-c12f-4f67-9ff1-9761edff2464.png)

**Comment by Jean-BaptisteC** [comment]
Could you please give a link to OSM :)

**Comment by endim8** [comment]
https://github.com/organicmaps/organicmaps/pull/4220 fixed it for me:

![signal-2023-02-15-204118](https://user-images.githubusercontent.com/26939824/219151013-18c35b3a-701b-4ffa-81f3-ba98e3cdcd4d.jpeg)

@toygarlk are you on the latest version and latest map data?

**Comment by toygarlk** [comment]
Fixed, thanks.
