### ISSUE TITLE
Routed path steers off highway which has actually no exits.

### ISSUE THREAD

**Issue by pitastrudl** [organicmaps/organicmaps#4476]
**Describe the issue**
Car travel route, seems to steer off sharply from speedway that has actually no exits but wants to join a road that is below it. Speedway is on a bridge.

**Steps to reproduce**

**Expected behavior**
A straight path

**Screenshots**
The route should continue forward. 
![image](https://user-images.githubusercontent.com/2771072/218580236-7ecc0404-4033-4772-892b-86b7ff54f982.png)

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.01.25-3-FDroid
 - Device Model: Samsung Android 

**Additional context**
Starting point:
https://omaps.app/84EHydXsqF/Autostrada_Sistiana-Rabuiese_%28tronco_II%29
Ending point:
https://omaps.app/w4EH4e8e46/Eurospar

You can use the points above to simulate the route. I am guessing it also could be an error in OSM data but when i try the same path in OSMand, the route is calculated differently.

**Comment by vng** [comment]
Fixed https://www.openstreetmap.org/changeset/132516737

**Comment by Jean-BaptisteC** [comment]
@pitastrudl problem is fixed ?

**Comment by pitastrudl** [comment]
@Jean-BaptisteC it is fixed, thanks! checked with fdroid version 2023.09.22-27-FDroid.
