### ISSUE TITLE
Airports priority

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#4478]
A current issue is that parking lots within airports clip each other (same z-index causing artifacts) when airport should be considered landuse (lower) and parking lots are a sort of land amenity that could be within an airport (higher, alongside parks, concrete, grass, road/pedestrian areas, etc.)

A similar problem happens when two airports overlap (i.e. when a named military base or private airfield is colocated with public airport property: runway-sharing arrangements are pretty common and will often be named/considered their own "airport," heliport, or air taxi "port" with entrances and facilities completely separate from the main airport's amenities) although this is obviously harder to find examples of, harder to resolve in code, and more likely to be a case where OSM simply prefers that they don't overlap (much like how Hickam AFB and Honolulu's airport have been separated.) Still, if it were possible to create consistent z-indexes to eliminate artifacting, that would be a nice catchall technologically speaking. (Artifacting is visually distracting and confusing.)

_Originally posted by @zyphlar in https://github.com/organicmaps/organicmaps/issues/4314#issuecomment-1427096457_

**Comment by pastk** [comment]
In the base style airports have a priority lower than parkings, so the parkings are rendered on top always.
Strangely, in the vehicle/navigation style they have same priorities indeed, to be fixed in #4477 

Same with military bases - their priority is higher so they should be drawn on top.
Do you have coordinates of cases where its rendered wrong?

**Comment by zyphlar** [comment]
Thanks! The case in question was a military airfield within a civilian airport, so two areas of the same type which is usually not something OSM likes. The parking lot fix should be good.

**Comment by zyphlar** [comment]
FYI natural=scrub and orchard also clip with landuse=farmland. Airport and parking also only clip at certain view angles, so that's interesting.

**Comment by pastk** [comment]
> FYI natural=scrub and orchard also clip with landuse=farmland. Airport and parking also only clip at certain view angles, so that's interesting.

#2170 would be an ultimate fix for that, changing relative priorities will not help here, as sometimes we'd like to see a patch of farmland inside a scrub, sometimes vice versa...

**Comment by pastk** [comment]
Fixed in #4477
