### ISSUE TITLE
Make "text-optional: true" default behaviour

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#4507]
By default POI's caption is "linked" to its icon and if the caption is displaced this makes the icon disappear too.
This kind of implies that an icon alone is useless without a caption. At the same time, if the same POI type has no text to display, then a lonely icon will be displayed anyway :)
It used by various types, e.g. `aeroway-gate`, `aeroway-terminal`, `amenity-bank`, `amenity-childcare`, `amenity-driving_school`,	`amenity-marketplace`, `barrier-gate` - I see no logic here, looks random.

There is a `text-optional: true` attribute in styles that makes the icon stay in those cases (i.e. only caption disappears). Still, if the icon is displaced, then the caption will go away too. This behavior makes sense. I think we should make all POIs behave like this and there is no need for a "text-optional" attribute at all.
(reasons to add it as an optional attribute instead of default behaviour are unclear https://github.com/mapsme/omim/pull/496)

@biodranik @vng 

Needed-for: #4317

**Comment by vng** [comment]
Yes! I'd like to see an icon if a caption was displaced. And yes, there is no need in a capital star if a caption was displaced ..
SO you will make text-optional=true as a default behaviour, right?

**Comment by pastk** [comment]
That's right, make it default, but retain the ability to turn it off (`text-optional: false`) for cases like capitals.
