### ISSUE TITLE
Take diet tags into account when searching for restaurants

### ISSUE THREAD

**Issue by silke** [organicmaps/organicmaps#4508]
**Describe the issue**
I tried to search for vegan restaurants by entering „vegan“ into the search bar. I do get restaurants as search results, but the OSM tag diet:vegan does not seem to be evaluated.

**Steps to reproduce**
1. Go to an area with restaurants on the map. My search area would be around the address Müggelseedamm 182, Berlin, Germany. It is a good example because it has 4 combinations of information:

restaurants tagged diet:vegetarian=yes and diet:vegan=only
restaurants tagged diet:vegetarian=yes and diet:vegan=no
restaurants tagged diet:vegetarian=yes, no information about vegan food
restaurants tagged diet:vegetarian=yes and diet:vegan=yes

2. Open the search from the bottom of the main screen. Enter „vegan“, press „search“.

3. The first 7 search results contain 4 places without vegan food (commented screenshot attached). The

No. 1 (good result)
https://www.openstreetmap.org/way/136813992
diet:vegetarian=yes
diet:vegan = only

No. 2 (bad result)
https://www.openstreetmap.org/way/297530572
diet:vegetarian=yes
diet:vegan = no

No. 4 (bad result)
https://www.openstreetmap.org/node/4908859222
diet:vegetarian=yes
No information on vegan food

No. 5 (good result)
https://www.openstreetmap.org/node/4348856690
diet:vegetarian=yes
diet:vegan = yes

**Expected behavior**
I expect to get a list of restaurants tagged diet:vegan=yes or diet:vegan=only.

**Screenshots**
![IMG_92CB162DBAFD-1](https://user-images.githubusercontent.com/1151403/219441780-88208e3b-ae71-44c0-b495-7085f03dcf79.jpeg)

**System information:**
- iOS 16.3.1
- Organic Maps 2023.02.13-10
- Device Model: iPhone 12 Pro

**Comment by vng** [comment]
Well, the problem is that we treat vegan and vegetarian as the same attributes for search:
```
cuisine-vegan|cuisine-vegetarian
en:Vegan|Vegetarian|veg cafe
```

Should we distinguish it? Is it very bad when for "vegan" we also return "vegetarian"?

**Comment by silke** [comment]
I would definitely distinguish. To give a comparison: For shops you also have different tags. "Beverages", "alcohol" or "coffee" all have something to do with drinking stuff but the shops sell very different things. You would not get a coffee in a "beverages" place because those are something like supermarkets for drinks.

While all vegan food is also vegetarian by definition, vice-versa this is not the case. Vegetarian places don't have anything to eat for vegans.

That said, there is a [pending merge request](https://github.com/organicmaps/organicmaps/pull/4498) concerning the "cuisine" tag that should not be used for tagging, it's "diet". Meanwhile of course there is "cuisine" tagged content now.
See https://wiki.openstreetmap.org/wiki/Key:diet:*

**Comment by silke** [comment]
I checked and it turned out that worldwide there were just a few dozen places left with the deprecated "cuisine" tag both for vegan and for vegetarian. I guess I updated almost all of them to use the diet tag. Searching for the old cuisine tag then won't give any results any more, so at some point the search function should look up diet tags and distinguish between vegan and vegetarian.

**Comment by silke** [comment]
Great, thank you!
