### ISSUE TITLE
[Android][F-Droid] Empty “Tracking settings” section in settings

### ISSUE THREAD

**Issue by anibyl** [organicmaps/organicmaps#452]
There's an empty section called “Tracking settings” in the app settings.
![image](https://user-images.githubusercontent.com/790717/119566238-c59ee600-bd5f-11eb-8b28-b8a0cde9a77b.png)
It should probably be hidden in case there's nothing there.

Version 2021.05.21-6-g6cfa29a770-FDroid

**Comment by rtsisyk** [comment]
This is a feature, not a bug. No tracking on F-Droid build ;)

**Comment by groovenectar** [comment]
What does it show on the Play Store version? I use F-Droid as well and was wondering about this section...
