### ISSUE TITLE
[android] JobIntentService in androidx.core.app has been deprecated

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#4531]
From: https://developer.android.com/reference/androidx/core/app/JobIntentService

> This class is deprecated.
>
> This class has been deprecated in favor of the Android Jetpack [WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager) library, which makes it easy to schedule deferrable, asynchronous tasks that are expected to run even if the app exits or the device restarts.

```
organicmaps/android/src/app/organicmaps/MwmJobIntentService.java:11: warning: [deprecation] JobIntentService in androidx.core.app has been deprecated
public abstract class MwmJobIntentService extends JobIntentService
                                                  ^
organicmaps/android/src/app/organicmaps/MwmJobIntentService.java:11: warning: [deprecation] JobIntentService in androidx.core.app has been deprecated
public abstract class MwmJobIntentService extends JobIntentService
                                                  ^
organicmaps/android/src/app/organicmaps/MwmJobIntentService.java:11: warning: [deprecation] JobIntentService in androidx.core.app has been deprecated
public abstract class MwmJobIntentService extends JobIntentService
                                                  ^
organicmaps/android/src/app/organicmaps/MwmJobIntentService.java:11: warning: [deprecation] JobIntentService in androidx.core.app has been deprecated
public abstract class MwmJobIntentService extends JobIntentService
```

**Comment by SigmaZardan** [comment]
I would like to work on this issue . Can you assign me 
 @rtsisyk

**Comment by AryanRajput2083** [comment]
@rtsisyk could you please elaborate on what we have to do here? do we have to switch our code to WorkManager instead of JobIntentService ?

**Comment by biodranik** [comment]
That issue is about fixing warnings by implementing a solution that will work on Android 5 (API 21) and above without warnings.
