### ISSUE TITLE
mention that it is a maps.me fork in Readme

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#454]
It would make it more clear what is going on (and maybe also easier to find for people looking for maps.me alternative)

**Comment by matkoniecz** [comment]
Maybe also mention differences?

MAPS.ME seems to be rolling back crippling changes for right now main difference is access to private data ("No Big Tech’s Prying Eyes on Your Private Trip Anymore."  from readme). Are there substantial differences in privacy policies of both projects?

**Comment by rtsisyk** [comment]
Feel the difference:

![photo_2021-05-28 12 05 46](https://user-images.githubusercontent.com/1799054/119959851-0d667d00-bfad-11eb-936d-92003e39ae3f.jpeg)

![photo_2021-05-28 12 05 42](https://user-images.githubusercontent.com/1799054/119959847-0ccde680-bfad-11eb-8896-f892fbf743e8.jpeg)


I will update the README later.

**Comment by j5k** [comment]
This issue seems to be done.

**Comment by matkoniecz** [comment]
yep
