### ISSUE TITLE
No location can be found

### ISSUE THREAD

**Issue by jakoblm** [organicmaps/organicmaps#4540]
**Describe the issue**

Since the release 2022.12.18-12-android from December 19, 2022 the location tracking in buildings does not work anymore. 
GPS is enabled, of course. In other apps my position is displayed correctly, even if I am in buildings (tested with Magic Earth, My Location, location data in microG). All these apps have the same permissions as Organic Maps. Wi-Fi throttling is disabled in the developer options. 
However, Organic Maps does not find a location most of the time. It seems that Organic Maps can't communicate with NLP backends at all, then no "location icon" appears in the top bar. I tested it with AppleWifiNlpBackend, Déjà Vu and MozillaNlpBackend. As I said, these location providers work correctly in all other apps. 
Rarely, it helps to turn the WLAN connection off and on again to display the location in Organic Maps. But most of the time it doesn't help.

**System information:**
- current /e/OS 1.8-r (Android 11 base) with microG 2.27.
 - Organic Maps version: 2023.02.13-11-android
 - Device Model: FP3+

**Additional context**
 In the release notes from Dec 19, 2022 it says something about "Fixed annoying Enable Location dialogs". Maybe there is a connection there? 

Another annoying thing is that the location search is interrupted as soon as I move the map with my fingers or zoom. There was already another issue about this here: https://github.com/organicmaps/organicmaps/issues/4376

**Comment by biodranik** [comment]
Are you using apk from FDroid? Please try to install the beta from our website, or install apk from github/Google Play and tell us if it works. 

I assume that all other apps were built with Google Play Location Services that are properly communicating with microg.

**Comment by Altonss** [comment]
I am experiencing a similar issue with the F-Droid version as I wrote in this comment https://github.com/organicmaps/organicmaps/issues/4223#issuecomment-1407082329

**Comment by jakoblm** [comment]
All apps are from F-Droid. Only Magic Earth is preinstalled in the operating system. 
Honestly, I don't want to add any other sources than F-Droid (Google Play or Github Beta). Also, for personal reasons, I lack the time for extensive testing at the moment. I ask for your understanding and hope that you will take care of it anyway.

**Comment by biodranik** [comment]
What other apps from FDroid except My Location did you try?

I'm telling you to try other versions because they will work with 99% confidence. We got similar issues from other users.
 
@rtsisyk  can you please check why My Location works in this case, but OM doesn't? All fdroid apps source code should be available.

**Comment by jakoblm** [comment]
A few months ago I tested Osmand from F-Droid. Mozilla Location Services is also from F-Droid. 

I understand your arguments. But for good reason I don't want to extend the F-Droid repo. Since other users are experiencing the same issues, couldn't you rather find a solution for the F-Droid version?

**Comment by biodranik** [comment]
We are using a standard Android code to work with location providers for FDroid that _should_ work, and already spent a lot of time trying to debug it. With Google Location Services wrapper it just works as expected. Without them, it doesn't.

@rtsisyk I still can't understand why other apps from FDroid, _presumably also without Google Services_, work, while OM doesn't.

**Comment by Jean-BaptisteC** [comment]
@jakoblm can you retry on latest version?

**Comment by RedAuburn** [comment]
closing as stale

**Comment by biodranik** [comment]
@jakoblm does the issue reproduce in the latest OM version?

**Comment by rmh2022** [comment]
Hi
I've been experiencing what seems like the same issue for some time:

- Using microG.
- Always testing while outdoors.
- GPS is enabled and operative 100% of the time while testing OM (using My Location to verify and keep the GPS lock)
- In all other apps (I've tested extensively with OsmAnd) location works correctly 100% of the time.
- OM is unable to find location most of the time. Often when first starting it, but it also stops getting location updates after a short time driving.
- When it happens, it sometimes helps to do one of these actions: 1. kill the app and restart it / 2. exit navigation mode / 3. toggle the Google Play Location Services switch.

In my latest test I was running OM 2025.06.26-3-Web on a phone with "LineageOS for microG" version 22.2-20250708-microG-FP3 which includes microG 0.3.7.250932, but I've also reproduced the problem with a variety of other combinations including pristine LineageOS + microG (installed as user app) 0.3.7.250932, with GPlay version of OM, and also with FDroid version of OM.

**Comment by biodranik** [comment]
@rmh2022 thanks for the details. Strange, that OM didn't work _without_ Google Location services in OM settings. The known microg issue is when Google Location Services are enabled.

**Comment by rmh2022** [comment]
> [@rmh2022](https://github.com/rmh2022) thanks for the details. Strange, that OM didn't work _without_ Google Location services in OM settings. The known microg issue is when Google Location Services are enabled.

You comment gave me an idea. Could it be that it's not the use of microG location services by OM that has a problem, but the mere presence of microG messes with GPS service in some way that breaks OM but -for whatever reason- has no effect on other apps?

So I grabbed the same phone, flashed pristine LineageOS original version without microG (22.2-20250709-NIGHTLY-FP3) and then installed OM (2025.07.13-9-Web). Now GPS works flawlessly!

My understanding is that GPS is completely independent of microG location services. However microG has some options that make it query GPS location regularly in background. Is that correct?

On my next trip I will try with microG installed, and play with microG settings, see if I can find any particular setting that breaks OM/GPS.

**Comment by rmh2022** [comment]
Well, there was no need to tweak microG settings. The default microG setup makes the bug appear again, even on a pristine system.

My test:

- Installed "LineageOS for microG" version 22.2-20250708-microG-FP3
- Didn't modify any microG settings. Default setup is as shown in the screen capture. Note that "Remember from GPS" is enabled.
- Installed OM 2025.07.13-9-Web
- Disabled "Google Location Services" in OM
- Made sure GPS is active (using com.mirfatif.mylocation), started OM (location is shown) and begun driving
- After a few minutes, OM stops receiving location updates

<img width="1080" height="2160" alt="Image" src="https://github.com/user-attachments/assets/a4079db7-ded4-4693-af7a-e926649284c3" />

**Comment by biodranik** [comment]
@rmh2022 To confirm: does disabling "Google Location Services" in OM fix this issue?

**Comment by rmh2022** [comment]
> [@rmh2022](https://github.com/rmh2022) To confirm: does disabling "Google Location Services" in OM fix this issue?

No

**Comment by biodranik** [comment]
(you likely need to restart OM after disabling Google Location Services)

So the bug is purely in Microg, right? Does it reproduce in the same config in other apps?

**Comment by rmh2022** [comment]
Hi

> (you likely need to restart OM after disabling Google Location Services)

Yes. I was missing that. Unfortunately all my previous tests are tainted and can't be relied on :-(

After disabling Google Location Services **and** restarting OM, everything works (with GPS location only)

> So the bug is purely in Microg, right? Does it reproduce in the same config in other apps?

I was unable to reproduce the problem with other apps. In particular, I tested OsmAnd a few times and it was working fine. I also use Waze regularly and it never exhibits this problem.

**Comment by biodranik** [comment]
Thanks for confirming it!

OsmAnd doesn't use Google's [Fused Location Provider](FusedLocationProviderClient). Not sure about Waze.

**Comment by rmh2022** [comment]
I think Waze is GPS-only. It stops updating location while inside a tunnel, and displays a message saying something about missing GPS signal. I don't remember the exact text but it clearly describes this situation, and it explicitly mentions GPS.

**Comment by rmh2022** [comment]
> I think Waze is GPS-only. It stops updating location while inside a tunnel, and displays a message saying something about missing GPS signal. I don't remember the exact text but it clearly describes this situation, and it explicitly mentions GPS.

Correction: while inside a tunnel it displays a message saying location is not exact because it isn't using GPS. It still displays a location though.
