### ISSUE TITLE
Wrong type of error message about buildings levels

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4541]
During my tests in this PR #4423, i have forgotten to test with buildings levels field -> this field have old error message under field

https://github.com/organicmaps/organicmaps/blob/bab264f2b198af4fc0498abb55123aad85c7e991/android/src/app/organicmaps/editor/EditorFragment.java#L185

CC @biodranik @satvik2131

**Comment by biodranik** [comment]
@Jean-BaptisteC can you fix it? )

**Comment by Jean-BaptisteC** [comment]
I have try to fix 
https://github.com/Jean-BaptisteC/organicmaps/commit/7c2d6c45982894be01efa63ec953050bd696a6cb
Build return String cannot be converted to int about `context.getString(R.string.error_enter_correct_storey_number, Editor.nativeGetMaxEditableBuildingLevels())`

String alone works but i don't know how do that to used method to get MaxEditableBuildingLevels

**Comment by Jean-BaptisteC** [comment]
Yes but in OM we have %d after string because we don't have give maxeditableBuildingLevel value :)

**Comment by biodranik** [comment]
Ah you're right! A possible solution is to add another method:

```Java
  public static void setInputError(@NonNull TextInputLayout layout, @StringRes int error)
  {
    setInputError(layout, error == 0 ? null : layout.getContext().getString(error));
  }

  public static void setInputError(@NonNull TextInputLayout layout, String error)
  {
    layout.getEditText().setError(error);
    final Context ctx = layout.getContext();
    layout.getEditText().setTextColor(error == null ? ThemeUtils.getColor(ctx, android.R.attr.textColorPrimary) : ctx.getResources().getColor(R.color.base_red));
  }
```
