### ISSUE TITLE
[android][ios] Deleting a bookmark needs an undo

### ISSUE THREAD

**Issue by thany** [organicmaps/organicmaps#4547]
**Is your feature request related to a problem? Please describe.**
When accidentally mispressing the screen and deleting a bookmark, I may have no clue what I just deleted. Or I may have deleted something that I put a lot of work in, figuring out whatever it is I need to write in the description field to help me on my way.

The bookmark will be deleted without confirmation, and permanently without the possibility to undo it. This is an antipattern - a destructive operation needs at least either.

In short - a bookmark is silently and permanently deleted. Everyone knows the feeling of accidentally deleting something without the possibility of ever getting it back without recreating it. It's a horrible feeling.

**Describe the solution you would like**
Either or both:
* Confirmation before deleting
* Undo deleting a bookmark

**Describe alternatives you have considered**
* Don't use the app while on the move, when it's easier to mis-tap the screen.
* Don't use the app while feeling weary, drunk, having a headache, with blurry vision, or when distracted.
* When consciously NOT tapping the delete button, be very particulate about staying well away from it, as touchscreens can register a tap at the lightest possible touch that a human would not register one at.

**Additional context**
This is a problem in both contexts:
* In the bookmarks list, holding a bookmark, a menu appears: share, edit, delete. Here, the delete button is close to edit, but also close to the Android back button.
* When selecting a bookmark on the map, a menu appears: route from, delete, route to, share. Here, the delete button can be pressed accidentally from all 4 sides.

In both these situations, a bookmark is silently and permanently deleted. So from a UX perspective, I would almost outright call this a bug, and a pretty severe one at that. But technically it's a feature. But I would probably register it as a pretty darn critical one still.

**Comment by biodranik** [comment]
See #1173

Confirmation breaks the simple UX, so let's focus on the undo solution for each case, and describe it in detail.

**Comment by thany** [comment]
Good to hear. Confirmation messages are less ideal because they can become muscle memory.

Same as deleting a file becomes `Del -> Enter`, which results in accidental deletes still being a thing.

**Comment by Raphael0** [comment]
I agree with others that an undo is the best solution when deleting individual bookmarks (I also often have to delete several temporary bookmarks that I just created).

However, what is not mentioned in this issue is that it is just as easy to delete a **list of bookmarks** potentially containing hundreds of individual bookmarks.

I would suggest the following
- add an undo when deleting individual bookmarks
- **add a confirmation message when deleting bookmark lists**.

I believe that is appropriate, since users delete bookmark lists much less often, and rarely if ever have to do it "en masse". An alternative would be to display a confirmation message only for lists containing more than X bookmarks, although I would not deem this necessary.

The issue is quite problematic on iOS where one only needs to inadvertently swipe left and could have a list with hundreds of bookmarks amassed over years deleted under a second.

**Comment by simonschaufi** [comment]
Copy from https://github.com/organicmaps/organicmaps/issues/5735#issue-1853942148

Folder can contain many bookmark and it's possible to easily delete a folder. It's a good practice to confirm final decisions like deletions.

**Criteria**

* When a bookmark folder has at least one bookmark, ask confirmation when deleting the folder - when deleting from ellipsis icon or by swiping the folder to the left.

**Design** https://www.figma.com/file/nYquGx60mBM3QQXBEce44A/OM-App-Features?type=design&node-id=25-2531&mode=design&t=GoBGKm2p1qxw2cuu-0

**Comment by kirylkaveryn** [comment]
The other way to create `undo` is the `Recently deleted` screen that contains all deleted bookmarks/lists with the ability to recover or to clear them finally with confirmation alert.
As example Filer or Photos in ios
<img width="407" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/2497afc2-649b-4e21-a712-3d0bac179719">
<img width="916" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/484bbe07-1620-4396-b041-4525ed9a6560">

**Comment by biodranik** [comment]
Confirming list deletion is annoying when you imported many temporary tracks or bookmark lists and want to quickly clean them up from your bookmarks for any reason.

OM's power is a simple UX. Let's focus on simpler undo solutions.

For example:
1. Use a special "Deleted" folder in bookmarks dialog with an option to clean it or better with auto-clean after a month.
2. Show some clickable snackbar/toast with the text like `The [bookmark list name] was deleted, press here to undo the deletion`.
3. Show Undo button somewhere in the UI (in the list?) when a list was deleted. This button will disappear after bookmarks dialog is closed.

**Comment by biodranik** [comment]
@thany please update this issue (or create a new one) in the context of a bookmark or track deletion from a list. It would be important to notice the root cause of an accidental deletion (e.g. a delete button is very close to some other button, etc.).
