### ISSUE TITLE
Traditional Chinese interface translations do not work on Android

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4551]
Tested with Taiwan, Macau, and Hong Kong options on Android 9 and 13.

It could be that locales are either removed/cleaned up for apk builds. CC @Jean-BaptisteC

**Comment by biodranik** [comment]
Quick-tested by commenting the line in build.gradle and it started working:
```
//resConfigs project.ext.supportedLocalizations
```

@Jean-BaptisteC looks like Chinese codes should be fixed there.

**Comment by Jean-BaptisteC** [comment]
Nice catch
zh_Hans,zh_Hant has need to be replace by zh, zh_TW
I have no idea how to fix this because name of languages is different in string.txt
Sed to replace in gradle.properties is ok for you ?

**Comment by biodranik** [comment]
Should it be zh-rTW? (Also MO and HK)

Bash variables replacement should be fine.

**Comment by Jean-BaptisteC** [comment]
Google doesn't explain which format used to specify resConfig, i have check others android project
They are used zh_TW, pt_PT, ...
For MO and HK, we don't have translations in strings.txt, for this translations we have symlinks to ../values-zh-rTW/strings.xml
