### ISSUE TITLE
Wrong colors in Create new bookmark list dialog in the Dark mode

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4562]
Dark mode can be forced from OM Settings.

![image](https://user-images.githubusercontent.com/170263/220269262-5a747588-cd17-4c9e-9002-78cc9fce46c3.png)

**Comment by Jean-BaptisteC** [comment]
Can i list all dialog with wrong color in this issue ?
Maybe we can also migrate to materialAlertDialogBuilder ?
https://www.material.io/components/dialogs
https://m3.material.io/components/dialogs/overview

**Comment by biodranik** [comment]
Yes, fixing all similar issues here would be great!

Migration is possible if it's easy and doesn't introduce a lot of heavy dependencies, and if it brings visual/UX benefits.

**Comment by Jean-BaptisteC** [comment]
I have doing somes search
All AlertDialog without xml layout have wrong colors in dark mode

Migrate AlertDialog to materialAlertDialogBuilder add possibility to used new material styles in app with better theming
We don't have need new dependencies, materialAlertDialog is available in com.google.android.material.

To improve theming, we can used themed daynight (`Theme.AppCompat.DayNight.Dialog.Alert`)with color for light theme in values/colors.xml and color for dark theme in values-night/colors.

It's a lot of work, but we reduce list of styles (one style for light/dark theme), i think the real difficulty is themed work on older devices.

**Comment by biodranik** [comment]
@arnaudvergnet @rtsisyk what do you think? Would it be the best approach?

**Comment by arnaudvergnet** [comment]
We're going to have to migrate to the latest material design theme at one point, so why not start with the dialogs?

**Comment by Jean-BaptisteC** [comment]
I have started to work to replace AlertDialog by MaterialAlertDialog
But work on theming is too complex for me

I try to fix wrong color in AlertDialog in dark mode, i have doing somes tests and i think this theme https://github.com/organicmaps/organicmaps/blob/3c1b2d1b2c5533be11a6d3e93efe42508f233c5d/android/res/values/themes.xml#L70 doesn't work for AlertDialog without xml layout
@arnaudvergnet Do you confirm this ?

**Comment by arnaudvergnet** [comment]
the style `MwmTheme.Night.AlertDialog` is set as the `alertDialogTheme` so all dialog should use it, even if they are created programmatically. If that's not the case we could force the dialog to use it with the last constructor listed here: https://developer.android.com/reference/android/app/AlertDialog#protected-constructors.

**Comment by Jean-BaptisteC** [comment]
It's already the case, in the most of alertDialog :)
https://github.com/organicmaps/organicmaps/blob/3c1b2d1b2c5533be11a6d3e93efe42508f233c5d/android/src/app/organicmaps/dialog/EditTextDialogFragment.java#L125

**Comment by biodranik** [comment]
Also the case for the error from public transport.

**Comment by Jean-BaptisteC** [comment]
Fixed by #4575
