### ISSUE TITLE
Whitespace at top of Wikipedia description

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#4563]
<img height="500px" src="https://user-images.githubusercontent.com/26939824/220323107-98b5a264-b160-4a1d-85f6-4d44b2ce2271.png">

with a build from latest main

**Comment by biodranik** [comment]
Before it was a bigger whitespace with the "DETAILS" word if you're talking about a gray horizontal line. What do you suggest? A solid white background for a whole place page?

There is also a case when bookmark is selected, see how the Edit bookmark button looks.

**Comment by biodranik** [comment]
Ah ok, you're speaking about a white part between Wikipedia button and the text )
