### ISSUE TITLE
Too much empty space at the top of the place page

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4565]
There is a lot of unused space above the "Painted Hall" title. @arnaudvergnet mentioned that it's there to avoid the case when PP (Place Page) header is covered by a top status bar (when PP is very long).

As a workaround solution, to avoid dynamic PP header height change, the indent/margin can be reduced, ideally, it should take into account a real system's status bar height.

![image](https://user-images.githubusercontent.com/170263/220340524-793dc6a9-fb8a-4a23-9522-3c0af4d101bd.png)

**Comment by ANS-UXI** [comment]
How about if we place the pull/drag icon in the middle of the gap like in ios?

![ios](https://user-images.githubusercontent.com/79016311/221272650-6e7042ad-2bc4-4a1c-aa4e-93d670474531.jpg)

**Comment by biodranik** [comment]
No, that doesn't look good and still wastes a good amount of important vertical space.

Google shows an additional top bar where important hidden/scrolled-up information (like title or coordinates) from the PP "jumps". But that's a complication at the moment. Simply reducing the current vertical height a bit may be enough (ideally taking into account the system toolbar height).

**Comment by jo780-full** [comment]
Hello for the unused space above how about placing an icon representing what was chosen for example if u have a hospital a red cross icon appears .. would that be a better alternative to an empty space?

**Comment by biodranik** [comment]
1. Do you think it will look good? Any examples?
2. We can't easily reuse icons from the map in the user interface now. But it may be feasible in the future, see #2026
