### ISSUE TITLE
amenity=loading_dock not rendering properly

### ISSUE THREAD

**Issue by jmarchon1** [organicmaps/organicmaps#4573]
**Describe the issue**
When tapping on a node tagged with amenity=loading_dock, the text "type.amenity.loading_dock" shows up, which does not seem like the intended result.

**Steps to reproduce**
1. Go to and tap on a node tagged with amenity=loading_dock
2. Look at the title

**Expected behavior**
I expected a more user-friendly title to show up, for example "Loading Dock".

**Screenshots**
![Screenshot_20230221-133952](https://user-images.githubusercontent.com/50030493/220513760-6c036602-dcd2-48ab-a6d5-92f0031026d5.png)

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.02.13-11-Google
 - Device Model: Pixel 6a

**Comment by biodranik** [comment]
That should be easy to fix. Check https://github.com/organicmaps/organicmaps/blob/master/docs/TRANSLATIONS.md and update data/strings/types_strings.txt

**Comment by Gua00va** [comment]
Hey!! I would like  to work on this issue? Can you assign it to me??
