### ISSUE TITLE
Not ideal search results

### ISSUE THREAD

**Issue by DavidKarlas** [organicmaps/organicmaps#4574]
**Describe the issue**
When searching for Library at https://www.openstreetmap.org/node/5859704949 
I entered in search "Knjižnica Rudnik" and another query "Dolenjska cesta 11" but failed to find it...

**Steps to reproduce**
1. Search "Knjižnica Rudnik"
2. See results
3. Should be at top of the list, but is at 6(outside screen when keyboard visible)

1. Search "Dolenjska cesta 11"
2. No results at all

**Expected behavior**
Results at top of list.

**Screenshots**
![image](https://user-images.githubusercontent.com/774791/220698396-2fed934f-001c-420f-8b74-9d03539f8244.png)

![image](https://user-images.githubusercontent.com/774791/220700505-15137ec6-30ee-4a16-b656-51effb5775ac.png)

**System information:**
 - Operating system and its version: iOS 16
 - Organic Maps version: Version: ⁦2023.02.13-10⁩
 - Device Model: iPhone11

**Comment by Jean-BaptisteC** [comment]
Tested on 2023.12.21-1-Google
- First search is in second place in the search result, @vng is it possible to improve this
- Second search returns this place https://www.openstreetmap.org/way/238038775 in the fourth place, @DavidKarlas is it the right place?

**Comment by DavidKarlas** [comment]
@Jean-BaptisteC did you search for "Dolniška cesta 11" or "Dolenjska cesta 11"?
I tried with latest version here are results:
"Dolenjska cesta 11" gets perfect result(1st place).
"Knjižnica Rudnik" is now in 3rd place, which is acceptable, but not best. Because 2 results before it don't have anything to do with "Rudnik"
![20231227_192443000_iOS](https://github.com/organicmaps/organicmaps/assets/774791/0049a982-8ca5-49ef-a678-61d5dc4035e4)
![20231227_192355000_iOS](https://github.com/organicmaps/organicmaps/assets/774791/f851c17a-e5a0-438b-a279-a3132a1f6801)

**Comment by DavidKarlas** [comment]
I saw in recent release notes that bug was fixed related to priority of search results, hence I re-checked this bug and now results are perfect!
