### ISSUE TITLE
Mixing styles from different types in a single feature might make it displace more important features

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#4590]
If a feature has several types and they have same drule elements (e.g. captions) then the renderer chooses the drule style with the highest priority.

E.g. a feature is a `building` and an `amenity-nursing_home`.
Both types have caption styles (different font size, color, possibly halo..).
The renderer will choose `building`'s caption style because it has higher priority.
But at the same time it will choose an icon style from `amenity-nursing_home` (because `building` has no icon style).

Its also possible that feature has a few types all of which have their own icon and caption styles, but their priorities could be set independently (due to various priority exceptions/hacks) and we'll end up with an icon from one type, but the its caption will be styled according to another type, which is wrong.

IMO icon and caption styles should be taken from a single type always.

Or maybe we should just take all drules from a single main type?
There are exceptions already for multiple line styles (resulting in e.g. ski and foot trails overlap https://github.com/organicmaps/organicmaps/issues/1577#issuecomment-1025788515) and multiple area styles is one of them is a hatching pattern.
Obviously, we'll also need to take an area style from a `building` if it has a POI (a main type).
Any more cases when we need to mix styles from different types?

**Comment by biodranik** [comment]
Is it possible to see a list of all types of the selected feature in the PP?

**Comment by pastk** [comment]
> Is it possible to see a list of all types of the selected feature in the PP?

Yes, in the desktop version ("raw types"). But not in prod versions.

**Comment by pastk** [comment]
Actually its more important and complex than that.

Even when POI's caption has higher priority than building's,
building-style caption could be displayed still on zoom levels where there is no POI caption defined.

E.g. `office-company` caption and icon are z18- and higher priority than `building`'s.
So on z18- office's caption and icon are displayed, but on z16-17 it changes to building's caption and no icon.
This makes `office-company` caption at `55.7391755, 37.6308282` to change from cyrillic `Объединенная Вагонная Компания` at z16-17 to translit latin `Obyedinennaya Vagonnaya Kompaniya` on z18-19 - more than just size and color change.

What's even more important - it makes low-priority POIs tagged as buildings displace much more important POIs.

For many POIs priority is increased because building's zoom bucket is used instead of POI's - as minVisibleScale is calculated for the whole feature i.e. including all of its types.
		
E.g. `office-company` is one of the lowest priority POIs with minVisibleScale = z18, but `building`'s is z14,
so `office-company` in a `building` is of much higher priority (z14 bucket) - higher than e.g. `amenity-restaurant`, `historic-memorial` (z15), `shop-supermarket`, `amenity-bank` (z16) POIs w/o a `building` tag.
		
Also `office-company` caption becomes visible from z16 (as it uses `building`'s caption style as described before) instead of normal z18-.
		
So `office-company` in a building becomes much more visible (caption is displayed from z16 instead of z18) and displaces a lot of POIs around (as its in a z14 zoom bucket instead of z18).
		
E.g. above mentioned `Obyedinennaya Vagonnaya Kompaniya` `office-company`'s caption displaces cafes and banks around.

![amenity-building-main-type](https://user-images.githubusercontent.com/18434508/221435182-7ea32ea3-1803-4bc2-bde1-af2d752ec665.png)

**Comment by pastk** [comment]
This behavior feels wrong and too complicated.

I think we need to define a "main type" for each feature and take both visibility/priority and drawing styles from the main type.

I.e. for above mentioned `Obyedinennaya Vagonnaya Kompaniya` POI a main style should be `office-company`, hence its caption should be visible from z18 and its priority should be in a z18 zoom bucket.

Logically, a main type should be chosen based on priority.
But which priority? It would have been simple if a type had a single priority value for its overlays (icons, captions) across all zooms (let's talk about overlays only for now, not about lines and areas).
But in our current system we can have different priorities on different zoom levels (https://github.com/organicmaps/organicmaps/issues/4314#issuecomment-1436016407) and different priorities for icons and captions (https://github.com/organicmaps/organicmaps/issues/4314#issuecomment-1433251614). If we define main type for a particular zoom only, then we can end up with a feature changing its appearance on different zooms again... Take the maximum value across all zooms? 

P.S. its not just about buildings, there could be other cases like `office` + `shop`, etc.

Related to #1392.

**Comment by pastk** [comment]
@vng @biodranik WDYT?

**Comment by biodranik** [comment]
We can treat any types that are on buildings (including buildings themselves) differently. Will it help?

**Comment by pastk** [comment]
> We can treat any types that are on buildings (including buildings themselves) differently. Will it help?

Making a buildings-only fix will be a little easier, but I think its better to make a generic fix that'll cover other more rare cases as well.

**Comment by pastk** [comment]
Some non-`building` cases I found:

`shop craft-tailor` (55.7414049, 37.6355783)
(or e.g. `shop craft-shoemaker` (47.4515309, 8.5632353))
Tailor should be the main type, but
- it uses z16 priority zoom bucket from `shop` (tailor is z17)
- at z16 only shop-style caption is displayed
- at z17 tailor-style icon is displayed together with a shop-style caption
- at z18 shop-style icon is displayed with a caption

`public_transport-platform amenity-bench` (47.4499559, 8.5618826)
Platform should be the main type, but:
- at z17 platform-style caption is displayed
- at z18 bench-style icon is displayed with a platform-style caption
- at z19 bench-style icon and caption are displayed
Here need to also raise platform's priority over bench'es to fix it.

`public_transport-platform highway-bus_stop amenity-bench amenity-shelter` (55.7418443, 37.6542492)
(related to #1392)
Bus stop should be the main type, but
- at z16 a bus-style icon is displayed with a shelter-style caption
- bus-style caption is used from z17

`public_transport-platform highway-bus_stop tourism-artwork amenity-bench amenity-shelter` (56.1319747, 48.4297477)
Bus stop should be the main type, but:
- it uses z15 priority zoom bucket from artwork (bus stop is z16)
- at z15 an artwork-style icon and caption are displayed
- at z16 icon changes to bus stop
- at z17 caption changes to bus-style

`landuse-industrial man_made-works` (47.4126425, 8.5343654)
Works should be the main type, but:
- it uses z15 priority zoom bucket from landuse (works is z16)
- landuse-style caption is displayed from z15 (works-style caption shall be visible from z18 only)
- works-style icon (z16-) is used with a landuse-style caption

`landuse-forest leisure-nature_reserve` (49.0958827, 16.7225058)
Reserve should be the main type, but:
- a forest-style caption is used
- from z11 a reserve-style icon is used
- from z13 a forest-style icon is used (though in this case icons are the same)
Rising reserve's overlays priority will likely fix it.

**Comment by pastk** [comment]
Types will have different priorities in different styles, so this might not work...
However at the moment its not clear how different we'll need them to be.

Are there any cases when we'd want the same feature to have a different main type (e.g. icon) in different styles?
As for now I don't have any real cases. Could be something like `wayside_shrine + drinking_water`: for a generic / touristic style it should be displayed as a shrine, but for outdoors it might be more important to display it as a water source..

**Comment by biodranik** [comment]
A good solution will display both.

**Comment by pastk** [comment]
>     4. `public_transport-platform highway-bus_stop tourism-artwork amenity-bench amenity-shelter` (56.1319747, 48.4297477)
>        Bus stop should be the main type, but:
>     * it uses z15 priority zoom bucket from artwork (bus stop is z16)
>     * at z15 an artwork-style icon and caption are displayed
>     * at z16 icon changes to bus stop
>     * at z17 caption changes to bus-style
> 

This case is quite tricky actually.
What is more important for the generic style? `tourism-artwork` or `highway-bus_stop`?

ATM artwork has higher priority than bus_stop, so artwork features are displacing nearby bus stops. If this is correct then a combined `highway-bus_stop tourism-artwork` feature should primarily look as an artwork too.

If we want it displayed primarily as a bus stop, then logically artwork features should not displace bus stops, but vice versa. We can do it by lowering artwork's priority or rising bus stop's one.

**Comment by pastk** [comment]
#4835 fixes/improves most of the cases described above, except the ones that need priorities adjustment (TBD in #4645).

![multiple-types-fixed](https://user-images.githubusercontent.com/18434508/227039742-14fdff24-e024-4b71-abb8-572b4232b071.png)

`Obyedinennaya Vagonnaya Kompaniya` is displayed from z18- now only (as it doesn't use `building`-style captions anymore), as well as some other long building captions around (its similar cases).
Also note bus stops are better visible now (case 3. above) - its because they don't display a shelter-style caption at z16 anymore (it was non-optional so icon+caption required more space around to be displayed).

**Comment by pastk** [comment]
Finished in #4645
