### ISSUE TITLE
Maybe document "Just make a PR"

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#4594]
@biodranik

> We do not assign issues to first-time contributors. Just choose any issue and fix it.

https://github.com/organicmaps/organicmaps/issues/4196#issuecomment-1373856560

maybe it would make sense to mention it in https://github.com/organicmaps/organicmaps/blob/master/docs/CONTRIBUTING.md ? I see numerous issues with "can I work on it" and "can you assign to me", most ignored

**Comment by biodranik** [comment]
Yes, please! It will save us a lot of time (hopefully) if that document will be read...

**Comment by matkoniecz** [comment]
Would it be OK to add CONTRIBUTING.md that would just link [docs/CONTRIBUTING.md](https://github.com/organicmaps/organicmaps/blob/master/docs/CONTRIBUTING.md)? It is linked in some placed by github if it exists.

**Comment by biodranik** [comment]
Will symbolic link work?

**Comment by matkoniecz** [comment]
Interesting question, never tried to have one in repository. No idea how Github and Windows will react.

**Comment by biodranik** [comment]
We require enabling of symlinks for everyone on Windows before cloning the repo. Or you can just add two INSTALL.md and CONTRIBUTING.md files with links to their docs counterparts.
