### ISSUE TITLE
link code of conduct?

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#4597]
Readme has 

> The Organic Maps community abides by the CNCF code of conduct.

"CNCF code of conduct" really should link to it

**Comment by matkoniecz** [comment]
either to https://github.com/organicmaps/organicmaps/blob/master/docs/CODE_OF_CONDUCT.md or directly to https://github.com/cncf/foundation/blob/main/code-of-conduct.md I guess

**Comment by biodranik** [comment]
@rtsisyk wdyt?

**Comment by Altonss** [comment]
This issue can be closed it seems, as the related PR is now merged https://github.com/organicmaps/organicmaps/pull/4610
