### ISSUE TITLE
Bad fonts for Persian and Thai languages.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#460]
For Persian, native speaker recommends to use https://github.com/rastikerdar/vazir-font or Noto fonts.
Need to check license.

**Comment by vng** [comment]
Persian sample with diacritics:
https://www.openstreetmap.org/way/707974106#map=19/35.51772/51.16111

**Comment by parnikkapore** [comment]
About the Thai text: It's not as bad as Persian; the text is correctly assembled and is perfectly readable. It just happens to be in a typewriter-like font.

As prior art, Google Maps seems to be using a localized version of Tahoma.

**Comment by vng** [comment]
Diacritics are not above symbols:
https://www.openstreetmap.org/node/248691069

**Comment by vng** [comment]
Integrate HarfBuzz

**Comment by biodranik** [comment]
Closing this issue as both Persian and Thai look ok and readable on the map. Please add more details/screenshots if something should be improved or fixed.
