### ISSUE TITLE
[android] multidex-config.txt is outdated

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#4621]
https://github.com/organicmaps/organicmaps/blob/40904fb7d9a9e0affe2393d8491124aebb20d5a2/android/multidex-config.txt#L1-L20

`app/organicmaps/maps/` doesn't exist anymore

**Comment by Jean-BaptisteC** [comment]
Multidex have interest ?
Because androidx.multidex:multidex dependecies have removed here https://github.com/organicmaps/organicmaps/pull/2701

**Comment by Jean-BaptisteC** [comment]
Removed by #6199
