### ISSUE TITLE
In metro view, the metro alignment doesn't match with the alignment of metro line in OSM data

### ISSUE THREAD

**Issue by sanketgarade** [organicmaps/organicmaps#4635]
**Describe the issue**
As seen in below screenshot the metro view is enabled in iOS OM app and the alignment of the metro in this view doesn't match the correct alignment shown by blue line. 

**Steps to reproduce**
1. Download the Maharashtra state map in India. 
2. Zoom to "Pune" city
3. Turn on metro view by clicking the left top view filter and selecting the metro view. 
4. Zoom to the area shown in the screenshot 

**Expected behavior**
The bold line in the metro view should match the metro alignment. 

**Screenshots**

![image](https://user-images.githubusercontent.com/74632379/221559642-bc2928bf-bf97-452a-a007-69ca22c506ef.jpeg)

**System information:**
 - Operating system and its version: iOS 16.3
 - Organic Maps version: 2023.02.23-10
 - Device Model: iPhone mini 12

**Additional context**

The metro line OSM reference [is here.](https://www.openstreetmap.org/relation/13916704#map=14/18.5148/73.8176)

**Comment by Altonss** [comment]
Noticed the same!
I think this is because OM simply smoothes out the path by simply connecting stations in a smooth way.

**Comment by sanketgarade** [comment]
> Why should it match? It's a _scheme_.

I guess, to give a true representation of the metro route. Even I wasn't sure if this was a bug or it's intentional. But now I know that it's not a bug, it's a feature! 😉
