### ISSUE TITLE
Detect/handle low memory events on Android

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4648]
Now we can't say if OM was killed due to a low-memory event. At first, it would be great to start logging these events:

https://developer.android.com/reference/android/content/ComponentCallbacks2#onTrimMemory(int)

https://developer.android.com/topic/performance/memory

At second, it may help to call Framework::MemoryWarning() from this event.

**Comment by satvik2131** [comment]
hi @biodranik , can you please elaborate what we have to do here, like do I have to check the reason of low memory in OM , please correct me if am wrong ?

**Comment by ANS-UXI** [comment]
> hi @biodranik , can you please elaborate what we have to do here, like do I have to check the reason of low memory in OM , please correct me if am wrong ?

Hey @satvik2131 
I'm also trying to work on this issue, lets collab and fix it, what do you say?

**Comment by Priyanshu-Mallick** [comment]
Hey, I think I can contribute to this issue and solve it, please assign me this issue

**Comment by ANS-UXI** [comment]
> Hey, I think I can contribute to this issue and solve it, please assign me this issue
> 
> 

If you can then fix it and make a PR, don't ask for assigning.

**Comment by biodranik** [comment]
@satvik2131 I've already written all the necessary details in the PR description. What is not clear to you? Please, ask specific questions.

There is already a method to clear some caches in the core. It is NOT called now on Android. It SHOULD be called if we get a low memory warning from the system.

**Comment by satvik2131** [comment]
> @satvik2131 I've already written all the necessary details in the PR description. What is not clear to you? Please, ask specific questions.
> 
> There is already a method to clear some caches in the core. It is NOT called now on Android. It SHOULD be called if we get a low memory warning from the system.

now it's clear , I was not able to exactly get the meaning from the description , thanks for the clarity .
