### ISSUE TITLE
Login to OpenStreetMap.org

### ISSUE THREAD

**Issue by xamanu** [organicmaps/organicmaps#465]
Trying to login with my OpenStreetMap account doesn't work. I'm with the first released version from F-Droid. I'm sure the password is correct:

![IMG_20210529_215427](https://user-images.githubusercontent.com/97706/120083453-0e8ccc80-c0c9-11eb-88f0-beac081500ff.jpg)

**Comment by j5k** [comment]
Same here.

**Comment by biodranik** [comment]
No worries, we'll fix it soon.
