### ISSUE TITLE
[GrapheneOS] Entire phone locks up under very specific conditions

### ISSUE THREAD

**Issue by andre4ik3** [organicmaps/organicmaps#4666]
## Describe the issue

When running under GrapheneOS, under some conditions, Organic Maps causes the entire phone to lock up (UI freeze until reboot).

Specific symptoms:
- Screen frozen (all of it, including system UI, app, etc.)
- If it froze whilst you were locking/unlocking the phone, screen will be frozen in the middle of the brightness changing animation (i.e. half-dimmed).
- Does not respond to presses (dragging from the side to invoke back gesture does not cause haptic feedback)
- _Does_ respond to button presses (pressing power button causes haptic feedback indicating power menu was opened)
- Sometimes it will un-freeze for around half a second, screen can go black and it can lock itself, time will update, but then it will immediately freeze again
- Phone remains in this state for several (3-4) minutes until it soft-reboots or user manually restarts.

## Steps to reproduce

_These are the steps that seem to consistently get it to reproduce on my Pixel 7 Pro, may be different for other users_

1. Enable Battery Saver
2. Enable Airplane Mode
3. Turn on music in the background (Finamp, Spotify, Apple Music, etc.)
4. Go to Organic Maps and start a walking route.
5. Within 5-10 minutes, the system will freeze.

## Expected behavior

Phone doesn't freeze

## Screenshots

N/A (Organic Maps UI appears over lock screen so it just looks like normal operation)

## System information

- Pixel 7 Pro GP4BC
- GrapheneOS TQ1A.230205.002.2023022300 (AOSP 13)
- Organic Maps 2023.02.13-11-FDroid
- Permissions: All (Location, Network, Sensors)

## Additional context

Related GrapheneOS issue: https://github.com/GrapheneOS/os-issue-tracker/issues/1972

**Comment by biodranik** [comment]
Interesting. It looks like some Pixel 7 issue. Another user wrote to us:

> It's crashing the OS all the time when I use the app for a long time (Pixel 7, Android 13)

Can you please try to type `?gl` in the search in OM and restart it, and see if the issue reproduces?

**Comment by andre4ik3** [comment]
Yes, I have not been able to reproduce issue since that update. Can safely say it's closed :)
