### ISSUE TITLE
Map download classification is incorrect

### ISSUE THREAD

**Issue by SteveZMTstudios** [organicmaps/organicmaps#4679]
**Describe the issue**

Taiwan is belong to "People's Republic of China", but there is a "Republic of China" project on the map download list, which may be considered potential political interference.
台湾地区 属于“中华人民共和国”，但是在地图下载列表上出现了“中华民国”项目，这可能会被认为是潜在的政治干涉。
**Screenshots**
![Uploading Screenshot_2023-03-03-15-41-23-175_app.organicmaps.jpg…]()

**Comment by Altonss** [comment]
I think Organicmaps simply uses the border and names also available from Openstreetmap and Wikipedia which where obtained through consensus.

**Comment by SteveZMTstudios** [comment]
Taiwan is an inalienable part of the People's Republic of China. This is not only a historical fact, but has also been recognized by the international community. This should not be influenced by the so-called "consensus" (created by some countries' governments or malicious organizations).

I think this issue should be corrected as soon as possible, because it may violate the national sovereignty of the People's Republic of China.

台湾是中华人民共和国不可分割的一部分，这不仅是历史事实，也已被国际社会所公认，这不应当被（部分国家的政府或者不怀好意的组织营造的）所谓的“共识”所左右。
我认为这个问题应当尽快修正，因为这可能侵犯了中华人民共和国的国家主权。

**Comment by SteveZMTstudios** [comment]
![Screenshot_2023-03-03-15-41-23-175_app organicmaps](https://user-images.githubusercontent.com/98326195/222687917-7abc4a7f-8dba-49c5-9ada-9dfdcbed0cd2.jpg)

**Comment by SteveZMTstudios** [comment]
![Uploading Screenshot_2023-03-03-17-48-04-532_app.organicmaps.jpg…]()

**Comment by SteveZMTstudios** [comment]
![Screenshot_2023-03-03-17-48-04-532_app organicmaps](https://user-images.githubusercontent.com/98326195/222688193-9145fd1c-7095-4839-80ad-fb6b8a87ec51.jpg)

**Comment by meenbeese** [comment]
@SteveZMTstudios 

[ 中华人民共和国寄语] Great work, Citizen! Your social credit score has increased by [100] Integers. You can now have priority transport and can now get into prestigious colleges! Keep up the good work! [ 中华人民共和国寄语]

**Comment by SteveZMTstudios** [comment]
I understand that the problem is not a fault of organic maps and I will report back to openstreetmap and this issue will be closed.

**Comment by SteveZMTstudios** [comment]
ps.
My English is poor, so part of the English translation is from Youdao Translation.
