### ISSUE TITLE
Disable zoom settings not working

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4680]
**Steps to reproduce**
1. Start OM
2. Open settings and disable zoom settings
3. Go to map -> buttons zoom is not disabled

**Expected behavior**
Zoom settings can able to enable or disable buttons zoom on map

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.03.02-1-Google-beta
 - Device Model: Pixel 6

**Comment by arnaudvergnet** [comment]
I'd say this issue belongs in https://github.com/organicmaps/organicmaps/milestone/6 as it is quite important. Do you have any idea as to when this bug was introduced? I don't remember working on anything related to that and it works in the current fdroid release.

**Comment by Jean-BaptisteC** [comment]
This https://github.com/organicmaps/organicmaps/commit/01b4565d7470c8bec7f877f3911803452f7c4302

**Comment by Aryan-Sagavekar** [comment]
![image](https://user-images.githubusercontent.com/109228835/222780537-a3abff6d-3347-4ce2-aea4-515c2332774a.png)
This does fix it.

**Comment by arnaudvergnet** [comment]
And it does not reintroduce the bug the commit fixed?

**Comment by ANS-UXI** [comment]
> And it does not reintroduce the bug the commit fixed?

Yes, the bug is reintroduced!

https://user-images.githubusercontent.com/79016311/222834238-d6ea3ef4-1a60-47fa-a8af-73f0b4355c3e.mp4

**Comment by ANS-UXI** [comment]
It might be useful. I've noticed that when I toggle the zoom button on and off, it doesn't work until I tap on a place page.

https://user-images.githubusercontent.com/79016311/222835800-99796555-5bc6-4125-964f-d35f66a1d12c.mp4

**Comment by Aryan-Sagavekar** [comment]
![image](https://user-images.githubusercontent.com/109228835/222871387-aac3ee25-f2e9-4049-81d9-e537625a4c79.png)
With this it solves the issue with the edit option.

https://user-images.githubusercontent.com/109228835/222871783-f97810e6-d90e-4632-9192-2e2650470548.mp4

**Comment by arnaudvergnet** [comment]
Yes if you have a working fix, please create a PR!

**Comment by Aryan-Sagavekar** [comment]
@arnaudvergnet as you said I created the resumeZoomButtons() functions and it works as expected. If you want you can try it.
![image](https://user-images.githubusercontent.com/109228835/223121911-54bf44d3-0007-4ca8-9c33-703383751af4.png)
Let me know if there are any changes I should make.
![image](https://user-images.githubusercontent.com/109228835/223122044-2d51ee52-7fb8-40fe-8078-0c2d854876bd.png)
Also showButton() function only has one use, maybe that could be changed.

**Comment by hoizan** [comment]
Tested on latest  release  2023.03.05-5-Google  still found having the issue. With  the Zoom buttons disabled, the  +/- buttons still pop up when you start to navigate.  The buttons disappear when  any POI is selected on map.

**Comment by Aryan-Sagavekar** [comment]
please could you check again because it is working fine for me.

**Comment by arnaudvergnet** [comment]
We are currently working on a fix. It will hopefully available in the next update.

**Comment by hoizan** [comment]
The issue is confirmed fixed in latest beta version 2023.03.18-6-Google.

**Comment by Jean-BaptisteC** [comment]
Not buttons zoom is not fixed in routing
Check this https://github.com/organicmaps/organicmaps/pull/4689#issuecomment-1474418909

**Comment by hoizan** [comment]
Yes, my bad. Not fixed in navigation mode but fixed in normal map view mode 

https://user-images.githubusercontent.com/92556284/226102312-3e6a91a6-1efe-44b2-a567-2155a9d477d0.mp4

**Comment by rtsisyk** [comment]
What is the current status here? Does anyone work on a fix?

**Comment by arnaudvergnet** [comment]
Should be fixed in https://github.com/organicmaps/organicmaps/pull/4808

**Comment by hoizan** [comment]
Verified that the issue  has been fixed on latest beta release 2023.05.05-5-Google-beta. The Zoom buttons now behave in  accordance with the settings.
