### ISSUE TITLE
Make icon label able to hide and unhide to review hidden neighbouring icon 

### ISSUE THREAD

**Issue by hoizan** [organicmaps/organicmaps#4685]
Icons on  map often disappeared when clicked on an neighbouring icon.

Currently, at different zoom levels, icons shown on map can be with or without a label. 
However when clicking on say X-icon , which ha no label, and is  closely next to say Y-icon, Y-icon disappears when the label 
for X-icon appeared.  One needs to play with different zoom levels to make Y-icon appears again.  Please see attached screen recording.

Propose to make icon label able to hide or unhide when clicking on it so as to review any icon hidden by it..   
I think this is more intuitive, and improve user experience when checking on icons of places of interest which are next to each other. 

https://user-images.githubusercontent.com/92556284/222883435-62465aa7-76e2-4691-bf29-67cf0a3e7bbc.mp4

**Comment by MANISH-LAB** [comment]
Assign me this issue

**Comment by biodranik** [comment]
@MANISH-LAB we do not assign issues to first-time contributors.

**Comment by biodranik** [comment]
Disappearing/appearing texts don't look good. This behavior should be changed/fixed.

Implementing grouping/collapsed icons likely would be better, it was discussed here: https://github.com/organicmaps/organicmaps/issues/1109

**Comment by hoizan** [comment]
Yes, the icons that disappeared when a neighbouring icon is selected will reappear when another icon or place, which is slightly away, is clicked  on. I tested a few clusters of icons which are fairly closed to each other.
