### ISSUE TITLE
[website] Add F-Droid button

### ISSUE THREAD

**Issue by j5k** [organicmaps/organicmaps#469]
Add F-Droid button next to App Store and Google Play on https://organicmaps.app

**Comment by rtsisyk** [comment]
Done

**Comment by j5k** [comment]
> Done

I can not see it. Even 3 days later (with cleared cache). Where can I find it?

**Comment by biodranik** [comment]
It's in Github Readme now, and in our new (not yet deployed) site.

**Comment by j5k** [comment]
Oh cool. Thanks!
