### ISSUE TITLE
Render landuse=farmyard

### ISSUE THREAD

**Issue by jmarchon1** [organicmaps/organicmaps#4694]
**Is your feature request related to a problem? Please describe.**
landuse=farmyard does not appear to be rendered.

**Describe the solution you would like**
I would like to see landuse=farmyard be rendered, similar to how it is rendered on openstreetmap.org

**Additional context**
There is an area tagged with landuse=farmyard here, but it does not show up:
![Screenshot_20230304-164114](https://user-images.githubusercontent.com/50030493/222935425-e96225d1-54a6-4304-8518-3953f417c9b5.jpg)

The names of farmyards also tagged with name=* appear to be rendered, as shown in the following screenshot. However, also rendering the area of the farmyard would be nice.
![Screenshot_20230304-164353](https://user-images.githubusercontent.com/50030493/222935468-4a4450a1-7566-4e6c-bf5b-11350bb98d65.jpg)

**Comment by jmarchon1** [comment]
Correction: It appears landuse=farmyard is rendered the same as landuse=farmland. Rendering it in a different color would be better, in my opinion. The first screenshot does not have a landuse=farmyard. Sorry for the confusion.

**Comment by biodranik** [comment]
We can make the farmyard a bit lighter or darker than the farmland. @pastk WDYT?

**Comment by biodranik** [comment]
And maybe in cases like this one, we also can apply the same logic as with greenery: make colors the same on observation zoom levels, and only distinguish them when zooming in?

**Comment by pastk** [comment]
> We can make the farmyard a bit lighter or darker than the farmland. @pastk WDYT?

Sounds good!
Maybe a more gray-ish / less saturate color as farmyards are about sheds, tarps, etc. 
Or just try to re-use the `@industrial;` color.
