### ISSUE TITLE
News short link doesn't work properly

### ISSUE THREAD

**Issue by MetehanOzyurek** [organicmaps/organicmaps#4697]
Turkish news short link, omaps.app/tr/news doesn't work properly. When you tap on it, it's redirecting to Organic Maps app. I have tested it on Android 12 device in Google Play release notes. Here's a screen record:

https://user-images.githubusercontent.com/80093621/222953781-c5fc8121-158a-4985-b43f-94204b945a45.mp4

**Comment by Jean-BaptisteC** [comment]
CC @rtsisyk

**Comment by MetehanOzyurek** [comment]
There is no problem in the new short link URL

![IMG_20230608_193240_262.jpg](https://github.com/organicmaps/organicmaps/assets/80093621/65dd69dd-0dce-4932-bd99-8517cc4281cc)
