### ISSUE TITLE
Hole in border drawing + incorrect information

### ISSUE THREAD

**Issue by Altonss** [organicmaps/organicmaps#4702]
**Describe the issue**
Hole in border drawing + incorrect information

**Steps to reproduce**
1. Go to 50.726669, 3.191524 (having only downloaded the french maps part
2. See the whole in the border line drawing
3. Click on the border line "National Border" and see the information error: especially the link which doesn't match at all with the objects involved (border, regions..)

**Expected behavior**
The border line shouldn't countain a hole, and the information displayed should be correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/66519591/222982711-234784da-020e-46a9-a41e-1f4f131bbe46.png)

**System information:**
 - Operating system and its version: Android 13 (Graphene OS)
 - Organic Maps version: 2023.02.13-11-FDroid

**Comment by vng** [comment]
Well, can't say for sure about the whole, but the tags are inherited from this Relation:
https://www.openstreetmap.org/relation/13810649

**Comment by vng** [comment]
I think we should filter boundary != administrative Relations for now.
France has too many fancy border types like: religious_administration, political, ...

**Comment by Altonss** [comment]
> Well, can't say for sure about the whole, but the tags are inherited from this Relation: https://www.openstreetmap.org/relation/13810649

Thanks for the information! But why is data from this relation shown? This shouldn't be part at all, because it is labelled as a national border, so no link to religious_administration at all...

**Comment by vng** [comment]
The generator uses "generic" approach when some tags are _always_ inherited from parent Relations. Definitely, should revise/update it.

**Comment by Altonss** [comment]
Should we split this issue into 2 parts? One for the inherited relations bug and one for hole in the border drawing?

**Comment by vng** [comment]
No, this is ok. Can't promise that will be fixed very soon, but I will check.

**Comment by Altonss** [comment]
> No, this is ok. Can't promise that will be fixed very soon, but I will check.

No worries :)

**Comment by vng** [comment]
If you update maps in the current store version, you should not see "catholique" links for this border.

**Comment by vng** [comment]
Damn. Do not take any tags from parent relations for boundary-administrative-2! This is the best solution to avoid it :)
