### ISSUE TITLE
Support network tag for bicycle_rental, atm and charging_station

### ISSUE THREAD

**Issue by thegrasshopper104** [organicmaps/organicmaps#4705]
For example, all bicycle_rental are marked with network=bubi in Budapest.
https://wiki.openstreetmap.org/wiki/Item:Q17871
Showing this first and only then the dropoff-point name (which is currently the only thing shown) would make more sense.

[[source](https://wiki.openstreetmap.org/wiki/Key:network#Amenities)] In conjunction with [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[bicycle_rental](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_rental) or [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[atm](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Datm) or [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[charging_station](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station), this key identifies an organization or brand that operates a similar amenity in various other locations. For example, a bicycle rental station in London may belong to the "tfl_cycle_hire" network. An ATM may belong to a network shared among many banks. Or a car-sharing station may be part of a network where different operators allow customers to use any station in the network.

Example:

network=[Bicikelj](https://wiki.openstreetmap.org/wiki/Tag:network%3DBicikelj) – [BicikeLJ](https://en.wikipedia.org/wiki/BicikeLJ) (Ljubljana bicycle rental)

![Screenshot_2023-03-06-13-00-33-88_10a7d9276315e62e56e7300dfec6be06](https://user-images.githubusercontent.com/57704946/223104970-6cac04d4-07d1-4d25-b6a4-cbc8f0012a69.jpg)

**Comment by aronkvh** [comment]
If the community would support it, they could even have a background color depending on the network name, making them even easier to distinguish

**Comment by biodranik** [comment]
SVG rendering on devices will help, see https://github.com/organicmaps/organicmaps/issues/2026#issuecomment-1030674156
