### ISSUE TITLE
Marker is not shown when i open GPS coordinates

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4707]
**Describe the issue**
When i try to open GPS coordinates from photo, sometimes marker on map is not show

**Steps to reproduce**
1. Open your gallery photo, select a photo and open OM with GPS coordinates -> OM is open with marker in the right place
2. Go back to gallery photo (be sure marker is always shown when you switch app)
3. Select other photo and open coordinates with OM -> OM is open in the right place but marker is not shown
- If i touch map on other place for marker disappear before go back to gallery and open GPS coordinates -> problem doesn't appear
- if i select POI, after i go back to gallery and open GPS coordinates -> problem doesn't appear 

**Expected behavior**
Each time, i used API, i want OM show marker in map

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.02.13-11-Google
 - Device Model: Pixel 6

**Comment by Jean-BaptisteC** [comment]
Similar of #2024

**Comment by biodranik** [comment]
@Jean-BaptisteC did you test it with OpenGL or Vulkan?

**Comment by Jean-BaptisteC** [comment]
OpenGL, i guess on my Pixel 6
