### ISSUE TITLE
Improve automated translations quality

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4717]
It would be helpful for app developers who want to add some new translation strings quickly.

The output of `tools/unix/generate_localizations.sh` can be improved by adding [DeepL API](https://www.deepl.com/docs-api) support and falling back to Google Translate for languages that are not supported by DeepL. One of the important reasons to add DeepL is that it correctly translates to Portuguese (pt, non-Brazil), while Google always translates to pt-BR.

**Comment by Saifuddin53** [comment]
hey @biodranik please assign this issue to me

**Comment by biodranik** [comment]
Why are you asking about the assignment? We do not assign issues, if you want to fix it — just do it without an assignment.

**Comment by LuciferCap** [comment]
please provide an api key for the deepl api

**Comment by biodranik** [comment]
Everyone can register and get a personal API key.

**Comment by LuciferCap** [comment]
But it's not free .

**Comment by biodranik** [comment]
Free API plan allows up to 500K free characters per month. That is way than enough for a casual developer. 

It would be great to ask developer to register a DeepL account if necessary, and fall back to Google Translate if for some reason Deepl API doesn't work.

**Comment by Jean-BaptisteC** [comment]
@biodranik fixed by #5118 ?

**Comment by biodranik** [comment]
Yes. Please use `tools/python/translate.py` now.
