### ISSUE TITLE
Add document or links to install Android auto simulator on computer

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4719]
Add document to install Android auto on computer

Tutorial is available here https://android-developers.googleblog.com/2015/08/announcing-android-auto-desktop-head.html

Just replace
`Enable Android Auto developer mode by starting the Android Auto companion app and tapping on the header image 10 times. This is a one-time step.`
By `Enable Android Auto developer mode by starting the Android Auto companion app and tapping on version 10 times. This is a one-time step.`

@AndrewShkrob congratulations for your work on Android Auto 🎉

**Comment by rtsisyk** [comment]
I can cover this part.
