### ISSUE TITLE
[search] Home Depot shops

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#4722]
Download Charlotte (NC) and make a viewport above it.

- searching for "Home Depot" - ok, but better to have "The Home Depot" shops on top
- searching for "The Home Depot" - ok
- searching for "Home Depot shop" - absolutely irrelevant results .. No "The Home Depot" shops on top-20 at all ...

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.01.09-6-Google version
