### ISSUE TITLE
OrganicMaps Android Auto (AA) branch fails to build.

### ISSUE THREAD

**Issue by n1snt** [organicmaps/organicmaps#4724]
**Describe the issue**
When trying to build organic maps repo with the aa branch checked out it throws errors.

**Steps to reproduce**
1. Clone the repo using the instructions given in the docs.
2. Use `./configure` to configure the cloned repo.
3. Run `./tools/android/set_up_android.py --sdk $HOME/Android/Sdk`
4. Open Android studio
5. Run build
6. It gives the following errors:

```
-- Found ZLIB: /home/nishant/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/23/libz.so (found version "1.2.12") 
-- Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR) 
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could NOT find BrotliDec (missing: BROTLIDEC_INCLUDE_DIRS BROTLIDEC_LIBRARIES) 
-- Found Python3: /usr/bin/python3.10 (found version "3.10.6") found components: Interpreter 
-- Found python to use in qt/, shaders/ and 3party/: /usr/bin/python3.10
-- Configuring incomplete, errors occurred!
See also "/home/nishant/Documents/organicmaps/android/nativeOutputs/Debug/636i326n/arm64-v8a/CMakeFiles/CMakeOutput.log".
See also "/home/nishant/Documents/organicmaps/android/nativeOutputs/Debug/636i326n/arm64-v8a/CMakeFiles/CMakeError.log".

C++ build system [configure] failed while executing:
    /usr/bin/cmake \
      -H/home/nishant/Documents/organicmaps \
      -DCMAKE_SYSTEM_NAME=Android \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_SYSTEM_VERSION=23 \
      -DANDROID_PLATFORM=android-23 \
      -DANDROID_ABI=arm64-v8a \
      -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
      -DANDROID_NDK=/home/nishant/Android/Sdk/ndk/25.2.9519653 \
      -DCMAKE_ANDROID_NDK=/home/nishant/Android/Sdk/ndk/25.2.9519653 \
      -DCMAKE_TOOLCHAIN_FILE=/home/nishant/Android/Sdk/ndk/25.2.9519653/build/cmake/android.toolchain.cmake \
      -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja \
      "-DCMAKE_C_FLAGS=-fno-function-sections -fno-data-sections -Wno-extern-c-compat" \
      "-DCMAKE_CXX_FLAGS=-fexceptions -frtti" \
      -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/nishant/Documents/organicmaps/android/build/intermediates/cxx/Debug/636i326n/obj/arm64-v8a \
      -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/nishant/Documents/organicmaps/android/build/intermediates/cxx/Debug/636i326n/obj/arm64-v8a \
      -DCMAKE_BUILD_TYPE=Debug \
      -B/home/nishant/Documents/organicmaps/android/nativeOutputs/Debug/636i326n/arm64-v8a \
      -GNinja \
      -DANDROID_TOOLCHAIN=clang \
      -DANDROID_STL=c++_static \
      -DOS=linux \
      -DSKIP_TESTS=ON \
      -DUSE_PCH=OFF
  from /home/nishant/Documents/organicmaps/android
Setting PLATFORM_ANDROID to true
C compiler: Clang
SKIP_TESTS: Skipping subdirectory bsdiff/bsdiff_tests
CMake Error at CMakeLists.txt:329 (target_compile_options):
  Cannot specify compile options for target "gflags_nothreads_static" which
  is not built by this project.
```

**Expected behaviour**
The project to build.

**Screenshots**
![image](https://user-images.githubusercontent.com/46300244/223630214-84b5412a-7acb-4ec4-a8dd-b2739798e832.png)
![image](https://user-images.githubusercontent.com/46300244/223630254-3634554b-7715-4e2f-88ee-57270a8e0eac.png)

**System information:**
 - Ubuntu 22.04 LTS

**Additional context**
Have tried rebooting, re-cloning.
Other branches seem to be building fine.

**Comment by shankarpriyank** [comment]
Are you able to run the master branch on your system?

**Comment by n1snt** [comment]
Yes, I am able to build & run the master branch.

**Comment by biodranik** [comment]
Did you get the latest, rebased `aa` branch without any errors? Try to delete your local aa branch, and then check out the fresh one again. And see if you get any errors in the process.

**Comment by n1snt** [comment]
@biodranik tried everything listed but still build fails with the following error:
```
CMake Error at CMakeLists.txt:328 (add_subdirectory):
The source directory
/home/nishant/Documents/organicmaps/3party/gflags
does not contain a CMakeLists.txt file.
```

**Comment by Jean-BaptisteC** [comment]
Did you have enable symlinks ?

**Comment by n1snt** [comment]
I have enabled symlinks.
Other branches seem to be working fine.

**Comment by Jean-BaptisteC** [comment]
Check if you don't have conflicts on git
We have migrate gflags to sub-module on master https://github.com/organicmaps/organicmaps/commit/50aa1c2637f69c813665fb244c94adaef3fbccef
But on aa branch, gflags is not sub module

**Comment by n1snt** [comment]
Is the gflags directory supposed to be empty?

**Comment by Jean-BaptisteC** [comment]
Not on aa branch, normally you have module gflags with cmakelists.txt

**Comment by n1snt** [comment]
For some reason, it was not pulling gflags.
I just copied gflags from the master branch and pasted it in aa.
And viola it's building fine.

**Comment by n1snt** [comment]
git pull --recurse-submodules would have done it too I guess.
