### ISSUE TITLE
Android auto app on emulator?

### ISSUE THREAD

**Issue by n1snt** [organicmaps/organicmaps#4735]
**Describe the issue**
There is no documentation on how to run the app on an Android Automotive emulator.

**Expected behaviour**
There should be docs on how to build and run the android auto app.

**Screenshots**
Is the app supposed to look like this?
![image](https://user-images.githubusercontent.com/46300244/223932170-ca19f100-d387-4e27-ab7a-22e1b2935080.png)

**System information:**
 - Ubuntu 22.04 LTS
 - Volvo Emulator.

**Additional context**
I am unable to run the app on android auto.

**Comment by Jean-BaptisteC** [comment]
Similar of #4719

**Comment by n1snt** [comment]
Can anyone help me out with how to build the `car` flavor?
I am unable to find it.

**Comment by AndrewShkrob** [comment]
Hi, @n1snt. There is no `car` flavor.

Android Auto (AA) and Android Automotive OS (AAOS) are absolutely different things.

As I understand, you want to run AA, but according to your screenshot, you're running AAOS emulator :)
We don't support AAOS yet.

Here are the steps to build app with AA support:
1. Checkout to the `aa` branch. It's better to checkout to this PR: #4681 
    It has a feature that allows you to switch maps between AA and Device screen without any problems.
2. Build and install the app on your android device.

That's it 😄 

How to run AA?
1. You'll need a Desktop Head Unit (DHU).
   Here is a guide on how to install it: https://developer.android.com/training/cars/testing#test-auto
2. Connect your android device to PC
3. Run the DHU
    `./desktop-head-unit --usb`

And you'll see the AA interface.

**Comment by n1snt** [comment]
Hi there!

Thanks for the explanation of the difference between Android Auto and Android Automotive OS. It's important to understand the distinction between the two. (I thought they both were the same before creating this issue)

Your instructions on how to build an app with Android Auto support and how to run Android Auto are clear and concise. It's great to have a step-by-step guide for those who are new to this process.

Thanks for sharing your knowledge on this topic!
