### ISSUE TITLE
Can't download maps on mobile network

### ISSUE THREAD

**Issue by hamlet** [organicmaps/organicmaps#474]
Hello,
I can't download maps on mobile network, but it works on wifi.

I tried with the app installed from Google Play, from GitHub release, and, as soon as publisehd, from Fdroid.
With the release version, I could download the world maps, but not the local ones.
In all versions, I click download (from the map or the menu), accept the notice about downloading on mobile network, and the download starts, but stays at 0% forever...
I tried to read the logs, but couldn't find anything related.

Only then did I think of activating my wifi, and I could download the map right away.

Please ask if you want more tests.

Thanks for the awesome work !
Best regards.

**Comment by biodranik** [comment]
Do you use any VPN/custom DNS provider? It would be great to check your `adb logcat` output when download is stalled. You may upload logs here or send them to android@organicmaps.app

**Comment by hamlet** [comment]
Hi !
I do use Blokada, no other special config (on ArrowOS 9.0). I tried to disable it, and then it worked ! Which is weird, since it works through wifi with blokada on...
More importantly, the url cdn.organicmaps.app is not blocked in blokada.
Here is the relevant part of logcat. Please tell me if you need more.
```
06-02 14:35:17.893 18782 18782 I MapsmeCore: storage/storage.cpp:1173 DownloadNode()  Downloading France_Brittany_Ille-et-Vilaine
06-02 14:35:17.974 18624 19716 D DownloadManager: [2729] Starting
06-02 14:35:17.989 18624 19716 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
06-02 14:35:17.989 18624 19716 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
06-02 14:35:17.999 18624 19716 W DownloadManager: [2729] Stop requested with status HTTP_DATA_ERROR: Unable to resolve host "cdn.organicmaps.app": No address associated with hostname
06-02 14:35:18.001 18624 19716 D DownloadManager: [2729] Finished with status WAITING_TO_RETRY
```
Weird, but not that bad, it might not affect most users.
Best regards.

**Comment by biodranik** [comment]
Thanks for the details. It's very strange that your dns resolver can't get ip addresses for the hostname.

What dns server address is active on your mobile network? Is it some localhost dns service started by Blokada?

**Comment by hamlet** [comment]
Nope, it's the default ones for my ISP. And it works through my browser (I get a 403) and pinging via termux. Maybe some timeout problem, I guess blokada must add some delay.

**Comment by biodranik** [comment]
Interesting. Looks like the OS DNS resolver which is used in Android NDK/C++ code is different from the one used in the browser.

**Comment by rtsisyk** [comment]
Do you have a firewall installed?

**Comment by groovenectar** [comment]
I experienced this exact same issue trying the app for the first time, world maps but no local maps... In my case I had a service forcing a custom DNS, it was set to Cloudflare's (1.0.0.1) and (1.1.1.1)... If I disabled custom DNS, the local maps would download.. cdn.organicmaps.app resolves normally in the browser regardless of DNS setting. Let me know if I can run any more tests for you.

Now I'm up and running and it's totally awesome. Thank you so much for the wonderfully humanitarian effort with this app!

**Comment by hamlet** [comment]
Sorry for the delay.

@rtsisyk Not that I'm aware of.

I did a new try, after the recent update (via fdroid), and it still doesn't work. What is weird is that the request about cdn.organicmaps.app is logged by blokada, as allowed. So the app does the request the right way, but doesn't get an answer. 

As said before, I suspect too short a timeout in the DNS request. My previous log shows that the download is cancelled 25ms after start, it might be a bit short.

Please tell how I can test this.
Regards

**Comment by biodranik** [comment]
Our current implementation uses the system's Downloading Manager service to download maps. Is it also blocked on your device?

**Comment by groovenectar** [comment]
@hamlet It looks like Blockade allows custom DNS setting... That feature is entirely disabled for you?

That was the issue for me, but via DNS66 rather than Blockada... Had to disable the custom DNS just for downloading local maps, then re-enable... The world map downloaded fine set to Cloudflare DNS...

**Comment by hamlet** [comment]
@groovenectar Indeed it is disabled. I double-checked through Termux, and it's really my ISP's DNS used there.

@biodranik Do you know how I could test my system's Downloading Manager service ? Some simple app maybe ? I've never noticed any trouble, but I mostly use Firefox to download things...

Best regards.

**Comment by jomo** [comment]
I'm having the same issue. Logcat shows `failed to connect to cdn.organicmaps.app/… (port 443)`. This happens with both IPv4 and IPv6 addresses.

I do use an "always-on" VPN connection on Android, but it doesn't alter DNS or traffic in any way (except for NAT obviously). Also, connecting using `netcat` on the phone with the same IP address and port given in the error message works just fine.

```
W System.err: java.net.MalformedURLException: no protocol: 
W System.err:  at java.net.URL.<init>(URL.java:601)
W System.err:  at java.net.URL.<init>(URL.java:498)
W System.err:  at java.net.URL.<init>(URL.java:447)
W System.err:  at com.mapswithme.util.HttpClient.run(HttpClient.java:3)
W MapsmeCore: core/jni_helper.cpp:218 HandleJavaException()  java.net.MalformedURLException: no protocol: 
W MapsmeCore:  at java.net.URL.<init>(URL.java:601)
W MapsmeCore:  at java.net.URL.<init>(URL.java:498)
W MapsmeCore:  at java.net.URL.<init>(URL.java:447)
W MapsmeCore:  at com.mapswithme.util.HttpClient.run(HttpClient.java:3)
W MapsmeCore: platform/servers_list.cpp:40 GetServersList()  Can't get servers list from request, using default servers: [1: https://cdn.organicmaps.app/ ]
D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
[…]
W DownloadManager: [862] Stop requested with status HTTP_DATA_ERROR: failed to connect to cdn.organicmaps.app/2606:4700:20::ac43:448c (port 443) from /fc00:<SNIP> (port …) after 20000ms
```

Is Cloudflare dropping the connection due to strict anti-abuse settings?

**Comment by hamlet** [comment]
@biodranik Blokada doesn't allow or block request based on apps, only by address. cdn.organicmaps.app is authorized, and logged as such when I try to download maps. As said before, if I completely disable blokada, maps downloading works... I don't mind that much, there's no ads in Organic Maps, but other users might get confused...

@jomo I'm not sure it's the same problem, as mine is about the DNS resolution, which seems to work in your case.

**Comment by biodranik** [comment]
Can you please try again now?

**Comment by biodranik** [comment]
> Is Cloudflare dropping the connection due to strict anti-abuse settings?
@jomo we didn't enable any strict checks there.

**Comment by hamlet** [comment]
> Can you please try again now?

Still stuck at 0%...

**Comment by groovenectar** [comment]
> Can you please try again now?

I went ahead and tried again too... Also stuck at 0%... This time disabling custom DNS didn't seem to do it either

**Comment by Termuellinator** [comment]
> @hamlet just try to allow Internet access for Downloading Manager (in Blokada or whatever firewall you are using) and then download maps :)

I can confirm that when download-manager is blocked (in af-wall in my case), only the worldmap can be downloaded - thanks to this issue i came to that solution :+1: 
Maybe fire a message if there is no progress for a while to check that for people not coming to github to check for issues?

**Comment by biodranik** [comment]
We have finally found a solution. In the next update download should work without Download Manager!

**Comment by biodranik** [comment]
The issue is fixed in all stores except FDroid, there are some strange build errors there.

**Comment by hamlet** [comment]
It works with the last update from fdroid! 
Thanks a lot.
