### ISSUE TITLE
Buttons missing when selecting bookmarks

### ISSUE THREAD

**Issue by Buntbart** [organicmaps/organicmaps#4742]
The buttons "Route from", " Save/Delete",  "Route to" and "Share" don't appear when selecting a bookmark from the list.

**Steps to reproduce**
1. Go to bookmarks
2. Click on a bookmark, it is shown on the map
3. Button "Route to" is missing

**Expected behavior**
Button "Route to", " Delete", "Route from" and "Share" should appear to do something with the bookmark.

**System information:**
 - Operating system Android 11 (LineageOS 18.1) without Google spyware
 - Organic Maps version: 2023.02.13-11-FDroid
 - Device Model: Samsung S5 klte

**Comment by Altonss** [comment]
This might be a duplicate issue of https://github.com/organicmaps/organicmaps/issues/1927

**Comment by Buntbart** [comment]
You are right, and it's the same device! I'll close this one.
