### ISSUE TITLE
Routing engine prefers local roads to dual carriageway

### ISSUE THREAD

**Issue by shompoe** [organicmaps/organicmaps#477]
Hi,

I am just curious as to why the app wants to take me off a dual carriageway onto a local road which meanders left and right etc. before crossing back over the same dual carriageway at a junction that is within within 0.2 miles of my destination. Surely just staying on the dual carriageway has to be a lot quicker and simpler.

![Screenshot-2021-06-01-18-01-28](https://user-images.githubusercontent.com/54352351/120363692-58152b80-c304-11eb-94ef-992aea7cb740.jpeg)

I'm not sure how I can send you the start and end points of my route.

**Comment by biodranik** [comment]
1. Can you please confirm that you don't have any specific route options/restrictions enabled in the app? They are located in Settings => Routing options.
2. Please check the same route online here and let us know if it works or not: http://map.project-osrm.org/

It may be a bug in OpenStreetMap data, and if so, the best way is to make a map note for OSM contributors with a detailed description.
It may also be a bug in our code, we'll try to reproduce it if you confirm that it works online at the above link.

**Comment by shompoe** [comment]
> Can you please confirm that you don't have any specific route options/restrictions enabled in the app? They are located in Settings => Routing options.
> I have not changed any of the settings under routing options. If I had (I just tried it) there would be a warning at the top when I took the screenshot right?> Please check the same route online here and let us know if it works or not: > http://map.project-osrm.org/
>
>
> It seems to work as I would expect on this website.
>
> I just tried again to confirm in the app, and now that is also working as I would expect, with the same start point and detination.>  
>
>
>
The only thing that has changed is that I had downloaded some additional maps. So I deleted them and was then able to recreate the problem. Even though the required route does not go off of the downloaded map it appears other maps are required to be present anyway.

**Comment by biodranik** [comment]
Wow, that's an issue. Can you please share with us the name of the map where we can reproduce the bug, and name(s) of other maps, which fix the bug when they are downloaded?

@vng you'll like that one ;-)

**Comment by shompoe** [comment]
Name of the map where we can reproduce the bug, 

United Kingdom/East of England - Essex
name(s) of other maps, which fix the bug when they are downloaded.

United Kingdom/South East England - Oxford.

**Comment by RedAuburn** [comment]
this is still an issue, but i've found the cause!

this small section of the motorway seems to be in the oxford mwm, not the essex one, causing a break in the motorway: https://www.openstreetmap.org/way/24335445

![signal-2023-11-01-215637_002](https://github.com/organicmaps/organicmaps/assets/26939824/2eabcf7d-0a91-413b-a6be-52833daede6a)

i guess the easiest fix would be to adjust the mwm border

**Comment by biodranik** [comment]
Can you please edit it? Check data/borders

**Comment by RedAuburn** [comment]
> Can you please edit it? Check data/borders

already on it 😉
