### ISSUE TITLE
[Android] Zoom center changes after selecting POI

### ISSUE THREAD

**Issue by Misalf-git** [organicmaps/organicmaps#4782]
After selecting a POI and thereby opening its place page, the zoom center is correctly shifted upwards (depending on the size of the place page) to zoom in/out according to the now limited map view.

After closing the place page, the zoom center is not reset.

https://user-images.githubusercontent.com/72605561/225057642-e85b0aee-000e-4eb6-9422-fe4e19ac2ded.mp4

OMaps 2023.03.05-5-Web

**Comment by biodranik** [comment]
Why and how should it be reset? An additional "map jump" back when Place Page is closed will be annoying to users, no?

**Comment by Misalf-git** [comment]
There is no map-jumping involved.

May I lead your attention to where the map is zooming into before, while and after the place page is selected, please.

Shouldn't the "center of zoom" be set to the middle of the visible map, just like it's done when a place page is visible?

Currently, it only resets to the middle after rotating the screen, but de-selecting the POI should be enough.

Or, in other words, the zooming behaves as if the last visible place page was still visible.

**Comment by biodranik** [comment]
Thanks, now I see it. It reproduces only with + and - zoom buttons, right?

**Comment by Misalf-git** [comment]
Yes.
AFAICT, gestures work consistantly (d ouble-tab zoom-in, two-finger-tab zoom-out and pinching).
I don't know of any other possible methods.

**Comment by Misalf-git** [comment]
Another glitch caused by this when resetting map rotation by pressing the compass button.
https://user-images.githubusercontent.com/72605561/225293567-8d08faab-41d1-4d15-b282-6df53adc486d.mp4

**Comment by Misalf-git** [comment]
Seems to be fixed.
I guess by #4863 .
