### ISSUE TITLE
Verify the flathub flatpak package

### ISSUE THREAD

**Issue by Altonss** [organicmaps/organicmaps#4793]
Maybe it would be cool to verify the flathub flatpak package like explained here: https://beta.flathub.org/about.
This would add a "verified" checkmark certifying that the package uploaded is coming from the official organicmaps team :)

**Comment by Altonss** [comment]
Maybe ping @Ferenc- and @biodranik :)

**Comment by biodranik** [comment]
I don't have flathub login for OM :)

**Comment by Ferenc-** [comment]
![Screenshot from 2023-03-18 17-39-44](https://user-images.githubusercontent.com/6553695/226120686-144a6ef5-b328-46d6-89f0-d17c9a2b7ed8.png)
Done.

**Comment by Altonss** [comment]
Thank you :)
