### ISSUE TITLE
[iOS] List description isn't showing anywhere in the app

### ISSUE THREAD

**Issue by BelKed** [organicmaps/organicmaps#4799]
**Describe the issue**
The list description isn't showing anywhere in the app.

---

**Expected behaviour**
I assume the description should be shown under the list title where is the blue text `DESCRIPTION` located.

---

https://user-images.githubusercontent.com/66956532/225744810-7b9a28cb-48ff-4918-8dfc-f1bece9310f9.mp4

---

**System information:**
 - Operating system and its version: iOS 16.3.1
 - Organic Maps version: `2023.03.02-1`
 - Device Model: iPhone SE 2020

---

**Additional context**
After unzipping the KMZ file, we can see the description data is saved there, so it's just a visualisation problem, I assume:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.2">
<Document>
…
  <name>Test</name>
  <description>List description</description>
…
```

**Comment by biodranik** [comment]
Looks like previously another dialog opened with a rich html description, likely with images. 

It would be great to show a limited size preview of the description and expand it on tap/clicking ...more button if necessary.
