### ISSUE TITLE
[iOS] Failed to load bookmarks (cold start)

### ISSUE THREAD

**Issue by BelKed** [organicmaps/organicmaps#4800]
**Describe the issue:**
Importing a valid bookmark files to a closed **Organic Maps** application fails.
Opening the **Organic Maps** application (keeping it open in the background) before importing the bookmarks fixes the issue.

---

**Steps to reproduce:**
1. Export a bookmark from the **Organic Maps** app to the **Files** app
2. Find the file in the **Files** app
3. Click on *Share* button and select **Organic Maps** app
4. The import fails

---

**Expected behaviour:**
The bookmark file should import successfully.

---

**Screenshots:**
<p align=center>
<img width="49%" src="https://user-images.githubusercontent.com/66956532/225750563-956aec00-a2ef-453c-b603-e22396d2cc2c.PNG">
<img width="49%" src="https://user-images.githubusercontent.com/66956532/225750960-1a797c1f-aa08-43fe-aadd-d7e89f415b44.PNG">
</p>

---

**System information:**
 - Operating system and its version: iOS 16.3.1
 - Organic Maps version: `2023.03.02-1`
 - Device Model: iPhone SE 2020

---

**Additional context:**
Probably related to https://github.com/organicmaps/organicmaps/issues/3012

**Comment by biodranik** [comment]
Does it fail with files that contain non-ascii symbols? I assume that it is related to #4759

**Comment by BelKed** [comment]
Nope, non-ASCII works fine. I’ve emoji and some other stuff in those bookmarks and they import without any problem.

**However, the app must be open in the background.**

**Comment by BelKed** [comment]
I’ve installed the latest version (`2023.06.04-12`), but the issue still persists…

**Comment by biodranik** [comment]
Looks like the import fails on the cold start if KML/KMZ/GPX file is imported from Files app, but doesn't fail on the cold start if imported from any other app.

Internally, opening the file by path fails here:
```
  ifstream ifs;
  ofstream ofs;
  ifs.exceptions(ifstream::failbit | ifstream::badbit);
  ofs.exceptions(ifstream::failbit | ifstream::badbit);

    ifs.open(fOld.c_str());  // open file fails here

```

@BelKed can you please confirm it?

**Comment by BelKed** [comment]
Yup, it’s exactly as you’ve written :)
Import from the Files app fails, but from other apps works fine.
Any idea what could be causing that?

**Comment by biodranik** [comment]
The only idea is that we try to load file before OM finishes initialization. That finished initialization is likely providing some permissions to OM to access the file.

**Comment by andrewtavis** [comment]
Thanks for opening the issue and providing the work around of keeping OM open in the background, @BelKed! Was very confused for a sec with the `The file may be corrupted or defective.` error for a file I was getting from OM on another device :) All 811 pins and their colors successfully transferred! 

And thanks for all the hard work here, @biodranik 🙏 Was a bit put off by the new four button with transparency design vs. tab bar, but now really like being able to see more of the map 😊
