### ISSUE TITLE
amenity=parking renders below amenity=hospital

### ISSUE THREAD

**Issue by jmarchon1** [organicmaps/organicmaps#4802]
**Describe the issue**
The pink color of amenity=hospital renders over the yellow of amenity=parking. The P's still show up, but not the areas. 

**Steps to reproduce**
1. Go to anywhere where there is an amenity=hospital area and an amenity=parking area.
2. See error

**Expected behavior**
I expected the yellow amenity=parking areas to show up above the amenity=hospital area, like they do everywhere else.

**Screenshots**
In Organic Maps:
![Screenshot_20230316-184229](https://user-images.githubusercontent.com/50030493/225791411-97c185c5-9ae2-4a9e-b0d6-c4a7f54ae699.png)

On osm.org:
![map](https://user-images.githubusercontent.com/50030493/225791441-2c37d904-3147-4664-a49e-1f70878646ab.png)

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.03.05-5-Google
 - Device Model: Pixel 6a

**Comment by pastk** [comment]
https://www.openstreetmap.org/way/584462990

Looks like mismapping to me - `amenity=hospital` is tagged as `layer=1` (and I see no reason for it), while all the inside features are without a `layer` tag. Hence hospital grounds pink fill is rendered "on top" of parkings, gardens etc..

**Comment by jmarchon1** [comment]
Oops, I didn't notice the layer tag. I've removed it so this issue can be resolved. Thanks!
