### ISSUE TITLE
Add feature to test TTS in settings

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4824]
**Is your feature request related to a problem? Please describe.**
Somes users have troubles with Text-To-Speech especially with ungoogled devices, i think we can add in settings, a feature to test TTS before users used routing

**Describe the solution you would like**
Add in TTS settings an option to play sound with TTS

**Describe alternatives you have considered**
Google Maps have similar option in routing options
<img src="https://user-images.githubusercontent.com/87148630/226439732-5b844d5e-45bb-40aa-8067-c7192177f411.png" height=400 />

**Comment by pranjalsrv123** [comment]
@Jean-BaptisteC Can you make me assignee of this issue ? I can add TTS setting ?

**Comment by Jean-BaptisteC** [comment]
Don't ask to work on issue
https://github.com/organicmaps/organicmaps/blob/master/docs/CONTRIBUTING.md#code-contributions

**Comment by satvik2131** [comment]
@Jean-BaptisteC  Yes , I also believe it so that we should add a separate panel for that , could you guide me like what features should we add , like should we add any additional features compare to google maps , or similar to gmaps is ok ?

**Comment by Jean-BaptisteC** [comment]
Button to test TTS can be add in TTS settings

**Comment by meenbeese** [comment]
Can be closed with #5859 being merged @Jean-BaptisteC ?
