### ISSUE TITLE
[android] Bookmark's list description doesn't get updated immediately

### ISSUE THREAD

**Issue by unsuman** [organicmaps/organicmaps#4826]
**Describe the issue**
Description of bookmark's list getting updated only after reopening the list but not instantly after saving.

**Steps to reproduce**
1. Go to 'Bookmarks'.
2. Click on a list.
3.  Open list settings.
4. Add or change the description and save.
5. Go back and reopen the list, changes are made.

**Expected behavior**
It should save the changes and be visible instantly.

**ScreenRecord**

https://user-images.githubusercontent.com/79016311/226468280-2dfbd23d-2a75-4c98-860d-adbb846f8dec.mp4

**System information:**
 - Operating system and its version: Android 9
 - Organic Maps version: 2023.03.19-2-FDroid
 - Device Model: Redmi 6 pro

**Comment by lapaz17** [comment]
@biodranik  What does '...more' *blue* title do there?

**Comment by ANS-UXI** [comment]
> @biodranik  What is the function of '...more' *blue* title over there?

It expands a long description view, but currently it is not working!
