### ISSUE TITLE
Cycle routing avoids cycleway=shared_lane

### ISSUE THREAD

**Issue by Robot8A** [organicmaps/organicmaps#4837]
**Describe the issue**
Bicycle routing avoids at all costs ways tagged with cycleway=shared_lane. See https://www.openstreetmap.org/way/79206847 for the way involved in the screenshots

**Steps to reproduce**
Select origin and destination, bicycle route. Make route involve a street tagged with cycleway=shared_lane.

**Expected behavior**
Routes through cycleway=shared_lane at some instances where that makes sense.

**Screenshots**
![image](https://user-images.githubusercontent.com/19521377/227061384-928833c7-8c19-413d-93ae-a660668bf304.png)
![image](https://user-images.githubusercontent.com/19521377/227061862-b5d4af9c-6b9b-4641-81c4-4e4aa0a7fc17.png)

**System information:**
 - Operating system and its version: iOS 16.3.1
 - Organic Maps version: 2023.03.02-1
 - Device Model: iPhone XR

**Additional context**
- Seems like it prefers going through the sidewalk, entering a parking garage, anything but routing through a cycleway=shared_lane

**Comment by biodranik** [comment]
I think the reason is that cycleway=shared_line is not yet supported by OM. @vng right?

**Comment by vng** [comment]
https://wiki.openstreetmap.org/wiki/Tag:cycleway%3Dshared_lane

**Comment by vng** [comment]
Interesting ...
Actually, the app takes cycleway=shared_line as allowed for bicycles. Check this [way](https://www.openstreetmap.org/way/149303976)

The problem with bicycle routing on "Paseo de la Independencia" and nearby is that there are a bunch of highway=crossing with bicycle=no tag. The app interprets it as "bicycles are not allowed to cross this node". And there is a lot of such kind of crossings mapped in that area. Can't say for sure if it is a valid mapping or not.

@Robot8A Do you familiar with that area? Maybe you know the sense of bicycle=no for the highway=crossing?

**Comment by Robot8A** [comment]
Yes, I am familiar with the area. My guess is that the mapper thought that adding bicycle=no means that the crossing is just for pedestrians, and not a bicycle-pedestrian crossing. But for sure bicycles are allowed to use the road! Good catch, I didn't realize about that!

**Comment by vng** [comment]
Ok, I see. Will add a generator workaround for this case.

**Comment by biodranik** [comment]
Am I correctly understanding that OSM data is correct here and it is an OM issue? Because if it's not, then it would be great to spread this info between OSMers.

**Comment by vng** [comment]
Looks like it's fancy, but still valid mapping.

**Comment by matkoniecz** [comment]
> My guess is that the mapper thought that adding bicycle=no means that the crossing is just for pedestrians, and not a bicycle-pedestrian crossing.

That is what `highway=crossing bicycle=no` means.
