### ISSUE TITLE
What 3 words

### ISSUE THREAD

**Issue by dj4oC** [organicmaps/organicmaps#4846]
I'm always frustrated when someone tells me an address on phone and I need to understand it very precise.

What three words has a handy solution for that. If I could use it in search and location information it would be very helpful to communicate with other people. 

**Describe alternatives you have considered**
- How do you solve this issue now with Organic Maps or other apps?
I use a different app

**Comment by biodranik** [comment]
Please check https://github.com/organicmaps/organicmaps/issues/3437
