### ISSUE TITLE
Fix floating button in navigation in RTL

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4850]
<img src="https://user-images.githubusercontent.com/87148630/227594104-988b1225-8ba6-440c-b123-448d04a06b73.png" height=400 /><img src="https://user-images.githubusercontent.com/87148630/227594208-b0170ccb-7204-4ece-8d83-42cb21cb64a8.png" height=200 />

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.03.05-5-Google
 - Device Model: Pixel 6

CC @arnaudvergnet

**Comment by rtsisyk** [comment]
Oh, this is really weird...

**Comment by biodranik** [comment]
@arnaudvergnet we can either make all layout elements take RTL into an account, or postpone it for now, and use LTR layout for all elements (e.g. for the bottom bar that moved to the right now).

If it's easy to "mirror" everything, then it should just work, right?

**Comment by Jean-BaptisteC** [comment]
Problem is caused by https://github.com/organicmaps/organicmaps/blob/master/android/app/src/main/res/layout/map_buttons_search_frame.xml, floating button doesn't support rtl and search button overlays credit card button.
