### ISSUE TITLE
A caption displayed before an icon

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#4854]
Usually icons are displayed first and after some more zooming in a caption appears also.

But there are several types where its vice versa and seems to be a bug?
```
landuse-forest                :	 caption z12-	icon z13-
leisure-beach_resort          :	 caption z15-	icon z16-
railway-subway_entrance       :	 caption z16-	icon z17-
railway-subway_entrance-adana :	 caption z16-	icon z17-
...(most entrances)
shop                          :	 caption z16-	icon z18-
shop-antiques                 :	 caption z16-	icon z18-
shop-art                      :	 caption z16-	icon z18-
shop-baby_goods               :	 caption z16-	icon z18-
shop-bag                      :	 caption z16-	icon z18-
shop-boutique                 :	 caption z16-	icon z18-
shop-cheese                   :	 caption z16-	icon z18-
shop-coffee                   :	 caption z16-	icon z18-
shop-craft                    :	 caption z16-	icon z18-
shop-electrical               :	 caption z16-	icon z18-
shop-paint                    :	 caption z16-	icon z18-
shop-pawnbroker               :	 caption z16-	icon z17-
shop-variety_store            :	 caption z16-	icon z18-
...(many shops w/o a dedicated icon)
```

![caps-before-icons](https://user-images.githubusercontent.com/18434508/227701953-bc7bb9c5-877f-4988-82b1-24f34504fa18.png)

**Comment by biodranik** [comment]
What does `git blame` say? I assume that for shops and entrances it was specifically tuned for bigger cities.

**Comment by pastk** [comment]
Visibility for generic shops icons was reduced from z16- to z18-, but the caption visibility left intact. https://github.com/organicmaps/organicmaps/pull/3985 @vng do you remember why?

Subway entrances were made like this as a part of a big refactoring, there is no more info.. f40a61a1242fc22e69a66dbd89f401a366a709e2

**Comment by vng** [comment]
"... , but the caption visibility left intact". Looks like a bug.

**Comment by pastk** [comment]
Current subway entrances behavior:
![subway-entrances](https://user-images.githubusercontent.com/18434508/227930064-a006146e-f949-4e09-8cc9-8d00c8c2ec4e.png)
A caption is being confusingly displayed before an icon - it takes more space than an icon and its hard to understand its for the subway entrance.
Luckily its quite a rare case because usually those icon-less caption is being displaced by surrounding POIs.
I think I'll just remove captions from z16, so both icon and caption will be displayed from z17.

Same for named forests.
Its better to replace a lone caption on z12 with an icon - it'll take less space.
![named-forest](https://user-images.githubusercontent.com/18434508/227930954-5dd120b6-98eb-4ec3-a6bc-0211b009aea7.png)

**Comment by vng** [comment]
Please fix it. IMO, the entrance should show an icon on the first zoom levels (z16-), and an icon + a caption on the last zoom only (z18-z19).

**Comment by pastk** [comment]
> Please fix it. IMO, the entrance should show an icon only on the first zoom levels (z16-), and an icon + a caption on the last zooms only (z18-z19).

I think for an "ordinary" subway system (not e.g. Spb for which we have separately tuned rules) its better to start display subway entrances on z17 only, e.g. look at the Sofia screenshot above - the entrances look quite crowded on z17 even, on z16 its going to be too dense for the most of the cases...

**Comment by pastk** [comment]
> Please fix it. IMO, the entrance should show an icon only on the first zoom levels (z16-), and an icon + a caption on the last zooms only (z18-z19).

I think for an "ordinary" subway system (not e.g. Spb for which we have separately tuned rules) its better to start display subway entrances on z17 only (its kind of the current behavior given that the captions are usually not displayed at z16), e.g. look at the Sofia screenshot above - the entrances look quite crowded on z17 even, on z16 its going to be too dense for the most of the cases...

**Comment by biodranik** [comment]
Is your desktop picture correspond to your mobile picture? Does testing how it looks on desktop definitely correlates with how it looks on mobiles?

**Comment by pastk** [comment]
> Is your desktop picture correspond to your mobile picture? Does testing how it looks on desktop definitely correlates with how it looks on mobiles?

In the cases above - yes, its the same.
