### ISSUE TITLE
Android: View is Off-Center during navigation

### ISSUE THREAD

**Issue by bitboy85** [organicmaps/organicmaps#4855]
This is since the last update i think. The arrow is shown at the very top of the screen. Best would be to show it in the lower third to see a maximum of the upcoming way.
![20230314_090226](https://user-images.githubusercontent.com/6197580/227719766-015917a3-9e12-42c3-954f-89177b0339fa.jpg)

**Comment by biodranik** [comment]
The same as in #4794

@rtsisyk can https://github.com/organicmaps/organicmaps/pull/3462 fix it?

**Comment by biodranik** [comment]
@bitboy85 what is your Android version?

**Comment by bitboy85** [comment]
Android version is 5.1.1.

**Comment by biodranik** [comment]
It reproduces on my Android 8 too:
1. Rotate to the landscape.
2. Build driving route (notice related issue here: the route is not centered on the screen, we might need to create another issue for it)
3. Start navigation.
