### ISSUE TITLE
[styles] Add icons for different artwork types

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#4858]
Currently, all `tourism=artwork` is rendered with a generic star.

It would be better to have different icons depending on the artwork type.
in particular, `artwork_type=statue` really needs its own icon.

see https://wiki.openstreetmap.org/wiki/Key:artwork_type for more types

**Comment by patepelo** [comment]
![image](https://github.com/organicmaps/organicmaps/assets/23003127/be28aa77-a79d-49d8-84d2-065795c4042c)
This are some examples

**Comment by dvdmrtnz** [comment]
As pointed out by @patepelo, currently [`tourism=artwork`](https://wiki.openstreetmap.org/wiki/Tag:tourism=artwork), [`tourism=attraction`](https://wiki.openstreetmap.org/wiki/Tag:tourism=attraction) and [`place=square`](https://wiki.openstreetmap.org/wiki/Tag:place=square) use the same generic star icon:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/efdf6ece-b0b4-4180-b2ba-43d7095a254c" width="36"/>

I think that we can keep the star icon for the `tourism=attraction` features and try to find some new icons for `tourism=artwork` and `place=square`.

**Comment by dvdmrtnz** [comment]
OSM Carto uses this generic artwork for `tourism=artwork`:
  
![](https://github.com/organicmaps/organicmaps/assets/47610359/1e867faa-5953-4d91-8065-4ada70e67f0e)

**Comment by dvdmrtnz** [comment]
The most frequently used `artwork_type=*` are:

![imagen](https://github.com/organicmaps/organicmaps/assets/47610359/7644ad1e-a3ef-4ea4-90c9-2665c17c1bcf)

https://taginfo.openstreetmap.org/keys/artwork_type#values

**Comment by RedAuburn** [comment]
> The most frequently used `artwork_type=*` are:
> 
> ![imagen](https://user-images.githubusercontent.com/47610359/267373500-7644ad1e-a3ef-4ea4-90c9-2665c17c1bcf.png)
> 
> https://taginfo.openstreetmap.org/keys/artwork_type#values

dwarf?? 🤔

**Comment by dvdmrtnz** [comment]
Proposal for `tourism=artwork`:
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/82c2df4c-f2d9-40c0-b760-6008643e0837" width="32"/>

Proposal for `tourism=artwork + artwork_type=statue`:
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/5b52c4c9-166a-4328-aeb6-ed0fae01e5a5" width="32"/>

**Comment by RedAuburn** [comment]
looks good, but i think they shouldn't be in a circle :)

**Comment by biodranik** [comment]
Definitely not in a circle, they're not businesses/amenities.

**Comment by dvdmrtnz** [comment]
You're right! Without circles:
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/522778cb-464e-47fe-b0cb-646badbe4574" width="32"/>
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/7418bc13-5e55-4e50-9ed7-fb95d05c78a8" width="32"/>

**Comment by biodranik** [comment]
It would be better to see icons on the map with the context, and also in the dark mode )

**Comment by dvdmrtnz** [comment]
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/8ba12b3a-c01f-48d7-a2bd-645e0b24d4a6" width="320"/>
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/5d52a626-24a2-41d3-a42d-2858ee10edc8" width="320"/>

**Comment by patepelo** [comment]
It seems really great. Is indeed an improvement. Maybe I would make the torso just a little bit more thick. Althoug this would work as well in my opinion, since statues shouldn't take much protagonism on such a map.
