### ISSUE TITLE
Search bookmarks

### ISSUE THREAD

**Issue by aronkvh** [organicmaps/organicmaps#4872]
Since you can rename bookmarks, (for consistency too) you should be able to search the custom name and it should have top priority in search.
You might add a friend's adress, home, work and many other 'nicknames' for bookmarks.

**Comment by biodranik** [comment]
Duplicate of #808 

Now you can search bookmarks when opening their lists.

**Comment by aronkvh** [comment]
I meant the general search should take into account custom names you gave bookmarked places, not the same as #808 (?)

**Comment by biodranik** [comment]
Why is it not the same? Search box is the general search box. What another search box did you have in mind?

**Comment by aronkvh** [comment]
If I press the search button from the main view (without clicking on
favourite and the list name) it doesn't take bookmarks into account

Alexander Borsuk ***@***.***> ezt írta (időpont: 2023. márc.
28., K 19:35):

**Comment by biodranik** [comment]
Exactly. And the issue I mentioned is to change this behavior.
