### ISSUE TITLE
Use 5 buttons on the bottom toolbar instead of 4 + More menu

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4887]
After the latest refactoring "add stop" button was swapped with "add bookmark" button when a route is built (select any point on the map and press route to first):

Before:
[1 route from] [2 add bookmark] [3 route to] [4 more menu with add stop and share]

After:
[1 route from] [2 add stop] [3 route to] [4 more menu with add bookmark and share]

While it is convenient to build a route now, it is inconvenient to add bookmarks in the process, and some users started to complain.

A better option is to always show 5 buttons:
More like it is now on the main map: [1 route from] [2 add bookmark] [3 route to] [4 add stop] [5 share]
or 
Like it is now after refactoring, highlighting the add stop: [1 route from] [2 add stop] [3 route to] [4 add bookmark] [5 share]

Texts and icons should be properly formatted, see #4545, that was the main blocker why 5 buttons didn't get into the release yet.

**Comment by Jean-BaptisteC** [comment]
@biodranik can be close, share button has been moved to place page?

**Comment by biodranik** [comment]
Yes, let's close it for now. Maybe we'll return back to 5 buttons later...
