### ISSUE TITLE
Action bar under bottomsheet is locked

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4903]
Requirements:
- Location disabled
- Google Play Services enabled on OM settings

**Steps to reproduce**
1. Start OM
2. Select POI
3.  Use button route to -> pop-up to search location with Google Play Services is shown
4. Deny pop-up ->wrong action bar stay at the bottom (we need to select other POI and leave place page to remove action bar)

**Screenshots**
In normally case (with Google Play Services disabled, OM show clickable bottom bar to add start point)
<img src="https://user-images.githubusercontent.com/87148630/229310613-06ee531d-09b9-4ed5-b68b-599335e93a40.png" height=400 />

In my case, OM keep at the bottom action bar used with place page
<img src="https://user-images.githubusercontent.com/87148630/229310655-142105fb-b652-45ed-b517-707b1d5a6a7a.png" height=400 />

Logs:
```
2023-04-01 21:27:19.611  5297-5297  PlacePageController app.organicmaps E  onStateChanged(): Called in the wrong activity state=STARTED
2023-04-01 21:27:19.616  5297-5297  PlacePageController app.organicmaps E  onSlide(): Called in the wrong activity state=STARTED
```

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.03.05-5-Google (reproduced on 2023.03.31-4-Google-beta)
 - Device Model: Pixel 6

CC @arnaudvergnet

**Comment by Jean-BaptisteC** [comment]
Used web version or Google Version
Google Play Services is enabled by default

**Comment by biodranik** [comment]
@n1snt FDroid build doesn't have GP services. If you build app locally, please use `web` flavor, e.g. `gradle installWebDebug`

**Comment by arnaudvergnet** [comment]
This popup is a native one, so it puts the app in "Pause" state, or since recent refactorings we stop the place page logic (and thus detecting when to hide the buttons) in the "onPause" event. You can see the same behavior if you press the "share" button and hide the place page at the same time. The fix should be easy enough, I'll try to include it in https://github.com/organicmaps/organicmaps/pull/4808
