### ISSUE TITLE
Build Error for Desktop App on Mac M1

### ISSUE THREAD

**Issue by YBSOHN** [organicmaps/organicmaps#4908]
When I tried building a desktop app on my M1 macbook using the command

``tools/unix/build_omim.sh -r desktop``

I received the following error.

<img width="818" alt="Screenshot 2023-04-02 at 8 15 34 AM" src="https://user-images.githubusercontent.com/19337129/229355135-9b7e7e63-d44e-49b3-a329-1ad58a5f17c0.png">

I would like to receive help on this error. Thank you.

**System information:**
 - Operating system and its version: macOS Ventura 13.2.1
 - Device Model: M1 MacBook Pro

**Comment by endim8** [comment]
Try cleaning the build files with 'tools/unix/build_omim.sh -c'

**Comment by YBSOHN** [comment]
I am still receiving the same error. But thanks for the suggestion.

**Comment by endim8** [comment]
Damn, maybe you haven't checked out the submodules? Try `git submodule update --init --recursive`

**Comment by biodranik** [comment]
You did not provide the details about the error (log lines above those on the screenshot). It is hard to guess why your linker has failed.

**Comment by YBSOHN** [comment]
I managed to solve this issue by using Rosetta 2 to run x86_64 binaries. I added ```set(CMAKE_OSX_ARCHITECTURES "x86_64")``` to the CMakeLists file so that it compiles for x86_64. Would it be helpful to mention this in the install.md?

**Comment by biodranik** [comment]
Organic Maps should build and work fine on arm M1 processors without Rosetta. It would be great if you share the original linker error so the issue could be fixed, instead of doing a (slow!) workaround with the x86_64 emulation.

**Comment by YBSOHN** [comment]
Yes. I received the following errors without Rosetta.

```batchfile
[222/222] Linking CXX executable OMaps.app/Contents/MacOS/OMaps
FAILED: OMaps.app/Contents/MacOS/OMaps 
: && /Library/Developer/CommandLineTools/usr/bin/c++ -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -mmacosx-version-min=13.2 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -fcolor-diagnostics qt/CMakeFiles/desktop.dir/desktop_autogen/mocs_compilation.cpp.o qt/CMakeFiles/desktop.dir/Unity/unity_0_cxx.cxx.o -o OMaps.app/Contents/MacOS/OMaps  -Wl,-rpath,/Users/yb/opt/anaconda3/lib  libgenerator.a  libqt_common.a  libmap.a  libgflags_nothreads.a  libtess2.a  librouting.a  libdescriptions.a  libkml.a  libdrape_frontend.a  libtransit.a  libtraffic.a  librouting_common.a  libshaders.a  libdrape.a  libsearch.a  libindexer.a  libeditor.a  libsearch.a  libindexer.a  libeditor.a  libstorage.a  libmwm_diff.a  libbsdiff.a  libge0.a  libopenlocationcode.a  libprotobuf.a  libopening_hours.a  libpugixml.a  libplatform.a  -framework Foundation  -framework SystemConfiguration  -framework CoreLocation  -framework CFNetwork  libcoding.a  libcppjansson.a  3party/jansson/jansson/lib/libjansson.a  libexpat.a  -lm  libsuccinct.a  liboauthcpp.a  libminizip.a  libgeometry.a  libbase.a  libicui18n.a  libicuuc.a  libfreetype.a  /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/lib/libbz2.tbd  /opt/homebrew/lib/libpng.dylib  /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/lib/libz.tbd  /opt/homebrew/Cellar/brotli/1.0.9/lib/libbrotlidec.dylib  libvulkan_wrapper.a  libstb_image.a  libsdf_image.a  -framework OpenGL  libagg.a  /Users/yb/opt/anaconda3/lib/libQt5Widgets.5.9.7.dylib  /Users/yb/opt/anaconda3/lib/libQt5Gui.5.9.7.dylib  /Users/yb/opt/anaconda3/lib/libQt5Core.5.9.7.dylib && :
ld: warning: ignoring file /Users/yb/opt/anaconda3/lib/libQt5Widgets.5.9.7.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Users/yb/opt/anaconda3/lib/libQt5Gui.5.9.7.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Users/yb/opt/anaconda3/lib/libQt5Core.5.9.7.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "qt_qFindChild_helper(QObject const*, QString const&, QMetaObject const&, QFlags<Qt::FindChildOption>)", referenced from:
      EditorDialog::OnSave() in unity_0_cxx.cxx.o
      qt::OsmAuthDialog::OnAction() in unity_0_cxx.cxx.o
      qt::SwitchToLogin(QDialog*) in unity_0_cxx.cxx.o
      qt::SwitchToLogout(QDialog*) in unity_0_cxx.cxx.o
  "qRegisterResourceData(int, unsigned char const*, unsigned char const*, unsigned char const*)", referenced from:
      qInitResources_resources() in unity_0_cxx.cxx.o
      __GLOBAL__sub_I_unity_0_cxx.cxx in unity_0_cxx.cxx.o
      qInitResources_resources_common() in libqt_common.a(unity_0_cxx.cxx.o)
      __GLOBAL__sub_I_unity_0_cxx.cxx in libqt_common.a(unity_0_cxx.cxx.o)
  "qUnregisterResourceData(int, unsigned char const*, unsigned char const*, unsigned char const*)", referenced from:
      qCleanupResources_resources() in unity_0_cxx.cxx.o
      (anonymous namespace)::initializer::~initializer() in unity_0_cxx.cxx.o
      qCleanupResources_resources_common() in libqt_common.a(unity_0_cxx.cxx.o)
      (anonymous namespace)::initializer::~initializer() in libqt_common.a(unity_0_cxx.cxx.o) ...
``` 
[error.txt](https://github.com/organicmaps/organicmaps/files/11138234/error.txt)

**Comment by biodranik** [comment]
What is anaconda3 and why do you use Qt from there? Looks like that version of Qt does not work well for arm. Did you try to install qt@5 from brew?

**Comment by YBSOHN** [comment]
I was able to build without Rosetta when I didn't use Python libraries from Anaconda. However, I received the following warnings:

ld: warning: ignoring file /opt/homebrew/Cellar/brotli/1.0.9/lib/libbrotlidec.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/lib/libpng.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64

**Comment by biodranik** [comment]
There is still some library or build command that incorrectly links to x86. Maybe checking the full build log can help.
