### ISSUE TITLE
Wikipedia links are missing

### ISSUE THREAD

**Issue by ddpasa** [organicmaps/organicmaps#4912]
**Describe the issue**

This is a newly introduced issue that I noticed in the current version (2023.03.05-5-FDroid) as well as the current beta (2023.04.02-7-android).

There are two sources of wikipedia information: one from OrganicMaps for the in-app feature, the other from OpenStreetMaps.  The links appear to be missing when they are in OpenStreetMaps, but not in OrganicMap's in-app feature.  This was not the case before, it looks like a recent change that happened in the last few releases.

I tested this for Android, I don't know about iPhone.

For example, this POI has a wikipedia page: https://www.openstreetmap.org/node/1908362611
It used to be present in previous versions, but not in the most recent version.

![Screenshot_20230403-195319019 (1)](https://user-images.githubusercontent.com/112642920/229588958-78acf739-b7c2-45c2-b83b-f455a3326d2a.jpg)

It might be introduced in this commit, but I'm not sure yet: https://github.com/organicmaps/organicmaps/commit/5e93fcc47648562ef9ec618edb9a5abe89743b26 (Edit: I'm 80% sure this commit is the reason.  It shows the wiki link only when the in-app feature database contains the wiki entry, but not otherwise.  This means that any wiki link on OSM will be ignored.)

**Comment by endim8** [comment]
good catch!

**Comment by ddpasa** [comment]
I created a merge request fixing this bug.  I'm testing it now.  On first impression it works ok.  But give me a day to be super-sure.
