### ISSUE TITLE
[android] Support google.com/maps links 

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#492]
See how it is done in OsmAnd: https://github.com/osmandapp/OsmAnd/blob/e4f9a7cea01bf2083e0b800522f445642cf15b3f/OsmAnd/AndroidManifest.xml#L603

**Comment by eighthave** [comment]
https://github.com/guardianproject/LocationPrivacy is a simple, standlone app that parses all kinds of location links. It is probably easier to navigate than Osmand. I'm happy to help too.  LocationPrivacy also does network queries to fetch the location from `goo.gl` short links and things like that.

**Comment by rtsisyk** [comment]
Replaced by #475
