### ISSUE TITLE
Car Routing always avoids mini-roundabouts

### ISSUE THREAD

**Issue by timothywashere** [organicmaps/organicmaps#4924]
When using Organic Maps I often find the car directions take unusual diversions.
It seems to be that it will never route through a highway=mini_roundabout
I am in the UK so they also have direction=clockwise but no other tags.
I can't see any tagging errors on the ways that connect to the mini roundabout, so I can only assume it's the mini-roundabout itself that the app is routing to avoid.

Here are two nodes it always avoids
https://www.openstreetmap.org/node/13139564
https://www.openstreetmap.org/node/275859174

https://youtube.com/shorts/85ByY6ahd7U
https://youtube.com/shorts/_DQjNXeslwg

Using the routers on the OSM website always seems to work.

**Comment by biodranik** [comment]
@vng if routing always avoids them, then it's a critical bug.

**Comment by vng** [comment]
Hm, confirm the bug. At least, not all roundabouts behave like this.
Route (50.4185376, -4.15666796) -> (50.4183476, -4.15058945) works fine.

Suspect that we break road graph connectivity _sometimes_ (depending on coordinates precision) when transforming mini_roundabout Node into circle Feature.

**Comment by Jean-BaptisteC** [comment]
@timothywashere can you check is problem is solved ?

**Comment by timothywashere** [comment]
Hi, it seems good to me. Great job
