### ISSUE TITLE
As a user I want to share my current position as a short locality OLC code

### ISSUE THREAD

**Issue by dpriskorn** [organicmaps/organicmaps#4930]
**Is your feature request related to a problem? Please describe.**
I'm trying to share my position in Nepal with a Nepalese friend who mostly use OLC codes in their everyday life.

**Describe the solution you would like**
generate local codes with a locality for sharing, such as WF8Q+WF Praia, Cabo Verde

**Describe alternatives you have considered**

**Additional context**
See the other OLC issues

**Comment by biodranik** [comment]
See #457
