### ISSUE TITLE
Icons of LDS places of worship

### ISSUE THREAD

**Issue by Xevib** [organicmaps/organicmaps#4931]
**Explaination:**
The LDS (aka mormon) places of worship shouldn't apear with a cross/crucifix as a symbol. 
This problem affects the churches  and temples 

**Possible solutions:**
Other options of icons for the LDS places of worship can be:
- [The Christus](https://en.wikipedia.org/wiki/Christus_(statue))
- [The Moroni Angel](https://en.wikipedia.org/wiki/Angel_Moroni)
- The icon for a regular place of worship

**Additional context:**
To add more context of why the LDS places of whorship should not be represented with the cross I recommend this [Wikipedia article](https://en.wikipedia.org/wiki/Symbolism_in_the_Church_of_Jesus_Christ_of_Latter-day_Saints)

**Examples:**
![temple](https://user-images.githubusercontent.com/2422305/230395881-b8aeaf98-4371-4096-9199-bd3264a08692.jpg)
[Temple of Madrid ](https://www.openstreetmap.org/way/145953136)

![church](https://user-images.githubusercontent.com/2422305/230396024-606852bd-b3be-4cd4-86ac-7b63b974079a.jpg)
[Church](https://www.openstreetmap.org/node/5327615553)

Thank you

**Comment by biodranik** [comment]
Using a separate subtype and different (or more neutral/generic) icon should be ok. Any good license-compatible icons in mind?

**Comment by Xevib** [comment]
@Jean-BaptisteC  on Google Maps 
![photo_2023-04-07_10-14-45](https://user-images.githubusercontent.com/2422305/230570815-47579589-3150-432e-a0f4-8329be3fd01d.jpg)
![photo_2023-04-07_10-15-02](https://user-images.githubusercontent.com/2422305/230570821-83e18532-c00c-45f1-81be-05defcd2eb23.jpg)

**Comment by Xevib** [comment]
@biodranik I don't have any located but I can search one. In wich format you need it and what license would be compatible?

**Comment by biodranik** [comment]
SVG format, more or less consistent with our current icons. For licenses/examples, please check data/copyright.html (or check Copyright in the help menu in Organic Maps app).

**Comment by matkoniecz** [comment]
OSM Carto is simply using generic place of worship icon.

See https://github.com/gravitystorm/openstreetmap-carto/pull/4587/files

Note that `denomination=la_luz_del_mundo` `denomination=iglesia_ni_cristo` `denomination=mormon` also have such preferences.

**Comment by dvdmrtnz** [comment]
Here is an icon that could be used. 

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/8657f531-4435-4742-94cb-5c9b1e827d77" width="35px"/>


Source: Own work, based on this (https://commons.wikimedia.org/wiki/File:USVA_headstone_emb-11.svg) public domain image.
