### ISSUE TITLE
Strange transit routing in New York

### ISSUE THREAD

**Issue by yoasif** [organicmaps/organicmaps#4935]
**Describe the issue**

I am routing from a movie theater to a Target location, using transit directions. I am expecting a pretty direct line (this is a fairly minimized case) via the Q113 or Q114 buses. 

**Steps to reproduce**
1. Search for Jamaica Multiplex - https://www.openstreetmap.org/node/2477142397
2. Select Route from
3. Add destination Target - https://www.openstreetmap.org/node/8783517426

**Expected behavior**

I would like to see a route from Archer Ave/160 St to Rockaway Tpke/Costco via the Q113. 

If applicable, add screenshots or screen recordings to help explain your problem.
![Screenshot_20230407-132803](https://user-images.githubusercontent.com/152493/230652200-ab38ad55-1b79-4d4a-bc3e-1c70a2e9eae8.png)

**System information:**

 - Organic Maps version: 2023.04.02-7-Google

**Comment by Altonss** [comment]
> via the Q113 or Q114 buses

Buses aren't integrated in OrganicMaps yet, that's why you are having this issue. You can view why here https://github.com/organicmaps/organicmaps/issues/837 or https://github.com/organicmaps/organicmaps/issues/3160.
