### ISSUE TITLE
Night Mode (auto) Not Activating (iOS)

### ISSUE THREAD

**Issue by Swamp2k9** [organicmaps/organicmaps#4937]
When "Auto" is selected in Settings > Navigation > Night Mode, the app doesn't change. It works fine when "On" is selected.

The time is currently 9pm local time (in New Zealand).

 - Operating system and its version: [iOS 16.5]
 - Organic Maps version: [Version: ⁦2023.03.31-7⁩]
 - Device Model: [iPhone14 Pro Max]

**Comment by biodranik** [comment]
Please see #749 for details.

**Comment by Jean-BaptisteC** [comment]
In the next version, theme app is sync with IOS :)
