### ISSUE TITLE
iOS: Some icons display half-size

### ISSUE THREAD

**Issue by geodavey** [organicmaps/organicmaps#494]
Thanks again for this fork! ✨

In iOS there are various icons which display at half-size, including:
- museum
- charging station
- car repair shop

![photo_2021-06-05_11-06-28](https://user-images.githubusercontent.com/25945912/120888562-c998f680-c5f0-11eb-86dc-b9fce078820a.jpg)

In the above example the icon for museum Las Hilanderas Museo de Seda is displayed at half-size

There are likely to be more, but for now these are the ones which I see around the map in my area. From what I understand from #53 the iOS map icons are copyright and must be replaced so I am sure this is a part of that process.

OMaps version 2021.05.13.0
Data version 210419

**Comment by rtsisyk** [comment]
This is a bug.

**Comment by biodranik** [comment]
Icons may be/should be replaced.

The half size probably is not a bug: minor features may have smaller icons.

**Comment by geodavey** [comment]
I looked into the issue, looks like to me the reason for the smaller icons isn't due to style differences but because the source svg's are 16x16px instead of the standard of other icons which are 24x24px

From the examples above, of all icons shown very small, each is size 16x16px
- Museum: https://github.com/organicmaps/organicmaps/blob/master/data/styles/clear/style-clear/symbols/museum-m.svg
- Charging Station: https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/charging-station-m.svg
- Car Repair shop: https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/car-repair-m.svg

Here are some icons that are shown "regular size" which are all 24x24px
- Shop: https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/shop-m.svg
- Alpine Hut: https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/alpine_hut-m.svg
- Hardware: https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/hardware-m.svg

I suspect that the "real" size that we want to show is 24x24px and that the 16x16px icons are in error. @rtsisyk if you can confirm this I can take care of this issue and submit a pull request
