### ISSUE TITLE
About screen lists impossible feature "No battery drain"

### ISSUE THREAD

**Issue by mirror176** [organicmaps/organicmaps#4942]
**Describe the issue**
About screen gives impossible feature of "No battery drain".

**Steps to reproduce**
1. Open Organic Maps
2. Click on Organic maps logo in bottom left
3. Make sure orientation is in portrait and review second bulletpoint features list. Viewing in landscape layout presented completely different information.

**Expected behavior**
Could be reworded to 'minimal battery drain', optionally drawing attention to lower power mode also available. On a side note, would be nice to define what features are disabled at what battery level instead of leaving that setting vague.

**Screenshots**
Reporting from separate PC but can try to get one dragged out of phone if necessary.

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.03.05-5-FDroid
 - Device Model: Samsung Galaxy S20 FE 5G

**Additional context**
Please add any other context and important details/notes/comments about the problem here.

**Comment by rtsisyk** [comment]
No battery drain sounds ok to me. @oleg-pah what do you think?

**Comment by RedAuburn** [comment]
"battery drain" is the specific case where battery is used unusually fast, so i think it's fine. if it said "uses no battery" then it'd be wrong.

**Comment by oleg-pah** [comment]
@mirror176 can you share a screenshot? This can be reworded to say "Saves your Battery" or "Efficient Battery Usage".

**Comment by patepelo** [comment]
> @mirror176 can you share a screenshot? This can be reworded to say "Saves your Battery" or "Efficient Battery Usage".

From a phrase style, "no battery drain" follows the context of the list "no trackers, no [...]", etc. Agree with @RedAuburn that is no excesive battery usage.

**Comment by rtsisyk** [comment]
I am not the best expert in English, but the “no battery drain” phrase has about 84,500 results in Google, which means that it is absolutely legit. The second link in my Google points to a Reddit discussion where one guy says, quoted "the problem has now gone away, no battery drain". Who am I to question such a reputable source of information as Reddit? 🙃

**Comment by RedAuburn** [comment]
i think it's safe to close this now 👍️
