### ISSUE TITLE
Stop showing water wells without drinking water like other water sources

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#4953]
Stop showing water wells without drinking water like other water sources

Currently

```
drinking_water=no
man_made=water_well
```

shows like `amenity=drinking_water`

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example:

I am regularly using OM to look for places to drink (and it is great for this!)

**Describe the solution you would like**

More elaborate processing of OSM tags.

And either not showing water wells without drinking water or show them clearly differently.

**Describe alternatives you have considered**

Show at least that there is no drinking water there?

**Additional context**

I used https://github.com/organicmaps/organicmaps/issues?q=is%3Aissue+is%3Aopen+water+well to check is it reported already

This is continuation of  #1621

**Comment by fizwidget** [comment]
I just noticed the same problem with: 
```
man_made=water_tap
drinking_water=no
```
So I guess the problem can be stated more generally as “`drinking_water` tag not respected for water sources”.

**Comment by matkoniecz** [comment]
This recently got worse as drinking water POIs got (deservedly) more prominent

**Comment by vng** [comment]
@pastk Is it ok to add 3-arity type like XXX-YYY-no_drinking ? Or any better idea?

**Comment by pastk** [comment]
> @pastk Is it ok to add 3-arity types like XXX-YYY-no_drinking ? Or add a separate _tag_ type like drinking_water=yes/no ?

Yes I think the best would be to add `-not_drinkable` subtypes. As we'll want to show them on the map still but at more detailed zooms and a different color (we have `@water_bad` already used for moats, wastewater...), maybe a different icon even.

If we do it as a separate tag `drinking_water=no` then we'll have to assign different drules at run-time via the "dynamic tags" mechanism (at the moment it can't check presence of another type, but its doable).

Related to
- #6331 
- [#1312 ](https://github.com/organicmaps/organicmaps/issues/1312#issuecomment-1706344221)

**Comment by joachim-n** [comment]
This is particularly bad in Venice, where there are LOTs of old water wells that show up as false positives in the drinking water built-in search.

These are tagged thus:

```
disused=yes
drinking_water=no
historic=yes
man_made=water_well
```

Example: https://www.openstreetmap.org/?mlat=45.43914&mlon=12.32375#map=19/45.43914/12.32375&layers=H

(They don't even show in the default map layer.)

**Comment by joachim-n** [comment]
Should it be a separate issue that these are highlighted by the built-in 'Water' search?

**Comment by matkoniecz** [comment]
> And unfortunately disused=yes is not supported yet

It is a bit of a https://wiki.openstreetmap.org/wiki/Trolltag here

> And there are some without drinking_water=no even https://www.openstreetmap.org/node/5674782803

I would treat it as OSM data error - Organic Maps has enough problems with well formed OSM data, I would not put effort into supporting badly mapped POIs

**Comment by joachim-n** [comment]
I think the disused water wells in Venice at least aren't trolltags in the same way that that wiki article says that marking a building as disused is ok because it's still a building. I saw these wells in Venice myself the other day - they are historic water wells which are no longer in use.

How should it be tagged?

**Comment by matkoniecz** [comment]
Are they providing drinking water? Then I would add also `drinking_water=no` to make more clear what is going on, see http://overpass-turbo.eu/s/1JPg

Are they accessible by general public? I would add `access=no` or `access=private` if applicable.

I would consider `disused:man_made=water_well` rather than `man_made=water_well` - but I guess it is whether you see it as a POI similar to shop (place providing water - should get lifecycle prefix) or landscape feature (such as forest - should get `***=yes` tag).

Note: first two should be done based on survey or local knowledge, that is why I have retagged none.

Third should get some agreement from community, preferably local one. See also https://community.openstreetmap.org/t/tagging-inactive-water-wells-man-made-water-well-disused-yes-vs-disused-man-made-water-well/97827 - I was considering proposing global bot edit, but I need to first finish some already started ones.

**Comment by vng** [comment]
Ok, so now we have when searching:
- "water" - shows _all_
- "drinking water" - shows only amenity=drinking_water or drinking_water=yes. Is it ok or not?

**Comment by matkoniecz** [comment]
1) I would consider including `shop=water` in "drinking water"

2) for "water" I would alias it to drinking water, as shorthand is far more likely than someone looking for lakes, rivers, private water well and drinking water

3) maybe have "all water" for all kinds of water including unusable one?

**Comment by biodranik** [comment]
What is the _real_ value for _most_ users to search for "water"? Would it be better to show drinking water only for such queries?

**Comment by pastk** [comment]
> What is the _real_ value for _most_ users to search for "water"? Would it be better to show drinking water only for such queries?

It was done mostly for outdoors and dry areas when any water is valuable, especially given that many drinkable sources are tagged as just "water" actually..

I think it'd make sense to default the pre-defined "Water" search to "drinking water" only - for the main style.
(and there will be a possibility to search for al water via a manual "water" query)
And leave the pre-defined "Water" as a more broad "water" query for the outdoors style.
- #6460

**Comment by pastk** [comment]
A separate issue from the search is that we should stop displaying explicit non-drinkable sources with a water drop icon.
For wells it should be a separate well icon.
A water tap icon for water_tap and water_point.
A "dirty paddle" icon for natural=spring.

**Comment by joachim-n** [comment]
> It was done mostly for outdoors and dry areas when any water is valuable, especially given that many drinkable sources are tagged as just "water" actually..

My use case is being on holiday and needing to find places to fill up water bottles, so it needs to be drinking water.

**Comment by pastk** [comment]
> 
> Perhaps there need to be two built-in searches: drinking water and any water.

We have them already, try typing "drinking water" into the search.
But we wouldn't want to add another similar category into the pre-defined "iconized" list in the search screen, that's why I suggest to differentiate it by the current active map style.

**Comment by joachim-n** [comment]
> We have them already, try typing "drinking water" into the search.

As a user, I wouldn't know that would work. I assumed the text search was for place names only.

If the predefined search isn't only drinking water, it needs to say.

Could the icons be differentiated?

> differentiate it by the current active map style.

That sounds like a spooky undocumented effect.

**Comment by matkoniecz** [comment]
> I think it'd make sense to default the pre-defined "Water" search to "drinking water" only - for the main style.
> (and there will be a possibility to search for al water via a manual "water" query)

That would leave me hopelessly confused if clickable "Water" and "Water" search would give different results

> As a user, I wouldn't know that would work. I assumed the text search was for place names only.

Interesting, I commonly search both in OM and Google maps for things like "toilet", "bicycle shop", "restaurant", "tourist attraction", "ice cream", "supermarket", "atm", "currency exchange" etc.

**Comment by pastk** [comment]
> 
> As a user, I wouldn't know that would work. I assumed the text search was for place names only.
> 

Yeap, the undiscoverability of this feature is a long standing UX issue...
Ideas are welcome! (there should be a separate issue for this)


> > differentiate it by the current active map style.
> 
> That sounds like a spooky undocumented effect.
> 

They'll have different names of course (different icons are possible too).

**Comment by vng** [comment]
Please, take into account incomplete OSM tagging. If we show only _true_ drinking water for regular "water" queries, we will miss a lot of _regular and probably drinking_ Water Wells for example.

**Comment by matkoniecz** [comment]
> Yeap, the undiscoverability of this feature is a long standing UX issue...

Maybe display some hints while search is running?


> Please, take into account incomplete OSM tagging. If we show only true drinking water for regular "water" queries, we will miss a lot of regular and probably drinking Water Wells for example.

I guess that is difference between "show only `drinking_water=yes` water wells" vs "exclude `drinking_water=no` water wells". Both have unpleasant failure modes.
