### ISSUE TITLE
Get wikipedia links from boundary to shown wikipedia links on place page about town

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4955]
In France, wikipedia links about town is wear by boundary relation not by town POI
To improve place page about town, we can get wikipedia links from relation and show this information on place page
Request to get list of wikipedia links wear by boundary relation on one department in France
https://overpass-turbo.eu/s/1tBK

CC @vng

**Comment by biodranik** [comment]
These relations all have admin_centre, right? Which is usually a node of type place=village or place=town, etc. Aren't these nodes already contain wiki links?

**Comment by vng** [comment]
@Jean-BaptisteC Will be fixed with the next app/data update.

**Comment by Jean-BaptisteC** [comment]
Fixed in latest beta
