### ISSUE TITLE
highway=* renders over railway=*

### ISSUE THREAD

**Issue by jmarchon1** [organicmaps/organicmaps#4958]
**Describe the issue**
Railways which overlap highways are not rendered.

**Steps to reproduce**
1. Go to somewhere where a road and railway are on each other
3. See error

**Expected behavior**
I expect the railway to render over the highway, because the highway is thicker. It will still show behind the railway.

**Screenshots**
This is what a railway on a road looks like on openstreetmap.org:
![image](https://user-images.githubusercontent.com/50030493/231306851-69aee334-1859-41e1-87f2-b13013cad994.png)
I think this is clear and a better way than how Organic Maps renders it currently, shown in the following screenshot:
![image](https://user-images.githubusercontent.com/50030493/231306963-23a853e8-fe9b-45ad-b3b0-19399b1cb82c.png)

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.04.02-7-Google
 - Device Model:Google Pixel 6a

**Comment by Jean-BaptisteC** [comment]
<img src="https://github.com/organicmaps/organicmaps/assets/87148630/5e8edf76-8ae6-40f9-a40e-4bb36579ec23" height=400 />

Fixed in 2023.07.13-10-Google version
