### ISSUE TITLE
tools/python/stylesheet/cat_stat.py - prefer English descriptions

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#4966]
I am trying out to figure out what https://github.com/organicmaps/organicmaps/blob/master/tools/python/stylesheet/cat_stat.py is doing/supposed to be doing and spotted one issue:

part of output is stuff like

```
tag,,,,,,,usages,description
highway=crossing,,,,,,,7658098,"b'\xd0\x92 \xd1\x8d\xd1\x82\xd0\xbe\xd0\xbc \xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xb5 \xd0\xbf\xd0\xb5\xd1\x88\xd0\xb5\xd1\x85\xd0\xbe\xd0\xb4\xd1\x8b \xd0\xbc\xd0\xbe\xd0\xb3\xd1\x83\xd1\x82 \xd0\xbf\xd0\xb5\xd1\x80\xd0\xb5\xd1\x85\xd0\xbe\xd0\xb4\xd0\xb8\xd1\x82\xd1\x8c \xd1\x87\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb7 \xd0\xb4\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb3\xd1\x83, \xd0\xbd\xd0\xb0\xd0\xbf\xd1\x80\xd0\xb8\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xbf\xd0\xbe \xd0\xbf\xd0\xb5\xd1\x80\xd0\xb5\xd1\x85\xd0\xbe\xd0\xb4\xd1\x83 \xd1\x82\xd0\xb8\xd0\xbf\xd0\xb0 ""\xd0\x97\xd0\xb5\xd0\xb1\xd1\x80\xd0\xb0"".'"
```

Decoding it gives `Обычно, но не обязательно расширенное место в конце дороги, предназначенное для более удобного разворота автотранспорта.`

For some reason it has taken nonenglish OSM Wiki description, I think that English would be preferable.

------------------------------------------------

that is part of https://github.com/organicmaps/organicmaps/issues/4895 - split also so I can easily find next part to work on (or maybe unlikely happens and someone else will implement this before I will have time)

-------------------------------

Also, maybe calling taginfo API instead of relying on downloaded databases would be a good idea?

**Comment by biodranik** [comment]
Why calling API is better? It's slower, and may be throttled, no?

**Comment by matkoniecz** [comment]
It does not require setting up databases to run a script, does not take 30GB of space, does not require periodical deletion and unpacking new databases. And can be just run.

And in case of such script difference between 10 or 50 seconds does not matter much (especially if oneshot run time reduction requires waiting multiple minutes for download and unpacking and manual obtaining of databases)

Maybe would be easier to use in CI.

I am still trying to figure out what exactly this script is doing but either it does something very similar to https://github.com/matkoniecz/taginfo_api_wrapper_in_python#listing-popular-tags-unsupported-by-id that generated https://github.com/openstreetmap/id-tagging-schema/issues/529 (listing all popular values within several keys which is not yet in presets, with some listed exceptions) or I will write one, in such case "can I just use API" is still applying.
