### ISSUE TITLE
Seperate leisure=stadium and leisure=pitch colors

### ISSUE THREAD

**Issue by MetehanOzyurek** [organicmaps/organicmaps#4967]
Organic Maps doesn't draw leisure=pitch on map when it overlaps with leisure=stadium
> Maybe, their colors may same. Or there may be a problem with the priorities about map display (or drawing).

**Here's an example:**
Pitch: https://www.openstreetmap.org/way/503909813
Stadium: https://www.openstreetmap.org/way/329248219

### How it looks in OpenStreetMap:
![resim](https://user-images.githubusercontent.com/80093621/231816727-7d1bd89d-48a5-45ea-a8eb-f5abf9674e6d.png)

### and how it looks in OM:
![resim](https://user-images.githubusercontent.com/80093621/231817252-1d8b183e-4761-43b2-915e-72a13e440d26.png)

**Comment by vng** [comment]
Also, check priorities. Now the generic stadium is higher than a pitch and soccer.

**Comment by pastk** [comment]
> Also, check priorities. Now the generic stadium is higher than a pitch and soccer. Because of this entry:

That shouldn't matter anymore, as we render smaller areas over bigger ones always...

**Comment by pastk** [comment]
If anyone wants to experiment with different colors - change it in https://github.com/organicmaps/organicmaps/blob/ce9d8f90545276bff9a5c2a544a5563eb4a314d9/data/styles/clear/include/Basemap.mapcss#L543-L549

Another option is to use no filling for the `leisure=stadium` at all (like we do for `leisure=sports_centre`).
