### ISSUE TITLE
Wikipedia articles and links are not showing for some villages

### ISSUE THREAD

**Issue by ivanbarsukov** [organicmaps/organicmaps#4974]
Some places has wikipedia tag but there are no links and info

Examples:
https://www.openstreetmap.org/node/519849009
https://www.openstreetmap.org/node/976985179
https://www.openstreetmap.org/node/1221481640
https://www.openstreetmap.org/node/1221481658

If there are mistakes in tags please let me know

**Comment by Jean-BaptisteC** [comment]
Fixed in next release by #4943

**Comment by Jean-BaptisteC** [comment]
@ivanbarsukov can you check problem is solved ?

**Comment by ivanbarsukov** [comment]
@Jean-BaptisteC Solved
