### ISSUE TITLE
Moving the share button in the place page

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#4983]
To help fix https://github.com/organicmaps/organicmaps/issues/4545 and reduce the number of buttons under the place page, @biodranik suggested moving the share button inside of the place page.

Here are some first impressions, what do you think? I tried putting the direction arrow under the share button but it did not look good (too much empty space under the title on the left).

|-|-|
|-|-|
| ![Screenshot_1681548984](https://user-images.githubusercontent.com/80701113/232202639-75a143c1-f152-43c4-ba97-e1c30af2d38c.png) | ![Screenshot_1681549002](https://user-images.githubusercontent.com/80701113/232202640-8d067c5e-987b-4f24-86b2-d30d7cb0ef36.png) |

**Comment by arnaudvergnet** [comment]
Regarding the design, there are a few questions I'd like to discuss:
- What color should be the icon? Grey like the the other buttons, or blue like the arrow?
- Should we show the "share" text under the icon?
- Should the button have a background?
- Should we reduce the title font size?
- Where is the best position for the share button?
- Is this a good idea at all?

If you have experience in design, your input and some mockups would help a lot!

**Comment by biodranik** [comment]
That doesn't look good. Because it doesn't look like a button (the same issue is with a blue arrow with distance, only a few users are able to guess that it is clickable!).

Can we try to implement it similarly to our iOS implementation (but better, there are some issues there)? (see the image below).

We may try, for example:
1. Add an X button like on iOS, in a circle. It helps users to close the PP instantly. Also add a share button in a circle nearby, as Apple does. And make them smaller (the size may be the same as in Apple Maps).
2. There are variations: a) to draw X and share icons _above_ the title, closer to OM on iOS; b) to draw X, share and arrow icons to the right of the title (maybe arrow should be drawn below X and share?)
3. The blue arrow can be moved at the POI's subtitle (type) line, similar to OM on iOS to make more space for the title.

OM|Apple Maps
---|---
![image](https://user-images.githubusercontent.com/170263/232223911-ede35e7d-384e-483c-b218-9da71edb1131.png)|![image](https://user-images.githubusercontent.com/170263/232224041-b52daea0-4193-416e-865c-6aab7d7ead75.png)

**Comment by Misalf-git** [comment]
Wouldn't it make sense for the share button to be close to the coordinates button in the expanded place pace?

Then it could also have a longer title than just "share" and the lying text could be removed:
```
Hi,

I'm here now: Antarktika. Click this link om://AQKoHQxGbK/Antarktika or this one https://omaps.app/AQKoHQxGbK/Antarktika to see the place on the map.

Thanks.
```

**Comment by arnaudvergnet** [comment]
The link text 100% needs to be updated. It only makes sense when you share your current location. For other places, it should just say the name to the place selected along with the address and coordinates/link. 

If we put the share button next to the coordinates, then users will need to expand the place page to see it.

Moving the direction arrow as in the iOS app would make it easier to put the share button on the top right. It would be nice to find a way to make users understand that the arrow can be clicked on.

**Comment by arnaudvergnet** [comment]
Here is some more experimentation. I think its starting to look nice! I'll see to change the arrow a bit to make it clear users can click on it.

|-|-|
|-|-|
| ![Screenshot_1681576266](https://user-images.githubusercontent.com/80701113/232237996-67feb9af-7c79-4586-9a79-fb7c8aafc1f2.png) | ![Screenshot_1681576243](https://user-images.githubusercontent.com/80701113/232237994-5120a9d8-95c9-49e5-8488-2a1028aa73e1.png) |

**Comment by arnaudvergnet** [comment]
And here is with reduced title font size and a background on the direction arrow:

|-|-|
|-|-|
| ![Screenshot_1681578463](https://user-images.githubusercontent.com/80701113/232240729-68442d40-84fc-4e22-a3d0-12106c69da9b.png) | ![Screenshot_1681578467](https://user-images.githubusercontent.com/80701113/232240724-5fbf7813-233f-4240-8061-b089561a2640.png) |

**Comment by endim8** [comment]
oooo, i like the look of this a lot! :)

**Comment by biodranik** [comment]
That's better, but the buttons are too big and too close to each other.

What about removing backgrounds for all of them? And, to compare, maybe also slightly reduce the size of X and share? It works well on Apple, maybe because they actually handle taps also at the surrounding area, not only at the small drawn circle.

**Comment by arnaudvergnet** [comment]
Here are some more experiments with smaller buttons. We'll need to try it a bit to see if we need to make the touch area larger than the actual button. I'm not a fan of removing the button backgrounds, it is not obvious users can interact with them.

I also made the bottom buttons background white, I think it is prettier than the current grey color, but we'll need to find a way to clearly indicate to the user we can expand the place page. I was thinking of showing a few pixels of the rest of the place page, so users can see the start of the content and understand they can scroll. Should we create a separate issue for this?

| Without background | With background |
|-|-|
| ![Screenshot_20230418-112517_Organic Maps (Debug)](https://user-images.githubusercontent.com/80701113/232736741-53e5c3f5-aae9-4779-aa0f-dd12fd76a450.png) | ![Screenshot_20230418-112354_Organic Maps (Debug)](https://user-images.githubusercontent.com/80701113/232736750-b3373e14-f529-45ec-a3a1-c816738e63d4.png) |

**Comment by biodranik** [comment]
1. Why our share icon has filled circles? The standard [material icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Sharp%3Ashare%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048) doesn't use filled circles. Which one looks better?

**Comment by arnaudvergnet** [comment]
1. Icons are from the android studio's icon generator, but it defaults to filled icons. The new screenshot uses the outline variant.
2. I tried using background to make it easier to understand you can click on the direction arrow. Should we keep the background on it or do you prefer no background on anything?
3. :+1: 
4. Again the screenshots use the android studio icon, so its the same as the first link. I don't like the version with the circle around it because the share icon does not have it so it looks weird.
5. Here are some tests:

| Without any background | With a background on the direction arrow |
|-|-|
| ![Screenshot_20230422-184959_Organic Maps (Debug)](https://user-images.githubusercontent.com/80701113/233797004-99337595-cd3e-4683-9c79-edaed9b0e656.png) | ![Screenshot_20230422-185331_Organic Maps (Debug)](https://user-images.githubusercontent.com/80701113/233796999-cee3ce6d-fca6-40da-89dd-bfbafce75a9e.png) |

**Comment by biodranik** [comment]
The first clean version looks great! We'll reduce the top margin one day too, right? :)

**Comment by biodranik** [comment]
I would also do right now the right capture of touches: assuming that buttons above the arrow are sharing the common left and right width, it makes sense to make that whole white area to the left and right from Share and X touchable, so users have a better touch UX there.

**Comment by arnaudvergnet** [comment]
> The first clean version looks great! We'll reduce the top margin one day too, right? :)

The top margins are already reduced, but we can reduce it further.

> I would also do right now the right capture of touches

This is also done but will need a bit of experimenting to make sure it works great.

**Comment by biodranik** [comment]
Where is it done? How to test it?
