### ISSUE TITLE
Signpost icons

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4993]
Objects tagged with tourism=information (where `information != office`) and information=route_marker should be displayed similarly to signposts (information=guidepost) (no background circles).

tourism=information + information=office is actually a business-like office with office workers, so it should stay as is (i icon in a circle).

**Comment by map-per** [comment]
How about using a generic 'i' icon like ![information-m](https://github.com/organicmaps/organicmaps/assets/79519062/f1d88647-b265-45fa-b059-6645562036cf) for tourism-information?

### Screenshots
![Bildschirmfoto vom 2023-09-03 14-34-52](https://github.com/organicmaps/organicmaps/assets/79519062/a2194b04-80b0-49b6-95a8-b833e98a15fb)
https://www.openstreetmap.org/node/4592840092

**Comment by dvdmrtnz** [comment]
This was fixed in https://github.com/organicmaps/organicmaps/pull/5916
