### ISSUE TITLE
Search doesn't find addr:housename nodes without addr:street

### ISSUE THREAD

**Issue by Colbertson** [organicmaps/organicmaps#4994]
Loose addr:housename nodes dont render and arent searchable, if the tags are on a building it works as it should.
Example: https://www.openstreetmap.org/node/9887239854

![OSM Carto](https://user-images.githubusercontent.com/81972292/232479539-465323f6-b17c-44c8-a1bc-d76a0cdc7223.png)
![Organic maps](https://user-images.githubusercontent.com/81972292/232482173-cc3c6944-9e7e-4cbb-a202-83e85a782975.png)

OM version 2023.04.02-7-Google.

**Comment by biodranik** [comment]
There is no street there. How people are searching for such objects? What's the official address?

**Comment by Colbertson** [comment]
That is the official address imported from the VZD database, usually small villages only have housenames.
Searching could be done with the post code or village name.

**Comment by Jean-BaptisteC** [comment]
@Colbertson can you check with new version ?

**Comment by Colbertson** [comment]
![Screenshot_20230519_095536_Organic Maps](https://github.com/organicmaps/organicmaps/assets/81972292/a90ee1db-5556-4724-8f28-1c9bdbc9b480)
They appear on the map and when searching now.
Thanks.

**Comment by soshial** [comment]
I have a question about viewing "addr:housename" in "place info" bottom sheet. It does not show address at all for me:

https://www.openstreetmap.org/node/3797620490

![photo_5199407608501495571_y](https://github.com/organicmaps/organicmaps/assets/100644/7f01c029-a5af-4bb8-b4f4-ed7d0406821e)

This might be related to https://github.com/organicmaps/organicmaps/issues/616
