### ISSUE TITLE
Update Lyon subway icon

### ISSUE THREAD

**Issue by Harfeur** [organicmaps/organicmaps#5004]
Hi,

The icon of the Lyon subway is outdated.

Here is the new icon :

![metro](https://user-images.githubusercontent.com/22135449/232860701-1ba6b72f-df29-4411-8797-9fc614a4f9d0.svg)

Can you tell me how to update it ? I saw [subway-lyon-m.svg](https://github.com/organicmaps/organicmaps/blob/master/data/styles/clear/style-night/symbols/subway-lyon-m.svg) but I'm not sure what is the difference between s and m...

Thanks <3

**Comment by vng** [comment]
Sizes: small, medium. Will be good if you can keep sizes like in existing svg files.
