### ISSUE TITLE
Wikipedia articles is not show each time on place page

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#5006]
**Steps to reproduce**
1. Open OM
2. Select village on map and open place page -> wikipedia link is present
3. Select big city on map and open place page -> wikipedia article is missing (and big padding is present on place page)
(Nothing in logcat)

**Video**

https://user-images.githubusercontent.com/87148630/232895649-59c380ec-e3d3-4425-9b50-8fcc80b94925.mp4

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.04.18-11-Web-debug (generate here #5003)
 - Device Model: Pixel 6

**Comment by Jean-BaptisteC** [comment]
@biodranik release blockers ?

**Comment by biodranik** [comment]
@Jean-BaptisteC it looks like a regression, right? Was it present in the previous/one past previous version? Could @arnaudvergnet 's changes cause this?

**Comment by Jean-BaptisteC** [comment]
Not present on latest release because wikipedia link are missing #4912

**Comment by vng** [comment]
Q22540 and "Florange" are not present in our current offline wiki dump. It is too old unfortunately (> 2 years already ..).

**Comment by vng** [comment]
Found another example:
fr.wikipedia.org/wiki/Gare_d'Hayange exists
wikidata/Q2800482 exists

But no offline wiki for https://www.openstreetmap.org/node/3892210605

**Comment by Jean-BaptisteC** [comment]
Problem is not on Florange, the main problem is if i consult POI with only wikipedia link, and after i consult POI with offline wiki, offline wiki is missing, please check video

**Comment by vng** [comment]
@Jean-BaptisteC My bad, sorry!
@arnaudvergnet @AndrewShkrob Please, take a look here.

**Comment by Jean-BaptisteC** [comment]
Fix by #5168
