### ISSUE TITLE
Compass Rose <or> Direction-of-Travel?

### ISSUE THREAD

**Issue by TriggerDingus** [organicmaps/organicmaps#5010]
### Discussed in https://github.com/orgs/organicmaps/discussions/5001

<div type='discussions-op-text'>

<sup>Originally posted by **TriggerDingus** April 18, 2023</sup>
I come from the days of hardcopy maps as a driver, SCUBA diver and hiker. The common thread is I always needed to know my direction of travel for orientation and route finding. I know this isn't a requirement for use of digital navigation, but I have an innate need to quickly and easily understand my directions.

The early versions of google maps had a compass rose on the map during navigation, a feature which they soon eliminated because eventually younger folks never had to learn magnetic directions at all. I degoogled myself many years ago and have been using a Garmin GPS and though they don't have a compass rose option, they do offer a way to enable 'direction of travel' in the status bar so I'm able to quickly determine direction that way.

I've been trying to learn and get used to Organic Maps and I've not found an option to denote direction-of-travel during navigation. I noticed I can press the blue arrow while running a route, but that rotates the map so North is upwards and so that isn't helpful.

Am I missing something obvious? Is there a compass rose or direction-of-travel feature I'm missing?</div>

**Comment by TriggerDingus** [comment]
#5001

**Comment by richlv** [comment]
Is this similar to #3511?

**Comment by TriggerDingus** [comment]
Yes, it appears to be.
