### ISSUE TITLE
"tea" should find tea shops, like "tea shop" does 

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#5012]

**Comment by biodranik** [comment]
Or, a suggestion "tea shop" should be shown to users.

**Comment by matkoniecz** [comment]
in general I would expect that searching by products, especially by primary products would find relevant shops

**Comment by biodranik** [comment]
Searching by one of the keywords in the shop's type is a good idea.

Are there any related OSM tags for products available in shops?

**Comment by Jean-BaptisteC** [comment]
Works in 2024.02.06-11-Google version
