### ISSUE TITLE
[android] Place page view

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#502]
No OH breaks. No dividers. No Open/Close status.

Compare iOS:
![telegram-cloud-photo-size-2-5323621829388121295-y](https://user-images.githubusercontent.com/175612/120895991-2532a680-c628-11eb-8933-f28a31479ffc.jpg)
and Android:
![telegram-cloud-photo-size-4-5900049480378595054-y](https://user-images.githubusercontent.com/175612/120895995-295ec400-c628-11eb-8e9d-0a211f25f0da.jpg)

**Comment by arnaudvergnet** [comment]
This issue is a bit old and the design (at least on Android) changed quite a bit since. Can we close this issue (and use https://github.com/organicmaps/organicmaps/issues/3355 for further design change discussion)?
