### ISSUE TITLE
Zoom buttons intermittently shown on higher Android screen zoom

### ISSUE THREAD

**Issue by mirror176** [organicmaps/organicmaps#5041]
**Describe the issue**
Zoom buttons are sometimes not displayed on screen.

**Steps to reproduce**
1. On my phone: Settings>Display>Screen zoom>move slider to the right 1 notch past middle to make things larger
2. Put device in landscape mode with autorotate on and open Organic Maps
3. Observe there is zoom in/out on screen
4. Click search
5. Click back
6. No zoom buttons are visible though pinch zoom works
7. Rotate to portrait and buttons appear
8. Rotate back to landscape and buttons stay on screen

**Expected behavior**
As there is no visible change in the rest of the interface, the buttons should have appeared.

**Screenshots**
If they are needed I will get them out somehow but on PC reporting this.

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: [you can find it by clicking the "?" button] No '?' button on my screen but the organic maps logo reports 2023.04.02-7-FDroid with OSM data 03/29/2023
 - Device Model: Galaxy S20 FE 5G. Template question: Why not ask this question next to OS? if looked up on Android you find hardware and OS one screen away on my Samsung vs Organic Maps version details are in a whole different program.

**Additional context**
Picking a searched address brings up a white details box bottom center. In portrait mode there is enough room for the buttons to be above the box while in landscape there is not and zoom buttons disappear. At normal screen zoom the buttons in landscape are placed to the right of the box; suspect both the buttons and the box are resized making relative placement and box sizing work unexpectedly.

**Comment by biodranik** [comment]
@arnaudvergnet is this issue fixed by one of your PRs?

**Comment by arnaudvergnet** [comment]
https://github.com/organicmaps/organicmaps/pull/4808 should fix it. If that's not the case please tell me

**Comment by Jean-BaptisteC** [comment]
Fixed in 2023.12.21-1-Google with max Android zoom
