### ISSUE TITLE
Lane Support Not Working

### ISSUE THREAD

**Issue by toygarlk** [organicmaps/organicmaps#5071]
The new lane support assistant is not working on my device. I tested on all beta versions and Google Play releases. My device is Samsung Galaxy S20 FE (Android 13) [Snapdragon 865].

**Comment by toygarlk** [comment]
Yes.

**Comment by strump** [comment]
@toygarlk to see lanes on the navigation screen this data should be added to [OpenStreetMap.org](https://osm.org)

OrganicMaps app takes data from that mapping site where anyone can improve map like Wikipedia. And if you don't see lanes arrows probably it's because those details are missing on OpenStreetMap.

Could you please share on which road do you expect to see lanes assistance?

**Comment by toygarlk** [comment]
Yes, I tested it on my own edited roads. I am OSM contributor.

**Comment by toygarlk** [comment]
Yes, I added before this date. I tested latest Google Play version and all new betas.

**Comment by endim8** [comment]
Could you link an example route on OSM?

**Comment by toygarlk** [comment]
https://www.openstreetmap.org/directions?engine=fossgis_valhalla_car&route=40.96593%2C27.48903%3B40.99095%2C27.57581#map=13/41.0059/27.5661

**Comment by endim8** [comment]
Ahh, I think you've added `lanes=*` this is needed for turn lanes, but turn lanes themselves must be tagged with `turn:lanes=*`
see https://wiki.openstreetmap.org/wiki/Key:turn#Examples

**Comment by toygarlk** [comment]
I tested on new beta but it not works

**Comment by biodranik** [comment]
@toygarlk can you please point to OSM ways that you edited with turn:lanes, that do not work? Were they edited _before_ the OSM snapshot in the beta was done? You can check it in About dialog.

**Comment by Jean-BaptisteC** [comment]
@RedAuburn 
I have tested this road, and we have 2 cases or turns lanes that can be shown
- https://www.openstreetmap.org/way/1087078178/ in this case, OM doesn't show turns lanes but tells in TTS to stay to the left
- https://www.openstreetmap.org/way/460060211 in this, OM shows turns lanes and tells to take the exit
