### ISSUE TITLE
Can't navigate with only village name and House number

### ISSUE THREAD

**Issue by djkato** [organicmaps/organicmaps#5075]
**Describe the issue**
Downloaded the app and tried to navigate to a specific house within a small village. Locations in Slovakia often don't have a street name, only village name and house number. I often have to navigate to such small places, and I can't be asked look for the house manually every time. Example: 
 https://omaps.app/04HBqWNxNU/Building.

**Steps to reproduce**
Look up [village name] [house number], I'd expect to find the address but it only finds the village.

**Comment by biodranik** [comment]
Search for duplicated issues by `addr:place` keyword (it's not supported yet).
