### ISSUE TITLE
Bug in parsing opening hours

### ISSUE THREAD

**Issue by euf** [organicmaps/organicmaps#5078]
**Describe the issue**

When opening hours string ends with `; Su,PH off `, Organic Maps incorrectly believes that Su is open instead of closed.

**Steps to reproduce**

A shop located at 34.680329, 33.040013 has the following opening_hours:

```
Mo-Tu,Th-Fr 09:00-19:00; We,Sa 09:00-14:00; Su,PH off
```

Organic Maps incorrectly shows that the shop is open on Sunday all day. 

**Expected behavior**

Organic Maps should see that Su is off. The string above is parsed correctly at https://openingh.ypid.de/evaluation_tool/ and OsmAnd also shows the schedule for this shop as expected (closed on Sunday).

**Screenshots**

![image](https://user-images.githubusercontent.com/11754264/235879621-f82b5009-9986-4aa8-bc1c-fa000d3eb705.png)

**System information:**
 - Operating system and its version: iOS 16.0
 - Organic Maps Version: ⁦2023.04.02-6⁩
 - Device Model: iPhone 12 mini

**Comment by biodranik** [comment]
Please check and reference duplicated issues: https://github.com/organicmaps/organicmaps/labels/Opening%20Hours

**Comment by Jean-BaptisteC** [comment]
Similar of #1612

**Comment by xephos1one** [comment]
Duplicate of #1575
