### ISSUE TITLE
Remove Map layers shortcut

### ISSUE THREAD

**Issue by Donkey-Doug** [organicmaps/organicmaps#508]
There is a shortcut in the top left corner to quickly change the map layers, but the same functionality is also implemented under the More options button (3 horizontal stripes, bottom right). No reason for duplicate buttons. I think adjusting map layers from the More options button is suffcient and makes more sense than an entire seperate button.

**Comment by tangsgod** [comment]
Agree!

**Comment by rtsisyk** [comment]
I also don't like that button.
