### ISSUE TITLE
Inconsistent layout in place page on iOS

### ISSUE THREAD

**Issue by Raphael0** [organicmaps/organicmaps#5088]
**Describe the issue**
Using iOS, when opening the place page there are inconsistent spaces and lines between the different parts of the page

**Steps to reproduce**
Open any place page on OrganicMaps using iOS

**Expected behavior**
Consistent layout in the places page

**Screenshots**
Screenshot 1: unexpected grey spacing
Screenshot 2: unexpected "double line"
Screenshot 3: overly large space after Wikipedia article and no lines at top and bottom of article
<p float="left">
  <img src="https://user-images.githubusercontent.com/23408445/236470996-45039e1a-1db6-4ef6-884b-0a813dc4ce58.PNG" width="250" />
  <img src="https://user-images.githubusercontent.com/23408445/236470988-128bfb08-f52c-4fc8-bb79-9cf356db760c.PNG" width="250" /> 
  <img src="https://user-images.githubusercontent.com/23408445/236471000-2e5ea509-8931-4c1d-b86c-211985be9842.jpeg" width="250" />
</p>

**System information:**
 - Operating system and its version: iOS 16.4.1
 - Organic Maps version: 2023.04.02-6
 - Device Model: iPhone 12 mini

**Additional context**
None

**Comment by matheusgomesms** [comment]
Yep, I confirm that but totally forgot to open an issue. This is kinda new (the grey bar), from 2-4 updates ago, if I am not mistaken. Sometimes if you click again on the same POI, it disappears, but I could not find a pattern.

**Comment by dvdmrtnz** [comment]
* Same as https://github.com/organicmaps/organicmaps/issues/3082
