### ISSUE TITLE
Hide bookmark button

### ISSUE THREAD

**Issue by Donkey-Doug** [organicmaps/organicmaps#509]
Make it possible to hide the bookmark buttom in the bottom bar. Bookmarks should be available when searching for a place or navigating to a place. No need for a seperate button.

**Comment by rtsisyk** [comment]
This proposal is controversal :)

**Comment by biodranik** [comment]
Please clarify your use case. Now the Star button after selecting a feature is the only way to add a bookmark.

**Comment by biodranik** [comment]
The bookmarks lists button on the main bottom bar is the fastest way to find something when the name is forgotten, and the fastest way to show/hide/export bookmarks.

**Comment by rtsisyk** [comment]
Up

**Comment by rtsisyk** [comment]
Closing by timeout. Feel free to re-open.
