### ISSUE TITLE
pub displays as type football

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#5092]
A pub displays as type football because it has sport=soccer:
https://omaps.app/0tdddYXcsW/Railway_Tavern

<img src="https://user-images.githubusercontent.com/26939824/236532963-a9c85e97-f47d-46cf-99b6-b6d13f2a718d.png" width="400px"/>

this is an OSM data issue, but sport=* tags shouldn't take priority over subtypes

**Comment by RedAuburn** [comment]
fixed by https://github.com/organicmaps/organicmaps/pull/6615

**Comment by patepelo** [comment]
> this is an OSM data issue

I don't see it as an OSM data issue, that would be a bar associated with soccer i.e. soccer matches can be watch there.

**Comment by RedAuburn** [comment]
> > this is an OSM data issue
> 
> I don't see it as an OSM data issue, that would be a bar associated with soccer i.e. soccer matches can be watch there.

There are ~800 cases where `amenity=pub` has `sport=*, but from what I can tell a lot of them are bowling or pool, so cases where you're actually playing the sport. This `sport=football` however means that football is shown on the TV. ideally a new tag would be proposed, something like `live_sports=soccer;tennis` etc.
