### ISSUE TITLE
Linux version is unable to get location

### ISSUE THREAD

**Issue by baarkerlounger** [organicmaps/organicmaps#5114]
**Describe the issue**
The Linux version is unable to get a location. This is reproducible on desktop Linux (debian) and Mobile Linux (PureOS), installed via Flatpak from Flathub in both cases.

On both devices Gnome maps and PureMaps are able to get a location fix using Geoclue (Wifi based on desktop, Wifi/GPS based on mobile)

Clicking the location icon doesn't do anything, and does not produce any console logs either.

**Steps to reproduce**
1. Install the flatpak from Flathub
2. Click on the location icon (marker with strikethrough)
3. Note that the map does not center on your actual location or display a marker for it

**Expected behavior**
Organic maps centers on my location and shows a marker

**System information:**
 - Operating system: Debian 12, PureOS 10
 - Organic Maps version: 2023.05.08-1-fd0133d9-dirty-Linux
 - Device Model: Librem 5, Thinkpad X1

**Comment by biodranik** [comment]
Are there any related existing issues already?

**Comment by baarkerlounger** [comment]
@biodranik possibly this https://github.com/organicmaps/organicmaps/issues/3870

**Comment by Ferenc-** [comment]
Done in https://github.com/organicmaps/organicmaps/pull/5823

**Comment by Ferenc-** [comment]
> @Ferenc- not sure if it's the same problem or a different one so let me know if I should rather open a new issue but this appears fixed for desktop but not mobile.
> 
> On mobile the app crashes as soon as the Location permission is granted with:
> 
> ```
> qt.positioning.geoclue2: Unable to start the client: "org.freedesktop.DBus.Error.AccessDenied" "Agent rejected 'app.organicmaps.desktop' for user '1000'. Please ensure that 'app.organicmaps.desktop' has installed a valid app.organicmaps.desktop.desktop file."
> ```
> 
> Device: Librem 5 OS: PureOS 10 "Byzantium" (Debian 11 based) Package: 2023.09.22-27 Flatpak from Flathub

This is a [duplicate of the currently pinned issue in the flathub repo](https://github.com/flathub/app.organicmaps.desktop/issues/61), please check the workaround there.
