### ISSUE TITLE
[android] Revive recent track recorder

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#512]
iOS now has this feature. A proper background service is needed, and a kind Google Play reviewer to pass the review with a new permission.

**Comment by rtsisyk** [comment]
I took one more look at this issue.

# Background

The original track recorded was removed for the following reasons:

1. It didn't work properly. The track points were recorded only when the app was in the foreground mode plus periodically a few times per hour. In other words, the track was very coarse.
2. Google's reviewers stopped accepting applications that called location API in the background (i.e. after Activity.onPause()).

All things considered, we decided to remove this feature and move forward.

#  Current State

I researched this topic one more time. According to https://developer.android.com/about/versions/oreo/background-location-limits:

> In an effort to reduce power consumption, **Android 8.0 (API level 26)** limits how frequently an app can retrieve the user's current location while the app is running in the background. Under these conditions, apps can receive location updates only a **few times** each hour.

This explains the situation completely. Foreground + few time each hour if you can pass Google Play review with such implementation. 

From https://developer.android.com/about/versions/oreo/background-location-limits#tuning-behavior:

> Consider whether your app's use cases for running in the background **cannot succeed** at all if your app receives infrequent location updates. If this is the case, you can retrieve location updates more frequently by performing one of the following actions:
>
>1. Bring your app to the foreground.
>
>2. Start a foreground service in your app by calling startForegroundService(). When such a foreground service is active, it appears as an ongoing notification in the notification area.
>
>**Caution**: If your app starts a foreground service while running in the background on a device that runs Android 11 (API level 30) or higher, your app cannot access location information unless the user has granted the **ACCESS_BACKGROUND_LOCATION** permission to your app. For more information, view the guidance about the while-in-use restrictions that are associated with foreground services.
>
>3. Use elements of the Geofencing API, such as the GeofencingClient, which are optimized for minimizing power use.
>4. Use a passive location listener, which may receive faster location updates if there are foreground apps requesting location updates at a faster rate.

# Proposals

Given these points, I see two possible options:

## Option 1. Restore the original track recorder code mostly as-is

It will record points in the foreground (see point 1 above) plus we can try to add "passive location listener" (see point 4 above). This option is not really bad. A user opens the app periodically to check location, directions and visual landmarks when navigating. The track recorder in this case can help the user to remember previous places and not to get lost. This solution is the low-hanging fruit. No need to display annoying notification in "notification area". No additional permissions from Google are required.

## Option 2. Implement the new full-featured track recorder

It should have at least start/stop buttons and records data into kml/bookmarks. This approach is more complex and requires more time and resources to get finished. I doubt that we have such resources at the moment.

**Comment by biodranik** [comment]
> Note: If your app needs access to location history that contains time-frequent updates, use the batched version of the Fused Location Provider API elements, such as the FusedLocationProviderApi interface. When your app is running in the background, this API receives the user's location more frequently than the non-batched API. Keep in mind, however, that your app still receives updates in batches only a few times each hour.

Looks like more locations with timestamps can be retrieved when using this API.

**Comment by rtsisyk** [comment]
The track former recorder is not revivable. The background mode has been significantly restricted since the original implementation. See explanation in https://github.com/organicmaps/organicmaps/pull/1807#issuecomment-1045934270.
