### ISSUE TITLE
Subway (layer=-1) Is Not Show On Map

### ISSUE THREAD

**Issue by toygarlk** [organicmaps/organicmaps#5126]
If train road have a layer=-1 and tunnel=yes tag, this is not show on map. I drop example link, please fix it.

https://www.openstreetmap.org/way/23045034

**Comment by biodranik** [comment]
@vng is map pollution in big cities the main reason we don't draw tunnels? Or is it a bug?

**Comment by vng** [comment]
https://github.com/organicmaps/organicmaps/issues/2245

Also we already had similar discussions before.

**Comment by pastk** [comment]
Closing as a duplicate of #2245
