### ISSUE TITLE
"Sehenswürdigkeit" (de) / "attraction" (en) is not visible when creating a new object and search is used

### ISSUE THREAD

**Issue by simonschaufi** [organicmaps/organicmaps#5128]
**Describe the issue**
"Sehenswürdigkeit" (de) is not visible when creating a new object but is shown when clicked on an existing object with the category from OSM. In OSM the category is "tourism" (left side) and the type is: "attraction", see https://www.openstreetmap.org/node/5248396510 as an example.

**Steps to reproduce**
1. Create a new object on the map
2. select type
3. search for "Sehensw"
4. No "Sehenswürdigkeit" available

**Expected behavior**
"Sehenswürdigkeit" is visible and scrolling is possible with open keyboard

**Additional context**
The main issue is that scrolling to all entries is only possible when the keyboard is closed.

**Comment by icharkas** [comment]
It seems be hidden under on-screen keyboard because of sorting by name.

![Screenshot_1](https://github.com/organicmaps/organicmaps/assets/126597376/bad81c09-4df3-4018-9c97-3470023adb10)
![Screenshot_2](https://github.com/organicmaps/organicmaps/assets/126597376/28afbba9-eae9-44be-b524-59da4ff12a43)

Do you thing it is better to show it before other subtypes of attraction (Sehenswürdigkeit)?

**Comment by simonschaufi** [comment]
Right, it is actually there but you have to close the keyboard in order to see it. I consider this a UI bug then because having the keyboard open, I can't scroll further down.

**Comment by Jean-BaptisteC** [comment]
@simonschaufi can you give your android version
I'm not able to reproduce problem on Android 13
I can scroll in list when keyboard is open

**Comment by simonschaufi** [comment]
@Jean-BaptisteC scrolling is possible but not to the last entry in the list.
I have Android 11

**Comment by icharkas** [comment]
Here is what I had on Samsung Galaxy Note20 Android 12. Switched to German
language and tried to add new plase with category "Attraction"
(Sehenswürdigkeit).

**Comment by icharkas** [comment]
![Uploading Screenshot_20230621-070857_Organic Maps.jpg…]()

**Comment by icharkas** [comment]
![Screenshot_20230621-070857_Organic Maps](https://github.com/organicmaps/organicmaps/assets/126597376/2523d289-fb1a-47fc-b593-082e9d3a029d)
![Screenshot_20230621-070631_Organic Maps](https://github.com/organicmaps/organicmaps/assets/126597376/84b43240-caf0-414b-9c35-5be84ed97c65)
