### ISSUE TITLE
OSM-based address search is unusable in large parts of US, needs interpolation or other data source?

### ISSUE THREAD

**Issue by quicklybeforeitstoo** [organicmaps/organicmaps#5134]
From a user perspective, Organic Maps often or even usually fails to find a street address in several US cities. (Especially in suburban places and smaller cities, e.g. Skokie and Evanston (suburbs of Chicago, IL) and Boulder, CO.) When online, I can search via other means and use OM for routing. This is not feasible offline, and makes it difficult to get others to switch from e.g. Google to OM. (Personally, I know two people IRL who might have switched if the address searching actually worked.)

I think I understand why this happens. OM looks for buildings of a given housenumber in OSM data. OSM does not have building information for many, many buildings in the US. Furthermore, some apartment buildings have a housenumber that is a range of numbers. OM search does not identify the range containing a given house number. (Is this a known bug? Maybe I should separately document this.) To an extent, this is OSM's "fault." However, in order for OM to be useful in the US, OM needs a solution.

In issue #1120 , biodranik has suggested that finding the street, rather than particular address, is "good enough in many cases." However, the last address I tried to look up is on a street that is 5 km long. This length of street is not atypical, and means that navigating to a street is not good enough for most of the use cases of people in my geographic area.  "Just" adding several million addresses to OSM is also not a real solution in the short term or even intermediate term, unless there is an automated solution that is sufficiently reliable.

In issue #1263 , biodranik expressed concern about resolving a location for an address that doesn't exist as an OSM building: "My point is that they could be disappointed in both scenarios: when the search did not find anything, or when the search finds an empty place on the OM map." From my experience, and experience with two other potential users of OM, the first case is very disappointing and makes the app unusable, and the second case would not even register most of the time. We are not zooming in enough to look at a building. We just want directions that take us to the correct block.

I understand that integrating additional data sources may not be feasible. I don't know much about this domain, but one possible solution may be to interpolate house numbers. (This is mentioned also in #1238 ). I realize this is a hard problem without an easy code fix, but right now OM is unusable in several places in the US. (Possibly many, but I haven't done a thorough survey.)

**Comment by biodranik** [comment]
Did you check the latest release? It should have interpolated addresses working.

**Comment by quicklybeforeitstoo** [comment]
Thank you, I tried it just now, but no luck. I tested an address on Central Road in Glenview, IL, USA, and it fails to find anything. Looking at OSM again, as I can tell, there are no housenumbers listed on Central Road in Gleview for the entire length of the road. So again, this is OSM's "fault," not OM, but it looks like another data source would be needed to make the address search functional.

**Comment by biodranik** [comment]
There are already several related issues, for example #1263

**Comment by jwmh** [comment]
@quicklybeforeitstoo Are you using the latest TestFlight / Beta Version?
- iOS: https://testflight.apple.com/join/lrKCl08I
- Android: https://appdistribution.firebase.dev/i/9ec3bca5e2b47373
- linux: https://repology.org/project/organicmaps/versions
- linux Flatpak also available.

Source:
bottom of this page:
https://organicmaps.app/
under ## Community

**Comment by zyphlar** [comment]
FYI supporting address interpolation is great, however there is extremely low interpolation coverage in the USA. Ultimately openaddress integration as a fallback for missing housenumbers is the fastest way to fix this (as seen with the OpenSuperMaps project for OsmAnd)

**Comment by quicklybeforeitstoo** [comment]
Openaddress integration would be an extremely useful feature in the US, even if at first it is just documention of how to manually create and import map data files with this information added.

**Comment by vng** [comment]
We added US Tiger interpolation addresses, please, check and test our latest Beta. Release will be available approx in a week.

**Comment by zyphlar** [comment]
The TIGER interpolation looks great, I think it's good enough that the only remaining task on this issue is checking for areas which TIGER may not cover (data QA) and ensuring that interpolated search results are intuitive (the locations are a bit more approximate and displayed slightly differently than precise results, which is OK but should be designed well for clarity among nontechnical people)

**Comment by biodranik** [comment]
@quicklybeforeitstoo please check the latest version with the latest map data. All externally available USA addresses from TIGER database should be already present. Feel free to reopen the issue if something is left to finish.
