### ISSUE TITLE
Desert/Sand blue in dark mode

### ISSUE THREAD

**Issue by map-per** [organicmaps/organicmaps#5153]
**Describe the issue**
It's not intentional that desert/sand has a blue color in dark mode, is it?

**Screenshots**
![Screenshot_20230514_195138](https://github.com/organicmaps/organicmaps/assets/79519062/039c1051-38cb-4849-b4c3-12aeb35dc526)

**Code**
https://github.com/organicmaps/organicmaps/blob/3d5a5f2b62c7cfb05a97270478a295d9292ee79e/data/styles/clear/style-night/colors.mapcss#LL46C1-L46C18

**Comment by biodranik** [comment]
What color do you recommend? Think about a driver using OM at night in the car.

**Comment by matheusgomesms** [comment]
Apple Maps uses #2596be on dark mode.
<img width="739" alt="Captura de Tela 2023-05-16 às 09 37 06" src="https://github.com/organicmaps/organicmaps/assets/86851490/d24687db-2b58-46e7-93b2-a18307746217">

**Comment by biodranik** [comment]
@vng let's change it?

**Comment by map-per** [comment]
Opened a PR for this (#5234)
