### ISSUE TITLE
[Mac] Build error XCode on Mac Silicon

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#5164]
I tried to build the app to test #5122, without success. With a clean install of XCode, I could not build it. It throws an error saying that cannot find some files (mainly related to 3rd party files: Vulkan, Boost, Succinct, and Jansson). When I cloned the project, I made sure all the files were there (with recursive parameter).

I also tried to give the exactly location of the path for the "missing" files, but then always another file would also be missed. I tried too to install Vulkan myself, and while it worked successfully on a clean project, I couldn't make OM find it. I even linked manually Custom Paths, Header Search Paths and so on, but nothing.

I tried on two machines, a Mac Air M1 and a Mac Pro M2.

Is there anything I am doing wrong?

**Comment by Jean-BaptisteC** [comment]
Did you have enable symlinks ?
https://github.com/organicmaps/organicmaps/blob/master/docs/INSTALL.md#getting-sources

**Comment by biodranik** [comment]
Did you run ./configure.sh as it was described in INSTALL.md?

**Comment by matheusgomesms** [comment]
Not sure if it's a dumb issue, but I tried again. My steps:

0 - clean all old files
1 - cloned repository with `git clone --recurse-submodules https://github.com/organicmaps/organicmaps.git`
2 - after checking everything was done (even 3rd party files), entered the folder and ran `bash ./configure.sh`
3 - got:

> Initializing repository with default values in Open-Source mode.
> 
> Could not find a suitable toolset.
> 
> You can specify the toolset as the argument, i.e.:
>     ./build.sh [options] gcc
>
>...
>
>Building B2 engine..
>Failed to build B2 build engine

I tried to update manually B2 (looking for some answers on internet), also tried to enable symlink with `git config --global core.symlinks true` later (maybe I had to do this before?), but still nothing. I later installed all dependencies to build the desktop app (just a test), with `brew install cmake ninja qt@5`, and could not run configure.sh.

Finally, I still could not run on Xcode.

**Comment by biodranik** [comment]
Did you install Command Line Tools? Try `xcode-select --install`

**Comment by matheusgomesms** [comment]
> Did you install Command Line Tools? Try `xcode-select --install`

Aaaah, that did the trick, thanks a lot you all!

It wasn't clear that to me, shall I update INSTALL.md to make this step clearer?

**Comment by biodranik** [comment]
Yes please. Something like "Make sure that Command Line Tools are installed".
