### ISSUE TITLE
Funicular Station is rendered with Train Icon instead of Funicular Icon

### ISSUE THREAD

**Issue by patepelo** [organicmaps/organicmaps#5169]
**Describe the issue**
If you look at the Montartre Funicular for example. You can see the Train Icon instead. While according to the wiki, there is already a Funicular Icon.

**Steps to reproduce**
1. Go to Montmartre in Paris and see the icon. (Android)

**Expected behavior**
See the Funicular Icon

**Screenshots**
![Screenshot_20230516-124910](https://github.com/organicmaps/organicmaps/assets/23003127/e2df4004-11f8-4f65-8b0d-9fa97084bd63)

**System information:**
Android 

**Additional context**
Please add any other context and important details/notes/comments about the problem here.

**Comment by biodranik** [comment]
What text is displayed when you select this icon?

**Comment by Jean-BaptisteC** [comment]
https://www.openstreetmap.org/node/1507214979
POI is represented like a station maybe a icon for node with funicular=yes

**Comment by patepelo** [comment]
![Screenshot_20230517-100433.png](https://github.com/organicmaps/organicmaps/assets/23003127/17806182-8010-425c-ab75-d98a37ea771e)

**Comment by patepelo** [comment]
version 2023.05.05-5-Google-beta

**Comment by vng** [comment]
Yes, moreover we already have funicular-m icon and it is unused ..

**Comment by biodranik** [comment]
Let's use it!
