### ISSUE TITLE
Make bookmark titles readable in MacOS darkmode

### ISSUE THREAD

**Issue by samcarter** [organicmaps/organicmaps#5171]
**Is your feature request related to a problem? Please describe.**

The desktop version works beautifully with macOS dark mode. The menu bars change colour, popup windows are white text on dark background etc. That's all very nice!

Just a tiny detail: the blue text of bookmark titles is hard to read in dark mode.

<img width="1552" alt="Screenshot 2023-05-16 at 14 21 34" src="https://github.com/organicmaps/organicmaps/assets/43832342/6ef4e2a7-88d6-4479-8e1e-2276a3d4edc7">

**Describe the solution you would like**

A quick solution could be to remove https://github.com/organicmaps/organicmaps/blob/e1b7de9f0854ccf9b07fb2a7fc1b16d0c78f2a91/qt/bookmark_dialog.cpp#L292

Without it, the title will be nicely readable both in light and dark mode:

<img width="1552" alt="Screenshot 2023-05-16 at 14 29 54" src="https://github.com/organicmaps/organicmaps/assets/43832342/f63c391b-dacd-4a6c-a006-50d23da21989">

**Describe alternatives you have considered**

Alternatively one could determine the current colour scheme and only use blue colour for light mode. Here an example how TeXStudio tests for the current colour scheme: https://github.com/texstudio-org/texstudio/blob/be257d72b4275f080cd0e43decb60554b8a991c1/src/configmanager.cpp#L1945-L1960

**Comment by biodranik** [comment]
Why can't you make this change yourself? :)

**Comment by samcarter** [comment]
> Why can't you make this change yourself? :)

@biodranik I find your legal requirements are a bit restrictive, in particular requiring to use a real name https://github.com/organicmaps/organicmaps/blob/master/docs/CONTRIBUTING.md#legal-requirements

**Comment by biodranik** [comment]
@rtsisyk FYI. Do you have any ideas about anonymous contributions?

**Comment by samcarter** [comment]
@biodranik Thanks a lot!
