### ISSUE TITLE
Add new link to Tracker Control

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#5173]
New project was created recently forked from Exodus Privacy platform to analyze permissions and trackers on IOS app

First report is available here:
- https://ios.trackercontrol.org/app/app.organicmaps

I suggest to add link in README.md and website

**Comment by biodranik** [comment]
Cool, what are the results for a competitor? :)

**Comment by Jean-BaptisteC** [comment]
https://ios.trackercontrol.org/app/com.mapswithme.full
https://ios.trackercontrol.org/app/com.google.Maps
https://ios.trackercontrol.org/app/com.waze.iphone

**Comment by Jean-BaptisteC** [comment]
Maybe doing same thing on website ?

**Comment by biodranik** [comment]
Yes )
