### ISSUE TITLE
App icon is totally Google Maps

### ISSUE THREAD

**Issue by jidanni** [organicmaps/organicmaps#518]
Okay, I have just installed the app for the first time and I haven't even opened it but the icon looks to me totally like some former Google maps icon. You got the same rainbow colors and seemingly Google Maps pin. All I know is other apps' icons don't look so much like Google maps' etc. icons. Sure you could say it's not exactly like Google Maps' (current) icon but it sure gives the impression.

**Comment by jidanni** [comment]
Maybe put a big O on top of it. But then of course it would look like Opera browser's icon.

**Comment by jidanni** [comment]
In fact the icon also looks like Apple maps' icon.

**Comment by Suburbanno** [comment]
The new icon will be this:
![image](https://user-images.githubusercontent.com/13632826/120949971-26450000-c71c-11eb-8be2-a9d3e6ebe584.png)

**Comment by rtsisyk** [comment]
Please wait for the next release - already tagged, will be available after review.

**Comment by jidanni** [comment]
> The new icon will be this:

OK that's much different than Google Maps... too different.
Perhaps toss in a road or two, or some folded paper map, or
something to differentiate it from a soybean company.

**Comment by jidanni** [comment]
https://www.google.com/search?q=gis+company+logo&tbm=isch hmmm....

**Comment by julianfairfax** [comment]
Personally I prefer the old icon. I think it looked more like a maps icon, fit it in better with Android, and resembled the GNOME Maps icon pretty well, which is quite a nice one.

**Comment by julianfairfax** [comment]
OpenStreetMap and GNOME Maps icons for comparison:
![image](https://user-images.githubusercontent.com/43753131/130283618-91b3761d-66e4-4624-b7fb-835578891af5.png)
![image](https://user-images.githubusercontent.com/43753131/130283563-5d68bded-86f7-42df-bbaf-7bc563186ab3.png)
