### ISSUE TITLE
Add GitHub link to Google Play page

### ISSUE THREAD

**Issue by jidanni** [organicmaps/organicmaps#519]
Nowhere on the Google Play page is a link to this GitHub. Sure everyone can go indirectly with more clicking, but to show your determination to open source please put a link to Github right there on the Google Play page.

**Comment by rtsisyk** [comment]
Let me check Google guidelines on link in the description.  BTW, we have a GitHub link in the Settings->About.

**Comment by jidanni** [comment]
> BTW, we have a GitHub link in the Settings->About.
I'm trying to increase the ways to get to GitHub one day if the app doesn't launch.

**Comment by rtsisyk** [comment]
Done.
