### ISSUE TITLE
disused amenity is shown on the map

### ISSUE THREAD

**Issue by Ilav1** [organicmaps/organicmaps#5195]
Hello, I recognized that a disuesed ameneties are shown in the map with opening hours. It doesnt appear in the search but is still shown on the map. I think that disused amenities should not be shown on the map.
Foe example: https://omaps.app/84JMSIamzq/Commerzbank

![Screenshot_20230519-231959_Organic Maps](https://github.com/organicmaps/organicmaps/assets/102852954/4ae16d71-c234-4808-b680-9a32eece9c35)

**Comment by RicoElectrico** [comment]
It is probably shown because of `entrance=main` tag. Guess that's what "Haupteingang" means.

**Comment by biodranik** [comment]
If it's OpenStreetMap.org data issue, then please fix it in OpenStreetMap.org and close OM issue.

**Comment by map-per** [comment]
I fixed the problem in OpenStreetMap
