### ISSUE TITLE
"Water turbine" type is not rendered as water layer

### ISSUE THREAD

**Issue by simonschaufi** [organicmaps/organicmaps#5197]
**Describe the issue**
I just noticed that a damn which is categorized as "water turbine" is not rendered as water layer. The node is https://www.openstreetmap.org/relation/5583334 and in comparison this node https://www.openstreetmap.org/way/163172081 IS rendered as water.

I don't know if this is an OSM categorization problem or a render problem in OM.

**Expected behavior**
https://www.openstreetmap.org/relation/5583334 is rendered as water

**Screenshots**

![Screenshot_20230520-203724_Organic Maps](https://github.com/organicmaps/organicmaps/assets/941794/8935dcf9-e83e-4488-9481-a479ec542fd6)

**Comment by vng** [comment]
Looks like there was a broken multipolygon. The lake will be ok in the next data update.

I suspect that power=generator tags should be removed from the lake and should be placed on an actual generator building (if not yet).

**Comment by vng** [comment]
<img width="954" alt="Screenshot 2023-05-20 at 12 47 17" src="https://github.com/organicmaps/organicmaps/assets/175612/84ac8c7a-23f5-43cf-812c-5cbf7049eef4">

**Comment by simonschaufi** [comment]
Sweet, thanks.
