### ISSUE TITLE
Add setting to disable fullscreen mode on tap on empty space

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#5199]
**Is your feature request related to a problem? Please describe.**
Some users do not want map controls to hide when touching an empty map area.

**Describe the solution you would like**
A setting to toggle this behavior.

**Comment by biodranik** [comment]
We don't have much complaints so far. Only a few people mentioned it (two?).

What should happen when a user taps on the empty area instead? "Nothing" is not good, it looks like "it doesn't work".

**Comment by arnaudvergnet** [comment]
Haven't given it much thought yet, just wanted to create an issue so we can track that request

**Comment by pastk** [comment]
One (raw) idea is to select any point on the map not just POI (instead of using a long tap for it) https://github.com/organicmaps/organicmaps/issues/1894.

**Comment by pastk** [comment]
No longer an issue after #7876
