### ISSUE TITLE
Add MGRS coordinates support.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#5204]
https://cove.army.gov.au/article/smart-soldier-understanding-military-grid-reference-system

Separate issue after discuss here https://github.com/organicmaps/organicmaps/issues/4715

**Comment by strump** [comment]
Added UTM & MGRS formats to Android app in #5225.

Need to add all supported formats to iOS.

**Comment by Jean-BaptisteC** [comment]
After support is added on IOS, close #1572
