### ISSUE TITLE
Bookmark: Pinning

### ISSUE THREAD

**Issue by pabloscloud** [organicmaps/organicmaps#5205]
**Is your feature request related to a problem? Please describe.**
It's always a little heavy to go too bookmarks, then click the correct list and the address.

**Describe the solution you would like**
Either pinning bookmarks above the list view or add 2 options above the lists. One for work and one for home.

**Describe alternatives you have considered**
![Screenshot_20230521-101402_Organic Maps](https://github.com/organicmaps/organicmaps/assets/93644977/59cd96db-eda7-4892-a02f-025cadd5ec47)

Just looking up my home address and work address manually every time.

**Additional context**
In relation to #4899

**Comment by biodranik** [comment]
Link it with existing Home issues please.

**Comment by pabloscloud** [comment]
> Link it with existing Home issues please.

Wdym "home" issues?

**Comment by Jean-BaptisteC** [comment]
#4732

**Comment by Jean-BaptisteC** [comment]
Duplicate of #4233 and #5619
