### ISSUE TITLE
Map objects beneath the Routing Info panel should not be selectable.

### ISSUE THREAD

**Issue by hoizan** [organicmaps/organicmaps#5218]
When planning a route, a route info panel appears at the bottom of the phone screen once it is done. For car, wallk and bike route planning, the panel will have a Start button on it, and a altitude graph for cases of walking and biking. 

Most users will tap on the start button to start the navigation; however, if users will to tap on any parts of the panel other than the start button, say if the altitude graph is tapped on, this will normally cause a random POI beneath the panel to be seleceted, which is not what users want.After all, the map is hidden under the panel. 
A new user might want to check on the altitude graph, or the routing panel itself to see if they are expandable for more info. Like all other pop-up panels, objects beneath it should not be selectable.

Similarly, the Directional Arrow panel show during the navigation, is also having the same issue. Tapping on it will cause to select a POI beneath it.

**System information:**
 - Android 13 
 - Organic Maps version: [2023.05.08-7-Google
 - 

https://github.com/organicmaps/organicmaps/assets/92556284/f59a2c51-20e0-40fb-a74c-7e3f0989a8e2

Samsung S21+

**Comment by biodranik** [comment]
@arnaudvergnet please fix it :)

**Comment by Jean-BaptisteC** [comment]
How i remove start or end point, if we remove ability to open place page from this IHM ?

**Comment by arnaudvergnet** [comment]
@hoizan what do you mean by `the Directional Arrow panel show during the navigation`? Can you share a screenshot please?

**Comment by biodranik** [comment]
I assume that POIs under the top left direction panel with direction arrow also passes taps to the map POIs for some reason.

**Comment by hoizan** [comment]
Yes, The top left panel with an arrow on it

**Comment by hoizan** [comment]
Sorry, also the same on the little white arrow panel too.

**Comment by biodranik** [comment]
@arnaudvergnet all panels should catch taps on them, and do not allow taps to reach the map view. The same in routing preview mode I assume.

**Comment by biodranik** [comment]
@hoizan @Jean-BaptisteC can you please test #5222 ?
