### ISSUE TITLE
Display public transport ticket vending machine operator

### ISSUE THREAD

**Issue by Altonss** [organicmaps/organicmaps#5219]
**Is your feature request related to a problem? Please describe.**
Display public transport ticket vending machine operator: this is really useful when there are several railway companies having each their own ticket vending machines.

**Describe the solution you would like**
Display as a "subtitle" under the object name.
osm.org displays it directly on the map, but this may clutter the view.

**Comment by pastk** [comment]
> The brand is already displayed in the subtitle when available, but not the operator.

You mean for transport ticket vending machines there is a brand also?

**Comment by pastk** [comment]
> > You mean for transport ticket vending machines there is a brand also?
> 
> See https://www.openstreetmap.org/node/3510137458 for example

Is it important for a user to see "DB Vertrieb GmbH" (operator) in this case?

"Deutsche Bahn" (brand) is an important bit here, isn't it?

**Comment by pastk** [comment]
I mean in this specific case:
"DB Vertrieb GmbH" is something well-known to end users?
Is it not enough for a machine to be labelled just "Deutsche Bahn" for end-users to understand what tickets they could buy via it?

**Comment by pastk** [comment]
In other words:
if the first machine is labelled as "Deutsche Bahn" in OM and the second machine as "NMBS/SNCB" - would it be enough info for users?

**Comment by dvdmrtnz** [comment]
* Fixed by https://github.com/organicmaps/organicmaps/pull/8595
