### ISSUE TITLE
Downloaded maps confusing

### ISSUE THREAD

**Issue by jidanni** [organicmaps/organicmaps#522]
Today I tapped downloaded maps
![Screenshot_20210607-102759.jpg](https://user-images.githubusercontent.com/1230959/120955582-43151e00-c784-11eb-91ab-30f6df5ce37a.jpg)

**Comment by jidanni** [comment]
Okay, apparently yesterday my download didn't complete and now I'm looking at a pending download. But what is confusing is the words downloaded maps, but the maps aren't downloaded yet. And the screen isn't moving.

**Comment by jidanni** [comment]
![Screenshot_20210607-102748.jpg](https://user-images.githubusercontent.com/1230959/120955755-b028b380-c784-11eb-9fe2-039a017b0f02.jpg)

**Comment by jidanni** [comment]
Above, is even more confusing. We are not actually asking for both maps at all. But it isn't clear.

**Comment by jidanni** [comment]
![Screenshot_20210607-102836.jpg](https://user-images.githubusercontent.com/1230959/120955805-cdf61880-c784-11eb-96cd-6803673a9e14.jpg)

**Comment by jidanni** [comment]
Okay, this above picture is much more understandable.

**Comment by rtsisyk** [comment]
Do you have a firewall or special blocking software installed? We have fast servers, the download should finish in 1-2 min max.

**Comment by biodranik** [comment]
@jidanni Please check that your Downloading Manager service is not blocked, this is a common issue on "privacy-first" phones.

**Comment by jidanni** [comment]
> Do you have a firewall or special blocking software installed? We have fast servers, the download should finish in 1-2 min max.

Ho ho ho... many users have slowest ADSL etc. So 100 MB may take many minutes. In the meantime they might have forgot they were downloading, and "hit the wipe button that made all apps sail off the right side of their cellphone."

**Comment by easrng** [comment]
I also have this issue.

> Please check that your Downloading Manager service is not blocked, this is a common issue on "privacy-first" phones.

My phone's download manager never works, any workarounds?

**Comment by easrng** [comment]
I found the issue, on some phones VPNs interfere with the download manager. I disabled mine and the maps started downloading.

**Comment by jidanni** [comment]
All I know is e.g., for Google Play, no matter how one closes it, the current app that one is updating continues to download.

**Comment by biodranik** [comment]
As we rewrote the Download logic, now it does not use the device's Download Manager, and downloads should work properly even if there are some firewalls or other restrictions enabled.
