### ISSUE TITLE
Underwater tunnels are not visible

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#5220]
Tunnels are now coverd by water and not visible anymore

(before (2023.04.02-7-FDroid) and after (2023.05.08-7-Google), https://www.openstreetmap.org/way/33817648)
![Screenshot (76)](https://github.com/organicmaps/organicmaps/assets/79519062/ddb7be18-f6e0-477f-8452-0b6641e5d34b)
![Screenshot_2023-05-14-09-15-32-153_app organicmaps](https://github.com/organicmaps/organicmaps/assets/79519062/b3028d67-3192-4690-a317-3241ecf9c40a)

_Originally posted by @map-per in https://github.com/organicmaps/organicmaps/issues/4927#issuecomment-1547950912_

**Comment by biodranik** [comment]
@pastk can you please fix it?

**Comment by pastk** [comment]
Tunnels usually have `layer=-1` and we have a `2000` value priority correction added/subtracted for each `layer` step. So an underwater tunnel will have an approx -500 priority (a normal highway is approx 1500).

"Before" water areas were background and had very low priority values (e.g. -10000). So tunnels were "above" still.
#4927 has moved water area into foreground with a priority around 1000, hence tunnels became "below" due to the layer correction.

One possible solution is to make water to have approx -2000 priority. But it won't work if there will be a tunnel with e.g. `layer=-3`...

**Comment by biodranik** [comment]
Can we invent some non-magic numbers approach that will not cause any surprises? Or maybe copy it from some other styles/apps/maps?

**Comment by pastk** [comment]
I would prefer a non-numbers approach too, because relying on number ranges is not robust.
But still, it could be the least evil solution considering other factors like refactoring complexity, etc. Need to think more here...

**Comment by matheusgomesms** [comment]
[This region](https://www.openstreetmap.org/#map=19/40.64146/-8.65330) looks weird on OM, I think because of the new water priority (and I believe tagging is kinda correct).
![IMG_F39B4D3F9112-1](https://github.com/organicmaps/organicmaps/assets/86851490/fe7c9926-430f-4fdf-9f2e-2772ceb622fe)

**Comment by pastk** [comment]
> [This region](https://www.openstreetmap.org/#map=19/40.64146/-8.65330) looks weird on OM, I think because of the new water priority (and I believe tagging is kinda correct).

Thanks for reporting! I've created a separate issue for this case: https://github.com/organicmaps/organicmaps/issues/5235

**Comment by arnaudvergnet** [comment]
Here is [another example](https://www.openstreetmap.org/#map=17/48.85339/2.37024), but from what I understand it does not use man_made=bridge but simply puts the water to layer=-1 and tunnel=yes

| OM | OSM |
|-|-|
| ![Screenshot_20230530-082657_Organic Maps](https://github.com/organicmaps/organicmaps/assets/80701113/a2ec23ba-77d7-47f9-820d-3627d6c8ca68) | ![Screenshot 2023-05-30 at 08-27-14 OpenStreetMap](https://github.com/organicmaps/organicmaps/assets/80701113/3b7e309a-1d06-4158-8354-567d5e45ed36) |

**Comment by arnaudvergnet** [comment]
This area is over 2km long so hopefully it can help test more cases

**Comment by arnaudvergnet** [comment]
In some case, even OSM is wrong. There are a few gardens which show the canal instead. Here the canal should appear only in the center of the circle, because there is a hole in the center. Other gardens so maybe this is an issue with multipolygons on OSM.

| OSM | reality |
|-|-|
| ![image](https://github.com/organicmaps/organicmaps/assets/80701113/ca72b7bb-3805-4fc7-b990-34d50dd9263e) | ![image](https://github.com/organicmaps/organicmaps/assets/80701113/9f58a2b5-1d95-4463-9c14-0bee9af5bdcc) |

**Comment by arnaudvergnet** [comment]
Same here, even OSM has it wrong. There is no pedestrian area on top all the way but it still is a tunnel so it should not show as much.

|OSM | reality |
|-|-|
| ![image](https://github.com/organicmaps/organicmaps/assets/80701113/436af7b3-c050-4237-b1cf-fd1de849a8a3) | ![image](https://github.com/organicmaps/organicmaps/assets/80701113/f071be68-4886-4306-ac10-0c1b7a7965aa) |

**Comment by map-per** [comment]
OSM Carto draws pedestrian areas in the road 'layer'. Therefore they are always on top of everything in the 'landcover' 'layer'.

I'd rather see this as a map data issue, drawing underground water areas is wrong in my opinion.

**Comment by telluroid** [comment]
It is a navigable canal. Why should it not be mapped?

**Comment by pastk** [comment]
> Tunnels are now coverd by water and not visible anymore

By the way, underwater tunnels in seas (not rivers) are visible (e.g. Eurasia tunnel in Istanbul). There water comes from coastlines definition and is rendered separately - I assume before everything else? (@vng is it right?)

**Comment by pastk** [comment]
> Same here, even OSM has it wrong. There is no pedestrian area on top all the way but it still is a tunnel so it should not show as much.
> OSM 	reality
> ![image](https://user-images.githubusercontent.com/80701113/241869963-436af7b3-c050-4237-b1cf-fd1de849a8a3.png) 	![image](https://user-images.githubusercontent.com/80701113/241870020-f071be68-4886-4306-ac10-0c1b7a7965aa.png)

Thanks for the tricky example!

I agree that water tunnels shouldn't be rendered in general. Just like we don't render underground subway lines.
But this is a navigable canal indeed, hence more tricky... Maybe only an outline of it should be rendered or it should be rendered half-transparent...

**Comment by pastk** [comment]
Overall our `layer` handling system is not perfect and need an improvement.

Let's collect here more tricky cases like:
- roads/bridges above buildings
- buildings over roads
- aerialways/powerlines above and below road bridges
- landuse/natural area over/under other area; e.g. a water pool above a garden?
- a roof water pool above a building and roads
- waterways above roads (aqueducts?)
- a road/path crossing under a man_made=bridge
- multi-level bridges
- etc...

**Comment by pastk** [comment]
For example, [around here](https://www.openstreetmap.org/way/1124133497) some under-building passages are visible under 2D buildings and some are not
(all of them are visible under 3D buildings because they're transparent).
Visible:
	`highway-footway`
	`highway-footway-tunnel`
	`highway-service-tunnel`
Hidden:	
	`highway-service layer=-1`
	`highway-service-tunnel layer=-1`
	`highway-footway-tunnel layer=-1`


![roads-under-buildings](https://github.com/organicmaps/organicmaps/assets/18434508/defc5d09-4589-4bbd-8d4a-267f880cbd9b)

**Comment by vng** [comment]
> > Tunnels are now coverd by water and not visible anymore
> 
> By the way, underwater tunnels in seas (not rivers) are visible (e.g. Eurasia tunnel in Istanbul). There water comes from coastlines definition and is rendered separately - I assume before everything else? (@vng is it right?)

This is a different type: natural-coastline water. And it has the lowest priority AFAIR.

**Comment by vng** [comment]
I doubt that we can distinguish non-navigable/navigable somehow (or important/not important).
The picture above looks ok to me.

**Comment by pastk** [comment]
> I doubt that we can distinguish non-navigable/navigable somehow (or important/not important).

There is `boat=yes motorboat=yes` but its tagged on the central waterway, not on the polygon.

**Comment by pastk** [comment]
Another tricky case https://www.openstreetmap.org/way/182078377

Layered tunnel water, man_made=bridge, rails and railway platforms and a building=roof on top..

![water-under-building](https://github.com/organicmaps/organicmaps/assets/18434508/f68073f6-b873-4873-9a75-9f12e8d14f0c)

Note that in 2D mode on z15 the building becomes semi-transparent and the water tunnel becomes very visible - looks strange IMO.

**Comment by pastk** [comment]
Here is one more tricky layering example: https://github.com/organicmaps/organicmaps/issues/5235#issuecomment-1574653711

**Comment by pastk** [comment]
Overall, I support an idea that we shouldn't render underground features generally as they add a lot of clutter to the map, see https://github.com/organicmaps/organicmaps/issues/4961

Road and foot tunnels being a biggest exception.
But usually we should hide areal underground features (like railway platforms, underground buildings, etc.) as they confuse a lot.. Areal water tunnels included.

**Comment by biodranik** [comment]
Can we somehow enable a separate substyle for the underground mode only when necessary? Maybe hiding features on the ground?

**Comment by pastk** [comment]
> Can we somehow enable a separate substyle for the underground mode only when necessary? Maybe hiding features on the ground?

Yes, that would be great (an underground view button idea in #4961 sounds very good).
And this feature is very related to indoor mapping IMO #1308

**Comment by pastk** [comment]
How shall we treat roads/paths crossing over buildings? There are many cases when `tunnel=building_passage` is missing. But probably in most cases the assumption is that the road is under the building (if its on top / above I'd expect to see a `layer=1`).
So it'll be best to show such roads as tunnels, but it'll need non-trivial pre-processing in the generator.. Another option is to keep them invisible like it is now.

And its opposite with the `waterway=dam`. Ways crossing it are assumed to go on top of it IMO (unless there is a `tunnel` or `layer=-1`).


> For example, [around here](https://www.openstreetmap.org/way/1124133497) some under-building passages are visible under 2D buildings and some are not (all of them are visible under 3D buildings because they're transparent). Visible: `highway-footway` `highway-footway-tunnel` `highway-service-tunnel` Hidden: `highway-service layer=-1` `highway-service-tunnel layer=-1` `highway-footway-tunnel layer=-1`
> 
> ![roads-under-buildings](https://user-images.githubusercontent.com/18434508/244086380-defc5d09-4589-4bbd-8d4a-267f880cbd9b.png)

**Comment by vng** [comment]
Treat like if they are mapped correctly. Need special styles for tunnel=building_passage - ok. Not building_passage - doesn't matter, let the building overlap the path.
