### ISSUE TITLE
Update java version on FDroid repository

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#5231]
With this PR https://github.com/organicmaps/organicmaps/pull/5058
We need Java 17 to build app, by default FDroid use Java 11 to build app
To fix problem, you need to update metadata file https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/app.organicmaps.yml?ref_type=heads with this:
```
sudo:
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
```

**Comment by biodranik** [comment]
I don't know how it works, but looks like the recent build was ok: https://gitlab.com/fdroid/fdroiddata/-/commit/24db6e3c853339de37c6266ed5ac44a508668622

**Comment by Jean-BaptisteC** [comment]
Yes, you right
But if we migrate to Kotlin + Compose, we need to update Java version

**Comment by arnaudvergnet** [comment]
Not sure about that, the compose version seems to be working fine with java 11

**Comment by Jean-BaptisteC** [comment]
If we specify java version=17 in build.gradle, we need update metadata file in FDroid repository, i have problem with Exodus app

**Comment by biodranik** [comment]
Looks like FDroid build server already has all java versions.

**Comment by Jean-BaptisteC** [comment]
Maybe, but by default, FDroid server use Java 11
I close this issue, because we do not have any problem now. But it's can be reopen when we migrate to Kotlin
