### ISSUE TITLE
Add man_made=bridge

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#5235]
[This region](https://www.openstreetmap.org/#map=19/40.64146/-8.65330) looks weird on OM, I think because of the new water priority (and I believe tagging is kinda correct).
![IMG_F39B4D3F9112-1](https://github.com/organicmaps/organicmaps/assets/86851490/fe7c9926-430f-4fdf-9f2e-2772ceb622fe)

_Originally posted by @matheusgomesms in https://github.com/organicmaps/organicmaps/issues/5220#issuecomment-1566209206_

**Comment by pastk** [comment]
ATM OM doesn't support the [`man_made=bridge`](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge) tag, hence bridge's outline is not rendered.
When added, it should be put into foreground areas and higher than water areas priority-wise.

(btw, looks like many renderers don't support it yet, i.e. on osm.org Cycle Map and Transport Map don't render it either)

**Comment by pastk** [comment]
Re rendering the garden located on the bridge - its tricky and I didn't find yet any osm-based map that renders it correctly.
Maybe playing with `layer=` might fix it for some renderers (atm both the garden and the bridge outline have `layer=1`).

**Comment by pastk** [comment]
There are some more good examples in #3322 too

**Comment by matheusgomesms** [comment]
Thanks for opening a new issue!

Regardless of the man_made=bridge, the river is over the garden (which has layer=1). Should this happen? On Carto, the road is on top of the bridge, but not the garden. Perhaps a layer=2 would do the trick, but anyway even with that I suspect that water would overlap the garden here on OM.

**Comment by pastk** [comment]
> Regardless of the man_made=bridge, the river is over the garden (which has layer=1). Should this happen? On Carto, the road is on top of the bridge, but not the garden. Perhaps a layer=2 would do the trick, but anyway even with that I suspect that water would overlap the garden here on OM.

You might want to change the garden to `layer=2` (which is actually not right as per OSM mapping guidelines) and see if it helps other renderers - I'm curious also  :)

**Comment by matheusgomesms** [comment]
> You might want to change the garden to `layer=2` (which is actually not right as per OSM mapping guidelines) and see if it helps other renderers - I'm curious also :)

Yeah, I agree. Nonetheless, I changed it on OSM, let's see how it goes! :D

**Comment by matheusgomesms** [comment]
Carto has serious issues with bridge and layer (it can be seen on [their Github](https://github.com/gravitystorm/openstreetmap-carto/issues/3203)). Look how it is now haha

<img width="288" alt="Captura de Tela 2023-05-31 às 19 28 33" src="https://github.com/organicmaps/organicmaps/assets/86851490/8363724f-a415-44f9-8e99-79db10754c73">

Anyway, let's see how it goes on OM, but I suspect the problem will persist.

**Comment by ivanbarsukov** [comment]
![image](https://github.com/organicmaps/organicmaps/assets/14816075/49efafb2-0718-48ba-9e78-5a3eef6d4b53)


Another example here 59.931662, 30.308919

**Comment by pastk** [comment]
> Another example here 59.931662, 30.308919

https://www.openstreetmap.org/relation/3299061

Its a very good tricky example, thanks!
A multipolygon man_made=bridge with a square under it :/ and with a parking on top of it (not rendered in osm.org).

**Comment by 501Ghost** [comment]
I think this issue can be closed.

**Comment by pastk** [comment]
> > You might want to change the garden to `layer=2` (which is actually not right as per OSM mapping guidelines) and see if it helps other renderers - I'm curious also :)
> 
> Yeah, I agree. Nonetheless, I changed it on OSM, let's see how it goes! :D

How does it look in the latest OM now?

**Comment by matheusgomesms** [comment]
> How does it look in the latest OM now?

A bit better, but still not 100% correct:

<img width="350" src="https://github.com/organicmaps/organicmaps/assets/86851490/3dfc7e33-b3af-474d-8e59-8bdacae2c3e5">

**Comment by map-per** [comment]
I think transparency for highways would be good. Here a foot and cycle bridge (1) below the railway bridge is hidden by the bridge area. And also in general being able to see the grass below the bridge, but not the road is weird.

(1) https://www.openstreetmap.org/way/933375495

![signal-2023-07-22-183857_002](https://github.com/organicmaps/organicmaps/assets/79519062/04f53795-19c8-4807-aff4-ece75bd93af2)

**Comment by pastk** [comment]
> I think transparency for highways would be good. Here a foot and cycle bridge (1) below the railway bridge is hidden by the bridge area. And also in general being able to see the grass below the bridge, but not the road is weird.
> 
> (1) https://www.openstreetmap.org/way/933375495

A good case, thanks! The transparency doesn't work because of #5339
