### ISSUE TITLE
Car routing refuses to use ferry where it is reasonable according to tagged opening_hours

### ISSUE THREAD

**Issue by paultjevdh** [organicmaps/organicmaps#5238]
**Describe the issue**
I want to generate a route which crosses the river 'Lek' from Culemborg. Only when I route from the ferry terminal itself, the generated route uses the ferry. When I start from 10m from the ferry terminal, the generated route is an elaborate scenic route.

**Steps to reproduce**
1. Route 'from' the ferry terminal in Culemborg (the Netherlands, south side of the river) to the ferry terminal on the north side (Schalkwijk)
2. The route uses the ferry:
![Screenshot_20230530-222426](https://github.com/organicmaps/organicmaps/assets/59084059/03d4993e-c5d1-4c16-923a-9662639be052)
3. Change the departure point to the veerweg, 10m from the ferry terminal, 
4. Now the route takes a ling detour
![Screenshot_20230530-222353](https://github.com/organicmaps/organicmaps/assets/59084059/153e9b24-abc4-4bda-af3b-0ef99256a92e)
Zoom in to the departure point
![Screenshot_20230530-222413](https://github.com/organicmaps/organicmaps/assets/59084059/eea6bf43-0b19-4fb8-8be9-2b6d43250a18)

**Expected behavior**
Use the ferry when it is quicker, such as in the example above. It only takes 5 minutes (I changed that recently, it used to be 0 mins) and goes about 6 times every hour in both directions so it takes 10 minutes at the most if you take waiting time into account. 

 - Operating system and its version: Android 11
 - Organic Maps version: 2023.05.08-7-FDroid
 - Device Model: Nokia 7.2

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/7094927

BTW, better title  would be something similar to "Car routing refuses to use ferry where it is reasonable according to tagged opening_hours"

Car routing disliking and avoiding ferries is fine and expected.

**Comment by paultjevdh** [comment]
The proposed change of title is fine.
The absurd detour for a 5m change in starting point is still weird though. The images above show that the router advises to drive 30km in 32min, whereas the ferry connection takes only 15 minutes. That 10m extra driving should not be responsible for an expected delay of more than 17 minutes in order to make the proposed detour a faster option.
Note that when using pedestrian or bicycle routing the additional time to get on the ferry is only 8 minutes (23 total crossing time whereas the route from the ferry terminal is only 15 minutes). Apparently a waiting time of 8 minutes is added, but:
- this should be the same regardless of means of transport
- This should be a realistic number.

For now I'll assume that defaults were used for both the crossing time (15 minutes, whereas the current map data for organic maps probably contains 0) and the waiting time. I added an interval key value (10 minutes) on openstreetmap just now, and a few days ago I changed the crossing time from 0 to 5 minutes. I hope this fixes the issue for this crossing in the next map release. I still think that the chosen values are too extreme, and inconsistent across different modes of transport.

**Comment by biodranik** [comment]
Adding ferry schedule info into OSM and processing it with the router algorithm can help in these cases. It can improve with better public transport support and GTFS feeds (are there any for ferries btw?).

Another heuristic can take into account ferry length and use it when calculating boarding delay penalty.

**Comment by Jean-BaptisteC** [comment]
Fixed in 2023.12.21-1-Google
