### ISSUE TITLE
Extreme battery drain

### ISSUE THREAD

**Issue by Donkey-Doug** [organicmaps/organicmaps#524]
I only used the app for 5 minutes and it consumed 30% of my battery. My battery has a size of 4000mAh.

Device: Xiaomi Mi 9T Pro
Android: Lineage 17.1
Version: 2021-05-21 (Beta)

**Comment by biodranik** [comment]
Wow! That's really unexpected behavior. We need as many details as possible.

1. What did you see in the power manager? Does it confirm that it's Organic Maps?
2. What actions did you do? Did everything work in the app or you saw some errors?
3. Can you please record and share `adb logcat` logs when running the app "from scratch", maybe we can understand more from them.

**Comment by Donkey-Doug** [comment]
Perhaps this was my phone malfunctioning.
