### ISSUE TITLE
Remove html tag in description on Huawei AppGallery

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#5262]
Description on [AppGallery ](https://appgallery.huawei.com/#/app/C104325611?local=en)doesn't support html tag, i suggest to remove tag

**Comment by biodranik** [comment]
@rtsisyk can we automate it by a script during upload, to avoid changing fdroid and google play descriptions? Can gradle strip any HTML tags from the text before the upload?

**Comment by rtsisyk** [comment]
https://github.com/cianru/huawei-appgallery-publish-gradle-plugin/issues/50
