### ISSUE TITLE
Bad translation for French of "Wind generator" string

### ISSUE THREAD

**Issue by Rpnpif** [organicmaps/organicmaps#5265]
Instead of "Générateur de vent" for Wind Generator, it should be translated to the French word: "Èolienne génératrice".
In French "Générateur de vent" means that the generator makes the wind, that it is not the goal.

https://github.com/organicmaps/organicmaps/blob/51c8e411026869fc8b6541e94d6b29e5725fa4c9/data/strings/types_strings.txt#L17775

Thanks.

**Comment by tungbq** [comment]
Can I take this assignment?
