### ISSUE TITLE
Is there a version of Flutter?

### ISSUE THREAD

**Issue by FrancisFYK** [organicmaps/organicmaps#5268]

**Comment by Jean-BaptisteC** [comment]
Not, but maybe we planned to migrate to Kotlin + Compose on Android #5179

**Comment by FrancisFYK** [comment]
Thank you for your reply

**Comment by RedAuburn** [comment]
> Would like to see a flutter version. Flutter allows you to compile apps for desktop and mobile.

there are already native versions for both :) although it's true it's just one codebase for all with flutter, native is preferable imo

**Comment by RedAuburn** [comment]
> Flutter compiles apps into native apps

it doesn't, it uses it's own engine and mimics native widgets
