### ISSUE TITLE
Add support to export in GPX

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#5271]
Import GPX is supported (#5166)
It would be great to export bookmarks in gpx
This features need to improve menu to export bookmarks to give ability to choose export format before start exportation. (Maybe we can add setting to choose prefere format export)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/organicmaps) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/organicmaps/organicmaps/issues/5271">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/organicmaps/organicmaps/issues/5271/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/organicmaps/organicmaps/issues/5271/pledge.svg">
</picture>
</a>

**Comment by biodranik** [comment]
It is important not to increase the number of required clicks to export, so adding two menu items (Export KMZ, Export GPX) instead of one (Export) may be the best way.

CC @cyber-toad

**Comment by Volodymyr-13** [comment]
I really love to have such option too! Export into GPX!

**Comment by cyber-toad** [comment]
@biodranik now I'm thinking about adding this to Android and have a question: looks like the most obvious way is to update method PrepareFileForSharing to pass additional parameter (could be a string "gpx"/"kml" or something else) to core method that will use different export function. But in this case in the same PR someone else need to fix it for iOS because otherwise method will be broken for objectivec client. Or add something like PrepareFileForSharingGpx for new call?
WDYT?

**Comment by biodranik** [comment]
Adding an int enum with kml and gpx (and later GeoJSON) should be fine.

@kirylkaveryn can help you with iOS if necessary.

**Comment by biodranik** [comment]
@cyber-toad note that several files can be exported too, in KML they're archived into KMZ. With GPX we may need to use GPZ, or disable the export of more than one GPX file.

Are there any apps that support GPZ? Is there any specific file format in it, or just a list of gpx files in a zip?

Another question then would be: should we support GPZ import?

**Comment by kirylkaveryn** [comment]
@cyber-toad please feel free to change core method and add this into android. I'll implement it to iOS. Just trigger me when the core method will be done.

**Comment by cyber-toad** [comment]
> note that several files can be exported too,

It is not clear, how it could be exported? Now if we export single file it is exported as kmz with single kml inside. The other option is to export all files in single kmz. So we are going to add export as gpx option for a single bookmark category that will product a single gpx. So looks we should not disable anything, just add a new menu item?

**Comment by 0709wiwiwi** [comment]
1. Import multiple gpx files compressed into zip or gpz (Locus).

 - A single gpx file can contain multiple tracks plus waypoints.  
Next (Cruiser) demo contains 4 alternatives navigation tracks. 
Usage: Select the prefered trajectory than start Cruiser navigation.
[Ediger_Eller to Cochem navtrk A_B_C_D.gpx.txt](https://github.com/organicmaps/organicmaps/files/15233134/Ediger_Eller.to.Cochem.navtrk.A_B_C_D.gpx.txt)

A single gpz file can additionally transfer (files) images.
Info: https://github.com/Logiqx/gpx-ideas/blob/main/docs/usage/gpz/README.md
