### ISSUE TITLE
Routing off motorway and immediately back on

### ISSUE THREAD

**Issue by shompoe** [organicmaps/organicmaps#528]
Several times I have noticed the app direct me to leave motorways, go straight over the roundabout, and merge back onto the same motorway, same direction.

So I tried a route along the same stretch of motorway using openstreetmap.org website to check if it was a problem in the map data but could not reproduce the problem.

I have screenshots of this issue but for some reason I can no longer attach images on github.

**Comment by j5k** [comment]
Maybe related to #353?

**Comment by shompoe** [comment]
Ah yes, this looks like the same problem.

--- 
Mark Desrousseaux



8 Jun 2021, 14:35 by ***@***.***:

**Comment by jeremiah-miller** [comment]
I've been seeing this issue on organic maps where I wouldn't see it when using osmand. I can post the specific highway if needed, but it seems like a routing algorithm issue rather than a data one to me (but that's just a hunch)

**Comment by biodranik** [comment]
Please share exact coordinates for us to debug and test. Also, please, double-check that the route wasn't broken in the OSM data at the time of our maps data generation.

**Comment by shompoe** [comment]
I'm sorry but since I logged this issue my phone died and I had to replace it. So I no longer have the screenshots and I cannot remember where I was driving at the time.

**Comment by shompoe** [comment]
Oh wait, I remember what road and was able to reproduce it in the app. Starting from Margate and going to Hemel Hempstead (United Kingdom). On M2 at junction 4 is where the error occurs.

**Comment by shompoe** [comment]
> Also, please, double-check that the route wasn't broken in the OSM data at the time of our maps data generation.

I'm sorry, I don't know how to do this.

**Comment by jeremiah-miller** [comment]
33.461132, -112.083156

**Comment by jeremiah-miller** [comment]
> 33.461132, -112.083156

That's an intersection where the issue occurs if you route from a couple miles west of there to a couple miles east of there (and vice versa) so that the route uses the highway

**Comment by shompoe** [comment]
Here is another example of the same problem.

![Screenshot_20210719-181955](https://user-images.githubusercontent.com/54352351/126200804-316b05a7-9cdb-4d0a-8f0b-82ab768a23cb.png)

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=52.45827%2C-0.73627%3B52.37246%2C-0.68489#map=11/52.4146/-0.7173&layers=N

**Comment by vng** [comment]
This issue is fixed. Could you please check on latest app and data version, if possible?
