### ISSUE TITLE
Support OSMAnd gpx extensions

### ISSUE THREAD

**Issue by cyber-toad** [organicmaps/organicmaps#5287]
@cyber-toad it would be amazing if you could also support OSMAnd gpx extensions for interoperability. I don't know if we need everything but here's [documentation](https://osmand.net/docs/technical/osmand-file-formats/osmand-gpx) so you could take a look.

_Originally posted by @pm4rcin in https://github.com/organicmaps/organicmaps/issues/624#issuecomment-1553432814_

For now looks like only color is supported by OM internal model

**Comment by cyber-toad** [comment]
@utack thanks for suggestions, I created an issue for Garmin colors: https://github.com/organicmaps/organicmaps/issues/5309

**Comment by cyber-toad** [comment]
@pm4rcin I made some initial implementation, but I have difficulties with testing it. Based on spec (https://osmand.net/docs/technical/osmand-file-formats/osmand-gpx/) it looks like only tracks could be colored. But looks like it is possible to assign color to waypoints only: https://github.com/osmandapp/web/blob/fb065eb598992235fa2e664f55dc92ceeb1bc3b9/main/docs/user/personal/tracks.md?plain=1#L122? I tried to record some tracks with OSMAnd, had some issues with it - it stores them somewhere and I don't understand how to assign colors for them. Do you have any examples of such tracks/waypoints sets with colors so I can test with them? For privacy you can remove all points except 1-2 of them and assign any coordinates - I just need to see a structure of this file.

**Comment by pm4rcin** [comment]
Here's 2 random waypoints each with different color. Looks like the "folder" to store them can also have color. And the track with color. Looks really simple. 
[track.txt](https://github.com/organicmaps/organicmaps/files/11869151/track.txt)
[favorites-Testowa.txt](https://github.com/organicmaps/organicmaps/files/11869152/favorites-Testowa.txt)

**Comment by cyber-toad** [comment]
> Here's 2 random waypoints each with different color. Looks like the "folder" to store them can also have color. And the track with color. Looks really simple. [track.txt](https://github.com/organicmaps/organicmaps/files/11869151/track.txt) [favorites-Testowa.txt](https://github.com/organicmaps/organicmaps/files/11869152/favorites-Testowa.txt)

Thanks, it helps a lot. I created initial PR: #5400

**Comment by cyber-toad** [comment]
https://github.com/organicmaps/organicmaps/pull/5400

**Comment by Jean-BaptisteC** [comment]
Hey,
It's seems OM doesn't support color in hex in osmand:points_groups
Do you want, I create a new ticket to track this issue ?
[color_not_working.zip](https://github.com/user-attachments/files/19170642/color_not_working.zip)

**Comment by cyber-toad** [comment]
> Hey, It's seems OM doesn't support color in hex in osmand:points_groups Do you want, I create a new ticket to track this issue ? [color_not_working.zip](https://github.com/user-attachments/files/19170642/color_not_working.zip)

Thanks for this finding, I created a ticket #10474 for it.
