### ISSUE TITLE
Cycleways have poor visibility if they go through a forest because of the color. (color blind?)

### ISSUE THREAD

**Issue by squeak9** [organicmaps/organicmaps#5289]
**Describe the issue**
I'm a bit colorblind so it might be a colorblind only thing but if you look at any `highway=cycleway` on the map that goes through a `landuse=forest` then it's really hard to make out, i can sorta see it but it doesn't stand out for sure. It might be perfectly fine for people with normal color vision but I would guess that it's at least less visible than an `highway=path` because that's a white dotted thicker line, even `highway=footway` is thicker and dotted and the color is less of an issue (at least for me)

Using night mode it's less of an issue but still the line is very thin.

The color or the lack of contrast it has is the main problem for me, it's way to similar to the green background

I'm really curious if everyone agrees that cycleways are at least a bit harder to make out in a forest than most other types highways. Post your thoughts below.

**Steps to reproduce**
1. Make sure you got the night mode disabled
2. Go to any cycleway that goes through a forest like this one for example: https://omaps.app/w4nByZrznI/Forest
3. Look at the cycleway and see if it's hard to see compared to a lets say a path or a footpath going through a forest (there is one to the west in the example link.

**Expected behavior**
The cycleway should be stand out no matter the background and maybe even should have a thicker line. The contrast is just the exact same which you can see if you look at the app using the grayscale filter on your phone, the cycleway just becomes invisible.

**Screenshots**

Full sized screenshot: https://github.com/organicmaps/organicmaps/assets/73029732/4dd0d8fd-657f-43f1-ad71-2fc75c070e71
![2023-06-08_11-59-24](https://github.com/organicmaps/organicmaps/assets/73029732/1cdf9621-ec81-4ebb-82c6-3d2faf869cd4)

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.06.04-13-Google (but it's been like this for a while)
 - Device Model: OnePlus 8T (KB2003)

**Additional context**
If you're designing anything you can try to test it using the grayscale setting [on your PC](https://support.microsoft.com/en-us/windows/use-color-filters-in-windows-43893e44-b8b3-2e27-1a29-b0c15ef0e5ce) or [your phone](https://support.google.com/accessibility/android/answer/11183305?hl=en#zippy=%2Cuse-color-correction) and if you can still use the app in some way then it should be fine. I'm not saying it has be absolutely usable in every way without color but it should at at least be somewhat usable.
Example: Even if you can't tell different ways apart in grayscale you should **at least see that there are ways there**, the rest you can find out by holding your finger on the way.

**Comment by endim8** [comment]
wow yes that's a definite accessibility issue, they are completely invisible
<img src="https://github.com/organicmaps/organicmaps/assets/26939824/4061dc76-21cc-4c17-b42e-99a8218da6f3" height="400px">

**Comment by biodranik** [comment]
@pastk will you take a look?

**Comment by pastk** [comment]
I never liked the cycleways color in OM :) Its too screaming on a default light grey background and now it appears its not very visible in the forest...

Any ideas for a better color and/or line style?

**Comment by pastk** [comment]
More generally - we really need a graphic-design-minded person to constantly keep an eye on the color palette we use and associated accessibility issues..
