### ISSUE TITLE
[iOS] Not all POIs shown at top zoom level

### ISSUE THREAD

**Issue by geodavey** [organicmaps/organicmaps#529]
![organic-maps-spar](https://user-images.githubusercontent.com/25945912/121194447-a7101300-c866-11eb-8eb5-af29bda8e5d5.png)

In the above image,

- Panel 1: Map zoomed into highest zoom level (Spar is not shown)
- Panel 2: Search for "Spar" shows the Spar
- Panel 3: Spar selected
- Panel 4: POI selection screen closed, Spar still displayed

Once zoomed out after panel 4 the screen goes back to the the screen showed in Panel 1.

Here is the same area in OSM Mapnik at top zoom level:
![screenshot-area-2021-06-08-144427](https://user-images.githubusercontent.com/25945912/121196086-16d2cd80-c868-11eb-92db-e0aa7d282583.png)

How are POI label priorities determined? Ideally all POIs would be shown at the highest zoom level, or perhaps the max zoom can be increased so that these POIs can be shown? Note that this happens also in MAPS.ME so it's not specific to this project. Both features are amenity/shop nodes.

Relevant links:
- Area in OSM: https://www.openstreetmap.org/#map=19/28.64873/-17.90070
- Spar node: https://www.openstreetmap.org/node/408515252
- Bar Dos Pinos node: https://www.openstreetmap.org/node/6379246170

Thanks so much for developing this! I know you are all inundated with issues & comments but thought this should be on your radar though it's not a critical fix.

**Comment by biodranik** [comment]
Looks like the rectangle from the nearby feature overrides the Spar node. Need to check the drape renderer engine, it may expand the rect at some constant value which probably may be reduced.

**Comment by vng** [comment]
Fixed in next update.
