### ISSUE TITLE
Incorrect display of the Kyiv red metro line

### ISSUE THREAD

**Issue by Scapior** [organicmaps/organicmaps#5299]
**Describe the issue**
The red line is rendered as a circle route.

**Steps to reproduce**
1. Open Kyiv city (the map "Kiev Oblast")
2. Menu -> "Map layers" -> Tap "Metro"
3. Look at the red metro line

**Expected behavior**
The red line ends don't connect.

**Screenshots**
![photo_2023-06-09_22-36-23](https://github.com/organicmaps/organicmaps/assets/23495305/11acce2b-dd7b-4ee0-af02-5d57af083bda)

**System information:**
 - Operating system and its version: iOS 16.5
 - Organic Maps version: 2023.06.04-12
 - Device Model: iPhone SE2
 - OpenStreetMap data: 2 June 2023

**Comment by alexey-zakharenkov** [comment]
This happens when an element (stop or platform) of the first station is mistakenly repeated at the end of the route.

Fixed in the changeset https://www.openstreetmap.org/changeset/137160827

**Comment by Jean-BaptisteC** [comment]
Fixed in 2023.07.13-10-Google
