### ISSUE TITLE
Gpx track not imported and no errors

### ISSUE THREAD

**Issue by grigio** [organicmaps/organicmaps#5304]
Some tracks gpx arent imported and no error is given. I attach an example
[VarianteGleisa.GPX.txt](https://github.com/organicmaps/organicmaps/files/11712556/VarianteGleisa.GPX.txt)

I've added. txt to be able to upload it

**Comment by hoizan** [comment]
I tried downloaded the file and renamed it with .gpx extension. I have no issue. OM imported it successfully.

**Comment by Jean-BaptisteC** [comment]
Problem is solved, can you close issue ?

**Comment by biodranik** [comment]
The issue is likely in folder permissions. OM can't read file from Downloads folder for example. Did you download file using browser? Can you open it from an email app or messenger?

**Comment by hoizan** [comment]
Some test cases  on Samsung S21+ and A33 (Android 13 ) :- 

OM ->  Download                 -  NG  (Download folder not accessible)
OM ->  Documents folder  -  OK  
OM ->  Folder X                    -  OK

File manager -> Download folder -> GPX file -> OM    -  OK
File manager -> Folder X  -> GPX file -> OM                   -  OK

Telegram -> GPX attachment    -  OK     ( OM in App pick list )
Whatsapp -> GPX attachment   - NG      (OM not in App pick list)
Gmail ->  GPX attachment         -  NG     ( OM not  in App pick list)

**Comment by biodranik** [comment]
Is OSMand in the list for Whatsapp and Gmail?

**Comment by hoizan** [comment]
Yes, OSMand is in the list for Whatsapp and Gmai

**Comment by biodranik** [comment]
@cyber-toad can you please check if we are missing something compared to OSMand?

**Comment by Jean-BaptisteC** [comment]
I have doing tests, OM appears correctly when i want open gpx or kmz from WhatsApp

**Comment by cyber-toad** [comment]
> @cyber-toad can you please check if we are missing something compared to OSMand?

Yes, I'll have a look

**Comment by grigio** [comment]
i tried with another track a .gpx inside a .zip and it worked. Maybe it's a permission issue or a compegis format problem

**Comment by hoizan** [comment]
How how those cases reported in my previous comment :

[...]
![20230613_082420](https://github.com/organicmaps/organicmaps/assets/92556284/b5479319-c419-4373-9d57-1d99f0104299)

Telegram -> GPX attachment - OK ( OM in App pick list )
Whatsapp -> GPX attachment - NG (OM not in App pick list)
Gmail -> GPX attachment - NG ( OM not in App pick list)
