### ISSUE TITLE
[mobile][linux] Support two-finger gestures (zoom, rotate)

### ISSUE THREAD

**Issue by Silmathoron** [organicmaps/organicmaps#5306]
At the moment, though they seem to be supported in theory, two-finger gestures (pinch to zoom, rotate) do not work reliably.
Most of the time they don't work at all (only double tap to zoom in works), though on rare occasions they do (seems random, could not reproduce). The one time they worked, single finger motions to translate the map was not working instead, meaning that even 1-finger actions were considered as 2-finger moves and led to zoom or rotation.

**Steps to reproduce**
Most of the time, trying to use 2-finger gestures should simply not work.

**Expected behavior**
Both 1- and 2-finger actions work reliably.

**System information:**
 - Operating system and its version: PureOS 10 (byzantium)
 - Organic Maps version: 2023.06.04-1-acc7c054-dirty-linux (flatpak)
 - Device Model: Librem 5

**Comment by bam80** [comment]
This should be addressed in QML UI we are working on.

**Comment by tristanvigar** [comment]
> This should be addressed in QML UI we are working on.

Are there any active branches/PRs for folks that are curious to have a look?

**Comment by bam80** [comment]
@YaAlex3

**Comment by olof-nord** [comment]
I love that OrganicMaps is available for Linux Phones!
It runs fine on my Librem 5, but I quickly wished for this feature as well. It would make usage way more intuitive and user-friendly.

PureOS 10
2023.07.13-1-b52b42bd-dirty-Linux
Librem 5

**Comment by Jean-BaptisteC** [comment]
@Ferenc- fixed by #6738?

**Comment by Ferenc-** [comment]
> @Ferenc- fixed by #6738?

Currently considered features:
- [x] Basic 2 finger pinch zoom
- [ ]  Fine tuned 2 finger zoom, that zooms immediately and proportionally to the pinch movement
- [ ] Basic 2 finger rotate
- [ ]  Fine tuned 2 finger rotate, that rotates immediately and proportionally to the rotation movement

Currently NOT considered:
- [ ] Pan gesture 
- [ ] Swipe gesture ???

**Comment by Ferenc-** [comment]
Done in https://github.com/organicmaps/organicmaps/pull/9616
