### ISSUE TITLE
Search for house addresses without streets but with addr:place

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#5307]
A lot of villages and even towns in Europe and all over the world use the addressing scheme without street address (no addr:street, but [addr:place](https://wiki.openstreetmap.org/wiki/Key:addr:place) instead). Organic Maps can't find these addresses.

The fix is not trivial, and this issue tracks the progress on it.

Related issues:
- https://github.com/organicmaps/organicmaps/issues/557
- https://github.com/organicmaps/organicmaps/issues/603
- https://github.com/organicmaps/organicmaps/issues/2689
- https://github.com/organicmaps/organicmaps/issues/5075
- https://github.com/organicmaps/organicmaps/issues/6821

**Comment by vng** [comment]
Some non-obvious examples:
place=island : https://www.openstreetmap.org/relation/1576343
addr:place : https://www.openstreetmap.org/way/111636419

**Comment by vng** [comment]
Should add place=allotments? Or place=neighbourhood is enough?
https://www.openstreetmap.org/relation/2414686
https://www.openstreetmap.org/node/1833400785

**Comment by hungerburg** [comment]
I came here because a user of organic maps adds addr:street tags to nodes/ways where addr:place is given and is the correct tagging, as the streets in these villages do not have names.

If organic maps is prompting users to do that please reconsider. The name of the village does not belong into addr:street.

**Comment by vng** [comment]
@hungerburg Could you please give the links on bad OSM changesets?

**Comment by hungerburg** [comment]
@vng E.g. changeset [141144838](https://www.openstreetmap.org/changeset/141144838) - There are more of that kind in the area. I commented on this changeset, the user continues with these gratuitous "additions".

**Comment by biodranik** [comment]
@vng One possible fix is to disable showing the street in the editor (and in the search) if addr:place is already present.

**Comment by hungerburg** [comment]
Another organic-maps user now startet to add address:street to houses, in a village, where there are no named streets. See changeset [143591644](https://www.openstreetmap.org/changeset/143591644) - They also use google as a datasource - this is against the OSM contributor terms.

Please modify your application to prevent users from doing this.

**Comment by vng** [comment]
@biodranik No because an address can have place and street together. https://taginfo.openstreetmap.org/keys/addr%3Aplace#combinations

Probably, the best option is to filter if a user puts the same name into a street as in existing addr:place or addr:city.

**Comment by biodranik** [comment]
@vng isn't it better to show the street from addr:place in the Street name in the UI, so users won't try to edit it? The street address also should be properly displayed in the Place Page on the selection, then it won't be edited by users.

@hungerburg can you please create a separate issue for that, with these comments?

**Comment by vng** [comment]
One more fancy mapping example:
- allotments (residential) "Баравая" https://www.openstreetmap.org/way/145292427
- hamlet "Баравая" https://www.openstreetmap.org/relation/7549217
- street "Баравая вулица" https://www.openstreetmap.org/way/40554124
All are placed close to each other.

And search for "Баравая 7" gives incomplete results. Also, want to search for "Минск Баравая 34" (https://www.openstreetmap.org/way/62164458)

**Comment by biodranik** [comment]
@vng I've created a separate issue to disable adding streets in the editor to addresses with the existing addr:place: https://github.com/organicmaps/organicmaps/issues/6821

This is the most important fix now. After that, we can improve the editor in https://github.com/organicmaps/organicmaps/issues/6491

**Comment by vng** [comment]
Closing this meta-issue, the Editor is tracked in a separate one.
