### ISSUE TITLE
show at least unusual fee=* info: fee=yes on tourism=viewpoint in object description, show fee=no for museums

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#5308]
See say https://www.openstreetmap.org/node/7093492186

Like wheelchair info is shown

**Comment by Jean-BaptisteC** [comment]
Similar of #1312 and #2254

**Comment by matkoniecz** [comment]
#2254 is kind of duplicate but it is also unclear bag of many ideas that cannot be ever finished
