### ISSUE TITLE
route guidance from a GPX import

### ISSUE THREAD

**Issue by cayenne17** [organicmaps/organicmaps#5314]
Organic maps supports the import of GPX exported from GéoVélo.
However, this is only a display. I'd like the guidance to follow the GPX route.
Is this possible, as I haven't found out how to do it?

I haven't found a similar issue.

**Comment by biodranik** [comment]
https://github.com/organicmaps/organicmaps/issues/1360

**Comment by cayenne17** [comment]
> #1360
@biodranik : Yes, that's exactly it, but with the added bonus of GPX.

Do I close my issue ?

**Comment by cayenne17** [comment]
#2384

**Comment by biodranik** [comment]
GPX or not doesn't matter at all.

**Comment by igor-suhorukov** [comment]
As requested by user in OM telegram channel also: https://t.me/OrganicMapsRu/44674

**Comment by cayenne17** [comment]
@Jean-BaptisteC duplicate with what issue ?
