### ISSUE TITLE
Specific address does not appear in search results

### ISSUE THREAD

**Issue by Benger85** [organicmaps/organicmaps#5328]
**Describe the issue**
There is a specific address that will not appear if you try to find it via search. You can pin point it manualy on the map and navigate to, but search doesn't find it. In OSM it can be found and the object has the correct address.

addr:city 	Vendersheim
addr:housenumber 	4
addr:postcode 	55578
addr:street 	Außerhalb

**Steps to reproduce**
Seek address "Vendersheim, Außerhalb 4, Germany" and it will not appear.

**Expected behavior**
The address should be in the results so I can select it.

**System information:**
 - Operating system and its version: Android 12
 - Organic Maps version: 2023.06.04-13-Fdroid
 - Device Model: Fairphone 4

**Additional context**
This is some kind of farm yard. The street is not existing. "Außerhalb" means "Outside". Every house outside this settlement gets the streetname "Außerhalb" and a number.

**Comment by matkoniecz** [comment]
See also https://www.openstreetmap.org/search?query=Vendersheim%2C+Au%C3%9Ferhalb+4%2C+Germany#map=19/49.86381/8.06849

**Comment by vng** [comment]
Somebody added the street's name and now matching is ok.
