### ISSUE TITLE
maps_generator ：assert USER_RESOURCE_PATH is not None AssertionError

### ISSUE THREAD

**Issue by fyfone** [organicmaps/organicmaps#5329]
./tools/unix/build_[omim.sh](https://omim.sh/) -r desktop ./tools/unix/build_[omim.sh](https://omim.sh/) -r generator_tool ./tools/unix/build_[omim.sh](https://omim.sh/) -r world_roads_builder_tool cd tools/python python -m maps_generator --countries="Canada_Yukon_North, Canada_Yukon_Whitehorse" --skip="Coastline"

 root@3d54e7e14fa3:/home/organicmaps/tools/python# python3 -m maps_generator -h Traceback (most recent call last):   File "/usr/lib/python3.8/[runpy.py](https://runpy.py/)", line 185, in _run_module_as_main     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)   File "/usr/lib/python3.8/[runpy.py](https://runpy.py/)", line 144, in _get_module_details     return _get_module_details(pkg_main_name, error)   File "/usr/lib/python3.8/[runpy.py](https://runpy.py/)", line 111, in _get_module_details     import__(pkg_name)   File "/home/organicmaps/tools/python/maps_generator/__[init.py](https://init.py/)", line 12, in <module>     settings.init(CONFIG_PATH)   File "/home/organicmaps/tools/python/maps_generator/generator/[settings.py](https://settings.py/)", line 229, in init     assert USER_RESOURCE_PATH is not None AssertionError 

I performed operations like this, but why are there still errors

**Comment by matkoniecz** [comment]
@tyfone Can you format code/command/CLI quotes with backsticks?

See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code
