### ISSUE TITLE
[android] Rudimental /sdcard/Android/data/app.organicmaps directory

### ISSUE THREAD

**Issue by ioctl-user** [organicmaps/organicmaps#534]
App creates useless directory, that has only one file: /sdcard/Android/data/app.organicmaps/cache/vulkan_dump.bin . All other staff is inside /data/data/app.organicmaps/ .

It's not a big problem itself, but some users can look this directory for bookmarks and so on, that's a little bit confusing.

So, may be it is possible to avoid creating /sdcard/Android/data/app.organicmaps at all?

**Comment by FabianInostroza** [comment]
I can't access /data/data/app.organicmaps on my phone, maps.me stored maps, bookmarks and other data in /sdcard/Android/data...
Would it be better for organicmaps to use a user accesible folder (ie: /sdcard/Android/...)?

**Comment by biodranik** [comment]
https://developer.android.com/about/versions/11/privacy/storage
