### ISSUE TITLE
Increase size of icons about disabled parking space

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#5342]
During SOTMFR 2023 in Marseille, i have some feedbacks on OM
For somes user, icons about disabled parking space is too small, is it possible to increase size for more visibility ?

**Comment by biodranik** [comment]
How icons are rendered now? Do they have the same standard size, or are they smaller than others?

**Comment by Jean-BaptisteC** [comment]
Icon is smaller, check this:
- [Disabled parking](https://github.com/endim8/organicmaps/blob/master/data/styles/clear/style-clear/symbols/parking-disabled-m.svg)
- [Parking](https://github.com/endim8/organicmaps/blob/master/data/styles/clear/style-clear/symbols/parking-m.svg)

**Comment by dvdmrtnz** [comment]
A white border similar to the ones in https://github.com/organicmaps/organicmaps/pull/3896 could be added to make these icons stand out a bit more

**Comment by Jean-BaptisteC** [comment]
I reopen the ticket because it's seems is not enough.
I have feedback from SOTMFR 2024.
Disabled space parking is also use by old persons which sometimes have a poor eyesight

**Comment by biodranik** [comment]
Bad eyesight is independent from disabled/not disabled status. Does it make sense to increase all icons size when a larger font size is set in settings?

**Comment by dvdmrtnz** [comment]
> Bad eyesight is independent from disabled/not disabled status. Does it make sense to increase all icons size when a larger font size is set in settings?

* https://github.com/organicmaps/organicmaps/issues/6919
