### ISSUE TITLE
Package for Flatpak and upload to Flathub

### ISSUE THREAD

**Issue by andrewshadura** [organicmaps/organicmaps#535]
Packaging for Debian proper is going to be a tricky because of a lot of vendored libraries.

Probably a Flatpak package might get usable results quicker — along with cross-distro support.

_Originally posted by @andrewshadura in https://github.com/organicmaps/organicmaps/issues/395#issuecomment-857836060_

**Comment by fgaz** [comment]
I'm in the process of writing an `app.organicmaps.OrganicMaps` flatpak manifest. Is it ok if I submit it to flathub once it's complete?

**Comment by biodranik** [comment]
We would be grateful for any help in this regard. It would be great if we can control/customize the app's description and other links to make the support easier and to avoid any confusion. Does it make sense to create a fork of flatpak in our org repo, so you can contribute to it, and we can then send official PRs into flatpak from our account?

**Comment by fgaz** [comment]
The best way to do that would be to have [appstream data](https://github.com/flathub/flathub/wiki/App-Requirements#appstream) directly in the repo.

> Does it make sense to create a fork of flatpak in our org repo, so you can contribute to it, and we can then send official PRs into flatpak from our account?

Sure (once the repo is there), or I could just give you access to the repo, or ownership of the repo (and maintainership of the flatpak) can be transferred to you.

**Comment by biodranik** [comment]
Cool, let's start with appstream data in this repo first.

**Comment by fgaz** [comment]
Organic Maps was added to Flathub! https://github.com/flathub/flathub/pull/2968#issuecomment-1104518002

**Comment by biodranik** [comment]
Should this issue be closed?
What is the proper procedure to upgrade/release the package?

**Comment by fgaz** [comment]
> Should this issue be closed?

I think so

> What is the proper procedure to upgrade/release the package?

* Do the usual release stuff in this repo -- changelog, tag, etc
  * **new**: also add the release [here](https://github.com/organicmaps/organicmaps/blob/0abd2a28b14002c70957366e679405a0d02eda66/qt/res/app.organicmaps.desktop.metainfo.xml#L109-L128=)
* Change `commit` and `tag` [here](https://github.com/flathub/app.organicmaps.desktop/blob/master/app.organicmaps.desktop.yml#L39-L40=). The package will be automatically published after 3 hours (the delay can be changed, and the build can be triggered manually, see https://github.com/flathub/flathub/wiki/App-Maintenance)

I'm following this repo and I'll do the last step when I see a release, but you can get added and do that yourself if you want to: just leave a comment in https://github.com/flathub/flathub/pull/2968

**Comment by biodranik** [comment]
Thanks! It would be great if someone can help to monitor our releases and update these files accordingly (and filter out some obvious mobile-only changes from release notes).

**Comment by fgaz** [comment]
> It would be great if someone can help to monitor our releases and update these files accordingly

If we want the flatpak to follow tags from this repo, this should be done _before_ tagging the release though.

About mobile-only stuff, someone should also take some desktop screenshots. Right now the flathub page shows mobile ones

**Comment by andrewshadura** [comment]
Hopefully now the Qt UI gets more exposure and — hopefully — more love from existing and prospective contributors 🙂

**Comment by tpikonen** [comment]
I just installed organicmaps from flathub without problems, so I think this issue should be closed.
