### ISSUE TITLE
Translate places which do not have name:example-language tag yet with DeepL

### ISSUE THREAD

**Issue by d4f5409d** [organicmaps/organicmaps#5370]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
It is useful to know what that one place means in my mother language when the place doesn't have multilingual descriptions and name tags.

**Describe the solution you would like**
Translate the places' names and descriptions and display it in the app instead of the original ones, with the ability to switch back to the original text with a button like the implementation of Megalodon. (3rd party Mastodon client)

**Describe alternatives you have considered**
- How do you solve this issue now with Organic Maps or other apps?
- Attach any examples, screenshots, or screen recordings from other apps that help us to better understand the idea.

Alternatives: fill up the missing name tags (hell lot of time)

**Additional context**

Motive: This feature would highly help travelers across the Globe. This feature would be unique among navigation applications and may get the interest of the masses to use Organic Maps.

**Comment by d4f5409d** [comment]
Or LibreTranslate or Lingva.

**Comment by Jean-BaptisteC** [comment]
Not a good idea to use a translator.
I think it's better to use translations from Wikidata. I guess you want translate names of cities and historic places.
