### ISSUE TITLE
Allow saving routes so you can load and display them 

### ISSUE THREAD

**Issue by uhuznaa** [organicmaps/organicmaps#5399]
I often use Organic Maps for cycling and hiking. Usually I try to plan a route by setting the start and end points and forcing the route where I want it to be by setting waypoints in between.

But as soon as I stop the routing process the route is lost. I hate that. I would really love to plan a route and then save it and reload it to just be able to see where I plan to ride and where I am. And often I want to reuse these routes and then I have to set up them again with every detail, basically re-planning them every fucking time instead of being able to load them again.

So can we please somehow save routes as we can save bookmarks? And share them? So when I have planned a route I get a share button and can save the route or send it to someone else, or export it or whatever. And give me a "load" button when I start to plan a route.

UI-wise this would require just another button for managing routes. Could surely be integrated with all importing and exporting of routes, but simple saving and loading them within Organic Maps should be extremely straightforward and obvious. I think.

**Comment by Jean-BaptisteC** [comment]
Please check similar issues

**Comment by biodranik** [comment]
https://github.com/organicmaps/organicmaps/issues/1785

**Comment by biodranik** [comment]
Closing as duplicate
