### ISSUE TITLE
Google Play. Android Auto quality criteria

### ISSUE THREAD

**Issue by AndrewShkrob** [organicmaps/organicmaps#5404]
Here is the quality criteria that our AA app must fit to be approved by Google Play.
According to this link: [Android app quality for cars](https://developer.android.com/docs/quality-guidelines/car-app-quality)

### Visual design and user interaction
These criteria ensure that your app follows critical design and interaction patterns to offer a consistent, intuitive, and enjoyable user experience in cars. Many elements, such as the navigation drawer, card backgrounds, fonts, and icon colors, are set and rendered by the system. Your app-specific design elements must meet the following criteria when running on a car's head unit screen.

Status | Criteria | ID | Description
-- | -- | -- | --
✅ | Screen Animation | SA-1 | The app must not display animated elements on the screen, such as animated graphics or video.
✅ | Visual or Text Ads | AD-1 | The app must not display text-based advertising other than the advertiser's name or the product name.
✅ | Image Usage | IU-1 | App elements do not display any images on the screen. Exceptions include: <br> * Apps can display a single static image for content context in the background of the consumption screen, such as album art or the advertiser's corporate logo.<br> * Apps can display icons in the content navigation drawer. <br> * Apps can display images and photographs to aid in driving decision-making. <br> * Navigation apps can display an image for lane guidance or junction guidance.
✅ | Permitted Categories | PC-1 | The app must not include features outside the app types intended for cars. For more information, see [Supported app categories](https://developer.android.com/training/cars#supported-app-categories).
✅ | Visual Information on Phone | VI-1 | <b>Android Auto only</b>: If the user must go to the phone screen—for example, to act on a permission request—then the app must display a message instructing the user to only look at their phone screen when it’s safe to do so. For more information, see [Handle general errors](https://developer.android.com/training/cars/media#errors) for media, and [Handle user input](https://developer.android.com/training/cars/apps#handle-user-input) for navigation, point of interest, and internet of things apps).
✅  | App Doesn't Crash | AC-1 | Users must be able to complete tasks in the app using five screens or fewer. For more information, see [Template restrictions](https://developer.android.com/training/cars/apps#template-restrictions).
✅ | Scrolling Text | ST-1 | The app must not display automatically scrolling text.
✅  | Voice Commands | VC-1 | The app must support Google Assistant voice commands. For more information, see [Support voice actions](https://developer.android.com/training/auto/audio#support_voice) for media, and [Support navigation intents](https://developer.android.com/training/cars/apps/navigation#support-navigation-intents) for navigation.
✅ | Delayed Response | DR-1 | App-specific buttons must respond to user actions with no more than a two-second delay.
✅ | Delayed Response | DR-2 | The app must launch in no more than 10 seconds.
✅ | Delayed Response | DR-3 | The app must load content in no more than 10 seconds.
✅  | Contrast | VD-1 | The app must provide icons and colors that meet Android Auto’s contrast requirements. For more information, see [Contrast](https://developers.google.com/cars/design/android-auto/design-system/color#contrast).

### Functionality
These criteria ensure that your app configures correctly and provides the expected functional behavior when running on the car's head unit screen.

Status | Criteria | ID | Description
-- | -- | -- | --
✅ | Expected Performance | EP-1 | App functionality must work as expected or described in the app's Google Play Store listing.
✅  | Expected Performance | EP-2 | When the app is relaunched from the home screen, the app must restore the app state as closely as possible to the previous state.
✅  | Driver Distraction | DD-1 | The navigation audio channel can only be used by navigation apps and for navigation instructions. For more information, see [Voice guidance](https://developer.android.com/training/cars/apps/navigation#voice-guidance).
✅ | Payments | PA-1 | The app must have simple flows if purchases are enabled, using shortcuts such as recent or favorite purchases. For more information, see [Purchase using an existing payment method](https://developers.google.com/cars/design/create-apps/sample-flows/purchase-with-existing-method).<br><br>The app must not allow any of the following:<br> * Setup of payment methods <br>Multiple items to be selected for purchase<br>Commitment to recurring payments, such as subscriptions
✅ | Notification Ads | NA-1 | The app must not present advertisements through notifications.
✅  | Irrelevant Notifications | IN-1 | The app must display notifications only when relevant to the driver's needs.<br>Examples:<br>Good: Notifying the user that a new message has arrived.<br>Bad: Notifying the user about a new album release.
✅ | Navigation Functionality | NF-1 | The app must provide turn-by-turn navigation directions.
✅ | Navigation Functionality | NF-2 | The app draws only map content on the surface of the navigation templates. Text-based turn-by-turn directions, lane guidance, and estimated arrival time must be displayed on the relevant components of the navigation template. Additional information relevant to the drive, speed limit, road obstructions, etc., can be drawn on the safe area of the map.
✅  | Navigation Functionality | NF-3 | When the app provides text-based turn-by-turn directions, it must also trigger navigation notifications. For more information, see [Turn-by-turn notifications](https://developer.android.com/training/cars/apps/navigation#turn-by-turn-notifications).
✅ | Navigation Functionality | NF-4 | When the navigation app provides text-based turn-by-turn directions, it must send next-turn information to the vehicle’s cluster display. For more information, see [Navigation metadata](https://developer.android.com/training/cars/apps/navigation#navigation-metadata).
✅   | Navigation Functionality | NF-5 | The app must not provide turn-by-turn notifications, voice guidance, or cluster information when another navigation app is providing turn-by-turn instructions. For more information, see [Start, end, and stop navigation](https://developer.android.com/training/cars/apps/navigation#starting-ending-stopping-navigation).
✅ | Navigation Functionality | NF-6 | The app must handle navigation requests from other Android Auto apps. For more information, see [Support navigation intents](https://developer.android.com/training/cars/apps/navigation#support-navigation-intents).
❌ | Navigation Functionality | NF-7 | The app must provide a “test drive” mode that simulates driving. For more information, see [Simulate navigation](https://developer.android.com/training/cars/apps/navigation#simulating-navigation).
✅ | Navigation Functionality | NF-8 | The app must draw a light-themed or dark-themed map when instructed to do so. For more information, see [Dark mode](https://developer.android.com/training/cars/apps/navigation#dark-mode).

Status | Description
 -- | -- 
✅ | Done
❌ | Not implemented
❓ | Should be tested

**Comment by pabloscloud** [comment]
Nice to see the current status and that it's being worked on 😁

**Comment by AndrewShkrob** [comment]
Only `Test Drive` mode is left to implement. I'm closing this issue.
