### ISSUE TITLE
Helicoptor navigation: Pop-up missing

### ISSUE THREAD

**Issue by j13m126** [organicmaps/organicmaps#5405]
**Describe the issue**
There is currently no pop-up notification in helicopter navigation that you haven't yet downloaded the map you want to navigate to.

**Steps to reproduce**
1. Click on a destination you haven't downloaded yet.
2. Choose helicopter mode
3. start navigating

**Expected behavior**
As in all other navigation modes, the user should be notified that there's a map missing from the start. Otherwise the user would be notified when he's already in a another country would have to pay for mobile data.

**Screenshots**
This is the pop-up notification helicopter navigation is missing right now.
![photo_2023-06-28_20-55-10](https://github.com/organicmaps/organicmaps/assets/7961926/10b88fc1-02a8-44a9-85a8-d651e9b94cbe)

**System information:**
I tested it on an iPhone 13 and Pixel 6.

**Comment by strump** [comment]
Imagine you want to measure distance between Prague and London (out of curiosity) and you use helicopter router to build straight line from one city to another. Current version will show you this line 1030 km long.

If we add pop-up notification it will block measurement till you download Germany, Netherland, Belgium and UK maps. It's not user-friendly.

Helicopter navigation is not intended to plan a trip to another country. Only for distance measurement and route estimation in a wild.

**Comment by j13m126** [comment]
Ok, I get it. It's intended as a measurement tool primarily. In this case a pop-up isn't necessary.

I was thinking of pilots using it or me using helicopter navigation on an international train trip. Adding a few train stations in between, I guess this way it could be useful as well.

**Comment by Misalf-git** [comment]
I guess "`Download additional maps to create a better route...`" doesn't apply to straight / zig-zag _routes_.

**Comment by biodranik** [comment]
Straight-line routes do not require downloaded maps. Although they can optionally display elevation along the route in the future if maps are downloaded.
