### ISSUE TITLE
Don't display vegetarian cuisine if it's also vegan cuisine in PP

### ISSUE THREAD

**Issue by endim8** [organicmaps/organicmaps#5462]
Additional label is redundant as the existence of vegan food means there is vegetarian food.
Example POI: https://omaps.app/84IIKLVgUd/Turkish_Doner_Kebab

![Screenshot_20230705-133657_Organic Maps](https://github.com/organicmaps/organicmaps/assets/26939824/88d010d0-7699-458b-bf88-154183101135)

**Comment by biodranik** [comment]
There are places that serve both types of food, or only one type of food. It is important to distinguish them.

**Comment by endim8** [comment]
I'm not so sure, any vegan food is automatically vegetarian
(as a vegetarian, I don't find any use in it saying vegetarian over vegan)

**Comment by biodranik** [comment]
1. A vegetarian person may prefer to eat only vegetarian food, not a vegan one.
2. A non-vegetarian and non-vegan person may find vegetarian food places acceptable at some hungry moment, but not vegan ones, for example.

It is very convenient to see if a business offers different types of food.

**Comment by Misalf-git** [comment]
So, the redundancy becomes necessity when in urge for a greek salad which a vegan-only restaurant won't offer.

**Comment by endim8** [comment]
Ah OK, the Greek salad example is a good case against this 👍 also thinking about it, vegan cheese is something everyone but vegans try to avoid 😄
