### ISSUE TITLE
historic=cannon displayed as memorial

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#5463]
tags:
`direction=345`
`historic=cannon`

https://omaps.app/4tddf0XhUA/Memorial
![Screenshot_20230705-134846_Organic Maps](https://github.com/organicmaps/organicmaps/assets/26939824/88661f88-d605-4060-91b0-1a7686f95c4e)

**Comment by endim8** [comment]
Need to properly review https://taginfo.openstreetmap.org/keys/historic#values
to see what other historic tags need custom icons etc. will try to get to it after this uni work push.

**Comment by RedAuburn** [comment]
<img src="https://github.com/organicmaps/organicmaps/assets/26939824/85764ba5-541e-470d-9e15-a21d564fbfaf" width="48px"/>

how about this for the icon?

**Comment by biodranik** [comment]
Good, would be great to see it in the map context )
