### ISSUE TITLE
Distance from shop is shown when location is disabled

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#5467]
**Steps to reproduce**
1. Open search or select categories (Location is disabled on device)
2. Distance is shown foreach results but value is 0 because location is disabled

**Expected behavior**
Shown distance in search only when location is enabled

**Screenshots**
<img src="https://github.com/organicmaps/organicmaps/assets/87148630/15fda85e-fb70-4e89-aa60-ab325474ac57" height=400 />

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.07.05-4-Google-beta
 - Device Model: Pixel 6
@AndrewShkrob

**Comment by biodranik** [comment]
"Location is disabled" means that you started OM and it didn't detect any location yet, right?

@AndrewShkrob it's a regression that should be fixed before the upcoming release.

**Comment by Jean-BaptisteC** [comment]
Yes or user deny location pop-up
