### ISSUE TITLE
Elevation contour lines appear in meters only

### ISSUE THREAD

**Issue by EmberHeartshine** [organicmaps/organicmaps#5498]
**Is your feature request related to a problem? Please describe.**
When toggling the map elevation contour lines, they appear with 100m increments. There is no option to switch to feet.

**Describe the solution you would like**
Tying the contour line units to the units of distance selected (or having a separate option to toggle feet/meters) would be ideal

**Describe alternatives you have considered**
At the moment I have been relying on static maps of the area or mapping utilities such as AllTrails to estimate elevation.

**Comment by biodranik** [comment]
Please see https://github.com/organicmaps/organicmaps/issues/1067

The problem is that isolines now are statically generated at the meters distance. Just displaying feet would be better, but an appropriate solution requires elevation refactoring #4163
