### ISSUE TITLE
Remaining distance is rounded every 10 Km with distances greater than 100 Km

### ISSUE THREAD

**Issue by gpesquero** [organicmaps/organicmaps#5501]
Used OM Version: 2023.07.05-4-Google-beta

While in navigation mode (by car or any other mode), the remaining distance is round up to 10 Km, if the remaining distance is greater than 100 Km.

This means that if the remaining distance is 204 Km, in navigation mode it will be displayed 200 Km; after many kilometers then 190 Km, 180, 170, etc.. which I think IMHO that is not best behavior.

**Comment by biodranik** [comment]
Is it broken on all platforms? @AndrewShkrob can you please check it?

**Comment by gpesquero** [comment]
On iOS (tested on the master branch) the distances above 100 Km are also rounded up to 10 Km.
