### ISSUE TITLE
Problem with the editor's handling of facebook URLs

### ISSUE THREAD

**Issue by Zozosticot** [organicmaps/organicmaps#5509]
**Describe the issue**

I don't know why, but facebook data is often duplicated when I edit a trade. I think this is the fourth time I've corrected this one. A Subdomain "people" seems to be responsible.

**Steps to reproduce**

1.  Insert a Facebook profile including "people" (https://facebook.com/people/...) in the editor's Facebook tab
2. Validate changes
3. See error

**Screenshots**

![Screenshot_20230710_172906_Organic Maps](https://github.com/organicmaps/organicmaps/assets/122051830/fbf56d90-9826-4872-8941-6f482dad00b7)
**System information:**

 - Operating system and its version: Android 13, One Ui, F-Droid
 - Organic Maps version: 2023.06.04-13-FDroid
 - Device Model: Samsung A23

**Additional context**

https://www.openstreetmap.org/changeset/138318657

**Comment by biodranik** [comment]
@strump maybe you have some insights?

**Comment by strump** [comment]
I was able to reproduce the issue with next steps:

1. Edit POI
2. Enter facebook link `https://facebook.com/people/Champa-asia/100072627630558`
3. Save edits
4. Close OrganicMaps (this is required!)
5. Enter OrganicMaps and edit POI
**Actual result:** Editor shows `https://facebook.com/https://facebook.com/people/Champa-asia/100072627630558`
