### ISSUE TITLE
Search for addresses with Polish characters

### ISSUE THREAD

**Issue by devhost97** [organicmaps/organicmaps#5517]
**Describe the issue**

When trying to search for an address containing Polish characters, the navigation shows the address of the village without indicating the exact house.

**Steps to reproduce**
1. Go to 'search'
2. Search for adress for example 'Dąbie 14’

**Expected behavior**

Indication of the exact address of the house

**Screenshots**
<img alt="IMG_0297" src="https://github.com/organicmaps/organicmaps/assets/25454629/0a86fbd0-d4a0-4cea-9499-c60d7b82f465" width="300px"/>
<img alt="IMG_0298" src="https://github.com/organicmaps/organicmaps/assets/25454629/fe20d1b2-e56b-49cd-8b11-704e3f58ff00" width="300px"/>
<img alt="IMG_0300" src="https://github.com/organicmaps/organicmaps/assets/25454629/525533ab-f9ce-42c1-a2ee-11ff43c94fd5" width="300px"/>
<img alt="IMG_0303" src="https://github.com/organicmaps/organicmaps/assets/25454629/fcc925aa-c630-4e91-b6cb-dd522c0cab93" width="300px"/>
<img alt="IMG_0302" src="https://github.com/organicmaps/organicmaps/assets/25454629/86aa7b94-69c8-4d7b-b40e-36001ed0d4d0" width="300px"/>

**System information:**
 - Operating system and its version: [iOS 16/iOS17
 - Organic Maps version: ⁦2023.07.09-12⁩
 - Device Model: iPhone 11 | iPhone 12

**Comment by biodranik** [comment]
Interesting, is it because of a non-ascii a letter? @vng https://www.openstreetmap.org/way/500129446

**Comment by devhost97** [comment]
Yes. It’s on Non-ASCII letter.

**Comment by vng** [comment]
https://www.openstreetmap.org/node/2824782078

The same as place + housenumber issues https://github.com/organicmaps/organicmaps/issues/5307
