### ISSUE TITLE
arrow of direction

### ISSUE THREAD

**Issue by abdullahO2** [organicmaps/organicmaps#5518]
There is an arrow at the bottom of the screen that indicates the direction of the target location, but this arrow shows the wrong direction. This experiment was done on multiple Android devices and showed the same problem.

**Expected behavior**
It should show the correct direction of the target location

**Screenshots**
![image](https://github.com/organicmaps/organicmaps/assets/61907628/c8e8a47d-f5d2-4f1c-aae4-cae1ae906a26)
![image](https://github.com/organicmaps/organicmaps/assets/61907628/f269db86-13b7-47f1-8b83-784cb96bf37f)

**System information:**
 - Operating system and its version: [Android 13]
 - Organic Maps version: 2023.06.04-13-Google
 - Device Model: [Samsung Galaxy A52s 5G]

**Comment by biodranik** [comment]
Did you try to calibrate the compass sensor on your device? For example, like it is described here: https://www.youtube.com/watch?v=-Uq7AmSAjt8

**Comment by abdullahO2** [comment]
Thank you, the problem was solved by the mentioned calibration method
