### ISSUE TITLE
App crash in latest version

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#5539]
**Steps to reproduce**
1. Start OM -> buttons is present but world map is not shown
2. App crashed after few seconds

**Screenshots**
<img src="https://github.com/organicmaps/organicmaps/assets/87148630/857924ad-004e-4e07-bac4-e5dbe5916a7d" height=400 />

https://github.com/organicmaps/organicmaps/assets/170263/041da466-07a9-4257-8aa4-c1ae86840b72

**System information:**
 - Operating system and its version: Android 8.1
 - Organic Maps version: 2023.07.13-10-Google
 - Device Model: Nexus 5X

**Comment by Jean-BaptisteC** [comment]
@biodranik can you check ANR on Google Play Console ?

**Comment by biodranik** [comment]
Unfortunately, there are no any crash reports from Android 8.1 yet in the Google Play console. We need crash logs recorded with `adb logcat` tool.

**Comment by cayenne17** [comment]
Hello,
I have a Google Nexus 5x and I have a same problem.
System information:
 - Device Model: Nexus 5X
 - Android Version: 8.1.0
 - Organic Maps version: 2023.07.13-4-FDroid

@Jean-BaptisteC, @biodranik : Here are some logcat logs :

[20230716_110953_organicmaps.log](https://github.com/organicmaps/organicmaps/files/12063628/20230716_110953_organicmaps.log)

**Comment by Komprogue** [comment]
Can confirm. The latest release from f-droid shows empty map and then crashes after few seconds on andoid 8.1. 

![orgmap](https://github.com/organicmaps/organicmaps/assets/84424346/08b25788-a043-468e-aa7c-18935d3fccf1)

**Comment by vng** [comment]
@Komprogue Could you please shared adb logcat?
If not, what is your device model? Nexus 5?

**Comment by Komprogue** [comment]
> @Komprogue Could you please share `adb logcat`? If not, what is your device model? Nexus 5?

Yes, it's the same old Nexus 5X.
 
Unfortunately, now I can't provide logcat.

**Comment by vng** [comment]
@Komprogue @cayenne17 
Could you please test this Beta version? It is installed separately.
https://cdn.organicmaps/www/apk/OrganicMaps-23071310-web-beta.apk

**Comment by cayenne17** [comment]
> @Komprogue @cayenne17 Could you please test this Beta version? It is installed separately. https://cdn.organicmaps/www/apk/OrganicMaps-23071310-web-beta.apk

@vng the link not work.
The domain name **cdn.organicmaps** does not exist

**Comment by vng** [comment]
Updated the link, sorry.

**Comment by cayenne17** [comment]
> @Komprogue @cayenne17 Could you please test this Beta version? It is installed separately. https://cdn.organicmaps.app/apk/OrganicMaps-23071310-web-beta.apk

2023.07.13-10-Web-beta it's work on Nexus 5x. it couldn't crash

**Comment by Komprogue** [comment]
> @Komprogue @cayenne17 Could you please test this Beta version? It is installed separately. https://cdn.organicmaps.app/apk/OrganicMaps-23071310-web-beta.apk

Tested it and this beta vers. works without any problems.

**Comment by vng** [comment]
@cayenne17 @Komprogue Ok, thanks. Now could you please uninstall the current Beta and check this one:

https://cdn.organicmaps.app/apk/OrganicMaps-23071601-web-beta.apk

**Comment by map-per** [comment]
I've got the same Problem. After the update the App worked initially, but when I opend it now the app crashes during the start and I don't see the map screen. 


**System information:**
- Operating system and its version: Android 10
- Organic Maps version: 2023.07.13-10-Google
- Device Model: Pocophone F1

**Comment by vng** [comment]
@map-per Is it possible to get ```adb logcat``` ?
If no adb, could you try fresh install and redownload maps? But previously backup your bookmarks.

If the updated app worked initially, the problem is with something else.

**Comment by map-per** [comment]
> @map-per do you store maps on SD card? If yes, can you please eject the SD card, start OM, and tell us if it works?

Thanks! It worked without the SD card. I now formated the SD card and downlowded the maps again and everything works.
I've had issues with my SD card before so I can't tell whether this was caused by OM or my SD card. 
Unfortunately I didn't capture a log and the problem is gone now.

**Comment by cayenne17** [comment]
> @cayenne17 @Komprogue Ok, thanks. Now could you please uninstall the current Beta and check this one:
> 
> https://cdn.organicmaps.app/apk/OrganicMaps-23071601-web-beta.apk

@vng  :  **2023.07.16-1-Web-beta** also works on Nexus 5x and does not crash.

**Comment by Komprogue** [comment]
> @cayenne17 @Komprogue Ok, thanks. Now could you please uninstall the current Beta and check this one:
> 
> https://cdn.organicmaps.app/apk/OrganicMaps-23071601-web-beta.apk

Sometimes it works, but sometimes there's a stuck on blank\white-brown screen.

**Comment by vng** [comment]
@rokuz "Sometimes it works, but sometimes there's a stuck on blank\white-brown screen."

Thanks! Seems like the best option is to disable Vulkan.

**Comment by cayenne17** [comment]
> > @cayenne17 @KomprogueD'accord merci.  Pouvez-vous maintenant désinstaller la version bêta actuelle et vérifier celle-ci : 
> > [https://cdn.organicmaps.app/apk/OrganicMaps-23071601-web-beta.apk ](https://cdn.organicmaps.app/apk/OrganicMaps-23071601-web-beta.apk)
> 
> Parfois, cela fonctionne, mais parfois il y a un écran vide \ blanc-marron.

@Komprogue, @vng 

indeed, after multiple tests on the **2023.07.16-1-Web-beta** version, I can confirm the same thing

![image](https://github.com/organicmaps/organicmaps/assets/47927025/82c679aa-ae4d-45c2-ad25-be95ca698d00)
![image](https://github.com/organicmaps/organicmaps/assets/47927025/b400e3c1-22da-4dad-adfe-34c2d18547ea)

**Comment by biodranik** [comment]
@cayenne17 can you please enable logs, restart OM, reproduce the blank screen, and send us logs via "Report a bug" with a note when you got the blank screen/crash (on start, after some actions, etc.) for `2023.07.16-1-Web-beta`?

**Comment by biodranik** [comment]
The workaround until a new release is typing `?gl` in the search box and restarting OM.

**Comment by biodranik** [comment]
@rokuz strange, there is nothing suspicious in logs except this:

```
07-18 17:49:15.020 W/Adreno-GSL(15355): <gsl_ldd_control:541>: ioctl fd 48 code 0x400c0907 (IOCTL_KGSL_DEVICE_WAITTIMESTAMP_CTXTID) failed: errno 35 Resource deadlock would occur
07-18 17:49:15.020 W/Adreno-GSL(15355): <log_gpu_snapshot:450>: panel.gpuSnapshotPath is not set.not generating user snapshot
07-18 17:49:16.543 I/zygote64(15355): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
07-18 17:49:16.544 I/zygote64(15355): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
07-18 17:49:16.544 W/Adreno-GSL(15355): <gsl_ldd_control:541>: ioctl fd 48 code 0x400c0907 (IOCTL_KGSL_DEVICE_WAITTIMESTAMP_CTXTID) failed: errno 35 Resource deadlock would occur
07-18 17:49:16.544 W/Adreno-GSL(15355): <log_gpu_snapshot:450>: panel.gpuSnapshotPath is not set.not generating user snapshot
07-18 17:49:16.567 W/Adreno-GSL(15355): <gsl_ldd_control:541>: ioctl fd 48 code 0x400c0907 (IOCTL_KGSL_DEVICE_WAITTIMESTAMP_CTXTID) failed: errno 35 Resource deadlock would occur
07-18 17:49:16.567 W/Adreno-GSL(15355): <log_gpu_snapshot:450>: panel.gpuSnapshotPath is not set.not generating user snapshot
07-18 17:49:16.572 W/Adreno-GSL(15355): <gsl_ldd_control:541>: ioctl fd 48 code 0x400c0907 (IOCTL_KGSL_DEVICE_WAITTIMESTAMP_CTXTID) failed: errno 35 Resource deadlock would occur
07-18 17:49:16.572 W/Adreno-GSL(15355): <log_gpu_snapshot:450>: panel.gpuSnapshotPath is not set.not generating user snapshot
07-18 17:49:16.576 W/Adreno-GSL(15355): <gsl_ldd_control:541>: ioctl fd 48 code 0x400c0907 (IOCTL_KGSL_DEVICE_WAITTIMESTAMP_CTXTID) failed: errno 35 Resource deadlock would occur
07-18 17:49:16.576 W/Adreno-GSL(15355): <log_gpu_snapshot:450>: panel.gpuSnapshotPath is not set.not generating user snapshot
07-18 17:49:16.580 W/Adreno-GSL(15355): <gsl_ldd_control:541>: ioctl fd 48 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
07-18 17:49:16.580 W/Adreno-GSL(15355): <log_gpu_snapshot:450>: panel.gpuSnapshotPath is not set.not generating user snapshot
07-18 17:49:16.584 W/Adreno-GSL(15355): <gsl_ldd_control:541>: ioctl fd 48 code 0x400c0907 (IOCTL_KGSL_DEVICE_WAITTIMESTAMP_CTXTID) failed: errno 35 Resource deadlock would occur
07-18 17:49:16.584 W/Adreno-GSL(15355): <log_gpu_snapshot:450>: panel.gpuSnapshotPath is not set.not generating user snapshot
07-18 17:49:16.591 W/Adreno-GSL(15355): <gsl_ldd_control:541>: ioctl fd 48 code 0x400c0907 (IOCTL_KGSL_DEVICE_WAITTIMESTAMP_CTXTID) failed: errno 35 Resource deadlock would occur
07-18 17:49:16.591 W/Adreno-GSL(15355): <log_gpu_snapshot:450>: panel.gpuSnapshotPath is not set.not generating user snapshot
07-18 17:49:16.595 W/Adreno-GSL(15355): <gsl_ldd_control:541>: ioctl fd 48 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
07-18 17:49:16.595 W/Adreno-GSL(15355): <log_gpu_snapshot:450>: panel.gpuSnapshotPath is not set.not generating user snapshot
```
This may be related: 
https://community.khronos.org/t/adreno-510-gpu-deadlock-would-occur-when-trying-to-use-ubo-in-fragment-shader/106773

**Comment by rokuz** [comment]
I don’t wonder, it can be so in case of driver issue. Link is related to OpenGL, not Vulkan btw.
