### ISSUE TITLE
Mention username under "OSM profile" in settings

### ISSUE THREAD

**Issue by 501Ghost** [organicmaps/organicmaps#5549]
As a minor QoL feature I would like to see the text "Logged in as [Username]" directly below "OpenStreetMap profile" in the settings, as information of which account is currently logged in. It can be in the same font size as the text "Choose between miles and kilometers" and the other settings explanations.

**Comment by devj22** [comment]
I want to contribute
please assign.

**Comment by Jean-BaptisteC** [comment]
Don't ask to work on issue, feel free PR if you want
We don't want you ask to work on issue to limit spam each time people want work on issue :)

**Comment by itfarrier** [comment]
@biodranik, I think this issue should be closed. Am I right?

![profile](https://github.com/organicmaps/organicmaps/assets/4352168/d695be18-0013-4da8-9ca3-06eb2c9af858)

**Comment by biodranik** [comment]
Right! Any Android volunteers to implement it?
