### ISSUE TITLE
Show/ Appear Organic Maps in Share Section

### ISSUE THREAD

**Issue by ghost** [organicmaps/organicmaps#555]
Show/ Appear Organic Maps in Share Section. Its helps to share maps links to open in organic maps.

**Comment by Github-com-foss** [comment]
![android-share-menu](https://user-images.githubusercontent.com/75672019/121641520-00807800-cadb-11eb-94f6-a7c9af2e1c26.png)

**Comment by biodranik** [comment]
Please clarify which exactly map link you're trying to open via sharing. OM won't open "just any link".

**Comment by rtsisyk** [comment]
@ghost please elaborate

**Comment by rtsisyk** [comment]
This is the same issue as #475.

**Comment by biodranik** [comment]
@rtsisyk does it work now like here on the screenshot, for OSM, 2GIS, and Google links?
