### ISSUE TITLE
Wayland Fractional Scaling Broken with qt6 updae

### ISSUE THREAD

**Issue by user82622** [organicmaps/organicmaps#5555]
**Describe the issue**
When using fractional scaling in Wayland session map itself and some window elements are blurry or have rendering artifacts. 

**Steps to reproduce**
1. Gnome 43 Wayland Sesion
2. Open Organic Maps
3. You see blurry map
4. Open prefrences
5. You see window rendering broken with artifacts

**Expected behavior**
Like with qt5 have sharp rendering of map

**Screenshots**
![image](https://github.com/organicmaps/organicmaps/assets/88026138/a71f47fa-0297-4ab5-97eb-afec76c3f042)

**System information:**
 - Operating system and its version: [Fedora 37, Gnome 43, Linux Deskop]
 - Organic Maps version: [Version: 2023.07.13-1-b52b42bd-dirty-Linux]

**Comment by RedAuburn** [comment]
also see https://github.com/organicmaps/organicmaps/issues/4836.

>it seems that devicePixelRatio() doesn't actually return the fractional scale value. (it returns 2 for me)
https://github.com/organicmaps/organicmaps/blob/73b898476c467d31fdc7215a2874ff89a4d13b28/qt/qt_common/map_widget.cpp#L346
setting it to 1.25f, (my screen is at 125%) i get correct scaling & window size. Unfortunately, QT doesn't seem to provide a way to access the actual scaling value...

_Originally posted by @RedAuburn in https://github.com/organicmaps/organicmaps/issues/4836#issuecomment-1619287130_

**Comment by bam80** [comment]
Could you try recent KDE session?

**Comment by user82622** [comment]
Nope not easily, would have to setup VM. Can do it maybe next week, 
currently have really poor internet connection, would take me days to 
download an image to do so. My system also has no Distrobox to try it 
in a container.

**Comment by bam80** [comment]
Worth trying, I know the fractional scaling was fixed recently in KWin. Don't know the details though, maybe it's still a problem in Qt

**Comment by RedAuburn** [comment]
I'll give it a try 👍

**Comment by bam80** [comment]
The "problem" seems to be Qt6 now supports new fractional scaling protocol on Wayland, which should make things even better considering compositor supports it.
I see an evidence Gnome (Mutter) doesn't support this and it's not clear when it happens:
https://www.reddit.com/r/kde/comments/z7iwpm/comment/iy7zmdx/?utm_source=share&utm_medium=web2x&context=3
So maybe without that support from compositor, we have such side-effect or "regression".
I don't have more detail ATM, but will try to attract more comments on the matter.

Refs:
https://pointieststick.com/2022/12/16/this-week-in-kde-wayland-fractional-scaling-oh-and-we-also-fixed-multi-screen/
https://www.phoronix.com/news/KDE-Lands-Wayland-Frac-Scaling
https://www.youtube.com/watch?v=87W6iIEicoM

**Comment by bam80** [comment]
And while we are waiting for a more info, it probably worth to file an issue to Qt itself, because at the first glance all is good from the app side.
Please also put the cross reference here.

**Comment by Ferenc-** [comment]
Fedora 37 was 4 releases ago, and is End Of Life by now so no support, plus this newer was really reproducible.
