### ISSUE TITLE
Can not find addr:place in search and no addr:place in object card

### ISSUE THREAD

**Issue by kuyantus** [organicmaps/organicmaps#557]
Hi, guys!

It seems that app can not recognize addr:place search and in object card. For example: https://www.openstreetmap.org/way/694329109 we can see addr:place in object card and search on site is working too.

But if we search or click on building in the app (both android and ios), addr:place tag is missing:
![photo_2021-06-11_23-51-06](https://user-images.githubusercontent.com/15859870/121747330-edd46600-cb0f-11eb-8c54-dab2e67416bc.jpg)
![photo_2021-06-11_23-51-11](https://user-images.githubusercontent.com/15859870/121747339-f0cf5680-cb0f-11eb-8f6d-de370785f31d.jpg)

According to osm wiki, this is valid [tag ](https://wiki.openstreetmap.org/wiki/Key:addr:place) and it would be great if app could show it in card object if building has no street name and it can be find in search. Thanks a lot!

**Comment by vng** [comment]
I have several thoughts on this issue:
- we should show addr:place or landuse=allotments (probably other place-like "places") in place page view
- we should match addr:place? or other area place-like objects in search (if still not)
- match places hierarchy in search (if still not)

**Comment by andrewshadura** [comment]
Another example: [Panické Dravce 124](https://www.openstreetmap.org/way/62130378#map=18/48.28669/19.65294).

**Comment by andrewshadura** [comment]
Another thing: some buildings (at least in small villages in Slovakia) are commonly addressed both ways, by `<Village> <conscription number>` and `<Street> <street number>, <Village>`. This happens when houses only have conscription numbers (a unique number within the village) but no street numbers, but sometimes it also happens when houses have both.

For example, [Hviezdoslavova 314/35, Nižná](https://www.openstreetmap.org/way/330130280#map=17/49.31133/19.52012) can also be addressed as:
* Hviezdoslavava 35, Nižná
* Nižná 314
but never Nižná 35.

**Comment by Zorroz-lab** [comment]
Так же не работает поиск по кварталам и микрорайонам и номер дома.
Например адрес 19 квартал, дом 2 (52.556187, 103.880051) не выдается в списке  при вводе в поисковой строке хоть "19 2", хоть "19 квартал, дом 2". Хотя в тегах стоит: adrr:place 19-й квартал, adrr:housenumber 2

**Comment by biodranik** [comment]
Another example https://www.openstreetmap.org/way/172825165

**Comment by vng** [comment]
https://github.com/organicmaps/organicmaps/issues/5075

**Comment by duiveldoder** [comment]
At this point I'd like to remind the devs - this critical tagging is still lacking support in Organic maps!

any dev here, please see here: https://wiki.openstreetmap.org/wiki/Key:addr:place

time to support it so at 

https://wiki.openstreetmap.org/wiki/Key:addr:place#Software_support

We can mark it "YES" and green :)

Thank you

**Comment by vigeron** [comment]
OK

![Test1](https://github.com/organicmaps/organicmaps/assets/16254462/d79f3853-e4a7-4edb-bccf-eecfcb9eef63)

Not OK
![Test2](https://github.com/organicmaps/organicmaps/assets/16254462/a4a75011-db9b-48c8-a8f7-9f6fe47fa7cf)

Again OK
![Test3](https://github.com/organicmaps/organicmaps/assets/16254462/d16935eb-e6ec-44e0-9129-9033c9de7264)

Here is something strange, Domaradz is a village, but the results list shows as if it were a street, assigned to the surrounding villages. The correct result is in the 5th position. The others are incorrect.
![Test4](https://github.com/organicmaps/organicmaps/assets/16254462/4af9fb12-b4fd-486e-80b4-823ddcaae954)

**Comment by vng** [comment]
- "Domaraz, 5" actually is not a matching bug, all addresses exist, but we also write _nearby_ village even if addr:place was matched. Should remove it.
- "Falkowice 4, Opole" is a ranking bug. Opole -> Opolska _prefix_ matching street. Should fix it.
Now you can simply add space to the end to avoid _prefix_ match.

"Hviezdoslavova 314" works fine for me.

**Comment by vng** [comment]
BTW, it's either a mapping bug or very fancy numeration, all "Domaradz 5" addresses are valid:
```
https://www.openstreetmap.org/way/427939538
https://www.openstreetmap.org/way/427936280
https://www.openstreetmap.org/way/427939541
```
I put the first 3 of them, all have the same address tags, and all are around Domaradz village, but obviously are different buildings. And there are more than 3 of them there :)

**Comment by vigeron** [comment]
You're right, Kozuby, Żabiniec, Paryż are part of Domaradz, but they are completely separate villages and they shouldn't be here. This screenshot shows correctly. 
![Domaradz](https://github.com/organicmaps/organicmaps/assets/16254462/4bd6a941-602c-477e-871e-cfb252da3e5b)

Spacebar works :)

I downloaded all of Slovakia for testing.
Hviezdoslavova 124 - ok
Hviezdoslavova 314/34 - wrong, but here is ok  https://nominatim.openstreetmap.org/ui/search.html?q=Hviezdoslavova+314%2F35&accept-language=en

**Comment by biodranik** [comment]
> This screenshot shows correctly.
@vigeron are these results the same as Viktor listed? If they belong to different villages, `addr:place` tag should NOT have Domaradz, but have the name of another village. It looks like an OSM map data bug. Are you local/familiar with OSM? What is the real situation there?

https://www.openstreetmap.org/way/427939538
https://www.openstreetmap.org/way/427936280
https://www.openstreetmap.org/way/427939541

**Comment by andrewshadura** [comment]
>  Hviezdoslavova 314/34 - wrong

It’s actually sort of okay. Consider this: 314 may be a building with several entrances. Only a few of them are mapped, and the one you’re looking for isn’t. You enter the full address, but instead of your exact address, it gives you the same building but a different door. Is it perfect? No. Is it better than nothing? Definitely.

**Comment by biodranik** [comment]
@andrewshadura if the precise address exists, then it should be found. It's a bug: https://www.openstreetmap.org/way/330130280

**Comment by vigeron** [comment]
@biodranik As for these villages, you are right, OSM indicates the wrong places. I will send an update request to OSM. Thanks :-)

**Comment by andrewshadura** [comment]
@vigeron, for https://www.openstreetmap.org/way/330130280 commonly accepted addresses are Nižná 314, Hviezdoslavova 35, but Hviezdoslavova 314 also (rarely) used. I was however talking about cases like https://www.openstreetmap.org/way/156061645 where the conscription number is the same for all entrances whereas street number varies.

**Comment by biodranik** [comment]
Can this issue be closed now?

**Comment by vng** [comment]
The issue still has examples of bad matching. Mostly OSM tagging issues, but anyway.

**Comment by biodranik** [comment]
Let's close this issue and create a new one with examples of bad matching which are NOT OSM tagging issues. And report/fix all OSM tagging issues upstream.
