### ISSUE TITLE
Add museum category 

### ISSUE THREAD

**Issue by elesto** [organicmaps/organicmaps#5577]
I would like the ability to filter by museum category. That is select the catory and have all museums near me highlighted on the map view

**Comment by biodranik** [comment]
Type "museum" (or string in your language) to see museums on the map. Organic Maps searches for any object types (categories), not only for "Categories" that are visually displayed in the search dialog. You may check them in data/categories.txt

**Comment by elesto** [comment]
ah that works now. can i add that museum category

**Comment by biodranik** [comment]
Add where? Into the visible UI list in the Search dialog? That can't be customized by users now. But you can always type museum in the search.

Btw, are museums highlighted when you search for the sightseeing category?

**Comment by elesto** [comment]
> Btw, are museums highlighted when you search for the sightseeing category?
Yes they are but also many many other things are highlighted
