### ISSUE TITLE
MAP ON LOCK SCREEN

### ISSUE THREAD

**Issue by G-i-o** [organicmaps/organicmaps#558]
When the Lock Screen is activated, it's not currently possible to see the map. So, the screen needs unlocking each time.

OpenTracks (https://github.com/OpenTracksApp/OpenTracks), for instance, has the option to see the data on the Lock Screen. This would be extremely useful.

**Comment by rtsisyk** [comment]
We will check how OpenTracks works.

**Comment by G-i-o** [comment]
👍️ Magic. Many thanks.

**Comment by jpovixwm** [comment]
App pinning could potentially be used as a workaround. This way, whenever you turn on your screen, you'll get back to Organic Maps without the need to enter your pin/password.

**Comment by G-i-o** [comment]
@jpovixwm

Freaking me! Thank You so much. I've never
realised screen pinning works that way.

This is so useful, with Organic Maps as well as
with a handful of other apps.

Much appreciated for the hint. 🙏️

**Comment by biodranik** [comment]
See also #1578
