### ISSUE TITLE
"Stacked" Bookmarks disagree in shown icon and opened bookmark

### ISSUE THREAD

**Issue by palzkillm** [organicmaps/organicmaps#5582]
**Describe the issue**
When several bookmarks are "stacked", meaning they have the exact same coordinates, the icon shown, and the result of tapping this icon, is not the same, in effect, you tap on the icon, but a different bookmark opens.

**Steps to reproduce**
1. Add a bookmark with a some coordinates, assign it a yellow icon, name it "1"
2. Add a bookmark with the exact same coordinates as the one before, assign it a grey icon, name it "4"
3. Look at the map - yellow icon is displayed
4. Tap on yellow icon
5. EXPECTED: Bookmark 1 opens
6. ACTUAL: Bookmark 4 opens

**Expected behavior**
On tap of an icon displayed, the according bookmark is opened - not another one.

**Screenshots**
![image1](https://github.com/organicmaps/organicmaps/assets/107746723/fe7c13bd-e616-4b12-a24a-1b5034aeec08)
![image0](https://github.com/organicmaps/organicmaps/assets/107746723/855c15ab-b111-4990-8c71-b0ded7852c55)

**System information:**
iOS 16.5.1c
OM 2023-07-15

**Comment by biodranik** [comment]
What is your use case for several bookmarks in the exactly same place? Are their descriptions and other parameters different? How are you creating them?

Also see https://github.com/organicmaps/organicmaps/issues/5275

**Comment by palzkillm** [comment]
Duplicate #5275
