### ISSUE TITLE
Tapping on empty area of map to show/hide menu sometimes cumbersome

### ISSUE THREAD

**Issue by palzkillm** [organicmaps/organicmaps#5583]
**Is your feature request related to a problem? Please describe.**
Tapping on an empty area of the map (which means: no tappable items on there, just plain surface) shows and hides the bottom menu and the zoom buttons on the right side. This normally works quite well for me.
In some situations, especially when it's hot, I run into the situation, that tapping on a seemingly empty area of the map in order to show/hide the menu, instead, an item on the map is activated. Then I tap on another area, and another item is activated. And again, and again. 
I don't actually think there is a bug in the application, I guess it's really just bad tapping on my end - however, in that situation, it frustrates me quite a lot.

**Describe the solution you would like**
I'd love an actual button to show/hide the menu.

**Comment by biodranik** [comment]
Interesting, why do you need to show/hide the interface so often, that it requires a separate dedicated button?

**Comment by pastk** [comment]
In my experience its also frustrating to try hide/show the UI when there are a lot of POIs around (which is usual in cities).
It might be better to have a small corner "pull" button.
It'll make the show/hide function easily discoverable by users also.

Another (raw) idea is to use long tap for show/hide (but not discoverable again) and a short tap to select any point on the map https://github.com/organicmaps/organicmaps/issues/1894.

Related: #5199

**Comment by palzkillm** [comment]
> Interesting, why do you need to show/hide the interface so often, that it requires a separate dedicated button?

I dont NEED to show/hide it so often - I usually run into the problem that somehow I managed to hide the menu bar (and with it, the zoom buttons), and then can not find an area on the screen that is empty enough to show them again without having to use a second hand to be abled to use pinch-zoom.

**Comment by biodranik** [comment]
Then the obvious solution is to change the default behavior: do not hide the interface on a single tap on an empty place. But it requires careful planning: what should happen instead? And should there be another way to hide the interface? Which one?

**Comment by pastk** [comment]
I think after #7876  its no longer an issue
