### ISSUE TITLE
Wrong instructions in RTL

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#5585]
Bug reported from matrix

With OM in RTL, instructions tell to turn left when we need to turn to right

**Expected behavior**
When app is in RTL, arrows instructions is properly reverse

**Screenshots**
<img src="https://github.com/organicmaps/organicmaps/assets/87148630/4b310182-8c5c-4ed6-b14a-27984840afd1" height=400 />

**System information:**
 - Operating system and its version: IOS
 - Organic Maps version: -
 - Device Model: -

**Comment by biodranik** [comment]
Does it work on Android? Where is this place on the screenshot?

**Comment by Jean-BaptisteC** [comment]
I'm not able to reproduce on Android
Location= https://www.openstreetmap.org/#map=15/25.0706/51.5649

**Comment by biodranik** [comment]
Why do you think that it is an error?
![image](https://github.com/organicmaps/organicmaps/assets/170263/ab87ca18-949b-4f0c-b8f7-9dea95191226)

**Comment by Jean-BaptisteC** [comment]
Yes, you right, OM just tell to keep in left. Instructions is correct
I close issue
