### ISSUE TITLE
Change icon name from "Organic Maps" to "Maps"

### ISSUE THREAD

**Issue by TheEvilSkeleton** [organicmaps/organicmaps#559]
IMO it looks better to have the name "Maps" since it's a lot shorter and it will be available in the M category in the app menu.

The name of the app itself can stay Organic Maps. My request is to only change the icon name to Maps, if possible. I'm pretty sure Google does that with their apps.

**Comment by rtsisyk** [comment]
I remember that Google, Yandex and other vendors used the short name "Maps" on Android. It was so confusing.

**Comment by biodranik** [comment]
Agree about the confusion. Can you please provide more specific details, which problem you're trying to solve? Maybe provide a screenshot?

**Comment by TheEvilSkeleton** [comment]
It's not a problem, but more of an annoyance. I find it better to name the icon with a generic name than name the icon the same as the app since everyone does it that way.

For example, on Linux (specifically GNOME desktops), the file manager's name is Nautilus, but in the app menu, it shows as Files:

https://gitlab.gnome.org/GNOME/nautilus/#nautilus

![image](https://user-images.githubusercontent.com/50847364/121809247-194b7380-cc2a-11eb-90d4-35689ccf9870.png)

It's more consistent and the names are smaller too, so they look prettier. Google does it, Microsoft does it, Apple does it to some extent, GNOME does it, etc.

**Comment by biodranik** [comment]
From our experience with other apps, the current naming which includes both a generic name and a unique name is the best approach. It works well for the search and visually looks better, so in general, it's more user-friendly. In any case, thanks for the feedback!
