### ISSUE TITLE
GPX import - 0 files imported

### ISSUE THREAD

**Issue by yagueto** [organicmaps/organicmaps#5590]
**Describe the issue**
I have been trying to import a GPX from the Geocaching website (cannot upload the file here due to copyright); however, when I select the folder it's on it says 0 files imported

**Steps to reproduce**
1. Go to the "star" (bookmarks) button
2. Click on "import bookmarks"
3. Select the folder the files are at

```Note: I have read other issues regarding permission issues with new android versions. I have moved the files all over my phone to check this is not the issue (Downloads, folder inside Downloads, folder at the root of the sdcard, without any difference)```

5. See the message

**Expected behavior**
It should import it :upside_down_face: 

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**System information:**
 - Operating system and its version:  Android 13
 - Organic Maps version: 2023.05.08-7-FDroid
 - Device Model: Samsung A33

**Additional context**
I have checked that the files are not corrupted, and I have been able to open them in other online websites

**Comment by biodranik** [comment]
Well, you are using an old Organic Maps version that does not support GPX import )

**Comment by yagueto** [comment]
Oh, woops, got misled by the import button hehe

Closing, thanks
