### ISSUE TITLE
Some icons in wiki are outdated

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#5591]
Some icons have been added and some removed in the app that should be updated on the wiki: https://github.com/organicmaps/organicmaps/wiki/Icons. I have modified this wiki before but it seems that I no longer have permission to edit. If you could give me permission I could update it.

**Comment by biodranik** [comment]
Strange, we did not change permissions. Can you edit labels on this issue? Can you edit other's issues?

**Comment by dvdmrtnz** [comment]
> Strange, we did not change permissions. Can you edit labels on this issue? Can you edit other's issues?

I can edit labels on this issue but I cannot edit other's issues.

**Comment by biodranik** [comment]
Try now?

**Comment by dvdmrtnz** [comment]
> Try now?

Now it works. Thanks!

**Comment by dvdmrtnz** [comment]
Done. Wiki updated!
