### ISSUE TITLE
[android] Use a FAB for feedback in the FAQ

### ISSUE THREAD

**Issue by meenbeese** [organicmaps/organicmaps#5594]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you would like**
A bottom bar in the FAQ page with only a `Feedback` option looks weird and out of place. A standard or maybe even extended FAB would look much better and would be easier to grasp/use.

**Describe alternatives you have considered**
None.

**Additional context**
FAB Documentations: 
https://m3.material.io/components/floating-action-button/overview 

https://m3.material.io/components/extended-fab/overview

![image](https://github.com/organicmaps/organicmaps/assets/114044633/199f0768-ff04-4fd9-bfe9-f76a06530a94)

**Comment by Jean-BaptisteC** [comment]
This change can be implemented during about fragment refactoring in kotlin + compose
CC @arnaudvergnet

**Comment by arnaudvergnet** [comment]
Yes if we make the switch to compose we can wait for such design changes
