### ISSUE TITLE
[android] want to use import as route, in addition to using it as track

### ISSUE THREAD

**Issue by sodinoel** [organicmaps/organicmaps#5595]
As a long-distance biker, I prefer Bikerouter.de (BR) to plan my tours of several hundred kilometers on a PC.
I would like to use the kml/gpx export function of the Web Platform BR, in combination with the navigation function of OM. 
On Android OM offers the possibility to import gpx as **track**. 
It would be a great option to use the import optionally as a **route**.

Pls see loading menu of BR as an example

![Screenshot_20230724-103653](https://github.com/organicmaps/organicmaps/assets/13116395/f2b11b16-2b6b-4c03-8973-141f3b73209e)

**Comment by sodinoel** [comment]
The GPX file does not differ. But if you load the GPX data as **route**, OM interprets it as a calculated route and you can use the "start" button to begin the with the navigation.

**Comment by cyber-toad** [comment]
> @cyber-toad can you please check out what's the difference in this route format with our supported track format?

@biodranik if I am not wrong @sodinoel requests navigation for imported track - so it is a duplicate of [#2384](https://github.com/organicmaps/organicmaps/issues/2384)

**Comment by sodinoel** [comment]
Yes, thats exactly what I mean:

1. planning a route with bikerouter.de
2. exporting it as .gpx or .kml
3. importing it into OM
4. not calculating the imported route with OM, only using it as foreign calculated route
5. want to use OM for navigation on bike

bikerouter.de is an excellent planning tool, but not for navigation
OM is an excellent navigation tool, but not for planning

**Comment by sodinoel** [comment]
Because is dublicate, I close

**Comment by biodranik** [comment]
> OM is an excellent navigation tool, but not for planning

@sodinoel what is missing in OM to make it an excellent planning tool too?

**Comment by sodinoel** [comment]
@biodranik 
For 90% of users or for spontaneous planning of a bike route, OM is perfectly adequate. However, my use case is the planning of long distances with several hundred kilometers distance. If you have some time then try once bikerouter.de then you quickly realize what the difference is.
I just want to take an imported .gpx file as a basis for navigation. Komot can do that, now I discovered Guru Maps, that can do that too. Unfortunately, OM can not (yet).

**Comment by biodranik** [comment]
What is the difference in importing track as a route vs as a track?

**Comment by sodinoel** [comment]
I apologize if I have not made myself clear. 
A track is a saved (recorded) route that is displayed (documented) on the map. A route is a collection of waypoints that you move along in sequence during navigation. During the calculation of the route this movement is simulated and for example the total distance and the elevation profile is calculated.

**Comment by 0709wiwiwi** [comment]
> What is the difference in importing **track as a route vs as a track**?

BRouter (bikerouter) web technically expresses the function somewhat "unhappily".
It's track in and then track out and (if set) inclusive the turn instructions.
The export does not contain a gpx (rte) route but an "enriched" gpx (trk) track.

Brouter web.
**Import as track.** Displays the track as a reference to design a new track.
**Import as route.** Uses the track as an attempt to calculate a new track.

There are 3 export modes that attach the calculated TBT instructions. 

- As gpx track with instructions in associated waypoints. (Locus).
- As gpx track with instructions in trackpoints. (Locus and Cruiser).
- As geojson track inclusive the turn instructions. (Cruiser). 

The RouteYou web (osrm) router offers the same functionality.
- At export choose as Locus gpx track. (Instructions in trackponts).

You can thus follow the track using the turn instructions.
This also works without the need for any routable map.

**Comment by biodranik** [comment]
@0709wiwiwi @sodinoel can you please provide some examples to compare tracks and routes with waypoints for voice instructions from different applications? The reason I'm asking is that we're implementing a track recorder #2147 and plan to implement saving routes built in OM #1785  , and it would be great to understand/compare existing implementations first.

CC @cyber-toad

**Comment by 0709wiwiwi** [comment]
More info.
https://github.com/devemux86/cruiser/discussions/250

Example files in zip. 
A gpx track vs gpx navtrack (enriched with instructions).
[Compare.zip](https://github.com/organicmaps/organicmaps/files/15429792/Compare.zip)

**Comment by 0709wiwiwi** [comment]
This next issue offers a chance to show a small example.
https://github.com/organicmaps/organicmaps/issues/8359
Without turnlist control, you just notice this @ navigation.
The turnlists of the demo osm routers show it correctly.
The simple gpx navtrack contains the correct instructions.
The navigation track composition can be found in the pdf.
[No u-turn_right_right.pdf](https://github.com/user-attachments/files/15530415/No.u-turn_right_right.pdf)
The gpx navigation track in attachment. Remove .txt
[no u-turn_navtrk.gpx.txt](https://github.com/user-attachments/files/15530428/no.u-turn_navtrk.gpx.txt)
Import as gpx navigation in Cruiser or Locus and navigate.
[Navigation Simulation Result](https://youtube.com/shorts/JpMYfE2hkmg)
