### ISSUE TITLE
After update to Android 13: "Organic Maps isn't responding" constantly

### ISSUE THREAD

**Issue by devurandom** [organicmaps/organicmaps#5596]
**Describe the issue**

I updated my Fairphone FP3 to Android 13. Since then, after opening Organic Maps 2023.07.13-10-FDroid, Android constantly (every <5s) opens a dialogue "Organic Maps isn't responding: :x: Close app :clock5: Wait". This makes Organic Maps unusable.

**Steps to reproduce**
1. Open Organic Maps
2. See Android dialogue

**Expected behavior**

I would expect Organic Maps to be responsive and Android seeing no reason to show me the "isn't responding" dialogue.

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.07.13-10-FDroid
 - Device Model: Fairphone FP3

**Comment by biodranik** [comment]
Do you use SD-card? Do you store downloaded maps on SD-card? If yes, then your SD-card is very slow. Choose Internal storage in OM settings to confirm that. And then you can buy a faster SD-card (we recommend V30+).

**Comment by devurandom** [comment]
Yes, I moved the data to the SD card a while ago. (Before the update to Android 13.) The card I use is a SanDisk Extreme 64GB SDXC UHS-I V30 U3 A1. So it should be fast enough, right?

Also notable is that the Android popup that the app is not responding opens constantly, even when I do not interact with the app for many seconds and the section of the map shown on the screen does not change. In that case Organic Maps should not load any data from the SD card anymore, right?

**Comment by biodranik** [comment]
Interesting, can you please enable logs in OM settings, restart OM, reproduce wait dialogs, and then send us logs via Report a bug?

**Comment by devurandom** [comment]
Sent, with a link to this issue in the message body.

**Comment by biodranik** [comment]
Thanks, we'll check it. So far you can move maps (or delete and redownload them) to the internal storage, it should fix your issue.

**Comment by cintek** [comment]
I also experienced this issue but only when the phone is in energy-saving mode. I just sent you an email with some logs.

**Comment by devurandom** [comment]
Regardless of the "application is unresponsive" dialogue, OM appears to fully work. If I manage to dodge that dialogue, I can start navigation and OM will without failure announce every turn via voice output, all the while showing the "unresponsive" dialogue on top.

**Comment by biodranik** [comment]
@cintek interesting, what is your Android version and device model? What was that energy setting that you changed?

Can anyone else check the sane issue on a fast SD card with energy saving disabled?

**Comment by cintek** [comment]
> @cintek interesting, what is your Android version and device model?
@biodranik I'm using LineageOS 20 which is equivalent to Android 13 on a Samsung Galaxy S8.

> What was that energy setting that you changed?
It's just the default battery saver of Android. I don't know what is does exactly but the description tells something about turning off background activity and visual effects.

**Comment by cintek** [comment]
It's totally strange and I'm not sure now if the problem is really coming from Organic Maps. I just started Organic Maps and had the same message. Then I wanted to record this behavior and the message didn't appear. Even after I closed and started Organic Maps multiple times. I restarted the phone, opened Organic Maps and the message did come back.

After all I tried again to record the problem and the I got the same message but for the recording app "Record You" (from F-Droid-Store). This would be an indication that the problem is caused by Android itself and not Organic Maps.

**Comment by biodranik** [comment]
The problem likely comes from the SD card or its controller which "hang" when reading or writing data to the SD card.

There is a small chance that the main app thread causes it implicitly somewhere, but it's not easy to find.

**Comment by biodranik** [comment]
Thanks for your logs! Looks like the issue is caused by the enormously slow enumeration of all downloaded maps on the main thread (Android shows Wait/ANR dialog after 5 seconds of blocking the main thread):
```
07-26 15:45:45.489 (main) I/OMcore: storage/storage.cpp:959 RegisterLocalFile(): Found file: Andorra in directory: /storage/4A21-0000/Android/data/app.organicmaps/files/230710 with size: 3761777

...

07-26 15:46:05.093 (main) I/OMcore: map/framework.cpp:147 RegisterMap(): Loaded Zimbabwe map, of version 230710
```

We need to check why is it done on the main app's thread.

**Comment by dr4Ke** [comment]
I have the same issue. But also the same phone as @devurandom with a SanDisk Extreme 64GB SDXC UHS-I V30 U3 A2 card.
On a computer, I can read it at 18MB/s, which is much slower than it should but it may be because of hardware limitation on the reader.
With the application SD Card Test, I have these results: 56MB/s on write, 83MB/s on read which is reassuring.

On the issue: it disappears sometimes. Maybe when it has finally checked all downloaded maps?

However, I can reproduce a delay to access the files in the sdcard with other applications. For example with the file manager, which stalls during a few seconds before opening any directory, and a call recorder.

**Comment by biodranik** [comment]
It means there is a slow directory listing, not only in Organic Maps. How fast will the directory with downloaded maps open?

**Comment by dr4Ke** [comment]
Well, every directories had mostly the same delay, of 2-3 seconds.

After many trials and error, with this sdcard and another, I have circumvented the issue to the exFAT filesystem type. When formatted in FAT32 (a shame) the issue disappears… I think I will stop trying here.

**Comment by biodranik** [comment]
We definitely need to fix it somehow, there are plenty of "slow" fast sd cards in the wild...

**Comment by biodranik** [comment]
@devurandom am I correctly understood that you didn't have that issue with the same SD card, on the same device, with the same number of downloaded maps, with an older Android version?

It would be great to confirm whether it is related to the Android 13 upgrade. Maybe there is a bug in how Google accesses SD card files.

Does anyone see this issue on older Android versions?

**Comment by dr4Ke** [comment]
I can confirm that exactly the same setup : phone, sdcard, maps was working seamlessly with android 11 and is now mostly unusable.

**Comment by devurandom** [comment]
> @devurandom am I correctly understood that you didn't have that issue with the same SD card, on the same device, with the same number of downloaded maps, with an older Android version?

Correct. Same SD card, same filesystem on it, exact same downloaded maps (I did not upgrade OM or its maps in between), same phone. Only difference: Before it ran Android 11, now it runs Android 13.

**Comment by biodranik** [comment]
@devurandom @cintek @dr4Ke can you please try to install this separate beta version and tell if it works well with many downloaded maps?
https://cdn.organicmaps.app/apk/OrganicMaps-23082621-fdroid-beta.apk

**Comment by dr4Ke** [comment]
It seems to be ok here. Same maps loaded, no more error messages.
I'll use it more tomorrow and report back.

**Comment by biodranik** [comment]
Thanks! Please make sure that you downloaded as many maps as possible. 

It would be great to also enable logs in OM settings, restart OM, use it, and then send us a log after 30 seconds via Report a bug with a comment "SD issue fix".

**Comment by cintek** [comment]
The beta version works fine. I tried it without energy saving mode and with it. Also downloaded more maps than I had in the normal version of Organic Maps. I just sent you an email with the log files.

Thanks for fixing this problem!!

**Comment by dr4Ke** [comment]
I can confirm that I have no more stale message with this version. Thank you for working on this.

**Comment by devurandom** [comment]
> can you please try to install this separate beta version and tell if it works well with many downloaded maps? https://cdn.organicmaps.app/apk/OrganicMaps-23082621-fdroid-beta.apk

I installed the APK, but noticed that it would not be able to use the already downloaded maps. Since my storage was almost full I could download the maps again. I am glad to hear that others found the APK to fix the problem. I will try the next released version of Organic Maps and will open a new issue should I still run into problems.

**Comment by biodranik** [comment]
What do you mean "it would not be able to use already downloaded maps"? What exactly happened?

**Comment by devurandom** [comment]
> What do you mean "it would not be able to use already downloaded maps"? What exactly happened?

I assume nothing unexpected to an application  developer familiar with the Android API: I have several GB of maps downloaded for the "normal" version of Organic Maps, but the testing APK I installed wanted to download the world map again, not detecting the already existing maps from the other APK. I assume that on Android one application cannot access another application's data files, even if they are stored on the SD Card or in the "internal *shared* storage"?

**Comment by biodranik** [comment]
@devurandom So your issue was that one app could not reuse maps from the other app, right? That's by design due to Android 11 scoped storage restrictions and our decision to avoid requesting privacy-unfriendly external storage permission.

Maps in OM are not shared between apps. They are stored either in the app's external storage or in the app's internal storage.

**Comment by biodranik** [comment]
It should be fixed in the next update. Please let us know if it reappears.

**Comment by devurandom** [comment]
I confirm that this is fixed in 2023.09.22-27-fdroid. Thanks a lot!

**Comment by devurandom** [comment]
The issue appears again with OM 2024.06.19-3-FDroid (maybe already in earlier versions).

**Comment by biodranik** [comment]
@devurandom we did not touch that code. Has anything changed in your system?

Do you store maps on SD? If yes, do you see the same issue if maps are stored on the internal storage? Do you see the same issue with a different SD card?

**Comment by devurandom** [comment]
> Has anything changed in your system?

Not that I know of.

> Do you store maps on SD?

Yes.

> If yes, do you see the same issue if maps are stored on the internal storage?

I do not have enough space in internal storage to move all maps. :(

> Do you see the same issue with a different SD card?

I do not have another "high speed" SD card. :(

---

I sent debug logs, maybe they help.

---

After reading https://github.com/organicmaps/organicmaps/issues/7828 I switched to a different app, leaving OM running in the background. updating maps. I kept getting the "isn't responding" messages for several (~5?) minutes, tapping "wait" every time they showed up, and then I mistapped into the empty space around the message, and from then on I no longer got any messages. When I switched back to OM, it was almost done updating maps (2-3 countries and ~300MB to go). Since then I have not seen another "isn't responding" message.

**Comment by devurandom** [comment]
Maybe relevant in this context: https://github.com/osmandapp/OsmAnd/issues/13943#issuecomment-2198758989

**Comment by devurandom** [comment]
The issue keeps happening after every update of the app.  I am now on 2025.02.17-3-FDroid and downloading updates of my maps, and I constantly get the "Organic Maps isn't responding" popup. Even when downloads have already aborted since many minutes, because "check your internet connection" or "check your storage space", the popups keep coming.

The "trick" from https://github.com/organicmaps/organicmaps/issues/5596#issuecomment-2198575817 ("I mistapped into the empty space around the message") does not work either.

**Comment by devurandom** [comment]
Persists with 2025.04.21-4-FDroid in the way described on 2025-03-13.

**Comment by vng** [comment]
@devurandom @cintek @dr4Ke Do you have the same issue with the latest update?

**Comment by cintek** [comment]
> [@devurandom](https://github.com/devurandom) [@cintek](https://github.com/cintek) [@dr4Ke](https://github.com/dr4Ke) Do you have the same issue with the latest update?

No, I didn't have this issue for a long time now. Thanks for your work!

**Comment by dr4Ke** [comment]
> > [@devurandom](https://github.com/devurandom) [@cintek](https://github.com/cintek) [@dr4Ke](https://github.com/dr4Ke) Do you have the same issue with the latest update?
> 
> No, I didn't have this issue for a long time now. Thanks for your work!

Same here.
