### ISSUE TITLE
Fails to open address from other apps

### ISSUE THREAD

**Issue by privatemaker** [organicmaps/organicmaps#5601]
**Describe the issue**
Please write here a clear and concise description of what the bug/issue is about.

When clicking on an address in third-party app (Contacts or Calendar) and trying to load a Point of Interest in OMaps it fails to do anything.

**Steps to reproduce**

Click on an address in third-party app (Calendar) and select OMaps

<img src="https://github.com/organicmaps/organicmaps/assets/49612519/0951cfcd-63cc-4f97-81ca-92ff03ad1d85" width="375">

When another map enabled app is installed, and Android prompts user to choose, the result is the same.

<img src="https://github.com/organicmaps/organicmaps/assets/49612519/c78f6a99-46ac-4284-89cf-4d1cc885469f" width="375">

OMaps opens, but does not center or seem to perform any look up on the map. 

Upon further investigation, it seems the issue is when accessing from a third-party app the address is in string format `Europlatz 1, 10557 Berlin`

In this case OMaps fails to do anything, when loading OMaps with a geo-coord `52.517355, 13.38998` it works perfectly as expected and loads the POI.

**Expected behavior**

- Perform geocode lookup if string is an address
- Take user to "Search" prompt with address string pre-populated
- Notify user with an error message such as:

```
Organic Maps could not locate the place:

Europlatz 1, 10557 Berlin
```

**System information:**

 - Operating system and its version: Android 13
 - Organic Maps version: 2023.07.13-FDroid
 - Device Model: Pixel 6

**Comment by RedAuburn** [comment]
tracked in https://github.com/organicmaps/organicmaps/issues/320 (implementing geo: uri query flag support)
