### ISSUE TITLE
Improve text message when sharing a place

### ISSUE THREAD

**Issue by privatemaker** [organicmaps/organicmaps#5602]
**Describe the issue**

When clicking the "Share" icon in OMaps, the text containing a Place (POI) is undesirable.

**Steps to reproduce**

Select any Place and then tap on the share icon which shows the following:

<img src="https://github.com/organicmaps/organicmaps/assets/49612519/d4670d9a-1020-490e-af04-93ab5b63acee" width="375">

The user sees the text `Hi, ...` which is unclear as to what is being shared.

**Expected behavior**
 
Produce a more useful sharable message such as:

```
Unter den Linden, 14, 10127

Open place in an app
geo:52.51745,13.38980?z=17  

See place on a webpage:
https://omaps.app/s4MnKE0BOq/Cold_War_Museum
```

The improved message does the following:

- Shows address on a single line
- Less conversational "Hi... I am here" which might not be true or contextually relevant
- Uses [Geo URI Scheme](https://en.wikipedia.org/wiki/Geo_URI_scheme) instead of app specific  `om://` for better interoperability
- More space between entities makes selecting to copy and paste easier

Alternative option is what OsmAnd~ does, which is pop-up an modal with multiple options, but this approach is more involved engineering wise.

<img src="https://github.com/organicmaps/organicmaps/assets/49612519/d6f2bd76-664d-476e-b120-12f13dfe5ed2" width="375">

**System information:**

- Operating system and its version: Android 13
- Organic Maps version: 2023.07.13-FDroid
- Device Model: Pixel 6

**Comment by Kopterlove** [comment]
Same as #2261

**Comment by privatemaker** [comment]
Not exactly "same" as I bring up other points as well as the one in #2261

Also related discussion #4536

**Comment by privatemaker** [comment]
The singular line `Hi,` issue I describe is discussed in #1083

May I suggest triaging (closing) those three issues other issues, as this one issue since I address all points here?
