### ISSUE TITLE
Bunch of addresses are not indexed 

### ISSUE THREAD

**Issue by kuba-orlik** [organicmaps/organicmaps#5604]
**Describe the issue**
It's impossible to find this node and all address nodes in its neighborhood using search in Organic Maps:

https://www.openstreetmap.org/node/2513769789

**Steps to reproduce**
1. Go to search
2. Type "Osiedle Armii Krajowej 48, Poznań"
3. Find results to various addresses that include the word "osiedle", but it seems to ignore all words after that

**Expected behavior**

This node should appear as one of the search results, as it's a direct address match

**Screenshots**
![Screenshot_20230725-172154_Organic_Maps](https://github.com/organicmaps/organicmaps/assets/2697916/db0b90b8-4165-4b2a-8c48-3de45c97cb55)

**System information:**
 - Operating system and its version: Android 11
 - Organic Maps version: 2023.07.13-10-FDroid
 - Device Model: Pixel 3a

**Comment by vng** [comment]
https://github.com/organicmaps/organicmaps/issues/5307

**Comment by vng** [comment]
https://github.com/organicmaps/organicmaps/pull/6643
