### ISSUE TITLE
Show the current speed limit of the road that you are on

### ISSUE THREAD

**Issue by K4LCIFER** [organicmaps/organicmaps#5612]
**Is your feature request related to a problem? Please describe.**
Currently you can only see your current speed limit, and have no indicator of what the maximum is for the road

**Describe the solution you would like**
Just a simple indicator of what the speed limit is of the current road

**Describe alternatives you have considered**
n/a

**Additional context**
n/a

**Comment by K4LCIFER** [comment]
duplicate of #952

**Comment by K4LCIFER** [comment]
@RedAuburn why was this switched from closed to not planned? There is an existing open request for it.

**Comment by biodranik** [comment]
It's planned, don't worry.

**Comment by K4LCIFER** [comment]
I'm not concerned, I'm just wondering why that specific change was made to this issue's status.

**Comment by RedAuburn** [comment]
> @RedAuburn why was this switched from closed to not planned? There is an existing open request for it.

The grey one is used for duplicate issues as well as not planned things, it's just housekeeping :)
