### ISSUE TITLE
Announce the first event when you start navigating.

### ISSUE THREAD

**Issue by K4LCIFER** [organicmaps/organicmaps#5614]
**Is your feature request related to a problem? Please describe.**
When you start navigating, the voice is silent, and only tells you the first event when you are immediately on it.

**Describe the solution you would like**
It would be good if the first even was verbally said as soon as navigation begins.

**Describe alternatives you have considered**
n/a

**Additional context**
n/a

**Comment by biodranik** [comment]
@Jean-BaptisteC was there already a similar issue?

**Comment by K4LCIFER** [comment]
> @Jean-BaptisteC was there already a similar issue?

I tried to search for one, but I was unable to find any. If you do find a duplicate, please let me know, so that I can close this issue as a duplicate.

**Comment by Jean-BaptisteC** [comment]
https://github.com/organicmaps/organicmaps/issues/4811

**Comment by K4LCIFER** [comment]
Duplicate of #4811.
