### ISSUE TITLE
When navigating, the name of the street should be announced with each event.

### ISSUE THREAD

**Issue by K4LCIFER** [organicmaps/organicmaps#5615]
**Is your feature request related to a problem? Please describe.**
It can be confusing at times to know what the navigator is telling you where to go if you don't know the name of what street to turn on to.

**Describe the solution you would like**
It would be best to say the name of the street that pertains to the navigation event. For example: "in x distance, turn right onto y street".

**Describe alternatives you have considered**
Related to this, it should also say the name of the destination, when you arrive.

**Additional context**
n/a

**Comment by K4LCIFER** [comment]
Duplicate of #615

**Comment by biodranik** [comment]
How often do you see or know the name of the street where you should turn? It is true mostly for highway exits.

**Comment by K4LCIFER** [comment]
> How often do you see or know the name of the street where you should turn? It is true mostly for highway exits.

It is exceedingly rare to not be able to see the name of the street that one is turning onto, in a well maintained municipality. I don't think this feature should be pushed aside simply because there exists municipalities in the world with poor maintenance practices.

**Comment by biodranik** [comment]
There are only a few municipalities on the world where street names are visible on crossings for drivers. And usually only major crossings are labeled in an easy to read way.

**Comment by K4LCIFER** [comment]
> There are only a few municipalities on the world where street names are visible on crossings for drivers. And usually only major crossings are labeled in an easy to read way.

I'm not sure where you are driving, but I guarantee you that if you drop a Google Street View pin at any crossing in the USA, or Canada (and I bet you in any other well developed country in the world), you are going to see a street name.

**Comment by zyphlar** [comment]
As you can see in the linked issue I'm working on this feature, but fun fact apparently in Japan people navigate based on intersection names and not street names! My penpal says that "turn right onto Main Street" is much less of a thing than "turn right at the Kojimachi Police Station."

So "Kojimachi Police Station" will literally be a sign on a stop light at an intersection, and it happens to exist at the corner of Shinjuku-Dori Avenue and an unnamed side street, and that's all you get. The presumption that every significant street has a name just isn't true.

However to your point, Japanese people *do* use clearly visible signage to navigate roads and intersections. And to Biodranik's point, when I plop down a Google Street View in Kiev I see a lot of "turn here if you want to go here" signs but basically no street name signs. So different parts of the world will have radically different ways of navigating.

**Comment by biodranik** [comment]
It would be great to learn from the most popular navigators ;-)

**Comment by zyphlar** [comment]
@biodranik good point, I've never asked, do you know how Google or Apple or other similarly mainstream apps work in your region? We've explained a lot about how Google works in America etc but obviously we need to handle all cases. So far it sounds like many Eastern Europeans prefer simple "turn left, then turn right" without details? I can tell you exactly what the situation is where I live but I'll be repeating myself since it's extensively discussed and we're already on the correct path
