### ISSUE TITLE
Missing icon for events venues

### ISSUE THREAD

**Issue by Outlet2048** [organicmaps/organicmaps#563]
In the current version of organic maps there are some POIs that don't display any icon

Ice cream parlor and amenety=events_venue seem to be affected

**Comment by pastk** [comment]
We have an icon for `amenity=ice_cream` already and we'll have it used for `shop=ice_cream` and `ice_cream=yes` next release (see https://github.com/organicmaps/organicmaps/pull/1966/commits/8d8239d444752e3a5ef10d4b4b3b0b9c81ac0f19).

We don't have an icon for `amenity=events_venue` indeed.

**Comment by dvdmrtnz** [comment]
I think we could make an icon based on a cake icon:

![baseline_cake_black_24dp](https://user-images.githubusercontent.com/47610359/203641491-bddcbe48-0916-44b4-b53c-0bcc2c1d462b.png)
https://fonts.google.com/icons?selected=Material%20Icons%3Acake%3A

Or a celebration icon:

![baseline_celebration_black_24dp](https://user-images.githubusercontent.com/47610359/203641367-ab1ed685-2bc6-49b5-8647-894375d30f5c.png)
https://fonts.google.com/icons?selected=Material%20Icons%3Acelebration%3A

**Comment by dvdmrtnz** [comment]
This was done in #5368
