### ISSUE TITLE
identical condition

### ISSUE THREAD

**Issue by maddin200** [organicmaps/organicmaps#5635]
[D:/Data/OpenSource/organicmaps-master/3party/opening_hours/opening_hours.cpp line 390
Code:
return lhs.GetStart() == rhs.GetStart() &&
         lhs.GetEnd() == rhs.GetEnd() &&
         lhs.GetPeriod() == lhs.GetPeriod();  // <-- should be rhs.GetPeriod()

**Comment by Jean-BaptisteC** [comment]
Create PR, if you want improve Organic Maps
