### ISSUE TITLE
"Organic Maps keeps stopping"

### ISSUE THREAD

**Issue by d0k3** [organicmaps/organicmaps#5648]
**Describe the issue**
When normally using Organic Maps (looking through maps), I get repeated "Organic Maps keeps stopping" popups every few seconds.

**Steps to reproduce**
1. Have some maps loaded
2. Look at some place of your choice on the maps
3. Look around
4. See the popup happen

**Expected behavior**
Being able to use Organic Maps without interuptions every few seconds.

**Screenshots**
As I believe everyone knows that popup and there are no special steps required to make it happen, no screenshots. I can add some if required, though. 

**System information:**
 - Android 13
 - Organic Maps version: 2023.07.13-10-Google (happens with all other versions I tried, including F-Droid version)
 - Device Model: Redmi Note 10 Pro

**Workaround**
It (apparently) stops happening when "VulkanForbidden=true" is added to settings.ini file. However, there's no setting in-app for that one, and the file is only reachable via a rooted phone.

**Comment by biodranik** [comment]
Is it a crash? Can you please enable logs in OM settings, reproduce the crash, and send us logs via Report a bug?

**Comment by biodranik** [comment]
If it's a wait dialog, please check #5596

**Comment by biodranik** [comment]
After collecting logs you can disable Vulkan by typing ?gl in the search box and restarting OM.

**Comment by d0k3** [comment]
@biodranik - thank you! Actually, that Vulkan setting did not fix it. I moved all my maps to the internal storage for now, and I'll see if it happens again (will close this issue if not). Where do I find the logs after enabling them? Organic Maps seems to have no info on the location.

**Comment by biodranik** [comment]
Logs are zipped and attached to email automatically when you "Report a bug". 

It may make sense to leave issue open for other users. There's clearly something wrong: our code should not read SD on the main UI thread. Maybe @rtsisyk or @vng can take a look on it.

**Comment by biodranik** [comment]
@d0k3 Can you please clarify, was that dialog you've seen about "Wait..." or "the app stopped working"? The second is about the crash. The first one is about another issue I referenced.

**Comment by d0k3** [comment]
@biodranik - actually it was similar to this one, with the three options shown:
https://forumstatic.oneplusmobile.com/opforum-gl/upload/image/front/thread/20220615/3028731/1089354309638291459/1089354309638291459.jpg

I moved all of my maps to the internal memory, and haven't seen that message since then.

**Comment by biodranik** [comment]
So it's about SD card, not about the crash. Good! Then typing ?gl was not relevant, you can enable Vulkan back by typing ?vulkan in the search and restarting OM.

**Comment by d0k3** [comment]
Alright. I also removed the VulkanForbidden=true line from my settings.ini. Still no issues so far

**Comment by biodranik** [comment]
Closing it as it duplicates https://github.com/organicmaps/organicmaps/issues/5596
