### ISSUE TITLE
Wrong name of A8 in Slovenia in Android App

### ISSUE THREAD

**Issue by dev24126** [organicmaps/organicmaps#5659]
**Describe the issue**
In the Android App the eastern part of the A8 is wrongly named B8. In opentreetmaps it is named comletely A8. 

**Steps to reproduce**
Just use the Android App and check in the maps. 

**Expected behavior**
The steet should be named A8 as it is in openstreetmaps.

**Screenshots**
![image_2023-08-06_07-38-30](https://github.com/organicmaps/organicmaps/assets/69791595/d8ff0143-6d38-4616-a71b-8fad72bd0bfb)

**Comment by Jean-BaptisteC** [comment]
Ref hav changed recently -> https://www.openstreetmap.org/way/330332786/history
Problem be fix in next version

**Comment by patepelo** [comment]
@dev24126 is this problem still present? Or it is now correct with the new OSM data?

**Comment by dev24126** [comment]
@patepelo it is now corrected in the new OSM data. Thanks.
