### ISSUE TITLE
Tourism attractions view is bloated

### ISSUE THREAD

**Issue by d4f5409d** [organicmaps/organicmaps#5660]
**Describe the issue**
Please write here a clear and concise description of what the bug/issue is about.

The attraction search includes pois that aren't attractions and not useful either.

**Steps to reproduce**
1. Search for tourist attractions
2. See the issue

**Expected behavior**
Only show pois that have `tourism=attraction` attached to them

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.
![Screenshot_2023-08-06-10-21-07-00_10a7d9276315e62e56e7300dfec6be06.jpg](https://github.com/organicmaps/organicmaps/assets/76624594/2d538444-ff9e-4bea-84cd-14a14b53a8fa)

![Screenshot_2023-08-06-10-21-48-99_50ecd26a21c2c56ce608de5e94733463.jpg](https://github.com/organicmaps/organicmaps/assets/76624594/b698155f-4047-4830-8d93-27c54461d63d)

https://overpass-turbo.eu/map.html?Q=%2F*%0AThis%20has%20been%20generated%20by%20the%20overpass-turbo%20wizard.%0AThe%20original%20search%20was%3A%0A%E2%80%9Ctourism%3Dattraction%20in%20Tihany%E2%80%9D%0A*%2F%0A%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%0A%2F%2F%20fetch%20area%20%E2%80%9CTihany%E2%80%9D%20to%20search%20in%0Aarea(id%3A3601078511)-%3E.searchArea%3B%0A%2F%2F%20gather%20results%0A(%0A%20%20%2F%2F%20query%20part%20for%3A%20%E2%80%9Ctourism%3Dattraction%E2%80%9D%0A%20%20node%5B%22tourism%22%3D%22attraction%22%5D(area.searchArea)%3B%0A%20%20way%5B%22tourism%22%3D%22attraction%22%5D(area.searchArea)%3B%0A%20%20relation%5B%22tourism%22%3D%22attraction%22%5D(area.searchArea)%3B%0A)%3B%0A%2F%2F%20print%20results%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B

**System information:**
 - Operating system and its version: A13
 - Organic Maps version: 2023.08.03-63-Google-beta
 - Device Model: OPlus8

**Additional context**
Please add any other context and important details/notes/comments about the problem here.

**Comment by RedAuburn** [comment]
the current types included in the @tourism category:

```
tourism-attraction|@tourism
tourism-artwork|@tourism
tourism-viewpoint|@tourism
tourism-information|@tourism
amenity-place_of_worship|@tourism
tourism-museum|@tourism
waterway-waterfall|@tourism
historic-archaeological_site|@tourism
historic-castle|@tourism
historic-city_gate|@tourism
historic-citywalls|@tourism
historic-fort|@tourism
historic-gallows|@tourism
historic-memorial|@tourism
historic-memorial-sculpture|@tourism
historic-memorial-statue|@tourism
historic-memorial-war_memorial|@tourism
historic-monument|@tourism
historic-pillory|@tourism
historic-ruins|@tourism
historic-ship|@tourism
historic-tomb|@tourism
historic-wayside_cross|@tourism
historic-wayside_shrine|@tourism
leisure-park|@tourism
tourism-zoo|@tourism|@children
tourism-information-office|@tourism
tourism-information-board|@tourism
tourism-information-map|@tourism
leisure-water_park|@tourism|@children
tourism-gallery|@tourism
tourism-theme_park|@tourism|@children
boundary-national_park|@tourism
leisure-nature_reserve|@tourism
natural-glacier|@tourism

```

**Comment by biodranik** [comment]
Please consider less dense areas where every viewpoint matters. "Bloated" here is a plus, because you can always select only what you need (if necessary), instead of assuming that there is nothing interesting in the area at all.

**Comment by d4f5409d** [comment]
My view would something like propose the tourism=attraction tag as a separate feature category and cosider this old one as an "interesting things" category which would be more relevant to everyone.

**Comment by biodranik** [comment]
Do you propose to introduce separate "interesting things" and "tourism attraction" visible search categories? What would be the difference? "interesting things" are very different for everyone, it would be hard to guess what users need.

**Comment by d4f5409d** [comment]
> Do you propose to introduce separate "interesting things" and "tourism attraction" visible search categories? What would be the difference? "interesting things" are very different for everyone, it would be hard to guess what users need.

I am not sure about the naming but yeah, you know what I mean. Tourists who wouldn't like to see every corner of the city, only a few main/bigger sights which is known by tourists should be either separated or highlighted.
