### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by maddin200** [organicmaps/organicmaps#5666]
/routing/regions_router.cpp line 96
code:
void RegionsRouter::Do()
{
  m_mwmNames.clear();

  auto sparseGraph = std::make_shared<RegionsSparseGraph>(m_countryFileGetterFn, m_numMwmIds, m_dataSource);
  sparseGraph->LoadRegionsSparseGraph();

  std::unique_ptr<WorldGraph> graph = std::make_unique<DummyWorldGraph>();

  std::unique_ptr<IndexGraphStarter> starter; // <-- unused

**Comment by Jean-BaptisteC** [comment]
CC @vng
