### ISSUE TITLE
Some Dutch and Italian translations

### ISSUE THREAD

**Issue by 501Ghost** [organicmaps/organicmaps#5688]
As a follow-up of some translations I added quite a while ago, I'm uploading a few additions to types_strings.txt here. I'm still not technical enough to figure out how exactly I'm supposed to present this in a PR or whatever, so it's just the raw text file. 

The changes consist mainly of new Dutch and Italian translations, and a little bit of English, e.g. "culvert" for waterway.ditch.tunnel.

[types_strings.txt](https://github.com/organicmaps/organicmaps/files/12307456/types_strings.txt)

**Comment by Jean-BaptisteC** [comment]
CC @biodranik
