### ISSUE TITLE
Can't search my address or look it up on the map even though it's on openstreetmaps

### ISSUE THREAD

**Issue by cardcraft** [organicmaps/organicmaps#5690]
When I'm trying to search my or other address on the app nothing shows even though its on the OpenStreetMaps website.

The building address I searched should take me to it.

**System information:**
 - Operating system and its version: Calyxos 4.11.0 on Android 13
 - Organic Maps version: 2023.07.13-10-FDroid
 - Device Model: Google pixel 6 pro

**Additional context**
I also can't search for anybody else's address as they don't show up either.

Looking up the streets works just fine and putting in their Latitude and Longitude also works fine.

**Comment by Jean-BaptisteC** [comment]
Please give an example

**Comment by biodranik** [comment]
Are addresses and houses present in OpenStreetMap.org map? OpenStreetMap.org website search uses Nominatim that can search even for addresses that are absent at OpenStreetMap.org.

**Comment by cardcraft** [comment]
OpenStreetMap.org does seem to be using Nominatim to find my addresses. Heres one example that found the building on the website but not on the app 

"7564 Moore Court, Arvada CO 80005"

**Comment by cardcraft** [comment]
Didnt mean to close it, I suck at github

**Comment by zyphlar** [comment]
There is no address mapped at this location as far as I can tell; OSM returns the street which is fortunately very small. This issue would be solved by more OSM address coverage or by OpenAddresses.io integration. @cardcraft I'm happy to help you work on an address mapping or import project for your city, that's the best way to make address search work for everyone.

**Comment by patepelo** [comment]
@zyphlar Thank you for clarifying. And thank you @cardcraft for reaching out. I will mark this issue as closed as it is at core data at OpenStreetMap. Feel free to reach out again if you need any help with those addresses. 🙃
