### ISSUE TITLE
Include important amenity-place_of_worship in tourism category

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#5704]
> We should include some important temples in sightseeing somehow. Think Sagrada de Familia in Barcelona, for example. Can you please create a separate issue?

_Originally posted by @biodranik in https://github.com/organicmaps/organicmaps/pull/5662#discussion_r1290903263_
      
      

Currently no places of worship are matched for tourism category because there are too many small/uninteresting ones.

could potentially generate a popularity ranking from Wikipedia yearly pageviews:
https://wikitech.wikimedia.org/wiki/Analytics/AQS/Pageviews

**Comment by biodranik** [comment]
A simpler solution would be to display POIs with Wikipedia links, maybe with some type of filtering (e.g. only place of worship).

**Comment by muralito** [comment]
> We should include some important temples in sightseeing somehow. Think Sagrada de Familia in Barcelona, for example. Can you please create a separate issue?

Shouldn't this kind of temples be also tagged as tourism=attraction? As a tourist, you will go there guided by the "tourism" info about the place, and not by the religious info. (I'm replying here without a previous search in wiki or OSM-Tagging list)

**Comment by biodranik** [comment]
You're right, most popular temples are already marked with tourism=attraction (6651 total in OSM). Then likely this issue can be closed or converted to another one, what are other criteria to highlight interesting places nearby?
