### ISSUE TITLE
Duplicate type name in the editor

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#5708]
![выява](https://github.com/organicmaps/organicmaps/assets/170263/8213f4c7-84d2-43b7-8763-e3ef0367eff8)

**Comment by strump** [comment]
After some debugging I found that 4 categories has no Ukrainian translation:

* `shop-chocolate`
* `shop-coffee`
* `shop-music`
* `shop-musical_instrument`

**Comment by biodranik** [comment]
@strump 
1. Can you please add them?
2. Are there any other language translations missing too? Can you please add them too using tools/python/translate.py or tools/unix/translate_categories.sh ?

**Comment by Adviser3523** [comment]
https://github.com/organicmaps/organicmaps/issues/5708#issuecomment-1676347182

> * `shop-chocolate`
> * `shop-coffee`
> * `shop-music`
> * `shop-musical_instrument`

Ukrainian is my native language so this is translations:
- `shop-chocolate -> шоколадна лавка`
- `shop-coffee -> Кав'ярня`
- `shop-music -> Музична крамниця`
- `shop-musical_instrument -> Крамниця спеціального інструменту`

**Comment by strump** [comment]
@ghost  категорія `shop-coffee` відноситься до POI з тегом `shop=coffee`. [Wiki](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcoffee) каже, що це "Shop focused on selling different kinds of coffee". `Кав'ярня` - це місце де готують каву. Може краще перекласти "Магазин кави" або "Кавова лавка"?

Також `shop-musical_instrument` ти пропонуєш перекласти як "Крамниця спеціального інструменту", але треба вказати, що мова саме про музичні інструменти. "Крамниця музичних інструментів" мабуть буде краще?

**Comment by strump** [comment]
Fixed in PR #6520
