### ISSUE TITLE
Map of India has a rendering issue

### ISSUE THREAD

**Issue by Kidcredo** [organicmaps/organicmaps#571]
![Screenshot_20210613-090840_Organic_Maps.png](https://user-images.githubusercontent.com/15522605/121794597-24d27680-cbf9-11eb-9b57-c88ed6c5a367.png)

**Comment by rtsisyk** [comment]
Hi, thank you for your report. We are aware of this problem. What is your version of the app? 2021-06+ versions don't have such problem.

**Comment by Kidcredo** [comment]
Version 2021.06.07-5-gd4d3b46566-FDroid is the version i have installed on my phone

**Comment by Kidcredo** [comment]
Clearing the app storage fixed this issue for me.
