### ISSUE TITLE
amenity=shelter + shelter_type=public_transport prevents highway=bus_stop from rendering

### ISSUE THREAD

**Issue by RicoElectrico** [organicmaps/organicmaps#5716]
**Describe the issue**
As in the title, bus stop icon is not visible even on highest zoom

**Steps to reproduce**
1. open this area in OM https://www.openstreetmap.org/#map=19/54.56293/18.49997

**Expected behavior**
Bus stop icon should take priority.

**Screenshots**
![Screenshot_20230814_011042_Organic_Maps_Beta](https://github.com/organicmaps/organicmaps/assets/1409116/3f03f349-e447-48c1-805f-d86fa3bfbf33)
![Screenshot_20230814_011048_Organic_Maps_Beta](https://github.com/organicmaps/organicmaps/assets/1409116/91a4d617-a6a7-4bf9-a805-60917d24aeab)

**System information:**
 - Android 13
 - Galaxy S23
 - Organic Maps 2023.08.07-10-Google-beta

**Additional context**
_Staniewicza 02_ doesn't have a shelter marked as a separate node while _Staniewicza 01_ does.

**Comment by biodranik** [comment]
@pastk

**Comment by pastk** [comment]
@RicoElectrico thanks for the report!
It was fixed already, but that beta didn't include the fix, it'll show up as a bus stop in the upcoming release!
