### ISSUE TITLE
Invalid routing

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#572]
Jun 12, 2021, 10:44 PM email:

> Маршрут Белорецк-Волгоград.
> В районе села Улукулево трасса проходит мимо села. Навигатор же построил маршрут с заездом в это село и > проездом ЖД переезда. Сама трасса проходит над ЖД мимо села.

![Screenshot_20210612-224318_Organic Maps](https://user-images.githubusercontent.com/1799054/121796624-316bc480-cc23-11eb-92af-cab119ed9d1e.jpg)

[logs.zip](https://github.com/organicmaps/organicmaps/files/6680784/logs.zip)

**Comment by biodranik** [comment]
Надо просить перепроверять в ОСМ и OSRM, плюс учитывать, что онлайн баги будут обычно исправлены, у нас же лаг с генерацией…

**Comment by vng** [comment]
Fixed
<img width="1063" alt="Screenshot 2022-01-26 at 16 43 44" src="https://user-images.githubusercontent.com/175612/151173888-9a925b2b-717f-4eaf-9586-05b1a7867c0c.png">
