### ISSUE TITLE
Improve flow of adding Place to OSM, fix bad state

### ISSUE THREAD

**Issue by privatemaker** [organicmaps/organicmaps#5727]
**Describe the issue**

While attempting to add a Place when clicking the back button `⭠` the user is taken to an incorrect state.

**Steps to reproduce**

The following triggers the bad state.

1. Select a point on map
2. Open drawer and click `Add Business`
3. Select appropriate category
4. Fill out fields of data for Place / Business
5. Click the confirm checkmark `✓` in top right (Red Circle 1)

The `✓` communicates to user that they should confirm saving the data they just input. It is unclear (to me) if the Place data has been saved somewhere, or if clicking `✓` saves state.

Upon clicking `✓` the user is taken to `Login to Open Street Maps` webview. 

<img src="https://github.com/organicmaps/organicmaps/assets/49612519/e21568b0-f8f3-4c18-859c-1cdd9920597e" width="600">

1. At the Open Street Map login, click the back `⭠` button (Red Circle 2)
2. User is taken to `Categories Search` view from Step `3.` 

The categories search field is a bad state. It is confusing to user where they are.
If the user clicks on the appropriate category, the input fields are partially incomplete from data they just entered.

**Expected behavior**

The confirm `✓` button in Step `5.` should not take the user directly to OSM login screen. 
The button should take the user back to the map view with the newly added Place selected.

**Additional context**

To submit data to OSM, there should be a toggle switch in the Add Place form.

```
Conribute Place to OSM   [Off / On]
```

The toggle should default to `Off` on each new Place unless it is editable in a global setting. 

Upon toggling to `On` if a user is logged into OSM, then nothing unusual happens, the data is sent.

If a user **is not logged into** OSM, then it should pop-up the OSM login screen at that moment.

**Comment by biodranik** [comment]
Can you please elaborate on why a toggle switch is needed at all? The main goal of the current UX is to motivate users to register in OSM and motivate them to contribute. There is no any value in adding something on the map and not uploading it to OSM automatically.

The bug is that the back button doesn't go back to the expected state, it should be fixed. For example, the back button can be removed, and the "Not now", or "Register later" button can be added instead. Or the back button can just open the map screen (of course, the edited or added map feature should be saved!). Introducing a switch looks like an unnecessary overkill.

**Comment by privatemaker** [comment]
**Privacy Implications**

> The main goal of the current UX is to motivate users to register in OSM and motivate them to contribute.

There are many user personas who need a user friendly privacy respecting map app with the ability to add Places which contain metadata beyond `Title` and `Details` as is offered with Bookmarks. Some personas with heightened privacy considerations:

- Small Businesses (their clients)
- Delivery Drivers (delivery stops)
- Activists
- Sex Workers
- Politically Persecuted Persons

> Introducing a switch looks like an unnecessary overkill.

It may seem like overkill, but when making it fast and intuitive for people to add Places with metadata, it is of utmost importance to make it clear and make it user decidable *exactly* when this data will be transmitted to an open-source database.


**UX Bug**

> the back button can just open the map screen (of course, the edited or added map feature should be saved!). 

Using a back button whereby data input is not a good UX pattern. In users minds `back` is related to `undo` while a checkmark to `confirm` makes a user know they are saving state.

**OSM Data Contribution**

Strategies for this will be explained in other issues.

**Comment by biodranik** [comment]
RE: privacy
You're likely speaking about this issue: https://github.com/organicmaps/organicmaps/issues/1325

**Comment by privatemaker** [comment]
@biodranik I am speaking about another aspect of #1325 aside from immediate timestamped updates which is an even further privacy issue- this is literally what Foursquare's entire value proposition was: `Let the world know where you are at the moment you are there`

In issue #5746 I outlined multiple personas who might benefit greatly from saving private Places which are **never uploaded to OSM** as well as sometimes, see comments there please 😄

**Comment by biodranik** [comment]
Note: the edit is not timestamped immediately ATM. Uploads are done when OM goes into the background.
