### ISSUE TITLE
Bicycle rental icon is using old style 

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#5729]
@RedAuburn What a great job you did in https://github.com/organicmaps/organicmaps/pull/3896! 👏

The icon for bicycle rental is still using the old style of icon inside blue background. I think it should be updated to the new style. Compare the new style in the bike parking and the old style in the bike rental:

![](https://github.com/organicmaps/organicmaps/assets/47610359/6261c53b-3995-4bcf-bbeb-566a2eaa9ae9)

**Comment by RedAuburn** [comment]
thank you <3 forgot about the bike-adjacent icons, will prepare a PR 👍

**Comment by Misalf-git** [comment]
Would it make sense to keep the background for `bicycle_rental`, as it's kind of similar, or closer to public transport, compared to parking?

**Comment by dvdmrtnz** [comment]
Actually, I was asking to do both things: remove the square blue background and change the bike icon drawing.

If we want to keep the blue background I would suggest to change the blue background to the same blue color as the transport icons.

As you can see in the [wiki](https://github.com/organicmaps/organicmaps/wiki/Icons) the bicycle rental icon is now in between styles, and I think it should be either a "Transport" icon or a "Parking" icon, for consistency.

![](https://github.com/organicmaps/organicmaps/assets/47610359/8e5f9dba-8678-4197-aaab-a790b2c1f78e)

**Comment by Misalf-git** [comment]
> If we want to keep the blue background I would suggest to change the blue background to the same blue color as the transport icons.

Yep.

In my understanding, it's fits better in the "Transport" category, but I'm not 100% certain.

**Comment by j13m126** [comment]
disabled parking spaces icon needs to be updated as well. ![Screenshot_20230816-220915.png](https://github.com/organicmaps/organicmaps/assets/7961926/4e1efd6b-f520-4382-a0ae-9ae234951b34)
