### ISSUE TITLE
Private parking is not transparent

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#5730]
After #3896 there are some private parkings that do not show as semitransparent, even though the description is of a private parking. Example:

https://omaps.app/0n_T5Mudwh/Parking_Zentral

om://0n_T5Mudwh/Parking_Zentral

https://www.openstreetmap.org/node/9167489588#map=19/42.81863/-1.64391

![](https://github.com/organicmaps/organicmaps/assets/47610359/56d08ebd-6405-44f0-94b7-d0c38b2a3875)
![](https://github.com/organicmaps/organicmaps/assets/47610359/4fd9603b-6866-4b82-9beb-59355cfc7a54)

**Comment by biodranik** [comment]
CC @vng @RedAuburn
