### ISSUE TITLE
Avoid duplicated description when cmt and desc tags are populated with the same value

### ISSUE THREAD

**Issue by cyber-toad** [organicmaps/organicmaps#5749]
@cyber-toad there is one improvement that should be done in a follow-up PR (you may create an issue from this comment if necessary). Some GPX tools export the same text content in both cmt and desc tags, assuming that user apps will display only one of them.

So the proper implementation should check if cmt == desc before appending it, and avoid duplication. An example of such a service is here: https://www.plotaroute.com/route/1944681?units=km

**Comment by biodranik** [comment]
It's better to mention "Fixes ..." or "Closes ..." in PRs to auto-close issues :)
