### ISSUE TITLE
Downloaded maps randomly disappearing

### ISSUE THREAD

**Issue by codingnooob** [organicmaps/organicmaps#5751]
**Describe the issue**
I downloaded all of the maps (which I have more than enough space for), but when I refresh the iOS app, some of the maps disappear at random.

**Steps to reproduce**
1. Download all maps
2. Refresh app
3. See maps
4. Some of the maps will be uninstalled

**Expected behavior**
The maps that are downloaded remain downloaded

**System information:**
 - Operating system and its version: iOS 16.6
 - Organic Maps version: 2023.07.13-3
 - Device Model: iPhone SE 2

**Comment by Jean-BaptisteC** [comment]
Can you add video?

**Comment by biodranik** [comment]
What does "refresh the app" mean? Is it about installing an update from the app store? Can you please connect your iPhone to a Mac next time when maps disappear, and copy all data from Organic Maps to a Mac? Then check if "disappeared" maps are actually there because maps can "disappear" if they are corrupted for whatever reason. And please let us know about the result.

**Comment by codingnooob** [comment]
After redownloading the maps that disappeared, it seems like the issue is resolved (perhaps the maps somehow didn't download properly the first time around). For now, everything seems good, but I don't know if it's going to occur again.

Below is a video of me redownloading all of the maps that disappeared.
https://ufile.io/8un002ab

**Comment by biodranik** [comment]
@codingnooob can you please clarify, if you were using downloaded maps before they disappeared, or you didn't use them before (that implies that they may fail to download).

**Comment by codingnooob** [comment]
> @codingnooob can you please clarify, if you were using downloaded maps before they disappeared, or if you didn't use them before (that implies that they may fail to download)?

I used a few of them, but not all. 

When they were originally downloaded, all of the maps had a checkmark beside them (showing that they had, at least according to the app, successfully downloaded). However, after restarting the app, some of the maps would revert to a folder or download symbol. The problem only occurred once, and so far hasn't happened again.
