### ISSUE TITLE
[android][auto] Duplicated “Route to” => “Start” screens on the search

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#5759]
**App:** b0e9a8b6c2f5b6450939fd05227dae65df06a36a Wed Jul 12 21:48:53 2023 +0200 [android-auto] Fix bugs
**Phone:** Samsung S10, Android 12 from Samsung, Android Auto 10.1.633034-release (latest)
**Auto:** Desktop Head Unit, Version 2.0-mac-arm64, Build 2022-03-30-438482292 (latest)

A screen with the “Route to” button is followed by a duplicating screen with the “Start” button.

**Reproducibility:** Always

**Steps to reproduce:**

1. [auto] Tap on “Search”

<img width="912" alt="Screenshot 2023-08-19 at 18 51 46" src="https://github.com/organicmaps/organicmaps/assets/1799054/887dfec2-aac7-40d0-bcb6-cf7a67a3e769">

2. [auto] Type something

<img width="912" alt="Screenshot 2023-08-19 at 18 52 11" src="https://github.com/organicmaps/organicmaps/assets/1799054/f506c1a1-7cb8-4165-9ab3-c28e25081bec">

3. [auto] Choose a result

<img width="912" alt="Screenshot 2023-08-19 at 18 52 41" src="https://github.com/organicmaps/organicmaps/assets/1799054/bd124148-9340-4a24-8aeb-fc1d2766daab">

4. [auto] Tap on green “Route to”

<img width="912" alt="Screenshot 2023-08-19 at 18 52 49" src="https://github.com/organicmaps/organicmaps/assets/1799054/c949e9e1-6afc-4172-930d-3a081f7ccef0">

5. [auto] One more screen with the “Start” button appears

<img width="912" alt="Screenshot 2023-08-19 at 18 52 56" src="https://github.com/organicmaps/organicmaps/assets/1799054/a4375171-5e8a-438d-8c04-6eaabeb49a82">

6. [auto] Finally, navigation starts, with one extra unneeded screen

<img width="912" alt="Screenshot 2023-08-19 at 18 53 02" src="https://github.com/organicmaps/organicmaps/assets/1799054/46f97f7b-507c-4c8e-9baf-5778dc1cfed1">

**Comment by AndrewShkrob** [comment]
This is the UX that we previously deliberated on and concurred with. I concur that I am not particularly fond of it either, but altering it is not presently a top priority. Implementing changes would demand a substantial amount of effort, so we can defer this to the next iteration.
