### ISSUE TITLE
[android][auto] Prompt the user to download the map

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#5768]
**App:** b0e9a8b6c2f5b6450939fd05227dae65df06a36a Wed Jul 12 21:48:53 2023 +0200 [android-auto] Fix bugs
**Phone:** Samsung S10, Android 12 from Samsung, Android Auto 10.1.633034-release (latest)
**Auto:** Desktop Head Unit, Version 2.0-mac-arm64, Build 2022-03-30-438482292 (latest)

Auto doesn't prompt the user to download maps.

<img width="912" alt="Screenshot 2023-08-19 at 21 01 05" src="https://github.com/organicmaps/organicmaps/assets/1799054/d1818f74-2769-49fa-8cae-0f95e01bdc23">

**Steps to reproduce**:

1. [auto] Start the app in a location without a downloaded map
2. [auto] No suggestion or hint provided that map should be downloaded

**Proposed behavior:** ask user to download the map.

**Comment by AndrewShkrob** [comment]
Done.
