### ISSUE TITLE
Wrong layout on button in Bookmarks

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#5769]
**Steps to reproduce**
1. Open OM
2. Go to bookmarks
3. Open a list with bookmarks
4. Rotate device to landscape
5. Start search -> Blue button is tiny and the icon is not centered

**Expected behavior**
The best way is to hide the button when we have not enough place to show button like zoom buttons and place page.

**Screenshots**
<img src="https://github.com/organicmaps/organicmaps/assets/87148630/0b2317a6-a22d-4a9b-b43b-6225adb71d26" height=400 />

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.07.13-10-Google
 - Device Model: Pixel 6

**Comment by sumitgarg21** [comment]
i would like to work on it. please assign me this issue

**Comment by Jean-BaptisteC** [comment]
Don't ask to work on issue, feel free open PR if you want.

**Comment by Jean-BaptisteC** [comment]
Not present with extend FAB
