### ISSUE TITLE
Regression in routing in 230814

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#5772]
**Start:** 35.333183, 33.291486
**Finish:** 35.312167, 33.280848
**Map:** Cyprus (230814)
**App:** 2023.08.20-12-Debug

<img src="https://github.com/organicmaps/organicmaps/assets/1799054/25a4c4a5-3d24-4a74-88ab-d94fdad22c55" width="400px" />

**Comment by biodranik** [comment]
Is OSM data correct there? What routes are built by OSM website?

**Comment by vng** [comment]
- What is the optimal route here on your opinion?
- OSRM makes a route via this https://www.openstreetmap.org/way/93449530, but honestly saying these tags are not trust-worthy for a car, IMO:
```
access=yes
highway=track
sac_scale=mountain_hiking
surface=unpaved
trail_visibility=intermediate
```

**Comment by vng** [comment]
And this road was marked as access=no
https://www.openstreetmap.org/way/111642919/history

**Comment by Jean-BaptisteC** [comment]
In 2024.03.18-5-Google, we have the same routing as GraphHopper, I close the issue.
