### ISSUE TITLE
Plan a route from GPX / KML Bookmarks (aka Waypoints) or Tracks

### ISSUE THREAD

**Issue by javerous** [organicmaps/organicmaps#5773]
**Is your feature request related to a problem? Please describe.**

- It's pretty frequent that for hiking or for biking, we download a track and/or a set of waypoints in a GPX file, that we want to follow in the form of route navigation.

- It's quite common to plan a road trip (car, bike, etc.) in advance with external tools (Google MyMap, any GPX-based planning software, etc.). In this case, either you put the places you want to visit / pass-by in a set of waypoints, either you directly trace tracks (for example when there is not known paths between the waypoints, so the software you are using is not able to compute a proper route from the waypoints, and the shortest path using straight line between waypoints is not what you want, or when you found a computed path between waypoint which is exactly what you want, and you don't want another software to compute another path).

-> Organic Maps, as much as I know, is not able to resolve these scenarios.

I searched a bit around that, and I din't find anything (sorry if there is).

For reference:
- https://mamot.fr/@javerous/110919369579206048#.
- https://mamot.fr/@javerous/110919381639678388#.
- https://fosstodon.org/@organicmaps/110920698624370705#.

**Describe the solution you would like**

It would be nice to:
- Be able to use a set of bookmarks / waypoints of a GPX / KML file to plan a route navigation (in the same order of the bookmarks). There is a workaround: plan a new route, then for each selected bookmark in the map, click "Add Stop". But it's not very practical, for example when there are lots of bookmarks, or when you are not sure of the initial order of the bookmarks. I guess it's not too complex to implement ?

and/or

- Be able to create a route which follows one of the tracks of a GPX / KML file. I guess it's significantly more complex, depending on how the route planer is implemented, and how well you want to handle route recomputation when you miss the track (wrong turn, road closure, etc.)
    - A track is no more (?) than a huge list of coordinates, that we can see as a huge list of "stop" points. It may be a way to implement it, but not sure the engine would support a huge list of stop point (they probably need to be hidden, anyway, so this would be special "stop" point), and I guess it wouldn't work for road closures case (Organic Map would keep trying to make you join back the next "virtual" stop which is not accessible)
    - Another way to handle a "runway exit" is to find the nearest coordinate in the track you still have to travel around, and compute an intermediate temporary route to this point (or extend the current route). I think Waze is doing something similar when you don't have internet connectivity and you got a wrong turn). <img width="941" alt="example" src="https://github.com/organicmaps/organicmaps/assets/1971659/4805d7f5-116c-458f-b33a-4118a4ae8900">

**Describe alternatives you have considered**
- For waypoints, I add them to the planed route manually, one by one, from the map, with the "Add Stop" feature.
- For tracks, there is no real solution. Komoot is able to do that. Iphigénie too, in some way. But it's limited to hiking / biking. And, well… it's not Organic Maps ;)

**Additional context**
N/A

**Comment by cyber-toad** [comment]
See also #5314, #2384, #1360

**Comment by javerous** [comment]
@cyber-toad Thanks ! I guess it means I’m very bad at searching issues 😧

@Jean-BaptisteC I guess this ticket should be closed as duplicate, then ?
