### ISSUE TITLE
Do not use double negatives in options

### ISSUE THREAD

**Issue by sciunto** [organicmaps/organicmaps#5779]
**Describe the issue**

It is quite a consensus that double negatives must be avoided as they make things slower to understand. [Example](https://uxplanet.org/16-rules-of-effective-ux-writing-2a20cf85fdbf?gi=ef2ffc0e89b9) of blog post on this.

**Expected behavior**

From the screenshot below.

Instead of "avoid on every route" , state "Allow on every route" and swap the boolean values

**Screenshots**

![Screenshot_20230819_180435_Organic Maps](https://github.com/organicmaps/organicmaps/assets/335370/4d9bf894-6d80-4dd0-afaf-d0d15f6b4225)

**System information:**
 - Organic Maps version: 2023.07.13-10-FDROID

**Comment by biodranik** [comment]
Do not allow is not equal to avoid. Avoid can still use the road if there's no any other way. How is it implemented in other apps?

**Comment by dvdmrtnz** [comment]
They all seem to use the "Avoid X" language, same as Organic Maps.

Organic Maps:
![](https://github.com/organicmaps/organicmaps/assets/47610359/1628307b-9575-4e4f-b40a-74257fe1e425)

Google Maps:
![](https://github.com/organicmaps/organicmaps/assets/47610359/8acacbe4-9c81-4fa6-b606-da038d79449c)

Apple Maps:
![](https://github.com/organicmaps/organicmaps/assets/47610359/7ef5c196-935e-42f4-8273-01e21268da28)

Osmand:
![](https://github.com/organicmaps/organicmaps/assets/47610359/c6d02672-745a-4348-8e28-c0300284a4b2)

**Comment by sciunto** [comment]
@dvdmrtnz If my initial suggestion cannot be implemented for some reason, then, I can say that I prefer the formulations by google, apple, and osmand. The reason is that reading the button entry is sufficient to understand the behavior of the sliding button while it is confusing for organic is the gray sentence is not red.

**Comment by pastk** [comment]
I agree, at first glance e.g. "Ferry crossings" switch reads like enabling them.

**Comment by dvdmrtnz** [comment]
I agree. Wording should be "Avoid X" in every line

**Comment by biodranik** [comment]
Who can help to improve it? :)

**Comment by meenbeese** [comment]
Made a PR now to fix this.
