### ISSUE TITLE
Why are downloads unencrypted?

### ISSUE THREAD

**Issue by AmadeuszL** [organicmaps/organicmaps#578]
Hello! 👋 
First of all I'd like to say that I really like your project. It looks like a compelling alternative to OsmAnd, which is really, really slow (even on modern, high-end hardware). 

My question is - **why are maps downloaded via HTTP** (and not HTTPS)? 
Possibility of tampering with the file in transit is one thing, maybe not that harmful, but it certainly leaks which "administrative regions" I was looking at... that's not the case with other map apps.

**Comment by biodranik** [comment]
Hi, great point. It was a temporary test, now we switched back to HTTPS.
