### ISSUE TITLE
Show shipwrecks

### ISSUE THREAD

**Issue by aronkvh** [organicmaps/organicmaps#5793]
Not much to add, water is usually empty anyways and it's an interesting point that's missing from OM.
historic=wreck

**Comment by dvdmrtnz** [comment]
https://wiki.openstreetmap.org/wiki/Tag:historic%3Dwreck

**Comment by RedAuburn** [comment]
what do people think about this for the icon?
<img width="48" src="https://github.com/organicmaps/organicmaps/assets/26939824/e4c9f80f-c51f-46ad-837c-26c02ec9ea47"/>

**Comment by Misalf-git** [comment]
Thats a messed up and most difficult to put hole on the golf course. :p

**Comment by aronkvh** [comment]
> what do people think about this for the icon? <img alt="" width="48" src="https://user-images.githubusercontent.com/26939824/262770079-e4c9f80f-c51f-46ad-837c-26c02ec9ea47.svg">

not too recognisable to me

**Comment by aronkvh** [comment]
this probably worse but how about something like this? 
![image](https://github.com/organicmaps/organicmaps/assets/57704946/e249fa76-7669-4913-9ca3-a9acfbd7ef8c)

**Comment by biodranik** [comment]
These shipwrecks in OSM... Are they visible or under the water? The latter case shouldn't be rendered on the map.

**Comment by aronkvh** [comment]
> These shipwrecks in OSM... Are they visible or under the water? The latter case shouldn't be rendered on the map.

according to the wiki, visibility is tagged as well

**Comment by dvdmrtnz** [comment]
> what do people think about this for the icon?
> <img alt="" width="48" src="https://user-images.githubusercontent.com/26939824/262770079-e4c9f80f-c51f-46ad-837c-26c02ec9ea47.svg">

I don’t think it’s too recognizable as a sinking ship. How about something like this:

![](https://github.com/organicmaps/organicmaps/assets/47610359/ba1dc60c-f464-46db-9a1b-d56a19e9a87a)

https://commons.wikimedia.org/wiki/File:Pictograms-nps-misc-partially_submerged_wreck.svg

**Comment by RedAuburn** [comment]
> > what do people think about this for the icon?
> > <img alt="" width="48" src="https://user-images.githubusercontent.com/26939824/262770079-e4c9f80f-c51f-46ad-837c-26c02ec9ea47.svg">
> 
> I don’t think it’s too recognizable as a sinking ship. How about something like this:
> 
> ![](https://user-images.githubusercontent.com/47610359/262817600-ba1dc60c-f464-46db-9a1b-d56a19e9a87a.png)
> 
> https://commons.wikimedia.org/wiki/File:Pictograms-nps-misc-partially_submerged_wreck.svg

this one looks good 👍
