### ISSUE TITLE
Show POI for power lines

### ISSUE THREAD

**Issue by chris-asdf** [organicmaps/organicmaps#5799]
Hi,

would it be possible to add an appropriate Poi symbol for power lines? At the moment only the poles are drawn if one is at maximum zoom. Maybe with bigger dots and lines in between? 
An example is this location:
49.821436, 12.201555
Which can also be found here: https://omaps.app/44Gjm2y3pb/Power_Tower

Thanks!

All the best,
Chris

**Comment by Jean-BaptisteC** [comment]
Why do you want increase visibility of power lines and power poles on map ?

**Comment by Misalf-git** [comment]
I agree.
Power poles / lines are usually quite tall constructions and could be the only features around that may help to understand where you are.
Currently, you would need to know exactly where it is on the map and zoom in all the way, while you can see it from far away on the ground.

**Comment by RedAuburn** [comment]
this might be a good thing to display on the outdoors style @pastk, maybe we should make a new label for outdoors?

**Comment by pastk** [comment]
They're displayed at z15- in the outdoors style already. It'd be great to have a slightly bigger icon for pylons - maybe a small circled crossed inside?

**Comment by patepelo** [comment]
> They're displayed at z15- in the outdoors style already. It'd be great to have a slightly bigger icon for pylons - maybe a small circle crossed inside?

Would something like this be a good icon when at zoom z17+? It's a way of revealing what it is when you zoom in.
![image](https://github.com/organicmaps/organicmaps/assets/23003127/32570e46-a760-4542-8ebf-591a26f53996)

**Comment by pastk** [comment]
I think it would be better to have an omnidirectional icon, because the actual lines will connect from any side of it. Also the icon shouldn't be too big still, IMHO.

**Comment by patepelo** [comment]
This is the approach of  openinframap.org

![image](https://github.com/organicmaps/organicmaps/assets/23003127/1fcdcb95-fc4a-4002-b9dd-b5d2cd5e848a)

I like it

**Comment by patepelo** [comment]
Note that is different from power poles:
![image](https://github.com/organicmaps/organicmaps/assets/23003127/abdd16b6-8292-45c5-9735-659cdd5f67af)

**Comment by biodranik** [comment]
Please try to keep map usable and not polluted too much. Even for the outdoor style.

**Comment by patepelo** [comment]
> ATM we don't display `power=pole` at all. Would be good to add them later for the outdoors style (and they could be displayed as just dots).

Maybe power poles shouldn't be represented ATM, they don't help much for orientation references and their coverage is very vague.

> But maybe better to have it in an "outline" style - like openinframap, but round.

I like the square approach since the elements are squared from that perspective but a circle will also work. 

Here some drafts. (Hidrant for size reference)

![image](https://github.com/organicmaps/organicmaps/assets/23003127/43c67719-4c9d-4deb-965f-1cb339d0d0a2)

**Comment by patepelo** [comment]
Without filling, sharper and in grey over some screenshot (z16) demo:
![image](https://github.com/organicmaps/organicmaps/assets/23003127/aff44fe1-9ffb-4e3f-b49d-f26c3473afdf)

And here again squared:

![image](https://github.com/organicmaps/organicmaps/assets/23003127/c110d4e8-bcbf-4b70-899f-c842c2ae8c94)

**Comment by pastk** [comment]
I like the first option (though it should be transparent inside).

And I think it should be smaller, i.e. half size of the hydrant.. Anyway we'll need to test it on actual map to get a better feeling of the best size.
Squared might look good too (you're right that from above its a more "real" shape), but should be smaller too.

**Comment by pastk** [comment]
It would be better to test the size on z14 (the earliest zoom for power towers) and z15 (when the lines appear).

**Comment by pastk** [comment]
Looks good!

Actually they don't look much more pronounces that dots, although squares are bigger. Dots look quite prominent because of a white "halo" around them.

**Comment by patepelo** [comment]
Here the SVG file:

![squared-power-tower](https://github.com/organicmaps/organicmaps/assets/23003127/d4742d02-b29a-43e0-a65c-e6b7dc94d9df)

if you otherwise prefer the circles, I'll prepare them

**Comment by pastk** [comment]
Thanks!

In the generic style we switch from S to M on z15 (so M is z15-).
In the outdoors style M is z14- for outdoorsy features, so its unlikely we'll need two sizes..
