### ISSUE TITLE
GPX imports not visible on map

### ISSUE THREAD

**Issue by fizwidget** [organicmaps/organicmaps#5800]
**Describe the issue**
GPX imports don't seem to work properly in v2023.08.18-7 (the current App Store release). A success message is displayed, but the imported trail is not visible on the map.

**Steps to reproduce**
1. Obtain a GPX file (example from AllTrails attached below).
2. Tap the share/open button in iOS and select OrganicMaps from the list of apps.
3. "Bookmarks loaded successfully!" is displayed.
4. The trail is visible and ticked in the "Bookmarks and Tracks" list.
5. It is missing/invisible on the map itself.

Example GPX file:
[Valley of the Waters to Wentworth Falls.gpx.zip](https://github.com/organicmaps/organicmaps/files/12418226/Valley.of.the.Waters.to.Wentworth.Falls.gpx.zip)

Corresponding KMZ file, which does import & display properly:
[Valley of the Waters to Wentworth Falls.kmz.zip](https://github.com/organicmaps/organicmaps/files/12418296/Valley.of.the.Waters.to.Wentworth.Falls.kmz.zip)

**Expected behavior**
The imported trail should be visible on the map (or at least, an explicit import error should occur).

**Screenshots**
1. Import appears to complete successfully:
![IMG_0113](https://github.com/organicmaps/organicmaps/assets/1172012/9d72b0fa-46b0-43c3-8886-8b9df1c1449d)

2. Imported trail is visible & ticked in this list:
![IMG_0115](https://github.com/organicmaps/organicmaps/assets/1172012/15ea9dc7-1c01-4d08-95f1-6b5d5db4f165)

3. It is missing from the map view:
![IMG_0114](https://github.com/organicmaps/organicmaps/assets/1172012/5cde1da7-98c4-415e-9716-737916326b79)

4. If I repeat the process with the KMZ file instead, it displays correctly:
![IMG_0117](https://github.com/organicmaps/organicmaps/assets/1172012/4b5c3687-a388-43cb-a362-8c5876089956)

**System information:**
 - Operating system and its version: iOS 16.5.1 (c)
 - Organic Maps version: 2023.08.18-7 (OSM data: 14 August 2023)
 - Device Model: iPhone XS Max

**Additional context**

- Same behaviour was observed with a GPX file from a different source (Wikiloc), so I don't think it's just an AllTrails thing.
- It worked correctly for me with the previous App Store release. 
- A GPX trail I’d imported using the previous release is still displaying correctly, it’s just new imports that don’t work.

**Comment by Jean-BaptisteC** [comment]
Import GPX works on Android -> track is visible on map

**Comment by biodranik** [comment]
@cyber-toad it looks like a regression. We received another report from another user too. Can you please check and fix it?

**Comment by cyber-toad** [comment]
hm, I checked on my Android phone and it works fine - gpx track is imported and displayed. There were minor changes in gpx system in last release, but they are common for ios and android, so not easy to guest what went wrong...

**Comment by fizwidget** [comment]
I just tried again this morning, and it’s now working for me 😳

So either…
* There’s some unknown factor that causes it work sometimes and not others.
* Or, I was making some silly mistake last night during my testing.

I’ll let you know if I’m able to reproduce it again- hopefully I wasn’t imagining the whole thing! 😅

**Comment by fizwidget** [comment]
…well that didn’t take long: I’m able to reproduce it again! Still not sure what the criteria are though. 

A couple of other details I’ve noticed:
* If I tap on the track in the bookmarks list, OM pans & zooms to its location (even though the track isn’t actually rendered on the map). 
* POIs from the imports *are* visible, it’s just the tracks that aren’t.

**Comment by cyber-toad** [comment]
@fizwidget once you have such issue, could you please tap on the item in bookmark list and check is there list of tracks displayed (should be one track for your file) and is there color and length displayed for it? It will help us to bisect import and draw issues.

**Comment by biodranik** [comment]
@cyber-toad please unzip these tracks and try them. I don't see the imported track on the map, but it is displayed in bookmarks & tracks dialog. 

[20230820.gpx.zip](https://github.com/organicmaps/organicmaps/files/12423724/20230820.gpx.zip)
[20230822.gpx.zip](https://github.com/organicmaps/organicmaps/files/12423725/20230822.gpx.zip)

**Comment by fizwidget** [comment]
@cyber-toad yup sure, here’s how I see the trail linked in the OP:

![IMG_0123](https://github.com/organicmaps/organicmaps/assets/1172012/e028ebb9-c472-4839-93c1-3c445c0c9817)

![IMG_0124](https://github.com/organicmaps/organicmaps/assets/1172012/b9a9484a-5409-4b8a-8340-196585ae5543)

So it’s 7km long and coloured purple. Second screenshot is after I tapped on it.

**Comment by cyber-toad** [comment]
> @cyber-toad @Jean-BaptisteC please unzip these tracks and try them. I don't see the imported track on the map, but it is displayed in bookmarks & tracks dialog.
> 
> [20230820.gpx.zip](https://github.com/organicmaps/organicmaps/files/12423724/20230820.gpx.zip) [20230822.gpx.zip](https://github.com/organicmaps/organicmaps/files/12423725/20230822.gpx.zip)

Both tracks are imported and visible on map on my device (Android).

**Comment by biodranik** [comment]
It looks like an iOS issue. @strump could we break it somehow?

**Comment by vng** [comment]
Please, check on this [commit](https://github.com/organicmaps/organicmaps/commit/f1021ed70b032621cd5088b40c50e4eb71ed1846)

If it works ok, we broke depth logic.

**Comment by biodranik** [comment]
This commit introduces the bug: 2e279f7b15
Reproduces easily in release on iOS

**Comment by biodranik** [comment]
The only difference between a good and bad track is the color:
<img width="1407" alt="image" src="https://github.com/organicmaps/organicmaps/assets/170263/9a6ea0b7-d502-4c3f-b101-345a001d673c">

Note that the proper fix should likely fix this bad color on load.

**Comment by cyber-toad** [comment]
> The only difference between a good and bad track is the color: <img alt="image" width="1407" src="https://user-images.githubusercontent.com/170263/263195490-9a6ea0b7-d502-4c3f-b101-345a001d673c.png">
> 
> Note that the proper fix should likely fix this bad color on load for existing users.

Sorry, I didn't get the idea - in source file from @fizwidget there is no color, also it is not set in the tracks that you mentioned above ([20230820.gpx.zip](https://github.com/organicmaps/organicmaps/files/12423724/20230820.gpx.zip) [20230822.gpx.zip](https://github.com/organicmaps/organicmaps/files/12423725/20230822.gpx.zip)) - how these kmls are created?

**Comment by biodranik** [comment]
By importing gpx and exporting kml, with and without a bad commit.
