### ISSUE TITLE
disused:shops shouldn't be render with their name

### ISSUE THREAD

**Issue by map-per** [organicmaps/organicmaps#5803]
**Describe the issue**
`disused:shops` are renderd with a name. They should either not appear on the map at all or render with 'addr:housenumber' instead of name.

(Before the latest release (2023-08-18) `disused:shops` used to render like addresses)

**Screenshots**
| latest release | before |
| --- | --- |
| ![Screenshot_2023-08-23-16-22-09-568_app organicmaps](https://github.com/organicmaps/organicmaps/assets/79519062/462eace3-60d8-453f-880f-8ac13a403d94) | ![Screenshot_2023-08-23-16-29-44-430_app organicmaps beta](https://github.com/organicmaps/organicmaps/assets/79519062/b7a6cc6b-7ba7-4974-9d99-64c12665ead2) |

OSM: https://www.openstreetmap.org/node/3929291591
Note: "Gebäude" is gernam for building

**Comment by Jean-BaptisteC** [comment]
Cc @pastk

**Comment by map-per** [comment]
And detailed information like the old website shouldn't show up in the place page (see https://www.openstreetmap.org/node/2457878842).

For german mapping practice it would make most sense to not rendering disused shops at all, but there are some countries (e.g. the Netherlands) where it is common to not map addresses separately (see https://github.com/gravitystorm/openstreetmap-carto/issues/4794)

**Comment by RedAuburn** [comment]
also see https://github.com/organicmaps/organicmaps/issues/1038

**Comment by Misalf-git** [comment]
I believe it's generally recommended to tag all relevant attributes of a feature with `disused:*` to prevent it from being rendered or used normally.

Meaning: `disused:shop="Some Shop"` + `disused:name="Some Name"`

**Comment by map-per** [comment]
> I believe it's generally recommended to tag all relevant attributes of a feature with `disused:*` to prevent it from being rendered or used normally.

Yes, that's recomended for stuff like `website` or `opening_hours`, but for `name `and address it is not common (at least in germany) to use `disused`. For `name` the [Wiki](https://wiki.openstreetmap.org/wiki/Key:disused:*) even suggests to keep it. But I started to disuse address attributes now.

At least in part this a database problem, as it's almost impossible for data consumers to tell whether an `addr:housenumber` is a feature (address feature) or an attribute (addition to e.g. a shop). Maybe a special OSM tag like e.g. `address_feature=yes`/`no` could resolve this in the long run.

**Comment by Misalf-git** [comment]
My understanding is that `name=*` (or any tag) should still be usable (e.g. no `disused:*`) if it may be relevant for anything not related to that disused feature.

The german wiki provides an example of a disused parking surface that has a `name=*` which is also still visible on the ground.
It can be found via search by name but shall not be found or suggested when searching for parking.

What I would do is tag a minor, disused shop with `disused:name=*` but for a major, land-mark like feature, leave `name=*` as-is.

I could imagine (but I don't believe) it (maybe) makes sense for nodes to be ignored entirely if they contain some `disused:*` tags.
This would probably be bad for ways / areas, though.

**Comment by map-per** [comment]
> What I would do is tag a minor, disused shop with `disused:name=*` but for a major, land-mark like feature, leave `name=*` as-is.

👍 I often use `old_name` instead for `disused:name` though, but I don't think there is a big difference



> I could imagine (but I don't believe) it (maybe) makes sense for nodes to be ignored entirely if they contain some `disused:*` tags.
> This would probably be bad for ways / areas, though.

Did a quick Overpass research: Worldwide there are 7611 nodes with both `shop` and `disused:shop`. Looks like that Idea is to simple...

**Comment by biodranik** [comment]
Can we filter out all disused objects at the map generation stage? Most users do not care about disused POI.

**Comment by Misalf-git** [comment]
> Can we filter out all disused objects at the map generation stage? Most users do not care about disused POI.

Without having it checked, I think it's already filtered out. No? Meaning, f.e. a disused shop has no icon. But the name is not "disused", so it's (correctly?) displayed.

> At least in part this a database problem, as it's almost impossible for data consumers to tell whether an `addr:housenumber` is a feature (address feature) or an attribute (addition to e.g. a shop).

Exactly. I'd be afraid to loose valuable information on the map when workaround-ing (as it seems to me) unclear or incorrect tagging.

**Comment by biodranik** [comment]
Filtering on generator stage should remove everything completely. 

@vng what about "if there's at least one disused: tag on a feature, then skip it"?

**Comment by Misalf-git** [comment]
> "if there's at least one disused: tag on a feature, then skip it"

@biodranik 

> Did a quick Overpass research: Worldwide there are 7611 nodes with both shop and disused:shop. Looks like that Idea is to simple...

**Comment by map-per** [comment]
So we need to check if `disused:shop`, `disused:amenity`, `disused:office`, `disused:healthcare` or `disused:leisure` is present and none out of shop, amenity, office, healthcare or leisure is tagged. That should work.

**Comment by biodranik** [comment]
1. Can you please clarify why `if (tag matches "disused:*") then discard whole feature (node, way or relation)` is not enough? Why do we need to check the specific list?
2. Why the `... and none out of shop, amenity, office, healthcare or leisure` check is needed?

**Comment by map-per** [comment]
1. There might be a shop that is still open, but the website is not working any more. This might be tagged as disused:website=...

2. As mentioned above ther are e.g. 7611 nodes with both shop and disused:shop. Taking a look at some of these nodes it looks like some poeple keep the old shop value as disused:shop when the operator changes. (I wouldn't tag that way, as the old shop isn't helpful information, but apparently some people do)

**Comment by map-per** [comment]
I don't think there is a nice and clean way of doing this as OSM tagging doesn't distict between address features and address attributes (https://github.com/organicmaps/organicmaps/issues/5803#issuecomment-1694252305)

**Comment by map-per** [comment]
👍 The fix is still proprietary code (#5979), is it?

**Comment by vng** [comment]
@map-per Will be available soon I hope. I'm working on a new search with addr:place, so there are a lot of _experiments_ still.

**Comment by pastk** [comment]
It was fixed by https://github.com/organicmaps/organicmaps/commit/d69d9bb2332ec581b5117f437ec638cf564ca90a

**Comment by map-per** [comment]
:rofl: Just wanted to write the same...
