### ISSUE TITLE
Render access restrictions

### ISSUE THREAD

**Issue by jmarchon1** [organicmaps/organicmaps#5814]
I would like to see access restrictions in OSM rendered in Organic Maps. Currently, highways such as driveways with a tag like `access=private` are rendered the same as ones without that tag. A slightly different color or pattern, such as that used by OSM Carto, would be nice to see to indicate that these highways are not publicly accessible.

**Comment by pastk** [comment]
We've been discussing this issue in https://github.com/organicmaps/organicmaps/issues/1454 already.

**Comment by jmarchon1** [comment]
Oops, my quick search must have missed that. Sorry for the duplicate, in that case.

**Comment by pastk** [comment]
Duplicate of https://github.com/organicmaps/organicmaps/issues/1454
