### ISSUE TITLE
Maps download URL?

### ISSUE THREAD

**Issue by WebFreak001** [organicmaps/organicmaps#582]
I'm trying to preload the maps to an SD card so that I can move them and the app to my device via SD card from my PC because I don't have any internet connection on that device, however I can't find the map download URLs anywhere.

From the code I was thinking starting with `https://cdn.organicmaps.app/data_version.json` should work, however I'm getting 404 there - and for the other URLs the defines are empty and it seems to me like it's doing HTTP requests to empty strings (`METASERVER_URL == ""`), so I have no idea what's being done there. Failing on this first URL that should be straightforward from a simple concat in code I thought I would just ask instead of investigating further, also helping others trying to preload maps.

I think if you could share a link to the maps here, that would make them a lot easier to find. Thanks!

**Comment by rtsisyk** [comment]
Hi @WebFreak001, could you please tell us about use case? Why do you want to download maps manually?

**Comment by WebFreak001** [comment]
> I'm trying to preload the maps to an SD card so that I can move them and the app to my device via SD card from my PC because I don't have any internet connection on that device

**Comment by biodranik** [comment]
Please drop us a line at download@organicmaps.app, we'll try to help you.

**Comment by rottenstump** [comment]
Having an option to download map files outside the app is a valid use case for an app that aims to be an offline navigation tool.

As an example of that, OsmAnd can be used with maps downloaded from https://download.osmand.net/list.php and placed under /sdcard/Android/data/net.osmand/files/ after sideloading an apk without ever being connected to the internet. This is helpful in the areas with slow, limited, and unreliable data connection, where the only viable way to get any large files on a phone is a cable or a card reader. Downloaded files also serve as a backup solution in case of software issues.

If the excessive load on a server caused by undesired downloads is a concern than steps to create our own map files could be provided as an alternative, although much less convenient solution.

**Comment by rtsisyk** [comment]
> s an example of that, OsmAnd can be used with maps downloaded from https://download.osmand.net/list.php and placed under /sdcard/Android/data/net.osmand/files/ after sideloading an apk without ever being connected to the internet. This is helpful in the areas with slow, limited, and unreliable data connection, where the only viable way to get any large files on a phone is a cable or a card reader.

Google removed access to `/sdcard/Android/data/*/files/` in Android 11. Android 11 already has 40%, and its market share is growing.

**Comment by WebFreak001** [comment]
my android car radio is a device that is only ever connected to the internet if I get close enough to any registered router and stay there parked for a while to download things, which is at my current living space not possible for me. Preloading the files to an SD card and then just moving the files to it would be much easier and faster for me and other apps like OSM and earlier another Maps.me fork on F-Droid made it very easy. (although the other fork stopped working because of GL issues I haven't resolved and wanted to test if they were fixed in this one) Android is not expected to be updated on that device either. Additionally access to files is something where there is always a way to obtain it through some means.

Another point for preloading on other devices is that wireless connection is often slower or for cellular data may just be too expensive to obtain multiple gigabytes of data. Downloading map files over a wired connection is faster, more reliable and in case of cellular data also cheaper.

I have a server with plenty of storage space and sufficient memory & CPU resources to process large parts of the OSM database and could offer a mirror for downloading the map files for certain regions too if there is a guide to create these map files ourself like @rottenstump has suggested.

**Comment by biodranik** [comment]
Please contact us at download@organicmaps.app about creating mirrors. We'll tell you how to sync with the latest map data. 
Our main concern is the huge amount of traffic which we need to pay for out of our pockets.

**Comment by WebFreak001** [comment]
download mirrors are now available on https://cdn.organicmaps.app/mirrors/
