### ISSUE TITLE
No perspective view

### ISSUE THREAD

**Issue by tangsgod** [organicmaps/organicmaps#583]
Hi, 
 Since the last update I don't have perspective view even if the option is on.

Lineage OS 17.1 Android 10 Redmi Note 8
Current version: 2021.06.07

**Comment by biodranik** [comment]
@rtsisyk can you reproduce it? I assume it may be related to some LineageOS driver issue.

**Comment by tangsgod** [comment]
Before going further, let me try it more.
Today, while going to work it was working. 
I think that i may have confuse no perspective view with very high view on the highway.
It may be because some others gps I tried kept perspective view while on highway.
I'll try it again on the road back to home and let you know what happen.

**Comment by biodranik** [comment]
@tangsgod ?

**Comment by biodranik** [comment]
@tangsgod If you meant 3D buildings, then please disable the power saving option in OM to see them.

**Comment by RedAuburn** [comment]
closing as no response
