### ISSUE TITLE
railway=platform with covered=yes is not rendered

### ISSUE THREAD

**Issue by map-per** [organicmaps/organicmaps#5851]
**Bug**
`railway=platform` with `covered=yes` is not rendered.

I tried to find the code that's responsible for this but couldn't find it.

**Screenshot**
e.g. platform 19;20: https://www.openstreetmap.org/way/86199264
![Screenshot_2023-08-28-11-13-26-203_app organicmaps](https://github.com/organicmaps/organicmaps/assets/79519062/b807577b-a5bb-4a97-b2fc-68a37ffe69f2)

**Comment by RedAuburn** [comment]
how do you think it be rendered?

**Comment by map-per** [comment]
I would render it just the same as non covered platforms

**Comment by map-per** [comment]
This might be related to #5979

**Comment by map-per** [comment]
The problem is solved no, looks like the handeling of covered=yes was changed in the generator (see #5979).
