### ISSUE TITLE
Factory icon

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#5874]
Currently factories ([`man_made=works`](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dworks)) are shown with a little chimney icon. I think a small factory icon would be more appropriate.

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/d8e76e9a-cb8a-447b-87e8-1390390f5ff4" width="375"/>

**Comment by dvdmrtnz** [comment]
Something like this:

![](https://upload.wikimedia.org/wikipedia/commons/a/a2/Factory.svg)

https://wiki.openstreetmap.org/wiki/File:Factory.svg

**Comment by biodranik** [comment]
I rarely see fabrics with triangle roofs. Maybe a flat roof?

**Comment by dvdmrtnz** [comment]
> I rarely see fabrics with triangle roofs. Maybe a flat roof?

I think triangle roofs are the most symbolic thing of a factory icon. Just take a look at: https://commons.wikimedia.org/wiki/Category:Factory_icons

**Comment by Misalf-git** [comment]
The angled side of the saw-tooth roof is basically glass / windows to let in more daylight. Bad for room climate or noise but good for constructing things while inside and very iconic for factories.

**Comment by dvdmrtnz** [comment]
Proposal:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/56584b36-c5cf-4de8-ab93-dcde63a26ef1" width="35"/>

**Comment by RedAuburn** [comment]
> Proposal:
> <img alt="" width="35" src="https://user-images.githubusercontent.com/47610359/265278968-56584b36-c5cf-4de8-ab93-dcde63a26ef1.svg">

i like it 😊

**Comment by biodranik** [comment]
Maybe less details then, e.g. 2 triangles instead of 3?

**Comment by dvdmrtnz** [comment]
> Maybe less details then, e.g. 2 triangles instead of 3?

Okay. Here it is simpler. Only two triangles:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/11d78f76-8388-4288-a0fd-27d443c76803" width="36"/>
