### ISSUE TITLE
App Crashes when the "more..." Wikipedia Button is Clicked

### ISSUE THREAD

**Issue by ethical-haquer** [organicmaps/organicmaps#5875]
**Describe the issue**
Clicking "more..." to expand a Wikipedia description of a place crashes Organic Maps.

**Steps to reproduce**
1. Click on a place that has a Wikipedia page.
2. Click on the "more..." button under the description.
3. The app crashes instantly.

**Expected behavior**
I expect to see the full place description.

**Screenshots**
https://github.com/organicmaps/organicmaps/assets/141518185/1a36ac5a-c1d7-4f20-aae0-fadca9840a0d

**System information:**
 - Operating system and its version: Android 13, One UI 5
 - Organic Maps version: 2023.08.18-8-Google
 - Device Model: Samsung Galaxy A52 4G

**Additional context**
This problem also existed on the last release, 2023.07.13-10-Google. Before that I don't know. My device is rooted with Magisk as well, and has a lot of system apps disabled. I can also try with all apps enabled if needed.
[logs.zip](https://github.com/organicmaps/organicmaps/files/12481178/logs.zip)

**Comment by Jean-BaptisteC** [comment]
Please update your maps and check if you have crash

**Comment by biodranik** [comment]
@ethical-haquer You have uninstalled or disabled the webview component in your system, it is required to render HTML content in Organic Maps. Enable it back to fix the crash:

```
08-30 10:45:19.591 E/AndroidRuntime(16762): Caused by: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
```

**Comment by ethical-haquer** [comment]
> @ethical-haquer You have uninstalled or disabled the webview component in your system, it is required to render HTML content in Organic Maps. Enable it back to fix the crash:
> 
> ```
> 08-30 10:45:19.591 E/AndroidRuntime(16762): Caused by: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
> ```

Thanks for the reply! That was indeed what was causing it, re-enabling the disabled system apps resolved the issue.  I don't know how webview works :blush:, but is there a way to display that info without it? Like the way it's showed before clicking the "more..." button? Or at least just have it open in a normal browser? TIA.

**Comment by biodranik** [comment]
No, we need to render HTML. And opening a browser is a worse/slower UX.
