### ISSUE TITLE
[iOS] Unable to view traffic data

### ISSUE THREAD

**Issue by parski** [organicmaps/organicmaps#588]
When I press the traffic lights icon (which I assume means traffic data such as congestion, there are no labels in the UI, only icons) I expect to see traffic data along my navigation but instead I see an alert telling me to check my settings and connection. I have a connection and I don't see any traffic data related options in the settings.

![IMG_1077](https://user-images.githubusercontent.com/2445818/122009262-3151fd00-cdba-11eb-92d7-703c76f3dfc1.jpg)

**Comment by maciboy** [comment]
@parski Where did you find the traffic lights icon? It shouldn‘t be visible anymore, since the feature was (unfortunately) deprecated by Maps.me as well as OrganicMaps…

**Comment by parski** [comment]
@maciboy Ah, that's unfortunate.

The icon is located at the bottom when in navigation mode. Press the hamburger menu to reveal it.

![IMG_1078](https://user-images.githubusercontent.com/2445818/122030209-de824080-cdcd-11eb-8fbd-9f44fa66158b.jpg)

**Comment by maciboy** [comment]
Indeed, you are right! I see it, too, and I get the same error…
@biodranik or @rtsisyk I assume the icon should vanish ;)

Btw: Any ideas, where Maps.me got its Traffic information from and if there is a chance, to bring traffic back somewhen in the Future?
I found opentraffic.io as a provider, but the project might be dead…

**Comment by ioctl-user** [comment]
I am using latest version from F-Droid. There is no traffic button at all.

Is it expected?

**Comment by biodranik** [comment]
Sorry, as we did not sign any commercial agreement with proprietary traffic data providers, there is no traffic info in Organic Maps. We have removed this non-working button.

**Comment by dumblob** [comment]
Do you still plan to add support for traffic info based on open data many countries publish for free?

**Comment by dumblob** [comment]
Potentially related: https://github.com/organicmaps/organicmaps/discussions/4102
