### ISSUE TITLE
Inability to show addresses using addr:place and without street name

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#5890]
**Describe the issue**
Some addresses have no matching street, but are matched to a place. Either settlement or some part of a city.

See for example https://www.openstreetmap.org/way/54562560

**Steps to reproduce**
1. Go to https://www.openstreetmap.org/way/54562560 in organic maps
2. Tap on that building
3. Note that address is not shown

**Expected behavior**
Its address is shown on tapping like for `addr:housenumber`

**Screenshots**
I can provide if it is useful at all, but it is a bit annoying to make them transfer out of phone and add here

**System information:**
 - Operating system and its version: Android 10
 - Organic Maps version: 2023.08.18-8-Google
 - Device Model: Mi A2 Lite

**Additional context**
I tried to report search issues as advised by https://news.ycombinator.com/reply?id=37349352&goto=item%3Fid%3D37347447%2337349352 and found also this one

searching for such places is covered by https://github.com/organicmaps/organicmaps/issues/5307

I am guessing that it is confused by missing street name tag and unable to use addr:place, but not fully sure about it

**Comment by vng** [comment]
https://github.com/organicmaps/organicmaps/issues/5307

**Comment by matkoniecz** [comment]
added note that more advanced handling (searching such addresses) is covered by #3507
