### ISSUE TITLE
Add `cave_entrance` to list to add objects

### ISSUE THREAD

**Issue by simonschaufi** [organicmaps/organicmaps#5892]
**Is your feature request related to a problem? Please describe.**
Please add `cave_entrance` to the possible categories of things to add.

**Describe the solution you would like**
`cave_entrance` is available to be added to the map

**Describe alternatives you have considered**
- currently I create another object and change it in OSM which is bad

**Comment by biodranik** [comment]
Wow, interesting, are there many not added caves yet? Do you do it for fun or for work?

**Comment by simonschaufi** [comment]
Yes, there are still a lot of caves missing. I've added at least 5 in the past week. I do it for fun while I'm traveling through Vietnam currently.
