### ISSUE TITLE
omaps.app location sharing page contains escaped HTML tags

### ISSUE THREAD

**Issue by aabacchus** [organicmaps/organicmaps#5893]
Look at the page https://omaps.app/00 which is an example of the page linked when sharing your location from the app.

At the top, it says 'Shared via &lt;a href="https&colon;//organicmaps.app"&gt;Organic Maps&lt;/a&gt;', because the &lt;&gt; characters in your template have been escaped.

![Screenshot_20230901_141044](https://github.com/organicmaps/organicmaps/assets/43711769/50e7ee8f-0b7e-4137-8b7a-a8d0d2805fc6)

It should be 'Shared via <a href="https://organicmaps.app">Organic Maps</a>'.

**Comment by biodranik** [comment]
Thanks! Fixed!
