### ISSUE TITLE
2 specific tolls invisible to router

### ISSUE THREAD

**Issue by KronosTheLate** [organicmaps/organicmaps#5902]
**Describe the issue**
I have encountered 2 local toll stations that appear correct in OpenStreetMap data, but that do not appear to exist in OrganicMaps. The tolls are not indicated during routing, nor are they avoided when avoiding toll roads.

**Steps to reproduce**
Note that the tolls are indicated as bookmarks in the screenshots. 

The toll located at 58.884643, 5.61761 does not appear visible to the router:
![Screenshot_20230902-035721](https://github.com/organicmaps/organicmaps/assets/61620837/61fa3d80-e85b-4404-a5da-4ab2f4f7c3c0)
Despite looking good in OSM data:
```
charge:hgv=62 NOK/hour
charge:motorcar=25 NOK/hour
contact:website=https://ferde.no
direction=forward
end_date=2030
highway=toll_gantry
name=Fv. 374 Nordsjøveien, mot Nord - Sola flyplass
operator=Ferde AS - Bymiljøpakken Nord Jæren
ref:toll=906727233
start_date=2018
toll:disabled=no
```
Note that this one is in the forward direction, matching the directional arrows of the road when selected and the physical toll station.

Not does the toll at 58.888846, 5.627956:
![Screenshot_20230902-035916](https://github.com/organicmaps/organicmaps/assets/61620837/1613d032-de81-4885-8194-b686980e1283)
Again, despite looking good in OSM data
```
charge:hgv=62 NOK/hour
charge:motorcar=25 NOK/hour
contact:website=https://www.bompenger.no
end_date=2030
highway=toll_gantry
name=Fv. 509 Flyplassveien, mot Sørvest - Sola flyplass
operator=Ferde AS - Bymiljøpakken Nord Jæren
ref:toll=906727232
start_date=2018
toll:disabled=no
```
Note that this one is not directional, as it is on a one-way street.

**Expected behavior**
When a toll is passed, a symbol should appear, demonstrated below:
![Screenshot_20230902-034907](https://github.com/organicmaps/organicmaps/assets/61620837/2780f4e7-8990-4b2e-a6a3-fe1c5cd20996)

Additionally, they should be avoided when "avoid toll roads" is enabled.

The expected behaviour is found is found for all other toll stations I have seen and tested in the area, which are part of Bymiljøpakken Nord Jæren.

**Comment by RedAuburn** [comment]
Invisible: https://www.openstreetmap.org/node/479336940
working and avoided: https://www.openstreetmap.org/node/1205782314

the only difference is `direction=forward` on the invisible one

**Comment by KronosTheLate** [comment]
Found another one. 

Coordinates: 58.983494, 5.672474

Tags:
```
charge:hgv=62 NOK/hour
charge:motorcar=25 NOK/hour
contact:website=https://www.bompenger.no
end_date=2030
highway=toll_gantry
name=E 39 Tastatorget, mot Øst - Ytre snitt nord
operator=Ferde AS - Bymiljøpakken Nord Jæren
ref:toll=906727257
start_date=2018
toll:disabled=no
```

**Comment by KronosTheLate** [comment]
Found a fourth one. 

Coordinates (approx): 58.869362, 5.726908

Tags:
```
charge:hgv=62 NOK/hour
charge:motorcar=25 NOK/hour
contact:website=https://ferde.no
direction=forward
end_date=2030
highway=toll_gantry
name=Dyre Vaas vei, mot Sør - Sandnes sentrum
operator=Ferde AS - Bymiljøpakken Nord Jæren
ref:toll=906727241
start_date=2018
toll:disabled=no

```

**Comment by KronosTheLate** [comment]
Fifth:
```
charge:hgv=62 NOK/hour
charge:motorcar=25 NOK/hour
contact:website=https://www.bompenger.no
end_date=2030
highway=toll_gantry
name=Fv. 443 Forusbeen, mot Øst - Forus
operator=Ferde AS - Bymiljøpakken Nord Jæren
ref:toll=906727247
start_date=2018
toll:disabled=no
```

**Comment by vng** [comment]
We can add toll_gantry to the map like toll_booth.
But for the correct routing avoid or notifications, the correspondent ways should also be tagged as tool=yes
https://wiki.openstreetmap.org/wiki/Tag%3Ahighway%3Dtoll_gantry
```
The way that the node is placed on must also be tagged with [toll](https://wiki.openstreetmap.org/wiki/Key:toll)=yes on any applicable road segments.
```

**Comment by KronosTheLate** [comment]
So the most apropriate fix would be to tag the road on which the toll is located with `toll=yes`? If the road has parts that can be used without hitting the toll, would the router still avoid that segment completely due to that tag? If yes, should a new segment be created to avoid that behaviour?

**Comment by vng** [comment]
The best way here is to connect with local OSM mappers. There are several possible options like (my assumptions):
- maybe all (major) roads in Norway are tolled, so mappers don't bother to tag them as toll
- maybe roads with specific refs are tolled always
- maybe these roads are tolled for tourists (foreigners) only, so mappers don't map them as toll
- all appropriate roads should be tagged as toll=yes
- tag only some segments where toll_booth is actually located. It also will be enough for routing algorithm to avoid this particular segment (and all road if there are no other ways to pass - only this segment)

**Comment by KronosTheLate** [comment]
To conclude, the issue is with the OSM data, not OM routing? If yes, then this issue should be closed. The discussion has been immensely useful though
