### ISSUE TITLE
Cant build the project on android studio 

### ISSUE THREAD

**Issue by RohanTemgire** [organicmaps/organicmaps#5933]
**Describe the issue**
Please write here a clear and concise description of what the bug/issue is about.
I tried to build the project following all the steps but still i get two errors
1: where my git is install in D: drive and not in C
2: it says "Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0."

![image](https://github.com/organicmaps/organicmaps/assets/56552357/d739fd5d-ee85-4da4-8b88-4dd8554bcdf9)

**Comment by Jean-BaptisteC** [comment]
Maybe update path of Git in Android Studio settings
Second error can be ignore
