### ISSUE TITLE
[beta] public bath, swimming

### ISSUE THREAD

**Issue by j13m126** [organicmaps/organicmaps#5945]
**Describe the issue**
1. Public baths with saunas (sauna=yes) are shown as saunas.
2. public baths are currently ranked lower than sport

**Expected behavior**
ad 1: Public baths should be ranked higher than saunas.
ad 2: public baths should be ranked higher than sport imo.

**Screenshots**
ad 1&2: [Therme Laa](https://www.openstreetmap.org/way/31827033) ![Screenshot_20230905-120415](https://github.com/organicmaps/organicmaps/assets/7961926/3d6270d7-c794-4a4b-ac88-dcb060b290d8)

**System information:**
OM version 2023.09.05-12-Google-beta

**Comment by Jean-BaptisteC** [comment]
CC @dvdmrtnz
