### ISSUE TITLE
Generic "craft=*" icon

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#5950]
>Do you have an idea for a generic "craft=" icon? The current "stopping palm" icon is a terrible mismatch :)

_Originally posted by @pastk in https://github.com/organicmaps/organicmaps/issues/5925#issuecomment-1706487236_

**Comment by dvdmrtnz** [comment]
For reference. Current craft icon is:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/84c24cd3-590a-4cd3-8f5b-bd4430f1a9a1" width="36"/>

**Comment by dvdmrtnz** [comment]
An idea for a generic craft=* icon could be a hammer or some other tool. However current hardware store icon is a hammer:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/6b730ff5-690f-4419-a769-6620142ecb17" width="36px"/>

**Comment by pastk** [comment]
There are many crafts that have nothing to do with hammers, e.g. craft-beekeeper/brewerey/photographer :)

The idea with a hand is good (something done by hands, small scale labour), but the current implementation is bad :)

**Comment by dvdmrtnz** [comment]
* Related to https://github.com/organicmaps/organicmaps/issues/2748

**Comment by patepelo** [comment]
I like the hand to represent this, but I would rotate it so it doesnt get confused with a stop sign. 

![image 9](https://github.com/organicmaps/organicmaps/assets/23003127/4019d1f7-f452-4522-a7b8-0df34dfffb5f)

**Comment by patepelo** [comment]
Related to #7804

**Comment by patepelo** [comment]
> For reference, current generic craft icon is:
> <img alt="" width="36px" src="https://private-user-images.githubusercontent.com/47610359/265782240-84c24cd3-590a-4cd3-8f5b-bd4430f1a9a1.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjY2MDIsIm5iZiI6MTcxMjgyNjMwMiwicGF0aCI6Ii80NzYxMDM1OS8yNjU3ODIyNDAtODRjMjRjZDMtNTkwYS00Y2QzLThmNWItYmQ0NDMwZjFhOWExLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA5MDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMGI1YjhiYTIwOTk0MGY1N2JkYmRlZDdjNjEwZGY1MDllNmI3Mjg0ZDIzNTBiM2EwNzA2YjViYzEzMzc4ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uoa-pEOsNzbvc8b5eA83RPIXvPUvrxRv07KBNnxJtEU">

Was this the case before? I have check it now and currently craft=* is shown without icon as "amenity". So it isn't supported.

On the contrary, the vertical "stop" hand is used in Tatto Parlor which isn't very intuitive.

IMO, we should redesign tatto parlor for I which I would create a new issue and take the hand for craft.

WDYT? @organicmaps/styles

**Comment by pastk** [comment]
> Was this the case before? I have check it now and currently craft=* is shown without icon as "amenity". So it isn't supported.
> 

You're right, the icon is assigned to `craft=*` in style files, but there is no actual `craft` OM type (like a `shop`), i.e. its not mapped.

**Comment by patepelo** [comment]
> I like the hand to represent this, but I would rotate it so it doesnt get confused with a stop sign.
> 
> ![image 9](https://private-user-images.githubusercontent.com/23003127/273139891-4019d1f7-f452-4522-a7b8-0df34dfffb5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NTM2MDcsIm5iZiI6MTcxMzY1MzMwNywicGF0aCI6Ii8yMzAwMzEyNy8yNzMxMzk4OTEtNDAxOWQxZjctZjQ1Mi00NTIyLWE3YjgtMGRmMzRkZmZmYjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDIyNDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjOWZiNDRkOGJjNjY3ZDQ3MWQwOTllZmVlZWJhYzdiMDdkY2U0MmYzNzYxZmNiNWUxYmU4MDljOTY3OTc3YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WNTmfjZe02mcfm1fFQ3snmvIQFpbQO0ECH2FCIviSl4)

Does someone have a better idea for the universal craft icon? Are we ok if we introduce the hand before (if at all) we change the tattoo parlos icon?
