### ISSUE TITLE
routing choosing longer route over a direct road

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#5956]
OSRM & GraphHopper build the same route, only Valhalla seems to build the correct one. (green in the image)

map data: 230901 

I have since added `sidewalk=*` tags in OSM to try and fix it, but it still hasn't fixed OSRM & GraphHopper. it's still very possible it's an OSM data issue though

<img src="https://github.com/organicmaps/organicmaps/assets/26939824/50db4dd7-4883-4ff4-b1db-9433ab2f0bfb" width="400px" />

Route in OSM: https://www.openstreetmap.org/directions?engine=fossgis_valhalla_foot&route=51.4556%2C0.0115%3B51.4666%2C0.0084#map=16/51.4611/0.0100

**Comment by RedAuburn** [comment]
Viktor, maybe it would be worth writing a short page on how you debug the routing? There are a lot of routing issues open and I wish we could help more with debugging them 😅

**Comment by janusbenissa** [comment]
It looks you add the sidewalk yesterday?
So you have to wait until OM update the map.
Same for OSRM & GraphHopper

**Comment by RedAuburn** [comment]
https://github.com/graphhopper/graphhopper/issues/2878

Had the same issue with Graphhopper, there it's caused by ranking down `highway=secondary` even for pedestrian routing, and even with `sidewalk=both`. 

@vng does OM do the same?

**Comment by RedAuburn** [comment]
> It looks you add the sidewalk yesterday? So you have to wait until OM update the map. Same for OSRM & GraphHopper

it still reproduces with a fresh map generation in OM, and still in Graphhopper & OSRM

**Comment by vng** [comment]
- sidewalk=both should be enough for OM, to prioritize the road.
- We have a bunch of experimental changes in the generator branch (for routing), so your local generations may give some different results
- Please, check after the new data snapshot will be available

**Comment by RedAuburn** [comment]
<img width="400px" src="https://github.com/organicmaps/organicmaps/assets/26939824/2558430f-b9c6-4ab5-8b89-a7593d2e0893"/>

routing is fixed with the latest data (added `sidewalk=both`) 👍
