### ISSUE TITLE
2023.08.18-8-FDroid and 2023.08.18-8-Google behave differently/are different

### ISSUE THREAD

**Issue by caluml** [organicmaps/organicmaps#5961]
I am trying to track down an issue, and have noticed that the two versions behave differently on startup.

Google opens the world map, and starts trying to download the local map for me (and fails - this is the problem I am investigating).

FDroid opens, and shows a screen saying I need to download the world map which will take 50MB of storage.
It offers me an checkbox to include the local map to my area, and has a blue download button at the bottom.

Both versions of the app immediately fail to download any maps (although my partner's phone can download the maps fine, so it's not the internet connection or a problem with the app).

I raise this as a bug in case you aren't aware that the two versions of the app are different/behaving differently.

I will raise a bug about the failure to download (with logcat output shortly)

**Comment by RedAuburn** [comment]
The different behaviours are intentional, the FDroid build doesn't include the world map in the app download, whereas the GPlay build does. This is why FDroid has an additional screen :)

for the download failure: the CDN seems to be up, so logs would indeed be helpful 👍

**Comment by caluml** [comment]
Aah, that explains it then.
I assumed that because the version number was the same, the APKs would be identical builds.

I've investigated and solved the download issue at https://github.com/organicmaps/organicmaps/issues/5962

Thanks, and congrats on a very nice app btw.
