### ISSUE TITLE
App fails to download initial maps if certificate authority is disabled

### ISSUE THREAD

**Issue by caluml** [organicmaps/organicmaps#5962]
Actual:
If the CA "Internet Security Research Group, ISRG Root X1" is disabled, the app fails to download maps due to 
`javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

Expected:
While this is expected behaviour, perhaps failures to download could display an error with a little more explanation about the problem - maybe the first line of the stacktrace? This would give the user an idea about what the problem is - read timedout, no such route, certificate problems

I have raised this bug in case someone else searches for it in the future.

**Comment by biodranik** [comment]
@caluml why did you disable root CA? Is it easy to do for an average Android user?

**Comment by RedAuburn** [comment]
Is it easy to do for an average Android user?

technically yes, it's accessible in the settings. i don't think many people would mess with it though

**Comment by RedAuburn** [comment]
> I have this error on an old Android 7 phone I just reset. I the phone is probably too old to have the right root certificate. I tried adding the certificate as a user certificate, but it doesn't seem to work.

It could be due to the issue fixed in https://github.com/organicmaps/organicmaps/pull/8754. What version do you have installed?
@biodranik the latest release should have this patch, right?

**Comment by biodranik** [comment]
This one should be fixed, as the cert is now embedded into the apk. @raphj did you install the latest Organic Maps version from Google Play or from GitHub?

For some reason, FDroid update wasn't built from the release branch with tag 2024.07.27-8-android
