### ISSUE TITLE
Snap ruler to user marks

### ISSUE THREAD

**Issue by strump** [organicmaps/organicmaps#5966]
**A problem:**
1. Start building ruler route
2. Tap on a user mark

Actual result: Ruler route is continued to some point near user mark

**Solution:**
Best option is to snap ruler point to the user mark.

**Comment by hoizan** [comment]
My 2 cents. Does it not somehow misinterprete user intention to do a survey measurement near a bookmark, but not to the actual bookmark? Perhaps, it's better to prompt user for confirmation?
