### ISSUE TITLE
Route uses wrong ramp then makes U-Turn on an interstate

### ISSUE THREAD

**Issue by ryukoposting** [organicmaps/organicmaps#5983]
**Describe the issue**

Heading west on I-94 in northwest Indiana, just after taking exit 16 Organic Maps produces a bizarre route that takes the wrong ramp, then tells you to make a U-turn in the middle of an interstate. This U-turn is illegal and you'd be driving through a ditch full of grass. 

**Steps to reproduce**

1. Open Organic Maps
2. Create a route from "Michigan City Municipal Airport, US 20, Michigan City, LaPorte County, Indiana, 46360, United States" to "Gary/Chicago International Airport, 6001, Airport Road, Gary, Lake County, Indiana, 46406, United States"
3. Zoom in on the interchange near 41.592, -87.232
4. See incorrect ramp selection, followed by a U-turn on the ITR (I-90)

**Expected behavior**

Organic Maps' route should match the route generated by OSM's web ui, taking the correct ramp to merge onto I-90 heading west.

**Screenshots**

Here is a screenshot of Organic Maps' incorrect route. Notice how, as the route heads north, it takes the right side of the fork, merges onto the ITR heading east, then quickly makes a U-turn to head west:

![organic-bad-route](https://github.com/organicmaps/organicmaps/assets/44929006/6b57573c-8c64-4091-9052-32ce5c34fe16)

Here is the correct route, produced by OSM with the same starting point and destination. Notice how it takes the left side of the fork, merging onto the ITR heading west:

![osm-correct-route](https://github.com/organicmaps/organicmaps/assets/44929006/7e0f6514-d2ba-4821-83c5-20ecbc2355b2)

**System information:**
 - Operating system and its version: Android 8.0
 - Organic Maps version: 2023.08.18-8-Google
 - Device Model: LG V35

**Other Info**

Thankfully, I knew where I was going and ignored Organic Maps' directions here. I have used OSM for ~1000 miles of driving, and it has worked beautifully everywhere except this one interchange.

**Comment by janusbenissa** [comment]
Looks like OM is using the emergency access https://www.openstreetmap.org/way/1186446719

**Comment by map-per** [comment]
Looks like `access=emergency` is a tagging mistake in the OSM database (see: https://wiki.openstreetmap.org/wiki/Key:access#Possible_tagging_mistakes). `access=no` + `emergency=designated` would be better here.

With 4572 uese `access=emergency` is in widespread use though, so maybe this can be replaced with `access=no` in replace_tags.txt.

**Comment by janusbenissa** [comment]
Solved in OSM

**Comment by RedAuburn** [comment]
> With 4572 uese `access=emergency` is in widespread use though, so maybe this can be replaced with `access=no` in replace_tags.txt.

https://taginfo.openstreetmap.org/keys/access#values
looks like we should also handle `access=military` (10,530 uses)

**Comment by ryukoposting** [comment]
It seems like my phone is still giving me the same, incorrect route. Do I need to re-download map data for the changes to take effect?

**Comment by janusbenissa** [comment]
You have to wait for a new map update, this can take a couple of weeks. (max)

**Comment by biodranik** [comment]
This issue is fixed in the latest beta, with the fresh, fixed OSM maps data. Stay tuned for the upcoming public release!

**Comment by RedAuburn** [comment]
this specific case is now fixed, but we should really properly handle `access=emergency`, `access=military`, & `highway-service-emergency_access` in code

**Comment by matkoniecz** [comment]
This bug is mentioned in https://hardfault.life/p/organic-maps-review and https://news.ycombinator.com/item?id=37592712 (I hope that it is OK to link such things, let me know if not)
