### ISSUE TITLE
[ios] Add a tile/link to a POI facebook page

### ISSUE THREAD

**Issue by FinixFighter** [organicmaps/organicmaps#600]
Hi! I noticed that lots of places don't even have a website but they do have a Facebook page. Having it displayed in the key information section of a POI could be very useful for both looking at place contacts, photos and more (especially considering that  OM doesn't have reviews yet). 
Possible scenarios:
1) A place has neither a website nor a facebook page 
2) A place has a website but not a facebook page
3) A place doesn't have a website but has a facebook page 
4) A place has a website and a facebook page

The tags that OSM uses for facebook pages are
  - facebook=* https://wiki.openstreetmap.org/wiki/Key:facebook (used 20,000+ times)
  - contact:facebook=* https://wiki.openstreetmap.org/wiki/Key:contact:facebook (used 130,000+ times)
So a check on both the tags should be made to see if one of them is not empty.

The info contained in the tags can be of two types:
   - contact:facebook=https://www.facebook.com/FacebookUserName
   - contact:facebook=FacebookUserName
   
The page will then open (when clicked) with the user preferred method (original facebook app, browser, SlimSocial etc...)

**Comment by rtsisyk** [comment]
Definitely makes sense. Facebook and Instagram are now more popular than web-sites.

**Comment by strump** [comment]
Looks like this issue duplicates #1016 "Display social network contact links for POIs".

**Comment by FinixFighter** [comment]
This has been implemented in version 2021.10.07-7. Closing. Great work!

**Comment by FinixFighter** [comment]
> Wait! It still needs to be added in iOS :) See #1196 for more details.

Oops, sorry!
