### ISSUE TITLE
Pedestrian Routing Issue with 

### ISSUE THREAD

**Issue by derickr** [organicmaps/organicmaps#6008]
**Describe the issue**
I was trying to route from one place to another, but the router send me the long way around, which wasn't needed. 

**Steps to reproduce**
1. Navigate to `51°33'44.08"N, 01°0123'55.89"W`
2. Click on 'Route From.'
3. Navigate to `51°3335'08.02"N, 01°24'32.89"W`
4. Click on "Route To"

**Expected behaviour**
 see that the route takes you through East Lockinge, instead of the footpath leading straight to where it says "B4494".

**Screenshots**
![Screenshot of too long route](http://derickrethans.nl/files/dump/Screenshot_20230912-121202_OrganicMaps.jpg)

**System information:**
Not relevant as it's a data issue.

**Additional context**
Project OSRM's route does handle this: https://map.project-osrm.org/?z=14&center=51.573522%2C-1.418953&loc=51.562932%2C-1.398997&loc=51.586057%2C-1.409254&hl=en&alt=0&srv=2

**Comment by RedAuburn** [comment]
i'm able to generate the correct route, but get the incorrect route with the "avoid unpaved roads" routing option enabled. we need to make routing options depend on the type of routing, as it was likely enabled for vehicle routing 👍

**Comment by derickr** [comment]
I can confirm that by turning off that setting, it creates the right route.

Feet don't need paved roads :-)

**Comment by RedAuburn** [comment]
> I can confirm that by turning off that setting, it creates the right route. Feet don't need paved roads :-)

Agreed :) it's been discussed before to implement per routing-profile settings instead of global, but there wasn't an actual issue opened yet. Now opened https://github.com/organicmaps/organicmaps/issues/6010 👍

**Comment by muralito** [comment]
> I can confirm that by turning off that setting, it creates the right route. Feet don't need paved roads :-)
Your assumption is not always true. For example, when it's raining people could prefer a paved road, because if they use the unpaved ones they ended covered by mud.
