### ISSUE TITLE
[styles] place=square icon

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#6013]
Coming from https://github.com/organicmaps/organicmaps/issues/4858, currently the [`place=square`](https://wiki.openstreetmap.org/wiki/Tag:place=square) icon is the same as the  [`tourism=artwork`](https://wiki.openstreetmap.org/wiki/Tag:tourism=artwork) and [`tourism=attraction`](https://wiki.openstreetmap.org/wiki/Tag:tourism=attraction) icons:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/efdf6ece-b0b4-4180-b2ba-43d7095a254c" width="36"/>

I think that we can keep the star icon for the `tourism=attraction` features and try to find some new icons for `place=square`.

**Comment by dvdmrtnz** [comment]
Some ideas:

A gazebo icon:

![](https://github.com/organicmaps/organicmaps/assets/47610359/35eb47a8-3b19-496e-a6ca-1fabd7e0d713)

--

An old streetlight icon:

![](https://github.com/organicmaps/organicmaps/assets/47610359/08c0b4cb-7ff0-448d-8fe2-bc7131259ca2)

--

An obelisk icon:

![imagen](https://github.com/organicmaps/organicmaps/assets/47610359/6bc61f1a-f564-4b33-8173-71469c220f9e)

**Comment by map-per** [comment]
I think an Icon doesn't really make sense for squares. I would use no Icon and render the label similar to e.g. place=locality.

**Comment by j13m126** [comment]
A gacebo is not a good idea imo, as it might be misunderstood as a shelter. 
But it could be used for an actual shelter (shelter:type=gacebo)

**Comment by euf** [comment]
Definitely no icon is needed for a square. Additionally, many squares have some landmark near the center, like a fountain or a monument. These features are more prominent physical structures, and they do have an icon.

**Comment by pastk** [comment]
Agreed, no need for an icon.

I think the star icon was used initially because quite often squares are touristic attractions too.
But the ones that are actually attractions should be tagged as such explicitly I think.
