### ISSUE TITLE
Fontsize

### ISSUE THREAD

**Issue by RJGhugo** [organicmaps/organicmaps#6021]
Zooming inside a map does not scale the font up for better visibility.

![100m](https://github.com/organicmaps/organicmaps/assets/41795683/6e889c2e-d7cb-41a9-9e90-c3b2f2d22d65)
![200m](https://github.com/organicmaps/organicmaps/assets/41795683/8db7c39a-21e4-444a-9747-8786f1888b2c)

**Comment by pastk** [comment]
Why is it important to have big fonts at close zooms? What's the use case? Does the "Increase size for map labels" setting work for it?

**Comment by RJGhugo** [comment]
Thank you very much! "Increase szie for map labels"/"Schrift auf der Karte vergrössern" hilft.
