### ISSUE TITLE
Rename "Unknown Place" pin title

### ISSUE THREAD

**Issue by RicoElectrico** [organicmaps/organicmaps#6041]
It doesn't sound good in my opinion. If we can't reverse geocode a particular location for whatever reason, then "Dropped pin" like in Google Maps (e.g. in Polish: just "Pinezka") seems to be suitable.

**Comment by Misalf-git** [comment]
I agree. It sounds like an error message while nothing is wrong.
Maybe something like "Selected place" or "Marked location".

**Comment by RicoElectrico** [comment]
> Maybe something like "Selected place" or "Marked location".

Currently this name is taken as a default bookmark name. Which isn't to say it could change to "Bookmark" if you try to save it.

**Comment by biodranik** [comment]
I remember we used Dropped Pin in MapsWithMe. If you check git log, you may find the reason of its renaming. 

What I don't like is that a new entity "pin" is introduced when we already have "bookmark". 

As the text name represents the address, an unknown place sounds more logical and clear. 

Maybe you'll have other ideas.

**Comment by pastk** [comment]
> I agree. It sounds like an error message while nothing is wrong. Maybe something like "Selected place" or "Marked location".

+1

But we need to think what name to use when saving as a bookmark.

**Comment by pastk** [comment]
> 
> As the text name represents the address, an unknown place sounds more logical and clear.

Actually there is no hint which suggest it represents an address.
Usually there is a POI name in the PP title. An address appears there only if there is nothing else to display.

So a "Selected place" is very logical IMO.

**Comment by RedAuburn** [comment]
"Saved Place" would make most sense imo

**Comment by biodranik** [comment]
1. Selected Place is not much better than Unknown Place. Unknown place at least consistently implies that its address is unknown.
2. If you bookmark this place, there will be confusion: bookmarks will have a "Selected Place" title. That is not good.

Let's focus on the context of the usage. Now user immediately sees and understands that a long-tapped place does not represent any object, and it does not have any address. If it's saved as a bookmark, it will be clear later that it was just a tap somewhere at an unknown place. 
"I don't like it" is not the best argument to introduce (potentially worse) change.

**Comment by pastk** [comment]
> Let's focus on the context of the usage. Now user immediately sees and understands that a long-tapped place does not represent any object, and it does not have any address.

Not really :)
I remember my first impression when I saw it was its some kind of an error.

And actually nothing hints it has anything to do with addresses. Users can learn it with time only by comparing to other long-tapped locations.

**Comment by biodranik** [comment]
That's the point. After some tapping you naturally learn it.

FYI: So far, in more than 10 years, users haven't complained about the Unknown place.

**Comment by Misalf-git** [comment]
> FYI: So far, in more than 10 years, users haven't complained about the Unknown place.

I count three complains right here allone. How many grandmas would have complained if they knew how to?

**Comment by pastk** [comment]
> That's the point. After some tapping you naturally learn it.

Yes, but its better when its intuitive from the very start :)

**Comment by pastk** [comment]
How about a very neutral "Map point"?

**Comment by biodranik** [comment]
> I count three complains right here allone. How many grandmas would have complained if they knew how to?

Don't forget about another side of any introduced change: Is it safe/ok to change something that works for hundreds of thousands of users for a long time if 3 users started to complain?

**Comment by Misalf-git** [comment]
I think it's safe to change this one, yes.

**Comment by meenbeese** [comment]
> How about a very neutral "Map point"?

I agree, this makes more sense and it is unlikely to create any confusion. It stays in the context and not references a place, bookmark, location, etc.

**Comment by pastk** [comment]
Or "A point on the map" is better from a language point of view?

**Comment by dvdmrtnz** [comment]
Why not simply set the lat lon coordinates as the title?

**Comment by meenbeese** [comment]
> Even better, a suggestion from a user: current date and time!
> 
> Coordinates are always visible anyway below the title.

I don't see how this provides any value to the user. Why would they want to check the date and time by long pressing somewhere? At least, "Dropped Pin" describes what the long press does. Correct me if I have misunderstood.

**Comment by pastk** [comment]
We have date + time used already as a bookmark title when "My Position" is saved. It provides information where a used had been at that time.

- if we use it for other bookmarks too then it might create confusion and a need to distinguish between saved "my positions" and just pins
- usefulness is questionable - a time when a user tapped at some place? (displaying bookmark creation/modification time is a good idea overall, but it shouldn't be in the title, but rather a small print somewhere)
- if a user long taps a spot and current date time is shown then it'll "freeze" (the time won't be updating unless we add some refresh timer etc.) which would create confusion; if it will be updating it'll attract attention unnecessarily

IMHO a plain text like "Map point" is the best solution so far.

**Comment by biodranik** [comment]
> I don't see how this provides any value to the user.

How do you think, why do users usually do long taps? What is one of the most popular use cases for the long tap? What's the next user's action after a long tap?

Note that long tap is extremely hard to discover, it is used mostly only by advanced/experienced users.

P.S. Explicitly storing the bookmark creation date may help in the future (AfAIR now the last modification date is stored in KML `<when>` tag). Displaying the last modification date may be also useful for bookmarks.

**Comment by pastk** [comment]
If there is a relevant argument "hidden" in your questions, then could you just lay it please?

I use long tap often to route to, to bookmark (an unmapped point or just a reference point for myself), to get to know a type of the feature at this point or a distance to it.. And I see very little value for the current date and time (sometimes could be good to know bookmark creation date), but I see issues with confusion it might cause, see my post above.

**Comment by biodranik** [comment]
You described well most of the cases. The displayed name is important in the case of saving it later in the bookmark.

Re: timestamp: to clarify, that was an idea from a user. I'm not insisting on it. I see that it can be implemented in a better way independently of the feature's name, by storing bookmark's creation time and displaying it when necessary.

**Comment by biodranik** [comment]
Why "Map Point", and not "Map Place", or "A place on the map"? Is the "Point" noun used anywhere else?

**Comment by pastk** [comment]
A "place" could be something rather large like an area, whereas a "point" is, well, an exact point :) with coordinates.
