### ISSUE TITLE
[ios] Fix section fonts in Settings

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6047]
Section is not readable in the dark mode:

![выява](https://github.com/organicmaps/organicmaps/assets/170263/9b87121a-d020-41d7-82c5-c98848bcd814)

It is also not visible/readable on M1/M2 arm Macs in light and dark modes:

<img width="1024" alt="выява" src="https://github.com/organicmaps/organicmaps/assets/170263/d0ddaf02-441e-40c2-a798-608c1813e18c">

**Comment by dhruvinjs** [comment]
hey can i take up this issue

**Comment by Jean-BaptisteC** [comment]
PR was already created to fix problem

**Comment by meenbeese** [comment]
This be closed with #6087 @Jean-BaptisteC
