### ISSUE TITLE
Generate map give issue with borders

### ISSUE THREAD

**Issue by dash7ou** [organicmaps/organicmaps#6049]
when run /omim-build-release/generator_tool --threads_count=2 --data_path=/maps_build/2023_09_16__17_41_42/intermediate_data --intermediate_data_path=/maps_build/2023_09_16__17_41_42/intermediate_data --cache_path=/maps_build/2023_09_16__17_41_42/intermediate_data --osm_file_type=o5m --osm_file_name=/maps_build/2023_09_16__17_41_42/planet.o5m --node_storage=map --user_resource_path=/organicmaps/data --dump_cities_boundaries=true --cities_boundaries_data=/maps_build/2023_09_16__17_41_42/intermediate_data/cities_boundaries.bin --generate_features=true --isolines_path= --generate_packed_borders=true

issue details: 
LOG TID(1) INFO     1.96e-05 generator/intermediate_data.cpp:188 MapFilePointStorageReader(): Nodes reading is started
LOG TID(1) INFO       1.6767 generator/intermediate_data.cpp:205 MapFilePointStorageReader(): Nodes reading is finished
LOG TID(1) INFO      1.67732 Offsets reading is started for file /maps_build/2023_09_16__17_41_42/intermediate_data/ways.dat.offs
LOG TID(1) INFO       1.7258 Offsets reading is finished
LOG TID(1) INFO      1.72634 Offsets reading is started for file /maps_build/2023_09_16__17_41_42/intermediate_data/relations.dat.offs
LOG TID(1) INFO      1.72752 Offsets reading is finished
LOG TID(1) INFO      1.72766 Offsets reading is started for file /maps_build/2023_09_16__17_41_42/intermediate_data/nodes.dat.id2rel
LOG TID(1) INFO      1.72897 Offsets reading is finished
LOG TID(1) INFO      1.73036 Offsets reading is started for file /maps_build/2023_09_16__17_41_42/intermediate_data/ways.dat.id2rel
LOG TID(1) INFO      1.75073 Offsets reading is finished
LOG TID(1) INFO      1.75121 Offsets reading is started for file /maps_build/2023_09_16__17_41_42/intermediate_data/relations.dat.id2rel
LOG TID(1) INFO      1.75155 Offsets reading is finished
LOG TID(1) INFO       1.7519 generator/borders.cpp:184 LoadCountriesList(): Loading countries.
TID(1) ASSERT FAILED
generator/borders.cpp:154

CHECK(currentPolygon.IsValid()) Invalid region in /maps_build/2023_09_16__17_41_42/intermediate_data/borders/Macedonia.poly
 0# 0x0000562B4C55AA28 in /omim-build-release/generator_tool
 1# 0x00007F73A843C4B0 in /lib/x86_64-linux-gnu/libc.so.6
 2# pthread_kill in /lib/x86_64-linux-gnu/libc.so.6
 3# gsignal in /lib/x86_64-linux-gnu/libc.so.6
 4# abort in /lib/x86_64-linux-gnu/libc.so.6
 5# 0x0000562B4C4E3049 in /omim-build-release/generator_tool
 6# 0x0000562B4C6A9DE2 in /omim-build-release/generator_tool
 7# 0x0000562B4C6AB21C in /omim-build-release/generator_tool
 8# 0x0000562B4C70CC14 in /omim-build-release/generator_tool
 9# 0x0000562B4C5C58FE in /omim-build-release/generator_tool
10# 0x0000562B4C5CC454 in /omim-build-release/generator_tool
11# 0x0000562B4C546375 in /omim-build-release/generator_tool
12# 0x0000562B4C52F1A8 in /omim-build-release/generator_tool
13# 0x00007F73A8423A90 in /lib/x86_64-linux-gnu/libc.so.6
14# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
15# 0x0000562B4C544535 in /omim-build-release/generator_tool
Aborted (core dumped)

**Comment by map-per** [comment]
Did you see the documentation in [tools/python/maps_generator/README.md](https://github.com/organicmaps/organicmaps/blob/adb93c6f499ca1e2985cc475058f3c83b0c293d1/tools/python/maps_generator/README.md)?

**Comment by dash7ou** [comment]
@dash7ou LOL! sure I am doing the steps :)

**Comment by pastk** [comment]
`maps_build/2023_09_16__17_41_42/intermediate_data/borders/Macedonia.poly` is supposed to be a symlink to `data/borders/Macedonia.poly` in the repo.
Please check its linked correctly.
Maybe you use Windows/WSL and didn't enable symlinks?

**Comment by dash7ou** [comment]
@pastk nvm After I generated the map with mwm format and uploaded it to my server to let the app download my custom mwm file for the specific country it failed why? is there any clear reason for this ? but when I add the file directly to the app files it works and shows my changes successfully.

**Comment by pastk** [comment]
What was the error and how did you point the app to your server?

Might be because of mwm checksum mismatch (cheksums are stored in data/countries.txt).

**Comment by dash7ou** [comment]
@pastk it gives me this error
LOG TID(1) WARNING   353.709 platform/http_thread_qt.cpp:98 OnHeadersReceived(): Http request to /maps/230814/Palestine.mwm aborted - invalid Content-Range: 18461748

**Comment by dash7ou** [comment]
@pastk I think this error related to changes in file size (Mismatched File Size) how can I fix this issue ?
