### ISSUE TITLE
Open Hours

### ISSUE THREAD

**Issue by RJGhugo** [organicmaps/organicmaps#6066]
Shop opens (Monday-Friday): 10h
Shop closes (Monday-Friday): 18:30h

But between 13:45-14:30 they are making a brake.

![Screenshot_20230919_094249_Organic Maps](https://github.com/organicmaps/organicmaps/assets/41795683/dc4019da-9a24-419f-a2df-74fa88c4b1f9)
![Screenshot_20230919_094318_Organic Maps](https://github.com/organicmaps/organicmaps/assets/41795683/fb2d478a-81d3-4382-b639-90c5e64352d7)

**Comment by dvdmrtnz** [comment]
Related to https://github.com/organicmaps/organicmaps/issues/5560

**Comment by strump** [comment]
@RJGhugo which POI is this? Could you please share coordinates or OSM ID?

**Comment by dvdmrtnz** [comment]
It seems that the opening hours break info was added to the POI just yesterday. Before, the opening hours tag didn’t have it. 

You will have to wait for the next map update to be able to see it in the app.

**Comment by dvdmrtnz** [comment]
This is how it will look after map data update:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/6c9ee8b4-cfa2-4fdb-9a72-52f8a9ca535b" width="310"/>

**Comment by RJGhugo** [comment]
Thanks!
