### ISSUE TITLE
[android] Location refresh interval is not updated when switching between FOLLOW / NOT FOLLOW modes

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#6073]
Reported by @vng

**Steps to reproduce**

1. Start the app
2. Change location mode to "FOLLOW_AND_ROTATE" or "NOT_FOLLOW"
3. LocationHelper will be restart with refresh interval = 3000 ms
4. Switch location mode to "FOLLOW"
5. LocationHelper will continue to use 3000 ms refresh interval instead of upgrading to 1000 ms for "FOLLOW" mode
6.  Switch to some other app and back
7. LocationHelper will be restarted with refresh interval = 1000 ms

**Expected behavior**

Location refresh interval should be updated when switching between FOLLOW_AND_ROTATE -> NOT_FOLLOW -> FOLLOW modes.

**Comment by biodranik** [comment]
@rtsisyk PTAL

**Comment by Jean-BaptisteC** [comment]
Fixed by #6133 ?

**Comment by rtsisyk** [comment]
This should be fixed by #6133.
