### ISSUE TITLE
Some metro icons don't show up in Lisbon

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#6082]
In Lisbon, after #3514, some metro stations and entrances don't have the custom icon as expected. I checked OSM tags and couldn't find anything apparently there. Is there something missing?

Some examples: [Baixa-Chiado](https://www.openstreetmap.org/way/898560648), [Restauradores](https://www.openstreetmap.org/way/695510929).

Didn't check all, but is it because these stations are drawn as ways, and not nodes?

Everything seems fine at [Subway Validator](https://cdn.organicmaps.app/subway/portugal.html).

**Comment by RedAuburn** [comment]
>  but is it because these stations are drawn as ways, and not nodes?

yes :/
https://github.com/organicmaps/organicmaps/issues/4120

**Comment by matheusgomesms** [comment]
Thanks for the feedback, @RedAuburn!
