### ISSUE TITLE
[Android][beta] Notification stuck after navigation finished

### ISSUE THREAD

**Issue by Misalf-git** [organicmaps/organicmaps#6084]
**Describe the issue**
Navigated from A to B on foot with the phone / app active in my pocket (I did put it out now and then to see where I am).
After arrival, navigation mode ended, yet the notification is still active and not even dismissable.

**System information:**
 - Android 12 (crDroid 8.8)
 - Organic Maps version: 2023.09.19-15-Google-beta
 - Device Model: Samsung A20e

**Comment by rtsisyk** [comment]
Good catch! This issue will be fixed by #6086.
