### ISSUE TITLE
Pop up to continue to search location is visible after I deny to search location

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#6098]
**Steps to reproduce**
1. Start OM (Need Google Play Services Enabled)
2. Deny Google Play pop-up
3. Wait 1 minute -> Pop-up to continue to search location is visible

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.09.22-25-Web-debug
 - Device Model: Pixel 6

**Comment by biodranik** [comment]
@Jean-BaptisteC is it a regression?

@rtsisyk can you please fix it?

**Comment by Jean-BaptisteC** [comment]
First time detected here #4602 but never fixed

**Comment by rtsisyk** [comment]
> **Steps to reproduce**
> 
>     1. Start OM (Need Google Play Services Enabled)
> 
>     2. Deny Google Play pop-up
> 
>     3. Wait 1 minute -> Pop-up to continue to search location is visible
> 
> 
> **System information:**
> 
>     * Operating system and its version: Android 13
> 
>     * Organic Maps version: 2023.09.22-25-Web-debug
> 
>     * Device Model: Pixel 6

I will take a look. Thanks for reporting!

**Comment by rtsisyk** [comment]
This is the same issue as https://github.com/organicmaps/organicmaps/issues/1128#issuecomment-1784435190 (see the second comment).

**Comment by rtsisyk** [comment]
Actually, this issue is different from #1128, but I have fixed both via #6435. Ancient legacy native code that does weird things, unfortunately.

**Comment by rtsisyk** [comment]
I've created a dedicated fix for this issue. Please review #6466.
