### ISSUE TITLE
Wrong status on location button

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#6100]
**Steps to reproduce**
1. Start OM
2. Deny pop-up to start location
3. Touch button to start location -> location button has wrong status
Before starting location button has NOT_FOLLOW value when I start the location button switch to PENDING_POSITION and go back to NOT_FOLLOW

**Expected behavior**
Before starting location button has NOT_FOLLOW value when I start the location button switch to PENDING_POSITION

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.09.22-25-Web-debug
 - Device Model: Pixel 6

**Comment by biodranik** [comment]
@rtsisyk can you please check it out? It's a regression after location refactoring.
CC @vng

**Comment by rtsisyk** [comment]
> **Steps to reproduce**
> 
>     1. Start OM
> 
>     2. Deny pop-up to start location
> 
>     3. Touch button to start location -> location button has wrong status
>        Before starting location button has NOT_FOLLOW value when I start the location button switch to PENDING_POSITION and go back to NOT_FOLLOW
> 
> 
> **Expected behavior** Before starting location button has NOT_FOLLOW value when I start the location button switch to PENDING_POSITION
> 
> **System information:**
> 
>     * Operating system and its version: Android 13
> 
>     * Organic Maps version: 2023.09.22-25-Web-debug
> 
>     * Device Model: Pixel 6

Do you mean that the location has "crossed out" (NOT FOLLOW NO POSITION a.k.a "disabled":) icon and it switches to "locating" icon (PENDING) and then back to "crossed out" if permissions were rejected?

**Comment by Jean-BaptisteC** [comment]
Yes but switching between icons is very fast.
Make sense to switch to PENDING_POSITION icon after users allow location.

**Comment by rtsisyk** [comment]
I can't reproduce this issue.

[Screen_recording_20231101_074017.webm](https://github.com/organicmaps/organicmaps/assets/1799054/a265211b-dd51-4802-a664-77b32da886db)

**Comment by Jean-BaptisteC** [comment]
https://github.com/organicmaps/organicmaps/assets/87148630/21208a50-110c-4b01-9152-dab79fb015f2

**Comment by biodranik** [comment]
Thanks! @rtsisyk PTAL

**Comment by rtsisyk** [comment]
Yes, the location mode is switched to "PENDING POSITION" when the user clicks the button. The app starts Google Play Location provider. A microsecond later, the provider realized that it wants to show a dialog. The app switches location back to "NOT_FOLLOW" mode until the dialog is resolved. I don't see any issues here.

**Comment by Jean-BaptisteC** [comment]
Ok for your explanation, I close this issue
