### ISSUE TITLE
Allow to edit parkings number of places

### ISSUE THREAD

**Issue by williamdes** [organicmaps/organicmaps#6101]
I love this app!

That said editing is a bit like in maps.me and others, not very welcoming when you get into the details of OSM

For this request I would like to be able to edit parkings to add their capacity.

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking

https://wiki.openstreetmap.org/wiki/Key:capacity

I often see in France:
- capacity:disabled
- capacity:parent
- capacity:charging

It would be cool to have the 3 keys available to edit

Probably a lot of other nodes types should have wheelchair available to edit

And finally, I may do a new issue about this but do you think it's possible to not send edits to OSM immediately and keep using the same changeset?

**Comment by dvdmrtnz** [comment]
Related to:
* https://github.com/organicmaps/organicmaps/issues/5836
* https://github.com/organicmaps/organicmaps/issues/5015
* https://github.com/organicmaps/organicmaps/issues/3729
* https://github.com/organicmaps/organicmaps/issues/4805
* https://github.com/organicmaps/organicmaps/issues/2254

**Comment by Misalf-git** [comment]
> do you think it's possible to not send edits to OSM immediately and keep using the same changeset? 

If you're not logged in to OSM, your edits will still show on the map.
I don't use OMaps for editing and never log in but sometimes I create _edits_ to not pollute my view with bookmarks. Typing "?edits" in the search field will then display all pending edits.

**Comment by biodranik** [comment]
> And finally, I may do a new issue about this but do you think it's possible to not send edits to OSM immediately and keep using the same changeset?

Edits should be batched, they are usually sent to the server only when OM goes to the background or you are switching to another app. Can you please confirm whether batching is working or not in your case?

**Comment by williamdes** [comment]
> If you're not logged in to OSM, your edits will still show on the map.
I don't use OMaps for editing and never log in but sometimes I create edits to not pollute my view with bookmarks. Typing "?edits" in the search field will then display all pending edits.

I am logged in
Thank you for the hint !

> Edits should be batched, they are usually sent to the server only when OM goes to the background or you are switching to another app. Can you please confirm whether batching is working or not in your case?

I tried and I can confirm it works like described.
It would be cool to have some manual step to upload changes, because when you have multiple maps or have to copy a website link you will switch apps. And then do a batch for each attribute of the node in the worst case scenario.

**Comment by biodranik** [comment]
Introducing a delay may help here. Any other ideas to avoid manual actions?

**Comment by williamdes** [comment]
Maybe fixed by https://github.com/organicmaps/organicmaps/pull/7026
