### ISSUE TITLE
[android][auto] Determine the minimal minCarApiLevel that needs to be supported

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#6105]
https://github.com/organicmaps/organicmaps/pull/5998/files#r1325636446

**Comment by rtsisyk** [comment]
https://issuetracker.google.com/issues/301603467

**Comment by AndrewShkrob** [comment]
Min CarApiLevels in different apps:
| App | App Version | Min CarApiLevel |
|--------|--------|--------|
| 2GIS | 6.26.0.525.13 | 4 |
| OsmAnd | [master](https://github.com/osmandapp/OsmAnd/blob/b5697e08c14a04ee07ff1aece33fb3e073673959/OsmAnd/AndroidManifest.xml#L1155-L1157) | 1 |
| Mapbox SDK | [master](https://github.com/mapbox/mapbox-navigation-android/blob/e6249f9c0f02f8c3302def516ab0fd14199bc198/libnavui-androidauto/src/main/AndroidManifest.xml#L14-L16) | 3 |
| Yandex.Maps | - | N/A |
| MAPS.ME | - | N/A |

**Comment by AndrewShkrob** [comment]
We're aware that CarApiLevel depends on the AA app version, not on the head unit version. Currently, we support CarApiLevel >= 5.

I believe there's nothing more to address here. I'll proceed to close the issue.
