### ISSUE TITLE
Add possibility to go back to the app by the statut bar

### ISSUE THREAD

**Issue by tangsgod** [organicmaps/organicmaps#611]
The title say it all, could it be possible to add acces to the app by the statut bar while it is on ?

It could be very very usefull because for now, if we use other apps while using Organic Map we have to tap the bottom left square icon and find the gps window to go back on the road.

**Comment by Jean-BaptisteC** [comment]
Do you want just show a notification when app is background ?
Show notifications only to go back in app is useless, we have already issues to show routing in notification like other apps gps (Maybe we can implement go back to app in same time), can you check ?

**Comment by RedAuburn** [comment]
i think this has effectively been implemented now, with the navigation notification.
