### ISSUE TITLE
Use the same maps data folder as OsmAnd

### ISSUE THREAD

**Issue by Massedil** [organicmaps/organicmaps#612]
Hello,

I already use [OsmAnd](https://f-droid.org/fr/packages/net.osmand.plus/) and I have a folder on the external SD card with more than 3 Go of maps already downloaded.

I have seen in Organic Maps parameters that I can choose the folder to store maps.

Is it possible to add the ability to use the same folder as OsmAnd and share the same data for maps in order to save space on our devices ?

**Comment by stephan75** [comment]
So you assume that osmand and organicmaps have the same map file data format?

**Comment by biodranik** [comment]
No, it's not possible. We have incompatible maps data format.
