### ISSUE TITLE
Street search bad matches (Hungary sample)

### ISSUE THREAD

**Issue by grinapo** [organicmaps/organicmaps#6127]
**Describe the issue**
Search prefers non-relevant results, and street number completely pushes down correct one.

**Steps to reproduce**
1. Download Hungary
2. Search "Szank" (name of a village), it is found properly as a village.
3. Type space and "béke" (name of a street, means „peace” by the way), and the search finds a completely irrelevant poi 120 km away which doesn't match any of the terms, then second is a street with the same name from a very different city (no match again), 3rd is the correct match. 
4. Type space and "utca" („street” in Hungarian, part of the name), nothing changes. 
5. Then type a non-existing house number (say, 55) and the correct match is gone away way down there.

**Expected behavior**
Relevant results. :-)
Step 3 shall not list non-matching results as first.
Step 5 shall not bury correct result due to wrong or missing house number.

**System information:**
 - Operating system and its version: Android 12
 - Organic Maps version: 2023.08.18-8-google
 - Device Model: xiaomi 10tpro

**Additional context**
Sent from matrix ;-)

**Comment by vng** [comment]
Please, check the new update from September (available soon).
If the bug still exists:
- You have all Hungary downloaded, right?
- Tell us your approx viewport when searching

**Comment by grinapo** [comment]
> Please, check the new update from September (available soon). 

I will. Until then, not to keep you wondering:

>     * You have all Hungary downloaded, right?

Right.

>     * Tell us your approx viewport when searching

Far away. Possibly on or around Budapest. I was searching the route _target_, the far end.

**Comment by vng** [comment]
@grinapo Please, check on the latest app and map data. Looks like the streets ranking now is ok.
