### ISSUE TITLE
Passing loop at Cessnock

### ISSUE THREAD

**Issue by thisisthedogtor** [organicmaps/organicmaps#6129]
**Describe the issue**
The metro layer shows a passing loop at Cessnock station on the Glasgow Subway. However, this loop does not actually exist (see https://cartometro.com/cartes/metro-glasgow/).

**Steps to reproduce**
1. Activate the metro layer in the area of Glasgow, Scotland
2. Find Cessnock station

**Expected behavior**
There shouldn't be a passing loop.

**Screenshots**
[Screenshot_20230925-112908-201.png](https://github.com/organicmaps/organicmaps/assets/91873696/74f504fa-fb6e-4190-a25c-f7b4367fbcce)

**System information:**
 - Operating system and its version: Android 11
 - Organic Maps version: 2023.08.18-8-Google
 - Device Model: Moto G9 play

**Additional context**

**Comment by biodranik** [comment]
CC @alexey-zakharenkov

**Comment by alexey-zakharenkov** [comment]
@thisisthedogtor thank you for alertness. The Inner Circle line was missing a stop in OSM. Fixed in the changeset https://www.openstreetmap.org/changeset/141992721

Please check it again when the next app release is released.

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.03.18-5-Google version
