### ISSUE TITLE
[drape] Bad curly street drawing.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#6137]
Lombard Street in SF:

<img width="876" alt="Screenshot 2023-09-25 at 22 16 01" src="https://github.com/organicmaps/organicmaps/assets/175612/59d66935-2f82-4287-a6e3-4f7d08cb55cf">

This section is one Feature ..

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.03.18-5-Google version
