### ISSUE TITLE
include street names in voice guidance

### ISSUE THREAD

**Issue by TimMagee** [organicmaps/organicmaps#615]
Almost every navigation app in existence will say the name of the street that the user is supposed to turn on. Organic Maps does not do this.

Here is an example. If the user is coming up on a turn, and is supposed to turn right on Second Street in 900 feet, Organic Maps will state "In 900 feet, turn right". In order to find the name of the street, the user must look at the app and check the name of the street displayed at the top.

It would be of great benefit if the app stated, "In 900 feet, turn right on Second Street" so that the user would know what road to turn onto without having to look at the app.

**Comment by letkan** [comment]
> Almost every navigation app in existence will say the name of the street that the user is supposed to turn on. Organic Maps does not do this.
> 
> Here is an example. If the user is coming up on a turn, and is supposed to turn right on Second Street in 900 feet, Organic Maps will state "In 900 feet, turn right". In order to find the name of the street, the user must look at the app and check the name of the street displayed at the top.
> 
> It would be of great benefit if the app stated, "In 900 feet, turn right on Second Street" so that the user would know what road to turn onto without having to look at the app.

I would recommend street names as an option only, not a default,  from experience I can tell you that the pronunciation of street names in a language other then the local one is more annoyance then help.

**Comment by TimMagee** [comment]
Well, then lets make it the default if the language of the current region matches the language of the TTS engine. For example if I am navigating in the USA (where English is the primary language), and I am using English as my TTS language, street names will be on by default.

We could have them off be default if the primary language of the region does not match the TTS language. So, in my case if I switch to Spanish TTS, then street names would be off by default.

**Comment by zyphlar** [comment]
Additionally, exit numbers on motorways. A simple "take exit 54" greatly reduces the difficulty of using a GPS app, at least in America where every significant exit is consistently numbered with prominent signage. (The longer-form announcement for motorways would often omit the street name unless it's the only destination name, so "take exit 54 for/towards Seattle" or "take exit 65 for Fifth Street." Sometimes in interchanges both are supplied: "take exit 123, for I-10 towards Seattle" or surface streets: "take exit 12 for Main Street, Downtown Shops."

**Comment by MarcTheSpark** [comment]
Just to add another voice to this: I had been using OSMAnd and just find out about organic maps, so I downloaded it. It looks great, works great, but I was baffled by the lack of street names in navigation, which forced my to take my eyes off the road a bunch unnecessarily. I'm in the US, for context, and agree that this is an expected feature of a maps app in this region.

**Comment by sn0ot** [comment]
echoing @zyphlar 's [comment](https://github.com/organicmaps/organicmaps/issues/615#issuecomment-968237661)

> Additionally, exit numbers on motorways. A simple "take exit 54" greatly reduces the difficulty of using a GPS app, at least in America where every significant exit is consistently numbered with prominent signage.

Voice guidance saying "take exit 4B" is **absolutely necessary** in situations when multiple exists and are several hundred meters apart.

I've been screwed in similar situations to when, for example, **I need to take Exit 4B and just couple hundred meters before it is Exit 4A. I was approaching Exit 4A and the navigator gave me a heads up to "turn right" implying take Exit 4B and the confusion can send a worried driver swerving to not miss Exit 4A that is closer.** 

"turn right to Exit 4A" would be a sufficient start to address this issue and "turn right to Exit 4A, follow signs to Rt Blah" could be the end goal.

**Comment by tvld** [comment]
I drive a lot in Europe with Waze, real-time traffic is essential, but the English accent for Street names make it unusable. They only sound good with original language voice... Just to consider;))

**Comment by AntonM030481** [comment]
I believe that we can easily add voice for exit numbers and road numbers.
Since they usually consist from letters and digits, which are pronounced separately.
Note: in USA numbers of target roads at exit contain also directions at the end, like B2 North or X33 South.

Destination names and road names look like much more difficult to implement with reasonable quality.

**Comment by TheAdventurer64** [comment]
What steps need to be done in order for this feature to be added?

**Comment by TimMagee** [comment]
> What steps need to be done in order for this feature to be added?

Here is my personal opinion as to what needs to be done for this issue:

1. We need a new setting.
  - This setting will be located at Settings -> Navigation -> Voice Instructions.
  - It will be titled, "Say Street Names".
2. When this settings is set to on, the voiced navigation instructions need to include Street Names.

**Comment by TheAdventurer64** [comment]
> > What steps need to be done in order for this feature to be added?
> 
> Here is my personal opinion as to what needs to be done for this issue:
> 
> 1. We need a new setting.
> 
> * This setting will be located at Settings -> Navigation -> Voice Instructions.
> * It will be titled, "Say Street Names".
> 
> 2. When this setting is set to on, the voiced navigation instructions need to include Street Names.

Regarding this, I think that street names should be on by default. You shouldn't have to turn on any settings in order for street names to be enabled.

**Comment by zyphlar** [comment]
Implemented in #3118

**Comment by zyphlar** [comment]
@the-man-machine the PR 3130 hasn't been merged yet, there may have been a short period of time where an iOS beta was available with this feature but it's not the current beta or release. Hopefully we can merge and release soon, November was a bit shaky for releases.

**Comment by zyphlar** [comment]
Hi all! PR #3130 has been merged and is available in the release version of the app. Please try it out by enabling it under Voice settings and let me know your feedback!

**Comment by caboteria** [comment]
"Turn right on Main Street"

ALL RIGHT! THANK YOU!

**Comment by zyphlar** [comment]
@caboteria you're welcome!
