### ISSUE TITLE
Parking icons improvements

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#6161]
After some nice work in reworking the parking icons by @RedAuburn in https://github.com/organicmaps/organicmaps/pull/3896 and https://github.com/organicmaps/organicmaps/pull/5732, this is the current status of car parking icons in Organic Maps:

| | `amenity=parking` | `amenity=parking` +<br>`parking=underground` | `amenity=parking` +<br>`parking=street_side` | `amenity=`<br>`parking_entrance` |
|-|-|-|-|-|
| **Default** | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking-m.svg" width="48"/> | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking_underground-m.svg" width="48"/>  | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking-s.svg" width="32"/> | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking_entrance-m.svg" width="48"/> |
| **`access=private`**  | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking_private-m.svg" width="48"/>  | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking_underground-m.svg" width="48"/> | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking-s.svg" width="32"/> | Not shown |
| **`fee=yes`** | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking_pay-m.svg" width="48"/>  | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking_pay-m.svg" width="48"/>  | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking_pay-s.svg" width="32"/> | <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking_entrance-m.svg" width="48"/> |

Some possible improvements:
- [ ] Add down arrow in letter P to `parking=underground` + `fee=yes`
- [ ] Show `amenity=parking_entrance` + `access=private` with transparent P and left arrow.
- [ ] Add transparency to `amenity=parking` + `parking=underground`+ `access=private` (https://github.com/organicmaps/organicmaps/issues/5730)
- [ ] Add transparency to `amenity=parking` + `parking=street_side`+ `access=private`

**Comment by DavidMacalister** [comment]
Just a test, the icons are wrong

![parking_underground-m2](https://github.com/organicmaps/organicmaps/assets/114320580/d2083cfd-9d35-4683-a3fe-ac05b7a7b386)
![parking_entrance-m](https://github.com/organicmaps/organicmaps/assets/114320580/2ff91206-e265-4881-94cd-38d26a867d7e)
![parking-m](https://github.com/organicmaps/organicmaps/assets/114320580/9a2fa80c-df3d-45d5-b24b-a90ea54e21ac)
![parking_underground-m](https://github.com/organicmaps/organicmaps/assets/114320580/fa27c72c-18d8-4b8f-b3cb-be76f8f3011f)
![parking_private-m](https://github.com/organicmaps/organicmaps/assets/114320580/6acd705d-2869-4690-9e41-3b16dbaa84cf)

**Comment by biodranik** [comment]
Maybe something like this? 
![выява](https://github.com/organicmaps/organicmaps/assets/170263/a5bb3478-3a1a-425d-a262-78fde7c4db7e)

**Comment by Ilav1** [comment]
Or maybe something like that for parking=underground
![4_1_1](https://github.com/organicmaps/organicmaps/assets/102852954/1bec65a8-d3ad-4410-84cc-f1e88e6610e2)

**Comment by pastk** [comment]
I think its better to reserve a "corner roof" P for a covered parking (which is not necessary underground) - we don't support it yet by might add in the future.

So an option suggested by @biodranik is better IMO.
To make it more obvious there is a ground above the parking consider adding a tree or a house, etc. above the ground line.

**Comment by dvdmrtnz** [comment]
> To make it more obvious there is a ground above the parking consider adding a tree or a house, etc. above the ground line.

I would not add trees or anything. Would make the icon too busy.

I actually like the current underground parking symbol as it is right now. IMO it's simple and clear. 

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/21c3fe51-ba52-45d8-bc33-a544c1ec20b7" width="48"/>

**Comment by matheusgomesms** [comment]
I like it too (down arrow), for the underground icon.

**Comment by biodranik** [comment]
The down arrow is better than a normal P letter.
