### ISSUE TITLE
Application doesnt register as a Navigation app on Android

### ISSUE THREAD

**Issue by piggz** [organicmaps/organicmaps#6179]
I have an android car radio, it has a hardware Navi button, which can be mapped to an installed Navigation app.  When i configure this, i get a list of Google Maps, Here WeGo, and OSMAnd (which I installed) ... Organic Maps does not appear in the list, so I wonder if there is some change required to the Manifest to register as such an application?

**Comment by Jean-BaptisteC** [comment]
Can you give the reference Android car radio ?

**Comment by piggz** [comment]
I dont think its anything special, a cheap, and quite janky chinese unit, which definitely lies about its android version! (though it beat my expectations!)  Specifically its this one https://www.ebay.co.uk/itm/185983338035

**Comment by Jean-BaptisteC** [comment]
This screen add support for Android Auto, but Organic Maps for AA is not yet full developed.
You can follow advancement here #4096

**Comment by piggz** [comment]
I dont think this is relevant to this issue and should be re-opened.  Android Auto is done using an app on the screen, connecting an android phone, this is not what im doing, im installing Organic Maps from fdroid on the radio itself, just like with OsmAnd, and running locally, not via AA.

**Comment by Jean-BaptisteC** [comment]
Sorry for the confusion,
Is it possible to start Organic Maps from Fdroid on car radio ?

**Comment by piggz** [comment]
Yes, there are no problems opening and using the app from either the launcher, or fdroid ... the bug is that other navigation apps such as OsmAnd, gmaps and Here, appear to register themselves as a "Navigation" app in android, and this allows the user to use the device settings to assign the "Navigation" app to the Navi hardware button.  I imagine it is probably something that can be added to the manifest?

**Comment by biodranik** [comment]
Maybe these apps are hard-coded in that launcher application? What is its name?

You may try to get device logs somehow via adb logcat and see which intent is sent when you press a nav button.

**Comment by piggz** [comment]
I havnt figured out how to adb into the device yet, but I did try a selection of more apps.  I installed Navit, Waze, Sygic and Maps.me, out of those, only waze and sygic showed up as options to select as navigation apps.

As you say, they might be hardcoded into the launcher, which would be a shame, but ill continue digging.

**Comment by piggz** [comment]
Ill close this ... i found a hidden "factory" menu in the device settings, which allows the "Navigation" apps to be manually selected
