### ISSUE TITLE
Bridge with road is displayed without road

### ISSUE THREAD

**Issue by dbf256** [organicmaps/organicmaps#6181]
**Describe the issue**
See image - looks like an issue with oedering in styles.
It is a bridge with car road rhat is above railroad way.
https://omaps.app/w4MngePK1I/Prenzlauer_Promenade

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**System information:**
 - Operating system and its version: Android
 - Organic Maps version: 2023.09.22-27-Google
![Screenshot_2023-10-02-10-58-21-280_app organicmaps~01](https://github.com/organicmaps/organicmaps/assets/2550295/61e8d20d-e5c6-484b-8b86-e3526dfd0f0f)

**Comment by pastk** [comment]
Most likely layer= tags are wrong in OSM... Could you please check it?

Or I'll check mysef a bit later..

**Comment by Jean-BaptisteC** [comment]
Yes you right roads have layer=1 and bridge have layer=2

**Comment by Jean-BaptisteC** [comment]
Will be fixed in the next version
