### ISSUE TITLE
Very few house numbers are displayed

### ISSUE THREAD

**Issue by dbf256** [organicmaps/organicmaps#6182]
**Describe the issue**
All houses have numbers, I expect to see all of rhem, but need to zoom in.
![Screenshot_2023-10-02-22-09-28-090_app organicmaps](https://github.com/organicmaps/organicmaps/assets/2550295/4aa7879f-1497-42c8-b49f-9b3d3279428e)

https://omaps.app/04MngywMWG/Körnerstraße%2C_40

**System information:**
 - Operating system and its version: Android
 - Organic Maps version: 2023.09.22-27-Google

**Additional context**
Please add any other context and important details/notes/comments about the problem here.

**Comment by Jean-BaptisteC** [comment]
CC @pastk

**Comment by map-per** [comment]
I made a PR (#6221) to fix this

**Comment by pastk** [comment]
> I made a PR (#6221) to fix this

Did you test that this case is fixed by your PR indeed? It looks like addresses are tagged on buildings themselves here instead of standalone nodes.

**Comment by map-per** [comment]
> It looks like addresses are tagged on buildings themselves here instead of standalone nodes.

No, most addresses are mapped on nodes in that area.

> Did you test that this case is fixed by your PR indeed?

There is a screenshot in #6221 🙃
