### ISSUE TITLE
App crashes when I try to open it

### ISSUE THREAD

**Issue by JimmyCushnie** [organicmaps/organicmaps#619]
![image](https://user-images.githubusercontent.com/32693298/122543125-6e580280-cff9-11eb-914e-488b8a5b2d40.png)

Whenever I try to open Organic Maps, I get a few seconds of a white screen, then this message. It still happens even with all other apps closed and immediately after restarting the device.

I suspect this is because of my old-ass phone. I have a Moto G (first gen -- 2013) and I'm on Android 5.1. Am I too low-spec for Organic Maps, or is there some way I can get it to work?

It's worth noting that I can run OsmAnd no problem, but I'd much rather run Organic.

**Comment by victorbnl** [comment]
Same here #630

**Comment by victorbnl** [comment]
Please make sure your <SD Card>/Android folder is accessible

**Comment by victorbnl** [comment]
Please make sure your <SD Card>/Android folder is accessible

**Comment by biodranik** [comment]
Can you please share `adb logcat` logs while trying to launch the app?

**Comment by rtsisyk** [comment]
I think this is the same as https://github.com/organicmaps/organicmaps/issues/634
We are already workin on the fix!

**Comment by biodranik** [comment]
This crash on Android 5 devices was fixed a long time ago.
