### ISSUE TITLE
Missing changeset comments?

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#6195]
https://www.openstreetmap.org/changeset/141964072

https://www.openstreetmap.org/changeset/142019990

It is possible that user is faking changeset tags and it is not made with OM.

But if it yes, then it would be highly useful to have way to provide changeset comments for changing place names.

See https://community.openstreetmap.org/t/edit-warring-over-nagorno-karabakh-region-republic/57413/35 and https://en.wikipedia.org/wiki/Flight_of_Nagorno-Karabakh_Armenians for context

**Comment by strump** [comment]
It's impossible to change city or town name from OrganicMaps. I think user `Nightwind20` tweaked `created_by` tag in the changeset.

**Comment by biodranik** [comment]
Cities and towns are not editable, but villages are.

**Comment by biodranik** [comment]
Another option could be to only allow adding translated names, without editing the main name tag. Making a required comment field in such (and other critical/important cases) may also be a good solution.

**Comment by vng** [comment]
Editing place's names is banned.

**Comment by matkoniecz** [comment]
in https://github.com/organicmaps/organicmaps/commit/070ba5fc3702962545928c2302c90e56f4ca9de7
