### ISSUE TITLE
handle rental=* like cuisine & recycling

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#6203]
see https://github.com/organicmaps/organicmaps/pull/6192#discussion_r1346146431

**Comment by pastk** [comment]
https://taginfo.openstreetmap.org/keys/rental#values

`city_bike` 60%
`yes` 7%
`city_bike;ebike` 5% (640 cases only)
everything else is <4% (<550 cases) ATM

So I'm not sure its worth an effort to parse multiple values and make it like e.g. recycling.

Adding one type `shop-rental-bikes` will be enough for now I think (for `city_bike` and `city_bike;ebike` values).

WDYT?

**Comment by RedAuburn** [comment]
ah you're right! Will update https://github.com/organicmaps/organicmaps/pull/6192
