### ISSUE TITLE
[ios] The distance to the next turn or to the final destination freezes

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6209]
> After an upgrade to the latest version, in the navigation mode, the distance to the next turn or to the final destination freezes at 10 kilometers (when the countdown should switch from counting kilometers to counting hundreds of meters) and unfreezes back only when the distance gets below 1 kilometer (when it switches to counting dozens of meters).

_Originally posted by @biodranik in https://github.com/organicmaps/organicmaps/issues/4029#issuecomment-1747466003_

**Comment by Jean-BaptisteC** [comment]
@biodranik are you able to reproduce on the latest version?

**Comment by biodranik** [comment]
Yes, there were at least 3 reports from users recently.

**Comment by fabwu** [comment]
I've just tried to reproduce this issue in the simulator but at least the distance to the next turn works fine for me:

<img src="https://private-user-images.githubusercontent.com/6050639/317472504-23b5a66c-6405-429b-9033-34f2e4d2d391.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NjQ1NDgsIm5iZiI6MTcxMTU2NDI0OCwicGF0aCI6Ii82MDUwNjM5LzMxNzQ3MjUwNC0yM2I1YTY2Yy02NDA1LTQyOWItOTAzMy0zNGYyZTRkMmQzOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMTgzMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIxZTQ1NjllNThkMmViYTU0OTc3OWFmOTcxYWIxMDc2Y2ExYmFjNmYzNzVkYzZmZWZlNGFiZmNhYmU3M2RkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Wv_Ncwk90o5P9eza2d33c1QZgFD71i5G7yHPRhHSF-0" alt="Simulator Screenshot - iPhone 15 - 2024-03-27 at 12 30 05" style="max-width: 100%;" width=300>

**Comment by biodranik** [comment]
Today I reproduced the issue by switching the locale to another one that uses commas as decimal separators and then starting a route to the destination with less than 10km of distance. The map froze on the CarPlay display, but it responded to the selection of a new destination.

**Comment by biodranik** [comment]
Reproduced not updating time and distance on simulator, with Russian locale, for distances between 1 and 10km

**Comment by fabwu** [comment]
It was the comma. See PR for the fix.

@biodranik btw. could we add unit tests to the ios project? It would really help fixing these small bugs...

**Comment by biodranik** [comment]
@fabwu tests would be great, any initiative is appreciated ) @kirylkaveryn what can you suggest?
