### ISSUE TITLE
Add missing translations (uk for example)

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6214]
https://github.com/organicmaps/organicmaps/blob/master/data/strings/strings.txt#L26151

![выява](https://github.com/organicmaps/organicmaps/assets/170263/ec08dba6-3f66-409a-aa1a-d6ee058f93dd)

**Comment by Jean-BaptisteC** [comment]
Good idea, I suggest to translate in priority languages most used (Stats can be found on Google Play Console)

**Comment by Yash-28-gits** [comment]
I have created a pull request for the changes that have been made to file to add uk translation
