### ISSUE TITLE
[android] Smoother corners for the place page

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6215]
![выява](https://github.com/organicmaps/organicmaps/assets/170263/0c83715e-4213-4f56-84fc-5ceb0b2e440e)

**Comment by aanyasinghdhaka** [comment]
can i resolve this issue ?

**Comment by biodranik** [comment]
As we do not see any pull requests from you with the fix, we don't know if you can resolve this issue or can not resolve it, so we can't answer your question.

**Comment by ashway171** [comment]
Do you typically assign the issues to contributors or devs may start working and submit their PRs upfront..?

**Comment by Jean-BaptisteC** [comment]
Don't ask to work on issue, feel free open PR
