### ISSUE TITLE
Remove logs dir in zip on Android

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#6219]
When I export logs from OM and I try to open them in files manager. I don't see files.
Logs are not visible because logs inside archive zip are stored in \logs directory.
@rtsisyk is it caused by new Android structure ?

**Comment by biodranik** [comment]
What exactly do you do? Is it Android 13? How it worked before?

**Comment by Jean-BaptisteC** [comment]
After few tests, logs is visible but now logs are inside directory in archive
- Older structure
  - logs.zip -> logs files
- New structure
  - logs.zip -> logs directory -> logs files
