### ISSUE TITLE
Exporting bookmarks to WhatsApp only exports text (iPhone)

### ISSUE THREAD

**Issue by AWBroch** [organicmaps/organicmaps#6230]
**Describe the issue**
When I try to export my bookmarks and share on WhatsApp, only the text that says ‘Hello, attached are my bookmarks…’ get sent, not the KMZ file.

All the other share methods work fine.

Even though WhatsApp is a 3rd party app, it’s so common that it would be nice to support it.

Would it work to maybe just send the KMZ instead of attaching it to a text message?

**Steps to reproduce**
1. Go to 'Bookmarks and Tracks'
2. Click on '...' then 'Export file'
3. Click on 'WhatsApp'
4. Pick your person, click Send
5. Check your WhatsApp messages
6. Only the text message that says ‘attached are my bookmarks’ is present, not the KMZ file

**Expected behavior**
I would expect it to send either both the text with the KMZ attached or the KMZ by itself.

**Screenshots**
![IMG_2853](https://github.com/organicmaps/organicmaps/assets/122807471/b36ed6df-b129-4eab-88fb-64d061316988)
![IMG_2852](https://github.com/organicmaps/organicmaps/assets/122807471/f13e4c8c-1cc6-4c37-a9dc-63d80905de90)
![IMG_2851](https://github.com/organicmaps/organicmaps/assets/122807471/b25acc9c-5470-40a6-a01f-0ab6ded05566)

**System information:**
 - iOS 16.6.1
 - Organic Maps version: 2023.09.22-20
 - Device Model: iPhone SE Gen. 2
 - WhatsApp version: 2.23.19.86

**Additional context**
I’d be willing to help fix this issue, but I haven’t worked on Organic Maps before, so I’d need to be pointed in the right direction.

**Comment by biodranik** [comment]
Can you build and run/debug iOS app on your device?

**Comment by biodranik** [comment]
Actually, it looks like whatsapp does not support kmz (or other arbitrary) files: https://stackoverflow.com/a/17723981

**Comment by AWBroch** [comment]
Hi, I ran a debug build and I’ve attached the log:

[run.log](https://github.com/organicmaps/organicmaps/files/12839379/run.log)

I’ve sent and received zipfiles over WhatsApp before, so I’d be kind of surprised if it’s impossible. I can do some more research

Could the problem maybe be in one of these lines of the log?

```
2023-10-07 18:33:44.318266-0400 Organic Maps (Debug)[935:28972] [ShareSheet] error loading metadata for documentURL:file:///private/var/mobile/Containers/Data/Application/BD72F204-F50A-4F7D-9E7C-EE28C5FA95AA/tmp/My%20Places.kmz error:Error Domain=NSFileProviderInternalErrorDomain Code=0 "No valid file provider found from URL file:///private/var/mobile/Containers/Data/Application/BD72F204-F50A-4F7D-9E7C-EE28C5FA95AA/tmp/My%20Places.kmz." UserInfo={NSLocalizedDescription=No valid file provider found from URL file:///private/var/mobile/Containers/Data/Application/BD72F204-F50A-4F7D-9E7C-EE28C5FA95AA/tmp/My%20Places.kmz.}
2023-10-07 18:33:44.409105-0400 Organic Maps (Debug)[935:28971] [default] LaunchServices: store (null) or url (null) was nil: Error Domain=NSOSStatusErrorDomain Code=-54 "process may not map database" UserInfo={NSDebugDescription=process may not map database, _LSLine=66, _LSFunction=_LSServer_GetServerStoreForConnectionWithCompletionHandler}
```

**Comment by AWBroch** [comment]
So, by just ignoring the `message` parameter sent to `MWMActivityViewController.shareControllerForURL`, the KMZ gets sent fine over WhatsApp

```diff
--- a/iphone/Maps/Classes/Share/MWMActivityViewController.mm
+++ b/iphone/Maps/Classes/Share/MWMActivityViewController.mm
@@ -42,7 +42,7 @@ + (instancetype)shareControllerForPlacePage:(PlacePageData *)data {
 + (instancetype)shareControllerForURL:(NSURL *)url
                               message:(NSString *)message
                     completionHandler:(UIActivityViewControllerCompletionWithItemsHandler)completionHandler {
-  NSMutableArray *items = [NSMutableArray arrayWithObject:message];
+  NSMutableArray *items = [NSMutableArray array];
   if (url) {
     [items addObject:url];
   }
```

Would there be any way to detect if something is shared by WhatsApp and filter out the message param? Or maybe putting the URL first and the text second?

**Comment by biodranik** [comment]
We can't know in advance will user choose whatsapp or not. 
I have an idea: edit the message and remove any URLs from it and see if it works.

**Comment by AWBroch** [comment]
I tried removing the URLs but it still only sent the text. [This Stackoverflow question](https://stackoverflow.com/questions/31920041/send-image-and-text-with-whatsapp) says you can’t send text and a file at the same time over WhatsApp

Would removing the text for every share method be an option?

**Comment by biodranik** [comment]
Need to investigate it first. Did you test in all other messengers, email apps, and map apps? Could it be a specific Whatsapp bug? Is there a way to reproduce it with some demo/minimal example? Does it make sense to file that bug to Whatsapp?

**Comment by Jean-BaptisteC** [comment]
@kirylkaveryn can you check on the latest version?

**Comment by kirylkaveryn** [comment]
> @kirylkaveryn can you check on the latest version?

Wow interesting...
I'll take a look soon!

**Comment by AWBroch** [comment]
Yeah, it looks like WhatsApp fixed this bug.
