### ISSUE TITLE
Add Station logo for Singapore Rail Network

### ISSUE THREAD

**Issue by hoizan** [organicmaps/organicmaps#6235]
Singapore has an extensive rail network  of more 140 stations across 6 MRT lines. May I request that OM renders  their stations with the station icon.

![Singapore_MRT-Station-logo](https://github.com/organicmaps/organicmaps/assets/92556284/b06c4849-6821-4ccf-be74-f1efa6c7ae1d)

https://www.lta.gov.sg/content/ltagov/en/getting_around/public_transport/rail_network.html

**Comment by RedAuburn** [comment]
https://en.wikipedia.org/wiki/File:Logo_of_Singapore_MRT.svg

hmm, it looks like the logo is copyrighted, @biodranik can we still include it?

**Comment by hoizan** [comment]
The propose logo is without the text. It is seen at every stattion. It got it  from here:
https://seeklogo.com/vector-logo/458877/mrt-station

**Comment by biodranik** [comment]
We can draw it ourselves, or find a logo source that is clearly allowed to be used in free apps like Organic Maps.

**Comment by hoizan** [comment]
@RedAuburn @vng Thanks ❤️ from SG
