### ISSUE TITLE
[iOS] App still asks for the background location access...

### ISSUE THREAD

**Issue by melnichek** [organicmaps/organicmaps#625]
![IMG_1952](https://user-images.githubusercontent.com/1378312/122580662-7befa580-d056-11eb-8554-fd27ed341eb2.jpg)

**Comment by biodranik** [comment]
Thanks, we didn't clean everything up yet :) @vng

**Comment by rtsisyk** [comment]
@vng is it fully fixed by #660?

**Comment by biodranik** [comment]
@melnichek please recheck if it's already fixed.

**Comment by melnichek** [comment]
@biodranik I can't reproduce it any more. Fixed!
