### ISSUE TITLE
Routing Algorithm

### ISSUE THREAD

**Issue by toygarlk** [organicmaps/organicmaps#6278]
n this year's updates, it started to direct users to side streets instead of primary or secondary roads and does not care about elevation data at all. We need an algorithm that directs more to main roads (like Graphopper).

**Comment by vng** [comment]
Could you please give more details? What route are you building (foot, bicycle) and start/end points (here or on email if they are private).

**Comment by toygarlk** [comment]
For example, same route OSM vs Google Maps:

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=41.05290%2C28.92008%3B41.07306%2C28.94065#map=15/41.0629/28.9373

https://www.google.com/maps/dir/41.0529768,28.919914/41.0747576,28.9417933/@41.0639895,28.9251982,14.75z/data=!4m2!4m1!3e0?entry=ttu

**Comment by vng** [comment]
Some bizzare default speeds was saved in a previous map data. Will be fixed in the next app and data update.

<img width="637" alt="Screenshot 2023-10-21 at 12 52 09" src="https://github.com/organicmaps/organicmaps/assets/175612/5d996861-5ffe-4f70-add6-37d4025ae889">

**Comment by vng** [comment]
https://github.com/organicmaps/organicmaps/pull/6295
