### ISSUE TITLE
Arrow Position

### ISSUE THREAD

**Issue by toygarlk** [organicmaps/organicmaps#6279]
In the first or older versions of Organic Maps, the location of the blue arrow in the route mode was a little closer to the middle of the screen, but in the latest updates, this arrow has completely moved to the bottom of the screen. This negatively affects the driver. And when I lock and unlock the screen in route mode, half of the arrow enters the screen and disappears.

Device: S20 FE

**Comment by biodranik** [comment]
#4456

**Comment by walterjwhite** [comment]
I created a route with a waypoint on an intersection which led to confusing directions.  The arrows for me display where I'd expect them to be, but I wasn't expecting to turn right at the intersection.  That was my fault on creating a waypoint where I did.

![Capture+_2023-11-08-08-06-28](https://github.com/organicmaps/organicmaps/assets/469680/d315c23b-1e82-4fca-a37c-e45b40b3707b)
![Capture+_2023-11-08-08-08-47](https://github.com/organicmaps/organicmaps/assets/469680/211066f3-56c6-4692-adbb-c05a0257ab0b)

**Comment by pastk** [comment]
Let's track it in #4456
