### ISSUE TITLE
Lane Assist

### ISSUE THREAD

**Issue by toygarlk** [organicmaps/organicmaps#6281]
Lane assist not works on my device (S20 FE). The lane information of the road was entered into OSM months ago by me.

**Comment by biodranik** [comment]
Please provide more details, what exactly was added and where, starting and ending points, what is visible on the screen when you drive there.

**Comment by toygarlk** [comment]
> Please provide more details, what exactly was added and where, starting and ending points, what is visible on the screen when you drive there.

For example; When I test drive on roads where I have added lane information to OSM and I approach a junction in Organic Maps, no lane information system appears above the screen. In other words, I do not have that lane support feature in the screenshots added by the OM, and I have been testing all FDroid, Google Play and beta versions for months, but none of them worked..

**Comment by strump** [comment]
@toygarlk could you please share road in OSM to which you added lanes information?
Maybe you added wrong info or map data should be updated?

**Comment by toygarlk** [comment]
> @toygarlk could you please share road in OSM to which you added lanes information? Maybe you added wrong info or map data should be updated?

For example; https://www.openstreetmap.org/directions?engine=graphhopper_car&route=41.0525%2C28.9195%3B41.0322%2C28.9335

**Comment by strump** [comment]
@toygarlk Organic Maps reads lanes information from `turn:lanes=` tag. See [OpenStreetMap wiki](https://wiki.openstreetmap.org/wiki/Key:turn) for details. Here's example: [road in Italy](https://www.openstreetmap.org/way/1119653334).
I don't see any roads with `turn:lanes` tag in Istanbul. Probably you or local mappers should update OpetStreetMap with lanes data.

**Comment by toygarlk** [comment]
> @toygarlk Organic Maps reads lanes information from `turn:lanes` tag. See [OpenStreetMap wiki](https://wiki.openstreetmap.org/wiki/Key:turn) for details. Here's example: [road in Italy](https://www.openstreetmap.org/way/1119653334). I don't see any roads with `turn:lanes` tag in Istanbul. Probably you or local mappers should update OpetStreetMap with lanes data.

Isn't just the lanes tag enough for the function to work?

**Comment by patepelo** [comment]
No
