### ISSUE TITLE
Tram and Light Rail Systems

### ISSUE THREAD

**Issue by toygarlk** [organicmaps/organicmaps#6282]
In some cities, light rail systems and trams are used more than subways. In my opinion, rail mode should be made instead of metro mode in OM, and tram and light rail systems should also be shown on the map and in route mode. Because they are vital.

**Comment by biodranik** [comment]
In our opinion, every type of public transport is vital and should be present in Organic Maps. With your help, we can implement it. Please check existing public transport issues, and help with validating/using OSM data for other types of transport.

**Comment by toygarlk** [comment]
> In our opinion, every type of public transport is vital and should be present in Organic Maps. With your help, we can implement it. Please check existing public transport issues, and help with validating/using OSM data for other types of transport.

To give an example, I live in Istanbul and I am the OSM contributor, and all the trams and subways in Istanbul are included in great detail and accurately on OSM. In the city I live in, trams are more popular than subways and the transportation network is very large. I would like to see this feature in Organic Maps because trams are supported in Maps.me and OSMAnd. I am ready to help you in any way possible, thank you and best regards.

**Comment by pgr0ss** [comment]
I noticed that the light rail system also isn't showing up in Seattle. You can see it on OSM (https://www.openstreetmap.org/#map=11/47.6133/-122.3822&layers=T) but turning on Subway in Organic Maps says "Subway map is unavailable". Thanks!

**Comment by biodranik** [comment]
If that light rail system is compatible in tagging scheme with other light rails in OM, then you can add it here (there is a spreadsheet table at the bottom, add a comment there): https://cdn.organicmaps.app/subway/

**Comment by pgr0ss** [comment]
> If that light rail system is compatible in tagging scheme with other light rails in OM, then you can add it here (there is a spreadsheet table at the bottom, add a comment there): https://cdn.organicmaps.app/subway/

Thanks, I added a comment: https://docs.google.com/spreadsheets/d/1SEW1-NiNOnA2qDwievcxYV1FOaQl1mb1fdeyqAxHu3k/edit?disco=AAAA9Eg1vvs
