### ISSUE TITLE
Show amenity=compressed_air stations

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#6294]
We should show `amenity=compressed_air` stations. This is used to map a device to inflate tires/tyres (e.g. motorcar, bicycle, motorcycle, etc).

8.6k uses worldwide

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcompressed_air

https://taginfo.openstreetmap.org/tags/amenity=compressed_air#overview

**Comment by dvdmrtnz** [comment]
Icon ideas: A wheel with a pressure gauge:
![Captura de pantalla 2023-10-12 a las 17 14 03](https://github.com/organicmaps/organicmaps/assets/47610359/efade859-3b98-46bc-bad8-c039fce5e49e)

**Comment by dvdmrtnz** [comment]
Or maybe use the [`tire-repair-m.svg`](https://github.com/organicmaps/organicmaps/blob/master/data/styles/clear/style-clear/symbols/tire-repair-m.svg) icon that is in the repo but is not used right now:

<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/tire-repair-m.svg" width="36"/>

**Comment by euf** [comment]
Reusing this icon without background would be great in terms of consistency. Also similar to petrol stations and gas pumps.

**Comment by patepelo** [comment]
Since we would implemante one for tyre repair for a facility. Maybe using one of your proposal for the actual pump station would be better.

I like thesefrom the ones you posted as inspiration:
![image](https://github.com/organicmaps/organicmaps/assets/23003127/08bd0442-f21f-445f-bdf5-d8b693a9ddbd)
![image](https://github.com/organicmaps/organicmaps/assets/23003127/73d9f37c-1e70-4e03-9e30-26deff8d2c0c)

**Comment by muralito** [comment]
> Or maybe use the [`tire-repair-m.svg`](https://github.com/organicmaps/organicmaps/blob/master/data/styles/clear/style-clear/symbols/tire-repair-m.svg) icon that is in the repo but is not used right now:
> 
> <img alt="" width="36" src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/tire-repair-m.svg">

I would prefer a wheel and a wrench, meaning that they can remove the wheel and dismount the tire. Also the wrench alone is used to represent all kind of repair shops.

**Comment by dvdmrtnz** [comment]
Proposal:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/5aa7620a-a926-484e-8ed4-0701c14caebc" width="36"/>

**Comment by RedAuburn** [comment]
https://wiki.openstreetmap.org/wiki/Key:compressed_air has about 3x the usage, and is usually tagged on POI, so maybe we should include that too?

**Comment by muralito** [comment]
> https://wiki.openstreetmap.org/wiki/Key:compressed_air has about 3x the usage, and is usually tagged on POI, so maybe we should include that too?

I think is the same service/amenity but mapped as an additional tag to amenity=fuel_station, so yes, it should be included.

Not OM related, but one problem with the key compressed_air as an additional tag to the fuel station, is that nowadays some fuel stations are charging a fee for the compressed air (in most of them you need to insert a coin to enable the compressor), and tag "fee=yes" can only be used when mapping the compressor as an amenity by itself.

**Comment by dvdmrtnz** [comment]
> https://wiki.openstreetmap.org/wiki/Key:compressed_air has about 3x the usage, and is usually tagged on POI, so maybe we should include that too?

Yes. Should be replaced with amenity=compressed_air

**Comment by dvdmrtnz** [comment]
> Proposal:
> <img alt="" width="36" src="https://user-images.githubusercontent.com/47610359/276991508-5aa7620a-a926-484e-8ed4-0701c14caebc.svg">

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/793afa7a-e310-47fb-827b-852ef92991c5" width="320"/>
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/602e6460-5604-415b-857a-924852fd926a" width="320"/>
