### ISSUE TITLE
Taxi Stop isn't rendering in some cases

### ISSUE THREAD

**Issue by patepelo** [organicmaps/organicmaps#6300]
**Describe the issue**

Taxi stop is not rendered even at max zoom.

![image](https://github.com/organicmaps/organicmaps/assets/23003127/fc2b4364-b17f-4c7d-abb3-7ba3d6af7880)

Data is https://www.openstreetmap.org/node/11085154905
Tags are correctly tagged as:
amenity=taxi
Data is two months old. Map data is up to date.

It only appears when you search it. I believe many icons are always hidden due to similar factors. Gotta when more zoom arrives.

![image](https://github.com/organicmaps/organicmaps/assets/23003127/96e8f997-bde3-48b1-a6b2-67d0174d3c7f)

In comparison, data from https://www.openstreetmap.org/node/5268554950
is correctly rendered. It only has more data tags like address and website.

![image](https://github.com/organicmaps/organicmaps/assets/23003127/d042ea60-70b6-4b0f-858f-2412e4c88a6c)

**Steps to reproduce**
1. Go to 
https://www.openstreetmap.org/#map=19/41.62260/2.69383
**Expected behavior**

Taxi Icon appearing

**Screenshots**
* see above

**System information:**
 - Operating system and its version: Android 12
 - Organic Maps version: Android Beta version 2023.10.09-1-Google-beta
 - Device Model: Google Pixel 3a

**Comment by vng** [comment]
The taxi icon was displaced by a street name here. Can check in "Add place" mode.
@pastk 
I think it is reasonable that street names have more priority, no?

**Comment by dvdmrtnz** [comment]
In latest beta 2023.10.15 that expands zoom to z20 it appears:

![](https://github.com/organicmaps/organicmaps/assets/47610359/9d4c83f5-757a-47a5-b85e-ab500d62b1ab)

**Comment by patepelo** [comment]
> The taxi icon was displaced by a street name here. Can check in "Add place" mode. @pastk I think it is reasonable that street names have bigger priority than parking, taxi, etc, no?

Yes, it is reasonable. But maybe on the last zoom level all icons should appear.

And yes, with more zoom now this feature will appear, this is great. We can close this if you agree.

**Comment by patepelo** [comment]
This is more of a problem in the Barcelona area where mappers have unilaterally decided to add street name to the each footway, making OM showing them and hidding many POIs on the way. But with more zoom, this will mostly be avoided. 

Great for the new zoom :)

**Comment by pastk** [comment]
> Yes, it is reasonable. But maybe on the last zoom level all icons should appear.
> 

I think so too.
Actually I made some experiments already not long ago

![IMG_20231016_180654_062.jpg](https://github.com/organicmaps/organicmaps/assets/18434508/c7237776-e434-488e-95fd-e56b279d8002)
