### ISSUE TITLE
Fiji and other countries split on the 180° degree

### ISSUE THREAD

**Issue by tttp** [organicmaps/organicmaps#6308]
**Describe the issue**

Organic map doesn't wrap around the world at 180, so you have to spin around the world to go a few degrees east when you are in fiji

**Steps to reproduce**
Search Wairiki and go there
You can't scroll further east and zoom out is acting weird

Search waitabu
https://omaps.app/gKIADaWnx_/Waitabu

You can't scroll west

These two places are a few kilometers apart in taveuni, Fiji, but on og, you need to scroll the whole world to go from one to the other

**Expected behavior**
It should be possible to scroll from a point west of the 180 to east and vice versa

**Screenshots**

**System information:**

Android pixel 6a
Om 2023.08.18-8-Google

**Comment by biodranik** [comment]
See #1373

**Comment by tttp** [comment]
Already reported (multiple time) closing, tha nsk
