### ISSUE TITLE
Wrong icon for private parking

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#6315]
This [private parking](https://www.openstreetmap.org/node/5611818744) use this [icon](https://github.com/organicmaps/organicmaps/blob/master/data/styles/clear/style-clear/symbols/place-of-worship-m.svg). I think it's caused by this PR #6261

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: 2023.10.15-20-Google-beta
 - Device Model: Pixel 6

**Comment by biodranik** [comment]
@Jean-BaptisteC can you please check if this issue was fixed in the latest beta?

**Comment by Jean-BaptisteC** [comment]
Yes fixed in latest beta
