### ISSUE TITLE
Crash after Location error occured QGeoPositionInfoSource::Error code: 0

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#6328]
This issue was discussed previously in https://github.com/organicmaps/organicmaps/pull/5823#issuecomment-1720250606

There are crashed happening with following in logs:
```
qt.positioning.geoclue2: Unable to start the client: "org.freedesktop.DBus.Error.UnknownMethod" "No such interface 'org.freedesktop.GeoClue2.Client' on object at path /org/freedesktop/GeoClue2/Client/1"
LOG TID(1) WARNING   624.012 platform/qt_location_service.cpp:117 OnErrorOccurred(): Location error occured QGeoPositionInfoSource::Error code: 0
Segmentation fault (core dumped)
```

Its happening on my Ubuntu 18.04 laptop when I press the location button.

What's worse sometimes it happens on every app launch during startup. I don't know what's triggering it exactly, but it seems that it happens after the app resets to a "first launch" state and asks to accept the lincense etc (and I don't know why it resets, maybe some builds force it for some changes).
Then it crashes on every launch and seems to stop after a few re-tries of after some time.
During this "crash period" in the settings.ini its `LastLocationStateMode=PendingPosition`, I tried changing it to `LastLocationStateMode=NotFollow` (or `NotFollowNoPosition`), but it didn't help, it keeps resetting to `PendingPosition`.

There is a similar startup crash report by a user using a linux flatpak on aarch64 (raspberry pi bulleye).

FYI @Ferenc-

**Comment by kt3115a** [comment]
Raspberry Pi OS (debian 11) 64 bit. Installed from flathub.
Crashes right on startup. Console mesages:
$ flatpak run app.organicmaps.desktop
LOG TID(1) INFO   2.2281e-05 qt/main.cpp:121 main(): Organic Maps 2023.09.22-1-3fc5d227-dirty-Linux started, detected CPU cores: 4
LOG TID(1) INFO      1.21168 platform/string_storage_base.cpp:24 StringStorageBase(): Settings path: /home/andrew/.var/app/app.organicmaps.desktop/config/OMaps/settings.ini
LOG TID(1) WARNING   1.21249 platform/string_storage_base.cpp:46 StringStorageBase(): Loading settings: /home/andrew/.var/app/app.organicmaps.desktop/config/OMaps/settings.ini; Read; Нет такого файла или каталога
LOG TID(1) INFO      5.35044 qt_common/helpers.cpp:66 SetDefaultSurfaceFormat(): Set default OpenGL version to ES 3.0
LOG TID(1) INFO      5.49763 storage/storage.cpp:620 LoadCountriesFile(): Loaded countries list for version: 230920
LOG TID(1) INFO      6.00918 search/processor.cpp:216 SetPreferredLocale(): New preferred locale: ru
LOG TID(2) WARNING   6.02305 search/geocoder.cpp:736 CacheWorldLocalities(): Can't find World map file.
LOG TID(2) WARNING   6.02317 search/cities_boundaries_table.cpp:49 Load(): Can't find World map file.
LOG TID(2) WARNING   6.02321 search/processor.cpp:342 LoadCitiesBoundaries(): Can't load cities boundaries
LOG TID(1) INFO      6.14308 map/framework.cpp:366 Framework(): System languages: ru_RU.UTF-8
LOG TID(1) WARNING    6.1435 power_management/power_manager.cpp:71 Load(): Cannot read power manager config file. Exception: /home/andrew/.var/app/app.organicmaps.desktop/config/OMaps/power_manager_config; Read; Нет такого файла или каталога
LOG TID(1) INFO      6.14443 storage/storage.cpp:955 RegisterLocalFile(): Found file: World in directory:  with size: 44308219
LOG TID(1) INFO      6.14449 storage/storage.cpp:955 RegisterLocalFile(): Found file: WorldCoasts in directory:  with size: 8593484
LOG TID(1) INFO       6.1451 map/framework.cpp:146 RegisterMap(): Loaded World map, of version 230920
LOG TID(1) INFO      6.14527 map/framework.cpp:146 RegisterMap(): Loaded WorldCoasts map, of version 230920
LOG TID(1) WARNING   6.16346 platform/qt_location_service.cpp:117 OnErrorOccurred(): Location error occured QGeoPositionInfoSource::Error code: 0

**Comment by pastk** [comment]
> During this "crash period" in the settings.ini its `LastLocationStateMode=PendingPosition`, I tried changing it to `LastLocationStateMode=NotFollow` (or `NotFollowNoPosition`), but it didn't help, it keeps resetting to `PendingPosition`.

Now it was crashing on every startup attempt with `LastLocationStateMode=NotFollowNoPosition` in the settings.ini, so maybe its not relevant.
It started crashing after an ordinary rebuild.

**Comment by pastk** [comment]
@kt3115a is it easy to setup your raspberry pi env in a VM to reproduce a crash?

Putting my system in a VM is just not feasible :)

**Comment by biodranik** [comment]
@pastk can't you catch the crash in the debugger?

**Comment by pastk** [comment]
It seems to crash in Qt code, so might be a (fixed) Qt bug.
```
Qt 6.2.4
libqt6positioning6 6.2.4-3
libgeoclue-2-0 2.4.7-1ubuntu1
```
But at the same time when using a flatpak (with org.kde.Platform 6.5) it crashes both for me and @kt3115a.

I've attached my debug session log (off the current master), not sure it'll be useful (I guess I'll need to build a debug Qt myself in order to go deeper?).
[qt-loc-crash-debug-log.txt](https://github.com/organicmaps/organicmaps/files/13063421/qt-loc-crash-debug-log.txt)

**Comment by Ferenc-** [comment]
> I've attached my debug session log (off the current master), not sure it'll be useful (I guess I'll need to build a debug Qt myself in order to go deeper?). [qt-loc-crash-debug-log.txt](https://github.com/organicmaps/organicmaps/files/13063421/qt-loc-crash-debug-log.txt)

@pastk While your environment is pretty different, your backtrace is deceptively similar to the one [reported here](https://github.com/flathub/app.organicmaps.desktop/issues/61#issuecomment-1734655976). 
Is it safe to assume that despite this similarity, the workaround confirmed there does not work for you?

**Comment by pastk** [comment]
> It seems to crash in Qt code, so might be a (fixed) Qt bug.
> 

This Qt fix looks relevant
https://code.qt.io/cgit/qt/qtpositioning.git/commit/src/plugins/position/geoclue2/qgeopositioninfosource_geoclue2.cpp?id=03a37f36b9d967205ec70c49ad21e438df362936

**Comment by Ferenc-** [comment]
> This Qt fix looks relevant https://code.qt.io/cgit/qt/qtpositioning.git/commit/src/plugins/position/geoclue2/qgeopositioninfosource_geoclue2.cpp?id=03a37f36b9d967205ec70c49ad21e438df362936

That fix is already part of [Qt 6.5.3](https://code.qt.io/cgit/qt/qtpositioning.git/log/?h=6.5.3) and if your flatpaks are up to date, then [kde runtime 6.5](https://invent.kde.org/packaging/flatpak-kde-runtime/-/commits/qt6.5/), should have that too.
And as long as your organicmaps flatpak is from flathub, then [it is based on the kde runtime 6.5](https://github.com/flathub/app.organicmaps.desktop/blob/master/app.organicmaps.desktop.yml#L3).

**Comment by pastk** [comment]
> That fix is already part of [Qt 6.5.3](https://code.qt.io/cgit/qt/qtpositioning.git/log/?h=6.5.3) and if your flatpaks are up to date, then [kde runtime 6.5](https://invent.kde.org/packaging/flatpak-kde-runtime/-/commits/qt6.5/), should have that too. And as long as your organicmaps flatpak is from flathub, then [it is based on the kde runtime 6.5](https://github.com/flathub/app.organicmaps.desktop/blob/master/app.organicmaps.desktop.yml#L3).

The runtime was updated to 6.5.3 on Sep 30th, while my current runtime (which is crashing) is from Sep 5th (I'll update and test when I can)..

@kt3115a could you please check if your org.kde.Platform flatpak runtime is from Sep 30th or newer?

**Comment by pastk** [comment]
> @pastk While your environment is pretty different, your backtrace is deceptively similar to the one [reported here](https://github.com/flathub/app.organicmaps.desktop/issues/61#issuecomment-1734655976). Is it safe to assume that despite this similarity, the workaround confirmed there does not work for you?

I have mixed results.
Besides changing the `desktopId` string and amending `geoclue.conf` I tried to add a `.desktop` file (its added by a flatpak, but is obviously missing when doing a regular build).
A few times OM managed to get and display my rough location on the map even. But its very unpredictable and unstable.
One time it works, 5 other times it crashes on startup or after location button press.. 

I can see the geoclue service being started successfully for OM
```
Oct 22 23:27:13 pastk-laptop dbus-daemon[752]: [system] Activating via systemd: service name='org.freedesktop.GeoClue2' unit='geoclue.service' requested by ':1.11964' (uid=1000 pid=9462 comm="../omim-build-debug/OMaps " label="unconfined")
Oct 22 23:27:13 pastk-laptop systemd[1]: Starting Location Lookup Service...
Oct 22 23:27:13 pastk-laptop dbus-daemon[752]: [system] Successfully activated service 'org.freedesktop.GeoClue2'
Oct 22 23:27:13 pastk-laptop systemd[1]: Started Location Lookup Service.
Oct 22 23:27:14 pastk-laptop kernel: [1248912.058073] OMaps[9462]: segfault at 8 ip 00007ff4428ced05 sp 00007ffe7422e150 error 4 in libQt6Core.so.6.2.4[7ff442725000+51e0
```
but it can't connect and crashes.

Sometimes it gets a valid location update first and then crashes anyway:
```
LOG TID(1) DEBUG     5.42809 platform/qt_location_service.cpp:137 Start(): Starting Updates from: geoclue2
LOG TID(1) DEBUG     5.51556 platform/qt_location_service.cpp:111 OnLocationUpdate(): Location updated with valid coordinates: 23.325 42.6951
qt.positioning.geoclue2: Unable to start the client: "org.freedesktop.DBus.Error.UnknownMethod" "No such interface 'org.freedesktop.GeoClue2.Client' on object at path /org/freedesktop/GeoClue2/Client/1"
LOG TID(1) WARNING   5.80511 platform/qt_location_service.cpp:117 OnErrorOccurred(): Location error occured QGeoPositionInfoSource::Error code: 0
Command terminated by signal 11
```

So there seems to be some race condition.

My geoclue package is quite old (2.4.7) and there were some timeout-related fixes since then.

**Comment by biodranik** [comment]
Let's first workaround/disable crash on startup, it breaks the work of our contributors. It can be enabled back when the fix is deployed.

**Comment by pastk** [comment]
> My geoclue package is quite old (2.4.7) and there were some timeout-related fixes since then.

I've updated geoclue to 2.5.7 (the newest I could find in PPAs for Ubuntu 18.04).
Then started the `geoclue-demo-agent` (it was added to autostart automatically) and everything started to work (OM gets location updates, no crashes; both regular builds and flatpak), no changes to geoclue.conf or `desktopId` param were required (but I've added an `OrganicMaps.desktop` file).

**Comment by kt3115a** [comment]
> > That fix is already part of [Qt 6.5.3](https://code.qt.io/cgit/qt/qtpositioning.git/log/?h=6.5.3) and if your flatpaks are up to date, then [kde runtime 6.5](https://invent.kde.org/packaging/flatpak-kde-runtime/-/commits/qt6.5/), should have that too. And as long as your organicmaps flatpak is from flathub, then [it is based on the kde runtime 6.5](https://github.com/flathub/app.organicmaps.desktop/blob/master/app.organicmaps.desktop.yml#L3).
> 
> The runtime was updated to 6.5.3 on Sep 30th, while my current runtime (which is crashing) is from Sep 5th (I'll update and test when I can)..
> 
> @kt3115a could you please check if your org.kde.Platform flatpak runtime is from Sep 30th or newer?

I do not know how to do it. flatpak liat just reports that KDE runtime is 6.5 w/o any details.

**Comment by Ferenc-** [comment]
> I do not know how to do it. flatpak liat just reports that KDE runtime is 6.5 w/o any details.

````
flatpak info org.kde.Platform//6.5 | grep Date
        Date: 2023-09-30 15:02:27 +0000
````

**Comment by kt3115a** [comment]
> > I do not know how to do it. flatpak liat just reports that KDE runtime is 6.5 w/o any details.
> 
> ```
> flatpak info org.kde.Platform//6.5 | grep Date
>         Date: 2023-09-30 15:02:27 +0000
> ```
Header: build of org.kde.Sdk, Sat Sep 30 11:26:29 UTC 2023 (53a7bbd2cbad9cbea5ab4caed207d13f55cd88c1)
Date: 2023-09-30 14:39:11 +0000

**Comment by aeblyve** [comment]
Hi:

I can report that it appears that something similar is happening with a fresh install of the nixpkgs 23.11 OrganicMaps.
```
LOG TID(1) WARNING 0.269494 platform/qt_location_service.cpp:117 OnErrorOccurred(): Location error occured QGeoPositionInfoSource::Error code: 0
zsh: segmentation fault (core dumped)  OMaps
```

**Comment by Ferenc-** [comment]
> Hi:
> 
> I can report that it appears that something similar is happening with a fresh install of the nixpkgs 23.11 OrganicMaps.
> 
> ```
> LOG TID(1) WARNING 0.269494 platform/qt_location_service.cpp:117 OnErrorOccurred(): Location error occured QGeoPositionInfoSource::Error code: 0
> zsh: segmentation fault (core dumped)  OMaps
> ```

@aeblyve `23.11`  is from the `2024.02.06-11` release, which doesn't contain the fix https://github.com/organicmaps/organicmaps/pull/7485, which is only in [2024.03.05-4](https://github.com/organicmaps/organicmaps/releases/tag/2024.03.05-4-android). In theory nixkpkgs unstalbe has the latest release.

**Comment by Ferenc-** [comment]
This is not reproducible anymore.
