### ISSUE TITLE
Some occasions where user's location on OM got stuck and not gets updated

### ISSUE THREAD

**Issue by hoizan** [organicmaps/organicmaps#6336]
There have been few occasions when trying the Android beta version 2023.10.15-20-Google-beta, which encountered the  location on the map somehow got stuck and refused to renew to a new position. Location and Google Play Service were both enabled.  Interestingly, the release version 2023.09.22.27-Google running in parallel is working fine.  
Unfortunately,  it happens randomly, and  there is no  obvious triggering point. 

**Expected behavior**
Users' location on map should get timely refreshed   

**Screen Recordings**

1)  Beta_20231018_085458_Organic Maps (Beta)
2)  Released_20231018_085543_Organic Maps
3)  BOTH_20231018_090634_Organic Maps (Beta)  -  @6-24 sec shows switching between 2 versions
4)  Beta_090739_Organic Maps (Beta)_stopped_navi

https://github.com/organicmaps/organicmaps/assets/92556284/5dc910e3-c382-4d8b-9460-5fab348ce372

https://github.com/organicmaps/organicmaps/assets/92556284/bff48c2d-1023-4041-ae51-6f52bc7d28cb

https://github.com/organicmaps/organicmaps/assets/92556284/55602185-92f4-40d1-b278-52c499b31c33

https://github.com/organicmaps/organicmaps/assets/92556284/c0ccf8de-bba4-43d0-9d88-e6b4e8d7d4e2

Log Captured :
1)  app.log 

[app.log](https://github.com/organicmaps/organicmaps/files/12975726/app.log)

**System information:**
 - Android 13
 -  2023.10.15-20-Google-beta
 - Device Model:  Samsung S23 Ultra

**Comment by biodranik** [comment]
@rtsisyk 
On iOS the issue is likely caused by something else. @jumelles it would be great to reproduce it and report separately.

**Comment by rtsisyk** [comment]
> There have been few occasions when trying the Android beta version 2023.10.15-20-Google-beta, which encountered the location on the map somehow got stuck and refused to renew to a new position. Location and Google Play Service were both enabled. Interestingly, the release version 2023.09.22.27-Google running in parallel is working fine. Unfortunately, it happens randomly, and there is no obvious triggering point.
> 

Thanks for reporting this issue. We need to reproduce this problem somehow.

**Comment by rtsisyk** [comment]
> There have been few occasions when trying the Android beta version 2023.10.15-20-Google-beta, which encountered the location on the map somehow got stuck and refused to renew to a new position. Location and Google Play Service were both enabled. Interestingly, the release version 2023.09.22.27-Google running in parallel is working fine. Unfortunately, it happens randomly, and there is no obvious triggering point.
> 
> **Expected behavior** Users' location on map should get timely refreshed
> 
> **Screen Recordings**
> 
>     1. Beta_20231018_085458_Organic Maps (Beta)
> 
>     2. Released_20231018_085543_Organic Maps
> 
>     3. BOTH_20231018_090634_Organic Maps (Beta)  -  @6-24 sec shows switching between 2 versions
> 
>     4. Beta_090739_Organic Maps (Beta)_stopped_navi
> 
> 
> Beta_090739_Organic.Maps.Beta._stopped_navi.mp4
> Beta_20231018_085458_Organic.Maps.Beta.mp4
> BOTH_20231018_090634_Organic.Maps.Beta.mp4
> Released_20231018_085543_Organic.Maps.mp4
> 
> Log Captured :
> 
>     1. app.log
> 
> 
> [app.log](https://github.com/organicmaps/organicmaps/files/12975726/app.log)
> 
> **System information:**
> 
>     * Android 13
> 
>     * 2023.10.15-20-Google-beta
> 
>     * Device Model:  Samsung S23 Ultra

Could you please check if you have or don't have Organic Maps routing notification in the notification bar when this situation happens?

**Comment by hoizan** [comment]
I'm not 100 percent sure, but it seemed that there was a notification during the last occurrence.

**Comment by hoizan** [comment]
Last night after chancing upon #6436, it got me inspired and I managed to reproduce the bug as follows:

1) Set destination and start navigation on the said OM beta version.
2) Swipe out the app, or close it, instead of minimising the app.
3) Reopen OM beta and you can see that the navigation still running, which not supposed to. 
    Nevertheless, the location update was dead since closing of the app at step 2.
4) To restore, stop the navigation and close the app and then reopen it. Evevrything works again.

**Comment by biodranik** [comment]
The grey arrow color in videos means that the GPS position was outdated. @rtsisyk did you check the log?

**Comment by rtsisyk** [comment]
I don't see any issues in the log. Yes, the gray arrow color means that GPS position was outdated. The phone loses GPS signal periodically. It happens. It is not a bug.

The latest 2023.11.17 release periodically dumps info about the number of satellites into log:

```
app.organicmaps.location: LocationHelper.java:91 onSatelliteStatusChanged(): total = 32 used = 0 fixed = false
```

Please try to capture the next moment with the gray arrow with enabled logs. I bet that you will see less than 3-4 required satellites in `used = `.
