### ISSUE TITLE
FAQ update after removing Route button 

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#6344]
After https://github.com/organicmaps/organicmaps/pull/6220 the FAQ needs to be updated

![](https://github.com/organicmaps/organicmaps/assets/47610359/4b6739a3-9812-4105-a2c4-a2d33e4a857e)

**Comment by biodranik** [comment]
Can you please update the data/faq.html? The corresponding paragraph in all languages should be removed.

**Comment by pratyaksh1610** [comment]
Is the line highlighted needs to be removed only ?

**Comment by Priyanshuthapliyal2005** [comment]
can you assign this issue to me??

**Comment by dvdmrtnz** [comment]
They don't usually assign issues in this project. You are free to work on this and submit a PR at any time!
