### ISSUE TITLE
No edit button

### ISSUE THREAD

**Issue by p-hofer** [organicmaps/organicmaps#6351]
**Describe the issue**
When I try to edit a POI, I used to get an "Edit" button when I open a POI and scroll to the bottom. It's not there anymore.

**Steps to reproduce**
1. Login to OSM in Organic Maps.
2. Click on a POI
3. Scroll down
4. There is no way to edit the POI.

**Expected behavior**
There should be a "edit" button.

**Screenshots**
![1000044546](https://github.com/organicmaps/organicmaps/assets/72199018/9d7fb5e3-61b3-4d62-b589-e590113bc2e7)
![1000044547](https://github.com/organicmaps/organicmaps/assets/72199018/d738be4e-bb64-4d92-8942-7d541eb474ab)

**System information:**
 - Operating system and its version: Android 9
 - Organic Maps version: 2023.08.18-8-FDroid
 - Device Model: Cyrus CS45XA

**Comment by Jean-BaptisteC** [comment]
Did you have the latest version of maps ?

**Comment by biodranik** [comment]
@arnaudvergnet we should indicate somehow that editing is not available until the map is not updated. Do you have any ideas on how to do that nicely?

**Comment by p-hofer** [comment]
@Jean-BaptisteC I have the newest data. I have even tried to re-install OM and therefore also re-download the data. Same issue.

**Comment by biodranik** [comment]
@p-hofer that is very strange. It works on our devices. Can you please share the screenshot of your About screen (bottom left button on the map) and the screenshot of your download maps dialog from the menu?

**Comment by p-hofer** [comment]
It also works on my other device (Pixel 6a), but not with the one mentioned in this issue. Here are the 2 screenshots:

![1](https://github.com/organicmaps/organicmaps/assets/72199018/bbf261fc-2051-4aed-85df-34286344bb06)
![2](https://github.com/organicmaps/organicmaps/assets/72199018/b371b0ee-e175-4136-9dc3-97f0e12bb767)

**Comment by p-hofer** [comment]
One more thing: Editing worked well previously. It stopped working ~2 weeks ago.

**Comment by Jean-BaptisteC** [comment]
Latest version is 2023.09.22-27-FDroid :)

**Comment by p-hofer** [comment]
Oh. Thank you so much for your quick reply, I missed the update. After updating the app + refreshing the maps everything works as expected!

Maybe a nice way of showing that you can't edit stuff is to show a text (á la "You can't edit this place as there are map updates available. Please update your app and map.") instead of the button. Since you have to actively scroll to this location, it probably will not clutter the UI.

**Comment by Jean-BaptisteC** [comment]
We have already issues to discuss how to tell to users that the map cannot be edited because they don't have the latest version of app.
I close the issue

**Comment by biodranik** [comment]
Interesting, I don't remember that we have code that prohibits edits in older app version. It can be possible only if a newer version was installed on top of the older one and then older one is installed back.

**Comment by richlv** [comment]
Hi, regarding "We have already issues to discuss how to tell to users that the map cannot be edited because they don't have the latest version of app" - could those please be linked to here? Would love to check on how that aspect works.
