### ISSUE TITLE
z20 is disappearing on latest master

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#6356]
When zooming in to z20 all the map disappears on app built from latest master.

https://github.com/organicmaps/organicmaps/assets/47610359/ff2f27d8-6909-44d5-9d58-fba6677d9c84

**Comment by Jean-BaptisteC** [comment]
Maybe need a regeneration of maps, yet see on latest beta

**Comment by biodranik** [comment]
@dvdmrtnz can you please check the master + commits from this branch? https://github.com/organicmaps/organicmaps/pull/6295

**Comment by dvdmrtnz** [comment]
> @dvdmrtnz can you please check the master + commits from this branch? #6295

@biodranik, still the same behavior

**Comment by dvdmrtnz** [comment]
I retested after last merges and it seems to be fixed. It seems to have been something related to https://github.com/organicmaps/organicmaps/pull/6359. Closing this now
