### ISSUE TITLE
[editor] Organic Maps creates anonymous notes

### ISSUE THREAD

**Issue by deevroman** [organicmaps/organicmaps#6360]
**Describe the issue**
In Organic Maps you can't make edits if you are not logged in to OSM. 
But OSM allows you to create anonymous notes. If I understand correctly, Organic Maps should not create such notes.

Here is an example of the last notes and their full list:
https://www.openstreetmap.org/note/3950263
https://www.openstreetmap.org/note/3948233

[anon_organic.csv](https://github.com/organicmaps/organicmaps/files/13060990/anon_organic.csv)

**Comment by biodranik** [comment]
Why OM should not create anonymous notes?

**Comment by deevroman** [comment]
Is there such an option? Whenever I specify something in OM without authorisation I am prompted to log in to my OSM account.

**Comment by biodranik** [comment]
You may login, but also may not login.

**Comment by map-per** [comment]
Looks like this is related to #1386
