### ISSUE TITLE
[android] Broken TTS on LeEco Le2 (x620)

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#637]
LeEco Le2 (x620)
https://www.gsmarena.com/leeco_le_2-8053.php

https://vc.ru/services/260687-sozdateli-maps-me-zapustili-servis-organic-maps-s-oflayn-kartami-bez-trekerov-i-registracii?comment=2933029

**Comment by ooprizrakoo** [comment]
> Извините, баг не подтвердился. Сегодня поставил в машину - все работает. Не шла озвучка, поскольку в позиционировании дом находится в 20м от асфальта, а озвучка идет при движении по маршруту.
