### ISSUE TITLE
[iOS][CarPlay] Missing distance, speed, and ETA

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#6380]
I didn't have a chance to find how to reproduce this issue, but it happened at least two times while driving:

![IMG_2235 copy 2](https://github.com/organicmaps/organicmaps/assets/1799054/d9f43af2-6853-4f4e-b268-d9a746e48222)

**Comment by dvdmrtnz** [comment]
Same here. Also somehow arrival time is before current time? 🤔😂

![](https://github.com/organicmaps/organicmaps/assets/47610359/d837e9d6-d72f-4aab-b4a5-efcb82930b97)

**Comment by biodranik** [comment]
This should be fixed.
