### ISSUE TITLE
Ski piste areas rendered wrong

### ISSUE THREAD

**Issue by j5k** [organicmaps/organicmaps#6391]
Organic Maps
![Screenshot_20231024-225713](https://github.com/organicmaps/organicmaps/assets/12898013/c8b6d742-acfe-40dd-97ee-9df9041c4788)

OsmAnd
![Screenshot_20231024-230015](https://github.com/organicmaps/organicmaps/assets/12898013/c6b13659-2d05-493c-9ea4-51f130b02de0)

OpenSnowMap
![Screenshot_20231024-230135](https://github.com/organicmaps/organicmaps/assets/12898013/fc1eae56-4cf6-46b9-9c53-e808c1aada32)

**Comment by patepelo** [comment]
Can you please elaborate what is missing in OM? The area? Colour? Direction? Name? Ref?

**Comment by map-per** [comment]
The screenshot are from this location (https://www.openstreetmap.org/way/104021975) and the OSM data is correct

**Comment by pastk** [comment]
Looks like yellow trails are rendered in black in OM.

**Comment by pastk** [comment]
Need to add support of e.g.
```
area=yes
piste:difficulty=easy
piste:type=downhill
```
ATM OM supports linear pistes only (`area=yes` is ignored).


And the yellow/orange piste is `piste:difficulty=freeride` but OM atm uses black for it (same as for `piste:difficulty=expert`).

**Comment by biodranik** [comment]
@pastk it would be great to fix it ASAP, considering that the season starts soon )

**Comment by VladimirMorozov** [comment]
IMO it's not that bad. I've used OM a few times while skiing and when I see 3 lines I know that one is centerline and the others are outlines. It would be good to have areas rendered differently, but IMO it's not that bad to have it prioritized for the season. It was a lot worse having those lines dissapear altogether at low zoom levels and leaving you without overview. But unless you'll make a separate ski layer, I'm not sure they should be emphasized from afar for everyone.

**Comment by habi** [comment]
I've also seen this the past weekend [1] in Zermatt, or Cervinia.

- http://opensnowmap.org/#map=18/7.69/45.946&b=snowmap&m=false&h=false
- https://www.openstreetmap.org/way/399074834/

![IMG_6409](https://github.com/organicmaps/organicmaps/assets/1651235/8ff9af0c-4db0-43d4-8f4e-e120ec061308)

Would it be possible to render `area=yes` pistes like rivers?

[1]: Thanks for making OrganicMaps an awesome all-around App for navigating! I was able to find my way in a ski-resort I never was before :)

**Comment by pastk** [comment]
Yes its possible of course (see https://github.com/organicmaps/organicmaps/issues/6391#issuecomment-1781806452). Its just no one is working on it at the moment.
