### ISSUE TITLE
Make adding new addresses possible

### ISSUE THREAD

**Issue by map-per** [organicmaps/organicmaps#6394]
Currently you can only edit existing addresses but can't add new ones.

**Comment by matheusgomesms** [comment]
Well, technically you can, but only in a building (not creating a new node). For this purpose, I migrated to EveryDoor to add addresses.

**Comment by biodranik** [comment]
Addresses can be added not only for the existing buildings but also in newly created POIs.

1. Why is it important to add (invisible?) address nodes on the map, not bound to any feature?
2. How to render these addresses on the map?
3. Won't users not familiar with OSM do something wrong if it is implemented?

**Comment by map-per** [comment]
Address nodes are visible on OM, but they are classified as `building` which would be confusing if we allow editing them.

What I forgot, however, is that address editing conventions varie from country to country, so some countries don't want separate address notes if there is already a shop. Therefore im closing the issue.

**Comment by biodranik** [comment]
@map-per let's list here (or in another related issue) contry-specific addressing issues to have them in mind.

**Comment by matheusgomesms** [comment]
This is not trivial, and quite complex. This is how iD addresses it: https://github.com/openstreetmap/iD/blob/develop/data/address_formats.json

Almost every country has a different format to input addresses, and many are still lacking: https://github.com/openstreetmap/iD/issues?q=is%3Aissue+address+is%3Aopen

**Comment by pastk** [comment]
- related to #2371
