### ISSUE TITLE
Weird rendering of roads in navigation

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#6398]
https://omaps.app/0n_TzlKvsl

om://0n_TzlKvsl

![IMG_3383](https://github.com/organicmaps/organicmaps/assets/47610359/aec8cf30-e09f-41c8-9277-011f6097e1ea)

**Comment by Jean-BaptisteC** [comment]
Circles are OSM nodes?
Maybe problem about simplification ?

**Comment by biodranik** [comment]
@vng @pastk I had the same issue today in iOS master.

**Comment by vng** [comment]
https://github.com/organicmaps/organicmaps/pull/6208 PR introduced a bug. And only on iOS.

**Comment by vng** [comment]
Maybe I missed some terminology, but the fix didn't return geometry for joints.
- I commented m_joinGeom routine as unused
- Actual fixes are [here](https://github.com/organicmaps/organicmaps/pull/6208/files#diff-7507ea303c77e7720b7d897fada1e74b1b42b839ef95d4d508a8d83c46050983L180) and [here](https://github.com/organicmaps/organicmaps/pull/6208/files#diff-7507ea303c77e7720b7d897fada1e74b1b42b839ef95d4d508a8d83c46050983L199)

The code filled m_capGeometry for joins. See SubmitJoin. But it didn't process caps properly like it should. In combination of ButtCap + RoundJoin.

**Comment by biodranik** [comment]
@rokuz maybe shaders should be fixed too?

**Comment by vng** [comment]
Forget about my changes. Take here https://github.com/mapsme/omim/blob/master/drape_frontend/line_shape.cpp, I put here some significant parts that are strange on my point of view:
```
dp::BindingInfo const & GetCapBindingInfo() override
  {
    if (m_params.m_cap == dp::ButtCap)
      return TBase::GetCapBindingInfo();

    static std::unique_ptr<dp::BindingInfo> s_capInfo;
    if (s_capInfo == nullptr)
    {
      dp::BindingFiller<CapVertex> filler(3);
      filler.FillDecl<CapVertex::TPosition>("a_position");
      filler.FillDecl<CapVertex::TNormal>("a_normal");
      filler.FillDecl<CapVertex::TTexCoord>("a_colorTexCoords");

      s_capInfo.reset(new dp::BindingInfo(filler.m_info));
    }

    return *s_capInfo;
  }

  dp::RenderState GetCapState() override
  {
    if (m_params.m_cap == dp::ButtCap)
      return TBase::GetCapState();

    auto state = CreateRenderState(gpu::Program::CapJoin, m_params.m_depthLayer);
    state.SetDepthTestEnabled(m_params.m_depthTestEnabled);
    state.SetColorTexture(m_params.m_color.GetTexture());
    state.SetDepthFunction(dp::TestFunction::Less);
    return state;
  }

  void SubmitJoin(glsl::vec2 const & pos)
  {
    if (m_params.m_join == dp::RoundJoin)
      CreateRoundCap(pos);
  }

  void SubmitCap(glsl::vec2 const & pos)
  {
    if (m_params.m_cap != dp::ButtCap)
      CreateRoundCap(pos);
  }
```

So middle join points are processed _differently_ for line with ButtCap + RoundJoin and for line with say RoundCap + RoundJoin. Is it intended to be like this? My fix makes this processing in the same way. Problem in ```if (m_params.m_cap == dp::ButtCap)```

**Comment by vng** [comment]
So the question is: if we put joins into m_capGeometry, should they also be drawn like gpu::Program::CapJoin ?

**Comment by vng** [comment]
And second question: maybe it is silly, but why do we can't draw circle joints for body and outline? If we are sure that outline's depth is lower than body's depth? Otherwise, we have artifacts in joints for lines with outline that I was trying to fix (bridges). Moreover, it works ok everywhere except iOS navigation mode. So, my initial assumption was about depth problems ..

**Comment by vng** [comment]
Yes, iOS artifacts are on literally every line in 3D. On Android and desktop I don't see artifacts.

And original code does **not** process joints as program::CapJoin for ButtCap + RoundJoin (this is the most used combo for highways). Joints are added into m_capGeometry vector, but processed as TBase::GetCapState

**Comment by vng** [comment]
> we didn’t generate joins if line had butt cap
We do actually.

**Comment by vng** [comment]
We will be grateful if you will have a chance to look deeper here. Thanks!

**Comment by vng** [comment]
I can't say for sure now, but looks like we don't (and didn't) have RoundCap+RoundJoin combo in styles at all .. Maybe in some overlays only, but I'm not sure.

**Comment by vng** [comment]
> Will it change anything?

No solid highways visible at all. Only dashed lines.
![telegram-cloud-photo-size-2-5328059011641233144-y](https://github.com/organicmaps/organicmaps/assets/175612/0bdee88a-b3c5-4ec1-bd8f-df3d589457dc)

**Comment by vng** [comment]
| MM (Line program for Joins) | OM original code (Line program for Joins) | OM no Joins at all | OM with fix (CapJoin program for Joins)
| ------------- | ------------- | ------------- | ------------- |
| ![telegram-cloud-photo-size-2-5328059011641233148-y](https://github.com/organicmaps/organicmaps/assets/175612/fd7be74f-e592-47e1-8c0e-1dd3d3f7eb6f) | 
![telegram-cloud-photo-size-2-5328059011641233150-y](https://github.com/organicmaps/organicmaps/assets/175612/b5a7d0f3-dbd4-41b4-a98a-097f284dd409) | 
![telegram-cloud-photo-size-2-5328059011641233147-y](https://github.com/organicmaps/organicmaps/assets/175612/9b62db8a-e8d9-4d29-97d8-9400a66539d2) | 
![telegram-cloud-photo-size-2-5328059011641233149-y](https://github.com/organicmaps/organicmaps/assets/175612/1e9b2c05-b1f6-4a5f-8ccd-6df6dfb945d1)
