### ISSUE TITLE
[FR] Add a new visual indication for the map orientation when it locked on North

### ISSUE THREAD

**Issue by GLLM** [organicmaps/organicmaps#640]
Hi !

when looking at maps, the map orientation compass icon does not enable to tell if your map is currently displayed locked on North or if it havs been manually re-oriented by the user.

I believe there are only 3 possibilities :
- map display is locked on North
- map display is following the device orientation (like often done when driving or following route instructions)
- maps has been manually oriented because the user wants it like this.

and that the missing one is a clear "locked on North" icon.

However when pressing the orientation, the switch between locked on North & device orientation is working fine. Just the locked on North icon could be changed to be clearer.

What's your opinion about this ?

Thanks
GLLM

**Comment by biodranik** [comment]
Maybe I don't understand the issue. Why do you need some additional icon that says "north is up", if it's the default state of any map?

**Comment by GLLM** [comment]
Closing this issue because I now do see what I wanted, at the time.
Sorry for the noise.
