### ISSUE TITLE
Add new icon for Clinic to differentiate from Hospital

### ISSUE THREAD

**Issue by patepelo** [organicmaps/organicmaps#6400]
![Image](https://github.com/organicmaps/organicmaps/assets/23003127/958f621c-6d10-4994-81df-7e43eb3a5b6a)

Discussions from developers, leave the cross for hospital and look for a new for clinic.

Ideas:  A stethoscope

More ideas are needed.

**Comment by biodranik** [comment]
Agree about the importance of the `emergency_ward_entrance`. That's what you need to find quickly when every second may be important.

**Comment by pastk** [comment]
Maybe just use the existing "main entrance" icon but colored in red.

**Comment by dvdmrtnz** [comment]
Stethoscope icon from Fontawesome looks nice

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/55e54129-5b8a-4fe8-99a3-75b5b73b26fc" width="36"/>


https://fontawesome.com/icons/stethoscope?f=classic&s=solid

**Comment by biodranik** [comment]
It's not too recognizable :(

**Comment by dvdmrtnz** [comment]
Some proposals:

1. <img src="https://github.com/organicmaps/organicmaps/assets/47610359/2055b2e7-c17b-4f18-a34b-e9a9db8f9360" width="36"/>

2. <img src="https://github.com/organicmaps/organicmaps/assets/47610359/350086b2-1fa8-480d-aa7a-f6fff7b4428c" width="36"/>

3. <img src="https://github.com/organicmaps/organicmaps/assets/47610359/5b957d2a-0ff6-4ba8-b438-ed3c1cbe6af8" width="36"/>

**Comment by patepelo** [comment]
Is great but still too similar to current hospital.

Maybe to add a more distant difference, we can also change the hospital to be something inspired in this:
![image](https://github.com/organicmaps/organicmaps/assets/23003127/ecd60140-f14d-49b0-9852-8c4e7d351ab8)

Hospitals are often represented as houses as well. 

WDYT?

**Comment by patepelo** [comment]
Hospital looks good that way as well. The clinic looks like a first aid kit, but it should be alright. I don't have better ideas.

 And I don't find it that critical that they are similar with each other. In many countries the line to differentiate both is often very thin.
