### ISSUE TITLE
Build fails with "unknown target 'desktop'"

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#6401]
It happens after building the `generator_tool` target (which doesn't have qt positioning enabled).

To reproduce (current master)
```
$ tools/unix/build_omim.sh -r desktop
# Builds fine

$ tools/unix/build_omim.sh -r generator_tool
# Builds fine

$ tools/unix/build_omim.sh -r desktop
...
ninja: error: unknown target 'desktop'
```

Looks related either to 
- #6244
- or #6054 

FYI @Ferenc-

**Comment by Ferenc-** [comment]
Hmm it appears a `cmake` run has been missing from the very beginning.

**Comment by Ferenc-** [comment]
@pastk could you test the above PR?
