### ISSUE TITLE
Reduce size of layer bottom sheet

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#6409]
Actually, layer bottom sheet takes up a lot of space in landscape on phones and tablets. I suggest reducing size of bottom sheet, by removing unused spaces between elements and maybe create new layout for the landscape.
This change could be beneficial when we add a new layer. (Outdoors layer for example)

|Landscape phone|Portrait tablet|Landscape tablet|
|-|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/be91aaf6-b6ad-4021-92b4-8bc75c3abc74" height=100 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/6d9b1af2-7ed1-4185-b082-03932b2c4389" height=300 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/6f615de3-b3bb-426b-a4fe-850e584eb3ce" height=300 />|

**Comment by Misalf-git** [comment]
Could it be replaced with a circular menu like in navigation?
![Screenshot_Organic_Maps_quicksearch.png](https://github.com/organicmaps/organicmaps/assets/72605561/824a08d8-54c6-4ead-a827-af151b3d3d68)

**Comment by Jean-BaptisteC** [comment]
With current icons, that's not enough recognizable let's focus to save space on the screen.

**Comment by biodranik** [comment]
It may make sense to finalize the layers/styles UX/UI first before refactoring this one.

Circullar menu also looks good, but I assume that all planned layers won't fit there.

@pastk can you please link relevant issues?

**Comment by rtsisyk** [comment]
> Actually, layer bottom sheet takes up a lot of space in landscape on phones and tablets. I suggest reducing size of bottom sheet, by removing unused spaces between elements and maybe create new layout for the landscape. This change could be beneficial when we add a new layer. (Outdoors layer for example)
> Landscape phone 	Portrait tablet 	Landscape tablet
> <img alt="" height="100" src="https://user-images.githubusercontent.com/87148630/278859942-be91aaf6-b6ad-4021-92b4-8bc75c3abc74.png"> 	<img alt="" height="300" src="https://user-images.githubusercontent.com/87148630/278859808-6d9b1af2-7ed1-4185-b082-03932b2c4389.jpg"> 	<img alt="" height="300" src="https://user-images.githubusercontent.com/87148630/278859725-6f615de3-b3bb-426b-a4fe-850e584eb3ce.jpg">

The current layer selection doesn't look convinient anyway. Let's finalize UX for the new styles feature @pastk works on, maybe it fixes the issue.
