### ISSUE TITLE
Remove useless menu

### ISSUE THREAD

**Issue by ghost** [organicmaps/organicmaps#6418]
Hello!

Can you remove this from the menu?
![IMG_0997](https://github.com/organicmaps/organicmaps/assets/149334202/53004243-aabd-4b74-8f54-bb3de85ca43a)

It is already been added in the top left corner:
![IMG_0999](https://github.com/organicmaps/organicmaps/assets/149334202/e3774be1-941b-4854-a862-f65fc3f34b5b)

And if you will click on it the same menu will appear:
![IMG_0997](https://github.com/organicmaps/organicmaps/assets/149334202/0d94a4ca-7ab9-4857-b4d4-f056ef061fe0)

**Comment by dvdmrtnz** [comment]
* Same as https://github.com/organicmaps/organicmaps/issues/5090

**Comment by rtsisyk** [comment]
I am closing this ticket as a duplicate. Please add your ideas to #5090.
