### ISSUE TITLE
"Bank" vs "Bench" in Spanish 

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#6423]
In Spanish, "Bank" and "Bench" are written the same way: "Banco". This causes some problems:

1. Selecting Bank category from search menu causes both Banks 👍 and Benches 👎 to show in the results:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/1fb9e5eb-16f0-4489-83ff-2d1286516628" width="320"/> <img src="https://github.com/organicmaps/organicmaps/assets/47610359/1bb9a3ae-bd2e-47b6-8985-4b65a2f0bd0e" width="320"/>

2. When adding a new POI there’s no way to distinguish Bank vs Bench:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/26988fdb-0a2f-4bef-bc8d-bf7dbff1c25b" width="320"/>

**Comment by patepelo** [comment]
Good point. Maybe translate bench into another synonym. Like "Banquillo", "Asiento", "Banqueta".  I can ask in the spanish-latin community to survey what substitution could be better.

**Comment by patepelo** [comment]
Or maybe translating the bank to "Entidad Bancaria"? I'm more for the bench as most users won't be searching for a bench.

**Comment by matheusgomesms** [comment]
In Portuguese both translations are exactly the same as in Spanish. However, in OM we display Assento (assiento in ES), even when the search term is "Banco".

![IMG_1080](https://github.com/organicmaps/organicmaps/assets/86851490/1050146b-2e4c-45bd-b207-26f6b909d710)

**Comment by matheusgomesms** [comment]
What could probably be improved is, when one user search for the category Banco (Bank), the result should be only banks (going for the tags), not the term "banco". Whey typing, then probably OM can't distinguish on the search, only in the results.

**Comment by Lewatoto** [comment]
Why don't use "banca" https://dle.rae.es/banca since it's like a synonym of "banco"

**Comment by patepelo** [comment]
I've asked in the spanish community and the word proposed is "Asiento". 

> Why don't use "banca" https://dle.rae.es/banca since it's like a synonym of "banco"

"Banca" can also be mixed with bankin as per definitions: 

> 2. f. Actividad económica de operaciones financieras que se realiza por medio de los bancos.
> 
> 3. f. Conjunto de entidades bancarias.


Let's change to "Asiento" in the translations like the portugues have done.

**Comment by muralito** [comment]
And also "Banca" is mostly used as "the house" in gambling, or lottery.

BTW, most probably the search for "Banco" is looking for a financial service.  When looking for a place to rest, i don't search for "banco", I search for "parque", "plaza", "iglesia" (the are lot of banks in churches, and they are quiet and cooler places in the summer :-) ) 

There are two separate problems IMO.
The search for categories "Banco" (and the icon with house and $) should only retrieve amenity=bank elements (and maybe another financial services). Also when you search for "Banco".
but, in the list, maybe it's more clear to translate "amenity=bank" as "Entidad bancaria" o "Entidad financiera".

Related to this problem, is the search for amenity=payment_centre which in the last 10-20 years has become common in LATAM, and provide a lot of useful services, from simple banking services (deposits and withdrawals from bank accounts) to payment of bills, to selling tickets for events or soccer matches, and depending on the country some of them exchange money or give small loans.
IMO this kind of amenity deserves a category in itself, at least in LATAM.

That brings two ideas to the categories search list:
1. for me it would be useful that i can order the list, so i can put my most used categories on top.
2. maybe the categories list can or should be dependent on the country (add or hide items or reorder them)

**Comment by biodranik** [comment]
Current implementation allows to separate 1) displayed titles from 2) search terms.

1. Please decide on what should be displayed to users and edit it in data/strings/types_strings.txt
2. Duplicate the same terms from types_strings.txt for the search in data/categories.txt, and also add popular synonyms there (for search only), and also add payment_centre if necessary.

**Comment by fmrtn** [comment]
The word _banco_ for financial meaning refers to whole company. The places that customers visits are _sucursales_ or better _**sucursal bancaria**._ Also know as office _oficina bancaria_

**Comment by patepelo** [comment]
1. Let's go with "asiento" only translation (never using "banco" in that context. There is no need to add further synonyms in the search since it isnt expected for people to search for these. 

For the bank institution let's keep go with "sucursal bancaria" as main label and "banco", "oficina bancaria" as synonyms just for the search.

**Comment by patepelo** [comment]
> Related to this problem, is the search for amenity=payment_centre which in the last 10-20 years has become common in LATAM, and provide a lot of useful services, from simple banking services (deposits and withdrawals from bank accounts) to payment of bills, to selling tickets for events or soccer matches, and depending on the country some of them exchange money or give small loans.
> IMO this kind of amenity deserves a category in itself, at least in LATAM.

Thanks for bringing this out. I'm doing a research of lesser known tags that are not common in europe to represent other regions and I will definitly add this one. I'll propose it as a separate tag.

>That brings two ideas to the categories search list:

>for me it would be useful that i can order the list, so i can put my most used categories on top. maybe the categories list can or should be dependent on the country (add or hide items or reorder them)

On this, I invite you to create a sepparate discussion to handle this broader necesitty.

**Comment by xephos1one** [comment]
In German a "Bank" is also both - a bank and a bench.
In OM a bench is already called a "Parkbank" (park bench).

But in my opinion benches should not be searchable at all as it's not really a destination.
This removes the whole issue and also removes a bit of clutter in the overall search results.

**Comment by biodranik** [comment]
I've been searching for benches very often since I added this feature in 2011. It is useful when you hike or walk in a park and want to rest, have a picnic, feed your children, see how well the area is developed or mapped to add missing benches, etc.

**Comment by xephos1one** [comment]
> I've been searching for benches very often since I added this feature in 2011.

Now it would be interesting how many actual end users search for benches.

> It is useful when you hike or walk in a park and want to rest, have a picnic, feed your children

Who does that instead of just using their eyes and using a bench that's along their way (e.g. to a real destination)?
As benches don't have names as an end user I wouldn't know which bench to pick from the list and instead pick a bench I like from the map and start routing to a bench that way and not via the search.

> see how well the area is developed or mapped to add missing benches, etc.

Is OM supposed to be a quality assurance tool or a maps app for end users?
I also don't see how removing benches from the search would affect this point.

**Comment by biodranik** [comment]
Of course, I'm looking for benches on the map, not in the list (although rarely a list is also useful).

Instead of fixing the translation issue for a few languages, you're trying to change/break the existing UX. The goal of OM is to be able to find _anything_. And to teach users that they can search for _anything_. Try to find a bench on Google Maps or some other maps.

**Comment by matheusgomesms** [comment]
I created a PR (#6489) to solve at least the search part. It will:

1 - if user searches for "Banco" (category or typing it), it will appear both Banks and Benches
1.1 - however, benches will be displayed as "Asiento"
2 - if user searches for "Asiento", only benches will be displayed
3 - Bench POI will be added under the name "Asiento" (no more confusion between _Banco_ and _Banco_)


For the search category part, I believe a new issue should be opened for better discussion, since it spans several languages.

**Comment by patepelo** [comment]
Thank you

> 1 - if user searches for "Banco" (category or typing it), it will appear both Banks and Benches

Thank you. Although as a spanish speaker, I believe "Banco" should only give you results for banks and not benches.

**Comment by biodranik** [comment]
The issue with "bank or bench?" is still there, at least for Portuguese. Need to double-check if translations/search were not broken also for Spanish and German.

- Category search button with bank icon should be solved by using the unique synonym for this case, that is _not_ applied for the bench in categories.txt
- Displayed names/translations of type/category can be augmented to clearly distinguish a financial institution from a bench, either using emoji or different translation terms in types_strings.txt
- All search synonyms should be correctly listed in categories.txt
