### ISSUE TITLE
Bus Stops: Separate stop position from platform

### ISSUE THREAD

**Issue by patepelo** [organicmaps/organicmaps#6428]
Let's create a separate issue for stop position, with the best examples form other apps.

_Originally posted by @biodranik in https://github.com/organicmaps/organicmaps/discussions/6275#discussioncomment-7433469_

**Comment by patepelo** [comment]
![image](https://github.com/organicmaps/organicmaps/assets/23003127/af795fdf-e162-491e-bcf9-2bf3fee90855)
Currently, they are both mixed.

A road map for incorporating bus transport in OM is first to be able to look up in the node of the stop position and find the lines listed that go trhough there from the relation of the stop position.

According to the wiki and well mapped bus routes relations, both are in the relation as stop and as platform so it's feasible to load the lines from both type of nodes.

The question is: Do we want to represent them differently? Maybe just the one to be of a higher priority in broader zoom levels to avoid duplicate icons and the other on the last zoom in. Differentiate them on the title of the card only?

### Bench mark of OSM based apps --> Screenshots

Osmand
![image](https://github.com/organicmaps/organicmaps/assets/23003127/a1ee4dcf-75c2-45d6-acbb-2ade720a270c)
![image](https://github.com/organicmaps/organicmaps/assets/23003127/9f76b889-3aa1-4998-9309-e5729fcdd08d)

Mapy.cz
![image](https://github.com/organicmaps/organicmaps/assets/23003127/53690de9-809f-49ff-bdbf-9e4d13c20034)
![image](https://github.com/organicmaps/organicmaps/assets/23003127/fb9630fd-8b1b-4593-847f-cd24bbf9c4ae)
![image](https://github.com/organicmaps/organicmaps/assets/23003127/82e445a6-860d-4cb1-a610-7066f3f3226f)

### Bench mark of non-OSM based apps --> Screenshots
CityMapper
![image](https://github.com/organicmaps/organicmaps/assets/23003127/f8acdf25-448f-464a-a1b7-e1e9bc7c8ba1)
Moovit
![image](https://github.com/organicmaps/organicmaps/assets/23003127/22205b16-699b-4850-bd07-a6eb62d754cd)
GMaps
![image](https://github.com/organicmaps/organicmaps/assets/23003127/1626ca97-1c3c-4abe-b6a4-d848920a0c56)

**Comment by map-per** [comment]
OM displays the location of `highway=bus_stop`. For each bus stop side `bus_stop` should only be tagged once, either on the `stop_position` or the `platform` (or sometimes as a separate node). But there is no consensus about which of these options is best.

So your example with two icons looks like an OSM data error.

**Comment by matheusgomesms** [comment]
The stop_position node has an extra tag: highway=bus_stop. This should not be there.

I agree on displaying the lines on the bus stop, but the tag is wrong (in the whole region, it seems to me). When tagged correctly, OM does not display both stops.

**Comment by patepelo** [comment]
Looks then like a task for the OSM community. I believe the wiki is not clear and maybe the translation is not accurate. Where would the stop be place preferably, on the route or on the platform?

**Comment by matheusgomesms** [comment]
> Looks then like a task for the OSM community. I believe the wiki is not clear and maybe the translation is not accurate. Where would the stop be place preferably, on the route or on the platform?

Indeed, the wiki is a bit confusing. However, it seems in BCN the stop position has this extra tag.

Please take a look [here as an example](https://www.openstreetmap.org/#map=19/40.18636/-8.41295). The highway=bus_stop is the "platform" (where exactly passengers wait for the bus, like the shelter or where the pole is located), so it usually mapped on the sidewalk. The stop_position is where the bus stops, a node placed on the highway line. Usually both nodes are placed close to each other (see example).

**Comment by patepelo** [comment]
Thank you. It seems it is a problem from the community, so I will give them notice and proceed to close this issue.
