### ISSUE TITLE
Add 'Drinking water' sources as a default category

### ISSUE THREAD

**Issue by Marskiner** [organicmaps/organicmaps#643]
Hi guys,
I've noticed that there's no predefined category for the drinking water sources. 
I think it could be a great resource especially for hikers, walkers and why not, also for all those who want to refill their water bottle to reduce the amount of plastic in the world and give a small contribution to the planet.

Attached a picture showing how they are displayed in OM
![DrinkingWater_OM](https://user-images.githubusercontent.com/81854689/122636847-accdea00-d0eb-11eb-8846-26a6121d8b78.png)

**Comment by pastk** [comment]
Its being done in #1621
