### ISSUE TITLE
[android] Green circle around the app icon in Android 14

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#6434]
Android 14 API=34

<img width="288" alt="image" src="https://github.com/organicmaps/organicmaps/assets/1799054/606e1727-345e-4a3f-a24f-bfe3876acb39">

**Comment by Jean-BaptisteC** [comment]
Not reproduced on Pixel 6

**Comment by rtsisyk** [comment]
Youtube has an orange icon... it looks like that an indication that the app is running.

**Comment by j13m126** [comment]
It is not an indication that the app is running, but that it is suggested by an algorithm. You can disable this suggestions in the settings.
![Screenshot_20231101-085826.png](https://github.com/organicmaps/organicmaps/assets/7961926/43efa044-bea4-41c5-aebb-f8c21480861c)

**Comment by Jean-BaptisteC** [comment]
Yes, It was implemented with Android 13

**Comment by rtsisyk** [comment]
Weird. Do we have any control over the color?

**Comment by Jean-BaptisteC** [comment]
Android choose color following category of app, Google Maps have green circle
