### ISSUE TITLE
Crash when rotate device and Google Play services is present

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#6443]
**Steps to reproduce**
1. Start OM
2. Use location button -> Google Play services dialog appears
3. Rotate device -> Crash

```
E  vulkan/android_vulkan_context_factory.cpp:428 GetWidth(): CHECK(IsValid()) 
A  /home/runner/work/organicmaps/organicmaps/android/app/src/main/cpp/app/organicmaps/vulkan/android_vulkan_context_factory.cpp:428: int android::AndroidVulkanContextFactory::GetWidth() const: assertion "false" failed
A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4074 (ganicmaps.debug), pid 4074 (ganicmaps.debug)
A  Cmdline: app.organicmaps.debug
A  pid: 4074, tid: 4074, name: ganicmaps.debug  >>> app.organicmaps.debug <<<
A        #02 pc 00000000020a31a4  /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/lib/arm64/liborganicmaps.so (android::AndroidVulkanContextFactory::GetWidth() const+252) (BuildId: 9779bba2ddb5b7f256a597a3097fddfd2774f86d)
A        #03 pc 00000000020a4020  /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/lib/arm64/liborganicmaps.so (android::Framework::Resize(_JNIEnv*, _jobject*, int, int)+92) (BuildId: 9779bba2ddb5b7f256a597a3097fddfd2774f86d)
A        #04 pc 00000000020b39a0  /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/lib/arm64/liborganicmaps.so (Java_app_organicmaps_Map_nativeSurfaceChanged+60) (BuildId: 9779bba2ddb5b7f256a597a3097fddfd2774f86d)
A        #10 pc 000000000000f728  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk!classes4.dex] (app.organicmaps.Map.onSurfaceChanged+0)
A        #15 pc 000000000000f218  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk!classes4.dex] (app.organicmaps.MapFragment.surfaceChanged+0)
A        #74 pc 0000000000253788  [anon:dalvik-classes.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk] (androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild+0)
A        #79 pc 000000000025419c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk] (androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild+0)
A        #84 pc 000000000025411c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk] (androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout+0)
```

**Expected behaviour**
Rotate device doesn't generate crash

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: [2023.11.01-5-Web-debug](https://github.com/organicmaps/organicmaps/actions/runs/6718577174)
 - Device Model: Pixel 6

**Comment by biodranik** [comment]
Can't reproduce it on Samsung Android 13. Is it Android 14-only bug?

The first step is to disable location in the system, right?

**Comment by Jean-BaptisteC** [comment]
Yes only on Android 14, not reproduced on Samsung Galaxy Tab S6 Lite - Android 13
Yes, I consider when I start OM, the location is disabled

**Comment by biodranik** [comment]
@rtsisyk did you try to reproduce it?

**Comment by rtsisyk** [comment]
I can't repro this issue on emulator. 

[Screen_recording_20231117_100853.webm](https://github.com/organicmaps/organicmaps/assets/1799054/d2e946a7-c3b8-432d-8ff3-d453ca3eaa48)

I doubt that this crash in OpenGL is caused by the Google dialog itself. It is more likely that it is some bug in Android and/or Google Services. I remember that we had a similar issue with AlertDialog which generated weird stack traces on re-creation of the activity. Probably we should cancel Google dialog when activity is stopped, but I don't see any method to do that.

Let's wait for Android 14 ROMs for real devices to debug this issue. I still don't have it on Pixel 4a. As you can see, it is really difficult to use the emulator because "System UI is not responding" error pops up literally every second. For now, it is not a blocker for the release because it is not a regression but rather a new issue caused by enabled Android 14 support.

**Comment by rtsisyk** [comment]
I will wait until CalyxOS finishes their work to support Pixel4 a or until I get another device that can run Android 14.

**Comment by Jean-BaptisteC** [comment]
Crash is fixed with december Android 14 update
