### ISSUE TITLE
Hide trail_visibility=horrible paths

### ISSUE THREAD

**Issue by thegrasshopper104** [organicmaps/organicmaps#6447]
Organic Maps shows trail_visibility=bad, trail_visibility=horrible, trail_visibility=no the same way as regular paths.

Most users will see these as map errors. I for one got lost because of these paths multiple times.

**Comment by biodranik** [comment]
Why hiding is the best solution? Maybe different styling/transparency could be better?

**Comment by aronkvh** [comment]
> Why hiding is the best solution? Maybe different styling/transparency could be better?

That's fine too , but it's visible in real life, so it should be invisible on the map as I see it. Maybe just shows them with 50% transparency in the outdoor style?

**Comment by pastk** [comment]
`trail_visibility=no` makes sense for e.g. rocky alpine routes, so people go there, but there could be no marks due to the nature of the surface and frequency of use.

**Comment by pastk** [comment]
There are several attributes/tags that should affect how a trail is rendered:
- `smoothness`
- `surface`
- `trail_visibility`
- `sac_scale`
- is it part of the route relation or not

So first we should come up with a comprehensive consistent vision how to handle these many combinations.
One approach is to try to reduce them into just a few "difficulty" levels, e.g. any or all of horrible surface or smoothness or trail_visibility or challenging sac_scale could be displayed by a red sparsely dotted red line (screams its difficult),  while excellent smoothness, easy sac_scale etc. could be a long dashed green / brown line. And a few options inbetween.

The challenge is to develop a smart algo / mapping from many original attribs to one (maybe two) display options.

We do have already a mapping of `surface` and `smoothness` into a single surrogate attribute `psurface=paved/unpaved_good/bad` (4 possible values) which is used for routing estimations - and its proved to be not easy :/ See the code in `generator/osm2type.cpp DetermineSurface()`

**Comment by janusbenissa** [comment]
> That's fine too , but it's visible in real life, so it should be invisible on the map as I see it.

If you don't see the path on the ground, the only thing you have is your navigation, so hide them in OM is in my opinion a bad idea. How can you find your way else?

**Comment by biodranik** [comment]
That's a good point. Even if the path is not visible at some place, following it using OM may lead to the right exit.

**Comment by pastk** [comment]
Related to
- #2185 
- https://github.com/organicmaps/organicmaps/issues/1577#issuecomment-980177481
