### ISSUE TITLE
Navigation does not work when the device screen is turned off (microg, lineageos)

### ISSUE THREAD

**Issue by mec-kon** [organicmaps/organicmaps#6450]
Hello,
I have installed the F-Droid version of OM.

As long as the screen of my smartphone is enabled, everything works fine. When I put the device in standby by pressing the power button after starting a navigation, the location no longer works.

I notice this because I do not get voice commands anymore when the display is off. When I turn the display back on, the device is at the location where I turned the display off and then starts updating the location.

**System information:**
 - Android 12 (LineageOS for microG version 19)
 - Organic Maps version: 2023.09.22-27-FDroid

**Comment by HAWK-Soft** [comment]
Hi I experienced same thing last summer. I think this is because of your settings application. You need to have the two last items setup like this:

![IMG_20231102_225145.jpg](https://github.com/organicmaps/organicmaps/assets/26247865/c9f014fa-1dc8-4481-bcaf-b9af1211cdff)

And maybe if you want (but this is additional) the "Power saving mode" item turn on Never.

Hope this helps.

---
Phone: Xiaomi 10T Lite - Android 
From organicmaps from F-Droid also

**Comment by biodranik** [comment]
@mec-kon let's clarify. Do you start navigation mode and then lock the device? Or do you lock the device without starting navigation mode? OM continues to use GPS for voice directions only in the former case.

**Comment by mart3nsite** [comment]
Hi,

I experience the same behavior: In navigation mode, when I lock the phone the location (and thus the voice guidance) no longer works. When I unlock the phone, OM updates the location and continue navigation.

> Hi I experienced same thing last summer. I think this is because of your settings application. You need to have the two last items setup like this:
> 
> And maybe if you want (but this is additional) the "Power saving mode" item turn on Never.

My application settings are the same as yours (with power saving set to "never").

> @mec-kon let's clarify. Do you start navigation mode (build the route and then press "Start") and then lock the device? Or do you lock the device without starting navigation mode? OM continues to use GPS for voice directions only in the former case.

I do start navigation mode before locking the device.

I use the F-Droid version and my system is Android 7.1.2.

**Comment by biodranik** [comment]
Are you using the latest OM version?
Do you see any notifications when you start navigation mode?

@rtsisyk what can cause non-working foreground service in these cases?

**Comment by mart3nsite** [comment]
> Are you using the latest OM version?

My bad, OM was not up to date on my phone. After update the navigation works fine when screen is not on, sorry for the inconvenience.

However, I still have the flickering bug when using the app on lock screen (I'm still on android 7.1) but that's not the subject of this thread.

**Comment by mec-kon** [comment]
Hello everyone,
sorry for the late response.
I will test the navigation again today with the settings recommended by HAWK-Soft on the latest F-Droid version and then get back to you.

@biodranik: Yes, I  do start navigation mode and then lock the device.

**Comment by mec-kon** [comment]
Hello,
I tested the navigation yesterday with the settings recommended by HAWK-Soft and it seems to work, but it also worked without changing the settings. Unfortunately, I can't say why it didn't work a short time ago. I suspect it is because of an update of LineageOS.
I will close this issue for now and open it again if the error occurs again.

Thanks for the quick help to everyone.
