### ISSUE TITLE
Wrong text color in edit Bookmark layout

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#6468]
**Steps to reproduce**
1. Start OM
2. Enable dark mode in settings
3. Go to bookmarks
4. Edit list bookmark
<img src="https://github.com/organicmaps/organicmaps/assets/87148630/a1138a50-bd46-4bbd-8a7f-60d22720e5b2" height=300 />

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: 2023.09.22-27-Google
 - Device Model: Pixel 6

**Comment by maityamit** [comment]
Hi, this side Amit. I go through the codebase of Android and face the same issue on my device as well. 
I really wanna contribute and fix this issue. and this is also a ```good first issue``` .  I can do this issue, and if I need any assistance, I will ask you. I hope you will help me.
