### ISSUE TITLE
Wrong text color on error message

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#6481]
**Steps to reproduce**
1. Start OM
2. Enable dark mode
3. Go to bookmark
4. Create new list with no name -> error message is not visible

<img src="https://github.com/organicmaps/organicmaps/assets/87148630/499c63da-2110-4cba-a7b1-ca8a4a1ef93f" height=300 />

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: 2023.09.22-27-Google
 - Device Model: Pixel 6

**Comment by Jean-BaptisteC** [comment]
This line doesn't work
https://github.com/organicmaps/organicmaps/blob/c1482ce288a1082b2168adee9bff2837a80f806a/android/app/src/main/java/app/organicmaps/util/UiUtils.java#L225

**Comment by walterjwhite** [comment]
@Jean-BaptisteC - I was debugging and set breakpoints there, but did not hit that line or the other method either.  I was able to reproduce the scenario above, but I am not hitting that breakpoint.  Can you confirm that is what is driving the above problem, if not, I'll have to dig further.

**Comment by Jean-BaptisteC** [comment]
I'm not sure all Input, use this part of code, you can check PR #4577 for more information

**Comment by Jean-BaptisteC** [comment]
Fixed in latest version 2023.11.17-18-Google

**Comment by Jean-BaptisteC** [comment]
Works if dark mode is enabled in Android settings
