### ISSUE TITLE
Unnecessarily lenghly "Vado (de lugar)" translation

### ISSUE THREAD

**Issue by fitojb** [organicmaps/organicmaps#6494]
**Describe the issue**
"Ford" is translated as "[Vado (de lugar)](https://github.com/search?q=repo%3Aorganicmaps%2Forganicmaps+vado+%22de+lugar%22&type=code)" with an unneeded parenthetical.

It should be translated just as "Vado". There is no ambiguity with regards to its meaning.

**Comment by biodranik** [comment]
It could be easier to edit that string directly at data/strings/types_strings.txt instead of creating an issue :)
