### ISSUE TITLE
Rotate map/compass button hide behind the layer button if the App set to Arabic

### ISSUE THREAD

**Issue by Colonel-Dixie** [organicmaps/organicmaps#6504]
Hi,
Couple of months ago I installed the app on my friend's android car stereo and clicked the arrow button to change the normal view (north side up) to a driving view (forward looking while moving) I noticed the rotate map/compass button hide behind the layer button.       
This also happen if you rotate the map with your fingers, you need to rotate it back north up manually.   
This happened if you set your language to Arabic due to the App change layout to Right-to-Left layout to follow the Arabic right-to-left script layout. I tried other Right-to-Left languages like Hebrew and there is no issue with Hebrew because it has the Left-to-Right app layout. 

**Steps to reproduce**
1. Make Language Arabic
2. Rotate the map with your fingers
3. Rotate map/compass button hidden behind the layer button at top

**Expected behaviour**
Rotate map/compass button do not hide behind the layer button at top.

**Screenshots**
iPhone: ![image](https://github.com/organicmaps/organicmaps/assets/35276833/33d67730-4140-49ac-850e-a0e9168fb0c8)
Android on VM (not so clear as the iPhone but if you zoom in to the layer button you will see it: 
![image](https://github.com/organicmaps/organicmaps/assets/35276833/b57b2272-7011-4ce1-8d9d-da2b107b12ea)

And here is a video from my iPhone showing the issue clearly (click the link):
https://github.com/organicmaps/organicmaps/assets/35276833/e475f28c-2258-4fdf-ac88-657a940fcf58

English Screenshot:
![English](https://github.com/organicmaps/organicmaps/assets/35276833/eed021f5-fe36-4e38-863e-2d8ac4b77be7)
 
Hebrew screenshot: 
![Hebrew](https://github.com/organicmaps/organicmaps/assets/35276833/9265752a-115a-4ea9-9a7b-1c9d2ff2112c)
  
Arabic screenshot: 
![Arabic lang](https://github.com/organicmaps/organicmaps/assets/35276833/548695a5-ddc0-4d48-9ea2-8f6071e718f0)

**System information:**
 - tested on iOS, Android and both have the issue
 - Organic Maps version: latest from AppStore and F-Droid.
 - Device Model: iPhone, unknown brand android car stereo, and an android VM on windows.

Thank you.

**Comment by Colonel-Dixie** [comment]
Sorry forgot to add **suggestions**:
1- Making the rotate map/compass button also change to the other side just like the layer map, so they don't be one above the other. (Recommended)*    
2-Make the language not shift right to left and make it stick like Hebrew and English.    

* First suggestion is recommended because it will also follow the System UI right to left layout.

**Comment by Colonel-Dixie** [comment]
Note: This might also happen to Hebrew if the Hebrew is not finished developing and change the layout in the future.

**Comment by Jean-BaptisteC** [comment]
Fixed by #7049
