### ISSUE TITLE
Hackerspaces with toilets are shown as toilets

### ISSUE THREAD

**Issue by svenpilz** [organicmaps/organicmaps#6518]
It seems that POIs with unknown type will be rendered using its properties. resulting in https://www.openstreetmap.org/node/260050809 being shown as a toilet.

More context and screenshots on Mastodon:
* https://mastodon.social/@tommi@pan.rent/111368073388923497
* https://mastodon.social/@svenpilz/111368260582234051

**Comment by Jean-BaptisteC** [comment]
CC @pastk

**Comment by pastk** [comment]
Related to
- #3867 
- #6493 
- #1312

**Comment by lint3** [comment]
Issue also occurs with building=university.

**Comment by pastk** [comment]
> Issue also occurs with building=university.

Could you post a sample link to OSM please?
`building=university` is processed like any other building; if there is no other tags except `toilets=yes`, then it'll be shown like a building with toilets POI

**Comment by lint3** [comment]
https://www.openstreetmap.org/way/29261250

Hmm, so this is expected behavior since this tag combination is indistinguishable from a university-operated toilet building?

**Comment by pastk** [comment]
For this particular case a proper solution would be to add a new POI type `historic=building`. Then it'll be correctly shown as a historic POI with toilets amenity.
Feel free to create a separate issue for that :)

P.S. `building=university` just means the building was built as a university, it doesn't mean there is a working uni there.
If there is an actual uni still then it should be tagged as `amenity=university`. If its one of many buildings in e.g. a campus then maybe read OSM wiki to know how to tag it correctly :)

**Comment by pastk** [comment]
> Hmm, so this is expected behavior since this tag combination is indistinguishable from a university-operated toilet building?

But if we consider a hypothetical `building=yes toilets=yes` then it should be shown as a building (with a name perhaps) with toilets attribute, i.e. it should not use toilets icon, but show presence of restroom when selected only and be searchable also. But it doesn't work this way in OM yet :)

`building=yes amenity=toilets` should be displayed as a toilets block using a corresponding icon.

**Comment by lint3** [comment]
Gotcha. In this case, this is a building that was built as part of Utah State University, but doesn't represent the entire uni. (Instead, there is a boundary around campus that has `amenity=university`). There are also other more modern uni buildings without `historic=building`, such as [this](https://www.openstreetmap.org/way/29261228).

My point is, I guess it seems like any feature with `building=*` and `amenity=toilets` should be rendered prominently as a "toilet building" (like
![image](https://github.com/organicmaps/organicmaps/assets/61328566/a8118c3d-598b-4c9a-b9e2-29e3f337cb15), and a building with `toilets=yes` should be a regular building that includes toilets somewhere, right? I think that would resolve the hackerspace issue as well as this university issue.

**Comment by lint3** [comment]
Here's an example of the toilet building just down the street from c-base hackerspace. https://www.openstreetmap.org/way/1075481505 - It has `amenity=toilets

**Comment by RedAuburn** [comment]
still the case after https://github.com/organicmaps/organicmaps/issues/2078 as we have no hackerspace type
