### ISSUE TITLE
3D viewer for POI with a linked 3d model

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#6521]
(Very much a bluesky idea)

Inspired by https://www.openstreetmap.org/user/b-unicycling/diary/402670

This would realistically have to be an online-only feature, but it would be so cool if there was a button to "view in 3D", which opened a 3D viewer where you could pan around an object, area or building

there isn't much usage yet, but adding it would likely boost usage of it and similar tags (i'm going to start tagging 3d models in my area in any case)

78 for `url:sketchfab=*`
39 for `3dmr=*`
21 for `sketchfab=*`

3d models can also be found via wikidata via P4896 eg. https://www.wikidata.org/wiki/Q243

example poi: https://www.openstreetmap.org/way/1221583451
example 3d model: https://skfb.ly/oNrYV

**Comment by patepelo** [comment]
It's a cool idea I'd like to see more in the OSM environment. I don't know if i would expect to have it intagrated in OM as a "pocket sized" simple app but as you say, to have the link to redirect to the website/app would be something :)

**Comment by RedAuburn** [comment]
closing as "eeeh"
