### ISSUE TITLE
To many "undefined" when share location from Undefined place

### ISSUE THREAD

**Issue by dbf256** [organicmaps/organicmaps#6524]
**Describe the issue**
See attached screenshot

**Steps to reproduce**
1. Tap on empty place
2. Share location

**Expected behaviour**
Header should be better

**Screenshots**
![Screenshot_2023-11-08-21-01-04-614_org telegram messenger~01](https://github.com/organicmaps/organicmaps/assets/2550295/3406b262-4d8a-47d7-84b3-fdc092c27037)

**Comment by RedAuburn** [comment]
this seems to happen when the POI name doesn't use characters from the latin alphabet.

eg. http://omaps.app/o4B4pYZsRs/Zoo_Zürich -> Zoo Zundefinedrich

eg. https://omaps.app/o4B4pYZsRs/ру́сский_алфави́т -> undefinedundefinedundefinedundefinedundefinedundefinedundefinedundefined undefinedundefinedundefinedundefinedundefinedundefinedundefinedundefined

**Comment by biodranik** [comment]
Thanks! Please check, it should be fixed now.

**Comment by dbf256** [comment]
Thanks, it works now.
