### ISSUE TITLE
[android] Can't export bookmarks.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#653]
![Screenshot_20210619-171910](https://user-images.githubusercontent.com/175612/122648483-2be61100-d132-11eb-80b0-ab9d468c1588.png)
![Screenshot_20210619-171935](https://user-images.githubusercontent.com/175612/122648484-2d173e00-d132-11eb-89cd-4962ed867325.png)

https://drive.google.com/file/d/1ixwD1r61G5apzoMCpb1gKoY4z6h1b10X/view?usp=sharing

**Comment by biodranik** [comment]
Fixed in #614
