### ISSUE TITLE
cumulative elevation gain for a planned biking route

### ISSUE THREAD

**Issue by adrienchaton** [organicmaps/organicmaps#6555]
Hello and great job, organic maps is a fantastic travel companion!

Either I did not find it or it would be an awesome improvement to the app. When planning a bike route from one point to another, I get distance, elevation profile and some absolute height difference value, as far as I understand. To me the absolute difference is much less useful than an estimated cumulative gain/loss ... Since I see an elevation profile, I would think it could be possible to get a rough estimate of the total gain/loss, maybe not as accurate than when recording our own track in live but still something more informative than the current default?

An ideal solution would be to have the option to switch between the current absolute difference and a cumulative one. For context, I saw these two issues but to me it is not clear whether or not you have made this possible ... I can't seem to find how to get the total gain/loss. https://github.com/organicmaps/organicmaps/issues/1618 https://github.com/organicmaps/organicmaps/issues/3477

Alternatives are to record our own track but this only help to get overall statistics of our bike tour afterward. I would otherwise gladly receive advice on what alternative solution could play well with organic maps and e.g. help trip planning by looking in advance at some estimated cumulative elevation changes.

Thanks for your great work!

**Comment by pastk** [comment]
> When planning a bike route from one point to another, I get distance, elevation profile and some absolute height difference value, as far as I understand.

Actually it shows cumulative gain and drop. Just try to build a route to top of the hill and back :)

**Comment by adrienchaton** [comment]
@pastk thanks for your reply!

I only now realise that my version is from 2021.09 and since back then I installed with Fdroid so play store never told me to update ...

So I want to update and catch up on all the great stuffs you have done since ... but how can I update my Fdroid version please? If I go on play store, it sees that I have it installed but it doesnt offer me to update since I guess the install wasnt managed by play store ... of course I would wish not to loose my data that I have on the Fdroid ... thanks for the support!

**Comment by pastk** [comment]
Did you install using an official F-Droid client? Then it should offer updates (unless you turned them off maybe?).
Do updates work for other apps you've installed via F-Droid?
In F-Droid's "Updates" tab try to pull down - it should query the repositories for the latest data and then should show available updates.

**Comment by adrienchaton** [comment]
@pastk thanks, that's awesome, I have now the update and can see all the improvements, including the up and down break down of elevation profile!

tbh I am not an Fdroid user, I installed this way because as far as I remember it was the only way to do back then, but since I never checked again the Fdroid and didnt see it was managing the updates

**Comment by pastk** [comment]
Awesome, enjoy your updated OM experience! We improve it all the time :)
