### ISSUE TITLE
[new icons] Dry Cleaning vs Laundry

### ISSUE THREAD

**Issue by patepelo** [organicmaps/organicmaps#6569]
Currently, the same icon is used for Dry Cleaning and for Laundry:

![image](https://github.com/organicmaps/organicmaps/assets/23003127/086fedad-6b25-4cc4-a087-9dc97a77c7a1)

They idea would be to generate a new icon for Dry Cleaning, here are some proposals:

![image](https://github.com/organicmaps/organicmaps/assets/23003127/644f9ea8-2123-4aa8-91c6-584acd2c942a)

These three type of POIs are very common and vary a lot in their use, so its convennient to differentiate:

From wiki: 

[Dry Cleaning](https://wiki.openstreetmap.org/wiki/Tag:shop%3Ddry_cleaning
)
![image](https://github.com/organicmaps/organicmaps/assets/23003127/e1feedef-6906-454d-aef6-17be6d7c08ce)

[Laundry](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dlaundry)
![image](https://github.com/organicmaps/organicmaps/assets/23003127/023f56f6-9f40-4703-b4c5-dc41213a4f88)

The latter is very commonly found as a self service. So we should categorized them or alternatively put in the meta data that it is of self service or not.

([self_service](https://wiki.openstreetmap.org/wiki/Key:self_service)=yes/no)

**Comment by dvdmrtnz** [comment]
I like the icon with only the hanger. Maybe the lower corners could be rounded a bit and made a bit thicker?

In the one with the shirt the hanger is not very noticeable when small.

**Comment by pastk** [comment]
I associate "hanger" icons with a shop selling clothes :)

**Comment by patepelo** [comment]
> I associate "hanger" icons with a shop selling clothes :)

What about using the typical iron found on cloth labels?

![image](https://github.com/organicmaps/organicmaps/assets/23003127/c4a6c39c-172c-45b3-a60a-23d9fc0eb7ed)

This one is in google material design library:

![image](https://github.com/organicmaps/organicmaps/assets/23003127/5674c40b-9542-4427-a4b7-039ad0dc7918)

**Comment by pastk** [comment]
An iron seems like a good idea.
Though I'm not sure people will immediately associate it with dry cleaning, but they'll learn after tapping on it.

**Comment by patepelo** [comment]
1. Google. 2. Google modified:
![image](https://github.com/organicmaps/organicmaps/assets/23003127/c885f43b-bdc8-4642-b553-075bb98556d9)

i prefer the first one.



> they'll learn after tapping on it

Exactly, this is the only way many times.

**Comment by patepelo** [comment]
> I like the icon with just the hanger. Maybe the lower corners could be rounded a bit and the whole design made a bit thicker?
> 
> In the one with the shirt the hanger is not very noticeable when small.

A bit improved. 

![image](https://github.com/organicmaps/organicmaps/assets/23003127/2b9af599-c23e-41fe-8a72-91fa3ea6a850)

**Comment by patepelo** [comment]
@organicmaps/styles @organicmaps/design 

Do we have a winner between iron vs hanger? Should any of those be improved?

**Comment by biodranik** [comment]
I like the hanger icon. And let's create a separate issue for self_service metadata.

**Comment by Misalf-git** [comment]
By the appearance allone (assuming equal _correctness_), the iron kinda looks like a stretched small letter "a" to me, so I'd go for the (no shirt) hanger icon, too.

I'm sure nobody deciphers the hieroglyphs on the small white patches hidden in their clothes.

**Comment by euf** [comment]
I'd vote for a hanger too, the iron is a little bit deformed and seems much harder to align on a 18×18 pixel grid.

**Comment by biodranik** [comment]
@patepelo  Can you attach the icon here?

**Comment by patepelo** [comment]
![dry_cleaner-m](https://github.com/organicmaps/organicmaps/assets/23003127/a17ca71d-b8cf-42fc-816a-e12ec8e15fe0)
This is the latest version. It's on Figma as well.

Source: Organic Maps original (self drawn) 😄
