### ISSUE TITLE
Crashes instantly - Xperia Z3c, Android 5.1

### ISSUE THREAD

**Issue by Darthagnon** [organicmaps/organicmaps#657]
Crashes instantly on my mum's Xperia Z3 Compact (Android 5.1). I was really looking forward to using it :'(

**Comment by rtsisyk** [comment]
Hi,

Thank you for the report. We already fixed this bug and waiting for a new
version to be published on Google Play.

If you have time, please test 2021-06-19  beta version:

https://appdistribution.firebase.dev/pub/i/3c5fcf9cd72f775f




This version will be available on Google Play as soon as Google approves it.

**Comment by tieugene** [comment]
The same (Micromax Q415, Android 5.1.1, OrganicMaps 2021.06.12-7-tramtaramtaram)

**Comment by rtsisyk** [comment]
https://github.com/organicmaps/organicmaps/issues/628#issuecomment-864538135

A fix is on review. Google reviews may slow to over a week due to COVID :(

**Comment by rtsisyk** [comment]
Fixed.

**Comment by Darthagnon** [comment]
I can confirm, it is indeed fixed! Thank you so much!
