### ISSUE TITLE
Do not display decimal separator in current speed when it's 0.0

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#6570]
I checked for issues related to 'decimal' or 'separator' but could not find a duplicate.

My issue here is, when you're driving and you stop, the current speed shows as 0,0. Shouldn't current speed only display integers?

![img](https://github.com/organicmaps/organicmaps/assets/86851490/70f1c598-9cd6-4dce-ac22-5ce7c2fc951e)

A bit related to #6560

**Comment by biodranik** [comment]
@Jean-BaptisteC does it also reproduce on Android?
CC @gpesquero

**Comment by Jean-BaptisteC** [comment]
Yes I reproduce on Android in 2023.09.22-27-Google version

**Comment by auge8472** [comment]
On iOS the speed is only displayed with a decimal place (IMHO under 5 kph) in very low speeds and speed being 0. Higher speeds are displayed without a decimal place. IMHO displaying a decimal place at low speed can be useful but not, when speed is 0.

**Comment by matheusgomesms** [comment]
Ok, did another test here. In driving mode, the speed is shown X.X until 9.9 kph (including 0.0). From 10 onwards, only integers.

Worth discussing, but is this necessary in driving mode? Perhaps cycling or walking, but I still don't think it's needed in any mode, especially considering the precision of GPS (who guarantees that the real speed is 5.4 kph, for example). Using only rounded integers, this problem disappears.

**Comment by biodranik** [comment]
How does it hurt you? 0,0 is a bug, it should be 0 instead. But what is bad with other speeds? They are useful to show any difference, even subtle one, when necessary.

**Comment by matheusgomesms** [comment]
I don't know what others think, but:

1 - any app can't guarantee true speed due to GPS precision, so OM is basically showing "wrong" info (rounded values don't have this issue)
2 - OM is a navigation app; even if the current speed is 100% precise, is it really necessary for navigation purposes (regardless of mode)? How useful is it to display 5.4 or 5.6 to the user?
3 - it occupies extra space on the app
4 - if current speed is moved to another place in the screen, how it will work?

For a regular user, I think these kind of values are useful when practicing sports (all sports apps display speeds with decimal values). However, no navigation app displays that (only OM).

**Comment by gpesquero** [comment]
I agree with @matheusgomesms and I think that speed shall not be displayed with decimals. 

Maybe while navigating by bike or walking it could be displayed with one decimal at low speeds (<10.0), but not by car.

**Comment by biodranik** [comment]
Making OM sports-friendly, with precise speed, is an excellent idea.

**Comment by biodranik** [comment]
> How useful is it for displaying 5.4 or 5.6 to the user?

For walkers, 500m difference after a rounding may be a huge deal, depending on the case.
