### ISSUE TITLE
OSM editing: Adds weird tag `external_uri`

### ISSUE THREAD

**Issue by dganske** [organicmaps/organicmaps#6571]
**Describe the issue**
When editing e.g. a hotel POI in a current organicmaps version, the tag `external_uri` will be added to the element on OSM. 

**Steps to reproduce**
1. Pick any hotel
2. edit it
3. upload to osm
4. edit will contain the nonsense `external_uri` tag 

For example, see [this edit](https://www.openstreetmap.org/changeset/144057080). 

**Expected behaviour**
Add only the edited data to openstreetmap, not the external_uri tag. 

**Screenshots**
[Link to test changeset](https://www.openstreetmap.org/changeset/144057080)
[Link to overpass turbo request for external_uri globally](https://overpass-turbo.eu/?w=%22external_uri%22%3D*+global&R)
[History of the tag](https://taghistory.raifer.tech/?#***/external_uri/)
[Taginfo](https://taginfo.openstreetmap.org/keys/external_uri)

**System information:**
 - Operating system and its version: any
 - Organic Maps version: **from 2023.09.22 onwards**
 - reproduced on
   - Organic Maps ios 2023.09.22
   - Organic Maps android 2023.09.22-27-FDroid
   - Organic Maps android 2023.09.22-27-Google

 - Device Model: any

**Additional context**
The tag `external_uri` is only added by Organic Maps, not by any other editor. This tag first showed up in osm on the 22.09.2023. It is not consumable by any other application and is unclear in both its meaning and data source. 

I suspect it is added unintentionally due to an issue with the most recent organicmaps prod version.

**Comment by RedAuburn** [comment]
cc @vng (wrt https://github.com/organicmaps/organicmaps/pull/5922)
