### ISSUE TITLE
[Android] Unable to select Portuguese or Spanish in TTS

### ISSUE THREAD

**Issue by zyphlar** [organicmaps/organicmaps#6577]
On the master branch (debug) it doesn't seem possible to choose Español in the OM TTS settings drop-down. When choosing Español it auto-chooses Español (Mexico). Same issue with Portugues and Portugues (Brasil) but no such trouble with Chinese Simplified/Traditional.

Choosing pt causes pt-BR to be selected but only pt to be announced, and choosing es causes es-MX to be selected but only es to be announced, so maybe there are buggy drop down values or logic?

**Comment by zyphlar** [comment]
Google TTS

**Comment by PepePi07** [comment]
> What TTS engine do you have?
Google TTS
![Screenshot_20231226-151245_Ajustes](https://github.com/organicmaps/organicmaps/assets/154900656/39014d95-5d29-4fea-9c5a-830f4c547968)

**Comment by biodranik** [comment]
It's fixed by https://github.com/organicmaps/organicmaps/pull/6934
Will be availabe in the next update.

**Comment by PepePi07** [comment]
> It's fixed by #6934 Will be available in the next update.
  Thank you very much!
