### ISSUE TITLE
Don't show "Routing options enabled" for Ruler routes

### ISSUE THREAD

**Issue by strump** [organicmaps/organicmaps#6579]
**Steps to reproduce:**
1. Open settings, Routing options and enable some road avoidance settings
2. Build a route using Ruler route type

**Actual result:**

"Routing options enabled" panel is shown

Screenshot:
<img src="https://github.com/organicmaps/organicmaps/assets/720808/5356c608-fb69-4d14-bae2-3095beb888ee" width="300px"/>

**Expected result:**
Panel should not be shown.

**Comment by Jean-BaptisteC** [comment]
https://github.com/organicmaps/organicmaps/pull/3601
