### ISSUE TITLE
[android] Remove RECEIVE_BOOT_COMPLETED permission

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#658]
https://www.facebook.com/melnichek/posts/10165325301365223?comment_id=10165325538280223&reply_comment_id=10165326609205223

**Comment by Endem10n** [comment]
@rtsisyk should we close this issue? Cannot find this permission anywhere in project source code.

**Comment by biodranik** [comment]
It was mentioned on the screenshot here: https://organicmaps.app/

Maybe fdroid build or some 3party lib enables it somehow? @rtsisyk

**Comment by Endem10n** [comment]
It's WorkManager dependency. Used in old proprietary code. Preparing PR.

**Comment by rtsisyk** [comment]
Won't fix currently.

**Comment by biodranik** [comment]
Wait, are there other working approaches to guarantee the uploading of OSM edits?

**Comment by rtsisyk** [comment]
=> https://github.com/organicmaps/organicmaps/issues/6169
