### ISSUE TITLE
Fix blurry thick lines

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#6583]
Thicker and/or dashed lines look blurry/dirty compared to thin solid lines, e.g.
(magnified several times to show the issue)

![image](https://github.com/organicmaps/organicmaps/assets/18434508/67a4c95b-a579-48f4-8d6e-c629259ffcd5)

Thin black line is very crisp, while only the core of the dashed line has a true color and the outer parts are semi-transparent.
Causes
- #5414.

For thinner solid lines OM uses GL line primitives, while dashed or thicker lines are drawn by explicitly-set textured quads
(see `drape_frontend/line_shape.cpp LineShape::Prepare()`).

Maybe this blurriness was added intentionally as a kind of anti-aliasing? But it looks bad, especially on lower dpi screens.

CC @vng

**Comment by pastk** [comment]
Likely causes
- #4467

**Comment by pastk** [comment]
A magnified screenshot from a highdpi (vs=2) device (prev screenshot was from a low dpi desktop):
![image](https://github.com/organicmaps/organicmaps/assets/18434508/31e658aa-5750-41c6-85fc-339dad334534)

Even white roads have blurred "dirty" edges. Compare to very crisp edges of areas.

**Comment by vng** [comment]
So, what do you want to fix here? We have a relatively cheap antialiasing, which is good, no :)

Drawing a _width_ line in drivers is deprecated, AFAIR: No in OGL (not ES) 3+,  No in Metal. Can't say for sure in Vulkan.

**Comment by pastk** [comment]
> So, what do you want to fix here? We have a relatively cheap antialiasing, which is good, no :)

- are you sure its significantly cheaper (if it all) than a proper AA?
- its not consistent, some elements have it, some not

> 
> Drawing a _width_ line in drivers is deprecated, AFAIR: No in OGL (not ES) 3+, No in Metal. Can't say for sure in Vulkan.

Not deprecated in OGL ES 3.2:
https://registry.khronos.org/OpenGL-Refpages/es3/html/glLineWidth.xhtml
