### ISSUE TITLE
Lower priority of sidewalks and their names

### ISSUE THREAD

**Issue by patepelo** [organicmaps/organicmaps#6587]
Reference is the special case of Barcelona where street names where copied to foot ways -sidewalks, crossings and similar walking features. It has cluttered the map and those labels hide completely many POIs at all zoom levels, making them like non-existent.

See screenshot:

![image](https://user-images.githubusercontent.com/23003127/283723578-8bc0cfa9-5ce9-4abe-85e5-58f34a8fd8a4.png)

Also consider drawing the pedestrian areas without dashed lines, it would look much better.

![img](https://user-images.githubusercontent.com/23003127/283723667-b4c5d94b-b0fe-4e38-a64c-6b4fb458ef8f.png)

>          > Another thing, now that street labels covering other POIs are mentioned. Every single mapped footway in Barcelona has been named (it helps foot TTS navigation and accessibility). The problem now is that many POIs are close to them and these labels hide them. (some POIs end up being non-existent)

>    It would be good if sidewalks names would be lowered to last level of zoom or even not shown: footway=sidewalk highway=footway

> Wow, even sidewalks are named? Do their name usually duplicate the one of the street?

> Its a good idea indeed to add a special type highway-footway-sidewalk and make it lower priority and visibility.
Current footways are z15- and at this zoom lining them along the streets is not informative but adds clutter.

Originally posted by @pastk in https://github.com/organicmaps/organicmaps/pull/6386#issuecomment-1814889829

**Comment by pastk** [comment]
> Also consider drawing the pedestrian areas without dashed lines, it would look much better.

Its a separate issue
- #5884

(better to keep issues focused, unless its a meta/epic-issue of course)

**Comment by RedAuburn** [comment]
sidewalk (`highway=footway`, `footway=sidewalk`) names shouln't be displayed at all IMO, it's just duplication of the road name

**Comment by patepelo** [comment]
> sidewalk (`highway=footway`, `footway=sidewalk`) names shouldn't be displayed at all IMO, it's just duplication of the road name

If they should be named in the OSM data is even a divided opinion and me personally don't have a preference. The mapper doing this work in Barcelona claims is for helping audio guidance for impaired people and since then I understand it better. 

So yes, I agree with @RedAuburn, those names could be dismissed in the render and kept for TTS.
