### ISSUE TITLE
[Question] Embedded opening_hours source code

### ISSUE THREAD

**Issue by werdahias** [organicmaps/organicmaps#6619]
I started working on a offical debian package for organic maps. Debian policy requires that external libraries shouldn't be vendored, if possible. I was wondering where the original opening_hours source code stems from.

**Comment by biodranik** [comment]
We wrote it.

**Comment by werdahias** [comment]
ah, ok, thanks. Does it exist somewhere on its own in a repo ? that would simplify packaging.

**Comment by biodranik** [comment]
No. Furthermore, we plan to rewrite/replace it completely.

**Comment by werdahias** [comment]
ok, thanks. I'll focus on getting the other relevant dependencies into debian then.
