### ISSUE TITLE
iOS: cannot edit objects

### ISSUE THREAD

**Issue by richlv** [organicmaps/organicmaps#6625]
**Describe the issue**
Latest app and map versions on iOS, cannot edit places.

**Steps to reproduce**
1. Open any place properties.
2. Observe no editing possible.
![image](https://github.com/organicmaps/organicmaps/assets/112888/6654396d-dc42-4b17-962b-0280d1a67ad1)

**Expected behaviour**
Editing available.

**Screenshots**
Removed all maps except one, made sure it's up to date.
![image](https://github.com/organicmaps/organicmaps/assets/112888/463ddab4-c7de-4235-8afa-db6fdd5dfc15)

**System information:**
 - Operating system and its version: iOS 16.7.2
 - Organic Maps version: 2023.09.22-20
 - Device Model: iPhone X

![image](https://github.com/organicmaps/organicmaps/assets/112888/49cd44a7-7f3c-4bb5-8c14-6044c6baf584)

**Additional context**
New places can still be added from the menu.
Somewhat similar to #6351, except that no app or map updates are available.

**Comment by rawcomposition** [comment]
I had the same issue yesterday, but it's working now after logging out and logging back in to my OSM account. Not sure if it was this that fixed it or the latest app update, but it's working now for me. I had previously changed my OSM username on the OSM website which might have messed something up.

![IMG_F6CCC532415A-1](https://github.com/organicmaps/organicmaps/assets/740090/480be982-a073-4707-8a81-140bf89751bd)

**Comment by biodranik** [comment]
@richlv does it reproduce after the app/maps update?

**Comment by richlv** [comment]
Thank you for checking this - there was an app update available now, and after updating the editing functionality is back.
Was it detecting an update that was not yet available to me?

**Comment by Jean-BaptisteC** [comment]
Update can take some days to be available on store
