### ISSUE TITLE
[android] Incorrect internal memory capacity

### ISSUE THREAD

**Issue by vigeron** [organicmaps/organicmaps#6659]
Incorrect internal memory capacity. I have a 128GB SD card and 64GB internal memory

Android: 9
Release OMap apk: 23111717

![image](https://github.com/organicmaps/organicmaps/assets/16254462/2fc29d78-b5f2-4552-a1a2-f82f2a8992ae)

**Comment by biodranik** [comment]
Is there something else displayed below? Can you please enable logs, restart OM, open these settings and send us logs via Report a Bug?

**Comment by vigeron** [comment]
there is nothing else on this screen
[logs.zip](https://github.com/organicmaps/organicmaps/files/13450627/logs.zip)

**Comment by biodranik** [comment]
The system api doesn't detect any other storages. Do other apps detect it properly?

**Comment by vigeron** [comment]
Both memories are detected because I can switch internal/external maps and everything works. It only indicates the capacity. Other programs also work well and even indicate the capacity correctly.

**Comment by biodranik** [comment]
Interesting, can you connect to your device using USB cable and `adb shell` ? If yes, can you try to `cd <path displayed in OM>` and then `df -h .` to see a free disk space there?

**Comment by vigeron** [comment]
I cant't enter to path, because I get "Permision Denied" message.

![image](https://github.com/organicmaps/organicmaps/assets/16254462/17d1c918-4db5-4016-beec-b3355e5027d8)
![image](https://github.com/organicmaps/organicmaps/assets/16254462/f7ccb534-d821-403c-9bc7-127f51285b1c)
![image](https://github.com/organicmaps/organicmaps/assets/16254462/2ae60296-0993-4cd2-a8bf-d67e9bba3f56)

**Comment by biodranik** [comment]
So you see that both `/storage/emulated` and `/mnt/expand` have the same size in your system. And OM correctly displays that information. For some reason, the system reports your SD card as an internal storage to applications. And doesn't see `/data` that is actually an internal storage. Maybe it's related to your system settings. Do you have a custom ROM/root access?

**Comment by vigeron** [comment]
After update firmware, is better, so the problem is the system, I guess you can close the issue

![image](https://github.com/organicmaps/organicmaps/assets/16254462/bc442b39-d0b6-4162-85bf-f63415fbb0e5)

![image](https://github.com/organicmaps/organicmaps/assets/16254462/b69b35aa-f731-4a20-9342-aa02f52c14c3)

**Comment by biodranik** [comment]
Good, thanks! Was it a custom/rooted firmware or an official one?

**Comment by vigeron** [comment]
Official by spflash, still the same version Android 9, but custom/rooted in progress
