### ISSUE TITLE
Update Porto metro logo

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#6660]
After this last Nov update, and #6136, the Portuguese community thought that the Porto metro icon has not so good visibility in light mode.

Is it possible to change it, using the alternative version (alternated colors) of the logo, only in light mode?

Here it is, PNG and SVG: https://commons.wikimedia.org/wiki/File:Porto_Metro_logo_B.svg

CC @RedAuburn

**Comment by matheusgomesms** [comment]
You can see on their website that they use both versions, depending on the background: https://www.metrodoporto.pt

**Comment by RedAuburn** [comment]
that makes sense 👍️ will make a pr later
