### ISSUE TITLE
Movie icon used for bookmarked playgrounds

### ISSUE THREAD

**Issue by fizwidget** [organicmaps/organicmaps#6665]
**Describe the issue**
When I bookmark a children's playground, the icon used for it is the movie/cinema one (at least that's what it looks like to me).

**Steps to reproduce**
1. Find a playground.
2. Tap the "Save" (add bookmark) button.

**Expected behaviour**
A more appropriate icon is displayed. Doesn't even need to be a custom playground one - the existing star, tree, or “exercising person” icons seem reasonable to me.

**Screenshots**
![IMG_1996](https://github.com/organicmaps/organicmaps/assets/1172012/7f52292d-b55a-4bdd-a548-8e983d627f5b)

**System information:**
- Operating system and its version: iOS 17
- Organic Maps version: 2023.11.17-15 (with 13 November 2023 map data)
- Device Model: iPhone XS Max

**Additional context**
N/A.

**Comment by Sanket-Arekar** [comment]
Hi @fizwidget, I would like to work on this issue. Please assign this issue to me.

**Comment by fizwidget** [comment]
Hi @Sanket-Arekar, I raised the issue but don’t have permission to assign it. I think the usual approach is to start working on an issue without being assigned it (e.g. see [this comment](https://github.com/organicmaps/organicmaps/issues/5837#issuecomment-1720004612)). 

So, feel free to start working on it 🙂

**Comment by patepelo** [comment]
Hi @Sanket-Arekar, I just assigned it to you. Thank you for collaborating.

**Comment by biodranik** [comment]
@patepelo we do not assign issues to new contributors. The usual practice is to assign the issue only in rare cases when a person will 100% take a look at it and investigate/fix it.

@Sanket-Arekar nobody stops you from creating a fix without being assigned. We have plenty of issues, and only a few volunteers working on some of them.
