### ISSUE TITLE
[android] Respect the "Keep the screen on" setting while in non-centered map mode

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#6669]
#6053 has changed the "Keep the screen on" setting to be ignored when the map is not centered on the current gps location.
(also the setting's description is inconsistent with the actual behavior as of now)

I don't see any arguments why make such an exception for the non-centered mode. WDYT?

The current behavior is inconvenient: 
> I was walking about and browsing the map around. It kept switching off and I had to turn it back on and tap the location button to get the gps fix back every now and then. Very inconvenient.
Having the map always centered to prevent the screen going off is even more inconvenient. I want to browse the map and not being restricted to a "centered" mode by a weird logic.

FYI @rtsisyk @biodranik

**Comment by rtsisyk** [comment]
Adding relevant history from https://github.com/organicmaps/organicmaps/pull/6053:

@biodranik :

> The default OM/MapsWithMe behavior for many years before this change was to keep the screen on only if position is centered (nav mode centers it automatically after 20 or 30 seconds). And in cases when device lock breaks active download.

@rtsisyk:

> in Organic Maps on Android (2023.09.24-4 compiled today) `FLAG_KEEP_SCREEN_ON` flag is on the start of the main (MwmActivity). Proof:
> 
> https://github.com/organicmaps/organicmaps/blob/634a3182019157cf9ea556535d12c5e2cbe858c4/android/app/src/main/java/app/organicmaps/MwmActivity.java#L1058-L1059
> I don't see any difference in the behavior no matter if the position is centered on the screen or not. Neither in the code nor practically in the app. 

I don't care here, and both behaviors are fine to me if the wake screen option is OFF by default to avoid #6053 happening again.
