### ISSUE TITLE
Park details disappears at some zoom levels

### ISSUE THREAD

**Issue by jpds** [organicmaps/organicmaps#6672]
**Describe the issue**

There appears to be a set of zoom levels where parks/gardens will disappear and then reappear closer:

https://github.com/organicmaps/organicmaps/assets/29158971/325dfc78-7d06-4f50-b647-e70b779215a7

**Steps to reproduce**
1. Go to South Kensington, London
2. Zoom in and out

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: 2023.11.17-17-android
 - Device Model: Pixel 6a

**Comment by pastk** [comment]
Wow, this bug had been around for more than a year :)
Thanks for spotting!
Here is the fix: #6673
