### ISSUE TITLE
Better Distinction Between Different Road Types

### ISSUE THREAD

**Issue by DesertBear** [organicmaps/organicmaps#6694]
When cycling, I generally don't want to be on A-Roads (trunk/primary) or B-Roads (secondary) if possible, as they're too busy and the traffic is often fast moving.  Instead, I want to always stick to small low-traffic roads (tertiary/unclassified) if I reasonably can – even if it takes longer.

Therefore, I plan routes in advance using the Bikerouter website, set to the "_Roadbike (minimized traffic, alternative)_" profile, which tries to use very-low-traffic roads wherever possible.  I then export this route as a GPX file and import it into Organic Maps for offline navigation – which works great.

The problem comes when there's a problem along the route and I need to use the built-in navigation.  Organic Maps routing will generally choose more quicker routes, therefore I need to override (manually add points) to make it route along tertiary and unclassified roads where I can.  The issue is, it's difficult to distinguish between different road types in Organic Maps because secondary, tertiary and unclassified roads are all coloured white and all look the same on a small phone screen.  However, there's a big difference cycling-wise between an unclassified road and a secondary road – unclassified roads are great, secondary roads are not.

It would be helpful if there was a clearer distinction between different road types.  Secondary roads especially should not be white, as it's important to easily see which ones they are – meaning they can then be more easily avoided when cycling.  Perhaps a colour-coding scheme something along the lines of darker colours the more major the road classification is, shifting to lighter colours the more minor the road classification is.  I.E.

| Road Type  | Colour |
| ------------- | ------------- |
| Trunk  | Orange (dark)  |
| Primary  | Orange (medium)  |
| Secondary  | Orange (light)  |
| Tertiary  | Yellow  |
| Unclassified  | White  |

I also use [cycle.travel](https://cycle.travel/map) quite often and find it really easy to distinguish between different road types when I'm using their maps. 

**Screenshot A – showing how different road types are displayed in OpenStreetMap style maps (zoomed out):**

[Link 1 to Bikerouter map](https://bikerouter.de/#map=13/50.8524/-4.4520/standard&lonlats=-4.485044,50.883177;-4.484756,50.827339&pois=-4.475109,50.883326,A-Road%20(highway%3Dtrunk)%20%5Bred%5D;-4.408333,50.868291,Minor%20Road%20(highway%3Dunclassified)%20%5Bthin%20white%5D;-4.384266,50.844278,Minor%20Road%20(highway%3Dtertiary)%20%5Bthick%20white%5D;-4.464947,50.829426,B-Road%20(highway%3Dsecondary)%20%5Byellow%5D;-4.400574,50.817779,A-Road%20(highway%3Dprimary)%20%5BOrange%5D&profile=fastbike-verylowtraffic)

![Screenshot A](https://github.com/organicmaps/organicmaps/assets/27423064/14ec4170-4ed3-477e-8578-ab4489798316)

**Screenshot B – showing how different road types are displayed in OpenStreetMap style maps (closer view):**

[Link 2 to Bikerouter map](https://bikerouter.de/#map=15/50.8344/-4.4917/standard&pois=-4.510961,50.839882,A-Road%20(highway%3Dtrunk)%20%5Bred%5D;-4.488035,50.829046,Minor%20Road%20(highway%3Dunclassified)%20%5Bthin%20white%5D;-4.490902,50.837579,Minor%20Road%20(highway%3Dtertiary)%20%5Bthick%20white%5D;-4.465024,50.829372,B-Road%20(highway%3Dsecondary)%20%5Byellow%5D;-4.510978,50.827469,A-Road%20(highway%3Dprimary)%20%5Borange%5D&profile=fastbike-verylowtraffic)

![Screenshot B](https://github.com/organicmaps/organicmaps/assets/27423064/ec13c588-f44f-4d94-9611-e3483ddd90c6)

**Screenshot C - showing how different road types are displayed in Organic Maps:** [GPS location 50.8344, -4.4917]

_Top image:_ This is how they are currently displayed, where it's difficult to distinguish between different road types because secondary, tertiary and unclassified roads are all coloured white and all look the same on a small phone screen.

_Bottom image:_ The same image, but with different colours added.  This is a mock-up to demonstrate how it makes it easier for a user to easily distinguish between road types when they're colour-coded and can plan their route to avoid busy roads more easily.

![Screenshot C](https://github.com/organicmaps/organicmaps/assets/27423064/c84a8aef-ecd6-479b-89a0-7cca2e236070)

**Comment by Misalf-git** [comment]
I agree on that.
More differentiating colors for roads would help to get a better sense of the surroundings and infrastructure (preferably preserving visibility for those who mix up or ignore parts of the spectrum).

As it is now, decreased thickness and transparency for minor roads prevents clutter and visual overload, but that's not quite the same as emphasizing major roads.

**Comment by Misalf-git** [comment]
#6128

**Comment by biodranik** [comment]
1. We plan a separate map style for cycling #2360. Actually, maybe even coloring in the outdoors style can be already enough. Adding more colors into the generic map style that is used by everyone may not be a good idea, it was deliberately done less cluttered. @pastk
2. Did you try to use the "Avoid highways" option in OM? Does it provide better routes? How different are they from brouter? Maybe adding the "Avoid secondary roads" option or "prefer low-traffic roads" option helps to resolve the issue even without recoloring.

**Comment by pastk** [comment]
@DesertBear re using yellow color it might conflict with some widely used background colors, see https://github.com/organicmaps/organicmaps/issues/6128#issuecomment-1734238727 and further for alternative ideas.

It might fit indeed into the outdoors style to better support a bike touring use case, but actually its more important to distinguish between paved / unpaved first.

**Comment by pastk** [comment]
BTW I made secondaries *a tad* more different from tertiaries etc. in https://github.com/organicmaps/organicmaps/pull/6590#issuecomment-1817918391, but don't expect any miracles there :)
