### ISSUE TITLE
Selected search result no longer highlighted on the map

### ISSUE THREAD

**Issue by keunes** [organicmaps/organicmaps#6695]
**Describe the issue**
The selected search result no longer highlighted on the map with a blue accent.

**Steps to reproduce**
1. Go to Search
2. Enter a search string
3. Click on one of the results

**Expected behaviour**
The selected entity (e.g. a street) is highlighted on the map.

**Screenshots**
After tapping on a search result:
![Screenshot_20231126-091602.png](https://github.com/organicmaps/organicmaps/assets/11229646/7d7e99f0-66e5-4e48-a7a1-24b877653d4a)

**System information:**
 - Operating system and its version: Android 11
 - Organic Maps version: 2023.11.17-17-FDroid
 - Device Model: Fairphone 3

**Additional context**
I would swear this was working in the previous version I had (maybe a month or two old?)

**Comment by Jean-BaptisteC** [comment]
Reproduced on Pixel 6 - Android 14
Problem appears when the result selected is not in viewport
CC @vng

**Comment by vng** [comment]
Do you folks get this problem every time? I can't reproduce on my devices.

**Comment by Jean-BaptisteC** [comment]
I'm able to reproduce with a specific position
- Start OM with this location https://www.openstreetmap.org/way/164973196#map=17/49.13959/6.16095
- Search `Boulevard André Maginot` and select first result

**Comment by hoizan** [comment]
This almost always happens with the very first search done after launching the OM

**Comment by vng** [comment]
@hoizan Please, write your device model and Android version. But better to enable logs and send them to us after reproducing the problem ("Report a bug" within the app).

**Comment by hoizan** [comment]
This bug can be reproduce as follows:
[app.log](https://github.com/organicmaps/organicmaps/files/13466701/app.log)

1) Launch OM and make a search
2) Select an item from the r searched esults
3) POI shown on map will not be highlighted
4) Make another search and pick any item from the search results. This time, the POI shown will be highlighted .
So far, I tested on 
1) Samsung S23 Ultra (Android 14)
2) Samsung S21+ (Android 13)
Attached log for S21+

**Comment by vng** [comment]
Confirm, I don't see blue highlighting either for POI or Street on the very first launch and search.

**Comment by vng** [comment]
@rtsisyk @AndrewShkrob 
This commit introduced a bug 86bbe486431994403852b736801ccd8f2415ee78
Any ideas?
