### ISSUE TITLE
app.organicmaps.routing.NavigationService.onStartCommand

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#6696]
### java.lang.SecurityException - Starting FGS with type location callerApp=ProcessRecord{82c53da 11225:app.organicmaps/u0a269} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_LOCATION] any of the permissions allOf=false [android.

  | Info | Value |
  |--------|--------|
  | appId | 1:939321867014:android:3fbc3b8e8b06da4f587c87 |
  | alertType | newFatalIssue |
  | id | 79c3db3d6b447d19876e99c1fbaad3f9 |
  | appVersion | 2023.11.22-3-Google |

**Comment by biodranik** [comment]
@rtsisyk these new issues look like a spam, and they don't have any stack traces/logs.

**Comment by rtsisyk** [comment]
yeah, I am disabled that bot
