### ISSUE TITLE
Show golf course place pins on outdoor style

### ISSUE THREAD

**Issue by rawcomposition** [organicmaps/organicmaps#6697]
When trying the new outdoor map style, I noticed that golf courses in the US look like parks with incomplete information. After noticing several of these I went to edit the map on OSM and noticed they do, indeed, have labeled places associated with them, they're just not shown in the outdoor style. This is important, at least in the US, since when looking for parks and trails, it the map looks really incomplete and I have to cross-reference with Google Maps when looking for places to hike or explore.

See screenshot from Ohio with unlabeled golf course in the center:

![IMG_2CF47E473705-1](https://github.com/organicmaps/organicmaps/assets/740090/45b53464-b4f9-47e5-a7e4-b33b1d2abdbc)

Related to #5696 but I would argue that this is really only important for the new outdoor style. Though even on the regular map, there's no way to get directions to a golf course since you can't tap on a place that's not visible.

**Comment by pastk** [comment]
Actually golf courses have an icon, but its displayed on very detailed zooms only (z17-).

I guess its also important to change a color, so that its easily recognizable as a private area (are all gold courses private / limited access?). Maybe a yellow (?) hatching pattern (we use red for military zones and green for nature reserves).

And for sure it should be improved in both main and outdoors styles.

**Comment by rawcomposition** [comment]
I see that now, if I zoom in to 200ft it shows up. The golf course was large enough that I wasn't zooming in to the correct spot to see the marker! Would be great to have them visible at less detailed zoom levels.

Styling the areas differently would be great. All golf courses that I'm aware of have been private/limited. AllTrails makes the areas transparent:

![IMG_0091](https://github.com/organicmaps/organicmaps/assets/740090/390b518a-f988-4ff0-b697-54fbd0506529)

**Comment by harshit4311** [comment]
I would love working on this issue! Could you please assign it to me?

**Comment by pastk** [comment]
> I would love working on this issue! Could you please assign it to me?

Sorry, I've almost finished working on it already, just testing is left :)

But feel free to start working on any other issue you like, you don't have to be "assigned" to do it (usually we don't use this "assignment" feature at all in OM).

**Comment by harshit4311** [comment]
> > I would love working on this issue! Could you please assign it to me?
> 
> Sorry, I've almost finished working on it already, just testing is left :)
> 
> But feel free to start working on any other issue you like, you don't have to be "assigned" to do it (usually we don't use this "assignment" feature at all in OM).

How do i make sure though that I the issue i want to work on isn't assigned to someone else?

**Comment by pastk** [comment]
> How do i make sure though that I the issue i want to work on isn't assigned to someone else?

I think just post in the issue that you're starting working on it. If someone is doing something already they will reply :)

At the moment there are many many more open issues in OM than active contributors, so such cases as just happened here (you wanted to start but I was on it already) are super rare.
