### ISSUE TITLE
Remove KAYAK ads

### ISSUE THREAD

**Issue by Mature57** [organicmaps/organicmaps#6707]
Please remove KAYAK integration.

I already reported violation is OSM license and anti-feature to F-Droid and OSM legal mail.

Spoiling project with ads is unacceptable and unexpected. You mentioned that in your app no “ads and crapware”. But not there is both.

Please don’t even try to mace any excuses or something like that. It is an ad. Small but ad.

Please remove this from your app.

P.S: For now I am searching new app to switch, if anyone knows good one please ping me.

**Comment by rtsisyk** [comment]
There are no any violation of Open Database License (ODbL). We don't add any new hotels that are not in OSM. Please check how it works in #6523 and re-read the license before making any accusations. 

Regarding interpreting the KAYAK link as an ad — let's continue in https://github.com/organicmaps/organicmaps/pull/6523. It's closed, but the discussion is still going on and we read it.

**Comment by pastk** [comment]
Why close the issue?
Its a valid request, regardless of whether its an ad or not.

And let's keep discussing in a respectful way, of course.

@Mature57 my current understanding is that the addition of the link is considered "experimental" with a purpose of
- getting more feedback from a larger community (this is what happening right here and in #6523)
- understanding how much funds the link will bring towards OM development and whether it was worth it

**Comment by Kasi78** [comment]
[They got anti feature 😂😂😂😂](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14082/diffs?commit_id=cdf6baa74e0f222ebb210ae63ca4d51a4b3807a8)

https://github.com/organicmaps/organicmaps/issues/7119
