### ISSUE TITLE
Icons improvements needed for the outdoors style

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#6713]
- [ ] the mountain_pass / saddle icon looks too heavy / big compared to mountain peaks
![image](https://github.com/organicmaps/organicmaps/assets/18434508/0f615092-1f61-4cd6-abd9-e54d0eb5e89c)

- [ ] need small versions of campsite-m, picnic-m, shelter-m, caravan_site-m, bcontrol-m and mountain-pass
- [ ] maybe a new "medium" icon for masts, flagpoles, etc. (now a "dot" is used, which is fine for low zooms, but at higher zooms would be good to have e.g. a dot surrounded by a small circle)
  - related to #5799

Those requests are mostly for the outdoors style, but some of them are needed for the generic one too (e.g. a lighter saddle icon).

**Comment by patepelo** [comment]
> * dot surrounded by a small circle)

Something like this:

![image](https://github.com/organicmaps/organicmaps/assets/23003127/3c593e61-397b-482d-92e9-101c537a3589)

**Comment by pastk** [comment]
I meant a dark dot inside a dark circle :)
(we try to make icons monochrome)

**Comment by pastk** [comment]
Great, many thanks!
Maybe make the saddle somewhat more "shallow"? Its too deep now, resembles more a skate park :)

**Comment by patepelo** [comment]
> I meant a dark dot inside a dark circle :) (we try to make icons monochrome)

Something like this?
![image](https://github.com/organicmaps/organicmaps/assets/23003127/26b02785-ada3-45cb-8826-ef56bbdec451)

**Comment by pastk** [comment]
Yes!
It just should be ~30-50% smaller than the power tower as they're for masts and flagpoles

**Comment by patepelo** [comment]
> Great, many thanks! Maybe make the saddle somewhat more "shallow"? Its too deep now, resembles more a skate park :)
> 
> I.e. maybe just remove a few pixel lines from the bottom of the original icon?

This is now the original icon resized unproportional to fit que squared area of the peak. The saddle is therefor more "shallow"

![mountain-pass-s (1)](https://github.com/organicmaps/organicmaps/assets/23003127/600eb92a-583e-484c-988b-4862d3a19ee1)
![mountain-pass-m (1)](https://github.com/organicmaps/organicmaps/assets/23003127/c7740266-6086-42ba-b7e8-23cc6d573950)

**Comment by pastk** [comment]
@patepelo could you please attach a final mast/flagpole icon?

**Comment by patepelo** [comment]
![A](https://github.com/organicmaps/organicmaps/assets/23003127/f46138f9-ce12-4d4e-9220-8e67e9169a40)
![E](https://github.com/organicmaps/organicmaps/assets/23003127/389f1729-21eb-4ef0-bfdc-4e7ea62ece7f)
![B](https://github.com/organicmaps/organicmaps/assets/23003127/4ccd91e4-67d3-4867-8284-a56503760da3)
![C](https://github.com/organicmaps/organicmaps/assets/23003127/e63e71a3-f2a7-4818-9800-005816206484)
![D](https://github.com/organicmaps/organicmaps/assets/23003127/fbe9b6f7-ad3d-4660-8e9b-5d23a608973a)

**Comment by patepelo** [comment]
Here's an antenna if you want one too 
![antenna-m](https://github.com/organicmaps/organicmaps/assets/23003127/14630721-c3b1-4404-b0d1-f709c7699a11)

**Comment by biodranik** [comment]
Aren't they too prominent and attractive? Why simple dots are not acceptable?

**Comment by pastk** [comment]
> Aren't they too prominent and attractive? Why simple dots are not acceptable?

Dots for overview zooms, small circles for detailed zooms..

**Comment by patepelo** [comment]
> @patepelo do you have an idea for a better [ford=*](https://wiki.openstreetmap.org/wiki/Key:ford) icon? E.g. maybe like a blue tilde or double tilde?

Hey @pastk, I'll be offline for a few weeks and won't be able to catch up with this icon. I'll leave here just two examples/inspirations:

![image](https://github.com/organicmaps/organicmaps/assets/23003127/3878a31d-511b-48a6-9bc4-646e0d9dba41)

And Carto's latest icon seems very accurate:

![image](https://github.com/organicmaps/organicmaps/assets/23003127/424940e6-1826-4b2d-b89c-4a03c7df2a47)


I would only add the white outline. 

Leaving just the wave like, you proposed, seems hard to understand IMO. 

CC @zyphlar
