### ISSUE TITLE
[UI] Annoying bug

### ISSUE THREAD

**Issue by ghost** [organicmaps/organicmaps#6726]
Little but super annoying. Can you please make it not overlap buttons?

![IMG_1310](https://github.com/organicmaps/organicmaps/assets/152339259/69e10d92-12bb-4122-84d4-651eedffeef7)

**Comment by biodranik** [comment]
There was another existing issue with this bug. @kirylkaveryn can you please take a look?

**Comment by Jean-BaptisteC** [comment]
Duplicate of #2556

**Comment by Hydrshg** [comment]
@Jean-BaptisteC https://github.com/organicmaps/organicmaps/issues/2556 is outdated because of redesign.
