### ISSUE TITLE
A marker on a water park displays the cinema Icon.

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6749]
![image](https://github.com/organicmaps/organicmaps/assets/170263/44d7fbe4-dde2-4e51-83a0-48b09f3b148f)

**Comment by arjundevasi** [comment]
I did some debugging and found out that 'bookmarkInfo' has id 6 for this and id 6 in 'Icon' class return entertainment icon.

**Comment by biodranik** [comment]
Good, let's understand how it works and propose the best fix for the root cause. Likely a generic bookmark icon should be ok here. Or are there any better existing icons for a water park?

**Comment by cyber-toad** [comment]
In code we have
`{"leisure-water_park", {kml::BookmarkIcon::Entertainment, BookmarkBaseType::Entertainment}},`
probably
`BookmarkBaseType::Swim`
is better.
