### ISSUE TITLE
Remove "click" sound when building route

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#675]
It's unpleasant and unnecessary. Got reports from Android, but need to check iOS too.

**Comment by endim8** [comment]
I don't think there is a click anymore, i can't hear any on max volume

**Comment by Jean-BaptisteC** [comment]
Closed because, this sound has removed, any sound is present when i click to build route on Android.
If this sound exists on IOS, I'm sure users would have opened a ticket to remove it
