### ISSUE TITLE
[android][auto] Test Android Auto implementation on CalyxOS and GrapheneOS

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#6753]
CalyxOS is adding support for Android Auto:

https://github.com/microg/GmsCore/issues/897#issuecomment-1793832674

**Comment by CaldeiraG** [comment]
Relevant but not the same OS, GrapheneOS is also adding support for Android Auto soon with their [sandboxed Google Play compatibility layer](https://grapheneos.org/usage#sandboxed-google-play) (https://twitter.com/GrapheneOS/status/1730495299196432422)

**Comment by pabloscloud** [comment]
not sure what to do exactly. I am running grapheneOS. Anything in particular that needs testing?

**Comment by CaldeiraG** [comment]
@pabloscloud seems like you're already been using it and opening issues about the issues so I guess this topic could be a to-do list or a collection of those issues

For everyone else, AA is currently available on GrapheneOS Alpha release channel.

**Comment by aszmal** [comment]
Hello, I installed GapheneOs on a Pixel 8, I am just testing android auto, I must say that it works perfectly, the main unit of tidal connects wirelessly, waze messenger, everything works as in the stock rom from google, thanks the developers of grapheneos for a great job

**Comment by pabloscloud** [comment]
For me it still won't load the route most of the times. I can select the bookmark but it keeps loading forever

**Comment by Jean-BaptisteC** [comment]
@pabloscloud too long loading about bookmarks will be fix in next version.

**Comment by pabloscloud** [comment]
> @pabloscloud too long loading about bookmarks will be fix in the next version.

For me it worked two out of two times so I guess it's working already :)

https://github.com/organicmaps/organicmaps/issues/7034#issuecomment-2019868921

**Comment by AndrewShkrob** [comment]
I can see from the comments above that AA is working on GrapheneOS, and our app has no problems (aside from the issues we already have, of course). I'm closing this issue.
