### ISSUE TITLE
[UI] Perfectionist horror XD

### ISSUE THREAD

**Issue by ghost** [organicmaps/organicmaps#6758]
Maybe I am perfectionist, but… Don’t you think it is not located properly? Fix this, please XD

![IMG_1387](https://github.com/organicmaps/organicmaps/assets/152744591/91b7b8b7-ad77-41a4-aabd-c5714481bd12)

**Comment by ashutosh-kumar-kushwaha** [comment]
I want to work on this. Please assign this to me.
