### ISSUE TITLE
[ios] Send a note to OSM editors disappeared

### ISSUE THREAD

**Issue by ghost** [organicmaps/organicmaps#6760]
Hi!

Tried to add place through your app. And found this:
![IMG_1389](https://github.com/organicmaps/organicmaps/assets/152744591/4bdef1b1-a09b-4c37-a03e-25a17cfc0d74)

Where to do this? And what does it mean? This text looks very confusing

**Comment by biodranik** [comment]
@kirylkaveryn It looks like a regression, I don't see the "Send a note to OSM editors" from screenshots in #6454. Could it break/hide the "Send a note" field?

**Comment by DicePenguin** [comment]
I can confirm that the "Send Note to OSM editors" is missing.

**Comment by biodranik** [comment]
@kirylkaveryn Android has this field enabled, so it should be enabled for iOS too (and tested).
