### ISSUE TITLE
I can't load a *.kml file into the program correctly

### ISSUE THREAD

**Issue by dmrlx** [organicmaps/organicmaps#677]
File has loaded, but "0 objects" in bookmarks list.

[Зоны, запрещённые для использования авиамоделей в Республике Беларусь.zip](https://github.com/organicmaps/organicmaps/files/6685387/default.zip)

As an ideas:
- a huge number of objects (300+)
- all objects are zones

**Comment by biodranik** [comment]
As far as I remember, we don't support yet areas from KML. It should be implemented first.

**Comment by dmrlx** [comment]
@biodranik Thanks for your answer. Will wait for implementation.
