### ISSUE TITLE
Replace kayak crap with new type of orientation

### ISSUE THREAD

**Issue by ghost** [organicmaps/organicmaps#6774]
### IT IS SEPARATE ISSUE. NOT DUPLICATE

You got a lot of hate about kayak crap. And in one of your excuses you told that users asked you to have photos. [Proof](https://github.com/organicmaps/organicmaps/pull/6523#issuecomment-1830464393) and 
[screenshot of proof](https://github.com/organicmaps/organicmaps/assets/152821853/fca4f1d7-ab0a-4a86-a21e-1b51bfd8252f) (for case you will try to hide it)

How about adding this instead of kayak crap?

Just add satellite images from https://map.openaerialmap.org/. Or add https://www.360cities.net/map to use photos

**Comment by Kasi78** [comment]
[They got anti feature 😂😂😂😂](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14082/diffs?commit_id=cdf6baa74e0f222ebb210ae63ca4d51a4b3807a8)

https://github.com/organicmaps/organicmaps/issues/7119 

By the way @RedAuburn not helpful why? Because you will not have money? 😂😂😂
