### ISSUE TITLE
[routing] Can't build a ferry route

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#6787]
App version: 653647cfa07c8af2f8ac5ecce02deb3b4a7fd34e (latest master)
Data version:  2023-11-13
Start point: [35.3431512, 33.3321387](https://www.openstreetmap.org/#map=18/35.3431512/33.3321387)
End point: [36.3135198, 33.8949451](https://www.openstreetmap.org/#map=18/36.3135198/33.8949451)

https://github.com/organicmaps/organicmaps/assets/1799054/ee89d554-902b-4cdd-bf00-8e47c5cf34d5

<img src="https://github.com/organicmaps/organicmaps/assets/1799054/1420874e-6c41-44a1-9311-b488233005f2" width="350px">

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.03.27-3-Google version
