### ISSUE TITLE
Android Auto in production

### ISSUE THREAD

**Issue by argrento** [organicmaps/organicmaps#679]
It would be awesome, if OrganicMaps support Android Auto, to make a good alternative to Waze/Google Maps etc.

**Comment by gthbusrr** [comment]
Hi, is it still in roadmap? Thanks :)

**Comment by biodranik** [comment]
It is.

**Comment by w202mg** [comment]
Would be really cool

**Comment by argrento** [comment]
Hi, gyus! Any updates or plans on the AA support?

**Comment by biodranik** [comment]
We're still looking for cool android devs to help us, because now our small team fixes a number of important bugs and other features.

**Comment by avinash14022002** [comment]
Hi @biodranik ,
Wanted to work on this issue can anyone let me know where to start?

as well as we migrate complete java code to kotlin to handle better null pointer exception.

**Comment by biodranik** [comment]
Start from the documentation. We don't plan to migrate to Kotlin. It was already discussed in #2212

**Comment by shankarpriyank** [comment]
Hey @biodranik how do I get started with this , couldn't really understand "Start from Documentation"

**Comment by biodranik** [comment]
1. Read docs about Android Auto.
2. Read docs in our repo about how to compile the code.
3. Check our existing code.
4. Highlight all found issues and potential blockers and plan how to integrate the Android Auto feature.

**Comment by shankarpriyank** [comment]
Okay , I am on it

**Comment by anant01tyagi** [comment]
Hello @biodranik . I am looking to work on this project as part of GSOC '22. Where should I start from and what should I do to strengthen my chances?

**Comment by biodranik** [comment]
The list is in my above comment. I would add that if you try to fix any other existing issues that increases your chances.

**Comment by deepak7488** [comment]
Hello @biodranik.  I am also looking to work on this project as part of GSOC '22. Can you provide a proposal template and also guide me to work on this.

**Comment by poojan-1510** [comment]
hi @biodranik can u please provide us with the project set up as I could not find specific mention about it on the Git hub page

**Comment by poojan-1510** [comment]
hi, can anyone pls help me with android\secure.properties' as it does not exist. I encoutered it during setting up the project.

**Comment by shankarpriyank** [comment]
Hey poojan have a look at the readme , you will find l the links and the instructions there,  also the error you are getting is because you have not configured your project correctly

**Comment by biodranik** [comment]
@deepak7488 sorry, I don't understand your question. All our GSoC ideas are described in the wiki: https://github.com/organicmaps/organicmaps/wiki/GSoC-2022-ideas

I described how to move on with Android Auto in another comment above.

@poojan-1510 You did not read/follow the documentation and did not run `./configure.sh` script.

Guys, if you want to contribute to an open-source project, please carefully read all documentation first before asking any questions. And then try to follow all the listed steps.

**Comment by anant01tyagi** [comment]
Hi!
Can anyone please specify what configuration is needed to run the project in android studio emulator in windows?
The documentation said no action is needed for configuration in windows, however studio is asking me to add a configuration.

**Comment by Jdbarad** [comment]
I like to work on this issue for GSoC 2022

**Comment by anant01tyagi** [comment]
Hi @biodranik ! Any guidelines for the GSOC proposal? What all should it include?

**Comment by biodranik** [comment]
Here is the link: https://organicmaps.app/news/2022-04-11/some-guidelines-for-google-summer-of-code-2022-gsoc-participants-who-want-to-become-open-source-contributors-to-organic-maps/

**Comment by ArduousBrain** [comment]
hi , I am getting error while setting up cmake file 
>
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

I tried 
>SET(CMAKE_C_COMPILER C:/MinGW/bin/gcc)
to cmakelists.txt

what else can I try

**Comment by biodranik** [comment]
Are you trying to build for Android or for desktop?

For Android, on Windows, you don't need to use MinGW. Just install Android Studio with NDK, cmake and ninja, and it should work. Sometimes setting paths in local.properties file also helps.

**Comment by ArduousBrain** [comment]
@biodranik yes, I did that before , but it said that Cmake version 1.9 + is required so I installed Cmake 3.23.1 but now it says to compile it .That is where I am facing trouble .If you could help me with that, that would be great.

**Comment by ArduousBrain** [comment]
My configure.sh file is asking me to choose an toolset . which one should I
 choose

**Comment by biodranik** [comment]
It's hard to help you without seeing the logs and understanding the context )

**Comment by ArduousBrain** [comment]
Initializing repository with default values in Open-Source mode.

Could not find a suitable toolset.

You can specify the toolset as the argument, i.e.:
    ./build.sh [options] gcc

Toolsets supported by this script are:
    acc, clang, como, gcc, intel-darwin, intel-linux, kcc, kylix, mipspro,
    pathscale, pgi, qcc, sun, sunpro, tru64cxx, vacpp

For any toolset you can override the path to the compiler with the '--cxx'
option. You can also use additional flags for the compiler with the
'--cxxflags' option.

A special toolset; cxx, is available which is used as a fallback when a more
specific toolset is not found and the cxx command is detected. The 'cxx'
toolset will use the '--cxx' and '--cxxflags' options, if present.

Options:
    --help                  Show this help message.
    --verbose               Show messages about what this script is doing.
    --debug                 Build b2 with debug information, and no
                            optimizations.
    --guess-toolset         Print the toolset we can detect for building.
    --cxx=CXX               The compiler exec to use instead of the detected
                            compiler exec.
    --cxxflags=CXXFLAGS     The compiler flags to use in addition to the
                            flags for the detected compiler.


Building B2 engine..

Could not find a suitable toolset.

You can specify the toolset as the argument, i.e.:
    ./build.sh [options] gcc

Toolsets supported by this script are:
    acc, clang, como, gcc, intel-darwin, intel-linux, kcc, kylix, mipspro,
    pathscale, pgi, qcc, sun, sunpro, tru64cxx, vacpp

For any toolset you can override the path to the compiler with the '--cxx'
option. You can also use additional flags for the compiler with the
'--cxxflags' option.

A special toolset; cxx, is available which is used as a fallback when a more
specific toolset is not found and the cxx command is detected. The 'cxx'
toolset will use the '--cxx' and '--cxxflags' options, if present.

Options:
    --help                  Show this help message.
    --verbose               Show messages about what this script is doing.
    --debug                 Build b2 with debug information, and no
                            optimizations.
    --guess-toolset         Print the toolset we can detect for building.
    --cxx=CXX               The compiler exec to use instead of the detected
                            compiler exec.
    --cxxflags=CXXFLAGS     The compiler flags to use in addition to the
                            flags for the detected compiler.



Failed to build B2 build engine

**Comment by biodranik** [comment]
You either need to run it from Visual Studio Command Prompt (it sets VS compiler environment) or properly set up MinGW compiler and run the command from the corresponding bash prompt. Or alternatively, run it from the WSL(2) command prompt environment (ubuntu for windows) with GCC installed. It is mentioned in documentation BTW.

**Comment by biodranik** [comment]
Let's implement its support first )

**Comment by andrewshadura** [comment]
I'm not sure why performance is important for the front-end given that all CPU-heavy code is in C++. The performance hit is negligible compared to the huge safety and convenience improvements.

**Comment by biodranik** [comment]
@andrewshadura why are you mentioning the performance here?

OSMand and MapsMe are great examples of why performance and battery matter everywhere, not just in the core.

**Comment by andrewshadura** [comment]
I think I replied to a wrong thread. O distinctively remember posting that into the Kotlin thread, not sure how it ended up here 😄

-- 
Cheers,
  Andrej

**Comment by chrisdebian** [comment]
> Here is the link: https://organicmaps.app/news/2022-04-11/some-guidelines-for-google-summer-of-code-2022-gsoc-participants-who-want-to-become-open-source-contributors-to-organic-maps/

Hi, all.

I'm keen to use Organic on Android Auto. Sadly I can't help implement this, so feel awkward asking; is Android Auto and closer to becoming a feature?

Many thanks,

Chris
chris_debian

**Comment by chrisdebian** [comment]
Hi, Roman.

I'm already part of the Beta, so hopefully I'll be able to report back.

Thanks,

Chris.
chris_debian

**Comment by replicajune** [comment]
I got a secondary phone and android auto works on it, I can also definitely participate in the beta if more testers are needed :). I'm based in North America if this matters.

Thanks for this feature and I can't wait to see it live 🥳

**Comment by Misalf-git** [comment]
If you're using Telegram, betas are also posted there: https://t.me/OrganicMapsApp

**Comment by AndrewShkrob** [comment]
Android Auto is now available on Google Play. 
Please monitor active Android Auto issues with the ["Android Auto" label](https://github.com/organicmaps/organicmaps/issues?q=is%3Aopen+is%3Aissue+label%3AAndroidAuto).

I am closing this issue.
