### ISSUE TITLE
Add wifi to railway stations

### ISSUE THREAD

**Issue by konfiot** [organicmaps/organicmaps#6793]
Hello,
I am not able to indicate that there is wifi in a railway station because the on/off switch is not présent for that type of infrastructure
 Would it be possible to add it ?
Thanks

**Comment by biodranik** [comment]
Can you please provide a link to the railway station in openstreetmap.org where wifi is not displayed in Organic Maps?

**Comment by konfiot** [comment]
![Screenshot_20231207-210742_Organic Maps](https://github.com/organicmaps/organicmaps/assets/961690/321f8020-b46d-4c44-a151-2359e944471e)
![Screenshot_20231207-210745_Organic Maps](https://github.com/organicmaps/organicmaps/assets/961690/87376cdb-e67b-4d64-b627-d641d9d5bb30)
Yep, for example "Gare du nord" in paris, I can't add wifi when editing the station

**Comment by konfiot** [comment]
Yes I know that I can edit it directly, but i wanted to edit it directly in organicmaps. I've also tried to do it on the corresponding building, but same problem in organicmaps

**Comment by biodranik** [comment]
Let's check with the OSM community about the rules of proper wifi tagging for stations first. After that, we can try to enable editing if it doesn't break something else.

**Comment by konfiot** [comment]
The wiki page seems to indicate that both nodes or polygons can be the target of internet_access=wlan : https://wiki.openstreetmap.org/wiki/Tag:internet_access%3Dwlan
Although in that particular cases, and at least for railway stations in france, I'd suggest putting it on the node as the wifi spans the whole station, including underground parts which do not necessarly appear as a polygon
Moreover, putting it on the node seems more appropriate if i want to search for "WiFi nearby", i'd prefer having the name of the station over having the building, which may not have the name of the station

Also looking at Switzerland it seems that lot of stations do already have the tag on the node : https://overpass-turbo.eu/map.html?Q=%2F%2F+%40name+Drinking+Water%0A%0A%2F*%0AThis+is+an+example+Overpass+query.%0ATry+it+out+by+pressing+the+Run+button+above%21%0AYou+can+find+more+examples+with+the+Load+tool.%0A*%2F%0Anode%0A++%5Brailway%3Dstation%5D%0A%5Binternet_access%3Dwlan%5D%0A++%2846.57019056757178%2C7.19329833984375%2C48.26491251331118%2C10.090942382812502%29%3B%0Aout%3B
