### ISSUE TITLE
add kind of places : climbing site - trail station -sundial 

### ISSUE THREAD

**Issue by paysdesecrins** [organicmaps/organicmaps#6794]
Hello, we would add some places in our city like climbing sites, trail station and sundial. But there is nothing which looks like to this in the list elements of the app...
Is it possible to add this kind of places ?

**Comment by biodranik** [comment]
Please add all possible types of objects directly at OpenStreetMap.org, the editor in Organic Maps has a limited subset of all features of OSM.org and other mobile editors like Vespucci, Street Complete, EveryDoor, or Go! Map.

We plan to improve the editor, but only after finishing working on some other important features.
