### ISSUE TITLE
[ios] Night mode set to »auto« doesn't do anything

### ISSUE THREAD

**Issue by jk** [organicmaps/organicmaps#680]
I've wondered if the App doesn't support dark mode on iOS. But looking at the settings there is a nigh mode set to »auto«. Which just does nothing. Albeit setting manually to on/off DOES toggle between night and day mode. Looks like a bug to me.

**Comment by biodranik** [comment]
A bug indeed!

**Comment by rtsisyk** [comment]
"Auto" should enable dark mode only during navigation.

**Comment by rtsisyk** [comment]
I drafted a proposal: https://github.com/organicmaps/organicmaps/issues/749
Please review and comment.

**Comment by Raycock2** [comment]
Above problem with auto still exists in newest version. Still does not auto switch between dark and light mode.

**Comment by biodranik** [comment]
It works only for the navigation mode now (this setting is in the "Navigation" section).

**Comment by Esmolante** [comment]
I find fine that only works in navigation mode, but the problem is that it doesn't work while you're navigating if night comes while you are driving. You have to exit the navigation and re-enter to have the night mode.
