### ISSUE TITLE
Large forest is displayed as Unknown place and is not green

### ISSUE THREAD

**Issue by dbf256** [organicmaps/organicmaps#6807]
2023.11.17

Osm https://www.openstreetmap.org/relation/3410#map=11/52.4564/13.2248

**Comment by dbf256** [comment]
![Screenshot_2023-12-09-13-08-46-520_app organicmaps](https://github.com/organicmaps/organicmaps/assets/2550295/d9350506-4caf-4f3c-9942-e03f9c20c5c3)

**Comment by Misalf-git** [comment]
Seems to have been a data issue that's already fixed for 231130 (next update).
![Berlin_Grunewald.png](https://github.com/organicmaps/organicmaps/assets/72605561/d66c5c5c-91e0-4943-92a8-c0a9abe28c11)

**Comment by biodranik** [comment]
Yes, if there was a bug in OSM map data when maps were generated, some large objects may be absent.
