### ISSUE TITLE
bookmark in multiple list

### ISSUE THREAD

**Issue by ghtesting2020** [organicmaps/organicmaps#6816]
**Is your feature request related to a problem? Please describe.**
It would be nice able to add bookmarks to multiple list.

Example in city of New York I want to pin lots of nice thing including gas station but in another list I only want gas stations when planning trip across the state of new york.

**Describe the ideal solution**
Being able to add bookmark to multiple list

**Describe alternatives you have considered**
No solution

**Additional context**
None

**Comment by Jean-BaptisteC** [comment]
Duplicate of #4160
