### ISSUE TITLE
[iOS] Editing a bookmark name does not update how it’s displayed right away

### ISSUE THREAD

**Issue by beyondcompute** [organicmaps/organicmaps#682]
See the following video. I needed to tap away from the bookmark and then tap it again to see the updated name.

https://user-images.githubusercontent.com/248055/122774048-8b1e5f80-d2b1-11eb-9328-b7cb4d9160bd.MP4

A similar thing happens after deleting a bookmark. The name, etc. is still displayed at the bottom of the screen even as the marker already gone from the map.

**Comment by Jean-BaptisteC** [comment]
Video is not available, can you reupload ?
