### ISSUE TITLE
parking_space is rendered incorrectly

### ISSUE THREAD

**Issue by brandoncote** [organicmaps/organicmaps#684]
we should follow the same rendering method that cartocss / the osm.org map uses

https://t.me/organicmaps/4298

https://t.me/organicmaps/4299

**Comment by anibyl** [comment]
`amenity=parking_space` should not be marked with 🅿️ as it is a part of `amenity=parking` ([source](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking_space)).

**Comment by mellangr** [comment]
example of a possible rendering `amenity=parking_space`

![photo_2021-06-21_18-39-18](https://user-images.githubusercontent.com/20912330/125185852-c0262e00-e22f-11eb-8ac3-d879fcbe6a97.jpg)

**Comment by endim8** [comment]
Definite +1 for this issue, I don't think _that_ many parking icons are needed 😅

(https://omaps.app/84IIKjMXh6/ is the location)
![Screenshot_20210905-044455_Organic_Maps](https://user-images.githubusercontent.com/26939824/132114274-4bdd317f-73ec-40d0-a1f3-571e2c9b8749.png)

**Comment by pastk** [comment]
To fix just remove `amenity=parking_space` from `data/styles/clear/include/Icons.mapcss` and `data/styles/vehicle/include/Icons.mapcss`
