### ISSUE TITLE
pronounce speech on ios

### ISSUE THREAD

**Issue by parduspanteri** [organicmaps/organicmaps#6840]
Organic Maps does not respect the system choice of the voice and always uses a default TTS voice for the language. The user's system choice of voice should be respected by Organic Maps.

![выява](https://github.com/organicmaps/organicmaps/assets/170263/208edca5-6ed2-4567-ab84-5312412dcb78)

**Comment by biodranik** [comment]
1. What exactly is wrong with pronunciation?
2. What is your voice language?
3. What is Siri Voice 2?
4. Is it available on iOS 12, 13, 14, 15, 16, 17?

**Comment by biodranik** [comment]
Thanks, I've updated the issue.
