### ISSUE TITLE
Bug: app doesn't open anymore on android 5

### ISSUE THREAD

**Issue by Altonss** [organicmaps/organicmaps#685]
I just updated to 2021.06.12-7-g75fd600f97-FDroid and the app just doesn't open anymore. I tried to reinstall it but the problem is still there.
My phone is running on Android 5.0.2 and I downloaded the app from F-Droid.

**Comment by ooprizrakoo** [comment]
Please update your App. New version available - now at Play Market, soon at F-Droid.

**Comment by Altonss** [comment]
Thanks I will wait for the Fdroid update and give you feedback if it works ;)

**Comment by ooprizrakoo** [comment]
![image](https://user-images.githubusercontent.com/661813/122809609-fe869800-d2d6-11eb-94f1-1740aaac5c0f.png)
:)

**Comment by rtsisyk** [comment]
https://gitlab.com/fdroid/fdroiddata/-/commit/7beb87085bc3cca26369d1a8b756a374143426a6

**Comment by Altonss** [comment]
The update just arrived in the F-Droid repository, I downloaded it, and it works again now! Thanks a lot :)
