### ISSUE TITLE
[ios] Add Test Voice button in TTS voice settings

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6850]
Android already has this feature.

![telegram-cloud-photo-size-2-5472077077621624771-y](https://github.com/organicmaps/organicmaps/assets/170263/b424c9cc-30b2-4812-a3a5-f036a09bfadf)

**Comment by biodranik** [comment]
@fabwu can you please add this button? Some users are confused if TTS is set up properly. 

Android plays randomly chosen phrases from a list, there was a discussion in a merged PR. It would be great to do the same on iOS.

**Comment by fabwu** [comment]
> @fabwu can you please add this button? Some users are confused if TTS is set up properly.

Yes sure I can try :)

**Comment by fabwu** [comment]
For reference the Android TTS test PR: https://github.com/organicmaps/organicmaps/pull/5859
