### ISSUE TITLE
Multi storey parking garage type description error

### ISSUE THREAD

**Issue by jmarchon1** [organicmaps/organicmaps#6854]
**Describe the issue**
When tapping on a paid multi-storey parking garage, the description under the name says "type.amenity.parking.multi-storey.fee" instead of something like "Paid parking garage".

**Steps to reproduce**
1. Go to any `amenity=parking` with `parking=multi-storey` and `fee=yes`.
2. Tap on it
3. See error

**Screenshots**
![image](https://github.com/organicmaps/organicmaps/assets/50030493/bf8b7820-5caf-4db9-a08c-9d464e54941e)
Example here is https://www.openstreetmap.org/way/45088437
Note that I have edited this parking lot since the last OM update. The descriptive name has since been removed.

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: 2023.11.17-18-Google
 - Device Model: Pixel 6a

**Comment by biodranik** [comment]
@vng @dvdmrtnz @RedAuburn can you please check if a correct translation is already present and reuse it with `ref = ` in types_strings.txt, or add a missing translation if necessary?

**Comment by vng** [comment]
Fixed some time ago.
