### ISSUE TITLE
Dark UI

### ISSUE THREAD

**Issue by DicePenguin** [organicmaps/organicmaps#6855]
**Is your feature request related to a problem? Please describe.**
When I switch to a Dark theme on my iphone XR the UI on organic maps doesn't detect it.

**Describe the ideal solution**
It would be ideal if the application follows the UI theme of the device. 

**Describe alternatives you have considered**
Another solution might be to add a setting in the application to change the UI without changing the map theme.

**Additional context**
For reference, I'm using an iPhone XR running iOS 17.1.2

**Comment by biodranik** [comment]
Please follow https://github.com/organicmaps/organicmaps/issues/749 for this issue.
