### ISSUE TITLE
[ios] App is not included into CarPlay

### ISSUE THREAD

**Issue by aism** [organicmaps/organicmaps#686]
Hello,

App is not included into CarPlay:
https://user-images.githubusercontent.com/699194/122805764-c9277d80-d2c9-11eb-8fd1-892e39df2db0.MP4

The CarPlay support is advertised from version 2021.06.18.

Details:
- iPhone 6s Plus, ios 14.6 (18F72)
- app version 2021.06.18.1, Data version 219529
- app is freshly installed.

Troubleshooting performed:
- closing and reopening the app
- restarting the phone

**Comment by biodranik** [comment]
What is this NissanConnect app? How does it detect CarPlay enabled apps?

**Comment by aism** [comment]
> What is this NissanConnect app? How does it detect CarPlay enabled apps?

It's not an app (well, there's one called like this but it's irrelevant here) - it's the name of the car (dunno where it pulls it from).
iPhone -> Settings -> General -> CarPlay -> MyCar -> %car_name% ("NissanConnect" in my case) -> Customize -> %list of CarPlay-enabled apps.%

Check here ("Arrange your CarPlay apps"): https://support.apple.com/en-us/HT205634

**Comment by hafenschiffer** [comment]
I do have the same problem
- iPhone 11 Pro
- iOS 14.6 (18F72)
- App version 2021.06.18.1 Data version: 210529

Car is VW, not sure if that is important...

Trouble shooting performed:
- Uninstalled App
- Restarted iPhone
- Reinstalled App
- Opened App
- Restarted iPhone
- Opened App

Still no luck :(

**Comment by biodranik** [comment]
Looks like car play entitlements were not properly integrated into the latest build. Fixed in #691

**Comment by al-nn** [comment]
Version 2021.06.22 : still no changes, no real carplay support after double changelog announces.
(Iphone x, ios 14.6, app 2021.06.22)

**Comment by hafenschiffer** [comment]
It works for me now. I did restart the iPhone after installing the latest update yesterday.

**Comment by al-nn** [comment]
> It works for me now. I did restart the iPhone after installing the latest update yesterday.

Thank you! Yes, device restart fixed trouble for me too.

**Comment by biodranik** [comment]
Fixed! Thanks to everyone!
