### ISSUE TITLE
One only backup file for all countries (points of interest)

### ISSUE THREAD

**Issue by serrq** [organicmaps/organicmaps#6865]
I have at least 25 countries saved locally. 25 "import" actions must I doing?

![1000102027](https://github.com/organicmaps/organicmaps/assets/113377431/d2a4dbb8-7fcc-4796-8835-3cc08a44ed49)

**Comment by biodranik** [comment]
Closing as a duplicate of #995

**Comment by biodranik** [comment]
What else do you need to backup in Organic Maps in addition to Bookmarks?
