### ISSUE TITLE
Please, add button to delete any external links

### ISSUE THREAD

**Issue by ghost** [organicmaps/organicmaps#6867]
I see https://github.com/organicmaps/organicmaps/pull/6863 privacy menu on screenshot. Can you also add a switch to remove anything external (like kayak, facebook, twitter or other shit that doesn’t respect users privacy)

This will protect privacy geeks from being exposed to any data brokers or other not welcome services.

Thank you for your understanding.

**Comment by RedAuburn** [comment]
see https://github.com/organicmaps/organicmaps/pull/6720

**Comment by biodranik** [comment]
If privacy geeks won't click explicitly displayed/marked links, their privacy won't be compromised. Closing as duplicate.
