### ISSUE TITLE
[ios] “Suggested changes” pop-ui is too high

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#6876]
**Describe the issue**
After reporting a place is closed, a pop-up appears saying that the requested changes have been sent. The problem is that the pop-up is too high, and is obstructed by my phone’s UI.

**Steps to reproduce**
1. Log into your OpenStreetMaps account
2. Edit a place
3. Mark it as “does not exist” and fill out the information requiewd
4. Submit the changes
5. See error

**Expected behaviour**
The pop-up should be lowered, so that it is not obstructed by the system UI.

**Screenshots**
![image](https://github.com/organicmaps/organicmaps/assets/50059322/1517dec3-c7f9-4f42-b8f0-98ae0a56b37d)

**System information:**
 - Operating system and its version: iOS 17.1.2
 - Organic Maps version: Version: ⁦2023.12.16-26⁩
 - Device Model: iPhone 14 Plus

**Additional context**
N/A

**Comment by biodranik** [comment]
An easy fix should use a toast-like message that is used in other places (e.g. when suggesting to zoom in to see isolines). @kirylkaveryn what are other toasts we have in the code?
