### ISSUE TITLE
Incorrect display of POI details for fuel stations

### ISSUE THREAD

**Issue by muralito** [organicmaps/organicmaps#6882]
**Describe the issue**
The information details for fuel station in same cases is wrong, priotitizing shop=yes or compressed_air=yes instead of amenity=fuel_station

**Steps to reproduce**
Select any fuel station POI and show its details.
The nodes listed here corresponds to the screenshots below
https://www.openstreetmap.org/node/4415553011
https://www.openstreetmap.org/node/1634035577
https://www.openstreetmap.org/node/427855756
https://www.openstreetmap.org/node/2508987962

**Expected behaviour**
The main feature is Fuel Station, and i think it is what should be displayed. shop=yes or compressed_air are additional properties of this POI, and maybe should be displayed, but not as the main feature.

Also, the "brand" is at the same importance of the name,and should be displayed in the same line, after or before the name.
When there are nor name, nor brand, IMO, the "operator" is more important than the addresss.

A similar problem occurs in the search list.

**Screenshots**
![Screenshot_20231216-182935](https://github.com/organicmaps/organicmaps/assets/7611868/9f600a62-207a-49de-b955-e8595de81e92)
![Screenshot_20231216-182839](https://github.com/organicmaps/organicmaps/assets/7611868/ccc5c508-1c55-4751-9708-f58bd61101d2)
![Screenshot_20231216-182659](https://github.com/organicmaps/organicmaps/assets/7611868/7483dce8-f056-43ab-b42f-cbbca8fe1a97)
![Screenshot_20231216-182735](https://github.com/organicmaps/organicmaps/assets/7611868/a0fa69a0-167b-45fd-bb9c-ec020add5fe8)
![Screenshot_20231216-182819](https://github.com/organicmaps/organicmaps/assets/7611868/39b8759a-b97c-41ab-89a3-8e655a6c5504)

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.11.17-17-FDroid
 - Device Model:

**Additional context**
OM is running with the spanish translation.

**Comment by muralito** [comment]
The worst parts of this issue were fixed in version 2023.12.18-11-FDroid.

The suggestion to put the "brand" at the same level of the "name" remains.

**Comment by Jean-BaptisteC** [comment]
We cannot show the brand on the same line of name, because we don't have enough place to show 2 information on the same line, especially on little devices.

**Comment by dvdmrtnz** [comment]
I agree with @muralito in this: When a place has no `name` tag but has `brand` tag, it makes sense to use the `brand` value as the name in the search results instead of using the address information as the name.

Same example shown in previous screenshots: 

https://www.openstreetmap.org/node/4414166773#map=19/-34.91513/-56.18491

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/23d4b4c2-fa8a-43c1-999f-f274fcee5683" width="320"/>

**Comment by muralito** [comment]
> We cannot show the brand on the same line of name, because we don't have enough place to show 2 information on the same line, especially on little devices.

Can you clarify what do you call little devices?
In the search results screenshots that @dvdmrtnz and I posted earlier, it seems to me that name and brand could be displayed, as name is shorter than half line, and brands are 4 or 5 additional characters. Also in several result items, the address information is displayed twice, once in boldface, and two lines below in italics.

BTW, i have tagged a lot of elements with tag short_name and I haven't seen any app using it used when the display area is small...
