### ISSUE TITLE
Show on the lock screen

### ISSUE THREAD

**Issue by M4skid** [organicmaps/organicmaps#6891]
"Show on the lock screen" doesn't work.
Still ask for password when i try to open it.

 - Android 8
 - Organic Maps version: 2023.11.17-18-Google
 - Device Model: Galaxy J5 Prime (SM-G570M)

**Comment by biodranik** [comment]
Does it work in any other app? Do you have any custom ROM/Launcher?

**Comment by M4skid** [comment]
it works on Open Camera. https://play.google.com/store/apps/details?id=net.sourceforge.opencamera&hl=en_US&gl=US
I'm using stock rom with Niagara Launcher https://play.google.com/store/apps/details?id=bitpit.launcher&hl=en_US&gl=US

**Comment by biodranik** [comment]
Maybe our implementation doesn't work properly on Android 8, need to check it.

CC @Jean-BaptisteC

**Comment by Jean-BaptisteC** [comment]
@M4skid can you retry on the latest version?
