### ISSUE TITLE
tourism=attraction should not replace other poi types

### ISSUE THREAD

**Issue by j13m126** [organicmaps/organicmaps#6892]
As described [here](https://github.com/organicmaps/organicmaps/issues/6016), I think tourism=attraction as a type should not replace the actual poi type (theater, café, castle, church, ...). This is currently the case for some poi types, which leaves the user guessing what the poi actually is. The tag "attraction" could be shown next to it.

Here is a draft of my suggestion:

![Screenshot_20231218-220818.png](https://github.com/organicmaps/organicmaps/assets/7961926/d3cec32c-7fe0-4a10-8117-9eafc04fad14)

**Comment by biodranik** [comment]
#6842 will be helpful

**Comment by pastk** [comment]
Discussed in 
- #6332

**Comment by dvdmrtnz** [comment]
* This was fixed in https://github.com/organicmaps/organicmaps/pull/8481. Now all relevant types are shown on the place page

**Comment by patepelo** [comment]
I'd say it isn't completly resolved icon wise. Please take a look (latest android version)
![image](https://github.com/user-attachments/assets/d273dc2c-b133-4772-9dd0-47b1857b679b)
