### ISSUE TITLE
[Partially Solved] Unable to import any bookmark in Organic Maps

### ISSUE THREAD

**Issue by LaurentGrenet** [organicmaps/organicmaps#6897]
If I try to import bookmarks from KML/KMZ/GPX file, using ""Import Bookmark and Tracks", this opens a file browser in which it is not possible to select any file...

[EDIT] Ooops : I juts discovered that we do not have to select the KMZ file itself, but rather the folder containing the KMZ(s) file(s)
And doing so it works.

On the other hand, if I browse my files, then open one of theseKML/KMZ/GPX file with Organic Maps, this starts the app.... but doesn't import anything in bookmarks....

[EDIT] But this second point still do not work. Is it  bug, or "behaviour as design" ? In this case, what does it mean to "open a KMZ file with OM" ? 

How could I import my bookmarks ?
[EDIT] : They are now imported.

I precise that these bookmarks were until recently stored and managed in Organic Maps (and I don't remember how I created them in the past in OM), but have been lost because I had to completely refresh my phone, and then re-install Organic Maps from crash.

And I can add that I have tested the following : create manually a bookmark in OM, export it as KMZ file, then erase it in OM. Even this KMZ fie cannot be imported....

**System information:**
 - Android 7
 - Organic Maps version: 2023.11.17-17-FDroid
 - Device Model: Samsung Galaxy A3-2016

**Comment by biodranik** [comment]
The current button allows importing KML, KMZ, GPX from a folder. There is an issue to allow importing of a single file #5413

Closing it as a duplicate.
