### ISSUE TITLE
App crashes or closes immediately after start

### ISSUE THREAD

**Issue by ioogithub** [organicmaps/organicmaps#690]
There isn't very much to report other than the app crashes as soon as it is launched. I have never been able to use it at all. I have tried it on two devices, the app crashes immediately on both.

Devices: Moto G7, Moto G7+
OS: LineageOS 17.0, 17.1
Version: 2021.05.21-6-g6cfa29a770-FDroid

Other similar map apps work- Maps and Maps.me work as expected.

This may be similar to this issue: https://github.com/organicmaps/organicmaps/issues/657 only I am not using this phone or the version from Google play.

Another issue here: https://github.com/organicmaps/organicmaps/issues/619 although I do not have an Android file in my /sdcard

The logcat data is reporting:

FATAL EXCEPTION: main
java.lang.IllegalArgumentException: Failed to find storage device at null

I can confirm my storage devices are all properly mounted.

**Comment by biodranik** [comment]
That's a very outdated version, we have already fixed many issues, and plan to update it ASAP.
CC @rtsisyk

**Comment by rtsisyk** [comment]
https://gitlab.com/fdroid/fdroiddata/-/commit/7beb87085bc3cca26369d1a8b756a374143426a6
