### ISSUE TITLE
Isolines are not visible in the dark theme

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6901]
Especially Outdoors style should highlight them.

**Comment by pastk** [comment]
I think #6590 fixes it already, e.g. this is how it looks in the latest beta:

**Comment by pastk** [comment]
main dark

![Screenshot_20231219-220635.jpg](https://github.com/organicmaps/organicmaps/assets/18434508/c35b1248-92e8-4750-a63a-734242f13e0a)

outdoor dark

![Screenshot_20231219-220719.jpg](https://github.com/organicmaps/organicmaps/assets/18434508/9011267c-b25b-46e0-8799-56dc43d87e9c)

**Comment by pastk** [comment]
For comparison: this is how it was in dark outdoors before #6590 (i.e. in the Dec release)
![image](https://github.com/organicmaps/organicmaps/assets/18434508/0cb65188-3079-412b-beaa-4e8136caa4df)

**Comment by biodranik** [comment]
Tested on iOS. They are too bright now IMO in both general and outdoor styles, and make the map hardly usable, especially in completely dark environments.

**Comment by pastk** [comment]
Fixed in https://github.com/organicmaps/organicmaps/pull/6590#issuecomment-1868350493
