### ISSUE TITLE
[android] Remove all third-party links from the manifest

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#6907]
Third-party links don't work on new Android anyway. Plus we don't parse the most of them properly (see https://github.com/organicmaps/organicmaps/issues/475). Because of third-party unverified domains, our "omaps.app" short links are open in the browser...

<img width="1111" alt="image" src="https://github.com/organicmaps/organicmaps/assets/1799054/d30f4b3c-3d59-49c5-a273-e706fff344eb">

**Comment by jayb-g** [comment]
Why were third party links removed from Organic Maps? I don't understand, it used to work fine with most third party links at least google maps as long as it used to work until few months back(using latest AOSP on pixel7) OM update and now it just supports two links. 

There are still other apps such as geddit, octodroid, labcoat for example that still use and work fine with opening third party domains. 

If it isn't an option anymore for OM, can it be supported to just be able to use 'share' a link from say a browser and see organic maps as an option to share with? (For links that OM can handle)

**Comment by biodranik** [comment]
@meenbeese @rtsisyk which problem was solved by removing these links? What exactly was improved in the app for users?

As far as I understood, it worked fine on older androids. Now it doesn't work, correct?

**Comment by jayb-g** [comment]
@biodranik I think it still works as per my testing if the app adds back supported links

**Comment by biodranik** [comment]
@jayb-g let's restore them back and test properly. Can you check a debug build from the PR?

**Comment by jayb-g** [comment]
@biodranik yes I had checked and it works as expected in the debug build.

**Comment by biodranik** [comment]
@meenbeese @rtsisyk can you please comment on https://github.com/organicmaps/organicmaps/issues/6907#issuecomment-1990864446 ? It would be beneficial to have this functionality at least on some older devices if there are no other downsides.

**Comment by meenbeese** [comment]
Apparently, it was causing issues when validating URL in the Play Console afaik. We can try to set a flag like`        android:maxSdkVersion="24"` to keep the functionality on older devices, but I am not sure if this will work. Worth I try I guess.

**Comment by jayb-g** [comment]
@meenbeese it should still be fine, apps _can_ support unverified links. Many apps still do, as mentioned above.

**Comment by biodranik** [comment]
I also saw warnings in the console. But what is their impact to users? Looks like there is no any impact, right? Then let's revert this change.
