### ISSUE TITLE
Extremely Slow Downloads on iPad Pro

### ISSUE THREAD

**Issue by iamrecursion** [organicmaps/organicmaps#6912]
**Describe the issue**
My iPad is having very slow downloads from Organic Maps' servers when updating maps. There is ample storage, and the network performance in other apps is much faster. On the same network, my phone (iPhone 15 Pro Max) doesn't exhibit this issue.

**Steps to reproduce**
1. Go to the hamburger.
2. Select "Download Maps"
3. Download the map

**Expected behaviour**
Performance equivalent to the iPhone version.

**System information:**
 - Operating system and its version: iOS 17.2  
 - Organic Maps version: 2023.12.18-7   
 - Device Model: iPad Pro 12.9" 2022 M2 (16GB RAM, 1TB)

**Comment by biodranik** [comment]
The download code is exactly the same. It could be something else, maybe the issue in the UI.

Is download faster when you download it from the map, not from Download Maps?

You're downloading only one map, not many of them, right?

**Comment by iamrecursion** [comment]
This is happening when downloading multiple at once. There's a bit of thrashing, but the speeds themselves seem far worse.

And I don't know about downloading from the map. This is happening when updating maps as I have the whole world downloaded.

**Comment by biodranik** [comment]
Slow updating of many maps at once is a known issue that should be fixed: https://github.com/organicmaps/organicmaps/issues/2628

Closing this as duplicate.

**Comment by iamrecursion** [comment]
Ah, got it! Thanks!
