### ISSUE TITLE
iOS 12 editor and Place Page are broken

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6917]
> Today (21 Dec 2023), after the update, the editable information fields 
for the saved (starred) places, have disappeard. 
Only the fields with the navigation arrows are visible. 

- iPad4,8 (12.5.7) 
- Organic Maps 2013.12.18-7

Also, Place Page is missing completely on iOS 12.4 in emulator. There are broken layout warnings for the landscape iPad mode. 

![image](https://github.com/organicmaps/organicmaps/assets/170263/cbcbd27c-9bb3-41bc-be2b-48f6f19ee895)
 
CC @kirylkaveryn

**Comment by DicePenguin** [comment]
I can confirm that the editable information fields for my saved places are also missing.

**Comment by biodranik** [comment]
https://github.com/organicmaps/organicmaps/commit/92c7b90c596f7c8702fdff2ab81a5b1e0b0d9457 breaks Place Page on iOS 12
