### ISSUE TITLE
Singapore Metro Icon is too tiny and blurred

### ISSUE THREAD

**Issue by hoizan** [organicmaps/organicmaps#6928]
1) Thank you for bringing Singapore metro icon on the latest OM release 2023-12-18-12-Google

2) However, the icon is bit too small and blurry even at max zoom level.

3) Attached a image comparing the metro icon between OM and OsmAnd

4) Attached reference icon image from OsmAnd downloded at https://github.com/osmandapp/OsmAnd-resources/blob/2dcc21ee03b23edd561b463a145da84057338049/rendering_styles/style-icons/map-icons-svg/mx_subway_singapore.svg

5) Please make the icon more distinctive.

**Expected behaviour**
The metro icon is slightly bigger, more distinctive and prominent 

**System information:**
 - Operating system and its version: [ Android 14]
 - Device Model: [Samsung S21+ and S22 Ultra]

Image of comparison:-
![sg_mrt_icon_compare](https://github.com/organicmaps/organicmaps/assets/92556284/49c042c1-0251-4bb8-b91e-93e352f712bc)

Reference icon form OamAnd at GitHub :-
![mx_subway_singapore](https://github.com/organicmaps/organicmaps/assets/92556284/d62d92b4-d765-4bbd-b119-4e89b6611adc)

**Comment by biodranik** [comment]
CC @RedAuburn

**Comment by RedAuburn** [comment]
Which would you prefer? @hoizan 

<img width="40px" src="https://github.com/organicmaps/organicmaps/assets/26939824/36fc3a9e-0763-4c88-b000-580f082c9ea9"/>

<img width="40px" src="https://github.com/organicmaps/organicmaps/assets/26939824/193f74f8-44bb-44de-82c4-e6592104175e"/>

**Comment by hoizan** [comment]
The left round icon is bigger and more consistent with the official logo with green background. Also, it is stands out more on the map. I pick the left.
 Thank you, @RedAuburn !
