### ISSUE TITLE
Highlight matched part of the address in search results

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6932]
Now only matched names are highlighted with bold. The address part in the top first result is not highlighted, and it looks like it's not the exact match but some wrong result from the first sight. 

![image](https://github.com/organicmaps/organicmaps/assets/170263/61909557-7c03-4e15-9eb6-8509a60a1e41)

**Comment by adysinghh** [comment]
Hey, Please review the changes that I made.

**Comment by adysinghh** [comment]
@biodranik Hey, Please review the changes that I made.
