### ISSUE TITLE
Contour lines are too prominent in non-outdoors style

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6937]
The General style can be more readable if contour lines will have similar colors as in outdoors style.

General | Outdoors
--------|---------
<img width="1448" alt="выява" src="https://github.com/organicmaps/organicmaps/assets/170263/e029b286-48f9-4e8f-8de2-0ce551140664">|<img width="1448" alt="выява" src="https://github.com/organicmaps/organicmaps/assets/170263/3db1e127-5713-4ec8-a3f2-abff394988b7">

**Comment by pastk** [comment]
Related to
- #6901

**Comment by pastk** [comment]
Fixed in https://github.com/organicmaps/organicmaps/pull/6590#issuecomment-1868350493
