### ISSUE TITLE
[android] Copied to clipboard toast is not displayed when running on the lock screen

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6938]
1. Run OM
2. Make sure "Use on the lock screen" OM setting is enabled.
3. Lock the device
4. Unlock the device
5. Select any object on the map
6. Try to hold your finger on the title of the selected object
7. Observe that "Copied to clipboard" message is not displayed

Reproduced on Android 14, didn't test on other versions.

**Comment by Jean-BaptisteC** [comment]
Caused by #6610

**Comment by biodranik** [comment]
@Jean-BaptisteC Something is not right.
1. I see the system notification and copied content preview on emulator, but not on the real device.
2. My Android version is 14, and I see the "Copied to clipboard." toast on it.
3. There is no string "Copied to clipboard." in our resources, there is "Copied to clipboard: $@" string.

How it can be explained?

**Comment by Jean-BaptisteC** [comment]
I have doing somes tests on my Pixel 6.
Copy from lockscreen works but preview pop-up is not present -> a solution is to revert my changes
I guess on your device, developers doesn't use new copy preview pop-up and just use toast to confirm text is in copy-paste.

**Comment by arjundevasi** [comment]
how about the app checks that if its showing on lock screen, only then show snackbar?
```
KeyguardManager keyguardManager = (KeyguardManager) context.getSystemService(Context.KEYGUARD_SERVICE);

    if (Build.VERSION.SDK_INT > Build.VERSION_CODES.TIRAMISU && keyguardManager.isDeviceLocked()){
      Utils.showSnackbarAbove(frame.getRootView().findViewById(R.id.pp_buttons_layout), frame,
              context.getString(R.string.copied_to_clipboard, text));
    }
```

**Comment by biodranik** [comment]
Did you test it? Does it work? Let's create a PR.

**Comment by arjundevasi** [comment]
It works. also the code has to be modified at 3 places, do you recommend making a pubic static method in utils.java or separate modification at each place?
