### ISSUE TITLE
Background voice directions do not work on iOS

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6940]
A follow-up of the #573

**Comment by biodranik** [comment]
It is indeed reproduced on iOS. There are no background voice instructions. @fabwu @kirylkaveryn do you have any ideas why?

**Comment by biodranik** [comment]
@fabwu this whole code looks strange. Looks like the location is updated separately from the framework update. Can you please check if the framework can be updated directly when the app receives the location while in the background? What was the reasoning for the current implementation? @igrechuhin maybe you remember it?

**Comment by fabwu** [comment]
I think the framework is updated directly it's just a bit hidden. 

On a location update `frameworkUpdateMode` is set and the setter of this property calls `updateFrameworkInfo`, which then updates the framework with the new location. 

We could refactor this code to make it clearer but I don't think that's necessary atm.

**Comment by biodranik** [comment]
@fabwu it would be great to have a cleaner code also in the context of the upcoming full-featured track recorder.

**Comment by fabwu** [comment]
Ok I didn't know about the full-featured track recorder. 

Anyway, I would first merge this PR and see if we get any bug reports before doing a refactor to limit the scope of the change.
