### ISSUE TITLE
Neighbourhoods are shown in larger font on the map than city districts.

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6951]
OSM | Organic Maps
----|---
![image](https://github.com/organicmaps/organicmaps/assets/170263/7f94d8df-5885-4322-bcb4-7fba8495478f)|![image](https://github.com/organicmaps/organicmaps/assets/170263/31c015fa-3d60-4625-8a22-02b9f78652f7)

**Comment by pastk** [comment]
[Here](https://www.openstreetmap.org/query?lat=48.3934&lon=9.9742) Weststadt is `place=suburb` while Postdörfle and Beim Kessel are `place=neighbourhood` and font sizes are inconsistent indeed.

**Comment by biodranik** [comment]
@pastk is it easy to fix?

**Comment by pastk** [comment]
Making font size bigger or smaller is easy, but that might break it relative to other `place=` features. So need to check all font sizes and styles (some labels are w/ halo and some are not; and it could change with the zoom level) for all place=* systematically.

**Comment by pastk** [comment]
> Upd: Sedanstraße is `place=quarter`

Actually we convert quarters to neighbourhoods, which is OK for now (its something between the latter and a suburb).
