### ISSUE TITLE
Failure to route bikes along a bicycle=designated path

### ISSUE THREAD

**Issue by sgued** [organicmaps/organicmaps#6962]
**Describe the issue**
Hi,
There is a path I went to where organic maps failed to provide optimal routing on a path for bicycles.

**Steps to reproduce**

The following routing in OSM: https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=45.77926%2C4.98055%3B45.78322%2C4.98958#map=16/45.7816/4.9859

![image](https://github.com/organicmaps/organicmaps/assets/51865119/3c1584de-820d-4106-a3a5-0cc7f7d8872b)

Is avoided on Organic Maps:

![image](https://github.com/organicmaps/organicmaps/assets/51865119/ab681ad9-d2c2-4ea3-9583-b36f877346e0)

**Expected behaviour**

I expected Organic Maps to follow the same path as the one provided by graphopper or by Organic Maps for foot walking.

![image](https://github.com/organicmaps/organicmaps/assets/51865119/477296eb-3037-4568-8a90-03cde2f12d9c)

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.12.20-4-FDroid
 - Device Model: Fairphone 4

**Additional context**
I initially looked at the tags for the path in OSM, but the data seems correct according to the wiki:

```
bicycle=designated
foot=designated
highway=path
segregated=no
```  

Which [according to the wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcycleway) seems valid (see usage for shared paths)

I created [this note](https://www.openstreetmap.org/note/4039194) on the map. I'll need to remember to close it once this is solved.

Thanks for the amazing work you put into this app!

**Comment by sgued** [comment]
After some more digging maybe it's linked to the `barrier=cycle_barrier` on the entrances of the path?

**Comment by cyber-toad** [comment]
Possible duplicate: https://github.com/organicmaps/organicmaps/issues/3920

**Comment by pastk** [comment]
> After some more digging maybe it's linked to the `barrier=cycle_barrier` on the entrances of the path?

Its this particular cycle_barrier in the middle of the path https://www.openstreetmap.org/node/1355254220 - all other cycle_barriers on the path have bicycle=yes/designated so OM was ignoring them.

https://github.com/organicmaps/organicmaps/pull/9455 made OM to ignore all cycle_barriers unless they have explicit `bycicle=no`. So its fixed now.
