### ISSUE TITLE
[android] Add stop during navigation is broken

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6964]
It is likely a regression, maybe an old one after PP refactorings.

1. Start navigation.
2. Select any object and add stop

The expected behavior is like on iOS: a stop is added to the route, and the map shows route preview mode with a Start [navigation] button.

Actual behavior: A place Page for the selected stop is displayed in a route preview mode. To see the Start button, user needs to close the Place Page first.

There is also another bug that may be related to this issue (it also works fine on iOS):

1. Set "Night Mode" to "Auto"
4. Begin navigation during night time.
5. During navigation, add a stop.
6. Navigation ends and map transitions to the light theme
7. Route recalculates and the stop's text colour is dark in the light theme while other destinations remain in a light colour

CC @arnaudvergnet @Jean-BaptisteC @rtsisyk

**Comment by biodranik** [comment]
Behavior on my Android 14 device in the latest January release is different, after pressing "Add Stop" the Place Page does not hide. @rtsisyk was it the latest release?
@Jean-BaptisteC can you reproduce the bug?

**Comment by Jean-BaptisteC** [comment]
I'm able to reproduce on my Pixel 6 with latest release :)
(I will check in few days, where bugs was introduced)

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.03.31-8-Google version
