### ISSUE TITLE
[iOS] Address is duplicated in Place Page

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#6977]
On latest master the address line in the place page is shown twice:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/40895afe-a821-47c4-b4aa-98eed057aef2" width="320"/>

**Comment by biodranik** [comment]
It does not reproduce on my device, strange. Is it reproduced on every POI? Anything specific that you did? Does it reproduce after restart?

**Comment by dvdmrtnz** [comment]
> It does not reproduce on my device, strange. Is it reproduced on every POI? Anything specific that you did? Does it reproduce after restart?

It happens on every POI, even after restart and after deleting and reinstalling the app

**Comment by biodranik** [comment]
I confirm the bug.
