### ISSUE TITLE
Wikipedia's links should respect the current locale whenever possible

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#6988]
Why "Bhutan" article is in Dzongkha language when opening with English locale?

<img src="https://github.com/organicmaps/organicmaps/assets/1799054/8ee177b3-e0fa-4214-8d3c-1800834e8e6b" width="350px">
<img src="https://github.com/organicmaps/organicmaps/assets/1799054/188e4244-20b6-4cbd-90d2-8515ea32121a" width="350px">

**Comment by biodranik** [comment]
@newsch is it possible to extract the list of languages in which article is available using the current wikiparser data files?

**Comment by newsch** [comment]
> is it possible to extract the list of languages in which article is available using the current wikiparser data files?

I don't think the per-language json entries have it, I'll have to check.
But after all articles are extracted, all language versions of an article [are stored in the same directory](https://github.com/organicmaps/wikiparser/pull/6#issue-1772212479). Is that helpful?
