### ISSUE TITLE
Not optimal walking route

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7007]
https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=13.7399%2C100.5554%3B13.7435%2C100.5406#map=16/13.7423/100.5477

1 | 2
--|--
![image](https://github.com/organicmaps/organicmaps/assets/170263/71088b72-d7b9-4139-a180-23117de630c6)|![image](https://github.com/organicmaps/organicmaps/assets/170263/1c1fa712-979a-4e42-b81f-5e78d86ccc38)

What is wrong here?

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.03.31-8-Google version
