### ISSUE TITLE
Android Auto (AA): Indefinite loading

### ISSUE THREAD

**Issue by pabloscloud** [organicmaps/organicmaps#7034]
**Describe the issue**
First day of using Android Auto. The navigation loads forever (couldn't get it to load at least).

**Steps to reproduce**
1. Set a bookmark on the phone
2. Open the bookmark in android auto
3. hit start to route to the destination
4. loads infinitely 

**Expected behaviour**
I didn't try to drive tho, so maybe it only loads when the location changes a bit.
It should say something like "Start driving" or directly show where to go.

**Screenshots**
[Video ](https://github.com/organicmaps/organicmaps/assets/93644977/f690f019-13cc-4c33-9598-713ef20c1391)

**System information:**
 - Operating system and its version: Android 14 (GrapheneOS)
 - Organic Maps version: 2023.12.25-6-Google (23122506)
 - Device Model: Pixel 4a (5g)

**Additional context**
This is the Organic Maps beta obviously.
Android Auto version 11.0.635014-release (110635014)

**Comment by wadeduvall** [comment]
I get this same bug in AA about 30% of the time. Sometimes it resolves itself, sometimes it displays the route but doesn't give voice prompts, and sometimes it gets stuck giving you the zoomed out view of the track. Please let me know if I can provide any additional data. I haven't found any particular triggers, but it happens frequently.

**Comment by pabloscloud** [comment]
I also noticed that when selecting a destination the route shows up, but it really takes a long time until the screen with the start button appears, should it ever.. 😆

**Comment by pabloscloud** [comment]
I have been using Android Auto a few times now and more times than not this is an issue. Either it takes forever to load or it doesn't load. Not after a few seconds or minutes at least.

**Comment by pabloscloud** [comment]
This is not fixed for me in the latest version available on Google play

**Comment by biodranik** [comment]
@pabloscloud is your issue still exactly the same as on the attached video?

@AndrewShkrob PTAL

**Comment by pabloscloud** [comment]
It's exactly the same issue. The only thing that changed is the phone.

Operating system and its version: Android 14 (GrapheneOS)
Organic Maps version: 2024.02.20-1-Google (23122506)
Device Model: Pixel 7

**Comment by pabloscloud** [comment]
I've not been able to route yet with Organic Maps inside of Android Auto so I'd suppose it occurs every time, but I need to use it a few more times to be sure.

**Comment by pabloscloud** [comment]
> How many bookmarks are in your list?
2. One for work, one for home

**Comment by pabloscloud** [comment]
> @pabloscloud is your issue still exactly the same as on the attached video? Does it reproduce always? How many bookmarks are in your list?
> 
> @AndrewShkrob PTAL

I just tried it again this morning and it worked fine so I'd guess this is fixed.
