### ISSUE TITLE
[android][auto] Night mode on all the time, even in Auto

### ISSUE THREAD

**Issue by Eelviny** [organicmaps/organicmaps#7041]
**Describe the issue**
My phone is set to dark mode always. My car also has its HUD set to dark mode permanently, so this does not change depending on the time of day.

When using Android Auto in car navigation, the map is always in night mode when night mode is set to Auto. I need to manually turn if off during the day.

**Steps to reproduce**
1. Set phone to dark mode
2. Set car to dark mode (I have no idea if this makes a difference)
3. Start navigation

**Expected behaviour**
I expect night mode to follow day and night, not the dark mode of my car or phone. So night mode should be off during the day.

**System information:**
 - LineageOS 20-20231128 (Android 13)
 - Organic Maps version: 2023.12.25-6-Google
 - Oneplus 8 IN2013
 - Volkswagen ID.3, wired Android Auto

**Comment by Jean-BaptisteC** [comment]
on Android Auto, in mode day/night map settings, you can select automatic to fix the problem

**Comment by Eelviny** [comment]
The setting "Day/Night mode for maps" in my Android Auto app is already set to Automatic.

**Comment by Jean-BaptisteC** [comment]
Did you have enabled dark mode in Organic Maps settings?

**Comment by Eelviny** [comment]
Will get back to you tomorrow on this when I'm back at my car, I'll toggle a few settings and see if I can make it work normally.

**Comment by Eelviny** [comment]
Closing, not an Organic Maps issue. Some smart Volkswagen engineer interpreted dark=night and forces Android Auto into night mode at all times when the interface is in dark mode, instead of switching based on how dark it is outside (which is how it's supposed to be implemented).

**Comment by Eelviny** [comment]
Only comment or tentative feature request would be to have some way to make night mode follow sunrise/sunset instead of what Android Auto reports. I know this would just be working around someone else's broken implementation but I think I would sooner see a flying elephant than VW fixing their infotainment system.

**Comment by Jean-BaptisteC** [comment]
Automatic value (default value) in Organic Maps theme settings follow day/night
And Organic Maps theme settings in Android Auto follow Organic Maps theme settings on phone. But it can be different.
I can have automatic on phone and force in dark on Android Auto.
