### ISSUE TITLE
[android] Strange speed limit warning

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#7057]
https://www.openstreetmap.org/#map=19/54.71010/25.24919
The OSM data looks ok.

![image](https://github.com/organicmaps/organicmaps/assets/175612/1ad07893-7506-4086-bbc4-4113caf796f2)

**Comment by RedAuburn** [comment]
the turn directions aren't right either 🤔

**Comment by tomar19** [comment]
Hello @RedAuburn @biodranik @pastk  :) I have tried your **organicmaps mobile application**. I have also suggested many of my friends and family members to install and use it. The app has helped me alot during my navigation to different places. My favourite part is that it does not require an **internet connection** to navigate ❤️.  Your community is very interesting and I would very much like to **contribute to this organization**. I want to add many new features and functionalities to this application. I just came to enquire if **Organicmaps** is participating in ***GSOC 2024*** 🔥.

**Comment by dmitrygribenchuk** [comment]
The same issue fixed [#7093 ](https://github.com/organicmaps/organicmaps/issues/7093)
@vng can you close it?
