### ISSUE TITLE
Make menu switchable on Android Auto full screen

### ISSUE THREAD

**Issue by Miq1** [organicmaps/organicmaps#7064]
I found that the top left OM menu is always visible when using OM on Android Auto in full screen mode. 

It would be nice if it could be shrunk into a burger menu icon as is possible on the smaller shared screen window.

**Comment by Jean-BaptisteC** [comment]
I'm not sure it's possible to reduce the menu, @AndrewShkrob can you confirm?

**Comment by AndrewShkrob** [comment]
Hello @Miq1,

Thank you for your request. Could you please provide more details on why you need this feature? Are you aiming for a "free drive" mode? The current Android Auto experience involves selecting a destination, creating a route, and navigation. It's challenging for me to imagine a scenario where users would require a full map view. Your insights into the intended use would be helpful in our decision-making process before implementation.

Understanding the purpose and user expectations is crucial before integrating new functionalities. From my perspective, this mode could potentially be valuable in conjunction with other features like live traffic updates, speed limits, and points of interest highlighting (such as speed cameras, parking spots, and gas stations). However, supporting these features would demand significant time and resources, making immediate implementation unfeasible. Without these elements, displaying a fullscreen map might not serve its intended purpose.

**Comment by Miq1** [comment]
Thank you for considering my request.

Actually I am using the free driving mode a lot, also with Google maps. It may be my personal spleen, but I like to see where I am on the map, the layout of the road ahead,  and the facilities available nearby. With the latter OrganicMaps excels particularly, as much more details can be seen.

The menu is occupying a lot of map space in full screen mode, one is like blind to the left ahead.

**Comment by GHDave3** [comment]
Most definitely agree with Jean-BaptisteC - the menu takes up a large portion of the screen, making the map less usable, and the option to remove it would be most helpful. I just started using Android Auto yesterday and I thought it must be a bug of some sort till I came here.  Thanks so much!
