### ISSUE TITLE
Screen sleeps even with 'Keep the screen on' enabled

### ISSUE THREAD

**Issue by secretServant** [organicmaps/organicmaps#7069]
**Describe the issue**
Screen sleeps even with 'Keep the screen on' enabled. Only started going to sleep in the last couple of updates.

**Expected behaviour**
Screen stays on while navigating

**System information:**
OS: LineageOS 20 (Android 13)
Organic Maps Version: 2023.12.20-4-FDROID

**Comment by Jean-BaptisteC** [comment]
Duplicate #6921
