### ISSUE TITLE
Wrong speed limit is displayed near camera

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7093]
If the speed limit of the camera is unknown, it should be taken from the road speed limit.

No speed limit at all for a camera is a very strange situation. Is it possible to find and pre-process such cases at the data generation stage?

![image](https://github.com/organicmaps/organicmaps/assets/170263/d4a9645b-f93a-49fc-a5da-7d10f5c697d6)

**Comment by RedAuburn** [comment]
same issue that causes https://github.com/organicmaps/organicmaps/issues/7057

**Comment by vng** [comment]
Here is a place to reproduce a bug: https://www.openstreetmap.org/way/1042076237#map=19/38.61074/-9.11017

No 0-camera in the data, looks like a bug appears after the previous valid camera.
