### ISSUE TITLE
Editor search can't find exact match

### ISSUE THREAD

**Issue by cimm** [organicmaps/organicmaps#710]
The search in the OpenStreetMap editor (when adding a POI to the map) works for some keywords but not all. The screen recording below clearly shows "Surveillance Camera" as one of the options in the list ([man_made|surveillance](https://github.com/organicmaps/organicmaps/blob/99c5b878a048b467d1c66cf5a5ff0ce04975c73b/data/types.txt#L1178) in OSM) but I can't find the same result via the search. Nor "Surveillance" or "Surveillance Camera" matches (cases don't matter). Searching for "Car" or "Car Rental" does work so it's not related to the multiple words as far as I can tell. I only tested this on iOS 14.6.

https://user-images.githubusercontent.com/68112/123090135-16b9fc80-d428-11eb-8432-b4e38cf469ae.mp4

I already noticed this issue when I was still using Maps.me way back so this is not a new issue.

**Comment by pastk** [comment]
`man_made=surveillance` is not being displayed by OM at the moment (prob that's why it wasn't searchable) and it was disabled in the Editor for this reason lately
