### ISSUE TITLE
app generates segfault and doesn't open

### ISSUE THREAD

**Issue by hodow1694** [organicmaps/organicmaps#7101]
**Describe the issue**
After current update Fedora 39 with Gnome GUI, OrganicMaps has stopped work.
In Journalctl log there is information about the segfault error.

**Steps to reproduce**
1. On a fedora 39 system, install the application.
2. Run it.

**Expected behaviour**
The application should start.

**Screenshots**
`    sty 07 10:02:27 localhost.localdomain systemd-coredump[24491]: [🡕] Process 24472 (OMaps) of user 1000 dumped core.
                                                               
                                                               Stack trace of thread 2:
                                                               #0  0x00007f51017f9dff n/a (/usr/lib/x86_64-linux-gnu/libQt6Gui.so.6.6.1 + 0x5f9dff)
                                                               #1  0x0000563b10af5a2e n/a (/app/bin/OMaps + 0x15aa2e)
                                                               #2  0x0000563b1153ead9 n/a (/app/bin/OMaps + 0xba3ad9)
                                                               #3  0x00007f5100be0101 n/a (/usr/lib/x86_64-linux-gnu/libQt6Core.so.6.6.1 + 0x1e0101)
                                                               #4  0x00007f5102b88a43 n/a (/usr/lib/x86_64-linux-gnu/libQt6Positioning.so.6.6.1 + 0x49a43)
                                                               #5  0x00007f50f44cacf1 n/a (/usr/plugins/position/libqtposition_geoclue2.so + 0x7cf1)
                                                               #6  0x00007f5102b8a7b0 n/a (/usr/lib/x86_64-linux-gnu/libQt6Positioning.so.6.6.1 + 0x4b7b0)
                                                               #7  0x00007f50f44ced15 n/a (/usr/plugins/position/libqtposition_geoclue2.so + 0xbd15)
                                                               #8  0x0000563b1153d9b4 n/a (/app/bin/OMaps + 0xba29b4)
                                                               #9  0x0000563b1153e3d6 n/a (/app/bin/OMaps + 0xba33d6)
                                                               #10 0x0000563b10b1a876 n/a (/app/bin/OMaps + 0x17f876)
                                                               #11 0x0000563b10ad18f8 n/a (/app/bin/OMaps + 0x1368f8)
                                                               #12 0x00007f510043b08a n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2808a)
                                                               #13 0x00007f510043b14b n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2814b)
                                                               #14 0x0000563b10aed935 n/a (/app/bin/OMaps + 0x152935)
                                                               ELF object binary architecture: AMD x86-64
sty 07 10:02:26 localhost.localdomain systemd[1]: Started systemd-coredump@5-24490-0.service - Process Core Dump (PID 24490/UID 0).
sty 07 10:02:26 localhost.localdomain kernel: Code: 0f 1f 84 00 00 00 00 00 0f 1f 00 f3 0f 1e fa 55 48 89 e5 48 83 ec 30 48 8b 7f 08 64 48 8b 04 25 28 00 00 00 48 89 45 f8 31 c0 <0f> b6 97 88 01 00 00 89 d0 c0 >
sty 07 10:02:26 localhost.localdomain kernel: OMaps[24472]: segfault at 188 ip 00007f51017f9dff sp 00007ffe4f5f5a40 error 4 in libQt6Gui.so.6.6.1[7f510132b000+672000] likely on CPU 13 (core 6, socket 0)
`

**System information:**
 - Operating system and its version: Fedora 39 with Gnome 45.2
 - Organic Maps version: 2023.12.20
 - Flatpak version: 1.15.6

**Comment by Ferenc-** [comment]
@hodow1694 we would need more info, because I have tested `2023.12.20` from flatpak on Fedora 39 VM, and it works just fine for me.

**Comment by hodow1694** [comment]
What kind of information would you need? I will try to provide it.

**Comment by Ferenc-** [comment]
1. For example the output of this `systemctl status geoclue.service` could be relevant.
2. Are the location services enabled here or not?
![image](https://github.com/organicmaps/organicmaps/assets/6553695/a710db39-15a0-48a2-b44a-92ca4aafa1e9)
3. Have you removed any RPMs from a standart Fedora 39 Installation?

**Comment by hodow1694** [comment]
The GeoClue service was masked.
However, it's strange that before the current Fedora update the program was working, and after the update it stopped, although I didn't change anything with the GeoClue service.
Thank you for your help.
