### ISSUE TITLE
Parking with toilet is shown as toilet 

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#7102]
Parking with `toilets=yes` is shown as toilet here:

https://omaps.app/4n_T5AnIsF/Parking_de_Hospitales
om://4n_T5AnIsF/Parking_de_Hospitales
https://www.openstreetmap.org/node/4109426451#map=19/42.80637/-1.66573

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/e77a995d-9015-407b-b42e-f773a37dc3c6" width="320"/>

**Comment by Jean-BaptisteC** [comment]
Similar as #1648

**Comment by matkoniecz** [comment]
sport shop with toilets=yes should be shown as shop, not as toilets #5252 was also similar and got fixed, fix may be applicable here
