### ISSUE TITLE
Switches from night mode to day mode on arrival

### ISSUE THREAD

**Issue by caboteria** [organicmaps/organicmaps#711]
Thank you for Organic Maps, it's got great potential!

I used it to drive home last night and the screen was in "dark mode" as expected, but when I arrived at my house it switched to "bright mode" so I got a bright light suddenly shining in my eyes. It would be less distracting if it stayed in dark mode.

I'm using version 2021.06.12-7g75fd600f97-FDroid with data version 210529 on LineageOS 18.1 on a Moto G7+.

**Comment by rtsisyk** [comment]
"Auto" enables dark mode only during navigation.

**Comment by caboteria** [comment]
Hi @rtsisyk , thank you for looking into this. I'm not clear on who you need feedback from.

**Comment by rtsisyk** [comment]
Please see #749.
