### ISSUE TITLE
Stop showing water taps without drinking water like other water sources

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#7127]
**Describe the issue**
Currently

```
drinking_water=no
drinking_water:legal=no
man_made=water_tap
```

shows up as a drinking water. This got worse recently when drinking water got more visible.

**Steps to reproduce**
1. Go to https://www.openstreetmap.org/node/11264629303 in organic maps

**Expected behaviour**

Drinking water locations are shown as drinking water location and not technical water supply

**Screenshots**
Will add if really needed

**System information:**
Will add if really needed.

 - Operating system and its version: [iOS 12, Android 10, Ubuntu 22, MacOS Big Sur, etc.]
 - Organic Maps version: [you can find it by tapping the button with the green Organic Maps logo, bottom left of the main screen on Android, or the `?` button on iOS]
 - Device Model: [e.g. iPhone 6, Samsung S22]

**Additional context**

very similar to #4953

**Comment by patepelo** [comment]
Wanted to open a similar issue, happy to have found this one.

How can we solve this problem and find other POIs to reconsider their representation?

IMO we should add a different icon at least for water tank refill point and maybe a different color for the drop if it's not drinkable, like a yellow outline around the drop. WDYT? @organicmaps/styles 

![image](https://github.com/user-attachments/assets/102a9d75-18e0-4e17-bfba-b2eacd565959)

**Comment by RedAuburn** [comment]
an idea, likely too detailed for small scales though:

<img width="64px" src="https://github.com/user-attachments/assets/9cbab582-0089-4794-9132-4a80e6fffe3f"/>

**Comment by RedAuburn** [comment]
will need to improve search too. 
eg. "drinking water","potable water" → drinkable only
"water" → both

**Comment by dvdmrtnz** [comment]
@RedAuburn I think those are too detailed. Remember that this icon is shown at 18x18px size.

I would maybe do a crossed water droplet:

![](https://github.com/user-attachments/assets/25dba6d5-bd2b-4c67-8a1f-adddec757826)

**Comment by dvdmrtnz** [comment]
* Related to https://github.com/organicmaps/organicmaps/issues/4953

**Comment by RedAuburn** [comment]
> @RedAuburn I think those are too detailed. Remember that this icon is shown at 18x18px size.
> 
> I would maybe do a crossed-out water droplet:
> 
> ![](https://private-user-images.githubusercontent.com/47610359/369561645-25dba6d5-bd2b-4c67-8a1f-adddec757826.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NzA5ODYsIm5iZiI6MTcyNjg3MDY4NiwicGF0aCI6Ii80NzYxMDM1OS8zNjk1NjE2NDUtMjVkYmE2ZDUtYmQyYi00YzY3LThhMWYtYWRkZGVjNzU3ODI2LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDIyMTgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMjQxZDNmNGVjNjljYjgwNDcyMDYzYzQ1M2Q5NjE2ZTNjYTIzMDZkODI5M2M0ODMyYmJlNzcwZjNlZTYwNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aok08AobT4-hoOwQRnlk-dLJ5q20HOhabr8GZaedbww)

that works, but the line hides a lot of the shape of the droplet, maybe too much..

**Comment by matkoniecz** [comment]
Maybe just stop showing water tank with undrinkable water? Why it is exactly shown on the map?

**Comment by RedAuburn** [comment]
> Maybe just stop showing water tank with undrinkable water? Why it is exactly shown on the map?

for watering cans, filling RV tanks, washing things etc. all use cases need to be considered :)

**Comment by matkoniecz** [comment]
Maybe have cup (like OSM Carto) for drinking water?

Or gray drop for undrinkable water?

**Comment by dvdmrtnz** [comment]
> > @RedAuburn I think those are too detailed. Remember that this icon is shown at 18x18px size.
> > I would maybe do a crossed-out water droplet:
> > ![](https://private-user-images.githubusercontent.com/47610359/369561645-25dba6d5-bd2b-4c67-8a1f-adddec757826.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NzA5ODYsIm5iZiI6MTcyNjg3MDY4NiwicGF0aCI6Ii80NzYxMDM1OS8zNjk1NjE2NDUtMjVkYmE2ZDUtYmQyYi00YzY3LThhMWYtYWRkZGVjNzU3ODI2LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDIyMTgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMjQxZDNmNGVjNjljYjgwNDcyMDYzYzQ1M2Q5NjE2ZTNjYTIzMDZkODI5M2M0ODMyYmJlNzcwZjNlZTYwNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aok08AobT4-hoOwQRnlk-dLJ5q20HOhabr8GZaedbww)
> 
> that works, but the line hides a lot of the shape of the droplet, maybe too much..

Thinner line:

![](https://github.com/user-attachments/assets/d1f50649-0011-4c0b-af9a-14a184ca1322)

**Comment by dvdmrtnz** [comment]
> Maybe have cup (like OSM Carto) for drinking water?

Using OSM Carto's cup is an interesting idea. Currently the water droplet icon is used for many features: `amenity=drinking_water`, `amenity=water_point`, `man_made=water_tap`, `man_made=water_well`, `natural=spring`, `natural=hot_spring`. We could maybe use the cup for `amenity=drinking_water` and leave the rest with the water droplet.

---

With faucet (same symbol as OSM Carto):

![](https://github.com/user-attachments/assets/eb577d7d-fb16-4100-a1d7-aeb7cdb84630)

---

Or maybe only water cup:


![369561645-25dba6d5-bd2b-4c67-8a1f-adddec757826](https://github.com/user-attachments/assets/90c4cb8a-7185-4a3c-8c05-2350485006d8)

**Comment by Misalf-git** [comment]
> With faucet (same symbol as OSM Carto):
> 
> ![](https://github.com/user-attachments/assets/eb577d7d-fb16-4100-a1d7-aeb7cdb84630)

It's probably more recognizable with the faucet.

**Comment by pastk** [comment]
> Thinner line:
> 
> ![](https://private-user-images.githubusercontent.com/47610359/369607093-d1f50649-0011-4c0b-af9a-14a184ca1322.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5Mzc4NTUsIm5iZiI6MTcyNzkzNzU1NSwicGF0aCI6Ii80NzYxMDM1OS8zNjk2MDcwOTMtZDFmNTA2NDktMDAxMS00YzBiLWFmOWEtMTRhMTg0Y2ExMzIyLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA2MzkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOTUyMDI0ZWQ1OTI3YzQwZTFhYzYwYWY1OGM4Y2Q2OTFkNzJmYzU3MmFjMzBmNDliYTA1MDllMzI5ZTJmYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-VR8AOeLCg-ZfNIGckL2b_4vtLSJhTTiYvtnjJ4CzDw)

Looks good IMO.
Maybe changing the color to more "undrinkable" would be good too. E.g. we have `@water_bad: #9dc7c1;`  for drains, wastewater ponds etc.

**Comment by pastk** [comment]
Changing known drinkable sources to a cup is also nice.
I think e.g. `man_made=water_tap` with explicit `drinking_water:legal=no` should be depicted by a cup also.

`man_made=water_well` or `natural=spring` - IDK. Sometimes it could be hard to get water from wells (e.g. no bucket, just a deep hole; water might be perfect, but access is hard).

**Comment by dvdmrtnz** [comment]
Using `@water_bad: #9dc7c1`:

![](https://github.com/user-attachments/assets/448a94b0-3961-4c8f-a8fd-eb3f811db277)
