### ISSUE TITLE
Adding national roads specifications, when crossing a border

### ISSUE THREAD

**Issue by Popolon** [organicmaps/organicmaps#7132]
**Is your feature request related to a problem? Please describe.**
When crossing a border, there are generally some rules about roads. Speed limit depending, on in city, outside city, national roads, motorways, highways, and it's highway toll payement system. There are often, but not always, some big panels with national routes about speed.

**Describe the ideal solution**
When crossing a border, a window, or an icon with an alert symbol that could be clicked to open the window (maybe settable by general settings), could indicate specific rules for the country, if available. As an exemple Czech Republic as a specific toll system that require driver to pay online, or on some specific automatic vending machines (not always work with foreign CB) in gaz stations. Among the information displayed on the window about country rules, a link toward the service to pay the right to use highway could be shown, allowing to jump to the website.

Concerning national speed limits, there is a page on the wiki of OSM, that could be used to fill the database: https://wiki.openstreetmap.org/wiki/Default_speed_limits

Commons.wikimedia.org also have some panels similar to those displayed on some countries, when crossing the border, with open licenses, including several in SVG format,  they could maybe be integrated in the window too?

https://commons.wikimedia.org/wiki/Category:Diagrams_of_National_Speed_Limits_road_signs

**Comment by Jean-BaptisteC** [comment]
Did you have check, if this feature is available in other GPS?

**Comment by matkoniecz** [comment]
> Commons.wikimedia.org also have some panels similar to those displayed on some countries, when crossing the border, with open licenses, including several in SVG format, they could maybe be integrated in the window too?

and exactly this signs are posted on borders

**Comment by Popolon** [comment]
Yes I know, I said it was already displayed, but you generally not see it when in crowded roads.
