### ISSUE TITLE
Is Organicmaps participating in GSOC 2024?❤️‍🔥

### ISSUE THREAD

**Issue by tomar19** [organicmaps/organicmaps#7134]
Is Organicmaps Organiztion participating in Google Summer Of Code 2024 ? 

If yes. Then what ideas and features are we working on? The GSOC 2024 is accepting applications from organizations around the world starting from January 22nd - Feb 6th 2024.

I want to contribute to this organization through GSOC 2024 as this one of the most active and interactive group I've seen on github, and since I've been using the organicmaps mobile application and had been an Android development enthusiast from many years. So please accept my request and inform if the organization is participating this year.
So that I can get familiar with the source code of this application and get ready with a proposal that will impress you to allow me to start contribution.

What you can expect from me:

1) You can expect replies from me within 1/2 an hour. I will be available the entrie time.

2) I can deeply understand the task and all related issues.

3) I will divide each task into small problems and finish the task within the given time.

**Comment by pastk** [comment]
Please check https://github.com/organicmaps/organicmaps/wiki/GSoC-2024-ideas
