### ISSUE TITLE
Traffic Data

### ISSUE THREAD

**Issue by mhmmdeminn** [organicmaps/organicmaps#7155]
Good work to all of you. I would like to give you a little advice to make organic maps a better alternative. If traffic data is added to organic maps and a system is made to change the route accordingly, it can make users prefer it. 

Good work. Good luck.

**Comment by pastk** [comment]
This is an often requested feature indeed and it has been discussed many times, e.g.
- #568
- #4889
- #5630
- #1160
- #2352 

It'd be great if someone could make a single concise summary issue (here?) about the state of the request and the development challenges.
