### ISSUE TITLE
Android Auto not appearing

### ISSUE THREAD

**Issue by kaibagley** [organicmaps/organicmaps#7163]
**Describe the issue**
When using the Gplay version of the app, downloaded from Aurora Store, AA doesn't appear. Neither does the Fdroid version or the GitHub version.

However, in a separate android profile with Google services given network permissions, the Gplay version does work. The alternate versions don't work (aurora, Fdroid, gh).

**Steps to reproduce**
1. Run Google services + no network perms
2. OM doesn't work with AA
3. Run Google services + network perms
4. OM from Gplay only works

**Expected behaviour**
All versions of OM work with AA, regardless of Gapps network permissions

**System information:**
 - Operating system and its version: GrapheneOS / AOSP 14
 - Organic Maps version: 2024.1.09-5-Web
 - Device Model: Pixel 7 Pro

**Additional context**
Unknown sources in the AA dev. settings is enabled. And other FOSS apps from Fdroid/GH work, such as Tempo, AntennaPod, Element, FairEmail etc.

**Comment by kaibagley** [comment]
Sorry! Just realised there is an issue for this: https://github.com/organicmaps/organicmaps/issues/7066

**Comment by fitojb** [comment]
In case it helps, I had to restart Android Auto after updating the app for it to appear in the Auto launcher. (I use wired Android Auto, so I unplugged the phone and plugged it back to the car’s port.)

**Comment by kaibagley** [comment]
> In case it helps, I had to restart Android Auto after updating the app for it to appear in the Auto launcher. (I use wired Android Auto, so I unplugged the phone and plugged it back to the car’s port.)

Was one of the first things I tried, unfortunately didn't work for me though ☹️
