### ISSUE TITLE
Add support of UK post codes in the search

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#717]
Postal codes are important to accurately identify addresses and locations. People across different countries commonly rely on postal codes when searching for specific point of interests. Organic Maps currently offers basic search capability using postal codes over existing OSM data, but users often encounter difficulties in locating objects on the map when addresses include postal codes.

People in different countries (and the U.K. especially) rely on postal codes in their every day life. This task is focused on mixing the external Ordnance Survey (U.K.) postal codes into the existing OSM data to fill the gap of missing postal codes in OSM, and on fixing postal code-related issues in the current Organic Maps search implementation. This is the same approach as used by Nominatim - OSM-based geocoding software.

https://wiki.openstreetmap.org/wiki/Key:postal_code

-------------------

<table>
  <tr>
    <td>
      <a href="https://nlnet.nl/"><img src="https://raw.githubusercontent.com/organicmaps/organicmaps/87f50b9fdb874ffc9b905d2738774d9b16d3c5a5/docs/sponsors/nlnet.svg" alt="The NLnet Foundation" width="200px"></a>
    </td>
    <td>
      This project has been funded through NGI0 Entrust Fund. <a href="https://nlnet.nl/entrust/">NGI0 Entrust Fund</a> is established by the <a href="https://nlnet.nl/">NLnet Foundation</a> with financial support from the European Commission's <a href="https://www.ngi.eu/">Next Generation Internet programme</a>, under the aegis of DG Communications Networks, Content and Technology under grant agreement No 101069594.
    </td>
  </tr>
</table>

**Comment by rtsisyk** [comment]
My brief research. There are three distinct scenarios:

## 1. Individual buildings and nodes 

> The tag [addr:postcode](https://wiki.openstreetmap.org/wiki/Key:addr:postcode)=* should be used in the context of addresses for buildings and nodes. [2]

U.K. specific:

> Certain organisations such as banks, medical centres & hotels were given unique post codes, presumably due to the high volume of correspondence they'd receive. Even though many of the properties have change businesses over the years (especially banks becoming eateries) they still retain their individual codes. [1]

**London:**

<img width="911" alt="image" src="https://github.com/organicmaps/organicmaps/assets/1799054/c625b6c6-6347-4471-8987-905c676fb415">

**Brighton:**

<img width="980" alt="image" src="https://github.com/organicmaps/organicmaps/assets/1799054/e608b777-efff-4cc9-85fa-8b315b032a6c">

**Germany (just to compare)**:

<img width="1006" alt="image" src="https://github.com/organicmaps/organicmaps/assets/1799054/49d6c183-9c1c-43db-995f-47769260a8b0">

## 2. Streets

> For streets with the same postcode on both sides of the way this postal_code=* is still valid and widely used. [2]

[1]: https://wiki.openstreetmap.org/wiki/Postal_codes_in_the_United_Kingdom
[2]: https://wiki.openstreetmap.org/wiki/Key:postal_code

**London**:

<img width="957" alt="image" src="https://github.com/organicmaps/organicmaps/assets/1799054/b1165b2f-9b04-4139-a925-f396ce183393">

**Brighton**:

<img width="975" alt="image" src="https://github.com/organicmaps/organicmaps/assets/1799054/6321d5f3-9353-44ad-bd46-a166ac69eb71">

**Germany (just to compare)**

<img width="1005" alt="image" src="https://github.com/organicmaps/organicmaps/assets/1799054/cbb8feee-9835-4a15-b3a1-42af4264563b">

## 3. Boundaries

> [boundary=postal_code](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dpostal_code) is used to specify a dedicated type=boundary area with a consistent national postcode.

**London:**

I found nothing.

**Brighton:**

I found nothing.

**Germany (just to compare):**

<img width="857" alt="image" src="https://github.com/organicmaps/organicmaps/assets/1799054/cd94b2cd-a23b-45ce-ae63-10ca5a439d17">

**Belgium (just co compare):**

<img width="865" alt="image" src="https://github.com/organicmaps/organicmaps/assets/1799054/0698d499-38be-417b-bf90-300afc6c4bf4">

## Other Data Sources

See [3]

**Code-Point Open**

Locations of every GB postcode centroid.

Useful for geographical analysis, simple route planning and asset management. Data contains postcodes, grid references, NHS® health and regional health authority codes; administrative ward, district, county and country area codes. PDF includes differences between Code-Point and Code-Point Open.

- Scale: 1 metre resolution for postcode central position
- Supply format: CSV (comma separated values: a text file)
- Update cycle: Quarterly, February, May, August and November
- Coverage: England, Scotland, Wales

https://beta.ordnancesurvey.co.uk/products/code-point-open#technical

```
"WR13 5DW",10,376933,251977,"E92000001","E19000001","E18000005","E10000034","E07000235","E05015380"
"WR13 5DX",10,378460,250850,"E92000001","E19000001","E18000005","E10000034","E07000235","E05015380"
"WR13 5DY",10,378625,250743,"E92000001","E19000001","E18000005","E10000034","E07000235","E05015380"
"WR13 5DZ",10,378181,250632,"E92000001","E19000001","E18000005","E10000034","E07000235","E05015380"
```

Attribute | Description
-- | --
Postcode | Contains elements for postal area, district, sector, and unit.
Positional quality indicator (PQI) | A flag used to indicate the positional accuracy of the coordinates allocated to each postcode record.
Easting | Distance in metres east of National Grid origin.
Northing | Distance in metres north of National Grid origin.
Country code | Code used by the Office for National Statistics (ONS) to identify the country in which the Code-Point Open georeferenced coordinates lies.
NHS regional health authority code | English Pan Strategic Health Authority in which Code-Point
Location Coordinate (CPLC) falls.
NHS health authority code | English Strategic Health Authority or Scottish Health Board in which CPLC falls.
Administrative county code* | County in which CPLC falls.
Administrative district code* | Unitary Authority, Metropolitan and Non-Metropolitan District, London Borough, or Scottish Council Area in which CPLC falls.
Administrative ward code* | Electoral Ward or Division in which CPLC falls.

There are hot discussions regarding importing vs non-importing PinPoint data

[3]: https://wiki.openstreetmap.org/wiki/Ordnance_Survey_OpenData_Licence
[4]: https://wiki.openstreetmap.org/wiki/Talk:Ordnance_Survey_OpenData

> For "CodePoint Open" and any other OS OpenData licenced information then the situation is at best unclear. There is no special permission from OS (or other rights holders) for these datasets, and the latest information from OS [[3]](http://robert.mathmos.net/osm/os-open-data.html) seems to imply that they regard the OS OpenData License as not compatible with the ODbL.

My take from these endless discussions that PinPoint data wasn't imported into OSM and there is no plans to do so.

## Plan

For U.K. (1) case should be prioritized. (2) and (3) can be useful for other countries, let's discuss separately.

High-level plan for the U.K.:

**Phase 1:**

1. Implement detection of the U.K. postcodes in the search string.
2. Prioritize search results in the radius of 100–200 (TBD) meters of the found postcode node.

**Phase 2:**

1. Augment OSM data with Code-Point Open data with deduplication.
2. Display copyrights properly.

**Comment by rtsisyk** [comment]
Experimental testing in Organic Maps:

## Case (1) - Nodes:

- ✅ "SE1 4PR", ⭕ "SE14PR"
- ✅ "SE1 3ST", ⭕ "SE13ST"

=> Parsing of  postcodes without space should be improved

## Case (2) - Streets:

"SE11 cafe"

![image](https://github.com/organicmaps/organicmaps/assets/1799054/f63cc4e2-1acd-461b-a8b4-35bcf3c08a87)


<img width="273" alt="image" src="https://github.com/organicmaps/organicmaps/assets/1799054/24c4398a-d7cb-42cd-8e3d-7fbbf4b333f6">

Seems to be working, but I don't have 100% confidence.

## Case (3) - Boundaries

![image](https://github.com/organicmaps/organicmaps/assets/1799054/e0c7d490-b596-4e97-8770-b5b5801b134c)

Seems to be working, but I am not sure that it is because of boundaries.

**Comment by rtsisyk** [comment]
Code-Point Open has 1,734,274 points. OSM (worldwide) has 1 ,281, 554 [distinct values in addr:postcode](https://taginfo.openstreetmap.org/keys/addr%3Apostcode#overview).

**Comment by endim8** [comment]
There was some sort of postcode centroid import 14 years ago: https://www.openstreetmap.org/changeset/792532, but it only has ~3000 points so imo isn't worth using.

Very happy to see that this is being worked on, thank you :D

**Comment by RedAuburn** [comment]
> I would use Organic Maps if OSM supported entering UK postcodes in the search box. Can’t wait to stop using Google Maps. - vladharbuz

https://news.ycombinator.com/item?id=37351545

**Comment by jahed** [comment]
I don't know if it will help with research, but there is a working script which generates post code data for OsmAnd as an OBF file here: https://github.com/hvdwolf/OsmAnd-UKpostcodes

**Comment by TS-CUBED** [comment]
Is there any progress on postcode search for the UK? Would love to move to Organic Maps, but in the UK no postcode search is an immediate no for most.

**Comment by biodranik** [comment]
This feature is planned. Please donate, support and stay tuned :)

**Comment by 3rdRockGuy** [comment]
2024jan29 OrganicSupport email reply has just told me
 "**We'll implement postal codes search from external sources in this year.** Please follow this issue: https://github.com/organicmaps/organicmaps/issues/717".
Fingers crossed and waiting hopefully....

**Comment by Cj-Malone** [comment]
> Code-Point Open
> Locations of every GB postcode centroid

This dataset covers Great Britain, not GB the country code (UK). It excludes Northern Ireland.

I have some Northern Ireland data [here](https://github.com/osm-uk/NI-Postcodes/blob/main/data/NI-postcodes.csv), I've not looked at it in years though.
