### ISSUE TITLE
[ios] Share location from OM to other apps

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7174]
1. Google Maps
2. Apple Maps
3. Tesla app
4. ...

Let's investigate which formats should be supported and how to better implement them. Together with #7173 it will be easier to switch between apps and migrate/use necessary missing features.

**Comment by aniket-singh-01** [comment]
Hi I am trying to solve but while setting up the project I am getting this error. How to solve it?
<img width="629" alt="Screenshot 2024-01-21 at 9 55 17 AM" src="https://github.com/organicmaps/organicmaps/assets/98407060/ea5dc3c6-4eef-4416-af25-12367480739a">

**Comment by kirylkaveryn** [comment]
@biodranik it's impossible to share the location with the sharing activity controller with the other apps.
Because we share the text (link or coordinates). And the apple cannot determine which app should handle the link (coodrinates).
The goolemaps, apple maps etc don't support any formats - you can see that it impossible to share anything  in this app. They only support the deeplinking.

Possible solution Is to make the _list of the apps_ that we want to share location _directly_, build the deeplink and open via the UIApplication.openURL(link).

For example:
```swift
self.viewController?.openUrl("https://www.google.com/maps/search/?api=1&query=\(self.placePageData.locationCoordinate.latitude),\(self.placePageData.locationCoordinate.longitude)", inSafari: true)
```

will handle the link as:

https://github.com/organicmaps/organicmaps/assets/79797627/832c636c-1542-409c-a158-43dba244ab11

**Comment by biodranik** [comment]
Thanks! Advertising other maps apps from Organic Maps looks like a controversial feature. We may need some better ideas.

**Comment by biodranik** [comment]
How to build URLs for Apple Maps: https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html#//apple_ref/doc/uid/TP40007899-CH5-SW1

**Comment by kirylkaveryn** [comment]
Here is the rough design with 3 variants of how we can implement this feature:

https://www.figma.com/design/tbIeaE9ixXpDW875A3gpd6/OM-ShareToApp?node-id=0-1&t=nvi1vvA8ZH5jsNwT-1

@biodranik @oleg-rswll @rtsisyk please leave your comments!

**Comment by biodranik** [comment]
Option 2.1 looks ok. Mixing displayed coordinates and opening them in apps looks too complex (option 1). Option 2 won't work well with many apps too.

**Comment by kirylkaveryn** [comment]
> Option 2.1 looks ok. Mixing displayed coordinates and opening them in apps looks too complex (option 1). Option 2 won't work well with many apps too.
> 
> The important thing is to detect apps that are present on a device and only show them if they are installed.

Thanks!
If we accept this option I'll start the developments.

**Comment by JustFxDev** [comment]
Hi!

Thanks for investigating this topic further!

I would like to adjust my inital idea:

At the moment the visble string is copied to the clipboard by doing a long press on it 

Maybe an other option on long press might be:

- do not copy to clipbard
- instead open a local menu with all possible calls like
** Copy string to clipboard
** Open Google Maps with the string (coordinates)
** Open "name of app" with that string...

Maybe this is more easy and fast to implement

Later on in let's "advanced option" one can add own calls to that menu... :-)

Cheers, Fx

**Comment by JustFxDev** [comment]
I tried that befor i posted my comment. But figma.com does not load. It complains my firefox is to old. But i'am using the very latest version....

So i could not look into it. I try with an other browser or without addins :-))

**Comment by JustFxDev** [comment]
Ha! I managed to open it. Options 2.1 and 2.2 are great!

**Comment by kirylkaveryn** [comment]
I've designed the 3rd variant with the new cell under the coordinates:
https://www.figma.com/design/tbIeaE9ixXpDW875A3gpd6/OM-ShareToApp?node-id=0-1&t=AMq3nRXB06N4NYCC-1

<img width="613" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/a1b78266-735c-4171-9e02-203b5c0e5644">

**Comment by oleg-rswll** [comment]
Option 2.1 looks good.  Storing icons of competitors locally makes more sense than requiring being online.  If icons change, they can be updated in the following release.

@kiryl
Moving the share button to the top right of the Place Page would align it with the Android version, and would place it where a share icon is quite common for many apps.  Looks like a good idea.  Adding a separate row in Place Page is probably not necessary with the Share icon already there.

Currently on iOS, when selecting the Share button, it displays contacts on the second line, on the third line apps to open in (looks like most communication apps like messaging and email apps), and below that option for Copy and other app integrations.  Can a section be added between contacts and messaging apps for the "Open in" apps?

**Comment by oleg-rswll** [comment]
![image](https://github.com/organicmaps/organicmaps/assets/123327737/f658f3d3-5638-47b6-9b4d-15e50a44031d)

**Comment by kirylkaveryn** [comment]
> Currently on iOS, when selecting the Share button, it displays contacts on the second line, on the third line apps to open in (looks like most communication apps like messaging and email apps), and below that option for Copy and other app integrations. Can a section be added between contacts and messaging apps for the "Open in" apps?

This share screen is fully composed by the system based on the applications that can handle the "data type" (text, image, kml etc) that we pass into it.
There is no possibility to edit/compose/directly affect on this share screen.

So the one possible solution is to leave the Share button as it is (and move to the right corner) but introduce a new button with proper description. This solution will not affect the default sharing.

**Comment by oleg-rswll** [comment]
To avoid the icon looking too similar  to the share button, how about the icon having arrow pointing to the upper right, something more like this:
https://icon-library.com/images/open-window-icon/open-window-icon-1.jpg

This option should probably be below the "Edit Place" button since it doesn't have anything to do with OSM data or bookmark data.

About the feature name, could be:
"Open place location in..."

**Comment by biodranik** [comment]
What about using icons of apps (maybe with their names below) where the coordinate will open, in a horizontal carousel (like in the current system sharing), with a text label "Check this place in:" placed above the carousel?

**Comment by Misalf-git** [comment]
> with a text label "Check this place in:"

"To check" seems rather specific to me (i.e. the user could do verifying, comparing).
Maybe just "Open place in App:" (what the button actually does)?

**Comment by euf** [comment]
Absolutely need **Waze**, since I imagine the main use case to be using live traffic navigation. They have documentation on deep links: https://developers.google.com/waze/deeplinks/

Also I agree with @oleg-rswll that a generic "Open in…" icon would be better than app icons. 

I designed one, please take a look: 

![0-open-in](https://github.com/organicmaps/organicmaps/assets/11754264/ca8eaefe-cc54-48e8-9d64-ba5645be9a8f)

**Comment by patepelo** [comment]
WDYT about adding www.openstreetmap.org to the options? It would help contributors see related data like history or subtags. Does it make sense to put it in here and would it be possible or better to put that apart?

**Comment by oleg-rswll** [comment]
Giving this more thought, it may be better to use the selector without the logos https://www.figma.com/file/tbIeaE9ixXpDW875A3gpd6?node-id=6:150&locale=en&type=design#844935958

- Even without logos, there would still be useful integration, but no focus on competitor branding.
- Apps like Yelp, when selecting a navigation app, show only names of the apps, not the logos.
- Without logos, there is no need to maintain updates of the logos.
- OM doesn’t even have OSM branding in the Place Page, where OSM data is used and could potentially be useful to see the OSM logo.  So probably no need to display big tech logos, just names.

**Comment by biodranik** [comment]
Only texts are okay. The UX becomes more complicated when the list of apps is very long...
