### ISSUE TITLE
POI pins with different colors

### ISSUE THREAD

**Issue by serrq** [organicmaps/organicmaps#7183]
I use POI to identifying everything: cities, railway stations, airports, toilets, SPA wellness, etc.

I would like assigning a specific colour on every pin and having the ability to include/esclude what I want to see or don't see.

For example:

Red: transport (bus, train, airplane stations)
Blue: cities, towns, villages, etc.
Yellow: toilets
Green: waterfalls, lakes, mountain huts, etc.
Pink: utilities like information points, travel agencies, etc.

Possibility to select/unselect pin colors that app can show on map.

![1000102862](https://github.com/organicmaps/organicmaps/assets/113377431/b1b9a70e-e371-4e61-93c9-69da95c49f53)

**Comment by janusbenissa** [comment]
Long click on the POI in the bookmarks and click edit :-)

**Comment by janusbenissa** [comment]
Put the POI in a KMZ file and you can choose to show them on the map or not.

**Comment by janusbenissa** [comment]
![Screenshot_2024-01-16-20-04-07-650_app organicmaps beta](https://github.com/organicmaps/organicmaps/assets/15191462/d2e1112e-2972-47b2-9064-4729c83f6fd4)
Not 100% sure what you want but I think it is posible, see my POI in OM

**Comment by janusbenissa** [comment]
I don't think it's fair to expect a globally used app to make an adjustment that's just for you?
99.% of users are more than satisfied with the way OM shows the POI.
