### ISSUE TITLE
Upload of OSM edits is broken

### ISSUE THREAD

**Issue by dbf256** [organicmaps/organicmaps#720]
![image](https://user-images.githubusercontent.com/2550295/123380197-d4afc880-d597-11eb-92c5-91fb95f71c99.png)

Build 2021.06.20

**Comment by biodranik** [comment]
Should be fixed in the upcoming updates 2021.06.23

**Comment by rtsisyk** [comment]
Please wait for the 2021-06-24 update in the store. I'm closing this issue as resolved, but feel free to re-open if 2021-06-24 still doesn't work.
