### ISSUE TITLE
Openstreetmap data update 

### ISSUE THREAD

**Issue by Uniquenameihave** [organicmaps/organicmaps#7203]
I want a feature in organic maps where we can update the openstreetmaps data like in osmand+

**Comment by Jean-BaptisteC** [comment]
Can you give more details?
We have planned to update maps more frequently (maybe each week), but it requires a lot of work, and generating maps files takes a lot of time.

**Comment by dmitrygribenchuk** [comment]
I guess (because I think about this feature too) is a manual update map on a local device.
This idea comes to me from Garmin watches, they store maps in .img files locally.

**Comment by Uniquenameihave** [comment]
> Can you give more details?

It is a manual update feature where we can update the osm live data manually 
This feature is available in osmand
![Screenshot_20240121-013642_OsmAnd~.png](https://github.com/organicmaps/organicmaps/assets/98287062/08b05562-477b-4126-b5e4-552289d77491)

**Comment by biodranik** [comment]
The whole data processing approach used in Organic Maps should be rewritten to support this feature. If we get enough donations to run a full-time dev team, then we can _start thinking_ about this feature.

**Comment by RedAuburn** [comment]
duplicate of https://github.com/organicmaps/organicmaps/issues/2317 / https://github.com/organicmaps/organicmaps/issues/835

**Comment by realeatham** [comment]
Close as not planned instead of completed
