### ISSUE TITLE
[android] Place page layout breaks down (regular?)

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#722]
Pixel 5, Android 11

![telegram-cloud-photo-size-2-5380066680434177227-y](https://user-images.githubusercontent.com/175612/123382884-227a0000-d59b-11eb-898e-309f6b0738ec.jpg)

![telegram-cloud-photo-size-2-5380066680434177226-y](https://user-images.githubusercontent.com/175612/123382904-29087780-d59b-11eb-935a-1ead47accc2f.jpg)

**Comment by Ihor-Khomenko** [comment]
@vng подскажи, пожалуйста, а какая последовательность шагов? У меня не получилось воспроизвести следующими способами:
1. Переход на точку через поиск
2. Переход на точку после тапа на карте
3. Переход на точку из списка избранного

**Comment by vng** [comment]
Последовательность неизвестна. Это баг из чатика. Проявляется нерегулярно, но часто ...

**Comment by rtsisyk** [comment]
@Ihor-Khomenko это точно как-то связано с поиском. Надо поискать что-то на карте и потом в какой-то момент происходит то, что происходит. При поиске скрывается тулбар и вместо него показывается какая полоска с кнопкой "LIST". Вероятно, что в какой-то момент почему-то тулбар неправильно восстанавливается. Мы гоняем monkey test уже достаточно давно и пока ни разу это не воспроизвелось. Но может вам повезет и вы поймемте последовательность.

**Comment by assusdan** [comment]
Воспроизводится на 2021.06.23-9-gc3f05a1-Google после поиска любого места, а затем добавления, в данном случае, организации (но, кажется, для любой метки так работает)

![Screenshot_20210629-112855_Organic Maps](https://user-images.githubusercontent.com/7590701/123765159-25902b80-d8ce-11eb-85e8-45cd3b6ea721.png)
![Screenshot_20210629-093334_Organic Maps](https://user-images.githubusercontent.com/7590701/123765165-26c15880-d8ce-11eb-9662-655f5c08aa84.png)

Samsung Galaxy S21

**Comment by rtsisyk** [comment]
Воспроизводится так:

1. Ставим две точки.
2. Кликаем на первую
3. Кликаем на вторую
4. Жмешь Edit Place на второй
5. Отменяем правку
6. Кликаем по первой


После этого либо разъезжается placepage, либо пропадают кнопки на тулбаре, либо и то и другое.

Копать надо в MwmActivity onPlacePageActivated/onPlacePageDectivated.
https://github.com/organicmaps/organicmaps/blob/master/android/src/com/mapswithme/maps/MwmActivity.java#L1131

**Comment by rtsisyk** [comment]
Видео: https://drive.google.com/file/d/1GdYEv1Sv5sxRTC8pQAr9J5DTdeMYDffr/view?usp=sharing

**Comment by Endem10n** [comment]
@rtsisyk На какой версии  Android и на каком устройстве удалось нарантированно воспроизвести?

**Comment by biodranik** [comment]
Вот ещё два примера, как будто хайдятся некоторые элементы интерфейса:

https://t.me/organicmaps/4868
https://t.me/organicmaps/4863

**Comment by Endem10n** [comment]
@biodranik В примерах выше одна и та же ошибка с наложением в одной и той же части разметки. Два последних скриншота выглядят, как ещё один отдельный баг.

**Comment by rtsisyk** [comment]
It seems that this problem is caused by some bug in Android layouts. I can re-produce it, but I don't see any problems in our code.  @Endem10n is trying to re-arrange layouts to create a workaround.

**Comment by rtsisyk** [comment]
I gave up, @biodranik is researching.

**Comment by biodranik** [comment]
The current workaround is to rotate the screen into the landscape and then back. Or to restart the app.
