### ISSUE TITLE
Update organicmaps/data/strings/strings.txt

### ISSUE THREAD

**Issue by laralem** [organicmaps/organicmaps#723]
Someone please open a pull request with the following file:
[strings.txt](https://github.com/organicmaps/organicmaps/files/6714678/strings.txt)

Working with regular files it's easy in GitHub but this is not the case since is a big file. I gave up trying to use GitHub desktop to work with this kind of files. Only made mistakes. I'm not a developer.

I've updated Portuguese and Brazilian Portuguese translations (and a few strings in other languages referring Maps.me instead Organic Maps).

**Comment by biodranik** [comment]
It would be great if someone also takes a look at https://github.com/organicmaps/organicmaps/blob/master/data/categories_cuisines.txt
and https://github.com/organicmaps/organicmaps/blob/master/data/categories.txt

**Comment by rtsisyk** [comment]
@laralem you can try to `git clone https://github.com/organicmaps/organicmaps.git` and then use VS Code to edit that file. It works ok without any problems.

**Comment by biodranik** [comment]
@laralem can you please also take a look on [data/strings/types_strings.txt](../blob/master/data/strings/types_strings.txt) and [iphone/plist.txt](../blob/master/iphone/plist.txt) ?

**Comment by laralem** [comment]
> It would be great if someone also takes a look at https://github.com/organicmaps/organicmaps/blob/master/data/categories_cuisines.txt
> and https://github.com/organicmaps/organicmaps/blob/master/data/categories.txt

> @laralem can you please also take a look on [data/strings/types_strings.txt](../blob/master/data/strings/types_strings.txt) and [iphone/plist.txt](../blob/master/iphone/plist.txt) ?

@biodranik Done! https://github.com/organicmaps/organicmaps/pull/1121 https://github.com/organicmaps/organicmaps/pull/1124 https://github.com/organicmaps/organicmaps/pull/1127 https://github.com/organicmaps/organicmaps/pull/1138

**Comment by pastk** [comment]
This issue could be closed I guess.
