### ISSUE TITLE
Custom storage location for map data to share with other Apps using OSM data

### ISSUE THREAD

**Issue by skwde** [organicmaps/organicmaps#7234]
**Is your feature request related to a problem? Please describe.**

I am also using OSMAnd which allows me to specify a custom path for my map data.
I would like to share map data between OSMAnd and Organic Maps.
To do this I need to specify a custom path in Organic Maps, which to my understanding is not possible at the moment.

**Describe the ideal solution**
Specify a custom path where organic maps should store / load maps data.

**Describe alternatives you have considered**
Installing maps twice, one time in OSMAnd one time in OrganicMaps, but this is insane.

**Additional context**

There is also this https://github.com/organicmaps/organicmaps/issues/6417 issue, which is only concerned with storing on a SD card.

**Comment by biodranik** [comment]
Our maps format is not compatible with OSMand.
