### ISSUE TITLE
Latest Android version crashes when opening a GPX-file

### ISSUE THREAD

**Issue by ststeiger** [organicmaps/organicmaps#7237]
**Describe the issue**
Opening a GPX file in OrganicMaps leads to an immediate crash. 

**Steps to reproduce**
0. Update OrganicMaps and Android to latest version. 
1. go to maps.google.com 
2. select a path from A to B
3. On the left side, select "Share or embed maps"
4. this gives a link like 
https://maps.app.goo.gl/9L1xa4uW5KRkjpi6A
5. now paste that link into 
https://mapstogpx.com
6. and download the gpx file
7. Send the gpx-file to the mobile phone via Telegram (or whatever you prefer) 
8. Open the gpx-file on Telegam on the phone (with OrganicMaps) 
9. Instant Crash (this used to work) 

**Expected behaviour**
This used to work fine in earlier versions. 
You used to see the track instead of a crash. 
Highly annoying. 
I use this a lot, as the route planner in OSM just isn't up to par with google. 

**System information:**
- Android 14, One-UI 6, Kernel 5.15.104, Security Patch December 1 2023, Knox 3.10
- Organic Maps V 2024.01.09-6-Google
- Device Model: Samsung Galaxy A54 5G

**Comment by Jean-BaptisteC** [comment]
I guess similar of this #7149

**Comment by ststeiger** [comment]
@Jean-BaptisteC: Yep, related to Security Patch December 1 2023

**Comment by biodranik** [comment]
@ststeiger did you test it with some older OM version? You may try some older beta, for example.

**Comment by biodranik** [comment]
@ststeiger please check if it was fixed in the latest OM version.

**Comment by ststeiger** [comment]
Fixed.
