### ISSUE TITLE
Color of pins not preserved during export from umap

### ISSUE THREAD

**Issue by Magnet-U** [organicmaps/organicmaps#7251]
Hello,

I am trying to export data from umap to organic maps (and I saw this issue was the same with [maps.me](https://maps.me/) and google earth). Unfortunately during the export the color (and shape) properties of the pins I have added are lost, thus organic maps and the others just assign them the same default value. Is this a bug or a missing feature?

Thanks!

**Comment by biodranik** [comment]
@Magnet-U do you have the kml example file? Are shapes and colors png images/icons?

**Comment by Magnet-U** [comment]
Hi! I don't see references to the pin in the kml file... I attach the screenshot. 
This is the map by the way:
http://u.osmfr.org/m/1015347/

Thanks!


![screenshotMapKml](https://github.com/organicmaps/organicmaps/assets/62301742/7bad9773-9163-4191-83a4-f84399b870e4)

**Comment by cyber-toad** [comment]
> Hi! I don't see references to the pin in the kml file... I attach the screenshot. This is the map by the way: http://u.osmfr.org/m/1015347/
> 
> Thanks!
> 
> ![screenshotMapKml](https://private-user-images.githubusercontent.com/62301742/300161197-7bad9773-9163-4191-83a4-f84399b870e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODcwNDEsIm5iZiI6MTcwNjM4Njc0MSwicGF0aCI6Ii82MjMwMTc0Mi8zMDAxNjExOTctN2JhZDk3NzMtOTE2My00MTkxLTgzYTQtZjg0Mzk5Yjg3MGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDIwMTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NDMzZWJkNjM2ZjM1MmIwOTA5YTUxOTE5MWE0YTcwMjQ5MTRhYTlmN2ZhYzU5ZGM3YmQ3YzYzYjEyMDI2NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TwPPEMc3S21x_OeKsUuBSGsJigdcYdCKgErcUVC4Dhc)

It looks like uMap website export colors only if you use "Full backup" download link - in this case colors are available in json that they provide. And for kml/gpx color is not included into file so Organic Maps uses default values.

**Comment by Magnet-U** [comment]
okay thanks! too bad when I click on full backup though, the file format is .umap and organic maps and other apps cannot really open it. thanks though!

**Comment by biodranik** [comment]
@Magnet-U you can create an issue for umap https://github.com/umap-project/umap/issues
And maybe even fix it, the related conversion code is here: https://github.com/umap-project/umap/blob/7fc19b10383739e6d9438b5aa2e0db463ac9759b/umap/static/umap/js/umap.share.js#L19
