### ISSUE TITLE
Add preference for configuring frequency of contour lines

### ISSUE THREAD

**Issue by maze88** [organicmaps/organicmaps#7252]
**Is your feature request related to a problem? Please describe.**
Like many others, I use Organic Maps also for hiking. I activate the _Contour Lines_ under _Map Styles and Layers_ and sometimes I navigate manually and other times by the application's routing.
It could be very useful to have an option to adjust the scale/frequency of the contour lines. This would be especially great for manual open field navigation (where I don't rely on trails or paths at all), especially in areas that don't have such steep topography - but still may have pronounced features in the field.

**Describe the ideal solution**
Add option under preferences, to adjust the scale/frequency of the contour lines (applied whenever the _Contour Lines_ layer is enabled).

**Comment by biodranik** [comment]
Please follow https://github.com/organicmaps/organicmaps/issues/8673 and related issues.

**Comment by pastk** [comment]
Closed as a duplicate.
