### ISSUE TITLE
Add a map legend

### ISSUE THREAD

**Issue by maze88** [organicmaps/organicmaps#7253]
**Is your feature request related to a problem? Please describe.**
Adding a map legend in the menu, so that one may understand what the different colors (lighter green, darker green, etc.), lines (white, brown dotted, thin blue, etc.) and icons mean.
I believe a legend is a key feature of **any** map, and I feel this most when travelling/hiking in new areas that have different terrain/climate than what I am used to locally (around home) - since having to understand a whole load of new icons and map notations can be frustrating when handling an entire new environment already.

**Describe the ideal solution**
Adding a map legend in the menu.

**Comment by Jean-BaptisteC** [comment]
Long press on map to know the type of object :)

**Comment by maze88** [comment]
Ok, that's new to me - is it documented anywhere?
Thanks!

**Comment by biodranik** [comment]
How would you make long tap discoverable by users? See #1105 

Implementing a legend is a very complex task. It would be great to avoid it by making the map style as easy to understand as possible and making it easier for users to discover object types by tapping on them and highlighting them properly.

**Comment by RedAuburn** [comment]
> How would you make long tap discoverable by users? See #1105

i think the only way would be a small popup at the top of the screen saying something like "try long-pressing" the first 3 times OM is launched or something.

i definitely don't think we need to implement a legend.

**Comment by maxoghana** [comment]
I was looking for days for a legend. I didn't know that long pressing displays the type of road. It's not really intuitive. Maybe you can just add a FAQ about this

**Comment by biodranik** [comment]
@maxoghana now a single pressing displays the type of any object. No need to complicate the FAQ.

**Comment by trutzig89182** [comment]
The single tap does not entirely make a legend obsolete, I reckon. Just had a question from a friend, what those red lines in an are mean. I had to check the legend on the OpenStreetMap website in order to see that it is a military areal. If I tap on the area it just gives back the specific objects like a "forest". Please let me know if I have missed something and there is a place in the app where I could have gotten the information on a military area.
