### ISSUE TITLE
Add screenshots to F-Droid

### ISSUE THREAD

**Issue by Korb** [organicmaps/organicmaps#7274]
https://f-droid.org/packages/app.organicmaps/

![Screenshot_2024_0130_081729_org fdroid fdroid](https://github.com/organicmaps/organicmaps/assets/3509797/29a9f5dc-d57e-49d3-96cb-1e9dc4784286)

**Comment by Jean-BaptisteC** [comment]
Screenshots, logo and banner are present on F-Droid website.

**Comment by Korb** [comment]
@Jean-BaptisteC, do you understand that if all application publishers adhere to this position, application stores, be it Google Play, Microsoft Store or Steam, will turn into lists of titles with “install” buttons? Would it be convenient for you to use such catalogs that do not contain any information that would help the user choose from a variety of applications the one that will be more useful to him than others? Conversely, when most applications in the catalog have detailed descriptions and screenshots, an application without them looks suspicious. One gets the impression that this is some kind of abandoned project, or even a malicious application that somehow found its way into the store, and will soon be removed with an apology after several complaints. I suggest you reconsider how your app is presented in app stores. You posted screenshots on Google Play, regardless of your principles. Make an exception for F-Droid, please.

**Comment by licaon-kter** [comment]
I can see description and screenshots in Client just fine

@Korb try to enable autoupdate and slide mobile data to the right at Always, pull to refresh, etc
