### ISSUE TITLE
[android] - Editor automatically adds a wrong postal code

### ISSUE THREAD

**Issue by patepelo** [organicmaps/organicmaps#7312]
⚠ Have you searched for similar, already existing issues?
Yes
**Describe the issue**

When editing a POI, it automatically adds a wrong postal code even if you're just editing the phone number.

**Steps to reproduce**
Select a POI in Barcelona, edit the phone number or simple details. 

Look up for the uploaded edit in OSM and see that it always adds the default 08001. 

**Screenshots**

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: 2024.01.18-9-Google-beta
 - Device Model: Pixel 4A

**Additional context**
This is a critical bug for the OSM Community since many wrong information will be added.

**Comment by Jean-BaptisteC** [comment]
Duplicate #6260

**Comment by patepelo** [comment]
Sorry @Jean-BaptisteC . I hadn't found it before. Merci!
