### ISSUE TITLE
Beta distribution channel for Android

### ISSUE THREAD

**Issue by Miq1** [organicmaps/organicmaps#7315]
Today I got a Firebase notification mail (again) about a new beta version. This seems to fix some issues I had with the previous beta, but...

The Firebase app has brownish icon, has "(Beta)" in its name and claims to be of February 5th. At the same time the Google Play Store beta app has not been updated yet and is of January 9th with a green icon and no "Beta" addition.

The problem is, Android Auto will only present the Google Play Store version to be started, the brownish Firebase icon is not to be seen.

What am I supposed to do - wait until the Google version eventually has been upgraded as well?

**Comment by Jean-BaptisteC** [comment]
Release and beta doesn't have same icon.
Android auto is only available on Google release

**Comment by Miq1** [comment]
I see. So I will have to wait for the beta on Google.
