### ISSUE TITLE
[iOS] Problem with Portuguese strings

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#7337]
In this latest version (Feb 2024, App Store), Portuguese strings (both PT and PT-BR) are borked.

Not sure if regen strings tools were updated, but looking at line 12654 (just an example) in strings.txt I can see PT string but not PT-BR, so this one only shows up in PT version. On the other hand, at 12682, there is PT-BR but not PT, so this string shows the translated version only in PT-BR (but not in PT).

This does not happen at ES and ES-MX (for example), and I'm not sure why PT-BR is not picking up from PT first instead of EN. Also, again, this didn't happen in the other OM versions, just in this one.

**Comment by matheusgomesms** [comment]
Example of PT-BR (line 12654):

![IMG_0D582C68E5B2-1](https://github.com/organicmaps/organicmaps/assets/86851490/863f843d-ab5a-4fa4-9db9-f3a37b7d98d7)

**Comment by biodranik** [comment]
@matheusgomesms thanks for raising this issue. @rtsisyk has broken translations for some reason in this commit: https://github.com/organicmaps/organicmaps/commit/ae19226c60eb8e1e36bc06b7146a6bc6bf70c577#diff-c162962c24e85830ee16e272359a89e6163b9d8a5586501178163c054ffa9cadR2

@rtsisyk do you use an older/unpatched version of twine not from tools/twine folder (or not using our `tools/unix/generate_localizations.sh` script)? How did you run it? Please check next time that you did not replace correctly translated files with wrong English versions.

A separate question @rtsisyk : how did it pass the code review?
