### ISSUE TITLE
Copy address by long tap

### ISSUE THREAD

**Issue by MrPaschenko** [organicmaps/organicmaps#736]
### Discussed in https://github.com/organicmaps/organicmaps/discussions/735

<div type='discussions-op-text'>

<sup>Originally posted by **MrPaschenko** June 25, 2021</sup>
Hello!
There is ability to copy coordinates now, but there is no such for copying address. I think it would be great feature to copy address by long tap!

There is screenshot of how it works now with coordinates:
![telegram-cloud-photo-size-2-5382237236646492017-y](https://user-images.githubusercontent.com/64316080/123480297-d2d31d00-d60a-11eb-9085-62b4c68c75a5.jpg)
</div>

**Comment by biodranik** [comment]
It should work in the upcoming release.
