### ISSUE TITLE
Screen not staying on!

### ISSUE THREAD

**Issue by DavidRLTG** [organicmaps/organicmaps#7366]
⚠ Have you searched for similar, already existing issues?
Yes!

**Screen turns off during navigation**
Whether I'm just viewing the map, or navigating, my phone screen turns off at some point.

**Steps to reproduce**
1. Turn on keep screen always on during navigation
2. It turns off anyway!

**Expected behaviour**
I wish for the screen to stay on!

**System information:**
 - GrapheneOS Stable Latest, Android 14
 - Organic Maps version: 2023.12.20-4-FDroid
 - Device Model: Google Pixel 8 (Non-Pro)

**Additional context**
I enabled keep screen always on, My battery was high, The app has all permissions necessary, Issue isn't fixed.
I also checked other issues, but did not find a fix for this and they were rather old. Any help is appreciated, Thank you.

Also, I use the F-Droid version that was not updated in ages due to the Ads disagreement

**Comment by biodranik** [comment]
This issue was already fixed and has been available in January releases. You can install a github releases [web version of OM](https://github.com/organicmaps/organicmaps/releases) instead of FDroid one (don't forget to save your bookmarks before uninstalling OM) or wait for FDroid updates.

**Comment by DavidRLTG** [comment]
> This issue was already fixed and has been available in January releases. You can install a github releases [web version of OM](https://github.com/organicmaps/organicmaps/releases) instead of FDroid one (don't forget to save your bookmarks before uninstalling OM) or wait for FDroid updates.

When will the F-Droid issue be resolved?
Sorry if I sound bad or anything, but it's a little.. Inconvenient to always update via Github.
Maybe we should just get a button to disable Kayak or something.
