### ISSUE TITLE
Phone data doesn't work well when separated by semicolons, mobile and fax tags aren't displayed

### ISSUE THREAD

**Issue by ahmetlii** [organicmaps/organicmaps#737]
Hello,
I've noticed the app doesn't accept semicolons on the phone data, and also doesn't accept mobile and fax tags.

**Comment by rtsisyk** [comment]
@vng could you please check what is the source of this problem - generator or UI?

**Comment by rtsisyk** [comment]
@ahmetlii please send a link to 1-2 OSM objects which doesn't work in the app

**Comment by ahmetlii** [comment]
@rtsisyk https://www.openstreetmap.org/way/945652511 (mobile=* doesn't render) https://www.openstreetmap.org/way/634091071 (fax=* doesn't render), and https://www.openstreetmap.org/node/8602951111 (multiple entries on phone data doesn't work)

**Comment by biodranik** [comment]
Thanks, it's definitely a bug. @vng please take a look, all info was already in nodes when we generated maps.

**Comment by biodranik** [comment]
Semicolon separator for phone numbers should work already for Android, but should be implemented for iOS.

![IMAGE 2022-04-16 08:35:54](https://user-images.githubusercontent.com/170263/163664633-9db94002-89d6-43ab-8e3a-b81ed13f74da.jpg)

**Comment by biodranik** [comment]
Regarding displaying the fax, I've added #2406

**Comment by biodranik** [comment]
Regarding mobile, here is a PR: #2407
