### ISSUE TITLE
Opening Hours not parsed

### ISSUE THREAD

**Issue by PinguDEV-original** [organicmaps/organicmaps#7372]
⚠ Have you searched for similar, already existing issues? Yes.

**Describe the issue**
I clicked on a Burger King and then looked at the opening hours: They werent parsed, so there was just like the raw data.

**Steps to reproduce**
1. Open Organic Maps (obviously)
2. Go to **49.350486, 8.632412**
3. Click on the burger king there

**Expected behaviour**
The usual opening hours thingy with "is open"/"is closed" and stuff like this.
**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem
![Screenshot_20240212-122800](https://github.com/organicmaps/organicmaps/assets/82669329/0ab639e8-4115-4342-9d59-34545282c4a2)
.

**System information:**
 - Operating system and its version: Android 14 stable
 - Organic Maps version: 2024.02.06-11-Web
 - Device Model: Pixel 6a with GrapheneOS

**Additional context**
Please add any other context or comments here that may be useful.

**Comment by CaldeiraG** [comment]
https://www.openstreetmap.org/node/416053213

Seems to be valid according to the evaluation tool: https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Th%2010%3A00-22%3A00%3B%20Fr%2010%3A00-23%3A00%2C%20Sa%2010%3A00-23%3A00%2C%20Su%2010%3A00-23%3A00%2C%20PH%2010%3A00-23%3A00&lat=48.7769&lon=9.1844&mode=0&DATE=1707738840000

**Comment by matheusgomesms** [comment]
Duplicated issue, the problem here is the PH part, which OM can't recognize.

**Comment by matkoniecz** [comment]
#3883 to be more specific

**Comment by matkoniecz** [comment]
BTW, found with https://github.com/organicmaps/organicmaps/issues?q=is%3Aissue+is%3Aopen+opening+hours+not+parsed
