### ISSUE TITLE
Organic Maps offers to call fake phone number on POI display

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#7373]
⚠ Have you searched for similar, already existing issues?

https://github.com/search?q=repo%3Aorganicmaps%2Forganicmaps+fake+phone+number&type=issues

https://github.com/search?q=repo%3Aorganicmaps%2Forganicmaps+phone+POI&type=issues

**Describe the issue**

https://www.openstreetmap.org/node/9985444500 has no phone number

Organic Maps has phone button that wants to call 667209002100

This is not even a valid phone number

**Steps to reproduce**
1. Go to https://www.openstreetmap.org/node/9985444500 in app
2. select this object
3. press phone call button in app

**Expected behaviour**
no fake phone number

**Screenshots**

![Screenshot_20240212-143336](https://github.com/organicmaps/organicmaps/assets/899988/16d08bb7-2f17-4206-b8a3-4dd2096afe77)

**System information:**
 - Operating system and its version: Android 10
 - Organic Maps version: 2023.02.06-11-Google
 - Device Model: Xiaomi Mi A2 Lite

**Additional context**
Please add any other context or comments here that may be useful.

**Comment by matheusgomesms** [comment]
The POI (in OSM) has Opening Hours in the phone tag, perhaps this is the issue.

**Comment by matkoniecz** [comment]
ops? I guess that counts as bad OSM data though some sanity check may make sense

fixed in OSM
