### ISSUE TITLE
[question] Updates abandoned?

### ISSUE THREAD

**Issue by Pakuter** [organicmaps/organicmaps#7389]
Hi!

I wanted to update maps data and…

![IMG_2319](https://github.com/organicmaps/organicmaps/assets/160077911/a5918b03-4e12-42cb-8d48-89920e783740)

Last release was last year… When will be next update?

**Comment by fitojb** [comment]
You should get an update soon.
https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client
