### ISSUE TITLE
Place editor assumes name:es should be name

### ISSUE THREAD

**Issue by garaolaza** [organicmaps/organicmaps#7396]
**Describe the issue**

When editing place names in Organic Maps, the form shows me three options (probably because of my personal settings):

- Español (for spanish)
- English
- Euskara (for basque, our language)

If I edit the Spanish name, Organic Maps will not update the "name:es" field in OSM, but the "name" field.

I feel this happens because Organic Maps assumes  name = name:es in Spain and name = name:fr is France which is not always true.

**Steps to reproduce**
1. Open Organic Maps somewhere in Spain
2. Click on an editable item, like a gas station or playground
3. Go to edit the item
4. See how there is not a general name field but only a Spanish name field.
5. Type some testing name text in the Spanish field.
6. Go to OSM and check the fields 'name' and 'name:es'

**Expected behaviour**
There should be one general 'name' field in Organic Maps

**Screenshots**
![2024-02-15 09 18 32](https://github.com/organicmaps/organicmaps/assets/1560704/44fa915b-b6cc-4b7f-ada4-625c4392c30c)

![2024-02-15 09-19-35](https://github.com/organicmaps/organicmaps/assets/1560704/745aea60-203b-4363-a583-fbee65d8ab52)

**System information:**
 - Operating system and its version: Android 12 SP1A.21812.016
 - Organic Maps version: 2024.02.06-11-Google
 - Device Model: Redmi Note 9

**Comment by matheusgomesms** [comment]
Long time bug #762 (and many others). There a PR open #6257 but not merged yet.

**Comment by garaolaza** [comment]
Ok, so I am closing this one to avoid duplicates. Thank you @matheusgomesms
