### ISSUE TITLE
Map downloads fail when the phone screen locks up

### ISSUE THREAD

**Issue by mkoncek** [organicmaps/organicmaps#7435]
⚠ Have you searched for similar, already existing issues?

**Describe the issue**
Map downloads fail when the phone screen locks up. The started download will finish and maybe one more but the following downloads will fail while the phone's screen is black.

**Steps to reproduce**
1. Set up a download of multiple maps and start downloading them
2. Press the right button of the phone, locking the screen
3. The first 1/2/3 maps will download, the rest will fail to download

**Expected behaviour**
Maps should keep downloading while the phone is locked in case there are lots of them

**Screenshots**
N/A

**System information:**
 - Android 12
 - 2024.02.06-11 (was happening previously too)
 - Samsung A41

**Additional context**
It is hard to tell when exactly the downloading will start failing and whether it even starts since the screen is black.
Only observable thing is that all the downloads are marked as failed.
I believe I noticed that the downloads fail gradually, i.e. when unlocking the phone, some downloads have failed but the latest one is still in process. From the user perspective, this is annoying. I have noticed this issue on my device with 100 % frequency.

**Comment by biodranik** [comment]
Is it related to #5586 ?

There also was a TODO issue about implementing an appropriate foreground service download notification to avoid interruption.

**Comment by mkoncek** [comment]
Very well possible, I do have the power saving mode on.

**Comment by mkoncek** [comment]
The download still fails for me even then I turn off the power saving mode.
