### ISSUE TITLE
Wrong path type names on long-tap selection

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7442]
> On certain foot paths, a long press on them reveals labels such as
"psurface-paved_good" or "hwtag-lit" in the name section rather than the
label "Foot Path". Here are some examples:

psurface-paved_good: https://www.openstreetmap.org/way/330654179
hwtag-lit: https://www.openstreetmap.org/way/685004787

CC @vng

**Comment by pastk** [comment]
Isn't it fixed by https://github.com/organicmaps/organicmaps/pull/7346?

Do you reproduce on a master build?

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.03.31-8-Google version
