### ISSUE TITLE
Add a clear mention when a shop is "open"

### ISSUE THREAD

**Issue by SuperMeepBoy** [organicmaps/organicmaps#7447]
⚠ Have you searched for similar, already existing issues?
Yes, I have.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example:
It is unclear whether the shop is "open" or if OrganicMaps does not have the information about the opening hours of a shop.

**Describe the ideal solution**
A mention "opened" (written in green by default, in blue for colourblind, or if there is not colourblind mode, in blue by default) should be added at the same place we see "Opens in 32 min".
Cf screenshot to see what I'm talking about.
![image](https://github.com/organicmaps/organicmaps/assets/17031351/7e87131f-cd9d-4dbc-a429-ceb6a2d8c14a)
How do I know if "Le Grillon" is currently opened or OrganicMaps just does not have the information about opening hours ?

**Describe alternatives you have considered**
Other alternatives include writing a mention such as "No information about the opening hours"/"Opening status unknown", or have the name displayed in different colors based on if they are opened or not but this would add too much circus vibes to the app (and it would be unclear because we would be wondering what the color means).

**Comment by Jean-BaptisteC** [comment]
The bar "Le Grillon" has not opening hours, we can only tell POI is opened only if we have opening hours

**Comment by SuperMeepBoy** [comment]
My bad. Thanks a lot. Closing the issue.
