### ISSUE TITLE
[iOS] Wrong color light mode in Edit Place

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#7448]
See video below, but basically my iPhone is in latest stable version (iOS and OM), dark mode, but I prefer light mode for OM. When I open OM, some stuff can't be seen (it seems it's on the dark mode colors), so when I switch OM to dark mode and return back to light mode, it's fine. But, when I close and open OM again, the same happens.

CC @kirylkaveryn 

https://github.com/organicmaps/organicmaps/assets/86851490/8dff5ea2-cd4a-49ec-85b7-9e8ae249953f

**Comment by kirylkaveryn** [comment]
Thanks! I will take a look!

**Comment by Kopterlove** [comment]
And, from last update can't see name delete button in bookmarks:![image](https://github.com/organicmaps/organicmaps/assets/99100821/d51b3af4-6cf0-4eba-bf1e-c881f2642772)
![image](https://github.com/organicmaps/organicmaps/assets/99100821/82b2c83c-bed5-4312-835a-3660317556e7)

**Comment by kirylkaveryn** [comment]
@Kopterlove can you please make a video with the bug?
This x button becomes visible only when you edit the field and hides when you finish editing (as before).
![image](https://github.com/organicmaps/organicmaps/assets/79797627/4b53f781-c950-4c66-8c8f-bba5649802a2)

**Comment by Kopterlove** [comment]
@kirylkaveryn, here is a video. (X) button here, but not visible. I can tap and delete name, but need to tap exactly in small button. 

https://github.com/organicmaps/organicmaps/assets/99100821/35205768-69b1-4f69-b9a4-5a790034f447

**Comment by kirylkaveryn** [comment]
@Kopterlove thanks a lot! I'll take a look
