### ISSUE TITLE
Allow adding wind turbines in the editor

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7454]
Do we already render wind turbines on the map? @organicmaps/styles

**Comment by RedAuburn** [comment]
They are displayed as a generic electricity symbol, but the type already exists in MWM. Just need an icon. zoom levels are more of an issue though, as the tagging for large wind turbines & small home turbines is the same, but with different rotor:swept_area=* & height=*.
i guess we could convert to smth like generator-wind-small & generator-wind-large?

**Comment by pastk** [comment]
Adding to the Editor is not possible atm due to
- #4523
