### ISSUE TITLE
Organic maps does not take path other OSM solutions do

### ISSUE THREAD

**Issue by Echolon** [organicmaps/organicmaps#7461]
⚠ Have you searched for similar, already existing issues?
Yes, there are issues like: https://github.com/organicmaps/organicmaps/labels/Routing

**Describe the issue**
I drove this route as Apple Maps were suggesting it still and I couldn't believe it does not work. And yes, its the best way.
OSM Routing finds it too:

https://map.project-osrm.org/?z=11&center=37.741085%2C-119.776451&loc=37.814395%2C-120.119019&loc=37.713702%2C-119.632874&hl=en&alt=0&srv=1
<img src="https://github.com/organicmaps/organicmaps/assets/29168011/47652a5a-ba26-4902-b33b-bfbd12519200" alt="drawing" width="800"/>

However, Organic maps prefers to take a detour and also forcing does not work:

<img src="https://github.com/organicmaps/organicmaps/assets/29168011/75ac2b09-2f07-45db-85ed-a69c01e92eda" alt="drawing" width="400"/>

**Expected behaviour**
Take the way as the other services suggest.

**System information:**
 - Operating system and its version: [Android 12]
 - Organic Maps version: ?, from October 2023
 - Device Model: Fairphone 4

**Comment by biodranik** [comment]
@Echolon what are your "avoid..." options? Did you try to disable them?

**Comment by Echolon** [comment]
> @Echolon what are your "avoid..." options? Did you try to disable them?

You are right, its a toll road -.- My bad.

And thanks that organic maps still show a fee sign.
