### ISSUE TITLE
Exit navigation button in expanded notification widget

### ISSUE THREAD

**Issue by j13m126** [organicmaps/organicmaps#7492]
⚠ Have you searched for similar, already existing issues?
yes

One thing I often miss in OM is a quick way to exit navigation mode. Swiping the widget in the notification drawer would be one way to quickly exit navigation mode once you arrive, but that may also lead to accidental exits. 

What I would suggest is to implement an exit button in the (expanded) widget like in Google Maps and OSMAnd. 

What do you think?

If you agree then his ticket could be added to the list #1104 

**notification widget collapsed**
![notification](https://github.com/organicmaps/organicmaps/assets/7961926/a58037b9-9f19-491e-b468-67da1f24d3ea)
**notification widget expanded**
![notification2](https://github.com/organicmaps/organicmaps/assets/7961926/4cc024b0-dfdf-4a72-9239-3bcae436af60)

**Comment by Jean-BaptisteC** [comment]
Good idea
A solution is to add action in the notification and call `stopService `methode

**Comment by biodranik** [comment]
We need to start extracting and fixing individual tickets from that large meta issue :)

What exactly happens in Google Maps and OSMand after pressing that button? Navigation stops, notification disappears, the app is _not_ activated, right?

**Comment by Jean-BaptisteC** [comment]
Works has been started [here](https://github.com/organicmaps/organicmaps/commit/b5f946ee39bc62799b690f3d53ac51a8222ac9cb)
