### ISSUE TITLE
[Android Auto] Make app usable for free driving mode

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7501]
Now the currently used template takes a lot of screen space. Changing it requires redesigning the UX flow and likely adding switching buttons, as there are also some limitations from Google. @AndrewShkrob right?

![выява](https://github.com/organicmaps/organicmaps/assets/170263/dd471bd3-9571-44b7-b3f9-1d23fe6b6ad3)

**Comment by Jean-BaptisteC** [comment]
Similar of #7064
