### ISSUE TITLE
Wrong walking time when in transport navigation mode

### ISSUE THREAD

**Issue by danilax86** [organicmaps/organicmaps#7509]
**Describe the issue**
When in public transport navigation mode and you have segments for walking, time for this kind of segments is taken from the previous navigation mode.

**Steps to reproduce**
1. Plan a route from A to B (do not start navigation) in public transport mode. A route can take quite some time.
2. Plan a route from A to C in public transport mode. NB! there is minimal distance and no public transport between A to C.
3. See that the time stays the same like between A to B.
4. Change between modes and see, that time changes with every mode, but the time for public transport is being preserved by the previous mode.

**Expected behaviour**
Walking time in public transport mode should have the same value as in walking mode.

**Screen capture**
https://github.com/organicmaps/organicmaps/assets/46713109/d1b47cfe-a291-47ae-b3ab-e0c0b7173e00

**System information:**
 - Operating system and its version: iOS 17.4
 - Organic Maps version: ⁦2024.02.18-14⁩
 - Device Model: iPhone 12 mini

**Comment by Jean-BaptisteC** [comment]
It's not a wrong ETA, if app doesn't find public transport for routing, we show walking routing (we support only metro and light rail).

**Comment by danilax86** [comment]
After cold start and choosing public transport, it shows weird nulls 
![IMG_0474](https://github.com/organicmaps/organicmaps/assets/46713109/e157b079-5f8e-4a3e-abc6-dbd7c33bb811)
