### ISSUE TITLE
[ios] Remove bookmark sharing artefacts

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#751]
![sharing](https://user-images.githubusercontent.com/1799054/123519402-c3f47500-d6b3-11eb-8836-ce07f0ec7f57.jpg)

**Comment by yesmanchyk** [comment]
Quick fix looks like
![image](https://user-images.githubusercontent.com/91508478/136878923-e3aa202d-a506-484f-9b86-904c8c5d68e4.png)

However there should be some image according to https://github.com/organicmaps/organicmaps/blob/9dd9e7e4ecfeba4b39c8deba0a2e58d4543c7384/iphone/Maps/Bookmarks/Categories/Categories/BMCCategoryCell.swift#L49
so further code cleanup may be required.

Please check https://github.com/organicmaps/organicmaps/pull/1416

**Comment by Jean-BaptisteC** [comment]
Fixed by #1416
