### ISSUE TITLE
Organic maps 03-05 has a different app ID on Android than last version

### ISSUE THREAD

**Issue by DireMunchkin** [organicmaps/organicmaps#7520]
**Describe the issue**
The APK for the latest version of Organic Maps seems to have a different app ID than the last version from 02-06. This means Android considers it a different app to the last version of OM. This is a problem since I now can't upgrade in place and keep my places. Install on i.e. Obtainum also errors out.

This is also a bit of a security issue, as Android has trust-on-first-use for installs, and I'm now being asked to re-trust that this new APK is also good.

**Steps to reproduce**
1. Download and install Feb release of Organic Maps on Android.
2. Download March release of OM.
3. Install new release.
4. You are asked to install new app, not upgrade the existing app.

**Expected behaviour**
I would expect the app ID to match, so that Android can upgrade from the last version, instead of treating it as a new install.

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: 03-05
 - Device Model: Pixel 7

**Comment by djm2k** [comment]
Breaking change here (https://github.com/organicmaps/organicmaps/commit/7e9b4a52b330a16f1ac7876a22434c0ed7f2dff6), it was a bugfix as the appId was not previously set correctly for `release` apks.

As updating an APK to a different appId isn't supported, exporting the app config as a file would be an acceptable workaround to migrate user data to the "new" app

**Comment by djm2k** [comment]
I found the Export List option and was able to update to the latest version; using Obtainium and with my Lists intact, like so:

1. Open Bookmarks and Tracks menu, tap the context button and choose Export for each of your Lists. Create a new folder for them all as the import is by folder not file.
2. Take note of user settings, OSM Profile; then uninstall `app.organicmaps`. (I am assuming this deletes the downloaded maps when it deletes `/data/data/app.organicmaps`, I don't have root on my device)
3. Remove `app.organicmaps` from Obtainium and re-add `app.organicmaps.web` from https://github.com/organicmaps/organicmaps.
4. Open the latest Organic Maps, download your maps and login to OSM/configure settings.
5. Open Bookmarks and Tracks menu, tap Import and choose the folder created from before. This should bulk import all the `.kmz` files.
6. Delete the default `My Places` list and rename `My Places1` to `My Places`.

**Comment by PoorPocketsMcNewHold** [comment]
> Breaking change here (https://github.com/organicmaps/organicmaps/commit/7e9b4a52b330a16f1ac7876a22434c0ed7f2dff6), it was a bugfix as the appId was not previously set correctly for `release` apks.
> 
> As updating an APK to a different appId isn't supported, exporting the app config as a file would be an acceptable workaround to migrate user data to the "new" app:
> 
> >You still can update app A to suggest download and installation of app B, then app B will suggest uninstallation of app A. App A can even expose data for app B to allow migration.
> – [Shlomi Katriel](https://stackoverflow.com/users/11958566/shlomi-katriel) Sep 8, 2022 at 19:31
> https://stackoverflow.com/q/73650020

So, the release file were using the wrong ID since the **beginning** ?
If not, i'm failling to understand the need to change the id. It already exported the web suffix to the version number, no need to precise it in the app ID.

**Comment by djm2k** [comment]
> So, the release file were using the wrong ID since the **beginning** ? If not, i'm failling to understand the need to change the id. It already exported the web suffix to the version number, no need to precise it in the app ID.

I am no contributor, but that is my understanding yes.
It would be preferable to revert the app_id change for the release apk if possible.

**Comment by Grishnackh** [comment]
In my opinion a regular/minor update should not enforce a reinstallation of the app. Furthermore the app id `app.organicmaps` seems more generic and suitable for the Android version. Any chance to revert the app id for the mobile releases?

**Comment by topcaser** [comment]
> In my opinion a regular/minor update should not enforce a reinstallation of the app. Furthermore the app id `app.organicmaps` seems more generic and suitable for the Android version. Any chance to revert the app id for the mobile releases?

Totally agree

**Comment by biodranik** [comment]
The main reason for changing the id was the need to install web/standalone apk separately to other store versions. We should use a different id from the beginning, but there were no time/resources to do it properly earlier. Sorry for the inconvenience 🙏

**Comment by DireMunchkin** [comment]
OK fair enough. I'll close the issue if it was intentional.

**Comment by nep2ner** [comment]
> The main reason for changing the ID was the need to install web/standalone apk separately from other store versions. 

@biodranik just curious why the need to install them separately is there. Is there something different about the github release versus the app store releases?

**Comment by ThreeDeeJay** [comment]
Sometimes F-Droid apps use FOSS alternatives to Google services or just remove them altogether, like Goggle Play services location provider in [Osmand](https://forum.f-droid.org/t/status-of-location-provider-on-modern-android-versions/22882/3), but I'm also curious about the differences here besides signatures
Or is it just for devs to install all versions simultaneously for testing? 👀
