### ISSUE TITLE
Night mode text contrast similar to other objects 

### ISSUE THREAD

**Issue by ooosssay** [organicmaps/organicmaps#7525]
Text can become unreadable when text is over foot paths or roads. During night mode.

**Steps to reproduce**
1. Just find text that is over paths or roads

**Expected behaviour**
Have text to be more visible by changing contrasts

**Screenshots**
![IMG_5885](https://github.com/organicmaps/organicmaps/assets/129241633/81f08411-fced-42f2-ae9d-3a32cd6a3471)

**System information:**
 - iOS 17.2.1
 - Organic Maps version: ⁦2024.03.03-18⁩
 - Device Model: iPhone XR

**Comment by dvdmrtnz** [comment]
* It’s fixed in https://github.com/organicmaps/organicmaps/pull/7413


![IMG_4340](https://github.com/organicmaps/organicmaps/assets/47610359/51468a3f-cb44-44fc-b0f5-d00f03bb7764)

**Comment by ooosssay** [comment]
It seems that the contrast was increased but I think it's not enough for people with visual difficulties. For example in the image you provided the lowercased letters are (well I think) still a little difficult to read and, with the variability of Open Street Map, there can be a lot of information put in an area making the letters to difficult to understand understand. Therefore, I think I will mark this completed and then create a feature request to make an accessibility feature to add a background to text to make things easier to read (if not already made).

**Comment by fitojb** [comment]
Outlining the text would help, I think!
