### ISSUE TITLE
London train directions use 'XR' abbreviation for the renamed 'Elizabeth Line'

### ISSUE THREAD

**Issue by Jackalaq** [organicmaps/organicmaps#7531]
⚠ Have you searched for similar, already existing issues? Yes. Not found.

**Describe the issue**
London train directions use 'XR' abbreviation for the renamed 'Elizabeth Line'.  It used to be called CrossRail during the construction phase but is now called the Elizabeth line.  I suggest the 'Eliz' abbreviation is a space saving name is required.
OpenStreetMaps seems to use the name Elizabeth Line, but I don't know where the data is being drawn from.

**Steps to reproduce**
1. Search for a route that includes this line, e.g. to Custom House station
2. Chose directions and public transport
3. Look at bottom of screen for directions. XR appears but makes no sense

**Expected behaviour**
Up to date map data should be included

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**System information:**
 - Operating system and its version: [iOS 12, Android 10, Ubuntu 22, MacOS Big Sur, etc.]
 - Organic Maps version: [you can find it by tapping the button with the green Organic Maps logo]
 - Device Model: [e.g. iPhone 6, Samsung S22]

**Additional context**
Please add any other context or comments here that may be useful.

**Comment by biodranik** [comment]
@alexey-zakharenkov

**Comment by alexey-zakharenkov** [comment]
@Jackalaq,
**XR** is the value of the [ref=*](https://wiki.openstreetmap.org/wiki/Key:ref) tag of OSM route objects [(one of them)](https://www.openstreetmap.org/relation/14773909). Why do you think it's obsolete? On the https://www.nationalrail.co.uk/travel-information/operators/elizabeth-line/ page the line is called **Elizabeth line (XR)**. If not XR, what's the ref of the Elizabeth line then?

**Comment by RedAuburn** [comment]
closing as not an OM issue, instead a real-life issue 😅
