### ISSUE TITLE
Map view improvements: visibility and priority of features

### ISSUE THREAD

**Issue by j5k** [organicmaps/organicmaps#755]
Here some suggestions to improve the map view:

1. Waterfalls and caves are really not so important on this zoom level :wink: But some high mountains would be nice.
![Screenshot_20210627-113720_Organic_Maps](https://user-images.githubusercontent.com/12898013/123540102-948a4a80-d73d-11eb-911f-26d2191b59eb.png)

2. The same with small nature reserves and forests
![Screenshot_20210627-114212_Organic_Maps](https://user-images.githubusercontent.com/12898013/123540285-796c0a80-d73e-11eb-825b-afbcbf167228.png)

3. If you have many locality defined, it slays you at the sight. Maybe add more min spacing or what I would prefer: show in higher zoom level only.
![Screenshot_20210627-114342_Organic_Maps](https://user-images.githubusercontent.com/12898013/123540319-a5878b80-d73e-11eb-8222-9a963132c6a6.png)

4. Also private swimming pools are not of interest (should only visible as blue area without POI attitude)
![Screenshot_20210627-114018_Organic_Maps](https://user-images.githubusercontent.com/12898013/123540377-f13a3500-d73e-11eb-8c81-d45931806087.png)

5. At this zoom level I'm not interested in the little airfield, but more in important villages:
![Screenshot_20210627-113757_Organic_Maps](https://user-images.githubusercontent.com/12898013/123540545-d4eac800-d73f-11eb-9e1b-08acc42b6a9c.png)

**Comment by biodranik** [comment]
When you are traveling in New Zealand, Hawaii or similar places, it's very useful to see waterfalls, forest reserves, parks, villages or other interesting places on the otherwise empty map.

In my opinion, objects may be displayed on earlier zooms, if they are useful and if they are not bloating the map. For that, a more sophisticated approach is required than just "reduce visibility zoom level".

**Comment by vng** [comment]
I fixed 4 and 5 - is also the obvious bug.
1,2,3 - are not so obvious and need deep investigation. Of course, you screenshots are very densely filled, but other world areas are not so dense-mapped :) and other user sometimes wants to see waterfalls, peaks, caves earlier.

We need to invent some dynamic styles for this issues.

**Comment by pastk** [comment]
Cave icons were fixed in #6131

**Comment by pastk** [comment]
Eveything was fixed except the localities, which are better tracked separately in #6960
