### ISSUE TITLE
[ios] Isolines reminder is displayed on top of other dialogs

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7555]
https://github.com/organicmaps/organicmaps/assets/170263/46e89c44-afd3-4846-add5-0c0dafe0933a

**Comment by v-lozko** [comment]
Is this the behavior you're looking for?

https://github.com/organicmaps/organicmaps/assets/156805389/345fa191-0ec2-4090-83cc-ce076f2ebbfa

**Comment by biodranik** [comment]
Yes, that looks better.
