### ISSUE TITLE
Add bicycle pump amenity=compressed_air on the map and in the search

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7557]
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcompressed_air

Note that it can be a subtype of another main type.

Adding it to the editor is also a good idea.

**Comment by pastk** [comment]
It was added in https://github.com/organicmaps/organicmaps/pull/6397 everywhere except the editor.
Do you have some sample when it doesn't show up?

**Comment by biodranik** [comment]
@pastk it was reported by a user, I didn't check the map. Can it be added to the editor too?
