### ISSUE TITLE
[bookmarks] kml's lastModified field should be fully initialized before saving

### ISSUE THREAD

**Issue by kirylkaveryn** [organicmaps/organicmaps#7564]
This bug is related to the https://github.com/organicmaps/organicmaps/issues/3475

### Bug description
 The `lastModified` attribute is missed during the group importing process, leading to unexpected groups sorting.

When the user imports a new file from some other apps and we parse it to kml the `lastModified` is skipped if file's last modified date wasn't set:
```cpp
  if (categoryData.m_lastModified != Timestamp())
  {
    writer << indent << "<mwm:lastModified>" << TimestampToString(categoryData.m_lastModified)
           << "</mwm:lastModified>\n";
  }
```
<img width="1728" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/c3107dfd-e128-444d-94ab-f3c6a56ad431">

And only after that method `UpdateLastModifiedTime(*collection);` is called at the end of the importing process.
So this metadata will be skipped in kml file but will be valid in the in-memory object.
Example of the newly imported file where we can see the absence of that field:
```xml
  <name>2024-02-18-0129 2024-02-15-0101 Безымянный трек-3-7</name>
  <visibility>1</visibility>
  <ExtendedData xmlns:mwm="https://omaps.app">
    <mwm:name>
      <mwm:lang code="default">2024-02-18-0129 2024-02-15-0101 Безымянный трек-3-7</mwm:lang>
    </mwm:name>
    <mwm:annotation>
    </mwm:annotation>
    <mwm:description>
    </mwm:description>
                                            // < -- should be here
    <mwm:accessRules>Local</mwm:accessRules>
  </ExtendedData>
  <Placemark>
    <name>2024-02-15-0101 Безымянный трек-3</name>
    <Style><LineStyle
      <color>FFC76E00</color>
```
How to reproduce:
- import some categories from the non-OM app
- see it at the top of the bookmarks list (because in-memory lastModified was set properly)
- terminate app
- open app
- category will be at the bottom of the list (because there's no such field in the the kml)

https://github.com/organicmaps/organicmaps/assets/79797627/68670756-0e3a-442d-9a64-f51485506236

### Related conversations about how to fix: 
https://github.com/organicmaps/organicmaps/pull/7533#discussion_r1516862565

**Comment by biodranik** [comment]
@cyber-toad Can we provide a fix first, and write tests later? :)
