### ISSUE TITLE
[iOS] Weird icons edit page

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#7566]
I believe #7508 introduced new icons where it should not be changed. Icons are better than before, but I don't believe in the Opening Hours page it should have been modified.

Please close this issue if I'm wrong here.

CC @kirylkaveryn

![IMG_2553](https://github.com/organicmaps/organicmaps/assets/86851490/b7f3b170-15ad-4f4b-bd5e-40c35436a6b0)

**Comment by kirylkaveryn** [comment]
Thanks for your attention. I will fix it tomorrow!
