### ISSUE TITLE
[iOS] Delete Bookmark button wrong

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#7567]
Not sure when this started happening (probably this year, but don't remember in which release), as soon as you add a new bookmark, this is what happens: button becomes gold/highlighted and with a minus sign.

![IMG_2541](https://github.com/organicmaps/organicmaps/assets/86851490/530a97d7-333f-4bc3-b685-f912be1fa205)

But when you deselect and select the same bookmark again (or any other bookmark, if it's not a new one), the Delete button is not highlighted and it not with the minus anymore, making it "more difficult" to be delete it.

![IMG_2542](https://github.com/organicmaps/organicmaps/assets/86851490/18eb9edf-96fe-4777-bc9d-4209f61f6bf9)

Is this the intended behavior?

CC @kirylkaveryn

**Comment by biodranik** [comment]
Does it always reproduce? I can't reproduce it on some random POI.

**Comment by matheusgomesms** [comment]
I just opened OM, added no bookmarks, and selected randomly like 40-50 bookmarks. 100% of the cases it happened.

**Comment by biodranik** [comment]
Wow, that's a bug. Do you have the latest master build or production version? Selecting any bookmark should show that golden star to remove/delete the bookmark.

**Comment by kirylkaveryn** [comment]
Yes. This is a bug. :(
I can reproduce it sometimes on the iPhone 6 (iOS 12.5) (but not on the 11 Pro or simulators).
I'll try to find out where is the problem!

**Comment by matheusgomesms** [comment]
I have latest iOS and OM versions (no beta, just official releases). iPhone 14 Max here.

**Comment by biodranik** [comment]
@kirylkaveryn do you reproduce it in Debug? Or only in Release?

**Comment by Kopterlove** [comment]
This bug started in February, as I remember. And did it not every time, But in March release it happened 100% times. 
If choose old bookmark, it every time dark. 
If create new, and select first time - it yellow. Next time  - is dark.

**Comment by biodranik** [comment]
@matheusgomesms @Kopterlove what are your devices and iOS versions?

**Comment by matheusgomesms** [comment]
17.3.1, iPhone 14 Pro.

**Comment by Kopterlove** [comment]
17.4 13 pro and same on 17.3.1 on XR
