### ISSUE TITLE
How to make a from or to point that is not my devices actual location? I would like to plan a trip before I leave my home, but it seems that Organic Map will only create a to or from route from my device's "current location". I do not need navigation now, I just want to compare possible routes in advance. Thank You, 

### ISSUE THREAD

**Issue by JuniperJohn666** [organicmaps/organicmaps#7593]
### Discussed in https://github.com/orgs/organicmaps/discussions/4178

<div type='discussions-op-text'>

<sup>Originally posted by **biodranik** December 31, 2022</sup>
Please share how you are planning your trips now and what could help you to save time and make it very easy.
</div>

**Comment by biodranik** [comment]
Did you try to select any starting point on the map with a single or a long tap, and press "Route From" at the bottom, before selecting the finish point and selecting "Route To"?

I'm closing it, as it is a discussion question, not an issue.
