### ISSUE TITLE
[android] Unify all links in the same section

### ISSUE THREAD

**Issue by meenbeese** [organicmaps/organicmaps#7602]
⚠ Have you searched for similar, already existing issues?
Yes.

**Is your feature request related to a problem? Please describe.**
The Wikipedia button on Android looks out of place. It occupies prime real estate and is above more important info like opening hours, wheelchair info, and even the Wikipedia description itself.

**Describe the ideal solution**
The way it is done on iOS. Wikipedia's button should be moved together with the rest of the buttons. Given that there is already a `More...` button, the Wikipedia button being prioritized is unnecessary.

**Describe alternatives you have considered**
None.

**Additional context**
This is where I propose it should be moved, which is already how it is done on iOS.
![Screenshot_20240315_225357_Organic Maps_1_1.jpg](https://github.com/organicmaps/organicmaps/assets/114044633/2dc1c64c-6c9b-4dde-9750-b5556b49a9aa)

**Comment by pastk** [comment]
I agree it takes prime space unnecessarily, but it also served like akind of a "title" to the wiki article excerpt.
After the move it'll be hard to say where does the description come from.

And it might be more important to distinguish different "descriptions" when we have an OSM description displayed in the same PP together with wiki excerpt. And there could be yet another description coming from a bookmark! See 
- https://github.com/organicmaps/organicmaps/issues/1953#issuecomment-1355537956

Would be good to take in into account and make sure the design is future-proof.
