### ISSUE TITLE
[ios] Text trimming on the Menu screen on small screen

### ISSUE THREAD

**Issue by kirylkaveryn** [organicmaps/organicmaps#7605]
Text in the Menu screen cells can be trimmed on the small screen.

Simulator iPhone SE 1st gen iOS 15:
<img width="400" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/3913bc2a-4219-47e1-9fb5-3c9410c2ee61">

This issue happens because of the Menu cell layout issue: it contains an image pinned to the trailing but this image is usually invincible except in some situations. But in both cases, it takes some place and decrease Label's width which cause the trimming. 

<img width="445" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/16b3c5f5-f42c-4a58-ad90-7559603b2c9e">

### How to fix:
The trailing Image should have zero width when it is hidden, and standard width when it's visible.

<img width="402" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/e3e98ed6-98ad-4e34-8833-66e10d2058da">

**Comment by v-lozko** [comment]
Hi, can this issue be assigned to me? I'd like to work on it

**Comment by kirylkaveryn** [comment]
> Hi, can this issue be assigned to me? I'd like to work on it

Thanks for your attention!
You can start fixing this issue without assigning. Just follow the documentation (see Contribution), code style guidelines and make a PR!
