### ISSUE TITLE
When searching for 'Water', include `drinking_water:refill=yes`

### ISSUE THREAD

**Issue by pred2k** [organicmaps/organicmaps#7613]
**Is your feature request related to a problem? Please describe.**

When i want to stay hydrated, i want to avoid plastic bottles.
I use the **Water** category in Organic Maps to finde places, where i can refill my bottle.
There are initiatives that drive shops to offer Bottle refills like https://atiptap.org, https://refill-deutschland.de and more.
OSM has a tag for this https://wiki.openstreetmap.org/wiki/Key:drinking_water:refill

**Describe the ideal solution**

When searching with the **Water** category, i want shops to be shown up, where `drinking_water:refill=yes`.
To give the user infos, why this `shop=outdoor` is shown up as a water-source, we need to indicate that it offers Bottle refill. Maybe with a Bottle Icon or a short text.
Also show `drinking_water:refill:network=Refill Deutschland`, if present.

**Additional context**

Example Nodes:
* https://www.openstreetmap.org/node/4317229513
* https://www.openstreetmap.org/node/9609813799
* Alot in the UK https://overpass-turbo.eu/s/1IID

**Comment by pastk** [comment]
I think just converting `drinking_water:refill=yes` to `drinking_water=yes` should do the trick (these places will become searchable) 
(related to #7475)

Adding a refill network name display could be done later, if needed (it seems like information of quite limited/niche use).
