### ISSUE TITLE
[android] R8 string resources shrinker is not reliable?

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#7617]
Follow up to
- https://github.com/organicmaps/organicmaps/pull/7586

There are more strings used in core only which are dropped by R8 shrinker, e.g. 
```
// speed units in PP
kilometers_per_hour
miles_per_hour

// prob used when clicked on a ! in a built route
toll_road
unpaved_road
ferry_crossing

// various bookmarks sort methods (leads to crash)
week_ago_sorttype
month_ago_sorttype
moremonth_ago_sorttype
moreyear_ago_sorttype
near_me_sorttype
others_sorttype
food_places
tourist_places
museums
parks
swim_places
mountains
animals
hotels
buildings
money
shops
parkings
fuel_places
medicine
religious_places
```

There is a report of resources usage in files produced by android builds, e.g. `app/build/outputs/mapping/fdroidBeta/resources.txt` (check under `Unused resources are:`).
The problem is that not all aforementioned strings are listed as unused there, because e.g. all strings starting with `m` or `c` or some other letters are marked for inclusion somehow, e.g.
```
Marking string:moremonth_ago_sorttype:2132017637 used because it matches string pool constant m
Marking string:moreyear_ago_sorttype:2132017638 used because it matches string pool constant m
```
(e.g. a newly introduced rule to keep all `@category_*` strings de-facto does nothing because these strings are kept already just because they start with a `c` :)) )

R8 seems to use some black magic to derive which resources are better to keep "just in case", ref https://developer.android.com/build/shrink-code#strict-reference-checks

The issue is this "implicit keep list" might change unobviously anytime due to some seemingly unrelated changes in the code or constants, so its not reliable.

And the unused resources report list some other unused strings, which I find tedious to check all of them (its doable though) and decide whether we need to add them to the keep list explicitly..
```
 string:abc_action_bar_home_description:2132017160
 string:abc_action_menu_overflow_description:2132017162
 string:abc_activity_chooser_view_see_all:2132017164
 string:abc_activitychooserview_choose_application:2132017165
 string:abc_searchview_description_query:2132017180
 string:abc_shareactionprovider_share_with:2132017184
 string:abc_shareactionprovider_share_with_application:2132017185
 string:blue:2132017225
 string:blue_gray:2132017226
 string:brown:2132017255
 string:deep_orange:2132017337
 string:deep_purple:2132017338
 string:editor_report_problem_duplicate_place_title:2132017456
 string:editor_report_problem_under_construction_title:2132017461
 string:ferry_crossing:2132017521
 string:food_places:2132017522
 string:fuel_places:2132017525
 string:gray:2132017529
 string:green:2132017530
 string:hide_bottom_view_on_scroll_behavior:2132017533
 string:hotels:2132017535
 string:kilometers_per_hour:2132017546
 string:light_blue:2132017554
 string:lime:2132017555
 string:near_me_sorttype:2132017710
 string:orange:2132017728
 string:parkings:2132017738
 string:parks:2132017739
 string:pink:2132017748
 string:pref_about:2132017767
 string:pref_appearance_dark:2132017768
 string:pref_appearance_light:2132017769
 string:public_access:2132017831
 string:purple:2132017832
 string:shops:2132017871
 string:swim_places:2132017883
 string:teal:2132017886
 string:traffic_data_unavailable:2132017897
 string:traffic_update_app:2132017898
 string:traffic_update_maps_text:2132017899
 string:unpaved_road:2132019201
```

So one simple solution is to just keep ALL strings to be safe.

Another one is to carefully check and whitelist each string from the report (and maybe enable `tools:shrinkMode="strict"` afterwards).

Note that this issue potentially affects other resource types also.
E.g. there are unused drawables, layouts (@Jean-BaptisteC you might find it interesting to check).
Full list: [unused-resources-2024.03.17.txt](https://github.com/organicmaps/organicmaps/files/14628707/unused-resources-2024.03.17.txt)

So maybe
- check what are actual size savings of resources shrinking
- if its negligible then disable it altogether
- manually check and delete bigger unused/obsolete resources

**Comment by pastk** [comment]
@biodranik @rtsisyk @Jean-BaptisteC 
WDYT?

**Comment by biodranik** [comment]
Isn't R8 cleans up not only OM's but also other deps resources?

What is the right way to keep _all_ strings of OM (but clean up unused strings from other Android libs)?

**Comment by pastk** [comment]
There seems to be no way to keep all OM's strings while allowing to drop strings that came from deps (and I see only 7 strings out of 26 unused ones that come from the app compat lib for sure)..

The current build saves ~124KB via resources shrinking.
`Removed unused resources: Binary resource data reduced from 6369KB to 6245KB. Removed 1%`
E.g. I get an APK size of 48,425,083 (FDroid beta, arm64 only).
(compared 48,564,322 with shrinking disabled via `shrinkResources false` in build.gradle)

Keeping all strings via `tools:keep="@string/*"`:
`Removed unused resources: Binary resource data reduced from 6369KB to 6300KB. Removed 1%`
~57KB savings less which is pretty much consistent with an actual APK size increase of ~55KB (new size 48,483,388).


IMO these miniscule savings don't justify it.
I'd suggest at least to keep all strings.

Maybe all other resources too? (just to be safe, though there haven't been any issues so far).
