### ISSUE TITLE
[iOS][android] Note created without username

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#7627]
I searched for the open issues and didn't find a similar one:

[I created an OSM note](https://www.openstreetmap.org/note/4158868#map=19/-3.72807/-38.56661&layers=N) in Organic Maps (iPhone, latest App Store version), and when sent to OSM DB, the created note is not assigned to my username, but rather Anonymous.

I checked in Settings and I was logged in. I made another test, I logged out and logged in again. [Created a new note](https://www.openstreetmap.org/note/4158872), the same happened.

It's useful to have the note assigned to an user (if logged in), so one can keep track of the note and receive OSM messages.

**Comment by strump** [comment]
@biodranik  I tested notes with OAuth2 authentication - nota has username.
I think after full migration to OAuth2 the issue would be resolved.

**Comment by map-per** [comment]
If I understand the [wiki](https://wiki.openstreetmap.org/wiki/API_v0.6#Create_a_new_note:_POST_/api/0.6/notes) correctly a note is published anonymously if the OAuth token is invalid. So it might make sense `TestOSMUser` before uploading notes.

**Comment by map-per** [comment]
On [Notes Review](https://ent8r.github.io/NotesReview/?view=list&query=%23organicmaps&limit=100&status=all) you can see recent notes created with Organic Maps worldwide. Today, about 50% of the notes were anonymous.

**Comment by biodranik** [comment]
We need to somehow remind users to log in/register to OSM when they are leaving an anonymous note. @euf any ideas?

Another issue can be created by using OSM API to check if there are any replies to created comments. Can anonymous replies also be tracked by the same app that created an anonymous note? Let's define the UX for it.

**Comment by matheusgomesms** [comment]
> Can anonymous replies also be tracked by the same app that created an anonymous note?

AFAIK no.

> Another issue can be created by using OSM API to check if there are any replies to created comments.

That would be very handy!

**Comment by biodranik** [comment]
>> Can anonymous replies also be tracked by the same app that created an anonymous note?

> AFAIK no.

Does anonymous API return an ID of a created anonymous note? If yes, then it can be stored locally on a client, and client can check later if there are any responses.

**Comment by matheusgomesms** [comment]
Here's more detail about the Notes API: https://wiki.openstreetmap.org/wiki/API_v0.6#Map_Notes_API

**Comment by matheusgomesms** [comment]
I believe every note has an ID, so perhaps this is a solution.

> > > Can anonymous replies also be tracked by the same app that created an anonymous note?
> 
> > AFAIK no.
> 
> Does anonymous API return an ID of a created anonymous note? If yes, then it can be stored locally on a client, and client can check later if there are any responses.

**Comment by map-per** [comment]
I think it's better, and probably way easier, to only upload notes linked to a user account. A way to ensure this could be to check the validity of the OAuth token before every note upload (I think the `TestOSMUser` funktion in `server_notes.cpp` can be used for this). But we then have to make sure users are notified in case their OAuth token is not valid.

**Comment by biodranik** [comment]
By disabling anonymous notes the community misses users' feedback, and users miss the chance to contribute (and may be frustrated by forced login). And don't forget that OM has a privacy audience too. 

The soft power is to always remind unobtrusively to register when an anonymous note is sent.

**Comment by map-per** [comment]
But let's focus on the Bug here. Allowing anonymous notes would be a new feature.

With the current OM implementation you can only add notes when you are logged in, but due to the bug, anonymous notes are published even though the users are logged in.

(The same bug is also discussed in #1386)

**Comment by map-per** [comment]
I took a look at older notes form October 2023, and almost all of them are from logged in users. So most of the anonymous notes will probably disappear after the oAuth2 migration (see https://github.com/organicmaps/organicmaps/issues/7627#issuecomment-2006719168).

So the approach from https://github.com/organicmaps/organicmaps/issues/7627#issuecomment-2041573103 would probably only be needed to fix the occasional, but rare anonymous notes from #1386.

**Comment by habi** [comment]
I am also seeing anonymous notes created from my logged in Organic Maps version: ⁦2024.03.31-7⁩.

Im uploading a bunch of notes while traveling (without roaming), with very abbreviated notes that I intend to fix later on WiFi in the hotel. If the notes are anonymous, it's much harder to track them down later than if they would be linked to my account.

**Comment by biodranik** [comment]
@strump can you please take a look? Another user also complained.

**Comment by matheusgomesms** [comment]
Just tested with new release version (iOS), did the logout/login as asked, uploaded a note, and works fine again (note appears under my username). Not sure on Android if it's fixed as well, but it seems on iOS it works and issue could be closed (after confirming Android).

**Comment by biodranik** [comment]
Any volunteers to debug/reproduce it for Android?

**Comment by map-per** [comment]
On [Notes Review](https://ent8r.github.io/NotesReview/?view=list&query=%23organicmaps&limit=100&status=all) things look good for iOS and Android. All recent anonymous notes are from users with map data from older releases.

**Comment by matheusgomesms** [comment]
I think we can close this issue, seems fixed. Please feel free to reopen if not the case.
