### ISSUE TITLE
[ios] Allow to use the app while CarPlay is active

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#763]
At the moment, immediately after connecting the device to CarPlay, the app becomes unusable. Users can control only the CarPlay screen.
It's way more convenient to choose the final destination from the device than from the CarPlay screen.

**Comment by eisams** [comment]
Any updates on this?

I find it quite cumbersome to use due to this missing functionality, compared to Apple and Google Maps

**Comment by biodranik** [comment]
You're not alone. It requires a lot of work to refactor our graphics `Drape` engine. Android Auto needs it too.

@AndrewShkrob do we have a dedicated Drape refactoring issue to support more than one rendering screen?

**Comment by AndrewShkrob** [comment]
No, only this PR: https://github.com/organicmaps/organicmaps/pull/4080

**Comment by euf** [comment]
Yandex allows to switch between CarPlay and iPhone by providing an additional button on their screens when they are inactive. Personally I find this solution good enough, since it simply gives the user a possibility to swap preferred display on the fly without changing the renderer logic.

**Comment by biodranik** [comment]
Implementing screen switching also requires many efforts, and also worsens the UX.

**Comment by euf** [comment]
Screen switching may be worse UX than an ideal approach (supporting both screens simultaneously). At the same time, it would still be better than an actual state: while it's not possible to perform some tasks on a head unit, the screen switching now is done by manually disconnecting/reconnecting the phone cable. It makes sense to me to aim at a marginal improvement of this current issue as I believed it could be a low hanging fruit.

**Comment by MontakOleg** [comment]
I made a quick prototype with just calling the code that usually get called on CarPlay connect/disconnect events and it works surprisingly well. On video preview you can see almost all code changes 😄 

https://github.com/organicmaps/organicmaps/assets/1800899/c971eab2-6f9b-4a52-9c2c-2e88fd672cff

**Comment by biodranik** [comment]
@MontakOleg you're the hero! Where is the PR? :)

**Comment by mrpuzzler** [comment]
Need this too

**Comment by MontakOleg** [comment]
I will polish code a little bit and then send the PR
