### ISSUE TITLE
Rendering of leisure=garden + garden:type=residential + access=private

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#7636]
### Discussed in https://github.com/orgs/organicmaps/discussions/7635

<div type='discussions-op-text'>

<sup>Originally posted by **Dr-Mx** March 19, 2024</sup>
This is probably me going a bit crazy with micro-mapping as of late, however rendering of these residential gardens on Organic Maps can make public parks/gardens become rather indistinct. May I suggest to avoid rendering these or using a much lighter colour?

https://omaps.app/44IAxoezek
https://wiki.openstreetmap.org/wiki/Tag:garden:type=residential

Kind regards.</div>

**Comment by RedAuburn** [comment]
how about this?:
before/after

![render](https://github.com/organicmaps/organicmaps/assets/26939824/73a36297-b96d-4858-8ea8-e21d711ead21)

**Comment by Dr-Mx** [comment]
Great, this is what I envisioned when opening the discussion. Many thanks.

**Comment by biodranik** [comment]
Isn't it too light now, lighter than a grassland? Should "more green" mean "more trees"?

**Comment by pastk** [comment]
> Isn't it too light now, lighter than a grassland? Should "more green" mean "more trees"?

`leisure=garden` (residential esp.) could be just a plain lawn or a couple of garden beds w/ carrots and cabbage :)

**Comment by biodranik** [comment]
Agree.

How different/contrasting are parks, grass, and gardens in other maps?

**Comment by pastk** [comment]
- some screenshots and a related discussion https://github.com/organicmaps/organicmaps/pull/4758#issuecomment-1465121605
- my suggestion there https://github.com/organicmaps/organicmaps/pull/4758#issuecomment-1465235989
- related https://github.com/organicmaps/organicmaps/issues/5422
