### ISSUE TITLE
Wrong OSM wheelchair=* values uploaded by Editor

### ISSUE THREAD

**Issue by map-per** [organicmaps/organicmaps#7642]
OM appears to consistently use `wheelchair=wheelchair-yes`, `wheelchair=wheelchair-no` and `wheelchair=wheelchair-limited` instead of yes, no and limited. The bug appears on Android an IOS.

**Edit:** The bug didn't appear before the OM update in March

Examples:
https://www.openstreetmap.org/changeset/148780783   (2024.03.05-4-FDroid)
https://www.openstreetmap.org/changeset/148914689   (2024.03.18-5-Google)
https://www.openstreetmap.org/changeset/148563120   (2024.03.07 ios)

**Comment by biodranik** [comment]
@dvdmrtnz can you please try to debug the editor's code and see why it happens?

**Comment by map-per** [comment]
It is related to #7475 / commit 0dd0741. These [Lines](https://github.com/organicmaps/organicmaps/blob/0dd074194327cf003dd0d550facf71e1160c4b5b/indexer/feature_utils.cpp#L465-L470) probably cause the problem.

**Comment by mxxcon** [comment]
This still exist in 2024.03.31-8-Google https://osmcha.org/changesets/149593029

**Comment by RedAuburn** [comment]
fixed wrongly uploaded values in https://www.openstreetmap.org/changeset/149834198

**Comment by map-per** [comment]
>  will re-check in a couple of months just in case

Can you re run the tag replacement? Currently there are about 350 POIs with the wrong wheelchair values.

**Comment by RedAuburn** [comment]
re-run 👍️
