### ISSUE TITLE
search result for a street only highlights part of it

### ISSUE THREAD

**Issue by joachim-n** [organicmaps/organicmaps#7643]
**Describe the issue**

Searching for a street highlights that street in the map. However, only part of the street is highlighted.

**Steps to reproduce**
1. Go to Naples.
2.Search for 'via san liborio'
3. Only the bottom part of the street is highlighted in blue. If you scroll up, you can see the street continues but it's not been highlighted.

**Expected behaviour**

The whole street should be highlighted.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**System information:**
 - Operating system and its version: iOS 15.8
 - Organic Maps version: 2024.03.07-1
 - Device Model: iPad Air 2

**Additional context**
Please add any other context or comments here that may be useful.

**Comment by Jean-BaptisteC** [comment]
Duplicate #5897
