### ISSUE TITLE
bookmark categories now switch position

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#7645]
before, categories would keep their position. now they move around (not in a useful way like showing enabled ones at the top, either)
(built from latest master 7339f2503c06622418e202f0060034048e1a59f7)

https://github.com/organicmaps/organicmaps/assets/26939824/b2245c05-8ef9-462a-ad65-33f2f7b6699f

**Comment by biodranik** [comment]
This is a consequence of fixing the proper list sorting by their modification time #3475

The list visibility is stored in the kml file itself, so changing it updates the list modification date.

The good question is: does user expect that checking and unchecking counts as a modification?
Or maybe the expectation is to always show unchecked lists at the bottom, and checked lists at the top? Or lists should not change their order at all? Let's discuss it first.

@euf WDYT?

One of the possible solutions is avoiding updating the modification time of a list when it's shown or hidden. That can be complex though.

Another solution is to avoid immediate order change on the screen.

**Comment by RedAuburn** [comment]
> The list visibility is stored in the kml file itself

is this so they'll keep their visibility when exporting them? Maybe it'd be better to keep that in a separate index file which gets included in the export/import

**Comment by biodranik** [comment]
Imagine you're backing up all your bookmarks and they reset their visibility.

Force-enable visibility for one exported list may be a good idea.

Or keeping visibility separately, but also export it in the KMZ and then import it back.
