### ISSUE TITLE
Public transport route time estimation is inherited from any other neighbor option

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7647]
Tap to car route: ETA is 10 mins
Tap to public: 10 mins

Tap to walk route: 1 hr 40 mins
Tap to public again: 1 hr 40 mins

Tap to bicycle: 30 mins
Tap to public again: 30 mins

@kirylkaveryn can you please check it?

@Jean-BaptisteC does it reproduce on Android?

**Comment by Jean-BaptisteC** [comment]
Duplicate of #7509
