### ISSUE TITLE
The "show on map" button in search results is not recognisable enough

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#7650]
![image](https://github.com/organicmaps/organicmaps/assets/18434508/7189bdad-3981-41f4-81f1-33eda995a8e4)

There've been multiple occasions when users either don't notice this important button or don't recognize its function by its looks (and never try it!). 

We had a more descriptive and bigger text "View on map" button before #2081.
AFAIR the main idea was to make it smaller to fit more search results into the screen.

However discoverability of this button is much more important than fitting one extra result.

We should make the button easily discoverable and it should be very clear what does it do.
Maybe return to the text button? Or use a bigger and better icon?

**Comment by pastk** [comment]
Before #2081:

![image](https://github.com/organicmaps/organicmaps/assets/18434508/f03fecf4-6d1a-4267-bcfb-6fc2b6c1bc89)

**Comment by kavikhalique** [comment]
Having view on map written directly in text is much easy and convenient for users to understand in my opinion.

**Comment by biodranik** [comment]
Let's revert it back then? )
