### ISSUE TITLE
Wrong styling for "copy coordinates" popup in night mode.

### ISSUE THREAD

**Issue by Endem10n** [organicmaps/organicmaps#769]
**Wrong background and text color for night mode in "copy coordinates" popup.**

**Steps to reproduce:**
1.Switch on night mode in settings.
2.Select any object on the map.
3.Long press on object's coordinates text view at the bottom layout.

![Screenshot_1624924025](https://user-images.githubusercontent.com/86627724/123718124-a4f60e80-d87e-11eb-8964-ea58ab2a1bbe.png)
![Screenshot_1624924186](https://user-images.githubusercontent.com/86627724/123718157-b9d2a200-d87e-11eb-8910-296fe16723e1.png)

Reproduces on: api 25+.

**Comment by biodranik** [comment]
Should be fixed in the next release.
