### ISSUE TITLE
Post office icon changes after zooming the map

### ISSUE THREAD

**Issue by gtrus21** [organicmaps/organicmaps#770]
![Screenshot_20210629-113253](https://user-images.githubusercontent.com/69676792/123775866-6e001700-d8d7-11eb-89f9-6d31850b56d6.png)
![Screenshot_20210629-113245](https://user-images.githubusercontent.com/69676792/123775876-6fc9da80-d8d7-11eb-818a-80060b06d7bb.png)
Change Post icon at change zoom
56.144198, 47.212666

**Comment by geodavey** [comment]
Looks like this is due to the mapcss styles:

https://github.com/organicmaps/organicmaps/blob/99c5b878a048b467d1c66cf5a5ff0ce04975c73b/data/styles/clear/include/Icons.mapcss#L2146-L2151

Maybe should be:

```
 node|z17[amenity=post_office] 
 {icon-image: mail-m.svg;} 
 node|z18-[amenity=post_office]
 {font-size: 11;text-optional: true;}
 node|z18-[amenity=post_box], 
 area|z18-[amenity=post_box] 
 {icon-image: postbox-m.svg;font-size: 11;text-optional: true;}
```

**Comment by biodranik** [comment]
Let's create a branch and try it! :)
