### ISSUE TITLE
CSV Bookmarks import/export

### ISSUE THREAD

**Issue by xplosionmind** [organicmaps/organicmaps#7706]
**Is your feature request related to a problem? Please describe.**
Recently implemented bookmark importing and exporting uses a very specific file format, compatible only with a limited set of apps.

**Describe the ideal solution**
Being able to use a more common plain text format, such as CSV.

**Describe alternatives you have considered**
- Manually add bookmarks by coping them from KML file
- Manually edit KML files sources

**Additional information**
One great use case is to use those CSV for [uMap](https://umap-project.org/) integration.

**Related issues**
#622 and #1082

**Comment by xplosionmind** [comment]
Hi @biodranik! Thanks for your reply, and sorry for getting back to this quite late.

> CSV is not a standard format for geo data. What are the pros of developing it?

As I also mentioned in the issue concerning uMap, importing/exporting CSV files would help interoperability with non-mapping-focused software. For example, I am using [a CSV file](https://codeberg.org/tommi/tommi.space/src/branch/main/data/places.csv) to list my favorite places with custom extra data, and the file is parsed by [Eleventy](https://11ty.dev) on my website.

**Comment by biodranik** [comment]
I would suggest writing a generic KML => CSV converter then. It will work not only with OM data, but with many other apps that produce KML.
