### ISSUE TITLE
Bookmark description input text field doesn't work

### ISSUE THREAD

**Issue by map-per** [organicmaps/organicmaps#7720]
Since recently the bookmark description text field  doesn't work any more. If you write longer text a few lines at the bottom of the text become uneditable, as scroling down is not possible. I think the problem started with the update in February.

|  |  |
|--------|--------|
| ![Screenshot_2024-03-28-19-52-28-860_app organicmaps beta](https://github.com/organicmaps/organicmaps/assets/79519062/623fe909-1ab8-4d98-8573-0c4c2472b669) | ![Screenshot_2024-03-28-19-52-13-302_app organicmaps beta](https://github.com/organicmaps/organicmaps/assets/79519062/a20c01cd-fac0-4892-bc08-9faabb381641) | 
| Full text | Fhe entire 2. section is not visible and scrolling down is not possible |

Devices: 
- Pocophone F1, Android 10, OrganicMaps 2024.03.27-3-Google 
- Samsung S5 mini, Android 6.0.1, OrganicMaps 2024.03.27-3-Google

**Comment by map-per** [comment]
Could this be related to #7267 or #7280?

**Comment by map-per** [comment]
It would be nice to fix this for the next release, I've got a few bookmarks where I would like to change the text at the bottom...

**Comment by biodranik** [comment]
> Could this be related to https://github.com/organicmaps/organicmaps/pull/7267 or https://github.com/organicmaps/organicmaps/pull/7280?

You can try to revert those and test if it helps. Or better check solutions here: https://stackoverflow.com/questions/6765534/android-soft-keyboard-resize-layout

And read docs here: https://developer.android.com/develop/ui/views/touch-and-input/keyboard-input/visibility
