### ISSUE TITLE
Activate GPS with one click 

### ISSUE THREAD

**Issue by map-per** [organicmaps/organicmaps#7727]
#### Current Behaviour
When you start the location search although GPS is deactivated in the system settings, OM shows a pop up and redirects users to the system settings.

#### With SettingsClient
The SettingsClient interface allows showing a pop up where users can activate the GPS with one click on "ok". This is e.g. used in Google Maps:

<img src="https://github.com/organicmaps/organicmaps/assets/79519062/27337511-36f4-476f-9e77-e12b92a35a52" width="250" />

#### Google documentation

https://developer.android.com/develop/sensors-and-location/location/change-location-settings

https://developers.google.com/android/reference/com/google/android/gms/location/SettingsClient

**Comment by Jean-BaptisteC** [comment]
That's the case when you use Google Play Services option

**Comment by map-per** [comment]
Oh no, that would have been cool...
