### ISSUE TITLE
"bicycle shop" matches amenity=bicycle_parking

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#7730]
⚠ Have you searched for similar, already existing issues?

yes

#5251 is closest I found but is distinct problem

**Describe the issue**
"bicycle shop" matches `amenity=bicycle_parking`

**Steps to reproduce**
1. Go to search
2. Type `bicycle shop`
3. Wait loooooong time for search to complete as usual 
4. Switch to map view

**Expected behaviour**
"bicycle shop" search does not highlight `amenity=bicycle_parking` objects

**Screenshots**
I can add if it is really needed and not replicable

**System information:**
 - Operating system and its version: Android 10
 - Organic Maps version: 2024.03.27-3-Google
 - Device Model: Xiaomi Mi A2 Lite

**Additional context**
Please add any other context or comments here that may be useful.

I mapped bicycle parkings quite thoroughly in my area, so this bug utterly breaks this search case for me.

**Comment by Misalf-git** [comment]
I think the system's locale can affect search results.

When I search for `bicycle shop`, OM doesn't find a single `bicycle parking`, but only shops, as expected.

When I search for `bicycle`, the search takes longer and finds `bicycle shop`s and `bicycle parking`s, still expected.

My system's language is set to German. Same result when (closing OM completely, then) changing to English.

**Comment by matkoniecz** [comment]
I have it set to English.

**Comment by vng** [comment]
Also depends on the concrete viewport. If you have no shops in a viewport, partial matching may occur.
Could you please share the search viewport?

**Comment by matkoniecz** [comment]
and now I cannot reproduce it

will reopen if able to reproduce
