### ISSUE TITLE
Rename Alpine Lodging (tourism-alpine_hut) into Serviced or Managed Hut

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#7732]
The [`tourism=alpine_hut`](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dalpine_hut) tag name is misleading because by wiki's description its not necessary limited to alpine environment.
The biggest difference from [`tourism=wilderness_hut`](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dwilderness_hut) is a level of service: alpine_huts are supposed to be staffed and better serviced, while wilderness_huts are unserviced.

It also means that the "alpine huts are more isolated and hence should be more visible on map" logic doesn't apply (see https://github.com/organicmaps/organicmaps/pull/6112) - both alpine and wilderness huts should have same visibility IMO.

In OM `alpine_hut` is translated as "Alpine Lodging" now, `wilderness_hut` is "Wilderness Hut".
I suggest to rename alpine huts to "Serviced Wilderness Hut" or maybe "Managed Wilderness Hut".

I think we should change [`tourism=chalet`](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dchalet) from "Chalet" to a "Holiday Cottage" also.

**Comment by pastk** [comment]
FYI @map-per @matkoniecz

**Comment by map-per** [comment]
LGTM 
Adding "Wilderness" as well is a good idea, so people will, in compliance with the wiki, only use it for remote locations.

**Comment by matkoniecz** [comment]
not entirely sure why I was pinged but...

> It also means that the "alpine huts are more isolated and hence should be more visible on map" logic doesn't apply (see https://github.com/organicmaps/organicmaps/pull/6112) - both alpine and wilderness huts should have same visibility IMO.

it makes sense to render both relatively early

**Comment by pastk** [comment]
Actually looking closer into https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dalpine_hut and https://wiki.openstreetmap.org/wiki/Proposal_talk:Wilderness_mountain_buildings alpine_hut description is limited to "mountains" indeed (which doesn't make sense IMO and leaves the serviced lowlands huts category not covered, but its the actual thing).

So probably better to rename alpine_hut to "Mountain Lodge" (just like in iD), which will put it closer to a kind of mountain hotel (which was the original idea behind this tag).

**Comment by matkoniecz** [comment]
> leaves the serviced lowlands huts category not covered

is it covered by hostels/chalets?

**Comment by pastk** [comment]
> > leaves the serviced lowlands huts category not covered
> 
> is it covered by hostels/chalets?

I won't say so:
- hostels are not isolated / back country
- chalets are separate houses, not a common space with bunk beds

**Comment by pastk** [comment]
A side-note, there is a [`amenity=shelter shelter_type=basic_hut`](https://wiki.openstreetmap.org/wiki/Tag:shelter_type%3Dbasic_hut) also. IMO its better to "merge" it into wilderness_hut instead of leaving under "shelter" in OM. Its 7k uses only so far.

**Comment by matkoniecz** [comment]
> hostels are not isolated / back country

Why not? (note, I am not  a native speaker - but I would see nothing blocking hotel/hostel from operating in remote location)
