### ISSUE TITLE
Text in the editors name field invisible

### ISSUE THREAD

**Issue by map-per** [organicmaps/organicmaps#7739]
1. In the current [FDroid Beta](https://github.com/organicmaps/organicmaps/actions/runs/8482316770) version from the master branch the text in the editors name field is invisible.
(When you copy the name you can see that it is the right name, so it's just invisible)

2. The first line of the opening_hours is missing

In Bug doesn't appear in the 2024.03.27-3 Google Playstore version 

|  |  |
|--------|--------|
| ![Screenshot_2024-03-30-10-05-58-613_app organicmaps debug](https://github.com/organicmaps/organicmaps/assets/79519062/97393776-1726-41db-a656-29a9622c1c5c) | ![Screenshot_2024-03-30-09-39-37-342_app organicmaps beta](https://github.com/organicmaps/organicmaps/assets/79519062/d13dd0a7-9264-4675-97fc-5df5129eb220) | 

_Example location: https://www.openstreetmap.org/node/319137702_

**Comment by pastk** [comment]
I can reproduce it on a fresh master build too (Android 9, F-Droid).

**Comment by Jean-BaptisteC** [comment]
I think, it's caused by this https://github.com/organicmaps/organicmaps/pull/7721

**Comment by gpesquero** [comment]
> I think, it's caused by this #7721

I've launched https://github.com/organicmaps/organicmaps/pull/7742 to revert PR #7721.
