### ISSUE TITLE
New support emails on iOS are created with Apple Mail even when the default mail app is set to a different provider

### ISSUE THREAD

**Issue by tobiaalberti** [organicmaps/organicmaps#7758]
**Describe the issue**
Tapping the email button in the "Follow and contact us" section of Organic Maps' about page creates a new support email with Apple Mail even when the default mail app is set to a different provider via iOS' settings.

**Describe the ideal solution**
As is the case when tapping email addresses in other parts of the app (store's details pages, for instance) the new email should be created with the default mail app.

**App version**
2024.03.07-1

**Comment by Jean-BaptisteC** [comment]
Which is your version of Organic Maps
We have already doing a fix #3327

**Comment by biodranik** [comment]
@tobiaalberti what is your other email app that is not open by default?

**Comment by biodranik** [comment]
Thanks! @kirylkaveryn can you please take a look?

**Comment by v-lozko** [comment]
Can i take a stab at this?

**Comment by biodranik** [comment]
Don't ask, do it! )

**Comment by v-lozko** [comment]
So the way it seems to be working is if you want to allow use of a different, default, email app then it will always open the app to create the email. So it seems like there are two choices:
1. Use the in-app apple mail first (where it pops up inside the omaps app) if available then try the default email
or 
2. always use the default app, and in the case where it is apple mail it will open the app, and not in app

**Comment by biodranik** [comment]
@v-lozko does (1) solve the issue? (2) sounds reasonable, no?

**Comment by v-lozko** [comment]
@tobiaalberti, that does seem to be the case. And 2 does sound reasonable to me

**Comment by kirylkaveryn** [comment]
I think that 2d solution is better. 
Is only needs to build a link using format:
`mailto:someone@example.com?subject=Your%20Subject&body=Your%20Message`

And if UIApplication.canopenUrl fails we can use native mail composer.

**Comment by v-lozko** [comment]
I created this PR:

https://github.com/organicmaps/organicmaps/pull/7862
