### ISSUE TITLE
[Editor] Upload opening hours failed when feature was edited online in OSM

### ISSUE THREAD

**Issue by gtrus21** [organicmaps/organicmaps#7794]
Adding opening hours at the store "Охотник" failed
 (52°02′21.5″N, 47°47′03.06″E)

A [feature](https://www.openstreetmap.org/way/424797407) with shop=hunting was generated in OM. Then it was edited in OSM by adding building=yes, that lead to the following error during uploading:

Version 2024.03.27-3-Google

![IMG_20240403_150901_578](https://github.com/organicmaps/organicmaps/assets/69676792/090f159d-69ff-4a72-bd22-a9dc462765d9)

**Comment by map-per** [comment]
I don't understand what happened here: The `shop=hunging` tag of this [way](https://www.openstreetmap.org/way/424797407) was added 7 years ago?! Can you share a link to the original OM changeset that added the shop?

**Comment by gtrus21** [comment]
No, as far as I remember, I just tried to add running time.  But the change did not happen

**Comment by gtrus21** [comment]
How share changeset?

**Comment by map-per** [comment]
Ok, I think I now understand what happened: There was a shop area in OSM, then someone added `building=yes` to it and then your edit of `opening_hours` in OM failed.

So the shop=hunting was **not** "generated in OM", but added with other OSM tools.

**Comment by gtrus21** [comment]
For such cases, notification is required if the edit is unsuccessful.  And the data from the unsuccessful edit (in this case, the operating time) should be indicated by an exclamation point, indicating that this operating time was saved only on this phone

**Comment by map-per** [comment]
Yes, secretly failing is not good

**Comment by map-per** [comment]
This appears to be the same issue as #6727, so this duplicate issue can be closed

**Comment by map-per** [comment]
Duplicate of #6727
