### ISSUE TITLE
Street name in local language is missing in UI

### ISSUE THREAD

**Issue by alnzrv** [organicmaps/organicmaps#7795]
**Describe the issue**
Street name in local language doesn't appear anymore.

**Steps to reproduce**
1. Go to search
2. Search '37°32′20.77″N, 126°56′26.25″E' and click on the road.
3. Verify that street name in Korean is not displayed.

**Expected behaviour**
Local street name should appear below the translated name. User should be able to copy it.

**Screenshots**

<details>
<summary>2024.03.27-3-Google</summary>
<p>
<img src='https://github.com/organicmaps/organicmaps/assets/7187657/c3fa297a-4dc6-44d7-ba40-651f6ad974db'>
<img src='https://github.com/organicmaps/organicmaps/assets/7187657/5bc967f1-c987-46d0-85db-a75ed9cad9f8'>
</p>
</details> 

<details>
<summary>2023.09.22-27-FDroid</summary>
<p>
<img src='https://github.com/organicmaps/organicmaps/assets/7187657/c6467a1e-850c-4632-a432-35f3f9fe4889'>
<img src='https://github.com/organicmaps/organicmaps/assets/7187657/af3f9a0c-2efb-426d-99d4-ab8931fe6264'>
</p>
</details>

**Comment by biodranik** [comment]
@dvdmrtnz @RedAuburn can you please take a look?
