### ISSUE TITLE
quarry displays too late

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#7826]
quarry at 55.981389, -2.458731 only displays on very high zoom

currently starts displaying on <z14. need to make it display at same level as farmland

**Comment by RedAuburn** [comment]
this is the case for industrial landuse generally

**Comment by pastk** [comment]
> this is the case for industrial landuse generally

and many other areas, e.g. even big university and hospital grounds are displayed from z14 only.

- related #2856

**Comment by RedAuburn** [comment]
closing as dup of https://github.com/organicmaps/organicmaps/issues/2856
