### ISSUE TITLE
Christmas Tree Showing in April

### ISSUE THREAD

**Issue by louwers** [organicmaps/organicmaps#7829]
⚠ Have you searched for similar, already existing issues?
Yes there is https://github.com/organicmaps/organicmaps/issues/4222 which is about opting out of holiday themes altogether.

**Describe the issue**
For me the Christmas tree is still showing in the menu bar. Even after updating Organic Maps to the latest version and downloading new maps.

**Steps to reproduce**
I presume can only be reproduced during the holidays, when the server is sending the settings with `isNY` set to `true` over the wire. For me, it never changed back afterwards.

**Expected behaviour**
The Christmas tree is only shown on Christmas day.

**Screenshots**
![image](https://github.com/organicmaps/organicmaps/assets/649392/28b203f1-289d-4088-8c74-83e433eace43)

**System information:**
 - Operating system and its version: iOS 17
 - Organic Maps version: 2024.03.31-7
 - Device Model: iPhone 13 Pro

**Additional context**
I suggest that instead of using the settings for this, a run time check for the date is added. Not sure if this should be added to the core in C++ or if each platform should have its own implementation.

**Comment by biodranik** [comment]
Did you restart the app after updating maps?

**Comment by louwers** [comment]
I did not. Christmas tree is finally gone now!

Feel free to close if you think this is not a worthwile change.

**Comment by kaoneko** [comment]
Wait, what? You have to update the maps to get rid of the Christmas tree?! 🤯 What a very strange design! I've been wondering about that Christmas tree for months...

**Comment by kaoneko** [comment]
You misunderstand, I was always on the latest version.
