### ISSUE TITLE
Handle plus code in GeoURI query: `geo:0,0?q=87G7MXQ4+M5`

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#7837]
Currently, the `+` is interpreted as space, even if escaped with `\+` or the query is encased in quotes.
gmaps fails in the same way, but this is technically a valid use so it makes sense to fix it.

would be good to add as test case to https://omaps.app/test too. (would add but page isn't in site repo, https://github.com/organicmaps/organicmaps.github.io/issues/227)

**Comment by biodranik** [comment]
@RedAuburn https://github.com/organicmaps/url-processor/blob/master/public/test.html

**Comment by RedAuburn** [comment]
https://developer.android.com/guide/components/intents-common#Maps

more useful test cases, will add some tomorrow to page 👍️

**Comment by RedAuburn** [comment]
> Note: All strings passed in the geo URI must be encoded. For example, the string 1st & Pike, Seattle becomes 1st%20%26%20Pike%2C%20Seattle. Spaces in the string are encoded with %20 or replaced with the plus sign (+).
