### ISSUE TITLE
Re-routing does not work in CarPlay as of version 2024.03.31-7⁩

### ISSUE THREAD

**Issue by Motorblade** [organicmaps/organicmaps#7840]
**Describe the issue**
As of the latest version ⁦(2024.03.31-7⁩), re-routing does not work in Apple CarPlay. Failing to take an instructed turn will simply cause the routing to freeze at the missed turn rather than finding a new route. Even if you return to the original route, it will not provide navigation and continue displaying the missed turn.

**Steps to reproduce**
1. Set a route in CarPlay.
2. Miss a turn or take an alternate route.
3. The navigation will hang on the missed turn, rather than finding a new route.

**Expected behaviour**
The navigation should find a new route when a turn is missed, like it did in previous versions..

**System information:**
 - Operating system and its version: iOS 12
 - Organic Maps version: ⁦2024.03.31-7⁩
 - Device Model: iPhone 13

**Comment by biodranik** [comment]
Does it depend on the route length or the location where the route goes? E.g. does rerouting work for short routes?

**Comment by Motorblade** [comment]
I haven’t been able to test it on a short route yet, but I noticed the issue on a route that was about 2 hours long. It happened consistently on that route even after restarting the app to manually re-route.

**Comment by biodranik** [comment]
Long route recalculations take some time. Please also check if you have the same issue without using CarPlay.

**Comment by Motorblade** [comment]
After the first few days of having that update installed, I haven't had any issues with rerouting. Should I close the issue?
