### ISSUE TITLE
Real RTL Support in Setting Menu UI

### ISSUE THREAD

**Issue by mohdalyahri** [organicmaps/organicmaps#7863]
**Describe the issue**
You just need the settings interface to switch the mirroring from right to left as shown in the image below.

![image](https://github.com/organicmaps/organicmaps/assets/30707693/253ac327-e3da-42d1-8f1b-fd3361c87b98)

NOW IT'S LIKE THIS

![image](https://github.com/organicmaps/organicmaps/assets/30707693/90fc5631-a2ef-487a-ba22-debc8fd0941d)

**System information:**
 - IOS 17.5
 - Organic Maps version: ⁦2024.03.31-7⁩
 - Device Model: iPhone 13 Pro Max

**Comment by biodranik** [comment]
@dvdmrtnz can you please take a look?
