### ISSUE TITLE
[ios] Import kml/kmz/gpx files into the app using the default File manager

### ISSUE THREAD

**Issue by kirylkaveryn** [organicmaps/organicmaps#7866]
Implement the kml/kmz/gpx files importing using the [UIDocumentPickerViewController](https://developer.apple.com/documentation/uikit/uidocumentpickerviewcontroller).

This feature will allow users to add files using the Files app.

![image](https://github.com/organicmaps/organicmaps/assets/79797627/891a42b1-069e-4896-a7b2-5f2fe40963e6)

**Comment by kirylkaveryn** [comment]
> Hello, I was looking at this and just had a question, where is the import button?


The possible place to this button is between the `Create new list` and `Export all`:
![image](https://github.com/organicmaps/organicmaps/assets/79797627/5c2eedc8-1725-4d8e-b939-18b2d4c4c50a)

But these buttons may be placed in the other place in future (top-right menu button in the nav bar as an example) - but it is not part of this PR.


> Also, i think found another minor issue. When pressing 'more' in a specific list the menu pops up in bottom left vs the bottom right above 'more'. if you or @biodranik want to open an issue related to this I'd gladly take a look at it.

Thanks! Please feel free to open this new issue and fix it.

**Comment by kirylkaveryn** [comment]
@biodranik @rtsisyk @oleg-rswll 

Here is the how it can look:
https://github.com/organicmaps/organicmaps/assets/79797627/147f046e-ccb4-40b1-be25-c7ea23a0d1f9

To implement a feature and create a PR its needed to:
1. handle the multiple import of the files. The current implentatiom adds multiple result alerts in the stack that looks bad. 
Possible solution (**requires design**):
   - create new method on cpp that will handle multiple files and returns the composed result.
2. design a new icon @euf can you halp please?
3. strings and localization

**Comment by biodranik** [comment]
@kirylkaveryn is it obvious/easy to change/choose a different directory with bookmarks in this multi-selection mode, if necessary?

A good start is to implement it as is, with multiple alerts, and existing icon from Android/Material.

Existing translation `[bookmarks_import]` `Import Bookmarks and Tracks` can be reused.

Then maybe @euf can help with a better icon, and we can brainstorm a better UX for reporting import success/failures for many imported files.

**Comment by kirylkaveryn** [comment]
> is it obvious/easy to change/choose a different directory with bookmarks in this multi-selection mode, if necessary?

With UIDocumentPicker any directory (as in the Files app) can be selected.

> A good start is to implement it as is, with multiple alerts, and existing icon from Android/Material.

Ok!
