### ISSUE TITLE
Add shop=kiosk to the OSM editor

### ISSUE THREAD

**Issue by Interactiondesigner** [organicmaps/organicmaps#7887]
It would be nice, if the object shop=kiosk would be available in the editor for OpenStreetMap. Kiosks are different from a small shop or convenience store and in many cases don't have an indoor area but e.g. have a counter facing the street.

https://wiki.openstreetmap.org/wiki/Tag:shop%3Dkiosk

**Comment by Misalf-git** [comment]
- https://github.com/organicmaps/organicmaps/issues/1005#issuecomment-907584738

**Comment by Misalf-git** [comment]
- #7709

**Comment by pastk** [comment]
It was added already in https://github.com/organicmaps/organicmaps/pull/7709
Will show up in the next release.
