### ISSUE TITLE
integration with https://www.eway.in.ua/en/api

### ISSUE THREAD

**Issue by soredake** [organicmaps/organicmaps#790]
Would be nice to have it for integration with ukraine public transport.

**Comment by dikkechill** [comment]
OrganicMaps has _experimental_ support for [GTFS based feeds](https://gtfs.org/). External API's are currently not supported. 
Do you know whether Eway provides a GTFS based public transport feed?

**Comment by soredake** [comment]
> Do you know whether Eway provides a GTFS based public transport feed?

I don't think they provide data in this format.

**Comment by biodranik** [comment]
Please see #5331

**Comment by biodranik** [comment]
Can this data be converted to a GTFS feed format?
