### ISSUE TITLE
Organic Maps not starting on Linux Mint 

### ISSUE THREAD

**Issue by brianmoeller** [organicmaps/organicmaps#7912]
Hi

After installing Organic Maps on Linux Mint nothing happens when trying to start the application. There are no error messages, and install apparently went ok.

Is this a know issue?

Yours sincerely  Brian Møller

**Comment by biodranik** [comment]
All important details are missing :)

**Comment by pastk** [comment]
@brianmoeller please provide more details,
e.g. how did you install it (e.g. flatpak or built yourself?), OS version, log output when started from the terminal..

**Comment by Ferenc-** [comment]
Closing as inactive and non-reproducible.
