### ISSUE TITLE
Route To Automatically Select Subway Option Problem

### ISSUE THREAD

**Issue by Birc-ftc** [organicmaps/organicmaps#7935]
Hi. İs there a solution for this? I need to select automatically driving. 

**Describe the issue**
Route To Automatically Select Subway Option Problem

**Expected behaviour**
Select automatically driving. 

**System information:**
 - Operating system and its version: [Android]
 - Organic Maps version: [2024. 03.31-8 Fdroid]
 - Device Model: [Xiaomi 11T]

**Comment by biodranik** [comment]
Did you turn off the Subway layer on the top left corner of the map? Turn it off.

**Comment by Birc-ftc** [comment]
> Did you turn off the Subway layer on the top left corner of the map? Turn it off.

Thanks. Worked.
