### ISSUE TITLE
Show POIs on map, not in the list

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#7936]
For some reason when searching I need to tap one extra button to see results on the map.

Why not show it on the map? I understand that some people are confused by maps by they seem unlikely to be using map app.

Maybe doing like Google maps (mini map + list) would be even better?

**Comment by biodranik** [comment]
Did you search for existing issues? I remember that @oleg-PK has already raised this question: to show both the list + result on the map.

**Comment by matkoniecz** [comment]
I tried, will retry again.

"Improve search results (list & map)" #6442 sounds like this but is actually about different thing.

https://github.com/organicmaps/organicmaps/issues/created_by/oleg-PK found #5675
