### ISSUE TITLE
release 2023-03-31-8 can't compile with Mesa due to Vulkan problem

### ISSUE THREAD

**Issue by Popolon** [organicmaps/organicmaps#7938]
⚠ Have you searched for similar, already existing issues?

yes

**Describe the issue**
Please write a clear and concise description of the issue here.

compilation fail with OrganicMaps 2023-03-31-8 with standard Mesa on Arch Linux, 

**Steps to reproduce**
1. compile
2. following error is returned:
<pre>
[49/99] Building CXX object drape/CMakeFiles/drape.dir/Unity/unity_1_cxx.cxx.o
FAILED: drape/CMakeFiles/drape.dir/Unity/unity_1_cxx.cxx.o 
/usr/bin/ccache /usr/bin/ccache /usr/bin/c++ -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_POSITIONING_LIB -DRELEASE -DUSE_FILE32API -I/data/pacaur/organicmaps-git/src/organicmaps-git -I/data/pacaur/organicmaps-git/src/omim-build-release/3party/gflags/include -I/data/pacaur/organicmaps-git/src/organicmaps-git/3party/glm -I/data/pacaur/organicmaps-git/src/organicmaps-git/3party/opening_hours/. -I/data/pacaur/organicmaps-git/src/organicmaps-git/3party/pugixml/pugixml/src -I/data/pacaur/organicmaps-git/src/organicmaps-git/3party/utfcpp/source -I/data/pacaur/organicmaps-git/src/organicmaps-git/3party/expat/expat/lib -I/data/pacaur/organicmaps-git/src/omim-build-release/3party/expat/expat -I/data/pacaur/organicmaps-git/src/omim-build-release/3party/jansson/jansson/include -I/data/pacaur/organicmaps-git/src/organicmaps-git/3party/liboauthcpp/include -I/data/pacaur/organicmaps-git/src/organicmaps-git/3party/protobuf/protobuf/src -I/data/pacaur/organicmaps-git/src/organicmaps-git/3party/vulkan_wrapper/../Vulkan-Headers/include -I/data/pacaur/organicmaps-git/src/organicmaps-git/3party/vulkan_wrapper/. -isystem /data/pacaur/organicmaps-git/src/organicmaps-git/3party/boost -isystem /usr/include/qt6/QtCore -isystem /usr/include/qt6 -isystem /usr/lib/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtNetwork -isystem /usr/include/qt6/QtPositioning -isystem /usr/include/freetype2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Wno-error=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -O3 -DNDEBUG -std=c++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -ffast-math -Ofast -Wall -Wextra -Wpedantic -Wno-unused-parameter -mno-direct-extern-access -MD -MT drape/CMakeFiles/drape.dir/Unity/unity_1_cxx.cxx.o -MF drape/CMakeFiles/drape.dir/Unity/unity_1_cxx.cxx.o.d -o drape/CMakeFiles/drape.dir/Unity/unity_1_cxx.cxx.o -c /data/pacaur/organicmaps-git/src/omim-build-release/drape/CMakeFiles/drape.dir/Unity/unity_1_cxx.cxx
In file included from /data/pacaur/organicmaps-git/src/omim-build-release/drape/CMakeFiles/drape.dir/Unity/unity_1_cxx.cxx:19:
/data/pacaur/organicmaps-git/src/organicmaps-git/drape/vulkan/vulkan_utils.cpp: In function 'std::string dp::vulkan::GetVulkanResultString(VkResult)':
/data/pacaur/organicmaps-git/src/organicmaps-git/drape/vulkan/vulkan_utils.cpp:62:8: error: 'VK_ERROR_COMPRESSION_EXHAUSTED_EXT' was not declared in this scope
   62 |   case VK_ERROR_COMPRESSION_EXHAUSTED_EXT: return "VK_ERROR_COMPRESSION_EXHAUSTED_EXT";
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/pacaur/organicmaps-git/src/organicmaps-git/drape/vulkan/vulkan_utils.cpp:63:8: error: 'VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR' was not declared in this scope
   63 |   case VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR: return "VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR";
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/pacaur/organicmaps-git/src/organicmaps-git/drape/vulkan/vulkan_utils.cpp:64:8: error: 'VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR' was not declared in this scope
   64 |   case VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR: return "VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR";
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/pacaur/organicmaps-git/src/organicmaps-git/drape/vulkan/vulkan_utils.cpp:65:8: error: 'VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR' was not declared in this scope
   65 |   case VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR: return "VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR";
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/pacaur/organicmaps-git/src/organicmaps-git/drape/vulkan/vulkan_utils.cpp:66:8: error: 'VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR' was not declared in this scope
   66 |   case VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR: return "VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR";
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/pacaur/organicmaps-git/src/organicmaps-git/drape/vulkan/vulkan_utils.cpp:67:8: error: 'VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR' was not declared in this scope
   67 |   case VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR: return "VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR";
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/pacaur/organicmaps-git/src/organicmaps-git/drape/vulkan/vulkan_utils.cpp:68:8: error: 'VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR' was not declared in this scope
   68 |   case VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR: return "VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR";
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/pacaur/organicmaps-git/src/organicmaps-git/drape/vulkan/vulkan_utils.cpp:69:8: error: 'VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR' was not declared in this scope
   69 |   case VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR: return "VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR";
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/pacaur/organicmaps-git/src/organicmaps-git/drape/vulkan/vulkan_utils.cpp:70:8: error: 'VK_INCOMPATIBLE_SHADER_BINARY_EXT' was not declared in this scope
   70 |   case VK_INCOMPATIBLE_SHADER_BINARY_EXT: return "VK_INCOMPATIBLE_SHADER_BINARY_EXT";
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
</pre>

**System information:**
 - Operating system and its version: [iOS 12, Android 10, Ubuntu 22, MacOS Big Sur, etc.]
 - Organic Maps version: [you can find it by tapping the button with the green Organic Maps logo]
 - Device Model: [e.g. iPhone 6, Samsung S22]
Arch Linux with today updates
* libva-mesa-driver 1:24.0.5-1
* mesa 1:24.0.5-1
* mesa-vdpau 1:24.0.5-1
* opencl-clover-mesa 1:24.0.5-1
* opencl-rusticl-mesa 1:24.0.5-1
* vulkan-headers 1:1.3.279-1
* vulkan-icd-loader 1.3.279-1
* vulkan-intel 1:24.0.5-1
* vulkan-mesa-layers 1:24.0.5-1
* vulkan-radeon 1:24.0.5-1
* vulkan-swrast 1:24.0.5-1
* vulkan-tools 1.3.269-1
* vulkan-validation-layers 1.3.275-1
* cmake 3.29.2-1
* gcc 13.2.1-5

**Comment by biodranik** [comment]
Did you run `git submodules update --init --recursive` ?
