### ISSUE TITLE
[routing] Ghost intermediate points after removal

### ISSUE THREAD

**Issue by RicoElectrico** [organicmaps/organicmaps#7939]
**Describe the issue**
When specific conditions are met, deleting an intermediate point when routing will make all intermediate markers disappear, but they will still be taken into account when routing 

**Steps to reproduce**
1. Make a route with 2 intermediate points
2. Start routing
3. Pass the 1st point
4. Delete 2nd point
5. Routing will turn off and show a new route
6. Start routing again
7. Route has ghost waypoints

**Expected behaviour**
It works as usual, points are wiped from the route entirely

**Screenshots**

https://github.com/organicmaps/organicmaps/assets/1409116/efdc5ca8-a1e4-40df-b488-2da78cce410c

**System information:**
 - Android 14
 - Organic Maps version: 2024.03.xx (Not sure which one, recording is from April 1st)
 - Device Model: Samsung Galaxy S23 SM-S911B

**Additional context**
Occurs also in all Fdroid archival versions down to 2021.09.01-6 (minimal usable with our map data CDN right now)

**Comment by RicoElectrico** [comment]
Replicated also on LG G6 (Android 9).
The behavior is similar, but the 2nd point doesn't persist, curiously.

**Comment by pastk** [comment]
Same as the following?
- https://github.com/organicmaps/organicmaps/issues/9592

I prefer to keep the latter as it has screenshots so easier to comprehend.
