### ISSUE TITLE
[ios] Wrong and unnecessary "Location Services are disabled" dialogs on the first launch

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#794]
This is an annoying UI bug that reproduces on the very fists app launch. And is easy to reproduce on Simulator after deleting the app.

On the first launch, you see:

1. "Location Services are disabled" dialog, which suggests opening the device's Settings and enabling location permissions there.
2. Immediately "Allow Organic Maps to use your location?" dialog appears on top of the previous one.
3. If you allow location access, then the "Continue detecting your location?" dialog appears.
4. If you press Continue, you again see dialog (1) with two buttons: Cancel and Settings.

The proper startup should:
- Check if the user already disabled location, and only if it's disabled, show dialog (1) from above.
- If a user didn't choose before, ask her for location permission and show dialog (2) from above.

Dialog (3) should be investigated and fixed too. It appears in some cases after restoring the app from the background and could be really annoying.

**Comment by biodranik** [comment]
@vng This one is not fixed yet, why did you close it?

**Comment by biodranik** [comment]
Ok, I was wrong, looks like it is not reproduced. But I don't remember that we fixed it :)

**Comment by vng** [comment]
I thought that it's already fixed here https://github.com/organicmaps/organicmaps/commit/6781e87581b99f0d139f7e177f9e5f91894eccbe

Can reproduce showing "Location Services are disabled" dialog 2 times (second after enabling locations).

**Comment by vng** [comment]
UPD. Should we make some _unified_ dialog for location?
location_is_disabled_long_text string, enable_location_services - only in **Android**

location_services_disabled_header, location_services_disabled_message, current_location_unknown_error_title, current_location_unknown_error_message - only in **iOS**
Also in **iOS**: location_services_disabled_1, location_services_disabled_2, location_services_disabled_3 ...

I saw "Continue detecting your current location" dialog once and can't reproduce it any more. Honestly, there is no reason in it ..

**Comment by jplatte** [comment]
I also see "Location Services are disabled" when starting up the app without location enabled (which is most of the time - I enable it only when I need it).

**Comment by biodranik** [comment]
Android behavior is different. Please re-check it in the latest update.

This iOS dialog also sometimes appears after switching back to the already launched app. And the actual location can be detected under the already displayed dialog. It would be great to find a reliable way to reproduce it.

**Comment by jplatte** [comment]
Yeah, the Android issue (#3138) was solved, thanks :)
I've hidden my previous msg as off-topic.
