### ISSUE TITLE
Wrong routing after excluding unpoved roads

### ISSUE THREAD

**Issue by ooprizrakoo** [organicmaps/organicmaps#796]
Если в приложении включить режим объезда "Избегать грунтовых дорог" и построить маршрут между двумя точками:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.54763%2C30.22959%3B48.54311%2C30.22910#map=17/48.54537/30.22936

то маршрут будет строиться НЕПРАВИЛЬНО, а именно  - 
![image](https://user-images.githubusercontent.com/661813/124331235-a170c900-db97-11eb-8323-693dcb1f6b47.png)
Вместо того, чтобы проложить маршрут по прямой магистрали, приложение ищет любые кружные пути. Помимо этого ругается на то, что эта дорога является "Грунтовой" (и выкидывает предупреждения) об этом.

Предположительно, проблема возникает из-за того, что у данной магистрали не указан тип покрытия.
![image](https://user-images.githubusercontent.com/661813/124331562-1c39e400-db98-11eb-8876-8c2d078ee3ab.png)

Однако по текущим правилам работы роутинга он должен считать грунтовыми только те дороги, которые явно указаны как грунтовые; а приоритет при выборе пути делать за счет указанных скоростных ограничений.

**Comment by ooprizrakoo** [comment]
к слову, в текущей версии "maps. me" данная проблема не наблюдается.

**Comment by vng** [comment]
С новыми данными проблема с ложными "грунтовками" уйдет.
