### ISSUE TITLE
Alignment text

### ISSUE THREAD

**Issue by mohdalyahri** [organicmaps/organicmaps#7976]
⚠ Have you searched for similar, already existing issues?
Did not find anything similar to.
**Describe the issue**
The text in photo need to be a little bit aligned.

**Steps to reproduce**
None.

**Screenshots**

![image](https://github.com/organicmaps/organicmaps/assets/30707693/27a07665-eade-4a23-b878-993f32692e82)

**System information:**
 - Operating system and its version: [iOS 17.5]
 - Organic Maps version: [⁦2024.03.31-7⁩]
 - Device Model: [iPhone 13 Pro Max]

**Additional context**
That's it for now.
Thanks!

**Comment by biodranik** [comment]
@v-lozko can you please check it out?

**Comment by biopsin** [comment]
Hi, I too noticed  a missalignment in "Bookmarks and Track" in Lists

Model : Xperia 1ii
Android 11 : Lineageos-18.1
Font size = Largest
Display size = Small
Smallest width = 463 dp

![Screenshot_20240426-131717_Trebuchet](https://github.com/organicmaps/organicmaps/assets/60029989/dc5fddc6-6849-44a6-90d5-a02d85e4fb30)

**Comment by mohdalyahri** [comment]
That was in en.
Try Arabic please.
