### ISSUE TITLE
Show category locations on the map all at once

### ISSUE THREAD

**Issue by Qtamo** [organicmaps/organicmaps#7988]
Sorry if it's duplicate, couldn't find anything similar.

Whenever I search for categories, I have to look through the search results one by one. It would be great if there was an option to show the location of all venues belonging to a category on the map. That way it would be possible to compare e.g shops or gas stations nearby quite quickly.

This is for organic maps android (not sure if it works the same on other versions).

Love the app, keep up the great work!

**Comment by kesapaiva** [comment]
The "View on map" button should show the results on the map:
<img src="https://github.com/organicmaps/organicmaps/assets/157038301/bb78482a-21f5-43f6-97c3-32b2a841eecc" width="450" />

**Comment by Qtamo** [comment]
Thanks! I'm either an idiot, had an old version, or have some bug where the button is not displayed (can't check right now as my phone is broken).

Anyway, I'll close this issue

**Comment by kesapaiva** [comment]
No problem, it could be that you had an older version where the button was placed differently: <img src="https://github.com/organicmaps/organicmaps/assets/157038301/edbfe07c-268b-4e8a-967e-61c21270a9ad" width="400"/>
