### ISSUE TITLE
Replace 'WiFi' text with icon in Place Page (PP) Preview

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#8000]
![ResizedImage_2024-04-26_19-50-06_1022.png](https://github.com/organicmaps/organicmaps/assets/26939824/bc1979ac-7b00-4a72-bc35-50cccc937860)

Using an icon here (🛜) would be more consistent with the other attributes (toilet, disabled etc, which are displayed as icons)

**Comment by biodranik** [comment]
Even better would be to find/use monochrome icons )

**Comment by RedAuburn** [comment]
> Even better would be to find/use monochrome icons )

There isn't a moochrome wifi icon unfortunately. We could use a custom emoji font though: https://emojipedia.org/noto-emoji

**Comment by biodranik** [comment]
Using a custom font in the UI to render some text-like symbols/chars in an easy way looks like an interesting idea. Do both iOS and Android allow apps to bundle and use a custom font for rendering some chars in the app's interface? If yes, we can prepare a custom font with only necessary chars/icons, in our unique (and simple) style. These icons may also be used on the map btw by our font renderer.

**Comment by dvdmrtnz** [comment]
> Even better would be to find/use monochrome icons )

* Related to https://github.com/organicmaps/organicmaps/issues/7700

**Comment by slackuj** [comment]
I am sorry but what does PP signifies to?

**Comment by patepelo** [comment]
> I am sorry but what does PP signifies to?

It's for Place Page. When you select a POI (Point of Interest), it opens a page for that place and you see all related info.

Maybe we should create a wiki subpage to include some terminology. WDYT?

**Comment by pastk** [comment]
> Using a custom font in the UI to render some text-like symbols/chars in an easy way looks like an interesting idea. Do both iOS and Android allow apps to bundle and use a custom font for rendering some chars in the app's interface? If yes, we can prepare a custom font with only necessary chars/icons, in our unique (and simple) style. 

Looks like Android supports that, see https://github.com/organicmaps/organicmaps/issues/9640
