### ISSUE TITLE
Add option to download map of all country by single click

### ISSUE THREAD

**Issue by Gamer750** [organicmaps/organicmaps#8011]

**Comment by Jean-BaptisteC** [comment]
Did you have try to select a country on map and press download button?

**Comment by biodranik** [comment]
@Gamer750 isn't it already present/working in the Download Maps screen?

**Comment by Gamer750** [comment]
> @Gamer750 isn't it already present/working in the Download Maps screen?

I mean by download all country map by single click

**Comment by RedAuburn** [comment]
> I mean by download all country map by single click

you can, press the folder icon on the left

**Comment by Gamer750** [comment]
> > I mean by download all country map by single click
> 
> you can, press the folder icon on the left

I mean by downloading every country from China to America(ie, downloading map of all country) by single click

**Comment by Jean-BaptisteC** [comment]
Do you want download all the world? (all maps takes more 10 Go)

**Comment by Gamer750** [comment]
> Do you want download all the world? (all maps takes more 10 Go)

Yeah

**Comment by RedAuburn** [comment]
There's very little practical reason to do that, and it puts unnecessary strain on the maps CDN

**Comment by Gamer750** [comment]
> CDN will survive, however, downloading 65+GB of the whole world files doesn't make any sense. It slows down the app. And you need to re-download maps again on the next map update.

65GB ? I thought it would be at max 10GB
