### ISSUE TITLE
Can you add option to find qibla

### ISSUE THREAD

**Issue by Gamer750** [organicmaps/organicmaps#8012]

**Comment by biodranik** [comment]
You can bookmark any place on the map by selecting it using either a single tap, a long tap, or by typing coordinates into the search, and then pressing a star at the bottom.

When any place (or bookmark) is selected, there is a small arrow that shows your location and distance. You can also click it to see a big arrow and big distance.

**Comment by RedAuburn** [comment]
closing as indirectly possible via direction arrow or line routing mode
