### ISSUE TITLE
Missing amenity=social_facility

### ISSUE THREAD

**Issue by tasinttttttt** [organicmaps/organicmaps#8021]
**Is your feature request related to a problem? Please describe.**
Can't add social facilities to the app because of a missing category.

**Describe the ideal solution**
Add the Social facility category, which matches OSM's amenity=social_facility. OSM has a tag for social facilities with many sub categories.

**Describe alternatives you have considered**
No category in the list fits… there are however categories which belong to the social facility tag: nursing home and day care.

**Comment by dvdmrtnz** [comment]
144k uses worldwide 

https://taginfo.openstreetmap.org/tags/amenity=social_facility#overview

**Comment by patepelo** [comment]
Carto: 
![imagen](https://github.com/organicmaps/organicmaps/assets/23003127/97c58fd2-d032-42aa-9e3a-3df7fb69d4eb)
Id Editor:
![imagen](https://github.com/organicmaps/organicmaps/assets/23003127/d41b43ef-2d1b-47b3-aa5e-8bf737376251)


Other similar and ideas:

![imagen](https://github.com/organicmaps/organicmaps/assets/23003127/7fcb7a86-c8a0-4277-9ce1-0def00cbed34)

![imagen](https://github.com/organicmaps/organicmaps/assets/23003127/9c267b5d-682c-4291-9d84-7b99e67597ff)

**Comment by RedAuburn** [comment]
lots of subkeys that should be added too:
https://taginfo.openstreetmap.org/keys/social_facility#values
