### ISSUE TITLE
Cycle routing via bicycle=dismount footways

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#8028]
<img src="https://github.com/organicmaps/organicmaps/assets/26939824/ef3ac4f5-cda8-497b-b6c6-361d9536ab36" width="300px"/>

https://www.openstreetmap.org/way/4358990

`highway=footway` + `bicycle=dismount` shouldn't be interpreted as cycle & footpath. dismount sections of cycle routes should be treated with suspicion, as they are likely only included because there's no other option to continue the route (such as crossing a river in this case)

this could be due to two cycle network relations:
https://www.openstreetmap.org/relation/13420707
https://www.openstreetmap.org/relation/1650927

**Comment by RedAuburn** [comment]
ah, style will be fixed by https://github.com/organicmaps/organicmaps/pull/8026.

i'm unsure how it's handled in routing though

**Comment by pastk** [comment]
Yeap it comes from a bicycle relation
```
      if (route == "bicycle")
        Base::AddCustomTag({"bicycle", "yes"});
```
and https://github.com/organicmaps/organicmaps/pull/8026 makes it insensitive to bicycle=yes so the display issue will be fixed in next data.

**Comment by pastk** [comment]
But the routing handles this case very bad ATM.
It treats `highway=footway bicycle=yes` as very fast for cycling (almost as a dedicated cycleway), though in this case its explicit `bicycle=dismount` meaning it should be not faster than walking.
FYI @vng

**Comment by pastk** [comment]
Probably a rather easy solution would be to not add `bicycle=yes` from a relation if there is a `bicycle=*` tag already.

**Comment by vng** [comment]
Data is merged https://github.com/organicmaps/organicmaps/pull/8009
