### ISSUE TITLE
footway with surface=fine_gravel should not be converted to path

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#8029]
<img height="500px" src="https://github.com/organicmaps/organicmaps/assets/26939824/e64eebd6-970d-4958-b3b6-562a320e16d0"/>

https://www.openstreetmap.org/way/52868110

**Comment by pastk** [comment]
The current logic is to treat gravel/fine_gravel as footways only in case there is explicit good smoothness/tracktype, i.e. if we're certain its of good park/urban quality.

Otherwise gravel/fine_gravel could be used on rough trails also.

**Comment by RedAuburn** [comment]
> The current logic is to treat gravel/fine_gravel as footways only in case there is explicit good smoothness/tracktype, i.e. if we're certain its of good park/urban quality.
> 
> Otherwise gravel/fine_gravel could be used on rough trails also.

hmm, i get the logic, but in my experience gravel footways in cities etc rarely have smoothness tagged.. 

i still think that fine_gravel is likely to be a reasonably smooth footway though. eg. the example image on the osm wiki:
<img width="300px" src="https://wiki.openstreetmap.org/wiki/File:Fine_gravel_path_in_Voltino,_Zagreb.jpg"/>

**Comment by pastk** [comment]
Yeap we might treat `fine_gravel` same as `compacted`?
