### ISSUE TITLE
Fails to download local map (Downloading: 0%)... then timesout.

### ISSUE THREAD

**Issue by ioogithub** [organicmaps/organicmaps#806]
When the app is opened and zoomed into the local area, it is never able to download the map. It stays on Downloading: 0% and eventually fails.

Version: 2021.06.12-7-g75fd600f97-FDroid
System: LineageOS 18.1

**Comment by biodranik** [comment]
@ioogithub Did you block Internet access for the system's Download Manager (Download Provider) service with any firewall software?

**Comment by DAFO45** [comment]
Same issue.
Never could download any map on my Android smartphone.
I'm downloading from 4G connection but it worked with Maps.me.
Got Downloading 0% ... for hours.

**Comment by biodranik** [comment]
@DAFO45 The same question: do you have any firewall (like Blokada) installed? If yes, please unblock the Download Manager service.

**Comment by DAFO45** [comment]
I don't find any firewall application on my smartphone.
Never installed such app for sure.
I there a way to test itis (or not) a firewall issue ?

**Comment by DAFO45** [comment]
Hi Alexander,

I connected my smartphone to internet throu wifi ... and now I can download maps.
It's like the app was preventing from downloading maps from a network connection.

Strange,


but it is great to have updated maps again ;-)))))

Best regards,

Daniel Folkeringa
(DAFO45 on github and DF45 on OSM)‌
 

De : "Alexander Borsuk"
A : "organicmaps/organicmaps" ,"DAFO45" ,"Mention"
Envoyé: lundi 5 Juillet 2021 11:56
Objet : Re: [organicmaps/organicmaps] Fails to download local map (Downloading: 0%)... then timesout. (#806)
 

 

@DAFO45 The same question: do you have any firewall (like Blokada) installed? If yes, please unblock the Download Manager service.

**Comment by thelazyoxymoron** [comment]
Hi, I'm facing the same issue on Android 11. I was running an ad-blocker [Dns66](https://f-droid.org/en/packages/org.jak_linux.dns66/) which shouldn't affect the download functionality, but of course disabling it made the download work.

I tried with TrackerControl as well, and the download was blocked. Can it be that using any vpn app blocks the download thread?

**Comment by biodranik** [comment]
We use Download Manager for map downloading. It's a system service that is probably blocked by these apps. Try to enable *.organicmaps.app hosts for Download Manager and see if it helps.

**Comment by thelazyoxymoron** [comment]
I checked and confirmed that all the system apps were bypassed by DNS66 by default. Still blocked.

**Comment by biodranik** [comment]
You can send us `adb logcat` logs recorded via USB cable (ideally) or enable "Logs" setting in the app and then sharing them via Settings/Help/Feedback.

**Comment by alisseo** [comment]
Same iusse, i cant download locals maps, it stuck at 0.00% i dont use vpn or firewall or dns, my phone is unrooted and i can put the filemap in the patch manually.. the downoad manger work great in chrome.
I already send app log and logcat via mail

**Comment by biodranik** [comment]
Guys, we found that the system download manager is unreliable, and our current code doesn't handle it well in all cases.
The good news is that the fix should be available soon! Please stay tuned, or write us at android@organicmaps.app and ask for a link to the beta version with the fix, until the main app will be updated in Google Play, FDroid, and other stores.

**Comment by alisseo** [comment]
Done!! whit the last update i dont have any problem to download the maps! :)

**Comment by biodranik** [comment]
Fixed!

**Comment by DAFO45** [comment]
H‌i,

I confirm !

THANKS,

Best regards,

Daniel
 

De : "Alexander Borsuk"
A : "organicmaps/organicmaps" ,"DAFO45" ,"Mention"
Envoyé: samedi 4 Septembre 2021 12:08
Objet : Re: [organicmaps/organicmaps] Fails to download local map (Downloading: 0%)... then timesout. (#806)
 

 

Fixed!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
