### ISSUE TITLE
Add 'Amusement Arcades' to the Category List

### ISSUE THREAD

**Issue by Swamp2k9** [organicmaps/organicmaps#8062]
[leisure=amusement_arcade]

Is your feature request related to a problem? Please describe.
It's a bit tedious when searching for Amusement Arcades. It's not in the Categories list.

Describe the ideal solution
Adding Amusement Arcades within the categories list. 

Describe alternatives you have considered
As a workaround, I would have to type out the category in search and filter through the outputted list.

**Comment by biodranik** [comment]
Categories list accumulated most popular categories. Adding many other categories will make it less useable (to find something useful, a long list should be scrolled).
