### ISSUE TITLE
Matrix icon m is off centered

### ISSUE THREAD

**Issue by ooosssay** [organicmaps/organicmaps#8069]
⚠ Have you searched for similar, already existing issues? Yea

**Describe the issue**
The m for the matrix icon is not centered in the brackets.

**Steps to reproduce**
1. Open Organic Maps info page
2. Scroll down to the icon 
3. See issue

**Expected behaviour**
Centered m in brackets

**Screenshots**
The squares on top is the same width
![IMG_6439](https://github.com/organicmaps/organicmaps/assets/129241633/49bbaf36-6762-41b0-9a60-269723229db2)

**System information:**
 - Operating system and its version: iOS 17.2.1
 - Organic Maps version: ⁦2024.04.29-31.39020.3447⁩
 - Device Model: iPhone XR

Sorry for nitpicking

**Comment by RedAuburn** [comment]
correct icon: 

https://matrix.org/images/matrix-favicon.svg
