### ISSUE TITLE
does not search associatedStreet

### ISSUE THREAD

**Issue by CupIvan** [organicmaps/organicmaps#809]
but if I click on building there is a correct street in the title

- place in osm https://www.openstreetmap.org/relation/2338953
- search with nominatim https://nominatim.openstreetmap.org/ui/search.html?q=%D0%BD%D0%B8%D0%B6%D0%BD%D0%B8%D0%B9+%D0%BD%D0%BE%D0%B2%D0%B3%D0%BE%D1%80%D0%BE%D0%B4+%D1%8E%D0%B6%D0%BD%D0%BE%D0%B5+%D1%88%D0%BE%D1%81%D1%81%D0%B5+33
- wiki page https://wiki.openstreetmap.org/wiki/Relation:associatedStreet

**Comment by Jean-BaptisteC** [comment]
Address in relation associatedStreet can be searched.
I close this issue
