### ISSUE TITLE
Tram stop is not rendered.

### ISSUE THREAD

**Issue by Endem10n** [organicmaps/organicmaps#810]
On max zoom level one of two tram stops, that close to each other, is not rendered.
After rotating map I can see both.

Coordinates of the place, where it's easy to reproduce this behaviour: 54°24′09.91″N 18°33′56.36″E

Reproduced on: 
  iPhone SE, iOS version 14.6
  Huawei Y7 2019, Android version 8.1

[Video from Android](https://drive.google.com/file/d/1jZsg63FC42EXNpb99uk2QvUJcG8-J68k/view?usp=sharing)
[Video from iOS](https://drive.google.com/file/d/1dqM2XRDgzpNaHHK4JRKgE1xmF6gqRq6l/view?usp=sharing)

**Comment by biodranik** [comment]
@Endem10n can the issue be closed?
