### ISSUE TITLE
This Hangul character is changing whenever I relaunched the app

### ISSUE THREAD

**Issue by lens0021** [organicmaps/organicmaps#8104]
**Describe the issue**
A Hangul character "답" keeps changing when I relaunched the app.

**Steps to reproduce**
1. Go to 37.566814, 127.0527

**Expected behaviour**
The first character should be statically "답"
![Screenshot_20240507-002847](https://github.com/organicmaps/organicmaps/assets/28209361/b427cec4-b2ef-4b75-8678-ba37d5579590)

**Screenshots**

![Screenshot_20240507-002732](https://github.com/organicmaps/organicmaps/assets/28209361/25590b6d-8989-4e9d-9c31-ff2fc163d0e4)
![Screenshot_20240507-002748](https://github.com/organicmaps/organicmaps/assets/28209361/d47e565b-b0a8-411a-abeb-19aaa1dd3d59)
![Screenshot_20240507-002758](https://github.com/organicmaps/organicmaps/assets/28209361/0dbae196-7566-487a-811a-119b34b1a479)
![Screenshot_20240507-003019](https://github.com/organicmaps/organicmaps/assets/28209361/05c65004-b2d1-4fa7-b667-53806984baae)

난, 밥, 밭 and 날 are not "답".

**System information:**
 - Android 13
 - Organic Maps version: 2024.03.31-8-Google
 - Device Model: Fairphone 5

**Additional context**
I've never seen this type of issue in my life on the Korean internet.

**Comment by biodranik** [comment]
Does it reproduce in the latest version?

**Comment by lens0021** [comment]
Not happen in 2024.05.04-9-android-rc, thank you!
