### ISSUE TITLE
Setting for default mode of transport

### ISSUE THREAD

**Issue by balki** [organicmaps/organicmaps#8105]
On clicking 'Route To' button, the app tries to find the public transit route by default. In my location, public transit is not good and driving is the only option for most cases. 
As of now, I have to 
1. Click 'Route to'
2. Wait for maps to display 'Unable to calculate route' 
3. Click Cancel
4. Click on the car icon on top
5. Wait for maps to find the route and then click 'Start'

**Solution**
An option in 'Settings' allowing to set default mode of transport to car, public, walk or bike.

**Comment by biodranik** [comment]
Please disable the Subway layer in the top left corner of the map screen.

@Jean-BaptisteC is it hard to quickly add _any_ indication icon in the top left when any layer is enabled, so users will be aware and disable it when necessary, without raising such questions?

CC @rtsisyk @euf

**Comment by biodranik** [comment]
It is clearer than nothing as it is now on android.

**Comment by balki** [comment]
> Please disable the Subway layer in the top left corner of the map screen.
> 
That worked! Thanks. Not sure If I enabled it or it was enabled by default.

**Comment by Korb** [comment]
> That worked! Thanks. Not sure If I enabled it or it was enabled by default.

Apparently this issue should be considered closed/resolved?

**Comment by pastk** [comment]
> @Jean-BaptisteC is it hard to quickly add _any_ indication icon in the top left when any layer is enabled, so users will be aware and disable it when necessary, without raising such questions?

This UX/UI aspect is tracked here:
- https://github.com/organicmaps/organicmaps/issues/3508
