### ISSUE TITLE
The OSM uploading code is executed several times for the same feature

### ISSUE THREAD

**Issue by map-per** [organicmaps/organicmaps#8125]
Things look really bad here:
Only 110 changeset were created with the Mai version, but there are already 14 flagged with feature_close_by adding duplicates. For some reason the uploading code of Organic Maps is executed more than once in some cases. This leads to OM adding e.g. a hotel once and then adding it once more a minute later (in a new changeset).

Usually one duplicate is created, but sometimes more. The different objects differ in their tags and the second one has updated or added matadata like `phone` or `opening_hours`. Android and ios are affected.

It looks like updating of recently added objects in OM doesn't work properly and new objects are added instead of updating. In the previous releases this bug was hidden by the code that I changed in #7853 (new nodes were merged into existing nodes closer than one meter). I think that this bug is also the reason for the empty changeset problem (#5472)

Link to OsmCha filter for `info:feature_close_by`: https://osmcha.org/?aoi=988f50d9-67fe-4ca4-8694-7c6066f063fd

**Comment by map-per** [comment]
@biodranik: Is it still possible to remove / revert #7853 for the Mai release? 14/110 edits being faulty is very bad.

**Comment by biodranik** [comment]
A follow up fix can be released. Any ideas about the cause?

**Comment by biodranik** [comment]
I see that the situation has become worse than before, duplicates are coming from different versions of OM https://www.openstreetmap.org/node/11861777570 (and nearby butcher shop).

The previous logic with merging features was safer. Let's revert it and try to fix it differently.
