### ISSUE TITLE
Fitness Centres aren't showing their addresses

### ISSUE THREAD

**Issue by patepelo** [organicmaps/organicmaps#8151]
![image](https://github.com/organicmaps/organicmaps/assets/23003127/fdd44a8c-af62-4e63-a0d9-b2ad1fa70c58)

In the place page, the address is not shown even when OSM POI has it.

**Comment by biodranik** [comment]
Where is the address? https://www.openstreetmap.org/way/123198739

**Comment by dvdmrtnz** [comment]
Fitness centre's adresses are showing up just fine for me:

https://www.openstreetmap.org/way/501309023#map=19/43.34125/-2.99458

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/eb39ba67-ff12-4257-bef0-5288122dc55c" width="320"/>

**Comment by patepelo** [comment]
> Where is the address? https://www.openstreetmap.org/way/123198739

Oh sorry. Bad example chosen.  And it's android on distributed version and version 2024.05.06-3-Google-beta

Here a good example:

![Screenshot_20240512-203817.png](https://github.com/organicmaps/organicmaps/assets/23003127/db369f01-6517-43ac-bb01-efd1edc27c7f)

![Screenshot_20240512-203811.png](https://github.com/organicmaps/organicmaps/assets/23003127/e23dc586-4e24-415f-a1a3-d7e18ff21fe4)

**Comment by biodranik** [comment]
Is it only related to Fitness centers?

**Comment by patepelo** [comment]
> Is it only related to Fitness centers?

Sports centers in general. Everything else seems ok.

**Comment by biodranik** [comment]
It looks like Android-only issue, right? Are there any volunteers to debug the Place Page code?

**Comment by patepelo** [comment]
> It looks like Android-only issue, right? Are there any volunteers to debug the Place Page code?

Also present in iOS 2024.05.10-1.

I tried browsing the code for it but didn't find the origin.

**Comment by dvdmrtnz** [comment]
I can reproduce it in iOS too Organic Maps version: ⁦2024.05.12-3⁩

https://www.openstreetmap.org/node/11420433469#map=19/41.38760/2.15464

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/9eb98bb3-5865-490a-9002-715221781326" width="320"/>
