### ISSUE TITLE
Some buttons disappear from map

### ISSUE THREAD

**Issue by oleg-rswll** [organicmaps/organicmaps#8184]
**Problem Statement**

After certain options are run, several of the buttons on the map disappear but the main buttons still remain.

It's not clear why this mode exists, why only some buttons hide, but some display.

Trying to get the buttons back is tricky and annoying. This becomes a task of trying different spots on the to find a spot that doesn't have anything, but what looks like nothing may actually have something, so this often takes many tries.

Recreation steps , iOS:
1) Press the burger menu on the main screen 
2) Select "Add Place to OpenStreetMap".  The map zooms in.
3) Press the "Cancel" button at the top left.
4) The main buttons at the bottom remain, but the other buttons (layer, zoom, location) disappear.  To get them back, need to tap on the map where there are no OSM features, and this is not obvious and can take many attempts.

There are other scenarios that cause this state, need to find all of them and make changes for all of them.

The buttons should not disappear.

**Criteria**
In the scenarios above, keep all the buttons on the map, don't have buttons disappear at all.

**Comment by biodranik** [comment]
Please check https://github.com/organicmaps/organicmaps/pull/7876

**Comment by oleg-PK** [comment]
7876 is about the tapping and selection on the map. This issue is about buttons disappear where they shouldn't.

**Comment by biodranik** [comment]
@oleg-PK you're right, that's a different issue. This is definitely a bug that should be fixed. May we ask @kirylkaveryn to earn +1 solved issue? ;-)
