### ISSUE TITLE
[ios] Crash during the Bookmark Update after the MarkID reloading/deleting

### ISSUE THREAD

**Issue by kirylkaveryn** [organicmaps/organicmaps#8189]
### Description
When the categories list OR bookmark edit screen OR the Place Page are opened, but the category/bookmark ID becomes invalid (because of different reasons) the app will crash during the attempt to update/delete this item.

This issue is related to the #8164, #1694 , #7978 

### How to reproduce
**use iPad**
1. Tap on the bookmark on the map
2. go into the BM list
3. delete the selected bookmark
4. return to the map
5. try to remove the bookmark by tapping on the `star`
6. receive the crash because this ID is invalid

![Simulator Screen Recording - iPad Air (5th generation) - 2024-05-16 at 11 19 15](https://github.com/organicmaps/organicmaps/assets/79797627/ba9200eb-ade3-4ee3-bfda-dd81905a0176)
<img width="400" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/51f4aecf-c67a-4e12-81e2-1500786e1dd0">

### Expected behavior
1. The opened categories list, bookmarks list, edit bm screen, and the place page should react to the changes even during the all VC lifecycle not only the appearing/dismissing.
2. If the current bookmark was deleted the screen should be dismissed. If content was updated - the screen should be redrawn.

**Comment by biodranik** [comment]
There is also a way to reproduce it on iPhone:
1. Build a route.
2. Select and bookmark any poi on the map.
3. Press Bookmarks and Tracks dialog button on the left
4. Delete that recent bookmark from this dialog.
5. Return back to the route planning mode
6. Delete selected POI bookmark
