### ISSUE TITLE
[ios] White corners on the place page for the Dark theme / White line in bookmarks

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#819]
![image-1](https://user-images.githubusercontent.com/170263/124831756-fcc9ff00-df7b-11eb-94f6-886da4739ea0.png)

**Comment by Raphael0** [comment]
This also happens in light theme though it is more difficult to spot:

<img width="500" alt="Image PNG" src="https://user-images.githubusercontent.com/23408445/124917658-5f5ee180-dff4-11eb-958a-970e2e0e6d06.png">
on iPhone 8, iOS 14.6

**Comment by biodranik** [comment]
There is also another white line in Bookmarks dialog:

![image](https://user-images.githubusercontent.com/170263/144889514-230569a8-7570-4379-a6a4-7fb744a43bf1.png)

**Comment by dvdmrtnz** [comment]
I think this may have been fixed and can be closed. I don't see the white corners nor the white line on latest master.

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/8b2d104f-cf93-4501-ba8b-1cddf7c55e9e" width="320"/> <img src="https://github.com/organicmaps/organicmaps/assets/47610359/b5bd6484-939e-4669-8eab-bccabc926fcb" width="320"/>
