### ISSUE TITLE
exportable routes

### ISSUE THREAD

**Issue by Online122228** [organicmaps/organicmaps#8208]
⚠ Have you searched for similar, already existing issues?

**Is your feature request related to a problem? Please describe.**
I sit in the car, everything packed but now i have to search for my destination and all the stops and manually put every location into my route

**Describe the ideal solution**
An exportable route that saves the entire route and all the stops in between

**Describe alternatives you have considered**
Only save the destination and stops on the route for less storage consumption

**Comment by Jean-BaptisteC** [comment]
Duplicate of #1785
