### ISSUE TITLE
[routing] Cross Mwm, Uman-Odessa.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#821]
Starting point is here: https://www.openstreetmap.org/#map=18/48.52081/30.22691&layers=N
End point is Odessa.

- If starting point is above bridge - the route is bad 346 km
- If starting point is below bridge - the route is good 243 km

Suspect that it happens because of nearby MWM border.

**Comment by ooprizrakoo** [comment]
the same bug: https://github.com/organicmaps/organicmaps/issues/796

**Comment by strump** [comment]
Looks like `CalculateSubrouteLeapsOnlyMode` function founds unoptimal route. Kyiv-Odessa route is calculated as on image. Each colored area is different oblast from a separete MWM file:

<img src="https://user-images.githubusercontent.com/720808/127142237-04164984-bb7d-48dc-a55a-3dff66d391fb.png" width="400px">


Green line - expected route. Red line - OrganicMaps route.

Dirty hack is to edit `index_router.cpp` line 1635:

```cpp
/* Remove these two lines
starter.GetGraph().SetMode(AreMwmsNear(starter) ? WorldGraphMode::Joints
                                                : WorldGraphMode::LeapsOnly);*/

//Add this line
starter.GetGraph().SetMode(WorldGraphMode::Joints);
```

But correct fix is to make IndexRouter build optimal LeapsOnly route.

**Comment by vng** [comment]
Еще один кейз:

Кстати, недавно нашел странное построене маршрута. Одесская область. Каролино-Бугаз - Белгород-Днестровский. Пускает о объезд лимана в т.ч. с пересечением границы Приднестровья, хотя очевидным решением было бы пустить по косе через Затоку.

![photo_2021-08-22 15 03 12](https://user-images.githubusercontent.com/175612/130354390-ea1a1ba1-ca45-454d-a8fe-0c66ea25a6ad.jpeg)
