### ISSUE TITLE
Car route is leading me off the highway and then back on it again without a clear reason why

### ISSUE THREAD

**Issue by simonschaufi** [organicmaps/organicmaps#8211]
**Describe the issue**
Organic Maps was sending me off the highway and then back on it again. I'm not sure if this is a data problem on OSM or a routing bug in Organic Maps.

This can be reproduced also here: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=49.25714%2C8.27967%3B49.24021%2C8.22252#map=17/49.24979/8.24729

**Steps to reproduce**

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=49.25714%2C8.27967%3B49.24021%2C8.22252#map=17/49.24979/8.24729

**Expected behaviour**
Stay on the highway like graphhopper_car or fossgis_valhalla_car which are doing it right.

**Screenshots**

![photo_2024-05-18_16-30-19](https://github.com/organicmaps/organicmaps/assets/941794/96259fb9-4d75-4b4a-a104-ffac18eace36)

![photo_2024-05-18_16-30-16](https://github.com/organicmaps/organicmaps/assets/941794/f0128c39-5c9f-41cd-8954-0d2ba89de953)

**System information:**
 - Organic Maps version: 2024.05.11-3-Google

**Comment by biodranik** [comment]
This issue is caused by missing penalties for crossings and exits/turns/traffic lights. The first exit lane has maxspeed 100, the second is maxspeed 70, while the center road has maxspeed 70. That's the reason why algorithm thinks that riding the lanes is faster.

**Comment by simonschaufi** [comment]
ok, then the bug is the speed of 100km/h on OSM. I'll fix this.

**Comment by biodranik** [comment]
@simonschaufi are you sure that the speed limit is wrong on that lane? What is the ground truth?

**Comment by simonschaufi** [comment]
if the main road is 70, the exit can't be 100. That doesn't make any sense :smile:

**Comment by biodranik** [comment]
Who knows? )
