### ISSUE TITLE
Pedestrian paths with "surface=brick" are displayed as unpaved

### ISSUE THREAD

**Issue by Motorblade** [organicmaps/organicmaps#8231]
**Describe the issue**
With the latest update (2024.05.10-1), paved pedestrian paths are displayed as white, while unpaved ones are displayed as brown. Paths with the tag "surface=brick" display as the brown unpaved color when they should display as the white paved color.

**Screenshots**
[IMG_1843](https://github.com/organicmaps/organicmaps/assets/81498895/108a92a8-508a-49d7-af4b-c93c4fff4633)
In this screenshot, all of the brown dotted segments are tagged with “surface=brick”.

**System information:**
 - iOS 17.5
 - Organic Maps version: 2024.05.10-1
 - Device Model: iPhone 12

**Comment by Misalf-git** [comment]
Isn't "brick" a value for `material=*`?
`surface=brick` seems like incorrect tagging to me. I'd probably expect `surface=paving_stones` unless walking on top of a brick wall.

**Comment by Motorblade** [comment]
Whether it is the correct tagging or not, it seems strange that unknown surface tags default to unpaved when missing surface tags default to paved.

**Comment by pastk** [comment]
We should process grass_paver (42k), artificial_turf (39k), tartan (37k), clay (34k), stone (12k) and soil (7k) also.

- related to #8029
