### ISSUE TITLE
3 vertically aligned dots on bookmarks list opens list instead of context menu

### ISSUE THREAD

**Issue by kaoneko** [organicmaps/organicmaps#824]
**Version:**
2021.06.23-9-gc3f05a1646-FDroid

**Regarding:**
The bookmarks screen, opened by tapping the star icon in the main screen.

**Expected behaviour:**
Tapping the 3 vertically aligned dots on a bookmarks list opens the context menu.

**Actual behaviour:**
Tapping the 3 vertically aligned dots on a bookmarks list opens the bookmarks list.

The context menu _can_ be opened by long tapping anywhere on a bookmarks list. But if this is the intended way to do it, why have the 3 vertically aligned dots?

**Comment by kaoneko** [comment]
Usually when long tapping a list item in any Android app one enters selection mode, where one can select multiple or all list items, delete them and sometimes rearrange them. So that would be the expected behaviour of long tapping here (if/when Organic Maps offers this functionality), instead of opening the context menu. Then the context menu should be opened by the three dots. And just tapping the list item should open it, as it already does.

**Comment by SeanConn15** [comment]
working on this issue now
