### ISSUE TITLE
Relations with `oneway=yes` are wrongly converting roads to one-way

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#8246]
There are around 2000 relations with `oneway=yes` tagging.
https://overpass-turbo.eu/s/1LQf

as reported on telegram, this road:
https://www.openstreetmap.org/way/6363768
is part of this relation:
https://www.openstreetmap.org/relation/1473170

the road incorrectly inherits `oneway=yes` from the relation.

**Comment by RedAuburn** [comment]
ah ok, 1911 uses are on relations with `type=route` (and only 2 on 'type=restriction'). The fix would be to not apply surface/oneway etc tags from route relations.

**Comment by muralito** [comment]
Which is the semantic of tag oneway=yes on a relation element? It's not specified in the wiki https://wiki.openstreetmap.org/wiki/Key:oneway

**Comment by pastk** [comment]
Probably we shouldn't infer *all tags* from relations, but should apply whitelisted ones only.
@vng

**Comment by vng** [comment]
Good catch. We don't take all tags, but the current logic is very complicated and aims to patch OSM _mapping traits_.
See RelationTagsWay::Process

**Comment by vng** [comment]
I will put a crutch, but I still don't have a clear vision of OSM mapping here.

For example, this https://www.openstreetmap.org/relation/12126834 I suspect that oneway=yes should be taken from this kind of relation (route=ferry). I see a contradiction here with route=road.

**Comment by pastk** [comment]
>     1. For example, this https://www.openstreetmap.org/relation/12126834 I suspect that oneway=yes should be taken from this kind of relation (route=ferry).
> 

Nope, here is a "backward" route that uses the same way: https://www.openstreetmap.org/relation/12234840

>     2. Should we take "surface" from route=road relations?

I think its mistagging.

**Comment by mvgorcum** [comment]
This is still an issue for me, since I get weird routes when using organicmaps for navigation in this area.

Note that openstreetmap itself and also osmand don't inherit oneway on these streets.

**Comment by mvgorcum** [comment]
This seems fixed now, at least for the roads that were causing me trouble.
