### ISSUE TITLE
Few search results are shown on the map

### ISSUE THREAD

**Issue by deevroman** [organicmaps/organicmaps#8283]
**Describe the issue**
The overview zoom shows few search results if there is free space. If you zoom in, the results will appear on the map

**Steps to reproduce**
0. Go to `59.946145, 30.490861`
1. Enter in the search "Стоматология" (dental clinic)
2. Click on 'Show on map'

**Expected behaviour**
All results are shown in the visible area

**Screenshots**

https://github.com/organicmaps/organicmaps/assets/25708359/1efe439c-4fed-4c0f-a814-1847d19d0840

**System information:**
 - Operating system and its version: Android 14 OneUI 6.0
 - Organic Maps version: 2024.05.04-9-Web
 - Device Model: Samsung A52

**Comment by vng** [comment]
Ok, we have "Стоматолог|дантист|зубной" keywords only.
Will add "Стоматология", otherwise the matching is fancy ..
