### ISSUE TITLE
English language codes - correcting US vs UK spelling

### ISSUE THREAD

**Issue by jamescridland** [organicmaps/organicmaps#829]
Having reported elsewhere about localisation for addresses, I also noticed that my search in Australia, on a device set up for `en-au`, returns the spelling "Recycling Center", which is incorrectly spelt. I thought I'd go and fix that for you... but:

In `/data/categories.txt` it has a line saying...

`# <lang>               ::= 'en'|'cs'|'sk'|'de'|'es'|'fr'|'it'|'ja' etc.`

Noting the presence of

```
zh-Hans:化妝品|商店
zh-Hant:化妆品|美妝店|購物
```

is the correct way to fix this issue to amend the file to read:

```
en:Recycling Center|U+1F6AE|U+267B
en-gb:Recycling Centre|U+1F6AE|U+267B
en-au:Recycling Centre|U+1F6AE|U+267B
en-ca:Recycling Centre|U+1F6AE|U+267B
```

... i.e. would a user with `en-us` be given "Center" in the above?

**Comment by jamescridland** [comment]
As a secondary thought - "Liquor Store" in en-us is the same as "Off licence" in en-gb, and "Bottle shop" in en-au - I'm absolutely happy making those changes too, if it makes sense to help.

I'd also add that "Butcher's" is wrong (it would be either "Butcher" or "Butchers"), and I'd be happy to go through and proof-read those too.

**Comment by biodranik** [comment]
Thanks! It would be great if you can proofread everything. The proper format is en-GB, en-AU, en-CA etc.

**Comment by biodranik** [comment]
Also, to save space, it may be more efficient to write like this:
```
en: Centre
en-US: Center
```

**Comment by jamescridland** [comment]
Done in #832 (my goodness, there's a lot to read through!)
