### ISSUE TITLE
Simple Mode Not Appearing When Adding/Editing POI Opening Hours

### ISSUE THREAD

**Issue by Swamp2k9** [organicmaps/organicmaps#8299]
**Describe the issue**
When adding/editing opening_hours of POI, simple hours don't appear (until I add a day/time in advanced mode). This only happens on POIs that don't have existing opening_hours data.

**Steps to reproduce**
1. Go to a POI that has the option for opening hours (coffee shop, movie theater, etc).
2. Click on 'Edit Place'
3. Scroll down to Details -> 'Add opening hours'
4. Notice that 'Simple Mode is inactive'. Clicking 'Example Values' shows 'Simple Mode' greyed out.
5. Add a placeholder [Su 10:00+] and click done.
6. Go back into Business Hours to see simple mode reactivated

**Expected behaviour**
Opening Business Hours should display the Simple Mode editor.

**Screenshots**
See video [here](https://owncloud.marshweb.co.nz/s/zfHvaaF0exC0git).

**System information:**
 - Operating system and its version: [iOS 17.5.1]
 - Organic Maps version: [2024.05.20-15]
 - Device Model: [iPhone SE 2022 (A2783)]

**Comment by Swamp2k9** [comment]
I've updated to the latest TestFlight on iOS. Simple Mode is still not appearing. 2024.05.31 (31.30386.52184)

**Comment by biodranik** [comment]
Because now it is impossible to edit opening hours in a simple way on iOS. Did you try to reproduce this bug?

**Comment by kirylkaveryn** [comment]
This bug is caused by the https://github.com/organicmaps/organicmaps/pull/7652


When the empty string and 24h was set method  MakeTimeTableSet  still returns false.
We should cover this method with units tested for such cases.
