### ISSUE TITLE
Missing elevation data above 60 degree north?

### ISSUE THREAD

**Issue by eisams** [organicmaps/organicmaps#830]
### Discussed in https://github.com/organicmaps/organicmaps/discussions/801

<div type='discussions-op-text'>

<sup>Originally posted by **eisams** July  4, 2021</sup>
Does Organic Maps take into elevation data?

I was visiting a cabin where you have to walk a trail that goes up by 50-60 meters. Organic Maps showed it as 0 m elevation change. Interestingly Google Maps does the same for walking instructions, but if you switch to cycling directions Google shows the real incline change

Try location
from: 60.125535, 10.407466
To: 60.130076, 10.412299

Interestingly if I try from my current location (Oslo) I get this elevation map

Maybe it is cut off above 60 degree north?

![B6125111-5BC2-4ECC-B626-04EFBEA7719D](https://user-images.githubusercontent.com/62468530/124396586-bcb01580-dd0a-11eb-9979-642beaf63eeb.png)

**Comment by vng** [comment]
Thanks. Will be fixed in the next data update.

**Comment by eisams** [comment]
This is now fixed!
