### ISSUE TITLE
Enable CarPlay scrolling with pan gesture instead of using four arrow buttons

### ISSUE THREAD

**Issue by YuryBogdanov** [organicmaps/organicmaps#833]
It is much more convenient and precise if you scroll/move map view with your finger instead of using arrow buttons (especially if you are driving)

**Comment by biodranik** [comment]
At the same time, not all cars have a touch screen.

**Comment by lonelymyp** [comment]
О да, прокрутка тыканием в стрелочки жутко неудобна.
