### ISSUE TITLE
Ask for confirmation before downloading world map

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [organicmaps/organicmaps#834]
Automatically downloading world maps at the start of the application could pose security and privacy risks in some situations. It would be much cleaner if the app did not immediately try to access the internet and download stuff.

**Comment by biodranik** [comment]
It only happens on WiFi now. On a cellular connection, it should ask for confirmation.
What case do you think poses security and privacy risks, considering that you've just installed the app using the same WiFi from the app store?

**Comment by IHateTheProgrammingClass** [comment]
@biodranik I think it's more about control. Doesn't matter where I look at it from, it simply does not look good that an app immediately starts downloading a map or anything for that matter after install. I could create some extreme examples if I really think about it but I don't think that's the point. It's just more control that's all.

**Comment by biodranik** [comment]
There should be real-life use cases for your points, otherwise, it sounds strange.

At the first launch after installing the app by downloading it from the store, an automatic map downloading on a WiFi connection, when a user zooms in on his location and expects to see his surroundings, is _extremely_ useful for the majority of users. We introduced this feature many years ago after complaints from many people, and it would be really strange to remove this _useful_ feature without a clear use case.

**Comment by IHateTheProgrammingClass** [comment]
@biodranik I don't know if there's a misunderstanding, but I want to make it clear that I do not want the world map download feature removed. I only want a button or something that triggers the whole download.

Also I disagree that I need an example for a simple suggestion that's not even specific.

I have never heard of an example where a libre app that respects privacy immediately started downloading stuff from the internet after it starts.

This issue is just an idea, if it's too difficult to implement or seem too unnecessary, then please reject and close the issue.

I also disagree that I have to provide an EXAMPLE when I have provided a REASON. But I like stories to here we go:

First though let's consider that the downloader might not even got the app from the same network he's connected to while opening the app. Maybe he opened it later after disconnecting, be cause he or she might have been in a hurry to an airport. Maybe he got the .apk from a friend. Maybe he forgot to disconnect from an insecure free airport network. On that insecure network he could've accidentally or intentionally opened the app. The app sent data over network. [Now insert extreme airport network haxor, IP hunter, TLS certificate spoofer DMV monitors the whole network conspiracy here.] And boom now the user is in Guatemala working as a gardener to a local Maffia leader or idk lol.

At the end of the day I still think it would be a nice feature to allow the user to choose whether or not he wants to download a map on all networks. (Even though the app might deny further access.)

_i had fun btw_

**Comment by GhostInTheKayak** [comment]
Not sure about the Guatemala example above, but maybe just display a popup:
-- "OK to download your first map?" -- maybe with the name of the map.
Responding No could then display some text about turning off the auto-download option and maybe offer to do that.
This would allow the user the option to navigate to a different "home" place before triggering the first download.

**Comment by biodranik** [comment]
@IHateTheProgrammingClass we're listening :)

**Comment by IHateTheProgrammingClass** [comment]
@biodranik Just noticed your reply. What exactly you want me to answer? I stated my opinion and if my idea does not make it @GhostInTheKayak 's is better than nothing.

**Comment by biodranik** [comment]
Sorry if it wasn't clear for you. We fixed the issue, as you proposed.
