### ISSUE TITLE
Road tags causes issues in description 

### ISSUE THREAD

**Issue by ooosssay** [organicmaps/organicmaps#8362]
⚠ Have you searched for similar, already existing issues? Yes

**Describe the issue**
Road tags are shown in description aren’t being shown correctly(?)

**Steps to reproduce**
1. Open Organic Maps
2. Click on a road ([in image if specific](
https://omaps.app/cmKy56JW1P/Interstate_Highway_65))
3. Open details

**Expected behaviour**
The tags to be not shown 

**Screenshots**
![IMG_6723](https://github.com/organicmaps/organicmaps/assets/129241633/1d4bc787-97c7-4241-be9a-99d1d6588c29)

**System information:**
 - Operating system and its version: iOS 17
 - Organic Maps version: Organic Maps version: ⁦2024.05.31-31.30386.52184⁩
 - Device Model: iPhone XR

**Comment by Jean-BaptisteC** [comment]
This issue is know, changes has been reverted here #8354
