### ISSUE TITLE
[android] GPX save on device does not work

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8367]
> On this latest beta, when exporting Bookmark as GPX to local folder, it was saved as xxxx.gpx.kmz and tried to share it back it failed. No issue to the KMZ export.

![image](https://github.com/organicmaps/organicmaps/assets/170263/93ee9fac-2a6d-41c6-9daa-57e4bc98f832)

_Originally posted by @biodranik in https://github.com/organicmaps/organicmaps/issues/8307#issuecomment-2143322907_

**Comment by biodranik** [comment]
@rtsisyk this one is mentioned in the release notes, so it should be fixed. I assume that the fix should be very simple, like adding a missing mime type into an intent.

**Comment by Jean-BaptisteC** [comment]
Fixed by #8366
