### ISSUE TITLE
How to help with public transport routing?

### ISSUE THREAD

**Issue by tannishpage** [organicmaps/organicmaps#837]
All the bus, ferry and train stations are already on the map in my city, with the routes lined out. But I can't access the routing feature, it says "Subway navigation in this region is not available yet". So, what can I do to help out?

**Comment by biodranik** [comment]
You may start from here: https://github.com/organicmaps/organicmaps/blob/master/docs/EXPERIMENTAL_PUBLIC_TRANSPORT_SUPPORT.md

It would be great if more people from the community help us with public transport. It's not an easy task.

**Comment by csidirop** [comment]
Is there a reason why you just added "subway, light rail, monorail and train routes and stops" and no tram or bus routes?

**Comment by biodranik** [comment]
Other developers started to implement the public transport feature (subways) and did not finish it yet. We would gladly finish it with the help of the community.

**Comment by csidirop** [comment]
I get an ModuleNotFound Error for requests. Where do the compiler found that import? 

> File "C:\osmtest\download_gtfs.py", line 15, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'

**Comment by biodranik** [comment]
https://docs.python-requests.org/en/master/user/install/#install

**Comment by csidirop** [comment]
Haha, here you can see my lack of python knowledge. But it seams that i have an other issue, because requests is already installed. 
I'll come back when i've solved that issue

**Comment by csidirop** [comment]
Fixed that other stupid issue. But the script won't work. I used the way without the omd key, mostly because their site is broken and i was not able to login. Here the log:

> ERROR:__main__:HTTP error 401 Client Error: Unauthorized for url: https://api.transit.land/api/v1/feeds/?per_page=50 downloading zip from https://api.transit.land/api/v1/feeds/?per_page=50
ERROR:__main__:HTTP error 401 Client Error: Unauthorized for url: https://api.transit.land/api/v1/feeds/?per_page=50 downloading zip from https://api.transit.land/api/v1/feeds/?per_page=50
ERROR:__main__:Empty urls from C:\osmtest

Looking at https://www.transit.land/ it seams that they need and an API key too:
> Transitland developers: As of June 9, 2021 developers need to include an API key on all requests to the Transitland v1 Datastore API. This will help us to better manage use and ensure all can access Transitland resources with fewer interruptions. Sign-up is free.

**Comment by tannishpage** [comment]
@csidirop Have you been able to make it work with a key? Or does the download_gtfs script need modification for it to work?

**Comment by csidirop** [comment]
@tannishpage no, i took a quick look at the pythonfile and didn't found any parameter for a transitland key (corrct me if i missed something). And since this requirement is new, and the file 6 months old, Im sure it needs modification.

And because this exceeds my nearly non-existent python knowledge, I got nowhere. I could have a look at it this weekend if I find the time, if one of the devs hasn't taken it over by then.

**Comment by tannishpage** [comment]
@csidirop I'll have a go at it. I've got some experience with python

**Comment by csidirop** [comment]
@tannishpage great! Let me know if there is something I can do

**Comment by tannishpage** [comment]
@csidirop I made the modifications to the file and it is working now. It is downloading all the gtfs data from transitland. However, some urls on transitland are causing 403, but that's not really the scripts fault. I'll make a pull request once it finishes running and I'm sure it's not causing any issues.

**Comment by tannishpage** [comment]
I am trying to compile the gtfs_converter.cpp file using cmake. But I keep getting this error. Am I doing something wrong? Are there any instructions on how to compile this?

`CMake Error at CMakeLists.txt:5 (omim_add_executable):
  Unknown CMake command "omim_add_executable".`

**Comment by biodranik** [comment]
Try to build gtfs_converter using CMakeLists.txt at the root of the project.

**Comment by tannishpage** [comment]
@biodranik How would I do that. I've never used cmake before. `cmake --install CMakeLists.txt` This is what I was running before. `cmake --install CMakeLists.txt transit/world_feed/gtfs_converter` I tried this and got the same error.

**Comment by csidirop** [comment]
@tannishpage updated download_gtfs.py works great under Win

**Comment by csidirop** [comment]
Btw, for everyone else trying that: Download can take over over an hour and needs more than 35GB.
But like tannishpage Im stuck with converting the gtfs.

**Comment by biodranik** [comment]
`tools/unix/build_omim.sh world_feed` command should build gtfs_converter

**Comment by tannishpage** [comment]
So I did `./configure`, because `tools/unix/build_omim.sh -r world_feed` asked me to do that. 

When I run `tools/unix/build_omim.sh -r world_feed`, it gives me the following output

```
CMake Warning at CMakeLists.txt:201 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.


CMake Error at CMakeLists.txt:203 (message):
  Qt5 cmake files were not found, please set QT_PATH environment variable


-- Configuring incomplete, errors occurred!
See also "/home/tannishpage/Documents/omim-build-release/CMakeFiles/CMakeOutput.log".
See also "/home/tannishpage/Documents/omim-build-release/CMakeFiles/CMakeError.log".
```

Here is CMakeError.log:

```
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/tannishpage/Documents/omim-build-release/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_0f32c/fast && /usr/bin/make  -f CMakeFiles/cmTC_0f32c.dir/build.make CMakeFiles/cmTC_0f32c.dir/build
make[1]: Entering directory '/home/tannishpage/Documents/omim-build-release/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_0f32c.dir/src.c.o
/usr/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD  -fPIE -std=c11 -o CMakeFiles/cmTC_0f32c.dir/src.c.o -c /home/tannishpage/Documents/omim-build-release/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_0f32c
/snap/cmake/918/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0f32c.dir/link.txt --verbose=1
/usr/bin/cc -fuse-ld=gold  CMakeFiles/cmTC_0f32c.dir/src.c.o -o cmTC_0f32c 
CMakeFiles/cmTC_0f32c.dir/src.c.o:src.c:function main: error: undefined reference to 'pthread_create'
CMakeFiles/cmTC_0f32c.dir/src.c.o:src.c:function main: error: undefined reference to 'pthread_detach'
CMakeFiles/cmTC_0f32c.dir/src.c.o:src.c:function main: error: undefined reference to 'pthread_cancel'
CMakeFiles/cmTC_0f32c.dir/src.c.o:src.c:function main: error: undefined reference to 'pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_0f32c.dir/build.make:99: cmTC_0f32c] Error 1
make[1]: Leaving directory '/home/tannishpage/Documents/omim-build-release/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_0f32c/fast] Error 2


Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/tannishpage/Documents/omim-build-release/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_8495f/fast && /usr/bin/make  -f CMakeFiles/cmTC_8495f.dir/build.make CMakeFiles/cmTC_8495f.dir/build
make[1]: Entering directory '/home/tannishpage/Documents/omim-build-release/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_8495f.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create -fPIE -std=c11 -o CMakeFiles/cmTC_8495f.dir/CheckFunctionExists.c.o -c /snap/cmake/918/share/cmake-3.21/Modules/CheckFunctionExists.c
Linking C executable cmTC_8495f
/snap/cmake/918/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8495f.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create -fuse-ld=gold  CMakeFiles/cmTC_8495f.dir/CheckFunctionExists.c.o -o cmTC_8495f  -lpthreads 
/usr/bin/ld.gold: error: cannot find -lpthreads
CMakeFiles/cmTC_8495f.dir/CheckFunctionExists.c.o:CheckFunctionExists.c:function main: error: undefined reference to 'pthread_create'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_8495f.dir/build.make:99: cmTC_8495f] Error 1
make[1]: Leaving directory '/home/tannishpage/Documents/omim-build-release/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_8495f/fast] Error 2
```

I'm running Elementary OS 6. Not really sure what to do

**Comment by biodranik** [comment]
Did you install qt5 dev package?

**Comment by tannishpage** [comment]
Ok, so I installed qt5 dev packages and everything worked nicely. I've generatred the json files using 
`./gtfs_converter --path_mapping=mapping.txt --path_mapping_edges=mapping_edges.txt --path_gtfs_feeds=dir_for_storing_feeds --path_json=result_json_dir --path_resources=./data` 

Step 3 is asking me to find a file called `map_generator.ini` which I can't seem to fine.

**Comment by biodranik** [comment]
There is a link to the doc in my link above:

https://github.com/organicmaps/organicmaps/blob/master/tools/python/maps_generator/README.md

**Comment by biodranik** [comment]
Here is the list of OpenStreetMap metro/subways validation results:

https://maps.mail.ru/osm/tools/subways/latest/
or
https://alexey-zakharenkov.github.io/subways/rapid/

You can help us by fixing red metro lines directly in OpenStreetMap. Then every @OrganicMaps user will have an updated Public Transport map (subways and S-Bahn at the moment).

Some general instructions are here:

https://wiki.openstreetmap.org/wiki/Metro_Mapping

And here is info how to validate a separate city: 

https://github.com/alexey-zakharenkov/subways/

**Comment by contrapunctus-1** [comment]
Does this issue include implementation of PT routing based on OSM (rather than GTFS) route data? Many important modes of transport (e.g. share taxis) are only available as OSM relations...

**Comment by biodranik** [comment]
@contrapunctus-1 let's discuss and plan it!

**Comment by julianfairfax** [comment]
GNOME Maps uses https://transport.opendata.ch/ for Switzerland. Hopefully this'll make its way into Transportr at some point soon (see https://github.com/grote/Transportr/issues/768), but it could also be used here, as it works perfectly fine in GNOME Maps.

**Comment by yellowhat** [comment]
Hi,
I am trying to run `gtfs_converter`, this is what I run on Fedora 35:

```bash
dnf install -y gcc g++ cmake qt5-qtbase-devel qt5-qtsvg-devel zlib-devel libicu-devel freetype-devel git python python-requests

git clone https://github.com/organicmaps/organicmaps --depth 1
cd organicmaps
git submodule update --init --recursive

./configure.sh
tools/unix/build_omim.sh -r world_feed
```

But still `gtfs_converter` is not compiled:

```bash
$ find . -iname "gtfs_*"
./transit/world_feed/gtfs_converter
./transit/world_feed/gtfs_converter/gtfs_converter.cpp
```

Does anyone have an end-to-end script to compile the "full public transport support".

Thanks

**Comment by biodranik** [comment]
Dis you try to use gtfs_converter target instead?

**Comment by yellowhat** [comment]
```bash
$ dnf install -y gcc g++ cmake qt5-qtbase-devel qt5-qtsvg-devel zlib-devel libicu-devel freetype-devel git python python-requests
$ git clone https://github.com/organicmaps/organicmaps --depth 1
$ cd organicmaps
$ git submodule update --init --recursive
$ cd transit/world_feed/gtfs_converter
$ cmake .
-- The C compiler identification is GNU 11.3.1
-- The CXX compiler identification is GNU 11.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:3 (omim_add_executable):
  Unknown CMake command "omim_add_executable".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.22)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.
$ cd ../../../
$ ./configure.sh
$ tools/unix/build_omim.sh -r world_feed                     
$ cmake transit/world_feed/gtfs_converter
CMake Error at CMakeLists.txt:3 (omim_add_executable):
  Unknown CMake command "omim_add_executable".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.22)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
```

**Comment by biodranik** [comment]
Wait wait wait. I meant running `tools/unix/build_omim.sh -r` with the right target.

Or call cmake manually for the root, and specify target for the make.

**Comment by yellowhat** [comment]
```bash
$ dnf install -y gcc g++ cmake qt5-qtbase-devel qt5-qtsvg-devel zlib-devel libicu-devel freetype-devel git python python--requests
$  dnf install protobuf-devel boost-devel
$ git clone https://github.com/organicmaps/organicmaps --depth 1
$ cd organicmaps
$ git submodule update --init --recursive
$ tools/unix/build_omim.sh -r gtfs_converter
...
[ 71%] Linking CXX static library ../libindexer.a
[ 71%] Built target indexer
[ 74%] Building CXX object editor/CMakeFiles/editor.dir/Unity/unity_0_cxx.cxx.o
In file included from /usr/include/boost/geometry/strategies/geographic/distance.hpp:38,
                 from /usr/include/boost/geometry/strategies/strategies.hpp:91,
                 from /usr/include/boost/geometry/geometry.hpp:58,
                 from /usr/include/boost/geometry.hpp:17,
                 from /root/organicmaps/geometry/intersection_score.hpp:16,
                 from /root/organicmaps/editor/feature_matcher.cpp:3,
                 from /root/omim-build-release/editor/CMakeFiles/editor.dir/Unity/unity_0_cxx.cxx:17:
/usr/include/boost/geometry/geometries/point_xy.hpp: In member function ‘void boost::geometry::model::d2::point_xy<CoordinateType, CoordinateSystem>::x(const CoordinateType&)’:
/usr/include/boost/geometry/geometries/point_xy.hpp:69:27: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Key, class _Compare, class _Alloc> class std::set’
   69 |     { this->template set<0>(v); }
      |                           ^
/usr/include/boost/geometry/geometries/point_xy.hpp:69:27: note:   expected a type, got ‘0’
/usr/include/boost/geometry/geometries/point_xy.hpp:69:27: error: template argument 2 is invalid
/usr/include/boost/geometry/geometries/point_xy.hpp:69:27: error: template argument 3 is invalid
/usr/include/boost/geometry/geometries/point_xy.hpp: In member function ‘void boost::geometry::model::d2::point_xy<CoordinateType, CoordinateSystem>::y(const CoordinateType&)’:
/usr/include/boost/geometry/geometries/point_xy.hpp:73:27: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Key, class _Compare, class _Alloc> class std::set’
   73 |     { this->template set<1>(v); }
      |                           ^
/usr/include/boost/geometry/geometries/point_xy.hpp:73:27: note:   expected a type, got ‘1’
/usr/include/boost/geometry/geometries/point_xy.hpp:73:27: error: template argument 2 is invalid
/usr/include/boost/geometry/geometries/point_xy.hpp:73:27: error: template argument 3 is invalid
In file included from /usr/include/boost/geometry/geometries/geometries.hpp:28,
                 from /usr/include/boost/geometry/io/svg/svg_mapper.hpp:43,
                 from /usr/include/boost/geometry/geometry.hpp:127:
/usr/include/boost/geometry/geometries/point_xyz.hpp: In member function ‘void boost::geometry::model::d3::point_xyz<CoordinateType, CoordinateSystem>::x(const CoordinateType&)’:
/usr/include/boost/geometry/geometries/point_xyz.hpp:68:27: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Key, class _Compare, class _Alloc> class std::set’
   68 |     { this->template set<0>(v); }
      |                           ^
/usr/include/boost/geometry/geometries/point_xyz.hpp:68:27: note:   expected a type, got ‘0’
/usr/include/boost/geometry/geometries/point_xyz.hpp:68:27: error: template argument 2 is invalid
/usr/include/boost/geometry/geometries/point_xyz.hpp:68:27: error: template argument 3 is invalid
/usr/include/boost/geometry/geometries/point_xyz.hpp: In member function ‘void boost::geometry::model::d3::point_xyz<CoordinateType, CoordinateSystem>::y(const CoordinateType&)’:
/usr/include/boost/geometry/geometries/point_xyz.hpp:72:27: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Key, class _Compare, class _Alloc> class std::set’
   72 |     { this->template set<1>(v); }
      |                           ^
/usr/include/boost/geometry/geometries/point_xyz.hpp:72:27: note:   expected a type, got ‘1’
/usr/include/boost/geometry/geometries/point_xyz.hpp:72:27: error: template argument 2 is invalid
/usr/include/boost/geometry/geometries/point_xyz.hpp:72:27: error: template argument 3 is invalid
/usr/include/boost/geometry/geometries/point_xyz.hpp: In member function ‘void boost::geometry::model::d3::point_xyz<CoordinateType, CoordinateSystem>::z(const CoordinateType&)’:
/usr/include/boost/geometry/geometries/point_xyz.hpp:76:27: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Key, class _Compare, class _Alloc> class std::set’
   76 |     { this->template set<2>(v); }
      |                           ^
/usr/include/boost/geometry/geometries/point_xyz.hpp:76:27: note:   expected a type, got ‘2’
/usr/include/boost/geometry/geometries/point_xyz.hpp:76:27: error: template argument 2 is invalid
/usr/include/boost/geometry/geometries/point_xyz.hpp:76:27: error: template argument 3 is invalid
make[3]: *** [editor/CMakeFiles/editor.dir/build.make:76: editor/CMakeFiles/editor.dir/Unity/unity_0_cxx.cxx.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:3337: editor/CMakeFiles/editor.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:6208: transit/world_feed/gtfs_converter/CMakeFiles/gtfs_converter.dir/rule] Error 2
```

**Comment by biodranik** [comment]
Please disable unity builds. The fix is in progress.

**Comment by biodranik** [comment]
Please check the cmake build output, the first few lines.

**Comment by yellowhat** [comment]
```console
Ninja is not found, using make instead
-- The C compiler identification is GNU 12.1.1
-- The CXX compiler identification is GNU 12.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using ld.gold
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for getpagesize
-- Looking for getpagesize - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for getrandom
-- Looking for getrandom - found
-- Looking for arc4random_buf
-- Looking for arc4random_buf - not found
-- Looking for arc4random
-- Looking for arc4random - not found
-- Looking for 4 include files stdlib.h, ..., float.h   
-- Looking for 4 include files stdlib.h, ..., float.h - found
-- Looking for off_t
-- Looking for off_t - not found
-- Looking for size_t
-- Looking for size_t - not found
-- Performing Test HAVE_SYSCALL_GETRANDOM
-- Performing Test HAVE_SYSCALL_GETRANDOM - Success
-- Performing Test FLAG_NO_STRICT_ALIASING
-- Performing Test FLAG_NO_STRICT_ALIASING - Success
-- Performing Test FLAG_VISIBILITY
-- Performing Test FLAG_VISIBILITY - Success
-- ===========================================================================
-- 
-- Configuration
--   Prefix ..................... /usr/local
--   Build type ................. Release
--   Shared libraries ........... OFF
--   Character type ............. char (UTF-8)
-- 
--   Build documentation ........ OFF
--   Build examples ............. OFF
--   Build fuzzers .............. OFF
--   Build tests ................ OFF
--   Build tools (xmlwf) ........ OFF
--   Build pkg-config file ...... OFF
--   Install files .............. OFF
-- 
--   Features
--     // Advanced options, changes not advised 
--     Attributes info .......... OFF
--     Context bytes ............ 1024
--     DTD support .............. ON
--     Large size ............... OFF
--     Minimum size ............. OFF
--     Namespace support ........ ON
-- 
-- 
-- ===========================================================================
-- Looking for C++ include fnmatch.h
-- Looking for C++ include fnmatch.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Looking for strtoll
-- Looking for strtoll - found
-- Found the following ICU libraries:
--   uc (required)
--   i18n (required)
--   data (required)
-- Found ICU: /usr/include (found version "69.1") 
-- Found Freetype: /usr/lib64/libfreetype.so (found version "2.12.1") 
-- Found Python3: /usr/bin/python3.10 (found version "3.10.5") found components: Interpreter 
-- Found OpenGL: /usr/lib64/libOpenGL.so   
-- Found Python: /usr/bin/python3.10 (found version "3.10.5") found components: Interpreter 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/omim-build-release

[  2%] Building C object 3party/expat/expat/CMakeFiles/expat.dir/Unity/unity_0_c.c.o
[  2%] Building CXX object routing_common/CMakeFiles/routing_common.dir/Unity/unity_0_cxx.cxx.o
[  5%] Building CXX object 3party/pugixml/CMakeFiles/pugixml.dir/Unity/unity_0_cxx.cxx.o
[  5%] Building CXX object 3party/gflags/CMakeFiles/gflags_nothreads_static.dir/Unity/unity_0_cxx.cxx.o
[  5%] Building CXX object 3party/bsdiff-courgette/CMakeFiles/bsdiff.dir/Unity/unity_0_cxx.cxx.o
[  5%] Building CXX object 3party/succinct/CMakeFiles/succinct.dir/Unity/unity_0_cxx.cxx.o
[  5%] Building CXX object transit/CMakeFiles/transit.dir/Unity/unity_0_cxx.cxx.o
[  5%] Building CXX object 3party/minizip/CMakeFiles/minizip.dir/Unity/unity_0_cxx.cxx.o
[  5%] Building CXX object 3party/jansson/CMakeFiles/jansson.dir/Unity/unity_0_cxx.cxx.o
[  8%] Building C object 3party/libtess2/CMakeFiles/tess2.dir/Unity/unity_0_c.c.o
[  8%] Building CXX object 3party/liboauthcpp/CMakeFiles/oauthcpp.dir/Unity/unity_0_cxx.cxx.o
[  8%] Building CXX object 3party/open-location-code/CMakeFiles/openlocationcode.dir/Unity/unity_0_cxx.cxx.o
[  8%] Building CXX object ge0/CMakeFiles/ge0.dir/Unity/unity_0_cxx.cxx.o
[  8%] Building CXX object 3party/opening_hours/CMakeFiles/opening_hours.dir/Unity/unity_0_cxx.cxx.o
[  8%] Building CXX object indexer/protobuf/CMakeFiles/protobuf.dir/Unity/unity_0_cxx.cxx.o
[ 11%] Building CXX object base/CMakeFiles/base.dir/Unity/unity_0_cxx.cxx.o
[ 11%] Building C object 3party/minizip/CMakeFiles/minizip.dir/Unity/unity_0_c.c.o
[ 14%] Linking CXX static library ../../libopenlocationcode.a

$ tools/unix/build_omim.sh -h
This tool builds Organic Maps
Usage: tools/unix/build_omim.sh [-d] [-r] [-c] [-x] [-s] [-t] [-a] [-g] [-j] [-l] [-p PATH] [-n NUM] [target1 target2 ...]

By default both debug and release versions are built in ../omim-build-<buildtype> dir.

-d  Build debug version
-r  Build release version
-x  Use precompiled headers
-c  Clean before building
-s  Skip desktop app building
-t  Build designer tool (only for MacOS X platform)
-a  Build standalone desktop app (only for MacOS X platform)
-g  Force use GCC (only for MacOS X platform)
-p  Directory for built binaries
-n  Number of parallel processes
-j  Generate compile_commands.json
-l  Launches built binary(ies), useful for tests
```

I can see Unity being compiled but I cannot find the option to disable it.

Thanks

**Comment by biodranik** [comment]
`Using unity builds, pass -DUNITY_DISABLE=ON to disable it.`

**Comment by thinkoid** [comment]
> ```[...]
> /usr/include/boost/geometry/geometries/point_xyz.hpp: In member function ‘void boost::geometry::model::d3::point_xyz<CoordinateType, CoordinateSystem>::x(const CoordinateType&)’:
> /usr/include/boost/geometry/geometries/point_xyz.hpp:68:27: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Key, class _Compare, class _Alloc> class std::set’
>    68 |     { this->template set<0>(v); }
>       |                           ^
 ```

FWIW clang does not have this bug. I built the desktop app with it.

**Comment by yellowhat** [comment]
I am able to compile it using `CMAKE_CONFIG="-DUNITY_DISABLE=ON" tools/unix/build_omim.sh -c -r gtfs_converter`, the binary is under `../omim-build-release/gtfs_converter` (took some time to find out).

While using the `download_gtfs.py` script seems that this [line](https://github.com/organicmaps/organicmaps/blob/ab568b42d56d932a6a62a32fd39069e89e68434b/tools/python/transit/gtfs/download_gtfs.py#L63) needs to be changed to `if feed["spec"].lower() != "gtfs":` as now the value for `feed["spec"]` is `GTFS` not `gtfs`, not sure why.

**Comment by gerion0** [comment]
Just want to mention [KPublicTransport](https://github.com/KDE/kpublictransport) here which is a C++/Qt library from the KDE project that provides (online) public transport routing.

**Comment by koenvanhollebeke** [comment]
I am not able to execute the gtfs_converter: getting stuck by how to specify the file:///path/to/file for the dir_for_storing_feeds, result_json_dir & path_resources. See below.

./gtfs_converter --path_mapping=mapping.txt --path_mapping_edges=mapping_edges.txt --path_gtfs_feeds=dir_for_storing_feeds --path_json=result_json_dir --path_resources=./data
LOG TID(1) WARNING 2.484e-05 gtfs_converter/gtfs_converter.cpp:295 main(): Some paths set in options are not valid. Check the directories: dir_for_storing_feeds result_json_dir ./data
gtfs_converter: Reads GTFS feeds or subway transit.json, produces json with global ids for generator.

Executing the gtfs_converter from ~/omim-build-release$ in Ubuntu 22.04. How to define those locations? "file:///path/to/file" doesn't work either:

./gtfs_converter --path_mapping=mapping.txt --path_mapping_edges=mapping_edges.txt --path_gtfs_feeds="file:///home/koenvh/Downloads/" --path_json="file:///home/koenvh/Downloads/" --path_resources="file:///home/koenvh/omim-build-release/data/"
LOG TID(1) WARNING 3.4137e-05 gtfs_converter/gtfs_converter.cpp:295 main(): Some paths set in options are not valid. Check the directories: file:///home/koenvh/Downloads/ file:///home/koenvh/Downloads/ file:///home/koenvh/omim-build-release/data/
gtfs_converter: Reads GTFS feeds or subway transit.json, produces json with global ids for generator.

**Comment by koenvanhollebeke** [comment]
> I am not able to execute the gtfs_converter: getting stuck by how to specify the file:///path/to/file for the dir_for_storing_feeds, result_json_dir & path_resources. See below.
> 
> ./gtfs_converter --path_mapping=mapping.txt --path_mapping_edges=mapping_edges.txt --path_gtfs_feeds=dir_for_storing_feeds --path_json=result_json_dir --path_resources=./data LOG TID(1) WARNING 2.484e-05 gtfs_converter/gtfs_converter.cpp:295 main(): Some paths set in options are not valid. Check the directories: dir_for_storing_feeds result_json_dir ./data gtfs_converter: Reads GTFS feeds or subway transit.json, produces json with global ids for generator.
> 
> Executing the gtfs_converter from ~/omim-build-release$ in Ubuntu 22.04. How to define those locations? "file:///path/to/file" doesn't work either:
> 
> ./gtfs_converter --path_mapping=mapping.txt --path_mapping_edges=mapping_edges.txt --path_gtfs_feeds="file:///home/koenvh/Downloads/" --path_json="file:///home/koenvh/Downloads/" --path_resources="file:///home/koenvh/omim-build-release/data/" LOG TID(1) WARNING 3.4137e-05 gtfs_converter/gtfs_converter.cpp:295 main(): Some paths set in options are not valid. Check the directories: file:///home/koenvh/Downloads/ file:///home/koenvh/Downloads/ file:///home/koenvh/omim-build-release/data/ gtfs_converter: Reads GTFS feeds or subway transit.json, produces json with global ids for generator.

Solved: the correct formatting is
./gtfs_converter --path_mapping=mapping.txt --path_mapping_edges=mapping_edges.txt --path_gtfs_feeds=/home/koenvh/Downloads/ --path_json=/home/koenvh/Downloads/ --path_resources=/home/koenvh/omim-build-release/data/

**Comment by endim8** [comment]
> I think that since we have a common goal, **it might be appropriate to join forces**: The goal is to provide efficient, up-to-date, free and privacy-friendly public transport routing! So I know, the technologies used are not the same (PublicTransportEnabler vs GTFS, Android vs Multiplatform, different licenses...). But maybe there could be some joint efforts or reflections!
> 
> That's it for my ideas, I look forward to your thoughts :)


YES!! I was following the Transportr revival, and wishing it could be integrated into OM in some way! 😄 
CC @biodranik @vng @rtsisyk this would be great

**Comment by gerion0** [comment]
public-transport-enabler (is btw also used by and written for [Öffi](https://oeffi.schildbach.de/index.html)) is written in Java. I would expect that to be a major drawback in integrating it. Maybe some kind of sharing would be possible, so to "export" a route from Transportr to OM but that needs a [proper sharing format](https://github.com/grote/Transportr/issues/787). The already linked KPublicTransport library is basically an already existing rewrite in C++/Qt (the same technology used by OM).

There also exists an Android/KDE/Qt app [KTrip](https://github.com/KDE/ktrip) that clones the features of Transportr/Öffi but without the nice GUI (at least the last time I checked that, installing is a bit of a pity, [check this out](https://community.kde.org/Android/FDroid#KDE_F-Droid_Release_Repository)). Anyway, it implements lots of the same APIs for querying public transport services.

**Comment by dikkechill** [comment]
@biodranik 
Would it be an idea to create a list of specific tasks - as in other 'master issue tickets e.g. for navigation' - that need to be done by people from the community?
* Which parts needs to be tested exactly?
* What still needs to be added to make GTFS work in generally in OrganicMaps?
* Which known bugs still need to be fixed?

**Comment by biodranik** [comment]
Creating a meta issue that links to subtasks is a good idea.

Our experience and current vision of the architecture is:

- Server collects schedules from different sources. Efficient implementation in golang, rust or C++ is preferred for easier scaling and maintenance.
- Different formats are converted to the universal one that can be read by Organic Maps and other clients to allow the following functionality:
- Clients are periodically updating schedule info, that is cached on them and can be used offline, if there is no connection. With the connection real-time info is available.
- Clients build routes from this schedule info offline.
- To scale efficiently, this format should be compact and easily cacheable on HTTP CDN.

There are many subtasks here, feel free to go deeper.

The main goal is to make a worldwide public transport routing better than Google, that is open-source and available to everyone. Development and support can be sponsored by cities and countries, by funds, and by the community.

**Comment by dikkechill** [comment]
> Creating a meta issue that links to subtasks is a good idea.
> 

Added a meta issue https://github.com/organicmaps/organicmaps/issues/5331 to collect all subtasks to implement public transport routing, please feel free to add

**Comment by biodranik** [comment]
Closing this issue in favor of #5331
