### ISSUE TITLE
Replace round checkboxes with square ones in the editor

### ISSUE THREAD

**Issue by euf** [organicmaps/organicmaps#8389]
RadiOn/Off buttons aka round checkboxes (see #7805) are confusing. 

**Square** checkboxes and **round** radio buttons should be preferred.

I've drawn two SVGs to replace round checkboxes in an editor. 

@kirylkaveryn @biodranik 
 
![check-empty](https://github.com/organicmaps/organicmaps/assets/11754264/595bb23c-ef1b-4286-a49a-57e23c41a79b)
![check-fill](https://github.com/organicmaps/organicmaps/assets/11754264/6cf455d6-1b08-4523-ab83-fc8118d7b6be)

**Comment by biodranik** [comment]
Great point :) I never mentioned it before.
