### ISSUE TITLE
Garden disappears after zooming in 

### ISSUE THREAD

**Issue by k1wiosm** [organicmaps/organicmaps#839]
`leisure=garden` disappears after zooming in 

https://www.openstreetmap.org/way/117484994

Zoomed out:

![](https://user-images.githubusercontent.com/8932566/125187619-c36de980-e230-11eb-840b-88b43764400f.jpeg)

Zoomed in:

![](https://user-images.githubusercontent.com/8932566/125187628-d2549c00-e230-11eb-9eaf-3d1d88e701b1.jpeg)

**Comment by biodranik** [comment]
Please check its visibility by grepping files in the data folder.
