### ISSUE TITLE
Adding support for `waste=cigarettes` (badge on `waste_basket`) tag ?

### ISSUE THREAD

**Issue by Arthur-GYT** [organicmaps/organicmaps#8393]
**Is your feature request related to a problem? Please describe.**

As with drinking water fountains, wouldn't it be a good idea to use a badge to indicate that certain garbage cans have an integrated ashtray?

**Comment by Misalf-git** [comment]
Can't extinguished roaches be disposed at any waste basket? I doubt anyone would search for a waste basket with an integrated ash tray in order to stand there and smoke.

**Comment by biodranik** [comment]
There is a simple yet powerful criterion for getting "would it be useful..." answer quickly:

Is this feature needed for your parents and grandparents? Will they discover it and use it without any issues?

**Comment by Arthur-GYT** [comment]
> Can't extinguished roaches be disposed at any waste basket? I doubt anyone would search for a waste basket with an integrated ash tray in order to stand there and smoke.

In this case, why indicate the types of waste for the recycling points?

**Comment by Arthur-GYT** [comment]
> There is a simple yet powerful criterion for getting "would it be useful..." answer quickly:
> 
> Is this feature needed for your parents and grandparents? Will they discover it and use it without any issues?

I don't know. In view of the messages on my last PR (justified, I do not question them), I take the liberty of asking. For me it would be a plus for those who want to try to sort their waste.

**Comment by Misalf-git** [comment]
> > Can't extinguished roaches be disposed at any waste basket? I doubt anyone would search for a waste basket with an integrated ash tray in order to stand there and smoke.
> 
> In this case, why indicate the types of waste for the recycling points?

In my area there are many recycling containers for either glass bottles or clothes - very different from one another.

Waste baskets in my area often have a small extra opening for cigarettes that prevents the other trash from burning (and encourages to refrain from just dropping cigarettes on the sidewalk).

Maybe I just don't get your point.
