### ISSUE TITLE
[ios] App hangs when a bookmark is selected on the map

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8416]
1. Add a bookmark to a list with a long name with non-Latin letters.
2. Select this bookmark on the map.
3. Observe that the app hangs.

The same issue stably reproduces on 24.5.31, production 24.6.2 and the latest testflight master 24.6.8 versions.

**Comment by biodranik** [comment]
The same issue stably reproduces on 24.5.31, production 24.6.2 and the latest testflight master 24.6.8 versions.

**Comment by kirylkaveryn** [comment]
![image](https://github.com/organicmaps/organicmaps/assets/79797627/b6126fcb-3743-4a93-be38-8c4e2a6f9963)

![image](https://github.com/organicmaps/organicmaps/assets/79797627/cbff3e4f-97ff-46ca-aa4d-8093d0253f36)

**Comment by kirylkaveryn** [comment]
Let's limit the number of line for the title and subtitle by 3.

**Comment by biodranik** [comment]
Is the issue caused by a not-imited line length? Can it be fixed without limiting the displayed length?
