### ISSUE TITLE
Parcel Machine

### ISSUE THREAD

**Issue by devhost97** [organicmaps/organicmaps#8430]
Have you thought about adding a parcel locker category in the search?
More and more machines of this type appear in the world and they are displacing post offices in favor of convenience.

OSM get the category named Parcel Locker

**Comment by RedAuburn** [comment]
they should already be searchable, is there a specific case where it's not working?

**Comment by vng** [comment]
Try to enter "parcel locker" in search.

**Comment by devhost97** [comment]
It's working locally but i am looking for long distance searching.
For example i am in travel and i am looking for machine i cannot search by name definied as "Ref" on OSM.

**Comment by vng** [comment]
Could you please give the example of OSM Poi you are looking for and the search query?

**Comment by devhost97** [comment]
When you are looking for KRA204M its doesn’t find, but when you search for parcel locker it find nearest to the map location you have on the view.

Due to the inability to search using the "Ref" tag - i.e. in this case KRA204M cannot be set on the map after this name, it makes navigation difficult if we are in a foreign city and we only know the signature of a given machine.

https://www.openstreetmap.org/node/8809812080#map=18/50.07025/20.04104&layers=N

![IMG_1948](https://github.com/organicmaps/organicmaps/assets/25454629/840cb182-3d69-4767-a1f5-dbe9fbb73cc9)
![IMG_1947](https://github.com/organicmaps/organicmaps/assets/25454629/55012f4e-6df1-4fc7-ba02-1e3fa8d69966)
![IMG_1946](https://github.com/organicmaps/organicmaps/assets/25454629/e1613b0c-e1fd-47ee-8931-2e53832445f7)
![IMG_1945](https://github.com/organicmaps/organicmaps/assets/25454629/bebcd80b-f0f9-4fa4-bf9e-bd75f7793621)
![IMG_1944](https://github.com/organicmaps/organicmaps/assets/25454629/5a28d731-55bd-4b49-806a-fec85446960c)

**Comment by vng** [comment]
Well, when a name tag is empty, we usually assign the ref as a name. Should check what happens here.
