### ISSUE TITLE
Display search hints (search suggestions) without waiting for search to finish

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8439]
Now blue hints appear only when the search finishes. For faster search and to teach users about our search synonyms, hints should be displayed instantly, without waiting.

An obvious improvement is to automatically hint some matching synonyms, without marking them explicitly with a number prefix (there already was an issue about it, right?).

**Comment by pastk** [comment]
> there already was an issue about it, right?

- yeap, this duplicates https://github.com/organicmaps/organicmaps/issues/1641
