### ISSUE TITLE
[CarPlay] Hide inactive traffic icon

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8449]
We may implement it later, now it only confuses users:

![image](https://github.com/organicmaps/organicmaps/assets/170263/0d2d9915-e819-4a90-acd2-37328532ec6b)

CC @kirylkaveryn @fabwu

**Comment by fabwu** [comment]
@biodranik So you want us to remove the traffic light symbol?

![image](https://github.com/organicmaps/organicmaps/assets/6050639/b9d49709-d8a1-441d-afb4-21dcb8f56eaa)

**Comment by biodranik** [comment]
Yes please )

**Comment by Jean-BaptisteC** [comment]
Duplicate of #868
