### ISSUE TITLE
Voice navigation instructions in Chinese

### ISSUE THREAD

**Issue by felixng1988** [organicmaps/organicmaps#8477]
Today, while using Organic Maps navigation, I noticed some odd Chinese voice prompts. For instance, during roundabouts it said "取道第 x 个出口", which sounded strange. So, I changed it to "从第 x 个出口驶出" and also corrected other voice prompt translations. I found these strings in the latest Beta Organic Maps apk at /assets/sound-strings/ and modified them, I hope to replace this string file in the next version of Organic Maps 😌
Strings files:
https://t.me/organicmaps/41559
https://t.me/organicmaps/41560

**Comment by zyphlar** [comment]
@felixng1988 did this get fixed? Sorry for the delays

**Comment by felixng1988** [comment]
> @felixng1988 did this get fixed? Sorry for the delays

Yes, it was fixed a long time ago
