### ISSUE TITLE
FR : Add tooltips when long-pressing on icons

### ISSUE THREAD

**Issue by GLLM** [organicmaps/organicmaps#848]
Hello,

I believe the marlet practices is to add tooltip when long-pressing icons in Android apps.
For example, I was  planning an itinerary and wondered what the star (bookmark ?) icon in the first 3rd of the left part of the screen meant. I long-pressed ... to no avail.

None if the shortcut have tooltips on long-presses. I think it's a nice to have for user friendlyness.

Thanks
GLLM

**Comment by Jean-BaptisteC** [comment]
Duplicate of #6638
