### ISSUE TITLE
Android Auto turn directions are off by one

### ISSUE THREAD

**Issue by dead10ck** [organicmaps/organicmaps#8480]
**Describe the issue**

During navigation on Android Auto, the UI shows the next two turn directions, with the next one being bigger, and the one after being smaller. However, the order of the instructions seems to be wrong.

The bigger instruction shows the street one is currently on, i.e. the street from the previous turn direction, and the small direction underneath which is supposed to be the direction after next instead shows the next street one is supposed to turn on. 

But to add to the confusion, the icon displayed for the type of turn in the upcoming directions is correct. So to get the directions, one has to look at the big icon to know which direction to turn, and the street name from the smaller UI component to see what to turn onto.

Here is an example I took while driving. Here, the directions were: 

1. Turn right onto US 4 North Greenbush Road
2. Turn left onto NY 43
3. Turn right onto Best Road

After one is on US 4 North Greenbush Road, the directions displayed say the next step is to turn left on US 4 North Greenbush Road, and the step after is to continue onto NY 43.

![PXL_20240616_160525680](https://github.com/organicmaps/organicmaps/assets/846275/2f3ebd5f-2e1f-4107-a693-3330e548f156)

This problem is generalized: it happens everywhere for every route. It does not happen using the regular smartphone UI.

**Steps to reproduce**

Do any navigation with Android Auto.

**System information:**

 - Operating system and its version: Android 14
 - Organic Maps version: version 2024.06.02-12-Google
 - Device Model: Pixel 8 Pro

**Additional context**
Please add any other context or comments here that may be useful.

**Comment by davetapley** [comment]
Yep, first time using it and I was very confused until I realized what was happening 🤪 

Android 14
2024.06.19-3-Google
Galaxy A54

![20240710_194124](https://github.com/organicmaps/organicmaps/assets/48232/dc7f5fd3-b82c-40c6-b200-6d52a2e7480c)

**Comment by davetapley** [comment]
New to code base but couldn't help 👀 

I _presume_ this? Which looks correct 🤔 

https://github.com/organicmaps/organicmaps/blob/fecccafba4e17757c9aac9da3c8956d2ffd5619a/android/app/src/main/java/app/organicmaps/car/util/RoutingUtils.java#L62-L67

https://github.com/organicmaps/organicmaps/blob/fecccafba4e17757c9aac9da3c8956d2ffd5619a/android/app/src/main/java/app/organicmaps/car/util/RoutingUtils.java#L86-L90


But I don't know where `info` comes from 🤪

**Comment by biodranik** [comment]
@zyphlar could it be a regression caused by your changes?

@AndrewShkrob what's the difference in the directions code between the main app and AA?

**Comment by zyphlar** [comment]
@davetapley hi Dave! Keep it dangerous 🏴‍☠️

@biodranik I don't think my TTS changes affected this, it's almost certainly a Java difference and plain off-by-one error. The fact that it's in /car/ and not regular should be a huge clue

**Comment by biodranik** [comment]
Yet another example:

> Please see the attached image.  It will show you a turn in 50 m, and Angeleno Avenue.  I am driving on Angeleno Avenue and what should be showing is a recommended turn on Glenoaks in 50 m., then a left Turn on Tujunga Ave (not shown).

![telegram-cloud-photo-size-2-5267460617982302458-y](https://github.com/user-attachments/assets/6c5c09f1-addd-40c6-9626-6e955d0ace01)

**Comment by biodranik** [comment]
This issue makes directions in AA unusable. Any help fixing this issue is appreciated.

CC @AndrewShkrob @rtsisyk
