### ISSUE TITLE
Filter filter search results by region

### ISSUE THREAD

**Issue by grahamjpark** [organicmaps/organicmaps#8501]
⚠ Have you searched for similar, already existing issues? Yes. Slight related, but not the same as https://github.com/organicmaps/organicmaps/issues/6442

**Is your feature request related to a problem? Please describe.**
Recently I went a bit crazy downloading maps. In part because I installed an SD card expansion in my phone, but also because I wanted to start using OM to save potential places to visit while traveling in other countries. A side effect of this has been that my searches are dramatically slower. I just tested searching for a restaurant in my area and it took ~50 seconds to return the results.

**Describe the ideal solution**
It would be nice to filter which maps to search. There could be a filter button in the search bar that presents a drop down of downloaded map areas. I could leave this filter on for my country most of the time, but then I could either remove the filter or change the filter when I hear a recommendation in another area that I want to save.

**Describe alternatives you have considered**
Other apps don't run the query locally, so they don't have the same issue. They also may have more advance natural language processing so if I pass a country name they automatically prioritize searching that country.

**Comment by biodranik** [comment]
1. Organic Maps understands a country name in the search. If it doesn't, please report it.
2. The search prioritizes the place where you are looking (viewport) and your current location.
3. Users don't expect any complex UI to filter where to search. Users expect the right search results. So our goal is to provide the best results without any additional complex user actions.
4. It looks like your SD card is very slow. 50 seconds for a local search is toooooo much.

**Comment by grahamjpark** [comment]
Thanks for the quick response. I'll try moving the maps to on-device storage and comparing the time. I'll also comparing timing when passing the country in the search.

**Comment by grahamjpark** [comment]
Moving to on device storage rapidly sped up the searches. Interestingly, I also noticed that the results came 1 at a time instead of all at once like it was on SD. Closing the issue though as it seems like the SD card was the issue.

Btw. Appreciate you pushing for things like point 3. Keeping it from becoming a clunky piece of software that scares off non-technical users.
