### ISSUE TITLE
"Eiffel Tower" returns unrelated results from around the World, but not from Paris (unless its in viewport)

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#8521]
I have Paris map downloaded.
The viewport is centered e.g. on Moscow.

![Eiffel_photo_2024-06-22_14-17-05](https://github.com/organicmaps/organicmaps/assets/18434508/72afe205-6ecf-443d-9e84-3f725a066934)

It returns 8 results total (and only the first is relevant) from other downloaded map regions e.g. US, India, which are more far away from Moscow than Paris is.

When viewport is centered on Europe (and France is fitting):
![Eiffel_France_photo_2024-06-22_14-26-32](https://github.com/organicmaps/organicmaps/assets/18434508/0eef8e1c-4f71-44d2-b7c7-d0dabe460939)

Results are great and as expected. But the blue suggestions are completely irrelevant.

**Comment by pastk** [comment]
FYI @vng

**Comment by pastk** [comment]
https://github.com/organicmaps/organicmaps/pull/8547 fixes Eiffel Tower findability, but the list of suggestions is irrelevant still (includes only "tower" partial matches and ignores "eiffel") - should I create a separate issue for it?

**Comment by vng** [comment]
We do suggest only streets and cities. And yes, suggestions are not always full-match and it is made especially for fast address input.
