### ISSUE TITLE
Treat natural-volcano and natural-peak as synonyms

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#8527]
E.g. searching for "mountain Elbrus" ("гора Эльбрус") doesn't work, but "volcano Elbrus" does, because its mapped as a volcano and it is a volcano indeed, but a dormant one and most people don't know it and generally refer to it as a mountain. Even the wiki entry is [Mount Elbrus](https://en.wikipedia.org/wiki/Mount_Elbrus).

current categories.txt:
```
natural-peak
en:Peak|mountain|mount|U+1F5FB|U+1F304
ru:Гора|вершина|пик
...

natural-volcano
en:4Volcano
ru:4Вулкан
...
```

Shall we just merge them?

Then it won't be possible to search specifically for "volcanoes".

**Comment by biodranik** [comment]
@pastk no need to merge, just add all peak synonyms to volcano.
