### ISSUE TITLE
Use Git LFS to reduce size of repository

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#8534]
**Is your feature request related to a problem? Please describe.**
On repository, .git directory takes around 10 Go
It's can be complicated to download repository for contributors with low Internet connection.
I guess 10 Go was take by files mwm update each months.

**Describe the ideal solution**
I suggest to use Git LFS, to store big files in another places in Github server and reduce size of repository
https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage

**Describe alternatives you have considered**
- How do you solve this issue now with Organic Maps or other apps?
- Attach any examples, screenshots, or screen recordings from other apps that help us to better understand the idea.

**Additional context**

**Comment by biodranik** [comment]
1. We tried it in the past, but it didn't work well for several reasons.
2. The LFS extension on Github is a paid one.
3. It is possible to make a shallow clone with a depth of 100 or so. Not sure though if commits are possible with a shallow clone. Did anyone check it?
