### ISSUE TITLE
Android - Failure to Register as Navigation Application

### ISSUE THREAD

**Issue by DominusFL** [organicmaps/organicmaps#8554]
Using DMD2 Application, when I select a map location and want to navigate using an external app, the DMD2 application will list all Android apps that are registered as navigation applications. This includes Waze, Google Maps, etc. But it does not include Organic Maps.

DMD2 team says this is due to Organic Maps failing to register itself with Android as a navigation app. Specifically, they state:
"The apps are given as an option by android - they're the apps that register themselves with android as a navigation app that can be passed a location to navigation too. The missing bit here is in Organic Maps, it needs to tell Android that it can be passed a location to navigate to."

 - Operating system and its version: Android 12
 - Organic Maps version: Latest June 2 Beta
 - Device Model: DMD-T665 Navigation Phone

**Comment by biodranik** [comment]
I'm not aware of any generic way to "register with Android as a navigation app that can be passed a location to navigation too". Can you please ask DMD2 team for the details?

All Android apps that I know explicitly specify the URL scheme to open in a programmatic intent. I assume that DMD2 team launches some URL scheme that is not supported yet by OM, or they explicitly list/use app-specific URL schemes to launch specific applications.

Here is the list of URL schemes supported by Organic Maps (and the most common one, `geo:` is supported): https://omaps.app/api

**Comment by DominusFL** [comment]
Head Developer of DMD2 has replied after reading this response: 
**João Pereira** -- "will add geo then. Should be an easy implement."

This issue can be closed as third-party app will address.
