### ISSUE TITLE
Support `self_service` tag

### ISSUE THREAD

**Issue by Arthur-GYT** [organicmaps/organicmaps#8556]
I think the title speaks for itself. It would be interesting for restaurants, laundries, etc...

If it's a yes, I can do the PR.

https://wiki.openstreetmap.org/wiki/Key:self_service

**Comment by biodranik** [comment]
Yes, this one is useful as a part of editable metadata for selected types.

**Comment by Arthur-GYT** [comment]
Okay, I will open a PR. Just one more thing, anyone have an idea for the icon ?

**Comment by patepelo** [comment]
> Okay, I will open a PR. Just one more thing, anyone have an idea for the icon ?

We should start adding subtags without the need for icons. There are going to be a lot of them so we should start thinking in a form of grouping them in a simple [key / value] methodology.

**Comment by Arthur-GYT** [comment]
Added for Android and iOs now.
