### ISSUE TITLE
Other tracks displayed in default blue if KML contains more than one

### ISSUE THREAD

**Issue by Shohreh** [organicmaps/organicmaps#8562]
OM release 2024.06.19-3-Google

Hello,

I noticed that If a KML file contains more than one track, the others are displayed in default blue rather than with the specified color — I always use red to make tracks easier to see on maps, especially when next to rivers.

Here's an example:
```
<?xml version="1.0" encoding="utf-8"?>
<kml>
 <Document>
  <name>Track</name>
  <Placemark>
   <name>Track1</name>
   <Style>
    <LineStyle>
     <color>
      FF0000FF
     </color>
     <width>
      6
     </width>
    </LineStyle>
   </Style>
   <LineString>
    <coordinates>
     -0.902225,43.510247,47.5 -0.902576,43.510206,46.75 -0.902711,43.51019,46.75 -0.904097,43.510172,46.5 -0.904532,43.510196,45.75  -1.209161,43.525336,2.75 -1.20853,43.525038,2 -1.207969,43.524786,0 -1.207532,43.52458,-1.75 -1.206688,43.524105,1 -1.206448,43.523992,0.5 -1.205498,43.52365,0.75
    </coordinates>
   </LineString>
  </Placemark>
  <Placemark>
   <name>Track2</name>
   <Style>
    <LineStyle>
     <color>
      FF0000FF
     </color>
     <width>
      6
     </width>
    </LineStyle>
   </Style>
   <LineString>
    <coordinates>
     0.505284,43.293855,367.75 0.505748,43.29347,362.25 0.505421,43.293271,362.75 0.504548,43.292685,361.75 0.504477,43.292657,361.5 0.504407,43.292642,361.75 0.50426,43.292357,360.5 0.504085,43.291951,361.25 0.504052,43.291811,361.25 0.504082,43.29124,362.25 0.554617,43.133224,530.75 0.556068,43.133182,530.75 0.55754,43.133198,530 0.557931,43.133213,529 0.559722,43.133394,525.25 0.56017,43.133446,525.25
    </coordinates>
   </LineString>
  </Placemark>
 </Document>
</kml>
```

Cheers,

![image](https://github.com/organicmaps/organicmaps/assets/1541861/27e292b5-6d93-470f-9bda-18b9c443f972)

**Comment by biodranik** [comment]
@cyber-toad can you please take a look?

**Comment by cyber-toad** [comment]
@Shohreh could you post the original file? I can't reproduce - it shows two short tracks, both of them are red:

![image](https://github.com/organicmaps/organicmaps/assets/128428520/747c958f-b7fa-4562-972b-9924a54e0dc7)

**Comment by Shohreh** [comment]
> @Shohreh could you post the original file? I can't reproduce - it shows two short tracks, both of them are red:

Here it is:

https://gofile.io/d/jy0SEQ

**Comment by cyber-toad** [comment]
@Shohreh I checked the file - the problem is how style is configured for the last track - it is placed inside MultiGeometry tag rather than to Placemark, so it is not used. If Style section is moved inside Placemark all tracks are red.

@rokuz By any chance, do you remember why you mentioned kml spec violation in this commit: https://github.com/cyber-toad/organicmaps/commit/c8d81293081afdb0e88ae6db27236942725e700c#diff-c16f904482bd8eb25901b3bee393895ac9744cd2495235cd1a2f6ecd509f8951R726
Based on spec https://developers.google.com/kml/documentation/kmlreference#placemark it should be there, or I'm missing something?

**Comment by Shohreh** [comment]
> I checked the file - how you created it? The problem is how style is configured for the last track - it is placed inside MultiGeometry tag rather than to Placemark, so it is not used. If Style section is moved inside Placemark all tracks are red.

Thanks for the info.

I…
1. Added the tracks to a layer in Umap map
2. Exported the layer as KML
3. To turn each track to red, ran a Python script that uses Beautiful Soup

This feature occurs in Umap, in the main track — the smaller ones I added later have no MultiGeometry parent. I'll investigate, and find a work-around if needed.

Thanks!

**Comment by Shohreh** [comment]
> @cyber-toad I believe I meant placemark should contain `styleUrl` but not `Style` itself

I'll update my script to add a single `Style` and add `styleUrl` reference with each `LineString`.

https://simplekml.readthedocs.io/en/latest/styling.html
