### ISSUE TITLE
Generate `taginfo.json` for the TagInfo project

### ISSUE THREAD

**Issue by soshial** [organicmaps/organicmaps#8566]
Many OSM projects provide information about which tags they support (for example: [Guru Maps](https://taginfo.openstreetmap.org/projects/guru_maps#tags), [Vespucci, OpenTopoMap, iD, JOSM](https://taginfo.openstreetmap.org/keys/man_made#projects) etc.)

In order to provide this information a `taginfo.json` file should be generated (for example, see [Guru Maps file](https://raw.githubusercontent.com/GuruMaps/MapStyle/master/taginfo.json)). This would help devs and other people in the community to check quickly whether any feature is supported or not yet.

**Comment by dvdmrtnz** [comment]
Same as https://github.com/organicmaps/organicmaps/issues/3917
