### ISSUE TITLE
App availability in Google Play Market on wearos.

### ISSUE THREAD

**Issue by SpiritOTHawk** [organicmaps/organicmaps#8592]
**Is your feature request related to a problem? Please describe.**
I can't download from Google Play and use organic maps on my watch (Galaxy Watch 4)

**Describe the ideal solution**
Add wearos support and upload to Google Play for wearos

**Describe alternatives you have considered**
- Google maps for wearos by example.

**Comment by RedAuburn** [comment]
duplicate of https://github.com/organicmaps/organicmaps/issues/1451
