### ISSUE TITLE
UTM coordinates are wrong in Germany

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8593]
The location information in UTM format shows 32N and 33N anywhere in German. Germany is located in 32U or 33U respectively.

![image](https://github.com/organicmaps/organicmaps/assets/170263/15f51124-977f-4786-ac7c-483efa6f9212)

@strump can you please take a look?

**Comment by strump** [comment]
Looks like Organic Maps always puts 'N' to UTM coordinates. While MGRS has valid zone letter. Will look into code and cover with tests
