### ISSUE TITLE
[android] Cut text in bookmarks list with a larger system font size

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8600]
This issue should be easy to fix.

<img width="367" alt="image" src="https://github.com/organicmaps/organicmaps/assets/170263/bb1b442f-ae46-40cd-ae43-ca1caa1f2699">

**Comment by slackuj** [comment]
Hello,
Is this issue solved?
![Screenshot_२०२४-०७-०४-१४-५८-४४-०७८_app organicmaps](https://github.com/organicmaps/organicmaps/assets/93903384/1551e988-0ac3-45f6-b5aa-73495f8df39c)


My phone doesn't show cut-text in bookmarks list!

**Comment by slackuj** [comment]
HELLO
