### ISSUE TITLE
Show traffic lights in routing (like Apple Maps)

### ISSUE THREAD

**Issue by PinguDEV-original** [organicmaps/organicmaps#8602]
⚠ Have you searched for similar, already existing issues?

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example:
Apple Maps can do this, it looks nice and is also helpful for the audio thing.

**Describe the ideal solution**
A small, nice looking traffic light, but only in routing mode.

**Describe alternatives you have considered**
Take a look at Apple maps:
![grafik](https://github.com/organicmaps/organicmaps/assets/82669329/b184ee20-f351-4174-b680-e80d10f50d11)

**Additional context**
You should include it in the audio thingy!

**Comment by dvdmrtnz** [comment]
* See https://github.com/organicmaps/organicmaps/pull/7281
