### ISSUE TITLE
Why not return result when the result is empty after filter by ViewportFilter?

### ISSUE THREAD

**Issue by HelloTrigger** [organicmaps/organicmaps#8667]
![image](https://github.com/organicmaps/organicmaps/assets/20265845/ba620c64-a90a-495d-91e3-13e6f7de1516)

**Comment by biodranik** [comment]
@HelloTrigger do you consider it a bug? What are your thoughts?

CC @vng

**Comment by RedAuburn** [comment]
maybe i'm missing something, but if the result is empty there's nothing to return, no?

**Comment by HelloTrigger** [comment]
I know the reason
