### ISSUE TITLE
POI search is really slow

### ISSUE THREAD

**Issue by matkoniecz** [organicmaps/organicmaps#867]
Search for shops should give results about nearby shops than waiting about 5 seconds

Right now my Mi A2 Lite on searching "Decathlon" in Kraków, Poland requires about 5 seconds to start showing results.

It would be nicer to show results quicker.

I am considering trying to dig into profiling, maybe even making PR (but right now my performance tuning experience on Adroid is nonexisting!), though not sure how to start.

I would be happy to provide more info if that would be useful.

**Comment by biodranik** [comment]
How many maps do you have? Are they on SD card? Is it faster on internal memory?

**Comment by matkoniecz** [comment]
Czech Republic, Poland, Slovakia (2.1 GB), on SD card.

But I hoped that it is not checking every single named object on all downloaded maps, but starts from nearby area.

I can test with an internal memory, I guess that it needs a reinstall?

**Comment by matkoniecz** [comment]
I tested now with just one map and on internal memory and it is much, much faster.

**Comment by biodranik** [comment]
How fast is your SD card? We can't help if it's slow. You see it with the fast internal memory.

You can try to experiment with different SD cards and share your results.

Also, how slow is it with just one map on SD?

**Comment by biodranik** [comment]
Also, you can move maps to/from SD from the Settings.

**Comment by Jean-BaptisteC** [comment]
@matkoniecz can you retry with latest version ?

**Comment by matkoniecz** [comment]
I sold my SD card back to Samsung (they actually honoured that "10 year warranty" printed on packaging I kept).

On retesting, it is not so slow with this specific case. Though I remember some problematic searches. I will reopen/make new issue if I will have a test case.
