### ISSUE TITLE
Naming Maps

### ISSUE THREAD

**Issue by RJGhugo** [organicmaps/organicmaps#8699]
The Swiss maps have "strange" locations[1] included.

a) Every capital of a canton **(Kantonshauptstadt)** should be mentioned on the map description.
b) _Some cities_ should be mentioned just for better understanding.

* Espace Mittelland - Bern --> better name would be "Espace Mittelland"
**Bern**, _Biel_, **Freiburg**, **Solothurn**, _Olten_, **Neuenburg**, **Delsberg**

* Espace Mittelland - Osten
_Thun_, _Interlaken_, _Langenthal_

* Genferseeregion
**Genf**, **Lausanne**, **Sitten**

* Kanton Tessin
**Bellinzona**, _Lugano_, _Locarno_

* Metropolregion Zürich
**Zürich**, _Winterthur_

* Nordwestschweiz
**Basel**, **Liestal**, **Aarau**

* Ostschweiz
**Chur**, **St. Gallen**, **Herisau**, **Appenzell**, **Frauenfeld**, **Glarus**, **Schaffhausen**

* Zentralschweiz
**Luzern**, **Zug**, **Sarnen**, **Stans**, **Altdorf**, **Schwyz**

[1]: https://waldvogel.family/@marcel/112729913445403222
![Name Maps](https://github.com/user-attachments/assets/abd24a6a-2579-48c8-971f-6c9c59732273)

**Comment by RedAuburn** [comment]
If you can use Git & submit a PR, these can be updated at https://github.com/organicmaps/organicmaps/blob/master/data/countries_names.txt :)

if not, one of us can update it 👍️
