### ISSUE TITLE
Improve icons for Android export menu

### ISSUE THREAD

**Issue by euf** [organicmaps/organicmaps#8722]
A user reported that export icons on Android are a bit confusing:

<img width="33%" src="https://github.com/user-attachments/assets/5918b84c-ae88-4f7d-afbc-01bd169004ad">

I have designed three new export icons for GPX, KML, KMZ export. They are based on Material Icons "copy file" metaphor and the text is aligned on the pixel grid. The result is expected to be crisp and readable:

![export-gpx](https://github.com/user-attachments/assets/078eeb46-1486-4b15-b613-6737796bbf7d)
![export-kml](https://github.com/user-attachments/assets/3b0c3397-e83d-4e73-991d-df6a82068e29)
![export-kmz](https://github.com/user-attachments/assets/000303f5-8c65-4223-b659-513de8716de0)

**Comment by RedAuburn** [comment]
@organicmaps/ios are these needed for iOS? or should this issue be closed now?

**Comment by biodranik** [comment]
Thanks for reminding, it should be closed, iOS doesn't use icons in the Action Sheet Menu.
