### ISSUE TITLE
no longer able to tap and set a pin on the map

### ISSUE THREAD

**Issue by uselessgames** [organicmaps/organicmaps#8725]
**Describe the issue**
we used to be able to tap anywhere on the map to get information, then be able to bookmark or route. 

now it seems can only tap on items

**Steps to reproduce**
1. open the app
2. find a place with nothing marked, say a park
3. tap and hold
4. nothing happens 

**Expected behaviour**
on step 4, above, before it would highlight blue and I could bookmark or route to/from. basically get the same menu options as selecting a an adres. 

**Screenshots**
n/a

**System information:**
 - Operating system and its version: android 14
 - Organic Maps version: 2024.07.08-3-Google
 - Device Model: pixel 4(5g)

**Additional context**
thank you for maintaining this awesome map. cheers

**Comment by RedAuburn** [comment]
tap behaviour was changed, try just short tapping anywhere & it should work :)
(see https://github.com/organicmaps/organicmaps/pull/7876)

**Comment by uselessgames** [comment]
ah dang, oke. sorry. it didn't come up in my search.
