### ISSUE TITLE
ETA/time estimates on some dirt and small residential roads are about 2-5x too slow

### ISSUE THREAD

**Issue by skylarmt** [organicmaps/organicmaps#8729]
**Describe the issue**

I live on the end of a dirt road.  Organic Maps seems to assume dirt roads have a speed limit somewhere around 5mph.  This results in trip estimates being 10 to 30 minutes too long, and causes some strange routing, like if I'm traveling mostly on dirt roads, trying to take me miles out of my way to a paved road and back around "the long way" instead of creating a route that's a fraction of a mile and goes straight to my destination.

**Steps to reproduce**
1. Pick a destination and starting point both on a dirt road near each other (this is happening in rural Montana, USA but likely other places too)
2. ETA is insane and route is likely to be as well

**Expected behaviour**
It performs in a normal manner when navigating on dirt roads.

**Screenshots**

Wants me to deviate to a highway and then come around the long way, despite this being several miles longer:
![Screenshot_20240709-164659](https://github.com/user-attachments/assets/8442459b-d4fd-43e5-93ba-8e3bd6433474)

Wants me to turn around at the next interstate exit (the one I actually had to get off at) so I can backtrack towards and through an entire city and back up into the hills on a slightly more paved route. Following these instructions would have required an extra half hour of driving and dozens more miles.  It kept prompting me to turn around after I left the interstate, even when I was almost to my destination.
![Screenshot_20240618-140103](https://github.com/user-attachments/assets/a058192e-b9da-40ca-ac16-1f4cac92e345)

Seems to assume a 9mph speed limit for no apparent reason, nobody drives that slowly (half the road involved is paved too):
![Screenshot_20240719-005301](https://github.com/user-attachments/assets/c50b50fd-2664-4021-95bf-378052ec67f9)

**System information:**
 - Operating system and its version: Android 14 (CalyxOS)
 - Organic Maps version: 2024.06.19-3-FDroid
 - Device Model: Fairphone 5

**Comment by biodranik** [comment]
What should be the ETA speed for dirt roads? How it's estimated in other navigators?

**Comment by euf** [comment]
In US states of Virginia and California 

> unpaved roads have a limit of 35 mph for roads that lack a posted speed limit.

In my personal driving experience a good dirt road could be around 50 km/h (30 mph) and a bad one (like agricultural track) around 25 km/h (15 mph). 

I've also noticed enormous ETA for highway=track. The speed estimates for them should be bumped, because right now they seem to utilize something close to the walking speed.

**Comment by biodranik** [comment]
Currently the ETA and routing penalties to guess a better route are mixed together. @vng do you have any ideas on how the routing should be improved/refactored to provide best possible results in all cases?

**Comment by euf** [comment]
I don't really know, but #8850 seems related to me in terms of mixed/separated ETA and routing penalties
