### ISSUE TITLE
OM fails downloading maps

### ISSUE THREAD

**Issue by Shohreh** [organicmaps/organicmaps#8737]
Hello,

I'm leaving for a trip in a couple of days. For some reason, OM fails downloading the maps I need on an old phone I use as backup.

Any idea what I could try?

Thank you.

Android 7
OM 2024.07.08-3-Google
Huawei P9 Lite

![image](https://github.com/user-attachments/assets/d006e62a-1291-4278-8446-6ac68b4ddd38)

**Comment by RedAuburn** [comment]
it looks like your device is in aeroplane mode, try disabling that?

**Comment by Shohreh** [comment]
> it looks like your device is in aeroplane mode, try disabling that? if that works, it's a bug with the downloader that we need to fix

Still NOK. I can access web pages and updates on Google Plays, so wifi works.

**Comment by RedAuburn** [comment]
> As a temporary work-around, can I download the maps on a computer, and copy them to that phone through USB?

Not possible without root unfortunately :(

Could you do the following:
- enable logging in settings
- restart the app
- try to download a map
- press the organic maps icon in the bottom panel
- press "report bug"
- send the email (it should have the logs txt file attached)

Then @biodranik can check the email, which should have info about the error :)

**Comment by RedAuburn** [comment]
Oooh, just noticed what looks like NetGuard in your notifications, try disabling that. If it works after disabling, it's likely to do with your netguard settings

**Comment by Shohreh** [comment]
> * nable logging in setti

Done. Subjet is "[2024.07.08-3-Google] Organic Maps Bugreport".

**Comment by Shohreh** [comment]
> Oooh, just noticed what looks like NetGuard in your notifications, try disabling that. If it works after disabling, it's likely to do with your netguard settings

I don't know what NetGuard is.

OM worked fine until today. I've downloaded maps successfully a month ago for another trip.

**Comment by biodranik** [comment]
The issue is caused by missing/not updated root certificates on Android 7 and lower devices:
https://community.letsencrypt.org/t/letsencrypt-certificates-fails-on-android-phones-running-android-7-or-older/205686

@Shohreh please try to install this build (in parallel to the main OM version) and let me know if it works: https://cdn.organicmaps.app/apk/OrganicMaps-24072006-web-release.apk

**Comment by Shohreh** [comment]
> please try to install this build (in parallel to the main OM version) and let me know if it works:

Yup, it successfully downloaded some maps.

Thank you!
