### ISSUE TITLE
View outlines of areas if selected

### ISSUE THREAD

**Issue by qwerty287** [organicmaps/organicmaps#8739]
⚠ Have you searched for similar, already existing issues?

Yes, I did, and didn't find something. However, I think this probably already exists. If yes, I'm sorry for the noise.

**Describe the ideal solution**
When you select an area, view its outlines.

**Additional context**
Example from OSMAnd:
![Screenshot_20240720-190325.png](https://github.com/user-attachments/assets/c92edf91-d599-46bb-a17b-8d4e46651bb9)

The same in Organic Maps:
![Screenshot_20240720-190318.png](https://github.com/user-attachments/assets/ca2d1d61-a929-4739-be33-daba2ebffedc)

**Comment by Jean-BaptisteC** [comment]
Duplicate of #2697
