### ISSUE TITLE
Android auto route planner does not work from car dashboard

### ISSUE THREAD

**Issue by anand-coding** [organicmaps/organicmaps#8750]
**Describe the issue**
Android auto does not allow me to search or select a route from bookmarks/categories or pick a point to route to

**Steps to reproduce**
1. Open organic maps in car dashboard. Switch to car
2. Click search/categories/bookmarks or select a point in the map. 
3. Try to route. It does not work, it goes back to the home screen.

**Expected behaviour**
Maps should allow search (and set a destination) when connected to the car

**Workaround**
Start the navigation in phone and then switch to car dashboard.

**System information:**
 - Operating system and its version: Android Version 14, One UI version 6.3 (Canada)
 - Organic Maps version: 2024.07.08-3-google
 - Device Model: Samsung S23

**Additional context**
Two users have the same issue (found while searching for solution online)  -> https://www.reddit.com/r/organicmaps/comments/1e8b9hh/wish_the_android_auto_worked_better/

**Comment by biodranik** [comment]
@AndrewShkrob PTAL

**Comment by madpilot78** [comment]
I am seeing this exact same behavior starting with the same version as OP. Previous version was working fine.

My phone is a Motorola moto G20, with android 11, the car is a Toyota Corolla MY 2022 (in Europe, if that's relevant)

**Comment by Chris-Kropp** [comment]
Same here on:
pixel 8
GrapheneOS Android 14
Organic Maps from fdroid
2019 Chevy Bolt

**Comment by madpilot78** [comment]
@Chris-Kropp On a side note, how did you get organic maps from fdroid to work on android auto? I was not able to do that even using developer mode, could you share how you did it?

**Comment by madpilot78** [comment]
Thanks all for the work on this.

I confirm now organic maps (version 2024.07.29-2-Google) allows me to start navigation from the car display.

**Comment by Miwer** [comment]
@madpilot78 - to get f-droid version working on AA, you have to download the .apk file and install with King Installer. This works for me. Also updates need to be installed with King Installer. If I let F-Droid update the app, it disappears from AA.

Thanks Google, I'm seriously considering rooting, just to be able to use AA-Tweaker to get rid of this and other AA limitations, like disabled on-screen keyboard while driving.
