### ISSUE TITLE
Water tunnel is displayed and described as pedestrian tunnel

### ISSUE THREAD

**Issue by VladimirMorozov** [organicmaps/organicmaps#8792]
**Describe the issue**
This tunnel is displayed and described as a footway tunnel, this may lead hikers to confusion

tunnel=yes
waterway=drain
...

![image](https://github.com/user-attachments/assets/763ed0f8-92c4-4408-bdb0-c829e0fa0deb)
https://www.openstreetmap.org/way/82206632

**Expected behaviour**
If I'm not mistaking, water tunnels are not displayed at all.

**System information:**
 - Operating system and its version: [iOS 17.5.1]
 - Organic Maps version: 2024.07.27-7
 - Device Model: iPhone SE2

**Comment by kesapaiva** [comment]
There seems to be a pedestrian tunnel marked next to the waterway: https://www.openstreetmap.org/way/186893874

**Comment by VladimirMorozov** [comment]
Thanks. Looks like id editor had hidden it from me, need to check it out.
