### ISSUE TITLE
OSM login on IPhone not working at all

### ISSUE THREAD

**Issue by ghost** [organicmaps/organicmaps#8793]
Yes password and username and email 100% valid. Yes, I am sure.

![IMG_4206](https://github.com/user-attachments/assets/0c8c26dd-8495-4f8f-a8a6-b57e22da0991)
![IMG_4207](https://github.com/user-attachments/assets/b34f16f8-2913-4e83-b434-b0abd3e48463)
![IMG_4208](https://github.com/user-attachments/assets/4272f3be-5b15-42b3-bd35-91136f13bfb2)
![IMG_4209](https://github.com/user-attachments/assets/e1aa0d91-1f72-4feb-8879-c39fb5e17eb9)

**Comment by Jean-BaptisteC** [comment]
Can you retry, OSM website have some troubles.

**Comment by Finopj** [comment]
> Can you retry, OSM website have some troubles.

Retried 7 times. Nothing

**Comment by Jean-BaptisteC** [comment]
@kirylkaveryn can you try to check ?

**Comment by Finopj** [comment]
@Jean-BaptisteC 

https://github.com/user-attachments/assets/a2a743d3-bf02-4199-ab33-0a70fc754ff9

**Comment by Finopj** [comment]
And proof

https://github.com/user-attachments/assets/f7c67c45-2f41-4ed8-af4c-c631336283f8

**Comment by biodranik** [comment]
@Finopj Did you try to type your password, not copy-paste it? Could it be that you copy-pasted a space symbol that is removed in OSM website password form?

**Comment by Finopj** [comment]
> @Finopj Did you try to type your password, not copy-paste it? Could it be that you copy-pasted a space symbol that is removed in OSM website password form?

Yes I tried. You can try yourself, I think…

**Comment by biodranik** [comment]
Of course I tried. Login works for me on iOS and Android. Can you please send us logs after a failed login attempt using "Report a bug" button in the About dialog?

**Comment by kirylkaveryn** [comment]
I relogged is several times and everything works correctly.

**Comment by biodranik** [comment]
It looks like a temporary issue with OSM servers (or blocked OSM servers). Hard to guess without logs.
