### ISSUE TITLE
[android] GPX or KMZ export to Google Drive doesn't work

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8806]
Google Drive folder is empty.

```
07-31 17:51:50.363  1335  2800 W ContentProviderHelper: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{f7a2db5 26070:com.android.intentresolver/u0a332} (pid=26070, uid=10332) that is not exported from UID 10464
07-31 17:51:50.364 26070 26115 W ChooserPreview: Could not read content://app.organicmaps.debug.provider/cache/My%20Places.kmz stream types. If a preview is desired, call Intent#setClipData() to ensure that the sharesheet is given permission.
07-31 17:51:50.365  1335  2800 W ContentProviderHelper: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{f7a2db5 26070:com.android.intentresolver/u0a332} (pid=26070, uid=10332) that is not exported from UID 10464
07-31 17:51:50.365 26070 26115 W ChooserPreview: Could not read content://app.organicmaps.debug.provider/cache/My%20Places.kmz metadata. If a preview is desired, call Intent#setClipData() to ensure that the sharesheet is given permission.
```

**Comment by biodranik** [comment]
This simple exporting works. @Jean-BaptisteC @rtsisyk do you have any idea why fancy sharing via ActivityResultLauncher doesn't work?

```
@@ -211,51 +212,61 @@ public class SharingUtils
   {
     Intent intent = new Intent(Intent.ACTION_SEND);
 
-    if (!info.mSubject.isEmpty())
-      intent.putExtra(Intent.EXTRA_SUBJECT, info.mSubject);
-    if (!info.mMail.isEmpty())
-      intent.putExtra(Intent.EXTRA_EMAIL, new String[]{info.mMail});
-    if (!info.mText.isEmpty())
-      intent.putExtra(Intent.EXTRA_TEXT, info.mText);
-
-    Intent chooser = Intent.createChooser(intent, context.getString(R.string.share));
-    SharingIntent sharingIntent = new SharingIntent(chooser);
-
-    if (!info.mFileName.isEmpty())
-    {
-      final Uri fileUri = StorageUtils.getUriForFilePath(context, info.mFileName);
-      intent.putExtra(Intent.EXTRA_STREAM, fileUri);
-      intent.setDataAndType(fileUri, info.mMimeType);
-
-      // Properly set permissions for intent, see
-      // https://developer.android.com/reference/androidx/core/content/FileProvider#include-the-permission-in-an-intent
-      intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
-      if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.LOLLIPOP_MR1) {
-        intent.setClipData(ClipData.newRawUri("", fileUri));
-        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION | Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
-      }
-
-      Intent saveIntent = new Intent(Intent.ACTION_CREATE_DOCUMENT);
-      saveIntent.setType(info.mMimeType);
-
-      final String fileName = fileUri.getPathSegments().get(fileUri.getPathSegments().size()-1);
-      saveIntent.putExtra(Intent.EXTRA_TITLE, fileName);
-
-      Intent[] extraIntents = {saveIntent};
-
-      // Prevent sharing to ourselves (supported from API Level 24).
-      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N)
-      {
-        ComponentName[] excludeSelf = { new ComponentName(context, SplashActivity.class) };
-        chooser.putExtra(Intent.EXTRA_EXCLUDE_COMPONENTS, excludeSelf);
-      }
-
-      chooser.putExtra(Intent.EXTRA_INITIAL_INTENTS, extraIntents);
-
-      sharingIntent.SetSourceFile(fileUri);
-    }
-
-    launcher.launch(sharingIntent);
+    final Uri fileUri = StorageUtils.getUriForFilePath(context, info.mFileName);
+
+    intent.putExtra(Intent.EXTRA_STREAM, fileUri);
+    intent.setType(info.mMimeType);
+    intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
+    if (context instanceof Application)
+      intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
+    Intent chooserIntent = Intent.createChooser(intent, context.getString(R.string.share));
+    context.startActivity(intent);
+

```

**Comment by biodranik** [comment]
@krozhdestvenski #8307 broke it. Why is using the launcher parameter required?

**Comment by krozhdestvenski** [comment]
@biodranik, wip. I'll check it and answer in a few days.

**Comment by krozhdestvenski** [comment]
@biodranik, Maybe the latest version has added functionality for automatically deleting temporary files? I know that temporary files have not been deleted before (https://github.com/organicmaps/organicmaps/issues/6893). 
 It looks like Google Drive only stores a link to the file on the device. And the file is deleted from Google Drive after it is deleted from the device (i see it in Google Drive actions log).

**Comment by biodranik** [comment]
@krozhdestvenski no, that issue is not related.

As I wrote in the code example above, normal sharing without `ActivityResultLauncher<SharingIntent> launcher` works fine with Google Drive. The current implementation is messy, it also has other issues (e.g. the inserted file name in Google Drive is wrong).

**Comment by krozhdestvenski** [comment]
@biodranik We can fixed core problem(saving to Google Drive) by easy way. By adding flag:
` intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);`
I tested it. It's working correctly.

Problem with file name is more complex and actual for previous solution(from your comment) too. 
For some reason, when we try to upload file to Drive, file name sets from param Intent.EXTRA_SUBJECT. 
And when we try to send e-mail, e-mail subject sets from Intent.EXTRA_SUBJECT.
We can set file name to Intent.EXTRA_SUBJECT, but in this case e-mail subject also will be equals file name.

**Comment by krozhdestvenski** [comment]
> > @biodranik We can fixed core problem(saving to Google Drive) by easy way. By adding flag: ` intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);` I tested it. It's working correctly.
> > Problem with file name is more complex and actual for previous solution(from your comment) too. For some reason, when we try to upload file to Drive, file name sets from param Intent.EXTRA_SUBJECT. And when we try to send e-mail, e-mail subject sets from Intent.EXTRA_SUBJECT. We can set file name to Intent.EXTRA_SUBJECT, but in this case e-mail subject also will be equals file name.
> 
> That sounds reasonable. I think that adding two buttons will be overkill. Let's try to find any human-readable value that works both as a file and email header.

The problem is that the file name in the subject line looks ugly and uninformative( And file name should have extension...

**Comment by biodranik** [comment]
@krozhdestvenski are there some other intent fields where we may try to insert the file name specifically for Google Drive to work? Are there any discussions in the internet about it? Is it possible to reverse-engineer the code of the Google Drive app to understand the logic of filling the file name value with the subject line?

**Comment by krozhdestvenski** [comment]
> @krozhdestvenski are there some other intent fields where we may try to insert the file name specifically for Google Drive to work? Are there any discussions in the internet about it? Is it possible to reverse-engineer the code of the Google Drive app to understand the logic of filling the file name value with the subject line?

I found this solution https://stackoverflow.com/questions/35382474/google-drive-changes-file-name-to-intent-extra-subject-when-sharing-a-file-via-i
And it works correctly:
1. On saving to Google Drive or Local Device we can see file name
2. On sending e-mail we can see correct subject

Can we use this solution?

**Comment by biodranik** [comment]
It should be tested with other system apps (files, gmail, etc.) and popular map apps. And if it works without any issues, then yes, we can use it. Strange that drive team didn't fix that.

**Comment by krozhdestvenski** [comment]
> It should be tested with other system apps (files, gmail, etc.) and popular map apps. And if it works without any issues, then yes, we can use it. Strange that drive team didn't fix that.

I tested it with files, gmail, drive. And did PR. 
Can anyone test with other apps?

**Comment by biodranik** [comment]
@Jean-BaptisteC can you please help with testing https://github.com/organicmaps/organicmaps/pull/8817 with other GPX and KML apps?
