### ISSUE TITLE
Cross Map-Section Search almost always fails.

### ISSUE THREAD

**Issue by danielh186** [organicmaps/organicmaps#881]
If the address that I am searching for, is not in the same map section that I am currently in (by GPS location), I can't find it with the search function. Even though I have downloaded the map section that my destination is located in.

So I have to manually move to the map section that contains my destination and zoom in so that map section gets loaded. If it is loaded there is no problem finding my destination.

But if I then close the app and reopen it, the problem is back.

I checked and that problem actually also exists in the current Maps.me app!

Makes the app totally unusable for me...

There is also someone that seems to have this Issue on some Maps.me clone application (8 months ago)
https://gitlab.com/axet/omim/-/issues/180

**Comment by biodranik** [comment]
Can you provide some samples of your search queries? Do you specify a city name where you are searching?

**Comment by danielh186** [comment]
I managed to resolve the issue  by uninstalling the Maps.me app and removing all of it's left over data that wasn't properly removed...
after that I also reinstalled the Organic Maps App and rebooted Android. Now it seems to be working just fine 👍 

Specifying city names in the search also seems to be something that will lead to useless search results but wasn't the issue for me.
For example if I search for "Saarstraße", I will get Saarstraße, Mainz without a problem but if I then add the city ("Saarstraße Mainz") to the search term, the entry will disappear from the results...

But since you asked like that, I guess that this is a known Issue, that will be fixed at some point. Or should I open a new Issue for that?

Also, is there an option to update the maps by hand without waiting for an app update. I recently fixed my Adress in open street map and of course that update isn't showing up in the app yet.
If I can't update it manually, how long does it normally take to get such an update from osm to the app?

**Comment by biodranik** [comment]
Did you have many maps installed on SD-card before? The search may be really slow due to a slower SD-card speed in comparison with the phone's internal storage speed.

We plan to update maps 1-4 times per month.

Does `Mainz Saarstraße` make any difference? You downloaded that city, right? How result changes if you change the map viewport?
