### ISSUE TITLE
[iOS] Compass is missing 

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#8814]
When you rotated the map you used to get a compass icon on the top right corner that showed the north and you could press on it to revert back to north is up. Latest master is missing this button.

Could be related to https://github.com/organicmaps/organicmaps/issues/8807?

- - - 

Before:

<img src="https://github.com/user-attachments/assets/69a979f1-6c85-4979-b08d-f9fec7450773" width="320"/>

- - -

Organic Maps version 2024.07.31-5⁩:

<img src="https://github.com/user-attachments/assets/c4ada271-e024-4674-b316-5c1fa3700387" width="320"/>

**Comment by RedAuburn** [comment]
see https://github.com/organicmaps/organicmaps/pull/8813
