### ISSUE TITLE
[android] Failed to parse geo link with percent encoding

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8816]
Some apps wrongly percent encode the comma in the url:

Example: `geo:-18.9151863%2C-48.28712359999999?q=-18.9151863%2C-48.28712359999999`

Fixing geo parser code in geo_url_parser.cpp with a proper test should be straightforward.

**Comment by RedAuburn** [comment]
idk, i'm not a fan of adding patches to fix other apps issues. we should try to conform as closely as possible to the spec, otherwise OM will be filled with these compatibility hacks

**Comment by biodranik** [comment]
I don't see harm in it. Only more happy users. Fixing source apps is good too.

**Comment by nicpottier** [comment]
Hi guys. I'm thinking of trying to tackle this as a first contribution. Looks pretty straightforward I think though will need to dust off my cpp skills. Are you ok with me putting together a PR for this?

**Comment by biodranik** [comment]
We're ok ) Usually, there's no need to ask about launching a PR, just do it. Questions about alternative implementations or better options/UX are always welcomed though )
