### ISSUE TITLE
[android] Not visible open/close button.

### ISSUE THREAD

**Issue by Endem10n** [organicmaps/organicmaps#882]
Not visible open/close toolbar button for navigation mode on api level 23. Reproduced on Android Emulator.
![Screenshot_1626634138](https://user-images.githubusercontent.com/86627724/126079133-a84e61ea-cc5b-4fdc-ada2-eb83f7d8d871.png)
![Screenshot_1626634141](https://user-images.githubusercontent.com/86627724/126079136-a74c2718-eb1d-4eb2-bda9-d9a1c0284896.png)

**Comment by rtsisyk** [comment]
I didn't get the problem, to be honest.

**Comment by Endem10n** [comment]
Button at the right side of navigation bar should be visible.

**Comment by Endem10n** [comment]
Should look like
![image](https://user-images.githubusercontent.com/86627724/129200991-b6d2cc5e-9001-403c-b685-76ba65c71117.jpeg)
![image](https://user-images.githubusercontent.com/86627724/129200948-41d74b9b-008c-4b8a-b55f-7f94caf934d3.jpeg)
