### ISSUE TITLE
App takes longer trunk detour instead of shorter primary.

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8823]
4.737768, -74.077599 to 4.684999, -74.046393

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=4.7378%2C-74.0776%3B4.6859%2C-74.0457#map=14/4.7113/-74.0623

![telegram-cloud-photo-size-1-4999374553276853534-y](https://github.com/user-attachments/assets/b1530f94-109f-4928-9fbb-f19c7f39bd32)

CC @vng

**Comment by KillerKingSolo** [comment]
I think the problem is it's trying to take you on the fastest path based off of the speed limits.
