### ISSUE TITLE
[android] Not clickable  Instagram item on about screen.

### ISSUE THREAD

**Issue by Endem10n** [organicmaps/organicmaps#885]

**Comment by Akshit6828** [comment]
Hi there! Would love to fix this if you please provide me a link to the Instagram URL of organic maps. 😃

**Comment by Endem10n** [comment]
@Akshit6828 https://www.instagram.com/organicmaps.app/

**Comment by Akshit6828** [comment]
Thanks for this. I'll fix this ASAP. 👍🏻

**Comment by Akshit6828** [comment]
Please check #888 and let me know if any changes are required.

**Comment by Akshit6828** [comment]
Hi @Endem10n. Please check #890 and let me know if any reviews are required. 😃

**Comment by Akshit6828** [comment]
Hello Sir @Endem10n. Please check #900.  😃
