### ISSUE TITLE
windows wsl compile error

### ISSUE THREAD

**Issue by nzb15555196162** [organicmaps/organicmaps#8857]
⚠ Have you searched for similar, already existing issues?

**Describe the issue**
execute ./build_omim.sh -r desktop error
Failed to find Qt component "Positioning"

**Steps to reproduce**
1. clone source code
2. compile 
3.  ./build_omim.sh -r desktop

**Expected behaviour**
compile success

**Screenshots**
![1](https://github.com/user-attachments/assets/5f61e219-1b55-47d0-afce-952437716c72)

**System information:**
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
 - Operating system and its version: [iOS 12, Android 10, Ubuntu 22, MacOS Big Sur, etc.]
 - Organic Maps version: [you can find it by tapping the button with the green Organic Maps logo]
 - Device Model: [e.g. iPhone 6, Samsung S22]
 
5.10.16.3-microsoft-standard-WSL2

**Comment by biodranik** [comment]
Maybe try `sudo apt install libqt6positioning6` ?

@Ferenc- was it mentioned in our docs?

**Comment by Ferenc-** [comment]
> Maybe try `sudo apt install libqt6positioning6` ?
> 
> @Ferenc- was it mentioned in our docs?

Yes. [Here](https://github.com/organicmaps/organicmaps/blob/master/docs/INSTALL.md#fully-supported-versions), `qt6-positioning-dev`, `libqt6positioning6-plugins` and `libqt6positioning6` are listed at the moment.

**Comment by nzb15555196162** [comment]
> Maybe try `sudo apt install libqt6positioning6` ?
> 
> @Ferenc- was it mentioned in our docs?



> > Maybe try `sudo apt install libqt6positioning6` ?
> > @Ferenc- was it mentioned in our docs?
> 
> Yes. [Here](https://github.com/organicmaps/organicmaps/blob/master/docs/INSTALL.md#fully-supported-versions), `qt6-positioning-dev`, `libqt6positioning6-plugins` and `libqt6positioning6` are listed at the moment.

hello all,
    Thank you, doc solved my problem, but it failed to compile the source code, many errors, and finally failed. Is it my environment problem or other problems? Please help me solve it.
The specific error message is in the screenshot
![1](https://github.com/user-attachments/assets/c7a222b8-58a9-4d4a-a5e9-38a80e6b24e1)
![2](https://github.com/user-attachments/assets/fcb3733b-f6be-4ad5-ab60-b5db552c65f8)
![3](https://github.com/user-attachments/assets/10609385-0885-4a96-86e7-d103f194f96a)
![4](https://github.com/user-attachments/assets/8234d3eb-1777-4136-b8c4-6736f8a8cd31)
![5](https://github.com/user-attachments/assets/ec489e63-c146-4bb3-b24f-b30bd50c710e)

**Comment by Ferenc-** [comment]
You seem to have incorrect Qt version. The very [same documentation](https://github.com/organicmaps/organicmaps/blob/master/docs/INSTALL.md#workarounds-for-older-ubuntu-versions) mentions that you need at least `6.4.0`.

**Comment by nzb15555196162** [comment]
> Referenc



> @Ferenc- can CMakeLists.txt explicitly request the minimum required version of the Qt?

hello all,
    Thank you for your guidance, the problem was solved successfully, although it was a specific system. At first I used Ubuntu 22.04. Due to the version problem of the Qt package, I was troubled for a long time, so I manually installed Qt 6.4. Although the manual installation was successful, the compilation project still failed. The specific reasons for the error are as follows. Therefore, I had to use Ubuntu 24.04 and compile it successfully according to the document. It was a bit difficult. Thanks for your reply and guidance. I will close this issue for now. Regarding the compilation problem caused by Qt, I will further study the cause and solution, but QT compilation takes too long, which is very annoying. I would like to ask if there are plans to replace Qt with lightweight tools in the future.

error message: Configuring with --debug-find-pkg=Qt6Widgets might reveal details why the
  package was not found.
