### ISSUE TITLE
[android] wrong text on rate item on about screen.

### ISSUE THREAD

**Issue by Endem10n** [organicmaps/organicmaps#886]
On about screen rate text the same for all builds ("Rate on Google Play"). In F-Droid build and in Huawei AppGalery build it should be different.
![Screenshot_20210718_232258](https://user-images.githubusercontent.com/86627724/126082762-669193db-7c95-4f2f-b7ab-081c4765396e.jpg)

**Comment by pratyaksh1610** [comment]
@rtsisyk I think this issue is resolved in the app, now it says
 `Rate the app` 
under the Help section, looks like this can be closed.

**Comment by Misalf-git** [comment]
Using F-Droid version, tapping "rate this app" leads to
https://organicmaps.app/donate/
while donating is not the same as rating.

**Comment by biodranik** [comment]
@rtsisyk We can rename this button for FDroid.

**Comment by RedAuburn** [comment]
this is fixed in fdroid builds now
