### ISSUE TITLE
Walking navigation doesn't announce street names if sidewalks don't have a name, but streets have names

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8862]
After implementing street announcements in https://github.com/organicmaps/organicmaps/pull/3130 we got feedback from a user that streets are not announced when walking navigation is active. 

The assumption is that most sidewalks do not have names so they're not announced.

Sidewalks names are not rendered, because they pollute the map: https://github.com/organicmaps/organicmaps/pull/6789

Storing names of sidewalks from nearby streets just for announcements may influence the map data size and the search index. A better solution could be to query the nearby streets dynamically and get names to announce from them when building directions. @vng WDYT?

@zyphlar should #8412 be updated?

**Comment by vng** [comment]
Definitely not like in #8861

**Comment by biodranik** [comment]
This issue was caused by missing code and was fixed in https://github.com/organicmaps/organicmaps/pull/8891

Let's see if it should be reopened later.

**Comment by zyphlar** [comment]
@biodranik I'm not sure it's totally fixed. As I mentioned previously some footways don't seem to pick up their nearby road's name, for reasons I can't perceive.

**Comment by biodranik** [comment]
@zyphlar let's create a specific detailed issue with osm data links then (tested already with your patch).
