### ISSUE TITLE
Bookmarks GPX export stores renamed bookmarks with original name

### ISSUE THREAD

**Issue by dkaparis** [organicmaps/organicmaps#8863]
If a bookmark name is changed in OM and later the list is exported to GPX, the exported file contains the original bookmark's name and not the current, modified one.

**Steps to reproduce**
1. Create a bookmark
2. Select bookmark created and tap `EDIT BOOKMARK` and give it a different name
3. Open the `Bookmarks and Tracks` list and for the list containing the above created bookmark, select `Export GPX`
4. The exported file will have the bookmark with its original name in `<name>` tag.

**Expected behaviour**
Exported bookmarks should be named as currently displayed in the app.

**System information:**
 - Operating system and its version: DivestOS 20-20240712-dos-guacamole based on Android 13
 - Organic Maps version: 2024.07.27-8-FDroid
 - Device Model: OnePlus 7Pro

KMZ export also writes the original name in `mwm:name` tag, but adds the currently set one in `mwm:customName` tag.

**Comment by biodranik** [comment]
Avoiding file renaming when it is edited locally has its pros and cons. Changing this behavior may lead to some issues and clashes (for example, characters that are not compatible with the file system, are removed from file names).

Renaming the file only when it's exported looks safe, @cyber-toad right?

> KMZ export also writes the original name in mwm:name tag, but adds the currently set one in mwm:customName tag.

Are you sure about that behavior?

- mwm:name in the Document context always keeps the current list name
- mwm:name in the Placemark context stores the original bookmarked object's names/translations taken from OSM data
- mwm:customName in the Placemark context stores user-typed/customized bookmarked object name

**Comment by biodranik** [comment]
Wow, that's a bug, sorry for misreading it. It should be fixed ASAP.
