### ISSUE TITLE
WiFi text not displayed properly

### ISSUE THREAD

**Issue by fizwidget** [organicmaps/organicmaps#8870]
**Describe the issue**
When I tap on a POI that has WiFi available, it’s displayed as “wifi” on the info card. The search categories list uses “WiFi”, so I guess there’s something wrong with how it’s displayed on POI cards?

**Steps to reproduce**
1. Use the en-GB language preference (unsure if this is required, I haven’t tried others). 
2. Tap on any POI that has WiFi available. 
3. Observe how it’s displayed as “wifi” on the info card. 

**Expected behaviour**
It should be displayed as WiFi (or Wi-Fi). 

**Screenshots**
![IMG_5864](https://github.com/user-attachments/assets/048abde9-7af7-45e5-87da-f2fc34ffca3e)

**System information:**
 - iOS 17.5.1
 - Organic Maps version: ⁦2024.07.27-7⁩
 - Device Model: iPhone XS Max

**Additional context**
N/A.

**Comment by Jean-BaptisteC** [comment]
Fixes by #8631
