### ISSUE TITLE
Display a more informative "nothing found" search message

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8879]
Now if something was not found, the following message is displayed:
```
Oops, no results found.
Try changing your search criteria.
```

At least suggesting downloading the areas where the search is done may improve the situation. Many first-time users search for their villages but can not find them without downloading the corresponding map region first. See #4791

Let's think about better wording to cover not downloaded areas and other possible search failures.

**Comment by DIlkhush00** [comment]
Hi @biodranik, I've some suggestions you might like:

```
No Results Found

Tip: You may need to download the area first if it’s not showing up. Once done, please try your search again.
```

or

```
Oops, No Results Found

Tip: It seems the area you're searching for isn't available. Download the area first, then give it another try.
```

or

```
No Results Found

Tip: It looks like the area you're searching for isn't available yet. Please download the area first and try your search again.
```
