### ISSUE TITLE
Display a more visible ford icon

### ISSUE THREAD

**Issue by ivanbarsukov** [organicmaps/organicmaps#8898]
Now in normal mode and especially in active tourism mode the icons are very poorly visible. Please make them more distinctive. Most likely, there is no need to worry about there being many of them at once.

![image](https://github.com/user-attachments/assets/036d8e85-e840-4a50-b331-275da735b946)
![image](https://github.com/user-attachments/assets/868bc6c4-5894-41dd-8e5b-92b7b3eb3c34)

**Comment by biodranik** [comment]
@euf @dvdmrtnz @RedAuburn any ideas on how it can be improved?

**Comment by dvdmrtnz** [comment]
@ivanbarsukov Can you link to the screenshot's area in OSM?

**Comment by ivanbarsukov** [comment]
Sure, but I am actualizing this area and one of the fords is removed

https://www.openstreetmap.org/node/8402518921
