### ISSUE TITLE
An ordinary building is divided into strange parts

### ISSUE THREAD

**Issue by ivanbarsukov** [organicmaps/organicmaps#8903]
The building without using simple 3d is displayed in parts

OSM link: https://www.openstreetmap.org/way/30824758

![image](https://github.com/user-attachments/assets/1b325dfb-c6f9-4785-8402-5d973c355c95)

**Comment by biodranik** [comment]
What is wrong here?

**Comment by ivanbarsukov** [comment]
Spaces in solid building

![Screenshot_20240810-175051.png](https://github.com/user-attachments/assets/e8f39911-3369-488f-8dba-d5b7bb0a2940)

![Screenshot_20240810-175100.png](https://github.com/user-attachments/assets/7021a143-3e25-4c91-8d12-c595514c162d)

**Comment by biodranik** [comment]
@ivanbarsukov there are no any relations with building parts tags, right?

@renderexpert any ideas on what can be wrong here?

**Comment by ivanbarsukov** [comment]
Yes, I only see the building

**Comment by Jean-BaptisteC** [comment]
Duplicate of #2643
