### ISSUE TITLE
GpsTrackStorage::TruncFile() consumes a lot of battery on each location update

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8927]
The current implementation creates a temporary file, writes all points in memory (for a 24-hour recent track it could be more than 5Mb of points), and replaces the original track storage file, for _each_ location update.

This issue becomes more visible to users after releasing the recent track https://github.com/organicmaps/organicmaps/pull/8183 on Android and implementing track recording on all platforms.

CC @rtsisyk @kavikhalique @kirylkaveryn

**Comment by biodranik** [comment]
Will the track be recorded indefinitely? We already know from other contributor's experiments that 3+ days tracks significantly slow down OM and make it unusable with the current implementation, mostly due to too many points/circles on the screen.

**Comment by kirylkaveryn** [comment]
I've done some research:
1. The `TruncFile` method 
https://github.com/organicmaps/organicmaps/blob/2af91bb48f2f440b731515954a9902207bf93f1d/map/gps_track_storage.cpp#L264
that clips the track's tail is called when `kMaxItemCount (100_000 points) * 2` as described in NOTES (this logic is already implemented here
https://github.com/organicmaps/organicmaps/blob/2af91bb48f2f440b731515954a9902207bf93f1d/map/gps_track_storage.hpp#L53-L63) 
So it doesn't consume a lot of power

2. The track rendering method
https://github.com/organicmaps/organicmaps/blob/2af91bb48f2f440b731515954a9902207bf93f1d/drape_frontend/gps_track_renderer.cpp#L178-L258 
is called on EVERY location update even if there are no new points to draw - see https://github.com/organicmaps/organicmaps/blob/2af91bb48f2f440b731515954a9902207bf93f1d/drape_frontend/gps_track_renderer.cpp#L223C1-L232
or viewport changing and rerenders the spline from scratch calculating all the data/point's colors etc. 

When there are a lot of points to draw the screen starts glitching very much (the track was generated):

https://github.com/user-attachments/assets/71e1874c-ca21-49ef-9260-32607612c499

**Comment by Rob-from-VI** [comment]
If lines are less power intensive than dots, then I vote for lines.

**Comment by biodranik** [comment]
@kirylkaveryn thanks for the detailed analysis! Do we already have a separate issue about track drawing speed? It would be great to copy your analysis there and discuss possible solutions.

**Comment by kirylkaveryn** [comment]
@biodranik I've created one: https://github.com/organicmaps/organicmaps/issues/9488

**Comment by pastk** [comment]
Seems like solved.
