### ISSUE TITLE
Show multiple targets at once

### ISSUE THREAD

**Issue by serrq** [organicmaps/organicmaps#8961]
Show me on map (or in list view) all the international airports in Finland.

![1000117815](https://github.com/user-attachments/assets/6eb1e1a2-adfa-43e3-9279-a9414f05e319)

**Comment by map-per** [comment]
Searching for "airport" will show you all airports in the current view

**Comment by biodranik** [comment]
Check data/categories.txt

**Comment by map-per** [comment]
The file is here: [data/categories.txt](https://github.com/organicmaps/organicmaps/blob/24126adb2bdabe948443dcc43b2cae830fb5250b/data/categories.txt)
