### ISSUE TITLE
Support "landuse=retail" tag

### ISSUE THREAD

**Issue by hujan86** [organicmaps/organicmaps#8967]
Unlike commercial areas, Organic Maps can't display the name of areas designated as "retail" in OpenStreetMap. The retail area's name didn't even appear in the search result. 

Implementation could be the similar to "landuse=commercial" but only need add the "retail" tag. 
[retailarea](https://github.com/user-attachments/assets/8b986d16-1982-48bb-916e-35ef9927875b)

**Comment by Jean-BaptisteC** [comment]
Duplicate of #4146
