### ISSUE TITLE
Obtainium typo

### ISSUE THREAD

**Issue by j5k** [organicmaps/organicmaps#8977]
https://github.com/organicmaps/organicmaps/blob/fa18f73d9d363c893dd4966814fe488e7f055740/.github/workflows/android-release.yaml#L152

Please fix text and url from `Obtanium` to `Obtainium`

**Comment by biodranik** [comment]
Thanks! Fixed in https://github.com/organicmaps/organicmaps/commit/d24eb11dad9dc6be508c1738130c1599f63c6de7
