### ISSUE TITLE
[ios] Voice Directions do not work over a car's Bluetooth

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8988]
Mercedes E-Class 2009.
The Bluetooth device is Audio 50 APS.

Apple Maps, Google Maps and other navigation apps are working well with the APS 50. So it’s not a compatibility problem.

Organic Maps directions are working well with the built-in speakers of the iPhone.

Note that it's _not_ a CarPlay device.

@fabwu any ideas on how it can be fixed? I saw that some apps apply a special "workaround" in their settings for some (older?) bluetooth devices.

**Comment by fabwu** [comment]
We could set the `AVAudioSessionMode` always to `AVAudioSessionModeVoicePrompt` not only when CarPlay is activated:

https://github.com/organicmaps/organicmaps/blob/fe3d9372319091f80fbebd0f36ec2607fa0770ab/iphone/Maps/Core/TextToSpeech/MWMTextToSpeech.mm#L243-L246

Here's the doc from Apple:

> A mode that indicates that your app plays audio using text-to-speech.

> Setting this mode allows for different routing behaviors when your app connects to certain audio devices, such as CarPlay. An example of an app that uses this mode is a turn-by-turn navigation app that plays short prompts to the user.

Source: https://developer.apple.com/documentation/avfaudio/avaudiosessionmodevoiceprompt

@biodranik Do you need a PR or can you build the app yourself and test it?

**Comment by biodranik** [comment]
Let's make a PR and test it from testflight.
