### ISSUE TITLE
RIver labels appear in Lakes

### ISSUE THREAD

**Issue by nicpottier** [organicmaps/organicmaps#8990]
⚠ Have you searched for similar, already existing issues?
Yes

**Describe the issue**
River labels sometimes show up in lakes. This doesn't seem right?

**Steps to reproduce**
1. Search for "Angeline Lake" in "Washington State"
2. Zoom in

"West Fork Foss River" is drawn through center of lake

**Expected behaviour**
No river labels in lakes.

**Screenshots**
![WhatsApp Image 2024-08-16 at 10 37 55 AM](https://github.com/user-attachments/assets/02e1a484-b1fa-4da1-8981-ef97845366d6)

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: 2024.07.29-2-Google
 - Device Model: Pixel 8

**Additional context**
Just adding this for tracking, didn't see it mentioned elsewhere.

**Comment by RedAuburn** [comment]
Likely the waterway through the lake should be tagged as [waterway=flowline](https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dflowline) instead

**Comment by nicpottier** [comment]
Guilty as charged 
<img width="367" alt="image" src="https://github.com/user-attachments/assets/4e4de43b-c424-448a-85f0-528a34c05e74">

Will update, thanks.
