### ISSUE TITLE
Way rendered with arrows because of `oneway=yes`

### ISSUE THREAD

**Issue by o-andras** [organicmaps/organicmaps#9028]
OrganicMaps renders an OSM way with arrows but no background, probably because of `oneway=yes`.

**Steps to reproduce**
1. Go to https://www.openstreetmap.org/way/1259702721 on OrganicMaps

**Expected behaviour**
`oneway=yes` should not have its own rendering, that is, it should not be rendered unless it applies to a feature that should be rendered (e.g. `highway`)

**Screenshots**
![oneway](https://github.com/user-attachments/assets/df79a30d-0623-481a-ab5c-85cda886e966)

**System information:**
 - Operating system and its version: Android
 - Organic Maps version: 2024.08.15-21-FDroid

**Additional context**
Please add any other context or comments here that may be useful.

**Comment by matheusgomesms** [comment]
Is this properly mapped?

**Comment by o-andras** [comment]
I asked on the local OSM group too. We think a `highway` is missing, but a quick look at the wiki suggested that `public_transport=platform` as a way is acceptable by itself (though I'm not too into how public transport is mapped, and I don't see what a platform as a way is supposed to represent of the physical world).

So while this specific feature still needs extra info on OSM, this is still a bug on OM (IMO).

**Comment by Misalf-git** [comment]
Osmose says...
Error:
`Tag highway missing on oneway`

and minor problem:
```
suspicious tag combination
oneway on suspicious object
```

`public_transport=platform` is the platform (or area) from which passengers enter a bus (or tram etc.), not the road (or rail) the transporting vehicle travels on.

I'd change this to `highway=service` and add a separate `public_transport=platform` and/or `highway=platform` at the place where people are actually supposed to stand and wait for the bus.

**Comment by Misalf-git** [comment]
Nonetheless, this is still true:
> **Expected behaviour**
> `oneway=yes` should not have its own rendering, that is, it should not be rendered unless it applies to a feature that should be rendered (e.g. `highway`)

**Comment by o-andras** [comment]
Right, I think we agree on everything :) We (the local group) are just waiting for someone to pass nearby and take a photo before fixing.

**Comment by patepelo** [comment]
This has been changed in OSM data (https://www.openstreetmap.org/way/1259702721/history)

On the next OM map data update it should be rendered differently and the issue can be closed.

**Comment by o-andras** [comment]
> On the next OM map data update it should be rendered differently and the issue can be closed.

@patepelo That's not the whole truth. The OSM data was fixed so the OM data will be fixed as well on the next update. However, the underlying bug is still not fixed!

**Comment by Misalf-git** [comment]
On second thought, is it really necessary for OM to "fix" this rendering-wise, if it only occurs for incorrectly tagged objects?

**Comment by o-andras** [comment]
I would say yes because (1) it's something that can easily happen on OSM (out of OM's control), but (2) OM users are affected (in OM's control). Users shouldn't need to know why there are arrows on the map if there's no routable way. Whether you think this particular case should or shouldn't be fixed on OM's side, there's clearly an user-friendliness argument to be made here, because "what the hell is an `hwtag-oneway`"?

The only plausible reason I can think of is that users may find and fix the errors in OSM instead of letting them live on. On the other hand, as [you have already mentioned before](https://github.com/organicmaps/organicmaps/issues/9028#issuecomment-2299144398), there are other tools for this, such as Osmose.

**Comment by patepelo** [comment]
OM could have a complex code to double secure such cases where OSM quality is bad, but to be realistic and practical this is not the current priority, this issue can be left open for the many years coming. Nor is is critical in the event such cases happen. The best way to avoid this is for Osmose and other QA volunteer projects doing their best and multipying the efforts to the diverse end consumers of the data. I'm going to close this issue to clear things up a bit in the over 2k+ list of pending issues. Thank you for raising it and let's continue discussions in other topis. Feel free to reopen if anyone considers.
