### ISSUE TITLE
Is addr:place being used?

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#9029]
I saw a couple of issues and PRs, open, closed and merged (mainly #6643), and still in doubt: is addr:place being used at all?

My case here (iOS):

At University of Hamburg, in a given campus they have this park/pedestrian area, with a name (Von-Melle-Park), in which I suppose the "correct" OSM tag to address the surrounding buildings is addr:place (and not addr:street, since it is not a street at all).

In OM I can see:

- the search does not work (eg: Von-Melle-Park, 3) (#557)
- the address is not shown in Place Page (#5890)
- in editor, the "Add a street" button is empty (#6491, #6821)

So, what is wrong here? OSM or OM?

Reference area: https://www.openstreetmap.org/#map=17/53.566226/9.984888

**Comment by matheusgomesms** [comment]
PS.: These buildings were tagged as addr:street before, but since OM makes some magic in matching street name with addresses, and no road around has name=Von-Melle-Park, the addresses were also not displayed. (already described similar situation here #7679)

**Comment by vng** [comment]
Ok, first I'd like to explain how matching works in _very short_:
- addr:place - OM generator looks for the nearby place=* object with the same name to _connect_ address object with its parent.
- addr:street - OM generator looks for the nearby highway=* (or place=square) object with the same name to _connect_ address object with its parent.

In your example, OSM has highway=footway + area=yes with name='Von-Melle-Park'.
I believe that all addresses should be mapped like addr:street here. Please, correct me if I'm wrong.

**Comment by matheusgomesms** [comment]
Thanks!

True, I converted the tag wrongly. According to wiki: An address may bear the name of a street that no longer exists, has been demolished, or never existed in the first place. Sometimes the name of a pedestrian walkway ([highway](https://wiki.openstreetmap.org/wiki/Key:highway)=[pedestrian](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpedestrian)) or square ([place](https://wiki.openstreetmap.org/wiki/Key:place)=[square](https://wiki.openstreetmap.org/wiki/Tag:place%3Dsquare)[[1]](https://wiki.openstreetmap.org/wiki/Key:addr:street#cite_note-1)) is used instead of a drivable street.

However, as I said in the previous comment, they were tag before with addd:street and it still didn't show up in OM. I'll revert the changes and we can check that.

**Comment by vng** [comment]
Thanks for this case, will check after the new data update.

**Comment by hungerburg** [comment]
> object with the same name to _connect_ address object with its parent

@vng I'd say, with place names no guaranty for success, e.g. https://www.openstreetmap.org/node/663411153 will fail, yet Stadtbahnbogen definitely not a street nor hamlet.

**Comment by vng** [comment]
@hungerburg Yes, this is an open problem for now, and needs a completely new approach in address indexing.

**Comment by hungerburg** [comment]
@vng From what I observe, the chaining to a parent (street or place) as mentioned in the other topic is not tested when users add data. OM users here add street names where there is no street of that name not nearby, not even in town.
