### ISSUE TITLE
Android Auto uses phone compass instead of car

### ISSUE THREAD

**Issue by Karmalakas** [organicmaps/organicmaps#9034]
**Describe the issue**
Exactly what title says

**Expected behaviour**
Car compass is used

**Screenshots**
https://github.com/user-attachments/assets/63b495e8-26c2-4fc0-a9aa-bf150032c8a4

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: 2024.08.17-4-Google
 - Device Model: Pixel 6a
 - 2023 Toyota Rav4

**Comment by biodranik** [comment]
Is there a compass in a car? @AndrewShkrob

**Comment by Karmalakas** [comment]
> Is there a compass in a car? @AndrewShkrob 

I believe yes. I can set cars navigation to show compass with a destination pin on the edge instead of a map with actual directions

**Comment by biodranik** [comment]
@Karmalakas please enable logs in OM settings, restart OM, reproduce the issue, and send us logs via Report a bug.

**Comment by Karmalakas** [comment]
I've replaced my coordinates with `00.000,00.000` in the log
Also I noticed this in a few places (some have `count was: 2`):
```
08-22 10:32:03.573 (main) D/CarSensorsManager: CarSensorsManager.java:113 onCarCompassUnsupported(): 
08-22 10:32:03.574 (main) D/SensorHelper: SensorHelper.java:116 addListener(): listener: app.organicmaps.car.util.CarSensorsManager$$ExternalSyntheticLambda1@42b7db0 count was: 1
```

[logs.zip](https://github.com/user-attachments/files/16707547/logs.zip)

**Comment by AndrewShkrob** [comment]
As you may see, `onCarCompassUnsupported()` was called. This means Android Auto cannot get data from the car's compass. This may be a bug in the Android Auto implementation, or more likely, your head unit does not provide hardware sensor information to Android Auto.

I don't think there's anything we can do about that.

**Comment by Karmalakas** [comment]
Can we get an option to disable compass completely when connected and adjust map orientation only by moving direction? Currently it's quite frustrating to use it when whole maps starts rotating and shaking when phone is moving. It seems Google and Waze maps don't show your orientation on car until you start moving.

**Comment by AndrewShkrob** [comment]
Why don't you use the location button to adjust orientation? There is an option that locks map rotation. Like in the mobile app

**Comment by AndrewShkrob** [comment]
Is that what you want? 🙂


https://github.com/user-attachments/assets/8b755986-b777-46e2-b2e7-075d3f1dba50

**Comment by Karmalakas** [comment]
I don't think so. That's what I have currently. In your video there are at least two issues:
- Map rotates like crazy as soon as you start the navigation 
- Even when it starts moving it's still shaky and very noticeable that it can't keep orientation to the driving direction

Both are quite distracting

Also, what happens when you turn? I assume it keeps the moving direction at the top as expected. 

I'll try to test this tomorrow 🙏

**Comment by AndrewShkrob** [comment]
No, the map keeps the north direction when navigation is off. When you turn on navigation, the map follows the driving direction.

**Comment by Karmalakas** [comment]
OK, I think I can get used to this. It's just a bit confusing when the arrow shows a different direction than the car is facing while not moving
