### ISSUE TITLE
[bookmarks] Add GeoJSON support to the Google Maps bookmark script

### ISSUE THREAD

**Issue by fabwu** [organicmaps/organicmaps#9038]
Google Maps exports bookmarks in CSV and GeoJSON format (see #8721). The `tools/python/google_maps_bookmarks.py` supports only CSV at the moment. It would be great if the script could also convert GeoJSON.

**Comment by rudokemper** [comment]
Having recently written code for this workflow in JS at https://github.com/rudokemper/google-maps-places-to-organic-maps, I can work on this if somebody else isn't already taking it on.
