### ISSUE TITLE
Compass drift

### ISSUE THREAD

**Issue by Minecodes** [organicmaps/organicmaps#9045]
⚠ Have you searched for similar, already existing issues?
Yes

**Describe the issue**
When I walk, the navigation error is 90°-180° to my relative walking direction. This is a problem because I can't use the map rotation with the compass.

**Steps to reproduce**
1. Choose compass rotation
2. Walk/Rotate the device (optionally try to calibrate it)
3. The arrow should face 90-180° to your device rotation

**Expected behavior**
The navigation arrow should face the direction the device is facing

**Screenshots**
![Screenshot_20240821-164650.png](https://github.com/user-attachments/assets/1304c15c-266f-4724-b855-9b4dc7d353bc)
The drawn arrow is the direction my device is facing

**System information:**
 - Operating system and its version: Android 14 / Nothing OS 2.6
 - Organic Maps version: 2024.08.15-21-FDroid
 - Device Model: Nothing Phone 2
 - Logs: https://paste.minecodes.de/unvulcanized-aniya.zip

**Comment by biodranik** [comment]
It looks like a device/hardware issue, please check https://www.reddit.com/r/NothingTech/comments/18qfxia/nothing_phone_2_compass_issue/

Does calibration immediately help?

Do you have any magnets/metal on the case or nearby?

**Comment by patepelo** [comment]
<stale>
