### ISSUE TITLE
outdoor_seating=no is added to all POIs by the editor

### ISSUE THREAD

**Issue by map-per** [organicmaps/organicmaps#9049]
Since the last release (2024-08-17-4-google) `outdoor_seating=no` is added to all POIs by the editor. The bug only occurs on android.

Example: https://www.openstreetmap.org/changeset/155576448 added `outdoor_seating=no` to a building

The bug looks limilar to #7642

**Comment by RedAuburn** [comment]
Can reproduce

**Comment by biodranik** [comment]
@vng is it related to a weird way of storing this metadata as a string? Can you please help with refactoring and fixing?

**Comment by Arthur-GYT** [comment]
I've identified the problem and I'll fix it before tonight.

**Comment by Arthur-GYT** [comment]
Unfortunately, it's going to take a little longer (1 day I hope). I'll have to use a system similar to the self_service tag

**Comment by haansn08** [comment]
More changesets that seem to be produced by this bug:
* https://www.openstreetmap.org/changeset/155967909
* https://www.openstreetmap.org/changeset/155968512
* https://www.openstreetmap.org/changeset/155968785

Will there be an effort by the Organic Maps team to undo the damage done by this bug?

**Comment by map-per** [comment]
Fixing the damage in OSM will be tricky. We need to remove all `outdoor_seating=no` tags that were added with the affected versions of OrganicMaps. By now (~one to two weeks since the release) an estimated number of 4,000 POIs is affected (10,000 is the monthly edit count of OrganicMaps Android) .

Affected versions: `Organic Maps android 2024.08.17-4-Google`, `Organic Maps android 2024.08.16-5-Web`, `Organic Maps android 2024.08.16-5-FDroid`, `Organic Maps android 2024.08.15-21-FDroid`, huawei version?, ...?

Does anyone know how we can fix the OSM databaset? @RedAuburn

**Comment by biodranik** [comment]
@map-per iOS edits are not affected, correct?

**Comment by map-per** [comment]
Yes, iOS is not affected (see: https://github.com/organicmaps/organicmaps/pull/9165#issuecomment-2322125316)

**Comment by Arthur-GYT** [comment]
I found a solution (with material 2)
![image](https://github.com/user-attachments/assets/f064ca1b-8bb2-4329-bb7f-38a3520f47df)

**Comment by Arthur-GYT** [comment]
@biodranik I've proposed another version of the fix on #9110

**Comment by map-per** [comment]
This Issue was fixed in #9165

**Comment by haansn08** [comment]
@map-per Is there an issue to track the cleanup effort?

**Comment by map-per** [comment]
There is no separate issue. You can create one if you want, but I think we can just keep discussing that in this issue.

**Comment by Fizzie41** [comment]
Sorry, but are you certain it's fixed?

OSM Changeset https://www.openstreetmap.org/changeset/156372040 was done at 2024-09-08T23:36:33Z & added outdoor_seating=no, but the OP says they didn't add it themself?

**Comment by haansn08** [comment]
@Fizzie41 It says this changeset was made by the affected OrganicMaps version `Organic Maps android 2024.08.16-5-FDroid`. The bug is probably fixed in the source code, but an unaffected version of OM still has to be released + people have to update their apps.

**Comment by SomeoneElseOSM** [comment]
I'd suggest posting to the forum c.osm.org about it in case anyone has any ideas, and add a link from this Github bug to there, and from the forum to this Github bug.  

Numbers of changesets for each of the allegedly affected versions (not including Huawei):

    changesets=> select count(*) from osm_changeset where created_at > '20240711' and tags -> 'created_by' = 'Organic Maps android 2024.08.17-4-Google';
     count
    -------
      3505
    
    changesets=> select count(*) from osm_changeset where created_at > '20240711' and tags -> 'created_by' = 'Organic Maps android 2024.08.16-5-Web';
     count
    -------
       474
    
    changesets=> select count(*) from osm_changeset where created_at > '20240711' and tags -> 'created_by' = 'Organic Maps android 2024.08.16-5-FDroid';
     count
    -------
      3286
    
    changesets=> select count(*) from osm_changeset where created_at > '20240711' and tags -> 'created_by' = 'Organic Maps android 2024.08.15-21-FDroid';
     count
    -------
       492

**Comment by map-per** [comment]
@SomeoneElseOSM: Thanks for taking a look at this. I [posted on the forum](https://community.openstreetmap.org/t/how-to-clean-up-osm-after-organic-maps-outdoor-seating-no-bug/119797), let's hope someone knows a solution.
