### ISSUE TITLE
[HELP] How to make itinerary from KML bookmark import

### ISSUE THREAD

**Issue by cyb31** [organicmaps/organicmaps#905]
Hello,
I would like to make an itinerary from waypoints I have imported to Organic Maps via Bookmark import.
My problem is that I can view waypoints but no itinerary joins them. When I would like to make one manually, I can't choose waypoints from bookmark list.
[<a href="https://ibb.co/4sqdHyF"><img src="https://i.ibb.co/4sqdHyF/Picture1.jpg" alt="Picture1" border="0"></a>](url)
When I would like to make an itinerary manually, I can put only 3 waypoint (A, B and C).
[<a href="https://ibb.co/8gTc92t"><img src="https://i.ibb.co/8gTc92t/Picture2.jpg" alt="Picture2" border="0"></a>](url)
You can see on the first picture that there is not itinerary and on the second picture, when I would like to make itineray manually, I can only put 3 waypoints (a,b,c).
Is there a way to do fix that?

**Comment by biodranik** [comment]
Are you building a walking route? There is a limit to a total of 5 waypoints at the moment.

**Comment by cyb31** [comment]
Hello,
I have built a road trip (for motorbike riding) with a software (http://www.benichou-software.com/index.php?option=com_content&view=article&id=4&Itemid=2&lang=fr) and export it in KML format. 
The aim is to have mandatory waypoints in my road trip.

**Comment by biodranik** [comment]
Thanks! As I mentioned, right now there is a limit of 5 points max if you build an itinerary manually. We need to think about how we can properly implement it for your use case.

**Comment by cyb31** [comment]
Ok, I Hope you Can do to his easily 😜

**Comment by cyb31** [comment]
Is it difficult to implement more than 5 points? Because I think a lot of bikers will use you app for their road trip!

**Comment by biodranik** [comment]
Nobody estimated yet. Will see.

**Comment by biodranik** [comment]
@cyb31 we implemented 100 waypoints support a long time ago. Did you try to test it? Can we close this issue?

**Comment by cyb31** [comment]
Hello @biodranik, I tried and it seems to bo work. Thanks a lot for the job :-)
