### ISSUE TITLE
Failed debug-build for android in Android Studio

### ISSUE THREAD

**Issue by Maschga** [organicmaps/organicmaps#9052]
**Describe the issue**
Starting this project in the debug-mode in Android Studio results in a failed build: [`File: log.txt`](https://github.com/user-attachments/files/16708183/log.txt)

**Steps to reproduce**
I followed the instructions in [`docs/INSTALL.md`](https://github.com/Maschga/organicmaps/blob/24126adb2bdabe948443dcc43b2cae830fb5250b/docs/INSTALL.md).

**Expected behaviour**
Successful build.

**System information:**
 - Operating system and its version: Windows 10
 - Organic Maps version: See [my fork](https://github.com/Maschga/organicmaps/tree/24126adb2bdabe948443dcc43b2cae830fb5250b)
 - Device Model: **Pixel 8 Pro API 34** in Android Studio as virtual device

**Additional context**
Perhaps the build fails because gradle can not handle the redirects in the files [`android/app/src/main/res/values-zh-rHK/strings.xml`](https://github.com/Maschga/organicmaps/blob/480fa6c2fcf53be296504ac6ba8e6b3d70f92b42/android/app/src/main/res/values-zh-rHK/strings.xml) and [`android/app/src/main/res/values-zh-rMO/strings.xml`](https://github.com/Maschga/organicmaps/blob/480fa6c2fcf53be296504ac6ba8e6b3d70f92b42/android/app/src/main/res/values-zh-rMO/strings.xml). Or these `Deprecated Gradle features` are the cause for the problem

=========

Thank you very much for this great project!
~ Maschga

**Comment by biodranik** [comment]
This error means that you did not enable symlinks support in your system/in git, as mentioned in the instructions. You may need to delete all working copy files in git after that and do a checkout again.

**Comment by Maschga** [comment]
I'll try it, thank you very much!
