### ISSUE TITLE
Organic Maps can't open gpx file from UMAP

### ISSUE THREAD

**Issue by alexgabi** [organicmaps/organicmaps#9064]
⚠ Have you searched for similar, already existing issues?

**Describe the issue**
organic maps cannot open gpx files created using UMAP (https://umap.openstreetmap.fr/). Opening file with... Organic Maps and OM don't run.

**Steps to reproduce**
1. In Telegram: gpx file > click
2. Open file with... > Organic Maps
3. Organic maps don´t run. No error message.

**Expected behaviour**
Organic Maps runs and and shows items of the gpx file

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**System information:**
 - Android 9
 - Organic Maps version: 2024.08.16-5-android
 - Xiaomi Readme Note 9

**Additional context**
Please add any other context or comments here that may be useful.

**Comment by biodranik** [comment]
Can you please share a video recording of the screen? When any app is selected to open a file, this app should be launched by a system. And in the case of OM, you should see either a success or an error message. If OM is not launched by a system, it could be some other issue.

Do KML/KMZ files open correctly? Do other GPX files open correctly?

**Comment by alexgabi** [comment]
Sorry, the issue happend with [2024.07.27-8-android] release, with [2024.08.16-5-android] releases app works fine. Plese, close the issue.
