### ISSUE TITLE
[navigation] Use yards instead of feet in the UK.

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#9074]
A few users from the UK have pointed out that the app uses feet in places where yards are typically expected.

In the UK and the US, road measurements typically use different units of measurement:

UK: Road measurements are generally given in yards. Speed limits, for instance, are commonly displayed in miles per hour, but distances and road signs are often in yards and miles. For example, road signs might indicate distances to landmarks or junctions in yards.

US: Road measurements are primarily in feet and miles. Speed limits are given in miles per hour, but distance markers, road signs, and construction zones are often measured in feet and miles. For example, a highway might have mile markers and construction signs indicating distances in feet or miles.

CC: @RedAuburn @dwaynebailey

**Comment by doug8888** [comment]
I was about to suggest this option. It would be good to be able to choose miles and yards or even miles and meters like you can in OsmAnd.

**Comment by RedAuburn** [comment]
also https://github.com/organicmaps/organicmaps/issues/3676

**Comment by RedAuburn** [comment]
closing as dup
