### ISSUE TITLE
Location Services Failed

### ISSUE THREAD

**Issue by ANONYMOUSEJR** [organicmaps/organicmaps#908]
Ive recently Switched my phone to a new one and noticed that, even after i gave location permission the app couldnt find where i was it just told me that i might not be in clear view of the sky.

Note: Reinstalling it didnt work.

**Comment by biodranik** [comment]
Did other apps work at the same time? GPS detection can take a lot of time depending on many conditions and depending on your device's model.

**Comment by ANONYMOUSEJR** [comment]
Thank you for replying,
I did some further checking and Organic maps was the only app that would need to use location services.

My current device is a Samsung A51 while the last one was a Samsung A31.

As i still have my old phone i redownloaded the app and found that it worked perfectly.


Also im not sure whether this is helpful or not but here is a screenshot of the error message (let it be known that both this device and my older one were in the same place during the test):
![Screenshot_20210723-124442_Organic Maps](https://user-images.githubusercontent.com/64444223/126771697-6f52fcf9-66d2-47f8-ba18-6bd0637b0fff.jpg)

**Comment by biodranik** [comment]
So on A51 location in OM does not work, but it works in all other apps. Right?

**Comment by ANONYMOUSEJR** [comment]
Hello, sorry for my late reply i reckon ive figured it out.
First to answer your question, yes ive tried other apps which were dependant on location services and they worked well enough.

I also think that the reason was a very bad connection to the satelites in orbit.

As of now for some reason my A51 has managed to function in terms of location, this was however after i was fully outside.

All i can think of is this may be because the satellites needed to locate my device?

Im sorry if i wasted your time with this.

Thank you for your time.

**Comment by ANONYMOUSEJR** [comment]
Also if i may ask, i noticed that in another app, Trail Sense, that i gives me the option to force the app to connect to a specific amount of Satellites before actually pinpointing me.
How many satellites does this app connect to before pinpointing me?
And is it possible to make it so that OM gives me the option to force it to connect to the number of satellites for a more stable and accurate location?

**Comment by biodranik** [comment]
Thanks, it would make sense to add some GPS debug info using https://developer.android.com/reference/android/location/GpsSatellite, @rtsisyk what do you think?

**Comment by studokim** [comment]
I'm experiencing the same problem on the LG G7, Android 8.0.0. App version 2021.08.05-15-<...>-FDroid. Location works in every app but Organic Maps.
Maps are downloaded and permissions are given.
Don't know, how to fetch GPS debug info though.

**Comment by biodranik** [comment]
@studokim which location providers do you have available in your settings?

**Comment by studokim** [comment]
GPS, network and WiFi (high accuracy mode). 

Actually the problem's gone now after reboot, although yesterday that didn't help.

**Comment by rtsisyk** [comment]
>Don't know, how to fetch GPS debug info though.

https://play.google.com/store/apps/details?id=com.chartcross.gpstest

**Comment by rtsisyk** [comment]
The latest release doesn't have any known GPS bugs. Please feel free to re-open if locations works in another apps and don't work in Organic Maps.
