### ISSUE TITLE
  Cannot find source file ../private.h in platform/CMakeLists.txt 

### ISSUE THREAD

**Issue by nzb15555196162** [organicmaps/organicmaps#9089]
⚠ Have you searched for similar, already existing issues?

**Describe the issue**
  Cannot find source file ../private.h in platform/CMakeLists.txt  

**Steps to reproduce**
platform/CMakeLists.txt line 177../private.h does not exist in the project main directory

**Expected behaviour**
If this is indeed the case, please fix it, but I'm wondering why the installation went fine.

**Comment by biodranik** [comment]
Please read documentation carefully. You forgot to run the configuration script.
