### ISSUE TITLE
If you select a node that has outdoor seating and then select something else it will incorrectly say it also has outdoor seating

### ISSUE THREAD

**Issue by Aerondyyyy** [organicmaps/organicmaps#9100]
⚠ Have you searched for similar, already existing issues?
Yes, i found #9049 which also is about outdoor seating but it involves the editor and this bug is about displaying the property.

**Describe the issue**
If you click a node that has `outdoor_seating=yes` and then click a second node that doesn't have it and expand it then it looks like the second object has outdoor seating even though it doesn't.

**Steps to reproduce**
1. Find a node that has `outdoor_seating=yes` like [this ice cream shop](https://www.openstreetmap.org/node/1778361759) and another nearby poi that doesn't have it like [this clothes shop](https://www.openstreetmap.org/node/4850279044).
1. Scroll to them on the map
1. Make sure nothing is selected
1. Click the first node for the ice cream shop with outdoor seating but don't "expand it".
1. Click the second node for the clothes shop and expand it to view more info, check if it has outdoor seating.
1. Close the node.
1. Click the clothes shop again and expand it to check if it's different in any way.

**Expected behaviour**
You would expect the clothes shop info to be displayed and it is but it also shows "outdoors seating" which is incorrect, it's like it inherits the property of the last thing selected.

**Screenshots**

<details>
<summary>Click here to see the screenshots</summary>

![lx5jeBiWST](https://github.com/user-attachments/assets/51f90c14-c539-4a22-b963-b15abea22140)

</details>

**System information:**
 - Operating system and its version: Android 14 (API 34)
 - Organic Maps version: 2024.08.17-4-Google
 - Device Model: OnePlus8T (KB2003)

**Additional context**
None.

**Comment by biodranik** [comment]
@Arthur-GYT can you please also fix this one?
