### ISSUE TITLE
Open in other applications only if you have already installed it

### ISSUE THREAD

**Issue by olivertzeng** [organicmaps/organicmaps#9103]
⚠ Have you searched for similar, already existing issues? Yes

**Is your feature request related to a problem? Please describe.**
I've not installed OpenStreetMaps but it still shows it in the menu

**Describe the ideal solution**
Hide apps that aren't installed in the menu

**Describe alternatives you have considered**
- How do you solve this issue now with Organic Maps or other apps?
- I don't

**Additional context**
![image](https://github.com/user-attachments/assets/25fdfe52-1b6e-4f56-b831-ede004a44da0)

**Comment by biodranik** [comment]
This is intentional to open a web site with OSM.

**Comment by olivertzeng** [comment]
> This is intentional to open a web site with OSM. 

How about other apps like Google maps
If it's not installed will the option show?
