### ISSUE TITLE
Add Go!! Maps in the open in other maps menu

### ISSUE THREAD

**Issue by olivertzeng** [organicmaps/organicmaps#9104]
⚠ Have you searched for similar, already existing issues? Yes

**Is your feature request related to a problem? Please describe.**
I always wanted to edit a place with Go!! Maps but view it in Organic Maps. Opening the place in it would be nice.

**Describe the ideal solution**
Add Go!! maps to the open in other maps menu if installed

**Describe alternatives you have considered**
No

**Additional context**
![image](https://github.com/user-attachments/assets/e9f5bcac-db65-4565-bb60-dcb0f3c3ae90)

**Comment by biodranik** [comment]
This is an example of an url scheme to use: https://github.com/bryceco/GoMap/blob/master/src/iOS/PhotoShare/ShareViewController.swift

@bruceco correct?

P.S. I also like and use Go! Map. @kirylkaveryn it should not be hard to add it into a list.

**Comment by bryceco** [comment]
For "Go Map!!" the URL should look like this:

https://gomaposm.com/edit?center=47.679056,-122.212559&zoom=21&view=aerial%2Beditor

**Comment by biodranik** [comment]
@bryceco as we're checking the presence of the app, and then opening the app directly, using local URL scheme would be preferred. Is it a correct example?
`gomaposm://edit?center=47.679056,-122.212559&zoom=21&view=aerial%2Beditor`

What is the `view` parameter about?

**Comment by bryceco** [comment]
`zoom` and `view` are optional. `view` indicates the editing mode to use, and can be one of:
- "aerial+editor": editing with aerial imagery as the background 
- "aerial": only shows aerial imagery
- "mapnik": only shows a base map 
- "editor": only shows the editor 

If you omit that parameter then it uses whatever the user most recently chose.

**Comment by bryceco** [comment]
Support for the gomaposm: url scheme seems to be broken at the moment.

**Comment by kirylkaveryn** [comment]
@biodranik @biodranik I'll add this one ASAP.

**Comment by bryceco** [comment]
Much appreciated everyone!
