### ISSUE TITLE
Update Subway data

### ISSUE THREAD

**Issue by MASangys** [organicmaps/organicmaps#911]
This validator shpuld update, already been long time no update.
http://osm-subway.maps.me/

**Comment by starsep** [comment]
You can find this report generated on 27.06.2021 00:32
https://alexey-zakharenkov.github.io/subways/rapid/index.html
Pinging author @alexey-zakharenkov

I agree up-to-date version should be hosted somewhere under https://organicmaps.app/ domain

**Comment by dikkechill** [comment]
I see https://cdn.organicmaps.app/subway/ has been active for a while. 
I guess this issue can be closed.

**Comment by strump** [comment]
Another outdated metro issue? Should we close it?
