### ISSUE TITLE
POI prison doesn't show up in search results

### ISSUE THREAD

**Issue by TheBiostarfly** [organicmaps/organicmaps#9121]
⚠ Have you searched for similar, already existing issues?

Yes

**Describe the issue**

When searching for the POI type prison it only shows places which have prison in the name not the POI. 

**Steps to reproduce**
1. Go to search
2. Search for prision
3. See that there are only results with 'prison' in the search results

**Expected behaviour**
I would expect it to show all prisons including the POI 

**System information:**
 - Operating system and its version: Android 14, OM Version 2024.08.16-5

**Comment by biodranik** [comment]
Looks like prisons were not added into data/categories.txt yet.

**Comment by jasmeen04** [comment]
I want to work on this issue. Please assign me this issue.
