### ISSUE TITLE
UTC timestamp with milliseconds isn't parsed

### ISSUE THREAD

**Issue by kirylkaveryn** [organicmaps/organicmaps#9127]
Our code parses only the timestamp strings with 20 (UTC) or 25 chars:
https://github.com/organicmaps/organicmaps/blob/56f5ed6a88fd57462d8f3fd6007e99216eb54b6f/base/timer.cpp#L117-L153

But there are some apps that use UTC date format with milliseconds and may be in the 20...25 range:
`2013-02-04T22:44:30.652Z`

For now, such strings cannot be parsed and all the timestamp data will be missed (method returns `-1`). 
The correct parsing is needed to implement #8972

**Comment by biodranik** [comment]
@kirylkaveryn Good catch! It should be easy to fix the parser and add a few unit tests. As these values break the ISO 8601 standard, but are produced by some "bad" software, we need to handle it properly and maybe print a warning in log.

**Comment by biodranik** [comment]
RFC says that fractions of seconds are valid, so we definitely should support it in the parser:
<img width="878" alt="выява" src="https://github.com/user-attachments/assets/0dc020b6-4bf4-4db6-9280-7df731b11b5b">
