### ISSUE TITLE
"route to" bookmark

### ISSUE THREAD

**Issue by ayounggun** [organicmaps/organicmaps#914]
Hi organic maps

It would be great to have an easy way to "route to" a bookmark. I'm not sure if there is a way to do this already.

I tried long pressing one of the bookmarks and also tapping a bookmark. When I tap a bookmark, it opens up the bookmark's location on the map, but I can't see a route to option from this part of the app.

Thanks!

**Comment by amo-f77** [comment]
When I tried what you describe, I have "route from" and "route to" options at the bottom of the screen on Android.

**Comment by ayounggun** [comment]
Ah! This is what I see.

I now see where the icons should be for "route to" etc on the blank the grey bar at the bottom.

I run grapheneos on a pixel3a with organic maps installed from fdroid.

I'll reboot my phone an see whether its an intermittent problem.

Thanks for the quick reply. 

[![signal-2021-07-23-181351.jpg](https://i.postimg.cc/cCrT1krB/signal-2021-07-23-181351.jpg)](https://postimg.cc/H81bB20r)

**Comment by ayounggun** [comment]
Just before I rebooted I noticed that the "route to" icons where there. I had never seen them there before.

I rebooted anyway and now they are not there again so its an intermittent issue. I have emailed some logs.

**Comment by ayounggun** [comment]
Its actually not just the bookmark area these icons are missing but other areas of the app too. 
[![signal-2021-07-23-182837.jpg](https://i.postimg.cc/d1qnTtS6/signal-2021-07-23-182837.jpg)](https://postimg.cc/v1N5JMyx)

**Comment by biodranik** [comment]
@rtsisyk did we already fix it?

**Comment by SeanConn15** [comment]
I can confirm I also saw this issue, but have not seen it recently. It's been at least a couple of weeks, probably about a month since I saw it last

**Comment by ayounggun** [comment]
I've just tried removing and re adding the app from F Droid and the issue seems to have gone away.

Please feel free to close the issue.

I had tried update all on F droid and there were no updates. I thought reinstall would be worth trying as you all had mentioned fixing the issue already.

Is there a place that I can send a donation?

Thanks

**Comment by biodranik** [comment]
Please check a "Sponsor" button with the heart above :) The issue you encounter is a weird bug with buttons layout on Android 11. There is a probable fix for it in the master branch waiting to be published in the update. But if you encounter the same bug again, please let us know the exact steps to reproduce it. Restarting the app should help to restore disappeared icons.
