### ISSUE TITLE
Self Hosted OSM Instance

### ISSUE THREAD

**Issue by jonasneumair** [organicmaps/organicmaps#9149]
⚠ Have you searched for similar, already existing issues? Yes, I have searched, but I did not find an issue related to this specific request.

**Is your feature request related to a problem? Please describe. 
I want to use Organic Maps with a privately hosted OSM instance or tile server, especially for private properties. These private instances contain customized data that I cannot publish officially on OSM due to privacy concerns, but I still need to access them frequently.

**Describe the ideal solution 
The ideal solution would be to allow Organic Maps to integrate with a privately hosted OSM instance or tile server. This feature would enable users to "interpose their private servers, allowing them to view and manage custom map data directly within Organic Maps without the need to push changes to the official OSM servers.

**Describe alternatives you have considered
Currently, I i dont have a solution using Organic Maps.

Another alternative could be using apps that support custom tile server integration, but these often lack the user-friendliness compared to Organic Maps.

**Additional context 

This feature would be particularly useful for managing private properties or restricted areas where map data needs to be kept confidential. The ability to use a private OSM instance within Organic Maps would streamline the workflow and enhance privacy.

**Comment by biodranik** [comment]
You can already take any custom data in OSM format, generate maps, and build a client to use your own data. So what are you asking is already possible.

Supporting some private custom data/styles in the official Organic Maps version is not technically feasible.
