### ISSUE TITLE
`leisure=pitch` and `leisure=sports_centre` are indistinguishable when together

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#9164]
`leisure=pitch` and `leisure=sports_centre` use the same color and are imposible to distinguish when one is on top of the other. They should use at least different shades of color to be able to see different pitches inside sports centres.

<img src="https://github.com/user-attachments/assets/b807052e-8c5f-4317-a629-86eca571a1e3" width="320"/>

<img src="https://github.com/user-attachments/assets/2a43ef19-dae6-4e4e-b4c6-0a2720563720" width="320"/>

**Comment by map-per** [comment]
The problem is not the `leisure=sports_centre` tag, but that OM treats everything that has a `sport=*` tag as a pitch. https://www.openstreetmap.org/way/51161587 is tagged with `sport=multi`.

OM should require `leisure=pitch` for sport pitches.

**Comment by map-per** [comment]
There is a similar issue with this FC Bayern fan shop. It is tagged with sport=soccer, so OM thinks it's a soccer field.
(https://www.openstreetmap.org/node/11029100225)

**Comment by dvdmrtnz** [comment]
> The problem is not the `leisure=sports_centre` tag, but that OM treats everything that has a `sport=*` tag as a pitch. https://www.openstreetmap.org/way/51161587 is tagged with `sport=multi`.
> 
> OM should require `leisure=pitch` for sport pitches.

I see. I think that area color should be removed from `sport=*` and a different shade of color should be added to `leisure=sports_centre`.

**Comment by Kazing** [comment]
Hello, please see similar issue #4086 with some examples
