### ISSUE TITLE
App crashes when entering text in search component

### ISSUE THREAD

**Issue by cafca** [organicmaps/organicmaps#917]
I am extremely happy to have succeeded in making a running MacOS build of Organic Maps. However, as soon as I enter any character in the search component, the app immediately crashes. 

On the terminal I see the following debug output

```
LOG TID(2) INFO       156.16 search/engine.cpp:288 DoSearch() Search started.
TID(2) ASSERT FAILED
indexer/categories_holder.cpp:281
CHECK(langCode != kUnsupportedLocaleCode) Invalid language code: bg at line: 4
[1]    52953 abort      /Applications/OMaps.app/Contents/MacOS/OMaps
```

My os is configured to use German language. My keyboard is using an English / international keyboard layout. The crash occurs for regular alphanumeric characters - I am not using umlauts or other special characters.

OS: MacOS 11.4
organicmaps compiled from [master@130c174db5](https://github.com/organicmaps/organicmaps/commit/130c174db5)

**Comment by vng** [comment]
Could you please try the fresh master? It's already fixed here: https://github.com/organicmaps/organicmaps/commit/d2b61fa335cdcd65f6fce610a8063f27af389f48
