### ISSUE TITLE
[Editor] Add data version to OSM notes

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#919]
https://github.com/organicmaps/organicmaps/blob/master/editor/osm_editor.cpp#L1253

https://github.com/organicmaps/organicmaps/pull/846/files/650a6eb5e688f3adee1a7643195111fc3e615736#r668127009

**Comment by vng** [comment]
Вот, пробрось мне версию в C++ и все сразу будет :)

**Comment by endim8** [comment]
Previously fixed by https://github.com/organicmaps/organicmaps/commit/7baf932c2bdf24ccadecbdc0fba1e10b4e42fd1d and can be closed now 👍
