### ISSUE TITLE
[ios] The recent track is not removed from the map after stopping track recording

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#9213]
The recent track is not removed from the map after the stopping of recording.

**Comment by biodranik** [comment]
It is an intentional implementation to test and get the feedback. Losing the (potentially many hours) recorded data doesn't look like a user-friendly decision.

Another use-case: to temporarily see the passed route on the screen, when saving a track is not needed.

**Comment by biodranik** [comment]
The current state looks inconsistent from the UX point of view. Either a track should be cleared, as this issue stated, or a proper "Pause Recording" functionality should be implemented (for Pause the track is not cleared neither on pausing it nor when recording starts again).
