### ISSUE TITLE
Add (built-in) text to speech

### ISSUE THREAD

**Issue by Donkey-Doug** [organicmaps/organicmaps#923]
The Mozilla text to speech engine is available here:

https://deepspeech.readthedocs.io/en/latest/SUPPORTED_PLATFORMS.html#android-aarch64

**Comment by TimMagee** [comment]
I think this is out of scope for the project. All major operating systems already provide TTS. There is no reason for Organic Maps to enter the TTS game when other apps already provide it.

**Comment by TimMagee** [comment]
Personally I use RH-Voice on F-Droid.

**Comment by gargamel17** [comment]
> @Donkey-Doug: It's usually provided by an app - try Google Speech Services or eSpeak.

Serious ? We use foss apps and you redirect to goolag  ?

**Comment by gargamel17** [comment]
> Personally I use RH-Voice on F-Droid.

Problem with RH is the very limited languages availability

**Comment by j-james** [comment]
Well, you have a lot of options on Android. eSpeak and RHVoice are the only FOSS options I know of, but there are plenty of non-FOSS but also non-Google options in the Play Store.

I personally use Google Speech Services and block its network access.

**Comment by TimMagee** [comment]
@gargamel17 

If the dedicated TTS apps cannot provide a reasonable TTS experience, why will Organic Maps be able to do better? Would this issue not be better filed with the dedicated TTS apps?

Organic Maps aims not to be bloated. Adding built-in TTS seems like bloat.

**Comment by biodranik** [comment]
Current TTS support can be improved even without integrating something. The code is a bit outdated, it can provide a better choice of different TTS engines and languages.

**Comment by gargamel17** [comment]
@TimMagee 
> If the dedicated TTS apps cannot provide a reasonable TTS experience, why will Organic Maps be able to do better? Would this issue not be better filed with the dedicated TTS apps?
> 
> Organic Maps aims not to be bloated. Adding built-in TTS seems like bloat.

I get your point, but if TTS is bloat, all map apps (including foss ones) are bloated.
From my point of view TTS is a functionality.

**Comment by biodranik** [comment]
It's really hard to find the best library suited for all worldwide languages. That's why users install and setup whatever engine they want, and OM just tries to use that engine.

There are bugs in the current implementation, let's focus on fixing them first. If some great solution becomes available, we'll consider it.
