### ISSUE TITLE
Unable to import GPX file

### ISSUE THREAD

**Issue by Stetru12** [organicmaps/organicmaps#9235]
I have recently installed Organic Maps on a Galaxy Tab Active (SM-T360) to use it as a navigation device on my motorcycle. However i cannot for the life of me import GPX tracks into the app, everytime i press on a GPX file the app opens and then the following error pops up:

Failed to open file file:///storage/emulated/0/Download/OFF16.gpx

java.io.FileNotFoundException: /storage/emulated/0/Download/OFF16.gpx: open failed: EACCES (Permission denied)

I have tried moving the gpx file into internal storage, but no luck

The tablet is running Android 5.1.1

**Comment by biodranik** [comment]
Please use another "File Manager" app to open files in Organic Maps. Looks like your program does not set permissions properly/does not use content providers to share files/open files in other apps. OM doesn't have READ_EXTERNAL_STORAGE permission and can't access that file.

Or try to open the file from gmail, or any messenger app.

**Comment by Stetru12** [comment]
Issue solved with "file manager" app from the play store

**Comment by biodranik** [comment]
@Stetru12 which app did you use before (which didn't work)?

**Comment by Stetru12** [comment]
The default Samsung file manager app.

I have also tried ES File Explorer but did not work.

The File Manager that worked is the one from ASD Dev
