### ISSUE TITLE
Improve search engine optimisation keyword  "École de conduite"

### ISSUE THREAD

**Issue by cayenne17** [organicmaps/organicmaps#9238]
⚠ Have you searched for similar, already existing issues?
- Yes

<br>

**Is your feature request related to a problem? Please describe.**
It's about the French language.
On OSMAnd, when I search for « Auto-école », it doesn't search in the `amenity=driving_school` category. It just finds the POIs that have the tag `name` containing « Auto-école ». On the other hand, when I type « école de conduite », OSMAnd does search: `amenity=driving_school`. 

On OrganicMaps, it's the other way round. When I search for « Auto-école", it searches in the category `amenity=driving_school`.
However, when I type in « école de conduite", OrganicMaps only finds POIs that have the tag `name` containing « école » and « conduite ». It doesn't search the ‘amenity=driving_school’ category.

<br>

**Describe the ideal solution**
- I'd like it to show me the `amenity=driving_school` POIs when I search for `école de conduite`. 

<br>

**Describe alternatives you have considered**

<br>

**Additional context**

<br>

**Questions**
- How do you contribute to something like this?
- Where are the keyword files in the OrganicMaps project to suggest improvements via Pull-Request?

**Comment by ProgramminCat** [comment]
This should be easily fixable via the categories.txt file, just add "École de conduite", alongside the already existing Auto-école.

Instead of this: `fr:Auto-école`
It would look more like this: `fr:Auto-école|École de conduite`

**Comment by cayenne17** [comment]
> Cela devrait être facilement réparable via le fichier catégories.txt, il suffit d'ajouter "École de conduite", à côté de l'Auto-école déjà existante.
> 
> Au lieu de ça : `fr:Auto-école` Cela ressemblerait plutôt à ceci : `fr:Auto-école|École de conduite`
@ProgramminCat : Thank you very much!
I've just applied for a PR (#9477)

I hope it will be validated quickly.
