### ISSUE TITLE
Share OSM Tiles (Files) with OSMand?

### ISSUE THREAD

**Issue by famo** [organicmaps/organicmaps#925]
I very much enjoy the ease of use with organic maps, but sometimes I need the power features of Osmand, so I have both installed on my device. However with this setup I need to download all regions twice, so I was wondering if it is possible to share the tile files with osmand?

**Comment by famo** [comment]
For reference, the folder setting s in OsmAnd:
![Screenshot_20210725-152407_OsmAnd~](https://user-images.githubusercontent.com/692646/126900684-3ea59ea6-2267-4600-a217-4772477b7b26.png)

**Comment by TimMagee** [comment]
This is not possible. As mentioned in #613, OsmAnd uses a completely different format for maps that is not compatible in any way with Organic Maps.
