### ISSUE TITLE
Grass renders over building=university

### ISSUE THREAD

**Issue by bbqman7089** [organicmaps/organicmaps#9256]
⚠ Have you searched for similar, already existing issues?

Yes

**Describe the issue**
Grass renders over buildings tagged with building=university and is rather jarring

**Steps to reproduce**
1. Go to 50°22′27.01″N 04°08′20.6″W
2. See error

**Expected behaviour**
Grass does not render over buildings 

**Screenshots**
![image](https://github.com/user-attachments/assets/e1bf0351-1a55-43e6-8d64-29a49c9402aa) 

Alternate angle: 
![image](https://github.com/user-attachments/assets/43db6eb0-8c32-41a2-8f68-f65e18c7c1ca)

**System information:**
 - Operating system and its version: iOS 16.7.7
 - Organic Maps version: 2024.09.03-26
 - Device Model: iPhone 8

**Additional context**
I'm on the most recent version of the Testflight beta

**Comment by Misalf-git** [comment]
Buildings are rendered slightly transparent in 3D, allowing to see through them. You can see paths, walls and bicycle parking as well.

**Comment by matkoniecz** [comment]
@bbqman7089 Are you asking here for 3D buildings blocking completely view behind them?

**Comment by patepelo** [comment]
Thank you for the feedback. Seems like a false positive in this case.

Community, shall we close and reopen if needed?
