### ISSUE TITLE
Location detection fails w/o GPS signal (indoors) / A-GPS

### ISSUE THREAD

**Issue by famo** [organicmaps/organicmaps#926]
I'm using organic maps on a wlan only tablet (among others) with [LineageOS for microG](https://lineage.microg.org/). As location backends I have configured Mozilla Location Service (with WiFi option) and Nominatim.

When I'm indoor and there is no GPS-signal, OM isn't able to detect my location, although it should be able to detect my location via wifi (within radius).

OsmAnd is able to instantly detect my location (within radius). And then after opening OsmAnd and switching to OM, OM is also able to detect my location.

**Comment by biodranik** [comment]
Thanks for reporting it, looks like our code has a bug. Do you use the FDroid version?

**Comment by famo** [comment]
> Thanks for reporting it, looks like our code has a bug. Do you use the FDroid version?

Your welcome! And yes I'm using the FDroid version.

**Comment by rtsisyk** [comment]
The latest version doesn't have any known GPS bugs. Please feel free to re-open if location works in other apps and don't work in Organic Maps.
