### ISSUE TITLE
Add OpenTopoMaps

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#927]
Organic Maps:

![1](https://user-images.githubusercontent.com/1799054/126907686-5c7ef420-3176-4d24-a66d-ec6541fd3862.jpg)

Mapy.cz:

![2](https://user-images.githubusercontent.com/1799054/126907687-e583ced4-cc08-4c07-bddd-460d5b92d3b2.jpg)

https://t.me/OrganicMapsRu/5757

**Comment by RedAuburn** [comment]
Partially resolved by outdoors style, remaining part is duplicate of https://github.com/organicmaps/organicmaps/issues/4163
