### ISSUE TITLE
Allow adding not only point objects to the map, but also roads

### ISSUE THREAD

**Issue by Korb** [organicmaps/organicmaps#9270]
Currently, Organic Maps user can add only a limited set of point objects. I propose to consider adding the ability to add linear objects of the [Key:highway](https://wiki.openstreetmap.org/wiki/Key:highway) category to the map _(Roads, Link roads, Special road types, Paths, When sidewalk / crosswalk is tagged as a separate way, When sidewalk (or pavement) is tagged on the main roadway, and When cycleway is drawn as its own way)_. Or at least some of them.

This will avoid using several mobile applications to work with one resource (OpenStreetMap), and will give users the opportunity to contribute to updating OSM to a greater extent.

**Describe alternatives you have considered**

[Osm Go !](https://github.com/OsmTravel/OsmGo)

**Comment by map-per** [comment]
I think this is rather out of scope for the OM Editor. 

The difficulties I see:
- Drawing new ways usually only makes sense with an aerial imagery background
- OM doesn't use the raw OSM data but compresses shapes
- OM doesn't directly use the OSM highway types, but does conversions based on `bicycle`, `surface` and `segregated`

**Comment by RedAuburn** [comment]
agreed, proper road editing is quite complex. it's better to leave a note so someone using a desktop editor can fix it
