### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by imeDevelopers** [organicmaps/organicmaps#9292]
Can you provide a way to integrate organic maps into a [Flutter](https://flutter.dev/) applications?!

example package: [flutter_mapbox_navigation](https://pub.dev/packages/flutter_mapbox_navigation)

it will be extremely perfect supporting new technologies like Flutter, Xamarin, etc.

This will give the developers the ability to provide the amazing organic maps inside their apps, specially for navigation!

thank you so much.

**Comment by imeDevelopers** [comment]
You can even convert the organic maps project to be completely Flutter project!

This means it will work on any platform, web, desktop, mobile, smart watches, even the apple vision pro, and more!

You need to take serious step that will significantly  enhance the organic maps project , thx!

**Comment by strump** [comment]
We have issue #5324 regarding SDK implementation.

**Comment by RedAuburn** [comment]
closing in favour of https://github.com/organicmaps/organicmaps/issues/5324
