### ISSUE TITLE
Import adresses from contacts

### ISSUE THREAD

**Issue by natrius** [organicmaps/organicmaps#930]
For quite some calendar apps it is possible to import birthdays into the app. Its easier to it that way because the date format should be quite clear, but it would be nice to add a function like this for adresses as well. 

A way i could think of is:
- Import adresses from contacts
- move map to contact-location or show "Not found"
- "Accept" or "Next adress"
- Get list of what adresses did not get imported

**Comment by biodranik** [comment]
What is the main use case? Create a bookmarks list with your contacts around to help you navigate to your contacts later?

**Comment by natrius** [comment]
Yepp.

**Comment by biodranik** [comment]
Related #1020, #1048 and #3474
