### ISSUE TITLE
iOS 18 Dark Mode Icon

### ISSUE THREAD

**Issue by brdbkr** [organicmaps/organicmaps#9312]
iOS 18 now features dark mode icons:

https://developer.apple.com/design/human-interface-guidelines/app-icons

![HOpsXJu](https://github.com/user-attachments/assets/21067c22-3dd7-4e9e-90ab-256e6190c335)

Google Maps, Mapy.cz, and Open GPX Tracker have already implemented this (or their icons allow it to be rendered automatically).

**Comment by patepelo** [comment]
Any ideas on how should DM OM look?

**Comment by brdbkr** [comment]
Like this?

![icon](https://github.com/user-attachments/assets/f21951da-5970-490a-bd10-7faa8ddefeb5)

**Comment by Misalf-git** [comment]
> Like this?
> 
> ![icon](https://github.com/user-attachments/assets/f21951da-5970-490a-bd10-7faa8ddefeb5)
> 
> I was able to open [this SVG](https://github.com/organicmaps/organicmaps/blob/master/android/.idea/icon.svg) in a text editor and just changed the hex values.

That choice of colors would also be quite fitting for the Android Web release (which currently has a poisonous green icon but I might be the only one who's bugged by it).

**Comment by not-available-username** [comment]
Hi there! Where is located on github the file of the current iOS icon?

**Comment by vng** [comment]
@kirylkaveryn I suspect that this one is easy to fix, if we take ready SVGs from here, right?

**Comment by not-available-username** [comment]
I’m updating the icons following Apple templates and guidelines.

**Comment by not-available-username** [comment]
**The tip at the base of the pin was slightly misaligned from the center, I fixed it.**

I made the Dark and Tinted icons following Apple guidelines. Here the gradient of the Light icon is a bit darker than the current one.
![Template - App Icon](https://github.com/user-attachments/assets/cceb2775-1e10-4b6a-98fd-4fbf642ffa35)

This is an alternative version of the Light icon that has a gradient that goes from dark to the OM green and not from the OM green to a lighter one, like in the current icon. I like this one more, because IMHO it is more consistent with the Dark and Play Store icons
![Template - App Icon 2](https://github.com/user-attachments/assets/044f0596-d5f8-4ba0-9af4-c36e931bcb99)

**Comment by kirylkaveryn** [comment]
@not-available-username please check out my latest PR https://github.com/organicmaps/organicmaps/pull/9366

**Comment by not-available-username** [comment]
> @not-available-username please check out my latest PR #9366
> 
> You can attach your pngs there and I'll try use tham so we can compare and choose better options

Hi! I think that your design works perfectly, I can send the light icon with a darker shade if you want, and make a comparison

**Comment by dvdmrtnz** [comment]
Tinted seems to be working fine but dark mode does not work.

Organic Maps version: ⁦2024.09.27-2⁩

![IMG_6163](https://github.com/user-attachments/assets/e80cfc71-ee1b-424b-b085-6fcb2bdfac46)
![IMG_6162](https://github.com/user-attachments/assets/a7272560-b76a-4e10-be8e-504954541263)
![IMG_6161](https://github.com/user-attachments/assets/b77bedbc-3743-44ce-bfd2-36f4bbff4cf6)

**Comment by kirylkaveryn** [comment]
@dvdmrtnz this is how the OM app icon reacts to the dark/tinted styles _Before_ the update. There is no difference before/after update.

It seems like the app from the TestFlight doesn't work with dark and tinted styles correctly. I dunno why but in the simulator all works fine. Maybe we should wait a little bit or only the release app version works well... there is lack of information. Or it's an Apple's bug.

**Comment by fizwidget** [comment]
Hi folks, the dark mode icon isn’t working in the 2024.10.04-5⁩ public release (despite the release notes mentioning it as a feature). 

Maybe this should be re-opened? (Or a new bug ticket raised?)

**Comment by not-available-username** [comment]
> Hi folks, the dark mode icon isn’t working in the 2024.10.04-5⁩ public release (despite the release notes mentioning it as a feature).
> 
> Maybe this should be re-opened? (Or a new bug ticket raised?)

Opened #9449
