### ISSUE TITLE
[Android][Beta] "Open in another App" activity is single-tasking

### ISSUE THREAD

**Issue by Misalf-git** [organicmaps/organicmaps#9327]
With
- #7105

finally available, opening a place in another app, in my case "[Öffi](https://f-droid.org/packages/de.schildbach.oeffi/)" (public transportation), prevents me from using OM and the other app simultaneously - no possibility to switch between the two apps (nor to open yet another app from OM).
I have to quit the app that was opened by OM until I can use OM again.

**Expected behaviour**
The external app should be invoked with it's own task to allow multi tasking.

**System information:**
 - Android 12
 - Organic Maps version: 2024.09.19-17-Google-beta
 - Device Model: Samsung A20e

**Additional context**
I intercepted the intent sent by OM in order to modify it before "Öffi" gets it.
It has:
`FLAG_ACTIVITY_PREVIOUS_IS_TOP` and
`FLAG_ACTIVITY_FORWARD_RESULT`

I added
`FLAG_ACTIVITY_NEW_TASK`
which results in "Öffi" and OM both being usable at the same time (i.e. I can switch from one app to the other).

I don't actually know what I'm doing though.

**Comment by RedAuburn** [comment]
adding the flag sounds right, you could make a PR for it :)
