### ISSUE TITLE
[ios] Add Dark and Tinted Icons for iOS18

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#9329]
![image](https://github.com/user-attachments/assets/1e97677f-37b9-4881-a4c0-a6a40928b794)

https://medium.com/@GuillemBruix/design-your-dark-and-tinted-versions-of-your-app-icon-for-ios-18-827444a31851

**Comment by RedAuburn** [comment]
Duplicate of https://github.com/organicmaps/organicmaps/issues/9312 :grin:
