### ISSUE TITLE
Draw Geodesics Correctly

### ISSUE THREAD

**Issue by BoostCookie** [organicmaps/organicmaps#9337]
**Describe the issue**
The shortest distance between two points is always drawn as a straight line.

**Steps to reproduce**
1. Select two points on the map with ROUTE FROM and ROUTE TO.
2. Select the the Vehicle Type "Count" all the way on the right to get the shortest distance on a sphere between the two points.
3. It shows the correct distance, calculated via the [Haversine formula](https://en.wikipedia.org/wiki/Haversine_formula).
4. It draws a straight line between the two points.

**Expected behaviour**
On the Mercator projection rhumb lines are straight, but geodesics (great-circle arcs) should curve.
[https://commons.wikimedia.org/wiki/File:Rhumb_line_vs_great-circle_arc.png](https://commons.wikimedia.org/wiki/File:Rhumb_line_vs_great-circle_arc.png)

**Screenshots**
![image](https://github.com/user-attachments/assets/9e68489b-ca10-4525-a341-29c90ce6d9a4)

**System information:**
 - Operating system and its version: Android 14, LineageOS 21
 - Organic Maps version: 2024.09.08-7FDroid
 - Device Model: Motorola Moto g32

**Comment by dvdmrtnz** [comment]
* See https://github.com/organicmaps/organicmaps/issues/5820

**Comment by BoostCookie** [comment]
Sorry, I was searching for the wrong keywords and did not find this already open issue. I will close this as duplicate.

**Comment by RedAuburn** [comment]
worth noting that the distance is calculated correcty (based on geodesics), it's _just_ the rendering that's wrong :)
