### ISSUE TITLE
Add existing Edit and Share options for bookmarks to tracks

### ISSUE THREAD

**Issue by Aurareus** [organicmaps/organicmaps#9339]
Currently when selecting (tapping and holding) on a track the only option presented is Delete:

![Screenshot_20240921-145918](https://github.com/user-attachments/assets/f56f9c18-04f3-4c07-91e5-b2551889f787)

In order for Organic Maps to replace the app I currently use for track recording it needs to have, as a minimum, the same management options available for tracks as are available for bookmarks.

When selecting a bookmark, there are Edit and Share options in addition to Delete:

![Screenshot_20240921-145857](https://github.com/user-attachments/assets/a5c88ca6-9583-4bc2-a80c-14aa5c573682)

What I need is those Share and Edit options to also be available for tracks.

Specifically, I need the edit options available on the bookmarks edit screen:

![Screenshot_20240921-150921](https://github.com/user-attachments/assets/a5b49997-597e-496f-8e42-4402b76fcd36)

The ability to change the name, change the color, change the list it is contained in, and set/change a description that are available in the bove edit screen for bookmarks, I would like those same options available in the same way for tracks as they are for bookmarks.

**Comment by hoizan** [comment]
To add on, it it not complete without an option to hide or unhide individual track/bookmark within a list.

**Comment by Rob-from-VI** [comment]
I emailed the following about this IMPORTANT subject:

3) As to the saving of the file, progress has been made in that if I rename the list it saved in, a new track will save in a new list, so by this workaround I can separate tracks, but I must do it before recording another track.   Many ways to improve this have been proposed on Github, ie enable the edit and share as you have for bookmarks.

**Comment by Aurareus** [comment]
The option to edit tracks as described here has been added, so I'm going to close this issue.
There still isn't an option to share tracks like you can with bookmarks, but I figure that should be opened as a new issue specifically for that if no existing issue for it currently exists.
