### ISSUE TITLE
[styles] New/Old Bookmark icons (discuss)

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#9356]
Users have doubts about size and outline after https://github.com/organicmaps/organicmaps/pull/9287

https://t.me/organicmaps/45621

CC @dvdmrtnz @pastk 

Device: Xiaomi 12 Pro (Android 13)

| Old | New |
------|------
| ![telegram-cloud-photo-size-2-5435951179982039173-y](https://github.com/user-attachments/assets/cf3ea37b-cf3d-4c8b-8aff-d306184c8f5e) | ![telegram-cloud-photo-size-2-5435951179982039172-y](https://github.com/user-attachments/assets/6800c3a0-4b82-4d49-9cf1-006db6cb7ac5) |
| ![telegram-cloud-photo-size-2-5435951179982039175-y](https://github.com/user-attachments/assets/9ccabdbd-871f-4b59-887e-ab1b55029711) | ![telegram-cloud-photo-size-2-5435951179982039174-y](https://github.com/user-attachments/assets/4e807e0b-f55b-48e7-af39-d78c8b281016) |
| ![telegram-cloud-photo-size-2-5435951179982039177-y](https://github.com/user-attachments/assets/6e592184-8dce-4938-b1ff-df9fed5bbd58) | ![telegram-cloud-photo-size-2-5435951179982039176-y](https://github.com/user-attachments/assets/e6f21387-1560-4807-bc17-d56aef1defe4) |
|   | ![](https://github.com/user-attachments/assets/81a6ef30-8bc4-4b01-88df-71e410f8de0d) |

**Comment by dvdmrtnz** [comment]
I suspect that the change in icon size may have something to do with the inconsistent scaling of icons 🤔 as mentioned in part 4 of https://github.com/organicmaps/organicmaps/issues/4017. I will take a look into it.

**Comment by pastk** [comment]
I think its better to keep icons' sizes as they were (i.e. smaller).

Bigger icons might look more cute in some cases but add more clutter when crowded.

Also there is a case when bigger icons are preferrable when e.g. driving or for people with vision issues, but IMO its better solved differently - we have a setting to enlarge map labels (fonts) already, makes sense to make icons bigger too (all icons, not just search results).

**Comment by dvdmrtnz** [comment]
Here is a comparison of old PNG vs new SVG bookmark icons, taken from the generated resources skins. I've also added added the regular pub icon for reference.

As you can see, icons have not changed in size for most resolutions except for the `6plus` skin. The old PNG icons used 2.4x scaling while the SVG icons use 3x. Notice how the regular POI icons also use 3x scaling for the `6plus` skin. That is the same discrepancy that @euf detected on part 4 of https://github.com/organicmaps/organicmaps/issues/4017. The old PNG icons were using 2.4x, the same scaling as `drape`, while the SVG icons use 3x.

![](https://github.com/user-attachments/assets/42caddb6-4356-4564-81f1-a67321af259d)

**Comment by dvdmrtnz** [comment]
> * What about default bookmark icon? Old - with a star; new - with a white whole.

I used for the bookmarks the same icons that we have for regular POI icons. So star is used for tourism=attraction. Then I had to add a new generic bookmark icon

**Comment by dvdmrtnz** [comment]
> * Did you check how svg goes to the skin png? Are there any factors also?
> 
> ```
> static double constexpr kXhdpiScale = 2.0;
> static double constexpr k6plusScale = 2.4;
> ```

When adding svgs to skins, `6plus` and `xxhdpi` use the same scaling (3x):

https://github.com/organicmaps/organicmaps/blob/a40ed508ec74882fa2611b376e099728b869d7f2/tools/unix/generate_symbols.sh#L89-L94

**Comment by brdbkr** [comment]
Can we switch away from the "pin-style" icons and just use circles?

**Comment by dvdmrtnz** [comment]
> Funny why 6plus generated skins don't have big arrow on first place like all other skins ..

_Comment by @vng in  https://github.com/organicmaps/organicmaps/pull/9287#pullrequestreview-2307075239_

This is why: In `6plus` skins we are using 2.4x scaling for PNGs while using 3x scaling for SVG icons.

All other resolutions use the same scaling for PNG/SVG.

**Comment by pastk** [comment]
> This is why: In `6plus` skins we are using 2.4x scaling for PNGs while using 3x scaling for SVG icons.

Is it a bug or a feature? :)

**Comment by dvdmrtnz** [comment]
> > This is why: In `6plus` skins we are using 2.4x scaling for PNGs while using 3x scaling for SVG icons.
> 
> Is it a bug or a feature? :)

🤪

It’s a bug. They should be the same scale, but I don’t know which one is the correct one. 

If by chance we actually like how they are scaled with this and we think this is a feature, then we should modify the icons so the rest of the phone resolutions get the same sizes

**Comment by pastk** [comment]
> This is why: In `6plus` skins we are using 2.4x scaling for PNGs while using 3x scaling for SVG icons.

2.4x makes sense, because 3x just duplicates existing `xhdpi`. 

E.g. Android has no  `6plus` even: `xhdpi` 2x is followed by `xxhdpi` 3x. 
https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp

**Comment by dvdmrtnz** [comment]
> > This is why: In `6plus` skins we are using 2.4x scaling for PNGs while using 3x scaling for SVG icons.
> 
> 2.4x makes sense, because 3x just duplicates existing `xxhdpi`.
> 
> E.g. Android has no `6plus` even: `xhdpi` 2x is followed by `xxhdpi` 3x. https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp
> 
> `6plus` seems optimized for iPhone 6 plus?

The screenshots from the original post are from an Android device. Why is it using the `6plus` skins?

**Comment by vng** [comment]
Core code doesn't care about iOS or Android, just a selector according to the passed visualScale. ```VisualParams::GetResourcePostfix```

Probably, may ask users for the logs to check their visual scale.

**Comment by pastk** [comment]
> > `6plus` seems optimized for iPhone 6 plus?
> 
> The screenshots from the original post are from an Android device. Why is it using the `6plus` skins?

Its fine other devices with similar densities use it. It just seems that it was originally introduced to provide an optimized version for iPhone 6 plus which is ~400 dpi or x2.4.

![image](https://github.com/user-attachments/assets/584630d6-d963-4cc4-89ba-2674b699be22)

I have no idea why its used for Xiaomi 12 Pro though. Shouldn't be the case as its much higher 520 dpi which is xxhdpi x3.
https://www.gsmarena.com/compare.php3?idPhone1=11287&idPhone2=6665

Actually we don't have confidence its using 6plus, we need to check logs to be sure..

**Comment by dvdmrtnz** [comment]
Old PNG vs new SVG of `bookmark-default-s` and `bookmark-default-xs`. Again discrepancy in sizes of `6plus` skins. Also borders are larger. This was an oversight on my part, I could make a PR changing the border width back to the original width if you think it's better.


![](https://github.com/user-attachments/assets/1b721fa0-7721-4ec8-a10d-b20809751372)


![](https://github.com/user-attachments/assets/82cf047d-bf8a-4e41-9a98-5dd38d413ef2)

**Comment by dvdmrtnz** [comment]
Also I can change the SVG scaling of `6plus` skins to 2.4x

**Comment by dvdmrtnz** [comment]
> Actually we don't have confidence its using 6plus, we need to check logs to be sure..

@pastk The only icons that have changed size are the `6plus` skins. It must be using it, otherwise it wouldn't look different size
