### ISSUE TITLE
GPX Tracks import with invalid timestamps for some coordinates.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#9365]
We made a hard logic when importing KML with checking points.size() == timestamps.size(), because geo-kml format is fancy when coordinates and times are stored separately.

GPX, in turn, has better format logic, and time entries are inside the ```trkptc```. So even if some time entries are bad, coordinate<->timestamp matching is still valid for other entries.

I've got a GPX file sample where:
```
vng@Viktars-MBP Downloads % cat 2024-05-04\ mid\ island\ nanoose.gpx | grep "<trkpt" | wc -l
    1409
vng@Viktars-MBP Downloads % cat 2024-05-04\ mid\ island\ nanoose.gpx | grep "<time>" | wc -l
    1405
```

So, should we update our Core Tracks code and GPX import to:
- support _INVALID_ timestamps for track points?
- ignore these tracks when importing (like now)?
- some fancy processing like deleting points with invalid timestamps?

**Comment by vng** [comment]
CC @cyber-toad WDYT?

**Comment by cyber-toad** [comment]
> CC @cyber-toad WDYT?

It is interesting why some timestamps are missing while there are coordinates, it looks liek a bug/issue with track recorder.

As a gpx user I don't care about timestamps most of the time, so if they are not available for 4 points of 1.4k it is not important and I personally would prefer to have track displayed. Removing of points with missing timestamps could lead to change of the track shape that could be important if road is not mapped or there is no road in this place. Using of INVALID marker is the most straightforward but could we have difficulties if we add features like display track profile with time/etc in future? Maybe reuse timestamp from last valid point as a tradeoff between usability, simplicity and precision?

**Comment by vng** [comment]
From user:
"A gpx track file which was recorded and then edited in OSMand would not import into Organic maps stating it was corrupt.   It displays fine in OSMand."
Probably, "edited in OSMand"

**Comment by Rob-from-VI** [comment]
My personal suggestion would be to allow the import, and either adjust the timestamp to be midway between the adjacent ones, or whatever it takes to make it come in.   A popup message indicating what was done would be wonderful, if possible.

**Comment by muralito** [comment]
Which are the use cases for importing the track in OM?
It's Just the position the data points that matters, or the is time is also needed for some time/speed analysis/display?
