### ISSUE TITLE
Fixed height of POI details after resume

### ISSUE THREAD

**Issue by kudlav** [organicmaps/organicmaps#937]
Hi,
after switching to another app and then back to the OrganicMaps, the POI detail always have height of POI before leaving the app.
See the screenshots.

1. Start app
2. Open POI without any detail (building, e.g.)
3. Switch to another app
4. Switch back to OrganicMaps
5. Open different POI with some details

Samsung Galaxy A40
Android 11
App 2021.07.08-6.g73931f7-Google

![Screenshot_20210727-000829_Organic Maps](https://user-images.githubusercontent.com/11516259/127105401-f05c0d68-62eb-4336-91ed-3d7b5663786e.png)
![Screenshot_20210727-001033_Organic Maps](https://user-images.githubusercontent.com/11516259/127105431-ea844b9a-c000-4704-a378-33eead5af513.png)

**Comment by biodranik** [comment]
Thanks for reporting! Already merged #875 should fix this issue. Please update this thread after the release.

**Comment by kudlav** [comment]
The problem persists in version 2021.09.14-4-Google

**Comment by biodranik** [comment]
That's bad news. @rtsisyk Please check it out.
