### ISSUE TITLE
[ios] Save button in List Settings does nothing

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#939]
Steps to reproduce:

1. Click Bookmarks Icon -> Select some list -> Click More -> List Settings 
2. Edit description
3. Click Save
4. Save button does nothing

https://user-images.githubusercontent.com/1799054/127122022-38a404e2-858b-43b5-becd-684aab5fb55f.mp4

**Comment by rtsisyk** [comment]
This problem still exists.

**Comment by BelKed** [comment]
I believe this issue is fixed :)
See my recording in https://github.com/organicmaps/organicmaps/issues/4799

**Comment by andre1110** [comment]
@biodranik I found a case when your fix makes another view controller to pop - should I create a new bug or will you re-open this one? I already prepared a fix

https://github.com/organicmaps/organicmaps/assets/135858315/5582af48-bbda-4983-bb80-a1107b10b7ce

**Comment by biodranik** [comment]
Any approach is good to me.

**Comment by andre1110** [comment]
While testing the fix, I reproduced a crash -- please see attached. I fixed it in the same PR

https://github.com/organicmaps/organicmaps/assets/135858315/a054fcd8-dc83-40c4-9939-aa3a124c59cc
