### ISSUE TITLE
Importing places fails to find file manager

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#9390]
### Discussed in https://github.com/orgs/organicmaps/discussions/9346

<div type='discussions-op-text'>

<sup>Originally posted by **chilburn06** September 21, 2024</sup>
I am trying to import my places from google maps, and it keeps telling me I need a file manager but I have 2. Any suggestions?
<img width="300px" src="https://github.com/user-attachments/assets/e1960c0f-83fa-4f33-b3f4-82422164979e"/>

<sup>Originally posted by **CMSplumbear** September 29, 2024</sup>
Same issue here.
Version 2024.08.16-5-FDroid is working perfectly.
Using Obtainium I installed the Github version 2024.09.08-7-Web in parallel, installed a few maps, then attempted to import the bookmarks exported from the F-Droid version and got the message above.

The Samsung file manager application doesn't propose Organic Maps (nor any other map app) to "share" or "open with" the exported .kmz file.
Using Ghost Commander it was possible to "open with" as "???" (unknown filetype?) and select Organic Maps to import the file correctly.
Still, the import dialog doesn't work
Device is Samsung A50 Android 11

</div>

**Comment by RedAuburn** [comment]
@chillburn06, are you also using a samsung device?

**Comment by RedAuburn** [comment]
(relevant lines in code)

https://github.com/organicmaps/organicmaps/blob/4c4a8a9784b26d613ad156915da616c3666b0470/android/app/src/main/java/app/organicmaps/bookmarks/BookmarkCategoriesFragment.java#L260C1-L265C4

**Comment by deshudiosh** [comment]
I have this error on samsung s20 fe, android 13

**Comment by chilburn06** [comment]
Google Pixel 6 pro

**Comment by CMSplumbear** [comment]
I tried the latest version on two old (Samsung) devices running Android 7 (A3 2016) and Android 8 (S7), it works perfectly.

The problem might be perhaps related to this 
https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9

**Comment by abstractionmage** [comment]
I have the same problem, but only with the Organic Maps version from F-Droid or the web-release-apk from [your latest release here on GitHub](https://github.com/organicmaps/organicmaps/releases/tag/2024.09.08-7-android). If I install organic maps from the google play store it is able to open Android's built-in file manager just fine.

I'm using a Fairphone 5 with stock android btw. 

[I originally posed about this on reddit](https://www.reddit.com/r/organicmaps/comments/1fsr7s8/unable_to_display_folder_selection_dialog_because/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) before a community member redirected me here.

**Comment by RealVegOs** [comment]
Same here with Lenovo Tab m8 4th Gen. I installed with Obtainium too. But as I remember former f-droid versions, the whole bookmark thing is absolutely unusable for me. I need to import single files, not a whole directory and these files should not be lists! So I still prefer AAT with the overlay concept. I do not use any kind of routing. I draw my routes on the pc and import them.

**Comment by RedAuburn** [comment]
this is very odd, because the only code differences between FDroid/web & GPlay are location services related. 

when people mention 'android's built in file manager', is it google branded, or the AOSP one?

**Comment by sunng87** [comment]
I found this has been fixed in the latest f-droid build. It now works correctly for me on motorola xt2241

**Comment by RealVegOs** [comment]
It works now with the latest GitHub version via Obtainium App. The bookmarks feature still needs some work, as I wrote above. I hope, it will improve to be useful for me too. Thanks so far!

**Comment by abstractionmage** [comment]
I can also confirm the problem being fixed with the latest F-Droid build on my Fairphone 5. I guess this issue can be closed now.

**Comment by deshudiosh** [comment]
I updated app today, and it started working. Thank you very, very much.
Samsung S20 FE
