### ISSUE TITLE
Prepare and publish application description for stores on different languages.

### ISSUE THREAD

**Issue by Endem10n** [organicmaps/organicmaps#940]
For current moment we only have Russian and English translations for application description in Google Play and other stores. We should add translations for other languages too.

**Comment by biodranik** [comment]
It would be great to store descriptions somewhere in the repo, so others can edit/fix them. Initial versions may be created with DeepL or Google Translate.

**Comment by rtsisyk** [comment]
After #206 and #659 

See https://hosted.weblate.org/projects/noice/play-store-and-f-droid-listing-metadata/ and https://github.com/ashutoshgngwr/noice/tree/master/fastlane/metadata/android for example.

**Comment by rtsisyk** [comment]
This is done.
