### ISSUE TITLE
Hurricane Helene Disaster Relief Features

### ISSUE THREAD

**Issue by ijustlovemath** [organicmaps/organicmaps#9401]
⚠ Have you searched for similar, already existing issues?

I have not, I'm guessing all of these features have been requested before, but am trying to coordinate other things and haven't had time to do a detailed search.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

As you probably have heard, almost all of WNC is without cell connectivity, and the connectivity that exists is sparse and unreliable (chat only, no voice calls or general web capabilities)

We're building open sourced community maps of resources, but they're not very useful if they're not available offline, and less useful if you cant transfer them peer to peer.

I'd like to request two features, and would be willing to sponsor development for 10-20 hours (and can chip in myself if anyone can help me get oriented)

1. Peer to peer downloaded map transfer, over Bluetooth (region and pins)
2. Alternative download server capabilities (so we could use different CDNs if we're having trouble accessing the map downloads directly)

**Describe the ideal solution**
A clear and concise description of what you want to see in Organic Maps.

1. A new settings option for map delivery (could be named something else). Would allow you to specify a URL of a server which supports the same map download protocol your servers use to distribute map files.
2. Peer to peer sharing of downloaded maps (Share -> Maps -> select the downloaded maps to export)
3. Peer to peer sharing of pins (called Lists in the app). (Share -> Lists -> select the lists to share)

**Describe alternatives you have considered**
- How do you solve this issue now with Organic Maps or other apps?

We are manually copying pins into peoples phones, taking screenshots, etc. This is really inefficient, not very user friendly, primitive, not scalable 

- Attach any examples, screenshots, or screen recordings from other apps that help us to better understand the idea.

**Additional context**

**Comment by ijustlovemath** [comment]
A side feature would be the ability to store sideloadable versions of the app itself for transfer over airdrop or bluetooth.  Not sure if iOS's new store features allow direct sideloading though

**Comment by map-per** [comment]
> 3. Peer to peer sharing of pins (called Lists in the app). (Share -> Lists -> select the lists to share)

Sharing a bookmark list or all bookmarks at once is already supported ([faq](https://organicmaps.app/faq/bookmarks/how-to-export/))

**Comment by ijustlovemath** [comment]
Hi, this does not export to Bluetooth as far as I'm aware, just to a file. iPhones don't have great native support for sharing files, so having an in-app AirDrop support would be amazing

**Comment by map-per** [comment]
On android you can download the APK of the [web release](https://github.com/organicmaps/organicmaps/releases/tag/2024.09.08-7-android) to share it without internet connection. 

The map data files are stored in Android/data/app.organicmaps/files/\<\<date of map creation>>. Replacing map data works fine in the Linux version, but I've never tried it on Android.

**Comment by ijustlovemath** [comment]
I think the greater need is for these features on iPhone, since that's the majority of users who would benefit in this disaster

**Comment by patepelo** [comment]
Related to #1801

**Comment by biodranik** [comment]
1. On iOS, maps can be uploaded into OM using file sharing: https://support.apple.com/en-us/120403
2. On Android, an APK from GitHub can be shared, and then maps can be uploaded via adb.

Important note: maps should not be newer than the app data version displayed in the About dialog.

**Comment by biodranik** [comment]
@ijustlovemath there is no value in sharing maps p2p without an opportunity to install the app first. And if the app is already installed, maps most likely have already been downloaded.

Sharing the app p2p is possible only on Androids, and only with some tech knowledge (send files over Bluetooth, enable installation from unknown sources). And it requires a pre-downloaded apk on a device, correct?
