### ISSUE TITLE
Bad walking routing

### ISSUE THREAD

**Issue by cypok** [organicmaps/organicmaps#9420]
Walking route from 48.197874, 11.524206 to 48.201816, 11.525847 contains the large detour:
<img src="https://github.com/user-attachments/assets/9f96d84d-df8f-4e8c-a3fd-85bf79b3e26a" width="40%"/> 

Valhalla, GraphHopper and OSRM suggest direct route.

App version 2024.09.08-2

**Comment by map-per** [comment]
This was caused by `use_sidepath` as well (see:  #9419). I fixed the OpenStreetMap data.
