### ISSUE TITLE
[Android] Maps download UI is covered by bottom navigation bar

### ISSUE THREAD

**Issue by strump** [organicmaps/organicmaps#9423]
**Description**
Some UI elements on map download UI are covered with Android navigation bar. Probably caused by #9251.

**Steps to reproduce**
1. Go to Menu / Download Maps / Ukraine
2. Try to tap "Download All" button

**Expected behaviour**
"Download All" button is accessible.

**Screenshots**
<img src="https://github.com/user-attachments/assets/42357182-c45d-4fdc-8ce2-82ec4565556f" width="300px"/> <img src="https://github.com/user-attachments/assets/a3857383-4d52-4857-ba98-3ad88261d94d" width="300px"/>

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: master at commit https://github.com/organicmaps/organicmaps/commit/aa436f3cf7351ccca84c733368d140953fa027ef

**Comment by biodranik** [comment]
Another related issue. @strekha can you please check and fix it?

1 | 2
---|---
![выява](https://github.com/user-attachments/assets/831c52f8-342d-4a45-8ace-8ab20d3cae8e)|![выява](https://github.com/user-attachments/assets/8b10071b-b7c3-478c-a163-ac9509e7d994)

**Comment by strump** [comment]
"Download All" button looks good. But floating button is still covered:

<img src="https://github.com/user-attachments/assets/ee4426d5-0335-4eda-a949-f985053a5938" width="300px"/>

**Comment by user334** [comment]
Can confirm - the issue is resolved now. 

![Screenshot_20241004-141309_Beta_Organic_Maps.png](https://github.com/user-attachments/assets/5fe4a2c9-4d9a-43f1-9b05-961037943754)

**Comment by vng** [comment]
@strekha I still have "Plus" button covered in Downloader.
![telegram-cloud-photo-size-2-5190513190792978742-y](https://github.com/user-attachments/assets/d11f6a2b-90bd-44a7-a18b-57dcc275e866)

**Comment by biodranik** [comment]
Is there an alternative, more robust way to fix all insets and avoid bugs like this one popping up again?

**Comment by strekha** [comment]
@biodranik, we always can apply paddings to screen's root view, but it won't look visually appealing. Ideally, insets handling should be done for each screen individually.  
The problem with this case is amount of states inside a single screen. and in the future, if another button will be added, insets handling should be updated as well
