### ISSUE TITLE
Dark icon on iOS not available  

### ISSUE THREAD

**Issue by not-available-username** [organicmaps/organicmaps#9449]
**Describe the issue**
OM does not switch to dark icon when the option is enabled. It has the same icon, slightly darkened by default. 

**Steps to reproduce**
Enable dark icon on the home screen. 

**Expected behaviour**
The icon shoud be dark. See #9366 

**Screenshots**
![IMG_3946](https://github.com/user-attachments/assets/549a605e-b1bc-401b-8527-49782b7e79d4)
![IMG_3945](https://github.com/user-attachments/assets/8a231c4b-ad5f-412d-b7ec-4ab94bdf25b8)

**System information:**
 - Operating system and its version: iOS 18.0.1
 - Organic Maps version: 2024.10.04-5⁩
 - Device: iPhone 12

**Comment by biodranik** [comment]
@kirylkaveryn PTAL

**Comment by kirylkaveryn** [comment]
This bug is weird because the dark and tinted icons work fine on the ios18 simulator. I still haven't found the reason...

**Comment by not-available-username** [comment]
> This bug is weird because the dark and tinted icons work fine on the ios18 simulator. I still haven't found the reason why it isn't working on the device...

Snapseed and Packages have the dark icon only when the icons are set to large. My home banking app has the dark icon only in the settings list, but not on the home screen, regardless the settings.

**Comment by brdbkr** [comment]
Doesn't work for me either.

**Comment by AndrewShkrob** [comment]
What is the version of the app?
It works for me

iOS 18.0.1
OM version: 2024.10.06-1

<img width="300" src="https://github.com/user-attachments/assets/3ca9ae10-46b7-4a77-97aa-78807811773d"/>

**Comment by not-available-username** [comment]
> What is the version of the app? It works for me
> 
> iOS 18.0.1 OM version: 2024.10.06-1
> 
> <img alt="" width="300" src="https://private-user-images.githubusercontent.com/10351358/373938307-3ca9ae10-46b7-4a77-97aa-78807811773d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTMzNDYsIm5iZiI6MTcyODIxMzA0NiwicGF0aCI6Ii8xMDM1MTM1OC8zNzM5MzgzMDctM2NhOWFlMTAtNDZiNy00YTc3LTk3YWEtNzg4MDc4MTE3NzNkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDExMTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMTQ5ZjFkZmNhNzg3YjhmMTkwY2I3MDIyYWM1OWQ3MDg1MmFmYmNmNGZhMDU0NjkxYWI5NDEzN2I1Y2Y4Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.31Ah8BwRUWuu1ZwsZb5SGdg2GLIudO4gtZ3iEOB48Jw">

As I wrote in the first comment, 2024.10.04-5⁩, it is the latest available on the Store for me

**Comment by dvdmrtnz** [comment]
This has been fixed in https://github.com/organicmaps/organicmaps/pull/9450

**Comment by kirylkaveryn** [comment]
@dvdmrtnz thanks!
