### ISSUE TITLE
TrackRecording drawing performance

### ISSUE THREAD

**Issue by kirylkaveryn** [organicmaps/organicmaps#9488]
During the track recording, the path may contain many points to draw.
In this situation, the path rendering logic consumes much drawing time and CPU usage, decreases fps a lot and make the app unresponsible when the track's path is on the screen:

https://github.com/user-attachments/assets/8eb4d32e-d915-4aae-b06d-2952ebc85b91

Related issues:
https://github.com/organicmaps/organicmaps/issues/8927#issuecomment-2396568925

## Profiling
on 60sec timeline

1. more than 1000 points (the GPS renderer draws less than 1000 because it depends on the current zoom level)
note: usually the tracks have less density on the screen. here I generate the high density track only for the testing purposes
<img width="410" alt="image" src="https://github.com/user-attachments/assets/48f6c3b8-4ad7-401c-874d-ab37a9b0eb48">
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/f9358a0b-04b2-4e97-88ba-677edc69c676">
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/53d00ae9-a0ec-4288-ba92-5f7d91ab59a3">

2. 0...30 points (start of the recording)
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/a67e75aa-9511-4cab-9bc8-d4a81af53fb0">

## Results
Here we can see that 
1. the long track's rendering takes ~ x3,35 more time (25.27/7.54) to render than small track
2. the longer track the more time is taken by the `RenderTrack` method
3. the `Spline::Iterator::GetLength()` takes 17,99 (11,17+6,82) seconds from the **total** app's 25,27 -> its about 71% (the equality operator takes a lot of time)

The length calculation happens on every iteration in the `CalculatePointColor` (there can be a lot of iterations):
https://github.com/organicmaps/organicmaps/blob/71f7a88a2d5e3ef729d58302a7ad203b5d6a7cd2/drape_frontend/gps_track_renderer.cpp#L230-L242

The track redrawing happens on every `RenderScene`.

Small fixes to the `RenderTrack` can save ~35% on the method's duration but it's still bad performance.
```cpp
m2::Spline::iterator it;
      if (m_pointsSpline.IsEmpty()) // <-- 1
        return;
      it.Attach(m_pointsSpline);
      auto const fullLength = it.GetFullLength(); <-- 2
      while (!it.BeginAgain())
      {
        m2::PointD const pt = it.m_pos;
        m2::RectD pointRect(pt.x - radiusMercator, pt.y - radiusMercator,
                            pt.x + radiusMercator, pt.y + radiusMercator);
        if (screen.ClipRect().IsIntersect(pointRect))
        {
          static int i = 0;
          i++;
          dp::Color const color = CalculatePointColor(it.GetIndex(), pt,
                                                      it.GetLength(), fullLength); <-- 2
```
<img width="1731" alt="image" src="https://github.com/user-attachments/assets/963a1a50-c6b7-4516-bb95-1d9b0b3ac08c">

___ 
The track rendering logic should be refactored and optimized to increase drawing speed.
We can optimize the current logic or implement drawing the path as a line.

@biodranik @vng WDYT?

**Comment by biodranik** [comment]
@kirylkaveryn thanks! Is it possible to share _release_ build profiling log file for xcode with applied GetLength/GetFullLength optimizations?

**Comment by kirylkaveryn** [comment]
> @kirylkaveryn thanks! Is it possible to share _release_ build profiling log file for xcode with applied GetLength/GetFullLength optimizations?

@biodranik 
Here is the trace log recorded on the device (iPhone 15pro, ios 18.0, Release build) for the generated track:
[track_recording_rendering.trace.zip](https://github.com/user-attachments/files/17330000/track_recording_rendering.trace.zip)

I dont believe that the real difference is so huge as in profiler ant there can be other bottlenecks.

<img width="1730" alt="image" src="https://github.com/user-attachments/assets/4ebfe0c0-fa90-4898-8388-ca030d6ca908">
<img width="1729" alt="image" src="https://github.com/user-attachments/assets/8b82d00d-2c48-4fc5-9ac8-4d3906a1265a">

**Comment by Rob-from-VI** [comment]
I know little about coding, but something about efficiency.   Might it be possible to limit the redraw to the most recent 10 points, or to only the portion currently onscreen, or some other limtation to avoid a complate recalc?   

In any case, only perform a complete redraw if the map zoom changes or if the user pans the map?

**Comment by kirylkaveryn** [comment]
> > or implement drawing the path as a line
> 
> 
> 
> IMHO the current discrepancy between looks of saved tracks (rendered as lines) and a track being recorded (dots with varying transparency) is confusing.
> 
> 
> 
> A track being recorded should look similar to other tracks yet it should stand out a bit just to show its not complete yet.
> 
> So IMHO it should be a line, but e.g.
> 
> - with an extra casing
> 
> - or make it thinner and more opaque, while saved tracks somewhat transparent and thicker
> 
> - or vice versa
> 
> - etc.
> 
> 

@pastk Ilike how the AllTrails draws the track:
![image](https://github.com/user-attachments/assets/4710e68d-ad9b-42b1-8dd8-303c539aecc0)
![image](https://github.com/user-attachments/assets/1d62cf0e-bc5b-41c2-ad6e-44e712c2df42)

**Comment by pastk** [comment]
> @pastk Ilike how the AllTrails draws the track:

that is a track in a "recording" state?

is it different from a saved/recorded track?

**Comment by kirylkaveryn** [comment]
> > @pastk Ilike how the AllTrails draws the track:
> 
> 
> 
> that is a track in a "recording" state?
> 
> 
> 
> is it different from a saved/recorded track?

Its default mapbox's drawing style.
The only difference is the color. Here is the recorded:
![image](https://github.com/user-attachments/assets/3ec57642-b306-460d-859c-c5886b06f155)

**Comment by Aurareus** [comment]
Using a different color for tracks in the recording state wouldn't work for Organic Maps because OM gives the user the option to change the color of tracks, which could lead to confusion in differentiating the track being currently recorded from tracks that were previously recorded.

If you wanted to instead render the currently recording track as a line I think the best way to differentiate it from other tracks would be to set recording tracks to a lower opacity.

**Comment by pastk** [comment]
> If you wanted to instead render the currently recording track as a line I think the best way to differentiate it from other tracks would be to set recording tracks to a lower opacity.

Yeap. Or maybe a higher opacity? :)
A lower opacity is like "less important", while high opacity is like something to focus on.

Actually I think it'd be useful to have some opacity for all tracks, so its possible to e.g. see if there is a path or nothing under it...
