### ISSUE TITLE
Don't show caves on the default zoom levels

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#949]
![2021-07-29 10 38 42](https://user-images.githubusercontent.com/1799054/127451481-7e9fdd32-b8f8-4ec3-b75b-72eda3ed0f70.jpg)

**Comment by j5k** [comment]
See also #755

**Comment by biodranik** [comment]
Please check my comment for #755 before working on this issue.

**Comment by pastk** [comment]
Another good example with too many caves displayed south of Vienna:
![Screenshot_1644057457](https://user-images.githubusercontent.com/18434508/152640142-954f927c-fe97-4aff-8ed3-2ccc4af6cc85.png)

**Comment by pastk** [comment]
A proper long-term fix (dynamic adjustment based on feature density in a viewport) is likely to take a long time.

In the meantime we can improve the situation easily by 
- making the "small" cave icon (`data/styles/clear/style-clear/symbols/cave-s.svg`) a bit smaller - its still looks big compared to other "small" icons
- making cave icons less prominent / distracting - atm they're very "heavy" looking with a lot of black color - try to make them "lighter" - compare to the forest icons in the screenshot above

**Comment by biodranik** [comment]
Agree. They can also be visible from the next zoom level.

**Comment by biodranik** [comment]
The same for waterfalls please.

**Comment by j5k** [comment]
And if possible and make sense, for small leisure=nature_reserve too. See #755

**Comment by pastk** [comment]
> And if possible and make sense, for small leisure=nature_reserve too. See #755

This one is not an easy fix unfortunately, because at the moment we have no mechanism to distinguish between "small" and "big" reserves.

**Comment by j5k** [comment]
> This one is not an easy fix unfortunately, because at the moment we have no mechanism to distinguish between "small" and "big" reserves.

Correct. Since it already works similarly for buildings, maybe we can have a look there.

**Comment by MisterY** [comment]
+1
The caves clearly dominate the map

![Screenshot_20220926-195606_Organic Maps](https://user-images.githubusercontent.com/462445/192349798-f15f77f9-b5ee-4501-af2e-382cb6b72a15.png)

**Comment by charlie2clarke** [comment]
I notice that changes since been made to cave and waterfall icons to make them less prominent (see below). Do you think that there should be any more short-term fixes?

I personally like the current POI granularity and imagine that typical OM users would like to see caves and waterfalls on this zoom level.

<img src="https://user-images.githubusercontent.com/58811769/227718160-6ef938a4-aa4f-47df-b96e-8582dd74a903.jpg" width="50%" height="50%">

**Comment by biodranik** [comment]
We can reduce the size of the cave icon to improve the image )

**Comment by charlie2clarke** [comment]
Here's a sample of what smaller cave icons look like:
<img src="https://user-images.githubusercontent.com/58811769/227731329-a054bd96-9260-48c8-b3e8-e0a31cf264c0.png">
<img width="828" src="https://user-images.githubusercontent.com/58811769/227731323-53f1e010-6cde-4aa2-8343-c05bc7652d47.png">

I don't know how much smaller you would want to make them, but an alternative could be trying a cave icon that only uses the outline, e.g.:
![image](https://user-images.githubusercontent.com/58811769/227731411-ab40b52d-ddc9-432d-9ece-76dde7273214.png)

**Comment by biodranik** [comment]
The icon is hardly recognizable as a cave... Can we find a better one?

**Comment by charlie2clarke** [comment]
Agreed, I think an icon which uses darker shading for the cave entrance could work better. I couldn't find a perfect one, but some options:
<img src="https://user-images.githubusercontent.com/58811769/227733764-3ba4d5d8-f17b-43e1-8ddc-1aaeb898c523.png" width="20%" height="20%">
<img src="https://user-images.githubusercontent.com/58811769/227733802-fde1f667-2511-4063-94ed-e898ebe2bcf4.png" width="20%" height="20%">
<img src="https://user-images.githubusercontent.com/58811769/227733964-f0630368-f912-4eba-a76b-3295f3d42917.png" height="20%" width="20%">
<img src="https://user-images.githubusercontent.com/58811769/227733992-5515df69-5c7e-4a2c-8490-db76369f7d27.png" height="20%" width="20%">

**Comment by biodranik** [comment]
It should look great on older mdpi devices too, without much detail.

The last two, with the idea of a dark hole, look better. How are they looking on the map?

Can our existing icon be improved (e.g. inversed), and have its hole increased a bit?

**Comment by charlie2clarke** [comment]
@biodranik What are your thoughts on this - using the existing icon style but using a slightly lighter shading for the grey to reduce the contrast and using a darker colour for the cave entrance to make it more recognisable as a cave?

<img src="https://user-images.githubusercontent.com/58811769/227770582-34efaf5c-88bb-44f6-97c1-75d04107962b.png" width="30%" height="30%">

**Comment by pastk** [comment]
I think the biggest issue with the current icon is that it looks like a peak, a rock... One might realize there is actually a cave entrance after paying more attention to the details only.
Ideally it should look like a cave from the very beginning :) Also caves are not necessarily in a mountain, e.g. the entrance could be located just on a slope, without any prominent rocks/hills around.
Maybe use an icon similar to tunnel road signs? But with a lower profile and less symmetric shape..

**Comment by pastk** [comment]
Or something like
![cave](https://user-images.githubusercontent.com/18434508/227777342-29eee789-b7cb-47ee-ab81-63d4ce9756bd.png)

https://www.flaticon.com/free-icon/cave_8830950?term=cave&page=1&position=62&origin=tag&related_id=8830950

**Comment by biodranik** [comment]
Agree with @pastk. And likely there should be no more than one color (plus transparency), colorful icons don't look good on the map (you can test it yourself).

**Comment by charlie2clarke** [comment]
I did see that icon. However, flaticon requires a subscription to download the SVG - does anyone have this? 

I tested out the icon I included [above](https://github.com/organicmaps/organicmaps/issues/949#issuecomment-1484058253), and it doesn't look good you're right. But what would be the proposal if we were to use the icon @pastk attached? Wouldn't that require multiple colours for the cave entrance?

**Comment by biodranik** [comment]
Is it hard to draw a similar, but maybe even better icon? OSM uses this:

<img width="112" alt="image" src="https://user-images.githubusercontent.com/170263/227796494-ca7a6535-d869-487e-9a65-bc8f8d43d0d9.png">

**Comment by charlie2clarke** [comment]
I tried the OSM icon out and I think it looks good at a glance - thoughts?
![image](https://user-images.githubusercontent.com/58811769/229935979-2f268a33-f8df-46d0-b069-2ba6d7a2e05c.png)

Then, I was trying to find something similar to the flaticon one suggested, but couldn't find anything suitable that was free and without the creator's signature. So, I tried making my own one which I think is ok, but doesn't look as good at a glance:
![image](https://user-images.githubusercontent.com/58811769/229936317-bfe56bb5-5346-4fbb-b3f9-9c6b13b66426.png)

Here is the icon standalone:
<img width="30%" height="30%" alt="image" src="https://user-images.githubusercontent.com/58811769/229936476-a287526c-a127-47ff-b47a-d2dbed90f840.png">

**Comment by biodranik** [comment]
OSM icon is ok, maybe the color should be a bit more grayish, to avoid attracting too much attention.

**Comment by biodranik** [comment]
Your icon is also ok with a bit of tuning ) A darker (maybe thicker) outline?

**Comment by charlie2clarke** [comment]
OSM in a grey shade:
![image](https://user-images.githubusercontent.com/58811769/230052873-5ff4cefd-f645-4b2f-8c4e-402f798a2873.png)

My icon with wider strokes and a darker shade:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/58811769/230060630-5a55c344-a0dc-415f-b3ae-088462690716.png">

**Comment by pastk** [comment]
I'd say OSM icon is more recognizable / easily readable.

Your custom icon looks good when its big, but not very readable when its small..

**Comment by biodranik** [comment]
A bit of asymmetry helps to get it easier. Maybe reduce the "hole" height in your icon? It would be easier to decide after checking how it looks on a device )

**Comment by alensiljak** [comment]
> What are others' thoughts?

A cave is my first association when looking at the OSM icon. I prefer your outer shape, though. It looks like a rock. So, there's only something with the dark shape on your icon. It might be too high for the "right" feel.

**Comment by pastk** [comment]
> A bit of asymmetry helps to get it easier. Maybe reduce the "hole" height in your icon? 

I second that.
Also maybe position the hole more in the center horizontally, now it touches the left "rock" side almost and it doesn't look good. The asymmetric look should come mostly from the irregular shape of "the rock" outline IMHO.

**Comment by dvdmrtnz** [comment]
> OSM in a grey shade: ![image](https://user-images.githubusercontent.com/58811769/230052873-5ff4cefd-f645-4b2f-8c4e-402f798a2873.png)

I think this one is good
