### ISSUE TITLE
Explicitly handle deletion of POI details

### ISSUE THREAD

**Issue by RicoElectrico** [organicmaps/organicmaps#9517]
Oftentimes POIs change their owner without changing their type. This is supported by OM, however it's not possible to just delete details such as phone number, website or opening hours which are very likely to change with new owner. If you do so, the merge algorithm will use pre-existing ones from previous OSM object version.

**Comment by map-per** [comment]
This is a duplicate of #6292, it will be fixed with #9242

**Comment by RicoElectrico** [comment]
> This is a duplicate of #6292, it will be fixed with #9242

Right! So closing this one as a dupe.
