### ISSUE TITLE
Is there a way to filter the markers in the map ? 

### ISSUE THREAD

**Issue by muhsin-art** [organicmaps/organicmaps#9531]
Hello,

I would like to inquire if there is a way to filter markers on the map in an Android application. Specifically, I am looking to implement functionality where users can filter locations by category through buttons. For example, if a user wants to view only restaurant markers, other categories should be hidden, and only restaurants should be displayed.

In addition, I would like to inquire about how to add custom markers, such as radar points, to the map. Could you provide guidance on how to achieve this?

Is this possible for Android users? I have been exploring the code but have been unable to find a clear solution, and I am currently feeling lost.

Thank you in advance for your assistance.

**Comment by muhsin-art** [comment]
I found my answer :) 

```
SearchEngine.INSTANCE.searchInteractive(
                    query, iscategory, Language.getKeyboardLocale(requireContext()),
                    System.nanoTime(), false /* isMapAndTable */);
```

**Comment by biodranik** [comment]
Great! What are you working on?

**Comment by muhsin-art** [comment]
I put a recyclerview in home page of your application. I will provide some categories to the user that they can filter the  place marks in the map. For example if the user clicks the cinama,   I would like to filter icons in the map and only the cinema marks will be shown. As I see from the application, you didnt filter, you bring front the related icons and make them bigger after found the places. But some queiries returns blue point marker. Is there any way to overwrite it? I have some icons for the some queries. I would like to replace it with the blue point.

**Comment by dvdmrtnz** [comment]
Are you talking about the search results blue icons? Take a look here: https://github.com/organicmaps/organicmaps/blob/master/map/search_mark.cpp

**Comment by muhsin-art** [comment]
How can I add custom points in the map ? I would like the add radar points , what is the best way to do it?

**Comment by biodranik** [comment]
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dspeed_camera

**Comment by muhsin-art** [comment]
I meant I have radar points and I would like to add the points according to user location

**Comment by biodranik** [comment]
Why won't adding radar points directly into osm.org work? It will benefit everyone, including your users.

**Comment by muhsin-art** [comment]
I will provide radar points for subscribed users, which they can choose to
display optionally. These points will be updated annually. The radar points
will be automatically updated from a remote server without affecting any
updates from osm.org. I want to retain full control over adding custom
points independently. Do you know how I can implement this functionality?

Alexander Borsuk ***@***.***>, 19 Eki 2024 Cmt, 18:54
tarihinde şunu yazdı:
