### ISSUE TITLE
Wrong POI info pane height and FAB positions after adding a POI to OSM

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#9544]
Happened after an addition of a POI to OSM.
I'm not sure how to reproduce it reliably.
(Android 10)

|||
|---|---|
|![photo_2024-10-18_21-05-08](https://github.com/user-attachments/assets/7c6b9aab-b362-4759-bbb0-1462ec511ea2)|![photo_2024-10-21_15-50-48](https://github.com/user-attachments/assets/8e078da2-dbbb-46bc-966d-f39e20fbd528)|

Also reported by a user on TG chat https://t.me/organicmaps/46469 (Android 9).

**Comment by pastk** [comment]
Could be related to following recent changes
- https://github.com/organicmaps/organicmaps/pull/9251
- https://github.com/organicmaps/organicmaps/pull/9430

@strekha could you please take a look?

**Comment by strekha** [comment]
It looks like IME inset was applied to the screen, which is strange, because POI editor is a separate Activity.  
Reproduction steps would be helpful, without these, I can only make assumptions about the problem.

**Comment by pastk** [comment]
A different case is reported by a user (https://t.me/organicmaps/46728):
> I am only search for Sabanetica downloading at the sane time the 3 maps for Colombia country

![photo_2024-10-31_14-46-09](https://github.com/user-attachments/assets/fe8fead7-3feb-4ca9-8d86-eed735956d47)

Maybe some prior or current (e.g. downloads in the background) interaction with the downloader is required to reproduce the bug..

**Comment by vng** [comment]
Probably, it will give more info:
Redmii Note 5 - Android 9

![telegram-cloud-photo-size-1-5014976258202775005-y](https://github.com/user-attachments/assets/e0408974-e215-4a23-bb5d-fe534e33a952)

**Comment by Misalf-git** [comment]
Similar to this? ...
https://github.com/user-attachments/assets/1f5fed09-4811-42ec-b053-5b45d85d0e1c

**Comment by pastk** [comment]
> Similar to this? ...

Its different. In your video the toast/snackbar is inited at the high PP height and remains (until disappears) there although PP is collapsed.

**Comment by pastk** [comment]
From another user

> it happens rather randomly. I click the search icon, then type in the street name, (or street name and house number), then click on one of the results in the result list, then it happens. But, not always. It happens only once per every 20 searches. Latest OM Beta on Android 10.

Another user with Android 9 has it reproduced on many, maybe most searches.
