### ISSUE TITLE
Add option to add adresses to OSM

### ISSUE THREAD

**Issue by road-runner-osm** [organicmaps/organicmaps#9557]
I am also opening this as a bug because OM users tend to select random POI categories (for example tourism=apartments) when adding an address and this causes a lot of problems to fix (see also [discussion ](https://community.openstreetmap.org/t/changeset-discussions-just-dont-work/120040)in the forum). Allowing also to add only addressees would solve this problem.

**Comment by pastk** [comment]
And related to #6733
