### ISSUE TITLE
 Add GPS Offset

### ISSUE THREAD

**Issue by maxlinux2000** [organicmaps/organicmaps#9559]
⚠ Have you searched for similar, already existing issues?
yes

It is very likely that during armed conflicts the GPS signal is interfered with by signals that can move our position on the map by 100km.
It would be good to have an offset in the configuration that allows us to fix, for example, our house or a known position and from there, the program calculates the real position based on the interfered data from the GPS satellites.

So the idea is to add a bookmark where we can mark, for example, our house with the exact coordinates.
Then, if we realize that the GPS is marking totally wrong positions, we select our correct position in the bookmarks, and the program calculates the correct offset.

greetings
MaX

**Comment by Danny3** [comment]
Yo mean by pointing on the map or we actually are and then calculate the offset from there?
It makes sense to me, but such a feature to be developed it will need to be tested, and I'm afraid that will be very hard unless someone actually is in a conflict zone.

**Comment by RedAuburn** [comment]
Out of scope IMO. Also, i can't imagine that the GPS offset is fixed, that would be kinda useless.

**Comment by maxlinux2000** [comment]
I'm not really sure how it should work.

But let's say that before the conflict I mark the position of my house in the favorites.

Then the interference starts and it turns out that my GPS position is 100km away in the middle of the sea, even though I'm still in front of my house.

So I think the ideal is to be physically in the conflict zone, or at least in the interference zone.

My idea is that when I realize that the GPS signal is interfered with, I can pass a new offset to the GPS while I'm in front of my house.

In this way, Organic Map should be able to calculate the difference between the current (wrong) position and the position of my house, to obtain an offset of the coordinates.

How to test it? Well, I don't know how GPS radio waves are interfered with. But you could use a wrong bookmark on purpose.

For example, I put a bookmark of the Colosseum in Rome as if it were my house, and when the GPS tells me that I am in front of my (real) house in Germany, I select the Colosseum so that it calculates the offset.

I think it could be simulated like this
regards
MaX

**Comment by maxlinux2000** [comment]
I don't know if it's out of scope, but it would be a huge help in these cases.
Keep in mind that in conflict zones you DON'T drive a car, but GPS and an offline map are very useful tools for radio amateurs.

Regarding the "Fixed Offset", just add a "reset offset" button.

**Comment by Misalf-git** [comment]
FWIW, [GPSTest](https://github.com/barbeau/gpstest) provides something similar to, I assume, measure or workaround GPS inaccuracy.

**Comment by pastk** [comment]
Hm, what makes you think that GNSS spoofers just "add an offset"?

We have plenty of reports of spoofers (and jammers) interference in the russian-speaking TG chat, and I don't remember any reports of a "fixed offset" spoofing. People get their location in the middle of a lake going in large circles at high speed etc, though they actually keep still in their places..
IDK maybe there are some types of spoofers that just add an offset indeed, but anyway it looks like a very niche case and a person apply that "offset fix" should know very well what they're doing...

> FWIW, [GPSTest](https://github.com/barbeau/gpstest) provides something similar to, I assume, measure or workaround GPS inaccuracy.

I just had a look and it allows to measure accuracy only.

What would be really useful for many users is an ability to somehow detect that signals are jammed or interfered with and warn a user accordingly. It might be doable but not easy for sure as there are many different patterns.

**Comment by maxlinux2000** [comment]
What we are not taking into account is that GPS are free and open to use until NATO allows us to use them.
The military cannot know who uses the GPS or set a password, because a GPS satellite is "simply" a clock that sends the time by radio.
A single satellite is useless, but with 3 you can calculate your own position on the map.

But they can change the time of the satellites which causes huge errors in the position on the map.

A "simple" Position OFFSET in OrganicMap can alleviate the problem.

**Comment by RedAuburn** [comment]
> What we are not taking into account is that GPS are free and open to use until NATO allows us to use them.
...
> A "simple" Position OFFSET in OrganicMap can alleviate the problem.

Believe me, i fully agree. Unfortunately GPS jamming isn't fixed by just adding an offset (otherwise it would be easily counter-able and effectively pointless).
 If even militaries are effected by GPS jamming, there's no chance that there's a simple fix as easy as using an offset.

**Comment by muralito** [comment]
The two known methods, jamming (disrupt GPS signals to make them unusable) or spoofing (send fake signals to make the receiver calculate a wrong position).

Nowadays, with several constellations (e.g. GPS, GLONASS, Galileo, and BeiDou) controlled by different countries, if your device can receive simultaneously from several constellations, the spoofing attack is probably not effective, because it needs to fake signals from all of them simultaneously. Less more if you are also using another location provider (e.g. based on wifis network, or cell towers)

And to protect from jamming, your receiver needs to have an array of antennas and do processing to clean the genuine signals from the fake ones. AFAIK none civil receiver has this kind of technology.

**Comment by maxlinux2000** [comment]
To sum up:

1) no civilian receiver can distinguish false signals from true ones.

2) There are thousands and thousands of satellites of different nationalities in Earth orbit and some could transmit at 1.5Ghz.

3) There are an undetermined number of military satellites that we don't know what they can do.

4) We don't really know if an Offset GPS can or cannot fix the problem... there are opinions, but... they are just opinions.

With all this, it seems reasonable to me to add some form of protection to our maps so that they at least have a chance of resisting a large scale GPS jamming, such as an attack between Russia, China, India, Pakistan, Iran, etc against NATO (us).

In addition, Trump has just won the elections which means that Europe is left alone.

In the end, how much code can there be? 100 lines? 200?

Think about it now while there is time, because later it may be too late.

Regards
MaX

**Comment by RedAuburn** [comment]
This is simply not feasible/possible i'm afraid.

**Comment by maxlinux2000** [comment]
please, have a look to this news.

https://www.elmundo.es/internacional/2024/11/09/672f2740fc6c83e3548b457a.html
