### ISSUE TITLE
Web-APK Wish

### ISSUE THREAD

**Issue by Jeffrey2307** [organicmaps/organicmaps#9563]

**Comment by Jean-BaptisteC** [comment]
Web apk is available in [Github releases](https://github.com/organicmaps/organicmaps/releases) and Organic Maps is not published on Izzy Repo

**Comment by Jeffrey2307** [comment]
But why it shows Izzy Repo and installed when I click on my Apps and then on Organic Maps...For example Organic Maps installed from Accrescent: When I click in my Apps in F-Droid it says: recommended - and in my Apps it says Google Play. But with the Web APK it is not like that.

**Comment by Jeffrey2307** [comment]
Thank you for saying that too!

**Comment by Misalf-git** [comment]
IzzyOnDroid does indeed provide the "web" release, but it's not published there by the OM team.
It's your own decision what repos you're using.

Check your F-Droid repository settings. You can change prefered repos globally and/or per app.

**Comment by Jeffrey2307** [comment]
But how is that possible, that other People than Organic Maps publish their App on Izzy Repo then?
