### ISSUE TITLE
Allow setting default mode of transport

### ISSUE THREAD

**Issue by tandy-1000** [organicmaps/organicmaps#9565]
⚠ Have you searched for similar, already existing issues?

Yes, a previously closed issue hinted that the map styles and layers contributes to the default transport mode used.

**Is your feature request related to a problem? Please describe.**

I only use this app for cycling directions, so it's quite frustrating to have to do the extra click everytime I start my route.

**Describe the ideal solution**

It would be ideal if I could set the default mode of transport in the settings, I would set bike as the default.

**Describe alternatives you have considered**
The current alternative is to continue using the app but consistently do the extra click required to switch to cycling directions.

Thank you!

**Comment by map-per** [comment]
On my phone (2024.10.08-5-Google) the last used mode of transport ist used by default.

@tandy-1000 Is the transport overlay activated on your phone? What is your phone defaulting to? What Organic Maps version and operating system do you use?

**Comment by Rob-from-VI** [comment]
This is working for me now on latest release where it defaults to CAR, so OK for now.   I still think it would be nice to have a default in settings.

**Comment by Danny3** [comment]
As someone who doesn't own a car and rarely goes by car, it would be best to have an option to set a default!

**Comment by Misalf-git** [comment]
No problem for me on Android (2024.10.23-2-Web) - _the last used mode of transport ist used by default_.

> What Organic Maps version and operating system do you use?

**Comment by pastk** [comment]
For me it defaults to the last used mode of transport too.
So there is no need for a separate setting.

If it keeps defaulting to something else then its a bug.
Or maybe you have the subway layer enabled - it makes it default to public transport routing.

**Comment by pastk** [comment]
> OK, so for consistency, why is subway treated differently? If I accidentally or purposely have my subway layer turned on, I cannot navigate by bike or by car without bad UX??

The idea is that if someone has enabled the subway layer then its very likely they want to go by subway.

If it was enabled accidentally then its hard not to notice it (but happens sometime anyway)
- https://github.com/organicmaps/organicmaps/issues/6915

> 
> So, I suggest it should be either a setting which always works, or always use last used, which can be changed at will as it is at present, but this should work regardless if Subway layer is on or off.

If following work goes forward then enabling subway won't affect the last used route mode
- https://github.com/organicmaps/organicmaps/pull/8431

**Comment by pastk** [comment]
I've added a comment about stopping defaulting to PT routing: https://github.com/organicmaps/organicmaps/issues/6915#issuecomment-2439570067

Please track it there, closing this issue as duplicate.

**Comment by tandy-1000** [comment]
After disabling the subways layer it stopped, but this is an easy mistake to make, with no indication in the UX that the two settings are related.
I would also have liked to still use the subway layer without this behaviour.
