### ISSUE TITLE
Min and Target SDK

### ISSUE THREAD

**Issue by Jeffrey2307** [organicmaps/organicmaps#9579]
Hey,

i saw that the App has Target SDK on 35 and Minimum SDK on 21 and I wanted to ask if you could make Minimum SDK to 23/24/26/28/29/31? (Higher is always better) I would appreciate that!

A higher Minimum SDK version implies that your app supports fewer Android versions, minimizing compatibility issues. Because higher SDK means also Versions which are supported better. It makes the work easier. because Android 12 (SDK 31) is the last version that receives security patches. Further more, the less minSdk, the more internal compatibility layers, techniques etc. For example, lower SDK versions require v1/v2 signing, have somewhat different optimization levels, etc.

**Comment by Jeffrey2307** [comment]
I wish I could get a real answer, than thumps down...I really don't understand this childish behaviour...

**Comment by Jean-BaptisteC** [comment]
Did you know the real impact to increase minSDK?
Organic Maps can be installed on devices which have ten years old and that's why our community like our app, because we support a lot of devices and with good performance.
Of course, there can be have comptability issues but we prefer to have somes bugs and support a lot of devices.
Did you have check minSDK in other apps ? For example Google Maps, or OSMAnd support Android 5 (minSDK 21) like us.

**Comment by Jeffrey2307** [comment]
I know the impact, but devices that are ten years old should not be used. What is the benefit if they don't get Updates and lack in that? If you would raise the SDK then People must update their Phones, which is the only right way. Because you should go with the Security and not with old Phones, which are not recommended. Supporting is not always better. We should guide them by having standards, that they can change their not good Security Behaviour by using old Phones...Not you Guys should confirm with them, they should confirm with the newest Android Versions, which would also make the work easier for you. In my opinion this makes your work harder for yourself but I know what you trying to say. But I can not understand that 100% if I need to be honest. Yes I have checked and many Open Source Apps have Min SDK on 26-31 and I specifically don't use low target and min SDK Apps. You should not mention or compare Google Maps and others. You should look up to the best one like GrapheneOS and how they did set their standards. Because they are all about Security and Privacy. And bumping the SDK would not send a bad message...It would instead show that you Guys value the latest Android Versions. It would only seen as bad for the ones who have bad Security Habits with using an outdated Phone with no Updates...It would make them aware, that every App is on higher Android Version and they would must change their bad Habits in terms of that. You would not loose good Users, just once, who are not truely following your morals. Because with Privacy, Security comes too. And what benefit would they have, if they have better privacy Apps but bad Security in general? Also Organic Maps is not really the most Privacy respecting App if we need to be honest...Even your Web-APK or F-Droid Version has Google Libraries too and are not fully FOSS...And adding a Build to Accrescent which has Google Location Services is not the most private...And I know that it can be disabled in the Settings but Privacy concious People would stay away from Google (Not private) or F-Droid (Security Issues). And about the Security in the App, I can not say something, but I guess that it should be good then.

**Comment by RedAuburn** [comment]
There is no security risk to having a low minimum SDK level. It simply means that it can run on those SDKs. The SDK is provided by your device's operating system, so if you have a new device the app will be using the latest SDK anyway.

What about the billions of people not in wealthy first world countries, where they can't afford a new device? Should we just abandon them?

**Comment by Jeffrey2307** [comment]
> There is no security risk to having a low minimum SDK level. It simply means that it can run on those SDKs. The SDK is provided by your device's operating system, so if you have a new device the app will be using the latest SDK anyway.

You are just supporting their bad Security Habits with that.

> What about the billions of people not in wealthy first world countries, where they can't afford a new device? Should we just abandon them?

It is not about abondon and that you ask this Question is really ridiculous...You should prioritize Security and if they can't afford newer Phones than this is not your Problem...And let's be real: Even in Bangladesh or like that, they got sometimes the newest Pixel or at least those with Security Updates...I'm not that wealthy too, but there are used Pixels too, for low Money. And they get Security Updates and everything. Even for them their is priority...I feel like for the most People this is just an escaping way...

> the FDroid version doesn't include Google libraries.

But why then did the User in a few Issues before did say that he compared both and that both have those libraries?

**Comment by Jeffrey2307** [comment]
@Jean-BaptisteC No I don't prefer or want these, I prefer a World without Phones, but thank you for claiming something which is not true! You should never accuse someone you don't know. I only said that latest Phones are better in terms of Security. And People could also buy used Phones too by the way...And I know that for sure what you mentioned about flagship Phones. Another Accusation here.
No Problem, me too. I never said that you should and most Foss Apps should not be the standard but never mind. No Problem, I only shared my view.
