### ISSUE TITLE
Hide "Wayside Cross" from the "Sights" section

### ISSUE THREAD

**Issue by kuba-orlik** [organicmaps/organicmaps#9613]
**Is your feature request related to a problem? Please describe.**

When planing a route in Poland, I used the "Sights" category in search view a few times. It was very hard to pick up interesting points, because the view is filled with Wayside Cross points. 

At least in Poland, Wayside Crosses are EVERYWHERE and not a sight to behold. It may hold some religious significance to some, but otherwise they are common and insignificant as road signs.

**Describe the ideal solution**

Don't include Wayside Cross points in Sights search, at least in Poland, or give an option to hide those points from the map.

**Describe alternatives you have considered**

* Going through points one by one (sometimes 40 of those) and finding by hand something that is actually interesting 

**Additional context**
![Screenshot_20241106-081751_Organic Maps png 600](https://github.com/user-attachments/assets/f02bf12e-7816-4984-bdb0-474f85bf2aee) ![Screenshot_20241106-081748_Organic Maps png 600](https://github.com/user-attachments/assets/19e98db7-a789-4a97-9b8e-418dd3275d37) ![Screenshot_20241106-081739_Organic Maps png 600](https://github.com/user-attachments/assets/690818ba-0193-46e1-ab6e-9c2f8cf0dff9) ![Screenshot_20241106-081734_Organic Maps png 600](https://github.com/user-attachments/assets/1100ffdb-83dd-479b-809d-45beed1e155f) ![Screenshot_20241106-081731_Organic Maps png 600](https://github.com/user-attachments/assets/7bdc9e42-7137-48f3-9152-b2a95c84a3d5) ![Screenshot_20241106-081729_Organic Maps png 600](https://github.com/user-attachments/assets/722804ac-66e5-4e49-9400-f264c8a08587)  ![Screenshot_20241106-081725_Organic Maps png 600](https://github.com/user-attachments/assets/20692849-3726-461c-8fd7-434e2294b1a0) ![Screenshot_20241106-082052_Organic Maps png 600](https://github.com/user-attachments/assets/a8a73de8-bd1d-46cb-ac82-55a0de6f1ca7)

**Comment by biodranik** [comment]
@vng is it feasible to search for category synonyms only for some languages? Otherwise, it's better to remove it from sights.

**Comment by matkoniecz** [comment]
> only for some languages

English tourist in Poland would be also affected by this.
