### ISSUE TITLE
[iOS] Map language is wrong

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#9630]
Map labels are showing in English, even though the app is set to Spanish.

Organic Maps version ⁦2024.11.10-1⁩

iOS 18.1

https://www.openstreetmap.org/way/51754330#map=19/42.818529/-1.644437

<img src="https://github.com/user-attachments/assets/467a1f5f-9cd6-417c-a934-9482e7d5ced3" width="320"/>

**Comment by dvdmrtnz** [comment]
* Could be related to https://github.com/organicmaps/organicmaps/pull/8237

**Comment by vng** [comment]
BTW, should we add "Use system setting" option to the in-app language settings?

**Comment by matheusgomesms** [comment]
I still would also love to see OM respecting users preference languages, as set in OS preferences. Would solve  #5817
