### ISSUE TITLE
Allow the user to return to search results after editing or adding a place

### ISSUE THREAD

**Issue by Korb** [organicmaps/organicmaps#9657]
**Is your feature request related to a problem? Please describe.**
I am ready to participate in updating OSM, but using Organic Maps makes it very unpleasant. In particular, because the user cannot work with the search query, combining it with editing the found places or adding new ones. As soon as you submit a request for updating OSM, the previous search result is reset, and you will have to search again.

**Describe the ideal solution**
After editing or adding a place on the map, you can use the Back gesture to return to the search results.

**Comment by map-per** [comment]
I'm curious what your use case is? What OpenStreetMap data do you update / add?

**Comment by Korb** [comment]
@map-per — names of organizations, addresses, working hours, menu, phones, Wi-Fi. Only what Organic Maps allows you to edit. I like to improve and do better what I use myself.

**Comment by map-per** [comment]
And what data source are you using? Usually people only edit places they have recently been to, because external data sources are usually copy right protected.

**Comment by Korb** [comment]
> And what data source are you using? Usually people only edit places they have recently been to, because external data sources are usually copy right protected.

@map-per, I see a sign with the name of the cafe. I see a door with the opening hours and phone number. I see the organization's menu with the company's website and messengers. I don't understand what copyrights are you worried about? Is it illegal in your country to add barriers, information stands, public organizations, drinking fountains, and gazebos to the map? If this is the case, please accept my condolences.

**Comment by map-per** [comment]
Adding data surveyed on site is totally fine in OSM. I'm just wondering why you need / use the search when editing.
