### ISSUE TITLE
Support Low Emission Zones in navigation

### ISSUE THREAD

**Issue by FedericoCeratto** [organicmaps/organicmaps#9666]
Hello and thank you for developing Organic Maps.

Many cities have Low Emission Zones or other forms of congestion management based on conditional access.
Organic Maps should be aware of it and route around blocked-off areas.

Access rules can be complex depending on:
- vehicle emissions
- vehicle type, use, size and weight
- hour of day, day of week, day of month

Organic Maps could either ask if the user can access a LEZ or even ask for vehicle information and attempt to compute access conditions based on current time.

Example: the majority of cars cannot access https://www.openstreetmap.org/relation/2459882 (currently this is making navigation unusable in city center).

Partially related: #5066 #5280

**Comment by map-per** [comment]
Related to #8387

**Comment by FedericoCeratto** [comment]
Oops, sorry for the duplicate! Closing this issue.

**Comment by RedAuburn** [comment]
also https://github.com/organicmaps/organicmaps/issues/8901
