### ISSUE TITLE
Search police stations of a particular type by also using the operator tag

### ISSUE THREAD

**Issue by Aquathing** [organicmaps/organicmaps#9674]
**Is your feature request related to a problem? Please describe.**
Sometimes it may not be possible to find a specific police location because of its mapping.
Italy has different kinds of police operators, to name a few, "Polizia di Stato" and "Carabinieri", the latter has its specific operator tag "Arma dei Carabinieri".

Both are mapped as police, but you won't be able to find "Carabinieri" unless the word is contained in the location name.

**Please note** that in Italy it is common to consider "Carabinieri" and Police separate things, so people do not search for Police when they need "Carabinieri".

**Describe the ideal solution**
Searching for the queried name in the operator= tag.

**Describe alternatives you have considered**
- Fixing every occurrence of this in OpenStreetMaps

**Comment by pastk** [comment]
- related to #9652 

Need to do a research first - what could be values of `operator=` for police in other countries? As we'd want to avoid displaying and searching for unrelated and confusing things.

**Comment by Aquathing** [comment]
Perhaps it would make sense to search for the string in `operator=` (and operator-short) only if the `amenity` is set to "police"?

**Comment by pastk** [comment]
> Perhaps it would make sense to search for the string in `operator=` (and operator-short) only if the `amenity` is set to "police"?

Yes. But what I meant is that in other countries `operator=` for `amenity=police`might contain something we better avoid displaying to users to avoid confusing. See some confusing examples for cafes and petrol stations (whereas in many cases operator is filled with relevant info for these POIs) in the issue I linked to above.

Actually I'm very surprised that Italian mappers decided to put "type of police" into `operator`...

**Comment by Aquathing** [comment]
> Yes. But what I meant is that in other countries operator= for amenity=policemight contain something we better avoid displaying to users to avoid confusing.

Sure, sorry for the misunderstanding.

> Actually I'm very surprised that Italian mappers decided to put "type of police" into operator...
Mapping in OpenStreetMap is new to me, if you have any idea of a place that could be better to put this value I could suggest it to the Italian mappers

**Comment by pastk** [comment]
Actually it seems like its common to use `operator` for specifying police "type", see https://wiki.openstreetmap.org/wiki/Tag:amenity=police

As far as search goes an easy but not ideal fix would be to add "Carabinieri" into search synonyms in `categories.txt` for amenity=police.
At the moment for IT it contains only "Polizia".
After adding "Carabinieri" there any search for "polizia" or "carabinieri" would return all `amenity=police` POIs.

**Comment by Aquathing** [comment]
> As far as search goes an easy but not ideal fix would be to add "Carabinieri" into search synonyms in categories.txt for amenity=police.

If you are going to consider this, please consider adding, all types of "operator" used for police in categories.txt. Otherwise, things such as "Guardia di Finanza" would not be matched.

**Comment by Aquathing** [comment]
If you want, I can open a PR to do this

**Comment by pastk** [comment]
Yes, please!

**Comment by Aquathing** [comment]
May I ask what's the difference between the strings with header `amenity-police|@category_police` and only `@category_police`

**Comment by pastk** [comment]
> May I ask what's the difference between the strings with header `amenity-police|@category_police` and only `@category_police`?

Both of them are used (combined together). A separate `@category_police` exists because its the way to link it to the "Police" category item in the UI.

Better add new synonyms to the `amenity-police|@category_police`.

**Comment by muralito** [comment]
> As far as search goes an easy but not ideal fix would be to add "Carabinieri" into search synonyms in `categories.txt` for amenity=police.

I'm not sure that putting distinct operators as alias is a good idea.
Will that means that searching for "Carabinieri" results lists all amenity=police (all distinct operators) and not only the ones with="Arma dei Carabinieri"? Is that what the users are looking for?

When an italian user, or user in Italy searches for "Carabinieri" it should get only "Carabinieri". But when it searchs for "police" (imagine a english speaking tourist which only speaks english) it should get any police station. The same could apply when searching for distinct security forces in every country.

**Comment by Aquathing** [comment]
Yes, you are right. 
I consider this to be a temporary fix (I also explained the drawbacks in the PR), just to make sure it is easy to find such locations until searching by operator tag is done.

**Comment by Aquathing** [comment]
The ideal fix here would be to search for the operator tag, and a nice-to-have thing would be for Mappers to specify the kind of service in the feature name.

But until that is done, this works good enough, because IMHO in this case it is better to have more results than less.

**Comment by pastk** [comment]
Ideally we would have distinct POI types for polizia, carabinieri, etc. Because even search using the operator key won't be ideal (a search for "polizia" would return all police stations incl. carabinieri and other divisions). 

But it seems much better to return all police stations when asked for "carabinieri", rather that return nothing. So yeap, its not ideal, but an improvement for sure.

**Comment by pastk** [comment]
FYI @vng

**Comment by muralito** [comment]
Maybe some kind of interface that offers automatically the filters that could be usefult to each POI could help. I was thinking in Amazon or other online stores, when you search in the textbox for "notebook" you get some results in a list, but then the app also offers some filters you can apply (the right pane) like brand, type of cpu, etc to narrow the search (thinking not in the specific GUI but in the use case of a search). This can improve searches for a lot of POI types.
