### ISSUE TITLE
Color of yellow road shields in dark mode

### ISSUE THREAD

**Issue by sostock** [organicmaps/organicmaps#9676]
In dark mode, yellow road shields become green. I think the color of the road shields in the app should be the same as the color of the actual shields, i.e., yellow shields should stay yellow. The green color might lead to confusion since there are shields that are actually green.

See below: `B 3` and `B 33` change color.

|Light|Dark|
|-|-|
|![Screenshot in light mode](https://github.com/user-attachments/assets/21e3813a-5db6-4acc-9d50-f0dbd8d76a8e)|![Screenshot in dark mode](https://github.com/user-attachments/assets/1ad0c67b-8924-4a79-bcec-a8118c0c3e96)|

If the current behavior is intentional (because yellow shields might be too bright for dark mode), the shields could maybe become yellow text on black background, so that the yellow color is still present? It would be like the black-on-white shields, which become white-on-black (`L 91`, `L 98`, `L 99` in the screenshots).

Also, the black text on green background is hard to read, which makes me think that this is a mistake instead of intentional behavior.

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2024.11.12-7-Google

**Comment by pastk** [comment]
Fix the `RoadShieldOrangeBackground-color: #136C30;` color in `data/styles/default/dark/style.mapcss` and run the `generate_drules.sh` script, see details in `docs/STYLES.md`.

**Comment by LoicHernaut** [comment]
Hello I will try to do that for a first issue

**Comment by pastk** [comment]
Fixed in https://github.com/organicmaps/organicmaps/pull/9804
