### ISSUE TITLE
A POI is visible twice and changes don't go to OSM

### ISSUE THREAD

**Issue by DerKarlos** [organicmaps/organicmaps#9681]
**Describe the issue**
The Café Julie https://www.openstreetmap.org/node/10643049352
is marked twice in OM. Only one of them is in the OSM data base.
OM does not use other data source to get POI's twice, do you?

And changed, I made to this one get not visible in OSM.
(I added the Web-Page)

**Steps to reproduce**
Sorry, no

**Expected behaviour**
Sorry, no

**Screenshots**
![IMG_1040](https://github.com/user-attachments/assets/b5b9ca73-1b34-489b-8339-a621191ebe0f)

**System information:**
 - Operating system and its version: iOS 17.6.1
 - Organic Maps version: 2024.11.12-6
 - Device Model: iPhone SE2

**Additional context**
Reloading the map data did not help
This issue may be related to #8448
I could TestFlight it

**Comment by Vuizur** [comment]
I checked it with the current map data in the newest organic maps and could not reproduce it in Android (there is only one point for me).

**Comment by DerKarlos** [comment]
Could someone test it with iOS please?
@Vuizur, did you see the homepage? It is only at the westwards POI.
Could I have that analyse tool you used? (I would like to have it vor odd routing things to)

I assumed, it was caused by the #8448 issue: In this case, it should be only in the data of my app's instance.
But it is on my iPad **and** my iPhone! So it **must** be caused by the OM data somehow, mustn't it?

Because of the delay from OSM to OM it is hard to test, even with TestFlight. Me, building OM locally and edit the map file would be a way, but a lot of effort.

**Comment by DerKarlos** [comment]
Ha, just now I got new map files and the double is gone!
On my iPad I could even watch it live: when the file was downloaded and refreshed the screen.
I am not sure if this is #8448. My change went into the OM data base but not in the OSM data.
But for now, it solved.
