### ISSUE TITLE
Possible name issue: OMaps mobile app exists

### ISSUE THREAD

**Issue by richlv** [organicmaps/organicmaps#97]
This might be a known issue, but there's an existing orienteering app for Lithuania, called "OMaps".

https://play.google.com/store/apps/details?id=com.devhouse.omaps&hl=en_US&gl=US
https://apps.apple.com/us/app/omaps/id1459023660

**Comment by rtsisyk** [comment]
Yes, I see. AppStore in 2021 is like .com. We need to think it over again.

**Comment by FinixFighter** [comment]
What did the "O" of OMaps stand for? If it is for "open" then what about "Open Maps"? (or OpenMaps). The code is open source, app uses OpenStreetMap, so Open Maps comes naturally XD

**Comment by KAMiKAZOW** [comment]
Just make the name "omaps.app" (incl. the .app). The .app and the different capitalization (not OMaps) should be distinct enough.

**Comment by rtsisyk** [comment]
>Just make the name "omaps.app" (incl. the .app). The .app and the different capitalization (not OMaps) should be distinct enough.

Yes, this is a possible option.

**Comment by bryceco** [comment]
On iOS it looks like "OMap" is available. 

There's a downside to having a name similar to an unrelated app: you'll get negative reviews from people expecting one thing and getting another. "Maps.OSM" would be similar to people migrating from maps.me and different from anything else.

**Comment by rtsisyk** [comment]
The name is Organic Maps.
