### ISSUE TITLE
Opening hours are not accurately displayed when location is not continuously open

### ISSUE THREAD

**Issue by guushoekman** [organicmaps/organicmaps#970]
The opening hours in Organic Maps are not displayed correctly in certain cases.

In some countries it's common for shops to be closed for a few hours in the afternoon. They'll be open in the morning, closed when it's very hot, and open up again in the late afternoon.

Organic Maps only shows the first opening time and the last closing time, making it seem like it is open throughout the day.

Here are the opening hours for a shop in Valencia, Spain ([node on OSM](https://www.openstreetmap.org/node/6960375095)):

![Screenshot_2021-07-31_19-29-43](https://user-images.githubusercontent.com/4881667/127749503-3befeeed-4f1b-436b-8b43-8fa29449880c.png)

As you can see it is closed between 14:00 and 16:30. However, this isn't shown on Organic Maps:

![photo_2021-07-31_19-55-46](https://user-images.githubusercontent.com/4881667/127749515-1e68e215-4a04-4f68-8e29-3a64c3f5dcf6.jpg)

**Comment by biodranik** [comment]
Reproduces only on Android.

**Comment by biodranik** [comment]
Please check if other issues referenced here are also fixed by @strump, and let's close them if so.

**Comment by Kazing** [comment]
Closing this issue, non-business time are now correctly displayed.
Checked with this POI: https://www.openstreetmap.org/node/6960375095
