### ISSUE TITLE
Display water safety for drinking for taps and wells

### ISSUE THREAD

**Issue by ftrebien** [organicmaps/organicmaps#9700]
⚠ Have you searched for similar, already existing issues?
Yes. I found two related issues about OSM's `drinking_water:refill=yes`, which indicates whether a source allows bottle refills. While this tag implies drinkability, it does not specify the drinking safety of sources in general, particularly in remote areas.

**Is your feature request related to a problem? Please describe.**
When searching for water sources in Organic Maps, I can find water taps and wells, but there’s no way to determine if they provide safe drinking water. The OpenStreetMap [drinking_water tag](https://wiki.openstreetmap.org/wiki/Key:drinking_water) contains this information: values `yes` and `treated`; values `conditional` and `boil` are drinkable in certain circumstances but need a warning.

**Describe the ideal solution**
Organic Maps could display whether a water source (tap or well) is safe for drinking. This should be visible when clicking on a water source. The drinkable sources could be marked with a unique icon, such as a cup with a check mark on a green background, or maybe the sources unsuitable for drinking could be displayed in gray. Intermediary values like `conditional` and `boil` could be displayed like unsafe sources or with a distinct colour.

I would also be nice to filter the water sources by this property.

**Describe alternatives you have considered**
Currently, I can only manually check OSM data through Overpass Turbo queries to filter by the `drinking_water` tag, which is impractical.

**Additional context**
This feature would be beneficial for people engaging in outdoor activities, such as hiking or biking, as well as for people facing emergencies affecting water supply.

**Comment by RedAuburn** [comment]
Additionally, searching for "drinking water" will only show drinkable water 👍️

**Comment by ftrebien** [comment]
Thank you, @map-per and @RedAuburn. I didn’t come across #9446 when I searched earlier, but I now see that the feature I requested is already implemented. I appreciate the clarification. Please disregard this request. The icon is a bit small on my mobile screen, which is why I didn’t fully understand it.
