### ISSUE TITLE
Strange display of the bottom panel

### ISSUE THREAD

**Issue by neonxp** [organicmaps/organicmaps#972]
![IMG_8381](https://user-images.githubusercontent.com/190940/127753827-80dde946-9d0c-454b-ae9b-11242b3f8ca4.jpg)

Device: Farcar s400
OS: Android 10
Display: 1024x768

**Comment by biodranik** [comment]
Thanks! Looks like some layout issue. We can try to reproduce it in the Emulator with the same OS and resolution.

**Comment by Endem10n** [comment]
@biodranik we already fixed this bug in https://github.com/organicmaps/organicmaps/pull/828/commits/c477c0b80d8ab18bbdd4655417c02f390da88345
This fix will be delivered to users with next app update.

**Comment by biodranik** [comment]
Awesome! @neonxp please let us know if the bug was fixed in the upcoming update.

**Comment by neonxp** [comment]
Just updated from play store. Bug is gone 👍

**Comment by biodranik** [comment]
Great, thanks!
