### ISSUE TITLE
[android] Button titles don't fit in the Track saving dialog

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#9727]
It works for English, but not for some other languages with longer words.

E.g. following is in Russian and the second option should be "Остановить без сохранения" (Stop without saving) but the last word is omitted hence it becomes a confusing "Stop without".

![image](https://github.com/user-attachments/assets/009b936c-8635-4900-99bc-3a0eee689f3c)

**Comment by Vadim-pmm** [comment]
May I ask You to replace  "Остановить без сохранения" with more straightforward "Удалить" ?
I don't think user pays close attention to the headline "Сохранить в метки и треки". He just wants to "Stop Recording" and decide what to do next it that context.
1. Continue recording
2. Delete recording
3. Cancel
