### ISSUE TITLE
The Version in Accrescent

### ISSUE THREAD

**Issue by PrivacyAndSecurity** [organicmaps/organicmaps#9740]
Hey,

i use Organic Maps from Accrescent but I'm not 100% happy, if I need to be honest and I wanted to share my thoughts about that. I love that Organic Maps is on Accrescent but I wish that the Web Build APK was published in Accrescent, instead of the Build which is there at the moment. I can understand that it was made compatible with Android Auto and Google Location Services but as a Person who don't like Google Libraries or Services, I feel not 100% comfortable. I know that I can turn Google Location Services in the Settings too and I did that. But I just wish that the Web APK Build was published instead of the Google Play compatible Version. Because in my Opinion the Web APK does more fit in the degoogle and Security/Privacy Section. And my Problem is this now: I would like to use the Web APK but the Accrescent Organic Maps enjoys the Security and Privcy Benefits of Accrescent. So if I would choose the Web APK the App get's checked by IzzyOnDroid Repo which is good, but I could not benefit from the Security and Privacy Features of Accrescent. And if I use the Accrescent Organic Maps, then I benefit from the Security and Privacy Features of Accrescent but would have Google Stuff in the Build...The best solution for me and generally that Security and Privacy Section/Community has the most benefit, would be to publish the Web-APK of Organic Maps to Accrescent, instead of the Google Play compatible made Version...I hope that you can switch it, because that would be the only ideal solution. And the Google Play compatible made Version could be instead published in Github, because that would make more sense too, since it has less Security/Privacy Benefit in Github. And Google Stuff makes more sense in Github, then in Accrescent in my opinion. I hope that my wish can be implemented, because I want to be 100% happy, with what I use.

**Comment by biodranik** [comment]
There is no difference between the web and Accrescent versions except one: The Accresscent version has an embedded world map, while the web version downloads it. Everything else is exactly the same.

Web version can be installed and updated using https://github.com/organicmaps/organicmaps/wiki/Installing-Organic-Maps-from-GitHub-using-Obtainium

**Comment by biodranik** [comment]
Web apk also contains the code from Google Location Services, in the same way as Accrescent build. You can completely disable it in Organic Maps settings if you don't need faster location detection from Google based on wifi/cellular networks.

By the way, did you test that Accrescent build works with Android Auto?
