### ISSUE TITLE
Does not allow x.com links

### ISSUE THREAD

**Issue by VoxelPrismatic** [organicmaps/organicmaps#9788]
⚠ Have you searched for similar, already existing issues?

**Describe the issue**
Please write a clear and concise description of the issue here.

When adding a business, the X social link does not accept x.com links, only the legacy twitter.com 

**Steps to reproduce**
1. Go to the 'Add a business' page
2. Paste a link to x.com

**Expected behaviour**
Would allow x.com links

**Screenshots**
![ResizedImage_2024-11-30_08-53-56_8641.png](https://github.com/user-attachments/assets/d83486f6-cf54-419b-a094-afad45554297)

**System information:**
 - Android 14
 - Organic Maps 2024.11.27-12-Web
 - Sony Xperia 1 V.

**Comment by map-per** [comment]
Thanks, I opened #9789 to fix this
