### ISSUE TITLE
"Sights" precise address should be added

### ISSUE THREAD

**Issue by sanika-jadhav** [organicmaps/organicmaps#9806]
1. ⚠When someone searches for sights to visit it only shows the name of the city and state, the address can be written precisely, like the exact address of that sight will help user 

2. Also the name can be change, like we can show this as "Sights to visit" or "Tourist places" this will be more familiar according to users PoV

**Comment by pastk** [comment]
1. If the sight had an address mapped in OSM then it should be displayed.

Could you please add specific examples when this is not the case?

![image](https://github.com/user-attachments/assets/afeb5562-30f2-4922-8dee-479dd7775d63)

**Comment by sanika-jadhav** [comment]
In my case, in India specifically, it's not showing the address for the sights.
Maybe it is only available for specific continents or specific countries.

**Comment by pastk** [comment]
There is no address data on OpenStreetMap, e.g. Shaniwar Wada https://www.openstreetmap.org/relation/2861672

So its an OSM data issue, not OSM issue.

You can go to OSM.org yourself and add missing addresses, then they would appear in OM as well (after next app/map update).

**Comment by sanika-jadhav** [comment]
Where can I find this file (OSM.org), I can't find this in the current repo of organic maps.

Can you please describe exact location of the file.

**Comment by pastk** [comment]
Its a web-site of a big OpenStreetMap project from where Organic Maps (and many other apps and sites) take map data.

openstreetmap.org

You'll need to register there in order to edit the map. Its recommended to go through https://wiki.openstreetmap.org/wiki/Beginners%27_guide first.
