### ISSUE TITLE
Garbage instead of accents in Spanish string

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#9812]
Spanish translation is showing garbage instead of accents in this string:

<img src="https://github.com/user-attachments/assets/fef4cf56-f3e3-41ab-94dd-40f45ecb23b4" width="320"/>

* Related to https://github.com/organicmaps/organicmaps/pull/9805

**Comment by map-per** [comment]
@kirylkaveryn Is it better to remove the html style links and use %@ encoding instead?
