### ISSUE TITLE
Incorrect 3D Building Rendering - OM or OSM Issue?

### ISSUE THREAD

**Issue by hujan86** [organicmaps/organicmaps#9833]
The lower part of this building (3 levels)  did not render in OM, causing it to go missing/invisible in 3D view. For whatever reason, only the building parts [building:part=yes] (4, 5, 6 levels respectively) are rendered in 3D view.
  
![Screenshot_20241206-124031](https://github.com/user-attachments/assets/62040623-b060-4714-a7b7-639a3fdda467)
![Screenshot_20241206-125211](https://github.com/user-attachments/assets/c4506d33-2368-4d4d-ae0b-02dc2164cfeb)
![petronasofficebuilding](https://github.com/user-attachments/assets/f51ff0d7-5154-41f4-9cd4-19afb75fdd70)

OM Version: 2024:11.27-12-FDroid

**Comment by map-per** [comment]
That's an issue in the OSM data. The `building=*` outline should be and is ignored for 3D rendering when the building contains `building:parts`. So the missing `building:part` area should be added to OSM.

**Comment by pastk** [comment]
Closing as not an OM issue.
