### ISSUE TITLE
Map fling gesture not working on Samsung S21 Ultra

### ISSUE THREAD

**Issue by jfitie** [organicmaps/organicmaps#987]
No inertia, scroll stops immediately after lifting finger. Works just fine on other devices I tested (Samsung A12, S9+, S8). Latest version from Google Play Store.

**Comment by biodranik** [comment]
Are there any specific settings for this device that may control the inertia? Like a battery-saving mode that disables animations, or some specific development settings?

**Comment by jfitie** [comment]
@biodranik No, and it works fine in other apps like Google Maps. Had the same issue in Maps.me.

**Comment by biodranik** [comment]
Interesting. Can you please enable logs in settings and share them with us either here or at bugs@organicmaps.app?

**Comment by robsmith11** [comment]
I have the same issue on my Samsung Fold 3.  I've sent the logs to the email address provided.

**Comment by biodranik** [comment]
Are there any swing/fling options/gesture sensitivity in device's settings -> display -> navigation bar -> more options? Did you try to change them?

**Comment by robsmith11** [comment]
No,  I don't see anything like that.  The closest setting is that I have animations turned off.   I turned animations back on, but it made no difference.

**Comment by biodranik** [comment]
Interesting, that only some newest Samsung devices have this issue. Looks like Samsung has changed something, or added some specific settings. And it's hard to debug without such a device in our hands.

Can you please try to install this debug version (it will be a separate application), enable logs, restart the app, reproduce the issue several times, and then send us logs back?
https://cdn.organicmaps.app/apk/OrganicMaps-22022702-google-debug.apk

**Comment by robsmith11** [comment]
Hmm.. I get an error trying to install it "There was a problem parsing the package".

I've been putting off upgrading to Android 12.  Maybe I should wait until i do that to debug more.

**Comment by biodranik** [comment]
@robsmith11 please try again the apk from the above link, I've updated it with all ABI architectures. Maybe it was the issue.

**Comment by endim8** [comment]
same as https://github.com/organicmaps/organicmaps/issues/2652

**Comment by RedAuburn** [comment]
Fixed by https://github.com/organicmaps/organicmaps/pull/6237
