### ISSUE TITLE
Rename villages without logging into the OSM account

### ISSUE THREAD

**Issue by Davidstutorialmap** [organicmaps/organicmaps#9881]
“Please add the option to rename villages without logging into the OSM account in the settings! So that everyone can adjust the names of villages and settlements themselves. Alternatively, multiple alternative names could be implemented as an option—please consider this?”

**Comment by RedAuburn** [comment]
It's already possible to leave a note without an account (in the edit option).
 Actually editing without an account is up to OpenStreetMap, not OM, and not likely to be changed due to being a key way of preventing vandalism & spam

**Comment by map-per** [comment]
> It's already possible to leave a note without an account (in the edit option).

No, Organic Maps doesn't support anonymous notes. Notes are only uploaded once the user logged in.

@Davidstutorialmap: If you want to create anonymous notes you can do that on https://www.openstreetmap.org. ([Wiki guide](https://wiki.openstreetmap.org/wiki/Notes))

**Comment by pastk** [comment]
> adjust the names of villages and settlements themselves

If its meant to be for personal use only then alternative names should go into bookmarks.
An option to display bookmarks labels on the map directly will help with visualizing:
- https://github.com/organicmaps/organicmaps/issues/3164
