### ISSUE TITLE
Open Apple Maps links on Android

### ISSUE THREAD

**Issue by ccptr** [organicmaps/organicmaps#989]
When clicking on an Apple Maps link, it'd be nice if it could be opened directly in Organic Maps.

Example link: https://maps.apple.com/place?address=4706%2050%20Ave,%20St.%20Paul%20AB%20T0A%203A2,%20Canada&ll=53.991561,-111.289525&q=Example%20Link&_ext=AbYpUFxEu1v+AbAxxqyaswXTW8A5zjFqF4L/AbBBWpCqWgvSW8BQBA%3D%3D&t=m

**Comment by biodranik** [comment]
Why do you think it's feasible? Are there other apps which open Apple Maps links?

**Comment by ccptr** [comment]
OsmAnd does. The links seem to contain both the address and coordinates.

**Comment by biodranik** [comment]
True, I was thinking about iOS. Thanks! It's possible.

**Comment by rtsisyk** [comment]
I am merging this issue into #475. Please subscribe for #475.
